UPDATE `Recipe` SET RecipeName='Another Sweet Potato Casserole', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='2606.jpg' WHERE ID=2606;
UPDATE `Recipe` SET RecipeName='Another Veggie Quesadilla', CookTime='10', DietType='TBD', IngredientCount='9', ImgURL='2607.jpg' WHERE ID=2607;
UPDATE `Recipe` SET RecipeName='Apple Rings', CookTime='15', DietType='TBD', IngredientCount='3', ImgURL='2608.jpg' WHERE ID=2608;
UPDATE `Recipe` SET RecipeName='Apple Salad', CookTime='5', DietType='TBD', IngredientCount='7', ImgURL='2609.jpg' WHERE ID=2609;
UPDATE `Recipe` SET RecipeName='Asian Spag Salad', CookTime='80', DietType='TBD', IngredientCount='12', ImgURL='' WHERE ID=2610;
UPDATE `Recipe` SET RecipeName='Autumn Chopped Salads', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='2611.jpg' WHERE ID=2611;
UPDATE `Recipe` SET RecipeName='Avocado and Spinach Salad', CookTime='5', DietType='TBD', IngredientCount='7', ImgURL='2612.jpg' WHERE ID=2612;
UPDATE `Recipe` SET RecipeName='Avocado and Tomato Salad', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='2613.jpg' WHERE ID=2613;
UPDATE `Recipe` SET RecipeName='Avocado Banana Salad', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='2614.jpg' WHERE ID=2614;
UPDATE `Recipe` SET RecipeName='Avocado Spinach Salad', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='2615.jpg' WHERE ID=2615;
UPDATE `Recipe` SET RecipeName='Awesome Beans', CookTime='60', DietType='TBD', IngredientCount='13', ImgURL='2616.jpg' WHERE ID=2616;
UPDATE `Recipe` SET RecipeName='Awesome Brussels Sprouts', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='2617.jpg' WHERE ID=2617;
UPDATE `Recipe` SET RecipeName='Awesome Cauliflower Casserole', CookTime='30', DietType='TBD', IngredientCount='10', ImgURL='2618.jpg' WHERE ID=2618;
UPDATE `Recipe` SET RecipeName='Awesome Cheesy Potatoes', CookTime='240', DietType='TBD', IngredientCount='10', ImgURL='2619.jpg' WHERE ID=2619;
UPDATE `Recipe` SET RecipeName='Awesome Rolls', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='2620.jpg' WHERE ID=2620;
UPDATE `Recipe` SET RecipeName='Awesome Scalloped Potatoes', CookTime='35', DietType='TBD', IngredientCount='11', ImgURL='2621.jpg' WHERE ID=2621;
UPDATE `Recipe` SET RecipeName='Bacon and Potato Green Beans', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='2622.jpg' WHERE ID=2622;
UPDATE `Recipe` SET RecipeName='Bacon Avocado Fries', CookTime='20', DietType='TBD', IngredientCount='5', ImgURL='2623.jpg' WHERE ID=2623;
UPDATE `Recipe` SET RecipeName='Bacon Baked Beans', CookTime='45', DietType='TBD', IngredientCount='12', ImgURL='2624.jpg' WHERE ID=2624;
UPDATE `Recipe` SET RecipeName='Bacon Biscuits', CookTime='25', DietType='TBD', IngredientCount='7', ImgURL='2625.jpg' WHERE ID=2625;
UPDATE `Recipe` SET RecipeName='Bacon Blue Grilled Onions', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='2626.jpg' WHERE ID=2626;
UPDATE `Recipe` SET RecipeName='Bacon Butter Muffins!', CookTime='10', DietType='TBD', IngredientCount='4', ImgURL='2627.jpg' WHERE ID=2627;
UPDATE `Recipe` SET RecipeName='Bacon Cheddar Bread', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='2628.jpg' WHERE ID=2628;
UPDATE `Recipe` SET RecipeName='Bacon Cheddar Potato Cakes', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='2629.jpg' WHERE ID=2629;
UPDATE `Recipe` SET RecipeName='Bacon Cheddar Scalloped Potatoes', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='2630.jpg' WHERE ID=2630;
UPDATE `Recipe` SET RecipeName='Bacon Cheddar Tots', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='2631.jpg' WHERE ID=2631;
UPDATE `Recipe` SET RecipeName='Bacon Fried Cabbage', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='2632.jpg' WHERE ID=2632;
UPDATE `Recipe` SET RecipeName='Bacon-Jalapeno Cheese Ball', CookTime='65', DietType='TBD', IngredientCount='12', ImgURL='2633.jpg' WHERE ID=2633;
UPDATE `Recipe` SET RecipeName='Bacon Jalapeno Pull Apart Bread', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='2634.jpg' WHERE ID=2634;
UPDATE `Recipe` SET RecipeName='Bacon Parmesan Potatoes', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='2635.jpg' WHERE ID=2635;
UPDATE `Recipe` SET RecipeName='Bacon Potato', CookTime='45', DietType='TBD', IngredientCount='3', ImgURL='2636.jpg' WHERE ID=2636;
UPDATE `Recipe` SET RecipeName='Bacon Ranch Potatoes', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='2637.jpg' WHERE ID=2637;
UPDATE `Recipe` SET RecipeName='Bacon Roasted Cauliflower', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='2638.jpg' WHERE ID=2638;
UPDATE `Recipe` SET RecipeName='Bacon Sheet', CookTime='10', DietType='TBD', IngredientCount='1', ImgURL='2639.jpg' WHERE ID=2639;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Cabbage', CookTime='40', DietType='TBD', IngredientCount='8', ImgURL='2640.jpg' WHERE ID=2640;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Green Beans', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='2641.jpg' WHERE ID=2641;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Potato Balls', CookTime='15', DietType='TBD', IngredientCount='12', ImgURL='2642.jpg' WHERE ID=2642;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Stuffing', CookTime='20', DietType='TBD', IngredientCount='1', ImgURL='2643.jpg' WHERE ID=2643;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Sweet Beans', CookTime='50', DietType='TBD', IngredientCount='9', ImgURL='2644.jpg' WHERE ID=2644;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Taters', CookTime='90', DietType='TBD', IngredientCount='2', ImgURL='' WHERE ID=2645;
UPDATE `Recipe` SET RecipeName='Baked Avocado Fries', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='2646.jpg' WHERE ID=2646;
UPDATE `Recipe` SET RecipeName='Baked Cabbage with Bacon', CookTime='60', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=2647;
UPDATE `Recipe` SET RecipeName='Baked Cauliflower and Potatoes', CookTime='140', DietType='TBD', IngredientCount='12', ImgURL='2648.jpg' WHERE ID=2648;
UPDATE `Recipe` SET RecipeName='Baked Cauliflower Tots', CookTime='25', DietType='TBD', IngredientCount='13', ImgURL='2649.jpg' WHERE ID=2649;
UPDATE `Recipe` SET RecipeName='Baked corn pudding', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2650;
UPDATE `Recipe` SET RecipeName='Baked Fast Food Curly Fries', CookTime='30', DietType='TBD', IngredientCount='10', ImgURL='2651.jpg' WHERE ID=2651;
UPDATE `Recipe` SET RecipeName='Baked Garlic Cilantro Fries', CookTime='25', DietType='TBD', IngredientCount='9', ImgURL='2652.jpg' WHERE ID=2652;
UPDATE `Recipe` SET RecipeName='Baked Onion Rings', CookTime='15', DietType='TBD', IngredientCount='11', ImgURL='2653.jpg' WHERE ID=2653;
UPDATE `Recipe` SET RecipeName='Baked Parmesan Tomatoes', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='2654.jpg' WHERE ID=2654;
UPDATE `Recipe` SET RecipeName='Baked Potato salad', CookTime='45', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=2655;
UPDATE `Recipe` SET RecipeName='Baked Stuffed Potatoes', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2656;
UPDATE `Recipe` SET RecipeName='Baked Sweet Potato Cakes', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='2657.jpg' WHERE ID=2657;
UPDATE `Recipe` SET RecipeName='Baked Tomatoes with Cheese', CookTime='10', DietType='TBD', IngredientCount='8', ImgURL='2658.jpg' WHERE ID=2658;
UPDATE `Recipe` SET RecipeName='Balsamic Green Beans', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='2659.jpg' WHERE ID=2659;
UPDATE `Recipe` SET RecipeName='Balsamic Roasted Carrots', CookTime='25', DietType='TBD', IngredientCount='8', ImgURL='2660.jpg' WHERE ID=2660;
UPDATE `Recipe` SET RecipeName='Balsamic Roasted Mushrooms', CookTime='10', DietType='TBD', IngredientCount='11', ImgURL='2661.jpg' WHERE ID=2661;
UPDATE `Recipe` SET RecipeName='Balsamic Sweet Potatoes', CookTime='50', DietType='TBD', IngredientCount='6', ImgURL='2662.jpg' WHERE ID=2662;
UPDATE `Recipe` SET RecipeName='Barbecue Green Beans', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='2663.jpg' WHERE ID=2663;
UPDATE `Recipe` SET RecipeName='Basic Bakers', CookTime='10', DietType='TBD', IngredientCount='1', ImgURL='' WHERE ID=2664;
UPDATE `Recipe` SET RecipeName='Basic Cabbage', CookTime='30', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=2665;
UPDATE `Recipe` SET RecipeName='Basic Waldorf Salad', CookTime='15', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=2666;
UPDATE `Recipe` SET RecipeName='Basil and Tomato Salad', CookTime='5', DietType='TBD', IngredientCount='8', ImgURL='2667.jpg' WHERE ID=2667;
UPDATE `Recipe` SET RecipeName='BBQ Chicken Salad', CookTime='25', DietType='TBD', IngredientCount='19', ImgURL='2668.jpg' WHERE ID=2668;
UPDATE `Recipe` SET RecipeName='BBQ Tomatoes', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='2669.jpg' WHERE ID=2669;
UPDATE `Recipe` SET RecipeName='Bean Salad', CookTime='10', DietType='TBD', IngredientCount='12', ImgURL='' WHERE ID=2670;
UPDATE `Recipe` SET RecipeName='Beautiful Mac and Cheese', CookTime='50', DietType='TBD', IngredientCount='9', ImgURL='2671.jpg' WHERE ID=2671;
UPDATE `Recipe` SET RecipeName='Beer Bread', CookTime='45', DietType='TBD', IngredientCount='4', ImgURL='2672.jpg' WHERE ID=2672;
UPDATE `Recipe` SET RecipeName='Beer Corn', CookTime='300', DietType='TBD', IngredientCount='2', ImgURL='2673.jpg' WHERE ID=2673;
UPDATE `Recipe` SET RecipeName='Berry Good Fruit Salad', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='2674.jpg' WHERE ID=2674;
UPDATE `Recipe` SET RecipeName='Best Bacon', CookTime='1', DietType='TBD', IngredientCount='2', ImgURL='2675.jpg' WHERE ID=2675;
UPDATE `Recipe` SET RecipeName='Best Balsamic Mushrooms', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='2676.jpg' WHERE ID=2676;
UPDATE `Recipe` SET RecipeName='Best Cole Slaw', CookTime='30', DietType='TBD', IngredientCount='13', ImgURL='2677.jpg' WHERE ID=2677;
UPDATE `Recipe` SET RecipeName='Best Corn Bread', CookTime='40', DietType='TBD', IngredientCount='10', ImgURL='2678.jpg' WHERE ID=2678;
UPDATE `Recipe` SET RecipeName='BEST Corn Casserole', CookTime='50', DietType='TBD', IngredientCount='10', ImgURL='2679.jpg' WHERE ID=2679;
UPDATE `Recipe` SET RecipeName='Best Corn on the Cob', CookTime='15', DietType='TBD', IngredientCount='4', ImgURL='2680.jpg' WHERE ID=2680;
UPDATE `Recipe` SET RecipeName='Best Creamed Corn', CookTime='240', DietType='TBD', IngredientCount='7', ImgURL='2681.jpg' WHERE ID=2681;
UPDATE `Recipe` SET RecipeName='Best Fries - Seriously', CookTime='40', DietType='TBD', IngredientCount='12', ImgURL='2682.jpg' WHERE ID=2682;
UPDATE `Recipe` SET RecipeName='Best Garlic Bread!', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='2683.jpg' WHERE ID=2683;
UPDATE `Recipe` SET RecipeName='Best Garlic Mushrooms', CookTime='35', DietType='TBD', IngredientCount='14', ImgURL='2684.jpg' WHERE ID=2684;
UPDATE `Recipe` SET RecipeName='Best Homemade Tortillas', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='2685.jpg' WHERE ID=2685;
UPDATE `Recipe` SET RecipeName='Best Twice Bakers', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='2686.jpg' WHERE ID=2686;
UPDATE `Recipe` SET RecipeName='Better Cheesy Biscuits', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='2687.jpg' WHERE ID=2687;
UPDATE `Recipe` SET RecipeName='Better Cinnamon Toast', CookTime='10', DietType='TBD', IngredientCount='8', ImgURL='2688.jpg' WHERE ID=2688;
UPDATE `Recipe` SET RecipeName='Black Beans and Onions', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='2689.jpg' WHERE ID=2689;
UPDATE `Recipe` SET RecipeName='Black Rice Pudding', CookTime='90', DietType='TBD', IngredientCount='4', ImgURL='2690.jpg' WHERE ID=2690;
UPDATE `Recipe` SET RecipeName='Blooming Onion Bread', CookTime='20', DietType='TBD', IngredientCount='2', ImgURL='2691.jpg' WHERE ID=2691;
UPDATE `Recipe` SET RecipeName='Blue Bacon Brussels Salad', CookTime='10', DietType='TBD', IngredientCount='9', ImgURL='2692.jpg' WHERE ID=2692;
UPDATE `Recipe` SET RecipeName='Boiled Baked Potato Salad', CookTime='35', DietType='TBD', IngredientCount='8', ImgURL='2693.jpg' WHERE ID=2693;
UPDATE `Recipe` SET RecipeName='Bread in a Crock Pot', CookTime='120', DietType='TBD', IngredientCount='0', ImgURL='2694.jpg' WHERE ID=2694;
UPDATE `Recipe` SET RecipeName='Bread - Just Bread', CookTime='70', DietType='TBD', IngredientCount='8', ImgURL='2695.jpg' WHERE ID=2695;
UPDATE `Recipe` SET RecipeName='Bread Stuffing in a Pinch', CookTime='10', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=2696;
UPDATE `Recipe` SET RecipeName='Brocc Cheese Mashed', CookTime='30', DietType='TBD', IngredientCount='15', ImgURL='2697.jpg' WHERE ID=2697;
UPDATE `Recipe` SET RecipeName='Brocc Zucc Sal', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2698;
UPDATE `Recipe` SET RecipeName='Broccoli and Garlic Cream Sauce', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='2699.jpg' WHERE ID=2699;
UPDATE `Recipe` SET RecipeName='Broccoli Cheddar Cups', CookTime='25', DietType='TBD', IngredientCount='5', ImgURL='2700.jpg' WHERE ID=2700;
UPDATE `Recipe` SET RecipeName='Broccoli Cheddar Potatoes', CookTime='80', DietType='TBD', IngredientCount='7', ImgURL='2701.jpg' WHERE ID=2701;
UPDATE `Recipe` SET RecipeName='Broccoli Cheddar Stuffed Potatoes', CookTime='80', DietType='TBD', IngredientCount='16', ImgURL='2702.jpg' WHERE ID=2702;
UPDATE `Recipe` SET RecipeName='Broccoli Gratin', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='2703.jpg' WHERE ID=2703;
UPDATE `Recipe` SET RecipeName='Broccoli w/ Mushroom Sauce', CookTime='45', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=2704;
UPDATE `Recipe` SET RecipeName='Broiled Red Potatoes', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='2705.jpg' WHERE ID=2705;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Bacon Ranch Cheese Fries', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='2706.jpg' WHERE ID=2706;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Bread', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='2707.jpg' WHERE ID=2707;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Potatoes', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='2708.jpg' WHERE ID=2708;
UPDATE `Recipe` SET RecipeName='Buiscuit Turnovers', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=2709;
UPDATE `Recipe` SET RecipeName='Bunny Rolls', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='2710.jpg' WHERE ID=2710;
UPDATE `Recipe` SET RecipeName='Burnin Fries', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='2711.jpg' WHERE ID=2711;
UPDATE `Recipe` SET RecipeName='Cajun Peanuts', CookTime='480', DietType='TBD', IngredientCount='5', ImgURL='2712.jpg' WHERE ID=2712;
UPDATE `Recipe` SET RecipeName='Canadian Fries', CookTime='30', DietType='TBD', IngredientCount='2', ImgURL='2713.jpg' WHERE ID=2713;
UPDATE `Recipe` SET RecipeName='Caprese Stuffed Mushrooms', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='2714.jpg' WHERE ID=2714;
UPDATE `Recipe` SET RecipeName='Caprese toast', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='2715.jpg' WHERE ID=2715;
UPDATE `Recipe` SET RecipeName='Caramelized Squash', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='2716.jpg' WHERE ID=2716;
UPDATE `Recipe` SET RecipeName='Carmelized Zucchini with Mint', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2717;
UPDATE `Recipe` SET RecipeName='Carrot Bread in a Blender', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='2718.jpg' WHERE ID=2718;
UPDATE `Recipe` SET RecipeName='Cashew Broccoli', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='2719.jpg' WHERE ID=2719;
UPDATE `Recipe` SET RecipeName='Cauliflower Broccoli Casserole', CookTime='50', DietType='TBD', IngredientCount='8', ImgURL='2720.jpg' WHERE ID=2720;
UPDATE `Recipe` SET RecipeName='Cauliflower Cakes', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='2721.jpg' WHERE ID=2721;
UPDATE `Recipe` SET RecipeName='Cauliflower Gratin', CookTime='50', DietType='TBD', IngredientCount='11', ImgURL='2722.jpg' WHERE ID=2722;
UPDATE `Recipe` SET RecipeName='Cauliflower on a Stick', CookTime='10', DietType='TBD', IngredientCount='10', ImgURL='2723.jpg' WHERE ID=2723;
UPDATE `Recipe` SET RecipeName='Celery and Horsey Dip', CookTime='15', DietType='TBD', IngredientCount='9', ImgURL='2724.jpg' WHERE ID=2724;
UPDATE `Recipe` SET RecipeName='Celery Garlic Toast (Diabetic)', CookTime='25', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=2725;
UPDATE `Recipe` SET RecipeName='Celery Stuffing', CookTime='60', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=2726;
UPDATE `Recipe` SET RecipeName='Cheddar Biscuits', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='2727.jpg' WHERE ID=2727;
UPDATE `Recipe` SET RecipeName='Cheddar Biscuits (1)', CookTime='15', DietType='TBD', IngredientCount='11', ImgURL='2728.jpg' WHERE ID=2728;
UPDATE `Recipe` SET RecipeName='Cheese Broccoli', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=2729;
UPDATE `Recipe` SET RecipeName='Cheeseburger Zucchini Boat', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='2730.jpg' WHERE ID=2730;
UPDATE `Recipe` SET RecipeName='Cheesy Bacon Biscuits', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='2731.jpg' WHERE ID=2731;
UPDATE `Recipe` SET RecipeName='Cheesy Bacon Cabbage', CookTime='40', DietType='TBD', IngredientCount='5', ImgURL='2732.jpg' WHERE ID=2732;
UPDATE `Recipe` SET RecipeName='Cheesy Bacon Hasselback Potatoes', CookTime='40', DietType='TBD', IngredientCount='8', ImgURL='2733.jpg' WHERE ID=2733;
UPDATE `Recipe` SET RecipeName='Cheesy Bacon Ranch Potatoes', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='2734.jpg' WHERE ID=2734;
UPDATE `Recipe` SET RecipeName='Cheesy Broccoli Bites', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='2735.jpg' WHERE ID=2735;
UPDATE `Recipe` SET RecipeName='Cheesy Cauliflower Pancakes', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='2736.jpg' WHERE ID=2736;
UPDATE `Recipe` SET RecipeName='Cheesy Fry Pack', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='2737.jpg' WHERE ID=2737;
UPDATE `Recipe` SET RecipeName='Cheesy Garlic Tomatoes', CookTime='15', DietType='TBD', IngredientCount='12', ImgURL='2738.jpg' WHERE ID=2738;
UPDATE `Recipe` SET RecipeName='Cheesy Green Bean Casserole', CookTime='30', DietType='TBD', IngredientCount='13', ImgURL='2739.jpg' WHERE ID=2739;
UPDATE `Recipe` SET RecipeName='Cheesy Hasselback Potatoes', CookTime='45', DietType='TBD', IngredientCount='8', ImgURL='2740.jpg' WHERE ID=2740;
UPDATE `Recipe` SET RecipeName='Cheesy Hot Fries', CookTime='25', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=2741;
UPDATE `Recipe` SET RecipeName='Cheesy Oven Potato Chips', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='2742.jpg' WHERE ID=2742;
UPDATE `Recipe` SET RecipeName='Cheesy Potato Pan', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='2743.jpg' WHERE ID=2743;
UPDATE `Recipe` SET RecipeName='Cheesy Potato Pancakes', CookTime='20', DietType='TBD', IngredientCount='12', ImgURL='2744.jpg' WHERE ID=2744;
UPDATE `Recipe` SET RecipeName='Cheesy Potato Patties', CookTime='40', DietType='TBD', IngredientCount='9', ImgURL='2745.jpg' WHERE ID=2745;
UPDATE `Recipe` SET RecipeName='Cheesy Ranch Tots', CookTime='25', DietType='TBD', IngredientCount='14', ImgURL='2746.jpg' WHERE ID=2746;
UPDATE `Recipe` SET RecipeName='Cheesy Scalloped Potatoes', CookTime='90', DietType='TBD', IngredientCount='8', ImgURL='2747.jpg' WHERE ID=2747;
UPDATE `Recipe` SET RecipeName='Cheesy Stuffed Biscuits', CookTime='12', DietType='TBD', IngredientCount='4', ImgURL='2748.jpg' WHERE ID=2748;
UPDATE `Recipe` SET RecipeName='Cheezy Spuds', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='2749.jpg' WHERE ID=2749;
UPDATE `Recipe` SET RecipeName='Chicken and Broccoli Salad', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='2750.jpg' WHERE ID=2750;
UPDATE `Recipe` SET RecipeName='Chicken Bouillon Rice', CookTime='20', DietType='TBD', IngredientCount='3', ImgURL='2751.jpg' WHERE ID=2751;
UPDATE `Recipe` SET RecipeName='Chicken Cheddar Garlic Biscuit', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='2752.jpg' WHERE ID=2752;
UPDATE `Recipe` SET RecipeName='Chicken Risotto', CookTime='10', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=2753;
UPDATE `Recipe` SET RecipeName='Chicken Salad Wraps', CookTime='40', DietType='TBD', IngredientCount='17', ImgURL='2754.jpg' WHERE ID=2754;
UPDATE `Recipe` SET RecipeName='Chili Roasted Green Beans', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=2755;
UPDATE `Recipe` SET RecipeName='Chili Roasted Potatoes', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=2756;
UPDATE `Recipe` SET RecipeName='Chineese Style Fried Rice', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2757;
UPDATE `Recipe` SET RecipeName='Chive and Cheddar Biscuits', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='2758.jpg' WHERE ID=2758;
UPDATE `Recipe` SET RecipeName='Cider Carrots', CookTime='15', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=2759;
UPDATE `Recipe` SET RecipeName='Cider Green Beans', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='2760.jpg' WHERE ID=2760;
UPDATE `Recipe` SET RecipeName='Cider Potatoes', CookTime='30', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=2761;
UPDATE `Recipe` SET RecipeName='Coconut MIlk Rolls', CookTime='180', DietType='TBD', IngredientCount='8', ImgURL='2762.jpg' WHERE ID=2762;
UPDATE `Recipe` SET RecipeName='Coleslaw with a Kick', CookTime='25', DietType='TBD', IngredientCount='9', ImgURL='2763.jpg' WHERE ID=2763;
UPDATE `Recipe` SET RecipeName='College Broc and Cheese', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='2764.jpg' WHERE ID=2764;
UPDATE `Recipe` SET RecipeName='College Garlic Toast', CookTime='5', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2765;
UPDATE `Recipe` SET RecipeName='Corn and Zucchini Fritters', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='2766.jpg' WHERE ID=2766;
UPDATE `Recipe` SET RecipeName='Corn Casserole', CookTime='85', DietType='TBD', IngredientCount='10', ImgURL='2767.jpg' WHERE ID=2767;
UPDATE `Recipe` SET RecipeName='Corn Crisps', CookTime='15', DietType='TBD', IngredientCount='11', ImgURL='2768.jpg' WHERE ID=2768;
UPDATE `Recipe` SET RecipeName='Corn on the Cob (Mexi)', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='2769.jpg' WHERE ID=2769;
UPDATE `Recipe` SET RecipeName='Cornbread heaven', CookTime='35', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=2770;
UPDATE `Recipe` SET RecipeName='Crab and Petso Biscuits', CookTime='32', DietType='TBD', IngredientCount='1', ImgURL='' WHERE ID=2771;
UPDATE `Recipe` SET RecipeName='Crack Corn and I Dont Care', CookTime='10', DietType='TBD', IngredientCount='7', ImgURL='2772.jpg' WHERE ID=2772;
UPDATE `Recipe` SET RecipeName='Cracker Barrel Hashbrown Casserole', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='2773.jpg' WHERE ID=2773;
UPDATE `Recipe` SET RecipeName='Cranberry Carrots', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=2774;
UPDATE `Recipe` SET RecipeName='Cranberry - Orange Relish', CookTime='5', DietType='TBD', IngredientCount='3', ImgURL='2775.jpg' WHERE ID=2775;
UPDATE `Recipe` SET RecipeName='Cranberry Spinach Salad', CookTime='20', DietType='TBD', IngredientCount='12', ImgURL='2776.jpg' WHERE ID=2776;
UPDATE `Recipe` SET RecipeName='Crazy Crunchy Potato Casserole', CookTime='60', DietType='TBD', IngredientCount='10', ImgURL='2777.jpg' WHERE ID=2777;
UPDATE `Recipe` SET RecipeName='Crazy Good Green Bean Casserole', CookTime='35', DietType='TBD', IngredientCount='8', ImgURL='2778.jpg' WHERE ID=2778;
UPDATE `Recipe` SET RecipeName='Creamed Onions', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2779;
UPDATE `Recipe` SET RecipeName='Creamy Cucumber Salad', CookTime='20', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2780;
UPDATE `Recipe` SET RecipeName='Creamy Spinach', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2781;
UPDATE `Recipe` SET RecipeName='Creamy Spinach Onions and Mushrooms', CookTime='50', DietType='TBD', IngredientCount='13', ImgURL='2782.jpg' WHERE ID=2782;
UPDATE `Recipe` SET RecipeName='Creole Rice', CookTime='5', DietType='TBD', IngredientCount='4', ImgURL='2783.jpg' WHERE ID=2783;
UPDATE `Recipe` SET RecipeName='Crispy Home Fries', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='2784.jpg' WHERE ID=2784;
UPDATE `Recipe` SET RecipeName='Crispy Parmesan Potatoes', CookTime='40', DietType='TBD', IngredientCount='12', ImgURL='2785.jpg' WHERE ID=2785;
UPDATE `Recipe` SET RecipeName='Crispy Roasted Root Vegetables', CookTime='35', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=2786;
UPDATE `Recipe` SET RecipeName='Crispy Tater Tots', CookTime='25', DietType='TBD', IngredientCount='9', ImgURL='2787.jpg' WHERE ID=2787;
UPDATE `Recipe` SET RecipeName='Crock Pot Apple Sauce', CookTime='360', DietType='TBD', IngredientCount='6', ImgURL='2788.jpg' WHERE ID=2788;
UPDATE `Recipe` SET RecipeName='Crock Pot Apple Sauce Again', CookTime='180', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=2789;
UPDATE `Recipe` SET RecipeName='Crock Pot Creamed Corn', CookTime='180', DietType='TBD', IngredientCount='8', ImgURL='2790.jpg' WHERE ID=2790;
UPDATE `Recipe` SET RecipeName='Crock Pot Stuffing', CookTime='180', DietType='TBD', IngredientCount='12', ImgURL='2791.jpg' WHERE ID=2791;
UPDATE `Recipe` SET RecipeName='Crock Pot Taters', CookTime='360', DietType='TBD', IngredientCount='5', ImgURL='2792.jpg' WHERE ID=2792;
UPDATE `Recipe` SET RecipeName='Crockpot Mushrooms', CookTime='300', DietType='TBD', IngredientCount='5', ImgURL='2793.jpg' WHERE ID=2793;
UPDATE `Recipe` SET RecipeName='Crumbled Blue Cheese Spinach S', CookTime='8', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2794;
UPDATE `Recipe` SET RecipeName='Crunchy Green Beans', CookTime='10', DietType='TBD', IngredientCount='14', ImgURL='2795.jpg' WHERE ID=2795;
UPDATE `Recipe` SET RecipeName='Crushed Cheesy Potatoes', CookTime='45', DietType='TBD', IngredientCount='10', ImgURL='2796.jpg' WHERE ID=2796;
UPDATE `Recipe` SET RecipeName='CTA Salad!', CookTime='20', DietType='TBD', IngredientCount='14', ImgURL='2797.jpg' WHERE ID=2797;
UPDATE `Recipe` SET RecipeName='Cuccumbers (sp?) dressing', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='2798.jpg' WHERE ID=2798;
UPDATE `Recipe` SET RecipeName='Cucumber n Tomato Salad', CookTime='10', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=2799;
UPDATE `Recipe` SET RecipeName='Cucumber Onion and Tomato Salad', CookTime='40', DietType='TBD', IngredientCount='7', ImgURL='2800.jpg' WHERE ID=2800;
UPDATE `Recipe` SET RecipeName='Cucumber Onion Salad', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='2801.jpg' WHERE ID=2801;
UPDATE `Recipe` SET RecipeName='Danish Red Cabbage', CookTime='90', DietType='TBD', IngredientCount='4', ImgURL='2802.jpg' WHERE ID=2802;
UPDATE `Recipe` SET RecipeName='Dijon Roasted Cabbage', CookTime='25', DietType='TBD', IngredientCount='9', ImgURL='2803.jpg' WHERE ID=2803;
UPDATE `Recipe` SET RecipeName='DIY low fat Tortillas', CookTime='55', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2804;
UPDATE `Recipe` SET RecipeName='DIY Taco Bowls', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='2805.jpg' WHERE ID=2805;
UPDATE `Recipe` SET RecipeName='DIY Tortillas', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='2806.jpg' WHERE ID=2806;
UPDATE `Recipe` SET RecipeName='Doritos Ramen Salad', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2807;
UPDATE `Recipe` SET RecipeName='Double Stuffed Bakers', CookTime='80', DietType='TBD', IngredientCount='10', ImgURL='2808.jpg' WHERE ID=2808;
UPDATE `Recipe` SET RecipeName='Easiest Biscuits', CookTime='40', DietType='TBD', IngredientCount='4', ImgURL='2809.jpg' WHERE ID=2809;
UPDATE `Recipe` SET RecipeName='Easy Bread', CookTime='600', DietType='TBD', IngredientCount='4', ImgURL='2810.jpg' WHERE ID=2810;
UPDATE `Recipe` SET RecipeName='Easy Bread Knots', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='2811.jpg' WHERE ID=2811;
UPDATE `Recipe` SET RecipeName='Easy Brown Rice', CookTime='80', DietType='TBD', IngredientCount='7', ImgURL='2812.jpg' WHERE ID=2812;
UPDATE `Recipe` SET RecipeName='Easy Cheesy Garlic Bread', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='2813.jpg' WHERE ID=2813;
UPDATE `Recipe` SET RecipeName='Easy Cheesy Scalloped Potatoes', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='2814.jpg' WHERE ID=2814;
UPDATE `Recipe` SET RecipeName='Easy Fried Sweet Corn', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='2815.jpg' WHERE ID=2815;
UPDATE `Recipe` SET RecipeName='Easy Garlic Breadsticks', CookTime='60', DietType='TBD', IngredientCount='13', ImgURL='2816.jpg' WHERE ID=2816;
UPDATE `Recipe` SET RecipeName='Easy Garlic Croutons', CookTime='10', DietType='TBD', IngredientCount='8', ImgURL='2817.jpg' WHERE ID=2817;
UPDATE `Recipe` SET RecipeName='Easy Garlic Fries', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='2818.jpg' WHERE ID=2818;
UPDATE `Recipe` SET RecipeName='Easy Garlic Pull Apart Rolls', CookTime='60', DietType='TBD', IngredientCount='8', ImgURL='2819.jpg' WHERE ID=2819;
UPDATE `Recipe` SET RecipeName='Easy Homemade Breadcrumbs', CookTime='25', DietType='TBD', IngredientCount='2', ImgURL='' WHERE ID=2820;
UPDATE `Recipe` SET RecipeName='Easy Hush Puppies', CookTime='5', DietType='TBD', IngredientCount='10', ImgURL='2821.jpg' WHERE ID=2821;
UPDATE `Recipe` SET RecipeName='Easy Mashed', CookTime='40', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2822;
UPDATE `Recipe` SET RecipeName='Easy Mashed Potato Cakes', CookTime='40', DietType='TBD', IngredientCount='13', ImgURL='2823.jpg' WHERE ID=2823;
UPDATE `Recipe` SET RecipeName='Easy Pickled Peppers', CookTime='360', DietType='TBD', IngredientCount='10', ImgURL='2824.jpg' WHERE ID=2824;
UPDATE `Recipe` SET RecipeName='Easy Potato Pancakes', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='2825.jpg' WHERE ID=2825;
UPDATE `Recipe` SET RecipeName='Easy Potato Salad', CookTime='35', DietType='TBD', IngredientCount='15', ImgURL='2826.jpg' WHERE ID=2826;
UPDATE `Recipe` SET RecipeName='Easy Potato Squares', CookTime='30', DietType='TBD', IngredientCount='3', ImgURL='2827.jpg' WHERE ID=2827;
UPDATE `Recipe` SET RecipeName='Easy Roasted Cabbage', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='2828.jpg' WHERE ID=2828;
UPDATE `Recipe` SET RecipeName='Easy Roasted Mushrooms', CookTime='40', DietType='TBD', IngredientCount='11', ImgURL='2829.jpg' WHERE ID=2829;
UPDATE `Recipe` SET RecipeName='Easy Roasted Potatoes', CookTime='70', DietType='TBD', IngredientCount='13', ImgURL='2830.jpg' WHERE ID=2830;
UPDATE `Recipe` SET RecipeName='Easy Stack Potatoes', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='2831.jpg' WHERE ID=2831;
UPDATE `Recipe` SET RecipeName='Fancy Green Beans', CookTime='10', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=2832;
UPDATE `Recipe` SET RecipeName='Fast Mac and Cheese', CookTime='35', DietType='TBD', IngredientCount='7', ImgURL='2833.jpg' WHERE ID=2833;
UPDATE `Recipe` SET RecipeName='Flat Bottomed Taco Shells', CookTime='10', DietType='TBD', IngredientCount='1', ImgURL='2834.jpg' WHERE ID=2834;
UPDATE `Recipe` SET RecipeName='Fried Cabbage with Bacon', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='2835.jpg' WHERE ID=2835;
UPDATE `Recipe` SET RecipeName='Fried German Potato Salad', CookTime='40', DietType='TBD', IngredientCount='13', ImgURL='2836.jpg' WHERE ID=2836;
UPDATE `Recipe` SET RecipeName='Fried Green Tomatos', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2837;
UPDATE `Recipe` SET RecipeName='Fried Zucchini', CookTime='45', DietType='TBD', IngredientCount='8', ImgURL='2838.jpg' WHERE ID=2838;
UPDATE `Recipe` SET RecipeName='Fruit Compote', CookTime='30', DietType='TBD', IngredientCount='4', ImgURL='2839.jpg' WHERE ID=2839;
UPDATE `Recipe` SET RecipeName='Garlic Baked Potato', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='2840.jpg' WHERE ID=2840;
UPDATE `Recipe` SET RecipeName='Garlic Bread Fries', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='2841.jpg' WHERE ID=2841;
UPDATE `Recipe` SET RecipeName='Garlic Bread from a Toaster', CookTime='3', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2842;
UPDATE `Recipe` SET RecipeName='Garlic Bread in a Pinch', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='2843.jpg' WHERE ID=2843;
UPDATE `Recipe` SET RecipeName='Garlic Cheese Biscuits', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='2844.jpg' WHERE ID=2844;
UPDATE `Recipe` SET RecipeName='Garlic Cheese Fries', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='2845.jpg' WHERE ID=2845;
UPDATE `Recipe` SET RecipeName='Garlic Croutons', CookTime='5', DietType='TBD', IngredientCount='3', ImgURL='2846.jpg' WHERE ID=2846;
UPDATE `Recipe` SET RecipeName='Garlic Green Beans', CookTime='5', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2847;
UPDATE `Recipe` SET RecipeName='Garlic Hasselback Roasted Potatoes', CookTime='50', DietType='TBD', IngredientCount='11', ImgURL='2848.jpg' WHERE ID=2848;
UPDATE `Recipe` SET RecipeName='Garlic Herb Potatoes', CookTime='50', DietType='TBD', IngredientCount='11', ImgURL='2849.jpg' WHERE ID=2849;
UPDATE `Recipe` SET RecipeName='Garlic Parmesan Fries', CookTime='45', DietType='TBD', IngredientCount='9', ImgURL='2850.jpg' WHERE ID=2850;
UPDATE `Recipe` SET RecipeName='Garlic Potato Balls', CookTime='20', DietType='TBD', IngredientCount='12', ImgURL='2851.jpg' WHERE ID=2851;
UPDATE `Recipe` SET RecipeName='Garlic Potato Halves', CookTime='45', DietType='TBD', IngredientCount='9', ImgURL='2852.jpg' WHERE ID=2852;
UPDATE `Recipe` SET RecipeName='Garlic Potato Wedges', CookTime='50', DietType='TBD', IngredientCount='11', ImgURL='2853.jpg' WHERE ID=2853;
UPDATE `Recipe` SET RecipeName='Garlic Roll Cupcakes', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='2854.jpg' WHERE ID=2854;
UPDATE `Recipe` SET RecipeName='Garlic Smashed Potatoes', CookTime='50', DietType='TBD', IngredientCount='11', ImgURL='2855.jpg' WHERE ID=2855;
UPDATE `Recipe` SET RecipeName='Garlic Wine Rice Pilaf', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=2856;
UPDATE `Recipe` SET RecipeName='German Fry Salad', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=2857;
UPDATE `Recipe` SET RecipeName='Glazed Carrots', CookTime='10', DietType='TBD', IngredientCount='7', ImgURL='2858.jpg' WHERE ID=2858;
UPDATE `Recipe` SET RecipeName='Good Ol Baked Beans', CookTime='60', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2859;
UPDATE `Recipe` SET RecipeName='Grand Marnier Grilled Oranges', CookTime='60', DietType='TBD', IngredientCount='3', ImgURL='2860.jpg' WHERE ID=2860;
UPDATE `Recipe` SET RecipeName='Grandmas Baked Beans', CookTime='300', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=2861;
UPDATE `Recipe` SET RecipeName='Green Bean Bundle', CookTime='25', DietType='TBD', IngredientCount='8', ImgURL='2862.jpg' WHERE ID=2862;
UPDATE `Recipe` SET RecipeName='Green Bean Feta Salad', CookTime='20', DietType='TBD', IngredientCount='14', ImgURL='2863.jpg' WHERE ID=2863;
UPDATE `Recipe` SET RecipeName='Grilled Asparagus and Feta', CookTime='10', DietType='TBD', IngredientCount='11', ImgURL='2864.jpg' WHERE ID=2864;
UPDATE `Recipe` SET RecipeName='Grilled Avacado', CookTime='15', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=2865;
UPDATE `Recipe` SET RecipeName='Grilled Bell Peppers', CookTime='15', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=2866;
UPDATE `Recipe` SET RecipeName='Grilled Cabbage', CookTime='40', DietType='TBD', IngredientCount='8', ImgURL='2867.jpg' WHERE ID=2867;
UPDATE `Recipe` SET RecipeName='Grilled Celery with Blue Chees', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=2868;
UPDATE `Recipe` SET RecipeName='Grilled Green Beans', CookTime='20', DietType='TBD', IngredientCount='13', ImgURL='2869.jpg' WHERE ID=2869;
UPDATE `Recipe` SET RecipeName='Grilled Potato Packs', CookTime='25', DietType='TBD', IngredientCount='7', ImgURL='2870.jpg' WHERE ID=2870;
UPDATE `Recipe` SET RecipeName='Grilled Zucchini', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='2871.jpg' WHERE ID=2871;
UPDATE `Recipe` SET RecipeName='Guilt Free Fries', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='2872.jpg' WHERE ID=2872;
UPDATE `Recipe` SET RecipeName='Ham Biscuits', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=2873;
UPDATE `Recipe` SET RecipeName='Ham Cheese and Cauliflower Fritters', CookTime='15', DietType='TBD', IngredientCount='12', ImgURL='2874.jpg' WHERE ID=2874;
UPDATE `Recipe` SET RecipeName='Ham Salad', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='2875.jpg' WHERE ID=2875;
UPDATE `Recipe` SET RecipeName='Hasselback Caprese Salad', CookTime='10', DietType='TBD', IngredientCount='8', ImgURL='2876.jpg' WHERE ID=2876;
UPDATE `Recipe` SET RecipeName='Hasselback Garlic Bread', CookTime='80', DietType='TBD', IngredientCount='12', ImgURL='2877.jpg' WHERE ID=2877;
UPDATE `Recipe` SET RecipeName='Hasselback Potatoes', CookTime='40', DietType='TBD', IngredientCount='9', ImgURL='2878.jpg' WHERE ID=2878;
UPDATE `Recipe` SET RecipeName='Hasselback Zucchini', CookTime='60', DietType='TBD', IngredientCount='13', ImgURL='2879.jpg' WHERE ID=2879;
UPDATE `Recipe` SET RecipeName='Hawaiian Rolls', CookTime='120', DietType='TBD', IngredientCount='10', ImgURL='2880.jpg' WHERE ID=2880;
UPDATE `Recipe` SET RecipeName='Hawaiian Sweet Rolls', CookTime='120', DietType='TBD', IngredientCount='10', ImgURL='2881.jpg' WHERE ID=2881;
UPDATE `Recipe` SET RecipeName='Healthy Coleslaw Revamp!', CookTime='5', DietType='TBD', IngredientCount='7', ImgURL='2882.jpg' WHERE ID=2882;
UPDATE `Recipe` SET RecipeName='Healthy Cucumber Salad', CookTime='120', DietType='TBD', IngredientCount='6', ImgURL='2883.jpg' WHERE ID=2883;
UPDATE `Recipe` SET RecipeName='Healthy Tots', CookTime='25', DietType='TBD', IngredientCount='8', ImgURL='2884.jpg' WHERE ID=2884;
UPDATE `Recipe` SET RecipeName='Home Bread', CookTime='180', DietType='TBD', IngredientCount='6', ImgURL='2885.jpg' WHERE ID=2885;
UPDATE `Recipe` SET RecipeName='Home Tortillas', CookTime='90', DietType='TBD', IngredientCount='3', ImgURL='2886.jpg' WHERE ID=2886;
UPDATE `Recipe` SET RecipeName='Homemade Applesauce', CookTime='30', DietType='TBD', IngredientCount='4', ImgURL='2887.jpg' WHERE ID=2887;
UPDATE `Recipe` SET RecipeName='Homemade Bread Bowl', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='2888.jpg' WHERE ID=2888;
UPDATE `Recipe` SET RecipeName='Homemade Chips', CookTime='25', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=2889;
UPDATE `Recipe` SET RecipeName='Homemade English Muffins', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='2890.jpg' WHERE ID=2890;
UPDATE `Recipe` SET RecipeName='Homemade Fried Rice', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='2891.jpg' WHERE ID=2891;
UPDATE `Recipe` SET RecipeName='Homemade Fries', CookTime='30', DietType='TBD', IngredientCount='4', ImgURL='2892.jpg' WHERE ID=2892;
UPDATE `Recipe` SET RecipeName='Homemade Parmesan Garlic Fries', CookTime='30', DietType='TBD', IngredientCount='10', ImgURL='2893.jpg' WHERE ID=2893;
UPDATE `Recipe` SET RecipeName='Homemade Pickled Jalapenos', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='2894.jpg' WHERE ID=2894;
UPDATE `Recipe` SET RecipeName='Homemade Pretzel Bites', CookTime='40', DietType='TBD', IngredientCount='7', ImgURL='2895.jpg' WHERE ID=2895;
UPDATE `Recipe` SET RecipeName='Homemade Skin Fries', CookTime='50', DietType='TBD', IngredientCount='4', ImgURL='2896.jpg' WHERE ID=2896;
UPDATE `Recipe` SET RecipeName='Homemade Sweet Pickles', CookTime='200', DietType='TBD', IngredientCount='8', ImgURL='2897.jpg' WHERE ID=2897;
UPDATE `Recipe` SET RecipeName='Homemade Tater Tots', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='2898.jpg' WHERE ID=2898;
UPDATE `Recipe` SET RecipeName='Homestyle Fried Potatoes', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=2899;
UPDATE `Recipe` SET RecipeName='Honey Garlic Carrots', CookTime='25', DietType='TBD', IngredientCount='7', ImgURL='2900.jpg' WHERE ID=2900;
UPDATE `Recipe` SET RecipeName='Honey Roasted Potatoes', CookTime='50', DietType='TBD', IngredientCount='8', ImgURL='2901.jpg' WHERE ID=2901;
UPDATE `Recipe` SET RecipeName='HPB - Casserole', CookTime='45', DietType='TBD', IngredientCount='8', ImgURL='2902.jpg' WHERE ID=2902;
UPDATE `Recipe` SET RecipeName='Italian Fries', CookTime='15', DietType='TBD', IngredientCount='9', ImgURL='2903.jpg' WHERE ID=2903;
UPDATE `Recipe` SET RecipeName='Italian Green Beans', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='2904.jpg' WHERE ID=2904;
UPDATE `Recipe` SET RecipeName='Italian Pasta Salad', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='2905.jpg' WHERE ID=2905;
UPDATE `Recipe` SET RecipeName='Italian Red Potatoes', CookTime='45', DietType='TBD', IngredientCount='9', ImgURL='2906.jpg' WHERE ID=2906;
UPDATE `Recipe` SET RecipeName='Jello Salad', CookTime='60', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2907;
UPDATE `Recipe` SET RecipeName='Jennys Creole Noodles', CookTime='12', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=2908;
UPDATE `Recipe` SET RecipeName='KFC Coleslaw', CookTime='120', DietType='TBD', IngredientCount='12', ImgURL='2909.jpg' WHERE ID=2909;
UPDATE `Recipe` SET RecipeName='Kupus Salata', CookTime='5', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2910;
UPDATE `Recipe` SET RecipeName='Layered Salad', CookTime='30', DietType='TBD', IngredientCount='19', ImgURL='2911.jpg' WHERE ID=2911;
UPDATE `Recipe` SET RecipeName='Lazy Sausage and Potatoes', CookTime='45', DietType='TBD', IngredientCount='14', ImgURL='2912.jpg' WHERE ID=2912;
UPDATE `Recipe` SET RecipeName='Leftover Mashed Potato Cakes', CookTime='20', DietType='TBD', IngredientCount='13', ImgURL='2913.jpg' WHERE ID=2913;
UPDATE `Recipe` SET RecipeName='Leftover Mashed Potato Muffins', CookTime='50', DietType='TBD', IngredientCount='8', ImgURL='2914.jpg' WHERE ID=2914;
UPDATE `Recipe` SET RecipeName='Lemon Broccoli', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='2915.jpg' WHERE ID=2915;
UPDATE `Recipe` SET RecipeName='Lemon Roasted Potatoes', CookTime='65', DietType='TBD', IngredientCount='5', ImgURL='2916.jpg' WHERE ID=2916;
UPDATE `Recipe` SET RecipeName='Lime Shrimp and Avocado Salad', CookTime='10', DietType='TBD', IngredientCount='11', ImgURL='2917.jpg' WHERE ID=2917;
UPDATE `Recipe` SET RecipeName='Lime Shrimp Avocado Salad', CookTime='10', DietType='TBD', IngredientCount='11', ImgURL='2918.jpg' WHERE ID=2918;
UPDATE `Recipe` SET RecipeName='Little Blooming Onions', CookTime='15', DietType='TBD', IngredientCount='13', ImgURL='2919.jpg' WHERE ID=2919;
UPDATE `Recipe` SET RecipeName='Loaded Bacon Potato Salad', CookTime='40', DietType='TBD', IngredientCount='7', ImgURL='2920.jpg' WHERE ID=2920;
UPDATE `Recipe` SET RecipeName='Loaded Cauliflower Casserole', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='2921.jpg' WHERE ID=2921;
UPDATE `Recipe` SET RecipeName='Loaded Mashed', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='2922.jpg' WHERE ID=2922;
UPDATE `Recipe` SET RecipeName='Loaded Mashed Potatoes', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='2923.jpg' WHERE ID=2923;
UPDATE `Recipe` SET RecipeName='Loaded Potato Salad', CookTime='35', DietType='TBD', IngredientCount='10', ImgURL='2924.jpg' WHERE ID=2924;
UPDATE `Recipe` SET RecipeName='Loaded Potato Slices', CookTime='90', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=2925;
UPDATE `Recipe` SET RecipeName='Loaded Stuffed Bread', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='2926.jpg' WHERE ID=2926;
UPDATE `Recipe` SET RecipeName='Low Cal Cauliflower', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='2927.jpg' WHERE ID=2927;
UPDATE `Recipe` SET RecipeName='Low Cal Cucumber Salad', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='2928.jpg' WHERE ID=2928;
UPDATE `Recipe` SET RecipeName='Low Carb Cauliflower Mashed', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='2929.jpg' WHERE ID=2929;
UPDATE `Recipe` SET RecipeName='Low Carb Mash Cauliflower', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='2930.jpg' WHERE ID=2930;
UPDATE `Recipe` SET RecipeName='Low (er) Fat Potato Casserole', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='2931.jpg' WHERE ID=2931;
UPDATE `Recipe` SET RecipeName='Low Fat Biscuits', CookTime='15', DietType='TBD', IngredientCount='1', ImgURL='2932.jpg' WHERE ID=2932;
UPDATE `Recipe` SET RecipeName='Mac and Cheese Rolls', CookTime='30', DietType='TBD', IngredientCount='1', ImgURL='2933.jpg' WHERE ID=2933;
UPDATE `Recipe` SET RecipeName='Macaroni Grill Bread', CookTime='45', DietType='TBD', IngredientCount='12', ImgURL='2934.jpg' WHERE ID=2934;
UPDATE `Recipe` SET RecipeName='Maple Glazed Carrots', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2935;
UPDATE `Recipe` SET RecipeName='Maple Sweet Potatoes', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='2936.jpg' WHERE ID=2936;
UPDATE `Recipe` SET RecipeName='Marinated Mushrooms', CookTime='120', DietType='TBD', IngredientCount='9', ImgURL='2937.jpg' WHERE ID=2937;
UPDATE `Recipe` SET RecipeName='Mario Salad', CookTime='15', DietType='TBD', IngredientCount='5', ImgURL='2938.jpg' WHERE ID=2938;
UPDATE `Recipe` SET RecipeName='Mashed Potato Bites', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='2939.jpg' WHERE ID=2939;
UPDATE `Recipe` SET RecipeName='Mashed Potato Muffins', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='2940.jpg' WHERE ID=2940;
UPDATE `Recipe` SET RecipeName='Mashed Potato Puffs', CookTime='35', DietType='TBD', IngredientCount='9', ImgURL='2941.jpg' WHERE ID=2941;
UPDATE `Recipe` SET RecipeName='Mexican Corn on the Cob', CookTime='10', DietType='TBD', IngredientCount='4', ImgURL='2942.jpg' WHERE ID=2942;
UPDATE `Recipe` SET RecipeName='Microwaved Twice Spuds', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=2943;
UPDATE `Recipe` SET RecipeName='More Baked Onion Rings', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='2944.jpg' WHERE ID=2944;
UPDATE `Recipe` SET RecipeName='More Caprese Garlic Bread', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='2945.jpg' WHERE ID=2945;
UPDATE `Recipe` SET RecipeName='More Cheesy Stuffed Biscuits', CookTime='15', DietType='TBD', IngredientCount='15', ImgURL='2946.jpg' WHERE ID=2946;
UPDATE `Recipe` SET RecipeName='More Glazed Carrots', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='2947.jpg' WHERE ID=2947;
UPDATE `Recipe` SET RecipeName='More Loaded Mashed', CookTime='60', DietType='TBD', IngredientCount='10', ImgURL='2948.jpg' WHERE ID=2948;
UPDATE `Recipe` SET RecipeName='More Loaded Mashed Potatoes', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='2949.jpg' WHERE ID=2949;
UPDATE `Recipe` SET RecipeName='More Loaded Potato Salad', CookTime='60', DietType='TBD', IngredientCount='10', ImgURL='2950.jpg' WHERE ID=2950;
UPDATE `Recipe` SET RecipeName='More Roasted Cauliflower', CookTime='60', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2951;
UPDATE `Recipe` SET RecipeName='More Roasted Lemon Potatoes', CookTime='45', DietType='TBD', IngredientCount='10', ImgURL='2952.jpg' WHERE ID=2952;
UPDATE `Recipe` SET RecipeName='More Roasted Potatoes', CookTime='50', DietType='TBD', IngredientCount='6', ImgURL='2953.jpg' WHERE ID=2953;
UPDATE `Recipe` SET RecipeName='More Stuffed Mushrooms', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='2954.jpg' WHERE ID=2954;
UPDATE `Recipe` SET RecipeName='More Stuffed Peppers', CookTime='30', DietType='TBD', IngredientCount='20', ImgURL='2955.jpg' WHERE ID=2955;
UPDATE `Recipe` SET RecipeName='More Stuffing', CookTime='15', DietType='TBD', IngredientCount='9', ImgURL='2956.jpg' WHERE ID=2956;
UPDATE `Recipe` SET RecipeName='More Taco Bowls', CookTime='10', DietType='TBD', IngredientCount='1', ImgURL='2957.jpg' WHERE ID=2957;
UPDATE `Recipe` SET RecipeName='More Twice Baked Potatoes', CookTime='90', DietType='TBD', IngredientCount='7', ImgURL='2958.jpg' WHERE ID=2958;
UPDATE `Recipe` SET RecipeName='Mountain Mash', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2959;
UPDATE `Recipe` SET RecipeName='Mozzarella Butter Garlic Rolls', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='2960.jpg' WHERE ID=2960;
UPDATE `Recipe` SET RecipeName='Oatmeal Stuffing', CookTime='10', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=2961;
UPDATE `Recipe` SET RecipeName='Olive Salad', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='2962.jpg' WHERE ID=2962;
UPDATE `Recipe` SET RecipeName='Onion Parmesan Potatoes', CookTime='45', DietType='TBD', IngredientCount='7', ImgURL='2963.jpg' WHERE ID=2963;
UPDATE `Recipe` SET RecipeName='Onion Potatoes', CookTime='80', DietType='TBD', IngredientCount='8', ImgURL='2964.jpg' WHERE ID=2964;
UPDATE `Recipe` SET RecipeName='Orange Salad', CookTime='10', DietType='TBD', IngredientCount='7', ImgURL='2965.jpg' WHERE ID=2965;
UPDATE `Recipe` SET RecipeName='Orange Tomato Salad', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='2966.jpg' WHERE ID=2966;
UPDATE `Recipe` SET RecipeName='Outback Potato', CookTime='45', DietType='TBD', IngredientCount='5', ImgURL='2967.jpg' WHERE ID=2967;
UPDATE `Recipe` SET RecipeName='Oven Asparagus', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='2968.jpg' WHERE ID=2968;
UPDATE `Recipe` SET RecipeName='Oven Fried Potatoes', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='2969.jpg' WHERE ID=2969;
UPDATE `Recipe` SET RecipeName='Oven Roasted Potatoes', CookTime='55', DietType='TBD', IngredientCount='6', ImgURL='2970.jpg' WHERE ID=2970;
UPDATE `Recipe` SET RecipeName='Oven Roasted Tomatoes', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='2971.jpg' WHERE ID=2971;
UPDATE `Recipe` SET RecipeName='Paddy Bowls', CookTime='20', DietType='TBD', IngredientCount='1', ImgURL='2972.jpg' WHERE ID=2972;
UPDATE `Recipe` SET RecipeName='Pan Asparagus', CookTime='5', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=2973;
UPDATE `Recipe` SET RecipeName='Paprika Roasted Cauliflower', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='2974.jpg' WHERE ID=2974;
UPDATE `Recipe` SET RecipeName='Parm Cauliflower', CookTime='25', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=2975;
UPDATE `Recipe` SET RecipeName='Parm Mashed', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='2976.jpg' WHERE ID=2976;
UPDATE `Recipe` SET RecipeName='Parmesan Brussels Sprouts', CookTime='40', DietType='TBD', IngredientCount='10', ImgURL='2977.jpg' WHERE ID=2977;
UPDATE `Recipe` SET RecipeName='Parmesan Garlic Knots', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='2978.jpg' WHERE ID=2978;
UPDATE `Recipe` SET RecipeName='Parmesan Roasted Broccoli', CookTime='10', DietType='TBD', IngredientCount='9', ImgURL='2979.jpg' WHERE ID=2979;
UPDATE `Recipe` SET RecipeName='Parmesan Zucchini Spears', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='2980.jpg' WHERE ID=2980;
UPDATE `Recipe` SET RecipeName='Parmeson Scalloped Potatoes', CookTime='70', DietType='TBD', IngredientCount='8', ImgURL='2981.jpg' WHERE ID=2981;
UPDATE `Recipe` SET RecipeName='Parsley Potatoes', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='2982.jpg' WHERE ID=2982;
UPDATE `Recipe` SET RecipeName='Perfect Garlic Bread', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='2983.jpg' WHERE ID=2983;
UPDATE `Recipe` SET RecipeName='Perfect Mashed', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='2984.jpg' WHERE ID=2984;
UPDATE `Recipe` SET RecipeName='PERFECT Mexican Rice', CookTime='40', DietType='TBD', IngredientCount='14', ImgURL='2985.jpg' WHERE ID=2985;
UPDATE `Recipe` SET RecipeName='PERFECT RICE! (Crockpot)', CookTime='120', DietType='TBD', IngredientCount='4', ImgURL='2986.jpg' WHERE ID=2986;
UPDATE `Recipe` SET RecipeName='Popovers', CookTime='40', DietType='TBD', IngredientCount='4', ImgURL='2987.jpg' WHERE ID=2987;
UPDATE `Recipe` SET RecipeName='Potato', CookTime='40', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2988;
UPDATE `Recipe` SET RecipeName='Potato Gratin Muffins', CookTime='30', DietType='TBD', IngredientCount='4', ImgURL='2989.jpg' WHERE ID=2989;
UPDATE `Recipe` SET RecipeName='Potato Onion Mushroom Bake', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='2990.jpg' WHERE ID=2990;
UPDATE `Recipe` SET RecipeName='Potato Pie Crust', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=2991;
UPDATE `Recipe` SET RecipeName='Potato Rosti', CookTime='35', DietType='TBD', IngredientCount='8', ImgURL='2992.jpg' WHERE ID=2992;
UPDATE `Recipe` SET RecipeName='Potato Rounds', CookTime='50', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=2993;
UPDATE `Recipe` SET RecipeName='Potato Waffles', CookTime='35', DietType='TBD', IngredientCount='15', ImgURL='2994.jpg' WHERE ID=2994;
UPDATE `Recipe` SET RecipeName='Pumpkin and Bacon Risotto', CookTime='15', DietType='TBD', IngredientCount='20', ImgURL='2995.jpg' WHERE ID=2995;
UPDATE `Recipe` SET RecipeName='Quick Chicken Fried Rice', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='2996.jpg' WHERE ID=2996;
UPDATE `Recipe` SET RecipeName='Quick Scratch Hash Browns', CookTime='10', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=2997;
UPDATE `Recipe` SET RecipeName='Ramen Salad', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=2998;
UPDATE `Recipe` SET RecipeName='Ranch Corn Salad', CookTime='10', DietType='TBD', IngredientCount='8', ImgURL='2999.jpg' WHERE ID=2999;
UPDATE `Recipe` SET RecipeName='Ranch Potato Skewers', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='3000.jpg' WHERE ID=3000;
UPDATE `Recipe` SET RecipeName='Ranch Veggies', CookTime='30', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=3001;
UPDATE `Recipe` SET RecipeName='Raw Avocado and Brocc Salad', CookTime='5', DietType='TBD', IngredientCount='10', ImgURL='3002.jpg' WHERE ID=3002;
UPDATE `Recipe` SET RecipeName='Red Cabbage Slaw (DIabetic)', CookTime='15', DietType='TBD', IngredientCount='2', ImgURL='' WHERE ID=3003;
UPDATE `Recipe` SET RecipeName='Red Lobster Biscuit Loaf', CookTime='75', DietType='TBD', IngredientCount='12', ImgURL='3004.jpg' WHERE ID=3004;
UPDATE `Recipe` SET RecipeName='Red Roasted Rosemary Potatoes', CookTime='40', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=3005;
UPDATE `Recipe` SET RecipeName='Rice-a-Roni Salad', CookTime='5', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=3006;
UPDATE `Recipe` SET RecipeName='Rice and Veggies', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=3007;
UPDATE `Recipe` SET RecipeName='Rice Curry', CookTime='25', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=3008;
UPDATE `Recipe` SET RecipeName='Rice Medley', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=3009;
UPDATE `Recipe` SET RecipeName='Roasted Asparagus', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='3010.jpg' WHERE ID=3010;
UPDATE `Recipe` SET RecipeName='Roasted Baby Potatoes', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='3011.jpg' WHERE ID=3011;
UPDATE `Recipe` SET RecipeName='Roasted Bacon Cabbage', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='3012.jpg' WHERE ID=3012;
UPDATE `Recipe` SET RecipeName='Roasted Bacon Cheesy Potatoes', CookTime='70', DietType='TBD', IngredientCount='7', ImgURL='3013.jpg' WHERE ID=3013;
UPDATE `Recipe` SET RecipeName='Roasted Balsamic Green Beans', CookTime='40', DietType='TBD', IngredientCount='12', ImgURL='3014.jpg' WHERE ID=3014;
UPDATE `Recipe` SET RecipeName='Roasted Carrots', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='3015.jpg' WHERE ID=3015;
UPDATE `Recipe` SET RecipeName='Roasted Lemon Potatoes', CookTime='40', DietType='TBD', IngredientCount='10', ImgURL='3016.jpg' WHERE ID=3016;
UPDATE `Recipe` SET RecipeName='Roasted Onions', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='3017.jpg' WHERE ID=3017;
UPDATE `Recipe` SET RecipeName='Roasted Parm Potatoes', CookTime='45', DietType='TBD', IngredientCount='8', ImgURL='3018.jpg' WHERE ID=3018;
UPDATE `Recipe` SET RecipeName='Roasted Parmesan Cauliflower', CookTime='50', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=3019;
UPDATE `Recipe` SET RecipeName='Roasted Potato Hearts', CookTime='35', DietType='TBD', IngredientCount='6', ImgURL='3020.jpg' WHERE ID=3020;
UPDATE `Recipe` SET RecipeName='Rosemary Flatbread', CookTime='80', DietType='TBD', IngredientCount='7', ImgURL='3021.jpg' WHERE ID=3021;
UPDATE `Recipe` SET RecipeName='Russian Sauteed Cabbage', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=3022;
UPDATE `Recipe` SET RecipeName='Salsa Rice', CookTime='25', DietType='TBD', IngredientCount='4', ImgURL='3023.jpg' WHERE ID=3023;
UPDATE `Recipe` SET RecipeName='Salt and Vinegar Potatoes', CookTime='45', DietType='TBD', IngredientCount='7', ImgURL='3024.jpg' WHERE ID=3024;
UPDATE `Recipe` SET RecipeName='Sausage Apples', CookTime='15', DietType='TBD', IngredientCount='4', ImgURL='3025.jpg' WHERE ID=3025;
UPDATE `Recipe` SET RecipeName='Sausage Potato Skillet', CookTime='15', DietType='TBD', IngredientCount='11', ImgURL='3026.jpg' WHERE ID=3026;
UPDATE `Recipe` SET RecipeName='Sauteed Mushrooms', CookTime='15', DietType='TBD', IngredientCount='2', ImgURL='3027.jpg' WHERE ID=3027;
UPDATE `Recipe` SET RecipeName='Scalloped Parm Potatoes', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='3028.jpg' WHERE ID=3028;
UPDATE `Recipe` SET RecipeName='Scalloped Potato Casserole', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='3029.jpg' WHERE ID=3029;
UPDATE `Recipe` SET RecipeName='Scalloped Potatoes', CookTime='0', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=3030;
UPDATE `Recipe` SET RecipeName='Scalloped Potatoes Camby', CookTime='90', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=3031;
UPDATE `Recipe` SET RecipeName='Scored Potatoes', CookTime='50', DietType='TBD', IngredientCount='5', ImgURL='3032.jpg' WHERE ID=3032;
UPDATE `Recipe` SET RecipeName='Sheperds Pie Potatoes', CookTime='70', DietType='TBD', IngredientCount='14', ImgURL='3033.jpg' WHERE ID=3033;
UPDATE `Recipe` SET RecipeName='Shrimp and Black Bean Salad', CookTime='20', DietType='TBD', IngredientCount='17', ImgURL='3034.jpg' WHERE ID=3034;
UPDATE `Recipe` SET RecipeName='Simple and Tasty Asparagus', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=3035;
UPDATE `Recipe` SET RecipeName='Simple Green Beans', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='3036.jpg' WHERE ID=3036;
UPDATE `Recipe` SET RecipeName='Simple Potato Salad', CookTime='25', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=3037;
