UPDATE `Recipe` SET RecipeName='Philly Cheese steak Peppers', CookTime='60', DietType='TBD', IngredientCount='8' WHERE ID=1492;
UPDATE `Recipe` SET RecipeName='Philly Cheesesteak Meatloaf', CookTime='45', DietType='TBD', IngredientCount='11' WHERE ID=1493;
UPDATE `Recipe` SET RecipeName='Philly Stuffed Peppers', CookTime='30', DietType='TBD', IngredientCount='12' WHERE ID=1494;
UPDATE `Recipe` SET RecipeName='Pot Roast (Slow Cook)', CookTime='480', DietType='TBD', IngredientCount='4' WHERE ID=1495;
UPDATE `Recipe` SET RecipeName='Potato Burger Casserole', CookTime='90', DietType='TBD', IngredientCount='10' WHERE ID=1496;
UPDATE `Recipe` SET RecipeName='Potato Stuffed Hot Dogs', CookTime='25', DietType='TBD', IngredientCount='6' WHERE ID=1497;
UPDATE `Recipe` SET RecipeName='Pretzel Bun Burgers', CookTime='45', DietType='TBD', IngredientCount='12' WHERE ID=1498;
UPDATE `Recipe` SET RecipeName='Professor Xavier Steak', CookTime='20', DietType='TBD', IngredientCount='10' WHERE ID=1499;
UPDATE `Recipe` SET RecipeName='Quick Cheeseburger Meatloaf', CookTime='50', DietType='TBD', IngredientCount='8' WHERE ID=1500;
UPDATE `Recipe` SET RecipeName='REAL Taco Pie', CookTime='40', DietType='TBD', IngredientCount='10' WHERE ID=1501;
UPDATE `Recipe` SET RecipeName='Really Good Stuffed Peppers', CookTime='60', DietType='TBD', IngredientCount='11' WHERE ID=1502;
UPDATE `Recipe` SET RecipeName='Ribs in the Crockpot', CookTime='480', DietType='TBD', IngredientCount='6' WHERE ID=1503;
UPDATE `Recipe` SET RecipeName='Ritzy Meatloaf', CookTime='60', DietType='TBD', IngredientCount='4' WHERE ID=1504;
UPDATE `Recipe` SET RecipeName='Roast Coke', CookTime='360', DietType='TBD', IngredientCount='3' WHERE ID=1505;
UPDATE `Recipe` SET RecipeName='Salisbury Steak', CookTime='35', DietType='TBD', IngredientCount='17' WHERE ID=1506;
UPDATE `Recipe` SET RecipeName='Shephards Pie', CookTime='50', DietType='TBD', IngredientCount='9' WHERE ID=1507;
UPDATE `Recipe` SET RecipeName='Shredded BBQ Beef', CookTime='360', DietType='TBD', IngredientCount='12' WHERE ID=1508;
UPDATE `Recipe` SET RecipeName='Simple Beef Chimichangas', CookTime='25', DietType='TBD', IngredientCount='10' WHERE ID=1509;
UPDATE `Recipe` SET RecipeName='Simple Sloppy Joes', CookTime='20', DietType='TBD', IngredientCount='8' WHERE ID=1510;
UPDATE `Recipe` SET RecipeName='Simple Stuffed Cabbage', CookTime='35', DietType='TBD', IngredientCount='5' WHERE ID=1511;
UPDATE `Recipe` SET RecipeName='Simple Taco Casserole', CookTime='20', DietType='TBD', IngredientCount='9' WHERE ID=1512;
UPDATE `Recipe` SET RecipeName='Sloppy Joe Casserole with Cornbread', CookTime='45', DietType='TBD', IngredientCount='12' WHERE ID=1513;
UPDATE `Recipe` SET RecipeName='Sloppy Joe Tater Tot Casserole', CookTime='30', DietType='TBD', IngredientCount='15' WHERE ID=1514;
UPDATE `Recipe` SET RecipeName='Slow Pot Roast', CookTime='300', DietType='TBD', IngredientCount='4' WHERE ID=1515;
UPDATE `Recipe` SET RecipeName='Sour Dog Dumps', CookTime='25', DietType='TBD', IngredientCount='3' WHERE ID=1516;
UPDATE `Recipe` SET RecipeName='Spicy Garlic Steak', CookTime='10', DietType='TBD', IngredientCount='6' WHERE ID=1517;
UPDATE `Recipe` SET RecipeName='Spinach Meatballs', CookTime='30', DietType='TBD', IngredientCount='18' WHERE ID=1518;
UPDATE `Recipe` SET RecipeName='Squash Casserole', CookTime='60', DietType='TBD', IngredientCount='12' WHERE ID=1519;
UPDATE `Recipe` SET RecipeName='Steak on a Stick', CookTime='25', DietType='TBD', IngredientCount='18' WHERE ID=1520;
UPDATE `Recipe` SET RecipeName='Steak Roulade', CookTime='60', DietType='TBD', IngredientCount='19' WHERE ID=1521;
UPDATE `Recipe` SET RecipeName='Steak Souvlakis', CookTime='30', DietType='TBD', IngredientCount='21' WHERE ID=1522;
UPDATE `Recipe` SET RecipeName='Steaks with Shallot Butter', CookTime='30', DietType='TBD', IngredientCount='10' WHERE ID=1523;
UPDATE `Recipe` SET RecipeName='Stout Corned Beef', CookTime='180', DietType='TBD', IngredientCount='5' WHERE ID=1524;
UPDATE `Recipe` SET RecipeName='Stroganoff', CookTime='15', DietType='TBD', IngredientCount='13' WHERE ID=1525;
UPDATE `Recipe` SET RecipeName='Stuffed Cabbage Casserole', CookTime='55', DietType='TBD', IngredientCount='16' WHERE ID=1526;
UPDATE `Recipe` SET RecipeName='Stuffed Cheesy Peppers', CookTime='30', DietType='TBD', IngredientCount='11' WHERE ID=1527;
UPDATE `Recipe` SET RecipeName='Stuffed Flank Steak', CookTime='45', DietType='TBD', IngredientCount='15' WHERE ID=1528;
UPDATE `Recipe` SET RecipeName='Stuffed Italian Meatballs', CookTime='30', DietType='TBD', IngredientCount='14' WHERE ID=1529;
UPDATE `Recipe` SET RecipeName='Stuffed Mashed Potato Balls', CookTime='45', DietType='TBD', IngredientCount='18' WHERE ID=1530;
UPDATE `Recipe` SET RecipeName='Stuffed Meat Loaf', CookTime='60', DietType='TBD', IngredientCount='24' WHERE ID=1531;
UPDATE `Recipe` SET RecipeName='Stuffed Pepper Casserole', CookTime='20', DietType='TBD', IngredientCount='12' WHERE ID=1532;
UPDATE `Recipe` SET RecipeName='Stuffed Peppers', CookTime='40', DietType='TBD', IngredientCount='6' WHERE ID=1533;
UPDATE `Recipe` SET RecipeName='Suisse Devil Steak', CookTime='20', DietType='TBD', IngredientCount='9' WHERE ID=1534;
UPDATE `Recipe` SET RecipeName='Swedish Meat Balls', CookTime='25', DietType='TBD', IngredientCount='12' WHERE ID=1535;
UPDATE `Recipe` SET RecipeName='Sweet Glazed Meat Loaf', CookTime='75', DietType='TBD', IngredientCount='12' WHERE ID=1536;
UPDATE `Recipe` SET RecipeName='Taco Bell Crunchwrap', CookTime='20', DietType='TBD', IngredientCount='10' WHERE ID=1537;
UPDATE `Recipe` SET RecipeName='Taco Casserole Bake', CookTime='60', DietType='TBD', IngredientCount='10' WHERE ID=1538;
UPDATE `Recipe` SET RecipeName='Taco Egg Rolls', CookTime='25', DietType='TBD', IngredientCount='5' WHERE ID=1539;
UPDATE `Recipe` SET RecipeName='Taco Hashbrown Casserole', CookTime='40', DietType='TBD', IngredientCount='13' WHERE ID=1540;
UPDATE `Recipe` SET RecipeName='Taco Meat Loaf', CookTime='45', DietType='TBD', IngredientCount='10' WHERE ID=1541;
UPDATE `Recipe` SET RecipeName='Taco Pie', CookTime='30', DietType='TBD', IngredientCount='7' WHERE ID=1542;
UPDATE `Recipe` SET RecipeName='Taco Rolls!', CookTime='20', DietType='TBD', IngredientCount='9' WHERE ID=1543;
UPDATE `Recipe` SET RecipeName='Taco Skillet Pizza', CookTime='45', DietType='TBD', IngredientCount='10' WHERE ID=1544;
UPDATE `Recipe` SET RecipeName='Taco Stuffed Potatoes', CookTime='60', DietType='TBD', IngredientCount='12' WHERE ID=1545;
UPDATE `Recipe` SET RecipeName='Taco Stuffed Shells', CookTime='45', DietType='TBD', IngredientCount='13' WHERE ID=1546;
UPDATE `Recipe` SET RecipeName='Tacos in a Muffin Pan', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1547;
UPDATE `Recipe` SET RecipeName='Tater Tot Beef Casserole', CookTime='50', DietType='TBD', IngredientCount='11' WHERE ID=1548;
UPDATE `Recipe` SET RecipeName='Tater Tot Enchiladas', CookTime='30', DietType='TBD', IngredientCount='13' WHERE ID=1549;
UPDATE `Recipe` SET RecipeName='Tater Tot Tacos', CookTime='40', DietType='TBD', IngredientCount='8' WHERE ID=1550;
UPDATE `Recipe` SET RecipeName='Teriyaki Meatloaf', CookTime='60', DietType='TBD', IngredientCount='6' WHERE ID=1551;
UPDATE `Recipe` SET RecipeName='Tomato Tacos', CookTime='20', DietType='TBD', IngredientCount='15' WHERE ID=1552;
UPDATE `Recipe` SET RecipeName='Totter Casserole', CookTime='30', DietType='TBD', IngredientCount='10' WHERE ID=1553;
UPDATE `Recipe` SET RecipeName='Turkey Shepherds Pie', CookTime='50', DietType='TBD', IngredientCount='12' WHERE ID=1554;
UPDATE `Recipe` SET RecipeName='vidco pudding', CookTime='480', DietType='TBD', IngredientCount='6' WHERE ID=1555;
UPDATE `Recipe` SET RecipeName='Whiskey Steaks', CookTime='20', DietType='TBD', IngredientCount='1' WHERE ID=1556;
UPDATE `Recipe` SET RecipeName='You got a Meat Loaf', CookTime='45', DietType='TBD', IngredientCount='11' WHERE ID=1557;
UPDATE `Recipe` SET RecipeName='Almond Chicken', CookTime='25', DietType='TBD', IngredientCount='12' WHERE ID=1558;
UPDATE `Recipe` SET RecipeName='Amazing Amazing Chicken', CookTime='40', DietType='TBD', IngredientCount='8' WHERE ID=1559;
UPDATE `Recipe` SET RecipeName='Amazing Chicken and Rice Casserole', CookTime='30', DietType='TBD', IngredientCount='0' WHERE ID=1560;
UPDATE `Recipe` SET RecipeName='Amazing Chicken Enchiladas', CookTime='20', DietType='TBD', IngredientCount='8' WHERE ID=1561;
UPDATE `Recipe` SET RecipeName='Amazing Lemon Chicken', CookTime='40', DietType='TBD', IngredientCount='14' WHERE ID=1562;
UPDATE `Recipe` SET RecipeName='Amazing Roasted Chicken', CookTime='120', DietType='TBD', IngredientCount='8' WHERE ID=1563;
UPDATE `Recipe` SET RecipeName='Another Chicken and Biscuit Casserole', CookTime='40', DietType='TBD', IngredientCount='9' WHERE ID=1564;
UPDATE `Recipe` SET RecipeName='Another Chicken Casserole', CookTime='60', DietType='TBD', IngredientCount='11' WHERE ID=1565;
UPDATE `Recipe` SET RecipeName='Another Oven Fried Chicken', CookTime='45', DietType='TBD', IngredientCount='13' WHERE ID=1566;
UPDATE `Recipe` SET RecipeName='Another Parmesan Chicken', CookTime='15', DietType='TBD', IngredientCount='7' WHERE ID=1567;
UPDATE `Recipe` SET RecipeName='Asparagus Stuffed Chicken', CookTime='25', DietType='TBD', IngredientCount='13' WHERE ID=1568;
UPDATE `Recipe` SET RecipeName='Avocado and Tomato Chicken', CookTime='20', DietType='TBD', IngredientCount='0' WHERE ID=1569;
UPDATE `Recipe` SET RecipeName='Avocado Chicken Avocados', CookTime='20', DietType='TBD', IngredientCount='13' WHERE ID=1570;
UPDATE `Recipe` SET RecipeName='Awesome Baked Chicken', CookTime='60', DietType='TBD', IngredientCount='8' WHERE ID=1571;
UPDATE `Recipe` SET RecipeName='Awesome Cashew Chicken', CookTime='30', DietType='TBD', IngredientCount='17' WHERE ID=1572;
UPDATE `Recipe` SET RecipeName='AWESOME Chicken!!', CookTime='70', DietType='TBD', IngredientCount='4' WHERE ID=1573;
UPDATE `Recipe` SET RecipeName='Awesome Chicken Marsala', CookTime='30', DietType='TBD', IngredientCount='11' WHERE ID=1574;
UPDATE `Recipe` SET RecipeName='Awesome Cordon Bleu', CookTime='60', DietType='TBD', IngredientCount='7' WHERE ID=1575;
UPDATE `Recipe` SET RecipeName='Bacon Cheese Chicken', CookTime='35', DietType='TBD', IngredientCount='7' WHERE ID=1576;
UPDATE `Recipe` SET RecipeName='Bacon Cheese Stuffed Chicken', CookTime='20', DietType='TBD', IngredientCount='9' WHERE ID=1577;
UPDATE `Recipe` SET RecipeName='Bacon Cheesy Chicken Skillet', CookTime='45', DietType='TBD', IngredientCount='6' WHERE ID=1578;
UPDATE `Recipe` SET RecipeName='Bacon Chicken Ranch Bites', CookTime='15', DietType='TBD', IngredientCount='10' WHERE ID=1579;
UPDATE `Recipe` SET RecipeName='Bacon Honey Mustard Chicken', CookTime='20', DietType='TBD', IngredientCount='16' WHERE ID=1580;
UPDATE `Recipe` SET RecipeName='Bacon Parmesan Fried Chicken', CookTime='30', DietType='TBD', IngredientCount='12' WHERE ID=1581;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Apple Chicken', CookTime='480', DietType='TBD', IngredientCount='6' WHERE ID=1582;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped BBQ Chicken', CookTime='20', DietType='TBD', IngredientCount='4' WHERE ID=1583;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Cheesy Chicken', CookTime='20', DietType='TBD', IngredientCount='7' WHERE ID=1584;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Cream Cheese Chicken', CookTime='30', DietType='TBD', IngredientCount='5' WHERE ID=1585;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Pesto Chicken', CookTime='60', DietType='TBD', IngredientCount='12' WHERE ID=1586;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Popper Chicken', CookTime='35', DietType='TBD', IngredientCount='9' WHERE ID=1587;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='5' WHERE ID=1588;
UPDATE `Recipe` SET RecipeName='Baked Chicken and Rice', CookTime='50', DietType='TBD', IngredientCount='8' WHERE ID=1589;
UPDATE `Recipe` SET RecipeName='Baked Chicken Chimis', CookTime='25', DietType='TBD', IngredientCount='13' WHERE ID=1590;
UPDATE `Recipe` SET RecipeName='Baked Chicken Flautas', CookTime='25', DietType='TBD', IngredientCount='16' WHERE ID=1591;
UPDATE `Recipe` SET RecipeName='Baked Pesto Chicken', CookTime='30', DietType='TBD', IngredientCount='6' WHERE ID=1592;
UPDATE `Recipe` SET RecipeName='Baked Sweet and Sour Chicken', CookTime='45', DietType='TBD', IngredientCount='11' WHERE ID=1593;
UPDATE `Recipe` SET RecipeName='Baked Turkey Meatballs', CookTime='35', DietType='TBD', IngredientCount='17' WHERE ID=1594;
UPDATE `Recipe` SET RecipeName='Balsamic Chicken and Veggies', CookTime='30', DietType='TBD', IngredientCount='16' WHERE ID=1595;
UPDATE `Recipe` SET RecipeName='Balsamic Chicken Strips', CookTime='15', DietType='TBD', IngredientCount='10' WHERE ID=1596;
UPDATE `Recipe` SET RecipeName='Balsamic Chicken with Mushroom', CookTime='20', DietType='TBD', IngredientCount='7' WHERE ID=1597;
UPDATE `Recipe` SET RecipeName='Bang Bang Chicken', CookTime='45', DietType='TBD', IngredientCount='17' WHERE ID=1598;
UPDATE `Recipe` SET RecipeName='Barbecued Chicken Classic', CookTime='20', DietType='TBD', IngredientCount='6' WHERE ID=1599;
UPDATE `Recipe` SET RecipeName='Basic Cordon Bleu', CookTime='30', DietType='TBD', IngredientCount='14' WHERE ID=1600;
UPDATE `Recipe` SET RecipeName='Basic Roasted Chicken', CookTime='35', DietType='TBD', IngredientCount='8' WHERE ID=1601;
UPDATE `Recipe` SET RecipeName='BBQ Cashew Chicken', CookTime='45', DietType='TBD', IngredientCount='6' WHERE ID=1602;
UPDATE `Recipe` SET RecipeName='BBQ Chicken Enchiladas', CookTime='55', DietType='TBD', IngredientCount='11' WHERE ID=1603;
UPDATE `Recipe` SET RecipeName='Bbq chicken Pizza', CookTime='20', DietType='TBD', IngredientCount='9' WHERE ID=1604;
UPDATE `Recipe` SET RecipeName='BBQ Chicken Sweet Potatoes', CookTime='35', DietType='TBD', IngredientCount='3' WHERE ID=1605;
UPDATE `Recipe` SET RecipeName='BEST Chicken and Rice', CookTime='90', DietType='TBD', IngredientCount='8' WHERE ID=1606;
UPDATE `Recipe` SET RecipeName='Best Chicken Enchilada Casserole', CookTime='50', DietType='TBD', IngredientCount='9' WHERE ID=1607;
UPDATE `Recipe` SET RecipeName='Best Chicken Enchiladas', CookTime='45', DietType='TBD', IngredientCount='14' WHERE ID=1608;
UPDATE `Recipe` SET RecipeName='BEST Chicken Pot Pie', CookTime='75', DietType='TBD', IngredientCount='19' WHERE ID=1609;
UPDATE `Recipe` SET RecipeName='Best Mexican Pizza', CookTime='15', DietType='TBD', IngredientCount='11' WHERE ID=1610;
UPDATE `Recipe` SET RecipeName='BEST Orange Chicken', CookTime='75', DietType='TBD', IngredientCount='15' WHERE ID=1611;
UPDATE `Recipe` SET RecipeName='BEST Sweet and Sour Chicken', CookTime='30', DietType='TBD', IngredientCount='6' WHERE ID=1612;
UPDATE `Recipe` SET RecipeName='Besta Fiesta Chicken Casserole', CookTime='30', DietType='TBD', IngredientCount='11' WHERE ID=1613;
UPDATE `Recipe` SET RecipeName='Best/Easiest Chicken Ever', CookTime='30', DietType='TBD', IngredientCount='4' WHERE ID=1614;
UPDATE `Recipe` SET RecipeName='Better Chicken Enchiladas', CookTime='40', DietType='TBD', IngredientCount='13' WHERE ID=1615;
UPDATE `Recipe` SET RecipeName='Blackend Chicken', CookTime='20', DietType='TBD', IngredientCount='3' WHERE ID=1616;
UPDATE `Recipe` SET RecipeName='Blackened Chicken', CookTime='20', DietType='TBD', IngredientCount='4' WHERE ID=1617;
UPDATE `Recipe` SET RecipeName='Border Turkey', CookTime='25', DietType='TBD', IngredientCount='11' WHERE ID=1618;
UPDATE `Recipe` SET RecipeName='Bourbon Street Chicken', CookTime='480', DietType='TBD', IngredientCount='9' WHERE ID=1619;
UPDATE `Recipe` SET RecipeName='"Br-eta" Chicken', CookTime='40', DietType='TBD', IngredientCount='6' WHERE ID=1620;
UPDATE `Recipe` SET RecipeName='Broccoli Cheese Stuffed Chicken', CookTime='30', DietType='TBD', IngredientCount='8' WHERE ID=1621;
UPDATE `Recipe` SET RecipeName='Broccoli Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='5' WHERE ID=1622;
UPDATE `Recipe` SET RecipeName='Brown Sugar Chicken', CookTime='35', DietType='TBD', IngredientCount='7' WHERE ID=1623;
UPDATE `Recipe` SET RecipeName='Bruschetta Chicken', CookTime='50', DietType='TBD', IngredientCount='16' WHERE ID=1624;
UPDATE `Recipe` SET RecipeName='Bruschetta Chicken Bake', CookTime='30', DietType='TBD', IngredientCount='7' WHERE ID=1625;
UPDATE `Recipe` SET RecipeName='Buffalo BBQ Chicken', CookTime='60', DietType='TBD', IngredientCount='1' WHERE ID=1626;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken and Cauliflower', CookTime='55', DietType='TBD', IngredientCount='16' WHERE ID=1627;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken and Potatoes', CookTime='90', DietType='TBD', IngredientCount='13' WHERE ID=1628;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Casserole', CookTime='60', DietType='TBD', IngredientCount='10' WHERE ID=1629;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Cups', CookTime='20', DietType='TBD', IngredientCount='5' WHERE ID=1630;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Meatballs', CookTime='30', DietType='TBD', IngredientCount='13' WHERE ID=1631;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Ranch Potato Casserole', CookTime='35', DietType='TBD', IngredientCount='13' WHERE ID=1632;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Toast', CookTime='25', DietType='TBD', IngredientCount='15' WHERE ID=1633;
UPDATE `Recipe` SET RecipeName='Bulk Chicken', CookTime='120', DietType='TBD', IngredientCount='3' WHERE ID=1634;
UPDATE `Recipe` SET RecipeName='Cabbage Chicken Salad', CookTime='0', DietType='TBD', IngredientCount='7' WHERE ID=1635;
UPDATE `Recipe` SET RecipeName='Cajun Bourbon Chicken', CookTime='30', DietType='TBD', IngredientCount='16' WHERE ID=1636;
UPDATE `Recipe` SET RecipeName='Cajun Chicken and Rice', CookTime='25', DietType='TBD', IngredientCount='13' WHERE ID=1637;
UPDATE `Recipe` SET RecipeName='Cajun Injected Spicy Turkey', CookTime='300', DietType='TBD', IngredientCount='17' WHERE ID=1638;
UPDATE `Recipe` SET RecipeName='Caprese Stuffed Chicken', CookTime='35', DietType='TBD', IngredientCount='11' WHERE ID=1639;
UPDATE `Recipe` SET RecipeName='Casserole of some kind', CookTime='45', DietType='TBD', IngredientCount='5' WHERE ID=1640;
UPDATE `Recipe` SET RecipeName='Cheddar Ranch Chicken', CookTime='30', DietType='TBD', IngredientCount='12' WHERE ID=1641;
UPDATE `Recipe` SET RecipeName='Cheese and Broccoli Stuffed Chicken', CookTime='30', DietType='TBD', IngredientCount='8' WHERE ID=1642;
UPDATE `Recipe` SET RecipeName='Cheese Stuffed Chicken Marsala', CookTime='45', DietType='TBD', IngredientCount='16' WHERE ID=1643;
UPDATE `Recipe` SET RecipeName='Cheese Stuffed Turkey Meatballs', CookTime='30', DietType='TBD', IngredientCount='17' WHERE ID=1644;
UPDATE `Recipe` SET RecipeName='Cheesy Baked Chicken Rolls', CookTime='35', DietType='TBD', IngredientCount='14' WHERE ID=1645;
UPDATE `Recipe` SET RecipeName='Cheesy Broccoli Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='11' WHERE ID=1646;
UPDATE `Recipe` SET RecipeName='Cheesy Buffalo Chicken Biscuits', CookTime='25', DietType='TBD', IngredientCount='9' WHERE ID=1647;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken and Rice', CookTime='30', DietType='TBD', IngredientCount='11' WHERE ID=1648;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken and Rice Casser', CookTime='30', DietType='TBD', IngredientCount='7' WHERE ID=1649;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Biscuit Bake', CookTime='60', DietType='TBD', IngredientCount='12' WHERE ID=1650;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Casserole', CookTime='60', DietType='TBD', IngredientCount='6' WHERE ID=1651;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Enchiladas', CookTime='25', DietType='TBD', IngredientCount='12' WHERE ID=1652;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Jalapeno Casserole', CookTime='50', DietType='TBD', IngredientCount='6' WHERE ID=1653;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken & Ramen', CookTime='10', DietType='TBD', IngredientCount='5' WHERE ID=1654;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Roll Ups', CookTime='30', DietType='TBD', IngredientCount='5' WHERE ID=1655;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Rolls', CookTime='25', DietType='TBD', IngredientCount='4' WHERE ID=1656;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Stuffed With Broccoli', CookTime='25', DietType='TBD', IngredientCount='12' WHERE ID=1657;
UPDATE `Recipe` SET RecipeName='Cheesy Pepper Chicken', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1658;
UPDATE `Recipe` SET RecipeName='Cheesy Smothered Chicken', CookTime='35', DietType='TBD', IngredientCount='8' WHERE ID=1659;
UPDATE `Recipe` SET RecipeName='Cheesy Spinach Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='9' WHERE ID=1660;
UPDATE `Recipe` SET RecipeName='Cheesy Stuffed Chicken Parmesan', CookTime='20', DietType='TBD', IngredientCount='1' WHERE ID=1661;
UPDATE `Recipe` SET RecipeName='Chic fila nuggets', CookTime='20', DietType='TBD', IngredientCount='19' WHERE ID=1662;
UPDATE `Recipe` SET RecipeName='Chicken Adobo', CookTime='120', DietType='TBD', IngredientCount='8' WHERE ID=1663;
UPDATE `Recipe` SET RecipeName='Chicken Alfredo Rollups', CookTime='45', DietType='TBD', IngredientCount='6' WHERE ID=1664;
UPDATE `Recipe` SET RecipeName='Chicken and Black Bean Casserole', CookTime='40', DietType='TBD', IngredientCount='13' WHERE ID=1665;
UPDATE `Recipe` SET RecipeName='Chicken and Broccoli', CookTime='60', DietType='TBD', IngredientCount='6' WHERE ID=1666;
UPDATE `Recipe` SET RecipeName='Chicken and Broccoli Stir', CookTime='15', DietType='TBD', IngredientCount='8' WHERE ID=1667;
UPDATE `Recipe` SET RecipeName='Chicken and Butter Sauce', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1668;
UPDATE `Recipe` SET RecipeName='Chicken and Cabbage', CookTime='15', DietType='TBD', IngredientCount='7' WHERE ID=1669;
UPDATE `Recipe` SET RecipeName='Chicken and Cranberry Sauce', CookTime='360', DietType='TBD', IngredientCount='3' WHERE ID=1670;
UPDATE `Recipe` SET RecipeName='Chicken and Dumpling Casserole', CookTime='50', DietType='TBD', IngredientCount='8' WHERE ID=1671;
UPDATE `Recipe` SET RecipeName='Chicken and Dumplings', CookTime='40', DietType='TBD', IngredientCount='7' WHERE ID=1672;
UPDATE `Recipe` SET RecipeName='Chicken and Feta Sauce', CookTime='35', DietType='TBD', IngredientCount='11' WHERE ID=1673;
UPDATE `Recipe` SET RecipeName='Chicken and Mango Curry', CookTime='35', DietType='TBD', IngredientCount='8' WHERE ID=1674;
UPDATE `Recipe` SET RecipeName='Chicken and Mushroom Pie', CookTime='50', DietType='TBD', IngredientCount='12' WHERE ID=1675;
UPDATE `Recipe` SET RecipeName='Chicken and Potato Casserole', CookTime='70', DietType='TBD', IngredientCount='9' WHERE ID=1676;
UPDATE `Recipe` SET RecipeName='Chicken and Rice', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1677;
UPDATE `Recipe` SET RecipeName='Chicken and Rice Casserole Bake', CookTime='90', DietType='TBD', IngredientCount='5' WHERE ID=1678;
UPDATE `Recipe` SET RecipeName='Chicken and Stuffing Casserole', CookTime='60', DietType='TBD', IngredientCount='6' WHERE ID=1679;
UPDATE `Recipe` SET RecipeName='Chicken and Veggie Stir Fry', CookTime='20', DietType='TBD', IngredientCount='12' WHERE ID=1680;
UPDATE `Recipe` SET RecipeName='Chicken Biscuit Casserole', CookTime='35', DietType='TBD', IngredientCount='5' WHERE ID=1681;
UPDATE `Recipe` SET RecipeName='Chicken Black Beans and Corn', CookTime='360', DietType='TBD', IngredientCount='7' WHERE ID=1682;
UPDATE `Recipe` SET RecipeName='Chicken Broccoli Pasta Bake', CookTime='45', DietType='TBD', IngredientCount='11' WHERE ID=1683;
UPDATE `Recipe` SET RecipeName='Chicken Broccoli Rice Casserole', CookTime='30', DietType='TBD', IngredientCount='6' WHERE ID=1684;
UPDATE `Recipe` SET RecipeName='Chicken Cordon Bleu', CookTime='30', DietType='TBD', IngredientCount='7' WHERE ID=1685;
UPDATE `Recipe` SET RecipeName='Chicken Enchilada Casserole', CookTime='45', DietType='TBD', IngredientCount='5' WHERE ID=1686;
UPDATE `Recipe` SET RecipeName='Chicken Enchiladas', CookTime='20', DietType='TBD', IngredientCount='4' WHERE ID=1687;
UPDATE `Recipe` SET RecipeName='Chicken Fajitas', CookTime='20', DietType='TBD', IngredientCount='13' WHERE ID=1688;
UPDATE `Recipe` SET RecipeName='Chicken for you', CookTime='25', DietType='TBD', IngredientCount='4' WHERE ID=1689;
UPDATE `Recipe` SET RecipeName='Chicken Fried Chicken', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1690;
UPDATE `Recipe` SET RecipeName='Chicken Fried Rice', CookTime='15', DietType='TBD', IngredientCount='9' WHERE ID=1691;
UPDATE `Recipe` SET RecipeName='Chicken Gloria', CookTime='60', DietType='TBD', IngredientCount='12' WHERE ID=1692;
UPDATE `Recipe` SET RecipeName='Chicken Green Bean Casserole', CookTime='20', DietType='TBD', IngredientCount='10' WHERE ID=1693;
UPDATE `Recipe` SET RecipeName='Chicken Macaroni Casserole', CookTime='30', DietType='TBD', IngredientCount='10' WHERE ID=1694;
UPDATE `Recipe` SET RecipeName='Chicken Meatballs with Cream Sauce', CookTime='40', DietType='TBD', IngredientCount='16' WHERE ID=1695;
UPDATE `Recipe` SET RecipeName='Chicken Mozz', CookTime='25', DietType='TBD', IngredientCount='11' WHERE ID=1696;
UPDATE `Recipe` SET RecipeName='Chicken n Biscuit Casserole', CookTime='45', DietType='TBD', IngredientCount='6' WHERE ID=1697;
UPDATE `Recipe` SET RecipeName='Chicken Parm Meatballs', CookTime='45', DietType='TBD', IngredientCount='15' WHERE ID=1698;
UPDATE `Recipe` SET RecipeName='Chicken Parm Rolls', CookTime='35', DietType='TBD', IngredientCount='7' WHERE ID=1699;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan', CookTime='35', DietType='TBD', IngredientCount='18' WHERE ID=1700;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Casserole', CookTime='30', DietType='TBD', IngredientCount='12' WHERE ID=1701;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Lasagna', CookTime='60', DietType='TBD', IngredientCount='14' WHERE ID=1702;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Meatballs', CookTime='30', DietType='TBD', IngredientCount='14' WHERE ID=1703;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Peppers', CookTime='60', DietType='TBD', IngredientCount='12' WHERE ID=1704;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Roll ups', CookTime='20', DietType='TBD', IngredientCount='2' WHERE ID=1705;
UPDATE `Recipe` SET RecipeName='Chicken Pasta Salad', CookTime='15', DietType='TBD', IngredientCount='4' WHERE ID=1706;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie', CookTime='40', DietType='TBD', IngredientCount='6' WHERE ID=1707;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie Biscuits', CookTime='45', DietType='TBD', IngredientCount='16' WHERE ID=1708;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie Casserole', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1709;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie Crescent', CookTime='30', DietType='TBD', IngredientCount='8' WHERE ID=1710;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie Crumble', CookTime='360', DietType='TBD', IngredientCount='24' WHERE ID=1711;
UPDATE `Recipe` SET RecipeName='Chicken Puffs', CookTime='20', DietType='TBD', IngredientCount='7' WHERE ID=1712;
UPDATE `Recipe` SET RecipeName='Chicken Ranch Tacos', CookTime='20', DietType='TBD', IngredientCount='8' WHERE ID=1713;
UPDATE `Recipe` SET RecipeName='Chicken Rice and Broccoli', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1714;
UPDATE `Recipe` SET RecipeName='Chicken & Rice Dinner', CookTime='25', DietType='TBD', IngredientCount='6' WHERE ID=1715;
UPDATE `Recipe` SET RecipeName='Chicken Salad II', CookTime='15', DietType='TBD', IngredientCount='11' WHERE ID=1716;
UPDATE `Recipe` SET RecipeName='Chicken & Spaghetti', CookTime='35', DietType='TBD', IngredientCount='9' WHERE ID=1717;
UPDATE `Recipe` SET RecipeName='Chicken Stir Fry', CookTime='15', DietType='TBD', IngredientCount='16' WHERE ID=1718;
UPDATE `Recipe` SET RecipeName='Chicken Stroganoff Simple', CookTime='15', DietType='TBD', IngredientCount='8' WHERE ID=1719;
UPDATE `Recipe` SET RecipeName='Chicken Stuffed Peppers', CookTime='45', DietType='TBD', IngredientCount='12' WHERE ID=1720;
UPDATE `Recipe` SET RecipeName='Chicken Teriaki - Easy', CookTime='60', DietType='TBD', IngredientCount='3' WHERE ID=1721;
UPDATE `Recipe` SET RecipeName='Chicken Teriyaki CP', CookTime='240', DietType='TBD', IngredientCount='4' WHERE ID=1722;
UPDATE `Recipe` SET RecipeName='Chicken Tomato Cream Sauce', CookTime='50', DietType='TBD', IngredientCount='13' WHERE ID=1723;
UPDATE `Recipe` SET RecipeName='Chicken Tortilla Pie', CookTime='45', DietType='TBD', IngredientCount='0' WHERE ID=1724;
UPDATE `Recipe` SET RecipeName='Chicken with Creamy Tomato Sauce', CookTime='30', DietType='TBD', IngredientCount='14' WHERE ID=1725;
UPDATE `Recipe` SET RecipeName='Chili Lime Chicken', CookTime='19', DietType='TBD', IngredientCount='6' WHERE ID=1726;
UPDATE `Recipe` SET RecipeName='Chimi Changas!', CookTime='30', DietType='TBD', IngredientCount='12' WHERE ID=1727;
UPDATE `Recipe` SET RecipeName='Cider Bacon Chicken', CookTime='30', DietType='TBD', IngredientCount='7' WHERE ID=1728;
UPDATE `Recipe` SET RecipeName='Coca Cola Chicken', CookTime='65', DietType='TBD', IngredientCount='5' WHERE ID=1729;
UPDATE `Recipe` SET RecipeName='Cola Chicken', CookTime='55', DietType='TBD', IngredientCount='4' WHERE ID=1730;
UPDATE `Recipe` SET RecipeName='Cordon Bleu Casserole', CookTime='70', DietType='TBD', IngredientCount='15' WHERE ID=1731;
UPDATE `Recipe` SET RecipeName='Cordon Bleu Nuggets', CookTime='25', DietType='TBD', IngredientCount='9' WHERE ID=1732;
UPDATE `Recipe` SET RecipeName='Corn Flaked Baked Chicken', CookTime='180', DietType='TBD', IngredientCount='12' WHERE ID=1733;
UPDATE `Recipe` SET RecipeName='Country Pecan Chicken', CookTime='25', DietType='TBD', IngredientCount='5' WHERE ID=1734;
UPDATE `Recipe` SET RecipeName='Cracker Fried Chicken', CookTime='25', DietType='TBD', IngredientCount='10' WHERE ID=1735;
UPDATE `Recipe` SET RecipeName='Cranberry Turkey', CookTime='120', DietType='TBD', IngredientCount='8' WHERE ID=1736;
UPDATE `Recipe` SET RecipeName='Crazy Good Chicken', CookTime='25', DietType='TBD', IngredientCount='9' WHERE ID=1737;
UPDATE `Recipe` SET RecipeName='Crazy Good Chicken Enchiladas', CookTime='20', DietType='TBD', IngredientCount='7' WHERE ID=1738;
UPDATE `Recipe` SET RecipeName='Cream Cheese Chicken', CookTime='45', DietType='TBD', IngredientCount='13' WHERE ID=1739;
UPDATE `Recipe` SET RecipeName='Creamy Bacon Crockpot Chicken', CookTime='495', DietType='TBD', IngredientCount='10' WHERE ID=1740;
UPDATE `Recipe` SET RecipeName='Creamy Cheesy Chicken Enchiladas', CookTime='25', DietType='TBD', IngredientCount='12' WHERE ID=1741;
UPDATE `Recipe` SET RecipeName='Creamy Chicken Bake', CookTime='50', DietType='TBD', IngredientCount='9' WHERE ID=1742;
UPDATE `Recipe` SET RecipeName='Creamy Chicken Enchiladas', CookTime='45', DietType='TBD', IngredientCount='10' WHERE ID=1743;
UPDATE `Recipe` SET RecipeName='Creamy Chicken Jalapeno Enchiladas', CookTime='25', DietType='TBD', IngredientCount='11' WHERE ID=1744;
UPDATE `Recipe` SET RecipeName='Creamy Lemon Chicken', CookTime='25', DietType='TBD', IngredientCount='8' WHERE ID=1745;
UPDATE `Recipe` SET RecipeName='Creamy Parmesan Chicken', CookTime='30', DietType='TBD', IngredientCount='13' WHERE ID=1746;
UPDATE `Recipe` SET RecipeName='Creamy Ritzy Chicken', CookTime='30', DietType='TBD', IngredientCount='7' WHERE ID=1747;
UPDATE `Recipe` SET RecipeName='Creamy Smothered Chicken', CookTime='45', DietType='TBD', IngredientCount='16' WHERE ID=1748;
UPDATE `Recipe` SET RecipeName='Crispy Cheddar Chicken', CookTime='45', DietType='TBD', IngredientCount='11' WHERE ID=1749;
UPDATE `Recipe` SET RecipeName='Crispy Cheesy Chicken Casserole', CookTime='40', DietType='TBD', IngredientCount='8' WHERE ID=1750;
UPDATE `Recipe` SET RecipeName='Crispy Chicken Casserole', CookTime='25', DietType='TBD', IngredientCount='16' WHERE ID=1751;
UPDATE `Recipe` SET RecipeName='Crispy Chicken Wraps', CookTime='15', DietType='TBD', IngredientCount='12' WHERE ID=1752;
UPDATE `Recipe` SET RecipeName='Crispy Garlic Chicken', CookTime='35', DietType='TBD', IngredientCount='8' WHERE ID=1753;
UPDATE `Recipe` SET RecipeName='Crispy Parmesan Chicken', CookTime='10', DietType='TBD', IngredientCount='10' WHERE ID=1754;
UPDATE `Recipe` SET RecipeName='Crispy Ranch Chicken', CookTime='45', DietType='TBD', IngredientCount='4' WHERE ID=1755;
UPDATE `Recipe` SET RecipeName='Crock Pot Bourbon Chicken', CookTime='300', DietType='TBD', IngredientCount='16' WHERE ID=1756;
UPDATE `Recipe` SET RecipeName='Crock Pot Cashew Chicken', CookTime='240', DietType='TBD', IngredientCount='12' WHERE ID=1757;
UPDATE `Recipe` SET RecipeName='Crock Pot Cherry Chicken', CookTime='300', DietType='TBD', IngredientCount='3' WHERE ID=1758;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken Gyros', CookTime='240', DietType='TBD', IngredientCount='14' WHERE ID=1759;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken Philly', CookTime='300', DietType='TBD', IngredientCount='11' WHERE ID=1760;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken Pot Pie', CookTime='480', DietType='TBD', IngredientCount='12' WHERE ID=1761;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken Teriyaki', CookTime='240', DietType='TBD', IngredientCount='11' WHERE ID=1762;
UPDATE `Recipe` SET RecipeName='Crock Pot Enchilada Peppers', CookTime='200', DietType='TBD', IngredientCount='18' WHERE ID=1763;
UPDATE `Recipe` SET RecipeName='Crock Pot Greek Chicken Pitas', CookTime='240', DietType='TBD', IngredientCount='11' WHERE ID=1764;
UPDATE `Recipe` SET RecipeName='Crock Pot Salsa Chicken', CookTime='360', DietType='TBD', IngredientCount='11' WHERE ID=1765;
UPDATE `Recipe` SET RecipeName='Crock Pot Sweet Garlic Chicken', CookTime='240', DietType='TBD', IngredientCount='12' WHERE ID=1766;
UPDATE `Recipe` SET RecipeName='Crock Pot Turkey Breast', CookTime='420', DietType='TBD', IngredientCount='3' WHERE ID=1767;
UPDATE `Recipe` SET RecipeName='Crockpot BBQ Chicken', CookTime='240', DietType='TBD', IngredientCount='7' WHERE ID=1768;
UPDATE `Recipe` SET RecipeName='Crockpot Chicken Tacos', CookTime='420', DietType='TBD', IngredientCount='7' WHERE ID=1769;
UPDATE `Recipe` SET RecipeName='Crunch Chicken', CookTime='30', DietType='TBD', IngredientCount='2' WHERE ID=1770;
UPDATE `Recipe` SET RecipeName='Crunchy Honey Chicken', CookTime='30', DietType='TBD', IngredientCount='17' WHERE ID=1771;
UPDATE `Recipe` SET RecipeName='Crushed Cornflake Chicken', CookTime='40', DietType='TBD', IngredientCount='8' WHERE ID=1772;
UPDATE `Recipe` SET RecipeName='Curried Chicken (Diabetic)', CookTime='30', DietType='TBD', IngredientCount='4' WHERE ID=1773;
UPDATE `Recipe` SET RecipeName='Deep Dish Cordon Blue', CookTime='50', DietType='TBD', IngredientCount='21' WHERE ID=1774;
UPDATE `Recipe` SET RecipeName='Diet Cola Chicken', CookTime='45', DietType='TBD', IngredientCount='2' WHERE ID=1775;
UPDATE `Recipe` SET RecipeName='Diet Salsa Chicken', CookTime='25', DietType='TBD', IngredientCount='3' WHERE ID=1776;
UPDATE `Recipe` SET RecipeName='Dorito Chicken', CookTime='40', DietType='TBD', IngredientCount='7' WHERE ID=1777;
UPDATE `Recipe` SET RecipeName='Dorito Chicken Casserole', CookTime='40', DietType='TBD', IngredientCount='9' WHERE ID=1778;
UPDATE `Recipe` SET RecipeName='Dorito Crusted Chicken', CookTime='35', DietType='TBD', IngredientCount='5' WHERE ID=1779;
UPDATE `Recipe` SET RecipeName='Doritos Taco Bake', CookTime='30', DietType='TBD', IngredientCount='6' WHERE ID=1780;
UPDATE `Recipe` SET RecipeName='Easiest Orange Chicken', CookTime='15', DietType='TBD', IngredientCount='9' WHERE ID=1781;
UPDATE `Recipe` SET RecipeName='Easy Amazing Chicken', CookTime='45', DietType='TBD', IngredientCount='8' WHERE ID=1782;
UPDATE `Recipe` SET RecipeName='Easy Baked Garlic Chicken', CookTime='30', DietType='TBD', IngredientCount='12' WHERE ID=1783;
UPDATE `Recipe` SET RecipeName='Easy Caprese Chicken', CookTime='30', DietType='TBD', IngredientCount='13' WHERE ID=1784;
UPDATE `Recipe` SET RecipeName='Easy Cheesy Chicken Casserole', CookTime='50', DietType='TBD', IngredientCount='4' WHERE ID=1785;
UPDATE `Recipe` SET RecipeName='Easy Chicken and Cabbage', CookTime='60', DietType='TBD', IngredientCount='10' WHERE ID=1786;
UPDATE `Recipe` SET RecipeName='Easy Chicken and Pasta', CookTime='25', DietType='TBD', IngredientCount='6' WHERE ID=1787;
UPDATE `Recipe` SET RecipeName='Easy Chicken Bites with Mustard Sauce', CookTime='35', DietType='TBD', IngredientCount='15' WHERE ID=1788;
UPDATE `Recipe` SET RecipeName='Easy Chicken Broccoli and Rice', CookTime='20', DietType='TBD', IngredientCount='15' WHERE ID=1789;
UPDATE `Recipe` SET RecipeName='Easy Chicken Cordon Bleu', CookTime='45', DietType='TBD', IngredientCount='6' WHERE ID=1790;
UPDATE `Recipe` SET RecipeName='Easy Chicken Pot Pie Biscuits', CookTime='20', DietType='TBD', IngredientCount='14' WHERE ID=1791;
UPDATE `Recipe` SET RecipeName='Easy chicken rice casserole', CookTime='35', DietType='TBD', IngredientCount='5' WHERE ID=1792;
UPDATE `Recipe` SET RecipeName='Easy Chicken Teriyaki', CookTime='30', DietType='TBD', IngredientCount='12' WHERE ID=1793;
UPDATE `Recipe` SET RecipeName='Easy Chicken Tomato Casserole', CookTime='40', DietType='TBD', IngredientCount='12' WHERE ID=1794;
UPDATE `Recipe` SET RecipeName='Easy Chimichangas', CookTime='30', DietType='TBD', IngredientCount='12' WHERE ID=1795;
UPDATE `Recipe` SET RecipeName='Easy Cordon Bleu', CookTime='40', DietType='TBD', IngredientCount='14' WHERE ID=1796;
UPDATE `Recipe` SET RecipeName='Easy Crock Pot Orange Chicken', CookTime='180', DietType='TBD', IngredientCount='10' WHERE ID=1797;
UPDATE `Recipe` SET RecipeName='Easy Easy Easy Chicken', CookTime='340', DietType='TBD', IngredientCount='2' WHERE ID=1798;
UPDATE `Recipe` SET RecipeName='Easy Enchiladas', CookTime='35', DietType='TBD', IngredientCount='11' WHERE ID=1799;
UPDATE `Recipe` SET RecipeName='Easy Italian Stuffed Chicken', CookTime='20', DietType='TBD', IngredientCount='6' WHERE ID=1800;
UPDATE `Recipe` SET RecipeName='Easy Lemon Chicken', CookTime='20', DietType='TBD', IngredientCount='26' WHERE ID=1801;
UPDATE `Recipe` SET RecipeName='Easy Lemon Fried Chicken', CookTime='20', DietType='TBD', IngredientCount='9' WHERE ID=1802;
UPDATE `Recipe` SET RecipeName='Easy Margarita Chicken', CookTime='30', DietType='TBD', IngredientCount='0' WHERE ID=1803;
UPDATE `Recipe` SET RecipeName='Easy Mexican Chicken Casserole', CookTime='20', DietType='TBD', IngredientCount='6' WHERE ID=1804;
UPDATE `Recipe` SET RecipeName='Easy Pan Roasted Chicken', CookTime='30', DietType='TBD', IngredientCount='10' WHERE ID=1805;
UPDATE `Recipe` SET RecipeName='Easy Parmesan Chicken', CookTime='45', DietType='TBD', IngredientCount='8' WHERE ID=1806;
UPDATE `Recipe` SET RecipeName='Easy Roast Chicken', CookTime='50', DietType='TBD', IngredientCount='14' WHERE ID=1807;
UPDATE `Recipe` SET RecipeName='Easy Sweet Chicken', CookTime='45', DietType='TBD', IngredientCount='5' WHERE ID=1808;
UPDATE `Recipe` SET RecipeName='Easy Teriyaki Chicken', CookTime='45', DietType='TBD', IngredientCount='6' WHERE ID=1809;
UPDATE `Recipe` SET RecipeName='Enchilada Lasanga', CookTime='40', DietType='TBD', IngredientCount='11' WHERE ID=1810;
UPDATE `Recipe` SET RecipeName='Enchilada Stuffed Peppers', CookTime='50', DietType='TBD', IngredientCount='18' WHERE ID=1811;
UPDATE `Recipe` SET RecipeName='Fajita Bubble Bake', CookTime='20', DietType='TBD', IngredientCount='9' WHERE ID=1812;
UPDATE `Recipe` SET RecipeName='Fajita Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='17' WHERE ID=1813;
UPDATE `Recipe` SET RecipeName='Fiesta Chicken and Rice', CookTime='20', DietType='TBD', IngredientCount='14' WHERE ID=1814;
UPDATE `Recipe` SET RecipeName='Garlic Chicken II', CookTime='55', DietType='TBD', IngredientCount='9' WHERE ID=1815;
UPDATE `Recipe` SET RecipeName='Garlic Lime Chicken', CookTime='20', DietType='TBD', IngredientCount='14' WHERE ID=1816;
UPDATE `Recipe` SET RecipeName='General Tso Chicken', CookTime='25', DietType='TBD', IngredientCount='12' WHERE ID=1817;
UPDATE `Recipe` SET RecipeName='Ginger Garlic Stir Fry', CookTime='20', DietType='TBD', IngredientCount='16' WHERE ID=1818;
UPDATE `Recipe` SET RecipeName='Glazed Chicken', CookTime='30', DietType='TBD', IngredientCount='8' WHERE ID=1819;
UPDATE `Recipe` SET RecipeName='Goodness Stuffed Chicken', CookTime='35', DietType='TBD', IngredientCount='14' WHERE ID=1820;
UPDATE `Recipe` SET RecipeName='Greek Chicken Skewers', CookTime='50', DietType='TBD', IngredientCount='14' WHERE ID=1821;
UPDATE `Recipe` SET RecipeName='Greek Marinated Chicken', CookTime='60', DietType='TBD', IngredientCount='12' WHERE ID=1822;
UPDATE `Recipe` SET RecipeName='Green Chili Chicken Lasagna', CookTime='40', DietType='TBD', IngredientCount='10' WHERE ID=1823;
UPDATE `Recipe` SET RecipeName='Grilled Cilantro Chicken', CookTime='40', DietType='TBD', IngredientCount='9' WHERE ID=1824;
UPDATE `Recipe` SET RecipeName='Grilled Rosemary Chicken', CookTime='30', DietType='TBD', IngredientCount='8' WHERE ID=1825;
UPDATE `Recipe` SET RecipeName='Guacamole Chicken', CookTime='45', DietType='TBD', IngredientCount='14' WHERE ID=1826;
UPDATE `Recipe` SET RecipeName='Hawaiian Chicken', CookTime='35', DietType='TBD', IngredientCount='6' WHERE ID=1827;
UPDATE `Recipe` SET RecipeName='Hawaiian Chicken Bake', CookTime='80', DietType='TBD', IngredientCount='11' WHERE ID=1828;
UPDATE `Recipe` SET RecipeName='Healthy Chicken Bake', CookTime='45', DietType='TBD', IngredientCount='13' WHERE ID=1829;
UPDATE `Recipe` SET RecipeName='Homemade Alfredo Sauce', CookTime='0', DietType='TBD', IngredientCount='8' WHERE ID=1830;
UPDATE `Recipe` SET RecipeName='Homemade Sausage', CookTime='15', DietType='TBD', IngredientCount='9' WHERE ID=1831;
UPDATE `Recipe` SET RecipeName='Honey Beer Chicken', CookTime='45', DietType='TBD', IngredientCount='11' WHERE ID=1832;
UPDATE `Recipe` SET RecipeName='Honey Dijon Chicken', CookTime='20', DietType='TBD', IngredientCount='8' WHERE ID=1833;
UPDATE `Recipe` SET RecipeName='Honey Fried Chicken', CookTime='20', DietType='TBD', IngredientCount='11' WHERE ID=1834;
UPDATE `Recipe` SET RecipeName='Honey Garlic Chicken', CookTime='360', DietType='TBD', IngredientCount='6' WHERE ID=1835;
UPDATE `Recipe` SET RecipeName='Honey Garlic Stir Fry', CookTime='30', DietType='TBD', IngredientCount='13' WHERE ID=1836;
UPDATE `Recipe` SET RecipeName='Honey Graham Cracker Chicken', CookTime='25', DietType='TBD', IngredientCount='4' WHERE ID=1837;
UPDATE `Recipe` SET RecipeName='Honey Mustard Chicken', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1838;
UPDATE `Recipe` SET RecipeName='Honey Mustard Garlic Chicken', CookTime='10', DietType='TBD', IngredientCount='10' WHERE ID=1839;
UPDATE `Recipe` SET RecipeName='Honey Mustard Grilled Chicken', CookTime='60', DietType='TBD', IngredientCount='9' WHERE ID=1840;
UPDATE `Recipe` SET RecipeName='Honey Sesame Chicken', CookTime='240', DietType='TBD', IngredientCount='15' WHERE ID=1841;
UPDATE `Recipe` SET RecipeName='Honey Soy Chicken', CookTime='50', DietType='TBD', IngredientCount='7' WHERE ID=1842;
UPDATE `Recipe` SET RecipeName='Honey Sriracha Tenders', CookTime='25', DietType='TBD', IngredientCount='15' WHERE ID=1843;
UPDATE `Recipe` SET RecipeName='Horseradish Chicken', CookTime='25', DietType='TBD', IngredientCount='7' WHERE ID=1844;
UPDATE `Recipe` SET RecipeName='Hummus Chicken', CookTime='35', DietType='TBD', IngredientCount='12' WHERE ID=1845;
UPDATE `Recipe` SET RecipeName='Incredible Lemon Chicken', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1846;
UPDATE `Recipe` SET RecipeName='Italian Chicken Meatloaf', CookTime='75', DietType='TBD', IngredientCount='5' WHERE ID=1847;
UPDATE `Recipe` SET RecipeName='Italian Chicken Parm', CookTime='15', DietType='TBD', IngredientCount='2' WHERE ID=1848;
UPDATE `Recipe` SET RecipeName='Italian Herb Chicken Rollups', CookTime='5', DietType='TBD', IngredientCount='5' WHERE ID=1849;
UPDATE `Recipe` SET RecipeName='Jalapeno Popper Baked Chicken', CookTime='35', DietType='TBD', IngredientCount='12' WHERE ID=1850;
UPDATE `Recipe` SET RecipeName='Jalapeno Popper Chicken', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1851;
UPDATE `Recipe` SET RecipeName='Jalapeno Stuffed BBQ Chicken', CookTime='45', DietType='TBD', IngredientCount='7' WHERE ID=1852;
UPDATE `Recipe` SET RecipeName='Jalapeno Stuffed Chicken', CookTime='30', DietType='TBD', IngredientCount='6' WHERE ID=1853;
UPDATE `Recipe` SET RecipeName='Jimmys Cran-Orange Chkn', CookTime='400', DietType='TBD', IngredientCount='8' WHERE ID=1854;
UPDATE `Recipe` SET RecipeName='Juicy Cheddar Garlic Chicken', CookTime='45', DietType='TBD', IngredientCount='9' WHERE ID=1855;
UPDATE `Recipe` SET RecipeName='Kettle Chip Crusted Chicken', CookTime='40', DietType='TBD', IngredientCount='5' WHERE ID=1856;
UPDATE `Recipe` SET RecipeName='Key West Chicken', CookTime='45', DietType='TBD', IngredientCount='9' WHERE ID=1857;
UPDATE `Recipe` SET RecipeName='KFC Baked Fried Chicken', CookTime='35', DietType='TBD', IngredientCount='6' WHERE ID=1858;
UPDATE `Recipe` SET RecipeName='Korean Chicken', CookTime='25', DietType='TBD', IngredientCount='6' WHERE ID=1859;
UPDATE `Recipe` SET RecipeName='Kung Pao Chicken', CookTime='60', DietType='TBD', IngredientCount='17' WHERE ID=1860;
UPDATE `Recipe` SET RecipeName='KY Grilled Chicken', CookTime='30', DietType='TBD', IngredientCount='6' WHERE ID=1861;
UPDATE `Recipe` SET RecipeName='Leftover Crescent Wreath', CookTime='30', DietType='TBD', IngredientCount='7' WHERE ID=1862;
UPDATE `Recipe` SET RecipeName='Leftover Turkey Bake', CookTime='20', DietType='TBD', IngredientCount='6' WHERE ID=1863;
UPDATE `Recipe` SET RecipeName='Lemon Chicken Kabobs', CookTime='80', DietType='TBD', IngredientCount='14' WHERE ID=1864;
UPDATE `Recipe` SET RecipeName='Lemon Chicken w Artichokes', CookTime='20', DietType='TBD', IngredientCount='10' WHERE ID=1865;
UPDATE `Recipe` SET RecipeName='Lemonade Chicken (Crock Pot)', CookTime='240', DietType='TBD', IngredientCount='8' WHERE ID=1866;
UPDATE `Recipe` SET RecipeName='Loaded Chicken and Potatoes', CookTime='60', DietType='TBD', IngredientCount='3' WHERE ID=1867;
UPDATE `Recipe` SET RecipeName='Loaded Chicken Casserole', CookTime='35', DietType='TBD', IngredientCount='16' WHERE ID=1868;
UPDATE `Recipe` SET RecipeName='Low-Carb Fajitas', CookTime='10', DietType='TBD', IngredientCount='8' WHERE ID=1869;
UPDATE `Recipe` SET RecipeName='Low Carb Popper Chicken', CookTime='30', DietType='TBD', IngredientCount='12' WHERE ID=1870;
UPDATE `Recipe` SET RecipeName='Low Carb Stuffed Chicken Peppers', CookTime='45', DietType='TBD', IngredientCount='12' WHERE ID=1871;
UPDATE `Recipe` SET RecipeName='Mayoless Chicken Salad', CookTime='15', DietType='TBD', IngredientCount='7' WHERE ID=1872;
UPDATE `Recipe` SET RecipeName='Melt in your Mouth Chicken', CookTime='45', DietType='TBD', IngredientCount='9' WHERE ID=1873;
UPDATE `Recipe` SET RecipeName='Melty Mushroom Stuffed Chicken', CookTime='75', DietType='TBD', IngredientCount='12' WHERE ID=1874;
UPDATE `Recipe` SET RecipeName='Mexican Chicken', CookTime='20', DietType='TBD', IngredientCount='5' WHERE ID=1875;
UPDATE `Recipe` SET RecipeName='Mini Pot Pie Muffins', CookTime='20', DietType='TBD', IngredientCount='5' WHERE ID=1876;
UPDATE `Recipe` SET RecipeName='Monterrey Chicken', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1877;
UPDATE `Recipe` SET RecipeName='More Bacon Wrapped Chicken', CookTime='20', DietType='TBD', IngredientCount='6' WHERE ID=1878;
UPDATE `Recipe` SET RecipeName='More Buffalo Chicken Casserole', CookTime='30', DietType='TBD', IngredientCount='17' WHERE ID=1879;
UPDATE `Recipe` SET RecipeName='More Buffalo Chicken Meatballs', CookTime='20', DietType='TBD', IngredientCount='10' WHERE ID=1880;
UPDATE `Recipe` SET RecipeName='More Chicken Fried Steak', CookTime='35', DietType='TBD', IngredientCount='12' WHERE ID=1881;
UPDATE `Recipe` SET RecipeName='More Chicken Rolls', CookTime='20', DietType='TBD', IngredientCount='7' WHERE ID=1882;
UPDATE `Recipe` SET RecipeName='More Cordon Bleu Casserole', CookTime='35', DietType='TBD', IngredientCount='7' WHERE ID=1883;
UPDATE `Recipe` SET RecipeName='More Creamy Lemon Chicken', CookTime='30', DietType='TBD', IngredientCount='15' WHERE ID=1884;
UPDATE `Recipe` SET RecipeName='More Dorito Casserole', CookTime='30', DietType='TBD', IngredientCount='8' WHERE ID=1885;
UPDATE `Recipe` SET RecipeName='More Dorito Chicken Casserole', CookTime='30', DietType='TBD', IngredientCount='3' WHERE ID=1886;
UPDATE `Recipe` SET RecipeName='More Honey Garlic Chicken', CookTime='30', DietType='TBD', IngredientCount='17' WHERE ID=1887;
UPDATE `Recipe` SET RecipeName='More Oven Fried Chicken', CookTime='20', DietType='TBD', IngredientCount='12' WHERE ID=1888;
UPDATE `Recipe` SET RecipeName='More Popper Stuffed Chicken', CookTime='25', DietType='TBD', IngredientCount='7' WHERE ID=1889;
UPDATE `Recipe` SET RecipeName='More Salsa Chicken', CookTime='50', DietType='TBD', IngredientCount='6' WHERE ID=1890;
UPDATE `Recipe` SET RecipeName='More Simple Chicken', CookTime='50', DietType='TBD', IngredientCount='2' WHERE ID=1891;
UPDATE `Recipe` SET RecipeName='More Sweet and Sour Chicken', CookTime='60', DietType='TBD', IngredientCount='12' WHERE ID=1892;
UPDATE `Recipe` SET RecipeName='More White Chicken Enchiladas', CookTime='35', DietType='TBD', IngredientCount='9' WHERE ID=1893;
UPDATE `Recipe` SET RecipeName='More Wrapped Stuffed Chicken', CookTime='45', DietType='TBD', IngredientCount='9' WHERE ID=1894;
UPDATE `Recipe` SET RecipeName='Moussaka', CookTime='60', DietType='TBD', IngredientCount='10' WHERE ID=1895;
UPDATE `Recipe` SET RecipeName='Mozzarella Chicken', CookTime='35', DietType='TBD', IngredientCount='10' WHERE ID=1896;
UPDATE `Recipe` SET RecipeName='One Pan Chicken Carbonara', CookTime='30', DietType='TBD', IngredientCount='16' WHERE ID=1897;
UPDATE `Recipe` SET RecipeName='One Pan Chicken Dinner', CookTime='60', DietType='TBD', IngredientCount='6' WHERE ID=1898;
UPDATE `Recipe` SET RecipeName='One Pan Chicken Squash and Brussels Sprouts', CookTime='35', DietType='TBD', IngredientCount='19' WHERE ID=1899;
UPDATE `Recipe` SET RecipeName='One Pan Greek Chicken', CookTime='25', DietType='TBD', IngredientCount='15' WHERE ID=1900;
UPDATE `Recipe` SET RecipeName='One Pot Chicken and Potatoes', CookTime='40', DietType='TBD', IngredientCount='10' WHERE ID=1901;
UPDATE `Recipe` SET RecipeName='One Skillet Italian Chicken', CookTime='15', DietType='TBD', IngredientCount='12' WHERE ID=1902;
UPDATE `Recipe` SET RecipeName='Open Faced Pot Pie', CookTime='30', DietType='TBD', IngredientCount='15' WHERE ID=1903;
UPDATE `Recipe` SET RecipeName='Orange Chicken Stir Fry', CookTime='30', DietType='TBD', IngredientCount='13' WHERE ID=1904;
UPDATE `Recipe` SET RecipeName='Orange Stir Fry', CookTime='30', DietType='TBD', IngredientCount='13' WHERE ID=1905;
UPDATE `Recipe` SET RecipeName='Oven Baked Fajitas', CookTime='30', DietType='TBD', IngredientCount='17' WHERE ID=1906;
UPDATE `Recipe` SET RecipeName='Oven Fried Chicken', CookTime='240', DietType='TBD', IngredientCount='11' WHERE ID=1907;
UPDATE `Recipe` SET RecipeName='Oven Fried Chicken (Diabetic)', CookTime='60', DietType='TBD', IngredientCount='5' WHERE ID=1908;
UPDATE `Recipe` SET RecipeName='Parmesan Paprika Chicken', CookTime='75', DietType='TBD', IngredientCount='7' WHERE ID=1909;
UPDATE `Recipe` SET RecipeName='Peachy Chicken', CookTime='30', DietType='TBD', IngredientCount='5' WHERE ID=1910;
UPDATE `Recipe` SET RecipeName='Peppered chicken', CookTime='45', DietType='TBD', IngredientCount='11' WHERE ID=1911;
UPDATE `Recipe` SET RecipeName='Pepperoni Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='12' WHERE ID=1912;
UPDATE `Recipe` SET RecipeName='Pineapple BBQ Chicken', CookTime='60', DietType='TBD', IngredientCount='9' WHERE ID=1913;
UPDATE `Recipe` SET RecipeName='Pizza Chicken', CookTime='30', DietType='TBD', IngredientCount='15' WHERE ID=1914;
UPDATE `Recipe` SET RecipeName='Pollo Fajitas', CookTime='20', DietType='TBD', IngredientCount='16' WHERE ID=1915;
UPDATE `Recipe` SET RecipeName='Poppy seed chicken', CookTime='40', DietType='TBD', IngredientCount='9' WHERE ID=1916;
UPDATE `Recipe` SET RecipeName='Potato Chicken Casserole', CookTime='90', DietType='TBD', IngredientCount='11' WHERE ID=1917;
UPDATE `Recipe` SET RecipeName='Quick Cashew Chicken', CookTime='20', DietType='TBD', IngredientCount='19' WHERE ID=1918;
UPDATE `Recipe` SET RecipeName='Quick Chick', CookTime='45', DietType='TBD', IngredientCount='5' WHERE ID=1919;
UPDATE `Recipe` SET RecipeName='Quick Chicken', CookTime='45', DietType='TBD', IngredientCount='9' WHERE ID=1920;
UPDATE `Recipe` SET RecipeName='Quick Chicken and Dumplins', CookTime='0', DietType='TBD', IngredientCount='9' WHERE ID=1921;
UPDATE `Recipe` SET RecipeName='Quick Chicken Marsala', CookTime='20', DietType='TBD', IngredientCount='4' WHERE ID=1922;
UPDATE `Recipe` SET RecipeName='Quick Mex Chicken', CookTime='50', DietType='TBD', IngredientCount='5' WHERE ID=1923;
UPDATE `Recipe` SET RecipeName='Ranch Chicken', CookTime='50', DietType='TBD', IngredientCount='3' WHERE ID=1924;
UPDATE `Recipe` SET RecipeName='Really Really Good Chicken', CookTime='25', DietType='TBD', IngredientCount='9' WHERE ID=1925;
UPDATE `Recipe` SET RecipeName='Ritz cracker chicken', CookTime='45', DietType='TBD', IngredientCount='3' WHERE ID=1926;
UPDATE `Recipe` SET RecipeName='Ritzy Chicken Roll Ups', CookTime='35', DietType='TBD', IngredientCount='14' WHERE ID=1927;
UPDATE `Recipe` SET RecipeName='Ritzy Fried Chicken', CookTime='15', DietType='TBD', IngredientCount='10' WHERE ID=1928;
UPDATE `Recipe` SET RecipeName='Rosemary Ranch Chicken', CookTime='300', DietType='TBD', IngredientCount='14' WHERE ID=1929;
UPDATE `Recipe` SET RecipeName='Rosemary Tomato Chicken Bake', CookTime='45', DietType='TBD', IngredientCount='10' WHERE ID=1930;
UPDATE `Recipe` SET RecipeName='salsa chicken with yellow rice', CookTime='40', DietType='TBD', IngredientCount='3' WHERE ID=1931;
UPDATE `Recipe` SET RecipeName='Santa Fe Stuffed Peppers', CookTime='60', DietType='TBD', IngredientCount='14' WHERE ID=1932;
UPDATE `Recipe` SET RecipeName='Scratch Chicken Teriyaki', CookTime='20', DietType='TBD', IngredientCount='13' WHERE ID=1933;
UPDATE `Recipe` SET RecipeName='Sesame Chicken', CookTime='60', DietType='TBD', IngredientCount='14' WHERE ID=1934;
UPDATE `Recipe` SET RecipeName='Sherry Chicken Curry', CookTime='45', DietType='TBD', IngredientCount='17' WHERE ID=1935;
UPDATE `Recipe` SET RecipeName='Simple Baked Chicken Recipe', CookTime='20', DietType='TBD', IngredientCount='5' WHERE ID=1936;
UPDATE `Recipe` SET RecipeName='Simple Chicken Wrap', CookTime='15', DietType='TBD', IngredientCount='6' WHERE ID=1937;
UPDATE `Recipe` SET RecipeName='Simple Lemon Chicken', CookTime='300', DietType='TBD', IngredientCount='6' WHERE ID=1938;
UPDATE `Recipe` SET RecipeName='Simple Mexican Chicken', CookTime='10', DietType='TBD', IngredientCount='3' WHERE ID=1939;
UPDATE `Recipe` SET RecipeName='Simple Orange Chicken', CookTime='30', DietType='TBD', IngredientCount='9' WHERE ID=1940;
UPDATE `Recipe` SET RecipeName='Simple Sesame Chicken', CookTime='60', DietType='TBD', IngredientCount='8' WHERE ID=1941;
UPDATE `Recipe` SET RecipeName='Simple Sweet and Sour', CookTime='45', DietType='TBD', IngredientCount='13' WHERE ID=1942;
UPDATE `Recipe` SET RecipeName='Simple Sweet Bacon Chicken', CookTime='35', DietType='TBD', IngredientCount='6' WHERE ID=1943;
UPDATE `Recipe` SET RecipeName='Simple Vinegar Chicken', CookTime='60', DietType='TBD', IngredientCount='5' WHERE ID=1944;
UPDATE `Recipe` SET RecipeName='Skinny Sweet Chicken', CookTime='25', DietType='TBD', IngredientCount='9' WHERE ID=1945;
UPDATE `Recipe` SET RecipeName='Smothered Chicken and Veggies', CookTime='20', DietType='TBD', IngredientCount='14' WHERE ID=1946;
UPDATE `Recipe` SET RecipeName='Smothered Enchiladas', CookTime='40', DietType='TBD', IngredientCount='7' WHERE ID=1947;
UPDATE `Recipe` SET RecipeName='Spicy Chicken Bombs', CookTime='35', DietType='TBD', IngredientCount='7' WHERE ID=1948;
UPDATE `Recipe` SET RecipeName='Spicy Chicken Breasts', CookTime='25', DietType='TBD', IngredientCount='6' WHERE ID=1949;
UPDATE `Recipe` SET RecipeName='Spicy Chicken Empanadas', CookTime='50', DietType='TBD', IngredientCount='0' WHERE ID=1950;
UPDATE `Recipe` SET RecipeName='Spinach and Cheese Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='8' WHERE ID=1951;
UPDATE `Recipe` SET RecipeName='Spinach Dip Stuffed Chicken', CookTime='30', DietType='TBD', IngredientCount='15' WHERE ID=1952;
UPDATE `Recipe` SET RecipeName='Stuffed Buffalo Chicken', CookTime='35', DietType='TBD', IngredientCount='4' WHERE ID=1953;
UPDATE `Recipe` SET RecipeName='stuffed chicken (College Style', CookTime='45', DietType='TBD', IngredientCount='4' WHERE ID=1954;
UPDATE `Recipe` SET RecipeName='Stuffed Chicken Marsala', CookTime='30', DietType='TBD', IngredientCount='17' WHERE ID=1955;
UPDATE `Recipe` SET RecipeName='Stuffed Chicken Parmesan', CookTime='30', DietType='TBD', IngredientCount='17' WHERE ID=1956;
UPDATE `Recipe` SET RecipeName='Stuffed Greek Chicken', CookTime='20', DietType='TBD', IngredientCount='9' WHERE ID=1957;
UPDATE `Recipe` SET RecipeName='Stuffed Lemon Chicken', CookTime='50', DietType='TBD', IngredientCount='13' WHERE ID=1958;
UPDATE `Recipe` SET RecipeName='Stuffed Wrapped Chicken', CookTime='40', DietType='TBD', IngredientCount='7' WHERE ID=1959;
UPDATE `Recipe` SET RecipeName='Super Chicken Casserole', CookTime='35', DietType='TBD', IngredientCount='6' WHERE ID=1960;
UPDATE `Recipe` SET RecipeName='Super Easy Stir Fry', CookTime='15', DietType='TBD', IngredientCount='22' WHERE ID=1961;
UPDATE `Recipe` SET RecipeName='Sweet and Spicy Balsamic Chicken', CookTime='20', DietType='TBD', IngredientCount='7' WHERE ID=1962;
UPDATE `Recipe` SET RecipeName='Sweet Baked Chicken', CookTime='25', DietType='TBD', IngredientCount='7' WHERE ID=1963;
UPDATE `Recipe` SET RecipeName='Sweet Garlic Chicken', CookTime='30', DietType='TBD', IngredientCount='7' WHERE ID=1964;
UPDATE `Recipe` SET RecipeName='Sweet Italian Chicken', CookTime='20', DietType='TBD', IngredientCount='3' WHERE ID=1965;
UPDATE `Recipe` SET RecipeName='Sweet Maple Chicken', CookTime='40', DietType='TBD', IngredientCount='9' WHERE ID=1966;
UPDATE `Recipe` SET RecipeName='Sweet Pineapple Chicken', CookTime='360', DietType='TBD', IngredientCount='5' WHERE ID=1967;
UPDATE `Recipe` SET RecipeName='Sweet Spicy Chicken Stir Fry', CookTime='30', DietType='TBD', IngredientCount='11' WHERE ID=1968;
UPDATE `Recipe` SET RecipeName='Sweet Spicy Glazed Chicken', CookTime='20', DietType='TBD', IngredientCount='5' WHERE ID=1969;
UPDATE `Recipe` SET RecipeName='Swiss Chicken Bake', CookTime='60', DietType='TBD', IngredientCount='10' WHERE ID=1970;
UPDATE `Recipe` SET RecipeName='Taco Bell Quesadilla', CookTime='25', DietType='TBD', IngredientCount='14' WHERE ID=1971;
UPDATE `Recipe` SET RecipeName='Tangy Grilled Chicken', CookTime='20', DietType='TBD', IngredientCount='9' WHERE ID=1972;
UPDATE `Recipe` SET RecipeName='Teriyaki Bowl', CookTime='20', DietType='TBD', IngredientCount='4' WHERE ID=1973;
UPDATE `Recipe` SET RecipeName='Teriyaki Chicken', CookTime='180', DietType='TBD', IngredientCount='5' WHERE ID=1974;
UPDATE `Recipe` SET RecipeName='Teriyaki Chicken by ME', CookTime='20', DietType='TBD', IngredientCount='12' WHERE ID=1975;
UPDATE `Recipe` SET RecipeName='Teriyaki Chicken Crock Pot', CookTime='240', DietType='TBD', IngredientCount='6' WHERE ID=1976;
