UPDATE `Recipe` SET RecipeName='Milkshake - Simple', CookTime='2', DietType='TBD', IngredientCount='2', ImgURL='' WHERE ID=1317;
UPDATE `Recipe` SET RecipeName='My Favorite Eggnog', CookTime='5', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=1318;
UPDATE `Recipe` SET RecipeName='No Fat Smoothie', CookTime='5', DietType='TBD', IngredientCount='3', ImgURL='1319.jpg' WHERE ID=1319;
UPDATE `Recipe` SET RecipeName='Oreo and Banana Milkshake', CookTime='10', DietType='TBD', IngredientCount='3', ImgURL='1320.jpg' WHERE ID=1320;
UPDATE `Recipe` SET RecipeName='Peach Slush', CookTime='5', DietType='TBD', IngredientCount='3', ImgURL='1321.jpg' WHERE ID=1321;
UPDATE `Recipe` SET RecipeName='Pinana Smoothie', CookTime='5', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1322;
UPDATE `Recipe` SET RecipeName='Pineapple Upside Down Shot', CookTime='120', DietType='TBD', IngredientCount='6', ImgURL='1323.jpg' WHERE ID=1323;
UPDATE `Recipe` SET RecipeName='Pumpkin Spice Frappe', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='1324.jpg' WHERE ID=1324;
UPDATE `Recipe` SET RecipeName='Shamrock Shake', CookTime='10', DietType='TBD', IngredientCount='4', ImgURL='1325.jpg' WHERE ID=1325;
UPDATE `Recipe` SET RecipeName='Simple Bloody Mary Mix', CookTime='10', DietType='TBD', IngredientCount='8', ImgURL='1326.jpg' WHERE ID=1326;
UPDATE `Recipe` SET RecipeName='Slush Punch', CookTime='480', DietType='TBD', IngredientCount='10', ImgURL='1327.jpg' WHERE ID=1327;
UPDATE `Recipe` SET RecipeName='strawberries & cream', CookTime='1', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1328;
UPDATE `Recipe` SET RecipeName='Strawberry Avocado Smoothie', CookTime='5', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1329;
UPDATE `Recipe` SET RecipeName='Strawberry Banana Surprise', CookTime='6', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=1330;
UPDATE `Recipe` SET RecipeName='Strawberry Basil Sangria', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='1331.jpg' WHERE ID=1331;
UPDATE `Recipe` SET RecipeName='Tasty Milkshake', CookTime='3', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1332;
UPDATE `Recipe` SET RecipeName='The RIOT', CookTime='2', DietType='TBD', IngredientCount='3', ImgURL='1333.jpg' WHERE ID=1333;
UPDATE `Recipe` SET RecipeName='Vanilla Ice', CookTime='60', DietType='TBD', IngredientCount='5', ImgURL='1334.jpg' WHERE ID=1334;
UPDATE `Recipe` SET RecipeName='Watermelon Gin', CookTime='45', DietType='TBD', IngredientCount='5', ImgURL='1335.jpg' WHERE ID=1335;
UPDATE `Recipe` SET RecipeName='Watermelon-rita', CookTime='60', DietType='TBD', IngredientCount='5', ImgURL='1336.jpg' WHERE ID=1336;
UPDATE `Recipe` SET RecipeName='Amazing Carne Asada', CookTime='120', DietType='TBD', IngredientCount='15', ImgURL='1337.jpg' WHERE ID=1337;
UPDATE `Recipe` SET RecipeName='AMAZING Mongolian Beef', CookTime='60', DietType='TBD', IngredientCount='15', ImgURL='1338.jpg' WHERE ID=1338;
UPDATE `Recipe` SET RecipeName='Amazing Prime Rib', CookTime='120', DietType='TBD', IngredientCount='11', ImgURL='1339.jpg' WHERE ID=1339;
UPDATE `Recipe` SET RecipeName='Another Awesome Meatloaf', CookTime='45', DietType='TBD', IngredientCount='13', ImgURL='1340.jpg' WHERE ID=1340;
UPDATE `Recipe` SET RecipeName='Another Burrito Casserole', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='1341.jpg' WHERE ID=1341;
UPDATE `Recipe` SET RecipeName='Another Meatloaf', CookTime='60', DietType='TBD', IngredientCount='17', ImgURL='1342.jpg' WHERE ID=1342;
UPDATE `Recipe` SET RecipeName='Another Mexican Casserole', CookTime='45', DietType='TBD', IngredientCount='12', ImgURL='1343.jpg' WHERE ID=1343;
UPDATE `Recipe` SET RecipeName='Another Mexican Lasagna', CookTime='60', DietType='TBD', IngredientCount='12', ImgURL='1344.jpg' WHERE ID=1344;
UPDATE `Recipe` SET RecipeName='Aussie Meat Loaf', CookTime='40', DietType='TBD', IngredientCount='18', ImgURL='' WHERE ID=1345;
UPDATE `Recipe` SET RecipeName='Awesome Street Tacos', CookTime='25', DietType='TBD', IngredientCount='17', ImgURL='1346.jpg' WHERE ID=1346;
UPDATE `Recipe` SET RecipeName='Bacon Burger Tot Casserole', CookTime='50', DietType='TBD', IngredientCount='8', ImgURL='1347.jpg' WHERE ID=1347;
UPDATE `Recipe` SET RecipeName='Bacon Cheddar Meatloaf', CookTime='60', DietType='TBD', IngredientCount='14', ImgURL='1348.jpg' WHERE ID=1348;
UPDATE `Recipe` SET RecipeName='Bacon Cheesburger Meatloaf', CookTime='75', DietType='TBD', IngredientCount='16', ImgURL='1349.jpg' WHERE ID=1349;
UPDATE `Recipe` SET RecipeName='Bacon Cheeseburger Loaf', CookTime='90', DietType='TBD', IngredientCount='11', ImgURL='1350.jpg' WHERE ID=1350;
UPDATE `Recipe` SET RecipeName='Bacon Cheeseburger Meatloaf', CookTime='50', DietType='TBD', IngredientCount='12', ImgURL='1351.jpg' WHERE ID=1351;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Balls', CookTime='45', DietType='TBD', IngredientCount='9', ImgURL='1352.jpg' WHERE ID=1352;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Mini Meatloafs', CookTime='85', DietType='TBD', IngredientCount='15', ImgURL='1353.jpg' WHERE ID=1353;
UPDATE `Recipe` SET RecipeName='Baked Cabbage Rolls', CookTime='50', DietType='TBD', IngredientCount='11', ImgURL='1354.jpg' WHERE ID=1354;
UPDATE `Recipe` SET RecipeName='Baked Frito Casserole', CookTime='20', DietType='TBD', IngredientCount='12', ImgURL='1355.jpg' WHERE ID=1355;
UPDATE `Recipe` SET RecipeName='Baked Italian Casserole', CookTime='60', DietType='TBD', IngredientCount='13', ImgURL='1356.jpg' WHERE ID=1356;
UPDATE `Recipe` SET RecipeName='Baked Tacos (Crunchy)', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='1357.jpg' WHERE ID=1357;
UPDATE `Recipe` SET RecipeName='Balsamic Filet', CookTime='20', DietType='TBD', IngredientCount='5', ImgURL='1358.jpg' WHERE ID=1358;
UPDATE `Recipe` SET RecipeName='Basic Roast Beef', CookTime='90', DietType='TBD', IngredientCount='6', ImgURL='1359.jpg' WHERE ID=1359;
UPDATE `Recipe` SET RecipeName='BBQ Meatballs', CookTime='240', DietType='TBD', IngredientCount='2', ImgURL='1360.jpg' WHERE ID=1360;
UPDATE `Recipe` SET RecipeName='BBQ Roast', CookTime='300', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1361;
UPDATE `Recipe` SET RecipeName='Beef and Bean Taco Bake', CookTime='45', DietType='TBD', IngredientCount='10', ImgURL='1362.jpg' WHERE ID=1362;
UPDATE `Recipe` SET RecipeName='Beef and Broccoli', CookTime='20', DietType='TBD', IngredientCount='13', ImgURL='1363.jpg' WHERE ID=1363;
UPDATE `Recipe` SET RecipeName='Beef and Cabbage Casserole', CookTime='50', DietType='TBD', IngredientCount='16', ImgURL='1364.jpg' WHERE ID=1364;
UPDATE `Recipe` SET RecipeName='Beef and Mushrooms', CookTime='45', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=1365;
UPDATE `Recipe` SET RecipeName='Beef and Noodle Casserole', CookTime='25', DietType='TBD', IngredientCount='15', ImgURL='1366.jpg' WHERE ID=1366;
UPDATE `Recipe` SET RecipeName='Beef and Ramen Noodles', CookTime='60', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1367;
UPDATE `Recipe` SET RecipeName='Beef Mix with Vegetables', CookTime='35', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=1368;
UPDATE `Recipe` SET RecipeName='Beef, Rice Beans', CookTime='40', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=1369;
UPDATE `Recipe` SET RecipeName='Beef Tenderloin', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='1370.jpg' WHERE ID=1370;
UPDATE `Recipe` SET RecipeName='Beef Tip Stir Fry', CookTime='45', DietType='TBD', IngredientCount='16', ImgURL='' WHERE ID=1371;
UPDATE `Recipe` SET RecipeName='Beef Tips and Mushrooms', CookTime='360', DietType='TBD', IngredientCount='5', ImgURL='1372.jpg' WHERE ID=1372;
UPDATE `Recipe` SET RecipeName='Beefy Tater Tot Casserole', CookTime='45', DietType='TBD', IngredientCount='8', ImgURL='1373.jpg' WHERE ID=1373;
UPDATE `Recipe` SET RecipeName='Beginner Brisket', CookTime='180', DietType='TBD', IngredientCount='6', ImgURL='1374.jpg' WHERE ID=1374;
UPDATE `Recipe` SET RecipeName='Best Beef Enchiladas', CookTime='60', DietType='TBD', IngredientCount='16', ImgURL='1375.jpg' WHERE ID=1375;
UPDATE `Recipe` SET RecipeName='BEST Beef Quesadillas', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='1376.jpg' WHERE ID=1376;
UPDATE `Recipe` SET RecipeName='Best Best Meatballs', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='1377.jpg' WHERE ID=1377;
UPDATE `Recipe` SET RecipeName='Best Best Meatloaf', CookTime='90', DietType='TBD', IngredientCount='13', ImgURL='1378.jpg' WHERE ID=1378;
UPDATE `Recipe` SET RecipeName='Best Mongolian Beef', CookTime='25', DietType='TBD', IngredientCount='3', ImgURL='1379.jpg' WHERE ID=1379;
UPDATE `Recipe` SET RecipeName='Best Sheppards Pie', CookTime='20', DietType='TBD', IngredientCount='15', ImgURL='1380.jpg' WHERE ID=1380;
UPDATE `Recipe` SET RecipeName='Blue Cheese Burger on a Stick', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='1381.jpg' WHERE ID=1381;
UPDATE `Recipe` SET RecipeName='Brown Sugar Keilbasa', CookTime='15', DietType='TBD', IngredientCount='2', ImgURL='' WHERE ID=1382;
UPDATE `Recipe` SET RecipeName='Brown Sugar Meat Loaf', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=1383;
UPDATE `Recipe` SET RecipeName='Brown Sugar Meatloaf', CookTime='60', DietType='TBD', IngredientCount='14', ImgURL='1384.jpg' WHERE ID=1384;
UPDATE `Recipe` SET RecipeName='Burgundy Beef', CookTime='260', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1385;
UPDATE `Recipe` SET RecipeName='Cabbage and Beef Casserole', CookTime='80', DietType='TBD', IngredientCount='12', ImgURL='1386.jpg' WHERE ID=1386;
UPDATE `Recipe` SET RecipeName='Cabbage and Beef Skillet', CookTime='20', DietType='TBD', IngredientCount='13', ImgURL='1387.jpg' WHERE ID=1387;
UPDATE `Recipe` SET RecipeName='Cabbage Roll Casserole', CookTime='100', DietType='TBD', IngredientCount='6', ImgURL='1388.jpg' WHERE ID=1388;
UPDATE `Recipe` SET RecipeName='Cajun Meat Loaf', CookTime='40', DietType='TBD', IngredientCount='16', ImgURL='' WHERE ID=1389;
UPDATE `Recipe` SET RecipeName='Cheesburger Pie', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1390;
UPDATE `Recipe` SET RecipeName='Cheese Stuffed Meatballs', CookTime='30', DietType='TBD', IngredientCount='13', ImgURL='1391.jpg' WHERE ID=1391;
UPDATE `Recipe` SET RecipeName='Cheeseburger Cups', CookTime='20', DietType='TBD', IngredientCount='13', ImgURL='1392.jpg' WHERE ID=1392;
UPDATE `Recipe` SET RecipeName='Cheeseburger in a Pan :)', CookTime='45', DietType='TBD', IngredientCount='13', ImgURL='1393.jpg' WHERE ID=1393;
UPDATE `Recipe` SET RecipeName='Cheeseburger Mac Casserole', CookTime='12', DietType='TBD', IngredientCount='14', ImgURL='1394.jpg' WHERE ID=1394;
UPDATE `Recipe` SET RecipeName='Cheeseburger Stuffed Bread', CookTime='40', DietType='TBD', IngredientCount='10', ImgURL='1395.jpg' WHERE ID=1395;
UPDATE `Recipe` SET RecipeName='Cheesesteak Mac and Cheese', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='1396.jpg' WHERE ID=1396;
UPDATE `Recipe` SET RecipeName='Cheesy Beef Casserole', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='1397.jpg' WHERE ID=1397;
UPDATE `Recipe` SET RecipeName='Cheesy Beefy Nacho Casserole', CookTime='45', DietType='TBD', IngredientCount='21', ImgURL='1398.jpg' WHERE ID=1398;
UPDATE `Recipe` SET RecipeName='Cheesy Beefy Quesadilla', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='1399.jpg' WHERE ID=1399;
UPDATE `Recipe` SET RecipeName='Cheesy Corn Beef', CookTime='45', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1400;
UPDATE `Recipe` SET RecipeName='Cheesy Meat Loaf', CookTime='60', DietType='TBD', IngredientCount='13', ImgURL='1401.jpg' WHERE ID=1401;
UPDATE `Recipe` SET RecipeName='Cheesy Stuffed Peppers', CookTime='30', DietType='TBD', IngredientCount='13', ImgURL='1402.jpg' WHERE ID=1402;
UPDATE `Recipe` SET RecipeName='Cheesy Trashy Casserole', CookTime='45', DietType='TBD', IngredientCount='7', ImgURL='1403.jpg' WHERE ID=1403;
UPDATE `Recipe` SET RecipeName='Chili Dog Casserole', CookTime='45', DietType='TBD', IngredientCount='12', ImgURL='' WHERE ID=1404;
UPDATE `Recipe` SET RecipeName='Chili Frito Burritos', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='1405.jpg' WHERE ID=1405;
UPDATE `Recipe` SET RecipeName='Coca-Cola Pot Roast', CookTime='480', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=1406;
UPDATE `Recipe` SET RecipeName='Cola Roast', CookTime='180', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1407;
UPDATE `Recipe` SET RecipeName='Corned Beef Cabbage Quesadilla', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='1408.jpg' WHERE ID=1408;
UPDATE `Recipe` SET RecipeName='Crazy Good Baked Meatballs', CookTime='35', DietType='TBD', IngredientCount='12', ImgURL='1409.jpg' WHERE ID=1409;
UPDATE `Recipe` SET RecipeName='Crazy Good Tater Tot Casserole', CookTime='40', DietType='TBD', IngredientCount='13', ImgURL='1410.jpg' WHERE ID=1410;
UPDATE `Recipe` SET RecipeName='Creamy burger casserole', CookTime='120', DietType='TBD', IngredientCount='15', ImgURL='' WHERE ID=1411;
UPDATE `Recipe` SET RecipeName='Creamy Burrito Casserole', CookTime='35', DietType='TBD', IngredientCount='12', ImgURL='1412.jpg' WHERE ID=1412;
UPDATE `Recipe` SET RecipeName='Crispy Cowboy Casserole', CookTime='45', DietType='TBD', IngredientCount='12', ImgURL='1413.jpg' WHERE ID=1413;
UPDATE `Recipe` SET RecipeName='Crock Pot Balsamic Roast', CookTime='240', DietType='TBD', IngredientCount='10', ImgURL='1414.jpg' WHERE ID=1414;
UPDATE `Recipe` SET RecipeName='Crock Pot Beef and Brocc', CookTime='420', DietType='TBD', IngredientCount='8', ImgURL='1415.jpg' WHERE ID=1415;
UPDATE `Recipe` SET RecipeName='Crock Pot Beef and Broccoli 2', CookTime='360', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=1416;
UPDATE `Recipe` SET RecipeName='Crock Pot Corned Beef', CookTime='480', DietType='TBD', IngredientCount='12', ImgURL='1417.jpg' WHERE ID=1417;
UPDATE `Recipe` SET RecipeName='Crock Pot Salisbury Steak', CookTime='300', DietType='TBD', IngredientCount='12', ImgURL='1418.jpg' WHERE ID=1418;
UPDATE `Recipe` SET RecipeName='crockpot pot roast', CookTime='300', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1419;
UPDATE `Recipe` SET RecipeName='CTC - Chili Tot Cass', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=1420;
UPDATE `Recipe` SET RecipeName='Danish Meat Balls with Dill Sa', CookTime='45', DietType='TBD', IngredientCount='15', ImgURL='' WHERE ID=1421;
UPDATE `Recipe` SET RecipeName='Delicious Chimichangas', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='1422.jpg' WHERE ID=1422;
UPDATE `Recipe` SET RecipeName='Dorito Taco Bake', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='1423.jpg' WHERE ID=1423;
UPDATE `Recipe` SET RecipeName='Easier Stuffed Peppers', CookTime='65', DietType='TBD', IngredientCount='12', ImgURL='1424.jpg' WHERE ID=1424;
UPDATE `Recipe` SET RecipeName='Easy Amazing Taco Cups', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='1425.jpg' WHERE ID=1425;
UPDATE `Recipe` SET RecipeName='Easy Beef and Broccoli', CookTime='25', DietType='TBD', IngredientCount='14', ImgURL='1426.jpg' WHERE ID=1426;
UPDATE `Recipe` SET RecipeName='Easy Beef Enchiladas', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='1427.jpg' WHERE ID=1427;
UPDATE `Recipe` SET RecipeName='Easy Beef Stir Fry', CookTime='15', DietType='TBD', IngredientCount='9', ImgURL='1428.jpg' WHERE ID=1428;
UPDATE `Recipe` SET RecipeName='Easy Burrito Casserole', CookTime='20', DietType='TBD', IngredientCount='12', ImgURL='1429.jpg' WHERE ID=1429;
UPDATE `Recipe` SET RecipeName='Easy Calzones', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=1430;
UPDATE `Recipe` SET RecipeName='Easy Cheesy Meatloaf', CookTime='30', DietType='TBD', IngredientCount='15', ImgURL='1431.jpg' WHERE ID=1431;
UPDATE `Recipe` SET RecipeName='Easy Frito Casserole', CookTime='30', DietType='TBD', IngredientCount='15', ImgURL='1432.jpg' WHERE ID=1432;
UPDATE `Recipe` SET RecipeName='Easy Goulash', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='1433.jpg' WHERE ID=1433;
UPDATE `Recipe` SET RecipeName='Easy Italian Meatballs', CookTime='35', DietType='TBD', IngredientCount='8', ImgURL='1434.jpg' WHERE ID=1434;
UPDATE `Recipe` SET RecipeName='Easy Korean Beef', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='1435.jpg' WHERE ID=1435;
UPDATE `Recipe` SET RecipeName='Easy Meat Loaf', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='1436.jpg' WHERE ID=1436;
UPDATE `Recipe` SET RecipeName='Easy Mexican Casserole', CookTime='30', DietType='TBD', IngredientCount='16', ImgURL='1437.jpg' WHERE ID=1437;
UPDATE `Recipe` SET RecipeName='Easy Mexican Lasagna', CookTime='30', DietType='TBD', IngredientCount='18', ImgURL='1438.jpg' WHERE ID=1438;
UPDATE `Recipe` SET RecipeName='Easy Mongolian Beef', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='1439.jpg' WHERE ID=1439;
UPDATE `Recipe` SET RecipeName='Easy Salisbury Steak Casserole', CookTime='30', DietType='TBD', IngredientCount='15', ImgURL='1440.jpg' WHERE ID=1440;
UPDATE `Recipe` SET RecipeName='Easy Steaks', CookTime='60', DietType='TBD', IngredientCount='3', ImgURL='1441.jpg' WHERE ID=1441;
UPDATE `Recipe` SET RecipeName='Easy Stuffed Cabbage Rolls', CookTime='165', DietType='TBD', IngredientCount='12', ImgURL='1442.jpg' WHERE ID=1442;
UPDATE `Recipe` SET RecipeName='Easy Stuffed Peppers', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1443;
UPDATE `Recipe` SET RecipeName='Flaked', CookTime='25', DietType='TBD', IngredientCount='2', ImgURL='1444.jpg' WHERE ID=1444;
UPDATE `Recipe` SET RecipeName='Flipped Meatball Casserole', CookTime='60', DietType='TBD', IngredientCount='16', ImgURL='1445.jpg' WHERE ID=1445;
UPDATE `Recipe` SET RecipeName='French Onion Meatballs', CookTime='240', DietType='TBD', IngredientCount='3', ImgURL='1446.jpg' WHERE ID=1446;
UPDATE `Recipe` SET RecipeName='Grilled Skirt Steak', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='1447.jpg' WHERE ID=1447;
UPDATE `Recipe` SET RecipeName='Ground Beef Wellington', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='1448.jpg' WHERE ID=1448;
UPDATE `Recipe` SET RecipeName='Hamburger Cheesy Potato Casserole', CookTime='90', DietType='TBD', IngredientCount='9', ImgURL='1449.jpg' WHERE ID=1449;
UPDATE `Recipe` SET RecipeName='Hamburger Lettuce Wraps', CookTime='20', DietType='TBD', IngredientCount='13', ImgURL='1450.jpg' WHERE ID=1450;
UPDATE `Recipe` SET RecipeName='Hamburger Potato Casserole', CookTime='85', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=1451;
UPDATE `Recipe` SET RecipeName='Herb-Crusted Rib Roast', CookTime='0', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=1452;
UPDATE `Recipe` SET RecipeName='Honey BBQ Meatloaf', CookTime='50', DietType='TBD', IngredientCount='8', ImgURL='1453.jpg' WHERE ID=1453;
UPDATE `Recipe` SET RecipeName='Hot Taco Bowl', CookTime='30', DietType='TBD', IngredientCount='18', ImgURL='1454.jpg' WHERE ID=1454;
UPDATE `Recipe` SET RecipeName='Hungarian Crockpot Goulash', CookTime='480', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=1455;
UPDATE `Recipe` SET RecipeName='Italian Crescent Casserole', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='1456.jpg' WHERE ID=1456;
UPDATE `Recipe` SET RecipeName='Italian Meatloaf', CookTime='60', DietType='TBD', IngredientCount='1', ImgURL='1457.jpg' WHERE ID=1457;
UPDATE `Recipe` SET RecipeName='Italian Stuffed Steak', CookTime='35', DietType='TBD', IngredientCount='13', ImgURL='1458.jpg' WHERE ID=1458;
UPDATE `Recipe` SET RecipeName='Leftover Beef Stir Fry', CookTime='20', DietType='TBD', IngredientCount='16', ImgURL='1459.jpg' WHERE ID=1459;
UPDATE `Recipe` SET RecipeName='Loaded Taco Potato', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='1460.jpg' WHERE ID=1460;
UPDATE `Recipe` SET RecipeName='Low Carb Philly Casserole', CookTime='50', DietType='TBD', IngredientCount='10', ImgURL='1461.jpg' WHERE ID=1461;
UPDATE `Recipe` SET RecipeName='Mashed Potato Bowl', CookTime='25', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=1462;
UPDATE `Recipe` SET RecipeName='Meat and Potato Casserole', CookTime='60', DietType='TBD', IngredientCount='14', ImgURL='1463.jpg' WHERE ID=1463;
UPDATE `Recipe` SET RecipeName='Meat Cous', CookTime='14', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1464;
UPDATE `Recipe` SET RecipeName='Meatball Parmesan', CookTime='40', DietType='TBD', IngredientCount='14', ImgURL='1465.jpg' WHERE ID=1465;
UPDATE `Recipe` SET RecipeName='Meatball Parmesan Casserole', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='1466.jpg' WHERE ID=1466;
UPDATE `Recipe` SET RecipeName='Meatball Stuffed Biscuits', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='1467.jpg' WHERE ID=1467;
UPDATE `Recipe` SET RecipeName='Meatloaf in the Microwave', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1468;
UPDATE `Recipe` SET RecipeName='Meatloaf Parmesan', CookTime='45', DietType='TBD', IngredientCount='17', ImgURL='1469.jpg' WHERE ID=1469;
UPDATE `Recipe` SET RecipeName='Meatloaf Roll', CookTime='60', DietType='TBD', IngredientCount='14', ImgURL='1470.jpg' WHERE ID=1470;
UPDATE `Recipe` SET RecipeName='Mexican Lasagna', CookTime='35', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1471;
UPDATE `Recipe` SET RecipeName='Mexican Steak Tacos', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=1472;
UPDATE `Recipe` SET RecipeName='Mexican Tot Casserole', CookTime='50', DietType='TBD', IngredientCount='10', ImgURL='1473.jpg' WHERE ID=1473;
UPDATE `Recipe` SET RecipeName='Mini Meat Pies', CookTime='55', DietType='TBD', IngredientCount='10', ImgURL='1474.jpg' WHERE ID=1474;
UPDATE `Recipe` SET RecipeName='Mini Meatloaf Muffins', CookTime='30', DietType='TBD', IngredientCount='17', ImgURL='1475.jpg' WHERE ID=1475;
UPDATE `Recipe` SET RecipeName='Mini Meatloafs', CookTime='40', DietType='TBD', IngredientCount='12', ImgURL='1476.jpg' WHERE ID=1476;
UPDATE `Recipe` SET RecipeName='Mississippi Roast', CookTime='360', DietType='TBD', IngredientCount='3', ImgURL='1477.jpg' WHERE ID=1477;
UPDATE `Recipe` SET RecipeName='More Bacon Wrapped Meatloaf', CookTime='60', DietType='TBD', IngredientCount='15', ImgURL='1478.jpg' WHERE ID=1478;
UPDATE `Recipe` SET RecipeName='More Beef and Broccoli', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='1479.jpg' WHERE ID=1479;
UPDATE `Recipe` SET RecipeName='More Cheese Stuffed Meatballs', CookTime='15', DietType='TBD', IngredientCount='14', ImgURL='1480.jpg' WHERE ID=1480;
UPDATE `Recipe` SET RecipeName='More Cheeseburger Casserole', CookTime='35', DietType='TBD', IngredientCount='5', ImgURL='1481.jpg' WHERE ID=1481;
UPDATE `Recipe` SET RecipeName='More Meat Balls', CookTime='40', DietType='TBD', IngredientCount='12', ImgURL='1482.jpg' WHERE ID=1482;
UPDATE `Recipe` SET RecipeName='More Meatball Parmesan Casserole', CookTime='45', DietType='TBD', IngredientCount='3', ImgURL='1483.jpg' WHERE ID=1483;
UPDATE `Recipe` SET RecipeName='More Meatball Stuffed Biscuits', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='1484.jpg' WHERE ID=1484;
UPDATE `Recipe` SET RecipeName='More Taco Pie', CookTime='40', DietType='TBD', IngredientCount='12', ImgURL='1485.jpg' WHERE ID=1485;
UPDATE `Recipe` SET RecipeName='More Taco Rolls', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='1486.jpg' WHERE ID=1486;
UPDATE `Recipe` SET RecipeName='Mozzarella Stuffed Meatloaf', CookTime='70', DietType='TBD', IngredientCount='16', ImgURL='1487.jpg' WHERE ID=1487;
UPDATE `Recipe` SET RecipeName='One Pan Meatballs', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=1488;
UPDATE `Recipe` SET RecipeName='Oven Baked Tacos', CookTime='35', DietType='TBD', IngredientCount='7', ImgURL='1489.jpg' WHERE ID=1489;
UPDATE `Recipe` SET RecipeName='Parmesan Meatball Skillet', CookTime='30', DietType='TBD', IngredientCount='3', ImgURL='1490.jpg' WHERE ID=1490;
UPDATE `Recipe` SET RecipeName='P.F. Mongolian Beef', CookTime='35', DietType='TBD', IngredientCount='12', ImgURL='1491.jpg' WHERE ID=1491;
UPDATE `Recipe` SET RecipeName='Philly Cheese steak Peppers', CookTime='60', DietType='TBD', IngredientCount='8', ImgURL='1492.jpg' WHERE ID=1492;
UPDATE `Recipe` SET RecipeName='Philly Cheesesteak Meatloaf', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=1493;
UPDATE `Recipe` SET RecipeName='Philly Stuffed Peppers', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='1494.jpg' WHERE ID=1494;
UPDATE `Recipe` SET RecipeName='Pot Roast (Slow Cook)', CookTime='480', DietType='TBD', IngredientCount='4', ImgURL='1495.jpg' WHERE ID=1495;
UPDATE `Recipe` SET RecipeName='Potato Burger Casserole', CookTime='90', DietType='TBD', IngredientCount='10', ImgURL='1496.jpg' WHERE ID=1496;
UPDATE `Recipe` SET RecipeName='Potato Stuffed Hot Dogs', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='1497.jpg' WHERE ID=1497;
UPDATE `Recipe` SET RecipeName='Pretzel Bun Burgers', CookTime='45', DietType='TBD', IngredientCount='12', ImgURL='' WHERE ID=1498;
UPDATE `Recipe` SET RecipeName='Professor Xavier Steak', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='1499.jpg' WHERE ID=1499;
UPDATE `Recipe` SET RecipeName='Quick Cheeseburger Meatloaf', CookTime='50', DietType='TBD', IngredientCount='8', ImgURL='1500.jpg' WHERE ID=1500;
UPDATE `Recipe` SET RecipeName='REAL Taco Pie', CookTime='40', DietType='TBD', IngredientCount='10', ImgURL='1501.jpg' WHERE ID=1501;
UPDATE `Recipe` SET RecipeName='Really Good Stuffed Peppers', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='1502.jpg' WHERE ID=1502;
UPDATE `Recipe` SET RecipeName='Ribs in the Crockpot', CookTime='480', DietType='TBD', IngredientCount='6', ImgURL='1503.jpg' WHERE ID=1503;
UPDATE `Recipe` SET RecipeName='Ritzy Meatloaf', CookTime='60', DietType='TBD', IngredientCount='4', ImgURL='1504.jpg' WHERE ID=1504;
UPDATE `Recipe` SET RecipeName='Roast Coke', CookTime='360', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=1505;
UPDATE `Recipe` SET RecipeName='Salisbury Steak', CookTime='35', DietType='TBD', IngredientCount='17', ImgURL='1506.jpg' WHERE ID=1506;
UPDATE `Recipe` SET RecipeName='Shephards Pie', CookTime='50', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=1507;
UPDATE `Recipe` SET RecipeName='Shredded BBQ Beef', CookTime='360', DietType='TBD', IngredientCount='12', ImgURL='1508.jpg' WHERE ID=1508;
UPDATE `Recipe` SET RecipeName='Simple Beef Chimichangas', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='1509.jpg' WHERE ID=1509;
UPDATE `Recipe` SET RecipeName='Simple Sloppy Joes', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=1510;
UPDATE `Recipe` SET RecipeName='Simple Stuffed Cabbage', CookTime='35', DietType='TBD', IngredientCount='5', ImgURL='1511.jpg' WHERE ID=1511;
UPDATE `Recipe` SET RecipeName='Simple Taco Casserole', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='1512.jpg' WHERE ID=1512;
UPDATE `Recipe` SET RecipeName='Sloppy Joe Casserole with Cornbread', CookTime='45', DietType='TBD', IngredientCount='12', ImgURL='1513.jpg' WHERE ID=1513;
UPDATE `Recipe` SET RecipeName='Sloppy Joe Tater Tot Casserole', CookTime='30', DietType='TBD', IngredientCount='15', ImgURL='1514.jpg' WHERE ID=1514;
UPDATE `Recipe` SET RecipeName='Slow Pot Roast', CookTime='300', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1515;
UPDATE `Recipe` SET RecipeName='Sour Dog Dumps', CookTime='25', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=1516;
UPDATE `Recipe` SET RecipeName='Spicy Garlic Steak', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1517;
UPDATE `Recipe` SET RecipeName='Spinach Meatballs', CookTime='30', DietType='TBD', IngredientCount='18', ImgURL='1518.jpg' WHERE ID=1518;
UPDATE `Recipe` SET RecipeName='Squash Casserole', CookTime='60', DietType='TBD', IngredientCount='12', ImgURL='' WHERE ID=1519;
UPDATE `Recipe` SET RecipeName='Steak on a Stick', CookTime='25', DietType='TBD', IngredientCount='18', ImgURL='1520.jpg' WHERE ID=1520;
UPDATE `Recipe` SET RecipeName='Steak Roulade', CookTime='60', DietType='TBD', IngredientCount='19', ImgURL='1521.jpg' WHERE ID=1521;
UPDATE `Recipe` SET RecipeName='Steak Souvlakis', CookTime='30', DietType='TBD', IngredientCount='21', ImgURL='' WHERE ID=1522;
UPDATE `Recipe` SET RecipeName='Steaks with Shallot Butter', CookTime='30', DietType='TBD', IngredientCount='10', ImgURL='1523.jpg' WHERE ID=1523;
UPDATE `Recipe` SET RecipeName='Stout Corned Beef', CookTime='180', DietType='TBD', IngredientCount='5', ImgURL='1524.jpg' WHERE ID=1524;
UPDATE `Recipe` SET RecipeName='Stroganoff', CookTime='15', DietType='TBD', IngredientCount='13', ImgURL='1525.jpg' WHERE ID=1525;
UPDATE `Recipe` SET RecipeName='Stuffed Cabbage Casserole', CookTime='55', DietType='TBD', IngredientCount='16', ImgURL='1526.jpg' WHERE ID=1526;
UPDATE `Recipe` SET RecipeName='Stuffed Cheesy Peppers', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='1527.jpg' WHERE ID=1527;
UPDATE `Recipe` SET RecipeName='Stuffed Flank Steak', CookTime='45', DietType='TBD', IngredientCount='15', ImgURL='1528.jpg' WHERE ID=1528;
UPDATE `Recipe` SET RecipeName='Stuffed Italian Meatballs', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='1529.jpg' WHERE ID=1529;
UPDATE `Recipe` SET RecipeName='Stuffed Mashed Potato Balls', CookTime='45', DietType='TBD', IngredientCount='18', ImgURL='' WHERE ID=1530;
UPDATE `Recipe` SET RecipeName='Stuffed Meat Loaf', CookTime='60', DietType='TBD', IngredientCount='24', ImgURL='1531.jpg' WHERE ID=1531;
UPDATE `Recipe` SET RecipeName='Stuffed Pepper Casserole', CookTime='20', DietType='TBD', IngredientCount='12', ImgURL='1532.jpg' WHERE ID=1532;
UPDATE `Recipe` SET RecipeName='Stuffed Peppers', CookTime='40', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1533;
UPDATE `Recipe` SET RecipeName='Suisse Devil Steak', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=1534;
UPDATE `Recipe` SET RecipeName='Swedish Meat Balls', CookTime='25', DietType='TBD', IngredientCount='12', ImgURL='1535.jpg' WHERE ID=1535;
UPDATE `Recipe` SET RecipeName='Sweet Glazed Meat Loaf', CookTime='75', DietType='TBD', IngredientCount='12', ImgURL='1536.jpg' WHERE ID=1536;
UPDATE `Recipe` SET RecipeName='Taco Bell Crunchwrap', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='1537.jpg' WHERE ID=1537;
UPDATE `Recipe` SET RecipeName='Taco Casserole Bake', CookTime='60', DietType='TBD', IngredientCount='10', ImgURL='1538.jpg' WHERE ID=1538;
UPDATE `Recipe` SET RecipeName='Taco Egg Rolls', CookTime='25', DietType='TBD', IngredientCount='5', ImgURL='1539.jpg' WHERE ID=1539;
UPDATE `Recipe` SET RecipeName='Taco Hashbrown Casserole', CookTime='40', DietType='TBD', IngredientCount='13', ImgURL='1540.jpg' WHERE ID=1540;
UPDATE `Recipe` SET RecipeName='Taco Meat Loaf', CookTime='45', DietType='TBD', IngredientCount='10', ImgURL='1541.jpg' WHERE ID=1541;
UPDATE `Recipe` SET RecipeName='Taco Pie', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='1542.jpg' WHERE ID=1542;
UPDATE `Recipe` SET RecipeName='Taco Rolls!', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='1543.jpg' WHERE ID=1543;
UPDATE `Recipe` SET RecipeName='Taco Skillet Pizza', CookTime='45', DietType='TBD', IngredientCount='10', ImgURL='1544.jpg' WHERE ID=1544;
UPDATE `Recipe` SET RecipeName='Taco Stuffed Potatoes', CookTime='60', DietType='TBD', IngredientCount='12', ImgURL='1545.jpg' WHERE ID=1545;
UPDATE `Recipe` SET RecipeName='Taco Stuffed Shells', CookTime='45', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=1546;
UPDATE `Recipe` SET RecipeName='Tacos in a Muffin Pan', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='1547.jpg' WHERE ID=1547;
UPDATE `Recipe` SET RecipeName='Tater Tot Beef Casserole', CookTime='50', DietType='TBD', IngredientCount='11', ImgURL='1548.jpg' WHERE ID=1548;
UPDATE `Recipe` SET RecipeName='Tater Tot Enchiladas', CookTime='30', DietType='TBD', IngredientCount='13', ImgURL='1549.jpg' WHERE ID=1549;
UPDATE `Recipe` SET RecipeName='Tater Tot Tacos', CookTime='40', DietType='TBD', IngredientCount='8', ImgURL='1550.jpg' WHERE ID=1550;
UPDATE `Recipe` SET RecipeName='Teriyaki Meatloaf', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1551;
UPDATE `Recipe` SET RecipeName='Tomato Tacos', CookTime='20', DietType='TBD', IngredientCount='15', ImgURL='1552.jpg' WHERE ID=1552;
UPDATE `Recipe` SET RecipeName='Totter Casserole', CookTime='30', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=1553;
UPDATE `Recipe` SET RecipeName='Turkey Shepherds Pie', CookTime='50', DietType='TBD', IngredientCount='12', ImgURL='1554.jpg' WHERE ID=1554;
UPDATE `Recipe` SET RecipeName='vidco pudding', CookTime='480', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1555;
UPDATE `Recipe` SET RecipeName='Whiskey Steaks', CookTime='20', DietType='TBD', IngredientCount='1', ImgURL='' WHERE ID=1556;
UPDATE `Recipe` SET RecipeName='You got a Meat Loaf', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=1557;
UPDATE `Recipe` SET RecipeName='Almond Chicken', CookTime='25', DietType='TBD', IngredientCount='12', ImgURL='' WHERE ID=1558;
UPDATE `Recipe` SET RecipeName='Amazing Amazing Chicken', CookTime='40', DietType='TBD', IngredientCount='8', ImgURL='1559.jpg' WHERE ID=1559;
UPDATE `Recipe` SET RecipeName='Amazing Chicken and Rice Casserole', CookTime='30', DietType='TBD', IngredientCount='0', ImgURL='1560.jpg' WHERE ID=1560;
UPDATE `Recipe` SET RecipeName='Amazing Chicken Enchiladas', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='1561.jpg' WHERE ID=1561;
UPDATE `Recipe` SET RecipeName='Amazing Lemon Chicken', CookTime='40', DietType='TBD', IngredientCount='14', ImgURL='1562.jpg' WHERE ID=1562;
UPDATE `Recipe` SET RecipeName='Amazing Roasted Chicken', CookTime='120', DietType='TBD', IngredientCount='8', ImgURL='1563.jpg' WHERE ID=1563;
UPDATE `Recipe` SET RecipeName='Another Chicken and Biscuit Casserole', CookTime='40', DietType='TBD', IngredientCount='9', ImgURL='1564.jpg' WHERE ID=1564;
UPDATE `Recipe` SET RecipeName='Another Chicken Casserole', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='1565.jpg' WHERE ID=1565;
UPDATE `Recipe` SET RecipeName='Another Oven Fried Chicken', CookTime='45', DietType='TBD', IngredientCount='13', ImgURL='1566.jpg' WHERE ID=1566;
UPDATE `Recipe` SET RecipeName='Another Parmesan Chicken', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='1567.jpg' WHERE ID=1567;
UPDATE `Recipe` SET RecipeName='Asparagus Stuffed Chicken', CookTime='25', DietType='TBD', IngredientCount='13', ImgURL='1568.jpg' WHERE ID=1568;
UPDATE `Recipe` SET RecipeName='Avocado and Tomato Chicken', CookTime='20', DietType='TBD', IngredientCount='0', ImgURL='1569.jpg' WHERE ID=1569;
UPDATE `Recipe` SET RecipeName='Avocado Chicken Avocados', CookTime='20', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=1570;
UPDATE `Recipe` SET RecipeName='Awesome Baked Chicken', CookTime='60', DietType='TBD', IngredientCount='8', ImgURL='1571.jpg' WHERE ID=1571;
UPDATE `Recipe` SET RecipeName='Awesome Cashew Chicken', CookTime='30', DietType='TBD', IngredientCount='17', ImgURL='1572.jpg' WHERE ID=1572;
UPDATE `Recipe` SET RecipeName='AWESOME Chicken!!', CookTime='70', DietType='TBD', IngredientCount='4', ImgURL='1573.jpg' WHERE ID=1573;
UPDATE `Recipe` SET RecipeName='Awesome Chicken Marsala', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='1574.jpg' WHERE ID=1574;
UPDATE `Recipe` SET RecipeName='Awesome Cordon Bleu', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='1575.jpg' WHERE ID=1575;
UPDATE `Recipe` SET RecipeName='Bacon Cheese Chicken', CookTime='35', DietType='TBD', IngredientCount='7', ImgURL='1576.jpg' WHERE ID=1576;
UPDATE `Recipe` SET RecipeName='Bacon Cheese Stuffed Chicken', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='1577.jpg' WHERE ID=1577;
UPDATE `Recipe` SET RecipeName='Bacon Cheesy Chicken Skillet', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='1578.jpg' WHERE ID=1578;
UPDATE `Recipe` SET RecipeName='Bacon Chicken Ranch Bites', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='1579.jpg' WHERE ID=1579;
UPDATE `Recipe` SET RecipeName='Bacon Honey Mustard Chicken', CookTime='20', DietType='TBD', IngredientCount='16', ImgURL='1580.jpg' WHERE ID=1580;
UPDATE `Recipe` SET RecipeName='Bacon Parmesan Fried Chicken', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='1581.jpg' WHERE ID=1581;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Apple Chicken', CookTime='480', DietType='TBD', IngredientCount='6', ImgURL='1582.jpg' WHERE ID=1582;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped BBQ Chicken', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='1583.jpg' WHERE ID=1583;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Cheesy Chicken', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='1584.jpg' WHERE ID=1584;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Cream Cheese Chicken', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='1585.jpg' WHERE ID=1585;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Pesto Chicken', CookTime='60', DietType='TBD', IngredientCount='12', ImgURL='1586.jpg' WHERE ID=1586;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Popper Chicken', CookTime='35', DietType='TBD', IngredientCount='9', ImgURL='1587.jpg' WHERE ID=1587;
UPDATE `Recipe` SET RecipeName='Bacon Wrapped Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='5', ImgURL='1588.jpg' WHERE ID=1588;
UPDATE `Recipe` SET RecipeName='Baked Chicken and Rice', CookTime='50', DietType='TBD', IngredientCount='8', ImgURL='1589.jpg' WHERE ID=1589;
UPDATE `Recipe` SET RecipeName='Baked Chicken Chimis', CookTime='25', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=1590;
UPDATE `Recipe` SET RecipeName='Baked Chicken Flautas', CookTime='25', DietType='TBD', IngredientCount='16', ImgURL='1591.jpg' WHERE ID=1591;
UPDATE `Recipe` SET RecipeName='Baked Pesto Chicken', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1592;
UPDATE `Recipe` SET RecipeName='Baked Sweet and Sour Chicken', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='1593.jpg' WHERE ID=1593;
UPDATE `Recipe` SET RecipeName='Baked Turkey Meatballs', CookTime='35', DietType='TBD', IngredientCount='17', ImgURL='1594.jpg' WHERE ID=1594;
UPDATE `Recipe` SET RecipeName='Balsamic Chicken and Veggies', CookTime='30', DietType='TBD', IngredientCount='16', ImgURL='1595.jpg' WHERE ID=1595;
UPDATE `Recipe` SET RecipeName='Balsamic Chicken Strips', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='1596.jpg' WHERE ID=1596;
UPDATE `Recipe` SET RecipeName='Balsamic Chicken with Mushroom', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=1597;
UPDATE `Recipe` SET RecipeName='Bang Bang Chicken', CookTime='45', DietType='TBD', IngredientCount='17', ImgURL='1598.jpg' WHERE ID=1598;
UPDATE `Recipe` SET RecipeName='Barbecued Chicken Classic', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1599;
UPDATE `Recipe` SET RecipeName='Basic Cordon Bleu', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='1600.jpg' WHERE ID=1600;
UPDATE `Recipe` SET RecipeName='Basic Roasted Chicken', CookTime='35', DietType='TBD', IngredientCount='8', ImgURL='1601.jpg' WHERE ID=1601;
UPDATE `Recipe` SET RecipeName='BBQ Cashew Chicken', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='1602.jpg' WHERE ID=1602;
UPDATE `Recipe` SET RecipeName='BBQ Chicken Enchiladas', CookTime='55', DietType='TBD', IngredientCount='11', ImgURL='1603.jpg' WHERE ID=1603;
UPDATE `Recipe` SET RecipeName='Bbq chicken Pizza', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=1604;
UPDATE `Recipe` SET RecipeName='BBQ Chicken Sweet Potatoes', CookTime='35', DietType='TBD', IngredientCount='3', ImgURL='1605.jpg' WHERE ID=1605;
UPDATE `Recipe` SET RecipeName='BEST Chicken and Rice', CookTime='90', DietType='TBD', IngredientCount='8', ImgURL='1606.jpg' WHERE ID=1606;
UPDATE `Recipe` SET RecipeName='Best Chicken Enchilada Casserole', CookTime='50', DietType='TBD', IngredientCount='9', ImgURL='1607.jpg' WHERE ID=1607;
UPDATE `Recipe` SET RecipeName='Best Chicken Enchiladas', CookTime='45', DietType='TBD', IngredientCount='14', ImgURL='1608.jpg' WHERE ID=1608;
UPDATE `Recipe` SET RecipeName='BEST Chicken Pot Pie', CookTime='75', DietType='TBD', IngredientCount='19', ImgURL='1609.jpg' WHERE ID=1609;
UPDATE `Recipe` SET RecipeName='Best Mexican Pizza', CookTime='15', DietType='TBD', IngredientCount='11', ImgURL='1610.jpg' WHERE ID=1610;
UPDATE `Recipe` SET RecipeName='BEST Orange Chicken', CookTime='75', DietType='TBD', IngredientCount='15', ImgURL='1611.jpg' WHERE ID=1611;
UPDATE `Recipe` SET RecipeName='BEST Sweet and Sour Chicken', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='1612.jpg' WHERE ID=1612;
UPDATE `Recipe` SET RecipeName='Besta Fiesta Chicken Casserole', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='1613.jpg' WHERE ID=1613;
UPDATE `Recipe` SET RecipeName='Best/Easiest Chicken Ever', CookTime='30', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1614;
UPDATE `Recipe` SET RecipeName='Better Chicken Enchiladas', CookTime='40', DietType='TBD', IngredientCount='13', ImgURL='1615.jpg' WHERE ID=1615;
UPDATE `Recipe` SET RecipeName='Blackend Chicken', CookTime='20', DietType='TBD', IngredientCount='3', ImgURL='1616.jpg' WHERE ID=1616;
UPDATE `Recipe` SET RecipeName='Blackened Chicken', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1617;
UPDATE `Recipe` SET RecipeName='Border Turkey', CookTime='25', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=1618;
UPDATE `Recipe` SET RecipeName='Bourbon Street Chicken', CookTime='480', DietType='TBD', IngredientCount='9', ImgURL='1619.jpg' WHERE ID=1619;
UPDATE `Recipe` SET RecipeName='"Br-eta" Chicken', CookTime='40', DietType='TBD', IngredientCount='6', ImgURL='1620.jpg' WHERE ID=1620;
UPDATE `Recipe` SET RecipeName='Broccoli Cheese Stuffed Chicken', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='1621.jpg' WHERE ID=1621;
UPDATE `Recipe` SET RecipeName='Broccoli Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='5', ImgURL='1622.jpg' WHERE ID=1622;
UPDATE `Recipe` SET RecipeName='Brown Sugar Chicken', CookTime='35', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=1623;
UPDATE `Recipe` SET RecipeName='Bruschetta Chicken', CookTime='50', DietType='TBD', IngredientCount='16', ImgURL='1624.jpg' WHERE ID=1624;
UPDATE `Recipe` SET RecipeName='Bruschetta Chicken Bake', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=1625;
UPDATE `Recipe` SET RecipeName='Buffalo BBQ Chicken', CookTime='60', DietType='TBD', IngredientCount='1', ImgURL='1626.jpg' WHERE ID=1626;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken and Cauliflower', CookTime='55', DietType='TBD', IngredientCount='16', ImgURL='1627.jpg' WHERE ID=1627;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken and Potatoes', CookTime='90', DietType='TBD', IngredientCount='13', ImgURL='1628.jpg' WHERE ID=1628;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Casserole', CookTime='60', DietType='TBD', IngredientCount='10', ImgURL='1629.jpg' WHERE ID=1629;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Cups', CookTime='20', DietType='TBD', IngredientCount='5', ImgURL='1630.jpg' WHERE ID=1630;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Meatballs', CookTime='30', DietType='TBD', IngredientCount='13', ImgURL='1631.jpg' WHERE ID=1631;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Ranch Potato Casserole', CookTime='35', DietType='TBD', IngredientCount='13', ImgURL='1632.jpg' WHERE ID=1632;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Toast', CookTime='25', DietType='TBD', IngredientCount='15', ImgURL='1633.jpg' WHERE ID=1633;
UPDATE `Recipe` SET RecipeName='Bulk Chicken', CookTime='120', DietType='TBD', IngredientCount='3', ImgURL='1634.jpg' WHERE ID=1634;
UPDATE `Recipe` SET RecipeName='Cabbage Chicken Salad', CookTime='0', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=1635;
UPDATE `Recipe` SET RecipeName='Cajun Bourbon Chicken', CookTime='30', DietType='TBD', IngredientCount='16', ImgURL='1636.jpg' WHERE ID=1636;
UPDATE `Recipe` SET RecipeName='Cajun Chicken and Rice', CookTime='25', DietType='TBD', IngredientCount='13', ImgURL='1637.jpg' WHERE ID=1637;
UPDATE `Recipe` SET RecipeName='Cajun Injected Spicy Turkey', CookTime='300', DietType='TBD', IngredientCount='17', ImgURL='1638.jpg' WHERE ID=1638;
UPDATE `Recipe` SET RecipeName='Caprese Stuffed Chicken', CookTime='35', DietType='TBD', IngredientCount='11', ImgURL='1639.jpg' WHERE ID=1639;
UPDATE `Recipe` SET RecipeName='Casserole of some kind', CookTime='45', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1640;
UPDATE `Recipe` SET RecipeName='Cheddar Ranch Chicken', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='1641.jpg' WHERE ID=1641;
UPDATE `Recipe` SET RecipeName='Cheese and Broccoli Stuffed Chicken', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='1642.jpg' WHERE ID=1642;
UPDATE `Recipe` SET RecipeName='Cheese Stuffed Chicken Marsala', CookTime='45', DietType='TBD', IngredientCount='16', ImgURL='1643.jpg' WHERE ID=1643;
UPDATE `Recipe` SET RecipeName='Cheese Stuffed Turkey Meatballs', CookTime='30', DietType='TBD', IngredientCount='17', ImgURL='1644.jpg' WHERE ID=1644;
UPDATE `Recipe` SET RecipeName='Cheesy Baked Chicken Rolls', CookTime='35', DietType='TBD', IngredientCount='14', ImgURL='1645.jpg' WHERE ID=1645;
UPDATE `Recipe` SET RecipeName='Cheesy Broccoli Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='11', ImgURL='1646.jpg' WHERE ID=1646;
UPDATE `Recipe` SET RecipeName='Cheesy Buffalo Chicken Biscuits', CookTime='25', DietType='TBD', IngredientCount='9', ImgURL='1647.jpg' WHERE ID=1647;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken and Rice', CookTime='30', DietType='TBD', IngredientCount='11', ImgURL='1648.jpg' WHERE ID=1648;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken and Rice Casser', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=1649;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Biscuit Bake', CookTime='60', DietType='TBD', IngredientCount='12', ImgURL='1650.jpg' WHERE ID=1650;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Casserole', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='1651.jpg' WHERE ID=1651;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Enchiladas', CookTime='25', DietType='TBD', IngredientCount='12', ImgURL='1652.jpg' WHERE ID=1652;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Jalapeno Casserole', CookTime='50', DietType='TBD', IngredientCount='6', ImgURL='1653.jpg' WHERE ID=1653;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken & Ramen', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1654;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Roll Ups', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='1655.jpg' WHERE ID=1655;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Rolls', CookTime='25', DietType='TBD', IngredientCount='4', ImgURL='1656.jpg' WHERE ID=1656;
UPDATE `Recipe` SET RecipeName='Cheesy Chicken Stuffed With Broccoli', CookTime='25', DietType='TBD', IngredientCount='12', ImgURL='1657.jpg' WHERE ID=1657;
UPDATE `Recipe` SET RecipeName='Cheesy Pepper Chicken', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='1658.jpg' WHERE ID=1658;
UPDATE `Recipe` SET RecipeName='Cheesy Smothered Chicken', CookTime='35', DietType='TBD', IngredientCount='8', ImgURL='1659.jpg' WHERE ID=1659;
UPDATE `Recipe` SET RecipeName='Cheesy Spinach Stuffed Chicken', CookTime='40', DietType='TBD', IngredientCount='9', ImgURL='1660.jpg' WHERE ID=1660;
UPDATE `Recipe` SET RecipeName='Cheesy Stuffed Chicken Parmesan', CookTime='20', DietType='TBD', IngredientCount='1', ImgURL='1661.jpg' WHERE ID=1661;
UPDATE `Recipe` SET RecipeName='Chic fila nuggets', CookTime='20', DietType='TBD', IngredientCount='19', ImgURL='1662.jpg' WHERE ID=1662;
UPDATE `Recipe` SET RecipeName='Chicken Adobo', CookTime='120', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=1663;
UPDATE `Recipe` SET RecipeName='Chicken Alfredo Rollups', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='1664.jpg' WHERE ID=1664;
UPDATE `Recipe` SET RecipeName='Chicken and Black Bean Casserole', CookTime='40', DietType='TBD', IngredientCount='13', ImgURL='1665.jpg' WHERE ID=1665;
UPDATE `Recipe` SET RecipeName='Chicken and Broccoli', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1666;
UPDATE `Recipe` SET RecipeName='Chicken and Broccoli Stir', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='1667.jpg' WHERE ID=1667;
UPDATE `Recipe` SET RecipeName='Chicken and Butter Sauce', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='1668.jpg' WHERE ID=1668;
UPDATE `Recipe` SET RecipeName='Chicken and Cabbage', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='1669.jpg' WHERE ID=1669;
UPDATE `Recipe` SET RecipeName='Chicken and Cranberry Sauce', CookTime='360', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=1670;
UPDATE `Recipe` SET RecipeName='Chicken and Dumpling Casserole', CookTime='50', DietType='TBD', IngredientCount='8', ImgURL='1671.jpg' WHERE ID=1671;
UPDATE `Recipe` SET RecipeName='Chicken and Dumplings', CookTime='40', DietType='TBD', IngredientCount='7', ImgURL='1672.jpg' WHERE ID=1672;
UPDATE `Recipe` SET RecipeName='Chicken and Feta Sauce', CookTime='35', DietType='TBD', IngredientCount='11', ImgURL='1673.jpg' WHERE ID=1673;
UPDATE `Recipe` SET RecipeName='Chicken and Mango Curry', CookTime='35', DietType='TBD', IngredientCount='8', ImgURL='1674.jpg' WHERE ID=1674;
UPDATE `Recipe` SET RecipeName='Chicken and Mushroom Pie', CookTime='50', DietType='TBD', IngredientCount='12', ImgURL='1675.jpg' WHERE ID=1675;
UPDATE `Recipe` SET RecipeName='Chicken and Potato Casserole', CookTime='70', DietType='TBD', IngredientCount='9', ImgURL='1676.jpg' WHERE ID=1676;
UPDATE `Recipe` SET RecipeName='Chicken and Rice', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=1677;
UPDATE `Recipe` SET RecipeName='Chicken and Rice Casserole Bake', CookTime='90', DietType='TBD', IngredientCount='5', ImgURL='1678.jpg' WHERE ID=1678;
UPDATE `Recipe` SET RecipeName='Chicken and Stuffing Casserole', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='1679.jpg' WHERE ID=1679;
UPDATE `Recipe` SET RecipeName='Chicken and Veggie Stir Fry', CookTime='20', DietType='TBD', IngredientCount='12', ImgURL='1680.jpg' WHERE ID=1680;
UPDATE `Recipe` SET RecipeName='Chicken Biscuit Casserole', CookTime='35', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1681;
UPDATE `Recipe` SET RecipeName='Chicken Black Beans and Corn', CookTime='360', DietType='TBD', IngredientCount='7', ImgURL='1682.jpg' WHERE ID=1682;
UPDATE `Recipe` SET RecipeName='Chicken Broccoli Pasta Bake', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='1683.jpg' WHERE ID=1683;
UPDATE `Recipe` SET RecipeName='Chicken Broccoli Rice Casserole', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='1684.jpg' WHERE ID=1684;
UPDATE `Recipe` SET RecipeName='Chicken Cordon Bleu', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='1685.jpg' WHERE ID=1685;
UPDATE `Recipe` SET RecipeName='Chicken Enchilada Casserole', CookTime='45', DietType='TBD', IngredientCount='5', ImgURL='1686.jpg' WHERE ID=1686;
UPDATE `Recipe` SET RecipeName='Chicken Enchiladas', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1687;
UPDATE `Recipe` SET RecipeName='Chicken Fajitas', CookTime='20', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=1688;
UPDATE `Recipe` SET RecipeName='Chicken for you', CookTime='25', DietType='TBD', IngredientCount='4', ImgURL='1689.jpg' WHERE ID=1689;
UPDATE `Recipe` SET RecipeName='Chicken Fried Chicken', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='1690.jpg' WHERE ID=1690;
UPDATE `Recipe` SET RecipeName='Chicken Fried Rice', CookTime='15', DietType='TBD', IngredientCount='9', ImgURL='1691.jpg' WHERE ID=1691;
UPDATE `Recipe` SET RecipeName='Chicken Gloria', CookTime='60', DietType='TBD', IngredientCount='12', ImgURL='1692.jpg' WHERE ID=1692;
UPDATE `Recipe` SET RecipeName='Chicken Green Bean Casserole', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='1693.jpg' WHERE ID=1693;
UPDATE `Recipe` SET RecipeName='Chicken Macaroni Casserole', CookTime='30', DietType='TBD', IngredientCount='10', ImgURL='1694.jpg' WHERE ID=1694;
UPDATE `Recipe` SET RecipeName='Chicken Meatballs with Cream Sauce', CookTime='40', DietType='TBD', IngredientCount='16', ImgURL='1695.jpg' WHERE ID=1695;
UPDATE `Recipe` SET RecipeName='Chicken Mozz', CookTime='25', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=1696;
UPDATE `Recipe` SET RecipeName='Chicken n Biscuit Casserole', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='1697.jpg' WHERE ID=1697;
UPDATE `Recipe` SET RecipeName='Chicken Parm Meatballs', CookTime='45', DietType='TBD', IngredientCount='15', ImgURL='1698.jpg' WHERE ID=1698;
UPDATE `Recipe` SET RecipeName='Chicken Parm Rolls', CookTime='35', DietType='TBD', IngredientCount='7', ImgURL='1699.jpg' WHERE ID=1699;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan', CookTime='35', DietType='TBD', IngredientCount='18', ImgURL='1700.jpg' WHERE ID=1700;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Casserole', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='1701.jpg' WHERE ID=1701;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Lasagna', CookTime='60', DietType='TBD', IngredientCount='14', ImgURL='1702.jpg' WHERE ID=1702;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Meatballs', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='1703.jpg' WHERE ID=1703;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Peppers', CookTime='60', DietType='TBD', IngredientCount='12', ImgURL='1704.jpg' WHERE ID=1704;
UPDATE `Recipe` SET RecipeName='Chicken Parmesan Roll ups', CookTime='20', DietType='TBD', IngredientCount='2', ImgURL='1705.jpg' WHERE ID=1705;
UPDATE `Recipe` SET RecipeName='Chicken Pasta Salad', CookTime='15', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=1706;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie', CookTime='40', DietType='TBD', IngredientCount='6', ImgURL='1707.jpg' WHERE ID=1707;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie Biscuits', CookTime='45', DietType='TBD', IngredientCount='16', ImgURL='1708.jpg' WHERE ID=1708;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie Casserole', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='1709.jpg' WHERE ID=1709;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie Crescent', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='1710.jpg' WHERE ID=1710;
UPDATE `Recipe` SET RecipeName='Chicken Pot Pie Crumble', CookTime='360', DietType='TBD', IngredientCount='24', ImgURL='1711.jpg' WHERE ID=1711;
UPDATE `Recipe` SET RecipeName='Chicken Puffs', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=1712;
UPDATE `Recipe` SET RecipeName='Chicken Ranch Tacos', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='1713.jpg' WHERE ID=1713;
UPDATE `Recipe` SET RecipeName='Chicken Rice and Broccoli', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='1714.jpg' WHERE ID=1714;
UPDATE `Recipe` SET RecipeName='Chicken & Rice Dinner', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1715;
UPDATE `Recipe` SET RecipeName='Chicken Salad II', CookTime='15', DietType='TBD', IngredientCount='11', ImgURL='1716.jpg' WHERE ID=1716;
UPDATE `Recipe` SET RecipeName='Chicken & Spaghetti', CookTime='35', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=1717;
UPDATE `Recipe` SET RecipeName='Chicken Stir Fry', CookTime='15', DietType='TBD', IngredientCount='16', ImgURL='1718.jpg' WHERE ID=1718;
UPDATE `Recipe` SET RecipeName='Chicken Stroganoff Simple', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=1719;
UPDATE `Recipe` SET RecipeName='Chicken Stuffed Peppers', CookTime='45', DietType='TBD', IngredientCount='12', ImgURL='1720.jpg' WHERE ID=1720;
UPDATE `Recipe` SET RecipeName='Chicken Teriaki - Easy', CookTime='60', DietType='TBD', IngredientCount='3', ImgURL='1721.jpg' WHERE ID=1721;
UPDATE `Recipe` SET RecipeName='Chicken Teriyaki CP', CookTime='240', DietType='TBD', IngredientCount='4', ImgURL='1722.jpg' WHERE ID=1722;
UPDATE `Recipe` SET RecipeName='Chicken Tomato Cream Sauce', CookTime='50', DietType='TBD', IngredientCount='13', ImgURL='1723.jpg' WHERE ID=1723;
UPDATE `Recipe` SET RecipeName='Chicken Tortilla Pie', CookTime='45', DietType='TBD', IngredientCount='0', ImgURL='1724.jpg' WHERE ID=1724;
UPDATE `Recipe` SET RecipeName='Chicken with Creamy Tomato Sauce', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='1725.jpg' WHERE ID=1725;
UPDATE `Recipe` SET RecipeName='Chili Lime Chicken', CookTime='19', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=1726;
UPDATE `Recipe` SET RecipeName='Chimi Changas!', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='1727.jpg' WHERE ID=1727;
UPDATE `Recipe` SET RecipeName='Cider Bacon Chicken', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='1728.jpg' WHERE ID=1728;
UPDATE `Recipe` SET RecipeName='Coca Cola Chicken', CookTime='65', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=1729;
UPDATE `Recipe` SET RecipeName='Cola Chicken', CookTime='55', DietType='TBD', IngredientCount='4', ImgURL='1730.jpg' WHERE ID=1730;
UPDATE `Recipe` SET RecipeName='Cordon Bleu Casserole', CookTime='70', DietType='TBD', IngredientCount='15', ImgURL='1731.jpg' WHERE ID=1731;
UPDATE `Recipe` SET RecipeName='Cordon Bleu Nuggets', CookTime='25', DietType='TBD', IngredientCount='9', ImgURL='1732.jpg' WHERE ID=1732;
UPDATE `Recipe` SET RecipeName='Corn Flaked Baked Chicken', CookTime='180', DietType='TBD', IngredientCount='12', ImgURL='1733.jpg' WHERE ID=1733;
UPDATE `Recipe` SET RecipeName='Country Pecan Chicken', CookTime='25', DietType='TBD', IngredientCount='5', ImgURL='1734.jpg' WHERE ID=1734;
UPDATE `Recipe` SET RecipeName='Cracker Fried Chicken', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=1735;
UPDATE `Recipe` SET RecipeName='Cranberry Turkey', CookTime='120', DietType='TBD', IngredientCount='8', ImgURL='1736.jpg' WHERE ID=1736;
UPDATE `Recipe` SET RecipeName='Crazy Good Chicken', CookTime='25', DietType='TBD', IngredientCount='9', ImgURL='1737.jpg' WHERE ID=1737;
UPDATE `Recipe` SET RecipeName='Crazy Good Chicken Enchiladas', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='1738.jpg' WHERE ID=1738;
UPDATE `Recipe` SET RecipeName='Cream Cheese Chicken', CookTime='45', DietType='TBD', IngredientCount='13', ImgURL='1739.jpg' WHERE ID=1739;
UPDATE `Recipe` SET RecipeName='Creamy Bacon Crockpot Chicken', CookTime='495', DietType='TBD', IngredientCount='10', ImgURL='1740.jpg' WHERE ID=1740;
UPDATE `Recipe` SET RecipeName='Creamy Cheesy Chicken Enchiladas', CookTime='25', DietType='TBD', IngredientCount='12', ImgURL='1741.jpg' WHERE ID=1741;
UPDATE `Recipe` SET RecipeName='Creamy Chicken Bake', CookTime='50', DietType='TBD', IngredientCount='9', ImgURL='1742.jpg' WHERE ID=1742;
UPDATE `Recipe` SET RecipeName='Creamy Chicken Enchiladas', CookTime='45', DietType='TBD', IngredientCount='10', ImgURL='1743.jpg' WHERE ID=1743;
UPDATE `Recipe` SET RecipeName='Creamy Chicken Jalapeno Enchiladas', CookTime='25', DietType='TBD', IngredientCount='11', ImgURL='1744.jpg' WHERE ID=1744;
