UPDATE `Recipe` SET RecipeName='French Toast Sticks', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='440.jpg' WHERE ID=440;
UPDATE `Recipe` SET RecipeName='French Toast Stuffed With Peanut Butter', CookTime='20', DietType='TBD', IngredientCount='14', ImgURL='441.jpg' WHERE ID=441;
UPDATE `Recipe` SET RecipeName='French Toast Wrapped Eggs', CookTime='35', DietType='TBD', IngredientCount='11', ImgURL='442.jpg' WHERE ID=442;
UPDATE `Recipe` SET RecipeName='Fried Bacon Hashbrowns', CookTime='15', DietType='TBD', IngredientCount='12', ImgURL='443.jpg' WHERE ID=443;
UPDATE `Recipe` SET RecipeName='Fried Egg and Avocado Toast', CookTime='10', DietType='TBD', IngredientCount='12', ImgURL='444.jpg' WHERE ID=444;
UPDATE `Recipe` SET RecipeName='Fried Sumac Eggs', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=445;
UPDATE `Recipe` SET RecipeName='Fruity Baked Oatmeal', CookTime='40', DietType='TBD', IngredientCount='13', ImgURL='446.jpg' WHERE ID=446;
UPDATE `Recipe` SET RecipeName='Fruity French Toast', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='447.jpg' WHERE ID=447;
UPDATE `Recipe` SET RecipeName='Ham and Egg Crepes', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='448.jpg' WHERE ID=448;
UPDATE `Recipe` SET RecipeName='Ham Egg and Cheese Wrap', CookTime='25', DietType='TBD', IngredientCount='7', ImgURL='449.jpg' WHERE ID=449;
UPDATE `Recipe` SET RecipeName='Hash Brown Omelette', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=450;
UPDATE `Recipe` SET RecipeName='Healthier Baked Pancakes', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='451.jpg' WHERE ID=451;
UPDATE `Recipe` SET RecipeName='Healthy Peach Breakfast', CookTime='45', DietType='TBD', IngredientCount='15', ImgURL='452.jpg' WHERE ID=452;
UPDATE `Recipe` SET RecipeName='High Protein Scrambled Eggs', CookTime='8', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=453;
UPDATE `Recipe` SET RecipeName='Holiday Breakfast Casserole', CookTime='90', DietType='TBD', IngredientCount='9', ImgURL='454.jpg' WHERE ID=454;
UPDATE `Recipe` SET RecipeName='Homemade Pancake Mix', CookTime='10', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=455;
UPDATE `Recipe` SET RecipeName='Incredible Breakfast Bake', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='456.jpg' WHERE ID=456;
UPDATE `Recipe` SET RecipeName='Italian Eggs in a Cup', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='457.jpg' WHERE ID=457;
UPDATE `Recipe` SET RecipeName='Kick your mouth Muffins', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='458.jpg' WHERE ID=458;
UPDATE `Recipe` SET RecipeName='Last Minute Egg and Pasta', CookTime='10', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=459;
UPDATE `Recipe` SET RecipeName='Lil Spicy Scrambled', CookTime='5', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=460;
UPDATE `Recipe` SET RecipeName='Loaded Breakfast Burritos', CookTime='30', DietType='TBD', IngredientCount='17', ImgURL='461.jpg' WHERE ID=461;
UPDATE `Recipe` SET RecipeName='Loaded Breakfast Casserole', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='462.jpg' WHERE ID=462;
UPDATE `Recipe` SET RecipeName='Low Carb Cream Cheese Pancakes', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='463.jpg' WHERE ID=463;
UPDATE `Recipe` SET RecipeName='Low French Toast', CookTime='20', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=464;
UPDATE `Recipe` SET RecipeName='Mexican Breakfast Pizza', CookTime='5', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=465;
UPDATE `Recipe` SET RecipeName='Mexican Eggs', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='466.jpg' WHERE ID=466;
UPDATE `Recipe` SET RecipeName='Mexican Roadkill', CookTime='8', DietType='TBD', IngredientCount='7', ImgURL='467.jpg' WHERE ID=467;
UPDATE `Recipe` SET RecipeName='Mini German Pancakes', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='468.jpg' WHERE ID=468;
UPDATE `Recipe` SET RecipeName='Mini Quiche', CookTime='40', DietType='TBD', IngredientCount='12', ImgURL='469.jpg' WHERE ID=469;
UPDATE `Recipe` SET RecipeName='More Baked French Toast', CookTime='60', DietType='TBD', IngredientCount='12', ImgURL='470.jpg' WHERE ID=470;
UPDATE `Recipe` SET RecipeName='More Breakfast Cups', CookTime='35', DietType='TBD', IngredientCount='9', ImgURL='471.jpg' WHERE ID=471;
UPDATE `Recipe` SET RecipeName='More Poached Eggs', CookTime='4', DietType='TBD', IngredientCount='3', ImgURL='472.jpg' WHERE ID=472;
UPDATE `Recipe` SET RecipeName='Muffled Eggs', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='' WHERE ID=473;
UPDATE `Recipe` SET RecipeName='Non Pancake Pancakes', CookTime='15', DietType='TBD', IngredientCount='5', ImgURL='474.jpg' WHERE ID=474;
UPDATE `Recipe` SET RecipeName='Nutella French Toast', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='475.jpg' WHERE ID=475;
UPDATE `Recipe` SET RecipeName='Oatmeal Cookie Pancakes', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='476.jpg' WHERE ID=476;
UPDATE `Recipe` SET RecipeName='Oatmeal in a Mug', CookTime='2', DietType='TBD', IngredientCount='5', ImgURL='477.jpg' WHERE ID=477;
UPDATE `Recipe` SET RecipeName='Omelet Casserole', CookTime='45', DietType='TBD', IngredientCount='7', ImgURL='478.jpg' WHERE ID=478;
UPDATE `Recipe` SET RecipeName='Omelet Egg Roll', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='479.jpg' WHERE ID=479;
UPDATE `Recipe` SET RecipeName='One More French Toast Bake', CookTime='45', DietType='TBD', IngredientCount='5', ImgURL='480.jpg' WHERE ID=480;
UPDATE `Recipe` SET RecipeName='Open Faced Tomato Sandwich', CookTime='10', DietType='TBD', IngredientCount='8', ImgURL='481.jpg' WHERE ID=481;
UPDATE `Recipe` SET RecipeName='Overnight Breakfast Casserole', CookTime='45', DietType='TBD', IngredientCount='9', ImgURL='482.jpg' WHERE ID=482;
UPDATE `Recipe` SET RecipeName='Overnight Sausage and Hashbrowns', CookTime='45', DietType='TBD', IngredientCount='8', ImgURL='483.jpg' WHERE ID=483;
UPDATE `Recipe` SET RecipeName='Pancake Bites', CookTime='20', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=484;
UPDATE `Recipe` SET RecipeName='Pancake Cups', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='485.jpg' WHERE ID=485;
UPDATE `Recipe` SET RecipeName='Pancakes from Scratch', CookTime='7', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=486;
UPDATE `Recipe` SET RecipeName='PB & J French Toast', CookTime='15', DietType='TBD', IngredientCount='12', ImgURL='' WHERE ID=487;
UPDATE `Recipe` SET RecipeName='Peanut Butter and Banana French Toast', CookTime='10', DietType='TBD', IngredientCount='12', ImgURL='488.jpg' WHERE ID=488;
UPDATE `Recipe` SET RecipeName='Perfect French Toast', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='489.jpg' WHERE ID=489;
UPDATE `Recipe` SET RecipeName='Picks Pankakes', CookTime='15', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=490;
UPDATE `Recipe` SET RecipeName='Pineapple Upside Down Pancake', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='491.jpg' WHERE ID=491;
UPDATE `Recipe` SET RecipeName='Pineapple Upsidedown Pancakes', CookTime='20', DietType='TBD', IngredientCount='11', ImgURL='492.jpg' WHERE ID=492;
UPDATE `Recipe` SET RecipeName='Poached Eggs (Micro)', CookTime='6', DietType='TBD', IngredientCount='5', ImgURL='493.jpg' WHERE ID=493;
UPDATE `Recipe` SET RecipeName='Poached Eggs n Avocado', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='494.jpg' WHERE ID=494;
UPDATE `Recipe` SET RecipeName='Pork Scramble', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='495.jpg' WHERE ID=495;
UPDATE `Recipe` SET RecipeName='Potato Bacon Casserole', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='496.jpg' WHERE ID=496;
UPDATE `Recipe` SET RecipeName='Pumpkin French Toast Bake', CookTime='50', DietType='TBD', IngredientCount='10', ImgURL='497.jpg' WHERE ID=497;
UPDATE `Recipe` SET RecipeName='Pumpkin Pankakes', CookTime='5', DietType='TBD', IngredientCount='4', ImgURL='498.jpg' WHERE ID=498;
UPDATE `Recipe` SET RecipeName='Pumpkin Pie French Toast', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='499.jpg' WHERE ID=499;
UPDATE `Recipe` SET RecipeName='Ramen Foo Young', CookTime='12', DietType='TBD', IngredientCount='8', ImgURL='500.jpg' WHERE ID=500;
UPDATE `Recipe` SET RecipeName='Sausage and Egg Grilled Cheese', CookTime='10', DietType='TBD', IngredientCount='7', ImgURL='501.jpg' WHERE ID=501;
UPDATE `Recipe` SET RecipeName='Sausage Bites', CookTime='25', DietType='TBD', IngredientCount='9', ImgURL='502.jpg' WHERE ID=502;
UPDATE `Recipe` SET RecipeName='Sausage Casserole', CookTime='105', DietType='TBD', IngredientCount='9', ImgURL='503.jpg' WHERE ID=503;
UPDATE `Recipe` SET RecipeName='Sausage Gravy', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='504.jpg' WHERE ID=504;
UPDATE `Recipe` SET RecipeName='Sausage Hashbrown Casserole', CookTime='35', DietType='TBD', IngredientCount='7', ImgURL='505.jpg' WHERE ID=505;
UPDATE `Recipe` SET RecipeName='Sausage Muffins', CookTime='15', DietType='TBD', IngredientCount='4', ImgURL='506.jpg' WHERE ID=506;
UPDATE `Recipe` SET RecipeName='Sausage-Mushroom Quiche', CookTime='90', DietType='TBD', IngredientCount='14', ImgURL='' WHERE ID=507;
UPDATE `Recipe` SET RecipeName='Sausage Pancake Muffins', CookTime='20', DietType='TBD', IngredientCount='14', ImgURL='508.jpg' WHERE ID=508;
UPDATE `Recipe` SET RecipeName='Sausage Stuffed Biscuits', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='509.jpg' WHERE ID=509;
UPDATE `Recipe` SET RecipeName='Sausage Tot Casserole', CookTime='50', DietType='TBD', IngredientCount='9', ImgURL='510.jpg' WHERE ID=510;
UPDATE `Recipe` SET RecipeName='Scrambled Egg Sandwich', CookTime='8', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=511;
UPDATE `Recipe` SET RecipeName='Scrambled Eggs Cups', CookTime='25', DietType='TBD', IngredientCount='13', ImgURL='512.jpg' WHERE ID=512;
UPDATE `Recipe` SET RecipeName='Scratch Biscuits and Gravy', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='513.jpg' WHERE ID=513;
UPDATE `Recipe` SET RecipeName='Sheared Eggs', CookTime='15', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=514;
UPDATE `Recipe` SET RecipeName='Simple Banana Bread', CookTime='60', DietType='TBD', IngredientCount='8', ImgURL='515.jpg' WHERE ID=515;
UPDATE `Recipe` SET RecipeName='Simple BB', CookTime='7', DietType='TBD', IngredientCount='5', ImgURL='516.jpg' WHERE ID=516;
UPDATE `Recipe` SET RecipeName='Simple Egg Casserole', CookTime='45', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=517;
UPDATE `Recipe` SET RecipeName='Simple Scrambled Eggs', CookTime='10', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=518;
UPDATE `Recipe` SET RecipeName='Snack Eggs', CookTime='5', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=519;
UPDATE `Recipe` SET RecipeName='Sour Cream Pancakes', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='520.jpg' WHERE ID=520;
UPDATE `Recipe` SET RecipeName='Spaghetti Frittata', CookTime='35', DietType='TBD', IngredientCount='14', ImgURL='521.jpg' WHERE ID=521;
UPDATE `Recipe` SET RecipeName='Steak and Eggs', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=522;
UPDATE `Recipe` SET RecipeName='Stuffed Biscuits and Gravy', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='523.jpg' WHERE ID=523;
UPDATE `Recipe` SET RecipeName='Stuffed Breakfast Bread', CookTime='60', DietType='TBD', IngredientCount='13', ImgURL='524.jpg' WHERE ID=524;
UPDATE `Recipe` SET RecipeName='Stuffed Breakfast Potatoes', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='525.jpg' WHERE ID=525;
UPDATE `Recipe` SET RecipeName='Stuffed Breakfast Quesadilla', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='526.jpg' WHERE ID=526;
UPDATE `Recipe` SET RecipeName='Stuffed French Toast', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='527.jpg' WHERE ID=527;
UPDATE `Recipe` SET RecipeName='Sweet Breakfast Potatoes', CookTime='30', DietType='TBD', IngredientCount='14', ImgURL='528.jpg' WHERE ID=528;
UPDATE `Recipe` SET RecipeName='Sweet Gravy', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='529.jpg' WHERE ID=529;
UPDATE `Recipe` SET RecipeName='Sweet Potato Eggs', CookTime='15', DietType='TBD', IngredientCount='11', ImgURL='530.jpg' WHERE ID=530;
UPDATE `Recipe` SET RecipeName='Tater Tot Breakfast Casserole', CookTime='45', DietType='TBD', IngredientCount='7', ImgURL='531.jpg' WHERE ID=531;
UPDATE `Recipe` SET RecipeName='Texas Breakfast Casserole', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=532;
UPDATE `Recipe` SET RecipeName='Thanksgiving Leftover Cups', CookTime='35', DietType='TBD', IngredientCount='5', ImgURL='533.jpg' WHERE ID=533;
UPDATE `Recipe` SET RecipeName='Tomato Breakfast Sand', CookTime='10', DietType='TBD', IngredientCount='8', ImgURL='534.jpg' WHERE ID=534;
UPDATE `Recipe` SET RecipeName='Ugly Shredded Wheat', CookTime='10', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=535;
UPDATE `Recipe` SET RecipeName='Ultimate Breakfast Biscuits', CookTime='25', DietType='TBD', IngredientCount='8', ImgURL='536.jpg' WHERE ID=536;
UPDATE `Recipe` SET RecipeName='Veggie Quiches', CookTime='25', DietType='TBD', IngredientCount='7', ImgURL='537.jpg' WHERE ID=537;
UPDATE `Recipe` SET RecipeName='Waffles Wow!', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='538.jpg' WHERE ID=538;
UPDATE `Recipe` SET RecipeName='A Better Pulled Pork', CookTime='360', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=539;
UPDATE `Recipe` SET RecipeName='Another Crock Pot Breakfast Casserole', CookTime='240', DietType='TBD', IngredientCount='12', ImgURL='540.jpg' WHERE ID=540;
UPDATE `Recipe` SET RecipeName='Another Crock Pot Lasagna', CookTime='240', DietType='TBD', IngredientCount='7', ImgURL='541.jpg' WHERE ID=541;
UPDATE `Recipe` SET RecipeName='Another Slow Cooker Philly', CookTime='360', DietType='TBD', IngredientCount='12', ImgURL='542.jpg' WHERE ID=542;
UPDATE `Recipe` SET RecipeName='Bacon Swiss Chicken and Mushroom', CookTime='240', DietType='TBD', IngredientCount='5', ImgURL='543.jpg' WHERE ID=543;
UPDATE `Recipe` SET RecipeName='Barbacoa', CookTime='240', DietType='TBD', IngredientCount='10', ImgURL='' WHERE ID=544;
UPDATE `Recipe` SET RecipeName='Beef Boogie Woogie', CookTime='480', DietType='TBD', IngredientCount='6', ImgURL='545.jpg' WHERE ID=545;
UPDATE `Recipe` SET RecipeName='Beef Stew', CookTime='240', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=546;
UPDATE `Recipe` SET RecipeName='Best Gameday Meatballs', CookTime='360', DietType='TBD', IngredientCount='9', ImgURL='547.jpg' WHERE ID=547;
UPDATE `Recipe` SET RecipeName='Buffalo Chicken Meatballs', CookTime='140', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=548;
UPDATE `Recipe` SET RecipeName='Cabbage Patch Soup', CookTime='240', DietType='TBD', IngredientCount='15', ImgURL='549.jpg' WHERE ID=549;
UPDATE `Recipe` SET RecipeName='Chicken Mississippi Roast', CookTime='360', DietType='TBD', IngredientCount='11', ImgURL='550.jpg' WHERE ID=550;
UPDATE `Recipe` SET RecipeName='Chicken Potato Pot Pie', CookTime='360', DietType='TBD', IngredientCount='10', ImgURL='551.jpg' WHERE ID=551;
UPDATE `Recipe` SET RecipeName='Chicken Taco Soup', CookTime='240', DietType='TBD', IngredientCount='10', ImgURL='552.jpg' WHERE ID=552;
UPDATE `Recipe` SET RecipeName='Chicken Tater Tot Casserole', CookTime='360', DietType='TBD', IngredientCount='9', ImgURL='553.jpg' WHERE ID=553;
UPDATE `Recipe` SET RecipeName='Crock Brocc and Cheese', CookTime='120', DietType='TBD', IngredientCount='8', ImgURL='554.jpg' WHERE ID=554;
UPDATE `Recipe` SET RecipeName='Crock Pot Bacon Apple Chicken', CookTime='480', DietType='TBD', IngredientCount='6', ImgURL='555.jpg' WHERE ID=555;
UPDATE `Recipe` SET RecipeName='Crock Pot BBQ Beef Roast', CookTime='360', DietType='TBD', IngredientCount='7', ImgURL='556.jpg' WHERE ID=556;
UPDATE `Recipe` SET RecipeName='Crock Pot Beef and Broccoli', CookTime='240', DietType='TBD', IngredientCount='12', ImgURL='557.jpg' WHERE ID=557;
UPDATE `Recipe` SET RecipeName='Crock Pot Beef Tacos', CookTime='480', DietType='TBD', IngredientCount='16', ImgURL='558.jpg' WHERE ID=558;
UPDATE `Recipe` SET RecipeName='Crock Pot Buffalo Chicken Pasta', CookTime='240', DietType='TBD', IngredientCount='13', ImgURL='559.jpg' WHERE ID=559;
UPDATE `Recipe` SET RecipeName='Crock Pot Cabbage Rolls', CookTime='360', DietType='TBD', IngredientCount='0', ImgURL='560.jpg' WHERE ID=560;
UPDATE `Recipe` SET RecipeName='Crock Pot Cashew Stir Fry', CookTime='240', DietType='TBD', IngredientCount='19', ImgURL='561.jpg' WHERE ID=561;
UPDATE `Recipe` SET RecipeName='Crock Pot Cheeseburger Dip', CookTime='120', DietType='TBD', IngredientCount='7', ImgURL='562.jpg' WHERE ID=562;
UPDATE `Recipe` SET RecipeName='Crock Pot Cheesy Bacon Potatoes', CookTime='240', DietType='TBD', IngredientCount='8', ImgURL='563.jpg' WHERE ID=563;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken and Brocc', CookTime='180', DietType='TBD', IngredientCount='10', ImgURL='564.jpg' WHERE ID=564;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken and Stuffing', CookTime='240', DietType='TBD', IngredientCount='6', ImgURL='565.jpg' WHERE ID=565;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken and Veggies', CookTime='360', DietType='TBD', IngredientCount='9', ImgURL='566.jpg' WHERE ID=566;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken Chili', CookTime='480', DietType='TBD', IngredientCount='9', ImgURL='567.jpg' WHERE ID=567;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken Noodle', CookTime='480', DietType='TBD', IngredientCount='13', ImgURL='568.jpg' WHERE ID=568;
UPDATE `Recipe` SET RecipeName='Crock Pot Chicken Parmesan', CookTime='300', DietType='TBD', IngredientCount='14', ImgURL='569.jpg' WHERE ID=569;
UPDATE `Recipe` SET RecipeName='Crock Pot Chili Mac and Cheese', CookTime='240', DietType='TBD', IngredientCount='14', ImgURL='570.jpg' WHERE ID=570;
UPDATE `Recipe` SET RecipeName='Crock Pot Collard Greens', CookTime='120', DietType='TBD', IngredientCount='8', ImgURL='571.jpg' WHERE ID=571;
UPDATE `Recipe` SET RecipeName='Crock Pot Fiesta Chicken', CookTime='360', DietType='TBD', IngredientCount='9', ImgURL='572.jpg' WHERE ID=572;
UPDATE `Recipe` SET RecipeName='Crock Pot French Dip', CookTime='300', DietType='TBD', IngredientCount='10', ImgURL='573.jpg' WHERE ID=573;
UPDATE `Recipe` SET RecipeName='Crock Pot Garlic Mashed Potatoes', CookTime='240', DietType='TBD', IngredientCount='8', ImgURL='574.jpg' WHERE ID=574;
UPDATE `Recipe` SET RecipeName='Crock Pot Gumbo', CookTime='300', DietType='TBD', IngredientCount='6', ImgURL='575.jpg' WHERE ID=575;
UPDATE `Recipe` SET RecipeName='Crock Pot Hashbrown Casserole', CookTime='180', DietType='TBD', IngredientCount='9', ImgURL='576.jpg' WHERE ID=576;
UPDATE `Recipe` SET RecipeName='Crock Pot Italian Beef', CookTime='480', DietType='TBD', IngredientCount='9', ImgURL='577.jpg' WHERE ID=577;
UPDATE `Recipe` SET RecipeName='Crock Pot Lime Chicken Tacos', CookTime='240', DietType='TBD', IngredientCount='5', ImgURL='578.jpg' WHERE ID=578;
UPDATE `Recipe` SET RecipeName='Crock Pot Parmesan Potatoes', CookTime='240', DietType='TBD', IngredientCount='9', ImgURL='579.jpg' WHERE ID=579;
UPDATE `Recipe` SET RecipeName='Crock Pot Pesto Chicken Pasta', CookTime='360', DietType='TBD', IngredientCount='7', ImgURL='580.jpg' WHERE ID=580;
UPDATE `Recipe` SET RecipeName='Crock Pot Pizza Pasta', CookTime='120', DietType='TBD', IngredientCount='5', ImgURL='581.jpg' WHERE ID=581;
UPDATE `Recipe` SET RecipeName='Crock Pot Salisbury Meatballs', CookTime='360', DietType='TBD', IngredientCount='12', ImgURL='582.jpg' WHERE ID=582;
UPDATE `Recipe` SET RecipeName='Crock Pot Scalloped Potatoes', CookTime='480', DietType='TBD', IngredientCount='0', ImgURL='583.jpg' WHERE ID=583;
UPDATE `Recipe` SET RecipeName='Crock Pot Sesame Chicken', CookTime='360', DietType='TBD', IngredientCount='3', ImgURL='584.jpg' WHERE ID=584;
UPDATE `Recipe` SET RecipeName='Crock Pot Sloppy Joes', CookTime='240', DietType='TBD', IngredientCount='16', ImgURL='585.jpg' WHERE ID=585;
UPDATE `Recipe` SET RecipeName='Crock Pot Spicy Cheeseburger Dip', CookTime='120', DietType='TBD', IngredientCount='6', ImgURL='586.jpg' WHERE ID=586;
UPDATE `Recipe` SET RecipeName='Crock Pot Spin Dip', CookTime='135', DietType='TBD', IngredientCount='13', ImgURL='587.jpg' WHERE ID=587;
UPDATE `Recipe` SET RecipeName='Crock Pot Stuffed Peppers', CookTime='360', DietType='TBD', IngredientCount='10', ImgURL='588.jpg' WHERE ID=588;
UPDATE `Recipe` SET RecipeName='Crock Pot Taco Lasagna', CookTime='240', DietType='TBD', IngredientCount='15', ImgURL='589.jpg' WHERE ID=589;
UPDATE `Recipe` SET RecipeName='Crock Pot Tamales', CookTime='180', DietType='TBD', IngredientCount='3', ImgURL='590.jpg' WHERE ID=590;
UPDATE `Recipe` SET RecipeName='Crockpot Chicken Tortilla Soup Recipe', CookTime='480', DietType='TBD', IngredientCount='16', ImgURL='' WHERE ID=591;
UPDATE `Recipe` SET RecipeName='Crockpot Orange Chicken', CookTime='240', DietType='TBD', IngredientCount='7', ImgURL='592.jpg' WHERE ID=592;
UPDATE `Recipe` SET RecipeName='Easy Buffalo Chicken Dip', CookTime='120', DietType='TBD', IngredientCount='8', ImgURL='593.jpg' WHERE ID=593;
UPDATE `Recipe` SET RecipeName='Easy Cheesy Ham and Potatoes', CookTime='120', DietType='TBD', IngredientCount='7', ImgURL='594.jpg' WHERE ID=594;
UPDATE `Recipe` SET RecipeName='Easy Chicken And Rice Soup In The Crock Pot', CookTime='240', DietType='TBD', IngredientCount='14', ImgURL='595.jpg' WHERE ID=595;
UPDATE `Recipe` SET RecipeName='Easy Coca Cola Cake', CookTime='120', DietType='TBD', IngredientCount='4', ImgURL='596.jpg' WHERE ID=596;
UPDATE `Recipe` SET RecipeName='Easy Crock Pot Buffalo Chicken Pasta', CookTime='240', DietType='TBD', IngredientCount='14', ImgURL='597.jpg' WHERE ID=597;
UPDATE `Recipe` SET RecipeName='Easy Crock Pot Candy', CookTime='120', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=598;
UPDATE `Recipe` SET RecipeName='Easy Crock Pot Chicken Enchiladas', CookTime='240', DietType='TBD', IngredientCount='12', ImgURL='599.jpg' WHERE ID=599;
UPDATE `Recipe` SET RecipeName='Easy Crock Pot Fajitas', CookTime='180', DietType='TBD', IngredientCount='10', ImgURL='600.jpg' WHERE ID=600;
UPDATE `Recipe` SET RecipeName='Easy Salsa Chicken', CookTime='240', DietType='TBD', IngredientCount='9', ImgURL='601.jpg' WHERE ID=601;
UPDATE `Recipe` SET RecipeName='Easy Slow Cooker Sweet Chicken', CookTime='240', DietType='TBD', IngredientCount='7', ImgURL='602.jpg' WHERE ID=602;
UPDATE `Recipe` SET RecipeName='Easy White Chicken Chili', CookTime='180', DietType='TBD', IngredientCount='16', ImgURL='603.jpg' WHERE ID=603;
UPDATE `Recipe` SET RecipeName='Hawaiian Chicken', CookTime='360', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=604;
UPDATE `Recipe` SET RecipeName='Honey B Broccoli cheese and potato soup', CookTime='200', DietType='TBD', IngredientCount='11', ImgURL='605.jpg' WHERE ID=605;
UPDATE `Recipe` SET RecipeName='HOT Hot Dogs', CookTime='120', DietType='TBD', IngredientCount='2', ImgURL='606.jpg' WHERE ID=606;
UPDATE `Recipe` SET RecipeName='Liver and Onions', CookTime='180', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=607;
UPDATE `Recipe` SET RecipeName='Mushroom Onion Pork Chops', CookTime='1', DietType='TBD', IngredientCount='8', ImgURL='608.jpg' WHERE ID=608;
UPDATE `Recipe` SET RecipeName='Pasta Fagiolio', CookTime='480', DietType='TBD', IngredientCount='12', ImgURL='' WHERE ID=609;
UPDATE `Recipe` SET RecipeName='Pineapple Teriyaki Meatballs', CookTime='45', DietType='TBD', IngredientCount='5', ImgURL='610.jpg' WHERE ID=610;
UPDATE `Recipe` SET RecipeName='Pulled Pork', CookTime='360', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=611;
UPDATE `Recipe` SET RecipeName='Red Velvet Brownies', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='612.jpg' WHERE ID=612;
UPDATE `Recipe` SET RecipeName='Slow Cashew Chicken', CookTime='180', DietType='TBD', IngredientCount='17', ImgURL='613.jpg' WHERE ID=613;
UPDATE `Recipe` SET RecipeName='Slow Cooker Bacon Chicken Tots', CookTime='240', DietType='TBD', IngredientCount='9', ImgURL='614.jpg' WHERE ID=614;
UPDATE `Recipe` SET RecipeName='Slow Cooker Bacon Ranch Chicken', CookTime='360', DietType='TBD', IngredientCount='5', ImgURL='615.jpg' WHERE ID=615;
UPDATE `Recipe` SET RecipeName='Slow Cooker Baked Potatoes', CookTime='540', DietType='TBD', IngredientCount='5', ImgURL='616.jpg' WHERE ID=616;
UPDATE `Recipe` SET RecipeName='Slow Cooker Balsamic Chicken', CookTime='240', DietType='TBD', IngredientCount='12', ImgURL='617.jpg' WHERE ID=617;
UPDATE `Recipe` SET RecipeName='Slow Cooker Balsamic Pork', CookTime='360', DietType='TBD', IngredientCount='9', ImgURL='618.jpg' WHERE ID=618;
UPDATE `Recipe` SET RecipeName='Slow Cooker BBQ Beans', CookTime='540', DietType='TBD', IngredientCount='13', ImgURL='619.jpg' WHERE ID=619;
UPDATE `Recipe` SET RecipeName='Slow Cooker Breakfast Casserole', CookTime='360', DietType='TBD', IngredientCount='14', ImgURL='620.jpg' WHERE ID=620;
UPDATE `Recipe` SET RecipeName='Slow Cooker Buffalo Chicken', CookTime='360', DietType='TBD', IngredientCount='3', ImgURL='621.jpg' WHERE ID=621;
UPDATE `Recipe` SET RecipeName='Slow Cooker Cabbage Rolls', CookTime='360', DietType='TBD', IngredientCount='10', ImgURL='622.jpg' WHERE ID=622;
UPDATE `Recipe` SET RecipeName='Slow Cooker Carnitas', CookTime='240', DietType='TBD', IngredientCount='10', ImgURL='623.jpg' WHERE ID=623;
UPDATE `Recipe` SET RecipeName='Slow Cooker Cheesy Chicken', CookTime='360', DietType='TBD', IngredientCount='10', ImgURL='624.jpg' WHERE ID=624;
UPDATE `Recipe` SET RecipeName='Slow Cooker Cheesy Garlic Chicken', CookTime='180', DietType='TBD', IngredientCount='11', ImgURL='625.jpg' WHERE ID=625;
UPDATE `Recipe` SET RecipeName='Slow Cooker Cheesy Philly', CookTime='240', DietType='TBD', IngredientCount='10', ImgURL='626.jpg' WHERE ID=626;
UPDATE `Recipe` SET RecipeName='Slow Cooker Chicken and Veggies', CookTime='240', DietType='TBD', IngredientCount='9', ImgURL='627.jpg' WHERE ID=627;
UPDATE `Recipe` SET RecipeName='Slow Cooker Chicken Fettuccine', CookTime='90', DietType='TBD', IngredientCount='6', ImgURL='628.jpg' WHERE ID=628;
UPDATE `Recipe` SET RecipeName='Slow Cooker Chicken Parmesan', CookTime='360', DietType='TBD', IngredientCount='9', ImgURL='629.jpg' WHERE ID=629;
UPDATE `Recipe` SET RecipeName='Slow Cooker Chicken Taquitos', CookTime='300', DietType='TBD', IngredientCount='8', ImgURL='630.jpg' WHERE ID=630;
UPDATE `Recipe` SET RecipeName='Slow Cooker Enchiladas', CookTime='150', DietType='TBD', IngredientCount='3', ImgURL='631.jpg' WHERE ID=631;
UPDATE `Recipe` SET RecipeName='Slow Cooker Mac and Cheese', CookTime='120', DietType='TBD', IngredientCount='6', ImgURL='632.jpg' WHERE ID=632;
UPDATE `Recipe` SET RecipeName='Slow Cooker Parmesan Potatoes', CookTime='240', DietType='TBD', IngredientCount='7', ImgURL='633.jpg' WHERE ID=633;
UPDATE `Recipe` SET RecipeName='Slow Cooker Philly', CookTime='180', DietType='TBD', IngredientCount='9', ImgURL='634.jpg' WHERE ID=634;
UPDATE `Recipe` SET RecipeName='Slow Cooker Popper Chicken', CookTime='360', DietType='TBD', IngredientCount='11', ImgURL='635.jpg' WHERE ID=635;
UPDATE `Recipe` SET RecipeName='Slow Cooker Sausage and Potatoes', CookTime='420', DietType='TBD', IngredientCount='7', ImgURL='636.jpg' WHERE ID=636;
UPDATE `Recipe` SET RecipeName='Slow Cooker Split Pea Soup', CookTime='300', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=637;
UPDATE `Recipe` SET RecipeName='Slow Cooker Sweet Chicken', CookTime='300', DietType='TBD', IngredientCount='11', ImgURL='638.jpg' WHERE ID=638;
UPDATE `Recipe` SET RecipeName='Slow Cooker Swiss Bacon Mushroom Chicken', CookTime='300', DietType='TBD', IngredientCount='5', ImgURL='639.jpg' WHERE ID=639;
UPDATE `Recipe` SET RecipeName='Slow Cooker Taco Pasta', CookTime='360', DietType='TBD', IngredientCount='15', ImgURL='640.jpg' WHERE ID=640;
UPDATE `Recipe` SET RecipeName='Slow Cooker Ziti', CookTime='150', DietType='TBD', IngredientCount='7', ImgURL='641.jpg' WHERE ID=641;
UPDATE `Recipe` SET RecipeName='Slow Hamburger and Potatoes', CookTime='480', DietType='TBD', IngredientCount='8', ImgURL='642.jpg' WHERE ID=642;
UPDATE `Recipe` SET RecipeName='Southern Potato Soup', CookTime='8', DietType='TBD', IngredientCount='7', ImgURL='643.jpg' WHERE ID=643;
UPDATE `Recipe` SET RecipeName='Spicy Chicken and Rice', CookTime='240', DietType='TBD', IngredientCount='11', ImgURL='644.jpg' WHERE ID=644;
UPDATE `Recipe` SET RecipeName='Sriracha Chicken Tacos', CookTime='180', DietType='TBD', IngredientCount='8', ImgURL='645.jpg' WHERE ID=645;
UPDATE `Recipe` SET RecipeName='Steak n Gravy', CookTime='120', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=646;
UPDATE `Recipe` SET RecipeName='Stupid Easy Chicken', CookTime='1', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=647;
UPDATE `Recipe` SET RecipeName='Sweet Parmesan Pork Roast', CookTime='360', DietType='TBD', IngredientCount='12', ImgURL='648.jpg' WHERE ID=648;
UPDATE `Recipe` SET RecipeName='Sweet Spicy Sausage', CookTime='90', DietType='TBD', IngredientCount='12', ImgURL='649.jpg' WHERE ID=649;
UPDATE `Recipe` SET RecipeName='Tortilla Soup', CookTime='120', DietType='TBD', IngredientCount='14', ImgURL='650.jpg' WHERE ID=650;
UPDATE `Recipe` SET RecipeName='3-2-1 Cake -Mix for Quick Fix', CookTime='5', DietType='TBD', IngredientCount='1', ImgURL='651.jpg' WHERE ID=651;
UPDATE `Recipe` SET RecipeName='3 Ingredient Banana Bread', CookTime='50', DietType='TBD', IngredientCount='2', ImgURL='652.jpg' WHERE ID=652;
UPDATE `Recipe` SET RecipeName='3-Ingredient PB Cookies', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='653.jpg' WHERE ID=653;
UPDATE `Recipe` SET RecipeName='Almond Joy Brownies', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=654;
UPDATE `Recipe` SET RecipeName='Almond Joy Dessert', CookTime='10', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=655;
UPDATE `Recipe` SET RecipeName='Almond Orange Macs', CookTime='25', DietType='TBD', IngredientCount='5', ImgURL='656.jpg' WHERE ID=656;
UPDATE `Recipe` SET RecipeName='Amazing Lemon Bars', CookTime='40', DietType='TBD', IngredientCount='9', ImgURL='657.jpg' WHERE ID=657;
UPDATE `Recipe` SET RecipeName='Another Chocolate Lasagna', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='658.jpg' WHERE ID=658;
UPDATE `Recipe` SET RecipeName='Another Cinnamon Roll Cake', CookTime='90', DietType='TBD', IngredientCount='11', ImgURL='659.jpg' WHERE ID=659;
UPDATE `Recipe` SET RecipeName='Another Deep Dish Cookie', CookTime='40', DietType='TBD', IngredientCount='11', ImgURL='660.jpg' WHERE ID=660;
UPDATE `Recipe` SET RecipeName='Apple Cobbler - Easy', CookTime='60', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=661;
UPDATE `Recipe` SET RecipeName='Apple Crisp', CookTime='50', DietType='TBD', IngredientCount='5', ImgURL='662.jpg' WHERE ID=662;
UPDATE `Recipe` SET RecipeName='Apple Donuts', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='663.jpg' WHERE ID=663;
UPDATE `Recipe` SET RecipeName='Apple Empanadas', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=664;
UPDATE `Recipe` SET RecipeName='Apple Fritter Cake', CookTime='60', DietType='TBD', IngredientCount='15', ImgURL='665.jpg' WHERE ID=665;
UPDATE `Recipe` SET RecipeName='Apple Knockers', CookTime='40', DietType='TBD', IngredientCount='13', ImgURL='' WHERE ID=666;
UPDATE `Recipe` SET RecipeName='Apple Muffins', CookTime='40', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=667;
UPDATE `Recipe` SET RecipeName='Apple Pie Bars', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='668.jpg' WHERE ID=668;
UPDATE `Recipe` SET RecipeName='Apple Pie Bombs', CookTime='10', DietType='TBD', IngredientCount='9', ImgURL='669.jpg' WHERE ID=669;
UPDATE `Recipe` SET RecipeName='Apple Pie Cookies', CookTime='45', DietType='TBD', IngredientCount='8', ImgURL='670.jpg' WHERE ID=670;
UPDATE `Recipe` SET RecipeName='Apple Pie Crescent Wraps', CookTime='35', DietType='TBD', IngredientCount='6', ImgURL='671.jpg' WHERE ID=671;
UPDATE `Recipe` SET RecipeName='Apple Pie Egg Rolls', CookTime='20', DietType='TBD', IngredientCount='8', ImgURL='672.jpg' WHERE ID=672;
UPDATE `Recipe` SET RecipeName='Apple Pie in a cup', CookTime='5', DietType='TBD', IngredientCount='4', ImgURL='673.jpg' WHERE ID=673;
UPDATE `Recipe` SET RecipeName='Apple Pie Rolls', CookTime='25', DietType='TBD', IngredientCount='4', ImgURL='674.jpg' WHERE ID=674;
UPDATE `Recipe` SET RecipeName='Apple Pie Tacos', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='675.jpg' WHERE ID=675;
UPDATE `Recipe` SET RecipeName='Apple Rose Tart', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='676.jpg' WHERE ID=676;
UPDATE `Recipe` SET RecipeName='Applesauce Brownies', CookTime='25', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=677;
UPDATE `Recipe` SET RecipeName='April Fools "Chicken Nuggets"', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='678.jpg' WHERE ID=678;
UPDATE `Recipe` SET RecipeName='Avocado Pie', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='679.jpg' WHERE ID=679;
UPDATE `Recipe` SET RecipeName='Awesome Banana Pudding', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='680.jpg' WHERE ID=680;
UPDATE `Recipe` SET RecipeName='Awesome Gooey Brownies', CookTime='35', DietType='TBD', IngredientCount='11', ImgURL='681.jpg' WHERE ID=681;
UPDATE `Recipe` SET RecipeName='Awesome Smores', CookTime='180', DietType='TBD', IngredientCount='7', ImgURL='682.jpg' WHERE ID=682;
UPDATE `Recipe` SET RecipeName='Bacon Cheesecake', CookTime='80', DietType='TBD', IngredientCount='9', ImgURL='683.jpg' WHERE ID=683;
UPDATE `Recipe` SET RecipeName='Bacon Cinnamon Rolls', CookTime='20', DietType='TBD', IngredientCount='2', ImgURL='684.jpg' WHERE ID=684;
UPDATE `Recipe` SET RecipeName='Bacon Monkey Bread', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='685.jpg' WHERE ID=685;
UPDATE `Recipe` SET RecipeName='Baileys Dark Chocolate Cake', CookTime='30', DietType='TBD', IngredientCount='1', ImgURL='' WHERE ID=686;
UPDATE `Recipe` SET RecipeName='Baked Blooming Apple', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='687.jpg' WHERE ID=687;
UPDATE `Recipe` SET RecipeName='Banana Berry Pie', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=688;
UPDATE `Recipe` SET RecipeName='Banana Boat', CookTime='7', DietType='TBD', IngredientCount='4', ImgURL='689.jpg' WHERE ID=689;
UPDATE `Recipe` SET RecipeName='Banana Bread in a Jar', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='690.jpg' WHERE ID=690;
UPDATE `Recipe` SET RecipeName='Banana Coconut Upsidedown', CookTime='45', DietType='TBD', IngredientCount='10', ImgURL='691.jpg' WHERE ID=691;
UPDATE `Recipe` SET RecipeName='Banana Crumb Bread', CookTime='50', DietType='TBD', IngredientCount='10', ImgURL='692.jpg' WHERE ID=692;
UPDATE `Recipe` SET RecipeName='Banana Pudding Casserole', CookTime='240', DietType='TBD', IngredientCount='6', ImgURL='693.jpg' WHERE ID=693;
UPDATE `Recipe` SET RecipeName='Banana Sushi Rolls', CookTime='10', DietType='TBD', IngredientCount='11', ImgURL='694.jpg' WHERE ID=694;
UPDATE `Recipe` SET RecipeName='Banana Wheat Muffins', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='695.jpg' WHERE ID=695;
UPDATE `Recipe` SET RecipeName='Basic Sponge Cake', CookTime='35', DietType='TBD', IngredientCount='5', ImgURL='696.jpg' WHERE ID=696;
UPDATE `Recipe` SET RecipeName='Best Banana Bread', CookTime='60', DietType='TBD', IngredientCount='2', ImgURL='697.jpg' WHERE ID=697;
UPDATE `Recipe` SET RecipeName='Best Best Brownies', CookTime='45', DietType='TBD', IngredientCount='8', ImgURL='698.jpg' WHERE ID=698;
UPDATE `Recipe` SET RecipeName='Best Buttermilk Pie', CookTime='60', DietType='TBD', IngredientCount='8', ImgURL='699.jpg' WHERE ID=699;
UPDATE `Recipe` SET RecipeName='Best Oatmeal Cookies Ever', CookTime='13', DietType='TBD', IngredientCount='12', ImgURL='700.jpg' WHERE ID=700;
UPDATE `Recipe` SET RecipeName='Best Peach Cobbler!', CookTime='50', DietType='TBD', IngredientCount='10', ImgURL='701.jpg' WHERE ID=701;
UPDATE `Recipe` SET RecipeName='Better For You Cookies', CookTime='15', DietType='TBD', IngredientCount='12', ImgURL='702.jpg' WHERE ID=702;
UPDATE `Recipe` SET RecipeName='Blueberries Foster', CookTime='5', DietType='TBD', IngredientCount='7', ImgURL='703.jpg' WHERE ID=703;
UPDATE `Recipe` SET RecipeName='Blueberry Cream Cheese Muffins', CookTime='25', DietType='TBD', IngredientCount='4', ImgURL='704.jpg' WHERE ID=704;
UPDATE `Recipe` SET RecipeName='Boston Cream Cupcakes', CookTime='45', DietType='TBD', IngredientCount='4', ImgURL='705.jpg' WHERE ID=705;
UPDATE `Recipe` SET RecipeName='Boston Cream Pie', CookTime='75', DietType='TBD', IngredientCount='7', ImgURL='706.jpg' WHERE ID=706;
UPDATE `Recipe` SET RecipeName='Brownie Bowls', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='707.jpg' WHERE ID=707;
UPDATE `Recipe` SET RecipeName='Brownie in a cup', CookTime='0', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=708;
UPDATE `Recipe` SET RecipeName='Brownie Pizza', CookTime='160', DietType='TBD', IngredientCount='10', ImgURL='709.jpg' WHERE ID=709;
UPDATE `Recipe` SET RecipeName='Brownie Trifle', CookTime='60', DietType='TBD', IngredientCount='5', ImgURL='710.jpg' WHERE ID=710;
UPDATE `Recipe` SET RecipeName='Brownies (standard)', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='711.jpg' WHERE ID=711;
UPDATE `Recipe` SET RecipeName='Cake Batter Fudge', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='712.jpg' WHERE ID=712;
UPDATE `Recipe` SET RecipeName='Cake in a blink', CookTime='5', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=713;
UPDATE `Recipe` SET RecipeName='Candy Bacon', CookTime='35', DietType='TBD', IngredientCount='7', ImgURL='714.jpg' WHERE ID=714;
UPDATE `Recipe` SET RecipeName='Candy Bar Apple Salad', CookTime='15', DietType='TBD', IngredientCount='5', ImgURL='715.jpg' WHERE ID=715;
UPDATE `Recipe` SET RecipeName='Caramel Apple Dip', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='716.jpg' WHERE ID=716;
UPDATE `Recipe` SET RecipeName='Caramel Apple Trifle', CookTime='40', DietType='TBD', IngredientCount='5', ImgURL='717.jpg' WHERE ID=717;
UPDATE `Recipe` SET RecipeName='Caramel Pretzel Brownies', CookTime='45', DietType='TBD', IngredientCount='12', ImgURL='718.jpg' WHERE ID=718;
UPDATE `Recipe` SET RecipeName='Carmel Brownies', CookTime='25', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=719;
UPDATE `Recipe` SET RecipeName='Champagne Cake in a Mug', CookTime='10', DietType='TBD', IngredientCount='7', ImgURL='720.jpg' WHERE ID=720;
UPDATE `Recipe` SET RecipeName='Cheerio Treats', CookTime='5', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=721;
UPDATE `Recipe` SET RecipeName='Cheesecake Brownies', CookTime='40', DietType='TBD', IngredientCount='13', ImgURL='722.jpg' WHERE ID=722;
UPDATE `Recipe` SET RecipeName='Cheesecake Chimichangas', CookTime='30', DietType='TBD', IngredientCount='12', ImgURL='723.jpg' WHERE ID=723;
UPDATE `Recipe` SET RecipeName='Cheesecake Cookies', CookTime='45', DietType='TBD', IngredientCount='14', ImgURL='724.jpg' WHERE ID=724;
UPDATE `Recipe` SET RecipeName='Cheesecake Strawberry', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='725.jpg' WHERE ID=725;
UPDATE `Recipe` SET RecipeName='Cherry Fluff', CookTime='10', DietType='TBD', IngredientCount='4', ImgURL='726.jpg' WHERE ID=726;
UPDATE `Recipe` SET RecipeName='Chewy Chocolate Chip Cookies', CookTime='15', DietType='TBD', IngredientCount='10', ImgURL='727.jpg' WHERE ID=727;
UPDATE `Recipe` SET RecipeName='Chewy Chocolate Cookies', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='728.jpg' WHERE ID=728;
UPDATE `Recipe` SET RecipeName='Chocolate Bacon and Eggs', CookTime='15', DietType='TBD', IngredientCount='2', ImgURL='729.jpg' WHERE ID=729;
UPDATE `Recipe` SET RecipeName='Chocolate Banana Wontons', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='730.jpg' WHERE ID=730;
UPDATE `Recipe` SET RecipeName='Chocolate Caramel Mug', CookTime='2', DietType='TBD', IngredientCount='9', ImgURL='731.jpg' WHERE ID=731;
UPDATE `Recipe` SET RecipeName='Chocolate Chess Pie', CookTime='40', DietType='TBD', IngredientCount='6', ImgURL='732.jpg' WHERE ID=732;
UPDATE `Recipe` SET RecipeName='Chocolate Chip Cookie Pie', CookTime='20', DietType='TBD', IngredientCount='9', ImgURL='733.jpg' WHERE ID=733;
UPDATE `Recipe` SET RecipeName='Chocolate Chip Crunchies', CookTime='17', DietType='TBD', IngredientCount='12', ImgURL='' WHERE ID=734;
UPDATE `Recipe` SET RecipeName='Chocolate Chip Oreo Cookies', CookTime='30', DietType='TBD', IngredientCount='10', ImgURL='735.jpg' WHERE ID=735;
UPDATE `Recipe` SET RecipeName='Chocolate Chip Pumpkin Bread', CookTime='50', DietType='TBD', IngredientCount='13', ImgURL='736.jpg' WHERE ID=736;
UPDATE `Recipe` SET RecipeName='Chocolate Chunk Muffins', CookTime='30', DietType='TBD', IngredientCount='16', ImgURL='737.jpg' WHERE ID=737;
UPDATE `Recipe` SET RecipeName='Chocolate Empanadas', CookTime='30', DietType='TBD', IngredientCount='3', ImgURL='738.jpg' WHERE ID=738;
UPDATE `Recipe` SET RecipeName='Chocolate Gooey Cake', CookTime='50', DietType='TBD', IngredientCount='6', ImgURL='739.jpg' WHERE ID=739;
UPDATE `Recipe` SET RecipeName='Chocolate Heaven Cake', CookTime='45', DietType='TBD', IngredientCount='0', ImgURL='740.jpg' WHERE ID=740;
UPDATE `Recipe` SET RecipeName='Chocolate Krispies', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='741.jpg' WHERE ID=741;
UPDATE `Recipe` SET RecipeName='Chocolate Lasagna', CookTime='90', DietType='TBD', IngredientCount='9', ImgURL='742.jpg' WHERE ID=742;
UPDATE `Recipe` SET RecipeName='Chocolate Lava Cake', CookTime='180', DietType='TBD', IngredientCount='8', ImgURL='743.jpg' WHERE ID=743;
UPDATE `Recipe` SET RecipeName='Chocolate Mousse', CookTime='5', DietType='TBD', IngredientCount='2', ImgURL='744.jpg' WHERE ID=744;
UPDATE `Recipe` SET RecipeName='Chocolate-Oatmeal cookies', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=745;
UPDATE `Recipe` SET RecipeName='Chocolate PB Balls', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='746.jpg' WHERE ID=746;
UPDATE `Recipe` SET RecipeName='Chocolate Peanut Butter Bars', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=747;
UPDATE `Recipe` SET RecipeName='Chocolate Pumpkin Pudding', CookTime='60', DietType='TBD', IngredientCount='10', ImgURL='748.jpg' WHERE ID=748;
UPDATE `Recipe` SET RecipeName='Chocolate Quesadillas', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='749.jpg' WHERE ID=749;
UPDATE `Recipe` SET RecipeName='Chocolate Sorbet easy', CookTime='200', DietType='TBD', IngredientCount='3', ImgURL='750.jpg' WHERE ID=750;
UPDATE `Recipe` SET RecipeName='Chocolate Tacos', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='751.jpg' WHERE ID=751;
UPDATE `Recipe` SET RecipeName='Christmas Cookie Pinwheels', CookTime='45', DietType='TBD', IngredientCount='6', ImgURL='752.jpg' WHERE ID=752;
UPDATE `Recipe` SET RecipeName='Churro Bites', CookTime='25', DietType='TBD', IngredientCount='10', ImgURL='753.jpg' WHERE ID=753;
UPDATE `Recipe` SET RecipeName='Churro Cheesecake', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='754.jpg' WHERE ID=754;
UPDATE `Recipe` SET RecipeName='Churro chips', CookTime='2', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=755;
UPDATE `Recipe` SET RecipeName='Cinnabon Rolls', CookTime='80', DietType='TBD', IngredientCount='12', ImgURL='756.jpg' WHERE ID=756;
UPDATE `Recipe` SET RecipeName='Cinnamon Cream Cheese Crescents', CookTime='30', DietType='TBD', IngredientCount='3', ImgURL='757.jpg' WHERE ID=757;
UPDATE `Recipe` SET RecipeName='Cinnamon Dessert Tacos', CookTime='10', DietType='TBD', IngredientCount='12', ImgURL='758.jpg' WHERE ID=758;
UPDATE `Recipe` SET RecipeName='Cinnamon Heart Rolls', CookTime='15', DietType='TBD', IngredientCount='2', ImgURL='759.jpg' WHERE ID=759;
UPDATE `Recipe` SET RecipeName='Cinnamon Monkey Bread', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='760.jpg' WHERE ID=760;
UPDATE `Recipe` SET RecipeName='Cinnamon Pull Apart', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='761.jpg' WHERE ID=761;
UPDATE `Recipe` SET RecipeName='Cinnamon Roll Cake', CookTime='5', DietType='TBD', IngredientCount='14', ImgURL='762.jpg' WHERE ID=762;
UPDATE `Recipe` SET RecipeName='Cinnamon Roll Cupcakes', CookTime='120', DietType='TBD', IngredientCount='11', ImgURL='763.jpg' WHERE ID=763;
UPDATE `Recipe` SET RecipeName='Cinnamon Roll Muffins', CookTime='35', DietType='TBD', IngredientCount='13', ImgURL='764.jpg' WHERE ID=764;
UPDATE `Recipe` SET RecipeName='Cinnamon Toast Twists', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='765.jpg' WHERE ID=765;
UPDATE `Recipe` SET RecipeName='Cinnamon Yogurt Fruit Dip', CookTime='5', DietType='TBD', IngredientCount='4', ImgURL='766.jpg' WHERE ID=766;
UPDATE `Recipe` SET RecipeName='Coffee Cake in a Mug', CookTime='2', DietType='TBD', IngredientCount='7', ImgURL='767.jpg' WHERE ID=767;
UPDATE `Recipe` SET RecipeName='Coke Cake', CookTime='40', DietType='TBD', IngredientCount='9', ImgURL='' WHERE ID=768;
UPDATE `Recipe` SET RecipeName='College Cookies - No Baking', CookTime='10', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=769;
UPDATE `Recipe` SET RecipeName='Contained Apple Pie', CookTime='50', DietType='TBD', IngredientCount='4', ImgURL='770.jpg' WHERE ID=770;
UPDATE `Recipe` SET RecipeName='Cookie and Cream Bars', CookTime='20', DietType='TBD', IngredientCount='2', ImgURL='771.jpg' WHERE ID=771;
UPDATE `Recipe` SET RecipeName='Cookie Brownies', CookTime='25', DietType='TBD', IngredientCount='3', ImgURL='772.jpg' WHERE ID=772;
UPDATE `Recipe` SET RecipeName='Cookie Dough Balls', CookTime='10', DietType='TBD', IngredientCount='16', ImgURL='773.jpg' WHERE ID=773;
UPDATE `Recipe` SET RecipeName='Cookie Dough Greek Yogurt', CookTime='5', DietType='TBD', IngredientCount='9', ImgURL='774.jpg' WHERE ID=774;
UPDATE `Recipe` SET RecipeName='Cookie Dough PB Cups', CookTime='60', DietType='TBD', IngredientCount='11', ImgURL='775.jpg' WHERE ID=775;
UPDATE `Recipe` SET RecipeName='Cookies and Cream Fudge', CookTime='240', DietType='TBD', IngredientCount='6', ImgURL='776.jpg' WHERE ID=776;
UPDATE `Recipe` SET RecipeName='Cornbread Pudding', CookTime='15', DietType='TBD', IngredientCount='6', ImgURL='777.jpg' WHERE ID=777;
UPDATE `Recipe` SET RecipeName='Cranberry Bars', CookTime='40', DietType='TBD', IngredientCount='7', ImgURL='778.jpg' WHERE ID=778;
UPDATE `Recipe` SET RecipeName='Cranberry Cobbler', CookTime='60', DietType='TBD', IngredientCount='5', ImgURL='' WHERE ID=779;
UPDATE `Recipe` SET RecipeName='Cream Cheese Banana Bread', CookTime='60', DietType='TBD', IngredientCount='14', ImgURL='780.jpg' WHERE ID=780;
UPDATE `Recipe` SET RecipeName='Crescent Roll Danish', CookTime='25', DietType='TBD', IngredientCount='4', ImgURL='781.jpg' WHERE ID=781;
UPDATE `Recipe` SET RecipeName='Crispy Peanut Butter Bars', CookTime='30', DietType='TBD', IngredientCount='1', ImgURL='782.jpg' WHERE ID=782;
UPDATE `Recipe` SET RecipeName='Crock Pot Baked Apples', CookTime='170', DietType='TBD', IngredientCount='6', ImgURL='783.jpg' WHERE ID=783;
UPDATE `Recipe` SET RecipeName='Crock Pot Chocolate Candy', CookTime='120', DietType='TBD', IngredientCount='5', ImgURL='784.jpg' WHERE ID=784;
UPDATE `Recipe` SET RecipeName='Crustless Pumpkin Pie', CookTime='300', DietType='TBD', IngredientCount='10', ImgURL='785.jpg' WHERE ID=785;
UPDATE `Recipe` SET RecipeName='Cup Cake Cones', CookTime='30', DietType='TBD', IngredientCount='3', ImgURL='786.jpg' WHERE ID=786;
UPDATE `Recipe` SET RecipeName='Deep Dish Cookie for One', CookTime='1', DietType='TBD', IngredientCount='9', ImgURL='787.jpg' WHERE ID=787;
UPDATE `Recipe` SET RecipeName='Delicious Lazy Cookies', CookTime='25', DietType='TBD', IngredientCount='5', ImgURL='788.jpg' WHERE ID=788;
UPDATE `Recipe` SET RecipeName='Delicious No-Bake Bas', CookTime='25', DietType='TBD', IngredientCount='14', ImgURL='' WHERE ID=789;
UPDATE `Recipe` SET RecipeName='Dr. Pepper Brownies', CookTime='35', DietType='TBD', IngredientCount='9', ImgURL='790.jpg' WHERE ID=790;
UPDATE `Recipe` SET RecipeName='Easy 3 Ingredient Icing', CookTime='5', DietType='TBD', IngredientCount='3', ImgURL='791.jpg' WHERE ID=791;
UPDATE `Recipe` SET RecipeName='Easy 3 Layer Cake', CookTime='75', DietType='TBD', IngredientCount='7', ImgURL='792.jpg' WHERE ID=792;
UPDATE `Recipe` SET RecipeName='Easy Apple Dumplings', CookTime='55', DietType='TBD', IngredientCount='7', ImgURL='793.jpg' WHERE ID=793;
UPDATE `Recipe` SET RecipeName='Easy Banana Oatmeal Cookies', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='794.jpg' WHERE ID=794;
UPDATE `Recipe` SET RecipeName='Easy Canoli', CookTime='100', DietType='TBD', IngredientCount='9', ImgURL='795.jpg' WHERE ID=795;
UPDATE `Recipe` SET RecipeName='Easy Caramel Snickerdoodles', CookTime='15', DietType='TBD', IngredientCount='4', ImgURL='796.jpg' WHERE ID=796;
UPDATE `Recipe` SET RecipeName='Easy Caramels', CookTime='6', DietType='TBD', IngredientCount='4', ImgURL='797.jpg' WHERE ID=797;
UPDATE `Recipe` SET RecipeName='Easy Cheesecake Muffins', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='798.jpg' WHERE ID=798;
UPDATE `Recipe` SET RecipeName='Easy Cookies with a Kiss', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='799.jpg' WHERE ID=799;
UPDATE `Recipe` SET RecipeName='Easy Cream Cheese Danish', CookTime='45', DietType='TBD', IngredientCount='11', ImgURL='800.jpg' WHERE ID=800;
UPDATE `Recipe` SET RecipeName='Easy Do-Nothing Cake', CookTime='50', DietType='TBD', IngredientCount='11', ImgURL='801.jpg' WHERE ID=801;
UPDATE `Recipe` SET RecipeName='Easy Fruit Cobbler', CookTime='50', DietType='TBD', IngredientCount='4', ImgURL='802.jpg' WHERE ID=802;
UPDATE `Recipe` SET RecipeName='Easy Funnel Cake', CookTime='20', DietType='TBD', IngredientCount='5', ImgURL='803.jpg' WHERE ID=803;
UPDATE `Recipe` SET RecipeName='Easy Jello Parfait', CookTime='120', DietType='TBD', IngredientCount='5', ImgURL='804.jpg' WHERE ID=804;
UPDATE `Recipe` SET RecipeName='Easy Lemon Bars', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='805.jpg' WHERE ID=805;
UPDATE `Recipe` SET RecipeName='Easy Nutella Fudge', CookTime='120', DietType='TBD', IngredientCount='5', ImgURL='806.jpg' WHERE ID=806;
UPDATE `Recipe` SET RecipeName='Easy Nutty Fudge', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='807.jpg' WHERE ID=807;
UPDATE `Recipe` SET RecipeName='Easy Oreo Truffles', CookTime='90', DietType='TBD', IngredientCount='4', ImgURL='808.jpg' WHERE ID=808;
UPDATE `Recipe` SET RecipeName='Easy PB Fudge', CookTime='10', DietType='TBD', IngredientCount='7', ImgURL='809.jpg' WHERE ID=809;
UPDATE `Recipe` SET RecipeName='Easy Peach Cobbler', CookTime='50', DietType='TBD', IngredientCount='6', ImgURL='810.jpg' WHERE ID=810;
UPDATE `Recipe` SET RecipeName='Easy Peanut Butter Balls', CookTime='30', DietType='TBD', IngredientCount='8', ImgURL='811.jpg' WHERE ID=811;
UPDATE `Recipe` SET RecipeName='Easy Peanut Butter Candy', CookTime='5', DietType='TBD', IngredientCount='7', ImgURL='' WHERE ID=812;
UPDATE `Recipe` SET RecipeName='Easy Peanut Butter Cookies', CookTime='10', DietType='TBD', IngredientCount='6', ImgURL='' WHERE ID=813;
UPDATE `Recipe` SET RecipeName='Easy Peanut Butter Cups', CookTime='45', DietType='TBD', IngredientCount='9', ImgURL='814.jpg' WHERE ID=814;
UPDATE `Recipe` SET RecipeName='Easy Peanut Butter Pie', CookTime='120', DietType='TBD', IngredientCount='6', ImgURL='815.jpg' WHERE ID=815;
UPDATE `Recipe` SET RecipeName='Easy Pineapple Bars', CookTime='25', DietType='TBD', IngredientCount='6', ImgURL='816.jpg' WHERE ID=816;
UPDATE `Recipe` SET RecipeName='Easy Pineapple Cake', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='817.jpg' WHERE ID=817;
UPDATE `Recipe` SET RecipeName='Easy Rum Bars', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='818.jpg' WHERE ID=818;
UPDATE `Recipe` SET RecipeName='Easy Sherbet Cake', CookTime='30', DietType='TBD', IngredientCount='4', ImgURL='819.jpg' WHERE ID=819;
UPDATE `Recipe` SET RecipeName='Easy Shortbread', CookTime='37', DietType='TBD', IngredientCount='3', ImgURL='820.jpg' WHERE ID=820;
UPDATE `Recipe` SET RecipeName='Easy Smores Bars', CookTime='30', DietType='TBD', IngredientCount='9', ImgURL='821.jpg' WHERE ID=821;
UPDATE `Recipe` SET RecipeName='Eggless Cookie Dough', CookTime='5', DietType='TBD', IngredientCount='8', ImgURL='822.jpg' WHERE ID=822;
UPDATE `Recipe` SET RecipeName='Fried Cheesecake Strawberries', CookTime='60', DietType='TBD', IngredientCount='8', ImgURL='823.jpg' WHERE ID=823;
UPDATE `Recipe` SET RecipeName='Fried Honey Bananas', CookTime='10', DietType='TBD', IngredientCount='2', ImgURL='824.jpg' WHERE ID=824;
UPDATE `Recipe` SET RecipeName='Frito Chocolate Chip Cookies', CookTime='20', DietType='TBD', IngredientCount='10', ImgURL='825.jpg' WHERE ID=825;
UPDATE `Recipe` SET RecipeName='Frozen Banana Bites', CookTime='60', DietType='TBD', IngredientCount='8', ImgURL='826.jpg' WHERE ID=826;
UPDATE `Recipe` SET RecipeName='Frozen Fruit Dessert', CookTime='720', DietType='TBD', IngredientCount='6', ImgURL='827.jpg' WHERE ID=827;
UPDATE `Recipe` SET RecipeName='Frozen Yogurt Bars', CookTime='60', DietType='TBD', IngredientCount='6', ImgURL='828.jpg' WHERE ID=828;
UPDATE `Recipe` SET RecipeName='Fruity Cake Bars', CookTime='13', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=829;
UPDATE `Recipe` SET RecipeName='Fruity Cheesecake Popsicles', CookTime='120', DietType='TBD', IngredientCount='5', ImgURL='830.jpg' WHERE ID=830;
UPDATE `Recipe` SET RecipeName='Gingersnaps', CookTime='40', DietType='TBD', IngredientCount='10', ImgURL='831.jpg' WHERE ID=831;
UPDATE `Recipe` SET RecipeName='Glazed Chocolate Doughnuts', CookTime='75', DietType='TBD', IngredientCount='8', ImgURL='832.jpg' WHERE ID=832;
UPDATE `Recipe` SET RecipeName='Green Velvet Cupcakes', CookTime='25', DietType='TBD', IngredientCount='14', ImgURL='833.jpg' WHERE ID=833;
UPDATE `Recipe` SET RecipeName='Grilled Cinnamon Chocolate Sandwich', CookTime='5', DietType='TBD', IngredientCount='8', ImgURL='834.jpg' WHERE ID=834;
UPDATE `Recipe` SET RecipeName='Grilled Peaches w/ Strawberry', CookTime='15', DietType='TBD', IngredientCount='4', ImgURL='835.jpg' WHERE ID=835;
UPDATE `Recipe` SET RecipeName='Guilt Free Ice Cream', CookTime='30', DietType='TBD', IngredientCount='5', ImgURL='836.jpg' WHERE ID=836;
UPDATE `Recipe` SET RecipeName='Healthier Banana Bread', CookTime='70', DietType='TBD', IngredientCount='9', ImgURL='837.jpg' WHERE ID=837;
UPDATE `Recipe` SET RecipeName='Healthy Ice Cream Sandwich', CookTime='10', DietType='TBD', IngredientCount='3', ImgURL='838.jpg' WHERE ID=838;
UPDATE `Recipe` SET RecipeName='Healthy Roasted Bananas', CookTime='15', DietType='TBD', IngredientCount='4', ImgURL='839.jpg' WHERE ID=839;
UPDATE `Recipe` SET RecipeName='Home Fudgesicles', CookTime='45', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=840;
UPDATE `Recipe` SET RecipeName='Home Made Coffee Ice Cream', CookTime='2', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=841;
UPDATE `Recipe` SET RecipeName='Homemade Berry Biscuits', CookTime='25', DietType='TBD', IngredientCount='11', ImgURL='842.jpg' WHERE ID=842;
UPDATE `Recipe` SET RecipeName='Homemade Brownie Mix', CookTime='35', DietType='TBD', IngredientCount='7', ImgURL='843.jpg' WHERE ID=843;
UPDATE `Recipe` SET RecipeName='Homemade Butterfingers', CookTime='20', DietType='TBD', IngredientCount='7', ImgURL='844.jpg' WHERE ID=844;
UPDATE `Recipe` SET RecipeName='Homemade Fruit Leather', CookTime='360', DietType='TBD', IngredientCount='3', ImgURL='845.jpg' WHERE ID=845;
UPDATE `Recipe` SET RecipeName='Homemade Fudge', CookTime='240', DietType='TBD', IngredientCount='7', ImgURL='846.jpg' WHERE ID=846;
UPDATE `Recipe` SET RecipeName='Homemade PB Balls', CookTime='50', DietType='TBD', IngredientCount='10', ImgURL='847.jpg' WHERE ID=847;
UPDATE `Recipe` SET RecipeName='Homemade Thin Mints', CookTime='10', DietType='TBD', IngredientCount='3', ImgURL='848.jpg' WHERE ID=848;
UPDATE `Recipe` SET RecipeName='Homemade Vanilla Wafers', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='849.jpg' WHERE ID=849;
UPDATE `Recipe` SET RecipeName='Honey Bun Cake', CookTime='50', DietType='TBD', IngredientCount='10', ImgURL='850.jpg' WHERE ID=850;
UPDATE `Recipe` SET RecipeName='Honey Peaches', CookTime='40', DietType='TBD', IngredientCount='4', ImgURL='' WHERE ID=851;
UPDATE `Recipe` SET RecipeName='Ice Cream in a Bag', CookTime='20', DietType='TBD', IngredientCount='4', ImgURL='852.jpg' WHERE ID=852;
UPDATE `Recipe` SET RecipeName='Ice Cream Sandwich Cake', CookTime='20', DietType='TBD', IngredientCount='5', ImgURL='853.jpg' WHERE ID=853;
UPDATE `Recipe` SET RecipeName='Individual Peach Pie', CookTime='15', DietType='TBD', IngredientCount='7', ImgURL='854.jpg' WHERE ID=854;
UPDATE `Recipe` SET RecipeName='Indoor Smoores', CookTime='10', DietType='TBD', IngredientCount='5', ImgURL='855.jpg' WHERE ID=855;
UPDATE `Recipe` SET RecipeName='Jail House Rock Cake', CookTime='30', DietType='TBD', IngredientCount='6', ImgURL='856.jpg' WHERE ID=856;
UPDATE `Recipe` SET RecipeName='Jello Cake', CookTime='120', DietType='TBD', IngredientCount='1', ImgURL='' WHERE ID=857;
UPDATE `Recipe` SET RecipeName='Jello Pie', CookTime='60', DietType='TBD', IngredientCount='2', ImgURL='' WHERE ID=858;
UPDATE `Recipe` SET RecipeName='Kentucky Butter Cake', CookTime='80', DietType='TBD', IngredientCount='9', ImgURL='859.jpg' WHERE ID=859;
UPDATE `Recipe` SET RecipeName='Kentucky Derby Pie', CookTime='60', DietType='TBD', IngredientCount='1', ImgURL='860.jpg' WHERE ID=860;
UPDATE `Recipe` SET RecipeName='Key Lime Pie', CookTime='20', DietType='TBD', IngredientCount='6', ImgURL='861.jpg' WHERE ID=861;
UPDATE `Recipe` SET RecipeName='Key Lime Pie Dip', CookTime='15', DietType='TBD', IngredientCount='8', ImgURL='' WHERE ID=862;
UPDATE `Recipe` SET RecipeName='Krispy Kreme Kopy Kat', CookTime='60', DietType='TBD', IngredientCount='9', ImgURL='863.jpg' WHERE ID=863;
UPDATE `Recipe` SET RecipeName='Layered Chocolate Love Cake', CookTime='60', DietType='TBD', IngredientCount='7', ImgURL='864.jpg' WHERE ID=864;
UPDATE `Recipe` SET RecipeName='Leftover Candy Blondies from Scratch', CookTime='30', DietType='TBD', IngredientCount='7', ImgURL='865.jpg' WHERE ID=865;
UPDATE `Recipe` SET RecipeName='Leia Cinnamon Rolls', CookTime='80', DietType='TBD', IngredientCount='8', ImgURL='866.jpg' WHERE ID=866;
UPDATE `Recipe` SET RecipeName='Lemon Blueberry Bread', CookTime='70', DietType='TBD', IngredientCount='13', ImgURL='867.jpg' WHERE ID=867;
UPDATE `Recipe` SET RecipeName='Lemon Blueberry Cake', CookTime='60', DietType='TBD', IngredientCount='13', ImgURL='868.jpg' WHERE ID=868;
UPDATE `Recipe` SET RecipeName='Lemon Cooler Cupcakes', CookTime='45', DietType='TBD', IngredientCount='10', ImgURL='869.jpg' WHERE ID=869;
UPDATE `Recipe` SET RecipeName='Lemon Cream Cookies', CookTime='15', DietType='TBD', IngredientCount='3', ImgURL='' WHERE ID=870;
UPDATE `Recipe` SET RecipeName='Lemon Loaf', CookTime='45', DietType='TBD', IngredientCount='13', ImgURL='871.jpg' WHERE ID=871;
UPDATE `Recipe` SET RecipeName='Lemon Lush', CookTime='30', DietType='TBD', IngredientCount='10', ImgURL='872.jpg' WHERE ID=872;
