INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('28869', '3', 'Remove bottom leaves and tough outer leaves, leaving tender heart and bottom.'),
('28869', '4', 'Cut each artichoke in half lengthwise. place in water mixture, tossing to coat.'),
('28869', '5', 'Heat oil in a large nonstick skillet over medium heat.'),
('28869', '6', 'Add onion. cook 5 minutes or until tender, stirring frequently.'),
('28869', '7', 'Add remaining 2 cups water, peas, and carrot. bring to a boil.'),
('28869', '8', 'Drain artichokes. add artichokes and potatoes to the pan. Cover, reduce heat, and simmer 45 minutes or until artichokes are tender. Uncover. cook 3 minutes. Stir in dill, mint, salt, and pepper.'),
('28869', '9', 'Remove from heat. stir in remaining 2 tablespoons juice.'),
('28870', '1', 'Preheat oven to 35'),
('28870', '2', 'Place 1 cup milk, egg substitute, and goat cheese in a blender. process until smooth.'),
('28870', '3', 'Combine goat cheese mixture, remaining 2 1/4 cups milk, black pepper, thyme, nutmeg, and garlic in a large bowl, stirring with a whisk.'),
('28870', '4', 'Add bread cubes. stir gently to combine.'),
('28870', '5', 'Let stand 10 minutes.'),
('28870', '6', 'Place half of the bread mixture in a 13 x 9-inch baking dish coated with cooking spray. Arrange Parmesan cheese, ham, and artichoke hearts evenly over the bread mixture. Top with remaining bread mixture, and sprinkle evenly with fontina cheese.'),
('28870', '7', 'Bake strata at 350 for 40 minutes or until edges are bubbly.'),
('28870', '8', 'Let stand 15 minutes.'),
('28874', '1', 'Combine mayonnaise and lemon juice in a medium bowl, and stir well.'),
('28874', '2', 'Add shrimp and remaining ingredients. toss gently to coat. Cover and chill at least 30 minutes.'),
('28876', '1', 'In a small bowl, combine the parsley, mint, garlic, salt and 1 tablespoon olive oil. In the cavity of the artichoke from which the choke was removed, place 1 teaspoon of the herb mixture. Repeat this procedure with the remaining chokes. Arrange all chokes in a deep pan that keeps them close together, in other words, one that doesn?t give them room to fall over.'),
('28876', '2', 'Add the wine, boiling water, remaining oil and a pinch of salt. Cover and simmer on the stovetop 1 hour.'),
('28876', '3', 'Serve hot or at room temperature.'),
('28879', '1', 'Preheat oven to 375 degrees F. Spray 1 1/2-quart casserole dish with cooking spray. set aside'),
('28879', '2', 'Blanch spinach. Squeeze excess water.'),
('28879', '3', 'In a medium bowl, mix together spinach, garlic and lemon zest.'),
('28879', '4', 'Add artichoke hearts, 1-cup Parmesan, sour cream, mayonnaise and cayenne pepper sauce.'),
('28879', '5', 'Mix.'),
('28879', '6', 'Place into prepared casserole dish.'),
('28879', '7', 'Bake for 30 minutes. The last 5 minutes add the remaining 1/2 cup of Parmesan to the top.'),
('28879', '8', 'Serve hot or cold along with pita chips.'),
('28880', '1', 'Place bread in a food processor. pulse 10 times or until coarse crumbs form to measure 1 cup.'),
('28880', '2', 'Preheat oven to 40'),
('28880', '3', 'Drain beans in a colander over a bowl, reserving liquid.'),
('28880', '4', 'Add enough water to liquid to measure 1 cup.'),
('28880', '5', 'Combine beans, thyme, sage, pepper, and 1 garlic clove.'),
('28880', '6', 'Heat 1 tablespoon oil in a large nonstick skillet over medium-high heat.'),
('28880', '7', 'Add 3 garlic cloves, leek, rosemary, salt, and artichokes. saut 4 minutes. Stir in bean liquid mixture. Cover, reduce heat, and simmer 10 minutes, stirring occasionally.'),
('28880', '8', 'Remove from heat.'),
('28880', '9', 'Spread half of bean mixture in an 11 x 7-inch baking dish coated with cooking spray, and top with half of goat cheese.'),
('28880', '10', 'Spread artichoke mixture over goat cheese. top with remaining bean mixture and remaining goat cheese.'),
('28880', '11', 'Combine the breadcrumbs and 1 tablespoon oil. sprinkle over goat cheese.'),
('28880', '12', 'Bake at 400 for 25 minutes or until lightly browned.'),
('28889', '1', 'Pierce potato with a fork, and arrange on paper towel in microwave oven. Microwave on HIGH 3 minutes or until done, turning potato after 1 1/2 minutes.'),
('28889', '2', 'Let stand 5 minutes. Peel and coarsely chop potato.'),
('28889', '3', 'Heat 1/2 teaspoon olive oil in a small nonstick skillet over medium-high heat.'),
('28889', '4', 'Add onion, bell pepper, and potato. saut 3 minutes or until tender.'),
('28889', '5', 'Add artichoke. cook 2 minutes.'),
('28889', '6', 'Add oregano, 1/8 teaspoon salt, and 1/8 teaspoon black pepper.'),
('28889', '7', 'Remove from heat, and set aside.'),
('28889', '8', 'Combine egg whites, whole eggs, 1/8 teaspoon salt, and 1/8 teaspoon pepper in a small bowl. stir with a whisk.'),
('28889', '9', 'Heat a small nonstick skillet over medium-high heat.'),
('28889', '10', 'Add 1/4 teaspoon olive oil and half of egg mixture, and cook until edges begin to set (about 2 minutes). Lift edges of omelet with a spatula, tilting pan to allow uncooked egg mixture to come in contact with pan. Cook 2 minutes or until set. Spoon half of potato mixture onto half of omelet. sprinkle with half of crumbled goat cheese. Loosen omelet with spatula. fold in half. Cook 2 minutes. Repeat procedure with 1/4 teaspoon olive oil, egg mixture, and potato mixture.'),
('28891', '1', 'Preheat oven to 37'),
('28891', '2', 'Heat oil in a large dutch oven over medium-high heat. Sprinkle chicken all over with salt and lay in hot oil, skin side down. Cook until browned, about 5 minutes. Turn chicken over and add 1 cup water, the garlic, and artichokes.'),
('28891', '3', 'Roast chicken in oven, uncovered, until cooked through, about 1 hour.'),
('28891', '4', 'Add olives and parsley.'),
('28891', '5', 'Prep hearts: Snap off thick green outer leaves down to yellowish core. Halve artichokes crosswise. discard thorny tips. Trim stem to about 1/2 in. and peel tough outer skin from remaining stem. Halve artichoke lengthwise. scoop out and discard fuzzy, red-tipped choke. Put hearts in cold water with a little lemon juice and set aside until you''re ready to cook.'),
('28892', '1', 'Saut chicken, onion, and bell pepper in hot oil in a large skillet over medium-high heat 5 minutes. Stir in rice, next 3 ingredients, and, if desired, salt. Bring mixture to a boil. cover, reduce heat to low, and simmer 15 minutes or liquid is absorbed and rice is tender.'),
('28892', '2', 'Remove from heat, and stir in spinach.'),
('28892', '3', 'Transfer to a serving platter, and sprinkle with cheese.'),
('28893', '1', 'Stir together first 9 ingredients in a large bowl until blended. spoon into a straight-sided 9- x 5-inch loafpan lined with plastic wrap. Cover and chill 8 hours, or freeze up to 1 month. thaw in the refrigerator 8 hours.'),
('28893', '2', 'Invert chilled mixture onto a serving plate. remove plastic wrap.'),
('28893', '3', 'Cut loaf in half crosswise. place 1 cut half directly on top of remaining cut half, and smooth sides.'),
('28893', '4', 'Serve with crackers or toasted French baguette slices.'),
('28893', '5', 'Garnish, if desired, by plunging green onion stems in boiling water. plunge stems into ice water to stop the cooking process. Immediately transfer to paper towels. drain stems, and press between paper towels to dry. Press stems into sides of cheese square, beginning with the end of one stem on each side. Bring stems up and over to center of top. form loops with remaining stems, and secure with wooden picks. Arrange chile pepper halves on top.'),
('28893', '6', 'Note: To make 2 small boxes, cut in half, and garnish each half, if desired.'),
('28898', '1', 'Combine water and 2 tablespoons juice. Working with one artichoke at a time, bend back outer green leaves of artichokes, snapping at base, until reaching light green leaves. Trim about 1/4 inch from top of artichoke.'),
('28898', '2', 'Cut off stem of artichoke to within 1/4 inch of base. peel stem.'),
('28898', '3', 'Cut artichoke in half vertically.'),
('28898', '4', 'Place artichoke halves in lemon water. Repeat with remaining artichokes. Set aside.'),
('28898', '5', 'Melt 1 1/2 teaspoons butter in a large nonstick skillet over medium-high heat.'),
('28898', '6', 'Add onions. cook for 3 minutes or until onions begin to brown, stirring occasionally.'),
('28898', '7', 'Remove onions from pan, and set aside.'),
('28898', '8', 'Add remaining 1 1/2 teaspoons butter and oil to pan, stirring until butter melts.'),
('28898', '9', 'Add shallots, mushrooms, and garlic. saut 1 1/2 minutes or until shallots are tender.'),
('28898', '10', 'Add onions and wine. cook for 3 minutes or until wine almost evaporates.'),
('28898', '11', 'Drain artichokes. Stir artichokes and peas into onion mixture. cook 3 minutes or until artichokes are tender.'),
('28898', '12', 'Remove from heat. stir in remaining 1 1/2 teaspoons juice, parsley, salt, and pepper. Sprinkle with cheese.'),
('28906', '1', 'Preheat the oven to 350 degrees F.'),
('28906', '2', 'Place the spinach in a strainer and squeeze out as much liquid as possible. set aside.'),
('28906', '3', 'Chop the artichokes into bite-size chunks.'),
('28906', '4', 'In a large bowl, add the spinach, artichokes, 1/2 cup Parmesan, gouda, mozzarella, garlic, red pepper flakes, coriander seeds, mayonnaise, sour cream and cream cheese and mix until combined.'),
('28906', '5', 'Pour into a baking dish, top with the remaining 2 tablespoons Parmesan and bake until the edges are bubbly and light golden brown, about 25 minutes.'),
('28906', '6', 'Allow the dip to cool slightly before serving with tortilla chips.'),
('28906', '7', '*Cook''s Note: A quick way to thaw out spinach: microwave for 3 minutes, covered.'),
('28909', '1', 'Line a 9-inch quiche dish or pie plate with pastry. trim excess pastry around edges. Prick bottom and sides of pastry with a fork.'),
('28909', '2', 'Bake at 400 for 3 minutes. remove from oven, and gently prick with a fork.'),
('28909', '3', 'Bake an additional 5 minutes.'),
('28909', '4', 'Let cool on a wire rack.'),
('28909', '5', 'Combine whipping cream, eggs, salt, pepper, and nutmeg in a medium mixing bowl. mix well, and set aside.'),
('28909', '6', 'Drain artichokes, reserving 2 tablespoons oil. set aside.'),
('28909', '7', 'Cut artichokes into bite-size pieces. set aside.'),
('28909', '8', 'Saut onion in reserved oil in a small skillet until tender. drain off oil. Stir in reserved artichoke pieces. spoon into prepared pastry.'),
('28909', '9', 'Pour whipping cream mixture over onion and artichokes. sprinkle cheese on top, and dot with butter.'),
('28909', '10', 'Bake at 375 for 45 minutes or until set.'),
('28909', '11', 'Let stand 10 minutes before cutting into wedges.'),
('28910', '1', 'Preheat oven to 37'),
('28910', '2', 'Combine first 6 ingredients. stir well.'),
('28910', '3', 'Place each chicken breast half between 2 sheets of heavy-duty plastic wrap. pound to 1/4-inch thickness using a meat mallet or rolling pin. Top each breast half with 2 tablespoons cheese mixture. roll up jelly-roll fashion. Tuck in sides. secure each roll with wooden picks.'),
('28910', '4', 'Heat a large nonstick skillet coated with cooking spray over medium-high heat.'),
('28910', '5', 'Add chicken to pan, and cook 3 minutes on each side or until browned. Wrap the handle of pan with foil, and bake at 375 for 15 minutes or until chicken is done.'),
('28913', '1', 'Heat the oil in a large nonstick skillet coated with cooking spray over medium-high heat. Sprinkle the pork with Italian seasoning, salt, and pepper.'),
('28913', '2', 'Add pork, and cook 1 minute on each side or until lightly browned.'),
('28913', '3', 'Remove from pan.'),
('28913', '4', 'Add bell pepper to pan. saut 2 minutes.'),
('28913', '5', 'Combine the broth, tomato paste, thyme, and sage, stirring with a whisk.'),
('28913', '6', 'Return pork to pan, and add broth mixture and artichoke hearts. Cover, reduce heat, and simmer 8 minutes or until thoroughly heated.'),
('28913', '7', 'Remove pork from pan, and keep warm. Increase heat to medium-high. cook 2 minutes or until slightly thickened. Spoon the artichoke mixture over the pork.'),
('28915', '1', 'Cook pasta according to package directions, omitting salt and fat.'),
('28915', '2', 'Heat oil in a large skillet over medium-high heat.'),
('28915', '3', 'Add chicken to pan. saut 2 minutes or until browned.'),
('28915', '4', 'Add garlic. saut 1 minute.'),
('28915', '5', 'Add wine, salt, pepper, and artichokes. simmer 5 minutes or until sauce is thickened and chicken is done.'),
('28915', '6', 'Remove from heat. stir in cheese and 1/3 cup basil.'),
('28915', '7', 'Place sauce and pasta in a large bowl. stir gently to combine.'),
('28915', '8', 'Garnish with chopped basil, if desired.'),
('28916', '1', 'Preheat oven to 35'),
('28916', '2', 'Place Romano cheese, 1/4 cup mayonnaise, 1 teaspoon lemon juice, salt, black pepper, red pepper, minced garlic, and white beans in a food processor, and process until smooth. Spoon into a medium bowl. Stir in the artichokes and spinach. Spoon the mixture into a 1-quart glass or ceramic baking dish coated with cooking spray. Sprinkle with 1/2 cup mozzarella.'),
('28916', '3', 'Bake at 350 for 20 minutes or until bubbly and brown.'),
('28917', '1', 'Cook pasta according to package directions, omitting salt and fat.'),
('28917', '2', 'Drain pasta, reserving 1/2 cup cooking liquid. Set pasta aside. keep warm.'),
('28917', '3', 'Combine 2 cups water and juice in a medium bowl. Working with 1 artichoke at a time, cut off stem to within 1/4-inch from the base. peel stem.'),
('28917', '4', 'Remove bottom leaves and tough outer leaves, leaving tender heart and bottom. trim about 1 inch from top of artichoke.'),
('28917', '5', 'Cut each artichoke in half lengthwise.'),
('28917', '6', 'Place artichoke halves in lemon water.'),
('28917', '7', 'Heat 1 tablespoon oil in a large skillet over medium heat.'),
('28917', '8', 'Drain artichokes well. pat dry.'),
('28917', '9', 'Add artichokes to pan. Cover and cook 8 minutes, stirring occasionally. uncover. Increase heat to medium-high. cook 2 minutes or until artichokes are golden, stirring frequently.'),
('28917', '10', 'Place artichokes in a large bowl.'),
('28917', '11', 'Place pan over medium heat. add remaining 1/4 cup water and asparagus to pan. Cover and cook 5 minutes or until crisp-tender.'),
('28917', '12', 'Add asparagus, parsley, and rind to artichokes. toss well.'),
('28917', '13', 'Add pasta, reserved cooking liquid, the remaining 2 tablespoons oil, thyme, salt, and pepper to artichoke mixture. toss well.'),
('28917', '14', 'Place 2 cups pasta mixture into each of 6 shallow bowls. top each serving with about 3 tablespoons cheese.'),
('28923', '1', 'Heat oven or toaster oven to 400 F. Divide 3/4 cup tomato sauce or chopped tomatoes, 1/2 cup crumbled Feta, and 1/4 cup chopped fresh herbs (such as parsley, mint, and basil) among 4 pita rounds. Top with sliced black olives and sliced marinated artichoke hearts, if desired.'),
('28923', '2', 'Bake until the cheese melts and the crusts are crispy, about 8 minutes.'),
('28925', '1', 'In a small saucepan, season the artichokes with salt and pepper and simmer them in the cream over moderately low heat until very tender, about 12 minutes.'),
('28925', '2', 'Transfer the artichokes and cream to a blender and puree.'),
('28925', '3', 'Add the lemon juice and season with salt and pepper.'),
('28925', '4', 'In a large saucepan of boiling salted water, cook the pasta until al dente.'),
('28925', '5', 'Drain the shells and return them to the pan.'),
('28925', '6', 'Add the artichoke cream, smoked chicken, tomatoes and chives. season with salt and pepper.'),
('28925', '7', 'Transfer to bowls and serve.'),
('28930', '1', 'Watch how to make this recipe.'),
('28930', '2', 'Squeeze the lemons into a large bowl filled with water.'),
('28930', '3', 'Place the lemon halves in the water.'),
('28930', '4', 'Cut off the pointy tops of the artichoke.'),
('28930', '5', 'Remove some of the tough outer leaves.'),
('28930', '6', 'Remove the stem of the artichoke and peel off the tough green outer layer and reserve in the lemon water.'),
('28930', '7', 'Gently spread the leaves of the artichoke. Using a melon baller, scoop out the hairy choke in the center of the artichoke. When the arties are clean reserve them in the lemon water.'),
('28930', '8', 'In a small bowl combine the garlic, herbs, pecorino, bread crumbs, and crushed red pepper. Finely chop the reserved artichoke stems and add them to the bowl. Slowly drizzle in olive oil until the mixture forms a paste. Season with salt.'),
('28930', '9', 'Stuff the artichokes with the paste.'),
('28930', '10', 'Place the artichokes, flat side down, in a saucepan large enough to accommodate them.'),
('28930', '11', 'Add the wine to the saucepan and enough lemon water to come 3/4 way up the sides of the artichokes.'),
('28930', '12', 'Add the lemon halves to pan also.'),
('28930', '13', 'Drizzle generously with olive oil and season with salt.'),
('28930', '14', 'Bring to a boil and reduce to a simmer. Simmer for 15 to 20 minutes, or until the base of the artichokes are tender when poked with a fork.'),
('28930', '15', 'Serve hot or cold drizzled with olive oil.'),
('28930', '16', 'May - Why We Love: Artichokes'),
('28932', '1', 'Place artichokes and goat cheese in a food processor. process until smooth. Scoop into a bowl. add 3 tablespoons chopped sun-dried tomatoes, chopped green olives, diced pickled jalapeo peppers, 2 tablespoons chopped Italian parsley, and sea salt, stirring well.'),
('28932', '2', 'Garnish with 2 teaspoons chopped sun-dried tomatoes and 1 teaspoon parsley. serve with your favorite crackers.'),
('28933', '1', 'For artichokes:  Pull off dark, tough outer green leaves of each artichoke. discard. Trim end and peel outside of stem, leaving it attached. Lay artichokes on side, and slice about 1/2 inch off the top. Halve artichokes lengthwise, and cut each in half again.'),
('28933', '2', 'Place artichoke quarters in a large pot. add water to cover.'),
('28933', '3', 'Add bay leaf, whole and minced garlic, and 2 teaspoons kosher salt. Bring to a boil. cover, reduce heat to medium, and simmer 10 minutes or until tender.'),
('28933', '4', 'Drain and let cool.'),
('28933', '5', 'Scrape out the small inside leaves and fuzzy center of artichoke heart with a teaspoon. discard.'),
('28933', '6', 'Place artichokes, cut side up on a sheet pan.'),
('28933', '7', 'Whisk together oil, vinegar, remaining 1/4 teaspoon salt, and pepper in a small bowl.'),
('28933', '8', 'Drizzle vinaigrette over artichokes. toss well. Set aside.'),
('28934', '1', 'To prepare vinaigrette, combine first 6 ingredients in a small bowl. stir with a whisk.'),
('28934', '2', 'To prepare salad, combine spinach and remaining ingredients.'),
('28934', '3', 'Drizzle with vinaigrette, and toss gently.'),
('28940', '1', 'Preheat oven to 275 degrees. Throw chuck roasts into a large, heavy pot.'),
('28940', '2', 'Pour on the roasted red peppers, the drained artichoke hearts, and the sun dried tomatoes. If the sun dried tomatoes are packed in oil, drizzle in about a tablespoon of the oil.'),
('28940', '3', 'Add onions, garlic cloves and beef broth, then place the lid on the pot and cook in the oven for four hours.'),
('28940', '4', 'Remove the pot after four hours and use a fork to confirm that the meat is falling apart/fork tender. (If not, put back into the oven for 30 minute increments until totally tender.)With a slotted spoon, remove the peppers, artichokes, onions, garlic, and sundried tomatoes and place them in a separate container.'),
('28940', '5', 'Remove the meat and place it in another separate containers. Cover the containers holding the veggies and meat and refrigerate them several hours or overnight.'),
('28940', '6', 'Place the lid on the pot and refrigerate it for several hours or overnight. When you''re ready to serve the roast, remove the meat and veggie bowls from the fridge and nuke them just to heat them up. Set aside. Cook egg noodles according to package directions.'),
('28940', '7', 'Drain and set aside.'),
('28940', '8', 'Remove the pot from the fridge and carefully skim off the solidified fat from the top of the liquid. Discard the fat.'),
('28940', '9', 'Mix flour with 1/2 cup of the cooking liquid and set aside.'),
('28940', '10', 'Add wine to the cooking liquid then bring it to a boil over high heat. Boil the liquid for several minutes, until it reduces by at least half. When bubbles appear all over the surface of the liquid, drizzle in a tablespoon or so of the flour paste. Check thickness: if it''s too liquidy, continue to boil for another minute or two. If it''s too thick, add some more broth or water. You want to wind up with a rich, thick liquid/gravy.Arrange cooked noodles on a large platter and arrange chunks of the meat and the intact artichoke hearts and peppers (and garlic cloves!) all around the meat. Spoon the thick gravy all over the top and sprinkle on minced fresh parsley.'),
('28940', '11', 'Serve immediately! Very, very flavorful.'),
('28943', '1', 'Watch how to make this recipe.'),
('28943', '2', 'Position the oven rack in center of the oven. Preheat the oven to 375 degrees F.'),
('28943', '3', 'Defrost the spinach in the microwave.'),
('28943', '4', 'Drain, then dry the spinach out as much as possible by wringing it out in a clean kitchen towel.'),
('28943', '5', 'Bring a saucepot of water to a boil.'),
('28943', '6', 'Add salt.'),
('28943', '7', 'Add the pasta and cook according to package directions for al dente.'),
('28943', '8', 'Meanwhile, heat 2 tablespoons extra-virgin olive oil in a small skillet over medium to medium-high heat and add the shallots and garlic and cook 2 to 3 minutes.'),
('28943', '9', 'Add the artichokes and cook until they are lightly brown.'),
('28943', '10', 'Add the wine to deglaze the pan.'),
('28943', '11', 'While the artichokes and pasta cook, in a saucepot over medium to medium-high heat, add the butter. When melted, whisk in the flour for 1 minute or so, then whisk in the milk and season with salt, pepper and a little nutmeg. Cook 5 to 6 minutes, or until thick enough to coat the back of a spoon, adjust the seasonings and stir in the Gruyere cheese.'),
('28943', '12', 'Combine the sauce with the spinach, pasta, and artichoke and stir until just combined.'),
('28943', '13', 'Transfer the mixture to a baking dish and cover with the remaining cheese. Cool and store for a make-ahead meal.'),
('28943', '14', 'Bake on a baking sheet 45 minutes or until brown and bubbly on top.'),
('28945', '1', 'Watch how to make this recipe.'),
('28945', '2', 'First thing to do is to steam the artichokes in a flavorful broth.'),
('28945', '3', 'Put the parsley, garlic, bay leaves, wine, and 1 of the halved lemons in a wide pot.'),
('28945', '4', 'Add 2 quarts of water and bring to a simmer. Season the broth with salt and pepper.'),
('28945', '5', 'While that''s coming to a simmer, wash the artichokes under cold water. Then, using a paring knife, trim the bottom end of each stem and shave the stem down to expose the tender, light green flesh underneath. Snap or cut off the outer petals until you reach the soft, pale green leaves in the center. Slice off about 1 inch from the top of the artichoke with a large knife. Do the same to prepare the rest of the artichokes.'),
('28945', '6', 'Slide the artichokes into the simmering broth. Then cover the pan and simmer over medium-low heat for about 20 minutes, until there is no resistance when a knife is inserted into the base of each artichoke.'),
('28945', '7', 'Remove the artichokes from the poaching liquid with tongs. Using a spoon, carefully scoop out the hairy choke from the center of each and discard. Try and keep the artichoke halves intact as best you can. it looks great for presentation.'),
('28945', '8', 'Put a large, deep skillet over medium heat and cover the bottom with a 2-count of oil. When the oil is smoking hot, add the sausage and cook for 7 to 10 minutes until cooked through. Take them out of the pan and set them aside.'),
('28945', '9', 'Add a drizzle of oil to the pan.'),
('28945', '10', 'Add the sage leaves and cook 2 to 3 minutes to infuse the oil with their flavor.'),
('28945', '11', 'Add the shallots, garlic, and lemon slices and cook 2 minutes. Then add the stock to the pan, bring to a simmer and simmer until reduced and thickened. Swirl in the butter to emulsify, and a drizzle of olive oil. Return the artichokes to the pan and cook over low heat for a few minutes to warm up them up. Spoon the artichokes out onto plates and serve with the sausage.'),
('28946', '1', 'Watch how to make this recipe.'),
('28946', '2', 'Place chicken in zip-top bags and pound with a meat mallet or rolling pin until 1/4-inch thick.'),
('28946', '3', 'Remove chicken from bag and season all over with salt and black pepper. In a shallow dish (or plastic bag), combine flour, lemon zest, paprika, and garlic powder.'),
('28946', '4', 'Mix well.'),
('28946', '5', 'Add chicken and turn to coat.'),
('28946', '6', 'Remove chicken from flour mixture and shake off excess flour.'),
('28946', '7', 'Heat oil in a large skillet over medium-high heat.'),
('28946', '8', 'Add chicken and saute 2 minutes per side, until golden brown and cooked through.'),
('28946', '9', 'Add lemon juice, wine and chicken broth and bring to a simmer. Simmer 5 minutes, until chicken is cooked through and sauce thickens.'),
('28946', '10', 'Add artichoke hearts and capers and simmer 1 minute to heat through.'),
('28946', '11', 'Cook rice according to package directions, adding lima beans at the beginning of cooking process.'),
('28946', '12', 'Serve chicken and sauce with rice.'),
('28954', '1', 'Preheat the oven to 400F.'),
('28954', '2', 'Add 1 tbsp olive oil into a very large skillet and add in the 2 cups of chopped onion. Cook about 7 minutes on medium heat until onion is translucent.2a. Meanwhile, in a food processor, process the bread into crumbs with 1 tsp earth balance.'),
('28954', '3', 'Remove and set aside. Omit this step if you use pre-made bread crumbs.2b. Now process the drained and rinsed navy beans, 1/4 cup water, 2 tbsp nutritional yeast, 1 tsp kosher salt, basil, and red pepper flakes.*If you dont have a food processor you could probably mash the mixture by hand.'),
('28954', '4', 'Add in minced garlic to skillet and cook for another few minutes on low.'),
('28954', '5', 'Add in your 4 cups of packed spinach and chopped artichoke hearts to the skillet and heat until spinach is wilted over low-medium heat.'),
('28954', '6', 'Add navy bean processed mixture to the skillet and stir until combined. Taste and adjust seasonings if necessary. Stir in 3/4 of the bread crumbs.'),
('28954', '7', 'Pour into an oven safe dish (I used a 4 cup Pyrex dish). Sprinkle on the remaining bread crumbs (and cheese if desired) and cover with foil.'),
('28954', '8', 'Cook, covered, in the oven at 400F for 20 mins. Now remove the foil cover and cook for an additional 10-15 minutes watching closely so as not to burn. Makes 2.5-3 cups. Allow to cool for about 5 minutes and then serve immediately with sturdy chips and crackers.'),
('28958', '1', 'Heat a large nonstick skillet over medium heat.'),
('28958', '2', 'Add olive oil to pan. swirl to coat.'),
('28958', '3', 'Add shallots, and cook for 2 minutes, stirring frequently. Stir in artichoke hearts and garlic. cook for 8 minutes or until artichoke hearts begin to brown, stirring occasionally.'),
('28958', '4', 'Remove from heat, and stir in herbes de Provence. Cool 10 minutes.'),
('28958', '5', 'Combine milk, black pepper, salt, and eggs in a large bowl, stirring with a whisk.'),
('28958', '6', 'Add Parmigiano-Reggiano cheese and bread. toss gently to combine. Stir in artichoke mixture, and let stand for 20 minutes.'),
('28958', '7', 'Preheat oven to 37'),
('28958', '8', 'Spoon half of bread mixture into an 8-inch square glass or ceramic baking dish coated with cooking spray. Sprinkle with half of goat cheese, and top with remaining bread mixture. Sprinkle remaining half of goat cheese over top.'),
('28958', '9', 'Bake at 375 for 50 minutes or until browned and bubbly.'),
('28960', '1', 'Cook orzo in a 4- to 5-quart pot of boiling salted water until al dente.'),
('28960', '2', 'Drain in a colander.'),
('28960', '3', 'While orzo cooks, lightly toast pine nuts in a dry small skillet over moderate heat, stirring, until pale golden, about 2 minutes.'),
('28960', '4', 'Remove from heat and cool 1 minute, then coarsely chop.'),
('28960', '5', 'Drain artichoke hearts in a large sieve and rinse well. Pull off leaves from bases of hearts and quarter bases. Rinse leaves and bases well, then drain thoroughly.'),
('28960', '6', 'Stir together oil, vinegar, salt, and pepper in a large bowl.'),
('28960', '7', 'Add orzo, pine nuts, artichokes (leaves and bases), parsley, and zest and toss to combine.'),
('28962', '1', 'Mix the artichoke hearts, green onions, garlic, cream cheese, mayonnaise, sour cream, mozzarella and parmigiano reggiano reserving some of the cheese.Hollow 1/2 an inch out of the center of both halves of the bread.'),
('28962', '2', 'Spread the mixture into the hole in the bread slices and top with the reserved cheese.'),
('28962', '3', 'Bake in a preheated 350F oven covered in foil for 20 minutes.'),
('28962', '4', 'Remove the foil and continue to bake until the cheese is melted and golden brown.'),
('28964', '1', 'Melt butter in large skillet over medium-high heat.'),
('28964', '2', 'Add mushrooms and garlic. saute until mushrooms release juices and begin to brown, about 7 minutes.'),
('28964', '3', 'Add artichokes and vermouth. Cook until liquid is absorbed, stirring occasionally, about 10 minutes. Season with salt and pepper.'),
('28968', '1', 'Using a sharp serrated knife, cut the top third and the stem off each artichoke. Snap off the outer leaves and with a small, sharp knife, trim the tough green skin from around each artichoke. Rub the artichokes all over with the lemon halves.'),
('28968', '2', 'Bring a large saucepan of salted water to a boil.'),
('28968', '3', 'Add the artichokes and simmer until tender when pierced through the bottom, about 15 minutes.'),
('28968', '4', 'Drain and let cool. With a spoon, scoop out the hairy chokes. Roughly chop the artichokes, then put them in a food processor and process until coarsely chopped. You should have about 3 cups.'),
('28968', '5', 'In a large bowl, mix the artichokes with the beef, scallions, parsley, bread crumbs, Gruyre, capers, tabil, pepper, cinnamon and 2 teaspoons of salt.'),
('28968', '6', 'Add 3 tablespoons of the paprika and the eggs and mix with your hands until thoroughly combined.'),
('28968', '7', 'Form the meat mixture into 3 dozen tablespoon-size meatballs. Form each ball into a football shape, then dredge in flour.'),
('28968', '8', 'In a large skillet, heat 1/2 inch of vegetable oil until shimmering. Working in 2 batches, fry the meatballs over moderately high heat, turning occasionally, until deep brown, about 12 minutes. reduce the heat if the meatballs start browning too quickly.'),
('28968', '9', 'Transfer the meatballs to paper towels to drain. keep warm.'),
('28968', '10', 'Heat the olive oil in a large skillet.'),
('28968', '11', 'Add the remaining 1 teaspoon of paprika and cook over low heat until fragrant, about 10 seconds.'),
('28968', '12', 'Add the tomatoes and their liquid and simmer over low heat until the sauce thickens, about 10 minutes. Season with salt. Spoon the sauce onto a large platter. Set the meatballs on the sauce and serve.'),
('28969', '1', 'Remove roots, outer leaves, and tops from leeks, leaving 1 1/2 to 2 inches of dark leaves. Slice leeks in half lengthwise. rinse with cold water.'),
('28969', '2', 'Drain.'),
('28969', '3', 'Remove dark leaves. chop dark leaves to measure 1 1/2 cups. set aside. Chop bulb ends to measure 2 cups. set aside.'),
('28969', '4', 'Remove stalks from fennel bulb. Chop the stalks to measure 1 1/2 cups. set aside. Chop bulb to measure 2 cups. set aside.'),
('28969', '5', 'Combine chopped dark leek leaves, chopped fennel stalks, 5 cups water, wine, and fennel seeds in a large Dutch oven. bring to a boil. Reduce heat. simmer 25 minutes. Strain leek mixture through a sieve over a bowl, reserving stock. discard solids.'),
('28969', '6', 'While the vegetable mixture simmers, combine 8 cups water and lemon juice. Working with 1 artichoke at a time, cut off stem to within 1 inch of base. peel stem.'),
('28969', '7', 'Remove bottom leaves and tough outer leaves, leaving tender heart and bottom.'),
('28969', '8', 'Cut artichoke in half lengthwise.'),
('28969', '9', 'Remove fuzzy thistle from bottom with a spoon.'),
('28969', '10', 'Cut artichoke lengthwise into quarters. place in lemon water. Repeat procedure with remaining artichokes.'),
('28969', '11', 'Drain artichokes. discard lemon water.'),
('28969', '12', 'Heat oil in pan over medium heat.'),
('28969', '13', 'Add chopped leek bulbs, salt, and pepper. saut 5 minutes.'),
('28969', '14', 'Add garlic. saut 2 minutes. Stir in chopped fennel bulb, artichoke quarters, reserved stock, potato, chickpeas, tomatoes, and saffron. bring to a boil. Cover, reduce heat, and simmer 35 minutes or until vegetables are tender.'),
('28969', '15', 'Serve with Rouille.'),
('28972', '1', 'Add lemon halves to a large bowl of cold water, squeezing to release juice.'),
('28972', '2', 'Cut off top inch of 1 artichoke and bend back outer leaves until they snap off close to base (keep stem attached). Discard several more layers in same manner until you reach pale yellow leaves.'),
('28972', '3', 'Cut remaining leaves flush with top of artichoke bottom using a sharp knife. Trim dark green fibrous parts from base and sides of artichoke.'),
('28972', '4', 'Peel sides of stem down to pale inner core. Put in lemon water while preparing remaining artichokes.'),
('28972', '5', 'Cook shallots, carrot, garlic, and seeds in 1/4 cup oil in a 4-to 5-quart heavy pot (pot should be wide enough to hold artichokes in 1 layer with stems pointing upward) over medium heat, stirring occasionally, 3 minutes.'),
('28972', '6', 'Add water, zest, and 3 tablespoons lemon juice and bring to a simmer. Stand artichokes in pot and season with 1 teaspoon salt and 1/4 teaspoon pepper. Cover artichokes with wax paper, then a lid, and simmer over medium-low heat until bases are just tender when pierced with a knife, 20 to 30 minutes.'),
('28972', '7', 'Transfer artichokes to a dish and reserve cooking liquid. When artichokes are cool enough to handle, halve lengthwise. Scoop out and discard inner choke (fuzzy center and any sharp leaves).'),
('28972', '8', 'Heat 2 tablespoons oil in a 12-inch heavy skillet over medium-high heat until it shimmers, then brown cut sides of artichokes in 2 batches, about 2 minutes per batch, transferring to a serving dish.'),
('28972', '9', 'Add reserved cooking liquid to skillet along with remaining tablespoon lemon juice and remaining 2 tablespoons oil. Boil vigorously 3 minutes, then stir in parsley and pour over artichokes.'),
('28972', '10', 'Serve warm or at room temperature.'),
('28973', '1', 'Preheat oven to 350F. Divide bread between 2 baking sheets.'),
('28973', '2', 'Bake until cubes are dry but not hard, stirring occasionally, about 15 minutes.'),
('28973', '3', 'Heat oil in heavy large skillet over medium-high heat.'),
('28973', '4', 'Add sausage and saute until cooked through, breaking up with back of fork, about 5 minutes.'),
('28973', '5', 'Add onions, celery, and garlic. Saute until celery is soft, about 10 minutes.'),
('28973', '6', 'Mix in artichokes, thyme, and mint. saute 2 minutes longer.'),
('28973', '7', 'Transfer sausage mixture to large bowl. (Bread and sausage mixture can be made 1 day ahead. Cover separately. Store bread at room temperature. Refrigerate sausage mixture and reheat to lukewarm before continuing.)'),
('28973', '8', 'Add bread to sausage mixture. toss to blend well.'),
('28973', '9', 'Mix in cheese, then 1 cup broth. Season with salt and pepper.'),
('28974', '1', 'Place yolks in medium bowl. Gradually whisk in lemon juice, then cream.'),
('28974', '2', 'Cook artichoke hearts and green beans in large pot of boiling salted water until crisp-tender, about 5 minutes. Using sieve, transfer vegetables from pot to large skillet. Return water to boil.'),
('28974', '3', 'Add pasta. boil until tender but still firm to bite.'),
('28974', '4', 'Drain pasta, reserving 1 1/2 cups cooking liquid.'),
('28974', '5', 'Add pasta to skillet with vegetables.'),
('28974', '6', 'Whisk 3/4 cup cooking liquid into yolk mixture.'),
('28974', '7', 'Add yolk mixture, 3/4 cup cheese, and parsley to skillet. Toss over medium heat just until sauce thickens and coats pasta, about 4 minutes, adding more cooking liquid by tablespoonfuls if dry. Season with salt and pepper.'),
('28974', '8', 'Serve, passing additional cheese alongside.'),
('28975', '1', 'Preheat oven to 37'),
('28975', '2', 'Combine first 4 ingredients in a medium saucepan.'),
('28975', '3', 'Place over medium heat. cook 12 minutes or until slightly thick, stirring occasionally.'),
('28975', '4', 'Remove from heat. set aside.'),
('28975', '5', 'Combine 1/2 cup provolone and the next 6 ingredients (through garlic) in a medium bowl. Spoon or pipe about 1 1/2 tablespoons cheese mixture into each pasta shell. place stuffed shells in a 13 x 9-inch baking dish coated with cooking spray. Spoon tomato mixture over shells. sprinkle with remaining 1/2 cup provolone.'),
('28975', '6', 'Bake at 375 for 25 minutes or until thoroughly heated and cheese melts.'),
('28977', '1', 'Heat 2 tablespoons oil in medium skillet over medium-high heat.'),
('28977', '2', 'Add artichokes to skillet. sprinkle with salt and pepper and saute until beginning to brown around edges, about 4 minutes.'),
('28977', '3', 'Add garlic and 1/2 cup water, reduce heat to medium-low, cover, and simmer until artichokes are tender when base is pierced with small sharp knife, about 10 minutes. Uncover and boil until any liquid remaining in skillet evaporates.'),
('28977', '4', 'Remove from heat.'),
('28977', '5', 'Preheat broiler.'),
('28977', '6', 'Whisk eggs and 2 tablespoons cheese in large bowl. Sprinkle with salt and pepper.'),
('28977', '7', 'Heat 2 tablespoons oil in medium nonstick ovenproof skillet over medium-high heat.'),
('28977', '8', 'Add mushrooms. saute until browned, about 5 minutes. Pat artichokes dry. add to skillet and stir 2 minutes.'),
('28977', '9', 'Add eggs. stir to blend. Reduce heat to medium, cover, and cook until eggs are almost set, about 5 minutes. Sprinkle with remaining 2 tablespoons cheese.'),
('28977', '10', 'Transfer frittata to broiler. Broil just until set in center, about 1 minute. Using rubber spatula, loosen edges of frittata and slide out onto platter.'),
('28977', '11', 'Serve warm or at room temperature.'),
('28977', '12', 'Nutrition Data'),
('28981', '1', 'Preheat oven to 425F.'),
('28981', '2', 'Cut artichokes into 1/2-inch pieces. Sprinkle baking sheet with yellow cornmeal. Unroll pizza crust dough onto prepared baking sheet. press out dough to 11-inch square.'),
('28981', '3', 'Brush dough with 1 tablespoon reserved marinade. Top dough with artichokes, plum tomato slices, crumbled herb-seasoned feta cheese and sweet onion slices.'),
('28981', '4', 'Drizzle with remaining 1 tablespoon marinade.'),
('28981', '5', 'Bake pizza until crust is crisp and golden, about 15 minutes.'),
('28981', '6', 'Transfer to platter. Sprinkle with mint.'),
('28981', '7', 'Cut pizza into 4 squares and serve.'),
('28986', '1', 'Preheat grill to medium-high heat.'),
('28986', '2', 'Cut 1/4 inch off stems of artichokes. peel stems.'),
('28986', '3', 'Remove bottom leaves and tough outer leaves from each artichoke, leaving tender heart and bottom. Trim about 1 inch from tops of artichokes.'),
('28986', '4', 'Place artichokes in a Dutch oven filled two-thirds with water. bring to a boil. Cover, reduce heat, and simmer 20 minutes or until a leaf near the center of each artichoke pulls out easily.'),
('28986', '5', 'Drain and cool.'),
('28986', '6', 'Cut in half lengthwise.'),
('28986', '7', 'Place artichoke halves, cut sides down, on grill rack coated with cooking spray. grill 4 minutes on each side or until golden.'),
('28986', '8', 'Heat oil in a large skillet over medium-high heat.'),
('28986', '9', 'Add onion to pan. saut 4 minutes or until tender.'),
('28986', '10', 'Add garlic. saut 4 minutes or until onion is golden.'),
('28986', '11', 'Add 2/3 cup water and next 3 ingredients (through beans). cook 2 minutes or until thoroughly heated.'),
('28986', '12', 'Place bean mixture in a food processor. process until smooth. Keep warm.'),
('28986', '13', 'Combine wine, sliced garlic, and shallot in a small saucepan. bring to a boil. Reduce heat, and simmer 4 minutes or until liquid almost evaporates.'),
('28986', '14', 'Add broth. simmer until reduced to 1/2 cup (about 3 minutes).'),
('28986', '15', 'Spoon about 1/2 cup bean mixture into each of 6 shallow bowls, and top each serving with 2 artichoke halves.'),
('28986', '16', 'Drizzle about 1 1/2 tablespoons broth mixture over top of each serving. sprinkle each serving with 1 teaspoon parsley and about 1/4 teaspoon thyme.'),
('28987', '1', 'In a food processor, pulse the flour with the salt a few times. In a medium bowl, beat the eggs with the olive oil. With the machine on, pour in the eggs and process until a smooth, sticky dough forms. Scrape the dough out onto a lightly floured work surface and knead until smooth. The dough will be soft and still slightly tacky.'),
('28987', '2', 'Transfer the dough to a medium bowl and rub the surface with olive oil. Cover with plastic wrap and let stand at room temperature for at least 30 minutes.'),
('28987', '3', 'Divide the dough in half. On a lightly floured surface, roll out 1 piece to a rectangle about 1/8 inch thick.'),
('28987', '4', 'Cut the dough in half. Using a pizza cutter, cut the dough into 6- to 8-inch-long strands 1/3 inch wide. Dust 2 large baking sheets with cornmeal and carefully lay the strands on the sheets. sprinkle the strands with cornmeal to prevent sticking. Repeat with the remaining dough. Cover and set aside at room temperature.'),
('28987', '5', 'Fill a large bowl with water and squeeze a lemon half into it. Working with 1 artichoke at a time, snap off the outer leaves. Using a sharp knife, cut off the top two-thirds of the leaves and trim the base and stem. Using a melon baller or teaspoon, scoop out the furry choke. Rub the artichoke heart all over with the remaining lemon half. Slice the heart 1/4 inch thick and put in the bowl of lemon water. Repeat with the remaining 3 artichokes.'),
('28987', '6', 'Drain the artichokes. In a medium saucepan, combine the artichokes with the stock, wine, garlic, tomato paste, olive oil and crushed pepper. season with salt and pepper and bring to a boil. Simmer over low heat, stirring a few times, until the artichokes are just tender and the sauce has thickened slightly, about 30 minutes. Season the sauce with salt and pepper and keep warm.'),
('28987', '7', 'Bring a large pot of salted water to a boil.'),
('28987', '8', 'Add the pasta and cook, stirring, until al dente, about 5 minutes.'),
('28987', '9', 'Drain and transfer to a large, wide pasta bowl. Spoon the sauce over the pasta and toss well. Sprinkle with the Pecorino, basil and parsley and serve at once.'),
('28991', '1', 'Fill a stockpot to half full with water.  Stir Italian seasoning, basil, thyme, liquid smoke, olive oil, salt, and white wine into water.  Squeeze the lemon wedges over the mixture and drop the wedge into the pot. Bring mixture to a boil over medium heat. add the artichoke halves and continue to boil until tender, 20 to 30 minutes.'),
('28991', '2', 'Remove artichokes from water and drain upside down on paper towel. allow to cool to the touch. Refrigerate until ready to serve.'),
('28991', '3', 'Preheat an outdoor grill for high heat and lightly oil grate.'),
('28991', '4', 'Lightly coat the cooled artichoke halves with cooking spray. Cook artichoke halves on grill until edges are slightly charred.'),
('28991', '5', 'Drizzle with melted butter to serve.'),
('28992', '1', 'Squeeze juice from 1 lemon half into a bowl of cold water, reserving remaining half. Keeping stem attached, cut off top 2 inches of 1 whole artichoke. Bend back outer leaves until they snap off close to base and discard several more layers of leaves in same manner until exposed leaves are pale green at top and yellow at base.'),
('28992', '2', 'Trim dark green fibrous parts from base and sides with a sharp paring knife, then rub cut surfaces with reserved lemon half.'),
('28992', '3', 'Trim 1/4 inch from end of stem and trim sides of stem down to pale inner core (don''t worry if remaining flesh is very thin), then cut artichoke lengthwise into 8 wedges and cut out choke.'),
('28992', '4', 'Rub cut surfaces with reserved lemon half and drop artichoke pieces into acidulated water. Trim remaining artichokes in same manner.'),
('28992', '5', 'Cut a shallow X in bottom of each tomato with a sharp paring knife and blanch in a 3-quart saucepan of boiling water 10 seconds.'),
('28992', '6', 'Transfer tomatoes with a slotted spoon to a bowl of ice and cold water to cool. Peel tomatoes, then discard seeds and finely chop.'),
('28992', '7', 'Prepare grill for cooking over direct heat with medium-hot charcoal (medium-high heat for gas). see Grilling Procedure'),
('28992', '8', 'Drain artichokes and pat dry between paper towels.'),
('28992', '9', 'Pat rabbit dry and sprinkle with 1 teaspoon salt and 1/2 teaspoon pepper.'),
('28993', '1', 'Set oven to broil. Lightly coat a large broiler pan with cooking spray. Sprinkle chicken with dried oregano. season with salt and pepper. place chicken in pan. Broil 2 minutes per side.'),
('28993', '2', 'Remove pan from oven. set oven to 450F.'),
('28993', '3', 'Mix goat cheese and ricotta in a bowl. spread evenly over pizza crust, leaving a 1-inch border. Top with chicken, artichokes, and tomatoes. sprinkle with Parmesan.'),
('28993', '4', 'Bake until Parmesan turns golden, about 8 minutes. Sprinkle with fresh oregano and serve.'),
('28993', '5', 'Self'),
('28996', '1', 'Preheat oven to 35'),
('28996', '2', 'Arrange the tomato halves, cut sides up, on a baking sheet.'),
('28996', '3', 'Drizzle with olive oil. sprinkle with 1 teaspoon thyme and black pepper.'),
('28996', '4', 'Bake at 350 for 45 minutes or until very tender. Cool slightly.'),
('28996', '5', 'Combine remaining 1/2 teaspoon thyme, low-fat mayonnaise, olives, rind, and juice.'),
('28996', '6', 'Spread cut sides of bread evenly with mayonnaise mixture. Divide tomato halves, Simple Roasted Leg of Lamb, onion, and artichokes evenly among 4 bread pieces. Top with remaining bread pieces. Wrap the sandwiches in foil or parchment paper. chill.'),
('28997', '1', 'In a large pasta pot, combine 6 quarts of water, the lemon juice, 2 tablespoons salt, and a few peppercorns.'),
('28997', '2', 'Add the artichokes and cook until tender, about 12 minutes.'),
('28997', '3', 'Drain the artichokes and set aside.'),
('28997', '4', 'Bring 6 quarts of water to a boil and add 2 tablespoons salt.'),
('28997', '5', 'Make the pasta according to the recipe and roll it out on the thinnest setting on a pasta rolling machine.'),
('28997', '6', 'Cut the rolled pasta into pieces 10 inches long by 5 inches wide. Set up an ice bath with only a few ice cubes next to the stove top. Cook the pasta in the boiling water for 1 minute, drain and refresh in the ice bath.'),
('28997', '7', 'Remove the pasta from the ice bath and set aside on clean, damp kitchen towels.'),
('28997', '8', 'Preheat the oven to 375 degrees F.'),
('28997', '9', 'Butter a 12 by 9-inch casserole.'),
('28997', '10', 'Cut the artichokes with a very sharp knife or a mandoline into 1/8-inch thick slices. Layer the lasagne, beginning with the besciamella, then a layer of pasta, then a layer of artichokes, each layer getting a sprinkling of pecorino. The top layer should be besciamella and cheese.'),
('28997', '11', 'Bake in the oven for 45 minutes. Allow to rest for 10 minutes before slicing and serving.'),
('28997', '12', 'Mound 3 1/2 cups of the flour in the center of a large wooden cutting board. Make a well in the middle of the flour and add the eggs and the olive oil. Using a fork, beat together the eggs and oil and begin to incorporate the flour, starting with the inner rim of the well.'),
('28997', '13', 'As you expand the well, keep pushing the flour up from the base of the mound to retain the well shape. The dough will come together when half of the flour is incorporated.'),
('28997', '14', 'Start kneading the dough with both hands, using the palms of your hands. Once you have a cohesive mass, remove the dough from the board and scrape up and discard any leftover bits. Lightly reflour the board and continue kneading for 6 more minutes. The dough should be elastic and a little sticky. Wrap the dough in plastic and allow to rest for 30 minutes at room temperature.'),
('28997', '15', 'Roll or shape as desired.'),
('28997', '16', 'In a medium sauce pan, heat butter until melted.'),
('28997', '17', 'Add flour and stir until smooth. Over medium heat, cook until light golden brown, about 6 to 7 minutes.'),
('28997', '18', 'Meanwhile, heat milk in separate pan until just about to boil.'),
('28997', '19', 'Add milk to butter mixture 1 cup at a time, whisking continuously until very smooth and bring to a boil. Cook 30 seconds and remove from heat. Season with salt and nutmeg and set aside.'),
('28999', '1', 'Preheat oven to 375F.'),
('28999', '2', 'Mix artichokes, cheese, tomatoes, and basil in medium bowl. Using small sharp knife and working with 1 chicken breast at a time, cut 2-inch-long slit horizontally into 1 side of chicken breast. Move knife back and forth in slit to form pocket. Divide 1 cup cheese mixture among chicken pockets (reserve remainder for frittata). Press edges to seal. Sprinkle chicken with salt and pepper.'),
('28999', '3', 'Heat oil in heavy large ovenproof skillet over high heat.'),
('28999', '4', 'Add chicken. cook 2 minutes. Turn chicken over. transfer skillet to oven.'),
('28999', '5', 'Bake until cooked through, about 10 minutes.'),
('28999', '6', 'Nutrition Data'),
('28999', '7', 'See Nutrition Data''s complete analysis of this recipe '),
('29002', '1', 'Sprinkle chicken with salt and pepper and dredge in flour. Warm oil in a large skillet over medium-high heat.'),
('29002', '2', 'Add chicken and cook, turning once, until browned on both sides, about 4 minutes total.'),
('29002', '3', 'Add wine and artichokes and bring to a boil. Reduce heat, cover and simmer until chicken is almost cooked through, 10 to 15 minutes. Scatter lemon slices over chicken, cover and cook until chicken is done, 2 to 3 minutes longer.'),
('29002', '4', 'Transfer chicken and lemon slices to a platter.'),
('29002', '5', 'Stir thyme into sauce and season with additional salt and pepper, if desired.'),
('29002', '6', 'Pour over chicken and serve.'),
('29008', '1', 'In a medium bowl, mix together artichoke hearts, mayonnaise, Parmesan cheese, Monterey Jack cheese, garlic powder, seasoning salt, soy sauce and hot pepper sauce. Chill in the refrigerator until serving.'),
('29009', '1', 'Arrange romaine lettuce, hearts of palm and artichokes on large platter.'),
('29009', '2', 'Combine the marmalade with lemon juice, mustard, season with salt and pepper and whisk in the olive oil slowly.'),
('29009', '3', 'Pour dressing evenly over salad when ready to serve.'),
('29009', '4', 'Garnish with toasted sliced almonds.'),
('29018', '1', 'Cook artichoke hearts in a 6- to 8-quart pot of boiling salted water until just tender, about 2 minutes.'),
('29018', '2', 'Transfer to a bowl with a slotted spoon. Return water to a boil.'),
('29018', '3', 'Meanwhile, heat oil and butter in a 12-inch heavy skillet over moderately high heat until foam subsides, then saute onion, salt, pepper, red-pepper flakes, and zest, stirring occasionally, until onion is softened, about 8 minutes.'),
('29018', '4', 'Add artichokes and saute, stirring occasionally, 3 minutes. Stir in lemon juice (to taste), then remove from heat and transfer mixture to a large heatproof bowl.'),
('29018', '5', 'While artichokes are sauteing, cook pasta in boiling water until al dente. Reserve 1 cup pasta-cooking water, then drain pasta in a colander and add to artichoke mixture along with 1/2 cup reserved water.'),
('29018', '6', 'Add parsley and cheese and toss to combine. Season pasta with salt and thin with additional reserved cooking water if desired.'),
('29018', '7', 'Serve with additional cheese on the side.'),
('29020', '1', 'Squeeze juice from lemon halves into large bowl. add lemon halves. Fill bowl with water. Trim stem of 1 artichoke. Starting at base, bend leaves back and snap off where they break naturally, continuing until all tough outer leaves have been removed. Using small sharp knife, trim outside of base until smooth and no dark green areas remain.'),
('29020', '2', 'Cut artichoke in half lengthwise. cut out any choke.'),
('29020', '3', 'Add to lemon water. Repeat with remaining artichokes.'),
('29020', '4', 'Heat oil in heavy large pot over medium-high heat. Sprinkle chicken with salt and pepper. Working in batches, add chicken to pot and brown well on all sides, about 12 minutes per batch.'),
('29020', '5', 'Transfer chicken to plate.'),
('29020', '6', 'Drain artichokes.'),
('29020', '7', 'Add artichokes and pearl onions to pot and saute until onions are golden, about 6 minutes.'),
('29020', '8', 'Add vinegar and stir until evaporated, about 3 minutes. Stir in 1/2 cup water, garlic and bay leaves. Arrange chicken atop vegetables. Sprinkle generously with salt and pepper. Cover. simmer until chicken is tender, about 30 minutes. Discard bay leaves.'),
('29020', '9', 'Transfer chicken and vegetables to platter. Sprinkle with parsley and serve.'),
('29021', '1', 'Heat olive oil in a large skillet over medium-high heat for 1 minute.'),
('29021', '2', 'Add onion to pan. cook until soft (4-5 minutes).'),
('29021', '3', 'Add garlic to pan. cook 2 minutes.'),
('29021', '4', 'Add chicken, 1/2 teaspoon salt, and 1/4 teaspoon pepper to pan. saut until cooked through (3-4 minutes).'),
('29021', '5', 'Transfer to a plate to cool.'),
('29021', '6', 'Combine mayonnaise, lemon juice, 1 tablespoon chopped fresh dill, turmeric, 1/2 teaspoon salt, and 1/2 teaspoonpepper in a large bowl. whisk well.'),
('29021', '7', 'Add cannellini beans, artichoke hearts, and chicken mixture to bowl, stirring to combine. Chill 1 hour.'),
('29021', '8', 'Place chicken salad evenly into butterhead lettuce leaves. garnish with 1 1/2 teaspoons chopped fresh dill.'),
('29023', '1', 'Cut the stems off the artichokes.'),
('29023', '2', 'Place the stems and artichokes in a steamer basket set over 1 inch of simmering water. Cover and steam over moderate heat until the artichoke bottoms are tender when pierced with a knife, about 40 minutes. When cool enough to handle, pull the leaves off the artichokes and trim off any fibrous outer skin. Using a spoon, scrape out the hairy chokes. Quarter the artichoke bottoms. Peel the artichoke stems and cut them into 1/2-inch rounds.'),
('29023', '3', 'In a small skillet, toast the cumin seeds over moderate heat until fragrant, about 40 seconds.'),
('29023', '4', 'Transfer to a spice grinder and let cool. Grind the cumin seeds to a powder and transfer to a large, shallow dish. Stir in the olive oil, vinegar and oregano and season with salt and pepper.'),
('29023', '5', 'Add the artichokes and coat well with the cumin marinade.'),
('29023', '6', 'Let stand at room temperature for 1 hour or refrigerate overnight.'),
('29023', '7', 'In a large heatproof bowl, pour the boiling water over the bulgur. Cover and let stand until the water is absorbed and the bulgur is tender, about 40 minutes. Fluff with a fork. Stir in the olive oil, lemon juice, scallions, parsley, plum tomato and mint. season with salt and pepper. Cover and refrigerate for 1 hour, or until chilled.'),
('29023', '8', 'In a bowl, toss the cherry tomatoes with the spinach, feta and pine nuts. Spoon 2 tablespoons of the marinade from the artichokes over the salad and toss well. season with salt and pepper.'),
('29023', '9', 'Spoon the tabbouleh onto plates and surround with the artichokes. Top with the spinach salad and serve.'),
('29028', '1', 'Bring a pot of lightly salted water to a boil.'),
('29028', '2', 'Add seashell pasta, cook for 8 to 10 minutes, until al dente, and drain.'),
('29028', '3', 'Heat the olive oil and melt the butter in a skillet over medium heat.'),
('29028', '4', 'Mix in the garlic, basil, and artichoke hearts, and cook 5 minutes, until heated through. Toss with the cooked pasta to serve.'),
('29043', '1', 'Stir together first 7 ingredients in a large bowl.'),
('29043', '2', 'Drain thawed spinach well, pressing between paper towels. stir into artichoke mixture. Season with pepper to taste. Cover and chill 30 minutes to 2 days.'),
('29043', '3', 'Serve with chips.'),
('29043', '4', 'Garnish, if desired.'),
('29044', '1', 'Combine 3 quarts water and salt in a Dutch oven, stirring until the salt dissolves.'),
('29044', '2', 'Add chicken to salt mixture. Cover and refrigerate 2 hours.'),
('29044', '3', 'Combine remaining 2 quarts water and juice.'),
('29044', '4', 'Cut off stem of each artichoke to within 1 inch of base. peel stem.'),
('29044', '5', 'Remove bottom leaves and tough outer leaves, leaving tender heart and bottom.'),
('29044', '6', 'Cut each artichoke in half lengthwise. place in lemon water.'),
('29044', '7', 'Heat 1 tablespoon olive oil in a large skillet over medium-high heat.'),
('29044', '8', 'Drain artichokes. pat dry.'),
('29044', '9', 'Add artichokes to pan. Cover and cook 10 minutes or until tender. Uncover and cook an additional 5 minutes or until browned, stirring frequently. Keep warm.'),
('29044', '10', 'Preheat oven to 45'),
('29044', '11', 'Remove chicken from salt mixture. discard salt mixture. Pat chicken dry. sprinkle evenly with pepper.'),
('29044', '12', 'Heat canola oil in a large ovenproof skillet over medium-high heat. Wrap handle of pan with foil.'),
('29044', '13', 'Add chicken to pan, meat side down. saut 1 minute.'),
('29044', '14', 'Bake at 450 for 10 minutes. Turn chicken over. bake an additional 12 minutes or until done. Keep warm.'),
('29044', '15', 'Place a zip-top plastic bag inside a 2-cup glass measure.'),
('29044', '16', 'Pour drippings into bag. let stand 10 minutes (fat will rise to the top). Seal bag. carefully snip off 1 bottom corner of bag.'),
('29044', '17', 'Drain drippings back into pan, stopping before fat layer reaches opening. discard fat.'),
('29044', '18', 'Add white wine to drippings in pan. bring to a boil, scraping pan to loosen browned bits. Reduce heat, and simmer until reduced to 1 cup (about 5 minutes).'),
('29044', '19', 'Add broth to pan. simmer until reduced to 1 1/2 cups (about 10 minutes).'),
('29044', '20', 'Reduce oven temperature to 35'),
('29044', '21', 'Place bread in food processor. pulse 10 times or until coarse crumbs measure 1 cup.'),
('29044', '22', 'Combine remaining 1 tablespoon olive oil and breadcrumbs in a bowl. toss to coat. Arrange crumbs in a single layer on a baking sheet. bake at 350 for 5 minutes or until golden.'),
('29044', '23', 'Add parsley. toss to combine.'),
('29044', '24', 'Serve chicken with artichokes and sauce. Top with breadcrumbs.'),
('29044', '25', 'Serve immediately.'),
('29045', '1', 'Rinse artichokes under cold water, and use a sharp knife to cut the top 1/3 off of each one. Trim the stems to about 1 inch, and remove the smaller leaves from around the base. Use scissors to remove any remaining leaf tips.'),
