INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('4753', '2', 'Let sit for 15 minutes before serving.Meanwhile, heat broiler. In a small bowl, mix together the curry paste, sugar, the remaining tablespoon of oil,  teaspoon salt, and  teaspoon pepper.'),
('4753', '3', 'Place the salmon on a foil-lined broilerproof baking sheet and, dividing evenly, brush with the curry paste mixture. Broil until the salmon is opaque throughout, 5 to 7 minutes.'),
('4753', '4', 'Serve with the slaw.'),
('4754', '1', 'Combine first 4 ingredients in a small bowl. Sprinkle both sides of fish with spice mixture.'),
('4754', '2', 'Heat a large nonstick skillet coated with cooking spray over medium heat, and add fish. Cook 6 minutes on each side or until fish flakes easily when tested with a fork.'),
('4756', '1', 'Preheat the oven to 50'),
('4756', '2', 'Set 1 salmon fillet, skin side down, on a work surface and season with white pepper. Arrange the orange zest on the salmon and top with half of the fennel tops. Cover with the second salmon fillet, skin side up. Pack the remaining fennel tops on the sides of the salmon so that there''s no exposed flesh. Tie the fillets together with kitchen string.'),
('4756', '3', 'Spread the kosher salt in a large roasting pan in an even layer and bake for 15 minutes. Carefully spread 1 cup of the hot salt in the bottom of a large loaf pan that is at least 5 inches wide. Set the salmon in the pan and pour the remaining salt over and around the fish. Gently pack the salt and bake the salmon for 45 minutes.'),
('4756', '4', 'Meanwhile, in a shallow bowl, combine the orange and lemon juices with the olive oil. Season lightly with table salt and white pepper.'),
('4756', '5', 'Add the sliced fennel and the capers, toss and let stand at room temperature for 30 minutes.'),
('4756', '6', 'Scrape the salt off the top of the salmon. Using the string, gently lift the salmon from the pan and set it on a work surface. Scrape the salt from the sides and remove the string. Using a spatula, lift the top fillet and transfer it to a plate, skin side down. Discard the fennel tops and orange zest and cut each fish fillet in half. Lift the salmon from the skin, leaving behind the salt, and transfer to plates. Spoon the fennel salad on top and serve.'),
('4757', '1', 'Pour sesame oil into a 10- to 12-inch ovenproof frying pan over medium heat. When hot, add mango and stir often just until heated through, 1 1/2 to 2 minutes.'),
('4757', '2', 'Scrape into a blender and add vinegar. whirl until very smooth, then whirl in enough white wine or water to give mixture a very thin, pourable consistency (about 1/4 cup).'),
('4757', '3', 'Pour sauce into a small, microwave-safe pitcher. Wipe pan clean.'),
('4757', '4', 'In a 3- to 4-quart pan, combine 2 cups water and the tea bags. bring to a boil over high heat.'),
('4757', '5', 'Remove tea bags and add rice and 1/2 teaspoon salt. stir, cover, and bring to a simmer. Reduce heat and simmer, covered, until rice is tender to bite, 45 to 55 minutes (about 20 minutes for jasmine rice).'),
('4757', '6', 'Meanwhile, in a small bowl, mix 2 1/2 tablespoons water, wasabi powder, and honey until blended. Rinse and dry salmon.'),
('4757', '7', 'Pour olive oil into the 10- to 12-inch ovenproof frying pan over medium-high heat. When hot, lay salmon pieces in pan, skinned side down. cook, turning once with a wide spatula, until lightly browned on both sides, 3 to 4 minutes total.'),
('4757', '8', 'Remove pan from heat and brush wasabi-honey mixture over tops of salmon pieces, using it all.'),
('4757', '9', 'Transfer pan with salmon to a 350 regular or convection oven.'),
('4757', '10', 'Bake just until fish is opaque but still moist-looking in center of thickest part (cut to test), 7 to 10 minutes.'),
('4757', '11', 'Heat mango sauce in a microwave oven at full power (100%), stirring occasionally, about 2 minutes total.'),
('4757', '12', 'Transfer a piece of salmon to each of four warmed plates. spoon rice equally alongside (or set salmon on rice).'),
('4757', '13', 'Drizzle mango pure around salmon and rice.'),
('4757', '14', 'Garnish with chopped cilantro, if desired, and add more salt to taste.'),
('4758', '1', 'In a large, shallow dish, combine the soy sauce and brown sugar with the 2 tablespoons of oil. add the salmon and coat well. Cover and refrigerate for 1 hour.'),
('4758', '2', 'Light a grill.'),
('4758', '3', 'Drizzle the cut sides of the onions with oil and grill over moderately high heat, cut side down, until nicely charred and starting to soften, about 15 minutes. Turn the onions and cook until tender, about 15 minutes longer.'),
('4758', '4', 'Push the onions to the side of the grill. Oil the peppers and grill them, skin side down, away from the hottest part of the grill until lightly charred, about 5 minutes. Turn and grill for 5 minutes. Push them over to the onions.'),
('4758', '5', 'Remove the salmon from the marinade and grill, skin side down, for 8 minutes. Turn and grill until the salmon is just cooked through, 4 minutes longer.'),
('4758', '6', 'Drizzle the onions with oil and the balsamic vinegar. Season with salt and pepper and sprinkle with the thyme.'),
('4758', '7', 'Transfer the salmon, peppers and onions to plates, sprinkle with the marjoram and serve.'),
('4760', '1', 'Preheat oven to 37'),
('4760', '2', 'Combine 1 tablespoon tarragon, 2 tablespoons drained capers, 1/4 teaspoon rind, and tomatoes in an 8-inch-square baking dish. season with salt and pepper.'),
('4760', '3', 'Place salmon, skin side down, on mixture. sprinkle with salt and pepper. Cover with foil.'),
('4760', '4', 'Bake at 375 for 15 minutes. uncover and bake 20 additional minutes, or until the fish flakes easily. Divide sauce among 4 plates. place a salmon fillet on each.'),
('4760', '5', 'Garnish with lime wedges.'),
('4761', '1', 'To make the sesame salt, place the sesame and salt in a mortar and pestle and crush. Set aside.Slice the salmon into fingers and place in a non-metallic dish.'),
('4761', '2', 'Combine the miso and vinegar, add to the salmon and toss to coat.'),
('4761', '3', 'Heat a wok or large non-stick frying pan over high heat until hot.'),
('4761', '4', 'Add the oil and heat until just smoking. Cook the salmon, in batches, for 1 minute, turning, until skin is crispy and fish is just cooked through.'),
('4761', '5', 'Remove and set aside.'),
('4761', '6', 'Add the peas, garlic and extra vinegar to the wok and cook, stirring, for 30 seconds. Arrange on plates, top with salmon pieces and sprinkle with sesame salt.'),
('4761', '7', 'Serve with fried shallots and pickled ginger.'),
('4761', '8', 'Serves 4.'),
('4762', '1', 'Preheat saut pan to medium high heat.'),
('4763', '1', 'Preheat broiler.'),
('4763', '2', 'Arrange tomatoes, onion, and garlic in an even layer on a jelly-roll pan coated with cooking spray. Sprinkle with 1/4 teaspoon salt and pepper. Broil 8 minutes. stir gently. Broil an additional 5 minutes or until vegetables begin to blacken at the edges.'),
('4763', '3', 'Place tomato mixture and tomato paste in a blender or food processor. process until smooth.'),
('4763', '4', 'Place tomato mixture in a saucepan over medium heat. Stir in broth. bring to a simmer. Cook 10 minutes, stirring frequently.'),
('4763', '5', 'Remove from heat. Strain mixture through a sieve into a large bowl. discard solids. Return tomato mixture to saucepan over medium heat.'),
('4763', '6', 'Combine 2 tablespoons water and cornstarch in a small bowl. Stir cornstarch mixture into tomato mixture. Increase heat to medium-high. bring tomato mixture to a boil. Cook for 1 minute, stirring constantly.'),
('4763', '7', 'Remove from heat.'),
('4763', '8', 'Place fish on a broiler pan lightly coated with cooking spray. Sprinkle evenly with 1/8 teaspoon salt. Broil 6 minutes or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('4763', '9', 'Place about 1/4 cup tomato mixture on each of 4 deep plates. top each with 1 salmon fillet. Sprinkle each with 1 tablespoon basil.'),
('4763', '10', 'Garnish with coarsely ground black pepper, if desired.'),
('4765', '1', 'Preheat oven to 425F.  Spray foil-lined baking sheet with cooking spray.'),
('4765', '2', 'Place FROZEN fillets, skin-side down, on baking sheet.'),
('4765', '3', 'Bake 20 to 24 minutes or until fish flakes easily with fork (145F).'),
('4765', '4', 'Meanwhile, place all remaining ingredients in small saucepan. stir to blend in flour.  Cook and stir over medium-high heat until mixture comes to a boil. cook 1 to 2 minutes more or until thickened.'),
('4765', '5', 'Serve sauce over fish.'),
('4766', '1', 'Preheat oven to 425F.  Spray foil-lined baking sheet with cooking spray.'),
('4766', '2', 'Place FROZEN fillets, skin-side down, on baking sheet.  Sprinkle with salt.'),
('4766', '3', 'Bake 20 to 24 minutes or until fish flakes easily with fork (145F).'),
('4766', '4', 'Meanwhile, stir together remaining ingredients in small bowl.'),
('4766', '5', 'Serve over fish.'),
('4768', '1', 'Combine first 4 ingredients in a small bowl. mix well.'),
('4768', '2', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('4768', '3', 'Add salmon, skin side down. cook 4 minutes on each side or until fish flakes easily with a fork or until desired degree of doneness. Arrange 1 fillet on each of 4 plates. Top fillets evenly with jalapeo slices. Spoon about 2 tablespoons soy sauce mixture over each serving. let stand 10 minutes before serving.'),
('4770', '1', 'Spray cold grate of grill with grilling spray.  Preheat grill to medium heat according to manufacturer''s directions. Stir together ketchup, marmalade, soy sauce, mustard, honey and curry powder in small bowl. set aside.'),
('4770', '2', 'Brush fillets with oil.'),
('4770', '3', 'Place flesh side down on grill grate. Cook 5 to 6 minutes or until fillets can be lifted easily off grill without sticking to grate. Turn over with skin side down and cook 2 to 3 minutes more or until fish flakes easily with fork (145F).'),
('4770', '4', 'Transfer fillets to serving platter.'),
('4770', '5', 'Spoon 1 tablespoon sauce over each fillet.'),
('4770', '6', 'Serve remaining sauce on the side.'),
('4771', '1', 'Preheat broiler.'),
('4771', '2', 'Combine first 6 ingredients in a small bowl, stirring well.'),
('4771', '3', 'Place fish on a jelly-roll pan coated with cooking spray.'),
('4771', '4', 'Brush half of marmalade mixture over fish. broil 6 minutes.'),
('4771', '5', 'Brush fish with remaining marmalade mixture. broil for 2 minutes or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('4774', '1', 'Preheat broiler.'),
('4774', '2', 'Place fish on a broiler pan. coat fish with cooking spray, and sprinkle with 1/8 teaspoon pepper. Broil 8 minutes or until fish flakes easily when tested with a fork.'),
('4774', '3', 'Combine sour cream and next 6 ingredients.'),
('4774', '4', 'Place fillets on plates. Spoon sauce over fish.'),
('4775', '1', 'Heat oil in a large nonstick skillet over low heat.'),
('4775', '2', 'Combine broth and next 5 ingredients (broth through garlic).'),
('4775', '3', 'Increase heat to medium-high, and heat 3 minutes.'),
('4775', '4', 'While pan heats, sprinkle fillets with salt and pepper.'),
('4775', '5', 'Add fillets to pan. cook 4 minutes on each side or until fish flakes easily when tested with a fork.'),
('4775', '6', 'Remove fillets from pan.'),
('4775', '7', 'Drain fat from pan, and discard fat.'),
('4775', '8', 'Add broth mixture to pan, scraping to loosen browned bits. Bring to a boil. cook 30 seconds.'),
('4775', '9', 'Remove from heat.'),
('4775', '10', 'Serve sauce over fish.'),
('4776', '1', 'Prepare grill.'),
('4776', '2', 'Combine fresh dill, mustard, rind, juice, salt, pepper, and garlic in a bowl, stirring with a whisk.'),
('4776', '3', 'Add salmon pieces, tossing gently to coat. Thread salmon onto each of 4 (8-inch) skewers.'),
('4776', '4', 'Place salmon on grill rack coated with cooking spray, and grill 3 minutes on each side or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('4776', '5', 'Garnish with dill sprigs, if desired.'),
('4777', '1', 'To prepare salmon, combine first 4 ingredients in a large zip-top plastic bag.'),
('4777', '2', 'Add fish to bag. seal. Marinate 10 minutes, turning occasionally.'),
('4777', '3', 'While fish marinates, heat grill pan or large nonstick skillet over medium-high heat.'),
('4777', '4', 'Remove fish from bag, discarding marinade. Coat pan with cooking spray.'),
('4777', '5', 'Add fish, and cook 5 minutes on each side or until the fish flakes easily when tested with a fork.'),
('4777', '6', 'While fish cooks, prepare the relish.'),
('4777', '7', 'Combine mango and the remaining ingredients.'),
('4777', '8', 'Serve over fish.'),
('4778', '1', 'Bring to a simmer over medium-high heat. immediately reduce heat to medium-low. Poach salmon 10 minutes per inch of thickness or until an instant-read thermometer inserted into thickest point registers 130 degrees.'),
('4778', '2', 'Remove poacher from heat. let cool until no longer steaming, about 1 hour. Refrigerate salmon in court-bouillon overnight.'),
('4779', '1', 'Combine first 7 ingredients in an 11 x 7-inch baking dish. stir well with a wire whisk.'),
('4779', '2', 'Add salmon, turning to coat. Cover and marinate in refrigerator 1 hour, turning occasionally.'),
('4779', '3', 'Remove salmon from dish, and discard marinade. Prepare grill.'),
('4779', '4', 'Place salmon on grill rack coated with cooking spray. grill 5 minutes on each side or until fish flakes easily when tested with a fork.'),
('4779', '5', 'Serve with Cilantro-Coconut Chutney.'),
('4780', '1', 'Combine first 4 ingredients in a heavy-duty zip-top plastic bag. Seal. crush seeds with a meat mallet or rolling pin.'),
('4780', '2', 'Place seed mixture in a large shallow dish. Coat 1 side of each fillet with seed mixture.'),
('4780', '3', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('4780', '4', 'Add fillets, seed sides down. saut 4 minutes on each side or until fish flakes easily when tested with a fork.'),
('4780', '5', 'Remove fish from pan. keep warm.'),
('4780', '6', 'Add apricot nectar and the remaining ingredients to pan, and bring to a boil, scraping pan to loosen browned bits. Cook 1 minute. Reduce heat. return fish to pan. Baste with nectar mixture. Cover and simmer 1 minute.'),
('4781', '1', 'Prepare grill.'),
('4781', '2', 'Combine first 7 ingredients.'),
('4781', '3', 'Place salmon fillet, skin side down, on a cutting board or work surface. brush evenly with olive oil. Sprinkle spice mixture evenly over salmon. gently rub mixture into fish. Cover lightly with plastic wrap, and chill 15 minutes.'),
('4781', '4', 'Place fish, skin side down, on a grill rack coated with cooking spray. grill 10 minutes or until fish flakes easily when tested with a fork.'),
('4782', '1', 'Combine first 8 ingredients in a large zip-top plastic bag, and add salmon to bag. Seal and marinate in refrigerator 1 1/2 hours, turning bag occasionally.'),
('4782', '2', 'Prepare grill or broiler.'),
('4782', '3', 'Remove salmon from bag, reserving marinade.'),
('4782', '4', 'Place salmon on a grill rack or broiler pan coated with cooking spray. Cook 6 minutes on each side or until fish flakes easily when tested with a fork, basting frequently with reserved marinade.'),
('4783', '1', 'Preheat oven to 42'),
('4783', '2', 'Combine first 5 ingredients in a small skillet over medium heat. cook for 1 minute or until fragrant.'),
('4783', '3', 'Transfer toasted spices to a spice grinder or coffee grinder. grind until fine.'),
('4783', '4', 'Cut 4 (12-inch) squares of parchment paper.'),
('4783', '5', 'Place 1 fillet in center of each square. Sprinkle evenly with salt and spice mixture. top fillets evenly with leeks. Fold paper. seal edges with narrow folds.'),
('4783', '6', 'Place packets on a baking sheet.'),
('4783', '7', 'Bake at 425 for 20 minutes or until puffy and lightly browned.'),
('4783', '8', 'Place on plates. cut open.'),
('4783', '9', 'Serve immediately.'),
('4786', '1', 'Heat broiler. In a small bowl, combine the honey and 1 teaspoon of the soy sauce.'),
('4786', '2', 'Place the salmon on a foil-lined broiler-proof baking sheet and season with  teaspoon salt and  teaspoon pepper. Broil for 5 minutes. Spoon the honey mixture over the salmon and broil until the salmon is opaque throughout, 2 to 5 minutes more.Meanwhile, heat the oil in a large skillet over medium-high heat.'),
('4786', '3', 'Add the bell pepper and cook, tossing occasionally, until just tender, 3 to 4 minutes. stir in the ginger.'),
('4786', '4', 'Add the spinach and  teaspoon salt and cook, tossing, until just wilted, 2 to 3 minutes.'),
('4786', '5', 'Add the remaining 2 teaspoons of soy sauce.'),
('4786', '6', 'Serve with the salmon and sprinkle with the sesame seeds.'),
('4787', '1', 'Cut potatoes into 1/2-inch cubes, then cook in a 1- to 1 1/2-quart heavy saucepan of boiling salted water until just tender, 8 to 10 minutes.'),
('4787', '2', 'Drain in a colander and set aside.'),
('4787', '3', 'Cook bacon in a 5-quart heavy pot over moderate heat, stirring occasionally, until crisp, about 8 minutes.'),
('4787', '4', 'Transfer with a slotted spoon to paper towels to drain.'),
('4787', '5', 'Pour off all but 2 tablespoons fat from pot, then cook scallions, corn, garlic, thyme, bay leaf, and red-pepper flakes in fat in pot over moderately low heat, stirring occasionally, until scallions are tender, about 5 minutes.'),
('4787', '6', 'Add milk and cream and bring just to a boil. Reduce heat to moderately low, then add potatoes, salmon, bacon, salt, and pepper and cook, gently stirring occasionally, until salmon is just cooked through and begins to break up as you stir, 5 to 8 minutes. Stir in lemon juice and salt and pepper to taste. Discard bay leaf before serving.'),
('4788', '1', 'In a bowl, mix the vinegar with the olive oil, lemon juice, garlic and lemon zest. Season with salt and pepper.'),
('4788', '2', 'In a large, deep skillet, bring 1 inch of water to a boil. Lightly oil a steamer rack and set it in the skillet. Carefully add the salmon fillets in a single layer. Cover and steam over moderate heat for 5 minutes. Strew the watercress over the salmon, cover and steam for 1 minute.'),
('4788', '3', 'Transfer the salmon and watercress to plates. Spoon the dressing over the salmon and serve.'),
('4789', '1', 'In a small bowl, combine the mustard with the honey and hot sauce.'),
('4789', '2', 'Spread the mixture on both sides of the salmon chops, arrange them in a single layer on a large dish and refrigerate for at least 10 minutes and up to 30 minutes.'),
('4789', '3', 'Preheat the oven to 50'),
('4789', '4', 'On a large rimmed baking sheet, drizzle the asparagus with the olive oil, rolling the spears to coat. Season with salt and pepper and roast for 4 minutes, or until crisp-tender.'),
('4789', '5', 'Meanwhile, in a small bowl, combine the miso paste with the lime juice.'),
('4789', '6', 'Remove the baking sheet from the oven and brush the asparagus generously with the paste. Return to the oven and roast for 3 minutes, or until tender and glazed. Keep warm.'),
('4789', '7', 'Preheat the broiler. Using a spatula, scrape most of the marinade off the salmon and arrange the chops in a layer on a rimmed baking sheet. Broil the salmon on 1 side only for 3 minutes, or until well browned. rotate the baking sheet for even cooking.'),
('4789', '8', 'Transfer the salmon and asparagus to plates and serve at once.'),
('4790', '1', 'Preheat the oven to 40'),
('4790', '2', 'In a medium enameled cast-iron casserole, combine the beets, vinegar, soy sauce, stock and 1/3 cup of the oil. Bring to a simmer. Cover and braise in the oven for about 1 hour, or until the beets are tender.'),
('4790', '3', 'Remove from the oven and let cool slightly. Peel the beets, cut them in wedges and return them to the braising liquid. keep warm. Leave the oven on.'),
('4790', '4', 'In a small saucepan, bring the wine to a boil.'),
('4790', '5', 'Add the cream and return to a boil. Reduce the heat to moderate and cook until reduced by half.'),
('4790', '6', 'Remove from the heat and stir in the arugula. Season with salt and pepper and keep warm.'),
('4790', '7', 'Heat the remaining 3 tablespoons of oil in a large ovenproof skillet. Season the salmon with salt and pepper and sear, skin side down, over high heat until the skin is crisp, about 1 minute. Turn carefully and sear 1 minute.'),
('4790', '8', 'Transfer to the oven and roast the salmon for about 3 minutes, or until medium rare and still bright pink in the center.'),
('4790', '9', 'Transfer to plates and spoon the arugula cream on top.'),
('4790', '10', 'Serve the beets alongside, drizzled with a little of their cooking liquid.'),
('4791', '1', 'Line a baking sheet with lightly greased parchment paper. Season salmon with kosher salt and pepper.'),
('4791', '2', 'Bake at 325 for 12 to 15 minutes or until salmon is no longer translucent but still moist-looking in center. Set aside.'),
('4791', '3', 'Place eggs in small saucepan, and cover with water. Bring to a boil. remove from heat, cover, and let stand 15 minutes. Rinse eggs with cold water, and let cool. Peel, dice, and set aside.'),
('4791', '4', 'Whisk together shallot and next 3 ingredients in a medium bowl. Season with kosher salt and pepper.'),
('4791', '5', 'Bring a 2-quart saucepan of salted water to a boil. Cook asparagus 30 to 60 seconds or until crisp-tender. lift out with a slotted spoon, rinse with cold water, and add to vinaigrette. Cook peas in same boiling water until just cooked, about 1 minute.'),
('4791', '6', 'Drain in a colander, rinse with cold water, and add to asparagus and vinaigrette. Sprinkle in herbs, and toss gently.'),
('4791', '7', 'Transfer salmon to plates using a spatula. Spoon asparagus mixture evenly over salmon. Sprinkle diced eggs over vegetables.'),
('4791', '8', 'Serve warm or at room temperature.'),
('4792', '1', 'Grate 1/4 teaspoon peel from lime and squeeze 1/2 teaspoon juice.  Stir together sour cream, lime peel, lime juice, 1/4 teaspoon cumin, sugar and pepper in small bowl.  Set Lime Sauce aside.'),
('4792', '2', 'Rinse and pat dry salmon.  Sprinkle flesh side with remaining 1/2 teaspoon cumin and salt.'),
('4792', '3', 'Heat oil in 10-inch nonstick skillet over medium-high heat.'),
('4792', '4', 'Add fillet, skin-side down, and cook 4 minutes.  Carefully turn fillet.  Continue cooking 2 to 3 minutes more or until fish flakes easily with fork (145F).'),
('4792', '5', 'Cut fillet into 2 pieces.'),
('4792', '6', 'Serve with Lime Sauce on top or on side of salmon.'),
('4795', '1', 'Combine vinegar and sugar in a small saucepan over medium-high heat. bring to a boil. Cook until reduced to 1/4 cup (about 7 minutes).'),
('4795', '2', 'Place in a large bowl. cool slightly.'),
('4795', '3', 'While vinegar mixture cooks, heat a large nonstick skillet over medium-high heat. Sprinkle fish with 1/4 teaspoon salt. Coat pan with cooking spray.'),
('4795', '4', 'Add fish. cook 4 minutes on each side or until fish flakes easily when tested with a fork.'),
('4795', '5', 'Add 1/2 teaspoon salt, watercress, and pepper to vinegar mixture. toss to coat.'),
('4795', '6', 'Place about 1 1/2 cups watercress mixture on each of 4 plates. top each serving with 1 fillet.'),
('4796', '1', 'Preheat broiler.'),
('4796', '2', 'Place fish, skin sides down, on a broiler pan coated with cooking spray.'),
('4796', '3', 'Combine remaining ingredients except lime wedges. sprinkle over fish. Broil 7 minutes or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('4796', '4', 'Serve with lime wedges, if desired.'),
('4798', '1', 'Prepare grill to medium-high heat. Sprinkle fillets with 1/4 teaspoon salt and 1/4 teaspoon black pepper.'),
('4798', '2', 'Place on grill rack coated with cooking spray, and grill for 4 minutes on each side or until desired degree of doneness.'),
('4798', '3', 'Place tomatoes, onion, and jalapeo on grill rack coated with cooking spray. grill tomatoes, cut side down, 6 minutes. Turn. grill for 1 minute. Grill onion and jalapeo for 6 minutes on each side or until lightly browned.'),
('4798', '4', 'Remove from grill, and cool slightly. Coarsely chop tomatoes and onion. finely chop jalapeo.'),
('4798', '5', 'Combine tomatoes, onion, jalapeo, 1/4 teaspoon salt, 1/4 teaspoon black pepper, and juice from 1/2 lime.'),
('4798', '6', 'Serve salsa over fish.'),
('4798', '7', 'Garnish with lime wedges.'),
('4799', '1', 'Place the dashi, mirin and soy in a small saucepan over medium heat and cook for 23 minutes. Set aside.To make the chilli salt, place the salt and chilli in a bowl and mix to combine. Set aside.Use a small, sharp knife to score the skin of the salmon.'),
('4799', '2', 'Brush with the oil and sprinkle with salt.'),
('4799', '3', 'Heat a large non-stick frying pan over high heat. Cook the salmon skin-side down for 3 minutes, turn and cook for a further 3 minutes or until cooked to your liking. Divide the salmon between bowls and spoon over the dashi sauce. Sprinkle with the chilli salt and serve with the edamame beans.'),
('4799', '4', 'Serves 4.'),
('4801', '1', 'Put the oven rack in the middle position and preheat to 200 degrees F. Using tweezers, remove any pin bones from the salmon. Slice the salmon into 2-3 even pieces.Mash the brown sugar, green curry paste and oil until smooth and spread all over the salmon.'),
('4801', '2', 'Place the fillets onto a baking sheet and put them in the oven.'),
('4801', '3', 'Bake until the thickest part registers 125 F on an instant read thermometer, about 20-30 minutes.For the spinach, blanch in boiling water until just wilted then drain, rinse under cold water and wring out any excess liquid with your hands. Roughly chop the spinach.'),
('4801', '4', 'Heat a saucepan over medium heat, add a splash of oil then fry the garlic until it turns brown.'),
('4801', '5', 'Add the kaffir lime leaves and fry for a few seconds.Provided the can hasn''t been disturbed, there should be a thick layer of coconut cream on the top. Carefully open the can and skim the thick white cream off the top and add it to the pan, you should get about half a can of cream.'),
('4801', '6', 'Add the brown sugar and salt and stir to combine.'),
('4801', '7', 'Add the spinach into the pan to reheat.To serve, spread a layer of creamed spinach down then top with a piece of slow roasted salmon.'),
('4802', '1', 'Fab it up: Preheat oven to 42'),
('4802', '2', 'Combine 1/4 cup chili sauce, 1 teaspoon lower sodium soy sauce, 1 tablespoon freshly grated peeled fresh ginger, and 1 tablespoon chopped scallions.'),
('4802', '3', 'Spread sauce evenly over salmon fillets. place on a foil-lined baking sheet.'),
('4802', '4', 'Bake just until heated through and golden on top (about 5-10 minutes).'),
('4804', '1', 'Whisk mayonnaise, mustard, honey, and vinegar in a small bowl. Mash 5 tablespoons of the dressing into the yolks to make a smooth filling. (Dressing, filling, and eggs can be covered and refrigerated overnight.) When ready to serve, spoon (or pipe) a portion of the yolk mixture into each egg white half. Gently toss lettuce with enough of the remaining dressing to lightly coat. Arrange a portion of lettuce leaves on a salad plate. Top each salad with 2 deviled eggs.'),
('4804', '2', 'Drizzle with a little additional dressing if desired.'),
('4804', '3', 'Serve.'),
('4804', '4', 'Mix strawberries, sugar, and wine in a medium bowl until sugar dissolves.'),
('4804', '5', 'Let stand 30 minutes up to 3 hours.'),
('4804', '6', 'Serve.Set salmon on a large rimmed baking sheet. coat both sides with 2 tablespoons of the olive oil and a generous sprinkling of salt and pepper. Toss potatoes with another 2 tablespoons of olive oil and a generous sprinkling of salt and pepper. place, cut side down, on a second rimmed baking sheet. Toss asparagus with remaining tablespoon of oil and a generous sprinkling of salt and pepper. Adjust oven racks to lowest and upper-middle position.'),
('4804', '7', 'Place potatoes on bottom rack and salmon on upper rack of cold oven, then heat oven to 400oF. Roast until salmon is just opaque throughout, about 25 minutes, and potatoes are golden brown, about 30 minutes.'),
('4804', '8', 'Transfer salmon to a large platter. add asparagus to salmon roasting pan. continue to roast, along with potatoes, until bright green and just tender, 5 to 8 minutes, depending on thickness. Meanwhile, mix extra virgin olive oil, parsley, dill, capers and juice, scallions and lemon zest in a small bowl. set aside. To serve, spoon dill mixture over salmon, garnishing platter with parsley, dill sprigs, and lemon wedges. Arrange potatoes and asparagus on platter with salmon.'),
('4804', '9', 'Serve immediately.Adjust oven rack to lower middle position and heat oven to 350oF.'),
('4804', '10', 'Mix flour, 1/4 cup sugar, and lemon zest in a medium bowl.'),
('4804', '11', 'Add butter and vanilla. beat (or simply mix with hands) to form a smooth dough. Drop dough by generous teaspoons onto a parchment or Silpat-lined cookie sheet. roll into balls.'),
('4804', '12', 'Bake until cookie bottoms are golden brown, about 15 minutes.'),
('4804', '13', 'Transfer cookies to a wire rack to cool completely.'),
('4804', '14', 'Place remaining sugar in a quart-size zipper-lock bag. Working a dozen at a time, drop cookies into sugar. shake to coat.'),
('4804', '15', 'Serve. (Can be stored in an airtight tin up to 1 week.) Makes about 2 dozen.'),
('4804', '16', 'Mix all ingredients in a medium bowl. Cover and refrigerate.'),
('4804', '17', 'Serve with Taste-Like-Fried Tortillas or tortilla chips for dipping. Makes 1 heaping quart.Adjust oven racks to lowest and middle positions and heat oven to 450 degrees.'),
('4804', '18', 'Heat a 5 to 6-quart heavy Dutch oven over low heat. Meanwhile, place roast in a large bowl. coat with 1 tablespoon of oil and season with 1 tablespoon of the cumin and a generous sprinkling of salt and pepper.'),
('4804', '19', 'Mix chiles, chili powder, remaining 1 teaspoon of cumin, and oregano in a small bowl. A few minutes before searing, increase heat to a strong medium-high until wisps of smoke start to rise from the pan.'),
('4804', '20', 'Add roast. sear, turning only once, until both sides form an impressive brown crust, about 8 minutes total.'),
('4804', '21', 'Transfer roast to a plate. set aside.'),
('4804', '22', 'Add garlic to the now empty pot. saute until fragrant and golden, about 30 seconds.'),
('4804', '23', 'Add chili mixture. saute to intensify flavor, another 30 seconds.'),
('4804', '24', 'Add chicken broth, bring to a simmer. return roast to the pot. Using 2 potholders to protect hands, place a sheet of heavy-duty foil over the pot, pressing on the foil so that it touches the stew. Seal foil around the edges. repeat with a second sheet of foil to completely seal. Turn burner on medium-high until you hear juices bubble. Set pot on middle oven rack. cook for a total of 1 1/2 hours.'),
('4804', '25', 'Remove roast from oven, cool to room temperature, and shred into bite size pieces. About 30 minutes before roast is done, toss onions and peppers with remaining 2 tablespoon of oil and sprinkle generously with salt and pepper on a baking sheet large enough for vegetables to fit in a single layer.'),
('4804', '26', 'Place pan on bottom oven rack. cook until tender-crisp, about 30 minutes. When ready to serve, gently warm meat and peppers and onions over low heat.'),
('4804', '27', 'Serve with warm tortillas*, bowls of sour cream, cilantro sprigs, and lime wedges. *Of course you can always microwave tortillas, but I prefer to oven-steam them. For each 8 tortillas, lay a damp paper towel on a 24- by 18-inch piece of heavy-duty foil. Set 2 stacks of 4 flour tortillas each side by side on towel. Cover with another damp paper towel. seal foil completely. Warm in a 350-degree oven until steamy, about 5 minutes.'),
('4804', '28', 'Place slaw ingredients in a large bowl, and when ready to serve, toss with the smaller amount of olive oil and a generous sprinkling of salt and pepper. Taste, adding more oil, salt, or pepper, if necessary.'),
('4804', '29', 'Add the smaller amount of lime juice. toss to coat. Taste, adding more, if necessary.Adjust oven rack to middle position and heat oven to 325 oF. Bring 1 quart of water to boil for a water bath.'),
('4804', '30', 'Whisking constantly, bring sugar and 1/4 cup water to boil over medium-high heat in a medium heavy-bottomed saucepan. When mixture starts to boil, turn heat to medium-low and stop whisking. Continue to simmer until mixture turns golden brown, 10 to 15 minutes.'),
('4804', '31', 'Pour mixture into a 9-inch deep-dish pie plate set in a roasting pan large enough to accommodate it. Meanwhile, beat cream cheese until light and fluffy in a medium bowl.'),
('4804', '32', 'Add eggs, one at a time, scraping down sides, after each addition. Beat in both milks and vanilla until smooth. Set roasting pan in oven. pour flan batter into pie plate and water into roasting pan.'),
('4804', '33', 'Bake until flan is jiggly, but set, about 1 hour.'),
('4804', '34', 'Remove from oven, cool to room temperature, and refrigerate until ready to serve. Run a small knife around pie plate perimeter to loosen flan. Invert onto a large lipped platter.'),
('4804', '35', 'Cut into wedges and serve.'),
('4805', '1', 'Mix wine, orange juice, and soy sauce in 13x9x2-inch glass baking dish.'),
('4805', '2', 'Place salmon, flesh side down, in dish. Cover with plastic wrap and refrigerate 2 hours, turning occasionally.Preheat oven to 450F. Line baking sheet with foil. Shake excess marinade off salmon.'),
('4805', '3', 'Transfer salmon to baking sheet, skin side down. Roast until fish is opaque in center, about 14 minutes. Sprinkle salmon with salt.'),
('4805', '4', 'Transfer to plates. Top with dollops of Cucumber Sour Cream.'),
('4807', '1', 'Preheat oven to 35'),
('4807', '2', 'In a small bowl, stir together the cucumber, sour cream, yogurt, dill, 1 minced garlic clove, 1 tablespoon lemon juice, and salt and pepper to taste. Set aside.'),
('4807', '3', 'Line a large baking pan with aluminum foil. Rinse salmon and pat dry. put skin side down in the pan. Sprinkle with remaining minced garlic clove, lemon juice, and salt and pepper to taste.'),
('4807', '4', 'Bake until barely opaque in the center, 10 to 15 minutes.'),
('4807', '5', 'Serve salmon warm or cold with yogurt sauce.'),
('4807', '6', 'Garnish with dill sprigs, if you like.'),
('4809', '1', 'Preheat oven to 450 degrees. Arrange salmon in a shallow baking pan. Season with salt and pepper. Roast until no longer pink in the middle and flaky, 10 to 13 minutes. Using a flat spatula, remove fillets, leaving skin on the baking sheet.'),
('4811', '1', 'Preheat oven to 450 degrees.'),
('4811', '2', 'Combine yogurt, mustard, dill, and parsley. season with salt and pepper.'),
('4811', '3', 'Place salmon, skin side down, on a rimmed baking sheet.'),
('4811', '4', 'Spread yogurt mixture on salmon.'),
('4812', '1', 'Preheat oven to 250 degrees.'),
('4814', '1', 'Prepare broiler.'),
('4814', '2', 'Combine the first 3 ingredients.'),
('4814', '3', 'Brush mustard mixture over fillets.'),
('4814', '4', 'Place fillets, skin sides down, on a broiler rack coated with cooking spray. broil 8 minutes or until fish flakes easily when tested with a fork.'),
('4814', '5', 'Serve fish with Sweet-and-Sour Cucumbers.'),
('4814', '6', '(Totals include Sweet-and-Sour Cucumbers)'),
('4817', '1', 'Combine the first 4 ingredients in a saucepan, and bring to a boil. Reduce heat, and simmer mixture until reduced to 3/4 cup (about 30 minutes). Strain the apricot mixture through a sieve over a bowl, and discard solids.'),
('4817', '2', 'Preheat broiler.'),
('4817', '3', 'Place salmon fillets on a broiler pan lined with foil. broil 5 minutes.'),
('4817', '4', 'Brush fish with 1/4 cup apricot mixture. Broil for 3 minutes or until lightly browned and fish flakes easily when tested with a fork.'),
('4817', '5', 'Serve the fish with the remaining apricot mixture.'),
('4818', '1', 'Preheat oven to 425.'),
('4818', '2', 'Sprinkle salmon fillets with salt and pepper.'),
('4818', '3', 'Place the fillets in large shallow baking dish.'),
('4818', '4', 'Drizzle with lemon juice, white wine, if desired and olive oil.'),
('4818', '5', 'Bake the fillets at 425 for 6 minutes. add capers and cook 4 to 6 more minutes or until fish flakes easily when tested with a fork.'),
('4818', '6', 'Remove fillets from pan, and keep warm.'),
('4818', '7', 'Garnish with lemons and chives.'),
('4821', '1', 'Whisk 1/3 cup olive oil, pressed garlic, lemon peel, thyme, and 1/2 teaspoon sea salt in small bowl.'),
('4821', '2', 'Place fish, skin side down, in 13x9x2-inch glass baking dish.'),
('4821', '3', 'Brush marinade over top and sides of fish. Cover. chill at least 2 hours and up to 4 hours.'),
('4821', '4', 'Heat 3 tablespoons olive oil in heavy large skillet over medium-high heat.'),
('4821', '5', 'Add onion, celery, tomatoes, chiles, and minced garlic. Saut until vegetables are just soft, about 5 minutes.'),
('4821', '6', 'Mix in black beans and cumin. Reduce heat to medium and cook until flavors blend, stirring occasionally, about 5 minutes. Season to taste with sea salt and pepper. DO AHEAD Can be made 2 hours ahead. let stand at room temperature.Spray grill rack with nonstick spray and prepare barbecue (medium-high heat). Arrange fish, skin side up, on rack. spray skin. Grill fish 4 to 5 minutes. turn over. Grill until fish is just opaque in center, about 3 minutes longer, depending on thickness.  Rewarm beans with 1/4 cup water over medium heat. mix in chopped cilantro.'),
('4821', '7', 'Place 1/2 cup beans on each plate. top with fish and dollop of Piment d''Espelette Mayonnaise. garnish with cilantro leaves.'),
('4822', '1', 'Place salmon filets in a resealable plastic bag.'),
('4822', '2', 'Combine marinade ingredients in a non-reactive bowl or measuring cup.'),
('4822', '3', 'Pour marinade over filets and refrigerate from 1 to 24 hours.'),
('4822', '4', 'In a grill basket sprayed with cooking spray, grill the salmon, skin side down, over hot coals. Flip after 2 to 3 minutes and cook for another 1 to 3 minutes, or until desired doneness.'),
('4822', '5', 'Serve with pineapple salsa spooned on the side.'),
('4822', '6', 'Place all ingredients in a small, non-reactive saucepan. Simmer over low heat for about 5 minutes. Cool. Refrigerate until ready to serve with the salmon.'),
('4823', '1', 'Bring water to a boil in a large skillet.'),
('4823', '2', 'Add salmon. reduce heat, and simmer 7 minutes or until fish flakes easily when tested with a fork.'),
('4823', '3', 'Remove from skillet. place in a shallow dish. Cover and chill.'),
('4823', '4', 'Combine the tomato and next 8 ingredients (tomato through salt). Cover tomato mixture and chill 30 minutes.'),
('4823', '5', 'Place 1 toast slice on each of 4 plates. top each with 1 cup tomato mixture and one fillet.'),
('4823', '6', 'Garnish with basil sprigs, if desired.'),
('4825', '1', 'Preheat oven to 425 degrees.'),
('4825', '2', 'Place parsnips on a rimmed baking sheet and toss with 2 tablespoons safflower oil.'),
('4825', '3', 'Spread in a single layer on the pan and roast until beginning to brown around the edges, about 15 minutes. Meanwhile, combine ginger, rosemary, tamari, orange juice, and remaining safflower oil in a small bowl.'),
('4827', '1', 'Place pine nuts, honey, lemon juice, 1/4 cup olive oil, basil, garlic, and chile in a blender and process until the mixture is pureed. Spoon the sauce over the salmon, and turn to coat. Cover and refrigerate overnight or for at least 4 hours, turning twice.'),
('4827', '2', 'Place bell peppers and watercress in a bowl. Toss with vinegar and 1 tablespoon olive oil. Cover and refrigerate while the salmon cooks.'),
('4827', '3', 'Oil the grill rack and preheat the grill to medium-high.'),
('4827', '4', 'Remove the salmon from the marinade, reserving the marinade. Sprinkle the salmon with salt and pepper on both sides.'),
('4827', '5', 'Place the salmon on the grill rack and grill until opaque throughout, 4 to 6 minutes on each side.'),
('4827', '6', 'Brush occasionally with reserved marinade.'),
('4827', '7', 'Garnish with bell pepper and watercress mixture before serving.'),
('4828', '1', 'Preheat oven to 42'),
('4828', '2', 'Place salmon fillets on a lightly greased rack on an aluminum foil-lined jelly-roll pan. sprinkle with salt and pepper.'),
('4828', '3', 'Place 2 dill sprigs and 2 lemon halves on each fillet.'),
('4828', '4', 'Bake at 425 for 15 to 20 minutes or just until fish flakes with a fork.'),
('4830', '1', 'Preheat oven to 425F.'),
('4830', '2', 'Rub salmon all over with 1 teaspoon oil and season with salt and pepper. Roast, skin side down, on a foil-lined baking sheet in upper third of oven until fish is just cooked through, about 12 minutes.'),
('4830', '3', 'Cut salmon in half crosswise, then lift flesh from skin with a metal spatula and transfer to a plate. Discard skin, then drizzle salmon with oil and sprinkle with herbs.'),
('4832', '1', 'In a 1- to 2-quart pan over high heat, stir soy sauce, wine, sherry, green onions, ginger, and sugar until boiling.'),
('4832', '2', 'Remove from heat and let cool to room temperature, stirring occasionally, about 25 minutes.'),
('4832', '3', 'Meanwhile, with tweezers, pull out tiny pin bones from salmon. Rinse fish and cut into eight equal pieces. arrange in a single layer in a 9- by 13-inch baking dish.'),
('4832', '4', 'Add lemons to cooled soy marinade and pour mixture evenly over fish. Cover and chill fish, turning pieces once, for at least 1 hour or up to 4 hours.'),
('4832', '5', 'Lift fish from marinade and pat dry. discard marinade. Set a 12-inch nonstick ovenproof frying pan (or two 10-inch pans) over medium-high heat. add oil and tilt to coat. Set fish, skin side up, in pan(s) and cook until browned on the bottom, 4 to 5 minutes. With a wide spatula, turn pieces over.'),
('4832', '6', 'Transfer pan(s) with fish to a 500 regular or convection oven.'),
('4832', '7', 'Bake just until fish is barely opaque but still moist-looking in center of thickest part (cut to test), 3 to 5 minutes.'),
('4832', '8', 'Transfer fish to a large platter or dinner plates and serve warm or at room temperature. Just before serving, mound sprouts equally on each serving, sprinkle with sea palm fronds and toasted sesame seeds, and mound crunchy cucumber salad alongside salmon (or serve in a separate dish).'),
('4833', '1', 'Grill, broil or bake at 425F salmon 10 minutes or until salmon is opaque.'),
('4833', '2', 'Serve Orange Salsa with salmon.'),
('4834', '1', 'Combine first 3 ingredients in a zip-top plastic bag. seal and marinate in refrigerator 1 hour, turning occasionally.'),
('4834', '2', 'Preheat oven to 40'),
('4834', '3', 'Remove fish from bag. discard marinade.'),
('4834', '4', 'Combine sugar and next 5 ingredients (through cinnamon). rub over fish.'),
('4834', '5', 'Place fish in an 11 x 7-inch glass or ceramic baking dish coated with cooking spray.'),
('4834', '6', 'Bake at 400 for 12 minutes or until fish flakes easily when tested with a fork.'),
('4834', '7', 'Serve with lemon slices, if desired.'),
('4835', '1', 'Preheat oven to 40'),
('4835', '2', 'Combine first 7 ingredients in a small bowl.'),
('4835', '3', 'Place salmon on the rack of a broiler pan coated with cooking spray. place rack in pan. Rub parsley mixture over salmon.'),
('4835', '4', 'Bake at 400 for 15 minutes or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('4836', '1', 'Preheat oven to 45'),
('4836', '2', 'Combine oil, 1/4 teaspoon salt, 1/4 teaspoon pepper, beans, and potato in a medium bowl. toss to coat.'),
('4836', '3', 'Place potatoes on a jelly-roll pan lined with foil. bake at 450 for 10 minutes.'),
('4836', '4', 'Reduce oven temperature to 42'),
('4836', '5', 'Add beans and tomatoes to pan. move potato mixture to one side of pan. Sprinkle fish with remaining 1/4 teaspoon salt and remaining 1/4 teaspoon pepper.'),
('4836', '6', 'Drizzle juice and Worcestershire sauce over fish.'),
('4836', '7', 'Add fish to pan.'),
('4836', '8', 'Bake at 425 for 18 minutes or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('4836', '9', 'Serve with lemon wedges, if desired.'),
('4837', '1', 'Combine first 3 ingredients in bottom of a large platter.'),
('4837', '2', 'Add fish, skin side up, to ginger mixture. Cover and marinate in refrigerator 20 minutes.'),
('4837', '3', 'Remove fish from marinade. pat dry with paper towel to remove excess marinade.'),
('4837', '4', 'Preheat oven to 45'),
('4837', '5', 'Place a baking sheet in oven 5 minutes.'),
('4837', '6', 'Place shallots and fish, skin side down, on baking sheet. sprinkle with salt and pepper.'),
('4837', '7', 'Brush fish with 1 tablespoon syrup.'),
('4837', '8', 'Bake at 450 for 10 minutes.'),
('4837', '9', 'Brush with 1 tablespoon syrup. bake an additional 7 minutes or until fish flakes easily when tested with a fork. Sprinkle with parsley, if desired.'),
('4838', '1', 'Combine carrots, leeks, lemon slices, thyme, parsley, bay leaf, peppercorns, coriander, salt, and wine in a wide saucepan.'),
('4838', '2', 'Add enough water so the liquid reaches a depth of 1 1/2 inches. Bring to a boil. reduce heat to barely simmering.'),
('4838', '3', 'Add salmon, cover with a lid or a parchment paper round trimmed to fit, and cook until flesh is firm but slightly moist in center, 6 to 8 minutes.'),
('4838', '4', 'Transfer fish to a plate. cover with plastic wrap. Cool to room temperature.'),
('4838', '5', 'Serve with Lemon-Caper Herb Sauce and Watercress-Cucumber Salad, if desired.'),
('4839', '1', 'Heat 1 tablespoon oil in large skillet over medium heat.'),
('4839', '2', 'Add shallots. saut until softened, about 5 minutes.'),
('4839', '3', 'Add garlic, 1/4 teaspoon coarse salt, 1/4 teaspoon thyme, and 1/8 teaspoon allspice. Stir until fragrant, about 30 seconds.'),
('4839', '4', 'Add blueberries, 1/4 cup water, and vinegar. Stir to blend. Mash berries with potato masher or back of fork and cook until sauce thickens, stirring often, 3 to 4 minutes. Season with freshly ground black pepper.'),
('4839', '5', 'Remove from heat. DO AHEAD Can be made 2 hours ahead.'),
('4839', '6', 'Let stand at room temperature. Rewarm before using.'),
('4839', '7', 'Brush grill rack with oil. Prepare barbecue (medium-high heat).'),
('4839', '8', 'Brush salmon on both sides with oil. sprinkle with coarse salt, thyme, allspice, and black pepper. Grill salmon until just opaque in center, 4 to 5 minutes per side.'),
('4839', '9', 'Transfer to plates. Stir 2 tablespoons sliced mint into warm blueberry sauce. Spoon sauce over salmon and sprinkle with remaining 1 tablespoon mint.'),
('4839', '10', 'Serve immediately.'),
('4840', '1', 'Preheat oven to 40'),
('4840', '2', 'Combine first 9 ingredients in a bowl. brush both sides of fish with the orange mixture. Reserve remaining orange mixture.'),
('4840', '3', 'Place fish on a broiler pan coated with cooking spray.'),
('4840', '4', 'Bake at 400 for 15 minutes or until fish flakes easily when tested with a fork.'),
('4840', '5', 'Place remaining orange mixture in a small saucepan. bring to a boil, and cook until reduced to 1/2 cup (about 2 minutes).'),
('4840', '6', 'Serve with fish, and garnish with orange wedges and parsley, if desired.'),
('4841', '1', 'Place a large baking sheet on bottom rack of oven. Preheat oven to 400F.Season salmon with salt and pepper.'),
('4841', '2', 'Cut two half inch slices into flesh of each piece of salmon. roll basil leaves and stuff into slits in salmon.'),
('4841', '3', 'Place a salmon fillet in the center of each piece of parchment paper.'),
('4841', '4', 'Drizzle each fillet with 1 teaspoon of the oil, then place lemon slices on top. Gather sides of parchment up over salmon to form a pouch, leaving no openings, and tie tightly with kitchen twine.'),
('4841', '5', 'Place packages directly on hot baking sheet in oven and cook for 20 minutes.'),
('4841', '6', 'Transfer to plates and carefully open packages to release steam before serving.'),
('4842', '1', 'Place the sugar, soy sauce, hoisin sauce, ginger, dash of red pepper flakes, garlic, and lime juice in a medium nonreactive saucepan.'),
('4842', '2', 'Bring the mixture to a boil, reduce the heat to medium, and cook for 15 to 20 minutes, or until the sauce forms a glaze. Set aside.'),
('4842', '3', 'Preheat the broiler.'),
('4842', '4', 'Place the salmon fillets on a broiler pan and baste with the sauce.'),
('4842', '5', 'Let sit for 15 minutes. Broil them until cooked through, about 8 minutes, basting again with the glaze.'),
('4842', '6', 'Remove the salmon from the heat and baste once more with the glaze before serving.'),
('4842', '7', 'Taste'),
('4842', '8', 'Book, using the USDA Nutrition Database'),
('4842', '9', 'From New Legal Sea Foods Cookbook by Roger Berkowitz & Jane Doerfer Copyright (c) 2003 by Roger Berkowitz & Jane Doerfer Published by Broadway Books.Roger Berkowitz, president and CEO of Legal Sea Foods since 1992, started working in his family''s fish market at the age of ten. He frequently offers his expert opinion on the fishing industry on network news segments (CNN, CBS News, Eye on America, NBC Nightly News), has given culinary advice and demonstrations on the Today Show and Good Morning America, and lectures widely. He and his wife, Lynne, live in Newton, Massachusetts.Jane Doerfer coauthored the previous Legal Sea Foods Cookbook with George Berkowitz. She is the author of several cookbooks, including Going Solo in the Kitchen. Edward Koren is a regular contributor to The New Yorker and has illustrated a number of books, including A Dogs Life and How to Eat Like a Child. He lives in Vermont.'),
('4844', '1', 'In a deep skillet, simmer the broccoli and cauliflower, covered, in 1/2 cup of the water for 3 minutes. transfer to a bowl.'),
('4844', '2', 'In the skillet, heat the 3 tablespoons of vegetable oil.'),
('4844', '3', 'Add the onion and ginger, season with salt and pepper and cook over moderate heat, stirring, until golden, about 8 minutes.'),
('4844', '4', 'Add the turmeric and cook, stirring, until fragrant.'),
('4844', '5', 'Add the coconut milk, lime pickle and remaining water and bring to a simmer. Stir in the vegetables and season with salt and pepper. Cover and remove from the heat.'),
('4844', '6', 'Preheat a grill pan. Rub the salmon with oil and season with salt and pepper. Grill, skin side down, over moderately high heat until crisp, 4 minutes. Turn and grill until just cooked through, 2 minutes longer.'),
('4844', '7', 'Serve the salmon with the vegetables.'),
('4845', '1', 'Bake at 400 for 12-14 minutes depending on the thickness of the fish filets and how many parchment packets you are baking at a time. I also prefer my salmon on the medium-rare side versus overcooked and dry. Open the parchment packet and make sure the salmon is cooked to your desired doneness by cutting into it with a fork and knife.'),
('4845', '2', 'Serve with rice, couscous or red potatoes for a great meal.Pin It'),
('4847', '1', 'Preheat oven to 200 and put a roasting pan half full of water on the bottom rack. Oil a rimmed baking tray and arrange salmon on one side. Pile fennel on other side and drizzle both with olive oil, then sprinkle both with salt and pepper. Toss fennel a little to coat and spread out in pan.'),
('4847', '2', 'Roast salmon until just firm to the touch, about 30 minutes. let cool.'),
('4847', '3', 'Remove salmon skin and break each fillet into 3 or 4 chunks.'),
('4847', '4', 'Put fennel in a medium bowl and mix with purslane, olives, and lemon juice and zest.'),
('4847', '5', 'Arrange salmon on plates with salad and drizzle with a little more oil.'),
('4848', '1', 'Preheat oven to broil.'),
('4848', '2', 'Combine pineapple, jalapeo, pomegranate seeds, lime juice and cilantro in a small dish, tossing gently. Refrigerate until ready to serve.'),
('4848', '3', 'Whisk together the maple syrup and mustard in a small saucepan over medium heat and bring to a boil. Simmer until slightly thickened, about 5 minutes.'),
('4848', '4', 'Remove from heat and set aside.'),
('4848', '5', 'Place the salmon in a foil-lined 9-by-13-inch baking dish. Season with the salt and pepper. Bush salmon with maple syrup mixture. Broil for 5 to 7 minutes or until desired degree of doneness.'),
('4848', '6', 'Serve with Pineapple-Pomegranate Salsa.'),
('4849', '1', 'Preheat oven to 45'),
('4849', '2', 'Combine first 4 ingredients in a bowl. cover and chill.'),
('4849', '3', 'Spread harissa over both sides of salmon. sprinkle with salt.'),
('4849', '4', 'Place salmon on a baking sheet coated with cooking spray.'),
('4849', '5', 'Bake at 450 for 20 minutes or until the fish flakes easily when tested with a fork.'),
('4849', '6', 'Serve with mango salsa.'),
('4850', '1', 'Preheat the oven to 35'),
('4850', '2', 'In a small saucepan, combine the soy sauce and ginger and bring to a simmer.'),
('4850', '3', 'Remove from heat and stir in the honey and mustard.'),
('4850', '4', 'Heat the olive oil in a large nonstick ovenproof skillet. Season the salmon with pepper and add it to the skillet, skinned side up. Cook over high heat until golden and crusty, 2 to 3 minutes. Turn the salmon and spoon the ginger-soy glaze on top.'),
('4850', '5', 'Transfer the skillet to the oven and bake the salmon for 5 minutes, or until cooked through. Using a slotted spatula, transfer the salmon fillets to plates, garnish with the cilantro and serve.'),
('4851', '1', 'Preheat oven to 425F.'),
('4851', '2', 'Combine flaxseed and panko in a small bowl. Set aside.'),
('4851', '3', 'Place salmon in a large baking dish. Season with salt and lemon pepper. drizzle with lemon juice. Rub flaxseed mixture over top of salmon fillets, pressing to coat'),
('4851', '4', 'Bake salmon at 425F for 16 minutes or until fish flakes easily when tested with a fork.'),
('4852', '1', 'Preheat oven to 400 degrees.'),
('4852', '2', 'Slice leek in half lengthwise beginning at white end but not cutting through green end. Rinse thoroughly under cold water separating leaves to remove trapped dirt.'),
('4852', '3', 'Cut green ends off of leek and reserve. Slice white and light green parts.'),
('4852', '4', 'Select a baking sheet large enough to accommodate the fish. Lay out a long double length of heavy-duty aluminum foil on top of the baking sheet across the shorter end of the sheet.'),
('4852', '5', 'Place another perpendicular to the first.'),
('4852', '6', 'Lay out the leek greens on the foil to form a bed where your salmon can nestle.'),
('4852', '7', 'Add half of the sliced leeks, shallots, garlic, herbs and bay leaves.'),
('4852', '8', 'Place the cleaned salmon on top of greens. Generously salt and pepper the both sides of the salmon.'),
('4852', '9', 'Drizzle all over with olive oil and rub to cover top and bottom. Lay tarragon or other herb stems across the top of the fish and cover the top with the rest of the sliced leeks.'),
('4852', '10', 'Optional step: insert an electronic meat thermometer probe inside the thickest end of the salmon. This will help you monitor the cooking process without opening the foil.'),
('4852', '11', 'Bring up the edges of the foil along both ends of the salmon.'),
('4852', '12', 'Add the wine.  Seal the edges together to form a compact tent around the salmon (let the cord of the thermometer poke through one of the seams if you are using one). Repeat with the second layer of foil.   The salmon can rest until you are ready to roast.'),
('4852', '13', 'Place in oven. Roast until internal temperature is 140 degrees. For a 2-3 lb salmon filet this took about 25-30 minutes.'),
('4852', '14', 'Let rest for at least 10 minutes.  Unwrap and remove to serving platter. Discard green leek ends.Top exposed flesh with jus and vegetables.'),
('4852', '15', 'Note:  This is also a fantastic way to cook whole salmon. For a 4lb salmon, you can use relatively the same amount of ingredients. Increase cooking time to 35-40 minutes.'),
('4854', '1', 'Cut the cucumber in half and then slice each half down the middle lengthwise. Use the tip of a teaspoon to scoop out the center seeds.'),
('4854', '2', 'Cut each half into thin slices and place in a colander along with the red onion slices.  Toss with salt and let sit in the sink for at least 30 minutes, until the water drains out.In the meantime, make the dressing: combine the sour cream, mayonnaise, white wine vinegar, dill, garlic, sugar and black pepper in a medium bowl and mix well.When the cucumbers and onions are ready, release any excess water by tapping the colander on the base of the sink, then use a large wad of paper towels to pat the vegetables dry.'),
('4854', '3', 'Add to the dressing and toss well. Cover and chill until ready to serve.Preheat the grill to high heat. Clean the grill rack, then brush lightly with oil. Close the lid and let return to temperature. Rub the salmon with olive oil and season generously with kosher salt (about 1 teaspoon) and pepper.'),
('4854', '4', 'Place the fillets skin side down and grill until golden brown and slightly charred, 4-5 minutes (resist the urge to peek or flip early. when fillets are nicely seared on the first side, they should release easily). Flip the fillets over and continue grilling until done, 2-3 minutes.'),
('4854', '5', 'Let cool slightly, remove the skin if desired, and serve with the cold cucumber-dill salad piled over top or alongside.'),
('4855', '1', 'Cut peel and any white pith from oranges with a sharp knife, then cut sections free from membranes, letting them drop into a bowl. Stir in remaining salsa ingredients.'),
('4856', '1', 'About 30 minutes before putting it in the oven sprinkle a large pinch of brown sugar and small pinch of salt on each salmon fillet and rub onto the flesh side, cover and let them come to room temperature. Preheat the oven to 200 degrees F.'),
('4856', '2', 'Place the salmon fillets on a roasting pan and put them in the oven. Depending on the thickness of your fillets, how cold they are and how accurate your oven temp is, the fish could take anywhere from 30 minutes to over an hour. You don''t want to check it so often that you let all the heat out of the oven, but the best way to tell if it''s done is to stick a fork in it and see if it flakes easily.To make the sauce heat a saucepan.'),
('4856', '3', 'Add the oil, garlic and ginger and fry until fragrant.'),
('4856', '4', 'Add the coriander seed, garam masala, cumin, and curry paste and mash together with the garlic and ginger until the spices give off a nice fragrance.'),
('4856', '5', 'Add the peanut butter and mash it all together into a smooth paste. Turn down the heat and add the coconut milk, whisking to combine into a smooth sauce.'),
('4856', '6', 'Heat until it just comes to a simmer but do not boil.For the slaw, wash and de-string the snap peas. Boil a large pot of well salted water. Drop the peas in the boiling water and lightly blanch (less than a minute).'),
('4856', '7', 'Drain and immediately rinse with cold water. Using a sharp knife slice the snap peas lengthwise into thin strips. Mince the mint and add it to the slaw along with the peanuts. When you''re ready to serve it dress the slaw with the fish sauce and vinegar (if you do it too early the vinegar will discolor the peas and mint).When the salmon is done just plate each fillet and cover with the sauce. It goes nicely with some jasmine rice.'),
('4858', '1', 'Roasted Salmon Stuffed with Spinach, Feta and Ricotta | Whole Foods Market'),
('4858', '2', 'Skip to main content'),
('4858', '3', 'Whole Foods Market'),
