INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('18693', '9', 'Remove from heat. stir in tarragon and butter.'),
('18694', '1', 'Heat a nonstick skillet coated with cooking spray over medium heat.'),
('18694', '2', 'Add pancetta. cook 1 minute or until browned.'),
('18694', '3', 'Place pancetta in a large bowl.'),
('18694', '4', 'Heat oil in pan.'),
('18694', '5', 'Add onion and garlic. saut 7 minutes.'),
('18694', '6', 'Add onion mixture to pancetta.'),
('18694', '7', 'Place flour in pan. Gradually add milk. stir with a whisk until blended. Cook over medium heat until thick (about 5 minutes). stir constantly.'),
('18694', '8', 'Add cream cheese. stir until cheese melts. Stir in peas, 1 cup Parmesan, basil, salt, and pepper.'),
('18694', '9', 'Add cheese sauce and pasta to pancetta mixture. toss well. Sprinkle with 1/4 cup Parmesan.'),
('18695', '1', 'Heat oil in a large Dutch oven over medium-high heat.'),
('18695', '2', 'Add onion, garlic, and pork. saut 5 minutes. Stir in rice.'),
('18695', '3', 'Add water and the next 4 ingredients (through broth). bring to a boil. Cover, reduce heat, and simmer 20 minutes or until liquid is absorbed and rice is tender. Stir in olives, cilantro, and peas.'),
('18701', '1', 'In a small saucepan, cover the rice with the water and bring to a boil. Cover the saucepan and cook over low heat for about 25 minutes, until the rice is tender and the water is absorbed.'),
('18701', '2', 'Spread the rice out on a baking sheet and let cool.'),
('18701', '3', 'In a skillet or wok, heat 1 tablespoon of the oil until shimmering.'),
('18701', '4', 'Add the garlic and cook over moderately high heat until fragrant, about 30 seconds.'),
('18701', '5', 'Add the sirloin, season with salt and cook, turning once, until browned, 1 minute. transfer to a plate.'),
('18701', '6', 'Heat the remaining 2 tablespoons of oil in the skillet.'),
('18701', '7', 'Add the onion and ginger and cook over moderate heat, stirring occasionally, until softened, about 6 minutes. Stir in the greens and stir-fry over high heat until wilted, about 1 minute. Stir in the rice and peas, then the soy sauce and steak and stir well. Season with salt and white pepper and transfer to a bowl.'),
('18701', '8', 'Garnish with the cilantro and serve with lime wedges.'),
('18702', '1', 'Preheat the broiler and position a rack 8 inches from the heat. Arrange the bacon slices on a baking sheet in a single layer. In a small bowl, stir together the honey, soy sauce and five-spice powder and brush liberally over the bacon. Broil for 10 minutes, turning once, until the bacon slices are browned and crisp.'),
('18702', '2', 'Transfer the bacon to a work surface and cut into 1/2-inch pieces.'),
('18702', '3', 'Let the bacon cool.'),
('18702', '4', 'In a large bowl, whisk the olive oil with the lime juice, lime zest, fish sauce and chile oil and season with salt and pepper.'),
('18702', '5', 'Add the snow peas, pea shoots, basil, mint and bacon and toss.'),
('18702', '6', 'Serve right away.'),
('18709', '1', 'Combine the dried peas, bacon, thyme, tomatoes, chiles and garlic in a large pot. Season with salt and pepper and pour the chicken broth over top. Simmer over medium-low heat until the peas are tender, about 1 hour.'),
('18709', '2', 'Drain the peas, reserving the cooking liquid. Discard the thyme and chiles.'),
('18709', '3', 'Remove the bacon, tomatoes and garlic from the cooked peas and set aside.'),
('18709', '4', 'Cut up the bacon and fold it back into the peas along with the cilantro, scallions and lemon juice.'),
('18709', '5', 'Puree the cooking liquid with the tomatoes and garlic in a blender. Dress the peas with the puree and give it a final seasoning with salt and pepper, if necessary. Top with cilantro and a drizzle of olive oil.'),
('18709', '6', 'Photographs by James Baigrie'),
('18710', '1', 'Cook the peas in boiling, slightly salted water until tender, then drain and tip into a blender, adding 1 tablespoon curry paste and the creme fraiche or sour cream. Season to taste with salt and perhaps add more curry paste, depending on how strong it is.'),
('18710', '2', 'Heat the oil and butter in a frying pan until foamy, and then fry the scallops for 2 minutes a side. If you are using big scallops then it is sometimes easier to cut them in half across.'),
('18710', '3', 'When they are cooked, they will have just lost their raw look in the middle and be lusciously tender, while golden and almost caramelised on the outside.'),
('18710', '4', 'Lift the scallops onto two warmed plates and then deglaze the hot pan by squeezing in the lime juice. Stir to mix well and pick up every scrap of flavour, and then pour over the scallops on each plate.'),
('18710', '5', 'Dish up the pea puree alongside the scallops, and sprinkle with the chopped cilantro or Thai basil.'),
('18710', '6', 'Serve with another wedge of lime if you feel like it.'),
('18711', '1', 'Combine sour cream and peas in a small bowl.'),
('18711', '2', 'Cook the pasta according to package directions.'),
('18711', '3', 'Drain, reserving 1/4 cup of the pasta water.'),
('18711', '4', 'Return pasta to pot and fold in sour cream mixture, ham, 3/4 cup cheese, tarragon, salt, and pepper.'),
('18711', '5', 'Divide among 4 bowls and garnish with additional tarragon and remaining Parmesan cheese.'),
('18712', '1', 'Cook peas in a large pot of boiling salted water 8 to 10 minutes or until just tender.'),
('18712', '2', 'Drain, rinse until cooled completely, and drain again.'),
('18712', '3', 'Combine vinegar and next 3 ingredients in a small bowl.'),
('18712', '4', 'Add olive oil in a thin, steady stream, whisking constantly.'),
('18712', '5', 'Add sea salt and pepper. stir in jalapeo.'),
('18712', '6', 'Drizzle half of vinaigrette over peas, and toss to coat.'),
('18712', '7', 'Arrange tomato slices on a platter or individual plates. Spoon peas over tomato, and serve with remaining vinaigrette. Sprinkle with basil, goat cheese, and additional salt and pepper, if desired.'),
('18713', '1', 'Blend the peas and vegetable broth in a blender until smooth. Take the lid off and, with the motor running, pour in the oil in a steady stream to emulsify the mixture.'),
('18713', '2', 'Add the lemon juice then chill in the refrigerator for 1 hour.'),
('18713', '3', 'To make the spicy crab, whisk the canola oil, chili paste, and lemon juice together in a bowl. Fold in the crabmeat and mint and season with a pinch of salt. Fill espresso or sake cups, about 3/4 full, with the chilled pea soup.'),
('18713', '4', 'Garnish the pea shots with a generous tablespoon of the spicy crab and serve immediately.'),
('18717', '1', 'In a medium saucepan of boiling, salted water, cook the shrimp until curled and cooked through, about 3 minutes.'),
('18717', '2', 'Drain and let cool, then cover and refrigerate.'),
('18717', '3', 'In a small saucepan, combine the soy sauce, vinegar, lemon juice, ginger, garlic, shallot, sesame oil, sugar and sambal oelek and simmer over low heat for 3 minutes. Pass the dressing through a fine strainer into a small bowl, pressing on the solids.'),
('18717', '4', 'Put the hijiki in a bowl and cover with hot water.'),
('18717', '5', 'Let stand until rehydrated, about 10 minutes.'),
('18717', '6', 'Drain well.'),
('18717', '7', 'In a small skillet, toast the sesame seeds over moderately high heat until the white seeds are golden, about 30 seconds.'),
('18717', '8', 'Transfer to a plate to cool.'),
('18717', '9', 'Pat the shrimp dry with paper towels. Toss the shrimp with 2 tablespoons of the ginger-soy dressing and let it stand for  5 minutes.'),
('18717', '10', 'In a large bowl, toss the tatsoi with the hijiki, sesame seeds, cucumber, shiso, edamame and chives.'),
('18717', '11', 'Add the shrimp and dressing and toss well. Season the poke with salt and toss again. Spoon the poke onto plates, top with the macadamia nuts and serve immediately.'),
('18719', '1', 'Prepare cake batter and bake as directed on package for 24 cupcakes.  Cool in pans 10 min.  Pierce tops with fork.'),
('18719', '2', 'Add boiling water to gelatin mix. stir 2 min. until completely dissolved. Spoon over cupcakes.'),
('18719', '3', 'Refrigerate 30 min.'),
('18719', '4', 'Remove cupcakes from pans. frost with COOL WHIP.  Decorate with remaining ingredients.'),
('18720', '1', 'Place all the ingredients except salt and inamona. Chill well.'),
('18720', '2', 'Garnish with inamona.'),
('18720', '3', 'Serve with salt on the side'),
('18721', '1', 'Prepare and bake brownie mix in 8-inch square baking pan as directed on package.'),
('18721', '2', 'Remove from oven.  Immediately use round handle of wooden spoon to poke holes at 1-inch intervals down through warm brownies to bottom of pan.'),
('18721', '3', 'Pour milk into large bowl.'),
('18721', '4', 'Add dry pudding mix.  Beat with wire whisk 2 min. or until well blended.  Immediately pour about 1/2 of the thin pudding mixture evenly over warm brownies.  Tap pan lightly to fill holes.'),
('18721', '5', 'Let remaining pudding stand at room temperature to thicken slightly. spread over top of brownies to "frost" brownies.'),
('18721', '6', 'Refrigerate at least 1 hour.'),
('18721', '7', 'Cut into 2-inch squares, then cut each square diagonally in half to form 2 triangles.  Store in tightly covered container in refrigerator.'),
('18723', '1', 'Prepare brownie batter and bake as directed on package for 8- or 9-inch square pan. Immediately poke deep holes in brownie at 1-inch intervals, using round handle of wooden spoon.'),
('18723', '2', 'Beat pudding mix and milk in large bowl with whisk 2 min.'),
('18723', '3', 'Add food colorings to tint pudding desired shade of orange. Immediately pour about half the pudding evenly over warm brownie. tap pan lightly on work surface to evenly fill holes in brownie with pudding.'),
('18723', '4', 'Let stand 5 min.'),
('18723', '5', 'Spread remaining pudding over top of brownie.'),
('18723', '6', 'Refrigerate at least 1 hour before serving.'),
('18723', '7', 'Cut into 2-inch squares, then cut each square diagonally in half to form triangles.'),
('18724', '1', 'In a medium size non-reactive bowl, combine Ahi, soy sauce, green onions, sesame oil, sesame seeds, chili pepper, and macadamia nuts. mix well. Refrigerate at least 2 hours before serving.'),
('18725', '1', 'Prepare cake batter as directed on pkg., using the egg white version.'),
('18725', '2', 'Pour evenly into 24 paper-lined or greased medium muffin cups, then bake as directed on package.  Cool cupcakes in pan 15 min.  Pierce cupcakes with large fork at 1/4-inch intervals.'),
('18725', '3', 'Stir boiling water into dry gelatin at least 2 min. until completely dissolved. spoon over cupcakes.  Refrigerate 3 hours.'),
('18725', '4', 'Spread whipped topping over cupcakes.  Draw umbrellas on cupcakes with decorating gel.  Sprinkle with colored sugar. top with jelly beans.  Store leftover cupcakes in refrigerator.'),
('18728', '1', 'Prepare cake batter and bake as directed on package for cupcakes.  Cool in pans 10 min. Pierce tops with fork.'),
('18728', '2', 'Add boiling water to gelatin mix in small bowl. stir 2 min. until completely dissolved. Spoon over cupcakes. Refrigerate 30 min.'),
('18728', '3', 'Remove from pans.'),
('18728', '4', 'Tint COOL WHIP with food coloring. spread over cupcakes. Decorate as desired.'),
('18730', '1', 'Heat oven to 350F.'),
('18730', '2', 'Prepare cake batter using the egg white version, and bake in 24 paper-lined muffin cups as directed on package.  Cool in pans 15 min.  Pierce cupcakes with large fork at 1/2-inch intervals.'),
('18730', '3', 'Add boiling water to gelatin mix. stir with whisk 2 min. until completely dissolved.  Spoon over cupcakes.  Refrigerate 3 hours.'),
('18730', '4', 'Frost cupcakes with COOL WHIP.  Draw footballs on cupcakes with frosting.   Use decorating icing to draw the laces.'),
('18731', '1', 'Prepare cake batter and bake as directed for cupcakes.  Cool in pans 10 min.  Pierce tops with fork.'),
('18731', '2', 'Add boiling water to gelatin mix. stir 2 min. until completely dissolved.  Spoon over cupcakes.  Refrigerate 30 min.'),
('18731', '3', 'Remove from pans.'),
('18731', '4', 'Tint COOL WHIP with food coloring. spread onto cupcakes.  Decorate as desired.'),
('18738', '1', 'Melt butter with oil in heavy large skillet over medium-high heat.'),
('18738', '2', 'Add onion and sugar. Saute until onion is lightly browned, about 7 minutes.'),
('18738', '3', 'Add vinegar. stir to blend.'),
('18738', '4', 'Add radicchio, raisins, salt, and pepper. Cook until radicchio is just wilted, about 5 minutes.'),
('18738', '5', 'Transfer to serving dish. sprinkle with pine nuts.'),
('18747', '1', 'Lightly oil a 9-inch square glass or ceramic baking dish. In a medium saucepan, combine the water, soy milk, garlic, rosemary and thyme and bring to a boil.'),
('18747', '2', 'Remove from the heat, and let steep for 10 minutes.'),
('18747', '3', 'Discard the garlic, rosemary and thyme and return the mixture to a boil. Gradually whisk in the polenta and simmer over low heat, whisking often, until very thick and no longer gritty, 10 minutes. Season with salt and pepper.'),
('18747', '4', 'Pour the polenta into the baking dish.'),
('18747', '5', 'Let cool to room temperature, then cover and refrigerate for at least 2 hours.'),
('18747', '6', 'Meanwhile, in a small saucepan, boil the balsamic vinegar over moderately high heat until reduced to 1/4 cup, about 15 minutes.'),
('18747', '7', 'Let cool to room temperature.'),
('18747', '8', 'Light a grill.'),
('18747', '9', 'Drizzle the radicchio wedges with olive oil and season with salt and pepper. Grill over moderately high heat until lightly charred and just tender, about 3 minutes per side. Clean the grill with a wire brush.'),
('18747', '10', 'Carefully unmold the polenta and cut it into 8 wedges or squares.'),
('18747', '11', 'Brush all over with olive oil. Grill the polenta until it''s lightly charred on the bottom and releases easily, 4 minutes per side. Arrange the grilled polenta and radicchio on plates, drizzle with the balsamic reduction and serve.'),
('18751', '1', 'Watch how to make this recipe.'),
('18751', '2', 'Soak the radicchio leaves in ice water to crisp up.'),
('18751', '3', 'Cook the rice with the garlic and herb seasoning according to package directions.'),
('18751', '4', 'Meanwhile, heat the oil in a large skillet over medium heat.'),
('18751', '5', 'Add the carrots and scallions and saute 2 minutes.'),
('18751', '6', 'Add the pork, cooked rice, and 2 tablespoons soy sauce and cook 2 more minutes to heat through.'),
('18751', '7', 'Spoon the pork mixture into the radicchio leaves.'),
('18751', '8', 'Serve with additional soy sauce for dipping, if desired.'),
('18752', '1', 'Preheat broiler.'),
('18752', '2', 'Whisk together vinegar, garlic, lemon juice, 1/2 cup oil, and 1/2 teaspoon each of salt and pepper in a large bowl.'),
('18752', '3', 'Put radicchio in a 4-sided sheet pan and toss with remaining 2 tablespoons oil. Broil 5 to 6 inches from heat, turning occasionally, until slightly wilted, 3 to 4 minutes.'),
('18752', '4', 'Add hot radicchio to balsamic marinade and gently toss to coat. Cover bowl (to keep heat in) and marinate, tossing once or twice, at least 1 hour.'),
('18752', '5', 'Transfer radicchio to a serving dish, pouring some of marinade over top. Scatter basil over radicchio.'),
('18752', '6', 'Drizzle ricotta with oil in a small bowl and serve with radicchio.'),
('18762', '1', 'Preheat oven to 450F. Rinse radicchio wedges in cold water. gently shake off excess water (do not dry completely).'),
('18762', '2', 'Place radicchio in large bowl.'),
('18762', '3', 'Drizzle with olive oil and sprinkle with thyme, salt, and pepper. toss to coat.'),
('18762', '4', 'Arrange radicchio wedges, 1 cut side up, on rimmed baking sheet. Roast until wilted, about 12 minutes. Turn over and roast until tender, about 8 minutes longer.'),
('18762', '5', 'Arrange radicchio on platter, drizzle with balsamic vinegar, and serve.'),
('18762', '6', 'Market Tip'),
('18762', '7', 'Radicchio (red-leaf Italian chicory) is available in many varieties. The most widely distributed in this country are the round head variety (di Castelfranco or di Chioggia), traditionally used in salads, and the long, flat, finger-shaped radicchio di Treviso, which is excellent grilled.'),
('18764', '1', 'Heat oven to 400 F. Pat the chicken dry with paper towels. Rub the chicken, inside and out, with 2 teaspoons of the oil and season with 1 teaspoon salt and 1/4 teaspoon pepper.'),
('18764', '2', 'Place in a roasting pan and cook for 30 minutes. Meanwhile, in a large bowl, combine the radicchio, vinegar, rosemary, 1/2 teaspoon salt, 1/4 teaspoon pepper, and the remaining oil.'),
('18764', '3', 'Add to the pan and continue cooking until the chicken is cooked through (internal temperature 180 F) and the radicchio is soft and brown at the edges, about 25 minutes.'),
('18764', '4', 'Transfer the chicken to a cutting board and let rest at least 10 minutes before carving. Divide the radicchio among individual plates and serve with the chicken.'),
('18765', '1', 'Whisk 3 tablespoons olive oil and next 5 ingredients in small bowl to blend. Season sauce to taste with salt and pepper. DO AHEAD Can be made 2 hours ahead.'),
('18765', '2', 'Let stand at room temperature.'),
('18765', '3', 'Prepare barbecue (medium-high heat) or heat heavy large skillet over medium-high heat.'),
('18765', '4', 'Brush veal chops with remaining 1 tablespoon olive oil. sprinkle with salt and pepper.'),
('18765', '5', 'Place veal chops on grill or in skillet and cook to desired doneness, about 6 minutes per side for medium.'),
('18765', '6', 'Transfer to platter.'),
('18765', '7', 'Brush radicchio lightly with some of sauce.'),
('18765', '8', 'Place leaves on grill or in batches in skillet and cook just until slightly wilted but not brown, pressing lightly to flatten, about 45 seconds to 1 minute per side.'),
('18765', '9', 'Divide radicchio and veal chops between plates. Spoon sauce over and serve.'),
('18767', '1', 'Cut radicchio heads in half lengthwise. cut out and discard cores. Thinly slice radicchio crosswise and transfer to a large bowl. Peel and core pears. cut into 1/2-inch chunks.'),
('18767', '2', 'Add pears and cheese to bowl with radicchio.'),
('18767', '3', 'In a small bowl or glass measure, mix lemon juice, olive oil, and salt to taste.'),
('18767', '4', 'Pour over radicchio mixture and mix gently to coat.'),
('18767', '5', 'Serve at once.'),
('18769', '1', 'In a 4- to 6-quart pan over high heat, bring 2 quarts water to a boil.'),
('18769', '2', 'Add pasta and cook until tender to bite, about 10 minutes.'),
('18769', '3', 'Drain, rinse with cold water, and drain again.'),
('18769', '4', 'Meanwhile, cut common and shiitake mushrooms into irregular chunks. In a 12-inch frying pan or 14-inch wok over medium-high heat, melt 1 tablespoon butter with the olive oil. When butter is foamy, add mushrooms. Sprinkle with salt and pepper and cook, stirring often, until mushrooms are lightly browned, 4 to 5 minutes.'),
('18769', '5', 'Add remaining tablespoon butter to pan. When melted, add garlic and ginger and stir until fragrant, 1 minute.'),
('18769', '6', 'Add radicchio and edamame and stir until radicchio is wilted, 1 to 2 minutes.'),
('18769', '7', 'Remove from heat.'),
('18769', '8', 'In a large bowl, whisk vinegar, mustard, and soy sauce until combined.'),
('18769', '9', 'Add pasta and mushroom mixture and stir gently to coat.'),
('18769', '10', 'Add salt and pepper to taste.'),
('18769', '11', 'Serve warm or let cool to room temperature. top with shaved parmesan cheese just before serving.'),
('18770', '1', 'Divide the cheese equally among the radicchio leaves, placing it in the center. Fold one edge of each leaf over cheese, then roll up gently to enclose. Wrap a slice of pancetta around each roll and secure with one or two toothpicks (it''s okay if pancetta tears a little).'),
('18770', '2', 'Lay radicchio rolls on an oiled barbecue grill over medium-hot coals or medium-high heat on a gas grill (you can hold your hand at grill level only 3 to 4 seconds). close lid on gas grill. Turn rolls as needed until pancetta is lightly browned and crisp on all sides, 5 to 8 minutes total.'),
('18770', '3', 'Arrange rolls on a platter and drizzle with vinegar.'),
('18770', '4', 'Serve warm or at room temperature.'),
('18773', '1', 'In a small bowl, combine the red wine vinegar, water, sugar, and salt.'),
('18773', '2', 'Add the onion and let stand for 1 hour.'),
('18773', '3', 'Unroll the slices of pancetta and wrap 2 pieces of pancetta around each radicchio quarter. Set aside.'),
('18773', '4', 'Heat a 10- to 12-inch nonstick saut pan over medium heat for 1 minute. Gently place the radicchio in the pan and cook, turning frequently with tongs, until the pancetta is browned and crisp, 6 to 8 minutes.'),
('18773', '5', 'Transfer to a plate. Sprinkle with salt and pepper, cover with foil, and keep in a warm place.'),
('18773', '6', 'Drain any fat from the pan, and add the balsamic vinegar and olive oil. Bring to a boil and reduce by half.'),
('18773', '7', 'Remove from the heat.'),
('18773', '8', 'Drain the onions, discarding the liquid, and arrange one-quarter of the onions in a small pile in the center of each plate. Lean the warm radicchio pieces up against the onions like a teepee, and spoon about 1 teaspoon balsamic sauce over each piece. Sprinkle with rosemary and serve immediately.'),
('18773', '9', 'var article'),
('18773', '10', 'Type_27_data = {}.'),
('18773', '11', 'article'),
('18773', '12', 'Type_27_data.init_step_by_step_images = 0.'),
('18783', '1', 'In the bowl of a stand mixer, whisk together the yeast, milk and honey.'),
('18783', '2', 'Let stand for 10 minutes as which point you should see lots of bubbles and some definite growth happening.'),
('18783', '3', 'Add flour, salt, and egg and mix with the dough hook to combine. While the mixer is running on medium-low add the soft butter 1 tablespoon at a time. Scrape down the bowl then continue to mix for 8-10 minutes.Cover with a dish towel or plastic wrap and let double, about two hours.'),
('18783', '4', 'Roll the dough into tight balls estimating that you will get between 9-12 buns. This is just a bit under  cup of dough per bun.'),
('18783', '5', 'Place on a parchment lined sheet tray (you may need two if you dont want them to touch at all) then cover with plastic wrap and let double again, about 1  hours.When the buns are just about doubled, pre-heat the oven to 400*.'),
('18783', '6', 'Brush the buns with the additional egg and top with sesame seeds.'),
('18783', '7', 'Bake for about 20  25 minutes, until deep golden on top and bottom.'),
('18783', '8', 'Let cool on a wire rack to prevent steaming.'),
('18784', '1', 'Heat the butter and 1 tablespoon of the oil in a large saucepan over medium heat.'),
('18784', '2', 'Add the onion and cook for 5 minutes.'),
('18784', '3', 'Add the rice and cook, stirring constantly, for 2 minutes. Reduce heat to medium-low.'),
('18784', '4', 'Add the wine and cook, stirring frequently, until the liquid is absorbed.'),
('18784', '5', 'Add the broth, 1/2 cup at a time, stirring occasionally and waiting until its absorbed before adding more. This should take about 30 minutes. The rice should be tender but still slightly firm. Meanwhile, about 5 minutes before the risotto is done, heat 2 tablespoons of the remaining oil in a large skillet over medium heat.'),
('18784', '6', 'Add the radicchio and garlic and cook, stirring occasionally, until the radicchio is browned and slightly wilted, about 5 minutes.'),
('18784', '7', 'Add the oregano (if using), vinegar, and 1/4 teaspoon of the salt.'),
('18784', '8', 'Transfer to a plate.'),
('18784', '9', 'Remove the risotto from heat and stir in the Parmesan, the remaining salt, and the pepper. Cover to keep warm. Wipe out skillet, return to medium heat, and heat the remaining oil.'),
('18784', '10', 'Add the bread crumbs and cook until golden brown, 2 to 3 minutes.'),
('18784', '11', 'Remove from heat. Spoon the risotto into individual bowls and top with the radicchio and bread crumbs.'),
('18786', '1', 'Using a fork or your fingers, shred the chicken meat, discarding the skin and bones. In a large bowl, combine the chicken, carrots, scallions, tarragon, 1/2 teaspoon salt, and 1/4 teaspoon pepper. In a small bowl, whisk together the mustard, vinegar, 1/4 teaspoon salt, and 1/4 teaspoon pepper. Slowly add the oil in a steady stream, whisking constantly until emulsified. Divide the radicchio leaves among individual plates, spoon the chicken salad over the top, and drizzle with the vinaigrette.Substitution: If you find radicchio too peppery, spoon the salad into Boston or Bibb lettuce leaves. Or serve it in endive leaves, as fork-free hors d''oeuvres.'),
('18792', '1', 'Put cider and honey in a small pan over medium-high heat. Cook until reduced to a syrup (about 1 tbsp.), 10 to 15 minutes.'),
('18792', '2', 'Put shallot, vinegar, and 1/2 tsp. salt in a medium bowl and let sit 5 to 10 minutes. Meanwhile, put 1/4 cup pine nuts into a mortar and use pestle to work into a rough paste. Set aside. Stir cider syrup into the shallot-vinegar mixture, then whisk in olive oil. Stir in pine-nut paste to create a creamy dressing and add salt to taste.'),
('18792', '3', 'Put radicchio in a large bowl.'),
('18792', '4', 'Drizzle with half of the dressing and toss thoroughly. Toss in apples, adding more dressing if necessary to coat the salad. Divide salad among 6 plates. Top each salad with prosciutto, parmesan, remaining 1/4 cup pine nuts, and pepper, dividing evenly.'),
('18796', '1', 'Squeeze juice from 1 lemon half into a large bowl of cold water, then drop same half into water.'),
('18796', '2', 'Cut off stem of 1 artichoke and discard.'),
('18796', '3', 'Cut off top inch of artichoke with a serrated knife. Bend back outer leaves until they snap off close to base, then discard several more layers of leaves in same manner until you reach pale yellow leaves with pale green tips.'),
('18796', '4', 'Cut remaining leaves flush with top of artichoke bottom with a sharp knife, then pull out purple leaves and scoop out fuzzy choke with a melon-ball cutter. Rub cut surfaces with remaining lemon half. Trim remaining dark green fibrous parts from base and sides of artichoke with sharp knife, then rub cut surfaces with same lemon half and drop artichoke into the acidulated water. Repeat with remaining artichokes.'),
('18796', '5', 'Just before serving, slice artichokes paper-thin crosswise with slicer. Immediately toss with frisee and radicchio in a large bowl.'),
('18796', '6', 'Drizzle with oil and toss. Sprinkle with kosher salt and pepper and toss.'),
('18796', '7', 'Drizzle with vinegar (to taste) and toss again.'),
('18801', '1', 'In a small saucepan, cook juice over high heat until reduced to 2 tbsp., about 5 minutes. let cool. In a small bowl, whisk together juice, oil, vinegar, salt, and chopped oregano.'),
('18801', '2', 'Cut off ends and outer white membrane from oranges. slice into rounds. In a bowl, gently toss oranges, radicchio, onion, and oregano leaves with dressing to coat.'),
('18803', '1', 'Bring broth and 1 cup water to a simmer in a medium saucepan (do not boil). Keep warm over low heat.'),
('18803', '2', 'Heat oil in a large Dutch oven over medium heat.'),
('18803', '3', 'Add onion to pan, and cook 5 minutes or until tender, stirring frequently.'),
('18803', '4', 'Add rice. cook for 2 minutes, stirring constantly. Stir in 1 1/2 cups Champagne. cook 2 minutes or until liquid is nearly absorbed, stirring constantly. Stir in broth mixture, 1/2 cup at a time, stirring constantly until each portion is absorbed before adding the next (about 20 minutes total).'),
('18803', '5', 'Remove from heat.'),
('18803', '6', 'Stir in remaining 1/2 cup Champagne, radicchio, 1/2 cup cheese, butter, salt, pepper, and nutmeg.'),
('18803', '7', 'Let stand 5 minutes.'),
('18803', '8', 'Serve with remaining 1/2 cup cheese.'),
('18804', '1', 'Heat oil in a large cast-iron or nonstick skillet over medium-high heat.'),
('18804', '2', 'Add onion, and saute 5 minutes, stirring frequently. Continue cooking 10 to 15 minutes or until deep golden brown, stirring frequently.'),
('18804', '3', 'Add radicchio and salt. saute 5 minutes or until wilted.'),
('18804', '4', 'Add garlic. cook 1 minute.'),
('18804', '5', 'Remove from heat. stir in vinegar. Sprinkle with black pepper.'),
('18804', '6', 'Preheat oven to 50'),
('18804', '7', 'Roll dough into a 12-inch circle on a lightly floured surface.'),
('18804', '8', 'Place pizza dough on a 12-inch pizza pan or baking sheet coated with cooking spray and sprinkled with cornmeal. Crimp edges of pizza dough with fingers to form a rim. Sprinkle mozzarella cheese on crust. Top with radicchio mixture. Drop ricotta by teaspoonfuls onto the radicchio mixture.'),
('18804', '9', 'Bake pizza at 500 for 15 minutes or until browned.'),
('18804', '10', 'Cut the pizza into 4 wedges.'),
('18806', '1', 'Preheat oven to 37'),
('18806', '2', 'Cut squash in half lengthwise. discard the seeds and membrane.'),
('18806', '3', 'Place squash halves, cut sides down, on a baking sheet. bake at 375 for 50 minutes or until squash is tender. Cool. Peel squash. mash pulp. Set aside 1 cup pulp, reserving remaining pulp for another use.'),
('18806', '4', 'Bring water and broth to a simmer in a large saucepan. Keep warm over low heat.'),
('18806', '5', 'Place a Dutch oven coated with cooking spray over medium-high heat until hot.'),
('18806', '6', 'Add radicchio to Dutch oven. saut 2 minutes or until wilted.'),
('18806', '7', 'Place radicchio in a bowl. Sprinkle with 1/8 teaspoon pepper. Melt butter in Dutch oven.'),
('18806', '8', 'Add onion. saut 3 minutes or until lightly browned.'),
('18806', '9', 'Add rice. saut 1 minute. Stir in wine and 1/2 cup broth mixture. cook 3 minutes or until the liquid is nearly absorbed, stirring constantly.'),
('18806', '10', 'Add 2 cups broth mixture, 1/2 cup at a time, stirring constantly until each portion of liquid is absorbed before adding the next (about 15 minutes total). Stir in squash pulp. Repeat procedure with remaining 1 1/4 cups broth mixture (about 9 minutes total). Stir in radicchio mixture and half-and-half.'),
('18806', '11', 'Remove from heat. stir in cheese. Sprinkle with 1/8 teaspoon pepper.'),
('18811', '1', 'Bring 6 quarts water to boil and add 2 tablespoons salt. In a 12 to 14-inch saute pan, heat the oil until smoking.'),
('18811', '2', 'Add the shallots, garlic, and chiles and saute until golden brown, about 4 to 5 minutes.'),
('18811', '3', 'Add the wine, bring to a boil, then add the butter, and remove from heat. Cook the pasta according to the package instructions, until just al dente, and drain.'),
('18811', '4', 'Add the drained pasta to the pan with the wine mixture and return pan to heat.'),
('18811', '5', 'Add crab, radicchio, and scallion and toss until radicchio is wilted, about 1 minute.'),
('18811', '6', 'Pour into a warm serving bowl and serve. .'),
('18815', '1', 'To make the salad, coat a large salad bowl with some Real Simple Vinaigrette.'),
('18815', '2', 'Add the salad greens, radicchio, and Cheese Croutons. Toss to coat.'),
('18815', '3', 'Add additional dressing if desired.'),
('18815', '4', 'Serve.'),
('18818', '1', 'In a 5- to 6-quart pan over high heat, bring about 4 quarts water to a boil.'),
('18818', '2', 'Add couscous and cook just until tender to bite, about 6 minutes (10 for orzo).'),
('18818', '3', 'Drain and rinse under cold running water until cool.'),
('18818', '4', 'Meanwhile, in a large bowl, mix vinegar and olive oil.'),
('18818', '5', 'Add couscous, radicchio, pistachios, parsley, and preserved lemon.'),
('18818', '6', 'Mix gently to coat, adding salt and pepper to taste.'),
('18820', '1', 'Cut the radicchio in quarters lengthwise, being sure to keep some of the stem attached to each quarter. Trim off any dark bits of stem. Submerge the radicchio quarters in ice water for 1 hour to remove some bitterness. Put a plate on top of the radicchio to keep them under water.'),
('18820', '2', 'In a medium bowl, combine all ingredients except the mozzarella.'),
('18820', '3', 'Mix well.'),
('18820', '4', 'Prepare a hot fire in your grill, or heat a cast iron grill pan over medium-high heat.'),
('18820', '5', 'Drain the radicchio and place them on paper towels to absorb remaining water. Open up the leaves and spoon the olive oil mixture inside.'),
('18820', '6', 'Place the radicchio quarters on a baking sheet and pour the remaining marinade mixture. Season generously with salt and pepper.'),
('18820', '7', 'Grill the radicchio until browned on the outside but still raw in the center, 3 to 5 minutes, turning occasionally. Be careful, as the oil mixture may flame up.'),
('18820', '8', 'When the radicchio begins to brown, pull from the grill, open up a section of each portion and place a slice of mozzarella inside.'),
('18820', '9', 'Place quarters back onto the sheet pan and place the pan directly on the grill for 5 minutes to melt the cheese.'),
('18820', '10', 'Drizzle any leftover dressing over the top of the grilled radicchio and serve warm.'),
('18820', '11', 'If making radicchio in advance: Before the party, have the radicchio drained and marinated in the vinaigrette in the refrigerator.'),
('18823', '1', 'Combine vinegar and fennel seeds in medium bowl. Gradually whisk in oil. Season dressing with salt and pepper.'),
('18823', '2', 'Cut all peel and white pith from grapefruits.'),
('18823', '3', 'Cut grapefruits between membranes to release segments. Stir segments into dressing.'),
('18823', '4', 'Let stand at least 15 minutes and up to 1 hour.'),
('18823', '5', 'Toss radicchio, spinach and olives in bowl.'),
('18823', '6', 'Add grapefruit segments and dressing to coat. Season with salt and pepper.'),
('18824', '1', 'Melt butter in a 12-inch heavy skillet over medium heat, then continue to cook until it is golden brown, about 2 minutes.'),
('18824', '2', 'Add oil, then nuts, and cook, stirring, until nuts are golden, 1 to 2 minutes.'),
('18824', '3', 'Transfer with a slotted spoon to a plate.'),
('18824', '4', 'Add squash to skillet and cook over medium heat, stirring occasionally, until golden and just tender, 6 to 8 minutes.'),
('18824', '5', 'Add radicchio and 1/2 teaspoon each of salt and pepper and cook, stirring, until wilted and just tender, about 3 minutes.'),
('18824', '6', 'Meanwhile, cook pappardelle in a pasta pot of boiling salted water (2 tablespoon salt for 6 quarts water) until al dente. Reserve 1 cup cooking water, then drain pasta.'),
('18824', '7', 'Add pasta to radicchio mixture with 1/2 cup cooking water and toss over low heat until heated through, 1 to 2 minutes.'),
('18824', '8', 'Add more cooking water to moisten if necessary.'),
('18824', '9', 'Serve topped with nuts and cheese.'),
('18827', '1', 'Heat oven to 400 F. Coat a 9-inch springform pan, round cake pan, or pie plate with 1 tablespoon of the oil and set aside. In a medium saucepan, bring 2 1/4 cups water to a boil.'),
('18827', '2', 'Whisking constantly, slowly add the polenta or cornmeal. Reduce heat to low and cook, stirring, until the polenta starts to pull away from the sides of the pan, 4 to 5 minutes. Stir in the salt, 1/4 teaspoon of the pepper, and the Parmesan.'),
('18827', '3', 'Remove from heat.'),
('18827', '4', 'Spread the polenta over the bottom of the prepared pan, using a spoon to form a raised edge. In a bowl, combine the radicchio, tomatoes, mozzarella, and the remaining oil and pepper. Spoon the mixture over the polenta.'),
('18827', '5', 'Bake for 30 minutes.'),
('18827', '6', 'Cut into wedges.Tip: This crisp polenta crust can accommodate almost any pizza topping. Try arugula and prosciutto, sausage and garlic, or caramelized onions and mushrooms.'),
('18828', '1', 'Bring chicken broth to a simmer in a medium pot. Keep at a simmer, covered, over low heat.'),
('18828', '2', 'Heat 2 tbsp. olive oil and 2 tbsp. butter over medium heat in a heavy-bottomed 8-qt. pot.'),
('18828', '3', 'Add onion and saut, stirring occasionally, until translucent and beginning to turn golden, about 10 minutes.'),
('18828', '4', 'Add rice and saut, stirring constantly, until just the edges of the grains look translucent, about 3 minutes.'),
('18828', '5', 'Add wine and 1/2 tsp. salt and cook, stirring, until wine is completely absorbed by rice.'),
('18828', '6', 'Add about 1/2 cup hot broth to rice and cook, stirring constantly, until broth is completely absorbed by rice. reduce heat to medium-low if mixture starts to boil. Continue adding broth 1/2 cup at a time, stirring until each addition is absorbed before adding the next, until rice is just tender to the bite (15 to 30 minutes. you will have broth left over). Keep rice at a constant simmer. While rice is cooking, cut radicchio into shreds.'),
('18828', '7', 'Heat 1 tbsp. olive oil in a large skillet over medium heat and add radicchio and 1/4 tsp. salt. Cook, stirring occasionally, until wilted and tender, 2 to 4 minutes.'),
('18828', '8', 'Remove rice from heat and stir in gorgonzola dolce, wilted radicchio, pepper, parsley, remaining 1 tsp. butter, and salt to taste. For a looser risotto, stir in 1 to 2 cups remaining broth.'),
('18828', '9', 'Serve immediately.'),
('18828', '10', '*For a recipe, go to sunset.com/chickenbroth'),
('18830', '1', 'Mix mayonnaise, lemon peel, and fresh lemon juice in medium bowl to blend. Season to taste with salt and pepper. Refrigerate 15 minutes.'),
('18830', '2', 'Toss apples, celery, radishes, cranberries, and red onion in large bowl.'),
('18830', '3', 'Add lemon mayonnaise and toss to coat. (Can be prepared up to 8 hours ahead. Cover and refrigerate.)'),
('18830', '4', 'Fold watercress and pecans into salad. Arrange 2 radicchio leaves on each plate. Spoon salad into center of radicchio leaves and serve.'),
('18835', '1', 'Cook beans in boiling water 1 minute. drain. Plunge beans into ice water. drain.'),
('18835', '2', 'Remove tough outer skins from beans. discard skins.'),
('18835', '3', 'Place beans in a large bowl. set aside.'),
('18835', '4', 'Prepare grill.'),
('18835', '5', 'Thread shrimp evenly onto 6 (12-inch) skewers. brush with 1 teaspoon oil. Sprinkle shrimp evenly with 1/4 teaspoon salt and 1/8 teaspoon pepper.'),
('18835', '6', 'Place skewers on a grill rack coated with cooking spray. grill 1 1/2 minutes on each side or until shrimp are done. Cool slightly. remove shrimp from skewers.'),
('18835', '7', 'Add shrimp to beans.'),
('18835', '8', 'Combine remaining 5 teaspoons oil, remaining 1/4 teaspoon salt, remaining 1/8 teaspoon pepper, juice, and garlic in a small bowl, stirring with a whisk.'),
('18835', '9', 'Drizzle juice mixture over shrimp mixture. toss to coat. Stir in parsley.'),
('18835', '10', 'Place 1 radicchio leaf on each of 4 salad plates. spoon 1 cup shrimp mixture into each leaf.'),
('18836', '1', 'In a large bowl, toss the radicchio, escarole, sunflower seeds and tarragon.'),
('18836', '2', 'In a medium skillet, heat the oil.'),
('18836', '3', 'Add the pancetta and cook over moderately high heat, stirring occasionally, until browned, about 3 minutes. Using a slotted spoon, transfer the pancetta to a plate.'),
('18836', '4', 'Add the apple and shallot to the skillet and cook over high heat, stirring, until softened and lightly browned, 2 to 3 minutes.'),
('18836', '5', 'Add the vinegar and boil.'),
('18836', '6', 'Pour the hot dressing over the greens, add the pancetta and toss well. Season with salt and pepper and serve immediately.'),
('18839', '1', 'Preheat oven to 35'),
('18839', '2', 'Put radicchio on a large rimmed baking sheet. Lightly brush all over with oil, sprinkle with salt and pepper, and bake until wilted, 8 to 10 minutes. Meanwhile, open up bread on another baking sheet and bake until lightly toasted, 8 minutes.'),
('18839', '3', 'Let radicchio and bread cool.'),
('18839', '4', 'Layer radicchio on bottom half of ciabatta, then top with roasted peppers, provolone, salami, and basil. Close bread and cut into 4 sandwiches.'),
('18839', '5', 'Combine vinegar and mustard in a small bowl. Just before serving, drizzle dressing into sandwiches through a cut side.'),
('18839', '6', 'Serve with plenty of napkins.'),
('18839', '7', 'Keeps: Up to 2 hours at room temperature, 3 hours with ice packs.'),
('18846', '1', 'TO ROAST THE RADICCHIO: Adjust the oven rack to the middle position, and preheat the oven to 400 degrees.'),
('18846', '2', 'Cut each radicchio half into 5 wedges. In a cast-iron or other oven proof 10-inch skillet, combine 2 tablespoons of the olive oil and 2 teaspoons of the vinegar. Arrange the wedges of radicchio in the skillet in a concentric circle, and place a small piece of rosemary underneath and on top of each wedge.'),
('18846', '3', 'Drizzle the remaining olive oil and vinegar over the radicchio, and sprinkle over the salt. Cover with plastic wrap and then foil, and roast in the oven for 15 minutes.'),
('18846', '4', 'Remove the foil, puncture the plastic to allow the steam to escape, and remove the plastic.'),
('18846', '5', 'Turn the wedges of radicchio over, and on the stovetop, over medium heat, cook the radicchio about 35 minutes to caramelize slightly, being careful not to burn it.'),
('18846', '6', 'TO SOAK THE MOZZARELLA: Bring it to room temperature and slice into -inch-thick slices.'),
('18846', '7', 'Pour warm salted water over the cheese to cover, and allow to sit a few minutes, until softened.'),
('18846', '8', 'Drain the slices on paper towels.'),
('18846', '9', 'Grill the bread (see Notes, below). Rub one side of each slice of bread with the garlic clove, and cut each slice in half on the diagonal.'),
('18846', '10', 'Place the slices on serving plates, garlic side up.'),
('18846', '11', 'FOR THE PESTO: Preheat the oven to 325 degrees.'),
('18846', '12', 'Spread the pine nuts on a baking sheet, and toast in the oven for about 8-10 mnutes, until lightly browned.'),
('18846', '13', 'using a mortar and pestle, pulverize the pine nuts, garlic, basil, and salt into a smooth paste. (If you don''t have one, finely chop the ingredients and smash them with a knife to puree.) Slowly drizzle in the olive oil, and add the Parmesan, mixing well to incorporate. Season with lemon juice and salt to taste, just before serving.'),
('18846', '14', 'TO ASSEMBLE THE SANDWICHES: Arrange 2 or 3 slices of mozzarella over each half-slice of bread, and spoon about a tablespoon of pesto over the cheese. Arrange the radicchio over the pesto and drizzle with olive oil.'),
('18847', '1', 'Trim any stalks from the Chioggia or Treviso radicchio to  inch. Fill a large deep frying pan with salted water. Bring to a boil. lower to a simmer.'),
('18847', '2', 'Place the radicchio in the water in a single layer. Cover with a clean tea towel. Cook in barely simmering water for 30 minutes.'),
('18847', '3', 'While the radicchio is simmering, prepare the bchamel sauce: Melt the butter in a 2-quart saucepan.'),
('18847', '4', 'Add the flour and cook, stirring, over low heat for 5 minutes. Slowly add the milk, whisking briskly to prevent lumps. be sure to scrape the corners, where lumps can hide. Increase the heat to medium. Cook for several minutes, stirring occasionally, until thickened. Stir in the salt and pepper.'),
('18847', '5', 'Remove from the heat and stir in the Parmesan.'),
('18847', '6', 'Preheat the oven to 350F.'),
('18847', '7', 'Butter an 8  8-inch baking dish.'),
('18847', '8', 'Drain the radicchio. Wrap each quarter in a slice of prosciutto. Or, if using Verona radicchio, divide the prosciutto as necessary to wrap each piece.'),
('18847', '9', 'Arrange in a single layer in the buttered pan.'),
('18847', '10', 'Spread with the bchamel, making sure to reach into the corners of the pan.'),
('18847', '11', 'Bake for 15 to 18 minutes, or until bubbly.'),
('18847', '12', 'var article'),
('18847', '13', 'Type_27_data = {}.'),
('18847', '14', 'article'),
('18847', '15', 'Type_27_data.init_step_by_step_images = 0.'),
('18848', '1', 'Put hazelnuts in an 8- or 9-inch pan.'),
('18848', '2', 'Bake in a 350 oven until golden beneath skins, 12 to 15 minutes.'),
('18848', '3', 'Pour onto a towel. let cool. Rub nuts in towel to remove loose skins. Lift nuts from towel and reserve. discard skins.'),
('18848', '4', 'Grate 1/2 teaspoon peel from 1 tangerine.'),
('18848', '5', 'Cut tangerine in half and ream 1/4 cup juice. use another tangerine if necessary. Put peel and juice in a wide, shallow bowl. Peel remaining tangerines. Pull each apart into halves.'),
('18848', '6', 'Cut halves crosswise into 1/4-inch-thick slices.'),
('18848', '7', 'Add to bowl. Pit dates and quarter lengthwise.'),
('18848', '8', 'Add dates, lemon juice, and olive oil to bowl.'),
('18848', '9', 'Add lettuce and radicchio to bowl, mix, and add salt and pepper to taste. Sprinkle with hazelnuts.'),
('18856', '1', 'Cut peel and white pith from oranges. Working over small bowl and using small sharp knife, cut between membranes to release segments. Squeeze membranes to release juice.'),
('18856', '2', 'Combine 1/4 cup orange juice and vinegar in small bowl (reserve remaining juice for another use).'),
('18856', '3', 'Whisk in olive oil. Season with salt and pepper.'),
('18856', '4', 'Toss mache, frisee, and radicchio in large bowl.'),
('18856', '5', 'Add orange segments, sliced red onion, and Kalamata olives.'),
('18856', '6', 'Drizzle orange dressing over salad and toss well to coat. Sprinkle with crumbled feta cheese and serve.'),
('18857', '1', 'Bring a large saucepan of salted water to a boil over high heat. Snap off ends of beans. Core radicchio and finely slice. Blanch beans in water until just tender, 5 to 7 minutes.'),
('18857', '2', 'Drain well and reserve pan.'),
('18857', '3', 'Return pan to medium heat and add butter. When melted, stir in radicchio and garlic. Cook, stirring occasionally, until lettuce is lightly wilted, about 3 minutes.'),
('18857', '4', 'Reduce heat to low and stir in beans. Cook, stirring occasionally, until beans are very tender, about 2 minutes. Season with lemon juice and salt and pepper to taste.'),
('18857', '5', 'Serve hot.'),
('18857', '6', 'var article'),
('18857', '7', 'Type_27_data = {}.'),
('18857', '8', 'article'),
('18857', '9', 'Type_27_data.init_step_by_step_images = 0.'),
('18858', '1', 'Using a mortar and pestle or a heavy knife, mash the garlic and salt until a paste forms.  (If using a knife, mince the garlic with the salt, then smash with the flat of the blade.)'),
('18858', '2', 'In a skillet over medium-high heat, saute the sausage in the oil until browned, about 5 minutes.  Sir in the garlic paste and vinegar and cook, scraping up any browned bits until the garlic is fragrant, another 1 to 2 minutes.'),
('18858', '3', 'Place the radicchio and frisee in a large bowl.'),
('18858', '4', 'Add the sausage mixture and pan drippings and toss well.'),
('18858', '5', 'Serve immediately, seasoning with more salt and oil to taste.'),
('18859', '1', 'Warm a 12-inch skillet over medium-low heat and add 2 tablepoons of oil with the pancetta.  Cook for about 2 minutes, until the pancetta releases its fat and begins to crisp, then add the radicchio with a pinch of salt and pepper.  Stir to coat with the fat and cook until wilted down, 6 to 7 minutes.'),
('18859', '2', 'In the meantime, heat a large heavy pot over medium heat and add the remaining olive oil.'),
('18859', '3', 'Saute the onion until soft, about 8 minutes, then add the rice.  Stir until the edges of the rice kernels turn translucent, then add the wine and stir until it evaporates.'),
('18859', '4', 'Add the warm broth little by little, stirring occassionally, as it is absorbed slowly.  Keep the risotto constantly at a lazy bubble, adjusting the heat as necessary.  Halfway through, stir in the racicchio-pancetta mixture. Total rice cooking time should be about 20 minutes, ending with a somewhat soupy and not-too-stiff consistency.  Season to taste.'),
('18859', '5', 'Stir in the butter and Parmesan and remove from the heat.  Cover and let sit for 2 minutes, then serve immediately.'),
('18861', '1', 'Bring a large pot of well-salted water to a boil over high heat. Meanwhile, trim stems and ribs from chard (save for another use, such as soup, if you like).'),
('18861', '2', 'Cut leaves crosswise into 1/3-in.-wide ribbons. Peel any rubbery outer leaves from radicchio and cut out tough core. discard both. Slice remaining leaves crosswise into 1/3-in.-wide ribbons. Zest lemon and set aside zest. Juice lemon and set aside 3 tbsp. juice.'),
('18861', '3', 'Heat olive oil in a 12-in. frying pan over medium heat.'),
('18861', '4', 'Add garlic and cook until just translucent, about 2 minutes. Increase heat to medium-high.'),
('18861', '5', 'Add chicken broth, sherry, chard, radicchio, and lemon zest. Turn to coat and cook until chard is just tender to the bite, 2 to 3 minutes.'),
('18861', '6', 'Add cream and half the cheese. stir to combine. Stir in chicken and cook until warmed through. Stir in lemon juice and season with salt and pepper.'),
('18861', '7', 'Meanwhile, cook pappardelle in boiling water according to package directions. When pasta is cooked, drain and add to frying pan. use tongs to combine.'),
('18861', '8', 'Transfer pasta to a serving bowl, sprinkle with remaining cheese, and serve.'),
('18864', '1', 'In a saucepan of boiling salted water, blanch the basil until just wilted.'),
('18864', '2', 'Drain the basil, run under cold water, then squeeze dry. transfer to a blender.'),
('18864', '3', 'Add 1/4 cup of the oil and puree. season with salt and pepper.'),
('18864', '4', 'Preheat a grill pan. Toss the peaches with 1/2 tablespoon of the olive oil and season with salt and pepper. Grill over high heat, turning once, until the peaches are lightly browned, 3 minutes. let cool.'),
('18864', '5', 'Transfer the peaches to a bowl.'),
('18864', '6', 'Add the lemon juice and the remaining 1 tablespoon of oil and toss.'),
('18864', '7', 'Add the radicchio, red onion and feta, season with salt and pepper and toss.'),
('18864', '8', 'Arrange the tomatoes on a platter and mound the peach-and-radicchio salad on top.'),
('18864', '9', 'Drizzle the salad with the basil oil and serve immediately.'),
('18866', '1', 'In a food processor, whirl garlic, 1/2 cup soy sauce, the oil, sugar, and five-spice powder until blended. Put pork tenderloin in a shallow dish or zip-lock plastic bag and slowly add soy mixture. Turn pork over to coat in marinade. Cover and refrigerate at least 1 hour and as long as overnight.'),
('18866', '2', 'Preheat broiler to high.'),
('18866', '3', 'Transfer pork to a roasting pan lined with foil. discard marinade. Position roasting pan 6 to 8 inches below broiler and cook until meat begins to brown on top, about 10 minutes. Turn pork over, move roasting pan to center oven rack, and reduce heat to 35'),
('18866', '4', 'Roast meat until a thermometer inserted in center of thickest part reaches 150, about 30 minutes (meat should be slightly pink. cut to check).'),
('18866', '5', 'Transfer to a cutting board, loosely cover with foil, and let rest 10 minutes.'),
('18866', '6', 'Meanwhile, in a small bowl whisk together plum sauce, mustard, remaining 2 tablespoons soy sauce, and the Sriracha. transfer sauce to a serving dish.'),
('18866', '7', 'To assemble wraps, slice tenderloin very thinly and arrange 1 slice on each radicchio leaf. Top with green onion and radish ribbons. Tuck up the bottom of each leaf and fold sides inward to eat.'),
('18866', '8', 'Drizzle with or dip into sauce.'),
('18868', '1', 'Mince 1 garlic clove and mash to a paste with 1/4 teaspoon salt, then transfer to a shallow bowl. Stir in 1 tablespoon oil, 1/4 teaspoon rosemary, and 1/4 teaspoon pepper.'),
('18868', '2', 'Add veal and turn once or twice to coat.'),
('18868', '3', 'Heat remaining tablespoon oil in a 12-inch heavy skillet over moderate heat until hot but not smoking, then cook veal, turning over once, until golden and just cooked through, 6 to 7 minutes total.'),
('18868', '4', 'Transfer veal to a plate.'),
('18868', '5', 'Finely chop remaining garlic clove and add to skillet, then cook over moderate heat, stirring, until golden, about 30 seconds.'),
('18868', '6', 'Add radicchio and beans and cook, stirring, until radicchio begins to wilt, about 2 minutes.'),
('18868', '7', 'Add vinegar and cook until most of vinegar is evaporated.'),
('18868', '8', 'Whisk together broth and cornstarch, then add to bean mixture and boil, scraping up brown bits, until sauce is thickened slightly and about two thirds of liquid is evaporated, about 4 minutes.'),
('18868', '9', 'Remove from heat and stir in remaining 1/4 teaspoon rosemary, 1/8 teaspoon salt, and 1/4 teaspoon pepper.'),
('18868', '10', 'Serve veal with radicchio and beans.'),
('18870', '1', 'Place golden raisins in a small saucepan, and cover with water. Bring to a boil. remove from heat. Cover and let stand 10 minutes.'),
('18870', '2', 'Drain well.'),
('18870', '3', 'Place sliced fennel, torn radicchio, and parsley leaves in a large bowl, and toss gently to combine.'),
('18870', '4', 'Combine the orange juice, vinegar, olive oil, salt, and black pepper, stirring well with a whisk. Stir in raisins.'),
('18870', '5', 'Drizzle orange juice mixture over fennel mixture, and toss gently to coat. Arrange 1 1/3 cups salad on each of 6 plates. sprinkle each serving with 1 teaspoon nuts.'),
('18875', '1', 'Preheat the broiler. Roast the bell pepper under the broiler or over an open flame, turning, until charred all over.'),
('18875', '2', 'Transfer the pepper to a bowl, cover with a plate and let steam for 5 minutes. Peel, seed and core the pepper and cut it into 1/2-inch dice.'),
('18875', '3', 'In a large skillet, heat 1 tablespoon of the olive oil.'),
('18875', '4', 'Add the pancetta and cook over low heat, stirring, until lightly browned, about 8 minutes. Using a slotted spoon, transfer the pancetta to a plate.'),
('18875', '5', 'Add half the chickpeas to the skillet and cook over moderately high heat, shaking the skillet, until the chickpeas are lightly browned and slightly crisp, 3 to 4 minutes. transfer to a plate. Repeat with the remaining chickpeas.'),
('18875', '6', 'In a small bowl, combine the Prosecco with the vinegar, garlic and the remaining 1 tablespoon of olive oil. Season with salt and pepper.'),
('18875', '7', 'Preheat the oven to 40'),
('18875', '8', 'Return the pancetta and chickpeas to the skillet and rewarm them in the oven for 3 minutes. In a large bowl, toss the radicchio with the arugula, provolone, pancetta, chickpeas and roasted red pepper.'),
('18875', '9', 'Add the dressing, toss well and serve at once.'),
('18876', '1', 'Preheat oven to 37'),
('18876', '2', 'Cut squash in half lengthwise. remove seeds.'),
('18876', '3', 'Place squash halves, cut sides down, on a foil-lined baking sheet coated with cooking spray.'),
('18876', '4', 'Bake at 375 for 30 minutes or until tender. Scoop out pulp. set aside. Discard skins.'),
('18876', '5', 'Heat 2 teaspoons oil in a large Dutch oven over medium heat.'),
('18876', '6', 'Add onion, parsley, sage, and thyme. cook 15 minutes or until lightly browned, stirring frequently.'),
('18876', '7', 'Add squash, water, 1 1/4 teaspoons salt, 1/4 teaspoon pepper, and minced garlic. bring to a boil. Partially cover, reduce heat, and simmer 25 minutes.'),
('18876', '8', 'Place about 2 1/2 cups squash mixture in a blender, and process until smooth.'),
('18876', '9', 'Pour pureed soup into a large bowl. Repeat procedure with remaining squash mixture, 2 1/2 cups at a time.'),
('18876', '10', 'Heat 1 tablespoon oil in a large nonstick skillet over medium-high heat.'),
('18876', '11', 'Add radicchio, 1/4 teaspoon salt, and 1/4 teaspoon pepper. saut 5 minutes or until lightly browned.'),
('18876', '12', 'Remove from heat. drizzle with vinegar, tossing to coat. Ladle 1 1/3 cups soup into each of 6 bowls. Top each serving with 1/3 cup radicchio and 1 tablespoon cheese.'),
('18879', '1', 'Preheat broiler.'),
('18879', '2', 'Cook radicchio with salt and pepper in oil in a deep 10-inch skillet over moderate heat, stirring, until just tender, 2 to 3 minutes.'),
('18879', '3', 'Transfer to a bowl and keep warm, loosely covered. Wipe skillet clean.'),
('18879', '4', 'Fill skillet with 1 1/4 inches cold water.'),
('18879', '5', 'Add vinegar and bring to a simmer.'),
('18879', '6', 'Break 1 egg into a cup, then slide egg into simmering water. Repeat with remaining 3 eggs, spacing them in skillet, and poach at a bare simmer until whites are firm but yolks are still runny, 2 to 3 minutes.'),
('18879', '7', 'Toast bread, then spread one side of each piece with truffle butter and cover with cheese. Broil toast on a baking sheet 4 to 6 inches from heat until cheese is just melted.'),
('18879', '8', 'Divide toast among 4 plates, then top with radicchio and poached eggs. Season with salt and pepper.'),
('18882', '1', 'Heat oil in a large Dutch oven over medium-high heat.'),
('18882', '2', 'Add onion. saut 15 minutes or until almost tender, stirring frequently. Reduce heat to medium-low. cook until deep golden (about 20 minutes), stirring occasionally.'),
('18882', '3', 'Add red pepper and garlic. Cook 3 minutes. stir occasionally.'),
('18882', '4', 'Add wine. cook 4 minutes or until liquid evaporates.'),
('18882', '5', 'Cook pasta according to package directions, omitting salt and fat.'),
('18882', '6', 'Drain pasta in a colander over a bowl, reserving 1/4 cup cooking liquid.'),
('18882', '7', 'Add reserved cooking liquid, pasta, radicchio, parsley, and oregano to onion mixture. Sprinkle with salt and black pepper. toss to combine. Top with cheese.'),
('18884', '1', 'In a small jar with a tight-fitting lid, combine garlic paste, pepper, balsamic vinegar, and olive oil. Cap jar and shake vigorously until dressing is emulsified.'),
('18884', '2', 'With a small, sharp knife, cut ends off grapefruit and oranges. Working with 1 fruit at a time, set it cut side down on a cutting board. Following curve of fruit with knife, slice off peel and white pith.'),
('18884', '3', 'Cut between inner membranes and fruit to release segments. put them in a large bowl. Discard membranes and peel.'),
('18884', '4', 'Pour off juices (or just pour into a glass and drink) to keep salad from getting soggy.'),
('18884', '5', 'Thinly slice dates and add to bowl along with radicchio, 1/2 cup parmesan shavings, and 1/4 cup almonds.'),
('18884', '6', 'Pour dressing over salad. toss thoroughly to coat. Turn salad onto a large platter or into a bowl and top with remaining 1/2 cup parmesan and 1/2 cup almonds.'),
('18886', '1', 'Bring water to a boil, salt it and cook pasta to al dente.'),
('18886', '2', 'In a mixing bowl, whisk together the orange marmalade, garlic, oregano, mustard and vinegar. Stream the olive oil into dressing while whisking and season dressing with salt and pepper. Pull off 8 of the outer leaves of radicchio. Form serving cups for the pasta salad out of the leaves using 2 leaves to form each bowl. Chop remaining radicchio. Toss radicchio and pasta and onions with the dressing to combine.'),
('18886', '3', 'Serve pasta in lettuce bowls.'),
('18887', '1', 'Stir fennel seeds in small skillet over high heat until beginning to brown, about 1 minute.'),
('18887', '2', 'Place in spice mill and grind to coarse powder.'),
('18887', '3', 'Transfer to small bowl.'),
('18887', '4', 'Add remaining ingredients. stir to blend. Season with salt and pepper. (Can be made 2 days ahead. Cover and chill.)'),
('18889', '1', 'Combine first 6 ingredients in a large bowl, stirring with a whisk.'),
('18889', '2', 'Add radicchio, radishes, and apples to bowl. toss gently to coat.'),
('18889', '3', 'Place about 3/4 cup salad on each of 8 plates. sprinkle each serving with 1 1/2 teaspoons nuts.');