INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('16993', '1', 'Melt margarine in a large saucepan over medium heat.'),
('16993', '2', 'Add onion and sweet potatoes. saut 5 minutes.'),
('16993', '3', 'Add mustard and remaining ingredients. bring to a boil. Cover, reduce heat, and simmer 20 minutes or until sweet potatoes are very tender.'),
('16993', '4', 'Place sweet potato mixture in a food processor. process until smooth.'),
('16995', '1', 'In a saucepan, melt 3 tablespoons of the butter.'),
('16995', '2', 'Add the milk and sugar and heat just until warm.'),
('16995', '3', 'Transfer to a large bowl, stir in the yeast and let stand until foamy, 5 minutes. Stir in the flour and 1 1/2 teaspoons of salt until a sticky dough forms. Turn the dough onto a lightly floured work surface and knead until smooth, 5 minutes. Oil the bowl and return the dough to it. Cover with plastic and let stand in a draft-free spot until doubled in bulk, about 1 hour.'),
('16995', '4', 'Butter a 10-inch tube or Bundt pan. Punch down the dough and divide it into 4 pieces.'),
('16995', '5', 'Roll each piece into a 12-inch log and cut each log in 12 equal pieces.'),
('16995', '6', 'Roll each piece into a ball.'),
('16995', '7', 'Heat 1 tablespoon of the butter in a skillet.'),
('16995', '8', 'Add the onion and cook over moderate heat until softened, 6 minutes. Stir in the mustard, chives and thyme.'),
('16995', '9', 'Add the remaining 4 tablespoons of butter. stir until melted. Season lightly with salt and transfer to the large bowl to cool slightly.'),
('16995', '10', 'Add half of the dough balls and turn to coat with the onion mixture. Arrange the balls in the bottom of the pan. Repeat with the remaining dough balls. Cover loosely with plastic wrap and let stand until risen to the top of the pan, about 1 hour.'),
('16995', '11', 'Preheat the oven to 42'),
('16995', '12', 'Bake the bread in the lower third of the oven for 25 minutes, or until golden. Cover the pan loosely with foil, reduce the oven temperature to 375 and bake for 30 minutes longer, or until risen.'),
('16995', '13', 'Let the bread cool in the pan for 15 minutes. Set an inverted plate on top and turn the bread out onto it. Set another plate on top and invert the bread so it''s right side up. Break into rolls or cut into slices.'),
('16996', '1', 'Preheat the oven to 45'),
('16996', '2', 'Using poultry shears, cut along each side of the chicken backbone and remove it. Turn the chicken breast side up and press on the breast bone to flatten the chicken. Using a sharp knife, cut partway through both sides of the joint between the thighs and the drumsticks.'),
('16996', '3', 'Cut partway through the joint between the wings and the breast.'),
('16996', '4', 'In a bowl, mix all of the remaining ingredients. Turn the chicken breast down and spread it with half of the mustard mixture. Set the chicken in a large skillet skin side up. spread with the remaining mixture.'),
('16996', '5', 'Set the skillet over high heat and cook the chicken until it starts to brown, 5 minutes.'),
('16996', '6', 'Transfer the skillet to the oven and roast the chicken for 30 minutes, until the skin is browned and the chicken is cooked through.'),
('16996', '7', 'Let the chicken rest for 5 minutes.'),
('16996', '8', 'Transfer the chicken to a cutting board, cut it into 8 pieces and serve.'),
('16998', '1', 'Cook the pasta in a large pot of boiling salted water until al dente. drain. Meanwhile, heat the olive oil in a large, deep skillet.'),
('16998', '2', 'Add the sausage meat and brown over moderately high heat, about 5 minutes.'),
('16998', '3', 'Add the wine and simmer, scraping up the browned bits from the bottom, until reduced by half, about 5 minutes.'),
('16998', '4', 'Add the cream, mustard and crushed red pepper and simmer for 2 minutes.'),
('16998', '5', 'Remove the skillet from the heat, add the pasta and basil and toss to coat.'),
('16998', '6', 'Serve at once.'),
('16999', '1', 'Light a grill. In a shallow dish, whisk the mayonnaise with the mustard, oil, lemon juice, lemon zest, garlic, salt and pepper.'),
('16999', '2', 'Add the asparagus and turn to coat.'),
('16999', '3', 'Let stand at room temperature for 30 minutes.'),
('16999', '4', 'Grill the asparagus over moderately high heat, turning occasionally, until the spears are tender and lightly blistered in spots, about 6 minutes.'),
('16999', '5', 'Serve the asparagus hot or at room temperature.'),
('17000', '1', 'Peel carrots and cut into 1/4-in. matchsticks.'),
('17000', '2', 'Bring 3 cups water and all ingredients except carrots to a boil in a large saucepan. Reduce heat to low and simmer 1 minute.'),
('17000', '3', 'Add carrots and simmer until almost tender, 2 to 3 minutes.'),
('17000', '4', 'Transfer carrots and liquid to a bowl and let cool to room temperature. Chill, covered, overnight to let flavors develop.'),
('17000', '5', 'Serve cold. Keeps, chilled, up to 1 week.'),
('17007', '1', 'Combine yeast and 1/2 cup warm water in a 4-cup liquid measuring cup, and let mixture stand 5 minutes. Stir in buttermilk.'),
('17007', '2', 'Combine flour and next 4 ingredients in a large bowl. cut in shortening with a pastry blender or fork until mixture resembles coarse meal.'),
('17007', '3', 'Add buttermilk mixture, stirring with a fork just until dry ingredients are moistened.'),
('17007', '4', 'Turn dough out onto a well-floured surface, and knead 4 to 5 times.'),
('17007', '5', 'Roll dough to 1/2-inch thickness. cut with a 2-inch round cutter, and place on lightly greased baking sheets. Cover and let rise in a warm place (85), free from drafts, 1 hour.'),
('17007', '6', 'Bake at 425 for 10 to 12 minutes or until golden. Split each biscuit, and spread evenly with Mustard Butter. Stuff biscuits with ham.'),
('17014', '1', 'Toss grated cheese with cornstarch: '),
('17014', '2', 'Place the shredded cheese and cornstarch in a plastic freezer bag. Seal, shake to coat the cheese with flour or cornstarch. Set aside.'),
('17014', '3', 'Rub inside of pot with garlic, add wine, lemon juice, bring to a simmer: Rub the inside of a 4-quart pot with the cut garlic, then discard.'),
('17014', '4', 'Add the wine and lemon juice to the pot, and bring to a low simmer on medium heat.'),
('17014', '5', 'Slowly stir cheese into the wine: Bit by bit, slowly stir the cheese into the wine. Stir constantly in a zig-zag pattern to prevent the cheese from seizing and balling up.'),
('17014', '6', 'Cook just until the cheese is melted and creamy. Do not let boil.'),
('17014', '7', 'Add kirsch, mustard, nutmeg: Once the mixture is smooth, stir in kirsch, mustard and nutmeg.'),
('17014', '8', 'Transfer to a serving pot and keep warm: '),
('17014', '9', 'Transfer the cheese to a fondue serving pot, set over a low flame to keep warm. If your pot is thin-bottomed, a lit candle will probably do. If thick-bottomed, you can use a small Sterno.'),
('17014', '10', 'Arrange dipping foods around the pot: Arrange various dipping foods around the fondue pot. (A lazy Suzan works great for this.)'),
('17014', '11', 'To eat, spear dipping foods with fondue forks or small forks. Dip to coat with the cheese, and eat.'),
('17021', '1', 'Preheat the oven to 45'),
('17021', '2', 'In a large ovenproof skillet, melt the butter. Stir in the bread crumbs and cook over moderate heat until golden. Stir in the parsley and season with salt and pepper.'),
('17021', '3', 'Transfer to a plate and let cool. Wipe out the skillet.'),
('17021', '4', 'Add the olive oil to the skillet and heat until shimmering. Season the chicken with salt and pepper and add it to the skillet, skin side down. Cook over moderately high heat until the skin is browned, 3 minutes. Flip the chicken and roast in the oven for 7 minutes, until just cooked through.'),
('17021', '5', 'Return the skillet to the burner.'),
('17021', '6', 'Add the syrup and vinegar. bring to a boil. Turn the chicken skin side down and cook until richly glazed, about 30 seconds. transfer to plates skin side up.'),
('17021', '7', 'Add the stock to the skillet and boil until reduced by one-third, scraping up any browned bits from the bottom. Stir in the mustard and season with salt and pepper. Spoon the sauce over the chicken. Top with the bread crumbs and serve.'),
('17023', '1', 'In a large skillet, toast the mustard seeds over moderately high heat, shaking the pan frequently, until they pop and start to brown, about 30 seconds.'),
('17023', '2', 'Transfer to a plate and let cool.'),
('17023', '3', 'Add the shallots, sherry vinegar and water to the skillet and simmer over moderately low heat until the liquid is reduced to 1 1/2 teaspoons, about 7 minutes.'),
('17023', '4', 'Add the cream and simmer over moderate heat until thickened, about 3 minutes.'),
('17023', '5', 'Transfer to a bowl and let cool to room temperature, then stir in the butter, mustard and toasted mustard seeds. Season with salt and pepper.'),
('17023', '6', 'In a large pot of boiling salted water, cook the green beans until crisp-tender, about 4 minutes.'),
('17023', '7', 'Drain the beans, pat dry and transfer to a large bowl.'),
('17023', '8', 'Add the mustard-seed butter, season with salt and pepper. toss and serve.'),
('17024', '1', 'In a large bowl, stir together the molasses, olive oil, port, mustard, soy sauce, pepper, Worcestershire sauce and shallot.'),
('17024', '2', 'Let stand at room temperature for 30 minutes.'),
('17024', '3', 'Add the chicken quarters and turn to coat. Refrigerate overnight.'),
('17024', '4', 'Light a grill or preheat the broiler.'),
('17024', '5', 'Remove the chicken from the marinade and arrange the pieces on large rimmed baking sheets.'),
('17024', '6', 'Brush the chicken quarters with the Sweet Mustard Barbecue Sauce and grill over a medium-hot fire or broil 12 inches from the heat, turning often and rotating to cook evenly, until cooked through and nicely glazed, 8 to 10 minutes per side.'),
('17024', '7', 'Serve hot or at room temperature.'),
('17025', '1', 'In a bowl, combine the vinegar, sugar and 1/4 teaspoon of salt.'),
('17025', '2', 'Add the celery leaves. toss to coat.'),
('17025', '3', 'Let stand for 10 minutes.'),
('17025', '4', 'In a bowl, mix the mustard, mayonnaise and miso.'),
('17025', '5', 'Add the cabbages and celery ribs and toss to coat. season with salt.'),
('17025', '6', 'Transfer the slaw to a serving bowl. Top with the celery leaves and serve.'),
('17028', '1', 'Preheat the oven to 35'),
('17028', '2', 'In a large ovenproof nonstick skillet, heat 1 tablespoon of the oil.'),
('17028', '3', 'Add the onion and cook over moderately high heat until golden brown, 10 minutes.'),
('17028', '4', 'Add the greens and cook until wilted.'),
('17028', '5', 'Season the eggs with salt and pepper and whisk in the remaining 2 tablespoons of oil.'),
('17028', '6', 'Pour the eggs into the skillet and cook over moderate heat until the bottom and sides begin to set. Lift the sides of the frittata to allow the uncooked eggs to seep under. Continue cooking until the bottom is set and the top is still runny, 3 minutes. Sprinkle the Parmigiano-Reggiano on top.'),
('17028', '7', 'Transfer the skillet to the oven and bake for about 8 minutes, until the center of the frittata is set. Slide the frittata onto a cutting board.'),
('17028', '8', 'Cut into 1 1/2-inch squares and serve hot, warm or at room temperature.'),
('17037', '1', 'Preheat the oven to 40'),
('17037', '2', 'Set each pork chop on a square of foil large enough to wrap it in. Season the pork chops with salt and pepper, then spread 1 side of each with 1/2 tablespoon of the mustard and sprinkle with a pinch of thyme. Cover each chop with a slice of Canadian bacon and top with 1/2 teaspoon of mustard and a thyme sprig.'),
('17037', '3', 'Wrap the pork chops in the foil, crimping the foil to seal tightly. Set the parcels on a baking sheet.'),
('17037', '4', 'Bake for 20 minutes. the pork will still be slightly pink in the center.'),
('17037', '5', 'Remove the baking sheet from the oven and let the pork chops stand for 5 minutes. Discard the foil and serve the pork chops with their juices.'),
('17040', '1', 'Cook tortellini according to package directions. Rinse under cold running water.'),
('17040', '2', 'Place sugar snap peas in a small bowl. cover with plastic wrap. Microwave at HIGH 2 minutes.'),
('17040', '3', 'Let stand, covered, 2 minutes. Rinse under cold running water.'),
('17040', '4', 'Thread each skewer with 1 sugar snap pea, 1 tortellini, and 1 tomato half.'),
('17040', '5', 'Place skewers in a 13- x 9-inch baking dish.'),
('17040', '6', 'Pour Mustard-Dill Vinaigrette over skewers, turning to coat. Cover and chill 4 hours.'),
('17040', '7', 'Transfer skewers to a serving platter. discard any remaining vinaigrette.'),
('17040', '8', '*1 (12-oz.) bottle light Champagne vinaigrette may be substituted. For testing purposes only, we used Girard''s Light Champagne Dressing.'),
('17041', '1', 'Stir together 3/4 cup light mayonnaise, 1/4 cup coarse grained Dijon mustard, and 2 Tbsp. honey. Cover and chill 20 minutes or up to 3 days.'),
('17042', '1', 'Preheat the oven to 45'),
('17042', '2', 'In a large roasting pan, melt the butter in 1 tablespoon of the oil in the oven. swirl to combine.'),
('17042', '3', 'Add the cauliflower, stems up, and season with salt and pepper. Cover with foil and bake on the bottom shelf of the oven for 30 minutes. Increase the oven temperature to 500 and bake for 10 minutes.'),
('17042', '4', 'Remove the foil and continue to bake for 10 minutes longer, or until the cauliflower starts to caramelize on the bottom.'),
('17042', '5', 'Meanwhile, in a large skillet, heat the remaining 3 tablespoons of oil.'),
('17042', '6', 'Add the onions, cover and cook over low heat, stirring occasionally, until very tender, about 20 minutes. Stir in the curry powder and mustard seeds and cook, stirring, until fragrant, about 5 minutes.'),
('17042', '7', 'Add the lemon juice and season the onions with salt and pepper.'),
('17042', '8', 'Transfer the roasted cauliflower to a large serving bowl and spoon the onions on top. Sprinkle with the chopped cilantro and serve at once.'),
('17043', '1', 'Preheat the oven to 350 degrees.'),
('17043', '2', 'Spread the crushed potato chips in a shallow dish. Beat together the egg and milk in a shallow bowl. Dip the chicken cubes into the egg mixture and then dredge them in the chips.'),
('17043', '3', 'Place the chicken nuggets on a baking sheet and drizzle with melted butter.'),
('17043', '4', 'Bake for 15 to 18 minutes, or until golden brown. The chicken nuggets can be frozen after baking.'),
('17043', '5', 'Serve with your favorite sauce, such as Honey Mustard or ranch dressing.'),
('17043', '6', 'Combine all ingredients except orange juice. stir well. Thin to pouring consistency for dressing or dipping consistency for dips with orange juice. Cover and chill for 2 or 3 hours.'),
('17046', '1', 'In a small saucepan, boil the passion fruit juice with the red chile until reduced to 1/4 cup, about 20 minutes.'),
('17046', '2', 'Meanwhile, in another saucepan, toast the cumin seeds over moderate heat until fragrant.'),
('17046', '3', 'Add the honey and green chile and bring to a simmer.'),
('17046', '4', 'Remove from the heat and let stand for 15 minutes. Strain the honey and stir in 1 teaspoon of the water.'),
('17046', '5', 'In a bowl, blend the dry mustard with the remaining 2 teaspoons of water. let stand for 5 minutes. Stir in the Dijon mustard. Strain the reduced passion fruit juice into the mustard and season with salt.'),
('17046', '6', 'Light a grill. Wrap each shrimp in a slice of bacon. Grill the shrimp over moderately high heat, turning a few times, until the bacon is lightly charred and the shrimp are cooked throughout, about 4 minutes.'),
('17046', '7', 'Fan the avocado slices on each plate and top with the shrimp. Spoon the mustard around the shrimp, then spoon the honey around the mustard.'),
('17046', '8', 'Drizzle the shrimp with olive oil, garnish with the passion fruit seeds and cilantro and serve.'),
('17049', '1', 'Preheat oven to 350F.'),
('17049', '2', 'In skillet, brown bacon, ground beef and chopped onion.'),
('17049', '3', 'Meanwhile mix together both sugars, ketchup, barbecue sauce, molasses, chili powder, salt, pepper, and mustard. set aside.'),
('17049', '4', 'Drain off excess fat and mix with beans and sauce.'),
('17049', '5', 'Bake uncovered at 350F for 1 hour and 15 minutes.'),
('17054', '1', 'Freeze ItQuarter the potatoes. Peel the carrots.'),
('17054', '2', 'Cut the carrots and zucchini into 2-inch sticks.'),
('17054', '3', 'Mix them in a bowl with 2 tablespoons olive oil, 2 tablespoons mustard, 1 tablespoon rosemary, 1/2 teaspoon salt, and 1/4 teaspoon pepper. Season the chicken with 1 teaspoon salt and 1/4 teaspoon pepper. Divide everything among 4 bags. Freeze, until ready to cook, for up to 3 months. Cook It'),
('17054', '4', 'Heat oven to 400 F.'),
('17054', '5', 'Remove the bags from the freezer (you''ll need 1 bag for each serving). Empty the contents of the bags into a baking dish. Roast for 25 minutes. Toss the vegetables, turn the chicken, and continue roasting until the chicken is cooked through, 20 to 25 minutes more. Divide among individual plates.'),
('17057', '1', 'Mix together the flour, cumin, salt, and pepper on a large plate. Lightly coat each piece of pork with the flour mixture. set aside.'),
('17057', '2', 'Heat the vegetable oil and butter in a large skillet over medium-high heat. Sprinkle the apple halves with a pinch of salt and pepper. Cook the apples cut-side down about 5 minutes or until golden brown.'),
('17057', '3', 'Remove from the skillet, cover, and set aside.'),
('17057', '4', 'Place the pork in the skillet, sprinkle with the parsley, and cook until the meat is golden brown and crispy, 4 to 5 minutes per side. While the pork is cooking, whisk together the broth and vinegar.'),
('17057', '5', 'Remove the pork from the skillet and set aside.'),
('17057', '6', 'Pour the broth mixture into the skillet, stirring and scraping up any browned bits. Bring to a boil and cook until slightly thickened. Divide the pork among 4 plates and pour some pan sauce over each. Before serving, place an apple half and a dab of mustard on each plate.'),
('17061', '1', 'Combine first 9 ingredients.'),
('17061', '2', 'Place half of mixture in a zip-top plastic bag. reserve remaining mixture.'),
('17061', '3', 'Add chicken to bag. seal. Chill 2 hours.'),
('17061', '4', 'Preheat grill to medium-high heat.'),
('17061', '5', 'Remove chicken from bag. Sprinkle chicken with salt.'),
('17061', '6', 'Place chicken on a grill rack coated with cooking spray. grill 8 minutes on each side or until done.'),
('17061', '7', 'Serve with reserved mustard mixture.'),
('17062', '1', 'Combine first 3 ingredients in a large bowl, stirring with a whisk.'),
('17062', '2', 'Add oil, stirring with a whisk until well combined.'),
('17062', '3', 'Cook edamame in boiling water 4 minutes.'),
('17062', '4', 'Add onion and celery. cook 1 minute.'),
('17062', '5', 'Drain well.'),
('17062', '6', 'Add edamame mixture to vinaigrette. toss well to coat. Stir in parsley. Chill 1 hour.'),
('17063', '1', 'Combine first 5 ingredients in a small bowl.'),
('17063', '2', 'Combine ketchup and next 3 ingredients (through mustard) in a small bowl. stir with a whisk.'),
('17063', '3', 'Heat a large grill pan over medium-high heat. Rub spice mixture evenly over chicken thighs. Coat pan with cooking spray.'),
('17063', '4', 'Add chicken to pan. cook 12 minutes. Turn chicken over.'),
('17063', '5', 'Brush with half of ketchup mixture. cook 12 minutes. Turn chicken over.'),
('17063', '6', 'Brush with remaining ketchup mixture. cook 2 minutes or until a thermometer registers 16'),
('17065', '1', 'Prepare grill.'),
('17065', '2', 'Lightly coat beef with cooking spray. sprinkle evenly with salt and pepper.'),
('17065', '3', 'Place beef on grill rack coated with cooking spray. Reduce heat to medium. Grill 30 minutes or until a thermometer registers 145 or until desired degree of doneness, turning to brown on all sides.'),
('17065', '4', 'Let beef stand 10 minutes.'),
('17065', '5', 'Sprinkle parsley, thyme, and rosemary in an even layer on an 18 x 15inch sheet of plastic wrap.'),
('17065', '6', 'Brush mustard evenly over beef.'),
('17065', '7', 'Place beef in herb mixture on plastic wrap. roll beef over herbs, pressing gently. Slice beef.'),
('17069', '1', 'Heat 2 tbsp. oil and mustard seeds in a large nonstick frying pan over medium-high heat, covered, just until seeds start to pop. Stir in cumin seeds and turmeric. then stir in potatoes, 1 tsp. salt, and pepper.'),
('17069', '2', 'Reduce heat to medium low and add 1 tbsp. water. Cook, covered, until potatoes are tender, 20 to 25 minutes.'),
('17069', '3', 'Add remaining 2 tbsp. oil, coriander, cumin, cayenne, and salt to taste. Cook, uncovered, turning occasionally, until potatoes are golden, 8 to 10 minutes. Stir in cilantro.'),
('17072', '1', 'Stir together all ingredients until blended.'),
('17073', '1', 'Stir together 1/2 cup orange marmalade and 2 Tbsp. stone-ground mustard.'),
('17073', '2', 'Brush 1 (3- to 3 1/2-lb.) corned beef brisket, fully cooked, with half of marmalade mixture, and place in a lightly greased jelly-roll pan.'),
('17073', '3', 'Bake at 425 for 30 to 35 minutes or until golden brown, basting with remaining half of marmalade mixture every 10 minutes.'),
('17073', '4', 'Serve corned beef with cooked cabbage.'),
('17082', '1', 'In a large bowl, whisk together the baking mix, cornmeal, garlic powder, and cayenne. In another bowl, whisk together the egg and milk.'),
('17082', '2', 'Pour the wet ingredients into the dry ingredients and whisk until blended.'),
('17082', '3', 'In a small bowl, stir together the mustard and preserves.'),
('17082', '4', 'When you are ready to fry, insert a chopstick into the end of each hot dog and push about halfway into the meat. (Reserve 2 hot dogs for the Online Round 2 Recipe Cheesy Hot Dog Scramble.) Dust each hotdog with flour, dip into the batter, and carefully lower it into the hot oil. Fry 2 or 3 at a time until golden brown, 3 to 5 minutes.'),
('17082', '5', 'Drain on brown paper.'),
('17082', '6', 'Brush with the sweet mustard sauce and serve warm.'),
('17084', '1', 'In a small jar with a tight-fitting lid, combine all the ingredients. Cover and shake vigorously. Leave the garlic in the dressing until ready to use, then remove and discard it.'),
('17085', '1', 'Soak wood chips in water 30 minutes. drain.'),
('17085', '2', 'Combine dill, juice, mustard, and salt, stirring well.'),
('17085', '3', 'Place salmon, skin side down, in a shallow baking dish. brush mustard mixture over salmon. Cover and refrigerate 20 minutes.'),
('17085', '4', 'Prepare the grill for indirect grilling, heating one side to low and leaving one side with no heat. Maintain temperature at 200 to 22'),
('17085', '5', 'Place wood chips on hot coals.'),
('17085', '6', 'Place a disposable aluminum foil pan on unheated side of grill.'),
('17085', '7', 'Pour 2 cups water in pan. Coat grill rack with cooking spray. place on grill.'),
('17085', '8', 'Place salmon, skin side down, on grill rack over foil pan on unheated side. Close lid. cook 35 minutes or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('17095', '1', 'Heat oil in a large frying pan over medium-high heat. Season chops on both sides with salt and pepper.'),
('17095', '2', 'Add chops to pan and cook until barely pink in center, turning once, 10 to 12 minutes.'),
('17095', '3', 'Transfer pork to a serving plate and tent with foil.'),
('17095', '4', 'Add broth to pan and bring to a boil over high heat. Stir in mustard, capers, and rosemary. Simmer until reduced by half, about 4 minutes. Spoon sauce over chops.'),
('17096', '1', 'Mix together the oil, vinegar, mustard, salt, and pepper in a large, shallow dish. If desired, wrap a rosemary sprig around edge of steak and tie ends securely with kitchen string. Repeat with other steaks.'),
('17096', '2', 'Place steaks in marinade and turn to coat. Cover with plastic wrap and refrigerate 30 minutes or overnight.'),
('17096', '3', 'Lightly coat clean grids of grill with cooking oil spray.'),
('17096', '4', 'Heat the grill to medium-high heat. Lightly brush onion and tomato halves with oil.'),
('17096', '5', 'Place onions on grill, cut side down, and grill 10 minutes with the lid down. Turn and cook 5 minutes more. transfer to a plate and keep warm.'),
('17096', '6', 'Place steaks on grill and cook, without turning, 4 minutes with the lid down. Turn steaks and place tomatoes, cut side down, on grill. Cook steak and tomatoes, with lid down, 4 minutes.'),
('17096', '7', 'Transfer steak to plates along with the onions and tomatoes.'),
('17097', '1', 'To prepare chicken, combine buttermilk and chicken. Marinate in refrigerator 30 minutes. drain.'),
('17097', '2', 'Preheat oven to 37'),
('17097', '3', 'Place cornflakes, paprika, sugar, and salt in a food processor. process until cornflakes are finely chopped.'),
('17097', '4', 'Combine chicken and cornflake mixture, tossing well to coat.'),
('17097', '5', 'Place the chicken on a baking sheet coated with cooking spray.'),
('17097', '6', 'Bake at 375 for 15 minutes or until done.'),
('17097', '7', 'To prepare sauce, combine mustard, honey, and ginger.'),
('17097', '8', 'Serve with chicken.'),
('17098', '1', 'Preheat oven to 40'),
('17098', '2', 'Heat a large ovenproof skillet over medium-high heat.'),
('17098', '3', 'Add oil. swirl to coat. Sprinkle chicken with pepper and salt.'),
('17098', '4', 'Add chicken to pan. saut 2 minutes on each side or until browned.'),
('17098', '5', 'Remove chicken from pan.'),
('17098', '6', 'Add broth, syrup, thyme, and garlic to pan. bring to a boil, scraping pan to loosen browned bits. Cook 2 minutes, stirring frequently.'),
('17098', '7', 'Add vinegar and mustard. cook for 1 minute, stirring constantly. Return chicken to pan, and spoon mustard mixture over chicken.'),
('17098', '8', 'Bake at 400 for 10 minutes or until the chicken is done.'),
('17098', '9', 'Remove chicken from pan. let stand 5 minutes.'),
('17098', '10', 'Place pan over medium heat. cook mustard mixture 2 minutes or until liquid is syrupy, stirring frequently.'),
('17098', '11', 'Serve with chicken.'),
('17100', '1', 'Preheat oven to 25'),
('17100', '2', 'Put unpeeled eggs in a bowl of warm water.'),
('17100', '3', 'Pour 1/4 cup oil into an 8- by 8-in. pan, add kohlrabi, and turn to coat. Cover tightly with foil.'),
('17100', '4', 'Remove eggs from water and set directly on an oven rack. Set pan of kohlrabi on another rack. Roast eggs and kohlrabi 2 hours (eggs will be freckled with brown syrupy spots).'),
('17100', '5', 'Remove eggs, crack all over under cold running water, and put in a bowl of cold water to cool.'),
('17100', '6', 'Turn kohlrabi over in pan and cover tightly. Increase oven temperature to 375 and roast kohlrabi until butter-soft when pierced with a knife, about 1 hour.'),
('17100', '7', 'Remove foil, turn kohlrabi over, and roast until crisply browned, about 30 minutes more.'),
('17100', '8', 'Meanwhile, in a small saucepan, heat mustard seeds over medium-high heat until just starting to pop, 2 to 3 minutes.'),
('17100', '9', 'Add 1/2 cup water, the bay leaves, vinegar, and honey. Bring to a boil, then lower heat and simmer, covered, until mustard seeds are tender, 15 to 20 minutes. Uncover and boil sauce until reduced to 1/2 cup, 2 to 5 minutes.'),
('17100', '10', 'Remove from heat and whisk in mustard. Season with salt to taste.'),
('17100', '11', 'Peel eggs. Chop and mix with sorrel in a medium bowl.'),
('17100', '12', 'While kohlrabi bulbs are still warm, tear some partway apart and some in half.'),
('17100', '13', 'Spoon egg-and-sorrel mixture among 4 plates or on a big platter. Arrange kohlrabi over the mixture, drizzle with honey-and-mustard sauce, and add a few small chunks of honeycomb. Top with small sorrel leaves.'),
('17100', '14', '*Jeremy Fox uses red sorrel, wood sorrel, and sheep sorrel from Ubuntu''s garden, but any kind of sorrel will work. Find honeycomb at well-stocked grocery stores and farmers'' markets.'),
('17100', '15', 'Quick twist: Replace the kohlrabi with small unpeeled Yukon Gold potatoes. Roast and serve them exactly the same way.'),
('17101', '1', 'Heat a large nonstick skillet coated with cooking spray over medium-high heat. Sprinkle steaks with 1/4 teaspoon salt and pepper.'),
('17101', '2', 'Add steaks to pan. cook 3 minutes on each side or until desired degree of doneness.'),
('17101', '3', 'Remove from pan. keep warm.'),
('17101', '4', 'Add dry white wine, sugar, and Dijon mustard to pan. bring to a boil. Cook 1 minute, stirring constantly.'),
('17101', '5', 'Remove from heat. Stir in 1/4 teaspoon salt, sour cream, and chopped tarragon. Spoon sauce over warm steaks.'),
('17101', '6', 'Garnish with tarragon sprigs, if desired.'),
('17104', '1', 'In a saucepan fitted with a steamer basket, bring 1 inch of water to a boil.'),
('17104', '2', 'Add the leeks, cover and steam until just tender, about 5 minutes.'),
('17104', '3', 'Drain the leeks, pat dry and refrigerate until chilled, 10 minutes.'),
('17104', '4', 'Meanwhile, in a small bowl, combine the shallot with the mustard and the red wine and balsamic vinegars.'),
('17104', '5', 'Whisk in the olive oil and season with salt and black pepper.'),
('17104', '6', 'Mound the steamed leeks on plates.'),
('17104', '7', 'Drizzle them with the vinaigrette, sprinkle with the parsley and serve.'),
('17105', '1', 'Drop the onions into lightly salted boiling water for 1 minute. drain.'),
('17105', '2', 'Place the onions in a bowl with the pepper, cumin, garlic, salt, vinegar, and orange zest. add just enough water to cover. Refrigerate until the onions are bright pink, about 3 hours.'),
('17105', '3', 'Drain before serving.'),
('17105', '4', 'Note: The sausages can be grilled or broiled earlier on the day of the party. Slice them into bite-size pieces (which makes knives unnecessary) and reheat them in foil in the oven before serving with the onions and an assortment of gutsy, grainy mustards.'),
('17106', '1', 'Heat oven according to the directions on the ham package.'),
('17106', '2', 'Place the ham on a rack in a roasting pan and pour the ginger ale over the top. Cover the pan with foil and bake according to the package directions. Meanwhile, in a small bowl, combine the brown sugar and mustard. About 20 minutes before the ham is finished, remove the foil and spoon the mustard mixture over the ham. Continue to bake, uncovered. Meanwhile, place the potatoes in a large pot with enough water to cover them.'),
('17106', '3', 'Add 2 teaspoons of the salt and bring to a boil. Simmer until tender, about 15 minutes.'),
('17106', '4', 'Drain, then return the potatoes to pot.'),
('17106', '5', 'Add the butter, sour cream, Cheddar, pepper, and the remaining salt to the potatoes and roughly mash. Cover to keep warm until the ham is done. Slice the ham, spoon the pan juices over it, and serve with the potatoes. Sprinkle with the parsley, if desired.Tip: Use a slightly larger ham (2 to 3 pounds) and enjoy plenty of leftovers.'),
('17107', '1', 'Season the pork chops with salt and pepper.  On one side of each chop sprinkle a little sugar.'),
('17107', '2', 'Pour 1 tablespoon of canola oil into a skillet.'),
('17107', '3', 'Place the chops sugar side down and then turn the heat to medium.  Cook for 5 minutes.  Flip the chops, turn the heat to low, and cover.  Cook until they register 140F, about 4-6 minutes.'),
('17107', '4', 'Combine the chicken stock, sour cream, Dijon mustard, stone-ground mustard, and cornstarch in a blender.  Process until smooth.'),
('17107', '5', 'Transfer the sauce to a small saucepan over low heat.'),
('17107', '6', 'Whisk the sauce until combined and thickened, about 3 minutes.'),
('17107', '7', 'Serve the chops with the sauce on top and a sprinkling of parsley.'),
('17109', '1', 'Watch how to make this recipe.'),
('17109', '2', 'Add potatoes, cream, milk, garlic, thyme and bay leaf into a large saucepan and gently boil for 15 minutes until potatoes are just tender and the tip of a paring knife goes through with little resistance. Strain potatoes and reserve the cream mixture but discard the bay leaf, thyme stems and the garlic. Mash the potatoes and fold in the cream mixture until the potatoes are smooth and creamy. Fold in about a tablespoon of the olive oil, the butter, and the grainy mustard. Season with salt and pepper.'),
('17110', '1', 'Whisk together all the ingredients in a large skillet or saucepan over medium heat. Bring to a gentle simmer. Cook until the sauce has thickened slightly, about 3 minutes.'),
('17110', '2', 'Pour or spoon the sauce over cooked meat.Good for: Chicken or pork'),
('17116', '1', 'Heat a large nonstick skillet over medium-high heat. Press pork pieces into 1/2-inch-thick medallions.'),
('17116', '2', 'Combine salt, pepper, and fennel. rub evenly over pork. Lightly coat pork with cooking spray.'),
('17116', '3', 'Add pork to pan. cook 4 minutes on each side or until done.'),
('17116', '4', 'While pork cooks, combine olives and remaining ingredients.'),
('17116', '5', 'Serve olive mixture over pork.'),
('17117', '1', 'Combine the first 6 ingredients in a large bowl.'),
('17117', '2', 'Add tomato slices, tossing gently to coat.'),
('17117', '3', 'Let stand 15 minutes.'),
('17134', '1', 'Heat a grill pan over medium-high heat. Sprinkle chicken evenly with 1/4 teaspoon salt and 1/8 teaspoon pepper. Coat pan with cooking spray.'),
('17134', '2', 'Place chicken in pan. cook 6 minutes on each side or until done.'),
('17134', '3', 'Combine remaining 1/4 teaspoon salt, remaining 1/8 teaspoon pepper, shallots, and next 6 ingredients (through sugar) in a bowl, stirring well with a whisk.'),
('17134', '4', 'Serve chicken over greens with sauce.'),
('17136', '1', 'Preheat the oven to 350 degrees F. Take the pork out of the refrigerator 45 minutes before you are ready to roast to allow the pork to come to temperature.'),
('17136', '2', 'Place the pork into a roasting pan fitted with a rack or onto a baking sheet, fat side up, and season with salt and pepper. Put in the oven and roast for 1 hour. Meanwhile, make the glaze.'),
('17136', '3', 'In a saucepan over medium-high heat, bring the apple juice to a boil and reduce it by half, about 10 minutes.'),
('17136', '4', 'Whisk in the brown sugar, soy sauce, Worcestershire sauce, and mustard and simmer until thickened, another 5 to 7 minutes.'),
('17136', '5', 'After the pork has roasted for 1 hour, start brushing it with the glaze every 15 minutes. Cook until the roast reaches an internal temperature of 150 degrees F, about 2 hours total cook time.'),
('17136', '6', 'Remove from the oven, give it another coating of glaze, and let it rest, uncovered, for 15 minutes before carving. (Reserve 1 cup of the meat for the Round 2 Recipe Pork Hash).'),
('17140', '1', 'Combine the first 6 ingredients in a small bowl. Score outside of ham in a diamond pattern. rub with spice mixture. Cover and chill overnight.'),
('17140', '2', 'Remove the ham from refrigerator. let stand at room temperature 1 hour.'),
('17140', '3', 'Preheat oven to 42'),
('17140', '4', 'Arrange ham, fat side up, on rack of a roasting pan coated with cooking spray, and place rack in pan.'),
('17140', '5', 'Bake at 425 for 30 minutes. Reduce temperature to 350 (do not remove ham from oven). bake at 350 for 1 1/2 hours.'),
('17140', '6', 'Combine maple syrup, Dijon mustard, and butter. Turn ham, fat side down.'),
('17140', '7', 'Bake an additional 40 minutes, basting with syrup mixture every 20 minutes. Turn ham again. Baste with the remaining syrup mixture, and bake an additional 35 minutes or until a thermometer inserted close to bone registers 14'),
('17140', '8', 'Let stand for 20 minutes. remove excess fat, and slice.'),
('17143', '1', 'Heat a large nonstick skillet over medium heat. Sprinkle both sides of steaks evenly with salt and pepper.'),
('17143', '2', 'Add steaks to pan. cook 3 minutes on each side or until browned.'),
('17143', '3', 'Remove steaks from pan. keep warm.'),
('17143', '4', 'Melt butter in pan.'),
('17143', '5', 'Add shallots to pan. cook 2 minutes, stirring occasionally.'),
('17143', '6', 'Add broth and mustard to pan. cook 1 minute or until sauce thickens, stirring occasionally. Stir in brandy. Return steaks to pan, and cook 1 minute on each side or until desired degree of doneness.'),
('17143', '7', 'Serve sauce with steaks.'),
('17145', '1', 'Cook beans 5 minutes or until crisp-tender in boiling water with 1 3/8 teaspoons salt.'),
('17145', '2', 'Drain and plunge beans into ice water.'),
('17145', '3', 'Drain and pat dry.'),
('17145', '4', 'Combine remaining 1/8 teaspoon salt, chives, and next 4 ingredients (through pepper) in a large bowl, stirring well with a whisk.'),
('17145', '5', 'Add beans to mustard mixture. toss. Divide beans evenly among 4 plates. top each serving with 1 1/2 teaspoons almonds.'),
('17151', '1', 'In a small bowl, combine the chili powder, cumin, mustard, cinnamon, oregano, and salt.'),
('17151', '2', 'Add enough olive oil to make a paste and rub over raw meat, under and over chicken skin, or on seafood.'),
('17154', '1', 'Preheat the oven to 40'),
('17154', '2', 'In a food processor, pulse the pretzels until coarsely ground. you should have coarse chunks and fine crumbs.'),
('17154', '3', 'Transfer to a large, shallow bowl.'),
('17154', '4', 'Wipe out the food processor.'),
('17154', '5', 'Add the oil, whole-grain and Dijon mustards, water and vinegar and process until smooth. Season the dressing with salt and pepper.'),
('17154', '6', 'Pour half of the dressing into a large shallow bowl, add the chicken breasts and turn to coat. Dredge the chicken in the pretzel crumbs and transfer to a rack set over a rimmed baking sheet.'),
('17154', '7', 'Bake in the upper third of the oven for 20 to 25 minutes, or until cooked through. Slice the chicken and serve warm or at room temperature with the remaining mustard dressing.'),
('17155', '1', 'Preheat the broiler.'),
('17155', '2', 'Brush the bread with olive oil and transfer to a baking sheet. Broil the bread a few inches from the heat, turning once, for 2 minutes, until golden and toasted. Lightly rub the whole garlic clove over the toasts.'),
('17155', '3', 'In a large, deep pot, heat the 1/4 cup of olive oil.'),
('17155', '4', 'Add the kielbasa, shallot and sliced garlic, season lightly with salt and pepper and cook over high heat, stirring, until the garlic is softened and lightly browned, about 3 minutes.'),
('17155', '5', 'Add the mussels and cook, stirring, for 1 minute.'),
('17155', '6', 'Add the lager, cover and steam the mussels until they open, about 5 minutes.'),
('17155', '7', 'Remove from the heat. Using a slotted spoon, transfer the mussels to 4 deep bowls, discarding any mussels that do not open.'),
('17155', '8', 'Add the butter, mustard and dill to the broth, swirling and shaking the pot until the butter melts. Slowly pour the broth over the mussels, stopping before you reach the grit at the bottom of the pot.'),
('17155', '9', 'Serve the mussels with the garlic toasts.'),
('17157', '1', 'In a blender, process the chicken stock, sour cream, Dijon and stone-ground mustards and the cornstarch until smooth.'),
('17157', '2', 'Transfer the sauce to a small saucepan and simmer over moderate heat until thickened, about 3 minutes. Stir in the parsley and keep warm.'),
('17157', '3', 'Heat a large skillet. Season the pork chops with salt and pepper and cook over moderately high heat until well browned, about 5 minutes. Turn the pork chops and cook until browned and just cooked through, about 3 minutes longer.'),
('17157', '4', 'Transfer the chops to warm dinner plates, spoon the mustard sauce on top and serve at once.'),
('17158', '1', 'Preheat the oven to 20'),
('17158', '2', 'Rub the steaks with olive oil and sprinkle them with the hot paprika, rubbing to coat. Season the steaks with salt and transfer them to a small roasting pan. Roast for about 1 1/2 hours, until an instant-read thermometer inserted in the thickest part of the steaks registers 125 for medium-rare.'),
('17158', '3', 'Meanwhile, in a mini food processor, puree the miso with the soy sauce, lime juice and zest, mustard powder, orange juice, kecap manis and sweet paprika.'),
('17158', '4', 'In a medium saucepan, melt the butter.'),
('17158', '5', 'Add the miso mixture and whisk over moderate heat until smooth and creamy, about 1 minute. Keep warm over low heat.'),
('17158', '6', 'In a skillet, heat 1 tablespoon of olive oil.'),
('17158', '7', 'Add the steaks and cook over high heat, turning once, until browned, 4 minutes total.'),
('17158', '8', 'Transfer the steaks to plates and serve with the citrus-mustard butter.'),
('17159', '1', 'In a small skillet, toast the fennel seeds over moderately high heat until fragrant.'),
('17159', '2', 'Transfer the seeds to a spice grinder and let cool completely. grind to a powder.'),
('17159', '3', 'In a large bowl, whisk the ground fennel with the vinegar, lemon juice, mustard and garlic.'),
('17159', '4', 'Whisk in the oil. season with salt and pepper.'),
('17159', '5', 'Add the mche and toss gently. Scatter the goat cheese on top and serve.'),
('17168', '1', 'Stir together honey and mustard. set aside all but 1/4 cup. Gently loosen chicken skin around breast. Rub 1/4 cup honey mustard mixture evenly under and over skin, pushing it into legs and thighs. Sprinkle chicken inside and out with salt and pepper. Fold wings under and tie legs together.'),
('17168', '2', 'Place chicken, breast side up, on a small rack or a ring made from foil inside slow cooker.'),
('17168', '3', 'Add 1/4 inch water. Cover. cook on high until an instant-read thermometer inserted into thigh registers 180F, 3 1/2 to 4 hours.'),
('17168', '4', 'Preheat broiler to high.'),
('17168', '5', 'Transfer chicken, breast side up, to a foil-lined baking sheet.'),
('17168', '6', 'Combine 1 Tbsp. reserved honey mustard with olive oil.'),
('17168', '7', 'Brush mixture over chicken and broil to brown skin, 2 to 3 minutes.'),
('17168', '8', 'Let rest 10 minutes on a cutting board before serving.'),
('17168', '9', 'Drizzle remaining honey mustard over each portion of sliced meat.'),
('17169', '1', 'Combine half of 1 (16-ounce) package cabbage-and-carrot coleslaw, 1 tablespoon brown sugar, 2 tablespoons cider vinegar, 1 tablespoon stone-ground mustard, and 1/8 teaspoon salt.'),
('17170', '1', 'Preheat oven to 35'),
('17170', '2', 'Trim fat and rind from ham. Score outside of ham in a diamond pattern.'),
('17170', '3', 'Place ham on a broiler pan coated with cooking spray.'),
('17170', '4', 'Combine juice, preserves, and mustard in a medium bowl, stirring until well combined. Set aside half of preserves mixture.'),
('17170', '5', 'Bake ham at 350 for 1 1/2 hours or until a thermometer registers 140, basting with half of preserves mixture every 20 minutes.'),
('17170', '6', 'Remove ham from oven.'),
('17170', '7', 'Place ham on a platter. cover and let stand 15 minutes before slicing.'),
('17170', '8', 'Place reserved preserves mixture in a large nonstick skillet over medium-low heat. Cook until reduced to 1 cup (about 15 minutes).'),
('17170', '9', 'Serve sauce with ham.'),
('17170', '10', 'Wine note: Smoked ham is a wine challenge--the dominance of the smoke usually ends up making wine taste like water. But one part of the world has a lot of experience pairing ham and pork with wine, and that''s the Alsace region of France. With a ham dish as complex as this one, opt for one of the most dramatic wines from Alsace: a dry muscat. Domaine Weinbach''s Muscat Rserve 2003 ($3'),
('17170', '11', 'is one of the best and dramatic enough to match this ham. Its exuberant fruity flavors must be experienced to be believed. -KM'),
('17177', '1', 'Combine sour cream, 2 tablespoons parsley, mustard, and 1/8 teaspoon pepper, stirring with a whisk until blended. Set aside.'),
('17177', '2', 'Heat a large nonstick skillet over medium heat.'),
('17177', '3', 'Add 1 teaspoon canola oil to pan, and swirl to coat.'),
('17177', '4', 'Add onion and celery. cook 5 minutes or until tender, stirring occasionally.'),
('17177', '5', 'Remove from heat. cool slightly.'),
('17177', '6', 'Combine shrimp and crab in a large bowl. Stir in onion mixture, remaining pepper, remaining 1/4 cup parsley, cheese, salt, egg whites, and egg. stir gently.'),
('17177', '7', 'Add panko. stir gently. Divide mixture into 8 equal portions. flatten to 1/2-inch-thick patties.'),
('17177', '8', 'Heat skillet over medium-high heat.'),
('17177', '9', 'Add remaining 2 tablespoons oil to pan. swirl to coat.'),
('17177', '10', 'Add patties to pan. cook 3 minutes or until lightly browned. Carefully turn over. cook 3 minutes or until done.'),
('17177', '11', 'Serve with sauce.'),
('17188', '1', 'Preheat the oven to 45'),
('17188', '2', 'Melt the 3 tablespoons of butter in a large ovenproof skillet. Season the lamb loins with salt and pepper and dredge in the flour.'),
('17188', '3', 'Add to the skillet and cook over moderately high heat, turning, until browned all over, about 6 minutes.'),
('17188', '4', 'Let the lamb cool slightly, then pat dry and brush with the mustard.'),
('17188', '5', 'On a plate, mix the bread crumbs with the parsley, garlic, shallot, oregano, basil, Parmesan and the melted butter.'),
('17188', '6', 'Roll the lamb in the crumb mixture, pressing it into the meat.'),
('17188', '7', 'Return the lamb to the skillet and roast for about 15 minutes for medium-rare meat.'),
('17188', '8', 'Transfer to a work surface, cover loosely with foil and let stand for 5 minutes. Slice the lamb loins 1/3 inch thick and serve.'),
('17192', '1', 'In a shallow dish, combine the wine with 1 teaspoon of the olive oil and 1/2 teaspoon each of the grainy mustard and rosemary.'),
('17192', '2', 'Add the duck breasts and turn to coat. Cover and refrigerate for 30 minutes.'),
('17192', '3', 'Meanwhile, bring a medium saucepan of water to a boil.'),
('17192', '4', 'Add the kumquat slices and simmer over moderately high heat until tender, about 5 minutes.'),
('17192', '5', 'Drain the kumquat slices. In the same saucepan, combine the sugar and water and bring to a boil stirring to dissolve the sugar.'),
('17192', '6', 'Add the kumquat slices and simmer over moderate heat for 8 minutes.'),
('17192', '7', 'Transfer the kumquats along with the sugar syrup to a heatproof bowl.'),
('17192', '8', 'In a large skillet, heat the remaining 1 tablespoon of olive oil.'),
('17192', '9', 'Remove the duck breasts from the marinade. reserve the marinade. Season the duck breasts with salt and pepper and cook over moderately high heat until browned on the bottom, about 3 minutes. Turn the duck breasts, reduce the heat to moderate and cook until browned on the bottom and medium rare, 2 to 3 minutes longer.'),
('17192', '10', 'Transfer the duck breasts to warmed plates.'),
('17192', '11', 'Add the shallots, jalapeo and remaining 1/2 teaspoon of rosemary to the skillet and cook over moderately low heat until softened, about 4 minutes.'),
('17192', '12', 'Add the reserved duck marinade and simmer over moderately high heat until syrupy, about 3 minutes.'),
('17192', '13', 'Add the kumquats and their syrup and bring to a simmer. Blend in the Dijon mustard and remaining 1 teaspoon of grainy mustard and remove from the heat. Season with salt and pepper.'),
('17192', '14', 'Pour the kumquat sauce over the duck breasts and serve.'),
('17194', '1', 'Combine mustard and horseradish. spread evenly over tenderloin. Pat breadcrumbs into mustard mixture. Wrap tenderloin in plastic wrap. refrigerate 1 to 24 hours.'),
('17194', '2', 'Preheat oven to 40'),
('17194', '3', 'Remove and discard plastic wrap from tenderloin.'),
('17194', '4', 'Place tenderloin on a broiler pan coated with cooking spray.'),
('17194', '5', 'Bake at 400 for 25 minutes or until a thermometer registers 145 (medium-rare) or until desired degree of doneness.'),
('17194', '6', 'Place tenderloin on a cutting board. cover and let stand 10 minutes before slicing.'),
('17198', '1', 'Preheat the oven to 350 degrees F. In a bowl, whisk together the ginger conserve, mustard, garlic flavored oil and soy sauce.'),
('17198', '2', 'Turn the sausages in the mustardy mix and then arrange them on either a large, shallow-sided tin or 2 smaller tins. The height of the tin''s sides will determine how quickly the sausages color and cook.'),
('17198', '3', 'If you are using high-sided tins, they will need about 45 minutes in the oven. cooked on a shallower tray, 30 minutes should be fine. And do line with foil or use throwaway foil trays, or washing-up will be a nightmare. To serve the sausages in their bread bowl, cut a circle around the top of the bread to take off a "lid". Put this lid on one side for a moment, and tear and pull out the doughy filling with your hands, leaving the crust intact so that you have a hollow bowl.'),
('17198', '4', 'Fill this emptied-out loaf with as many sausages as you can - you may have to top up with a few as you go - and then you can balance the lid at a jaunty angle for maximum effect and your guests'' amusement.'),
('17198', '5', 'Serve with a small pot of cocktail sticks to spear the'),
('17198', '6', 'sausages, but if you''re skipping the bread bowl option, let the hot sausages cool slightly before handing them out.'),
('17201', '1', 'Spread each slice of bread with mustard. Top 1 slice with the Cheddar and the apple slices. Sandwich with the remaining bread.'),
('17212', '1', 'Combine mustard, 1 tablespoon parsley, 1 1/2 teaspoons thyme, and chicken in a large zip-top plastic bag. toss well to coat. Chill 8 hours or overnight.'),
('17212', '2', 'Remove chicken from bag, and discard marinade. Sprinkle chicken with salt and black pepper.'),
('17212', '3', 'Heat olive oil in a large Dutch oven over medium-high heat.'),
('17212', '4', 'Add chicken to pan, and cook 5 minutes on each side or until browned.'),
('17212', '5', 'Remove from pan.'),
('17212', '6', 'Add chopped onion to pan, and saut 5 minutes or until tender, stirring frequently.'),
('17212', '7', 'Add garlic to pan, and saut 1 minute, stirring constantly. Stir in wine and chicken broth, scraping pan to loosen browned bits. Stir in 1 tablespoon parsley and remaining 1 1/2 teaspoons thyme. Return chicken to pan. Cover, reduce heat, and simmer 25 minutes or until chicken is done.'),
('17212', '8', 'Remove chicken from pan with a slotted spoon. Keep warm.'),
('17212', '9', 'Cook sauce, uncovered, over medium heat 4 minutes or until slightly thick.'),
('17212', '10', 'Pour sauce over chicken, and sprinkle with remaining 2 tablespoons parsley.'),
('17215', '1', 'In a blender or mini-processor, combine the vegetable oil, onion, wine, rosemary, garlic and Dijon mustard and blend until smooth.'),
('17215', '2', 'Transfer the marinade to a resealable plastic bag, add the lamb and refrigerate overnight.'),
('17215', '3', 'In a small bowl, combine the whole-grain mustard, crme frache, honey and a pinch each of cayenne and black pepper. whisk until smooth.'),
('17215', '4', 'Remove the lamb from the bag and scrape off the marinade.'),
('17215', '5', 'Heat the olive oil in a skillet. Season the lamb with salt and black pepper, add it to the skillet and cook over high heat until browned, about 3 minutes on each side for medium rare.'),
('17215', '6', 'Transfer the lamb to a cutting board, cover with foil and let stand for 10 minutes.'),
('17215', '7', 'Thinly slice the lamb, fold the pieces and spear them on wooden picks.'),
('17215', '8', 'Transfer to a platter and serve immediately with the mustard dipping sauce.'),
('17219', '1', 'Stir together yeast and warm water in a small bowl and let stand until foamy, about 5 minutes. (If mixture doesn''t foam, start over with new yeast.)'),
('17219', '2', 'Put 1 1/2 cups flour in a medium bowl, then make a well in center of flour and add yeast mixture to well. Stir together egg, 1 tablespoon oil, and 1 1/2 teaspoons salt with a fork.'),
('17219', '3', 'Add egg mixture to yeast mixture and mix with a wooden spoon or your fingertips, gradually incorporating flour, until a soft dough forms.'),
('17219', '4', 'Transfer dough to a floured surface and knead, working in additional flour (up to 1/4 cup) as necessary, until smooth and elastic, about 5 minutes.'),
('17219', '5', 'Transfer dough to an oiled bowl and turn to coat. Cover with plastic wrap and let rise in a draft-free place at warm room temperature until doubled, 1 to 1 1/2 hours.'),
('17219', '6', 'While dough rises, heat remaining 1/3 cup oil in a 12-inch heavy skillet over medium-high heat until it shimmers, then saute fennel seeds until a shade darker, about 30 seconds. Stir in onions, remaining teaspoon salt, and 1/2 teaspoon pepper, then reduce heat to medium-low and cover onions directly with a round of parchment paper. Cook, stirring occasionally, until onions are very tender and golden brown, 1 to 1 1/4 hours.'),
('17219', '7', 'Preheat oven to 375F with rack in middle.'),
('17219', '8', 'Knead dough gently on a floured surface with floured hands to deflate. Pat out dough on a large heavy baking sheet (preferably blue steel) into a 15- by 12-inch rectangle, turning up or crimping edge, then brush mustard evenly over dough, leaving a 1/2-inch border around edge.'),
('17219', '9', 'Spread onions evenly over mustard, then sprinkle evenly with cheese.'),
('17219', '10', 'Bake tart until crust is golden brown, 30 to 35 minutes.'),
('17219', '11', 'Cut into 2-inch squares or diamonds and serve warm or at room temperature.'),
('17220', '1', 'Preheat oven to 400F.'),
('17220', '2', 'Mix first 6 ingredients in medium bowl. (Can be prepared 1 day ahead. Cover and refrigerate)'),
('17220', '3', 'Line large roasting pan with double layer of foil. Trim any tough rind and fat from upper side of ham, leaving 1/4-inch-thick layer of fat. Using long sharp knife, score fat in 1-inch-wide diamond pattern.'),
('17220', '4', 'Place ham in prepared pan.'),
('17220', '5', 'Pour Madeira and 1 cup orange juice into bottom of pan.'),
('17220', '6', 'Bake ham until heated through, about 45 minutes.'),
('17220', '7', 'Remove pan from oven. Increase oven temperature to 450F.'),
('17220', '8', 'Spread mustard mixture generously over top and sides of ham. Return to oven and continue to bake until mustard coating is golden brown, about 35 minutes.'),
('17220', '9', 'Transfer ham to platter. Skim fat from pan juices and discard.'),
('17220', '10', 'Pour pan juices into medium saucepan.'),
('17220', '11', 'Add marjoram and bring to boil. Season sauce to taste with salt and pepper. Slice ham into 1/2-inch-thick slices.'),
('17220', '12', 'Serve with sauce.'),
('17222', '1', 'Heat olive oil in a heavy pot over high heat. Sprinkle short ribs on both sides with salt and pepper. Quickly sear both sides of the short ribs, using tongs to flip them halfway through. (Just sear about 1 1/2 minutes per side.)'),
('17222', '2', 'Remove the shortribs to a plate.'),
('17222', '3', 'Pour wine and beef broth into the pot.'),
('17222', '4', 'Add rosemary. Stir to combine, scraping the bottom of the pot to deglaze. Return the shortribs to the pot, reduce heat to low, then cover the pot and simmer it for 2 1/2 to 3 hours. (You can also put the pot into a 300 degree oven if you''d prefer not to simmer on the stovetop.)After they have cooked, carefully remove the shortribs from the pot again. Stir in mustard, cream, and capers, then raise the heat and allow it to bubble up and gently boil for a good couple of minutes, or until it has thickened a bit. Taste and add more salt and pepper if needed. Return the shortribs to the sauce, put on the lid, and turn off the heat.To roast the mushrooms, preheat oven to 400 degrees. Arrange the mushrooms in a single layer on a baking sheet.'),
('17222', '5', 'Drizzle with olive oil and sprinkle with salt and pepper, then roast the mushrooms until they''re golden brown, about 15 to 20 minutes.'),
('17222', '6', 'Serve the shortribs on top of the mushrooms, then drizzle with extra cream sauce.'),
('17222', '7', 'Add a little rosemary sprig if you want to be fancy.This is absolutely divine.'),
('17225', '1', 'Preheat oven to 375 degrees. Rub chicken breasts lightly with olive oil, and season with salt and pepper.'),
('17225', '2', 'Combine 2 tablespoons butter with the mustard. reserve 2 teaspoons for sauce. Melt remaining 2 tablespoons butter. mix with breadcrumbs and rosemary, and season with salt and pepper.In a large skillet, heat oil over medium-high heat. Sear chicken skin side down until crispy, about 5 minutes.'),
('17225', '3', 'Remove from heat. Smear with mustard mixture, and sprinkle with breadcrumbs. Turn skin side up. apply mustard mixture and breadcrumbs.'),
('17225', '4', 'Transfer skillet to oven, and roast until chicken is cooked through and top is golden brown, 15 to 20 minutes.'),
('17225', '5', 'Transfer chicken to serving platter.'),
('17225', '6', 'Add stock and cream to skillet over medium heat, and stir with wooden spoon until creamy and reduced to 3/4 cup, about 3 minutes.'),
('17225', '7', 'Remove from heat, and stir in reserved mustard mixture. Strain through a fine sieve, and serve with chicken.'),
('17225', '8', 'Garnish with rosemary.'),
('17226', '1', 'Preheat oven to 350 degrees.'),
('17226', '2', 'Pour milk over the bread slices. Allow it to soak in for several minutes.'),
('17226', '3', 'Place the ground beef, milk-soaked bread, Parmesan, seasoned salt, salt, black pepper, and parsley in a large mixing bowl.'),
('17226', '4', 'Pour in beaten eggs.With clean hands, mix the ingredients until well combined. Form the mixture into a loaf shape on a broiler pan, which will allow the fat to drain. (Line the bottom of the pan with foil to avoid a big mess!)Lay bacon slices over the top, tucking them underneath the meatloaf. Make the sauce: add ketchup, brown sugar, mustard, and hot sauce in a mixing bowl. Stir together.'),
('17226', '5', 'Pour 1/3 of the mixture over the top of the bacon.'),
('17226', '6', 'Spread with a spoon.'),
('17226', '7', 'Bake for 45 minutes, then pour another 1/3 of the sauce over the top.'),
('17226', '8', 'Bake for another 15 minutes. Slice and serve with remaining sauce.'),
('17226', '9', 'Serve with mashed potatoes. Yummy!'),
('17227', '1', 'Place chicken in a bowl. Sprinkle with salt and add mustard.In a food processor, chop half the onion, tomato, cilantro, garlic, and black pepper (or jalapeno/habanero).'),
('17229', '1', 'Heat oven to 400 F.'),
('17229', '2', 'Cut the sausages in quarters lengthwise, then in half crosswise.'),
('17229', '3', 'Cut the puff pastry into strips 3 inches long and 1 inch wide.'),
('17229', '4', 'Roll the sausage pieces in the pastry strips and transfer to a parchment-lined baking sheet.'),
('17229', '5', 'Bake until puffed and golden brown, 15 to 20 minutes.'),
('17229', '6', 'Transfer to a platter and serve with the mustard for dipping.'),
('17235', '1', 'Spray grill rack with nonstick spray. Prepare barbecue ( medium-high heat ).'),
('17235', '2', 'Whisk mustard, mayonnaise, tarragon, and brown sugar in medium bowl.'),
('17235', '3', 'Brush mustard sauce generously on both sides of pork cutlets.'),
('17235', '4', 'Grill pork until just cooked through and firm to touch, 2 to 3 minutes per side.'),
('17235', '5', 'Transfer to plates.'),
('17235', '6', 'Serve with Grilled Red and Green Cabbage Slaw.'),
('17235', '7', 'Per serving: 294 calories, 13g fat (4g saturated), 85mg cholesterol, 618mg sodium, 5g carbohydrates, 0g fiber, 33g protein'),
('17235', '8', 'Nutrition Data'),
('17235', '9', 'See Nutrition Data''s complete analysis of this recipe '),
('17238', '1', 'In a bowl, blend the Dijon mustard and mustard seeds. Season the rabbit parts with salt and pepper.'),
