INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('15979', '8', 'Transfer the potatoes to a rack set over a baking sheet, season with salt and keep warm on the back of the stove. Fry the remaining potatoes.'),
('15979', '9', 'Thickly slice the lamb. Arrange the potatoes on a plate, top with the lamb and spoon the chimichurri over it all.'),
('15981', '1', 'Heat a large Dutch oven over medium heat. Coat pan with cooking spray.'),
('15981', '2', 'Add half of lamb to pan, and cook 9 minutes, browning on all sides.'),
('15981', '3', 'Remove lamb from pan. Repeat procedure with cooking spray and remaining lamb.'),
('15981', '4', 'Add onion and carrot to pan; cook for 4 minutes, stirring frequently. Increase heat to medium-high. Stir in wine, scraping pan to loosen browned bits.'),
('15981', '5', 'Add rind and next 4 ingredients (through pepper); cook 5 minutes.'),
('15981', '6', 'Add lamb and broth; bring to a simmer. Cover, reduce heat, and simmer 2 1/2 hours or until lamb is very tender.'),
('15981', '7', 'Remove lamb and vegetables from pan with a slotted spoon; place in a large bowl.'),
('15981', '8', 'Place a large zip-top plastic bag inside an 8-cup glass measure or bowl.'),
('15981', '9', 'Pour broth mixture into bag; let stand 10 minutes (fat will rise to the top). Seal bag, and carefully snip off 1 bottom corner of bag.'),
('15981', '10', 'Drain drippings into pan, stopping before fat layer reaches opening; discard fat.'),
('15981', '11', 'Combine juice and 1 cup beans in a small bowl; mash with a fork until pastelike.'),
('15981', '12', 'Add juice mixture and remaining beans to pan; stir well to combine.'),
('15981', '13', 'Add lamb mixture; cook 5 minutes or until thoroughly heated.'),
('15981', '14', 'Garnish with parsley, if desired.'),
('15984', '1', 'Make about 8 small incisions on the fatty side of the lamb and insert a smashed garlic half and some rosemary into each slit. Rub the lamb on both sides with the olive oil, Marsala, remaining garlic and rosemary, mint, salt, and pepper Cover and refrigerate overnight or let stand 1 hour at cool room temperature.'),
('15984', '2', 'Brush the grill grates lightly with the safflower oil. Prepare a hot fire in a gas or charcoal grill.'),
('15984', '3', 'If the lamb has been in the refrigerator, bring it to room temperature.'),
('15984', '4', 'Remove the meat from the marinade and drain slightly, allowing some of the marinade to remain on the lamb for added flavor.'),
('15984', '5', 'When the fire is medium-hot (if using charcoal, the coals will be grey and slightly glowing), place the lamb on the grill and cook 15-20 minutes per side (depending on how hot the fire is), basting frequently with the remaining marinade. Move the lamb to the side of the grill away from the direct heat and continue to cook 10 to 15 minutes longer, turning once, or until the internal temperature registers 130 to 135 degrees for medium-rare and 140 to 145 degrees for medium'),
('15984', '6', 'Remove the lamb from the grill and let rest, lightly covered, on a carving board 10 minutes before slicing. Carve into 1/4-inch slices and serve immediately with Foster''s Seven Pepper Jelly with Fresh Mint.'),
('15987', '1', 'Preheat the oven to 35'),
('15987', '2', 'Heat the olive oil in a large saucepan.'),
('15987', '3', 'Add the minced garlic, onion and carrot and cook over moderately high heat, stirring occasionally, until lightly browned, about 5 minutes.'),
('15987', '4', 'Add the haricot blancs, thyme sprigs, 1 quart of the stock and the water and bring to a boil.'),
('15987', '5', 'Add the bacon and simmer over low heat, stirring occasionally, until the beans are very tender, about 2 1/2 hours. Season with salt and pepper and stir in the parsley.'),
('15987', '6', 'Meanwhile, rub the lamb all over with the chopped thyme, season with salt and roll into the shape of a roast; tie at 1-inch intervals with kitchen string.'),
('15987', '7', 'Set the roast in a shallow 12-inch baking dish.'),
('15987', '8', 'Add the remaining 1 cup of stock and roast the lamb for 30 minutes.'),
('15987', '9', 'Add the remaining 6 garlic cloves, cover with foil and roast for 2 1/2 hours, turning once, until the lamb is tender.'),
('15987', '10', 'Transfer the lamb to a carving board. Cover loosely with foil for 10 minutes.'),
('15987', '11', 'Mash the garlic into the pan juices and season with salt. Carve the lamb into thick slices.'),
('15987', '12', 'Serve the lamb with the pan sauce and the beans.'),
('15990', '1', 'Heat a medium saucepan over medium heat. Coat pan with cooking spray.'),
('15990', '2', 'Add onion and garlic to pan; cook 5 minutes or until golden brown, stirring frequently.'),
('15990', '3', 'Add rice and next 3 ingredients (through bay leaf); bring to a boil. Cover, reduce heat, and simmer 20 minutes. Discard bay leaf. Keep warm.'),
('15990', '4', 'Prepare grill.'),
('15990', '5', 'Combine salt and next 6 ingredients (through pepper).'),
('15990', '6', 'Brush lamb with oil, and rub with salt mixture.'),
('15990', '7', 'Place lamb on grill rack coated with cooking spray; grill 10 minutes, turning once or until a thermometer registers 145 (medium-rare) to 160 (medium).'),
('15990', '8', 'Let stand 5 minutes before slicing into chops.'),
('15990', '9', 'Serve lamb with rice.'),
('15990', '10', 'Wine note: Lambeven spicy lamb like thisis one of the most flexible meats when it comes to wine. It goes with just about every major red varietal. That said, when spice plays a key role, as it does here, I love to choose a thick, rich, spicy red that will both mirror the spiciness of the dish and act as a soft, thick backdrop. An Australian shiraz is perfect. And since this is a special, fairly expensive cut of meat, I''ve chosen a wine worthy of it: Penfolds St. Henri 2003 from South Australia, $ Karen MacNeil'),
('15992', '1', 'Prepare a charcoal or gas grill for high heat (450 to 550; you can hold your hand 5 in. above cooking grate only 2 to 4 seconds). In a large resealable plastic bag, combine garlic, mint, lemon zest, 1/4 cup olive oil, and 1 tsp. each salt and pepper.'),
('15992', '2', 'Add lamb chops and mix to coat.'),
('15992', '3', 'Grill tomato, onion, and bell peppers, turning twice, until soft and blackened, 6 minutes.'),
('15992', '4', 'Remove from heat.'),
('15992', '5', 'Remove chops from bag, keeping marinade on meat. Grill chops, turning once, until done the way you like, 5 minutes total for medium-rare (cut to test).'),
('15992', '6', 'Chop vegetables and mix with remaining 1/4 cup olive oil, the parsley, lemon juice, and remaining 1 tsp. each salt and pepper.'),
('15992', '7', 'Serve with lamb.'),
('15998', '1', 'In a mini food processor, combine the garlic, rosemary and olive oil and process until the garlic is finely chopped. Season the lamb racks with salt and pepper and rub the garlic-rosemary oil all over them. Set the racks fat side up on a large rimmed baking sheet and let stand for 1 hour.'),
('15998', '2', 'Preheat the oven to 45'),
('15998', '3', 'Roast the lamb in the upper third of the oven for 15 minutes. Turn the racks and roast for 10 minutes longer for medium-rare meat.'),
('15998', '4', 'Transfer the racks to a carving board, stand them upright and let rest for 10 minutes.'),
('15998', '5', 'Carve the racks in between the rib bones and transfer to plates.'),
('15998', '6', 'Serve right away.'),
('16000', '1', 'Preheat oven to 45'),
('16000', '2', 'Secure roast at 1-inch intervals with heavy string. Rub surface of roast with rosemary and garlic.'),
('16000', '3', 'Place roast on the rack of a broiler pan or roasting pan; insert a meat thermometer into thickest portion of roast.'),
('16000', '4', 'Bake at 450 for 1 hour and 15 minutes or until thermometer registers 140 (medium-rare) to 155 (medium).'),
('16000', '5', 'Sprinkle with salt.'),
('16000', '6', 'Place roast on a cutting board; cover loosely with foil.'),
('16000', '7', 'Let stand 10 minutes. (Temperature of roast will increase 5 upon standing.)'),
('16000', '8', 'Remove string before slicing.'),
('16001', '1', 'Preheat oven to 400°F with rack in middle.'),
('16001', '2', 'Mince and mash garlic to a paste with 1/2 teaspoon salt and 1/2 teaspoon pepper. Stir together with herbs and 1 tablespoon oil.'),
('16001', '3', 'Put tomatoes cut sides up in an oiled small baking dish and drizzle with a third of garlic mixture. Roast until tender, 30 to 40 minutes.'),
('16001', '4', 'Meanwhile, pat lamb dry and season with 1/4 teaspoon salt and 1/4 teaspoon pepper.'),
('16001', '5', 'Heat 1 tablespoon oil in a 10-inch ovenproof skillet over medium-high heat until it shimmers. Brown lamb on all sides, 4 to 6 minutes total.'),
('16001', '6', 'Transfer lamb to a cutting board and discard oil from skillet.'),
('16001', '7', 'Heat remaining tablespoon oil in skillet over medium heat and cook shallots and potatoes, stirring occasionally, until edges are browned, 3 to 5 minutes. Stir in  water and half of remaining garlic mixture and remove from heat.'),
('16001', '8', 'Rub remaining garlic mixture on fat side of lamb racks. Arrange lamb over potatoes and roast in oven until an instant-read thermometer inserted into center of meat (do not touch bone) registers 130°F for medium-rare, 20 to 25 minutes.'),
('16001', '9', 'Let stand, loosely covered, 5 to 10 minutes.'),
('16001', '10', 'Serve with tomatoes.'),
('16004', '1', 'Spray grill rack with nonstick spray; prepare barbecue (medium-high heat). Grill lamb 25 minutes for medium-rare (internal temperature at the thickest part of meat should be 125°F).'),
('16004', '2', 'Let lamb rest 5 minutes before slicing.'),
('16007', '1', 'Preheat the oven to 32'),
('16007', '2', 'Spread the pine nuts on a baking sheet and toast until golden, about 5 minutes.'),
('16007', '3', 'Let cool.'),
('16007', '4', 'Fill a small bowl with ice water. In a small saucepan of boiling water, blanch the basil leaves for 10 seconds.'),
('16007', '5', 'Drain and immediately transfer to the ice water.'),
('16007', '6', 'Drain and squeeze dry.'),
('16007', '7', 'Place the basil in a food processor with the 1/3 cup of warmed oil and puree until fairly smooth.'),
('16007', '8', 'Add the toast, 1 of the garlic cloves, 2 teaspoons of the lemon zest and 1/2 cup of the pine nuts and pulse until coarsely chopped. Season with salt, pepper and cayenne.'),
('16007', '9', 'Set the lamb on a work surface fat side down and season it with salt and pepper. Rub half of the basil mixture on the meat.'),
('16007', '10', 'Roll up the meat and tie it at 1-inch intervals with kitchen string.'),
('16007', '11', 'In a flameproof roasting pan, heat the 1 tablespoon of olive oil. Season the lamb with salt and pepper.'),
('16007', '12', 'Add the lamb to the roasting pan and cook over high heat, turning occasionally, until browned all over, 10 minutes.'),
('16007', '13', 'Add the butter, thyme and the remaining garlic clove to the roasting pan and cook for 1 minute, basting the lamb.'),
('16007', '14', 'Transfer the lamb to the oven; roast for 1 hour and 15 minutes, turning once or twice, until an instant-read thermometer registers 130 for medium-rare.'),
('16007', '15', 'Transfer the lamb to a cutting board; remove the strings.'),
('16007', '16', 'Preheat the broiler.'),
('16007', '17', 'Spread the remaining basil mixture over the roast and return the meat to the pan. Broil it 8 inches from the heat for 5 minutes, until the crust is lightly browned and sizzling.'),
('16007', '18', 'Transfer the meat to a cutting board; let rest for 20 minutes.'),
('16007', '19', 'Meanwhile, in a bowl, whisk the lemon juice with the mustard.'),
('16007', '20', 'Whisk in the remaining 1/3 cup of the oil, 1/4 cup of pine nuts, 1 teaspoon of lemon zest and the chopped basil; season with salt and pepper. Slice the meat; transfer to plates.'),
('16007', '21', 'Drizzle with the vinaigrette and serve.'),
('16010', '1', 'Boil cider, ginger, garlic, soy sauce, vinegar, and honey in a small saucepan until reduced to about 1/4 cup, 10 to 12 minutes. Cool completely. Reserve 2 tablespoons glaze for drizzling.'),
('16010', '2', 'Preheat broiler.'),
('16010', '3', 'Pat lamb chops dry and sprinkle with 1/2 teaspoon salt (total). Arrange on rack of a broiler pan and brush top of chops with half of glaze. Broil 3 to 4 inches from heat 3 minutes. Turn over and brush with remaining glaze, then broil 3 to 4 minutes more for medium-rare.'),
('16010', '4', 'Transfer chops to a plate and drizzle with reserved glaze.'),
('16010', '5', 'Let stand 5 minutes, then sprinkle with scallion.'),
('16010', '6', 'Nutrition Data'),
('16011', '1', 'Bring vermouth and raisins to a boil in a small saucepan, then remove from heat and let steep until raisins are soft and plump, about 15 minutes.'),
('16011', '2', 'Cook onion in oil in a large heavy skillet over medium-low heat, stirring occasionally, until onion is tender but not browned, 5 to 8 minutes.'),
('16011', '3', 'Add chard, raisins with any remaining vermouth, 1/2 teaspoon salt, and 1/4 teaspoon pepper and cook over medium heat, turning chard constantly with tongs, until chard is tender and liquid has evaporated, about 12 minutes.'),
('16011', '4', 'Transfer to a bowl and stir in nuts, then cool.'),
('16012', '1', 'Combine oil, lemon juice, garlic, oregano, salt, and pepper in sealable plastic bag.'),
('16012', '2', 'Add lamb and seal bag, pressing out air. Turn bag to coat lamb, then put bag in a shallow baking pan and marinate, chilled, turning bag over occasionally, at least 8 hours.'),
('16012', '3', 'Bring lamb to room temperature, about 1 hour, before grilling.'),
('16012', '4', 'Prepare grill for cooking over direct heat with medium-hot charcoal (moderate heat for gas); see Grilling Procedure'),
('16012', '5', 'Remove lamb from marinade (discard marinade) and run 3 or 4 skewers lengthwise through lamb about 2 inches apart. Grill on a lightly oiled grill rack, covered only if using gas grill, turning over occasionally and, if necessary, moving around on grill to avoid flare-ups, until thermometer registers 125 to 128°F, 8 to 14 minutes total for medium-rare.'),
('16012', '6', 'Transfer lamb to a cutting board and remove skewers.'),
('16012', '7', 'Let lamb stand, loosely covered with foil, 20 minutes. (Internal temperature will rise to 135°F while meat stands.)'),
('16012', '8', 'Cut across the grain into slices.'),
('16016', '1', 'Break cinnamon sticks into 1-inch pieces and finely grind in batches in an electric coffee/spice grinder with coriander, cumin, and cloves. Stir together with paprika and cayenne.'),
('16016', '2', 'Stir together 1/4 cup oil and 1 tablespoon garlic in a large bowl and add 25 lamb chops, tossing to coat. Season with salt and toss with 1/4 cup spice mixture and 1 cup cilantro to coat.'),
('16016', '3', 'Transfer coated lamb to sealable plastic bags and coat remaining meat in same manner. Marinate, chilled, at least 2 hours.'),
('16016', '4', 'Prepare grill.'),
('16016', '5', 'Season lamb with salt and grill in batches on an oiled rack about 4 minutes on one side, then 2 minutes on the other for medium-rare. (Alternatively, broil lamb under a preheated broiler 2 to 3 inches from heat.)'),
('16016', '6', 'Serve lamb warm or at room temperature.'),
('16019', '1', 'Preheat the oven to 275-degrees Fahrenheit.Truss and tie the lamb roast with 100% cotton cooking twine to ensure even cooking an attractive appearance.Pierce the lamb roast, inserting about half the garlic cloves into the roast.  Reserve the remaining cloves for the skillet.'),
('16019', '2', 'Heat about two tablespoons clarified butter in a cast iron skillet over a medium-high flame until it melts.'),
('16019', '3', 'Add the trussed and tied lamb roast to the hot fat, searing on each side for about 1 minute or so.Reduce the heat to medium and add the sun-dried olives, quartered preserved lemon, remaining garlic cloves and about half the fresh oregano to the skillet.  Allow this mixture to cook with the lamb, stirring as needed, for about two minutes.'),
('16019', '4', 'Pour about 1 cup of red or white wine or chicken stock, to the skillet.'),
('16019', '5', 'Remove from the heat and place the skillet in an oven preheated to 275 degrees Fahrenheit.Roast for about two to three hours, depending on the roast’s size.'),
('16019', '6', 'Serve in the skillet, sprinkled with remaining fresh oregano.'),
('16020', '1', 'Preheat the oven to 30'),
('16020', '2', 'Season the lamb shanks with salt and pepper.'),
('16020', '3', 'Heat 1/4 cup of the olive oil in a large enameled cast-iron casserole. Working in batches, cook the lamb shanks over moderate heat, turning often, until well browned on all sides, about 12 minutes; transfer to a platter.'),
('16020', '4', 'Pour off any fat from the casserole and add the remaining 2 tablespoons of olive oil.'),
('16020', '5', 'Add the carrots, celery and onions and cook over moderate heat until the vegetables start to brown, about 8 minutes. Stir in the tomato paste, then add the wine, scraping up the browned bits from the bottom. Stir in the bay leaves and peppercorns. Return the lamb shanks to the casserole and add the stock. Bring to a boil, cover and bake the shanks in the oven for about 3 hours, or until the meat is very tender.'),
('16020', '6', 'Transfer the shanks to the platter and remove the meat from the bones.'),
('16020', '7', 'Put the meat in a bowl and cover with a damp towel. Strain the sauce into a large saucepan, pressing on the vegetables to extract as much liquid as possible. Boil the sauce over high heat until it is thick enough to coat the back of a spoon, about 25 minutes; season with salt and pepper. Return the lamb to the sauce and rewarm over moderate heat.'),
('16020', '8', 'In a small bowl, mix the parsley with the lemon zest and garlic. Spoon the lamb stew over the Morel and Sweet Pea Risotto, sprinkle with the gremolata and serve.'),
('16021', '1', 'Season the lamb roasts generously with salt and pepper, wrap in plastic and refrigerate overnight. Bring the roasts to room temperature before cooking.'),
('16021', '2', 'Preheat the oven to 32'),
('16021', '3', 'In a food processor, pulse the almonds with the garlic until finely chopped.'),
('16021', '4', 'Add the mint leaves, cheese and 3/4 cup of the oil and process until smooth. Season the pesto with salt.'),
('16021', '5', 'In a large skillet, heat the remaining 2 tablespoons of olive oil until shimmering.'),
('16021', '6', 'Add the roasts and cook over high heat, turning, until browned all over, about 10 minutes.'),
('16021', '7', 'Transfer the roasts to a large roasting pan and spread half of the pesto over them. Cover tightly with foil and roast for about 2 hours, until an instant-read thermometer inserted in the center of each roast registers 17'),
('16021', '8', 'Remove the foil, increase the oven temperature to 425 and roast for 30 minutes longer, until browned on top.'),
('16021', '9', 'Transfer the lamb to a cutting board and let rest for 10 minutes.'),
('16021', '10', 'Remove the strings and carve each roast into 1/2-inch-thick slices.'),
('16021', '11', 'Serve with the remaining pesto and lemon wedges.'),
('16022', '1', 'In a small bowl, cover the morels with the boiling water and let soak until softened, about 15 minutes.'),
('16022', '2', 'Drain the morels, reserving the liquid. Slice the morels 1/2 inch thick, discarding the stems.'),
('16022', '3', 'Pour the liquid into a bowl, leaving behind any grit.'),
('16022', '4', 'In a saucepan, cook the lamb scraps over moderately high heat, stirring often, until browned all over.'),
('16022', '5', 'Add the veal stock and cook over moderate heat until reduced to 1/2 cup, about 20 minutes. Strain the stock, add 1/2 cup of the morel liquid and cook until the sauce is reduced to 1/2 cup. Season with salt and pepper.'),
('16022', '6', 'In a large pot of boiling, salted water, cook the fava beans for 2 minutes. Using a slotted spoon, transfer the favas to a plate and let cool, then peel them.'),
('16022', '7', 'Return the water to a boil and add the Potato Gnocchi. Stir gently twice and let the gnocchi rise to the surface. Cook for about 1 minute; the gnocchi should be puffed and cooked through.'),
('16022', '8', 'Drain the gnocchi and transfer to an oiled plate.'),
('16022', '9', 'Preheat the oven to 40'),
('16022', '10', 'In an ovenproof skillet, heat the oil until shimmering. Season the lamb with salt and pepper and cook, fatty side down, until browned and crusty, about 5 minutes. Turn the chops, transfer the skillet to the oven and roast for 10 minutes for medium rare.'),
('16022', '11', 'Let rest for 5 minutes on a cutting board.'),
('16022', '12', 'Melt 1/2 tablespoon of the butter in a large nonstick skillet.'),
('16022', '13', 'Add the morels and favas and cook over moderately high heat until warmed through, about 3 minutes.'),
('16022', '14', 'Add to the lamb sauce and swirl in 1 1/2 tablespoons of the butter.'),
('16022', '15', 'In the skillet, melt the remaining 2 tablespoons of butter over moderately high heat until golden.'),
('16022', '16', 'Add the gnocchi and thyme, season with salt and pepper and cook, tossing, until lightly golden.'),
('16022', '17', 'Spoon the gnocchi onto 4 plates and add the morels and favas. Slice the lamb between the bones and arrange on the plates.'),
('16022', '18', 'Drizzle any remaining sauce around the lamb and serve.'),
('16023', '1', 'Preheat the oven to 40'),
('16023', '2', 'Set the lamb racks in a medium roasting pan. Season the lamb generously with salt and pepper and drizzle with olive oil. Roast until an instant-read thermometer inserted into the center registers 125 for medium-rare, about 35 minutes.'),
('16023', '3', 'Transfer to a cutting board and let rest for 5 minutes.'),
('16023', '4', 'Meanwhile, in a blender, combine the coconut milk, mint leaves, ginger, garlic, lime juice, jalapeo and cilantro and puree until smooth. Season the sauce with salt and pepper.'),
('16023', '5', 'In a medium skillet, melt the butter.'),
('16023', '6', 'Add the shallot and cook over moderate heat, stirring, until softened, 2 to 3 minutes.'),
('16023', '7', 'Add the peas and brown sugar, season with salt and pepper and cook until the peas are lightly coated, 2 to 3 minutes longer.'),
('16023', '8', 'Carve the lamb into chops and serve with the coconut-mint sauce and peas.'),
('16029', '1', 'Let lamb stand at room temperature 1 hour.'),
('16029', '2', 'Roll up lamb jelly-roll fashion; secure at 1-inch intervals with twine.'),
('16029', '3', 'Heat a large skillet over medium-high heat.'),
('16029', '4', 'Add oil to pan.'),
('16029', '5', 'Add lamb; cook 6 minutes, browning on all sides.'),
('16029', '6', 'Combine ketchup and next 5 ingredients (through garlic) in a large bowl. Coat lamb evenly with ketchup mixture.'),
('16029', '7', 'Place lamb on the rack of a roasting pan coated with cooking spray; place rack in pan.'),
('16029', '8', 'Preheat oven to 20'),
('16029', '9', 'Bake lamb at 200 for 2 hours or until a thermometer registers 135 or until desired degree of doneness.'),
('16029', '10', 'Let stand 20 minutes before slicing.'),
('16030', '1', 'Combine first 7 ingredients in a small bowl, stirring well.'),
('16030', '2', 'Place lamb in a single layer in a shallow dish; rub spice mixture evenly over both sides of lamb. Cover and refrigerate for 4 hours.'),
('16030', '3', 'Prepare grill.'),
('16030', '4', 'Place lamb on a grill rack coated with cooking spray. Grill 4 minutes on each side or until desired degree of doneness.'),
('16030', '5', 'Serve immediately.'),
('16031', '1', 'In a medium saucepan, melt 1 tablespoon of the butter in the olive oil.'),
('16031', '2', 'Add the chopped shallots and cook over high heat, stirring a few times, until richly browned, about 5 minutes.'),
('16031', '3', 'Add the beef stock, red wine and thyme leaves and boil over high heat until reduced to 1 cup, about 10 minutes. Strain the shallot jus into a small saucepan.'),
('16031', '4', 'Whisk in the remaining 4 tablespoons of butter, 1 tablespoon at a time. Season with salt and pepper.'),
('16031', '5', 'Preheat the oven to 40'),
('16031', '6', 'Season the lamb with salt and pepper. In a large ovenproof skillet, heat 1 tablespoon of the vegetable oil until shimmering.'),
('16031', '7', 'Add the lamb fat side down, and cook over moderately high heat, turning once, until browned all over, about 8 minutes.'),
('16031', '8', 'Transfer the lamb to a large plate and let stand for 10 minutes. Using a mortar and pestle or spice grinder, coarsely crush the coriander seeds.'),
('16031', '9', 'Spread the coriander on a plate. Rub the lamb all over with the coriander, pressing to adhere.'),
('16031', '10', 'Pour off any fat in the skillet.'),
('16031', '11', 'Add the remaining 1 tablespoon of vegetable oil and heat until shimmering. Set the lamb in the skillet, fat side down, and transfer the skillet to the oven. Roast for about 22 minutes, turning the lamb halfway through, until the meat is medium-rare and an instant-read thermometer inserted in the thickest part registers 12'),
('16031', '12', 'Transfer the lamb to a carving board and let rest for 10 minutes.'),
('16031', '13', 'Gently reheat the jus, stirring, until hot; do not let it boil.'),
('16031', '14', 'Cut the rack between the ribs and arrange the chops on plates.'),
('16031', '15', 'Serve, passing the shallot jus at the table.'),
('16032', '1', 'Preheat broiler.'),
('16032', '2', 'Bring 1 cup of water to a boil in a medium saucepan; gradually stir in couscous.'),
('16032', '3', 'Remove from heat; cover and let stand 5 minutes. Fluff with a fork.'),
('16032', '4', 'While couscous stands, sprinkle lamb with salt and 1/8 teaspoon pepper.'),
('16032', '5', 'Place lamb on a broiler pan coated with cooking spray; broil 5 minutes on each side or until desired degree of doneness.'),
('16032', '6', 'While lamb cooks, combine 1/8 teaspoon pepper, yogurt, and remaining ingredients.'),
('16032', '7', 'Serve lamb over couscous with yogurt sauce.'),
('16033', '1', 'Heat a large nonstick skillet over medium-high heat. Sprinkle lamb chops with 1/8 teaspoon salt and 1/8 teaspoon black pepper. Coat pan with cooking spray.'),
('16033', '2', 'Add lamb to pan; cook 2 minutes on each side or until lightly browned.'),
('16033', '3', 'Remove lamb from pan.'),
('16033', '4', 'Add remaining 1/8 teaspoon salt, remaining 1/8 teaspoon black pepper, onion, and garlic to pan; saut 2 minutes.'),
('16033', '5', 'Place fennel seeds in a heavy-duty zip-top plastic bag; seal. Crush seeds with a rolling pin.'),
('16033', '6', 'Add seeds, capers, and tomatoes to pan; bring to a boil. Return lamb to pan. Cover, reduce heat, and cook 6 minutes or until desired degree of doneness.'),
('16034', '1', 'Preheat broiler.'),
('16034', '2', 'Prepare pasta according to package directions, omitting salt and fat.'),
('16034', '3', 'Drain.'),
('16034', '4', 'Combine pasta, spinach, and the next 5 ingredients (through oil) in a medium bowl. Stir in 1/4 teaspoon salt.'),
('16034', '5', 'Combine remaining 1/4 teaspoon salt, herbes de Provence, mustard, and pepper in a small bowl. Rub lamb evenly with herb mixture.'),
('16034', '6', 'Place on a broiler pan coated with cooking spray; broil 6 minutes, turning once halfway through cooking or until desired degree of doneness.'),
('16034', '7', 'Serve with pasta mixture.'),
('16035', '1', 'Preheat oven to 42'),
('16035', '2', 'Combine first 5 ingredients in a small bowl; stir with a whisk.'),
('16035', '3', 'Sprinkle lamb evenly with salt and freshly ground pepper; rub lamb evenly with herb mixture.'),
('16035', '4', 'Place on a jelly-roll pan or broiler pan coated with cooking spray.'),
('16035', '5', 'Bake at 425 for 35 minutes or until a thermometer registers 145 (medium-rare). Cover with foil; let stand 10 minutes before serving. Slice rack into 8 pieces.'),
('16036', '1', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('16036', '2', 'Combine rosemary, salt, and 1/4 teaspoon pepper in a small bowl, stirring well. Rub spice mixture evenly over both sides of lamb.'),
('16036', '3', 'Add lamb to pan; cook 5 minutes on each side.'),
('16036', '4', 'Remove lamb from pan. Wipe pan clean with paper towels.'),
('16036', '5', 'Return pan to medium heat; recoat with cooking spray.'),
('16036', '6', 'Add garlic to pan; cook 30 seconds.'),
('16036', '7', 'Add remaining 1/4 teaspoon pepper and broth; cook 1 minute, scraping pan to loosen browned bits. Stir in preserves and vinegar; cook 3 minutes or until slightly thick. Return lamb to pan; turn to coat. Cook 1 minute or until desired degree of doneness.'),
('16036', '8', 'Garnish with parsley sprigs, if desired.'),
('16037', '1', 'In a food processor, combine the 1/2 cup of cilantro leaves with the garlic and mint and pulse until coarsely chopped.'),
('16037', '2', 'Add 1/3 cup of the lemon juice, 1 tablespoon of olive oil, the paprika, black pepper, cumin, turmeric, fennel seeds, cayenne, cinnamon and 1 teaspoon of kosher salt. Process until a paste forms.'),
('16037', '3', 'Put the chops in a baking dish, pour the marinade over them and turn to coat.'),
('16037', '4', 'Light a grill or preheat a grill pan. Grill the chops over a medium-high fire for 8 minutes, turning once, until an instant-read thermometer inserted in the thickest part of a chop registers 125 to 130 for medium rare.'),
('16037', '5', 'Transfer the chops to a platter and let rest for 5 minutes.'),
('16037', '6', 'Meanwhile, in a small bowl, whisk the tahini and water with the remaining 2 tablespoons of lemon juice and 1 1/2 tablespoons of olive oil.'),
('16037', '7', 'Garnish the chops with the chopped cilantro and serve with the tahini sauce.'),
('16038', '1', 'Straddle roasting pan across 2 burners, then cook onions and peppers in 1/4 cup oil with bay leaves and 1 teaspoon salt over medium heat, stirring occasionally, until onions are softened, about 5 minutes.'),
('16038', '2', 'Add tomatoes with juice, breaking them up with a spoon, and cook, stirring, until liquid has evaporated, about 3 minutes. Sprinkle paprika over tomato mixture and stir just to combine, then immediately stir in broth.'),
('16038', '3', 'Remove from heat.'),
('16038', '4', 'Preheat oven to 350°F with rack in middle.'),
('16038', '5', 'Pat shanks dry and season all over with 2 teaspoon salt.'),
('16038', '6', 'Heat 1/4 cup oil in a 12-inch heavy skillet over high heat until it shimmers, then add 4 shanks and brown, turning once, about 8 minutes total.'),
('16038', '7', 'Add shanks to tomato mixture in roasting pan.'),
('16038', '8', 'Pour off fat from skillet and wipe clean.'),
('16038', '9', 'Heat remaining 1/4 cup oil and brown remaining 4 shanks in same manner, transferring to roasting pan.'),
('16038', '10', 'Pour off fat from skillet, then add wine to skillet and boil, stirring and scraping up any brown bits, 15 to 20 seconds.'),
('16038', '11', 'Pour into roasting pan. Bring to a boil, then cover tightly with heavy-duty foil and braise in oven until very tender, 2 to 2 1/2 hours (depending on size).'),
('16038', '12', 'Transfer shanks with a slotted spoon to a platter and keep warm, loosely covered with foil. Skim off any fat from braising liquid.'),
('16038', '13', 'Whisk together sour cream and flour in a medium bowl.'),
('16038', '14', 'Whisk about 1 cup hot braising liquid into sour-cream mixture, then add mixture to remaining braising liquid in roasting pan and simmer (straddled across 2 burners) over low heat, whisking occasionally, until sauce is thickened, about 5 minutes.'),
('16038', '15', 'Return shanks to sauce along with any meat juices from platter, and simmer until heated through, about 10 minutes. Discard bay leaves.'),
('16039', '1', 'Special equipment: Large square of cheesecloth'),
('16039', '2', 'Bring 8 cups of water to a boil in a big pot. Wrap the fennel seeds, coriander seeds, cumin seeds, garlic, cardamom, cinnamon, and bay leaves into the center of the cheesecloth square and tie up the sides of the cheesecloth into a little package and tie a tight knot at the top, a bouquet garni. Drop the bouquet garni into the boiling water.'),
('16039', '3', 'Add the onion and tomato. When the water comes back up to a boil, add the lamb meat. Bring the mixture back to a boil, and then reduce the heat to medium-high and simmer for 20 minutes, or until the meat is tender.'),
('16039', '4', 'In another large pot, heat 2 tablespoons vegetable oil over medium heat and saute the onion with the caraway seeds until soft. Stir in the drained rice and toast until the grains separate from each other, and the rice glistens with oil, about 5 minutes.'),
('16039', '5', 'Remove the bouquet garni from the stock.'),
('16039', '6', 'Remove the lamb from the stock.'),
('16039', '7', 'Pour the stock over the rice and bring to boil. Reduce the heat to medium-low and simmer on low, covered, 15 minutes, or until the rice is cooked.'),
('16039', '8', 'Place a bed of rice on each plate, top with a few pieces of lamb. Sprinkle the cashews and raisins over the dish and serve.'),
('16042', '1', 'Rub chops with oil and 1 tablespoon lemon juice; sprinkle evenly with 1/2 teaspoon salt and pepper. Rub chops with garlic and lemon rind. Cover and chill 30 minutes.'),
('16042', '2', 'Combine chopped tomato, next 7 ingredients, and remaining 1 tablespoon lemon juice.'),
('16042', '3', 'Grill lamb, covered with grill lid, over medium-high heat (350 to 40'),
('16042', '4', '5 to 7 minutes on each side or to desired degree of doneness.'),
('16042', '5', 'Serve chops with salsa over hot cooked couscous.'),
('16042', '6', '*1/4 cup drained canned crushed pineapple in juice may be substituted.'),
('16043', '1', 'Mince garlic, then mash to a paste with salt. Stir together garlic paste, oil, lemon zest and juice, thyme, pepper, and allspice. Put lamb, fat side up, in a large ceramic or glass dish. Using a paring knife, make 1 1/2-inch-long slits (about 2 inches deep) 2 inches apart all over leg. Reserve 1 teaspoon thyme mixture and push remainder into slits, then rub all over with reserved teaspoon of mixture. Marinate lamb, covered and chilled, 12 hours.'),
('16043', '2', 'Let lamb stand at room temperature 30 minutes before grilling.'),
('16043', '3', 'Prepare grill for indirect-heat cooking over medium-hot charcoal (high heat for gas). If using a gas grill, preheat all burners on high, covered, 10 minutes, then turn off all burners except burner closest to you.'),
('16043', '4', 'Oil grill rack, then grill lamb over area with no coals (or over turned-off burner or burners), covered, without turning, until thermometer inserted into thickest part of roast (almost to the bone but not touching it) registers 125°F for medium-rare, 1 1/4 to 1 1/2 hours (temperatures in thinner parts of leg may register up to 160°F). To maintain medium-hot charcoal, add more charcoal (about 2 cups) every 15 minutes.'),
('16043', '5', 'Let lamb stand on a cutting board, uncovered, 30 minutes.'),
('16044', '1', 'Prepare grill for direct-heat cooking over medium-hot charcoal (medium-high heat for gas); see Grilling Procedure. Soak mushrooms in boiling-hot water (2 cups) until softened, about 20 minutes. Lift mushrooms out of water and strain liquid through a paper-towel-lined sieve set over a small saucepan. Coarsely chop mushrooms.'),
('16044', '2', 'Boil mushroom liquid in saucepan until reduced to about 1/4 cup, 13 to 15 minutes.'),
('16044', '3', 'Whisk in mustard, butter, and 1/8 teaspoon pepper and simmer until slightly thickened, about 2 minutes. Stir in mushrooms.'),
('16044', '4', 'Transfer to a small bowl and cool slightly. Stir in 2 tablespoon parsley.'),
('16044', '5', 'Meanwhile, pulse rosemary, kosher salt, garlic, and 1/2 teaspoon pepper in a food processor to form a coarse paste, scraping down sides. Rub oil all over chops, then coat evenly with rosemary mixture.'),
('16044', '6', 'Oil grill rack, then grill chops in 2 batches, covered only if using a gas grill, turning once, 4 to 6 minutes per batch for medium-rare.'),
('16044', '7', 'Sprinkle porcini mustard with remaining tablespoon parsley and serve with lamb.'),
('16045', '1', 'Preheat broiler.'),
('16045', '2', 'Stir together cinnamon and 11/2 teaspoon each of salt and pepper in a bowl, then rub over chops. Broil in a 4-sided sheet pan 3 to 4 inches from heat, turning once, 8 to 10 minutes total for medium-rare.'),
('16046', '1', 'Pat lamb dry and score fat by making shallow cuts all over with tip of a sharp small knife.'),
('16046', '2', 'Pound garlic to a paste with sea salt using a mortar and pestle (or mince and mash with a heavy knife) and stir together with rosemary and pepper. Put lamb in a lightly oiled roasting pan, then rub paste all over lamb.'),
('16046', '3', 'Let stand at room temperature 30 minutes.'),
('16046', '4', 'Preheat oven to 350°F.'),
('16046', '5', 'Roast lamb in middle of oven until an instant-read thermometer inserted 2 inches into thickest part of meat (do not touch bone) registers 130°F, 1 1/2 to 1 3/4 hours.'),
('16046', '6', 'Transfer to a cutting board and let stand 15 to 25 minutes (internal temperature will rise to about 140°F for medium-rare).'),
('16046', '7', 'Add wine to pan and deglaze by boiling over moderately high heat, stirring and scraping up brown bits, 1 minute. Season pan juices with salt and pepper and serve with lamb.'),
('16047', '1', 'Mix first 4 ingredients and 1 tablespoonolive oil in large bowl.'),
('16047', '2', 'Add lamb; turn tocoat.'),
('16047', '3', 'Let marinate at room temperature atleast 30 minutes and up to 1 hour.'),
('16047', '4', 'Preheat oven to 400°F.'),
('16047', '5', 'Heat remaining1 tablespoon olive oil in heavy largeovenproof skillet over high heat.'),
('16047', '6', 'Add lamb;cook until browned, about 3 minutes perside.'),
('16047', '7', 'Transfer skillet to oven and roastlamb chops to desired doneness, about10 minutes for medium-rare.'),
('16047', '8', 'Transfer lambto platter, cover, and let rest 5 minutes.'),
('16049', '1', 'Combine first 5 ingredients in processor; blend until garlic is finely chopped. Coat chops with garlic mixture. Arrange chops in single layer on baking sheet. (Can be made 8 hours ahead. Cover; chill.)'),
('16049', '2', 'Preheat broiler. Watching closely, broil lamb 4 to 5 inches from heat source until cooked to desired doneness, about 3 minutes per side for medium-rare.'),
('16049', '3', 'Transfer 3 chops to each plate and serve.'),
('16050', '1', 'Season the lamb racks with pepper. In a large shallow dish, combine the olive oil with the rosemary.'),
('16050', '2', 'Add the lamb and turn to coat. Cover and refrigerate for at least 1 hour or overnight.'),
('16050', '3', 'Light a grill or preheat the oven to 50'),
('16050', '4', 'Season the lamb with salt and grill it, fat side down, until the fat is browned and very crisp, about 5 minutes. Turn the lamb and move it away from the coals (if necessary, push the coals to one side). Cover and grill the lamb for about 10 minutes, turning, until an instant-read thermometer inserted into the meat registers 130 for medium rare. Alternatively, heat a large ovenproof skillet.'),
('16050', '5', 'Add the lamb racks, fat side down, and cook over moderately high heat until well browned, about 8 minutes. Turn the racks and lightly brown the other meaty side, about 3 minutes.'),
('16050', '6', 'Transfer to the oven and roast for about 10 minutes, or until medium rare.'),
('16050', '7', 'Transfer the racks to a cutting board and let stand for 5 minutes.'),
('16050', '8', 'Brush the lamb racks generously with the mustard and pat the herbs on top. Carve the lamb into 8 double chops.'),
('16050', '9', 'Serve at once.'),
('16051', '1', 'Watch how to make this recipe.'),
('16051', '2', 'In a food processor, combine the pistachios, olives, capers, garlic, and herbs and puree. While the machine is running, slowly drizzle in olive oil until the mixture becomes a paste.'),
('16051', '3', 'Add the zest and pulse 1 more time, drizzling in more oil if necessary. Reserve until ready to use.'),
('16051', '4', 'Have a butcher remove the 2nd and 7th rib bones from the 8 rib rack to make it a 6 rib rack. This will create 6 even chops that are thicker than a normal lamb chop.'),
('16051', '5', 'Cut into 6 even chops and season them generously with salt and allow them to sit for 10 to 15 minutes before cooking.'),
('16051', '6', 'Preheat the oven to 425 degrees F.'),
('16051', '7', 'Coat a large saute pan generously with olive oil and bring to medium-high heat. When the oil is hot but not smoking, add the lamb chops and cook for about 2 minutes on each side to brown. If the pan begins to smoke, lower the heat. The chops should be beautifully caramelized on both sides.'),
('16051', '8', 'Remove the chops to a sheet pan and schmear generously with the pistachio tapenade.'),
('16051', '9', 'Place in the oven and cook another 4 to 5 minutes for medium rare.'),
('16051', '10', 'Remove the chops from the oven and let them rest for at least 5 minutes before serving.'),
('16052', '1', 'Watch how to make this recipe.'),
('16052', '2', 'Preheat a charcoal grill to high heat using the direct heat method.'),
('16052', '3', 'Whisk together the jam, vinegar, mint, parsley and season with salt and pepper.'),
('16052', '4', 'Brush the chops with oil on both sides and sprinkle with salt and pepper.'),
('16052', '5', 'Put the chops on the grill and cook until golden brown and slightly charred, about 3 minutes. Flip over, brush with glaze and continue cooking until cooked to medium-rare doneness, about 3 minutes longer, brushing with more of the glaze.'),
('16052', '6', 'Remove to a platter and sprinkle with the pistachios, sumac and parsley leaves.'),
('16053', '1', 'Bring 1 1/4 cups broth, 2 teaspoons oil, and 1/8 teaspoon salt to a boil in a medium saucepan. Stir in couscous; cover.'),
('16053', '2', 'Remove pan from heat.'),
('16053', '3', 'Combine remaining 2 teaspoons olive oil, remaining 3/8 teaspoon salt, rosemary, garlic powder, and pepper in a bowl. Rub paste evenly on both sides of chops.'),
('16053', '4', 'Heat a skillet over medium-high heat. Coat pan with cooking spray.'),
('16053', '5', 'Add lamb; cook for 6 minutes or until desired degree of doneness, turning once.'),
('16053', '6', 'Remove from pan, and keep warm.'),
('16053', '7', 'Add remaining 1/4 cup broth, jelly, vinegar, and mustard. Bring to a boil. Reduce heat; simmer for 90 seconds or until slightly syrupy.'),
('16053', '8', 'Fluff couscous with a fork; stir in pistachios, and sprinkle with mint. Spoon sauce over lamb.'),
('16053', '9', 'Garnish with rosemary leaves, if desired.'),
('16054', '1', 'Prepare grill.'),
('16054', '2', 'Combine first 5 ingredients; rub evenly over both sides of lamb.'),
('16054', '3', 'Place lamb on a grill rack coated with cooking spray; grill 4 minutes on each side or until desired degree of doneness.'),
('16055', '1', 'Preheat oven to 40'),
('16055', '2', 'Combine first 5 ingredients in a bowl; stir in 1 tablespoon vinegar.'),
('16055', '3', 'Sprinkle lamb with 1/4 teaspoon salt and 1/4 teaspoon pepper.'),
('16055', '4', 'Heat a large ovenproof skillet over medium-high heat. Coat pan with cooking spray.'),
('16055', '5', 'Add lamb to pan; cook for 2 minutes on each side or until browned.'),
('16055', '6', 'Remove lamb from pan; pat thyme mixture over lamb. Return lamb to pan; place pan in oven.'),
('16055', '7', 'Bake at 400 for 15 minutes or until a thermometer registers 13'),
('16055', '8', 'Remove lamb from pan, and let stand for 10 minutes.'),
('16055', '9', 'Cut into chops.'),
('16055', '10', 'Return pan to medium-high heat; add remaining 1/4 cup vinegar, port, and shallots. Bring to a boil. Boil 1 minute or until mixture is reduced by half; stir in broth. Bring to a boil; cook 3 minutes or until liquid measures about 1/2 cup. Stir in remaining 1/4 teaspoon salt, remaining 1/4 teaspoon pepper, and preserves. Cook 1 minute; remove from heat.'),
('16055', '11', 'Add butter, stirring until butter melts.'),
('16055', '12', 'Serve sauce with lamb.'),
('16061', '1', 'To prepare sauce, combine cornstarch and water in small bowl, stirring with a whisk to form a slurry. Bring vinegar and sugar to a simmer in small saucepan, stirring until sugar dissolves.'),
('16061', '2', 'Add slurry mixture; simmer 2 minutes or until slightly thickened, stirring constantly with a whisk.'),
('16061', '3', 'Remove from heat. Stir in mint and curry powder; steep 30 minutes. Strain and set aside.'),
('16061', '4', 'Preheat oven to 45'),
('16061', '5', 'To prepare lamb, place bread in a food processor, and pulse 10 times or until coarse crumbs measure 1 cup.'),
('16061', '6', 'Combine breadcrumbs, garam masala, 1/2 teaspoon salt, and 1/2 teaspoon pepper in a small bowl.'),
('16061', '7', 'Place lamb on a shallow baking sheet. Press breadcrumb mixture onto lamb.'),
('16061', '8', 'Bake at 450 for 15 minutes or until desired degree of doneness.'),
('16062', '1', 'Season the lamb on all sides with salt and pepper. In a Dutch oven on medium-high heat add the olive oil. When the oil begins to swirl, add the shanks and sear until golden on all sides.'),
('16062', '2', 'Remove the shanks to a plate and add the butter, curry powder, allspice, and paprika. Stir with a wooden spoon until fragrant and the spices darken, about 2 minutes.'),
('16062', '3', 'Add the onions, bell pepper, garlic, thyme, scotch bonnet, and then season with salt and pepper. Allow the vegetables to become tender and golden with the spices, about 5 minutes. Stir everything together then add the shanks back to the pot.'),
('16062', '4', 'Add the chicken stock, cover and bring to a simmer.'),
('16062', '5', 'Simmer, stirring occasionally, until the lamb is fork tender, about 2 hours. Taste and season if needed, then add the potatoes and simmer until the potatoes are fork tender, about 30 minutes more. If making the day before, refrigerate and remove the film of fat from the top before reheating.'),
('16062', '6', 'Serve the lamb shanks over Right Rice, recipe follows and garnish with chopped cilantro.'),
('16062', '7', 'Rinse the rice 3 times to remove the starch.'),
('16062', '8', 'Put the rice in a medium saucepan and fill with enough water to cover the rice by 1/2-inch or measure by placing your thumb tip on the rice and filling the pot with water until the water reaches the middle of your thumbnail. Bring the rice to a simmer, cover and cook until tender and the liquid is evaporated, about 15 minutes.'),
('16062', '9', 'Remove from the heat and let the rice stand another 5 minutes, covered.'),
('16063', '1', 'Position rack in center of oven and preheat to 450°F.'),
('16063', '2', 'Place parsley, chopped rosemary, grated Parmesan cheese and garlic in processor. Process to coarse paste. With machine running, gradually add olive oil. Season pesto to taste with salt and pepper.'),
('16063', '3', 'Place lamb on small rimmed baking sheet. Sprinkle with salt and pepper.'),
('16063', '4', 'Spread all pesto over rounded side of lamb. Roast 10 minutes. Reduce oven temperature to 400°F and roast to desired doneness, about 15 minutes longer for medium-rare.'),
('16063', '5', 'Cut lamb between bones into chops. Divide chops between 2 plates; garnish with rosemary sprigs.'),
('16066', '1', 'Place trimmed lamb in large bowl; sprinkle generously with salt and pepper. Cover and let stand at room temperature 30 minutes.'),
('16066', '2', 'Combine 1 cup chopped parsley, minced garlic, and grated lemon peel in small bowl. Reserve remaining 1/4 cup parsley for garnish.'),
('16066', '3', 'Heat oil in heavy large pot over high heat. Working in batches, add lamb and cook until well browned on all sides, about 7 minutes per batch.'),
('16066', '4', 'Transfer lamb to medium bowl.'),
('16066', '5', 'Add leeks and onion to drippings in pot and sauté until softened, about 7 minutes.'),
('16066', '6', 'Add chopped parsley mixture and thyme; stir 30 seconds. Return lamb and any accumulated juices to pot.'),
('16066', '7', 'Add 1 1/2 cups broth and bring to boil. Reduce heat to medium-low; cover and simmer until lamb is very tender, about 1 1/2 hours.'),
('16066', '8', 'Lamb stew can be prepared 1 day ahead of serving. Cool slightly. Refrigerate stew uncovered until cold, then cover and keep refrigerated. Bring lamb stew to simmer before continuing with recipe.'),
('16066', '9', 'Fill medium bowl with cold water. Squeeze juice from lemon half into water; add squeezed lemon half. Break off tough outer leaves from 1 artichoke where leaves break naturally, stopping when first yellow leaves are reached.'),
('16066', '10', 'Cut off stem and top 1/2 inch from artichoke, then cut artichoke in half lengthwise and drop into lemon water. Repeat with remaining artichokes.'),
('16066', '11', 'Drain artichokes and add to lamb stew. Bring to boil. Reduce heat to medium-low; cover and simmer until artichokes are tender, adding more broth by 1/4 cupfuls if stew is dry, about 25 minutes. Season stew to taste with salt and pepper.'),
('16066', '12', 'Transfer to bowl; sprinkle lamb stew with reserved 1/4 cup chopped parsley and serve with Mock Risotto alongside.'),
('16068', '1', 'Preheat oven to 425°F. Sprinkle lamb with salt and pepper.'),
('16068', '2', 'Combine jam and Dijon mustard in small bowl; whisk to blend.'),
('16068', '3', 'Mix pecans, Italian parsley, and fresh breadcrumbs in another small bowl to blend.'),
('16068', '4', 'Spread half of mustard glaze over rounded side of each lamb rack. Pat half of breadcrumb mixture over mustard glaze on each.'),
('16068', '5', 'Drizzle each with 2 tablespoons melted butter.'),
('16068', '6', 'Transfer lamb to large rimmed baking sheet. Roast until breadcrumb topping is golden and thermometer inserted into lamb registers 130°F for medium-rare, about 30 minutes.'),
('16068', '7', 'Cut racks between bones into individual chps and serve.'),
('16070', '1', 'Preheat the oven to 350°F. Oil a roasting pan just large enough to hold the lamb.'),
('16070', '2', 'Place a rack in the pan.'),
('16070', '3', 'Stuff the lamb Unroll the lamb and spread the boned-out side with the tapenade.'),
('16070', '4', 'Roll up the lamb tightly. Tie it at 2-inch intervals with kitchen twine. With a small, sharp knife, cut slits 2 or 3 inches apart in the top of the roast. Push the garlic slices into the slits. Sprinkle the roast all over with the rosemary, salt, and pepper.'),
('16070', '5', 'Roast the lamb for about 1 hour and 15 minutes. To check for doneness, insert an instant-read thermometer in the thickest part of the meat. For medium-rare, the temperature should be 140 to 150°F. Cover loosely with foil and let the meat rest for at least 30 minutes before slicing.'),
('16070', '6', 'To serve'),
('16070', '7', 'Cut into thin slices.'),
('16071', '1', 'In a large roasting pan, mix 1/2 cup of the lemon juice with 2 teaspoons of salt.'),
('16071', '2', 'Place the lamb in the pan and coat well with the lemon juice.'),
('16071', '3', 'Let the lamb stand in the juice for 30 minutes, then drain.'),
('16071', '4', 'In a large bowl, mix the yogurt with the oil, garlic, ginger, dry mustard, cumin, nutmeg, cardamom, black pepper, cinnamon, turmeric and cayenne. Stir in 2 teaspoons of salt and the remaining 2 tablespoons of lemon juice. With a small knife, make 1-inch-deep slits all over the lamb. Coat the lamb thoroughly with the marinade, pushing it into the slits. Cover and refrigerate for at least 6 hours or overnight.'),
('16071', '5', 'Light a charcoal grill.'),
('16071', '6', 'Remove the leg of lamb from the marinade, leaving on a thick layer. Move the hot coals to one side of the grill and place a drip pan opposite the coals. Set the lamb over the drip pan, cover the grill and cook until glazed and an instant-read thermometer registers 140 for medium, about 2 hours.'),
('16071', '7', 'Line a platter with the onions and sprinkle with the cilantro.'),
('16071', '8', 'Place the leg of lamb on top, brush it with the melted butter and let rest for 15 minutes. Carve the lamb into slices and serve with the lemon wedges.'),
('16072', '1', 'Heat 2 Tbsp. olive oil in a large skillet over medium-high heat.'),
('16072', '2', 'Add mushrooms and cook for 5 minutes.'),
('16072', '3', 'Remove from skillet; set aside.'),
('16072', '4', 'Season lamb chops with 1 tsp. salt and pepper.'),
('16072', '5', 'Heat remaining 1 Tbsp. oil in skillet.'),
('16072', '6', 'Add lamb chops, in batches if necessary, and cook over medium-high heat, turning once, until medium-rare, 6 to 8 minutes.'),
('16072', '7', 'Transfer to a platter; cover with foil to keep warm.'),
('16072', '8', 'Remove all but 1 Tbsp. fat from skillet.'),
('16072', '9', 'Add shallot and cook for 2 minutes.'),
('16072', '10', 'Pour in wine, scraping bottom of pan. Bring to a boil, lower heat and reduce liquid for 5 minutes.'),
('16072', '11', 'Add broth; cook for 10 minutes.'),
('16072', '12', 'In a medium saucepan, bring chicken broth and 1 tsp. salt to a boil. Gradually pour in polenta, whisking. Reduce heat and cook, stirring, for 5 minutes. Stir in butter. Cover and set aside.'),
('16072', '13', 'Add chops and mushrooms to red wine sauce and warm through.'),
('16072', '14', 'Serve with polenta.'),
('16073', '1', 'In a medium saucepan, bring chicken broth to a boil. Stir in rice and return to a boil, then reduce heat. Cover and simmer until rice has absorbed all liquid, about 20 minutes.'),
('16073', '2', 'Preheat broiler. In a bowl, combine olive oil, garlic, cumin, coriander, fennel and salt.'),
('16073', '3', 'Place all four lamb chops in a resealable plastic bag and pour wet rub over them. Seal bag and rub chops so that marinade fully covers them.'),
('16073', '4', 'Let them sit for about 5 minutes.'),
('16073', '5', 'Place lamb chops on a broiler pan or a foilcovered baking sheet. Broil 4 inches from heat for about 4 minutes per side for medium rare.'),
('16073', '6', 'Remove chops from oven and set aside to rest for 7 to 10 minutes.'),
('16073', '7', 'Serve warm with rice.'),
('16074', '1', 'Combine lamb, garlic, ginger, cinnamon, nutmeg and 1 tsp. salt in a large bowl. Cover and refrigerate for at least 1 hour, or up to'),
('16074', '2', 'Place lamb in a slow cooker; add carrots and 2 cups chicken broth. Cover and cook on low until lamb is fork-tender, about 6 hours.'),
('16074', '3', 'In a large saucepan, bring remaining 2 cups broth and 1/2 tsp. salt to boil.'),
('16074', '4', 'Add couscous, stir, cover and remove from heat.'),
('16074', '5', 'Let stand 5 minutes, fluff with a fork, and transfer to a large serving bowl. Spoon lamb and skimmed juices over couscous and sprinkle with parsley.'),
('16074', '6', 'Serve immediately.'),
('16075', '1', 'In a small pot over low heat, combine the honey and thyme and bring to a slow simmer. Cook the honey low and slow.'),
('16075', '2', 'Keep at a low simmer for 30 minutes then strain and season with salt, and pepper. Keep warm.'),
('16075', '3', 'Meanwhile, preheat a grill or grill pan over high heat. Preheat the oven to 400 degrees F.'),
('16075', '4', 'Combine the garlic powder, fines herb, and parsley in a bowl and mix to combine. Season the lamb with salt and pepper. Rub the outside of the lamb with the spices and place over a very hot grill, fat side down.'),
('16075', '5', 'Let the lamb sit for just 1 minute or until the fat chars a bit, turn and cook the other side for 2 minutes.'),
('16075', '6', 'Transfer the lamb to a baking sheet and finish in the oven for about 10 minutes.'),
('16075', '7', 'Remove the lamb from the oven and let rest for 5 minutes before slicing the chops.'),
('16077', '1', 'Heat a large Dutch oven over medium-high heat.'),
('16077', '2', 'Add 2 teaspoons oil to pan; swirl to coat.'),
('16077', '3', 'Add onion, thyme, and rosemary; saut for 5 minutes, stirring occasionally.'),
('16077', '4', 'Place onion mixture in a large bowl.'),
('16077', '5', 'Place flour in a shallow dish. Sprinkle lamb evenly with 1/2 teaspoon salt and 1/2 teaspoon pepper. Dredge lamb in flour, and shake off excess. Return pan to medium-high heat.'),
('16077', '6', 'Add 1 tablespoon oil to pan; swirl to coat.'),
('16077', '7', 'Add half of lamb mixture to pan; saut for 6 minutes, turning to brown on all sides.'),
('16077', '8', 'Add browned lamb to onion mixture. Repeat the procedure with remaining lamb and remaining 1 tablespoon oil.'),
('16077', '9', 'Add beer to pan; bring to a boil, scraping pan to loosen browned bits. Cook until reduced to 1 cup (about 5 minutes). Return onion mixture and lamb to pan. Stir in the tomato paste; cook 30 seconds.'),
('16077', '10', 'Add broth and bay leaf; bring to a boil. Cover, reduce heat, and simmer for 1 hour and 15 minutes, stirring occasionally. Uncover and stir in potato, carrot, and turnips. Simmer, uncovered, for 1 1/2 hours or until meat and vegetables are tender. Stir in remaining 1/2 teaspoon salt, the remaining 1/4 teaspoon pepper, and 1 tablespoon mustard. Ladle about 1 cup stew into each of 7 bowls; sprinkle evenly with parsley.'),
('16078', '1', 'Watch how to make this recipe.'),
('16078', '2', 'Heat olive oil in a pan over medium-high heat; add the sliced garlic and cook until it just begins to turn brown.'),
('16078', '3', 'Add the rosemary and continue cooking until rosemary is crispy and garlic is nicely brown.'),
('16078', '4', 'Let cool and stir in lemon zest.'),
('16078', '5', 'Prepare a hot grill.'),
('16078', '6', 'Season lamb chops with salt and pepper.'),
('16078', '7', 'Brush with oil of the marinade and grill to desired doneness; medium-rare is recommended. Arrange on a platter and spoon solids of rosemary mixture on top and serve.'),
('16079', '1', 'Place lamb in a bowl; toss with flour, 1/2 tsp. salt and pepper.'),
('16079', '2', 'Melt butter in a large skillet over medium-high heat.'),
('16079', '3', 'Add half of lamb and cook until browned, about 7 minutes.'),
('16079', '4', 'Transfer to a slow cooker. Repeat with remaining lamb.'),
('16079', '5', 'Pour broth into skillet, add remaining 3/4 tsp. salt and scrape pan with a wooden spoon.'),
('16079', '6', 'Add liquid, spices, onion, apricots, raisins, carrots and parsnips to slow cooker. Cover and cook over low heat until lamb is tender, about 5 1/2 hours.'),
('16080', '1', 'Combine red wine, oil, sea salt, pepper and oregano and rub all over leg of lamb.'),
('16080', '2', 'Combine peppers with cheeses and pine nuts. Lay lamb fat side down and spread the filling across the meat, leaving the edges clean.'),
('16080', '3', 'Roll into a jelly roll and tie with kitchen twine. Make a bed of chopped vegetables in a large roasting pan and set the lamb on top of the vegetables (or on a wire rack above the pan), fat side up.Roast at 450 degrees for 20 minutes. Reduce heat to 350 degrees and continue to roast until the temperature reaches 130 degrees, about 1 to 2 hours depending on size of the roast.'),
('16080', '4', 'Let meat rest before slicing.'),
('16080', '5', 'Serve with mint leaves for garnish.'),
('16086', '1', 'In a small skillet, toast the saffron over moderately high heat until fragrant, about 10 seconds.'),
('16086', '2', 'Transfer to a small bowl and let cool. Crumble the saffron threads and cover with 2 tablespoons of water.'),
('16086', '3', 'In a large enameled cast-iron casserole, melt 3 tablespoons of the butter.'),
('16086', '4', 'Add the lamb, onions, cinnamon sticks, ginger, pepper, turmeric and 2 teaspoons of salt. Cook over moderate heat, stirring a few times, until fragrant, 5 minutes.'),
('16086', '5', 'Add the cilantro, the saffron water and 2 cups of fresh water to the casserole and bring to a simmer. Cover with a round of parchment paper and a lid; simmer, turning the lamb once, until tender, 1 hour.'),
('16086', '6', 'Transfer the lamb and all but 1/2 cup of the cooking liquid to a bowl. Discard the cilantro and cinnamon sticks.'),
('16086', '7', 'Add the remaining 2 tablespoons of butter to the casserole; cook over moderate heat, stirring a few times, until the liquid has evaporated, about 15 minutes. Return the lamb and cooking liquid to the casserole and season with salt. Cover and let stand.'),
