INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('26481', '4', 'Remove.  If either looks like it is going to turn black then immediately remove.'),
('26481', '5', 'Toss the pumpkin and sesame seeds in a food processor and blend until they become a fine dust.  Set aside.'),
('26481', '6', 'Remove the skin from the chicken pieces.  Season with salt and set in a large pot.'),
('26481', '7', 'Pour in the chicken stock and bring to a simmer.  Cook for 20 minutes.'),
('26481', '8', 'Remove the chicken.'),
('26481', '9', 'Add the onion, garlic, habanero, tomatillos, and half of the pistachios.  Cook at a simmer for 10 minutes.  Toss out the habanero.'),
('26481', '10', 'Using a slotted spoon, remove the vegetables and toss them in a blender.  Keep the stock.'),
('26481', '11', 'Add about 1 cup of the stock and blend until very smooth.'),
('26481', '12', 'Add more stock if it''s too dry.'),
('26481', '13', 'Pour the sauce into a large skillet, turn the heat to medium-low, and slowly whisk in the ground pumpkin and sesame seeds.  It should thicken the sauce up, but if it gets too dry add some more of the stock.'),
('26481', '14', 'Add the chicken to the skillet and let them warm back up.'),
('26481', '15', 'Serve the chicken with the sauce on top.  Sprinkle with the rest of the pistachios.'),
('26489', '1', 'Preheat oven to 37'),
('26489', '2', 'To prepare sauce, discard husks and stems from tomatillos. Bring 2 quarts water to a boil in a large Dutch oven.'),
('26489', '3', 'Add tomatillos. cook 2 minutes.'),
('26489', '4', 'Drain.'),
('26489', '5', 'Place tomatillos, avocado, and next 5 ingredients (avocado through garlic) in a blender. process until smooth. Strain mixture through a sieve into a medium bowl. discard solids.'),
('26489', '6', 'To prepare enchiladas, combine the cheese, 1/4 teaspoon salt, and crab. Warm tortillas according to package directions. Spoon about 1/2 cup crab mixture down center of each tortilla. roll up.'),
('26489', '7', 'Place, seam-side down, in an 11 x 7-inch baking dish coated with cooking spray. Cover and bake at 375 for 12 minutes or until thoroughly heated.'),
('26489', '8', 'To prepare topping, combine lettuce and remaining ingredients.'),
('26489', '9', 'Serve enchiladas with sauce and topping.'),
('26490', '1', 'Watch how to make this recipe.'),
('26490', '2', 'Preheat the oven to 400 degrees F.'),
('26490', '3', 'In a large bowl, toss the onions, tomatillos, jalapenos, and garlic with 1 tablespoon of the olive oil and spread on a baking sheet. Roast until soft and starting to brown, about 20 to 30 minutes, stirring twice during roasting.'),
('26490', '4', 'Meanwhile, in a large Dutch oven over medium-high heat, add the oil and heat. Brown the pork, in batches, until well-browned. When browned, add all of the pork back to the pan and cover with chicken stock.'),
('26490', '5', 'Add the roasted vegetables, cover the pan and place in the oven. Cook until the pork is very tender, about 1 1/2 hours.'),
('26490', '6', 'While pork is cooking, place the cilantro in a food processor.'),
('26490', '7', 'Add 2 tablespoons of water and puree.'),
('26490', '8', 'Remove the pork from the oven and stir in the cilantro puree. Season, to taste, with salt and pepper.'),
('26490', '9', 'Serve with warm flour tortillas.'),
('26491', '1', 'Put them in a bowl and pour over enough cold water to cover them completely. Soak until pliable but not completely softened, about 20 minutes.'),
('26491', '2', 'Drain.'),
('26491', '3', 'Combine the drained chiles, garlic, and one-third of the cooled tomatillos in a blender jar and blend until smooth.'),
('26491', '4', 'Add the remaining tomatillos and blend, using quick on/off pulses, just until smooth. dont overblend.'),
('26491', '5', 'Pour into a bowl and season with salt. The salsa can be kept at room temperature for up to 4 hours or refrigerated for up to 12 hours before serving.'),
('26491', '6', 'Before roasting, remove the husks and wash thhe tomatillos thorougly to remove all traces of stickiness. Leave the cores intact.'),
('26491', '7', 'var article'),
('26491', '8', 'Type_27_data = {}.'),
('26491', '9', 'article'),
('26491', '10', 'Type_27_data.init_step_by_step_images = 0.'),
('26497', '1', 'Ingredients:for the sauce:2 lb bulk Italian sausage (casing removed if necessary)1 large onion, diced3 cloves garlic, minced1 cubanelle pepper, minced56 oz canned coarse ground tomatoes14 oz canned diced tomatoes6 oz tomato paste1 teaspoon balsamic vinegarred wine (optional)10 basil leavessaltpepperfor the pasta:1 1/2 cup flour1/2 cup finely minced basil3 eggsfor the filling:1 lb ricotta1/2 lb frozen chopped spinach, defrosted and squeezed dry1 1/2 cup mixed Italian cheese*1 eggsaltpepperextra shredded cheese for sprinkling'),
('26497', '2', 'Start the sauce first. Brown the sausage in a large, heavy pot (I used this dutch oven) breaking up any large pieces. When nearly fully cooked, drain off as much fat as possible.'),
('26497', '3', 'Add the onion, garlic and pepper. Cook until the onion is translucent.'),
('26497', '4', 'Add the tomatoes, tomato paste, balsamic, salt and pepper. Simmer as you make the pasta. It should reduce by about an inch and half or so.'),
('26497', '5', 'Add wine if desired periodically. Stir occasionally. When the sauce is cooked, stir in the basil leaves.for the pasta:While the sauce is bubbling away, pour the flour onto a clean counter top. Create a well on top and add the eggs. Knead together until a ball forms then work in the basil. Knead until a flexible dough forms. Divide into 9 equal balls.'),
('26498', '1', 'In a large nonreactive baking dish, mix 1/4 cup plus 2 tablespoons of the canola oil with 3 tablespoons of the lime juice, the garlic, jalapeo and 1 teaspoon of salt.'),
('26498', '2', 'Add the chicken, turn to coat and let stand at room temperature for 1 hour or refrigerate for up to 4 hours.'),
('26498', '3', 'Roast the red and green peppers under the broiler or directly over a gas flame, turning occasionally, until charred all over, about 10 minutes.'),
('26498', '4', 'Transfer to a bowl, cover with plastic wrap and let steam for 10 minutes. Peel the peppers, discard the stems and seeds, then dice.'),
('26498', '5', 'Meanwhile, in a medium skillet, heat 1/4 cup of the oil until shimmering.'),
('26498', '6', 'Add the tortilla strips and fry over high heat, turning frequently, until golden, about 2 minutes.'),
('26498', '7', 'Drain on paper towels and sprinkle with salt.'),
('26498', '8', 'In a blender, combine the remaining 3/4 cup of oil with the cilantro, sugar, vinegar and the remaining 1/4 cup of lime juice and puree until smooth. Season the vinaigrette with salt and pepper.'),
('26498', '9', 'Heat a large cast-iron grill pan and lightly rub it with oil.'),
('26498', '10', 'Remove the chicken from the marinade and scrape off any garlic and jalapeo bits. Grill the chicken over moderate heat, turning occasionally, until browned and cooked through, 10 to 12 minutes.'),
('26498', '11', 'Transfer to a work surface and let stand for 10 minutes, then cut into 3/4-inch dice.'),
('26498', '12', 'In a large bowl, combine the roasted peppers with the tomatoes, avocados, onion, jicama, tomatillos and chicken.'),
('26498', '13', 'Add the vinaigrette and toss gently to coat. season with salt and pepper.'),
('26498', '14', 'Transfer the salad to a large platter, scatter the fried tortilla strips on top and serve.'),
('26499', '1', 'Watch how to make this recipe.'),
('26499', '2', 'Fill a medium saucepan with 2 quarts cold water.'),
('26499', '3', 'Add the salt, coriander, peppercorns and lemon wedges, squeezing the juice into the pot first, and bring to a boil.'),
('26499', '4', 'Let boil for 5 minutes. Reduce the heat to a simmer, add the shrimp, and simmer for about 4 minutes, or until just cooked through.'),
('26499', '5', 'Drain the shrimp in a colander, transfer to a bowl, cover and let chill in the refrigerator for at least 1 hour.'),
('26499', '6', 'When shrimp is chilled, serve with dipping sauce.'),
('26499', '7', 'Preheat oven to 400 degrees F.'),
('26499', '8', 'Place tomatillos, onion, garlic, and jalapeno on a half-sheet pan, toss with the oil, and season with salt and pepper. Cook until the mixture is soft, but do not allow it to color, about 15 to 20 minutes.'),
('26499', '9', 'Transfer to a food processor and process until smooth.'),
('26499', '10', 'Add the vinegar, honey, horseradish, and cilantro and pulse just to combine. Season with salt and pepper.'),
('26499', '11', 'Scrape into a bowl, cover, and refrigerate for at least 1 hour before serving.'),
('26500', '1', 'Preheat oven to 35'),
('26500', '2', 'To prepare salsa, bring water to a boil.'),
('26500', '3', 'Add tomatillos, garlic, and chile. cook 7 minutes.'),
('26500', '4', 'Drain and rinse with cold water.'),
('26500', '5', 'Combine tomatillos, garlic, chile, chopped cilantro, onion, lime juice, and 1/4 teaspoon salt in a food processor or blender. pulse 4 to 5 times or until coarsely chopped. Set aside.'),
('26500', '6', 'To prepare chicken, place bread in a food processor, and pulse 10 times or until coarse crumbs measure 1 1/2 cups. Arrange crumbs on a baking sheet. bake at 350 for 3 minutes or until lightly browned. Cool completely.'),
('26500', '7', 'Place each chicken breast half between 2 sheets of heavy-duty plastic wrap. pound to 1/2-inch thickness using a meat mallet or rolling pin.'),
('26500', '8', 'Combine 1/2 teaspoon salt, cumin, and red pepper. sprinkle evenly over chicken.'),
('26500', '9', 'Place breadcrumbs in a shallow dish.'),
('26500', '10', 'Place egg in another shallow dish. Dip chicken in egg. dredge in breadcrumbs.'),
('26500', '11', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('26500', '12', 'Add chicken. cook 4 minutes on each side or until done. Top chicken with salsa, and sprinkle with queso fresco cheese.'),
('26500', '13', 'Garnish with cilantro sprigs and lime wedges, if desired.'),
('26502', '1', 'Arrange the tomatillos and green chiles under a very hot broiler and cook, turning occasionally, until roasted and blackened in spots, about 10-12 minutes.'),
('26502', '2', 'Transfer everything to a blender and blend into a smooth puree.'),
('26502', '3', 'In a large pot or dutch oven, heat the oil over medium and cook the onion until golden, about 7 minutes.'),
('26502', '4', 'Add the garlic and cook an additional minute, then pour in the tomatillo puree.  Bring to a boil, then stir in the broth and crema.  Season to taste with salt, then add the cilantro or epazote and bring back to a boil. Turn off the heat.'),
('26502', '5', 'In the meantime, preheat the oven to 400F. Arrange the chips on a 13x9 baking dish, then pour the sauce over them, pressing the chips gently to ensure they are covered in sauce. Sprinkle the cheese over the top and bake until bubbling and slightly brown on the edges, about 15 minutes.'),
('26502', '6', 'Serve immediately before the chips go soggy.'),
('26503', '1', 'To prepare salsa, combine first 6 ingredients. cover and refrigerate.'),
('26503', '2', 'To prepare burgers, combine 1 1/2 cups water and lentils in a saucepan. bring to a boil. Cover, reduce heat, and simmer 25 minutes or until lentils are tender.'),
('26503', '3', 'Drain.'),
('26503', '4', 'Place half of lentils in a large bowl.'),
('26503', '5', 'Place remaining lentils in a food processor. process until smooth.'),
('26503', '6', 'Add processed lentils to whole lentils in bowl.'),
('26503', '7', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('26503', '8', 'Add onion and carrot. saut 6 minutes or until tender, stirring occasionally.'),
('26503', '9', 'Add garlic. cook 1 minute, stirring constantly.'),
('26503', '10', 'Add tomato paste, cumin, oregano, chili powder, and 1/4 teaspoon salt. cook 1 minute, stirring constantly.'),
('26503', '11', 'Add onion mixture to lentils.'),
('26503', '12', 'Add remaining 1/2 teaspoon salt, barley, and next 5 ingredients (through egg). stir well. Cover and refrigerate 1 hour or until firm.'),
('26503', '13', 'Divide mixture into 8 portions, shaping each into a 1/2-inch-thick patty.'),
('26503', '14', 'Heat 1 1/2 tablespoons oil in a large nonstick skillet over medium-high heat.'),
('26503', '15', 'Add 4 patties. cook 3 minutes on each side or until browned. Repeat procedure with remaining 1 1/2 tablespoons oil and 4 patties.'),
('26503', '16', 'Serve with salsa.'),
('26505', '1', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('26505', '2', 'Add ground pork to pan. cook 5 minutes or until browned, stirring to slightly crumble.'),
('26505', '3', 'Drain well.'),
('26505', '4', 'Transfer pork to an electric slow cooker.'),
('26505', '5', 'Recoat pan with cooking spray.'),
('26505', '6', 'Add pork shoulder. cook 5 minutes or until lightly browned, turning occasionally.'),
('26505', '7', 'Transfer pork to slow cooker.'),
('26505', '8', 'Recoat pan with cooking spray.'),
('26505', '9', 'Add onion and bell pepper. saut 8 minutes, stirring frequently.'),
('26505', '10', 'Add garlic. saut 1 minute.'),
('26505', '11', 'Add tomato paste. cook 1 minute, stirring constantly. Stir in beer. cook 1 minute.'),
('26505', '12', 'Transfer onion mixture to slow cooker.'),
('26505', '13', 'Add chili powder, and next 9 ingredients (through ham hock) to slow cooker. Cover and cook on HIGH 5 hours or until meat is tender.'),
('26505', '14', 'Remove bay leaves and ham hock. discard. Stir in sugar. Ladle about 1 1/3 cups chili into each of 8 bowls. top each serving with 1 tablespoon cilantro, 1 tablespoon green onions, and 1 tablespoon cheese.'),
('26505', '15', 'Serve each serving with 1 lime wedge.'),
('26505', '16', 'Note: You can also cook the chili in a slow cooker on LOW for 8 hours. For cooking chili on the stovetop, use a total of 12 ounces beer and simmer, covered, for 2 1/2 to 3 hours or until the pork shoulder is tender.'),
('26506', '1', 'Preheat broiler to high.'),
('26506', '2', 'Halve, stem, and seed chiles.'),
('26506', '3', 'Place chiles, skin side up, on a foil-lined baking sheet coated with cooking spray. broil for 5 minutes or until charred.'),
('26506', '4', 'Place chiles in a paper bag. seal.'),
('26506', '5', 'Let stand for 15 minutes. Peel and discard skins. Arrange tomatillos on prepared baking sheet, and broil 14 minutes or until blackened, turning once.'),
('26506', '6', 'Combine the chiles, tomatillos, 1/4 cup cilantro, cumin, and oregano in a blender.'),
('26506', '7', 'Add 1 cup broth. process until smooth.'),
('26506', '8', 'Heat a large Dutch oven over medium-high heat.'),
('26506', '9', 'Add 2 teaspoons olive oil. swirl to coat.'),
('26506', '10', 'Add onion, carrot, celery, and bell pepper. saut for 2 minutes, stirring occasionally. Stir in flour. saut for 2 minutes, stirring frequently.'),
('26506', '11', 'Add garlic. saut for 30 seconds, stirring constantly.'),
('26506', '12', 'Place onion mixture in a large bowl.'),
('26506', '13', 'Sprinkle chicken with 1/2 teaspoon salt and 1/4 teaspoon black pepper.'),
('26506', '14', 'Add 2 teaspoons oil to pan. swirl to coat.'),
('26506', '15', 'Add half of chicken. saut 3 minutes.'),
('26506', '16', 'Add browned chicken to onion mixture. Repeat procedure with remaining chicken and 2 teaspoons oil.'),
('26506', '17', 'Combine remaining 1 cup broth, tomatillo mixture, onion mixture, and hominy in pan over medium-high heat, and bring to a boil. Cover, reduce heat, and simmer for 45 minutes, stirring occasionally. Stir in 1/2 teaspoon salt and 1/4 teaspoon black pepper. Ladle 1 2/3 cups stew into each of 6 bowls, and top each with 1 tablespoon sour cream.'),
('26506', '18', 'Garnish with cilantro, if desired.'),
('26509', '1', 'Place a large skillet over medium-high heat. Toss the onion halves, garlic, tomatillos, and jalapenos with 1/2 cup of the oil.'),
('26509', '2', 'Add about half of this mixture, or as many that will fit in one layer, to the skillet. Cook, turning occasionally until slightly blackened on all sides.  Repeat with the other half. Toss the cooked ones in a large bowl except the jalapeno, which needs to have its stem and seeds removed. Then add it to the bowl.'),
('26509', '3', 'After they cool for a little bit, blend everything up in batches.'),
('26509', '4', 'Transfer the pureed sauce to a large bowl and set aside.'),
('26509', '5', 'Preheat the broiler. Coat the poblano in 2 tablespoons of the oil and then set underneath the broiler. Cook, turning occasionally, until blackened on all sides.'),
('26509', '6', 'Transfer to a plastic bag and let steam for 15 minutes. Then remove the blackened skin, stem, and seeds. Roughly chop the flesh.'),
('26509', '7', 'Add the poblano, pumpkin seeds, cilantro, epazote, and 2 cups of the broth to the blender and puree until smooth.'),
('26509', '8', 'Combine with the tomatillo sauce.'),
('26509', '9', 'Add the lard to a large pot or dutch oven set over medium heat. Carefully pour in the chile mixture (it might splatter). Cook for 5 minutes, stirring occasionally.'),
('26509', '10', 'Pour in the remaining stock and 1 tablespoon salt. Cook for 10 minutes.'),
('26516', '1', 'Brown sausage in a large skillet over medium-high heat, stirring occasionally, 11 to 14 minutes or until meat crumbles and is no longer pink.'),
('26516', '2', 'Remove sausage from skillet using a slotted spoon, and drain on paper towels.'),
('26516', '3', 'Saut onion and garlic in hot drippings over medium-high heat 2 to 3 minutes or until onion is tender.'),
('26516', '4', 'Remove from heat. Stir in sausage, 1/2 cup tomatillo salsa, and 1/4 cup chopped cilantro.'),
('26516', '5', 'Place 2 tortillas between damp paper towels. Microwave tortillas at HIGH 15 seconds. Repeat procedure with remaining tortillas.'),
('26516', '6', 'Spoon about 1/3 cup sausage mixture evenly down center of each softened tortilla, and sprinkle each with 1 Tbsp. cheese. roll tortillas up, and place, seam sides down, in a lightly greased 13- x 9-inch baking dish. Lightly coat tops of tortillas with cooking spray.'),
('26516', '7', 'Bake at 350 for 20 to 25 minutes or until tortillas are crisp.'),
('26516', '8', 'Stir together 2 cups tomato salsa, 1/2 cup chicken broth, and remaining tomatillo salsa in a medium saucepan over medium-high heat. cook, stirring occasionally, 4 to 6 minutes or until thoroughly heated.'),
('26516', '9', 'Pour salsa mixture over tortillas, and top evenly with remaining cheese.'),
('26516', '10', 'Bake 5 more minutes or until cheese is melted.'),
('26516', '11', 'Let stand 5 minutes.'),
('26516', '12', 'Garnish, if desired.'),
('26516', '13', '*Ground pork sausage may be substituted.'),
('26516', '14', '**8 (6-inch) fajita-size flour tortillas may be substituted, omitting Step'),
('26516', '15', 'Note: For testing purposes only, we used La Costea Green Mexican Salsa for tomatillo salsa.'),
('26518', '1', 'Preheat oven to 40'),
('26518', '2', 'Coat both sides of tortillas with cooking spray. place over 1-quart glass mixing bowls or 10-ounce pyrex bowls on baking sheets. Gently press tortillas around bowls.'),
('26518', '3', 'Bake at 400 for 5 minutes or just until lightly browned. Cool 5 minutes on bowls. remove from bowls and cool completely.'),
('26518', '4', 'Place 1 1/2 cups lettuce in each tortilla bowl.'),
('26518', '5', 'Combine chicken, taco sauce, and 1/2 teaspoon chipotle chile in a small bowl. Spoon mixture evenly into each tortilla bowl.'),
('26518', '6', 'Combine black beans, corn, chili powder, and garlic in a small bowl. Spoon evenly into each tortilla bowl.'),
('26518', '7', 'Combine tomato, tomatillos, and cilantro in a small bowl. Spoon evenly into each tortilla bowl. Sprinkle salads evenly with cheese and green onions.'),
('26518', '8', 'Combine ranch dressing and 1 tablespoon chipotle chile. drizzle over salads.'),
('26520', '1', 'Watch how to make this recipe.'),
('26520', '2', 'Special equipment: 4 individual casserole dishes'),
('26521', '1', 'Preheat broiler with oven rack 3 in. from heat. Set yellow onion, poblanos, serrano, tomatillos, and garlic on a rimmed baking sheet. Broil, turning, until vegetables are browned to blackened all over, 15 to 30 minutes, moving them to a bowl as browned.'),
('26521', '2', 'Let cool.'),
('26521', '3', 'Toast ancho chiles in a large pot over medium heat until fragrant, pressing down with tongs and turning occasionally, about 3 minutes. Turn off heat.'),
('26521', '4', 'Peel and seed poblanos and serrano. Peel garlic. Whirl serrano, garlic, onion, tomatillos and any juices, and 1/2 cup pumpkin seeds in a food processor until very smooth.'),
('26521', '5', 'Pour into pot with whole anchos (they''ll fall apart as they cook). Coarsely chop poblanos and add to pot.'),
('26521', '6', 'Stir in hominy, 5 cups broth, 2 tsp. oregano, and the cumin. Cover, bring to a boil over high heat, then reduce heat and simmer, stirring occasionally, until cumin flavor is mellow, about 45 minutes. Discard any large pieces of ancho chile.'),
('26521', '7', 'Stir zucchini into posole and simmer just until tender, about 5 minutes. Stir in more broth if you''d like a thinner soup.'),
('26521', '8', 'Ladle posole into bowls and serve with remaining pumpkin seeds and oregano and other accompaniments to taste.'),
('26522', '1', 'Remove silver skin from tenderloin, leaving a thin layer of fat covering tenderloin.'),
('26522', '2', 'Cut tenderloin into 1-inch-thick medallions.'),
('26522', '3', 'Combine blue-corn tortilla chips and next 5 ingredients in a bowl.'),
('26522', '4', 'Brush pork medallions with 1 1/2 Tbsp. olive oil, and dredge in tortilla chip mixture, pressing mixture into medallions on all sides to thoroughly coat.'),
('26522', '5', 'Cook pork medallions in remaining 1 1/2 Tbsp. hot oil in a large skillet over medium heat 6 minutes on each side or until done.'),
('26522', '6', 'Serve with salsas.'),
('26522', '7', 'Garnish, if desired.'),
('26530', '1', 'Heat oven to 500 degrees F.'),
('26530', '2', 'Heat a grill pan to high.'),
('26530', '3', 'Cut potatoes into Texas fries, 10 per potato. Coat in extra-virgin olive oil, about 2 to 3 tablespoons, then season with chipotle powder, salt and pepper and roast 25 minutes, turning once.'),
('26530', '4', 'Toast pumpkin seeds in a small skillet 2 minutes then grind in food processor or spice mill or a coffee bean grinder.'),
('26530', '5', 'Mix the ground pumpkin seeds with cumin and coriander. Season the tenderloin with salt and pepper and rub with the spices. Rub the grill pan with extra-virgin olive oil and grill pork tenderloins 20 minutes.'),
('26530', '6', 'Heat a skillet over medium-high heat with a tablespoon extra-virgin olive oil, a turn of the pan.'),
('26530', '7', 'Add the chopped onion, garlic, jalapeno and cook a few minutes while you chop tomatillos.'),
('26530', '8', 'Add the tomatillos, season with salt and pepper and cook 7 to 8 minutes. Stir in lime zest and juice and cilantro and remove from heat.'),
('26530', '9', 'While salsa is cooking, toss the cabbage with sliced onion.'),
('26530', '10', 'Wrap the tortillas in damp clean towel and warm in microwave 2 minutes or put in the oven after you remove potatoes for 1 to 2 minutes.'),
('26530', '11', 'Thinly slice pork and serve 1/2 tenderloin per person. Wrap pork slices in soft tacos with salsa and some shredded cabbage and red onions.'),
('26530', '12', 'Serve with Texas chipotle fries.'),
('26532', '1', 'Heat the broiler to high.'),
('26532', '2', 'Place the poblanos under hot broiler and char until blackened an all sides, 10 to 12 minutes. Leave the door of the oven cracked to allow the steam to escape.'),
('26532', '3', 'Place the peppers in a bowl and cover tightly with plastic wrap. Allow the peppers to cool enough to handle.'),
('26532', '4', 'While peppers char, heat extra-virgin olive oil in a high sided skillet over medium-high heat.'),
('26532', '5', 'Add chicken and lightly brown, 3 to 4 minutes. Stir in onions, jalapeno and garlic and cook to soften onions about 5 minutes. While onions cook, place tomatillos and cilantro in the food processor and process until smooth.'),
('26532', '6', 'Pour the tomatillos into the chicken mixture and stir to combine. Stir in chicken stock and honey, season with salt and pepper and simmer chili 10 minutes.'),
('26532', '7', 'When poblano peppers are cool enough to handle, remove seeds and chop, stir into chili.'),
('26532', '8', 'Remove chili pan from heat and stir in lime juice.'),
('26532', '9', 'Add dollops of creme fraiche on top of the chili, placing spoonfuls evenly across the pan. Cover the pan with a layer of crushed chips and top with Swiss and Monterey Jack cheeses.'),
('26532', '10', 'Place under broiler until brown and bubbly.'),
('26532', '11', 'Serve from hot skillet, spooning out chili into shallow dinner bowls. TOUCHDOWN!'),
('26544', '1', 'Put the pork in the freezer until its firm enough to cut (about 30 minutes).'),
('26544', '2', 'Remove the seeds and stems from the chilies and put them in a bowl. Boil some water and pour it onto the chilies and allow them to rehydrate (about 10 minutes).'),
('26544', '3', 'Put the chilies in a food processor along with all the other marinade ingredients and process until smooth.'),
('26544', '4', 'Add the marinade to a pot and bring to a boil for 5 minutes. This destroys some of the enzymes in fresh pineapple that can turn your meat into mush. Turn off the heat then let the marinade cool to room temperature.Take the roast out of the freezer and orient the roast how you''d have it sitting in the roasting pan (fat side up). The idea here is that you want to slice the meat into 1/2" thick slices that will stack on top of each other in the roasting pan. I don''t slice all the way through which helps when you''re trying to put the roast back together.Slather the marinade between each layer until every nook and cranny is covered. Tie the roast back together. Cover it and allow it to marinade for no more than an hour. Fresh pineapple has a powerful enzyme that breaks down proteins and while heating it destroys some of the enzymes, it''s still a powerful meat tenderizer. If you''re using canned pineapple let it marinate overnight as most of the enzyme is destroyed in the canning process.When the roast is ready to go in the oven, set the oven to 450 degrees F.'),
('26544', '5', 'Put the roast on a rack in a roasting pan and add water to the bottom of the pan (this is to keep the drippings from smoking). Roast for 30 minutes at this temperature then place the pineapple slices on top of the roast and turn down the heat to 300 degrees F. Roast until the meat is tender (about 3 hours).After removing the meat from the oven, cover it with foil and let it rest for about 20 minutes. When you''re ready to serve, just cut the meat up into small cubes. I like to pan fry it at this point to give the pieces a bit more caramelization but it''s up to you.To assemble the tacos just heat up a pile of tortilla''s in the microwave covered with a damp paper towel for about 30 seconds. Using 2 tortilla''s per taco, fill with meat, then top with minced onions, cilantro and salsa verde.'),
('26544', '6', 'Serve with a wedge of lime for squeezing.For Salsa Verde'),
('26544', '7', 'Move your oven rack to the top position and lay down a piece of foil. Score the bottoms of the tomatillos (so they don''t explode) then place them on the foil.'),
('26544', '8', 'Place the jalepenos skin side up around the tomatillos along with the onions and garlic. Turn the broiler on and allow everything to get a nice bubbly char going on. Using tongs, flip things over and then char the other side. The smaller items like onion and garlic may need to come out first.Flake off any excess char (you want to keep some of it) then toss everything in a food processor along with the cilantro and salt and pepper. Process until smooth.'),
('26545', '1', 'In a small bowl, combine the paprika, chili powder, cayenne, cumin, sugar, and 1/4 teaspoon of the salt.'),
('26545', '2', 'In a large saucepan, heat 2 tablespoons of the oil over moderately low heat.'),
('26545', '3', 'Add the flour and cook, whisking, until golden, about 3 minutes.'),
('26545', '4', 'Add the garlic. cook for 30 seconds.'),
('26545', '5', 'Add the paprika and chili powder mixture and then add the broth slowly, whisking, until smooth. Bring to a simmer. Simmer, covered, until thick enough to coat a spoon, about 25 minutes.'),
('26545', '6', 'Meanwhile, in a large frying pan, heat the remaining 1 tablespoon oil over moderate heat. Season the chicken with the remaining 1/4 teaspoon salt and the pepper and cook until browned and just done, about 5 minutes per side.'),
('26545', '7', 'Remove the chicken from the pan and let it rest for 5 minutes.'),
('26545', '8', 'Cut crosswise into slices.'),
('26545', '9', 'Add the tortilla chips to the chile sauce and cook, stirring, until the chips are soft but not falling apart, about 2 minutes.'),
('26545', '10', 'Put the sauce on plates and top with the feta, sour cream, onion, cilantro, and chicken.'),
('26545', '11', 'Wine Recommendation: These forceful, varied flavors need a gutsy wine, and zinfandel will more than hold its own. Look for old-vine cuves from Sonoma''s Dry Creek or Russian River valleys.'),
('26546', '1', 'Combine tomatillo salsa, chopped avocado, and cilantro. set aside.'),
('26546', '2', 'Place bread in a food processor. pulse 10 times or until crumbs measure 1 cup.'),
('26546', '3', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('26546', '4', 'Add onion and bell peppers. saut 5 minutes or until tender. Stir in 1/2 teaspoon fajita seasoning and 1/8 teaspoon salt. Cool.'),
('26546', '5', 'Combine breadcrumbs, onion mixture, remaining 1 1/2 teaspoons fajita seasoning, remaining 1/8 teaspoon salt, tomato paste, turkey, and egg white in a large bowl. Using damp hands, divide turkey mixture into 4 equal portions, shaping each into a 3/4-inch-thick patty.'),
('26546', '6', 'Heat pan over medium heat. Recoat pan with cooking spray.'),
('26546', '7', 'Add patties. cook 4 minutes on each side or until done.'),
('26546', '8', 'Place 1 patty on bottom half of each bun. Top each serving with 1 1/2 tablespoons salsa mixture. top with remaining halves of buns.'),
('26553', '1', 'Combine all ingredients in a large bowl. Toss gently to mix.'),
('26555', '1', 'Preheat grill or broiler.'),
('26555', '2', 'Combine chili powder and salt. rub over both sides of chicken.'),
('26555', '3', 'Place chicken on a grill rack or broiler pan coated with cooking spray. cook 5 minutes on each side or until done. Cool slightly, and coarsely chop.'),
('26555', '4', 'Preheat oven to 35'),
('26555', '5', 'Place tortillas directly on middle rack in oven.'),
('26555', '6', 'Bake at 350 for 7 minutes (tortillas should be slightly pliable). Mash beans in a microwave-safe bowl to desired consistency. stir in Dried-Chile Pure. Microwave at high 30 seconds or until hot. Divide bean mixture evenly among tortillas. top with chicken. Spoon 2 tablespoons Tomatillo Pure over chicken. sprinkle each with about 1 tablespoon onions.'),
('26558', '1', 'Preheat oven to 375 degrees F. Rub oil on tomatillos, onion and garlic with 3 tablespoons of oil and season with salt and pepper.'),
('26558', '2', 'Place in a roasting pan and roast until soft and golden brown about 20 to 25 minutes.'),
('26558', '3', 'Place tomatillos, onions, garlic, chipotle, lime juice and spinach in a food processor and blend until smooth. With the motor running, slowly add the 3/4 cup olive oil and season with honey and salt and pepper. Keep warm in a bain marie.'),
('26559', '1', 'Set the oven or toaster oven to broil and preheat. Alternatively, you can preheat the oven to 500F. If youre using the oven broiler, position the rack 8 inches from the heat source. Core the tomato and cut a small X through the skin on the opposite end. Roast the tomato, cored side up, and tomatillos on a foil-lined pan, turning the tomatillos over once halfway through, until their tops and bottoms have blackened and they are a khaki-green color and cooked to the core, 20 to 30 minutes. and the tomato (without turning) until its top is blackened and its cooked to the core, 20 to 30 minutes total. Slip the skin off the tomato.Meanwhile, heat a comal, griddle, or heavy skillet over medium-low heat, and roast the onion and garlic on the comal, turning the garlic over occasionally, until it is just tender and golden brown with some blackened spots, 8 to 10 minutes. and carefully turning the onion slice over once, until its softened and charred on both sides, 15 to 20 minutes.'),
('26559', '2', 'Heat 1/2 cup of the oil in a medium heavy skillet over medium heat until it simmers. Fry the chiles, a few of the same variety at a time, turning them over with tongs, until puffed and slightly changed in color, 30 to 45 seconds per batch of mulato and ancho chiles, 45 seconds to 1 minute for pasilla chiles, and about 11/2 minutes for chipotle meco chiles. As the chiles are fried, transfer them to a large bowl. When all the chiles are fried, add enough cold water to cover them and let them soak for 30 minutes. Discard the remaining oil from frying the chiles and set the skillet aside.Using tongs, hold the tortilla directly over a burner set to medium, turning it over frequently, until its dark, golden brown, and some burned spots appear on both sides. Crumble it into the soaking fried chiles.Have ready a medium bowl and a metal sieve set over a small heatproof bowl.'),
('26559', '3', 'Heat the remaining 1/2 cup of oil in the reserved skillet over medium heat until it shimmers and fry the following ingredients one by one. As theyre fried, use a slotted spoon to transfer them to the medium bowl (for ingredients that are difficult to scoop, empty the contents of the skillet into the sieve to drain first, then return the oil to the skillet and put the fried ingredient into the medium bowl).Fry the almonds, stirring, until they are golden, about 2 minutes.Fry the pumpkin seeds, stirring, until they are puffed and only slightly browned, about 1 minute.Fry the raisins, stirring, until they are puffed, about 1 minute.Fry the bread, turning over once, until golden on both sides, about 3 minutes.Fry the plantain slices, turning over once, until golden, about 3 minutes.'),
('26559', '4', 'Transfer the remaining oil (2 to 4 tablespoons) in the skillet to a 7- to 8-quart heavy pot and set aside.Wipe the skillet clean and heat it over medium heat until its hot. Toast 3 tablespoons of the reserved chile seeds (save the remainder for another use) in the skillet, stirring, until fragrant and a shade darker, about 2 minutes.'),
('26559', '5', 'Transfer the chile seeds to the medium bowl. Toast the sesame seeds, canela, cloves, aniseed, coriander, allspice, and peppercorns in the skillet, stirring, until the sesame seeds are a shade darker, about 11/2 minutes.'),
('26559', '6', 'Transfer the mixture to the medium bowl.'),
('26559', '7', 'Drain the chiles and discard the soaking water, and puree them in the blender jar with about 2 cups of the stock.'),
('26559', '8', 'Heat the reserved oil in the pot over medium heat until hot, then add the chile puree and cook (use a splatter screen so the sauce doesnt make a mess of the stove), stirring occasionally, until thickened slightly, about 10 minutes.Meanwhile, working in 2 batches, combine the fried and toasted ingredients (from the medium bowl) with the roasted tomato, tomatillos, onion, and garlic in the blender jar, along with 2 more cups of the stock per batch, and blend until smooth, about 3 minutes per batch. Be careful when youre blending hot ingredients: Cover the top with a towel, and hold the top firmly in place with your hand.'),
('26559', '9', 'Add the mixture to the chile puree in the pot as you blend it, and once youre done, swish a little liquid around in the blender and add it to the pot.'),
('26559', '10', 'Add the chocolate, sugar, and salt to the mole, stirring until the chocolate melts. Simmer, partially covered, stirring occasionally and adding more stock as needed to maintain a velvety consistency that thickly coats a wooden spoon, but isnt gloppy, about 45 minutes. Season to taste with additional sugar and salt.At this point you would add cooked chicken or turkey to the mole, reduce the heat to low, and cook until its just heated through, 15 to 20 minutes.'),
('26564', '1', 'Heat the olive oil in a large skillet over medium-high heat. Sear the pork in the hot oil until browned on all sides, about 10 minutes.'),
('26564', '2', 'Place into a slow cooker along with the cumin, New Mexico chiles, quartered onion, garlic, and 1 minced jalapeno pepper.'),
('26564', '3', 'Pour in the water, cover, and cook on High for 6 to 8 hours, then reduce heat to Low and cook until the pork is tender and easily shredded, 12 to 16 hours more. Once cooked, remove the pork and vegetables to a large bowl and shred finely with two forks.'),
('26564', '4', 'Mix in enough cooking liquid to moisten the meat to your taste.'),
('26564', '5', 'Prepare the pico de gallo 2 to 6 hours before the carnitas will be ready.'),
('26564', '6', 'Combine the tomatoes, onion, tomatillos, and 2 minced jalapeno peppers in a mixing bowl. Season with lime juice, salt, and pepper.'),
('26564', '7', 'Mix well, and refrigerate until ready to serve.'),
('26565', '1', 'Cook and stir onion in lightly oiled skillet on medium heat  to 5 min. or until tender.'),
('26565', '2', 'Add garlic. cook and stir an additional 30 seconds.'),
('26565', '3', 'Place onion mixture in blender container.'),
('26565', '4', 'Add tomatillos, chiles and cilantro. cover.  Blend until smooth.  Season with salt and pepper to taste, if desired.'),
('26565', '5', 'Heat lightly oiled skillet on medium-high heat.'),
('26565', '6', 'Add tortilla strips and chicken. mix lightly.  Top with  tomatillo sauce and cheese. cover.  Cook 3 to 5 min. or until mixture is heated through and cheese is melted.'),
('26565', '7', 'Serve hot with refried beans and lime wedges.'),
('26566', '1', 'Bring cactus to boil in 1-1/2 qt. (6 cups) salted water in medium saucepan. Simmer on medium heat 15 min. or until tender. drain well.  Cool 5 min.'),
('26566', '2', 'Place cactus in large bowl.'),
('26566', '3', 'Add remaining ingredients. mix lightly.'),
('26567', '1', 'Place tomatillos, onion, garlic, and chile pepper into a saucepan. Season with cilantro, oregano, cumin, and salt. pour in water. Bring to a boil over high heat, then reduce heat to medium-low, and simmer until the tomatillos are soft, 10 to 15 minutes.'),
('26567', '2', 'Using a blender, carefully puree the tomatillos and water in batches until smooth.'),
('26571', '1', 'Mix first 4 ingredients until blended.'),
('26571', '2', 'Pour over meat in shallow dish. turn to evenly coat meat.  Refrigerate 30 min. to marinate.'),
('26571', '3', 'Heat grill to medium heat.'),
('26571', '4', 'Remove meat from marinade. discard marinade.  Grill meat 20 min. or until done (145F), turning occasionally.'),
('26571', '5', 'Remove from grill. cover to keep warm.'),
('26571', '6', 'Grill tomatillos and chiles 8 to 10 min. or until skins are blistered and blackened.'),
('26571', '7', 'Place in blender.'),
('26571', '8', 'Add dressing, cilantro and avocados. blend until smooth.'),
('26571', '9', 'Slice 1 tenderloin. serve with the tomatillo sauce.  Shred remaining tenderloin. refrigerate until ready to use to make Grilled Pork Tacos (see Tip).'),
('26572', '1', 'Blend 1/4 cup dressing, water, tomatillos, pumpkin seeds and 1/4 cup cilantro in blender until smooth. set aside.'),
('26572', '2', 'Heat 2 Tbsp. of the remaining dressing in large skillet on medium-high heat.'),
('26572', '3', 'Add chops. cook 5 to 7 min. or until browned on both sides, turning after 4 min.'),
('26572', '4', 'Remove from skillet. cover to keep warm.'),
('26572', '5', 'Add remaining dressing and onions to skillet. cook 2 to 3 min. or until onions are tender.  Return chops to skillet. cover with tomatillo mixture.  Bring to boil. cover.  Cook on medium-low heat 10 to 12 min. or until chops are done (145F).'),
('26572', '6', 'Remove chops from skillet, reserving sauce in skillet. cover chops to keep warm.'),
('26572', '7', 'Stir cream cheese into sauce. cook, uncovered, 3 min. or until cream cheese is melted and sauce is well blended, stirring frequently.  Spoon over chops. sprinkle with remaining cilantro.'),
('26573', '1', 'Heat broiler.'),
('26573', '2', 'Place tomatillos and chiles in shallow pan. brush with oil.  Broil, 6 inches from heat, 15 min. or until blackened. Meanwhile, cook patties as directed on package. Chop coarsely.'),
('26573', '3', 'Transfer tomatillos and chiles to blender.'),
('26573', '4', 'Add broth. blend until pureed.'),
('26573', '5', 'Pour into large saucepan.  Stir in chopped patties, chickpeas and tomatoes.'),
('26573', '6', 'Bring to boil. simmer on medium-low heat 15 min., stirring occasionally.'),
('26573', '7', 'Serve topped with avocados and cilantro.'),
('26574', '1', 'Place the oven rack in the middle position and heat to 350 degrees F.Tear the tops off the chili peppers and empty the seeds into a small bowl. Discard the stems and any membranes and tear the chilies into flat pieces.'),
('26574', '2', 'Place them on a foil lined baking sheet in a single layer. Spray generously with cooking spray.'),
('26574', '3', 'Place them in the oven and allow to roast for 5-10 minutes or until they change color and a spicy caramel aroma floats through the kitchen. Be careful not to burn them as this will make your mole taste bitter. Once out of the oven, put them in a bowl and cover with warm water to rehydrate.'),
('26574', '4', 'Put the almonds, pumpkin seeds and raisins on the baking sheet, spray with cooking spray and return to the oven until the pumpkin seeds take on a golden color and the raisins are slightly puffy. Again, be careful not to burn them. Set the pan aside and allow to cool.In a heavy bottomed pan like a cast iron skillet, toast the chile seeds, sesame seeds, star anise, cloves, cinnamon and black pepper until the sesame seeds just start to change color and the whole thing smells sweet, nutty and spicy like incense.'),
('26574', '5', 'Transfer the seeds and spices to a food processor and process for a few minutes or until it''s ground into a powder.'),
('26574', '6', 'Add the roasted almonds, pumpkin seeds and raisins and blitz until there are no chunks.'),
('26574', '7', 'Add the oregano, epazote, bay leaf and masa harina and continue to process until powderized.Move the oven rack to the top position and turn the broiler on.'),
('26574', '8', 'Place the tomatillos, tomato, onion slices and garlic on a baking sheet and put it under the broiler.'),
('26574', '9', 'Let the tops of the tomatillos and tomato get completely charred before flipping to char the other side.'),
('26574', '10', 'Remove them from the oven and allow them to cool a bit.'),
('26574', '11', 'Add to the food processor along with 1 cup of chicken stock and blitz with the spice/seed mixture until it''s smooth.'),
('26574', '12', 'Transfer this mixture to a bowl, cover and set aside.Return the work bowl to the food processor and add the rehydrated chili peppers along with 3/4 C of the soaking liquid. Process until smooth.Generously salt and pepper the rabbit.'),
('26574', '13', 'Heat a large dutch oven until hot, add a splash of oil then swirl to coat.'),
('26574', '14', 'Place the seasoned rabbit pieces in the pot and allow them to brown for 5-7 minutes without disturbing them. If you go to flip them and they''re stuck to the pan they aren''t ready to flip. Brown the other side then transfer to a plate.Turn the heat down, then pour the chili pepper puree into the pan through a single mesh strainer, pressing on the solids with a rubber spatula to remove all the skins. Deglaze the bottom of the pan and cook until the mixture is very thick.'),
('26574', '15', 'Pour the spice/seed mixture into the pot through the strainer pressing on any solids.'),
('26574', '16', 'Add the chicken stock and chocolate then salt to taste. If you like it even sweeter you can add more sugar.Return the rabbit to the pot and simmer uncovered over medium low heat until the rabbit is tender (about 1 hour).'),
('26574', '17', 'Serve with fresh tortillas, cilantro and lime wedges.'),
('26576', '1', 'Preheat an outdoor grill for high heat, and lightly oil the grate.'),
('26576', '2', 'Lay the poblano peppers, serrano peppers, and tomatillos on the hot grill, and cook, turning every 2 minutes, until the pepper skins are evenly charred and blackened, and the tomatillos have turned pale yellow and started to ooze juice, about 10 minutes.'),
('26576', '3', 'Remove the vegetables from the grill.'),
('26576', '4', 'Scrape off most of the burned pepper skin, cut the stems off, cut the peppers in half the long way, and remove the seeds.'),
('26576', '5', 'Place the onion and garlic in the work bowl of a food processor, and pulse about 4 times to chop. Drop in the peppers, pulse 4 times to roughly chop, and add the tomatillos and salt. Pulse 4 or more times to the desired smoothness, and stir in the cilantro.'),
('26577', '1', 'Preheat an oven to 400 degrees F (200 degrees C). Lightly oil a 9x13 inch baking dish.'),
('26577', '2', 'Place jalapeno peppers, tomatillos, green onions, quartered onion, and cilantro in a food processor. Pulse until mixture is coarsely chopped, about 8 pulses.'),
('26577', '3', 'Pour mixture into a saucepan over medium heat and bring to a simmer. cook about 5 minutes. Stir in cream and chicken broth. season with salt and pepper. Return to a simmer and cook until slightly thickened, about 10 minutes. Set aside.'),
('26577', '4', 'Place shrimp and spinach in a skillet over medium heat. Cover tightly and cook until spinach wilts and shrimp are heated through, about 3 minutes.'),
('26577', '5', 'Remove from heat.'),
('26577', '6', 'Wipe skillet dry and pour in 1 teaspoon of the oil. heat oil over medium heat.'),
('26577', '7', 'Place a tortilla in skillet about 10 seconds. turn and heat on second side about 5 seconds to soften for easier handling. Fill tortilla with a tablespoon of the shrimp and spinach mixture and about a tablespoon of shredded cheese. Repeat with each tortilla adding more oil to the skillet as needed.'),
('26577', '8', 'Place filled tortillas snugly in prepared baking dish.'),
('26577', '9', 'Pour sauce over tortillas and sprinkle with remaining grated cheese and any remaining filling. Top with dollops of sour cream and some green pepper sauce, if desired.'),
('26577', '10', 'Bake in preheated oven for 15 to 20 minutes or until hot and bubbly.'),
('26578', '1', 'preheat oven to 300 degrees F. in a small bowl, combine coffee, salt, jalapeno powder and chile powder and mix. rub all over brisket to coat well.heat a large dutch oven over medium high heat and add olive oil. sear meat on each side until nicely browned. add remaining ingredients plus 2 cups water and bring to a simmer. cover and transfer pot to oven and cook for 3 hours or until tender. remove meat from broth and set aside until cool enough to shred. strain liquid and return to pot. simmer over medium heat until slightly reduced. stir shredded meat into broth and keep warm.heat olive oil in a medium saute pan over medium high heat. add peppers, onion and garlic and saute 10 minutes or until softened. stir in heavy cream and oregano.for each taco, top a warm corn tortilla with about 1/4 cup meat, a few tablespoons of stewed peppers and onions, salsa, cheese and avocado. enjoy!'),
('26579', '1', 'Heat grill to medium heat.'),
('26579', '2', 'Blend first 3 ingredients in blender just until blended. (Some chunks can remain.)'),
('26579', '3', 'Combine oil, oregano and cumin. brush onto cactus. Grill 8 min. or until tender, turning occasionally.'),
('26579', '4', 'Transfer to plate.'),
('26579', '5', 'Spread cactus with beans. top each with 1 Tbsp. tomatillo mixture.  Cover with onions and cheese.'),
('26579', '6', 'Serve with remaining tomatillo mixture.'),
('26583', '1', 'Line a 10-inch heavy skillet (preferably cast-iron. not nonstick) with foil, then heat over moderately high heat until hot but not smoking.'),
('26583', '2', 'Add 2 whole garlic cloves and half of tomatillos, cut sides down, and roast on top of stove until well browned, 4 to 5 minutes (skillet will begin to smoke at this point). Turn over garlic and tomatillos (tomatillos may stick to foil) and roast until well browned and tomatillos are completely soft, 3 to 4 minutes.'),
('26583', '3', 'Transfer roasted garlic and tomatillos to a food processor. Discard foil, then line skillet with a fresh sheet of foil and roast remaining 2 whole garlic cloves and remaining tomatillos in same manner, transferring as done to food processor. Cool garlic and tomatillos to room temperature in bowl of processor, about 30 minutes.'),
('26583', '4', 'Add chiles, half of cilantro, and 2 tablespoons water to mixture in processor, then pulse until it forms a chunky sauce, adding 1 tablespoon more water if too thick.'),
('26583', '5', 'Transfer to a bowl and stir in onion and 1 teaspoon salt.'),
('26583', '6', 'If using avocado leaves, toast, 1 at a time, in a dry 10-inch heavy skillet (without foil lining) over moderate heat, turning every few seconds, until lightly browned and aromatic, about 1 minute, transferring to a plate as toasted. Bring beans and remaining 2 cups water to a simmer in a 3-quart heavy saucepan, stirring occasionally, then add avocado leaves and simmer, uncovered, stirring occasionally, 20 minutes.'),
('26583', '7', 'Drain beans in a sieve set over a bowl, reserving liquid. Pure beans, 1/4 cup cooking liquid (reserve remainder), avocado leaves (if using), and chopped garlic in a food processor until smooth.'),
('26583', '8', 'Heat oil in a 10-inch heavy nonstick skillet over moderate heat until hot but not smoking, then add bean puree and cook, stirring, until very thick, about 5 minutes. Stir in remaining 3/4 teaspoon salt, then remove from heat and keep warm, covered.'),
('26583', '9', 'Halve and pit avocados, then scoop out flesh in large pieces and cut into 1/2-inch cubes.'),
('26583', '10', 'If necessary, stir some of reserved bean-cooking liquid in to make bean puree soft and easily spreadable. Divide warm beans among tostadas and spread evenly. Spoon about 1 tablespoon tomatillo sauce over each tostada, then divide avocado among tostadas and top with romaine, cheese, and remaining cilantro.'),
('26583', '11', 'Serve remaining tomatillo sauce on the side.'),
('26585', '1', 'Preheat the oven''s broiler. Arrange the whole cloves of garlic, tomatillos, and jalapenos on a baking sheet.'),
('26585', '2', 'Place under the broiler, and cook for a few minutes.'),
('26585', '3', 'Remove garlic cloves first, as soon as they are toasted, to avoid developing a bitter flavor. Continue to roast jalapenos and tomatillos until evenly charred, turning occasionally. Set aside to cool. Don''t remove the charred parts of the tomatillos or the peppers. They add a really nice flavor.'),
('26585', '4', 'Place peppers and tomatillos in a blender with the garlic and cilantro.'),
('26585', '5', 'Add a little water to the mixture if necessary to facilitate blending. Season with salt and pepper to taste. Refrigerate until serving.'),
('26588', '1', 'Heat oil in large deep skillet over medium-high heat.'),
('26588', '2', 'Add onion. saute until tender, about 5 minutes.'),
('26588', '3', 'Add garlic. stir about 30 seconds.'),
('26588', '4', 'Add 3 cups clam juice and next 4 ingredients to skillet. simmer 5 minutes. DO AHEAD Can be made 4 hours ahead. Cool slightly. Refrigerate uncovered until cold, then cover and chill. Bring to simmer before continuing.'),
('26588', '5', 'Add shrimp, scallops, and 3 tablespoons cilantro to simmering broth, adding more clam juice to thin if necessary. Simmer until seafood is just opaque in center, about 3 minutes. Season with salt and pepper. Divide among bowls. sprinkle with remaining cilantro.'),
('26589', '1', 'Toss pork in bowl of slow cooker with salt, black pepper, and dried oregano to coat.'),
('26589', '2', 'Place onion pieces atop pork. Cover slow cooker and cook pork on low setting until meat is very tender and falling apart, about 6 hours.'),
('26589', '3', 'Using slotted spoon, transfer pork to cutting board. Discard onion pieces. Using fingers, shred pork. transfer carnitas to platter.'),
('26589', '4', 'Place avocado slices, cilantro sprigs, and sliced red bell peppers, if desired, alongside. Wrap corn tortillas in damp kitchen towel. microwave until warm, about 1 minute.'),
('26589', '5', 'Serve carnitas with warm tortillas and tomatillo salsa.'),
('26589', '6', 'Per serving: 516 calories, 22g fat (6g saturated), 136mg cholesterol, 1570mg sodium, 32g carbohydrates, 8g fiber, 47g protein See Nutrition Data''s complete analysis of this recipe '),
('26589', '7', 'Nutrition Data'),
('26596', '1', 'Spray three 12-cup mini muffinpans with nonstick spray. Preheat oven to350F.'),
('26596', '2', 'Combine masa, flour, and 3/4 teaspoonsalt in processor. using on/off turns, processto blend.'),
('26596', '3', 'Add butter.'),
('26596', '4', 'Add shortening byrounded teaspoonfuls. Using on/off turns,process until mixture resembles coarsemeal.'),
('26596', '5', 'Add 1/4 cup warm water and processjust until moist clumps form, adding morewater by teaspoonfuls if dry.'),
('26596', '6', 'Transfer dough to work surface. forminto ball.'),
('26596', '7', 'Roll scant tablespoonful doughbetween palms into 1-inch round. Flatteninto disk, then press onto bottom and upsides of 1 muffin cup, keeping top edgeof dough inside cup (do not form anyoverhang). Repeat with remaining dough.'),
('26596', '8', 'Bake crusts until dry to touch and easyto remove from cups, about 35 minutes.Cool on rack. DO AHEAD:  Can be made 1day ahead. Store at room temperature inairtight container.'),
('26597', '1', 'Heat oil in a 3 1/2-quart flameproof nonreactive shallow casserole or deep skillet to 375F. Fry tortillas in batches, turning occasionally, until golden, about 1 minute, and transfer to paper towels to drain (return oil to 375F between batches). Carefully pour off all but 1 tablespoon hot oil into a large metal bowl to cool before discarding.'),
('26598', '1', 'Heat the oil in a large saucepan over high heat until hot. Reduce the heat to medium, add the onion, and cook, stirring occasionally, until softened, about 5 minutes.'),
('26598', '2', 'Add the salsa and cook, stirring, for 5 minutes.'),
('26598', '3', 'Add the chicken broth and simmer, partially covered, for 10 minutes.'),
('26598', '4', 'Add the chicken and hominy and simmer until heated through.'),
('26598', '5', 'Add salt and pepper to taste. To serve, ladle into bowls and let everyone garnish their own portion.'),
('26600', '1', 'Watch how to make this recipe.'),
('26600', '2', 'Pull the husks from the tomatillos and wash them under cool water until they no longer feel sticky.'),
('26600', '3', 'Cut them into quarters and put them into the work bowl of a food processor.'),
('26600', '4', 'Add the onion and garlic and process until smooth.'),
('26600', '5', 'Add the cilantro, jalapeno and lime juice and process until the jalapeno is finely chopped.'),
('26600', '6', 'Scrape the mixture into a small saucepan. Season lightly with salt and bring to a boil over medium heat. Cook, stirring occasionally, until most of the liquid is boiled off and the salsa looks relish-y, about 15 minutes. Cool before using. The sauce can be refrigerated for up to 1 week. If refrigerated, you may want to add a little salt and/or lime juice to the salsa before serving.'),
('26602', '1', 'Pour 1/3 cup dressing over steaks in shallow dish. turn to coat both sides of each steak. Refrigerate 30 min. to marinate.  Meanwhile, cook tomatillos in 2 cups simmering water in saucepan on low heat 15 min. or until tomatillos are softened and skins are tender.  (Do not let tomatillos boil.)'),
('26602', '2', 'Drain tomatillos, reserving 1/2 cup cooking liquid. place tomatillos and reserved liquid in blender.'),
('26602', '3', 'Add avocados, 1/4 cup cilantro, 1/2 cup onions and garlic. blend until smooth.'),
('26602', '4', 'Heat remaining dressing in large skillet on medium-high heat.'),
('26602', '5', 'Add onions. cook on medium heat 5 min.'),
('26602', '6', 'Remove from skillet. cover to keep warm.'),
('26602', '7', 'Remove steaks from marinade. discard marinade.'),
('26602', '8', 'Add steaks, in batches, to skillet. cook 2 min. on each side or until medium doneness (160F). Return steaks and onions to skillet. Top with avocado sauce. Cook on low heat 1 to 2 min. or until sauce is heated through.'),
('26602', '9', 'Serve topped with sour cream and remaining cilantro.'),
('26605', '1', 'Preheat broiler. Line large rimmed bakingsheet with foil. brush lightly with 1tablespoon olive oil. Arrange tomatillos,poblano chiles, cut side down, and garliccloves on prepared baking sheet. Broil untiltomatillos and chiles begin to soften andblacken in several spots, watching closely toprevent burning, about 10 minutes (do notturn).'),
('26605', '2', 'Remove from oven.'),
('26605', '3', 'Let stand until coolenough to handle, about 15 minutes.'),
('26605', '4', 'Transfer tomatillos to processor. Peelgarlic and add to processor. Peel charredparts of chiles. coarsely chop chiles.'),
('26605', '5', 'Addgenerous 1/3 cup chopped chiles to processor(reserve remaining chiles for enchiladafilling).'),
('26605', '6', 'Add 2 cups cilantro and 1 cup greenonions to processor. using on/off turns,blend until coarse puree forms. Season salsaverde to taste with salt and pepper.'),
('26605', '7', 'Transfer1 1/2 cups salsa verde to shallow bowl.'),
('26605', '8', 'Heat 2 tablespoons oil in large nonstickskillet over medium-high heat.'),
('26605', '9', 'Add choppedred onion and saute until slightly softened,about 2 minutes. Sprinkle shrimp with saltand pepper.'),
('26605', '10', 'Add shrimp, oregano, cumin,and remaining chopped chiles to skillet.saute just until shrimp are almost opaquebut not completely cooked through, tossingoften, 3 to 31/2 minutes.'),
('26605', '11', 'Remove shrimpmixture from heat.'),
('26605', '12', 'Preheat oven to 350F.'),
('26605', '13', 'Brush 15x10x2-inch glass baking dish with remaining1 tablespoon olive oil.'),
('26605', '14', 'Spread 1/2 cup salsaverde from processor in bottom of dish. Stacktortillas. wrap in damp paper towels andplace on plate. Microwave tortillas on highjust until soft and pliable, 1 to 11/2 minutes.Working with 1 tortilla at a time, dip tortillainto bowl with 1 1/2 cups salsa verde, turningto coat both sides evenly.'),
('26605', '15', 'Transfer toprepared baking dish.'),
('26605', '16', 'Place 4 shrimp andsome onion-chile mixture down center oftortilla, then sprinkle rounded tablespoonfulcheese over.'),
('26605', '17', 'Roll up tortilla, enclosingshrimp and onion-chile filling.'),
('26605', '18', 'Place seamside down in dish. Repeat with remainingtortillas, shrimp, onion-chile mixture,and cheese.'),
('26605', '19', 'Spread 2 cups salsa verdefrom processor over enchiladas.'),
('26605', '20', 'Bake enchiladas just until heatedthrough and cheese melts, about 20 minutes.Using spatula, transfer 2 enchiladas toeach of 6 plates. Spoon any remaining salsaverde over. sprinkle with remaining cheese.'),
('26605', '21', 'Drizzle with crema and garnish with redonion slices and additional chopped cilantro,if desired.'),
('26605', '22', '* Available in the produce section of somesupermarkets and at Latin markets.'),
('26608', '1', 'In a food processor, puree the tomatillos with the jalapeos, scallions, rosemary, one-fourth of the garlic, 2 tablespoons of the olive oil and 1 tablespoon of the honey.'),
('26608', '2', 'Pour the puree into a sturdy resealable plastic bag.');