INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('21163', '11', 'Combine all the julienned vegetables and the chopped cilantro in a bowl. In another bowl mix the lime juice, fish sauce and superfine sugar, and dress the vegetables with this.'),
('21163', '12', 'For serving: Arrange the beef on a serving platter and pour over the reduced sauce over the meat, then dress the top with the hot and sour shredded salad. If you are using cubes of stew meat, rather than slices of shank, you''d probably do better to use a deeper dish.'),
('21163', '13', 'Make Ahead Note: Cook the beef for 1 3/4 hours then transfer to a bowl to cool. Cover, refrigerate and store in refrigerator for up to 2 days. When ready to use, return the beef to the Dutch oven and heat gently until sauce is just boiling. Cover and return to oven for 30 minutes, or until the beef is piping hot.'),
('21163', '14', 'Transfer meat to an ovenproof dish and finish sauce as directed.'),
('21163', '15', 'Freeze Note: Cook and cool as above then freeze for up to 3 months in airtight container. Thaw overnight in fridge and reheat and finish as above.'),
('21166', '1', 'Combine vinegar, salt and sugar in a bowl and mix well to dissolve. Taste and adjust salt/sugar if desired.'),
('21166', '2', 'Place sliced chillies in another bowl and pour boiling water over them.'),
('21166', '3', 'Let it stand for 30 seconds, and then drain off the water.'),
('21186', '1', 'In a medium bowl, combine the beans, oil, salt, and pepper. Roughly mash the mixture with the back of a fork.'),
('21186', '2', 'Place 8 of the bread slices on a work surface. Divide the mashed beans among the slices. Top with the onion, cucumber, sprouts, and avocado. Stack the open-faced sandwiches on top of one another, avocado-side up, to make 4 double-decker sandwiches. Top with the remaining 4 slices of bread. Slice each sandwich in half, if desired, and serve.Tip: You can make this quick sandwich even more quickly by using store-bought hummus in place of the smashed white beans.'),
('21194', '1', 'Blend tomatoes, tomato juice, 1/2 teaspoon oil, lime juice and hot sauce with 1/2 cup water in a blender or food processor until smooth. Strain through a fine-mesh sieve; discard solids.'),
('21194', '2', 'Add 1/4 teaspoon salt. Freeze in an ice cream maker, as directed by manufacturer. Store in freezer.'),
('21194', '3', 'Heat remaining 1/4 cup oil in a medium saucepan over medium heat. Cook onion until tender, about 10 minutes. Reduce heat to low; cook 10 minutes more.'),
('21194', '4', 'Remove from heat; cool to room temperature. Blend in a blender until smooth. Strain through a fine-mesh sieve; discard solids. Set aside. Slice avocado thinly and divide among 8 small plates, fanning out slices to form a flat surface. Coat avocado with cooking spray; cover with plastic wrap until needed (to prevent oxidation).'),
('21194', '5', 'Place diced lime on and around avocado. Sprinkle with remaining 1/4 teaspoon salt.'),
('21194', '6', 'Place 1 scoop sorbet on top of avocado slices; drizzle with 1 teaspoon onion oil. Divide chips among plates; sprinkle with black pepper.'),
('21194', '7', 'Garnish with cilantro.'),
('21194', '8', 'Self'),
('21203', '1', 'Scoop avocado flesh into a bowl and mash with a fork (leave slightly chunky). Stir in all other ingredients except sesame seeds. Sprinkle with the seeds.'),
('21203', '2', '*An aromatic herb; find shiso at Asian markets.'),
('21204', '1', 'Peel, pit, and slice 2 firm-ripe avocados (3/4 lb. total) and mash with a fork. Stir in 3 tablespoons lime juice, 1/4 cup thinly sliced green onions, 2 tablespoons minced fresh cilantro, 1 tablespoon minced fresh jalapeo chili, and salt to taste.'),
('21211', '1', 'Peel, pit, and slice 2 firm-ripe avocados (3/4 lb. total) and mash with a fork. Stir in 3 tablespoons lime juice, 1/4 cup thinly sliced green onions, 2 tablespoons minced fresh cilantro, 1 tablespoon minced fresh jalapeo chili, and salt to taste.'),
('21212', '1', 'In a small bowl, combine 1 diced, peeled Granny Smith apple, 1/2 diced small white onion, 1 minced jalapeo pepper, 1 diced Hass avocado, 2 tablespoons chopped fresh cilantro, 1 tablespoon fresh lime juice, and 1/2 teaspoon kosher salt. Toss well.'),
('21219', '1', 'Mix everything.'),
('21220', '1', 'Peel, pit, and slice 2 firm-ripe avocados (3/4 lb. total) and mash with a fork. Stir in 3 tablespoons lime juice, 1/4 cup thinly sliced green onions, 2 tablespoons minced fresh cilantro, 1 tablespoon minced fresh jalapeo chili, and salt to taste.'),
('21228', '1', 'Mash everything to the desired consistency.'),
('21233', '1', 'Combine first 5 ingredients in a large bowl; stir until smooth.'),
('21233', '2', 'Add tomato and remaining ingredients; stir gently.'),
('21233', '3', 'Serve with cucumber and zucchini rounds.'),
('21234', '1', 'Cut avocados in half. Scoop pulp into a bowl, and mash with a potato masher or fork until slightly chunky. Stir in chopped red onion and next 4 ingredients. Cover with plastic wrap, allowing wrap to touch mixture, and let stand at room temperature 30 minutes.'),
('21234', '2', 'Serve guacamole with tortilla chips.Cilantro Guacamole: Mash avocado, and stir in ingredients as directed. Stir in 3 Tbsp. chopped fresh cilantro and an additional 1 Tbsp. lime juice. Cover mixture, and let stand at room temperature 30 minutes.'),
('21237', '1', 'Combine first 5 ingredients. Gently stir in Lime Vinaigrette to coat. Cover and chill at least 1 hour.'),
('21237', '2', 'Garnish, if desired.'),
('21239', '1', 'Grill corn until nice and golden, with good grill marks on the kernels. Allow to cool a bit, then cut the kernels off the cobs. Set aside. Halve avocados and remove pit.'),
('21239', '2', 'Cut avocado into a dice inside the skin, then scoop out with a spoon. In a bowl, combine corn kernels, diced avocados, diced tomato, jalapenos, minced garlic, lime juice, salt, and cumin. Stir gently to combine.'),
('21239', '3', 'Add cilantro and stir in.'),
('21252', '1', 'Preheat a grill pan. In a small bowl, toss the scallions, garlic and jalapeo with the vegetable oil. Grill over moderately high heat, turning occasionally, until charred all over, 5 to 6 minutes.'),
('21252', '2', 'Transfer to a work surface and let cool.'),
('21252', '3', 'Finely chop the scallions and jalapeo and transfer to a medium bowl. Peel the garlic cloves, mash them to a paste and add them to the bowl. Scoop the avocado flesh into the bowl and coarsely mash with a fork. Fold the cilantro and lime juice into the guacamole, season with salt and pepper and serve.'),
('21255', '1', 'In a shallow bowl, mix the avocados, tomato, onion, cilantro, mint, jalapeo and lime juice; season with salt and pepper. Melt the cheese in a microwave-safe bowl, pour over the guacamole and serve with tortilla chips.'),
('21257', '1', 'Combine first 5 ingredients in a small bowl. Reserve 3/4 cup juice mixture. Stir carrot and chile into remaining 1/2 cup juice mixture, and set aside.'),
('21257', '2', 'Peel shrimp, leaving tails intact. Starting at tail end, butterfly each shrimp, cutting to, but not through, backside of shrimp.'),
('21257', '3', 'Combine reserved 3/4 cup juice mixture and shrimp in a large bowl, tossing to coat; cover and marinate in refrigerator 1 hour, tossing occasionally.'),
('21257', '4', 'Remove shrimp from bowl, reserving marinade.'),
('21257', '5', 'Prepare grill for medium-high heat.'),
('21257', '6', 'Place reserved marinade in a small saucepan; bring to a boil. Reduce heat, and simmer 5 minutes. Cool slightly.'),
('21257', '7', 'Thread 3 shrimp onto each of 12 (10-inch) skewers.'),
('21257', '8', 'Place shrimp on a grill rack coated with cooking spray. Grill shrimp 2 1/2 minutes on each side or until done, basting frequently with cooked marinade.'),
('21257', '9', 'Cut 3 avocado halves in half lengthwise; peel and dice remaining avocado half.'),
('21257', '10', 'Brush cooked marinade over mango and avocado wedges; coat with cooking spray. Arrange in a single layer on grill rack coated with cooking spray. Coat lime wedges with cooking spray; place on grill rack. Grill fruit 2 minutes on each side or until marked but not soft, basting frequently with marinade.'),
('21257', '11', 'Place 1 lettuce leaf on each of 6 salad plates; top each leaf with 2 mango slices, 2 lime wedges, and 1 avocado wedge.'),
('21257', '12', 'Place 2 skewers on each plate; sprinkle evenly with diced avocado. Sprinkle with cilantro, if desired.'),
('21257', '13', 'Serve with carrot mixture.'),
('21261', '1', 'Combine the first 7 ingredients, stirring well.'),
('21261', '2', 'Warm tortillas according to package directions.'),
('21261', '3', 'Spread about 2 tablespoons avocado mixture over each tortilla, leaving a 1-inch border. Arrange Simply Roasted Pork slices down center of tortillas. Top each tortilla with 1/4 cup shredded lettuce and 1 tablespoon salsa, and roll up.'),
('21264', '1', 'Preheat the broiler.'),
('21264', '2', 'Put the poblano on a baking sheet and broil as close to the heat source as possible, turning once, until charred all over, about 4 minutes.'),
('21264', '3', 'Transfer the poblano to a small bowl, cover tightly with plastic wrap and let stand for 5 minutes. Rub the skin off of the chile with a paper towel and discard the stem and seeds.'),
('21264', '4', 'Cut the poblano into 1/4-inch dice.'),
('21264', '5', 'Transfer all but 1 tablespoon to a medium bowl.'),
('21264', '6', 'In a metal baking pan, broil the tomatillos, turning once, until lightly browned, about 3 minutes.'),
('21264', '7', 'Transfer the tomatillos to a food processor and puree.'),
('21264', '8', 'Add the tomatillo puree to the diced poblano along with the onion, garlic, chopped cilantro, lime juice and half of the avocado; mash well with a fork.'),
('21264', '9', 'Add the remaining avocado and mash lightly. Season with salt and pepper.'),
('21264', '10', 'Transfer the guacamole to a serving bowl and top with the reserved 1 tablespoon of diced poblano and the cilantro leaves.'),
('21264', '11', 'Serve right away with baked tortilla chips.'),
('21270', '1', 'Get everything, except the avocados, prepped when you get home. Just before you want to eat, peel and stone the avocados and put the flesh in a bowl. Don''t worry about how pulpy you make the avocado, as it will be mashed. Dissolve the salt in the lime juice and pour it over. Then add the other ingredients and mash with a fork until you have a rough lumpy mixture. At all costs avoid turning it into a smooth puree; by its nature the avocado will be smooth anyway, but you want as many soft but form-holding clumps as possible.'),
('21274', '1', 'In a large, unoiled frying pan over medium heat, pan-roast the Jalapeos, onion, garlic, and tomatillo on all sides, 20 to 25 minutes total.'),
('21274', '2', 'In a blender, whirl the vegetables with 1/4 cup water until blended but still chunky.'),
('21274', '3', 'Add avocado and lime juice; pulse until blended.'),
('21274', '4', 'Add cilantro and salt, pulse to combine, and add more salt and/or lime juice to taste.'),
('21284', '1', 'Place olive oil and garlic in a mortar, and mash with pestle to a paste. Mash avocado by hand or with a fork in a medium bowl; stir in garlic paste and remaining ingredients. Store in an airtight container; refrigerate until ready to serve.'),
('21286', '1', 'Slice each avocado in half lengthwise, pop out seed and slip off the skin. Smash the avocado in a bowl and add onion, chiles, cilantro, lime juice, tomatoes, and garlic and mix well. Season with salt and pepper, cover, and let sit in refrigerator for a couple of hours to allow flavors to combine.'),
('21290', '1', 'Save Recipe'),
('21290', '2', 'Print Recipe'),
('21290', '3', 'Guacamole'),
('21290', '4', 'Ingredients3 large ripe avocados2 roma tomatoes, seeded and diced1/2 small onion, peeled and diced1 jalapeno, seeded and diced3 tbsp fresh lime juice3 tbsp fresh chopped cilantro3/4 tsp  smoked paprika1/4 tsp oregano'),
('21290', '5', 'Salt to taste'),
('21290', '6', 'Total Time: 10 Minutes'),
('21290', '7', 'Servings: 12'),
('21290', '8', 'Kosher Key: Pareve'),
('21304', '1', 'Preheat a grill pan. In a small bowl, toss the scallions, garlic and jalapeo with the vegetable oil. Grill over moderately high heat, turning occasionally, until charred all over, 5 to 6 minutes.'),
('21304', '2', 'Transfer to a work surface and let cool.'),
('21304', '3', 'Finely chop the scallions and jalapeo and transfer to a medium bowl. Peel the garlic cloves, mash them to a paste and add them to the bowl. Scoop the avocado flesh into the bowl and coarsely mash with a fork. Fold the cilantro and lime juice into the guacamole, season with salt and pepper and serve.'),
('21319', '1', 'Combine Tomatillo Pure, serrano chile, salt, and avocados in a bowl, and mash the mixture to desired consistency. Cover and chill.'),
('21323', '1', 'Place the scooped avocado pulp, the pico de gallo, and the Mrs. Dash seasoning blends in a large bowl. Using a potato masher, mix the ingredients thoroughly.'),
('21323', '2', 'Serve.'),
('21326', '1', 'Mash together 4 Haas avocados, 1/4 cup store-bought thick, chunky salsa and 1/4 cup chopped cilantro; season with salt.'),
('21326', '2', 'Serves'),
('21332', '1', 'Preheat oven to 45'),
('21332', '2', 'To prepare guacamole, wrap garlic cloves in foil; bake at 450 for 15 minutes or until soft.'),
('21332', '3', 'Let cool slightly; remove skins and discard.'),
('21332', '4', 'Place garlic in a medium bowl; mash with a fork.'),
('21332', '5', 'Preheat broiler.'),
('21332', '6', 'Cut bell pepper and poblano in half lengthwise; discard seeds and membranes.'),
('21332', '7', 'Place pepper halves, skin sides up, on a foil-lined baking sheet; flatten with hand. Broil 15 minutes or until blackened, turning frequently.'),
('21332', '8', 'Place in a zip-top plastic bag; seal.'),
('21332', '9', 'Let stand 10 minutes. Peel and finely chop.'),
('21332', '10', 'Add peppers, onions, and next 4 ingredients to mashed garlic; stir well.'),
('21332', '11', 'Reduce oven temperature to 42'),
('21332', '12', 'To prepare chips, combine tortilla wedges, 2 teaspoons juice, and 1/4 teaspoon salt in a large bowl, tossing to coat. Arrange tortillas in a single layer on a baking sheet coated with cooking spray.'),
('21332', '13', 'Bake at 425 for 10 minutes or until crisp and lightly browned, turning once. Cool 5 minutes.'),
('21332', '14', 'Serve with guacamole.'),
('21334', '1', 'In a small skillet, toast the cumin seeds over moderately high heat, shaking the skillet, until fragrant, about 30 seconds.'),
('21334', '2', 'Transfer the cumin seeds to a mortar to cool completely, then finely grind with a pestle.'),
('21334', '3', 'Scoop half of the avocados into a large bowl and coarsely mash them with a fork. Stir in the lemon juice, cilantro, onion, garlic, jalapeo and ground cumin. Scoop chunks of the remaining avocados into the bowl; stir lightly with a spoon. Season the guacamole with salt and serve at room temperature or lightly chilled.'),
('21337', '1', 'Watch how to make this recipe.'),
('21337', '2', 'Cut the avocados in 1/2, remove the pits, and scoop the flesh out of their shells into a large bowl. (I use my hands.) Immediately add the lemon juice, hot pepper sauce, onion, garlic, salt, and pepper and toss well. Using a sharp knife, slice through the avocados in the bowl until they are finely diced.'),
('21337', '3', 'Add the tomatoes.'),
('21337', '4', 'Mix well and taste for salt and pepper.'),
('21340', '1', 'Mash avocados with lime juice in medium bowl. Using sharp knife, remove corn kernels from cob and add to avocado mixture. Stir in tomato and green onions.'),
('21340', '2', 'Combine chipotle and sour cream in small bowl; whisk to blend. Stir cream mixture into avocado mixture. Season with salt. Do ahead: Can be made 4 hours ahead.'),
('21340', '3', 'Place plastic wrap directly onto surface of guacamole and refrigerate. Bring to room temperature before serving.'),
('21340', '4', '*Chipotle chiles are dried, smoked jalapeños canned in adobo sauce. They are available at some supermarkets, at specialty foods stores, and at Latin markets.'),
('21341', '1', 'Remove the outer husk from the corn and loosen the silks without removing. Dunk into water and place directly onto a hot grill for 15 minutes.'),
('21341', '2', 'Remove from grill.'),
('21341', '3', 'Remove remaining husks and silks and cut the kernels off of the cob.'),
('21341', '4', 'Combine all ingredients in a bowl and season with salt and pepper.'),
('21341', '5', 'Serve with fried blue, yellow and white corn chips.'),
('21351', '1', 'Make chips: Preheat oven to 375F. Split each pita in half.'),
('21351', '2', 'Brush both sides with oil and sprinkle with cumin and salt.'),
('21351', '3', 'Cut each half into 6 wedges and spread in a single layer on 2 ungreased baking sheets.'),
('21351', '4', 'Bake for 10 minutes, turning pitas over and swapping position of pans halfway through, until pitas are crisp and golden.'),
('21351', '5', 'Make guacamole: In a glass bowl, mash avocado with a fork until chunky.'),
('21351', '6', 'Mix in onion, jalapeo, cilantro, lime juice and tomato; season with salt and pepper. Cover with plastic wrap pressed directly onto guacamole and chill for 20 minutes.'),
('21351', '7', 'Serve with cumin chips.'),
('21358', '1', 'Watch how to make this recipe.'),
('21358', '2', 'Halve and pit the avocados; scoop out the flesh with a tablespoon into a mixing bowl. Mash the avocados with a fork, leaving them still a bit chunky.'),
('21358', '3', 'Add the remaining ingredients, and fold everything together to gently mix.'),
('21358', '4', 'Lay a piece of plastic wrap right on the surface of the guacamole so it doesn''t brown and refrigerate for at least 1 hour before serving.'),
('21360', '1', 'Mash together 4 Haas avocados, 1/4 cup store-bought thick, chunky salsa and 1/4 cup chopped cilantro; season with salt.'),
('21360', '2', 'Serves'),
('21364', '1', 'Scoop avocado pulp into a bowl; mash with a fork just until chunky. Stir in orange and next 5 ingredients. Cover and chill 1 to 4 hours.'),
('21364', '2', 'Serve with tortilla chips.'),
('21364', '3', 'Garnish, if desired.'),
('21375', '1', 'Mix everything in a food processor until the desired consistency is reached.'),
('21380', '1', 'Make the chile paste: Grind the onion, cilantro, jalapeo, and salt together in a molcajete until all the ingredients are very finely ground. Alternatively, use a fork to mash all the ingredients to a paste in a wide hardwood bowl.'),
('21380', '2', 'Cut each avocado in half, working the knife blade around the pit. Twist the halves to separate them and flick out the pit with the tip of the knife. Fold a kitchen towel in quarters and hold it in the palm of your non-knife hand. Rest an avocado half cut side up in your palm and make 3 or 4 evenly spaced lengthwise cuts through the avocado flesh down to the skin, without cutting through it. Make 4 crosswise cuts in the same way. Scoop the diced avocado flesh into the molcajete. Repeat with the remaining avocado halves.'),
('21380', '3', 'Gently fold the avocado into the paste, keeping the avocado in as large pieces as possible.'),
('21380', '4', 'Add the tomato, cilantro, and onion and fold in gently. Check and add salt if necessary.'),
('21380', '5', 'Serve immediately, right from the molcajete (or bowl), with the chips and tortillas.'),
('21380', '6', 'VARIATIONSGuacamole with Seafood (Guacamole con Mariscos)'),
('21380', '7', 'Makes 6 servings pound lump crabmeat (preferably jumbo), picked over for shells and cartilage (about  cup)  pound cooked peeled baby shrimp, left whole, or larger shrimp, cut into small pieces3 tablespoons chopped fresh cilantro2 tablespoons finely chopped jalapeo1 tablespoon olive oil2 teaspoons chipotle adobo puree'),
('21380', '8', 'Salt to taste'),
('21380', '9', 'Toss all the ingredients together in a mixing bowl.'),
('21380', '10', 'Let stand at room temperature for 20 to 30 minutes.'),
('21380', '11', 'Prepare the guacamole, adding the marinated seafood salad at the end along with the tomato, cilantro, and onion. Guacamole with Fruit (Guacamole can Frutas)'),
('21380', '12', 'Makes 6 servings'),
('21380', '13', 'Diana Kennedy, the Julia Child of Mexican cookbook authors, and Maria Dolores Torres-Izabal, a dear friend and author of The Mexican Gourmet, introduced me to guacamole with fruit. This is a specialty of two states in central Mexico'),
('21380', '14', 'Morelos and Guanajuato. The contrast between the spicy guacamole and the sweet and juicy fruits is delicious. The dish should always look a little over the topuse the most beautiful, ripe fruits you can find and as many of the embellishments as you like.'),
('21380', '15', 'Prepare the, guacamole, omitting the cilantro entirely. Gently fold in 12 black grapes, halved; 12 green grapes, halved; and 1 cup peeled and diced (-inch) peaches or mango. Taste the guacamole and add additional chile or salt to balance the sweetness of the fruits.'),
('21380', '16', 'Pile the guacamole into martini glasses or half-coconut shells and decorate with any or all of these garnishes: sliced peeled peaches, pomegranate seeds, toasted coconut flakes, and/or raspberries.'),
('21380', '17', 'var article'),
('21380', '18', 'Type_27_data = {};'),
('21380', '19', 'article'),
('21380', '20', 'Type_27_data.init_step_by_step_images = 0;'),
('21382', '1', 'Scoop out avocado flesh into a molcajete or bowl, add garlic and jalapeo, and mash (with a pestle or a wooden spoon) until the avocados are creamy but still very chunky. Stir in tomato, onion, and salt to taste. Sprinkle with lime juice and cilantro, then stir and taste once more.'),
('21382', '2', 'Add more garlic, jalapeo, onion, salt, lime juice, or cilantro as desired.'),
('21382', '3', 'Serve with tortilla chips.'),
('21389', '1', 'Place cream cheese and mayonnaise in a mixer fitted with a paddle attachment. Beat to combine.'),
('21389', '2', 'Add remaining ingredients except almonds and beat gently until just combined. Spoon into a heatproof baking dish. Sprinkle with slivered almonds, then bake at 375 degrees for 20 to 25 minutes or until golden and bubbly on top.'),
('21389', '3', 'Serve with corn chips or crackers.In a blender or food processor, combine avocado, lemon juice, onion, and Worcestershire. Pulse until combined. (Leave some texture to the avocados.)'),
('21389', '4', 'Add cream cheese, sour cream, and salt. Pulse a couple of times. Stir in crab meat. Chill dip until needed. Keep in mind that the avocado will discolor within a few hours, so make no more than a couple of hours before serving!'),
('21391', '1', 'Combine all ingredients (scrape avocado from skin) except for chopped chives in the bowl of a food processor. Pulse a few times, scraping the bowl once or twice if necessary. Continue pulsing until salad reaches the consistency you want: chunky or more smooth!'),
('21391', '2', 'Remove blade from bowl and stir in chives. Check seasoning and adjust as necessary.'),
('21391', '3', 'Serve on a sandwich (spread bread with a mix of Dijon and mayonnaise) or serve on a thick slice of tomato as a cool salad. Sprinkle on extra chives to make it purty.'),
('21396', '1', 'Halve, pit, and peel avocados. Coarsely mash in a bowl. Stir in onion, chiles, 1/4 cup lime juice, and 1 1/4 teaspoons salt, then fold in pomegranate seeds, mango, and cilantro. Season with salt and additional lime juice.'),
('21400', '1', 'Watch how to make this recipe.'),
('21400', '2', 'Place peas in a medium bowl and mash thoroughly with a potato masher or fork. (Or puree peas in a small blender or food processor and transfer to a medium bowl.)'),
('21400', '3', 'Add avocado, yogurt, lime juice, garlic, 1/4 teaspoon salt, 1/8 black pepper, cumin, and chile powder. Continue to mash until blended.'),
('21400', '4', 'Stir in tomatoes, onion, and some cilantro and/or jalapenos, if using. Season with additional salt and pepper, if desired. Enjoy!'),
('21404', '1', 'Preheat broiler.'),
('21404', '2', 'Cut poblanos in half lengthwise, and discard the seeds and membranes.'),
('21404', '3', 'Place poblano halves (skin sides up), tomatoes, and garlic on a foil-lined baking sheet. Broil for 12 minutes or until poblanos are blackened, turning the tomatoes once.'),
('21404', '4', 'Place the poblanos in a zip-top plastic bag, and seal.'),
('21404', '5', 'Let stand 10 minutes. Peel poblanos, tomatoes, and garlic.'),
('21404', '6', 'Place the poblanos and garlic cloves in a food processor, and pulse until coarsely chopped.'),
('21404', '7', 'Combine the poblano mixture, tomato, avocado, parsley, juice, and salt in a bowl. Sprinkle with cheese and radishes.'),
('21404', '8', 'Serve with tortilla chips.'),
('21406', '1', 'Preheat oven to 45'),
('21406', '2', 'To prepare guacamole, wrap garlic cloves in foil; bake at 450 for 15 minutes or until soft.'),
('21406', '3', 'Let cool slightly; remove skins.'),
('21406', '4', 'Place garlic in a medium bowl; mash with a fork.'),
('21406', '5', 'Preheat broiler.'),
('21406', '6', 'Cut peppers in half lengthwise; discard seeds and membranes.'),
('21406', '7', 'Place pepper halves, skin sides up, on a foil-lined baking sheet; flatten with hand. Broil 15 minutes or until blackened, turning frequently.'),
('21406', '8', 'Place in a zip-top plastic bag; seal.'),
('21406', '9', 'Let stand 10 minutes. Peel and finely chop.'),
('21406', '10', 'Add peppers, onions, and next 4 ingredients (through avocado) to mashed garlic; stir well.'),
('21406', '11', 'Reduce heat to 42'),
('21406', '12', 'To prepare chips, combine tortilla wedges, 2 teaspoons juice, and 1/4 teaspoon salt in a large bowl, tossing to coat. Arrange the tortillas in a single layer on a baking sheet coated with cooking spray.'),
('21406', '13', 'Bake at 425 for 10 minutes or until crisp and lightly browned, turning once. Cool 5 minutes.'),
('21406', '14', 'Serve with guacamole.'),
('21419', '1', 'In a small bowl, whisk together the garlic, lemon juice, mustard, anchovy paste, Parmesan, oil, and a few grinds of pepper. Set aside.'),
('21419', '2', 'Place half a romaine heart on each plate and top with some of the chicken, chickpeas, avocado, and walnuts.'),
('21419', '3', 'Drizzle with the dressing. Top with shaved Parmesan, if desired.'),
('21421', '1', 'In a large bowl, combine the avocados, onion, jalapeo, cilantro, lime juice, salt, and pepper. Stir well.'),
('21421', '2', 'Serve with the tortilla chips.Tip: Plan ahead. You can prepare guacamole up to two hours before serving. To keep it from turning brown, cover the bowl with plastic wrap so that the wrap lies directly on the guacamole, with no air in between, then refrigerate.'),
('21423', '1', 'Scoop the avocados out of their skins and place in a food processor.'),
('21423', '2', 'Add the cilantro, sour cream, lime juice, jalapeo, 1 teaspoon salt, and 1/4 teaspoon pepper and blend until smooth.'),
('21423', '3', 'Serve with the vegetables.'),
('21435', '1', 'Preheat oven to 37'),
('21435', '2', 'To prepare chips, cut each tortilla into 8 wedges; arrange tortilla wedges in a single layer on 2 baking sheets coated with cooking spray. Sprinkle wedges with 1/2 teaspoon salt and chile powder; lightly coat wedges with cooking spray.'),
('21435', '3', 'Bake at 375 for 12 minutes or until wedges are crisp and lightly browned. Cool 10 minutes.'),
('21435', '4', 'To prepare guacamole, peel papery husk from tomatillos; wash, core, and finely chop.'),
('21435', '5', 'Combine tomatillos, onion, and remaining ingredients; stir well.'),
('21435', '6', 'Serve guacamole with chips.'),
('21438', '1', 'Preheat oven to 20'),
('21438', '2', 'In a medium saucepan, heat 1 1/2 in. oil until it registers 375 on a deep-fry thermometer.'),
('21438', '3', 'Meanwhile, mix flour with 1/4 tsp. salt in a shallow plate. Put eggs and panko in separate shallow plates. Dip avocado in flour, shaking off excess. Dip in egg, then panko to coat. Set on 2 plates in a single layer.'),
('21438', '4', 'Fry a quarter of avocado slices at a time until deep golden, 30 to 60 seconds.'),
('21438', '5', 'Transfer slices to a plate lined with paper towels. Keep warm in oven while cooking remaining avocados. Sprinkle with salt to taste.'),
('21452', '1', 'Halve each half avocado lengthwise and arrange quartered avocados on a platter.'),
('21452', '2', 'Heat lemon 10 seconds on high in microwave to get the juices flowing. Dress avocados with lemon juice, wrap with ham, then continue to dress with extra virgin olive oil, cilantro and salt and pepper, serve.'),
('21453', '1', 'Slice avocado in half. Scoop pulp from 1 half of avocado; set remaining half aside.'),
('21453', '2', 'Place tofu, avocado pulp, salsa verde, and next 3 ingredients in a food processor; process until smooth, scraping down sides of bowl occasionally.'),
('21453', '3', 'Transfer to a medium bowl.'),
('21453', '4', 'Dice remaining avocado.'),
('21453', '5', 'Add diced avocado, tomato, and onion to tofu mixture, stirring well.'),
('21455', '1', 'Slice the red onion and put it in a bowl with the lemon juice. Dice the avocado, add it to the bowl, and toss well to coat.'),
('21455', '2', 'Add the olive oil and garlic and season with salt and pepper. Just before serving stir in the parsley.'),
('21462', '1', 'Heat oil in a 1-quart heavy saucepan over moderate heat until hot but not smoking, then fry shallot, stirring, until golden brown, about 2 minutes.'),
('21462', '2', 'Transfer with a slotted spoon to paper towels to drain (shallots will crisp as they cool). Reserve oil.'),
('21462', '3', 'Soak tamarind pulp in boiling-hot water in a small bowl until softened, about 5 minutes. Force pulp through a sieve into a bowl, discarding solids.'),
('21462', '4', 'Add sugar, soy sauce, fish sauce, and 1 1/2 tablespoons lime juice and stir until sugar is dissolved.'),
('21464', '1', 'In a medium bowl, mash together the avocados, lime juice, and salt.'),
('21464', '2', 'Mix in onion, cilantro, tomatoes, and garlic. Stir in cayenne pepper. Refrigerate 1 hour for best flavor, or serve immediately.'),
('21469', '1', 'Mash avocados in medium bowl.'),
('21469', '2', 'Add remaining ingredients; mix well.'),
('21473', '1', 'Cut the avocadoes in half, remove pits, and scoop the flesh into a bowl.'),
('21473', '2', 'Add the lemon juice and sea salt, to taste. Mash the ingredients together with a fork, keeping the texture slightly chunky.'),
('21473', '3', 'Mix in the tomato, onion, and cilantro.'),
('21473', '4', 'Put a cast iron skillet over medium high heat. When the pan is hot, put in a corn tortilla and cook until the tortilla is heated through and softened, about 30 seconds per side.'),
('21473', '5', 'Spread some of the guacamole onto a heated tortilla, fold it in half, and eat immediately. Repeat with remaining ingredients.'),
('21478', '1', 'Watch how to make this recipe.'),
('21478', '2', 'Cut avocados in half around the pit. Separate the halves. Pop out pit with spoon, then scoop flesh of avocados into a bowl. Squeeze the juice of a lemon over the avocados. Squeeze the juice with the lemon halves facing cut-side up, allowing the juice to spill down over the sides of the lemon into the bowl. This method keeps the seeds in the lemon and out of the guacamole.'),
('21478', '3', 'Add garlic, jalapeno, tomato, onion and salt to the bowl. Mash and mix the ingredients into a chunky dip using a fork.'),
('21478', '4', 'Serve with blue corn tortilla chips.'),
('21481', '1', 'Preheat broiler. Line rimmed baking sheet with foil.'),
('21481', '2', 'Place tomatillos on prepared baking sheet. Broil until tomatillos are just blackened in spots and tender, about 8 minutes per side.'),
('21481', '3', 'Combine onion, cilantro, chiles, and lime juice in large bowl.'),
('21481', '4', 'Add roasted tomatillos and any juices from baking sheet to onion mixture. Using fork, mash coarsely.'),
('21481', '5', 'Add avocados and mash with fork until mixture is very coarsely pureed and some chunks remain. Season guacamole to taste with salt. (Can be made 4 hours ahead. Cover and chill.)'),
('21491', '1', 'Purée chiles, vinegar, and 1 teaspoon salt in a blender.'),
('21491', '2', 'Transfer to a bowl and stir in remaining ingredients.'),
('21496', '1', 'Watch how to make this recipe.'),
('21496', '2', 'Halve and pit the avocados. Scoop out the flesh with a tablespoon into a mixing bowl. Mash the avocados with a fork, leaving them somewhat chunky.'),
('21496', '3', 'Add the remaining ingredients, and fold everything together to gently mix. Lay a piece of plastic wrap right on the surface of the guacamole so it doesn''t brown and refrigerate 1 hour before serving.'),
('21503', '1', 'In a bowl, stir together tomato and chili cocktail mix, tequila, lime juice, onion, cilantro, and 2 teaspoons chili.'),
('21503', '2', 'Pit and peel avocados; cut into 1/2-inch cubes.'),
('21503', '3', 'Add avocados and shrimp to cocktail mixture.'),
('21503', '4', 'Mix gently and add salt and more chili to taste.'),
('21503', '5', 'If desired, rub rims of 4 to 6 margarita or martini glasses with a lime wedge. Immediately dip into a dish filled with 1/4 inch kosher salt.'),
('21503', '6', 'Spoon avocado-shrimp cocktail equally into glasses.'),
('21503', '7', 'Garnish with lime wedges and serve with tortilla chips or saltine crackers.'),
('21513', '1', 'Watch how to make this recipe.'),
('21513', '2', 'Combine all ingredients in a molcajete and mix to a chunky consistency. Season, to taste, with salt, pepper, and cilantro.'),
('21513', '3', 'Serve immediately with cumin tortilla chips.;'),
('21513', '4', 'Fry the tortillas, in batches, until light golden brown.'),
('21513', '5', 'Drain on paper towels and season immediately with cumin and salt.'),
('21515', '1', 'Top 4 tortillas evenly with kimchi, then with cheese, avocados, and remaining tortillas.'),
('21515', '2', 'Mix oil, vinegar, and sesame seeds in a small bowl; set aside.'),
('21515', '3', 'Heat a 12-in. frying pan over medium-high heat. Toast each quesadilla until lightly browned and cheese has melted, 1 to 2 minutes per side. Slice each quesadilla into wedges, sprinkle with cilantro, and serve with sesame dipping sauce.'),
('21516', '1', 'In a large bowl, place the avocados, tomatoes, onions, cilantro, serrano, lemon juice, and salt. Stir gently until well combined.'),
('21516', '2', 'Transfer to a serving bowl and serve.'),
('21517', '1', 'With a sharp knife, cut peel and outer membrane from grapefruit. Working over a strainer set over a bowl, cut between inner membranes and fruit to release segments into strainer. Squeeze juice from membranes into bowl. Discard peel and membranes.'),
('21517', '2', 'In a large bowl, combine oil, lime juice, and grapefruit juice.'),
('21517', '3', 'Add salad greens and mix gently to coat. Divide evenly among four plates and top with grapefruit segments, avocado, almonds, and green onions.'),
('21517', '4', 'Add salt and pepper to taste.'),
('21521', '1', 'Mix all ingredients together in a medium bowl. Cover and refrigerate for at least 45 minutes, but preferably overnight.'),
('21526', '1', 'Mash avocados in small bowl.'),
('21526', '2', 'Add all remaining ingredients except crackers; mix well.'),
('21526', '3', 'Serve with crackers.'),
('21528', '1', 'In a large bowl, whisk together 1/4 cup lime juice, 1 tablespoon red wine vinegar, 1 tablespoon olive oil, 1 1/2 teaspoons salt, 1/2 teaspoon pepper, 1/4 teaspoon ground cumin, and 1/8 teaspoon cayenne.'),
('21528', '2', 'Remove husks and silk from 2 ears corn.'),
('21528', '3', 'Cut kernels off cobs (about 2 cups) and add to bowl. Rinse, stem, seed, and dice 1 red bell pepper (8 oz.).'),
('21528', '4', 'Add bell pepper, 1/2 cup diced red onion, and 1/4 cup chopped cilantro to bowl; stir into dressing. Peel, pit, and chop 3 firm-ripe avocados (1 1/2 lb. total).'),
('21528', '5', 'Add to bowl and gently mix, taking care not to smash the avocado too much.'),
('21530', '1', 'In a bowl, mix the crab, shrimp, cucumber, mayonnaise, and parsley. Season with salt, and pepper. Cover, and chill until serving.'),
('21530', '2', 'Slice the avocados lengthwise, and remove the pit. Scoop out the flesh of the avocado, leaving about 1/2 inch on the peel. Spoon the seafood mixture into the hollowed centers of the avocado halves. Sprinkle the tops with paprika.'),
('21531', '1', 'Pure all ingredients with 3/4 cup water in a food processor until smooth.'),
('21531', '2', '*Spot spring onions'' plump bulbs in the produce aisle next to their skinnier green onion relatives.'),
('21540', '1', 'Prepare a grill for high heat (450 to 550; you can hold your hand 5 in. above cooking grate only 2 to 4 seconds). Rub 1 tbsp. oil over chiles. Cook chiles, turning often, until skins are browned. Put chiles in a bowl, cover, and let cool. Seed chiles and rub off skins.'),
('21540', '2', 'Meanwhile, rub remaining 1 tbsp. oil over chicken.'),
('21540', '3', 'Combine cumin, cayenne, and salt and sprinkle evenly over each breast. Grill chicken, turning once, until browned and cooked through, about 10 minutes total.'),
('21540', '4', 'Squeeze a little lime over chicken, then top each breast with a few avocado slices, a reserved chile, and about 1/4 cup cheese. Grill, covered, until cheese melts, about 4 minutes.'),
('21541', '1', 'Rinse steak and pat dry.'),
('21541', '2', 'Cut into 4 equal pieces.'),
('21541', '3', 'Set an 11- to 12-inch frying pan with ovenproof handle over high heat; when pan is hot, add oil and tilt to coat pan bottom.'),
('21541', '4', 'Add steak and cook, turning pieces once, until browned on both sides but still rare in the center (cut to test), 6 to 7 minutes total.'),
('21541', '5', 'Remove from heat and add tequila and vinegar to pan. Light with a match (not under an exhaust fan or any flammable materials) and shake pan until flames subside.'),
('21541', '6', 'Lay chilies equally on steaks; top with cheese slices. Broil 4 inches from heat just until cheese is melted, 1 to 2 minutes.'),
('21541', '7', 'Meanwhile, pit, peel, and thickly slice avocado.'),
('21541', '8', 'Transfer steaks to plates. Spoon any pan juices around meat. Arrange avocado equally on portions.'),
('21541', '9', 'Add salt and pepper to taste.'),
('21543', '1', 'In a 1- to 2-quart pan over high heat, bring 1 cup water and the sugar to a boil.'),
('21543', '2', 'Add vinegar and onions, and stir occasionally until boiling again.'),
('21543', '3', 'Remove from heat and let cool, about 30 minutes.'),
('21543', '4', 'Meanwhile, spread mayonnaise on toast and set each slice, mayonnaise side up, on a plate. Arrange half the prosciutto, then half the avocado, on each slice of toast.'),
('21543', '5', 'Drain onions well and mound half on each open-faced sandwich. Sprinkle with salt and pepper. Eat with a knife and fork.'),
('21544', '1', 'Preheat an oven to 350 degrees F (175 degrees C). Grease and flour 2 9x5 inch loaf pans.'),
('21544', '2', 'Mix flour, baking soda, baking powder, and salt in a bowl. Set aside. Beat the butter and sugar with an electric mixer in a large bowl until light and fluffy. The mixture should be noticeably lighter in color.'),
('21544', '3', 'Add the room-temperature eggs one at a time, allowing each egg to blend into the butter mixture before adding the next. Beat in the avocado and lemon juice with the last egg.'),
('21544', '4', 'Pour in the flour mixture alternately with the milk, mixing until just incorporated. Fold in the lavender and lemon zest; mixing just enough to evenly combine.'),
('21544', '5', 'Pour the batter into prepared pans.'),
('21544', '6', 'Bake in the preheated oven until a toothpick inserted into the center comes out clean, about 1 hour. Cool in the pans for 10 minutes before removing to cool completely on a wire rack.'),
('21545', '1', 'In a large bowl, whisk together lime juice, oil, and sugar until sugar dissolves.'),
('21545', '2', 'Dice mangoes and avocados into 3/4-in. cubes; add to bowl.'),
('21545', '3', 'Add green onion, cilantro, chile, and shrimp.'),
('21545', '4', 'Mix gently.'),
('21545', '5', 'Serve or cover and chill for up to 1 hour.'),
('21546', '1', 'Whirl avocados, olive oil, vinegar, 1/2 tsp. salt, and 1/2 cup water in a blender until smooth. Stir in chives and tarragon. Cover and let sit 30 minutes at room temperature to let flavors blend.'),
('21546', '2', 'Season sauce with salt to taste and serve with crab.'),
('21551', '1', 'Preheat broiler. When hot, broil poblanos on a baking sheet until blackened, turning as needed, about 15 minutes.'),
('21551', '2', 'Meanwhile, in a food processor, whirl garlic to mince.'),
('21551', '3', 'Cut onion in chunks and pulse with garlic until chopped; set aside.'),
('21551', '4', 'Drain hominy; set aside.'),
('21551', '5', 'Cut chicken into 1- to 1 1/2-in. chunks and sprinkle with salt and 1 tsp. oregano.'),
('21551', '6', 'Heat oil in a 5- to 6-qt. pan over high heat. Brown half the chicken lightly, stirring occasionally, about 5 minutes. With a slotted spoon, transfer meat to a plate. Repeat with remaining chicken.'),
('21551', '7', 'Reduce heat to medium-high.'),
('21551', '8', 'Add onion mixture and remaining 1 tsp. oregano to pan and saut until onion is softened, 3 minutes. Meanwhile, in a microwave-safe bowl, microwave broth until steaming, about 3 minutes.'),
('21551', '9', 'Add ground chiles to pan and cook, stirring, about 30 seconds.'),
('21551', '10', 'Add broth, hominy, and chicken to pan. Cover and bring to a boil, then reduce heat and simmer to blend flavors, 10 minutes.'),
('21551', '11', 'Remove stems, skins, and seeds from poblanos and discard; chop poblanos.'),
('21551', '12', 'Stir poblanos into posole and cook 1 minute. Ladle into bowls; top with garnishes.'),
('21551', '13', '*Find Mexican oregano at well-stocked grocery stores, along with ground red New Mexico chiles.'),
('21552', '1', 'Preheat oven to 35'),
('21552', '2', 'Lay 12 won ton wrappers flat and, using about half the butter, brush both sides. Press into mini muffin cups (2 tbsp. size), pleating each to form a small cup. Sprinkle wrappers with half the sesame seeds.'),
('21552', '3', 'Bake until golden brown (watching carefully; they can burn easily), 7 to 9 minutes. Loosen from cups with a small spatula and put on a cooling rack. Repeat with remaining 12 won ton wrappers, butter, and sesame seeds.'),
('21552', '4', 'In a small bowl, combine salmon, green onions, cilantro, lime juice, ginger, and salt; mix well.'),
('21552', '5', 'Add avocado (see Notes) and toss very gently until well combined. Put a generous spoonful in each won ton cup.'),
('21552', '6', 'Serve immediately.'),
('21552', '7', 'Smoked salmon: The one-minute guide.'),
('21552', '8', 'More than any other fish, salmon lends itself to being smoked. Superb smoked salmon comes from Canada, Ireland, Norway, Scotland, and the United Statesand it all falls into two basic categories.'),
('21552', '9', 'COLD-SMOKED: The salmon is cured in brine or with sugar, salt, and spices, then smoked over wood chips at a low temperature (usually 70 to 9'),
('21552', '10', 'for anywhere from a day to three weeks. The smoke doesn''t actually cook the fish, so it stays silky and has a mild smoke flavor. Nova salmon is cured in a mild brine solution. Scottish-style uses a dry rub that is rinsed off before smoking. Indian-cure salmon is first brined and then smoked for up to two weeks, until it has the texture of jerky. Lox, the bagel''s best friend, is brined and sometimes (but not always) lightly smoked, and tends to be on the salty side. Scandinavian gravlax is not smoked at all, just dry-cured with salt, sugar, and dill.'),
('21552', '11', 'HOT-SMOKED: As with cold-smoked, hot-smokedor kipperedsalmon is cured first. Then it''s smoked at a higher temperature (generally 120 to 18'),
('21552', '12', 'for a shorter period, typically no more than 12 hours. The result: a flaky, cooked texture and a deep, smoky flavor.'),
('21553', '1', 'Whisk together yogurt, garlic, salt, spices, and 2 cups cold water in a large bowl.'),
('21553', '2', 'Add cucumber, avocado, mint, and dill, stirring gently to combine.'),
('21553', '3', 'Drizzle each serving with 1 tsp. oil.'),
('21554', '1', 'In a 2- to 3-qt. pan over high heat, bring about 1 qt. water to a boil.'),
('21554', '2', 'Add green beans and cook until tender to the bite, 3 to 6 minutes.'),
('21554', '3', 'Drain and immerse immediately in ice water until cool, about 2 minutes; drain again.'),
('21554', '4', 'In a blender or food processor, combine avocado, yogurt, lime juice, mint (if using), garlic, and salt; whirl until very smooth.'),
('21554', '5', 'Spoon dip into a bowl and serve with green beans and jicama sticks.'),
('21555', '1', 'Place butter in a shallow 2- to 3-quart baking dish and heat in a 425 oven until melted, 3 to 4 minutes.'),
('21555', '2', 'Meanwhile, in a blender or food processor, whirl eggs and milk until blended.'),
('21555', '3', 'Add flour and whirl until smooth, then add 1 tablespoon of the chiles and whirl just to blend.'),
('21555', '4', 'Pour batter into hot baking dish.'),
('21555', '5', 'Bake until Dutch baby is puffed and well browned, about 20 minutes.'),
('21555', '6', 'Meanwhile, in a bowl, mix remaining 1/2 tablespoon chiles with avocado, tomato, green onion, and lime juice.'),
('21555', '7', 'Dust baked Dutch baby with cayenne if desired.'),
('21555', '8', 'Cut into wedges.'),
('21555', '9', 'Add avocado salsa and salt to taste.'),
('21556', '1', 'Rinse and peel jicama, then cut into 1/8- by 2-inch sticks.'),
('21556', '2', 'Cut off and discard peel and white membrane from grapefruits and oranges. Working over a bowl to catch juices, cut between inner membranes and fruit to free segments, dropping fruit into bowl.'),
('21556', '3', 'Pit, peel, and thinly slice avocados.'),
('21556', '4', 'Line a platter or salad plates with lettuce. With a slotted spoon, lift fruit from bowl; reserve 2 tablespoons juice for persimmon dressing and the rest for other uses. Arrange fruit, avocados, onion, and jicama on lettuce.'),
('21556', '5', 'Spoon about 1/4 cup of dressing over salad. Offer remaining dressing and salt to add to taste.'),
('21557', '1', 'Bring rice and 2 3/4 cups water to a boil, covered, then simmer 20 minutes.'),
('21557', '2', 'Let sit 10 minutes. Turn out onto a rimmed baking sheet and toss gently with salt.'),
('21557', '3', 'Moisten your hands with water and divide rice into 8 balls. Set 1 ball on a piece of plastic wrap, pinch off half, and flatten remaining rice into a small round. Layer with avocado, salmon, and about 1/2 tsp. furikake, leaving 1/2-in. border around filling. Top with rest of rice and use plastic to help you form a blunt triangle about 1 in. thick. Repeat with remaining rice and fillings.'),
('21557', '4', 'Position base of 1 rice triangle facing you. Center 1 nori strip over rice, angling it diagonally from left bottom corner. Tuck ends around triangle.'),
('21557', '5', 'Place 2nd nori strip over first, angled the opposite way; tuck ends under. Lay 3rd strip over and flush with base of triangle and tuck ends under.'),
('21557', '6', '*Find furikake at Asian grocery stores.'),
('21559', '1', 'Marinate the onion'),
('21559', '2', 'Place the onion slices and vinegar in a resealable plastic bag, press out as much air as possible, and close the bag. Alternatively, place the onion and vinegar in a small bowl and put a piece of plastic wrap directly on the surface of the ingredients so that the onion slices remain submerged in the vinegar. Allow the onion to marinate for at least 30 minutes.'),
('21559', '3', 'Assemble the salad and serve'),
('21559', '4', 'Reserve a few tablespoons of the vinegar used to marinate the onion before draining the onion slices and setting aside.'),
('21559', '5', 'Place the avocado slices on a serving platter and top with the red onion slices.'),
('21559', '6', 'Drizzle the oil and reserved red wine vinegar over the salad and season with salt and pepper to taste.'),
('21559', '7', 'Cooking notes'),
('21559', '8', 'Ingredients'),
('21559', '9', 'Florida versus Hass avocados Cubans tend to use Florida avocados since these are more widely available in the Caribbean and in Miami. They are larger than the California or Hass variety, and they remain green when ripe, in contrast to Hass, which are dark green, almost black, when ripe.Florida avocados have a milder flavor due to their higher water content, and they are ready to eat as soon as they yield to pressure when squeezed lightly.Techniques'),
('21559', '10', 'Marinating onions Allowing raw onions to marinate in vinegar or another highly acidic liquid mellows out the strong flavor and softens its texture.Slicing an avocado Start by slicing the avocado in half lengthwise with a large knife and, once you hit the seed in the center, move your knife along its perimeter. Open the avocado by gently twisting and pulling on each half.'),
('21559', '11', 'Remove the seed by tapping it with the sharp edge of your knife, causing the knife to become wedged into the seed. Twist the knife a bit to dislodge the seed from the flesh.Finally, slice the avocado by taking the tip of your knife and drawing straight lines through the flesh of each avocado half, making sure the tip of the knife reaches the skin of the avocado. The closer the lines, the thinner the slices. Use a spoon to scoop out the sliced avocado.Advance preparation'),
('21559', '12', 'The onions can be left marinating up to a few days in advance. However, while the oil and vinegar help slow down the browning of the avocado''s flesh, it''s best to slice the avocado shortly before serving.'),
('21559', '13', 'Reprinted with permission from Latin Grilling by Lourdes Castro, © 2011 Ten Speed Press, a division of Random House, Inc.A Miami native, Lourdes Castro has served as a personal chef and nutritionist for high-profile clients, such as Cristina Saralegui and professional athletes, and as an associate of the James Beard Foundation. A highly regarded Latin chef and cooking teacher, Castro is the author of Simply Mexican and Eat, Drink, Think in Spanish. She currently teaches food science at New York University and is the director of the Culinary Academy at the Biltmore Hotel in Coral Gables, Florida. Find out more at Lourdescastro.com'),
('21560', '1', 'Mix everything.'),
('21561', '1', 'Mix sour cream, salsa, cheese and hot pepper sauce in large bowl.'),
('21561', '2', 'Add shrimp; mix lightly.'),
('21561', '3', 'Place 1 avocado half on each salad plate.  Fill evenly with the shimp mixture; sprinkle with cilantro.'),
('21562', '1', 'Process avocados and next 3 ingredients in a blender or food processor until smooth, stopping to scrape down sides.'),
('21562', '2', 'Pour mixture into a large bowl; stir in half-and-half and next 3 ingredients until smooth.'),
('21562', '3', 'Place plastic wrap directly over soup; chill 1 hour.'),
('21562', '4', 'Garnish before serving, if desired.'),
('21562', '5', '*Off-dry white wines such as Gewrztraminer or Chenin Blanc may be substituted.'),
('21563', '1', 'Process avocados and next 3 ingredients in a blender or food processor until smooth, stopping to scrape down sides.'),
('21563', '2', 'Pour mixture into a large bowl; stir in half-and-half and next 3 ingredients until smooth.'),
('21563', '3', 'Place plastic wrap directly over soup; chill 1 hour.'),
('21563', '4', 'Garnish before serving, if desired.'),
('21563', '5', '*Off-dry white wines such as Gewrztraminer or Chenin Blanc may be substituted.'),
('21565', '1', 'Make dressing: In a container with a lid, shake all dressing ingredients until blended.'),
('21565', '2', 'Make salad: Put lettuces, carrot, and radishes in a large bowl. Put remaining ingredients in small bowls.'),
('21565', '3', 'Combine lettuce mixture with half the dressing.'),
('21565', '4', 'Spoon greens onto plates and let each person add toppings and remaining dressing to taste.'),
('21568', '1', 'Heat oil in a skillet over medium-high. While oil is heating, salt and pepper both sides of the chicken.'),
('21568', '2', 'Add chicken to pan and sear 4 or 5 minutes per side, until browned and just cooked through.'),
('21568', '3', 'Remove chicken from pan and let sit for 10 minutes.'),
('21568', '4', 'While chicken is cooling, combine avocado, tomato, scallions, and cilantro in a bowl. Then cut the lime into approximate halves, with one slightly bigger than the other. Squeeze larger half over ingredients in bowl. Stir to combine.'),
('21568', '5', 'Once fairly cooled, chop chicken into 1/2-inch chunks. Squeeze remaining lime over chunks and add to avocado mixture. Stir until combined. (Avocado should cover everything, but shouldn’t itself be annihilated.) Salt and pepper to taste.'),
('21572', '1', 'Combine first 10 ingredients in a bowl; toss gently to combine. Cover and chill 2 hours.'),
('21572', '2', 'Combine 3 tablespoons olive oil, garlic, and salt.'),
('21572', '3', 'Place bread slices on a baking sheet, and brush evenly with olive oil mixture.'),
('21572', '4', 'Bake at 350 for 12 minutes or until toasted; cool.'),
('21572', '5', 'Top each toast evenly with avocado mixture. Sprinkle with cilantro before serving.'),
('21573', '1', 'Toss together first 6 ingredients. Cover and chill 1 hour.'),
('21573', '2', 'Garnish, if desired.'),
('21573', '3', 'Note: For testing purposes only, we used Del Monte SunFresh Citrus Salad and Del Monte SunFresh Tropical'),
('21573', '4', 'Mixed Fruit in Light Syrup With Passion Fruit Juice.'),
('21575', '1', 'Preheat oven to 20'),
('21575', '2', 'In a medium saucepan, heat 1 1/2 in. oil until it registers 375 on a deep-fry thermometer.'),
('21575', '3', 'Meanwhile, mix flour with 1/4 tsp. salt in a shallow plate. Put eggs and panko in separate shallow plates. Dip avocado in flour, shaking off excess. Dip in egg, then panko to coat. Set on 2 plates in a single layer.'),
('21575', '4', 'Fry a quarter of avocado slices at a time until deep golden, 30 to 60 seconds.'),
('21575', '5', 'Transfer slices to a plate lined with paper towels. Keep warm in oven while cooking remaining avocados. Sprinkle with salt to taste.'),
('21580', '1', 'In a bowl, whisk the lemon juice and olive oil. Season with salt and pepper. In another bowl, combine the avocados and scallions with half of the dressing and toss. Arrange the avocados around a large platter or shallow bowl.'),
('21580', '2', 'Add the radishes to the remaining dressing and toss. Mound in the center of the platter. Sprinkle the cilantro over the salad and serve.'),
('21582', '1', 'Assemble sandwiches and enjoy.'),
('21585', '1', 'On a plate, season the avocado with a drizzle of oil and salt and pepper to taste.'),
('21585', '2', 'Spread the butter on the bottom slice of the baguette, and top with the avocado and the ham. Close the sandwich, slice into three or four pieces, and serve.'),
('21587', '1', 'Pit avocados. Scoop flesh into a food processor, add sugar and lemon juice, and whirl until smooth.'),
('21587', '2', 'Add sweetened condensed milk and coconut milk and whirl to blend.'),
('21587', '3', 'Pour mixture into an ice cream maker and freeze according to manufacturer''s instructions. Freeze a metal bowl.'),
('21587', '4', 'Scrape ice cream into cold bowl. Cover and freeze until firm enough to scoop, about 2 hours.'),
('21587', '5', '*For a delicate flavor, buy real coconut milk. For a bigger coconut hit, buy a product made with coconut extract.'),
('21587', '6', 'Make ahead: Freeze airtight up to 2 weeks.'),
('21597', '1', 'Blend dressing, chiles and onions in blender until smooth.'),
('21597', '2', 'Combine avocados and fruit in large bowl.'),
('21597', '3', 'Add dressing mixture; toss to coat.  Stir in 2 Tbsp. coconut and 1 Tbsp. cilantro.'),
('21597', '4', 'Top with remaining coconut and cilantro.'),
('21597', '5', 'Serve with tortilla chips and RITZ Crackers.'),
('21600', '1', 'In medium bowl, stir together salsa ingredients.'),
('21600', '2', 'In another medium bowl, place avocados; coarsely mash. Stir in remaining guacamole ingredients.  Spoon guacamole into shallow serving bowl; top with salsa.'),
('21600', '3', 'Serve with tortilla chips as desired.'),
('21602', '1', 'In a deep saute pan, heat 1 cup of the canola oil over high heat until a deep-frying or candy thermometer reads 375F. In a bowl, combine the crabmeat, onion, scallions, bell pepper, mayonnaise, Tabasco, 1/4 cup of the bread crumbs, the lemon juice, and Worcestershire sauce.'),
('21602', '2', 'Mix until fully incorporated. Form into cakes about 3 inches in diameter and 3/4 inch thick.'),
('21602', '3', 'Place the flour on a plate, and stir in the salt and pepper.'),
('21602', '4', 'Place the beaten egg in a bowl and the remaining 1 cup bread crumbs on another plate. Dredge each crab cake in the flour, then in the egg, and then in the bread crumbs. Lay the cakes in the oil and panfry until each cake has a nice brown crust on both sides, 5 to 6 minutes total.'),
('21602', '5', 'Transfer to paper towels to drain.'),
('21605', '1', 'In a small bowl, whisk together vinegar, oil, salt, and sugar.'),
('21605', '2', 'Cut vanilla bean in half lengthwise, scrape seeds from one half with the back of a paring knife, and add seeds and scraped pod to vinaigrette (reserve other half of pod for another use). Set aside at room temperature for at least 1 hour to let the vanilla flavor develop.'),
('21605', '3', 'Arrange lettuce leaves on a large platter in a single layer. On each leaf, lay 1 or 2 slices of papaya and 1 or 2 slices of avocado.'),
('21605', '4', 'Drizzle vinaigrette over salad.'),
('21605', '5', '*Available at gourmet grocery stores and from hawaiianvanilla.com'),
('21607', '1', 'Chop tomatillos coarsely. Pure half each of tomatillos, onion, and broth in a blender with garlic. Rub through a fine strainer into a stainless steel bowl; discard contents of strainer. Finely chop remaining tomatillos.'),
('21607', '2', 'Add remaining tomatillos, onion, and broth; cucumber; 2 tbsp. lime juice; 2 tsp. hot sauce; and the oregano to bowl and stir.'),
('21607', '3', 'Nest bowl in ice water; stir often until cold, 15 minutes.'),
('21607', '4', 'Add avocado and cilantro and, if you like, more lime juice and hot sauce.'),
('21608', '1', 'In a bowl, roughly mash avocados. Stir in sour cream. Gently fold in tomatoes, jalapeos, garlic, onion, cilantro and lime juice. Season to taste with salt and pepper.'),
('21608', '2', 'var article'),
('21608', '3', 'Type_27_data = {};'),
('21608', '4', 'article'),
('21608', '5', 'Type_27_data.init_step_by_step_images = 0;'),
('21622', '1', 'Mash avocados in medium bowl.'),
('21622', '2', 'Add remaining ingredients; mix well.'),
('21624', '1', 'Cut the corn kernels off the cobs into a large pot, scraping the cobs to re-lease all the milky juice. Break each cob in two or three pieces. Put all thecobs into the pot along with the milk.'),
('21624', '2', 'Add red pepper flakes and season with salt and pepper. Bring to a simmer over medium heat. Adjust the heat to maintain a very low simmer, cover, and cook for 30 minutes.'),
('21624', '3', 'Using tongs, remove and discard the cobs. Purée the soup in a food processor, then strain it through a fine-mesh sieve into a bowl. Rinse out the pot then pour the puréed soup back in the pot. Taste, season with salt and pepper, then refrigerate the soup until cold.'),
('21624', '4', 'Pour the soup into individual chilled bowls.'),
('21624', '5', 'Garnish, dividing the lobsterand avocado cubes between the bowls.'),
('21624', '6', 'Serve with a squeeze of lime and lots of chopped cilantro.'),
('21625', '1', 'Combine ingredients.'),
('21626', '1', 'Peel and seed papayas; cut lengthwise into 1/2-inch-thick slices. Peel and rinse jicama; cut into matchstick- size strips about 1/8 inch thick and 3 inches long. Pit and peel avocados; cut lengthwise into thin slices.'),
('21626', '2', 'In a small pitcher or bowl, mix orange juice, lime juice, rice vinegar, and salt.'),
('21626', '3', 'Arrange papaya and avocado slices on a rimmed platter. Top with jicama and drizzle with sour orange dressing.'),
