INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('10368', '6', 'In a food processor, pulse the pistachios with the garlic until coarsely chopped.'),
('10368', '7', 'Add the parsley and broccoli rabe and pulse until finely chopped.'),
('10368', '8', 'Add the olive oil and process until incorporated. Stir in the Pecorino, season with salt and pepper and serve.'),
('10372', '1', 'Cook the linguine according to the package directions. Meanwhile, in a large saucepan, over medium heat, fry the bacon until crisp, about 4 minutes.'),
('10372', '2', 'Transfer to a paper towel. Spoon off all but 1 tablespoon of the drippings from the pan, reserving the rest.Return pan to medium heat, add the garlic and broccoli rabe, and toss.'),
('10372', '3', 'Add the broth and bring to a boil. Reduce heat and simmer until the broccoli rabe is tender, about 3 minutes. Stir in the corn, either the reserved bacon drippings or the butter, the salt, and pepper.'),
('10372', '4', 'Add the drained linguine and toss.'),
('10372', '5', 'Heat until warmed through, about 3 minutes.'),
('10372', '6', 'Remove from heat. Sprinkle with the Parmesan and reserved bacon and toss.Tip: Broccoli rabe has a bitter flavor that many people find pleasing. If you''re not one of them, use a 5-ounce bag of fresh spinach instead.'),
('10372', '7', 'Add it to the pan, one handful at a time, along with the linguine.'),
('10374', '1', 'Heat the oil from sun-dried tomatoes in a large skillet over medium-high heat.'),
('10374', '2', 'Add chicken and cook 3 to 5 minutes, until golden brown on all sides.'),
('10374', '3', 'Add tomatoes, broccoli rabe, olives, and 1/4 cup water, season with salt and pepper, cover and cook 3 minutes, until broccoli rabe wilts and chicken is cooked through.'),
('10374', '4', 'Remove from heat, transfer to a serving plate and top with feta cheese. Usually served with capellini pasta or rice.'),
('10376', '1', 'Combine flour, cornstarch, and spices in a medium bowl. In another bowl, mix olive oil with 1 1/2 cups cold water. Slowly whisk into flour mixture until smooth. Cover and chill at least 1 hour.'),
('10376', '2', 'Pour 2 in. vegetable oil into a large, wide pot. Insert a deep-fry thermometer and heat over high heat to 375, then reduce heat to medium to maintain temperature.'),
('10376', '3', 'Meanwhile, whisk whites with a mixer until soft peaks form. Using a rubber spatula, fold whites into batter.'),
('10376', '4', 'Dip 1 stalk broccoli rabe at a time into batter, then carefully lower into hot oil. Cook, turning once, until golden, about 5 minutes.'),
('10376', '5', 'Transfer to a paper towel-lined baking sheet. Sprinkle with salt while warm. Dip and fry lemon slices the same way.'),
('10376', '6', 'Serve both warm or at room temperature with lemon wedges.'),
('10377', '1', 'Cook pasta as package directs. Meanwhile, in a large frying pan over medium-high heat, brown sausages in oil, stirring to break up, about 5 minutes.'),
('10377', '2', 'Add shallot and garlic and cook until fragrant, about 1 minute.'),
('10377', '3', 'Pour in vinegar and scrape pan to loosen browned bits.'),
('10377', '4', 'Add broccoli rabe, sprinkle with 1/4 tsp. salt and the pepper, and cook, covered, until bright green and tender-crisp, about 2 minutes.'),
('10377', '5', 'Drain pasta, reserving 1/2 cup cooking water. Return pasta to pot along with sausage mixture.'),
('10377', '6', 'Add a little reserved water if pasta seems dry. Season with salt to taste and serve with parmesan.'),
('10380', '1', 'Cook the pasta according to the package directions. Meanwhile, in a large saucepan, over medium heat, heat the oil.'),
('10380', '2', 'Add the sausage and cook, crumbling it with a spoon, until browned, about 5 minutes.'),
('10380', '3', 'Add the garlic and cook for 1 minute more.'),
('10380', '4', 'Add the broth and red pepper and bring to a boil. Then add the broccoli rabe, cover, and cook until tender, about 3 minutes. Stir in the butter and Parmesan and cook, uncovered, until the sauce thickens slightly, about 2 minutes.'),
('10380', '5', 'Add the drained pasta, season with the salt and black pepper, and toss to combine.Tip: Broccoli rabe, a leafy distant cousin of broccoli, has a bitter flavor and smaller florets. For a milder alternative, substitute broccoli. For a more peppery bite, try arugula, Swiss chard, or beet greens.'),
('10383', '1', 'Bring 4 quarts water to a boil in a large Dutch oven.'),
('10383', '2', 'Add broccoli rabe to pan. cook 2 minutes.'),
('10383', '3', 'Remove with a slotted spoon. drain well. Coarsely chop. Return water to a boil.'),
('10383', '4', 'Add pasta to pan. cook according to package directions, omitting salt and fat.'),
('10383', '5', 'Drain in a colander over a bowl. reserve 3/4 cup pasta water. Cook bacon in a large skillet over medium heat until crisp.'),
('10383', '6', 'Remove bacon from pan, reserving 1 tablespoon drippings in pan. crumble bacon. Increase heat to medium-high.'),
('10383', '7', 'Add garlic and chickpeas to drippings in pan. saut 2 minutes or until garlic is golden. Stir in broccoli rabe, 1/2 teaspoon salt, and 1/4 teaspoon freshly ground black pepper. cook 3 minutes or until broccoli rabe is heated. Stir in pasta, 3/4 cup pasta water, and bacon. toss well.'),
('10387', '1', 'Cook broccoli rabe in boiling water 4 minutes.'),
('10387', '2', 'Remove broccoli rabe with a slotted spoon, and place in a colander. drain.'),
('10387', '3', 'Add gnocchi to pan. cook 3 minutes or until done.'),
('10387', '4', 'Drain gnocchi in a colander over a bowl, reserving 1/4 cup cooking liquid.'),
('10387', '5', 'Heat oil in a large nonstick skillet over medium heat.'),
('10387', '6', 'Add garlic to pan. cook 3 minutes or until lightly browned, stirring frequently.'),
('10387', '7', 'Add broccoli rabe, gnocchi, and reserved cooking liquid to pan. cook 2 minutes. Stir in salt and pepper.'),
('10387', '8', 'Place 1 1/4 cups gnocchi mixture in each of 4 shallow bowls. top each serving with 1 tablespoon cheese.'),
('10389', '1', 'In a blender, combine 1 cup olive oil, basil, red pepper flakes and 2 cloves garlic. Puree until blended and thick.'),
('10389', '2', 'Pour into a shallow baking dish and add the chicken. Toss to coat and marinate the chicken while finishing the dish.'),
('10389', '3', 'Bring a large pot of water to a boil. Preheat a grill or grill pan to medium heat.'),
('10389', '4', 'Meanwhile, heat a large skillet. Crush 3 garlic cloves and set aside.'),
('10389', '5', 'Heat 1 cup olive oil in the skillet.'),
('10389', '6', 'Add the garlic and cook until golden.'),
('10389', '7', 'Remove sausage from casings and add to the skillet.'),
('10389', '8', 'Saute the sausage until browned.'),
('10389', '9', 'In the boiling water, blanch the broccoli rabe until just soft but still crunchy.'),
('10389', '10', 'Transfer rabe to a bowl of ice water.'),
('10389', '11', 'Remove from water, drain on paper towel-lined plate and set aside.'),
('10389', '12', 'Grill the chicken until cooked through and juices run clear.'),
('10389', '13', 'To the browned sausage, add the mushrooms and saute until mushrooms start getting soft.'),
('10389', '14', 'Add the rabe, the chicken stock and a pinch of red pepper flakes and season with salt and pepper.'),
('10389', '15', 'Slice the bread and lay out on a serving plate. Spoon some of the broccoli rabe/sausage mixture over top, then cover each with 1 chicken breast and 1 thigh. Top with arugula, tomatoes and sliced provolone cheese. Then drizzle some of the broccoli rabe sauce over top, to wilt the arugula, and serve immediately.'),
('10393', '1', 'Cook broccoli rabe in boiling water 2 minutes.'),
('10393', '2', 'Remove with a slotted spoon and plunge into ice water. drain well. Coarsely chop. Return water to boil.'),
('10393', '3', 'Add pasta. cook according to package directions, omitting salt and fat.'),
('10393', '4', 'Drain pasta in a colander over a bowl, reserving 1/4 cup cooking liquid.'),
('10393', '5', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('10393', '6', 'Remove casings from sausage.'),
('10393', '7', 'Add sausage to pan. cook 4 minutes or until browned, stirring to crumble.'),
('10393', '8', 'Add garlic. saut 1 minute. Stir in broccoli rabe. cook 1 minute, stirring frequently. Stir in pasta, reserved cooking liquid, 1/2 teaspoon salt, and 1/4 teaspoon freshly ground black pepper. cook 1 minute or until thoroughly heated.'),
('10393', '9', 'Serve immediately.'),
('10401', '1', 'Make dough: Put yeast, oil, and 2 cups plus 1 tbsp. cold tap water in bowl of a stand mixer and mix, using dough hook, on lowest speed, 5 minutes or until yeast has completely dissolved.'),
('10401', '2', 'Add flour and mix another 8 minutes.'),
('10401', '3', 'Cover bowl loosely with a dampened towel and let dough rise 20 minutes.'),
('10401', '4', 'Add salt and mix on low speed until incorporated and dissolved, about 7 minutes.'),
('10401', '5', 'Turn dough onto a lightly floured work surface and cut into 6 equal portions.'),
('10401', '6', 'Roll each portion with a circular pressing motion into a tight ball.'),
('10401', '7', 'Place on a lightly floured baking sheet.'),
('10401', '8', 'Cover tightly with plastic wrap and let rise at least 4 hours at warm room temperature. Dough balls have risen properly when they are soft, pillowy, and full of air.'),
('10401', '9', 'Heat a pizza stone or baking sheet on lowest rack of oven at 550 (or as high as oven will go), at least 30 minutes.'),
('10401', '10', 'Make toppings: With flat side of a chef''s knife, mash a third of mozzarella until pulverized. Dice remaining mozzarella into 1/2-in. cubes. In a medium bowl, mix both mozzarellas with mozzarella liquid, caciocavallo, cream, and buttermilk. Season with 1/4 tsp. salt.'),
('10401', '11', 'Cut broccoli rabe into 1-in. sections, discarding tough lower stems.'),
('10401', '12', 'In a large frying pan over very low heat, cook garlic in oil, stirring often, until it starts to turn transparent, about 5 minutes.'),
('10401', '13', 'Add chile flakes and toast for a second, then add broccoli rabe. Stir in remaining 1/4 tsp. salt and several grinds of pepper.'),
('10401', '14', 'Crank heat to medium-high and cook broccoli rabe, stirring, until liquid starts to evaporate and broccoli rabe is tender-crisp, 5 to 7 minutes (don''t cook it to mush). If liquid is gone and broccoli rabe is still too crunchy, add water in 1/4-cup increments and cook until tender-crisp.'),
('10401', '15', 'Working with 1 dough ball at a time (keep the rest tightly covered), set on a well-floured pizza peel or baking sheet. To stretch into an 11- to 12-in. circle, first tap down center of ball with your fingertips to gently deflate it. Next, push it outward from the center with your fingertips. Then pick up the dough circle and, holding it under the rim, turn it like a steering wheel, letting the gravity of the dough help it stretch. Drape the dough over the backs of your hands and gently stretch outward, rotating periodically. Flop the stretched dough down onto the pizza peel.'),
('10401', '16', 'Spread about 2/3 cup cheese mixture evenly over dough. Top with 1/2 cup broccoli rabe, a generous pinch chile flakes, and 2 tbsp. olives. Give peel a good shake every few seconds to keep dough from sticking.'),
('10401', '17', 'Plant tip of pizza peel (or long edge of baking sheet) on pizza stone and shove pizza quickly onto stone (or preheated sheet).'),
('10401', '18', 'Bake 5 to 6 minutes, or until puffy and browned.'),
('10401', '19', 'Drizzle with extra-virgin olive oil. Repeat with 2 dough balls and toppings (top remaining 3 differently or freeze).'),
('10401', '20', 'Make ahead: Form dough into balls (through step'),
('10401', '21', 'and chill overnight, tightly covered with plastic wrap, instead of letting rise on counter (it will rise slowly in the fridge). You can also freeze dough for up to 2 weeks. let chilled or frozen dough come to room temperature before stretching. Make cheese topping and broccoli rabe topping up to 1 day ahead and chill, covered.'),
('10401', '22', '*Find at well-stocked grocery stores and Italian markets.'),
('10401', '23', '**While Delfina uses 3 tbsp. of kosher salt, in our tests 1 1/2 tbsp. kosher salt also delivered a well-seasoned crust. If you''re concerned about sodium intake, you can successfully use the lower amount.'),
('10405', '1', 'Boil plum wine in heavy medium saucepan until syrupy and reduced to generous 1/3 cup, about 16 minutes. (Can be made 1 day ahead.'),
('10405', '2', 'Let stand at room temperature. Rewarm over low heat before using.)'),
('10405', '3', 'Using heavy large knife, cut each duck lengthwise in half.'),
('10405', '4', 'Cut away backbone.'),
('10405', '5', 'Cut off leg-thigh pieces, then cut off breast pieces. trim excess fat.'),
('10405', '6', 'Remove bones from breast pieces.'),
('10405', '7', 'Transfer leg-thigh pieces and breast pieces to platter (reserve remaining duck trimmings for another use).'),
('10405', '8', 'Preheat oven to 375F.'),
('10405', '9', 'Mix Chinese five-spice powder, salt, ground black pepper, and ground ginger in small bowl. Rub spice mixture all over duck pieces.'),
('10405', '10', 'Heat olive oil in heavy large ovenproof skillet over medium-high heat.'),
('10405', '11', 'Add leg-thigh pieces and cook until deep brown, about 4 minutes per side. Cover skillet and roast duck in oven until cooked through, about 45 minutes.'),
('10405', '12', 'Transfer duck to plate. cover with foil to keep warm.'),
('10405', '13', 'Heat same skillet over medium-high heat.'),
('10405', '14', 'Add duck breasts to skillet. cook to desired doneness, about 10 minutes per side for medium.'),
('10406', '1', 'Preheat the oven to 42'),
('10406', '2', 'Lightly oil an 8-by-11 1/2-inch or 9-by-13-inch baking dish. In a medium saucepan, bring the chicken stock and 2 cups of water to a boil.'),
('10406', '3', 'Add 1 teaspoon of salt. Gradually whisk in the cornmeal until smooth. Cook over moderate heat, stirring with a wooden spoon, until thickened, about 10 minutes.'),
('10406', '4', 'Pour the polenta into the baking dish and smooth the top. brush with 1 tablespoon of olive oil.'),
('10406', '5', 'Bake for 1 hour and 15 minutes, until the top and bottom are golden and crusty.'),
('10406', '6', 'Meanwhile, in a large, deep skillet, heat the remaining 3 tablespoons of olive oil until shimmering.'),
('10406', '7', 'Add the pancetta and cook over moderately high heat until golden, 4 to 5 minutes.'),
('10406', '8', 'Add the onion, garlic and crushed red pepper and cook until the onion softens.'),
('10406', '9', 'Add the broccoli rabe and the remaining 1/4 cup of water, season with salt and pepper and toss gently. Cover and cook until softened, 5 minutes. Uncover and cook, stirring occasionally, until the water has evaporated and the broccoli rabe is tender, 2 minutes longer.'),
('10406', '10', 'Cut the polenta into 6 pieces and transfer to plates. Stir half of the Pecorino into the broccoli rabe and spoon it over the polenta. Sprinkle with the remaining Pecorino and serve.'),
('10407', '1', 'Heat oil in a Dutch oven over medium-high heat. add chickpeas and saut 2 minutes or until they''re just beginning to brown.'),
('10407', '2', 'Add garlic and crushed red pepper and saut 30 seconds.'),
('10407', '3', 'Add broccoli rabe and chicken broth to pan. bring to a simmer and cook 3 minutes or until broccoli rabe is crisp-tender.'),
('10407', '4', 'Stir in hot pasta and salt. cook 2 minutes or until heated throughout.'),
('10407', '5', 'Divide among 4 shallow bowls, and top each with Parmesan cheese.'),
('10414', '1', 'Heat 2 tablespoons extra-virgin olive oil in heavy large skillet over medium heat.'),
('10414', '2', 'Add sausages. Cover skillet and cook until sausages are brown and cooked through, about 8 minutes per side.'),
('10414', '3', 'Transfer sausages to plate. tent with foil to keep warm.'),
('10414', '4', 'Add garlic to drippings in same skillet and stir 30 seconds.'),
('10414', '5', 'Add broccoli rabe and 1/2 cup broth. Cover skillet and cook until broccoli rabe is crisp-tender, about 8 minutes.'),
('10414', '6', 'Meanwhile, heat 2 tablespoons oil in heavy large saucepan over medium heat.'),
('10414', '7', 'Add polenta. mash with potato masher until smooth.'),
('10414', '8', 'Mix in remaining 1/2 cup broth and cheese. Simmer until polenta is warmed through, about 5 minutes. Season polenta with salt and pepper.'),
('10414', '9', 'Spoon polenta onto 2 plates. Top with sausages and broccoli rabe.'),
('10415', '1', 'Heat oil in heavy large skillet over medium-high heat.'),
('10415', '2', 'Add leeks and saute until golden and soft, about 5 minutes.'),
('10415', '3', 'Add broccoli rabe and saute, tossing with tongs, until slightly softened and bright green, about 3 minutes.'),
('10415', '4', 'Add garlic and stir 1 minute. Stir in broth, crme frache, and lemon peel, then 1/3 cup cheese.'),
('10415', '5', 'Season to taste with salt and pepper. Meanwhile, cook pasta in large pot of boiling salted water until just tender but still firm to bite, stirring occasionally.'),
('10415', '6', 'Drain, reserving 1 cup pasta cooking liquid. Return pasta to pot. Stir in broccoli rabe mixture and walnuts, adding  1/2 cup cooking liquid to moisten and adding more by tablespoonfuls if needed. Divide pasta among bowls.'),
('10415', '7', 'Serve, passing remaining cheese separately.'),
('10415', '8', '*An Italian leafy green vegetable with scattered clusters of tiny, broccoli-like florets. available at some supermarkets and at specialty foods stores.'),
('10417', '1', 'Put the cornmeal into a bowl. Slowly add 3 cups of water, stirring with a wooden spoon as you do so.'),
('10417', '2', 'Put 4 1/2 cups water into a large pot and bring to a boil over medium high heat.'),
('10417', '3', 'Add the salt. Stir the cornmeal mixture again and then slowly pour it into the boiling water, stirring with a wooden spoon as you do so. Bring to a boil, stirring all the time. The mixture will thicken very quickly into a homogeneous paste. Quickly pour this paste into the baking dish, smooth over the top with the back of your wooden spoon, cover, and bake for 50 minutes.'),
('10417', '4', 'Serve as is (perhaps stirring in a small slice of butter or some grated cheese) or cool, cover, and refrigerate. Polenta that has cooled will firm up and may be toasted or fried.'),
('10417', '5', 'Broccoli Rabe with Garlic'),
('10417', '6', '- serves 4 -'),
('10417', '7', 'Cut the coarse stems off the broccoli rabe and wash it well. Bring a large pot of water to a rolling boil. Put 2 teaspoons salt into the water and then add the broccoli rabe. Cover, bring to a boil again, and boil rapidly for 2 minutes, or until just tender.'),
('10417', '8', 'Drain and rinse immediately under cold running water.'),
('10417', '9', 'Drain and set aside until just before eating.'),
('10417', '10', 'Put the oil and garlic into a large frying pan and set over medium heat. When the oil begins to sizzle and the garlic turns a light golden color, put in the broccoli rabe. Sprinkle with about 1/2 teaspoon salt and the chile flakes and stir gently to mix. Turn the heat to low and turn the greens gently until heated through.'),
('10418', '1', 'Cook pasta in large pot of boiling salted water 3 minutes.'),
('10418', '2', 'Add broccoli rabe and boil until broccoli rabe is just crisp-tender and pasta is just tender but still firm to bite, stirring occasionally, about 5 minutes longer.'),
('10418', '3', 'Drain pasta and broccoli rabe, reserving 1/2 cup cooking liquid. Return pasta and broccoli rabe to pot.'),
('10418', '4', 'Meanwhile, bring vegetable broth and crushed red pepper to simmer in medium saucepan.'),
('10418', '5', 'Add beans and simmer until beans are heated through, stirring frequently, about 5 minutes.'),
('10418', '6', 'Add bean mixture, pesto, and vinegar to pasta and broccoli rabe. Stir well, adding pasta cooking liquid by tablespoonfuls if necessary. Season with salt and pepper.'),
('10418', '7', 'Serve in shallow bowls.'),
('10419', '1', 'Trim stem ends from broccoli rabe and discard.'),
('10419', '2', 'Cut remainder crosswise into  1 1/2-inch pieces.'),
('10419', '3', 'Cook broccoli rabe and peas in a 4- to 6-quart pot of boiling salted water until broccoli rabe is wilted and stems are crisp-tender, 2 to 3 minutes.'),
('10419', '4', 'Drain well in a colander.'),
('10419', '5', 'Heat oil with garlic in a 12-inch heavy skillet over moderately high heat, turning garlic frequently, until garlic is golden, 1 to 2 minutes, then discard garlic.'),
('10419', '6', 'Add broccoli rabe, peas, salt, and pepper to skillet and saute, stirring, until well coated with garlic oil, about 2 minutes.'),
('10422', '1', 'Preheat the oven to 375F.'),
('10422', '2', 'Pour the oil into a large skillet set over medium heat.'),
('10422', '3', 'Add the onions and cook until very soft, about 5 minutes.  Dump in the tomatoes and the oregano and thyme.  Cook, breaking up the large pieces of tomato with a wooden spoon, for about 20 minutes.  Season with salt and pepper to taste.'),
('10422', '4', 'Meanwhile, bring a large pot of water to a boil.  Roughly chop the broccoli rabe.'),
('10422', '5', 'Add to the water and cook for about 1 minute.'),
('10422', '6', 'Remove with some tongs and drain in a colander.  Rinse under cold water to stop the cooking.'),
('10422', '7', 'Return the large pot of water to a boil and add the pasta.  Cook until very al dente, about 3 minutes less than the package says.'),
('10422', '8', 'Drain and rinse under cold water to stop the cooking.  Set aside.'),
('10422', '9', 'Form the Italian sausage into 1-inch balls.'),
('10422', '10', 'Saute them in a large skillet set over medium-high heat.  There should be enough fat from the sausage, but if the meat sticks then add a drizzle of oil.  Cook until browned on a all sides.'),
('10422', '11', 'Add to the tomato sauce.'),
('10422', '12', 'Rub some butter on the inside of a casserole dish.  Dump in the pasta and broccoli rabe.'),
('10422', '13', 'Pour on the sauce.  Top with a sprinkling of the mozzarella.'),
('10422', '14', 'Bake for about 30 minutes, or until the cheese is bubbling.'),
('10423', '1', 'Preheat oven to 400F.'),
('10423', '2', 'Cook broccoli rabe in boiling salted water 5 minutes, then drain in a colander.'),
('10423', '3', 'Meanwhile, cook sausage meat in an ovenproof heavy skillet (preferably cast-iron) over moderately high heat, breaking up meat with a spoon, until browned and crisp.'),
('10423', '4', 'Transfer with a slotted spoon to a large bowl.'),
('10423', '5', 'Add oil and garlic to skillet and cook over moderate heat, stirring, until garlic is golden, about 1 minute.'),
('10423', '6', 'Add broccoli rabe and cook, stirring, 3 minutes.'),
('10423', '7', 'Add salt, then pepper to taste.'),
('10423', '8', 'Add to sausage with spaghetti, cheese, and eggs. Toss well and spoon mixture into skillet, spreading to smooth top.'),
('10423', '9', 'Bake in middle of oven until center is set but still moist, 20 to 25 minutes.'),
('10423', '10', 'Let stand 5 minutes before cutting into wedges.'),
('10427', '1', 'Watch how to make this recipe.'),
('10427', '2', 'Preheat oven to 375 degrees F.'),
('10427', '3', 'Toss the pumpkin with olive oil and salt and place in a single layer on a sheet tray and bake in the oven until soft, about 20 minutes.'),
('10427', '4', 'Remove from oven and reserve.'),
('10427', '5', 'Bring a large pot of well-salted water to a boil. Set up a bowl of well-salted ice water.'),
('10427', '6', 'Drop the broccoli rabe into the pot of boiling water, swirl it around, remove from the water, and immediately plunge into the salty ice water. Reserve the boiling water to cook the pasta in.'),
('10427', '7', 'Remove the broccoli rabe from the ice water, squeeze out excess water, and reserve.'),
('10427', '8', 'Coat a large saute pan with olive oil and add the pancetta and crushed red pepper. Bring the pan to a medium heat and cook the pancetta until brown and crispy. When the pancetta is brown and crispy add the roasted squash and about 3/4 cup of the broccoli rabe cooking water. Simmer until the water reduces by half.'),
('10427', '9', 'Add the orecchiette to the reserved boiling broccoli rabe water and cook until the pasta is al dente, about 1 minute less than the cooking time says on the box.'),
('10427', '10', 'Remove the pasta from the water and add to the pan with the pancetta and squash.'),
('10427', '11', 'Add the broccoli rabe and about a 1/2 cup of the pasta cooking water. Cook until the water has evaporated and the sauce clings to the pasta.'),
('10427', '12', 'Drizzle with olive oil and sprinkle with the grated Parmigiana. Toss or stir vigorously.'),
('10427', '13', 'Divide the pasta between 2 serving dishes, sprinkle with a little more grated parm, and top with toasted green pumpkin seeds.'),
('10427', '14', 'Delicioso!!'),
('10429', '1', 'Cook broccoli rabe in boiling water 1 1/2 minutes. drain and rinse with cold water.'),
('10429', '2', 'Drain well.'),
('10429', '3', 'Place in a large bowl. Set aside.'),
('10429', '4', 'Heat a large skillet over medium-high heat.'),
('10429', '5', 'Add 1 tablespoon olive oil to pan. swirl to coat.'),
('10429', '6', 'Add sausage. cook for 6 minutes or until browned, stirring to crumble.'),
('10429', '7', 'Add grapes, 1/8 teaspoon salt, and 1/8 teaspoon pepper. cook for 2 minutes or until grapes begin to soften.'),
('10429', '8', 'Add sausage mixture to broccoli rabe.'),
('10429', '9', 'Return pan to medium-high heat.'),
('10429', '10', 'Add remaining 1 tablespoon oil to pan. swirl to coat.'),
('10429', '11', 'Add onion. cook 2 minutes or until soft.'),
('10429', '12', 'Add garlic. cook 30 seconds or until fragrant.'),
('10429', '13', 'Add wine. cook 2 minutes or until liquid almost evaporates.'),
('10429', '14', 'Add remaining 1/8 teaspoon salt, remaining 1/8 teaspoon pepper, sausage mixture, and vinegar. Toss to combine. cook 1 minute or until thoroughly heated. Sprinkle with cheese. serve immediately.'),
('10431', '1', 'Lay the pancetta on a baking sheet lined with plastic wrap and freeze until firm. Finely chop the pancetta, then transfer it to a food processor and pulse until minced.'),
('10431', '2', 'In a large bowl, combine the ground pork, veal and beef with the minced pancetta. In a small bowl, combine 1 teaspoon of salt with the cinnamon, allspice, cloves and nutmeg. Sprinkle the spices over the meat and mix thoroughly but gently with your hands. Pat the meat into 6 burgers and refrigerate.'),
('10431', '3', 'Light a grill. In a large pot of boiling salted water, cook the broccoli rabe until just tender, about 2 minutes.'),
('10431', '4', 'Drain, lightly squeeze out any excess water and coarsely chop.'),
('10431', '5', 'Heat the olive oil in a large skillet.'),
('10431', '6', 'Add the garlic and crushed red pepper and cook over moderate heat until fragrant, about 1 minute.'),
('10431', '7', 'Add the broccoli rabe and cook, stirring, until heated through. Season with salt and pepper.'),
('10431', '8', 'Season the burgers with pepper and grill over a hot fire until just cooked through, about 5 minutes per side. Melt the Fontina on the burgers about 1 minute before they are done. Spoon the broccoli rabe onto the bottom buns, then set the burgers on top. Close the sandwiches and serve at once.'),
('10437', '1', 'Cook pasta in large saucepan as directed on package, omitting salt and adding broccoli rabe to the boiling water for the last 3 min.'),
('10437', '2', 'Meanwhile, heat oil in large skillet on medium-high heat.'),
('10437', '3', 'Add chicken and garlic. cook and stir 6 to 8 min. or until chicken is done.'),
('10437', '4', 'Drain pasta mixture.'),
('10437', '5', 'Mix cream cheese spread, milk and Italian seasoning until blended.'),
('10437', '6', 'Add to chicken mixture along with the pasta mixture. mix well.  Cook 2 to 3 min. or until heated through, stirring frequently.  Sprinkle with Parmesan.'),
('10439', '1', 'Cook broccoli rabe in a large pot of boiling water 2 minutes or until crisp-tender. drain.'),
('10439', '2', 'Heat a large skillet over medium-high heat.'),
('10439', '3', 'Add oil to pan. swirl to coat.'),
('10439', '4', 'Add bacon. saut 3 minutes, stirring frequently. Stir in onion, oregano, and red pepper. saut 4 minutes or until onion begins to soften, stirring occasionally.'),
('10439', '5', 'Add garlic. saut 30 seconds, stirring constantly.'),
('10439', '6', 'Add chickpeas. saut 1 minute. Stir in broccoli rabe, salt, and black pepper. cook 2 minutes or until thoroughly heated, tossing to combine.'),
('10439', '7', 'Place about 1 1/2 cups chickpea mixture on each of 4 plates. shave 1/2 ounce cheese evenly over each serving.'),
('10441', '1', 'Bring 6 quarts water and 2 teaspoons salt to a boil in a large stockpot. Stir in pasta. partially cover, and return to a boil, stirring frequently. Cook 8 minutes or until pasta is almost al dente, stirring occasionally.'),
('10441', '2', 'Drain pasta in a colander over a bowl, reserving 2 cups cooking water.'),
('10441', '3', 'While pasta cooks, heat oil in a Dutch oven over medium-high heat.'),
('10441', '4', 'Add garlic and prosciutto. cook 1 minute, stirring constantly.'),
('10441', '5', 'Add pepper. cook 2 1/2 minutes or until prosciutto is crisp, stirring frequently.'),
('10441', '6', 'Add reserved 2 cups cooking water and chickpeas. bring to a boil.'),
('10441', '7', 'Add broccoli rabe (do not stir). cover, reduce heat, and simmer 7 minutes or until broccoli rabe is tender. Uncover. simmer 15 minutes or until liquid almost evaporates.'),
('10441', '8', 'Add pasta, and cook 1 minute or until pasta is al dente, tossing to combine.'),
('10441', '9', 'Remove from heat. stir in cheese.'),
('10441', '10', 'Serve immediately.'),
('10442', '1', 'Watch how to make this recipe.'),
('10442', '2', 'In a medium pot, bring a few inches of water to a boil over medium heat, then salt the water. Trim the broccoli rabe and cut it into 1 1/2 to 2-inch lengths. Simmer in boiling water to reduce the bitterness, about 4 to 5 minutes, then cold shock in ice water and drain very well.'),
('10442', '3', 'Heat a Dutch oven or large soup pot over medium-high heat with extra-virgin olive oil, a turn of the pan.'),
('10442', '4', 'Add the sausage and brown and crumble, 7 to 8 minutes.'),
('10442', '5', 'Add the onions, garlic and chile and cook a few minutes more.'),
('10442', '6', 'Add the thyme and lemon zest, then add broccoli rabe and season with a little nutmeg. Stir in the stock and the water and bring to a boil. Simmer a few minutes to combine the flavors. Turn off the heat, cool and store for a make-ahead meal. Reheat the stoup over low heat and bring to a low boil.'),
('10442', '7', 'Add the pasta and cook to al dente, about 10 minutes. Ladle the stoup in shallow bowls and garnish with cheese.'),
('10442', '8', 'Serve with crusty bread for mopping.'),
('10445', '1', 'Blend together eggs, milk, flour, and salt in a blender until smooth.'),
('10445', '2', 'Transfer to a bowl.'),
('10445', '3', 'Lightly brush a 10-inch nonstick skillet with melted butter and heat over moderate heat until hot but not smoking. Ladle about 1/4 cup batter into skillet, tilting and rotating skillet to coat bottom, then pour excess batter back into bowl. (If batter sets before skillet is coated, reduce heat slightly for next crespella.) Cook until just set and underside is lightly browned, about 30 seconds, then invert crespella onto a clean kitchen towel to cool completely. (It will be cooked on one side only.) Make 5 more crespelle with remaining batter in same manner, brushing skillet with melted butter as needed.'),
('10446', '1', 'In a skillet over moderate heat, combine oil, butter and flour. Cook 2 or 3 minutes.'),
('10446', '2', 'Whisk in broth.'),
('10446', '3', 'Add the sliced veal in thickened sauce 3 or 4 minutes and transfer to a warm platter. Season veal with salt and pepper.'),
('10446', '4', 'Add lemon zest, lemon juice and chopped parsley to the sauce and remove pan from heat.'),
('10446', '5', 'Heat water for broccoli rabe. Blanch until just cooked but still crispy.'),
('10446', '6', 'Drain broccoli rabe.'),
('10446', '7', 'Place a second skillet over medium high heat.'),
('10446', '8', 'Add extra-virgin olive oil, garlic, and broccoli rabe and cook until tender. Season with salt, pepper and nutmeg.'),
('10446', '9', 'To assemble, divide broccoli rabe between 2 dinner plates. Top with veal and pour pan sauce equally over the 2 plates.'),
('10447', '1', 'FIRST Prepare the Barbecued Pork as directed in the recipe.'),
('10447', '2', 'SECOND Trim the stem ends and wilted leafy ends of the broccoli rabe and discard. If using Western broccoli, with a sharp paring knife cut away the stem ends and peel away the tough outer skin and separate the florets.'),
('10447', '3', 'Cut the broccoli stems on the diagonal into 1-inch sections.'),
('10447', '4', 'THIRD Bring 3 quarts of water to a boil, drop in the broccoli, partially cook for 2 minutes, or until just tender, remove with a slotted strainer, and refresh in cold water.'),
('10447', '5', 'Drain and set aside. Bring the water back to a boil, add the noodles, stir, and cook 5 to 6 minutes, until nearly tender.'),
('10447', '6', 'Drain in a colander, rinse lightly to remove the starch, and drain again thoroughly in a colander. Put in a bowl and toss lightly with the mixed toasted sesame and olive oils.'),
('10447', '7', 'Spread the noodles out on a large baking sheet.'),
('10447', '8', 'FOURTH'),
('10447', '9', 'Heat the broiler until red-hot.'),
('10447', '10', 'Place the noodles 3 inches under the broiler and cook about 10 minutes on each side, until golden brown, flipping them over once. Turn off the broiler and keep the noodles warm in the oven.'),
('10447', '11', 'FIFTH'),
('10447', '12', 'Heat a wok or large skillet, add the 2 tablespoons oil, and heat until very hot, about 15 seconds.'),
('10447', '13', 'Add the garlic, ginger, and scallion greens and stir-fry about 30 seconds, until very fragrant.'),
('10447', '14', 'Add the Sauce and cook over medium heat until it thickens.'),
('10447', '15', 'Add the barbecued pork and cooked broccoli and toss gently in the sauce.'),
('10447', '16', 'Place the browned noodles on a deep platter or in a large pasta bowl and spoon the pork, broccoli, and sauce on top.'),
('10447', '17', 'Serve immediately.'),
('10447', '18', 'var article'),
('10447', '19', 'Type_27_data = {}.'),
('10447', '20', 'article'),
('10447', '21', 'Type_27_data.init_step_by_step_images = 0.'),
('10448', '1', 'Sprinkle chicken all over with 2 teaspoonscoarse kosher salt.'),
('10448', '2', 'Place chicken, breastside up, on rack set in roasting pan.Refrigerate uncovered overnight.'),
('10448', '3', 'Place parsley sprigs and 1/2 lemon inchicken cavity. Tie legs together.'),
('10448', '4', 'Placereserved heart and gizzard and garliccloves under rack in roasting pan.'),
('10448', '5', 'Drizzle2 teaspoons oil over chicken breast.'),
('10448', '6', 'Letstand at room temperature 30 minutes.'),
('10448', '7', 'Position 1 rack in bottom third and1 rack in center of oven. preheat to 400F.'),
('10448', '8', 'Place broccoli rabe and potatoes in largebowl. sprinkle with salt and pepper.'),
('10448', '9', 'Add1/4 cup oil. toss to coat.'),
('10448', '10', 'Transfer vegetablesto large rimmed baking sheet and spreadout in even layer.'),
('10448', '11', 'Roast chicken on center oven rack25 minutes.'),
('10448', '12', 'Add 3/4 cup broth to pan withchicken and place potatoes and broccoli onlower oven rack. Roast chicken until instantreadthermometer inserted into thickestpart of thigh registers 165F, adding morebroth by 1/4 cupfuls if pan is dry, 45 to 55minutes longer.'),
('10448', '13', 'Let rest 15 minutes.'),
('10448', '14', 'Continue roasting vegetables untilpotatoes are tender and slightly brownedand broccoli rabe stems are crisp-tenderand leaves are crisp but not browned,tossing occasionally, about 10 minuteslonger. Season to taste with salt and pepper.Tent with foil to keep warm.'),
('10448', '15', 'Tilt chicken to allow juices from cavityto pour into roasting pan. Discard heart andgizzard. Strain pan juices into heatproofmeasuring cup, pressing on solids to forcegarlic through strainer into cup. Spoon fatfrom surface of juices.'),
('10448', '16', 'Add wine to panjuices. Return mixture to roasting pan.Stir over medium heat until jus is heatedthrough, scraping up browned bits, about 1minute. Squeeze enough juice from secondlemon half to measure 2 teaspoons. add tojus. Stir in chopped parsley. Season jus totaste with salt and pepper.'),
('10448', '17', 'Carve chicken. divide among plates.Spoon potatoes and broccoli rabe alongside.'),
('10448', '18', 'Drizzle jus over chicken and serve.'),
('10448', '19', '* An Italian leafy green vegetable withscattered clusters of tiny broccoli-likeflorets. available at some supermarkets andat specialty foods stores.'),
('10451', '1', 'Cook orecchiette in large pot of boiling salted water until pasta is tender but still firm to bite.'),
('10451', '2', 'Drain pasta, reserving 1 cup cooking liquid.'),
('10451', '3', 'Meanwhile, melt butter with olive oil in another large pot over high heat.'),
('10451', '4', 'Add garlic and stir 30 seconds.'),
('10451', '5', 'Add garbanzo beans and saute until garbanzo beans are beginning to color, about 8 minutes.'),
('10451', '6', 'Add half of sliced fresh sage and saute 1 minute to blend flavors.'),
('10451', '7', 'Add broccoli rabe, wine, and 1/2 cup reserved cooking liquid to pot. Cover and simmer until broccoli rabe is crisp-tender, about 5 minutes. Uncover and add pasta, remaining sage, and Parmesan cheese. toss to combine.'),
('10451', '8', 'Mix in more of reserved cooking liquid by tablespoonfuls if pasta is dry. Season to taste with salt and pepper.'),
('10451', '9', 'Transfer to large bowl and serve.'),
('10452', '1', 'Bring a large pot of well-salted water to a boil. Set up a bowl of well-salted ice water. Cook the broccoli rabe in the boiling water for 1 to 2 minutes and then immediately plunge in the salted ice water. This will prevent the broccoli rabe from being overcooked and will set the lovely green color.'),
('10452', '2', 'Drain the broccoli rabe and squeeze out any excess water. coarsely chop.'),
('10452', '3', 'Place the broccoli rabe in the bowl of a food processor and puree until it is a coarse paste.'),
('10452', '4', 'Add the pistachios and parmigiano and puree until smooth. Taste and adjust the seasoning. you probably will need more salt.'),
('10452', '5', 'Add the ricotta and pulse until combined. Taste for seasoning once again-it should be full-flavored, slightly bitter and creamy at the same time. Set aside.'),
('10452', '6', 'Bring a large pot of well-salted water to a boil. (If you are making the pasta right after the pesto, just use the broccoli rabe blanching water.) Cook the pasta 1 minute less than the cooking time on the package.'),
('10452', '7', 'While the pasta is cooking, place the pesto in a large skillet and add about 1 to 1 1/2 cups of the pasta cooking water. place over medium-high heat. When the pasta is ready, drain and add to the skillet with the pesto. Stir vigorously to combine and cook until the sauce is creamy and heated through, 1 to 2 minutes. add salt to taste.'),
('10452', '8', 'Remove from the heat, add 1 to 2 tablespoons olive oil, if desired, and stir vigorously.'),
('10452', '9', 'Garnish with more parmigiano. Voila!'),
('10452', '10', 'Photograph by Con Poulos'),
('10453', '1', 'Place broccoli rabe and salt in a large pot of boiling water. Cook 12 minutes, or until stems are tender.'),
('10453', '2', 'Drain, reserving 1 cup of liquid.'),
('10453', '3', 'Heat 3 tablespoons olive oil in a medium saucepan over medium-high heat, and cook sausage 10 minutes, or until evenly browned.'),
('10453', '4', 'Remove sausage from saucepan. Stir garlic into saucepan, and cook approximately 30 seconds.'),
('10453', '5', 'Place broccoli rabe and reserved cup of liquid in pan, and mix in 1/2 the lemon juice. Return sausage to pan, and allow the mixture to simmer approximately 10 minutes.'),
('10453', '6', 'Mix in remaining olive oil and lemon juice before serving.'),
('10454', '1', 'Bring 2 inches water in a deep skillet to a boil for broccoli rabe and 1 large pot of water to a boil for pasta. Salt the water liberally.'),
('10454', '2', 'Simmer the broccoli rabe in water 10 to 12 minutes, then drain. Return the skillet to medium heat with 1/4 cup extra-virgin olive oil.'),
('10454', '3', 'Add garlic and red pepper to the oil and gently cook a couple of minutes, add broccoli rabe and cook 5 minutes more.'),
('10454', '4', 'While the broccoli rabe cooks, drop the rigatoni into the boiling water and cook until al dente. Just before draining reserve 1 cup starchy liquid.'),
('10454', '5', 'Combine the ricotta, Parmesan, salami and black pepper, to taste, in a pasta bowl.'),
('10454', '6', 'Add the starchy liquid and stir.'),
('10454', '7', 'Add the broccoli rabe and pasta and toss 2 minutes to coat and combine.'),
('10458', '1', 'Watch how to make this recipe.'),
('10458', '2', 'Heat medium soup pot over medium-high heat.'),
('10458', '3', 'Add the olive oil and sausage and brown.'),
('10458', '4', 'Add veggies, bay leaf and beans. Season with salt and pepper. Cook mixture 5 minutes to begin to soften the vegetables.'),
('10458', '5', 'Add rabe and wilt.'),
('10458', '6', 'Add stock and cover pot. Raise heat and bring soup to a boil. Reduce heat to simmer and cook 15 minutes. Adjust seasonings and serve soup with grated cheese, for topping.'),
('10459', '1', 'Bring a large pot of lightly salted water to a boil over high heat.'),
('10459', '2', 'Add the farfalle pasta, and cook until al dente, 8 to 10 minutes. drain.'),
('10459', '3', 'Meanwhile, heat the olive oil in a large skillet over medium-high heat. Stir in the Italian sausage until crumbly and no longer pink, about 5 minutes. Stir in the garlic, and continue cooking until the sausage begins to brown, about 5 minutes more.'),
('10459', '4', 'Pour off the excess grease, then pour in the chicken broth and red pepper flakes. Bring to a boil over high heat, then add the broccoli rabe, and cover. Cook until the broccoli rabe is tender, about 4 minutes.'),
('10459', '5', 'When the broccoli rabe is done, stir in the butter, Parmesan cheese, salt, and pepper until the meat sauce has thickened. Toss with the farfalle and serve.'),
('10466', '1', 'Heat 2 tablespoons oil in heavy large skillet over medium-high heat.'),
('10466', '2', 'Add garlic and cook until golden brown, stirring frequently, about 3 minutes. Discard garlic.'),
('10466', '3', 'Add onion, pancetta, and fennel seeds to skillet. saute until onion is tender and pancetta begins to brown, about 8 minutes.'),
('10466', '4', 'Add dried crushed red pepper, then broccoli rabe stems and cook 4 minutes to soften slightly, stirring occasionally. Stir in broccoli rabe tops, sprinkle with salt, and add 1 cup water. Cover and cook until stems and tops are tender, about 5 minutes. Season to taste with salt and pepper.'),
('10466', '5', 'Meanwhile, cook pasta in large pot of boiling salted water until just tender but still firm to bite.'),
('10466', '6', 'Drain pasta, reserving 1 cup cooking liquid.'),
('10466', '7', 'Add pasta to skillet with broccoli rabe and stir over low heat to combine, adding reserved cooking liquid by tablespoonfuls to moisten if necessary. Stir in remaining 2 tablespoons oil and 1 cup cheese. Season to taste with salt and generous amount of pepper.'),
('10466', '8', 'Transfer to shallow bowl. Sprinkle with pine nuts and serve, passing additional cheese separately.'),
('10473', '1', 'To roast vegetables, preheat oven to 400 degrees F.'),
('10473', '2', 'Place tomatoes and rapini on a baking sheet and season with salt and pepper and coat with 1/4 cup of the olive oil. Roast the vegetables until tender, then remove and allow to cool.'),
('10473', '3', 'Begin the Marsala sauce by heating 1/4 cup of the oil in a saute pan and cooking the shallots or onion gently until translucent. Deglaze the pan with the wine and add the stock and fresh thyme. Allow to reduce by 2/'),
('10473', '4', 'For the stuffed chicken, preheat oven to 350 degrees F. Lay a long piece of plastic wrap over your cutting board and tuck it underneath the sides of the board. The chicken breasts should be placed on the covered cutting board, skin side down, with enough space between them so they can lay flat after you "butterfly" them. To make the butterfly cut, carefully slice open (without slicing the chicken all the way through) and spread the flesh of the chicken out so you will be able to pound it out into a single thin piece on which you will place stuffing and then roll up. Season the breasts with salt and pepper. Then put another length of plastic wrap over the seasoned chicken breasts and flatten with meat mallet to integrate the seasoning into the chicken. (Covering the chicken with the plastic will also keep the mess down when you pound with the meat mallet.) Pound chicken thin and remove plastic. Lay sliced smoked mozzarella on each breast followed by broccoli rabe and roasted tomatoes. Fold in each end and roll tightly, securing with toothpicks as needed, and placing on a baking sheet. Season with salt and pepper and brush with 2 tablespoons olive oil.'),
('10473', '5', 'Place in the oven and roast until fork tender about 45 to 50 minutes.'),
('10473', '6', 'Place the potatoes on a baking sheet, season with salt and pepper, and coat with olive oil.'),
('10473', '7', 'Place in the oven and roast potatoes until they are also fork tender.'),
('10473', '8', 'Strain Marsala sauce and whisk in butter to finish. Season with salt and pepper, as needed.'),
('10473', '9', 'Remove any toothpicks securing the chicken. Slice each chicken roll to reveal the stuffed interior.'),
('10473', '10', 'Place on serving plate with roasted potatoes. Spoon Marsala sauce around chicken.'),
('10473', '11', 'Garnish with chopped chives.'),
('10474', '1', 'For the beef: Preheat the oven to 300 degrees F.'),
('10474', '2', 'Sprinkle the roast liberally with salt and pepper. In a heavy-bottomed roasting pan over high heat, heat the grapeseed oil until shimmering.'),
('10474', '3', 'Add the roast and sear all sides until a golden crust forms, about 10 minutes.'),
('10474', '4', 'Remove and set aside on a sheet tray.'),
('10474', '5', 'Add the garlic, onions, dried Italian seasoning and red pepper flakes.'),
('10474', '6', 'Saute until caramelized.'),
('10474', '7', 'Add the wine and deglaze, scraping the bottom.'),
('10474', '8', 'Add the stock, thyme, salt and pepper, to taste, and bring to a simmer. Return the roast to the pan and any accumulated juices from the sheet tray. Roast in the oven, turning every 20 minutes, until the internal temperature of the meat registers 125 degrees F, 1 hour 30 minutes to 2 hours. While the roast is cooking, start on the garnishes.'),
('10477', '1', 'Heat the olive oil in an 8-quart soup pot or stockpot over medium-high heat.'),
('10477', '2', 'Add the onion, celery, bell pepper, 1 teaspoon of the salt, and  teaspoon of the black pepper and cook, stirring, until the vegetables are tender, about 6 minutes.'),
('10477', '3', 'Add the garlic, dried Italian herbs, and crushed red pepper and cook, stirring, until fragrant, about 1 minute.'),
('10477', '4', 'Add the stock, beans, Parmesan rind, bay leaf, and water and bring to a low boil. Reduce the heat to simmer gently and cook, partially covered and stirring occasionally, until the beans are tender, 45 to 60 minutes.Using a slotted spoon, transfer about 1 cup of the beans from the pot to a small bowl and mash them with the back of a spoon. Return the mashed beans to the soup and add the remaining 1 tablespoon salt. Bring to a simmer over medium-high heat and continue to cook, uncovered, until the broth thickens slightly, about 15 minutes.'),
('10477', '5', 'Add the remaining black pepper, the broccoli rabe, and rosemary sprig and continue to cook until the broccoli rabe is just tender, about 5 minutes. Stir in the lemon zest and lemon juice.'),
('10477', '6', 'Remove the Parmesan rind, bay leaf, and rosemary sprig and discard them.'),
('10477', '7', 'Serve the soup in wide, shallow bowls, garnished with grated Parmesan and a drizzle of extra-virgin olive oil.'),
('10481', '1', 'Bring a large pot of salted water to a boil, add the broccoli rabe and blanch for 2 minutes.'),
('10481', '2', 'Drain in a colander and run cold water over.'),
('10481', '3', 'Drain well again and squeeze out excess liquid.'),
('10481', '4', 'Heat 2 tablespoons of the oil, chili flakes and garlic in a large saute pan over medium heat and cook for 1 minute.'),
('10481', '5', 'Add the broccoli rabe, salt and pepper and cook until slightly tender, about 5 minutes.'),
('10481', '6', 'In a separate large saute pan, heat the remaining 2 tablespoons of oil over high heat until the oil begins to shimmer.'),
('10481', '7', 'Add the sausage links and using a wooden spoon, gently break up the meat into coarse pieces. Cook until deep golden brown. (You do not need to cook all the way because it will continue to cook in the oven.)'),
('10481', '8', 'Combine the sausage and the broccoli rabe and let cool slightly.'),
('10481', '9', 'Heat the oil in a medium saucepan over high heat.'),
('10481', '10', 'Add the garlic and cook for 30 seconds.'),
('10481', '11', 'Add the tomatoes and oregano, bring to a boil and cook until the mixture thickens, about 15 minutes. Stir in the basil and season with salt and pepper.'),
('10481', '12', 'Let cool slightly.'),
('10481', '13', 'Dissolve the yeast and water in the bowl of a mixer fitted with the paddle attachment.'),
('10481', '14', 'Add the oils and mix for 30 seconds.'),
('10481', '15', 'Add the cornmeal, 3 cups of the flour and salt andbeat for 5 minutes. Switch to the dough hook and mix in the remaining 2 1/2 cups of flour and knead, using the dough hook for 2 minutes.'),
('10481', '16', 'Add the butter and knead until incorporated. The dough is a very moist dough so do not add more flour unless absolutely needed.'),
('10481', '17', 'Place the dough in a large bowl lightly oiled with vegetable oil, cover with plastic wrap or clean kitchen towels and let rise in a warm place until doubled in size, about 45 minutes. Punch down the dough and allow to double in size again.'),
('10481', '18', 'Preheat the oven to 450 degrees F.'),
('10481', '19', 'Place 2 pizza stones into the oven to preheat as well. Generously oil 2 (9 or 10-inch) deep dish pie pans with olive oil (about 2 tablespoons for each pan).'),
('10481', '20', 'Divide the dough in half and press the dough out slightly on the counter top.'),
('10481', '21', 'Place the dough in the prepared pans and push out to cover the bottom and up the side of the pans. (If using the 9-inch pans, pinch a 2-inch ball off each dough to make a better fit.)'),
('10481', '22', 'Combine the cheese in a bowl.'),
('10481', '23', 'Place half of the cheese of the bottom of each pie crust. Divide the sausage filling over the cheese and then top with the remaining cheese, patting the cheese firmly down over the filling. Spoon some of the sauce over the top of the cheese to cover completely.'),
('10481', '24', 'Place the pans into the oven on the pizza stones and bake in the oven until golden brown, about 40 minutes.'),
('10481', '25', 'Remove from the oven and sprinkle the top with Parmesan.'),
('10481', '26', 'Let the pizza rest on a baking sheet for 5 minutes before slicing.'),
('10497', '1', 'Trim/clean Brussels sprouts, then cut them in half if desired (or you can leave them whole). Arrange on two baking sheets and toss with olive oil. Sprinkle with plenty of salt and pepper and roast at 375 degrees for 25 to 30 minutes, or until brown.'),
('10497', '2', 'Combine balsamic vinegar and sugar in a saucepan. Bring to a boil, then reduce heat to medium-low and reduce until very thick, about 15 to 20 minutes.'),
('10497', '3', 'Drizzle the balsamic reduction over the roasted sprouts, then sprinkle on dried cranberries. Toss and serve immediately.'),
('10498', '1', 'Heat oven to 425 F. In a small saucepan, over medium heat, warm the vinegar.'),
('10498', '2', 'Add the raisins. Turn off heat. let plump. In a large skillet, fry the bacon until crisp, about 7 minutes. Reserve the drippings.'),
('10498', '3', 'Cut any large sprouts in half.'),
('10498', '4', 'Place the sprouts on a baking sheet or in an ovenproof pan. Toss with the oil, 2 tablespoons of the bacon drippings, the salt, and pepper. Roast, stirring once, for about 30 minutes. Meanwhile, cook the onion in the remaining drippings over medium heat for 5 to 7 minutes. Sprinkle the sprouts with the onions, crumbled bacon, and plumped raisins.Make Ahead: Trim the Brussels sprouts a couple of days in advance, and refrigerate them in an unsealed plastic bag. Cook the bacon and onion up to several hours before serving.'),
('10524', '1', 'Melt butter in a large nonstick skillet over medium-high heat.'),
('10524', '2', 'Add onion and garlic. saut 4 minutes or until lightly browned. Stir in Brussels sprouts. saut 2 minutes.'),
('10524', '3', 'Add broth and sugar. cook 5 minutes or until liquid almost evaporates, stirring frequently. Stir in salt. Sprinkle with pecans.'),
('10529', '1', 'Bring a medium saucepan of salted water to a boil.'),
('10529', '2', 'Add the brussels sprouts and cook over high heat until tender but still bright green, about 3 minutes.'),
('10529', '3', 'Drain well, reserving about 2 tablespoons of the cooking liquid.'),
('10529', '4', 'In a large skillet, cook the bacon over moderate heat, stirring occasionally, until browned, 7 minutes.'),
('10529', '5', 'Add the brussels sprouts and cook over moderately high heat for 2 minutes, stirring occasionally.'),
('10529', '6', 'Add the sour cream and the reserved cooking liquid and simmer over moderate heat until the brussels sprouts are coated. Season with salt and pepper, transfer to a bowl and serve.'),
('10531', '1', 'Prepare the Brussels Sprouts'),
('10531', '2', 'Heat oven to 400 F. On a large rimmed baking sheet, toss the Brussels sprouts, pecans, oil, garlic, 1/2 teaspoon salt, and 1/4 teaspoon pepper. Turn the Brussels sprouts cut-side down.Cook the Brussels Sprouts'),
('10531', '3', 'Roast until golden and tender, 20 to 25 minutes.'),
('10543', '1', 'In a microwave-safe bowl, heat the cranberries in the wine at high power for 2 minutes.'),
('10543', '2', 'Let stand until the cranberries are slightly plumped, about 10 minutes.'),
('10543', '3', 'Drain the cranberries and discard the liquid.'),
('10543', '4', 'In a large skillet, heat the oil.'),
('10543', '5', 'Add the shallots and cook over low heat until softened, about 2 minutes.'),
('10543', '6', 'Add the brussels sprouts and cook over moderately high heat until bright green, about 2 minutes.'),
('10543', '7', 'Add the water and drained cranberries and season with salt and pepper. Cover and cook over moderate heat until the brussels sprouts are tender, about 12 minutes. Uncover and continue cooking until the liquid has evaporated, about 2 minutes.'),
('10543', '8', 'Add the butter and toss to coat.'),
('10543', '9', 'Serve right away.'),
('10553', '1', 'Preheat oven to 42'),
('10553', '2', 'Toss together Brussels sprouts and next 3 ingredients in a 15- x 10-inch jelly-roll pan.'),
('10553', '3', 'Bake 17 to 20 minutes or until sprouts are tender and edges are lightly browned, stirring occasionally.'),
('10553', '4', 'Meanwhile, cook pancetta in a large skillet over medium heat 8 to 10 minutes or until crisp.'),
('10553', '5', 'Remove pancetta, and drain on paper towels. Crumble pancetta.'),
('10553', '6', 'Remove sprouts from oven, and place in a large serving dish. Top with cheese and crumbled pancetta.'),
('10556', '1', 'In a large skillet, heat 1 tablespoon of the oil until shimmering.'),
('10556', '2', 'Add the Rice Krispies and togarashi and cook over high heat, stirring, until browned, about 30 seconds. Season with salt.'),
('10556', '3', 'Transfer to a plate and wipe out the skillet.'),
('10556', '4', 'In a small bowl, combine the fish sauce, water, sugar, rice vinegar, lime juice, garlic and chile and stir until the sugar is dissolved.'),
('10556', '5', 'Add the cilantro and mint.'),
('10556', '6', 'Add the remaining 1 tablespoon of oil to the skillet and heat until nearly smoking.'),
('10556', '7', 'Add the brussels sprouts. cook over high heat, stirring, until charred in spots and heated through, about 5 minutes.'),
('10556', '8', 'Transfer to a bowl and toss with the vinaigrette. Just before serving, sprinkle the Rice Krispies on top and serve right away.'),
('10559', '1', 'Heat olive oil in a large frying pan over high heat.'),
('10559', '2', 'Add garlic and brussels sprouts, and cook until brown and softened, stirring occasionally, about 8 minutes.'),
('10559', '3', 'Add broth and cook until sprouts are tender but not soggy, 3 to 4 minutes.'),
('10559', '4', 'Add pine nuts and season to taste with salt and pepper.'),
('10559', '5', 'Transfer to a small dish and sprinkle with parmesan.'),
('10564', '1', 'Cook shallot in 2 tablespoons butter in a 12-inch heavy skillet over medium-high heat, stirring occasionally, until softened, 1 to 2 minutes.'),
('10564', '2', 'Add carrots, Brussels sprouts, 3/4 teaspoon salt, and 1/2 teaspoon pepper and cook, stirring occasionally, until vegetables begin to brown, 3 to 4 minutes.'),
('10564', '3', 'Add water and cover skillet, then cook over medium-high heat until vegetables are tender, 5 to 8 minutes. Stir in vinegar, remaining tablespoon butter, and salt and pepper to taste.'),
('10567', '1', 'Cook bacon in a Dutch oven over medium heat 10 minutes or until crisp.'),
('10567', '2', 'Remove bacon, and drain on paper towels, reserving drippings in Dutch oven. Crumble bacon.'),
('10567', '3', 'Add broth, brown sugar, and salt to drippings in Dutch oven, and bring to a boil. Stir in Brussels sprouts. Cover and cook 6 to 8 minutes, or until tender.'),
('10567', '4', 'Transfer Brussels sprouts to a serving bowl using a slotted spoon, and sprinkle with bacon.'),
('10567', '5', 'Serve immediately.'),
('10576', '1', 'Bring a large pot of salted water to a boil.'),
('10576', '2', 'Add the brussels sprouts and cook until bright green, 2 minutes.'),
('10576', '3', 'Drain well and pat dry.'),
('10576', '4', 'In a large, deep skillet, heat 3 tablespoons of the oil until shimmering.'),
('10576', '5', 'Add half of the garlic and half of the brussels sprouts and cook over high heat undisturbed for 1 minute.'),
('10576', '6', 'Add half of the crushed red pepper, season with salt and cook over moderate heat, stirring a few times, until the brussels sprouts are browned and tender, about 3 minutes.'),
('10576', '7', 'Transfer to a serving bowl. Repeat with the remaining oil, garlic, brussels sprouts and crushed red pepper.'),
('10576', '8', 'Serve warm.'),
('10589', '1', 'Preheat oven to 450F with rack in upper third.'),
('10589', '2', 'Toss Brussels sprouts with oil, then arrange, cut sides down, in a 17- by 12-inch shallow baking pan. Roast, without turning, until outer leaves are tender and very dark brown, 40 to 45 minutes.'),
('10589', '3', 'Add butter and toss to coat.'),
('10594', '1', 'Preheat oven to 42'),
('10594', '2', 'Place Brussels sprouts in a 15- x 10-inch jelly-roll pan. drizzle with 1 tablespoon oil, tossing to coat. Arrange sprouts on pan, cut sides down, and bake 30 minutes or until tender and browned.'),
('10594', '3', 'Meanwhile, bring sugar and water to a boil in a small saucepan over medium-high heat, stirring constantly to dissolve sugar.'),
('10594', '4', 'Remove from heat. Stir in cranberries, and let stand 10 minutes.'),
('10594', '5', 'Whisk together fish sauce, chili-garlic sauce, and 1 teaspoon canola oil in a large bowl. Stir in cranberry mixture.'),
