INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('34125', '8', 'Pour the hazelnut vinaigrette over the lentils and add the shallot. Toss the salad until the lentils are evenly coated.'),
('34125', '9', 'Serve the lentil salad warm.'),
('34125', '10', 'Make ahead: This salad can be refrigerated, covered, for up to 1 day.'),
('34125', '11', 'Let the salad return to room temperature, or rewarm before serving.'),
('34128', '1', 'Combine the lentils, garlic, chile, ginger, onions, tomatoes and enough water to cover in a medium saucepan over medium heat. Bring the mixture to a boil, and then lower the heat and simmer until the lentils are tender, 30 to 45 minutes.'),
('34128', '2', 'Whisk the cooked lentils to release some of their starch and break them down further.'),
('34128', '3', 'Warm the oil in a small saute pan over medium heat.'),
('34128', '4', 'Add the cumin seeds and cook until they are sizzling and spluttering. Stir in the paprika and turmeric.'),
('34128', '5', 'Pour the seasoned oil onto the lentils (be prepared for a big sizzle). Stir to combine. sprinkle with salt and a small drizzle of honey. Ladle into soup bowls and garnish with cilantro, a drizzle of yogurt, lemon or lime wedges.'),
('34129', '1', 'Melt the butter in a medium saucepan.'),
('34129', '2', 'Add the white onion and carrot and cook over moderate heat, until softened, about 5 minutes. Stir in the tomato paste, paprika and cumin, then add the lentils and water and bring to a boil. Simmer over moderate heat until the lentils are tender and have absorbed about three-fourths of the liquid, about 8 minutes. Stir in the bulgur and remove from the heat.'),
('34129', '3', 'Let stand until the liquid is absorbed and the bulgur is softened, about 20 minutes. Season with salt and pepper.'),
('34129', '4', 'Transfer to a rimmed baking sheet. spread in an even layer to cool.'),
('34129', '5', 'Put 1/2 cup of flour in a plate. Divide the lentil mixture into 16 portions. form into 3/4-inch-thick patties. Dredge the patties in the flour, shake off any excess and set on a floured baking sheet. In a large skillet, heat 1/4 inch of vegetable oil until shimmering. Working in batches, fry the patties over moderately high heat, turning once, until golden, about 5 minutes.'),
('34129', '6', 'Drain on paper towels.'),
('34129', '7', 'Add more oil to the skillet as necessary.'),
('34129', '8', 'In a large bowl, toss the red onion with the cucumber, bell pepper and tomatoes. In a small bowl, whisk the olive oil with the lemon juice and pomegranate molasses.'),
('34129', '9', 'Pour all but 2 tablespoons of the dressing over the salad, season with salt and pepper and toss. Stir in 2 tablespoons of the parsley.'),
('34129', '10', 'In a large bowl, toss the romaine with the remaining 2 tablespoons of dressing and arrange on a large platter. Set the lentil cakes on the lettuce. Spoon the salad on top and sprinkle with the remaining parsley and serve.'),
('34132', '1', 'Pour 1 1/2 cups boiling water over lentils in a small bowl. let stand 10 minutes.'),
('34132', '2', 'Heat a Dutch oven over medium-high heat. Coat pan with cooking spray.'),
('34132', '3', 'Add carrot, celery, onion, and parsley to pan. saut for 4 minutes.'),
('34132', '4', 'Add rhubarb, and saut for 3 minutes.'),
('34132', '5', 'Drain lentils, and add lentils to pan. Stir in chicken broth and salt. bring to a boil. Cover, reduce heat, and simmer 35 minutes or until lentils are tender.'),
('34132', '6', 'Remove from heat. let cool 5 minutes.'),
('34132', '7', 'Place 3 cups lentil mixture in a blender or food processor.'),
('34132', '8', 'Remove center piece of blender lid (to allow steam to escape). secure blender lid on blender.'),
('34132', '9', 'Place a clean towel over opening in blender lid (to avoid splatters). Blend until smooth. Return pureed mixture to pan. stir in pepper.'),
('34132', '10', 'Combine chopped dill and crme frache in a small bowl.'),
('34132', '11', 'Serve crme frache mixture on top of soup. garnish with dill sprigs, if desired.'),
('34135', '1', 'Heat the oil in a wide, medium-sized saucepan, and fry the pancetta until beginning to crisp.'),
('34135', '2', 'Add the lamb breaking it up with a fork in the bacony pan as it browns.'),
('34135', '3', 'Tip in the caramelized onions, Marsala, tomatoes, lentils and water and bring the pan to the boil.'),
('34135', '4', 'Simmer the ragu for 20 minutes stirring occasionally. Sprinkle over the cheese before serving, if using.'),
('34135', '5', '1 tablespoon olive oil'),
('34135', '6', '2 cups sliced onions (about 2 medium size onions)'),
('34135', '7', 'Heat a large saute pan over medium heat.'),
('34135', '8', 'Add the olive oil and heat.'),
('34135', '9', 'Add the onions and cook, stirring, until the onions are a deep golden brown and soft, about 25 to 30 minutes. Make sure to use a gentle heat and cook the onions slowly so they don''t burn. Onions will keep in the fridge for up to 1 week.'),
('34136', '1', 'Heat oil in a large saucepan over medium heat. Stir in lentils, onion, cabbage, and garlic. cook until tender. Stir in sausage and tomatoes. Crumble vegetable cubes over mixture and pour in water. Stir in bay leaf, thyme, and cayenne pepper. Bring to a boil. cover, and simmer until lentils are tender, about 30 minutes. Season with salt and pepper to taste.'),
('34137', '1', 'Rinse the quinoa thoroughly under cold water, and drain. Melt butter in a large saucepan over medium heat, and cook and stir the quinoa until the water has evaporated and the quinoa is lightly toasted, about 3 minutes.'),
('34137', '2', 'Pour in the chicken broth, bring to a boil, reduce heat to low, and simmer until the quinoa has absorbed all the broth, about 10 minutes. Cool quinoa in refrigerator at least 10 minutes.'),
('34137', '3', 'Mix together green pepper, red onion, corn, black beans, cilantro, tomato, lime juice, red wine vinegar, olive oil, adobo seasoning, and feta cheese in a large salad bowl. Lightly stir in the quinoa, and season with salt, pepper, and additional lime juice to taste, if desired. Chill the salad at least 30 minutes before serving. serve cold.'),
('34138', '1', 'In a soup pot heat oil.'),
('34138', '2', 'Add onions and carrots and saute 5 to 6 minutes until tender.'),
('34138', '3', 'Add curry, garlic and saute 1 more minute.'),
('34138', '4', 'Add lentils and chicken'),
('34138', '5', 'stock and bring to a boil. Reduce heat and simmer 35 to 40 minutes or until the lentils are tender.'),
('34138', '6', 'Puree soup with yogurt and adjust seasoning.'),
('34138', '7', 'Add mint and hot sauce if desired.'),
('34139', '1', 'Heat oil in a skillet over medium heat. cook and stir onion and garlic until tender, about 5 minutes.'),
('34139', '2', 'Mix lentils and taco seasoning into onion mixture. cook and stir for 1 minute.'),
('34139', '3', 'Cover lentils with chicken broth and bring to a boil. Reduce heat to low. cover and simmer until lentils are tender, 25 to 30 minutes.'),
('34139', '4', 'Uncover and cook until mixture is slightly thickened, 6 to 8 minutes. Mash lentils slightly. stir in salsa.'),
('34139', '5', 'Serve about 1/4 cup lentil mixture in each taco shell. top with lettuce, tomatoes, Cheddar cheese, and sour cream.'),
('34140', '1', 'Place lentils and water in a saucepan, and bring to a boil. Cover, reduce heat to low, and simmer until tender, about 30 minutes.'),
('34140', '2', 'Drain.'),
('34140', '3', 'In a large bowl, mix together the cooked lentils, milk, wheat and barley cereal, eggs and walnuts. Season with onion soup mix and poultry seasoning.'),
('34140', '4', 'Mix well using your hands, as the mixture will be very thick.'),
('34140', '5', 'Let stand for 30 minutes, or refrigerate overnight.'),
('34140', '6', 'Heat oil in a large skillet over medium heat. Use an ice cream scoop to portion out  balls of the lentil mixture. Drop the scoops into bread crumbs, and coat while flattening into patties.  Fry burgers in the hot skillet until nicely browned on both sides, about 5 minutes per side, depending on the thickness of the patties.'),
('34141', '1', 'Heat coconut oil in a skillet over medium heat.'),
('34141', '2', 'Place onion in skillet and cook, stirring, until tender, about 5 minutes.'),
('34141', '3', 'Add garlic and cook another minute.'),
('34141', '4', 'Stir in lentils, broth, chili powder, cumin, and oregano. Bring to a boil, reduce heat to low, and simmer until lentils are tender, about 30 minutes. Season with salt and pepper.'),
('34141', '5', 'Combine black beans and corn in a saucepan (if using canned beans and corn, drain first). Cook over medium heat, stirring occasionally, until heated through about 8 minutes.'),
('34141', '6', 'Spread tortilla chips on a serving platter. Spoon a layer of lentils on the chips, then a layer of black beans and corn, and then salsa. Sprinkle with shredded cheese.'),
('34141', '7', 'Serve while still warm.'),
('34156', '1', 'Bring broth to a boil in a large saucepan. add beans, and return to a boil. Cover, reduce heat, and simmer 20 minutes or until tender.'),
('34156', '2', 'Drain beans, reserving 1 cup broth in pan, and keep warm.'),
('34156', '3', 'Whisk together yogurt and cornstarch. whisk into broth. Bring to a boil over medium heat, stirring constantly. Boil, stirring constantly, 1 minute or until thickened. Stir in beans, lemon juice, and remaining ingredients.'),
('34156', '4', 'Garnish, if desired.'),
('34158', '1', 'Sort and wash beans. place in a large Dutch oven. Cover with water to 2 inches above beans. cover and let stand 8 hours or overnight.'),
('34158', '2', 'Drain the beans. Return beans to pan. stir in salt and pepper.'),
('34158', '3', 'Preheat oven to 30'),
('34158', '4', 'Cook bacon slices in a large nonstick skillet over medium heat until crisp.'),
('34158', '5', 'Remove bacon from pan with a slotted spoon. set bacon aside.'),
('34158', '6', 'Add onion and carrot to drippings in pan. saut 5 minutes or until golden.'),
('34158', '7', 'Add onion mixture, bacon, 2 cups water, and butter to bean mixture in Dutch oven. stir well. Cover and bake at 300 for 2 1/2 hours or until beans are tender, stirring every hour.'),
('34159', '1', 'Cook lima beans in simmering water 20 minutes or until tender. Rinse with cold water. drain.'),
('34159', '2', 'Combine olive oil, red wine vinegar, and salt.'),
('34159', '3', 'Add beans, grape tomatoes, olives, and parsley. toss well.'),
('34160', '1', 'In a large saucepan, cover the lima beans with 2 inches of water and bring to a boil. Simmer over low heat, stirring occasionally, until the limas are just tender but still al dente, about 2 1/2 hours. add water as needed to keep the limas covered by 2 inches. Season the limas with salt and let stand at room temperature for 5 minutes.'),
('34160', '2', 'Drain the limas, reserving 1 1/2 cups of the cooking liquid.'),
('34160', '3', 'In a medium saucepan, heat 3 tablespoons of the olive oil.'),
('34160', '4', 'Add the onion and garlic and cook over moderately low heat until softened, about 8 minutes.'),
('34160', '5', 'Add the tomatoes, oregano and the reserved bean cooking liquid and simmer over low heat, stirring occasionally, until the sauce has reduced to 1 1/2 cups, about 1 hour. Season the tomato sauce with salt.'),
('34160', '6', 'In a mini food processor, combine the olive oil with the oregano, parsley and garlic and pulse to a coarse puree. Season the oregano pesto with salt.'),
('34160', '7', 'Preheat the oven to 42'),
('34160', '8', 'In a 9-by-13-inch baking dish, mix the limas with the tomato sauce and sprinkle the feta on top.'),
('34160', '9', 'Bake in the upper third of the oven for about 40 minutes, until the beans are bubbling and the cheese is browned.'),
('34160', '10', 'Remove the baking dish from the oven and let stand for 10 minutes.'),
('34160', '11', 'Meanwhile, in a large skillet, heat the remaining 2 tablespoons of olive oil.'),
('34160', '12', 'Add the bread crumbs and cook over moderately high heat, stirring, until toasted, about 3 minutes. Season with salt.'),
('34160', '13', 'Top the beans with the bread crumbs, dollop with the oregano pesto and serve.'),
('34161', '1', 'Sort and wash beans. drain.'),
('34161', '2', 'Combine beans and next 5 ingredients (through bay leaf) in a medium saucepan. Bring to a boil. Cover, reduce heat, and simmer 20 minutes or until tender. Discard thyme sprigs and bay leaf. Stir in salt and pepper.'),
('34165', '1', 'Butter a 2-quart shallow baking dish, and set aside.'),
('34165', '2', 'Stir together lima beans and remaining ingredients in a large bowl. spoon into prepared dish.'),
('34165', '3', 'Bake, covered, at 375 for 30 minutes. Uncover. stir and bake 30 more minutes or until bubbly and browned.'),
('34165', '4', 'Serve with a slotted spoon, if desired. Beans will thicken as they begin to cool.'),
('34166', '1', 'Cook lima beans, water, 2 tablespoons oil, 1 tablespoon parsley, garlic, and salt in a 2-quart heavy saucepan, tightly covered, over moderate heat, stirring occasionally, until beans are tender, 17 to 20 minutes. Season with salt and pepper and transfer to a bowl.'),
('34166', '2', 'Serve sprinkled with remaining tablespoon parsley and drizzled with remaining tablespoon oil.'),
('34169', '1', 'Heat the oil in a large skillet.'),
('34169', '2', 'Add the onion and saut over medium heat until golden.'),
('34169', '3', 'Add the lima beans and tomatoes and bring to a simmer. Cook gently until the lima beans are done to your liking.'),
('34169', '4', 'Stir in the dill, season with salt and pepper, and serve.'),
('34171', '1', 'Beat butter and cream cheese at medium speed with a heavy-duty electric stand mixer until creamy.'),
('34171', '2', 'Combine flour and next 2 ingredients in a small bowl. Gradually add flour mixture to butter mixture, beating at low speed just until blended. Shape dough into 24 balls, and place dough balls on a baking sheet. cover and chill 1 hour.'),
('34171', '3', 'Preheat oven to 40'),
('34171', '4', 'Place 1 dough ball into each of 24 greased assorted-shape tartlet tins. press dough into tins and all the way up sides, forming shells.'),
('34171', '5', 'Bake at 400 for 15 to 17 minutes or until edges are golden. Carefully remove pastry shells from tins to wire racks, and cool completely (about 15 minutes).'),
('34171', '6', 'Let stand at room temperature up to 4 hours before filling, if desired.'),
('34171', '7', 'Spoon 1 rounded tablespoonful Tomato-Lima Bean Relish into each pastry shell.'),
('34172', '1', 'Preheat the oven to 40'),
('34172', '2', 'In a large skillet, melt 2 tablespoons of the butter.'),
('34172', '3', 'Add the sliced leeks and cook over low heat, stirring, until they are softened, about 3 minutes.'),
('34172', '4', 'Add the mushrooms, cover and cook over low heat, stirring occasionally, until they are tender, 15 minutes.'),
('34172', '5', 'Add the stock, cream, bay leaves and tarragon and bring to a boil. Season with salt and pepper and remove from the heat.'),
('34172', '6', 'Put the frozen lima beans in the bottom of a 12- to 14-cup glass or ceramic baking dish.'),
('34172', '7', 'Pour the hot cream mixture over the limas.'),
('34172', '8', 'Bake for 1 1/4 hours, or until the cream sauce is thickened.'),
('34172', '9', 'Preheat the broiler. In a small bowl, toss the bread crumbs with the Parmesan and melted butter. Sprinkle the crumbs over the lima beans and broil for about 1 minute, rotating the dish for even browning.'),
('34172', '10', 'Let the gratin stand for 15 minutes before serving.'),
('34174', '1', 'Save Recipe'),
('34174', '2', 'Print Recipe'),
('34174', '3', 'Persian Dill and Lima Bean Rice - Baghali Polo'),
('34174', '4', 'Ingredients3 cups white basmati rice1 bag (12 oz.)  frozen baby green lima beans or fresh young fava beans, shelled and steamed till tender2 tsp salt1/2 tsp saffron threads3/4 cup vegetable oil (I use grapeseed)1 cup fresh chopped dill, or more to taste'),
('34174', '5', 'You will also need'),
('34174', '6', 'Medium mixing bowl, large 5 quart nonstick pot with tight fitting lid, spice mortar and pestle, large colander, wooden spoon, thin kitchen towel'),
('34174', '7', 'Prep Time: 1 Hour 30 Minutes'),
('34174', '8', 'Cook Time: 1 Hour 15 Minutes'),
('34174', '9', 'Total Time: 2 Hours 45 Minutes'),
('34174', '10', 'Servings: 12 side servings'),
('34174', '11', 'Kosher Key: Pareve'),
('34177', '1', 'Sort and wash beans. drain and place in a medium saucepan. Cover with water to 2 inches above beans. bring to a boil. Cover, reduce heat, and simmer 20 minutes or until tender.'),
('34177', '2', 'Drain.'),
('34177', '3', 'Place beans and remaining ingredients in a food processor. process until smooth.'),
('34178', '1', 'Preheat oven to 35'),
('34178', '2', 'Line a fine wire-mesh strainer with 1 coffee filter.'),
('34178', '3', 'Place strainer over a bowl. spoon yogurt into strainer. Cover yogurt with plastic wrap, and chill 2 hours.'),
('34178', '4', 'Meanwhile, cut baguette into 1/4-inch slices, and place on a baking sheet. Lightly coat 1 side of bread with cooking spray, and sprinkle with pepper.'),
('34178', '5', 'Bake at 350 for 8 to 10 minutes or until toasted.'),
('34178', '6', 'Spoon yogurt into a bowl, discarding strained liquid. (Yogurt will be thick.) Stir in cucumber and salt.'),
('34178', '7', 'Spread Lima Bean Mash on bottom of a 9-inch deep-dish pie plate.'),
('34178', '8', 'Spread yogurt mixture over Lima Bean Mash. Top with cheese, tomato, and bacon.'),
('34178', '9', 'Serve with toasted bread slices and assorted vegetable slices.'),
('34180', '1', 'Cook beans in boiling water 10 minutes or until very tender.'),
('34180', '2', 'Drain, reserving 1/2 cup cooking liquid.'),
('34180', '3', 'Place sesame seeds in a blender. process until finely ground.'),
('34180', '4', 'Add juice and remaining ingredients. process until blended.'),
('34180', '5', 'Add beans and 1/2 cup reserved liquid. process until almost smooth, scraping sides of blender occasionally.'),
('34182', '1', 'Preheat oven to 450F.'),
('34182', '2', 'Mix oil, chopped mint, parsley, rosemary, and garlic in small bowl.'),
('34182', '3', 'Place lamb, cut side up, on work surface. Sprinkle lamb generously with coarse salt and pepper and rub into meat.'),
('34182', '4', 'Spread herb mixture over top of lamb, then roll up, enclosing herb mixture completely. Sprinkle outside of lamb with coarse salt and pepper. Tie lamb with kitchen string at 2-inch intervals.'),
('34182', '5', 'Place lamb in roasting pan. Roast until instant-read thermometer inserted into thickest part of meat registers 130F for medium-rare, about 1 hour 15 minutes.'),
('34182', '6', 'Remove pan from oven. let lamb rest 15 minutes.'),
('34182', '7', 'Remove kitchen string from lamb.'),
('34182', '8', 'Cut lamb into 3/4-inch-thick slices. arrange on platter.'),
('34182', '9', 'Garnish with mint sprigs.'),
('34182', '10', 'Serve with Lima Bean Puree.'),
('34190', '1', 'Saut corn kernels in hot oil in a large skillet over medium-high heat 3 minutes or until tender. add lima beans, and cook 2 minutes.'),
('34190', '2', 'Remove from heat, and let cool 10 minutes.'),
('34190', '3', 'Toss together lima bean mixture, bell pepper, and next 4 ingredients in a large bowl. Cover and chill 1 hour.'),
('34190', '4', '*1 cup frozen baby lima beans, thawed, may be substituted.'),
('34192', '1', 'Cook bacon in a large saucepan over medium heat until crisp.'),
('34192', '2', 'Remove bacon from pan, reserving 1 tablespoon drippings in pan. Crumble bacon. set aside.'),
('34192', '3', 'Add leek to drippings in pan. cook 7 minutes or until tender, stirring frequently. Stir in beans, broth, and water. bring to a boil. Reduce heat, and simmer 10 minutes or until beans are tender.'),
('34192', '4', 'Place half of the bean mixture in a blender.'),
('34192', '5', 'Remove center piece of blender lid (to allow steam to escape). secure lid on blender.'),
('34192', '6', 'Place a clean dishtowel over opening in blender lid (to prevent spills), and process until smooth.'),
('34192', '7', 'Pour pureed bean mixture into a large bowl. Repeat procedure with remaining bean mixture. Stir in lemon juice, salt, and pepper. Ladle about 1 cup soup into each of 8 bowls. top each serving with 1 tablespoon onions, 1 tablespoon sour cream, and about 1 teaspoon bacon.'),
('34193', '1', 'In a large saucepan, cover the limas with 4 inches of water and bring to a boil. Simmer over low heat for 1 hour, then add water to cover by 2 inches.'),
('34193', '2', 'Add the garlic, chopped fennel, onion and lemon zest. Boil over moderately high heat for 15 minutes, stirring often. Reduce the heat to low and simmer, stirring occasionally, until the lima beans and fennel become a thick and creamy puree, about 2 hours.'),
('34193', '3', 'Meanwhile, preheat the oven to 45'),
('34193', '4', 'Season the veal roast with salt and pepper and set it, fat side down, on a rack set in a medium roasting pan.'),
('34193', '5', 'Spread half of the mustard cream over the veal and top with half of the sage leaves.'),
('34193', '6', 'Put the roast in the oven, reduce the temperature to 300 and roast for 45 minutes. Carefully turn the veal fat side up. spread with the remaining mustard cream and top with the remaining sage leaves. Roast the veal for 1 hour longer, or until an instant-read thermometer inserted in the thickest part of the meat registers 14'),
('34193', '7', 'Transfer the veal roast to a carving board to rest for 10 minutes.'),
('34193', '8', 'Stir the ground fennel seeds into the fennel-lima puree. Season with salt and pepper. Discard the kitchen string and slice the meat thickly.'),
('34193', '9', 'Transfer the veal to plates and spoon the fennel-lima puree alongside.'),
('34193', '10', 'Garnish with the fennel fronds.'),
('34195', '1', 'Whisk vinegar, shallot and cream in small bowl. Gradually whisk in oil. Season vinaigrette with salt and pepper.'),
('34195', '2', 'Bring chicken broth to simmer in large saucepan.'),
('34195', '3', 'Add lima beans. Cover and simmer until tender, about 10 minutes. Using slotted spoon, transfer beans to large bowl.'),
('34195', '4', 'Add artichoke hearts to broth. Cook 2 minutes.'),
('34195', '5', 'Add peas. Cover and cook until peas and artichokes are heated through, about 3 minutes longer.'),
('34195', '6', 'Drain well.'),
('34195', '7', 'Add to beans.'),
('34195', '8', 'Add chopped mint to vegetables.'),
('34195', '9', 'Mix in enough vinaigrette to coat. Season with salt and pepper.'),
('34195', '10', 'Garnish with mint sprigs.'),
('34195', '11', 'Serve warm or at room temperature.'),
('34196', '1', 'Pour lima beans into a colander. sort and remove debris, then rinse and drain beans. In a 4- to 5-quart pan over high heat, bring 2 1/2 to 3 quarts water and beans to a boil. cook for 2 minutes. Cover tightly, remove from heat, and let stand for 1 hour.'),
('34196', '2', 'Drain beans, reserving 2 quarts cooking liquid.'),
('34196', '3', 'Rinse chicken and pat dry.'),
('34196', '4', 'Cut each thigh in half lengthwise along one side of bone. or with a cleaver, cut whole chicken through bones into 2- by 3-inch pieces (see notes). Pull off and discard any lumps of fat. Rinse green beans and remove and discard stem ends and any tough strings. cut beans into 3-inch lengths.'),
('34196', '5', 'If using a charcoal barbecue (at least 22 in. wide), ignite 160 briquets (about 9 1/2 lb.) on the firegrate. open dampers. When coals are dotted with ash, in 15 to 20 minutes, spread into an even double layer about 2 inches wider than base of paella pan. Set grill 4 to 6 inches above charcoal.'),
('34196', '6', 'Let coals burn down until they''re hot (you can hold your hand at grill level only 2 to 3 seconds), 5 to 10 minutes.'),
('34196', '7', 'If using a gas barbecue (at least 19 in. wide), turn temperature to high, close lid, and let heat for 10 minutes.'),
('34196', '8', 'Set a 17-inch paella pan on grill over hot coals or high heat on a gas grill.'),
('34196', '9', 'Add 2 tablespoons oil. with a wide spatula, spread to coat bottom of pan. When oil is hot, add chicken pieces (close lid on gas barbecue). cook, turning once, until lightly browned on both sides, 6 to 12 minutes total.'),
('34196', '10', 'Add tomatoes and stir until most of the juices have evaporated, 1 to 2 minutes. Stir in remaining 1 tablespoon oil, green beans, 1 1/2 teaspoons salt, paprika, and turmeric.'),
('34196', '11', 'Add soaked lima beans and the reserved 2 quarts cooking liquid (if it''s cold, heat in a microwave oven or pan until hot before adding). Note level of liquid in pan: Measure distance from pan rim or handle rivets to level of liquid. (Close lid on gas barbecue.) Bring to a gentle boil.'),
('34196', '12', 'Boil gently to flavor broth, 25 to 30 minutes (on gas barbecue, regulate heat as needed to maintain gentle boil).'),
('34196', '13', 'Remove about 1 cup broth from pan.'),
('34196', '14', 'Add enough water to match original level of liquid, 3 to 5 cups. Taste broth in pan, and season to taste with more salt. also taste reserved broth and season with salt.'),
('34196', '15', 'Pour rice in a band down center of pan. Draw a wooden spoon or spatula in a wide zigzag pattern through rice and across pan to distribute rice evenly. Push any grains floating above broth back under. Simmer, without stirring, until rice is tender to bite, 25 to 30 minutes. If rice begins to scorch before it''s tender, remove pan from heat and let coals burn down to a lower temperature before continuing. (On gas barbecue, close lid and regulate heat so liquid simmers briskly in the beginning, then lower heat when most of the liquid has evaporated. rotate pan occasionally so bottom cooks evenly.) If rice is still firm, drizzle about 1/2 cup of the reserved broth evenly over the top and cook for a few more minutes. repeat if necessary. (If reserved broth isn''t needed, save for another use.)'),
('34196', '16', 'With spoon, push aside a little of the top layer of rice to see if there is a brown crust on the bottom. if one hasn''t formed yet, cook a few more minutes (adjust gas heat as necessary to brown, but not burn, rice).'),
('34196', '17', 'Remove from heat and let stand for about 5 minutes. Squeeze juice from lemons over rice.'),
('34196', '18', 'Add salt to taste.'),
('34203', '1', 'Cook bacon in a 10-inch nonstick skillet over moderate heat, stirring occasionally, until crisp.'),
('34203', '2', 'Transfer bacon with a slotted spoon to paper towels to drain, then cook onion and bell pepper in fat in skillet over moderate heat, stirring frequently, until vegetables are softened, 5 to 6 minutes.'),
('34203', '3', 'Add lima beans, corn, water, salt, and pepper, then simmer, covered, until vegetables are tender, about 8 minutes. Increase heat to high and add cream, then boil, uncovered, until liquid is reduced by half, 7 to 10 minutes. Stir in herbs and salt to taste.'),
('34203', '4', 'Serve sprinkled with bacon.'),
('34210', '1', 'Bring a large pot of salted water to a boil.'),
('34210', '2', 'Add lima beans and carrots and cook for 4 minutes.'),
('34210', '3', 'Add asparagus and cook 1 minute longer. Using a slotted spoon, remove vegetables and rinse under cold water to stop cooking.'),
('34210', '4', 'Add fettuccine to water and cook until tender, 8 to 10 minutes (or according to package directions).'),
('34210', '5', 'Drain, reserving 1/2 cup cooking water.'),
('34210', '6', 'When fettuccine has cooked for about 5 minutes, melt butter in a large frying pan over mediumhigh heat.'),
('34210', '7', 'Add garlic and saut until fragrant, 1 minute.'),
('34210', '8', 'Add vegetables, season with salt and pepper, and saut until vegetables look glazed and are crisp-tender, 3 to 4 minutes.'),
('34210', '9', 'Add the drained fettuccine and 1/4 cup reserved cooking water and toss well.'),
('34210', '10', 'Transfer to a large, shallow serving bowl and toss with Parmesan and parsley.'),
('34210', '11', 'Add ricotta to hot pasta by spoonfuls and toss gently to combine. Season with salt and pepper. If pasta appears dry, drizzle in a little more cooking water.'),
('34210', '12', 'Serve immediately.'),
('34212', '1', 'Heat dressing in large saucepan on medium heat.'),
('34212', '2', 'Add tomatoes, onions and garlic. cook  4 min.  Stir in beans and cilantro. cook 1 min.'),
('34212', '3', 'Add water. bring to boil. Cover.  Cook on low heat 1 hour or until beans are tender.'),
('34212', '4', 'Serve with crackers.'),
('34216', '1', 'Combine 8 cups water and soup mix in a large stockpot. bring to a boil. Cover, remove from heat and let sit one hour. Return pan to heat. stir in 2 cups chopped carrots and 1 1/2 cups chopped celery.'),
('34216', '2', 'Add 1 1/2 pounds smoked ham hock. bring to a boil. Cover, reduce heat and simmer 2 hours or until beans are tender. skim fat as necessary.'),
('34216', '3', 'Remove ham hock from soup. remove meat from bone. Chop meat and return to soup. Stir in 1/4 teaspoon pepper.'),
('34216', '4', 'Heat thoroughly and serve.'),
('34218', '1', 'Preheat oven to 450F.'),
('34218', '2', 'Puree almond paste, granulated sugar, butter, and a pinch of salt in a food processor until smooth.'),
('34218', '3', 'Add 1 egg, vanilla, and almond extract and puree until incorporated.'),
('34218', '4', 'Add flour and pulse until incorporated.'),
('34218', '5', 'Roll out 1 puff pastry sheet into an 11 1/2-inch square on a lightly floured surface with a floured rolling pin, then brush off excess flour from both sides.'),
('34218', '6', 'Cut out an 11-inch round by tracing around an inverted plate with tip of a paring knife.'),
('34218', '7', 'Transfer round to a buttered large baking sheet (not dark metal, or pastry may brown too much), discarding trimmings, and chill. Repeat procedure with second pastry sheet, leaving round on floured surface.'),
('34218', '8', 'Beat remaining egg with a fork and brush some over top of second round. Score round decoratively all over using tip of knife, then make several small slits all the way through pastry, at about 2-inch intervals, to create steam vents.'),
('34218', '9', 'Brush some of egg in a 1-inch-wide border around edge of chilled pastry round (on baking sheet). Mound almond cream in center of chilled round, spreading slightly, and bury bean in cream. Immediately cover with decorated round and press edges together lightly. Holding a small spoon with side at an angle, press around edge to seal galette decoratively.'),
('34218', '10', 'Bake galette in lower third of oven until puffed and pale golden, 13 to 15 minutes. Dust galette with confectioners sugar and bake in upper third of oven until edge is deep golden brown and shiny, 12 to 15 minutes more.'),
('34218', '11', 'Transfer to a rack to cool slightly, 5 to 10 minutes.'),
('34218', '12', 'Serve warm.'),
('34220', '1', 'Preheat the oven to 42'),
('34220', '2', 'Bring a large saucepan of salted water to a boil.'),
('34220', '3', 'Add the lima beans and corn and boil until tender, about 3 minutes.'),
('34220', '4', 'Drain the beans and corn, transfer to a bowl and let cool.'),
('34220', '5', 'Slice off the bottom of each tomato so it sits flat. Using a knife, cut around the center of each tomato to form a cone that can easily be removed once the tomato is baked.'),
('34220', '6', 'Brush the tomatoes with olive oil and set them in a large pie plate, stem side up. Season the tomatoes with salt and pepper and roast just until tender, about 5 minutes.'),
('34220', '7', 'Let cool slightly, then spoon out and discard the centers to make room for the succotash.'),
('34220', '8', 'Meanwhile, in a large skillet, melt 1 1/2 teaspoons of the butter in the 1 tablespoon of olive oil.'),
('34220', '9', 'Add the bell pepper and cook over moderately high heat, stirring occasionally, until crisp-tender, about 3 minutes.'),
('34220', '10', 'Add the limas and corn and cook, stirring, for 2 minutes.'),
('34220', '11', 'Remove from the heat. Stir in the remaining 1 1/2 teaspoons of butter and the chives and season with salt and pepper. Spoon the succotash into the tomatoes and serve warm or at room temperature.'),
('34221', '1', 'Preheat oven to 40'),
('34221', '2', 'Saut garlic in hot oil in a 10-inch ovenproof skillet over medium heat 1 minute.'),
('34221', '3', 'Add onion and carrots. saut 3 to 4 minutes or until tender.'),
('34221', '4', 'Add ham. cook 3 minutes. Stir in beans, peas, and next 2 ingredients. bring to a boil, and cook 5 minutes.'),
('34221', '5', 'Remove from heat. pour batter over ham mixture.'),
('34221', '6', 'Bake at 400 for 28 to 30 minutes or until golden brown and bubbly.'),
('34226', '1', 'To cook the lima beans'),
('34226', '2', 'Heat a medium saucepan over high heat for 1 minute. Swirl in 2 tablespoons olive oil, and add the onion, garlic, and thyme. Saut over medium heat 3 to 4 minutes, until the onion is translucent.'),
('34226', '3', 'Add the beans, and cook a few minutes, stirring often to coat the beans with the onion and oil. Season with salt and pepper, and add enough water to cover the beans by a few inches. Simmer 5 to 7 minutes, until the beans are just tender. Cool and store the beans in the cooking liquid.'),
('34226', '4', 'To make the salad'),
('34226', '5', 'Combine the shallots, lemon juice, and a teaspoon salt in a small bowl.'),
('34226', '6', 'Let sit 5 minutes.'),
('34226', '7', 'Whisk in 5 tablespoons olive oil.'),
('34226', '8', 'Drain the cooled beans well and toss them with this vinaigrette and a pinch of salt and pepper. Taste for seasoning and stir in the herbs.'),
('34226', '9', 'var article'),
('34226', '10', 'Type_27_data = {}.'),
('34226', '11', 'article'),
('34226', '12', 'Type_27_data.init_step_by_step_images = 0.'),
('34229', '1', 'Prepare the beef: Preheat the oven to 50'),
('34229', '2', 'In a large glass baking dish, combine the soy sauce, maple syrup, shallots and curry powder.'),
('34229', '3', 'Add the beef and rub the soy mixture all over.'),
('34229', '4', 'In an ovenproof skillet, heat the vegetable oil until almost smoking. Season the beef with salt, add to the skillet and cook over moderately high heat until browned, about 15 minutes.'),
('34229', '5', 'Transfer the skillet to the oven and roast the meat for about 20 minutes, or until it reaches 125 on an instant-read thermometer for medium rare.'),
('34229', '6', 'Transfer the roasts to a cutting board and let stand until cooled.'),
('34229', '7', 'In a pot of boiling salted water, cook the sugar snaps for 1 minute. Using a slotted spoon, transfer them to a colander set under cold running water. drain, pat dry and transfer to a large bowl. Repeat with the lima beans, cooking them until just tender, about 4 minutes. add them to the peas.'),
('34229', '8', 'In a small skillet, toast the curry powder over low heat, stirring, for 2 minutes. transfer to a plate.'),
('34229', '9', 'Add the mustard seeds to the skillet and cook for 2 minutes. transfer to another plate.'),
('34229', '10', 'In a bowl, combine the curry powder, oil, vinegar, garlic, lemon zest and salt.'),
('34229', '11', 'Cut each roast into 1/4-inch-thick slices.'),
('34229', '12', 'Add the radishes, cucumbers, chives, mustard seeds and 1/2 cup of the curry vinaigrette to the sugar snaps and lima beans and toss.'),
('34229', '13', 'Serve the beef with the vegetables and pass the remaining vinaigrette separately.'),
('34233', '1', 'Soften the beans in simmering water for about 2 minutes. In another pan, heat the oil, red peppers, rosemary, and garlic over medium-low heat until the rosemary starts to sizzle. Turn off heat.'),
('34233', '2', 'Drain the beans well, add them to the pan, and let soak in the oil for 30 minutes.'),
('34233', '3', 'Remove the rosemary leaves from the stalk. discard the stalk and 1 of the red peppers. In a blender or food processor, puree the beans, oil, garlic, rosemary leaves, lemon juice, and the remaining red pepper.'),
('34233', '4', 'Add the salt and black pepper.'),
('34233', '5', 'Drizzle with more extra-virgin olive oil and serve with crostini.'),
('34233', '6', 'Slice a baguette into 1-inch slices.'),
('34233', '7', 'Drizzle with olive oil, salt, and black pepper to taste.'),
('34233', '8', 'Bake in a 375F oven until crisp and just browned.'),
('34236', '1', 'Position a broiler rack 6in (15cm) from the source of heat and preheat the broiler. Prick the sausages with a fork. Arrange on the broiler rack and broil about 10 minutes, turning occasionally, until cooked through.'),
('34236', '2', 'Transfer to a plate.'),
('34236', '3', 'Meanwhile, heat the oil in a saucepan over medium-low heat.'),
('34236', '4', 'Add the onion, celery, and garlic, and cook, stirring frequently, about 5 minutes, or until softened. Increase the heat to medium-high and add the wine. Bring to a boil, then stir in the canned tomatoes with their juices. Stir in the ketchup and paprika, season with salt and pepper, and bring to a boil. Reduce the heat to medium-low and simmer, uncovered, for about 20 minutes, or until lightly thickened.'),
('34236', '5', 'Stir in the lima beans and sausages. Simmer for 10 minutes. Sprinkle with basil and serve hot.'),
('34236', '6', 'var article'),
('34236', '7', 'Type_27_data = {}.'),
('34236', '8', 'article'),
('34236', '9', 'Type_27_data.init_step_by_step_images = 0.'),
('34237', '1', 'If using fresh limas, blanch them in a large saucepan of boiling salted water until just tender, about 5 minutes. drain.'),
('34237', '2', 'In a large saucepan, heat 3/4 cup of the olive oil with the rosemary.'),
('34237', '3', 'Add the lima beans and garlic and cook over moderate heat until the limas are soft, about 10 minutes.'),
('34237', '4', 'Drain the beans in a fine sieve set over a heatproof bowl. Discard the rosemary sprig and reserve the oil.'),
('34237', '5', 'Transfer the lima beans to a food processor and pulse until pureed. With the machine on, gradually add the reserved oil and process until smooth.'),
('34237', '6', 'Add 2 tablespoons of the lemon juice and season with salt and pepper.'),
('34237', '7', 'In a bowl, combine the olives, parsley and the remaining 1 tablespoon of oil and 1/2 tablespoon of lemon juice.'),
('34237', '8', 'Add half of the cheese and toss gently.'),
('34237', '9', 'Spoon the lima puree onto a platter or into a bowl. Scatter the olive mixture and the remaining cheese shavings on top and serve right away, passing the baguette toasts alongside.'),
('34240', '1', 'Place lima beans in large bowlwith enough water to cover by5 inches. Soak overnight.'),
('34240', '2', 'Bring 2 cups water anddried mushrooms to boil in smallsaucepan. Using slotted spoon,transfer mushrooms to mediumbowl. reserve liquid in saucepan.'),
('34240', '3', 'Heat oil in heavy large potover medium heat.'),
('34240', '4', 'Add onion andgarlic. saute until onion is tender,10 minutes.'),
('34240', '5', 'Drain beans. add topot.'),
('34240', '6', 'Pour in mushroom liquid,leaving sediment behind.'),
('34240', '7', 'Add 6cups water. Bring to simmer. skimfoam from top. Stir in red pepperand thyme. Simmer partiallycovered until beans are tender, 45minutes. Season with salt. Chopmushrooms. add to pot. Simmeruncovered over medium heat untilbeans and mushrooms are verytender, stirring occasionally andadding water to thin as needed,about 15 minutes longer. DO AHEAD:  Can be made 3 days ahead.Cool, then cover and chill. Rewarmbeans before continuing.'),
('34240', '8', 'Add chard to beans. Coverpot. cook until chard is tender,stirring often, about 8 minutes.Season with salt and pepper.'),
('34241', '1', 'Simmer beans, onion, garlic, salt, and water in a 3-quart saucepan, covered, until beans are tender, about 8 minutes. Stir in cilantro and parsley and let stand, uncovered, 5 minutes.'),
('34241', '2', 'Drain bean mixture in a sieve and transfer to a food processor.'),
('34241', '3', 'Add cumin, cayenne, 3 tablespoons lemon juice, 4 tablespoons oil, dill, and mint and puree until smooth.'),
('34241', '4', 'Transfer to a bowl and cool to room temperature, stirring occasionally. Season with salt and pepper and add lemon juice to taste.'),
('34241', '5', 'Mound dip in a serving bowl and drizzle with remaining tablespoon oil.'),
('34246', '1', 'Bring a large pot of lightly salted water to a boil.'),
('34246', '2', 'Place rotini pasta in the pot, cook for 8 to 10 minutes, until al dente, and drain.'),
('34246', '3', 'Heat the olive oil in a skillet over medium-high heat.'),
('34246', '4', 'Place lima beans in skillet. Season with garlic, tarragon, and salt. Cook and stir until heated through. Toss with cooked rotini and top with Parmesan cheese to serve.'),
('34247', '1', 'Preheat broiler.'),
('34247', '2', 'Cut poblano chile in half lengthwise. discard seeds and membranes.'),
('34247', '3', 'Place chile halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 10 minutes or until blackened.'),
('34247', '4', 'Place in a zip-top plastic bag. seal.'),
('34247', '5', 'Let stand 5 minutes. Peel, chop, and set aside.'),
('34247', '6', 'Place beans in a medium saucepan. cover with water. Bring to a boil. reduce heat to medium, and cook 25 minutes or until tender.'),
('34247', '7', 'Drain.'),
('34247', '8', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('34247', '9', 'Add onion and bell peppers. saut 6 minutes.'),
('34247', '10', 'Add garlic. saut 1 minute. Stir in beans and corn. saut 6 minutes or until corn is tender.'),
('34247', '11', 'Add poblano and tomatoes. cook 2 minutes.'),
('34247', '12', 'Remove from heat. stir in chopped cilantro, juice, salt, and black pepper.'),
('34247', '13', 'Garnish with cilantro sprigs, if desired.'),
('34248', '1', 'Combine first 8 ingredients in a large bowl.'),
('34248', '2', 'Combine lemon juice and the remaining ingredients. stir with a whisk.'),
('34248', '3', 'Drizzle dressing over salad, and toss gently to combine.'),
('34249', '1', 'Bring a large pot of salted water to a boil, then add the pasta.'),
('34249', '2', 'After 5 minutes, add the lima beans.'),
('34249', '3', 'Meanwhile, heat the olive oil in a skillet over medium heat.'),
('34249', '4', 'Add the onion and cook until browned, about 7 minutes.'),
('34249', '5', 'When the pasta is ready, drain it with the beans (reserving 1/2 cup of the liquid), then return the pasta and beans to the pot along with the onion, creme fraiche, thyme (if using), salt, pepper, goat cheese, and the reserved water. Toss together and serve.'),
('34251', '1', 'Wash and dry the lettuce and tear into bite-size pieces.'),
('34251', '2', 'Line a large plastic bag with a sheet of paper toweling.'),
('34251', '3', 'Add the greens and place another sheet on top of them. Close and refrigerate.'),
('34251', '4', 'In a medium saucepan of lightly salted boiling water, cook the fresh lima beans for 10 to 15 minutes until tender. (If using frozen beans, cook for 1 to 2 minutes.)'),
('34251', '5', 'Drain, cool under cold water, and drain again. Set aside.'),
('34251', '6', 'Rub the duck skin with the thyme. Season with salt and pepper, and set aside.'),
('34251', '7', 'In a large skillet, heat 2 tablespoons of the oil over medium heat.'),
('34251', '8', 'Add the peppers and, tossing occasionally, cook until wilted, about 10 minutes, Using a slotted spoon, remove the peppers to a bowl and set aside.'),
('34251', '9', 'Raise the heat to high. When the skillet begins to smoke, add the duck breasts, skin side down. Cook until the skin is golden, about 4 minutes. Turn and sear for 3 more minutes until the duck breasts are rare. (Magrets are best served rare. for medium rare, cook about 2 minutes longer.)'),
('34251', '10', 'Remove from the pan and reserve on a warm plate.'),
('34251', '11', 'In a large bowl, whisk together the vinegar with salt and pepper to taste. Gradually whisk in the remaining 6 tablespoons oil.'),
('34251', '12', 'Add the greens and toss to coat. Divide the greens among 4 serving plates and sprinkle with the lima beans and pepper strips.'),
('34251', '13', 'Slice the duck breasts across the grain into thin slices and arrange over the greens. Sprinkle with the chervil and optional truffle.'),
('34251', '14', 'var article'),
('34251', '15', 'Type_27_data = {}.'),
('34251', '16', 'article'),
('34251', '17', 'Type_27_data.init_step_by_step_images = 0.'),
('34252', '1', 'Place beans in large saucepan.'),
('34252', '2', 'Add enough water to cover beans.  Bring to boil. simmer on medium-low heat 2-1/2 hours or until tender.'),
('34252', '3', 'Cook bacon in large skillet on medium heat until crisp.'),
('34252', '4', 'Drain on paper towels, reserving drippings in skillet for later use.'),
('34252', '5', 'Crumble bacon.'),
('34252', '6', 'Add to beans along with the corn, sausage and onions. mix well.  Simmer on medium-low heat 1 hour.'),
('34252', '7', 'Stir flour into reserved bacon drippings in skillet. cook on medium-low heat until hot and bubbly, stirring frequently.  Gradually stir in water until well blended. cook on medium heat until mixture comes to boil and thickens, stirring constantly.'),
('34252', '8', 'Add to soup. simmer 30 min., stirring occasionally.  Stir in pepper.'),
('34253', '1', 'Cook bacon in a 10-inch heavy skillet over moderate heat, stirring frequently, until crisp, about 5 minutes.'),
('34253', '2', 'Transfer bacon with a slotted spoon to paper towels to drain, then add butter to fat in skillet and melt over moderate heat.'),
('34253', '3', 'Add corn, lima beans, bell pepper, and white and pale green parts of scallions and cook, stirring, 2 minutes.'),
('34253', '4', 'Add cream, water, salt, and pepper, then simmer, partially covered, until vegetables are tender, 10 to 15 minutes. Stir in bacon, scallion greens, and salt and pepper to taste.'),
('34254', '1', 'In a large bowl, cover lima beans with water, cover with a towel and soak overnight.'),
('34254', '2', 'In a large pot, add oxtails, onions, scallions, garlic, thyme, red pepper, paprika, bay leaf, hot sauce, and gravy master and marinate at least 4 hours or overnight in the refrigerator, stirring occasionally.'),
('34254', '3', 'Add enough water to just cover the oxtails and bring the mixture to a boil. Lower to a simmer, cover and cook 2 hours. Every 30 minutes for 2 hours add 2 cups of water or broth, alternating, as necessary, to keep oxtails covered with liquid.'),
('34254', '4', 'At 2 hours, add the beans, tomato paste, and 2 more cups of beef broth and water, if needed. Bring to a boil then simmer uncovered 2 hours, skimming fat off top and stirring occasionally. In the last 1/2 hour of cook time, season with 2 tablespoons salt.'),
('34254', '5', 'Serve with rice.'),
('34254', '6', 'Rinse rice 3 times to remove starch. Put rice in a medium saucepan. Fill saucepan with enough water to cover the rice by 1/2-inch or measure by placing your thumb tip on the rice and filling the pot with water until the water reaches the middle of your thumbnail. Bring rice to a simmer, cover and cook until tender and liquid is evaporated, about 15 minutes.'),
('34254', '7', 'Remove from heat and let rice stand another 5 minutes, covered.'),
('34257', '1', 'Bring all ingredients to a boil in a Dutch oven over medium-high heat, stirring often. Cover, reduce heat to low, and simmer, stirring occasionally, 25 minutes or until thoroughly heated.'),
('34258', '1', 'Sort and wash beans. place in a large Dutch oven. Cover with water to 2 inches above beans. cover and let stand 8 hours or overnight.'),
('34258', '2', 'Drain beans. Cover with water to 2 inches above beans, and bring to a boil. Cover, reduce heat, and simmer 1 hour or until beans are tender.'),
('34258', '3', 'Drain beans.'),
('34258', '4', 'Preheat oven to 32'),
('34258', '5', 'While beans cook, heat oil in a large nonstick skillet over medium heat.'),
('34258', '6', 'Add onion, celery, carrot, and garlic. cook 10 minutes, stirring occasionally. Stir in oregano and tomatoes. simmer 10 minutes. Stir in parsley, dill, honey, salt, and pepper.'),
('34258', '7', 'Combine the cooked beans and tomato mixture in a 3-quart casserole coated with cooking spray.'),
('34258', '8', 'Bake at 325 for 1 hour.'),
('34259', '1', 'In a skillet, cook the bacon and onion over medium-high heat, stirring, until half-cooked and not yet crispy, about 8 minutes.  Set aside.'),
('34259', '2', 'In a large stockpot, add the water and tomatoes and bring to a boil over high heat.'),
('34259', '3', 'Add the live crabs and boil for 12 minutes.'),
('34259', '4', 'Remove the crabs and set aside to cool.  (If using carcasses, leave them in the pot.)  Reduce the heat to low and simmer for 1 hour.'),
('34259', '5', 'Meanwhile, remove the meat from the crabs and set aside.  As this is mysteriously complicated unless you are from Maryland, see the instructions below for guidance on how to shell a crab.'),
('34259', '6', 'After the soup has been simmering for 1 hour, add the celery, corn, green beans, peas, lima beans, potatoes, Old Bay seasoning, red chile flakes, and the reserved bacon and onion. if you have used crab carcasses and shells, strain the soup before adding the vegetables and discard the shells.  Simmer until the vegetables are cooked, about 30 minutes.  Season with salt.'),
('34259', '7', 'Add the reserved crab meat and add the fresh claw meat, stir, and serve.'),
('34259', '8', 'How to Pick Crabs'),
('34259', '9', 'Twist off the claws and legs.'),
('34259', '10', 'Place the crab on its back and pull the apron up and off.'),
('34259', '11', 'Cut the bottom shell just under the mouth with a knife.'),
('34259', '12', 'Remove and discard the spongy white gills, which are inedible.'),
('34259', '13', 'Snap the crab body into halves.'),
('34259', '14', 'Twist off the back fins.'),
('34259', '15', 'Crack the claws with a mallet to remove the claw meat.'),
('34259', '16', 'Remove the meat from the other parts with a nut pick.'),
('34260', '1', 'Heat oil in heavy large skillet over mediumheat.'),
('34260', '2', 'Add onion and sprinkle with coarsesalt. Saute until soft and translucent, about5 minutes.'),
('34260', '3', 'Add garlic. stir until fragrant,about 1 minute.'),
('34260', '4', 'Add tomatoes, corn, andlima beans. Reduce heat to medium-low,cover, and simmer until corn and limabeans are tender and tomatoes are soft,about 20 minutes, stirring occasionally.Season to taste with salt and pepper. DO AHEAD:Can be made 1 day ahead. Coverand chill. Rewarm before continuing.'),
('34260', '5', 'Stir in basil and serve.'),
('34261', '1', 'Bring 4 cups of water to a boil.'),
('34261', '2', 'Add dry lima beans, and boil for 2 to 3 minutes.'),
('34261', '3', 'Remove from heat, and allow the beans to sit, covered, for 1 to 2 hours to soften.'),
('34261', '4', 'Drain and rinse until water runs clear, discarding bean water.'),
('34261', '5', 'In a soup pot, saute vegetables in olive oil until onions and celery are translucent.'),
('34261', '6', 'Add lima beans, and saute for another 2 to 3 minutes.'),
('34261', '7', 'In the meantime, bring 4 cups of water to a boil.'),
('34261', '8', 'Add the vegetable bouillon to the boiling water, and stir until dissolved.'),
('34261', '9', 'Add broth to the sauteed vegetables and beans.'),
('34261', '10', 'Add remaining water, and allow soup to simmer over a low flame for 1 to 1 1/2 hours.'),
('34261', '11', 'Serve steaming hot.'),
('34262', '1', 'Cook meat in hot oil over medium-high heat in a large Dutch oven 6 to 8 minutes or until browned.'),
('34262', '2', 'Stir in frozen mixed vegetables, next 9 ingredients, and 1 1/2 qt. water, stirring to loosen particles from bottom of Dutch oven. Bring mixture to a boil over medium-high heat. cover, reduce heat to low, and simmer, stirring occasionally, 55 to 60 minutes or until potatoes are tender.'),
('34262', '3', 'Note: For testing purposes only, we used Knorr Chicken Bouillon cube.'),
('34263', '1', 'Watch how to make this recipe.'),
('34263', '2', 'Add the beans to a pot with enough cold water to cover well. Bring to a boil, lower the heat, cover, and simmer until just soft throughout but not quite cooked, approximately 50 to 80 minutes, depending on the beans.'),
('34263', '3', 'Drain and set aside.'),
('34263', '4', 'Preheat the oven to 325 degrees F.'),
('34263', '5', 'Heat olive oil over medium heat in a Dutch oven.'),
('34263', '6', 'Add onion and cook until soft.'),
('34263', '7', 'Add the garlic and cook for 30 seconds.'),
('34263', '8', 'Add tomatoes and their liquid, 2 cups water, honey, cloves, salt, and pepper and boil gently for 20 to 30 minutes or until it begins to thicken. Stir in the parsley and remove from heat.'),
('34263', '9', 'Place the beans in an oven-proof dish, pour tomato mixture on top, stir and spread mixture out evenly.'),
('34263', '10', 'Bake 1 1/2 to 2 hours, or until beans are soft. (Check the dish during cooking and if needed, add a small amount of boiling water.) The dish will look crispy on top.'),
('34263', '11', 'Remove from the oven and let sit for 10 minutes before serving.'),
('34263', '12', 'Serve hot or at room temperature.'),
('34265', '1', 'Place lima beans in a Dutch oven or soup kettle. add water to cover by 2 in. Bring to a boil. boil for 2 minutes.'),
('34265', '2', 'Remove from the heat. cover and let stand for 1 hour.'),
('34265', '3', 'Drain and rinse beans, discard liquid.'),
('34265', '4', 'In a Dutch oven coated with nonstick cooking spray, cook onions and garlic until tender. Stir in the broth, ham, carrots, water, jalapeno, parsley, pepper and lima beans. Bring to a boil. Reduce heat. cover and simmer for 50 minutes or until beans are tender.'),
('34266', '1', 'Place whole tomatoes,  water, lima beans, corn, sliced carrots, chopped onion,  Old Bay seasoning, and beef broth,  in a  4 quart pot.'),
('34266', '2', 'Heat to simmer, cover, and cook for 5 minutes.'),
('34266', '3', 'Bring 1 gallon water to boil.'),
('34266', '4', 'Add crab claws and boil 6 minutes.'),
('34266', '5', 'Drain crab and set aside'),
('34266', '6', 'Stir crabmeat (and crabs claws, if desired) into tomato and vegetable mixture. Cover and simmer 10-15 minutes longer.'),
('34266', '7', 'Serve hot.'),
('34268', '1', 'Put cannellini beans in a medium pot, cover with water, and bring to a boil. Cover and turn off heat.'),
('34268', '2', 'Let sit 1 hour.'),
('34268', '3', 'Drain beans, then return to pot and add carrot, celery, halved onion, whole garlic cloves, parsley sprigs, thyme, and peppercorns. Cover with water by 1 in. and bring to a boil. Reduce heat to maintain a steady simmer and cook until beans are tender, 1 to 1 1/2 hours. Discard vegetables and herbs and let beans cool.'),
('34268', '4', 'Drain, reserving liquid, and set liquid and beans aside.'),
('34268', '5', 'Put 1 tbsp. olive oil, mushrooms, and 1 tsp. salt in a large (not nonstick) frying pan over high heat. Cook, stirring, until mushrooms stop giving off liquid and start to brown.'),
('34268', '6', 'Transfer to a large bowl.'),
('34268', '7', 'In same frying pan over medium-high heat, add remaining 2 tbsp. olive oil and chopped onion. Cook until onion is soft, 3 minutes.'),
('34268', '8', 'Add chopped garlic and cook, stirring, until fragrant, about 1 minute.'),
('34268', '9', 'Add vinegar and cook, scraping up any brown bits, until pan is almost dry. Return mushrooms to pan along with reserved beans and 1/4 cup reserved bean-cooking liquid. Cook, stirring, until well combined and hot. Stir in chopped parsley and salt and pepper to taste.'),
('34268', '10', 'Serve hot or warm.'),
('34271', '1', 'Watch how to make this recipe.'),
('34271', '2', 'Sprinkle the steak with salt and pepper. Set aside.'),
('34271', '3', 'In a large Dutch oven (preferably enameled cast iron) over medium-high heat, render the bacon until just starting to crisp, 6 to 7 minutes, stirring as needed.'),
('34271', '4', 'Remove 1 tablespoon of the bacon fat and set aside.'),
('34271', '5', 'Add the onions and jalapenos and cook until the onions are translucent, about 5 minutes more.'),
('34271', '6', 'Add in the garlic cook 1 to 2 minutes.'),
('34271', '7', 'Remove all from the pot to a small bowl. Set aside.'),
('34271', '8', 'Wipe down the inside of the pot, add the reserved 1 tablespoon bacon fat and, when starting to smoke, add in 1/3 to 1/2 of the steak and cook, stirring as needed until just starting to brown, about 8 minutes.'),
('34271', '9', 'Remove to the vegetable bowl, repeat with the remaining steak.'),
('34271', '10', 'Once the steak is cooked, deglaze with 1 tablespoon apple cider vinegar. Then return all the vegetables and cooked steak back to the pot and add in the beans, including the liquid in the can.'),
('34271', '11', 'Add the molasses, brown sugar, soy and ketchup, and stir to combine. Bring to a simmer over low heat, cover and cook for 2 hours, stirring every 20 to 30 minutes to assure that the bottom doesn''t stick.'),
('34271', '12', 'Add in more apple cider vinegar, a few tablespoons at a time to personal taste, and serve with crusty bread.'),
('34273', '1', 'Bring 4 cups water and 1 teaspoon salt to a boil in a medium, heavy saucepan. gradually whisk in grits. Reduce heat. simmer, uncovered, 20 to 25 minutes or until thick, stirring often.'),
('34273', '2', 'Remove from heat, and add 1/4 cup butter and Parmesan cheese, stirring until cheese melts. cover and keep warm.'),
('34273', '3', 'Heat 1 tablespoon oil in a saut&eacute. pan or large skillet over medium-high heat. add lima beans, onion, celery, and carrot. saut&eacute. 2 minutes.'),
('34273', '4', 'Add 1/2 cup water. cover, reduce heat, and simmer 15 minutes.'),
('34273', '5', 'Add corn. cook, uncovered, 3 to 5 minutes.'),
('34273', '6', 'Remove vegetables from pan. keep warm.'),
('34273', '7', 'Add remaining 1 tablespoon oil to pan, and heat. add shrimp, and cook 1 to 2 minutes on each side.'),
('34273', '8', 'Add ham and shallot. cook 2 minutes.'),
('34273', '9', 'Add white wine, and cook to deglaze pan (stirring to loosen particles from bottom of skillet).'),
('34273', '10', 'Add lima bean mixture and tomato halves to pan. Cook 1 to 2 minutes or until heated through. Stir in remaining 1/4 cup butter, lemon juice, and Tabasco sauce. season to taste with salt (about 1/4 teaspoon) and white pepper.'),
('34273', '11', 'Serve shrimp and succotash over hot grits.'),
('34274', '1', 'Sift together flour, salt, and sugar into a chilled large metal bowl. Set a grater over flour mixture and coarsely grate frozen butter into flour, gently lifting flour and tossing to coat butter.'),
('34274', '2', 'Drizzle ice water evenly over flour mixture and gently stir with a fork until incorporated. Turn out mixture onto a lightly floured surface and divide into 6 portions. With heel of your hand, smear each portion once or twice in a forward motion to help distribute fat. Gather dough together with scraper and form into a 6- to 7-inch square. Wrap in plastic wrap and chill at least 1 hour. (Dough will be lumpy and streaky.)'),
('34275', '1', 'In a large covered kettle, bring 6 quarts salted water to a rolling boil over high heat.'),
('34275', '2', 'Add the lobsters, cover, and cook for 10 minutes.'),
('34275', '3', 'Drain and cool under cold running water. With poultry shears, cut away the claw and tail shells and carefully remove the meat. If the lobsters are female, reserve the grainy red coral and chop finely. Cover and refrigerate the lobster meat and coral.'),
('34275', '4', 'With a sharp knife, cut the kernels off the cob, slicing from the top of the ear downward, but not too close to the cob. You should have about 4 cups. Using a small spoon, scrape the milky liquid from the cobs into a medium bowl.'),
('34275', '5', 'Add the kernels and reserve.'),
('34275', '6', 'In a medium saucepan of lightly salted boiling water, blanch the lima beans until almost tender, 3 to 5 minutes. Cool under cold running water.'),
('34275', '7', 'Drain and reserve.'),
('34275', '8', 'In a large heavy nonreactive saucepan, melt the butter over medium heat.'),
('34275', '9', 'Add the cream. When it begins to steam, add the corn and its pulp and cook for 10 minutes, stirring often until the liquid thickens slightly.'),
