INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('6534', '3', 'Place rinsed and well-strained rice in a large bowl.Toast Pecans in a 375F oven for 10-12 minutes (reduce time if nuts are chopped), stirring occasionally, until lightly browned.'),
('6534', '4', 'Remove from oven, and cool to room temperature.To make dressing, in a small bowl mix together orange zest, orange juice, lemon zest, lemon juice, grated garlic and white distilled vinegar (you can also add a little olive oil if desired).In the large bowl with rice, combine golden raisins, chopped parsley, chopped cilantro, and dressing mixture.'),
('6534', '5', 'Add salt and pepper to taste. For best flavor, refrigerate for about 2 hours before serving.'),
('6534', '6', 'Mix in toasted pecans immediately before serving so they remain nice and crunchy. Enjoy your healthy and delicious meal!'),
('6535', '1', 'Combine flour, half the herbs, and half the salt.Season the fish with additional salt and pepper, then dredge in flour mixture to coat, shaking off the excess.'),
('6535', '2', 'Heat 1 TBS butter in a large skillet over moderately high heat and cook fish 3 minutes on each side.'),
('6535', '3', 'Remove from pan.Reduce heat to moderately low and add butter pieces and simmer until a light golden brown, about 5 minutes.'),
('6535', '4', 'Remove skillet from heat and stir in lemon juice, remaining herbs, salt and pepper to taste.'),
('6535', '5', 'Pour over fish fillets.'),
('6536', '1', 'Place fish in a casserole dish and pour wine mixed with teriyaki sauce. Sprinkle wth scalions and herbs.COver loosely and nuke for about 9 minutes or until fillets flake.'),
('6537', '1', 'Combine crushed chips, parmesan cheese and parsley.In a separate bowl combine mayonnaise and 2 Tbsp lemon juice.'),
('6537', '2', 'Pour the remaining lemon juice into another bowl.Dip the fish in the lemon juice, then the mayonnaise and finally the chip mixture.'),
('6537', '3', 'Place onto a greased baking dish and bake 5-10 minutes at 400 F.'),
('6538', '1', 'Preheat the oven to 450F Lightly spray a baking sheet with non-stick cooking spray. Arrange the potato wedges on one side, leaving enough room for the fillets, and spray them with the cooking spray.'),
('6538', '2', 'Bake in the preheated oven for 25 minutes, or until golden brown and tender.While the potatoes are baking, combine the flour, bread crumbs, and pepper in a shallow bowl.In another shallow bowl lightly beat the egg white. Dip the fish fillets in the egg white, then coat both sides with the flour mixture.'),
('6538', '3', 'Transfer to the baking sheet, alongside the potatoes, and continue to cook for 10 minutes more, or until the fillets are crisp and browned.'),
('6538', '4', 'Combine all the ingredients for the tartar sauce in a small bowl and mix well.'),
('6538', '5', 'Serve 1 tablespoon on each fish fillet.'),
('6539', '1', 'Mix all ingredients together, EXCEPT fish and melted butter.Rinse fish fillets and pat dry. Rub with butter and dip each side into bread crumb mixture.'),
('6539', '2', 'Bake in 325 degree oven for 15 to 20 minutes (uncovered) until fish flakes when pressed with a fork.'),
('6540', '1', 'Marinate fish fillets for 1 hours in wine.'),
('6540', '2', 'Drain fillets on paper towels.Dip both sides of fish in crumbs.Arrange in greased shallow baking dish.'),
('6540', '3', 'Mix Mayonnaise, onion, sour cream, and spread evenly over fish.Cover with thin layer of crumbs.Dust with paprika.'),
('6540', '4', 'Bake at 500 degrees F for 10 minutes or until fish flakes.'),
('6541', '1', 'Slightly defrost fish fillets, cut them in bite-size cubes.In a large saucepan heat olive oil, add garlic, ginger, red pepper flakes and shrimps. Cook for 2 minutes, turn the shrims, add leak and celery and cook for another 3 minutes, constantly stirring.'),
('6541', '2', 'Add hot water, fish cubes, carrots, potatoes and salt. Bring to boil. Reduce heat and simmer for 20 minutes.'),
('6541', '3', 'Remove from heat, add lemon juice, season with salt and/or pepper if desired. Just before serving you may add low fat cream.'),
('6541', '4', 'Serve sprinkled with chopped scallions.'),
('6543', '1', 'You will want get the potatoes on first as these take the longest.Potatoes.In a medium bowl mix potatoes with oil and season with salt and pepper.'),
('6543', '2', 'Place in roasting pan with garlic cloves and cook in 200c oven for 30-40 minutes.'),
('6543', '3', 'Serve potatoes and garlic on the side and sprinkle with mint.For the Fish.In a saucepan bring some water to a boil and add spinach, for fresh cook until just wilted, for frozen cook until thawed, drain, let it cool and then squeeze excess liquid out.In a pan combine oil and butter and heat, add onions and cook until soft, add mushrooms and garlic, cook until mushrooms are slightly browned and soft set to one side.For the Sauce.'),
('6543', '4', 'Heat milk in a pan, add cayenne, nutmeg and paprika. When milk is almost boiling mix a little water with cornflour and pour into milk, stirring until mixture thickens.'),
('6543', '5', 'Add the cheeses, reserving the few tablespoons of Parmesan for the top, stir until melted.Poaching fish.In a large pan mix wine with herbs, add fish and poach for about 8 minutes until fish flakes but is not falling apart.Assembly.'),
('6543', '6', 'Mix mushroom and onion mixture into spinach, spoon into the bottom of a casserole dish covering the bottom.Lay fish fillets on top of the spinach,'),
('6543', '7', 'Pour the sauce over fillets, sprinkle with remaining Parmesan cheese.Grill until browned on top and bubbling.While I am grilling fish I put my potatoes over low heat on stove top to keep warm.'),
('6544', '1', 'Marinate sturgeon in olive oil, coriander, shallots and dill for 8 hours, refrigerated. Soak tea and applewood chips in water for 2 hours.'),
('6544', '2', 'In a stove top smoker place soaked tea and apple chips in bottom of pan and put over medium heat on stove.'),
('6544', '3', 'Drain of any excess oil and place sturgeon on rack and cover.'),
('6544', '4', 'Let smoke on stovetop until fish begins to flake, about 12 minutes.'),
('6544', '5', 'Remove from pan and garnish with onions, capers, and chopped eggs.'),
('6544', '6', 'Drizzle with creme fraiche and serve.'),
('6545', '1', 'Combine first 5 ingredients in spice grinder and process until finely ground.'),
('6545', '2', 'Transfer to blender.'),
('6545', '3', 'Add parsley and next 4 ingredients to blender. With blender running, gradually add oil and blend until coarse puree forms. Season to taste with salt. Do ahead Charmoula can be made 1 day ahead.'),
('6545', '4', 'Transfer to bowl and refrigerate.'),
('6545', '5', 'Let stand at room temperature 1 hour before using.'),
('6545', '6', 'Place fish on large plate.'),
('6545', '7', 'Pour 3/4 cup charmoula over fish, turning to coat. Cover and refrigerate fish at least 1 hour and up to 1 day. Cover and refrigerate remaining charmoula to use as dressing for salad.'),
('6546', '1', 'Finely grind fennel seeds in grinder.'),
('6546', '2', 'Whisk together fennel and 1 cup yogurt with garlic, ginger, cumin, coriander, black pepper, turmeric, cayenne, and 1/2 teaspoon salt. Coat fish with yogurt mixture and marinate in a shallow baking dish, covered and chilled, 1 hour.'),
('6546', '3', 'While fish is marinating, whisk together remaining cup yogurt, mint, zest, and remaining 1/2 teaspoon salt to make sauce.'),
('6546', '4', 'Prepare grill for cooking. If using a charcoal grill, open vents on bottom of grill, then light charcoal. Charcoal is medium-hot when you can hold your hand 5 inches above rack for 3 to 4 seconds. If using a gas grill, preheat burners on high, covered, 10 minutes, then reduce heat to moderate.'),
('6546', '5', 'Lift fish out of marinade, letting excess drip off (discard marinade), and grill fish, covered only if using a gas grill, on lightly oiled grill rack, turning over once, until just cooked through, about 12 minutes total. (If using halibut, grill skin sides down first and grill, turning once, 8 to 9 minutes total.)'),
('6546', '6', 'Serve fish with sauce.'),
('6546', '7', 'Cooks'' note:If you aren''t able to grill outdoors, sturgeon can be grilled in a well-seasoned large ridged grill pan (without crowding) over moderately high heat, turning once, until just cooked through, about 12 minutes total. (Halibut will take 8 to 9 minutes total.)'),
('6550', '1', 'Cut all the fish and veggies into similar-sized pieces. this helps everything lay flat when it is on the grill.2 Marinate the fish and vegetables: To make the marinade, pure the onion, rosemary, garlic, salt and pepper in a food processor.'),
('6550', '2', 'Drizzle in the olive oil while pureing, continue to pure until smooth, about 1-2 minutes.Coat the fish and veggies in the marinade. Set in the fridge for at least an hour and up to overnight.3 Thread onto skewers:When skewering the fish and vegetables, pierce the fish against the grain, and select pieces of veggies that are close to the same size as your fish. This is important, because if the pieces are different widths, some things will be charred and others undercooked.You also want to be careful when loading up the skewers. it''s easy to stab yourself by accident! Alternate pieces of fish with pieces of various veggies, leaving a little space between everything. Dont crowd the skewer, or the parts that are touching will cook too slowly.Note that by threading the skewers with assorted veggies and fish, some things will be cooked more or less than others, as some things take longer to cook than others. If you want all of your items to be cooked perfectly, use a separate skewer for the onions, one for the tuna, one for the bell peppers, etc.'),
('6550', '3', 'Put the onions and bell peppers down first because they take longer to cook.4 Grill on high, direct heat:Prepare the grill for high, direct heat. Clean the grates and wipe them down with a paper towel that has been dipped in vegetable oil. Lay the skewers on the grill.Don''t move them until the fish pieces are well browned on one side, about 3-6 minutes.Then using tongs, carefully turn the skewers over and cook them until they are seared on the other side.'),
('6550', '4', 'Serve hot or at room temperature.'),
('6550', '5', 'Drizzle with lemon juice or serve with lemon wedges.'),
('6551', '1', 'Pour 1 tablespoon olive oil into a medium pan over medium heat. When hot, add shallots and garlic. stir often until limp, about 2 minutes.'),
('6551', '2', 'Trim ends from lemon grass stalks and peel off tough outer layers. crush with the flat side of a large knife, then cut into lengths that will fit in your pan. Stir curry paste, ginger, turmeric, and the lemon grass into pan. cook until fragrant, about 2 minutes.'),
('6551', '3', 'Add coconut milk, fish sauce, sugar, and lime peel. simmer, stirring often, until slightly thickened, about 10 minutes.'),
('6551', '4', 'Remove lemon grass.'),
('6551', '5', 'Add salt to taste.'),
('6551', '6', 'Meanwhile, preheat oven to 45'),
('6551', '7', 'Sprinkle both sides of fish with salt and pepper.'),
('6551', '8', 'Pour remaining 1 1/2 tablespoons olive oil into a large ovenproof frying pan over medium-high heat.'),
('6551', '9', 'Add fish and cook until browned on the bottom, 3 to 4 minutes. Turn pieces and transfer pan to oven.'),
('6551', '10', 'Bake just until fish is opaque in center of thickest part, about 8 minutes.'),
('6551', '11', 'Spoon curry sauce onto four plates and top with fish.'),
('6551', '12', 'Wine pairing: Off-dry but crisp Riesling, with aromatic citrus, apple, and tropical notes over good minerals. Best in our pairing: Poet''s Leap 2004 (Columbia Valley, WA. $22), V. Sattui off-dry Johannisberg 2004 (Napa Valley. $18), and Firestone 2004 (Central Coast, CA. $10).'),
('6551', '13', 'Flavor bridges: A little sugar in the Riesling matches the sweetness and tames the spice in the dish. Low alcohol and fruitiness lower the heat too. Sweetness in the wine also gives it weight--viscosity--to match the mouth-feel of the coconut milk. Good acid, on the other hand, cuts through that richness for a mouthwatering effect (a flabby wine would go flat). Citrus and tropical notes echo the lemon grass, lime, ginger, and aromatic spices in the curry.'),
('6552', '1', 'To make the vinaigrette, whisk together the vinegar, shallot, and mustard in a bowl. Slowly pour in the oils, whisking until emulsified. Season with salt and pepper.'),
('6552', '2', 'Squeeze any excess water out of the crabmeat.'),
('6552', '3', 'Place the crab in a mixing bowl with the mayonnaise, vinaigrette, and chives, and season with salt and pepper.'),
('6552', '4', 'Mix together well and set aside. Puree the cantaloupe in a blender.'),
('6552', '5', 'For each serving, place 2 tablespoons of the cantaloupe puree in the center of the plate.'),
('6552', '6', 'Place a ring mold on top and fill with a layer of sliced avocado and then crab.'),
('6552', '7', 'Place a dollop of caviar on top of the crab to complete.'),
('6552', '8', 'Taste'),
('6552', '9', 'Book, using the USDA Nutrition Database'),
('6552', '10', 'Mixt Greens. Partnering with his sister and brother-in-law, Leslie and David Silverglide, the team launched the San Francisco Bay Area''s greenest restaurant in 200'),
('6552', '11', 'Mixt has since expanded to multiple locations across the country while still preserving its gutsy approach to salads, maintaining ecologically sound business practices, and retaining its original mandate of environmental sustainability. Swallow''s home base is in San Francisco.'),
('6553', '1', 'In a large frying pan over medium-high heat, stir bacon often until browned and crisp, 6 to 7 minutes.'),
('6553', '2', 'Add portabellas and stir often until golden brown, about 5 minutes. pour into a bowl.'),
('6553', '3', 'Add leeks, carrot, and celery to pan. reduce heat to medium and stir often until vegetables are soft, 8 to 10 minutes.'),
('6553', '4', 'Return portabellas to pan and add chicken broth, wine, and thyme. simmer, stirring often, until liquid is almost evaporated, about 10 minutes. Season to taste with salt and pepper.'),
('6553', '5', 'Meanwhile, preheat oven to 45'),
('6553', '6', 'In a spice or coffee grinder, grind dried mushrooms to a fine powder. pour into a wide, shallow bowl. Sprinkle both sides of fish with salt and pepper, then coat with the ground mushrooms.'),
('6553', '7', 'Pour olive oil into another large, ovenproof frying pan over medium-high heat.'),
('6553', '8', 'Add fish and cook until browned on the bottom, 3 to 4 minutes. Turn pieces and transfer pan to oven.'),
('6553', '9', 'Bake just until fish is opaque in center of thickest part, about 8 minutes.'),
('6553', '10', 'Divide mushroom-leek ragout among four plates. Top with fish.'),
('6553', '11', 'Wine pairing: Earthy, smoky Pinot Noir with mushroom notes under dark berry flavors. Best in our pairing: Tandem Sangiacomo Vineyard 2002 (Sonoma Coast. $38), Foxen 2004 (Santa Maria Valley, CA. $28), Willa'),
('6553', '12', 'Kenzie Pierre Lon Vineyard 2003 (Willamette Valley, Yamhill/Carlton, OR. $36), and Estancia Stonewall Vineyard 2003 (Santa Lucia Highlands, CA. $30).'),
('6553', '13', 'Flavor bridges: Pinot Noir can be meaty without being heavy and tannic. tender, white-fleshed fish like sturgeon is also meaty but lean (as are portabella mushrooms). Smokiness in the wine plays off the bacon in the ragout, and mushroom flavors--well, Pinot is about the only wine that offers them flat out.'),
('6555', '1', 'Sauce'),
('6555', '2', 'Mix first 3 ingredients in 2-cup glass measuring cup. gradually whisk in oil. Season with pepper.'),
('6555', '3', 'Pour half of mixture into small bowl. mix in 3 tablespoons sugar, capers, and shallot for sauce.'),
('6555', '4', 'Mix 1 tablespoon sugar into remaining mixture. Reserve for dressing salad.'),
('6555', '5', 'Salad'),
('6555', '6', 'Mix sliced fennel and cucumbers in large bowl. Mince enough fennel fronds to measure 3 tablespoons. add to bowl. Season to taste with dressing in measuring cup. Season with salt and pepper.'),
('6555', '7', 'Assembly'),
('6555', '8', 'Cover large platter with lettuce leaves. Arrange smoked fish and salad atop lettuce.'),
('6555', '9', 'Garnish with caper berries, lemon wedges, and eggs (if desired).'),
('6555', '10', 'Serve with bread, butter, and Mustard-Caper Sauce.'),
('6559', '1', 'In a small mixing bowl, beat cream cheese, mayonnaise, paprika, black pepper, garlic powder and ground red pepper with an electric mixer on medium speed till well combined.Stir in the imitation crab, chopped tomato and green onions.Cover and chill for 3-24 hours.'),
('6560', '1', 'Shred surimi and place in bowl.Slice avocado in half and twist to open. Carefully Lodge a knife in the seed and twist to remove.Score avocado into 1 inch by 1 inch sections and spoon into bowl.'),
('6560', '2', 'Add tomato, onion slivers, and cilantro.Squeeze 1/2 lime over the salad.Salt and pepper to taste.Stir well and serve.'),
('6561', '1', 'Prepare pasta according to package directions.'),
('6561', '2', 'Heat sauce and crabmeat in medium saucepan until hot. add pasta, heat through.Top with cheese.'),
('6562', '1', 'Saute the onions in the butter until caramelized.Distribute the caramelized onions over the bottom of the crust.Sprinkle the krab over the onions and then top with the bleu cheese, mozzarella and provolone.'),
('6562', '2', 'Whisk together the eggs, milk, salt and pepper and then pour the mixture into the crust.Sprinkle the top with Parmesan cheese.'),
('6562', '3', 'Bake at 350F for 40 to 50 minutes.Allow to set at least 5 minutes before serving.'),
('6563', '1', 'Flake crab with 1 t lemon juice in large bowl.'),
('6563', '2', 'Add onion, celery (optional), vinegar, soy sauce, worcestershire, and 1 t dill.Stir until mixed.Stir in mayonnaise (adjust amount according to taste).'),
('6563', '3', 'Add salt and pepper to taste.Slice avocado into bitesize pieces and sprinkle with remaining 1 t lemon juice (keeps avocado from browning) and 1/2 t dill.Gently stir avocados and olives into the salad.Taste and adjust seasonings as needed.'),
('6563', '4', 'Serve or refrigerate for several hours.'),
('6564', '1', 'In a medium sized bowl place the crab or surimi and pick through to remove any bones or cartilage.Stir in the cheese, green onions and just enough mayonnaise to hold it all together.Spoon the crab on 4 slices of bread and top with remaining bread.'),
('6564', '2', 'Heat a griddle to medium-low heat.'),
('6564', '3', 'Brush tops of bread liberally with melted butter and place butter side down on hot griddle.Cook slowly until golden and crisp on the bottom, about 2-3 minutes.'),
('6564', '4', 'Brush tops with melted butter and turn to cook the other side, again slowly until bread is browned, 2 minutes more.'),
('6564', '5', 'Cut in half and serve while still hot.'),
('6565', '1', 'Combine all ingredients and chill before serving.'),
('6565', '2', 'Serve with celery sticks, or on rolls or crackers.'),
('6566', '1', 'Into a large saucepan of salted boiling water stir rice and boil 10 minutes.'),
('6566', '2', 'Drain rice in a colander and rinse.Set colander over a kettle of boiling water (rice should not touch water) and steam rice, covered with a kitchen towel and lid, until fluffy and dry, 10 to 15 minutes (check water level in kettle occasionally, adding water if necessary).While rice is steaming, in a small saucepan bring 1/4 cup vinegar to a boil with sugar and salt, stirring until sugar is dissolved, and remove from heat.In a dry small skillet toast sesame seeds over moderate heat, stirring, until golden and fragrant and transfer to a small bowl.'),
('6566', '3', 'Transfer rice to a large bowl and stir in vinegar mixture.Cool rice and stir in sesame seeds, remaining 3 tablespoons vinegar, oil, ginger, scallions, carrot, and cucumber.Salad may be prepared up to this point 1 day ahead and chilled, covered.Bring salad to room temperature before proceeding.Dry-roast nori, 1 sheet at a time, directly above moderate heat (gas or electric burner), holding it at opposite corners and moving it back and forth, until it turns bright green, 30 seconds to 1 minute.With scissors cut nori into thin 2-inch-long strips.Peel and pit avocado.Quarter avocado and cut crosswise into thin slices.'),
('6566', '4', 'Add avocado to salad with surmimi if using and two thirds of nori strips and toss well.Make dressing: In a small bowl stir wasabi powder into hot water and stir in cold water, soy sauce, and ginger juice.'),
('6566', '5', 'Serve salad sprinkled with remaining nori strips and drizzled with dressing.'),
('6567', '1', 'In a glass bowl, toss together the ingredients for the salsa. Season with salt and pepper and set aside to let the flavors build. Single'),
('6567', '2', 'GuyChef says to let it sit for an hour but 30 minutes is also okay.'),
('6567', '3', 'Combine the chopped avocado and lime juice, season with sea salt and freshly ground black pepper. Set aside.In another glass bowl, add all of the ingredients for the faux crab.Toss, season with sea salt and freshly ground black pepper to taste.Okay, now for the combining the three bits:.You could make the crab the base, then the avocado, then the salsa, topped with sour cream.Or -- you could make the avocado the base, topped with crab, then with salsa, then with sour cream.Or -- you could spread a nice base of salsa, top with the crap and then add the avocado, sour cream on top or to the side.Or -- well, start using your imagination, you don''t need me to tell you how to do everything, do you?.I''ve served these in our house as an appetizer in oversized martini glasses. I''ll let you guess the order I layered the bits -- .-).'),
('6568', '1', 'Preheat oven to 300F.In a small bowl, whisk together oil, sugar, garam masala, curry and cayenne, add peanuts and mix well.'),
('6568', '2', 'Bake on a nonstick cookie sheet 20 minutes, remove and cool on paper towels.'),
('6568', '3', 'Combine cole slaw mix, green onion, tomato and Krab in a large bowl.In a small bowl, whisk together mayo, vinegar and sugar.'),
('6568', '4', 'Pour dressing over cabbage mixture, season with salt and pepper, toss to combine, refrigerate 2 hours or overnight and top with nuts just before serving.'),
('6569', '1', 'Remove the skin from the swordfish and cut it into cubes. Salt the fish well and dust the cubes in flour.'),
('6569', '2', 'Heat the olive oil in a saut pan large enough to hold all the swordfish chunks in one layer. Sear them well on at least two sides. Give the first side 1-2 minutes, then sear other sides for 30 seconds to 1 minute each.2 When the swordfish is cooked, remove it to a bowl and reserve.'),
('6569', '3', 'Add the garlic slices and saut 30 seconds or so  the second it begins to brown, add the tomatoes, parsley, white wine, pine nuts and paprika. Toss to combine and cook 1 minute, then add the swordfish back to the pan, toss to combine and cook another 30 seconds or so.'),
('6569', '4', 'Serve at once.'),
('6570', '1', 'Sprinkle fish with 1/2 teaspoon red pepper, salt, and pepper.'),
('6570', '2', 'Heat 1 tablespoon oil in large nonstick skillet over medium-high heat.'),
('6570', '3', 'Add fish. cook until opaque in center, 4 to 5 minutes per side.'),
('6570', '4', 'Transfer to platter. cover.'),
('6570', '5', 'Add 1 tablespoon oil and shallots to skillet. saut over medium heat until golden, 3 to 4 minutes.'),
('6570', '6', 'Add 1/8 teaspoon red pepper, garlic, and olives. saut 1 minute.'),
('6570', '7', 'Add pine nuts, parsley, and wine. boil until most of liquid is gone, 30 seconds. Season with salt and pepper. Spoon over fish.'),
('6571', '1', 'Make the peanut paste by combining peanut butter, paprika, chili pepper, salt, ground ginger and lime juice.'),
('6571', '2', 'Stir well and taste. Adjust spices as necessary'),
('6571', '3', 'Place fish strips in a large bowl  and pour peanut sauce over it, then using your hands, mix well ensuring the pieces are coated with the sauce.'),
('6571', '4', 'Leave to marinate for a few hours or overnight.'),
('6571', '5', 'When ready to cook, prepare the bbq and let the coals heat up till fiery red.'),
('6571', '6', 'Then pass (soaked wooden) skewers through each piece of swordfish, and place on an oiled rack.'),
('6571', '7', 'Let cook for 5-6 minutes on one side, then flip over and let the other side cook for 2-3 minutes. If not ready, remove to part of grill where heat is indirect and let cook till ready.'),
('6571', '8', 'Serve with thinly sliced red onions, sliced cherry tomatoes, lime halves and coriander leaves'),
('6571', '9', 'In a blender or food processor, grind the peanuts till they are crushed.The ground nuts will stick to the sides of the mixing container, so using a spatula, loosen bits from the bottom and round the sides.'),
('6571', '10', 'Then add oil, drizzling in along with a pinch of salt, blending till you get a ''thick cream'' consistency.'),
('6571', '11', 'Use as directed above.'),
('6574', '1', 'Light a grill or preheat the broiler. In a large skillet, heat 3 tablespoons of the olive oil over high heat.'),
('6574', '2', 'Add the onions, garlic, rosemary, vinegar and honey and cook until the onions soften, about 4 minutes. Season with salt and pepper. Cover and cook over low heat until the onions are very tender, about 10 minutes.'),
('6574', '3', 'Add the plums to the skillet, cover and cook until the plums are tender, about 8 minutes. Discard the rosemary sprigs.'),
('6574', '4', 'Meanwhile, brush the swordfish with the remaining 1 tablespoon of olive oil and season with salt and pepper. Grill the fish until it is just cooked through, about 5 minutes per side. Spoon the onions and plums onto a platter, top with the swordfish and serve.'),
('6575', '1', 'Preheat the grill. Wash the swordfish fillets with cold water and pat dry. Rub with the Cajun seasoning, dividing it evenly between the fillets and coating them well.  Quickly, grill the swordfish, flipping once until cooked through (a few minutes on each side depending on thickness).'),
('6575', '2', 'Remove and allow to rest for about 5 minutes before serving.Meanwhile, make the Tarragon Yogurt Sauce by placing the yogurt, tarragon, a pinch of salt, and lemon juice into a food processor or blender. Process the mixture until smooth. Check seasoning and adjust if needed.To serve, place a piece of swordfish on a plate and top with a generous amount of the Tarragon Yogurt Sauce. Enjoy!'),
('6577', '1', 'Watch how to make this recipe.'),
('6577', '2', 'Blend the basil, pine nuts, garlic, zests, juices, salt, and pepper in a food processor until the mixture is finely chopped. With the machine running, gradually add the olive oil until the mixture is smooth and creamy.'),
('6577', '3', 'Transfer to a bowl and stir in the Parmesan.'),
('6577', '4', 'Place a grill pan over medium-high heat or preheat a gas or charcoal grill.'),
('6577', '5', 'Brush both sides of the swordfish fillets with olive oil and season with salt and pepper. Grill the swordfish about 3 to 4 minutes on each side for a 1-inch thick fillet.'),
('6577', '6', 'Transfer the grilled swordfish to serving plates, top with the citrus pesto, and serve.'),
('6580', '1', 'Prepare coals for grilling or preheat the broiler.'),
('6581', '1', 'Trim the swordfish steaks to remove any bloodlines.  Pat them dry and refrigerate, uncovered, for about an hour before cooking.'),
('6581', '2', 'Cut an x in the bottom end of each tomato.  Briefly blanch the tomatoes in boiling, salted water and shock them in an ice bath.  When cool enough to handle, core, peel, and seed them, then cut them into chunks.'),
('6581', '3', 'Place the tomatoes in a blender, add the shallot and garlic, and puree until smooth.'),
('6581', '4', 'Heat the olive oil in a small, shallow pan over medium-low heat.'),
('6581', '5', 'Add the saffron, crumbling it with your fingers, and toast in the oil until fragrant.'),
('6581', '6', 'Remove from heat and carefully pour it into the tomato puree.  Whiz the mixture in the blender again to incorporate, then pour the mixture out into the pan.  Warm over medium heat until slightly reduced.'),
('6581', '7', 'Season the swordfish steaks with salt on both sides.'),
('6581', '8', 'Add a thin film of grapeseed oil to the bottom of a skillet and warm over medium-high heat until shimmering.'),
('6581', '9', 'Add the swordfish steaks two at a time and saut until browned and just cooked through, about 3-5 minutes per side, depending on thickness.'),
('6581', '10', 'Stir the sherry vinegar into the coulis, season with salt to taste, and divide the sauce among four plates.'),
('6581', '11', 'Place the seared swordfish steaks on top, and finish with a sprinkle of chopped fresh parsley.'),
('6582', '1', 'Soak the wood chips in water for 1 hour. drain. Meanwhile, in a large, shallow baking dish, combine the lime juice with the olive oil and garlic.'),
('6582', '2', 'Add the swordfish, season with salt and pepper. turn to coat. Refrigerate for 20 minutes.'),
('6582', '3', 'Light a grill. If using charcoal, scatter the wood chips over the coals. If using a gas grill, place the chips in the smoker box or on a 12-inch square of foil. fold the foil into a 6-inch square and poke 12 holes in the top.'),
('6582', '4', 'Place the package near the flames and heat until smoking. Lightly brush the grate with vegetable oil. Grill the swordfish until just cooked through, about 4 minutes per side.'),
('6582', '5', 'Serve with the Charred Tomato Salsa and warm flour tortillas.'),
('6583', '1', 'Saut onion in hot oil in an ovenproof skillet or pan over medium heat 3 minutes or until tender.'),
('6583', '2', 'Add garlic, 1/4 teaspoon salt, and 1/4 teaspoon pepper. saut 1 minute. Reduce heat to low. stir in wine, olives, and capers.'),
('6583', '3', 'Sprinkle fish evenly with remaining salt and pepper.'),
('6583', '4', 'Place fish over onion mixture.'),
('6583', '5', 'Bake, covered, at 400 for 26 minutes or until fish flakes with a fork. Sprinkle with diced tomatoes and parsley.'),
('6585', '1', 'Preheat broiler.'),
('6585', '2', 'Combine first 9 ingredients in a food processor. pulse 3 times or until coarsely chopped.'),
('6585', '3', 'Place fish on a broiler pan coated with cooking spray. spread 1/2 cup shallot mixture evenly over fish. Broil 15 minutes or until fish flakes easily when tested with a fork.'),
('6585', '4', 'Serve the fish with the remaining shallot mixture, and garnish with cilantro sprigs and lemon wedges, if desired.'),
('6586', '1', 'Brush plantain slices and lime halves evenly with 1 tablespoon coconut oil.'),
('6586', '2', 'Place plantains and lime halves, flesh-side down, on a greased grill rack. Grill, covered with grill lid, over medium-high heat (350 to 40'),
('6586', '3', 'about 4 minutes or until golden brown. set aside.'),
('6586', '4', 'Sprinkle swordfish with salt and pepper. brush fillets with remaining 2 tablespoons coconut oil.'),
('6586', '5', 'Place fish on a greased grill rack. Grill, covered, over medium-high heat 1 to 2 minutes on each side or until fish flakes with a fork.'),
('6586', '6', 'Arrange greens on 2 serving plates. Top evenly with fish, plantains, and grilled lime. drizzle with Tomato-Molasses Dressing.'),
('6588', '1', 'Add onion to skillet. season with 1/4 teaspoon salt and crushed red pepper flakes. Cook until softened and sizzling, about 3 minutes.'),
('6588', '2', 'Add tomatoes and stir to combine. Fill tomato can with 1/2 cup hot water and add to pan. Increase heat and bring mixture to a boil. Stir in 3/4 teaspoon salt and mint. reduce heat to a simmer and cook for 5 minutes.'),
('6589', '1', 'In a medium skillet, heat 2 tablespoons of the olive oil.'),
('6589', '2', 'Add the garlic and jalapeo and cook over moderate heat until the garlic is golden, about 2 minutes.'),
('6589', '3', 'Add the orange zest, vermouth and bay leaf and boil over moderately high heat until the liquid has almost evaporated, about 1 minute.'),
('6589', '4', 'Add the tomatoes and their juices and a pinch of salt and simmer over moderate heat, stirring occasionally, until the sauce is slightly thickened, about 10 minutes. Stir in the marjoram. Season with salt and sherry vinegar.'),
('6589', '5', 'In a very large skillet, heat the remaining 1 tablespoon of olive oil. Season the fish with salt and add to the skillet. Cook over high heat until browned, about 4 minutes per side.'),
('6589', '6', 'Add the sauce, shaking the skillet to distribute it evenly. Cover and simmer the swordfish over low heat, turning once, until the steaks are just cooked through, about 4 minutes. Using a spatula, transfer the swordfish to plates. Stir the olives into the sauce and season with salt and sherry vinegar. Spoon the sauce around the steaks and serve.'),
('6590', '1', 'Tip:This recipe can be doubled, but youll need to use two pans for the fish.    In a small bowl, combine the mayonnaise, mustard, horseradish, and capers. stir until well blended.    In another small bowl, combine the paprika, thyme, oregano, garlic powder, 1/2 tsp. salt, and 1/8 tsp. pepper.'),
('6590', '2', 'Brush the swordfish with 1 tsp. of the oil.'),
('6590', '3', 'Spread equal amounts of the paprika mixture onto both sides of the swordfish and let sit for 10 minutes.    In a large cast-iron or heavy-duty skillet, heat the remaining 2 tsp. oil over medium-high heat until very hot.'),
('6590', '4', 'Add the swordfish and cook until well browned, 4 to 5 minutes. Flip the swordfish and continue to cook until the fish is cooked through (cut into it to check) and the second side is well browned, another 3 to 5 minutes.'),
('6590', '5', 'Serve with the rmoulade sauce.    Serving Suggestions'),
('6590', '6', 'Serve with rice and red beans.'),
('6591', '1', 'Place the coconut milk, jalapeo, cilantro, ginger, garlic, lime juice and zest, agave nectar, and olive oil in the blender.Pu Puree until smooth'),
('6591', '2', 'Place the swordfish in a shallow glass dish and pour the coconut mixture over them, Cover and refrigerate ofr   4 hours.'),
('6591', '3', 'Cut a sheet of heavy duty aluminum foil for each piece of fish to enclose it completely when roasting.'),
('6591', '4', 'Preheat oven to 450 degrees.'),
('6591', '5', 'Remove fish pieces from marinade.'),
('6591', '6', 'Place each piece on  a sheet of foil, Sprinkle with salt and pepper, and top with a basil leaf.'),
('6591', '7', 'Seal pouches and place on baking sheet in over.'),
('6591', '8', 'Bake at 450F for 8-10 minutes and let sit, still wrapped in foil, on a platter until ready to serve.'),
('6591', '9', 'Meanwhile, heat the remaining marinade in a saucepan, add the cream or half and half, and the avocado. When warmed, turn off the stove and puree with an immersion mixer.'),
('6591', '10', 'To serve: divide the greens among four plates.'),
('6591', '11', 'Remove the fish from packets and slice in thin pieces. Put each set of slices on top of the greens.'),
('6591', '12', 'Drizzle the sauce over the fish and greens.'),
('6591', '13', 'Serve with rice and garnish with diced cucumber and extra sauce on the side.'),
('6592', '1', 'Preheat broiler.'),
('6592', '2', 'Combine first 7 ingredients in a small saucepan. Dip each steak into the lime mixture to coat.'),
('6592', '3', 'Place fish on a broiling pan coated with cooking spray. Sprinkle with salt and pepper. Broil 10 minutes or until fish flakes easily when tested with a fork.'),
('6592', '4', 'While fish cooks, place lime juice mixture over medium heat. cook until reduced by half (about 8 minutes).'),
('6592', '5', 'Serve sauce with fish.'),
('6593', '1', 'Watch how to make this recipe.'),
('6593', '2', 'Prepare the grill (medium-high heat).'),
('6593', '3', 'Whisk the oil, mint, lemon juice, basil, and garlic in a medium bowl to blend. Season the lemon and olive oil mixture with salt and pepper, to taste.'),
('6593', '4', 'Brush the swordfish steaks with 2 tablespoons of the lemon and olive oil mixture. Grill the steaks until just cooked through, about 3 minutes per side (depending on thickness of steaks).'),
('6593', '5', 'Transfer the steaks to plates. Spoon the remaining sauce over and serve.'),
('6595', '1', 'Pour dressing over fish in shallow glass dish. turn fish over to coat both sides of each steak with dressing.  Refrigerate 30 min. to marinate.  Meanwhile, combine remaining ingredients. Refrigerate until ready to serve.'),
('6595', '2', 'Heat grill to medium-high heat.'),
('6595', '3', 'Remove fish from marinade. discard marinade. Grill fish 6 to 8 min. on each side or until fish flakes easily with fork.'),
('6595', '4', 'Serve fish with the papaya mixture.'),
('6596', '1', 'Strip rosemary leaves from branches, leaving 2 inches of leaves at tip of stems. chop leaves to measure 2 tablespoons.'),
('6596', '2', 'Whisk together chopped rosemary, garlic, and next 5 ingredients in a small bowl.'),
('6596', '3', 'Alternately thread fish, potato, tomatoes, and onion onto rosemary skewers.'),
('6596', '4', 'Place in a 13- by 9-inch baking dish, and add marinade. Turn skewers gently in marinade to coat.'),
('6596', '5', 'Let stand 15 to 20 minutes.'),
('6596', '6', 'Grill, covered with lid, over medium-high heat (350 to 40'),
('6596', '7', '6 minutes on one side. Turn carefully, and grill 6 additional minutes.'),
('6597', '1', 'In a large enameled cast-iron casserole, heat 2 tablespoons of the olive oil.'),
('6597', '2', 'Add the onion and cook over moderately low heat, stirring occasionally, until softened, about 10 minutes.'),
('6597', '3', 'Add the bell peppers, cover and cook for 10 minutes.'),
('6597', '4', 'Add the tomatoes and cook for 5 minutes.'),
('6597', '5', 'Add the wine and simmer for 5 minutes.'),
('6597', '6', 'Add the oregano, raisins, lime juice, brown sugar and parsley and cook for 3 minutes. Season with salt and pepper.'),
('6597', '7', 'Heat 2 tablespoons of olive oil in each of 2 large skillets.'),
('6597', '8', 'Add 4 steaks to each skillet, season with salt and pepper and cook over moderately high heat until browned on the bottom, about 5 minutes. Turn and cook 3 to 4 minutes longer. Spoon the sauce onto plates, top with the swordfish steaks and serve.'),
('6598', '1', 'Heat greased grill to high heat.'),
('6598', '2', 'Brush fish with oil.  Grill 3 to 4 min. on each side or until fish flakes easily with fork.'),
('6598', '3', 'Meanwhile, melt butter in medium skillet on medium heat.'),
('6598', '4', 'Add leeks. cook and stir until tender.'),
('6598', '5', 'Add remaining ingredients. cook on low until cream cheese is melted and mixture is well blended, stirring frequently.'),
('6598', '6', 'Serve fish topped with sauce.'),
('6599', '1', 'Preheat an outdoor grill for high heat, and lightly oil grate.'),
('6599', '2', 'Cut a slit in steak to create a pocket that is open on one side only. In a cup, mix together 1 tablespoon olive oil and lemon juice. brush over both sides of fish. Set aside.'),
('6599', '3', 'In a small skillet, heat 1 teaspoon olive oil and garlic over medium heat. Cook spinach in oil until wilted.'),
('6599', '4', 'Remove from heat, and stuff into pocket.'),
('6599', '5', 'Place feta in pocket over spinach.'),
('6599', '6', 'Arrange fish on grill, and cook for 8 minutes. Turn over, and continue cooking until cooked through.'),
('6600', '1', 'Light a grill. In a medium bowl, mix the oil with the herbes de Provence and 1/2 teaspoon each of salt and pepper.'),
('6600', '2', 'Add the swordfish cubes and toss to coat. Thread one sixth of the swordfish cubes and 1 slice of pancetta onto each of 6 skewers (or soaked rosemary sprigs), wrapping the pancetta around the fish as you go.'),
('6600', '3', 'Grill the spiedini over high heat, turning occasionally, until the swordfish is cooked through and lightly charred, 8 to 9 minutes.'),
('6600', '4', 'Transfer to plates and serve.'),
('6601', '1', 'Brush swordfish with 3 tbs oil and sprinkle with salt and pepper. Grill 7 minutes on a side over medium hot fire.'),
('6601', '2', 'Remove to platter and squeeze juice of one lime over fish. Tent with aluminum foil and allow to rest for 10 minutes.'),
('6601', '3', 'While steaks are grilling, saute green onions and ginger in oil.'),
('6601', '4', 'Add chicken stock and boil until reduced to a glaze, about 1-2 minutes.'),
('6601', '5', 'Add curry paste and juice of remaining lime, and saute until fragrant.'),
('6601', '6', 'Add tomato and cook until tomato pieces begin to break down.'),
('6601', '7', 'Add coconut milk and simmer about 10 minutes.'),
('6601', '8', 'Serve over fish.'),
('6603', '1', 'In a large skillet (one wide enough to hold swordfish in a single layer), heat oil over medium-high heat.'),
('6603', '2', 'Add onion and garlic. cook, stirring frequently, until onion is lightly browned, 3 to 4 minutes.'),
('6603', '3', 'Remove from heat.'),
('6603', '4', 'Add sun-dried tomatoes, olives, capers, wine and generous pinch red pepper flakes. stir together.'),
('6603', '5', 'Transfer to bowl.'),
('6603', '6', 'Lightly season swordfish with salt and pepper. in a single layer, place fish in skillet.'),
('6603', '7', 'Return skillet to medium-high heat, cover and cook for 3 minutes per side.'),
('6603', '8', 'When swordfish is cooked through and browned, cover with sauce and warm.'),
('6603', '9', 'Sprinkle roughly torn basil and serve.  This dish can also be served room temperature.'),
('6604', '1', 'To prepare sauce, combine the first 6 ingredients in a small bowl.'),
('6604', '2', 'To prepare fish, heat a nonstick grill pan over medium-high heat.'),
('6604', '3', 'Combine paprika and next 6 ingredients (through red pepper). sprinkle over both sides of fish. Lightly coat both sides of fish with cooking spray. add fish to pan. Cook 4 minutes on each side or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('6604', '4', 'Serve with the sauce.'),
('6604', '5', 'Garnish with mint sprigs, if desired.'),
('6606', '1', 'In a glass baking dish, combine the garlic, white wine, lemon juice, soy sauce, olive oil, poultry seasoning, salt and pepper.'),
('6606', '2', 'Mix just to blend.'),
('6606', '3', 'Place swordfish steaks into the marinade, and refrigerate for 1 hour, turning frequently.'),
('6606', '4', 'Preheat an outdoor grill for high heat, and lightly oil the grate.'),
('6606', '5', 'Grill swordfish steaks for 5 to 6 minutes on each side.'),
('6606', '6', 'Garnish with parsley and lemon wedges.'),
('6609', '1', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray. Sprinkle fish evenly with salt and black pepper.'),
('6609', '2', 'Add fish to pan. saut 5 minutes on each side or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('6609', '3', 'Remove fish from pan. cover and keep warm.'),
('6609', '4', 'Recoat pan with cooking spray. add nuts and garlic to pan. Saut for 30 seconds.'),
('6609', '5', 'Add 2 tablespoons raisins, orange juice, kalamata olives, and bell pepper to pan. cook 1 minute or until liquid evaporates.'),
('6609', '6', 'Serve with fish.'),
('6611', '1', 'Stir together lime juice, honey, oil, and coriander in a shallow dish.'),
('6611', '2', 'Add swordfish, turning to coat, and marinate at room temperature, turning over once, 15 minutes. (Do not marinate longer.)'),
('6612', '1', 'Make the salsa: In a medium-size bowl, combine oranges, pineapple chunks, mango, minced jalapenos, 3 tablespoons orange juice, diced red bell pepper, sugar, and cilantro.'),
('6612', '2', 'Mix well, and refrigerate covered.'),
('6612', '3', 'In a non-reactive bowl, mix 1/2 cup orange juice, olive oil, cayenne pepper, and pineapple juice concentrate.'),
('6612', '4', 'Place swordfish steaks in bowl, and turn to coat well. Marinate the swordfish in the mixture for 30 minutes.'),
('6612', '5', 'Prepare an outside grill with oiled rack set 6 inches from the heat source. On a gas grill, set the heat to medium-high.'),
('6612', '6', 'Grill the swordfish on each side for a total time of about 12 to 15 minutes, until opaque in the center.'),
('6612', '7', 'Serve the grilled fish with the salsa.'),
('6613', '1', 'Rinse and pat dry swordfish.'),
('6613', '2', 'Place fish in a glass baking dish. In a large mixing bowl, whisk together white wine, soy sauce, mustard, ginger, garlic, sesame oil, olive oil and 1/4 cup lemon juice.'),
('6613', '3', 'Pour sauce over fish, cover and refrigerate for several hours or overnight.'),
('6613', '4', 'Remove swordfish from marinade. reserve marinade. Use a sharp knife to cut pockets into the sides of the swordfish steaks.'),
('6613', '5', 'In a large bowl, toss together arugula, tomato, 3 tablespoons olive oil and 3 tablespoons lemon juice. Stuff swordfish with arugula mixture and seal with toothpicks.'),
('6613', '6', 'Place marinade in a small saucepan and cook over high heat until reduced by half.'),
('6613', '7', 'Heat a grill or broiler to high heat. Grill swordfish for 5 minutes on each side. Spoon reduced marinade over swordfish and serve.'),
('6617', '1', 'Light a grill or preheat the broiler. In a small bowl, mix the lemon juice with the salt until the salt dissolves. Stir in the oregano. Slowly whisk in the olive oil and season generously with pepper.'),
('6617', '2', 'Grill the swordfish steaks over high heat (as close to the heat as possible), turning once, until cooked through, 6 to 7 minutes.'),
('6617', '3', 'Transfer the fish to a platter. Prick each fish steak in several places with a fork to allow the sauce to penetrate. Using a spoon, beat the sauce, then drizzle it over the fish.'),
('6617', '4', 'Serve at once.'),
('6618', '1', 'Rub the swordfish with salt and pepper, brush it generously with olive oil and let stand until ready to use.'),
('6618', '2', 'Place the orange and lemon juices in a small saucepan over medium-high heat and cook until reduced to 1/3 cup, 10 to 12 minutes. Reduce the heat to low, whisk in 1 teaspoon of the honey, and taste the orange sauce. it should be nicely sweet and tart. If it is too tart, add more honey.'),
('6618', '3', 'Let the sauce cook for another minute. Season the sauce with salt to taste and keep warm until ready to serve.'),
('6618', '4', 'Light the grill and preheat it to high or preheat the broiler.'),
('6618', '5', 'Grill the swordfish on an oiled grate positioned 5 inches above the glowing coals, or broil it, until just cooked through, 3 to 4 minutes per side. The fish is done when it just flakes when prodded with a fork.'),
('6618', '6', 'Transfer the fish to a plate and cover it with aluminum foil to keep warm.'),
('6618', '7', 'Heat 1 teaspoons olive oil in a large skillet over high heat with the garlic.'),
('6618', '8', 'Add the asparagus and cook, tossing, for 1 minute.'),
('6618', '9', 'Add the fish stock and thyme and bring to a boil. Cover the skillet and cook the asparagus until it is bright green and crisp-tender, 3 to 5 minutes.'),
('6618', '10', 'Transfer the asparagus to a plate. Continue to cook the fish stock mixture until it is reduced and syrupy, 3 to 5 minutes. Divide the asparagus among 4 plates and drizzle the fish stock mixture on it. Arrange a fish steak on each plate and drizzle the orange sauce over the asparagus and the fish.'),
('6618', '11', 'Drizzle a little olive oil over each serving and sprinkle sea salt on top.'),
('6618', '12', 'Serve at once.'),
('6618', '13', 'var article'),
('6618', '14', 'Type_27_data = {}.'),
('6618', '15', 'article'),
('6618', '16', 'Type_27_data.init_step_by_step_images = 0.'),
('6619', '1', 'Combine the garlic, lemon juice, 6 tablespoons of the olive oil, and the oregano in a large plastic bag with a resealable closure.'),
('6619', '2', 'Add the swordfish and marinate in the refrigerator, turning the bag over once or twice, for 1 to 2 hours.'),
('6619', '3', 'Toss the tomatoes with the salt and drain in a colander for 15 minutes. Pat dry on paper towels. Soak the red onion in ice water for 20 minutes.'),
('6619', '4', 'Drain and pat dry.'),
('6619', '5', 'Combine the tomatoes, onion, cucumber, olives, radishes, feta, capers, vinegar, and the remaining 2 tablespoons olive oil in a large bowl. Toss well and season with salt and pepper. You should have about 3 cups.'),
('6619', '6', 'Prepare a charcoal fire and allow the coals to burn down to a gray ash. Lightly oil the grill and set about 4 inches from the coals. (Alternatively, preheat a large well-oiled grill pan or preheat the broiler and set a broiling pan about 4 inches from the heat.)'),
('6619', '7', 'Remove the sword-fish from the marinade and pat dry with paper towels. Season on both sides with salt and pepper. Grill or broil until lightly browned and slightly firm to the touch, 4 to 5 minutes per side.'),
('6619', '8', 'Serve on warmed plates topped with a spoonful of the salsa.'),
('6619', '9', 'Garnish each plate with a pinch of the shredded basil.'),
('6619', '10', 'Serve the remaining salsa on the side.'),
('6619', '11', 'var article'),
('6619', '12', 'Type_27_data = {}.'),
('6619', '13', 'article'),
('6619', '14', 'Type_27_data.init_step_by_step_images = 0.'),
('6620', '1', 'In a medium saucepan, blend coconut milk with ginger, red onion, chili powder, and salt.'),
('6620', '2', 'Mix in mango, and bring to a boil.'),
('6620', '3', 'Place swordfish chunks into the coconut extract mixture, and reduce heat. Taking care not to break up the swordfish chunks, cook, stirring occasionally, 25 to 30 minutes, until the mixture is thickened and fish is easily flaked with a fork.'),
('6621', '1', 'Cut off the top third of each artichoke, snip off the sharp tips from the remaining leaves, and trim the bottom slightly so that it is even.'),
('6621', '2', 'In a small stockpot, bring 3 quarts of lightly salted water to a boil.'),
('6621', '3', 'Add the artichokes and boil for about 20 minutes, or until the outer leaves pull away easily with a sharp tug.'),
('6621', '4', 'Drain the artichokes, immediately plunge them into ice and water to stop the cooking process, and then drain again.'),
('6621', '5', 'Cut the artichokes in half lengthwise, brush them lightly with 2 tablespoons of the vegetable oil, and sprinkle with salt and pepper to taste.'),
('6621', '6', 'Place the artichokes on the grill over a medium-hot fire, cut side down, and cook them for about 10 minutes, or until the cut sides are well browned.'),
('6621', '7', 'Remove the artichokes and cut each half in half.'),
('6621', '8', 'In a medium bowl, combine the artichokes, tomato, olives, parsley, garlic, red pepper flakes, olive oil, and lemon juice and mix well. Set aside.'),
('6622', '1', 'Light a grill. Soak the bay leaves in hot water for 10 minutes, then drain. Alternately thread the swordfish, bay leaves and lemon wedges onto skewers.'),
('6622', '2', 'Drizzle with olive oil and season with salt and pepper. Grill the kebabs over high heat, turning occasionally, until the fish is cooked through and the lemons are charred in spots, about 5 minutes.'),
('6622', '3', 'Serve right away.'),
('6624', '1', 'Combine the first 8 ingredients in a large bowl.'),
('6624', '2', 'Add fish, turning to coat. Cover and refrigerate for 1 hour, turning the bag occasionally.'),
('6624', '3', 'Prepare grill.'),
('6624', '4', 'Place fish on grill rack coated with cooking spray. grill 4 minutes on each side or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('6625', '1', 'Build a medium fire in a charcoal grill, or heat a gas grill to medium-high. (Alternatively, heat a grill pan over medium-high heat.) Bring oil and garlic to a simmer in a small saucepan over medium heat and cook until garlic is toasted and light golden brown, about 6 minutes (remove from heat if garlic is cooking too quickly).'),
('6625', '2', 'Pour oil through a fine-mesh sieve into a small bowl and let cool. (The garlic could burn if left in the oil.) Reserve garlic chips for garnish.'),
('6625', '3', 'Combine peppers, onion, jalapeo, vinegar, and 1/4 cup garlic oil in a large bowl.'),
('6625', '4', 'Add arugula. toss to coat. Season salad with salt and pepper.'),
('6625', '5', 'Let stand for 10 minutes.'),
('6625', '6', 'Place 34 cubes swordfish on each skewer.'),
('6625', '7', 'Brush fish with remaining garlic oil. sprinkle with rosemary and season with  salt and pepper. Grill swordfish until just opaque in the center and lightly browned in spots, about  2 minutes on each of the 4 sides.Divide salad among plates.'),
('6625', '8', 'Place a skewer atop each.'),
('6625', '9', 'Garnish with garlic chips and lemon quarters for squeezing over.'),
('6626', '1', 'In a small bowl, soak the raisins in warm water for 10 minutes. drain.'),
('6626', '2', 'In a large skillet, heat 1/4 cup of the olive oil until shimmering.'),
('6626', '3', 'Add the onion, garlic, pine nuts, capers, bay leaves, oregano and crushed pepper and cook over high heat, stirring occasionally, until the onion is softened and lightly browned, about 5 minutes.'),
('6626', '4', 'Add the tomatoes, season with salt and cook until the tomatoes are slightly broken down, about 3 minutes.'),
('6626', '5', 'Add the raisins, vinegar and sugar and cook, stirring, until the sauce thickens, about 5 minutes longer. Discard the bay leaves.'),
('6626', '6', 'In each of 2 medium skillets, heat 1 tablespoon of the olive oil until shimmering. Season the swordfish with salt and pepper and cook over high heat, turning occasionally, until browned outside and just cooked through, about 6 minutes. Spoon the sauce onto plates, top with the swordfish and serve.'),
('6628', '1', 'Bring a large pot of salted water to a boil.'),
('6628', '2', 'Add the pasta shells and cook, stirring often, until al dente.'),
('6628', '3', 'Drain the shells and return to the pot.'),
('6628', '4', 'Meanwhile, heat the olive oil in a large, deep skillet.'),
('6628', '5', 'Add the cubed swordfish, season with salt and pepper and cook over moderately high heat until lightly browned all over, about 4 minutes. With a slotted spoon, transfer the swordfish to a large serving bowl.'),
('6628', '6', 'Add the zucchini, tomatoes and garlic to the skillet and cook over moderately high heat for 3 minutes, stirring.'),
('6628', '7', 'Add the scallions and cook until the tomato skins pop, 2 minutes longer. Return the swordfish and any accumulated juices to the skillet and stir in the mint and parsley.'),
('6628', '8', 'Add the wine and pasta and season with salt and pepper.'),
('6628', '9', 'Transfer to the large bowl and serve.'),
('6629', '1', 'Light a grill. In a small bowl, blend the butter with the basil, capers and 1 teaspoon of the lemon juice. Season with salt and pepper, and refrigerate.'),
('6629', '2', 'In a large, shallow dish, mix the olive oil with the remaining 1 tablespoon of lemon juice. Season the swordfish with salt and pepper and turn the fish in the olive oil mixture. Refrigerate for 15 minutes.'),
('6629', '3', 'Grill the swordfish steaks over a hot fire until nicely charred on the outside and just cooked within, about 4 minutes per side.'),
('6629', '4', 'Transfer the steaks to plates, top each with a dollop of basil-caper butter and serve right away, with the Arugula and Endive Salad with Pine Nuts and Parmesan.'),
('6630', '1', 'Combine olive oil, lemon juice, Dijon mustard, onion, black pepper, Cajun seasoning, cilantro, and cayenne pepper in a shallow glass baking dish.'),
('6630', '2', 'Add swordfish steaks, turning to coat with marinade.  Cover and refrigerate for at least 30 minutes, turning occasionally.'),
('6630', '3', 'Preheat an outdoor grill for high heat, and lightly oil the grate.'),
('6630', '4', 'Grill swordfish steaks for 5 to 6 minutes on each side until the fish flakes easily with a fork.'),
('6631', '1', 'Stir wine, garlic, and 1 teaspoon rosemary together in an 8 inch square baking dish. Sprinkle fish with salt and pepper.'),
('6631', '2', 'Place in the baking dish, turning to coat. Cover, and refrigerate for at least 1 hour.'),
('6631', '3', 'In a small bowl, stir together the lemon juice, olive oil, and remaining rosemary. Set aside.'),
('6631', '4', 'Preheat grill for medium heat.'),
('6631', '5', 'Transfer fish to a paper towel-lined dish, and discard marinade. Lightly oil grill grate to prevent sticking. Grill fish 10 minutes, turning once, or until fish can be easily flaked with a fork.'),
('6631', '6', 'Remove fish to a serving plate. Spoon lemon sauce over the fish, and top each fillet with a slice of lemon for garnish.'),
('6633', '1', 'In a blender or food processor, process the cottage cheese until creamy.'),
('6633', '2', 'Transfer the cottage cheese to a small bowl, and stir in the milk, 1 1/2 teaspoons of the lemon juice, parsley, basil, and 1/2 teaspoon of the dried thyme.  Cover and chill in the refrigerator.'),
('6633', '3', 'Preheat oven to 350 degrees F (175 degrees C).'),
('6633', '4', 'Place the fish in an 8x8 inch baking dish.'),
('6633', '5', 'Pour the water and the remaining lemon juice into the dish.'),
('6633', '6', 'Place the bay leaf in the water, and sprinkle the remaining 1/2 teaspoon of dried thyme over the fish. Cover the dish with foil.'),
('6633', '7', 'Bake in a preheated oven for 20 minutes or until the fish flakes easily when tested with a fork and is opaque all the way through.'),
('6633', '8', 'Meanwhile, place asparagus in a steamer over 1 inch of boiling water, and cover. Cook until tender but still firm, about 2 to 6 minutes.'),
('6633', '9', 'Drain.'),
('6633', '10', 'When fish is done, transfer to a serving platter and arrange the asparagus next to the fish.'),
('6633', '11', 'Serve with the cottage cheese sauce.'),
('6634', '1', 'In a medium bowl, stir together the lime juice, white wine vinegar, salt, pepper, ginger, basil, thyme, parsley, hot pepper sauce, cayenne pepper, and oil.'),
('6634', '2', 'Place the fish fillets into the bowl, cover, and marinate for at least 10 minutes, or preferably up to 3 hours.'),
('6634', '3', 'Preheat broiler or an outdoor grill for high heat.'),
('6634', '4', 'Place fish onto the grill or a broiling pan. Discard marinade. Grill or broil fish about five minutes each side, until the fish flakes easily with a fork.'),
('6635', '1', 'Place swordfish steaks in a large, shallow bowl. In a small bowl, mix lemon juice, dry sherry, ginger and mango chutney.'),
('6635', '2', 'Pour the mixture over swordfish steaks, turning steaks to coat. Cover, and marinate in the refrigerator 1 hour.'),
('6635', '3', 'Preheat oven to 350 degrees F (175 degrees C).'),
('6635', '4', 'Place swordfish steaks in a medium baking dish. Cover with marinade.'),
('6635', '5', 'Bake in the preheated oven 20 to 30 minutes, basting occasionally with marinade, until fish is easily flaked with a fork.'),
('6638', '1', 'In a large, shallow dish, combine the olive oil, garlic, cumin, paprika, parsley and crushed red pepper.'),
('6638', '2', 'Add the swordfish and stir to coat with the marinade. Refrigerate for 1 hour.'),
('6638', '3', 'Light a grill. Thread the swordfish onto 6-inch skewers. Season with salt. Grill the kebabs over a hot fire, turning once, until lightly charred and cooked through, about 8 minutes.'),
('6638', '4', 'Serve hot, with lemon wedges and harissa.'),
('6639', '1', 'To prepare salsa, combine first 9 ingredients.'),
('6639', '2', 'To prepare fish, rub cut sides of garlic over fish. place fish in a small zip-top plastic bag.'),
('6639', '3', 'Add 1 1/2 tablespoons lime juice to bag. seal. Marinate in refrigerator 30 minutes, turning once.'),
('6639', '4', 'Preheat broiler.'),
('6639', '5', 'Remove fish from marinade, discarding marinade. Sprinkle fish with salt, cumin, and black pepper. place fish on a broiler pan coated with cooking spray. Broil 5 minutes on each side or until fish flakes easily when tested with a fork.'),
('6639', '6', 'To prepare rice, heat oil in a medium saucepan over medium-high heat.'),
('6639', '7', 'Add onion. saut until tender.'),
('6639', '8', 'Add rice. cook 2 minutes, stirring frequently.'),
