INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('35427', '2', 'Makes an 8-inch triple-layer cake. serves 12 to 162 cups all-purpose flour2 1/2 cups sugar3/4 cup unsweetened cocoa powder, preferably Dutch process2 teaspoons baking soda1 teaspoon salt1 cup neutral vegetable oil, such as canola, soybean or vegetable blend1 cup sour cream1 1/2 cups water2 tablespoons distilled white vinegar1 teaspoon vanilla extract2 eggs1/2 cup coarsely chopped peanut brittle'),
('35427', '3', 'Preheat the oven to 350 degrees F. Butter the bottoms and sides of three 8-inch round cakepans. Line the bottom of each pan with a round of parchment or waxed paper and butter the paper.'),
('35427', '4', 'Sift the flour, sugar, cocoa powder, baking soda, and salt into a large bowl.'),
('35427', '5', 'Whisk to combine them well.'),
('35427', '6', 'Add the oil and sour cream and whisk to blend. Gradually beat in the water. Blend in the vinegar and vanilla.'),
('35427', '7', 'Whisk in the eggs and beat until well blended. Scrape down the sides of the bowl and be sure the batter is well mixed. Divide among the 3 prepared cake pans.'),
('35427', '8', 'Bake for 30 to 35 minutes, or until a cake tester or wooden toothpick inserted in the center comes out almost clean.'),
('35427', '9', 'Let cool in the pans for about 20 minutes. Invert onto wire racks, carefully peel off the paper liners, and let cool completely. (Deb note: These cakes are very, very soft. I found them a lot easier to work with after firming them up in the freezer for 30 minutes. Theyll defrost quickly once assembled. Youll be glad you did this, trust me.)'),
('35427', '10', 'To frost the cake, place one layer, flat side up, on a cake stand or large serving plate.'),
('35427', '11', 'Spread 2/3 cup cup of the Peanut Butter Frosting evenly over the top. Repeat with the next layer.'),
('35427', '12', 'Place the last layer on top and frost the top and sides of the cake with the remaining frosting. (Deb note 1: Making a crumb coat of frostinga thin layer that binds the dark crumbs to the cake so they dont show up in the final outer frosting layeris a great idea for this cake, or any with a dark cake and lighter-colored frosting. Once you mask your cake, let it chill for 15 to 30 minutes until firm, then use the remainder of the frosting to create a smooth final coating. Deb note 2: Once the cake is fully frosting, it helps to chill it again and let it firm up. The cooler and more set the peanut butter frosting is, the better drip effect youll get from the Chocolate-Peanut Butter Glaze.)'),
('35427', '13', 'To decorate with the Chocolate'),
('35427', '14', 'Peanut Butter Glaze, put the cake plate on a large baking sheet to catch any drips. Simply pour the glaze over the top of the cake, and using an offset spatula, spread it evenly over the top just to the edges so that it runs down the sides of the cake in long drips. Refrigerate, uncovered, for at least 30 minutes to allow the glaze and frosting to set completely.'),
('35427', '15', 'Remove about 1 hour before serving. Decorate the top with chopped peanut brittle.Peanut Butter Frosting'),
('35427', '16', 'Makes about 5 cups10 ounces cream cheese, at room temperature1 stick (4 ounces) unsalted butter, at room temperature5 cups confectioners sugar, sifted2/3 cup smooth peanut butter, preferably a commercial brand (because oil doesnt separate out)'),
('35427', '17', 'In a large bowl with an electric mixer, beat the cream cheese and butter until light and fluffy. Gradually add the confectioners sugar 1 cup at a time, mixing thoroughly after each addition and scraping down the sides of the bowl often. Continue to beat on medium speed until light and fluffy, 3 to 4 minutes.'),
('35427', '18', 'Add the peanut butter and beat until thoroughly blended.Chocolate-Peanut Butter Glaze'),
('35427', '19', 'Makes about 1 1/2 cups8 ounces seimsweet chocolate, coarsely chopped3 tablespoons smooth peanut butter2 tablespoons light corn syrup1/2 cup half-and-half'),
('35427', '20', 'In the top of d double boiler or in a bowl set over simmering water, combine the chocolate, peanut butter, and corn syrup. Cook, whisking often, until the chocolate is melted and the mixture is smooth.'),
('35427', '21', 'Remove from the heat and whisk in the half-and-half, beating until smooth. Use while still warm.'),
('35433', '1', 'Weigh or lightly spoon baking mix into dry measuring cups. level with a knife.'),
('35433', '2', 'Combine baking mix and next 4 ingredients in a medium bowl, stirring well with a whisk. Fold in banana.'),
('35433', '3', 'Heat a large nonstick skillet or griddle over medium heat.'),
('35433', '4', 'Pour 1/4 cup batter per pancake onto hot pan. Cook 2 to 3 minutes or until tops are covered with bubbles and edges look cooked. Carefully turn pancakes over. cook 2 to 3 minutes or until bottoms are lightly browned. Repeat procedure with remaining batter.'),
('35435', '1', 'Lightly spoon flour into a dry measuring cup. level with a knife.'),
('35435', '2', 'Place peanut butter, sugar, and egg in a medium bowl. beat with a mixer at medium speed until smooth.'),
('35435', '3', 'Add flour. stir well. Shape dough into 36 (1-inch) balls. place 1-inch apart on baking sheets coated with cooking spray. Press thumb into center of each cookie, leaving an indentation. Cover and chill 3 hours.'),
('35435', '4', 'Preheat oven to 37'),
('35435', '5', 'Bake cookies at 375 for 12 minutes or until golden.'),
('35435', '6', 'Remove from pans. cool on wire racks. Spoon 1/2 teaspoon jam into the center of each cookie.'),
('35436', '1', 'Combine first 3 ingredients in a glass bowl. microwave at HIGH 3 to 4 minutes or until melted, stirring once. Stir in vanilla.'),
('35436', '2', 'Fold in 6 cups cereal and peanuts.'),
('35436', '3', 'Spread mixture into a lightly greased 13- x 9-inch pan. Cover and chill 1 hour or until set. cut into small squares.'),
('35436', '4', 'Prep: 10 min., Chill: 1 hr.'),
('35450', '1', 'Prepare the crust: Spray a 9-by-5-inch metal loaf pan with cooking spray and line with plastic wrap, leaving a 2-inch overhang on all sides. spray the plastic wrap. Finely grind the peanuts and graham crackers in a food processor.'),
('35450', '2', 'Add the melted butter and pulse until combined. Press the mixture into the bottom of the prepared pan and refrigerate.'),
('35450', '3', 'Make the ice cream: Bring 2 inches of water to a simmer in a saucepan over medium heat. Fill a bowl with ice water.'),
('35450', '4', 'Whisk the egg yolks, 1/2 cup sugar, the banana puree, hazelnut liqueur and salt in a large metal bowl.'),
('35450', '5', 'Place the bowl over the pot of simmering water (do not let the bowl touch the water) and whisk until thickened, 8 to 10 minutes.'),
('35450', '6', 'Remove the bowl from the pot and put in the ice water to cool.'),
('35450', '7', 'Beat the heavy cream and the remaining 1/4 cup sugar with a mixer until the cream just holds stiff peaks (do not overbeat). Gently fold the cream into the banana custard.'),
('35450', '8', 'Heat the peanut butter in the microwave until soft, about 20 seconds. let cool slightly.'),
('35450', '9', 'Drop spoonfuls of the peanut butter into the banana cream and fold until swirled.'),
('35450', '10', 'Spread the mixture over the crust in the pan, cover with plastic wrap and freeze until firm, at least 9 hours. Lift out of the pan using the plastic wrap and cut into 1-inch slices.'),
('35450', '11', 'Photograpy by Kate Sears'),
('35453', '1', 'Combine powdered sugar, peanut butter, and cream cheese in a large bowl. beat with a mixer at medium speed until smooth.'),
('35453', '2', 'Add milk. beat until combined. Fold in whipped topping. Divide mixture evenly between crusts. chill 8 hours or until set (pies will have a soft, fluffy texture).'),
('35453', '3', 'Cut into wedges. drizzle with chocolate syrup.'),
('35457', '1', 'Combine powdered sugar, peanut butter, and cream cheese in a large bowl. beat with a mixer at medium speed until smooth.'),
('35457', '2', 'Add milk. beat until combined. Fold in whipped topping. Divide mixture evenly between crusts. chill 8 hours or until set (pies will have a soft, fluffy texture).'),
('35457', '3', 'Cut into wedges. drizzle with chocolate syrup.'),
('35461', '1', 'Combine peanut butter and yogurt, stirring until smooth.'),
('35461', '2', 'Drizzle juice over bananas. toss gently to coat.'),
('35461', '3', 'Spread about 3 tablespoons peanut butter mixture over each tortilla, leaving a 1/2-inch border. Arrange about 1/3 cup banana slices in a single layer over peanut butter mixture.'),
('35461', '4', 'Combine wheat germ and cinnamon. sprinkle evenly over banana slices.'),
('35461', '5', 'Roll up. Slice each roll into 6 pieces.'),
('35483', '1', 'To make the crust:Preheat oven to 350F.'),
('35483', '2', 'Combine all the crust ingredients in a medium bowl, stirring until moistened. Press the mixture evenly on the bottom and up the sides of a 9-inch pie pan.'),
('35483', '3', 'Bake for 10 minutes. Set aside to cool.To make the filling'),
('35483', '4', 'Using an electric mixer on medium speed, beat the cream cheese, peanut butter, confectioners sugar, and vanilla until combined.In a separate bowl, use an electric mixer with a whisk attachment to whip cream until soft peaks form. Gently fold the whipped cream into the cream cheese mixture. Fold in the chocolate chips.'),
('35483', '5', 'Pour the filling into the baked crust. Refrigerate for about 4 hours, or until set, before serving. Keep pie refrigerated.'),
('35484', '1', 'Preheat oven to 350 degrees F. Line a six cup cupcake tin with cupcake papers.'),
('35484', '2', 'Combine the egg, peanut butter, oil, and honey in a large bowl.'),
('35484', '3', 'Add in the carrots and stir to combine.'),
('35484', '4', 'Combine the flour and baking soda in a small bowl and add to the carrot mixture. Stir until fully incorporated.Divide among prepared cupcake tins.'),
('35484', '5', 'Bake for 25-30 minutes, until a toothpick inserted in the center comes out with a few crumbs on it.'),
('35484', '6', 'Remove from oven and let cool on wire rack. Frost tops with a little peanut butter before serving to your furry friend.'),
('35491', '1', 'Preheat oven to 350F.Melt butter. Once it has melted, continuing cooking it until it smells nutty and the milk solids have turned light brown. Take off the heat and cool.Bash graham crackers in a zip loc bag until they''re almost a fine powder (a few bigger chunks are ok). In an ovenproof dish, mix together brown butter and pulverized graham crackers.'),
('35491', '2', 'Spread out in a thin layer and toast for about 10 minutes until it''s one shade darker. Keep an eye on it the whole time. Cool.Whip in a standing mixer (or by hand) the peanut butter and vanilla until softened. Set aside.'),
('35491', '3', 'Whisk together half and half, yolks, sugars, and salt. Set aside.Prepare an ice water bath.'),
('35491', '4', 'Place a fine strainer over a medium-sized bowl. Immerse bottom of bowl in a larger bowl filled with ice and water. Set aside.'),
('35491', '5', 'Heat heavy cream in a medium-sized saucepan. Turn off heat as it starts to boil. Take off heat and slowly whisk into half and half/egg mixture.'),
('35491', '6', 'Pour back into the pot and cook on low heat. Stir with a wooden spoon until it thickens slightly. It''s done when you drag your finger across the back of the wooden spoon and it leaves a trail.'),
('35491', '7', 'Pour mixture through the strainer into the bowl that''s over the ice bath.'),
('35491', '8', 'Whisk in softened peanut butter/vanilla mixture. Leave bowl in the ice bath until the custard is cool. Stir every 10 minutes or so.'),
('35491', '9', 'Place saran wrap on top surface of custard to prevent a skin from forming. Refrigerate custard for several hours. Churn in ice cream machine according to manufacturer''s directions. Freeze for a few hours before serving. Top with brown butter graham cracker crumbs.Email This'),
('35491', '10', 'BlogThis!Share to Twitter'),
('35491', '11', 'Share to Facebook'),
('35491', '12', 'Share to Pinterest'),
('35492', '1', 'Line 2 baking sheets with parchment paper. Use a small cookie cutter or drinking glass to trace thirty 1 1/2 -inch circles in rows on the paper, about 1 1/2 inches apart. Flip the paper over (you''ll still be able to see the marks through the paper). Finely grind the peanuts in a food processor.'),
('35492', '2', 'Add the almond flour and confectioners'' sugar and pulse to make a fine powder. Sift twice through a fine sieve. discard any chunks. Beat the egg whites in a bowl with a mixer on high speed until foamy. Gradually add the granulated sugar and beat until soft peaks form.'),
('35492', '3', 'Add the vanilla and beat until stiff peaks form. Fold in half of the peanut mixture with a rubber spatula. Repeat with the remaining peanut mixture.'),
('35492', '4', 'Transfer the batter to a pastry bag with a 1/4 -inch round tip. Holding the bag perpendicular to the baking sheet, pipe mounds of batter into the traced circles on the parchment paper. Tap the baking sheets against the counter to help the batter settle.'),
('35492', '5', 'Let sit at room temperature until the tops are slightly crusty, about 15 minutes.'),
('35492', '6', 'Meanwhile, preheat the oven to 375 degrees F.'),
('35492', '7', 'Bake the macaroons until slightly crisp, 13 to 15 minutes. Slide the parchment paper with the macaroons onto a rack to cool. Carefully remove the macaroons from the parchment paper.'),
('35492', '8', 'Spread 1 teaspoon jam on the flat side of a macaroon. top with another macaroon, flat side down. Repeat with the remaining macaroons and jam. (These are best eaten within 1 day.)'),
('35492', '9', 'Photograph by Kana Okada'),
('35493', '1', 'Line an 8-inch square baking dish with wax paper.'),
('35493', '2', 'Place 9 tablespoons milk in a microwave-safe bowl.'),
('35493', '3', 'Add chocolate chips, cocoa, and coffee. Microwave at HIGH for 1 minute or until melted. Stir in 1/2 teaspoon vanilla.'),
('35493', '4', 'Spread into prepared pan.'),
('35493', '5', 'Combine the remaining milk, peanut butter chips, and peanut butter in a microwave-safe bowl. Microwave at HIGH for 1 minute or until melted. Stir in remaining 1/2 teaspoon vanilla.'),
('35493', '6', 'Spread evenly over chocolate layer, and sprinkle with peanuts. Cover and chill 2 hours.'),
('35493', '7', 'Cut into 25 squares.'),
('35496', '1', 'Combine first 3 ingredients, and set aside. Beat margarine and peanut butter at medium speed of a mixer until light and fluffy. Gradually add sugars, beating at medium speed until well-blended.'),
('35496', '2', 'Add vanilla and egg white, and beat well.'),
('35496', '3', 'Add flour mixture. stir well. Turn dough out onto wax paper. shape into a 6-inch log. Wrap log in wax paper. freeze 3 hours.'),
('35496', '4', 'Preheat oven to 35'),
('35496', '5', 'Cut log into 24 (1/4-inch) slices, and place slices 1 inch apart on a baking sheet coated with cooking spray.'),
('35496', '6', 'Bake at 350 for 8 to 10 minutes.'),
('35496', '7', 'Remove from pan, and cool on wire racks.'),
('35497', '1', 'Preheat oven to 22'),
('35497', '2', 'Place the chocolate in a medium microwave-safe bowl. microwave at HIGH 45 seconds or until almost melted, stirring until smooth. Cool completely.'),
('35497', '3', 'Cover a large baking sheet with parchment paper. secure with masking tape. Sift together 1/3 cup powdered sugar and cocoa.'),
('35497', '4', 'Place egg whites and cream of tartar in a medium bowl. beat with a mixer at medium speed until soft peaks form. Increase speed to high, and gradually add granulated sugar and then cocoa mixture, 1 tablespoon at a time, beating until stiff peaks form.'),
('35497', '5', 'Add 1/2 cup of egg white mixture to melted chocolate. beat just until blended.'),
('35497', '6', 'Add chocolate mixture to remaining egg white mixture, and beat just until blended.'),
('35497', '7', 'Drop 30 mounds onto prepared baking sheet.'),
('35497', '8', 'Bake at 225 for 1 hour and 15 minutes. Turn oven off. cool meringues in closed oven 1 1/2 hours or until dry. Carefully remove meringues from paper.'),
('35497', '9', 'Combine peanut butter and remaining ingredients, stirring with a whisk until smooth.'),
('35497', '10', 'Spread about 1 teaspoon of peanut butter mixture onto flat sides of 15 meringues, and top with remaining meringues.'),
('35501', '1', 'TIP: The chocolate drizzle on the cookies will harden as it cools.'),
('35501', '2', 'Preheat oven to 35'),
('35501', '3', 'Beat first 4 ingredients at medium speed with an electric mixer until creamy.'),
('35501', '4', 'Add egg, beating until blended.'),
('35501', '5', 'Add baking mix, beating at low speed just until blended. Stir in toffee bits, chopped peanuts, and 2/3 cup chocolate morsels.'),
('35501', '6', 'Drop dough by rounded tablespoonfuls onto ungreased baking sheets. flatten dough with hand.'),
('35501', '7', 'Bake at 350 for 10 to 12 minutes or until golden brown. Cool cookies on baking sheets 1 minute. remove cookies to wire racks.'),
('35501', '8', 'Microwave caramels and 2 tablespoons cream in a glass bowl at HIGH 1 minute. stir. Continue to microwave at 30-second intervals, stirring until caramels melt and mixture is smooth. add remaining cream, if necessary. Stir in vanilla. Spoon caramel mixture evenly onto tops of cookies. drizzle evenly with melted chocolate.'),
('35538', '1', 'Place all ingredients in a blender. process until smooth.'),
('35540', '1', 'Preheat oven to 35'),
('35540', '2', 'Stir together peanut butter and next 4 ingredients in a medium bowl until well blended. Stir in chocolate morsels.'),
('35540', '3', 'Drop dough by rounded tablespoonfuls 2 inches apart onto parchment paper-lined baking sheets.'),
('35540', '4', 'Bake at 350 for 12 to 14 minutes or until puffed and lightly browned. Cool on baking sheets on a wire rack 5 minutes.'),
('35540', '5', 'Transfer to wire rack, and let cool 15 minutes.'),
('35552', '1', 'Preheat oven to 35'),
('35552', '2', 'To prepare crust, place first 4 ingredients in a large bowl. beat with a mixer at medium speed until smooth. Lightly spoon 1 cup flour into a dry measuring cup. level with a knife.'),
('35552', '3', 'Add flour and salt to peanut butter mixture. cut in flour with a pastry blender or 2 knives until mixture resembles coarse meal. Sprinkle surface with cold water, 1 tablespoon at a time. toss with a fork until combined.'),
('35552', '4', 'Shape mixture into 24 balls.'),
('35552', '5', 'Place 1 ball in each of 24 miniature muffin cups coated with cooking spray. Press dough into bottoms and up sides of muffin cups.'),
('35552', '6', 'To prepare filling, combine 2/3 cup brown sugar and the next 4 ingredients (2/3 cup brown sugar through milk) in a small saucepan over medium-low heat. Cook 3 to 4 minutes or until smooth, stirring frequently.'),
('35552', '7', 'Remove from heat. stir in 2 tablespoons flour and egg until well blended. Divide chocolate mixture evenly among muffin cups.'),
('35552', '8', 'Bake at 350 for 10 minutes or until the pastry is lightly browned. cool in pan on a wire rack 5 minutes. Run a knife around outside edges of cups.'),
('35552', '9', 'Remove cups from pan. cool completely on wire rack. Sprinkle with powdered sugar.'),
('35553', '1', 'Prepare the satay sauce by whisking satay sauce ingredients in a bowl until well combined, set aside until needed. In a small bowl, add chili powder, cumin, dried chili flakes and salt to peanut butter..'),
('35553', '2', 'On a nonstick sheet pan, lay out 4 slices of brioche, coat each slice with the spicy peanut butter, and add about 3 slices of cheese to each slice of bread.'),
('35553', '3', 'Put the other slice of bread on top, toast and cut into triangles.'),
('35553', '4', 'Drizzle with satay sauce and serve..'),
('35553', '5', 'Mix well so all ingredients are incorporated well.'),
('35564', '1', 'Place all ingredients in a blender. process until smooth.'),
('35569', '1', 'Combine 1 cup puffed rice cereal and 3/4 cup pretzel sticks, broken into bite-sized pieces. Melt 6 ounces semisweet chocolate chips in a microwave, stirring until smooth.'),
('35569', '2', 'Add 1/4 cup chunky peanut butter, stirring just until combined. Stir chocolate mixture into pretzel mixture. combine well. Drop 20 mounds onto a cookie sheet lined with parchment paper. chill until firm (about 10 minutes).'),
('35578', '1', 'Place banana in freezer. freeze until firm (about an hour).'),
('35578', '2', 'Remove from freezer. let stand 5 minutes.'),
('35578', '3', 'Combine banana and remaining ingredients in a blender. process until smooth.'),
('35578', '4', 'Serve immediately.'),
('35582', '1', 'Light a grill. In a bowl, toss the mango with the chicken and 3 tablespoons of the peanut sauce and season lightly with salt and pepper. Loosely thread the mango and chicken onto 8 skewers, alternating the pieces.'),
('35582', '2', 'Brush the skewers with oil and grill over high heat, turning occasionally, until the chicken is lightly charred in spots and nearly cooked through, 8 to 10 minutes.'),
('35582', '3', 'Brush 2 tablespoons of the peanut sauce on the skewers and grill, turning, until lightly browned, about 2 minutes. If the sauce becomes too thick to brush, thin it slightly with water.'),
('35582', '4', 'Serve the chicken-and-mango skewers with lime wedges and pass the remaining peanut sauce at the table.'),
('35585', '1', 'Preheat oven to 37'),
('35585', '2', 'Stir together chopped peanuts, peanut flour, 1/2 cup all-purpose flour, 1/4 cup light brown sugar, and 3 1/2 tablespoons melted butter until mixture is crumbly.'),
('35585', '3', 'Stir together baking soda, next 3 ingredients, and remaining 1 1/2 cups all-purpose flour in a bowl.'),
('35585', '4', 'Process mango in a blender or food processor 15 to 20 seconds or until pureed.'),
('35585', '5', 'Pour puree into a measuring cup to equal 1 cup. (If necessary, discard any remaining puree, or reserve for another use.)'),
('35585', '6', 'Whisk together 1 cup mango puree, granulated sugar, buttermilk, egg, and remaining 1/4 cup brown sugar and 2 tablespoons melted butter in a medium bowl until well blended. Gradually whisk in flour mixture just until combined.'),
('35585', '7', 'Place baking cups in a muffin pan. Spoon batter into cups, filling two-thirds full. Sprinkle peanut streusel mixture over batter.'),
('35585', '8', 'Bake at 375 for 22 to 24 minutes or until a wooden pick inserted in center comes out clean. Cool in pan on a wire rack 10 minutes. Gently transfer muffins from pan to a wire rack using a knife or metal spatula, and cool completely (about 20 minutes).'),
('35585', '9', '*2 cups frozen cubed mango, thawed, may be substituted.'),
('35585', '10', 'Note: To make ahead, freeze baked, cooled muffins in a heavy-duty zip-top plastic freezer bag up to 1 month. To reheat, remove muffins from baking cups, wrap in a paper towel, and microwave at HIGH 20 seconds or until thoroughly heated. For testing purposes only, we used 12% fat light roast peanut flour.'),
('35591', '1', 'Process first 7 ingredients in a food processor until coarsely chopped, stopping to scrape down sides as needed. With processor running, pour olive oil through food chute in a slow, steady stream, processing until mixture is smooth. Stir in up to 5 Tbsp. water, 1 Tbsp. at a time, for desired consistency.'),
('35591', '2', 'Serve with pita chips, sliced carrots and cucumbers, bell pepper strips, and quartered radishes.'),
('35592', '1', 'Beat butter and sugars with a mixer at medium speed until well blended.'),
('35592', '2', 'Add vanilla and egg. beat well.'),
('35592', '3', 'Add peanut butter. beat until blended. Divide butter mixture evenly between 2 bowls.'),
('35592', '4', 'Lightly spoon flour into dry measuring cups. level with a knife.'),
('35592', '5', 'Combine flour, baking soda, and salt. Spoon half of flour mixture into 1 bowl of butter mixture. stir until well blended.'),
('35592', '6', 'Stir cocoa into remaining flour mixture. add to remaining bowl of butter mixture, stirring until well blended. Cover both bowls of dough, and chill at least 1 hour.'),
('35592', '7', 'Preheat oven to 37'),
('35592', '8', 'Roll peanut butter dough into 76 (1/2-inch) balls.'),
('35592', '9', 'Roll chocolate dough into 76 (1/2-inch) balls. Gently roll together 1 chocolate dough ball and 1 peanut butter dough ball.'),
('35592', '10', 'Place balls 2 inches apart on baking sheets coated with cooking spray. Flatten cookies with the bottom of a glass.'),
('35592', '11', 'Bake at 375 for 8 minutes. Cool 1 to 2 minutes on pans.'),
('35592', '12', 'Remove from pans. cool completely on wire racks.'),
('35593', '1', 'Bake at 350 degrees for 20-25 minutes. Mine were done in about 18.These brownies were a hit. They were a bit dry. I think they would have benefited from some extra moisture somewhere. The taste was really good, though.brownies, chocolate0 Comments'),
('35602', '1', 'In a bowl, with an electric mixer on medium speed, beat butter, granulated sugar, brown sugar, and peanut butter until well blended. Beat in eggs and vanilla until smooth, scraping down sides of bowl as needed.'),
('35602', '2', 'In another bowl, mix flour, cocoa powder, baking powder, and salt. Stir or beat into butter mixture until well incorporated. Stir in chocolate chips, oats, and peanuts.'),
('35602', '3', 'Drop dough in rounded 2-tablespoon portions, 3 inches apart, onto buttered or cooking parchment-lined 12- by 15-inch baking sheets. With a lightly floured fork, flatten slightly into 2 1/2-inch rounds about 1/2 inch thick.'),
('35602', '4', 'Bake in a 350 oven until cookies are golden and tops feel set when lightly pressed, 12 to 14 minutes (they will feel underdone but will firm up as they cool). if baking more than one pan at a time, switch pan positions halfway through baking.'),
('35602', '5', 'Let stand 5 minutes on sheets, then, with a wide spatula, transfer cookies to racks to cool. If hot cookies start to break, slide a thin spatula under them to release. let stand on pan to firm up, 2 to 5 minutes, then transfer to racks to cool completely.'),
('35606', '1', 'Cut chicken into 1/4-inch-thick strips.'),
('35606', '2', 'Coat a medium nonstick skillet or stir-fry pan with cooking spray. add oil.'),
('35606', '3', 'Place over medium-high heat until hot. add chicken, and stir-fry 2 minutes.'),
('35606', '4', 'Add broccoli and next 3 ingredients. stir-fry 2 minutes.'),
('35606', '5', 'Add bean sprouts, snow peas, and water chestnuts. stir-fry 1 minute.'),
('35606', '6', 'Combine chicken broth and next 4 ingredients, stirring until smooth. add to chicken mixture. Cook, stirring constantly, until mixture is slightly thickened and thoroughly heated. Spoon chicken mixture over cooked rice.'),
('35608', '1', 'Process first 7 ingredients in a food processor until coarsely chopped, stopping to scrape down sides. With processor running, pour olive oil through food chute in a slow, steady stream, processing until mixture is smooth. Stir in up to 5 Tbsp. water, 1 Tbsp. at a time, for desired consistency. Stir in sesame seeds.'),
('35608', '2', 'Serve with rice crackers and vegetables.'),
('35609', '1', 'Place potato in a microwave-safe dish. Spray potato with cooking spray, and sprinkle with salt and pepper.'),
('35609', '2', 'Add 2 tablespoons water. cover and microwave at HIGH 5 minutes or until tender.'),
('35609', '3', 'Combine lime juice, oil, honey, and ginger in a small bowl. stir well with a whisk.'),
('35609', '4', 'Combine potato, lettuce, chicken, peanuts, mint, and cilantro in a large bowl.'),
('35609', '5', 'Add dressing. toss gently to coat.'),
('35610', '1', 'In a medium saucepan, over medium heat, heat the oil and garlic for 1 minute.'),
('35610', '2', 'Add the tomatoes, tomato paste, peanut butter, broth, vinegar, cayenne, and salt and whisk to combine. Bring to a boil.'),
('35610', '3', 'Add the rice, reduce heat to low, cover, and cook for 20 minutes. Ladle into individual bowls and garnish with the scallions and peanuts.Tip: For a more substantial soup, add an additional spoonful of cooked rice to the bowl with the scallions and peanuts.'),
('35614', '1', 'Place potatoes in a saucepan. cover with water. Bring to a boil. reduce heat, and simmer 15 minutes or until tender.'),
('35614', '2', 'Drain and cool. Shred potatoes into a large bowl.'),
('35614', '3', 'Cook bacon in a large nonstick skillet over medium heat until crisp.'),
('35614', '4', 'Remove bacon from pan. crumble.'),
('35614', '5', 'Add corn, onion, bell pepper, and chopped thyme to drippings in pan. cook 4 minutes or until onion is tender.'),
('35614', '6', 'Combine potatoes, bacon, corn mixture, green onions, peanuts, salt, and egg. stir with a fork until well blended.'),
('35614', '7', 'Coat a nonstick griddle or large nonstick skillet with cooking spray. Spoon about 1/3 cup potato mixture onto hot griddle or skillet. flatten slightly with a spatula. Cook 5 minutes on each side or until golden brown.'),
('35614', '8', 'Garnish with thyme, if desired.'),
('35623', '1', 'Line a jelly-roll pan with parchment paper.'),
('35623', '2', 'Place chocolate in a small microwave-safe bowl. Microwave at HIGH 1 minute or until chocolate melts, stirring every 15 seconds. Stir in peanut butter until smooth. Working with 1 pretzel at a time, dip and roll 1 end of pretzel in chocolate mixture to coat.'),
('35623', '3', 'Place pretzel on prepared pan. Repeat procedure with remaining pretzels and chocolate mixture.'),
('35623', '4', 'Place in freezer for 30 minutes or until set.'),
('35633', '1', 'Combine peanut butter and honey in a large pot. cook over medium-low heat until peanut butter and honey are melted (about 2-3 minutes).'),
('35633', '2', 'Add crispy brown rice cereal and chopped dried cherries to the mixture. stir until sticky. Press into a 9- x 13-inch pan coated with cooking spray. Chill in refrigerator 40 minutes.'),
('35633', '3', 'Cut into 15 (2 1/2 - x 3-inch) squares. serve.'),
('35641', '1', 'Whisk together all of the dressing ingredients in a bowl or jug.'),
('35641', '2', 'Put the mange-tout, bean sprouts, sliced red pepper, sliced scallions and noodles into a bowl.'),
('35641', '3', 'Pour over the dressing and mix thoroughly to coat everything well.'),
('35641', '4', 'Sprinkle with the sesame seeds and coriander/cilantro and pack up as needed.'),
('35643', '1', 'Preheat oven to 35'),
('35643', '2', 'Beat together butter and sugars at high speed with an electric mixer until smooth and creamy. Stir in vanilla and egg.'),
('35643', '3', 'Lightly spoon flour into a dry measuring cup. level with a knife. Sift together flour and next 3 ingredients.'),
('35643', '4', 'Add to butter mixture, beating well. Stir in remaining ingredients.'),
('35643', '5', 'Drop by level tablespoonfuls 2 inches apart onto parchment-lined baking sheets.'),
('35643', '6', 'Bake at 350 for 12 minutes or until golden brown. (Cookies will be slightly soft in center.) Cool for 3 minutes on baking sheet before removing to wire racks.'),
('35644', '1', 'Place potato in a microwave-safe dish. Spray potato with cooking spray, and sprinkle with salt and pepper.'),
('35644', '2', 'Add 2 tablespoons water. cover and microwave at HIGH 5 minutes or until tender.'),
('35644', '3', 'Combine lime juice, oil, honey, and ginger in a small bowl. stir well with a whisk.'),
('35644', '4', 'Combine potato, lettuce, chicken, peanuts, mint, and cilantro in a large bowl.'),
('35644', '5', 'Add dressing. toss gently to coat.'),
('35646', '1', 'Place all ingredients in a blender. process until smooth. Store in an airtight container in refrigerator for up to 2 days.'),
('35647', '1', 'Save Recipe'),
('35647', '2', 'Print Recipe'),
('35647', '3', 'Peanut Butter Pie for Mikey'),
('35647', '4', 'Ingredients12 oz chocolate cookies6 tbsp melted unsalted butter8 oz finely chopped chocolate or semi-sweet chocolate chips1/4 cup chopped unsalted peanuts1 cup heavy whipping cream8 oz cream cheese (one package)1 cup creamy-style peanut butter1 cup confectioners (powdered) sugar1 can (14 oz.) sweetened condensed milk1 tsp vanilla extract1 tsp freshly squeezed lemon juice'),
('35647', '5', 'You will also need'),
('35647', '6', 'Food processor (optional), 9 inch springform pan, electric mixer'),
('35647', '7', 'Prep Time: 20 Minutes'),
('35647', '8', 'Total Time: 3 Hours'),
('35647', '9', 'Servings: One 9 inch pie (10-12 slices)'),
('35647', '10', 'Kosher Key: Dairy'),
('35655', '1', 'Preheat oven to 35'),
('35655', '2', 'Shape cookie dough into 24 (1-inch) balls, and place in cups of lightly greased miniature muffin pans.'),
('35655', '3', 'Bake 15 to 18 minutes or until edges are lightly browned.'),
('35655', '4', 'Remove from oven, and press 1 miniature peanut butter cup candy into each cookie. Sprinkle each cookie with 1/2 tsp. granola cereal.'),
('35655', '5', 'Note: We tested with Reese''s Peanut Butter Cups and Quaker Natural Granola cereal.'),
('35655', '6', 'Double Peanut Butter Candy Bites With Peanuts: Substitute chopped peanuts for granola. Proceed with recipe as directed.'),
('35655', '7', 'Peanut Butter-Caramel Candy Bites With Granola: Substitute 24 bite-size chocolate-covered caramel-peanut nougat bars for miniature peanut butter cup candies. Proceed with recipe as directed. Note: We tested with Snickers.'),
('35655', '8', 'Peanut Butter-Caramel Candy Bites With Colorful Candies: Substitute 24 bite-size chocolate-covered caramel-peanut nougat bars for miniature peanut butter cup candies. Substitute 72 candy-coated chocolate pieces for granola. Proceed with recipe as directed. Note: We tested with Snickers and M & M''s.'),
('35656', '1', 'Beat butter at medium speed with an electric mixer until creamy. Gradually add sugars, beating until smooth.'),
('35656', '2', 'Add peanut butter and vanilla, beating until blended.'),
('35656', '3', 'Add eggs, 1 at a time, beating after each addition.'),
('35656', '4', 'Combine flour, baking soda, and salt. gradually add to butter mixture, beating at low speed just until blended. Stir in granola and morsels. cover and chill 2 hours.'),
('35656', '5', 'Shape dough into 1 1/2-inch balls, and place the balls 2 inches apart on baking sheets.'),
('35656', '6', 'Bake at 375 for 8 to 10 minutes or until golden. Cool on baking sheets 5 minutes.'),
('35656', '7', 'Remove to wire racks to cool completely.'),
('35656', '8', 'Note: For larger cookies, drop by 1/4 cupfuls onto baking sheets.'),
('35656', '9', 'Bake at 375 for 18 to 20 minutes.'),
('35657', '1', 'Preheat oven to 325F. Butter 9-inch-diameter tart pan with removable bottom.'),
('35657', '2', 'Mix cookie crumbs and butter in medium bowl until moist clumps form. Press mixture onto bottom and up sides of prepared tart pan.'),
('35657', '3', 'Bake until set, about 10 minutes. Cool completely.'),
('35658', '1', 'Bring half-and-half, brown sugar, corn syrup, and salt to a boil in a 2-quart heavy saucepan over moderately high heat, whisking until smooth.'),
('35658', '2', 'Remove from heat and whisk in peanut butter until smooth.'),
('35658', '3', 'Transfer to a glass measure or small heatproof pitcher and cool slightly, about 5 minutes.'),
('35658', '4', 'Divide ice cream among 4 bowls, then top each serving with some banana slices and 3 tablespoons peanut butter sauce. (You will have some sauce left over.)'),
('35673', '1', 'Heat oil in a large saucepan over medium-high heat.'),
('35673', '2', 'Add squash and next 5 ingredients (through coriander). saut 5 minutes or until onion is tender.'),
('35673', '3', 'Add broth, peanut butter, tomato paste, and pepper, stirring well to combine. bring to a boil. Reduce heat. simmer, uncovered, 10 minutes or until the squash is tender. Sprinkle with cilantro.'),
('35674', '1', 'Cook carrots, snow peas, and noodles in boiling water 3 minutes. drain.'),
('35674', '2', 'Heat 2 teaspoons oil in a large nonstick skillet over medium-high heat.'),
('35674', '3', 'Cut chicken crosswise into thin strips.'),
('35674', '4', 'Add chicken and 1 tablespoon soy sauce to pan. stir-fry 3 minutes.'),
('35674', '5', 'Remove chicken from pan. keep warm.'),
('35674', '6', 'Combine remaining 2 tablespoons soy sauce, broth, oyster sauce, sugar, and pepper, stirring well.'),
('35674', '7', 'Heat remaining 1 teaspoon oil over medium-high heat.'),
('35674', '8', 'Add mushrooms and ginger to pan. stir-fry for 3 minutes.'),
('35674', '9', 'Add broth mixture, and cook for 1 minute.'),
('35674', '10', 'Add noodle mixture and chicken to pan. cook 1 minute, tossing to combine. Sprinkle with onions and peanuts.'),
('35678', '1', 'Bring cream and sugar to simmer in saucepan, whisking to dissolve sugar.'),
('35678', '2', 'Remove from heat.'),
('35678', '3', 'Add chocolate. let stand 1 minute.'),
('35678', '4', 'Whisk until smooth.'),
('35678', '5', 'Whisk in peanut butter. Chill uncovered overnight.'),
('35681', '1', 'HEAT oven to 250 F.  COMBINE sugar and syrup in small saucepan. Cook over medium heat, stirring constantly, until mixture begins to boil.'),
('35681', '2', 'Remove from heat. Blend in peanut butter and vanilla.  PLACE popped popcorn and peanuts in a large bowl.'),
('35681', '3', 'Pour peanut butter mixture over popcorn, stirring until coated.  PLACE popcorn in a single layer on a foil-lined cookie sheet.'),
('35681', '4', 'Bake 10 minutes, stirring after 5 minutes.'),
('35681', '5', 'Remove from oven and cool.'),
('35687', '1', 'Preheat oven to 35'),
('35687', '2', 'Coat a 9x 13 baking pan with cooking spray. Set aside.Using an electric mixer, combine flour, brown sugar, peanut butter, and butter.'),
('35687', '3', 'Remove 1 cup of mixture and set aside.'),
('35687', '4', 'Mix in baking powder and baking soda.'),
('35687', '5', 'Mix in milk and vanilla.'),
('35687', '6', 'Add eggs, 1 at a time, mixing well after each addition.'),
('35687', '7', 'Transfer batter to prepared pan. Sprinkle top with reserved flour mixture and chocolate chips.'),
('35687', '8', 'Bake 35-40 minutes, or until a toothpick inserted into the center comes out clean.'),
('35694', '1', 'In a standing electric mixer fitted with the paddle, beat the butter until creamy.'),
('35694', '2', 'Add the brown sugar and beat at medium-high speed until fluffy, 3 minutes. Beat in 1 teaspoon of the vanilla and the 1 whole egg.'),
('35694', '3', 'Add the 2 1/4 cups of flour and 1/2 teaspoon of salt and beat until a soft dough forms. Divide the dough into 2 mounds and transfer to 2 sheets of plastic wrap. Pat each mound of dough into a 1/3-inch-thick square, wrap and refrigerate until firm, 20 minutes.'),
('35694', '4', 'Preheat the oven to 350 and line 2 large baking sheets with parchment paper. Working with 1 square at a time, on a floured work surface, roll the dough out to a 13-inch square,  1/8 inch thick. Using a 2 1/2-inch biscuit cutter, stamp out rounds and arrange them 1/2 inch apart on the baking sheets. repeat with the second square of dough. Gather the scraps and refrigerate until firm. Reroll and cut out more rounds, using the scraps only once. Refrigerate the cookies just until firm, about 10 minutes.'),
('35694', '5', 'Bake the cookies in the upper and middle thirds of the oven for about 15 minutes, until lightly browned, shifting the pans halfway through baking.'),
('35694', '6', 'Let cool slightly, then carefully invert the cookies onto racks and let cool completely.'),
('35694', '7', 'Spread the melted chocolate on half of the cookies and the peanut butter on the other half. Allow the chocolate to set.'),
('35694', '8', 'In a small saucepan, boil the corn syrup over high heat without stirring until it registers 230 to 235 (thread ball) on a candy thermometer. Meanwhile, in a clean standing mixer fitted with the whisk, beat the 2 egg whites with the cream of tartar and a pinch of salt until firm peaks form. Slowly drizzle in the hot corn syrup and beat at high speed until glossy, about 2 minutes. At medium-low speed, beat in the remaining 2 teaspoons of vanilla and the 1 cup of confectioners'' sugar.'),
('35694', '9', 'Transfer the marshmallow to a pastry bag with a plain 1/2-inch tip or a large zippered plastic bag with the corner snipped off. Pipe 1 1/2-tablespoon mounds of the marshmallow onto the chocolate-covered cookies. Top with the peanut buttercovered cookies and press lightly to spread the marshmallow to the edges.'),
('35694', '10', 'Let the moon pies stand in an airtight container for 2 hours (they will soften slightly) before dusting with confectioners'' sugar, cocoa and cinnamon and serving.'),
('35709', '1', 'Preheat oven to 35'),
('35709', '2', 'Combine 1/4 cup condensed milk, butter, and next 3 ingredients (butter through egg white) in a bowl (batter will be very stiff). Coat bottom of a 13 x 9-inch baking pan with cooking spray. Press two-thirds of batter into prepared pan using floured hands. pat evenly (layer will be thin).'),
('35709', '3', 'Bake at 350 for 10 minutes.'),
('35709', '4', 'Combine 1/2 cup condensed milk and marshmallow creme in a bowl. stir in morsels.'),
('35709', '5', 'Spread marshmallow mixture evenly over brownie layer. Carefully drop remaining batter by spoonfuls over marshmallow mixture.'),
('35709', '6', 'Bake at 350 for 30 minutes. Cool completely in pan on a wire rack.'),
('35710', '1', 'Peel cucumbers. cut in half lengthwise, removing and discarding seeds.'),
('35710', '2', 'Cut cucumber halves into half-moon-shaped slices.'),
('35710', '3', 'Whisk together soy sauce and next 7 ingredients in a large bowl. add cucumber, pasta, carrot, and onions, tossing to coat. Cover and chill 8 hours, if desired.'),
('35714', '1', 'Cut tofu crosswise into 8 equal pieces.'),
('35714', '2', 'Cut each piece into two triangles. Arrange tofu in a single layer on several layers of heavy-duty paper towels. Cover tofu with additional paper towels.'),
('35714', '3', 'Place a cutting board on top of tofu.'),
('35714', '4', 'Place a heavy pan on cutting board.'),
('35714', '5', 'Let stand 20 minutes. Pat tofu dry with paper towels.'),
('35714', '6', 'Combine rice and milk in a medium saucepan. bring to a boil. Cover, reduce heat, and simmer for 5 minutes. Stir in onions, cilantro, bell pepper, and 1/2 teaspoon salt. Cover and keep warm.'),
('35714', '7', 'Combine 1 teaspoon water and egg white in a shallow dish.'),
('35714', '8', 'Place peanuts in a food processor. process until finely ground.'),
('35714', '9', 'Combine ground peanuts, garlic powder, ginger, red pepper, and remaining 1/2 teaspoon salt in a shallow dish. Dip one side of each tofu triangle in egg mixture. Dredge the same side in peanut mixture.'),
('35714', '10', 'Heat 1 teaspoon oil in a large nonstick skillet coated with cooking spray over medium heat.'),
('35714', '11', 'Add half of tofu. cook 2 minutes on each side or until browned. (Watch closely to prevent burning.) Repeat procedure with remaining 1 teaspoon oil and tofu.'),
('35714', '12', 'Serve tofu with rice.'),
('35719', '1', 'Preheat oven to 350 degrees F (175 degrees C).'),
('35719', '2', 'In a saucepan over medium heat, combine sugar and water. Bring to a boil, and stir until sugar is dissolved.'),
('35719', '3', 'Add peanuts, and cook stirring, over medium heat until peanuts are evenly coated, and no syrup is left in pan.'),
('35719', '4', 'Spread nuts out on a baking sheet.'),
('35719', '5', 'Bake in preheated oven for 20 minutes, stirring every 5 minutes to evenly roast peanuts.'),
('35732', '1', 'Preheat oven to 375 degrees. Grease a baking sheet. In a large bowl, cream together sugar and butter. Beat in egg to mixture.'),
('35732', '2', 'Mix in peanut butter and vanilla until smooth and creamy. Stir in salt, baking soda and flour until well combined.'),
('35732', '3', 'Roll dough into 1 inch balls and then roll in sugar.'),
('35732', '4', 'Place on baking sheet and flatten with fork.'),
('35732', '5', 'Bake for 12-15 minutes.'),
('35734', '1', 'Preheat the oven to 350 degrees F.'),
('35734', '2', 'Place the toasted bread cubes into a standard loaf pan sprayed with nonstick spray and sprinkle chocolate chips evenly on top.'),
('35734', '3', 'In a blender, combine soymilk, egg substitute, peanut butter, brown sugar, and salt. Process on medium speed until smooth.'),
('35734', '4', 'Pour the mixture over the bread cubes, making sure all the bread cubes are covered.'),
('35734', '5', 'Let stand 5 minutes.'),
('35734', '6', 'Place dish in the oven and bake until pudding is firm, 45 to 50 minutes. Top with whipped topping and garnish with additional chocolate chips and chopped peanuts, if using. Slice, serve, and enjoy!'),
('35736', '1', 'Place peanuts in a spice or coffee grinder. process until medium ground.'),
('35736', '2', 'Heat oil in a large Dutch oven over medium-high heat.'),
('35736', '3', 'Add onion. saut 10 minutes or until lightly browned. Stir in ground peanuts, water, and next 5 ingredients (water through sweet potato). bring to a boil. Reduce heat, and simmer 15 minutes. Stir in chicken. cook 10 minutes or until chicken is done. Stir in cilantro.'),
('35736', '4', 'Note: To make ahead, prepare the soup as directed, but stop before adding the cilantro. Cover soup and refrigerate up to two days.'),
('35736', '5', 'Let stand 30 minutes at room temperature. place in a saucepan over medium heat. Cook the soup until thoroughly heated. stir in cilantro.'),
('35737', '1', 'Combine first 3 ingredients in a small bowl, tossing well.'),
('35737', '2', 'Combine peanuts and bread slice in a food processor. process until finely chopped. Sprinkle salt and pepper evenly over chicken. Dredge chicken in the breadcrumb mixture.'),
('35737', '3', 'Heat oil in a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('35737', '4', 'Add chicken to pan. cook 2 minutes on each side or until done.'),
('35737', '5', 'Serve chicken with pineapple mixture.'),
('35737', '6', 'Garnish with cilantro sprigs, if desired.'),
('35740', '1', 'Preheat broiler.'),
('35740', '2', 'Cook rice according to package directions, omitting salt and fat.'),
('35740', '3', 'Drain. cover and keep warm.'),
('35740', '4', 'Cut steak diagonally across grain into 1/4-inch-thick slices.'),
('35740', '5', 'Combine steak and hoisin in a bowl. toss to coat. Thread steak onto each of 8 (8-inch) skewers. sprinkle evenly with salt.'),
('35740', '6', 'Place skewers on a broiler pan coated with cooking spray. broil 3 minutes on each side or until desired degree of doneness. Sprinkle skewers with cilantro.'),
('35740', '7', 'Combine coconut milk and remaining ingredients in a bowl, stirring until smooth.'),
('35740', '8', 'Serve with skewers and rice.'),
('35758', '1', 'Wash the rice. This is one of the most crucial steps in creating a delicate pulao, where each grain of rice is separate from the other.'),
('35758', '2', 'Pour the rice into a large bowl and fill with fresh water. Gently wash the rice, running your hand through the rice without breaking the grains. The water will go smoky.'),
('35758', '3', 'Pour off the water and fill the bowl again. Wash, drain, and repeat 3 or 4 times until the water runs clear. By washing the rice in this way, you''ve just removed the excess starch from the rice so the grains won''t stick together.'),
('35758', '4', 'In a Dutch oven over medium-high heat, warm the canola oil until it''s shimmering, but not smoking.'),
('35758', '5', 'Add the cardamom, cinnamon, and cloves - they should sizzle as they hit the oil.'),
('35758', '6', 'Saute gently until their woodsy aromas waft up into your nostrils.'),
('35758', '7', 'Add the Ginger-Garlic Paste and the chopped scallions and saute 1 minute or so until they soften.'),
('35758', '8', 'Add the rice to the pot, season with salt, and saute gently until the grains aren''t sticking together anymore and the rice turns translucent, about 2 minutes. You should also start to smell the basmati''s gentle aroma. This smell always reminds me of my mum!'),
('35758', '9', 'Add the can of tomatoes and stir. Cook about 2 minutes to get rid of some of the excess liquid.'),
('35758', '10', 'Add the water and salt and turn the heat up so that the contents of the pot come to a boil. Then turn the heat down as low as it can go, put a lid on it, and cook for 15 minutes. Don''t take the lid off at all during this process! Once the 15 minutes are over, resist the temptation to take the lid off again.'),
('35758', '11', 'Let it sit 5 minutes off heat. This will steam the rice and give you a nice, fluffy pulao.'),
('35758', '12', 'Finish with a flourish of peanuts and a sprinkling of the scallion greens and serve.'),
('35758', '13', 'Throw the garlic, ginger, and canola oil in a mini-food processor and let it go until it forms a semi-smooth paste. There will still be tiny little pieces in there, but overall, it should resemble a paste.'),
('35758', '14', 'Save what you don''t use in a small glass jar. It should last in the fridge for 2 to 3 weeks. It''s a delicious addition to marinades, pasta sauces, stir fry sauces, slow-cooker recipes, gravy etc. We always had a jar of this stuff in our fridge growing up.'),
('35763', '1', 'Preheat the oven to 350 and position 2 racks in the lower and middle third of the oven. Line 24 muffin cups with paper or foil liners.'),
('35763', '2', 'Put the cocoa powder in a medium heatproof bowl.'),
('35763', '3', 'Add the boiling water and whisk until a smooth paste forms.'),
('35763', '4', 'Whisk in the buttermilk until combined. In a medium bowl, sift the flour with the baking soda, baking powder and salt. In a large bowl, using an electric mixer, beat 1 1/2 sticks of the butter with the granulated sugar until light and fluffy, about 3 minutes. Beat in the eggs and vanilla, then beat in the dry ingredients in 2 batches, alternating with the cocoa mixture. Carefully spoon the cupcake batter into the lined muffin cups, filling them about two-thirds full.'),
('35763', '5', 'Bake for 20 to 22 minutes, or until the cupcakes are springy.'),
('35763', '6', 'Let the cupcakes cool in the pans for 5 minutes, then transfer them to wire racks to cool completely.'),
('35763', '7', 'In a medium bowl, beat the peanut butter with the remaining 3 tablespoons of butter until creamy. Sift the confectioners'' sugar into the bowl and beat until light and fluffy, about 2 minutes. Spoon all but 3 tablespoons of the peanut butter filling into a pastry bag fitted with a 1/4-inch star tip. Holding a cupcake in your hand, plunge the tip into the top of the cake, pushing it about 3/4 inch deep. Gently squeeze the pastry bag to fill the cupcake, withdrawing it slowly as you squeeze. you will feel the cupcake expand slightly as you fill it. Scrape any filling from the top of the cupcake and repeat until all of the cupcakes are filled.'),
('35763', '8', 'In a small saucepan, bring the heavy cream to a simmer. Off the heat, add the semisweet chocolate to the cream and let stand for 5 minutes, then whisk the melted chocolate into the cream until smooth.'),
('35763', '9', 'Let the chocolate icing stand until slightly cooled and thickened, about 15 minutes. Dip the tops of the cupcakes into the icing, letting the excess drip back into the pan.'),
('35763', '10', 'Transfer the cupcakes to racks and let stand for 5 minutes. Dip the tops of the cupcakes again and transfer them to racks. Spoon the remaining 3 tablespoons of peanut butter filling into the pastry bag and pipe tiny rosettes on the tops of the cupcakes.'),
('35765', '1', 'Beat peanut butter and cream cheese in a bowl until creamy. Gradually add milk, beating until smooth. Fold in whipped topping. pour into pie crust. Freeze about 30 minutes.'),
('35765', '2', 'Garnish each serving with a dollop of whipped topping and sprinkle of cocoa and chopped peanuts, if desired. Store in refrigerator.'),
('35766', '1', 'Place butter, chocolate, and cocoa in a heatproof bowl. Set bowl over saucepan with two inches of simmering water. Gently stir butter and chocolate until melted and combined. Set aside until mixture is warm to touch.'),
('35766', '2', 'Whisk flour, baking soda, and baking powder in small bowl to combine.'),
('35766', '3', 'Whisk eggs in second bowl to combine. add sugar, vanilla, and salt until fully incorporated.'),
('35766', '4', 'Add cooled chocolate mixture and whisk until combined. Sift one-third of flour mixture over chocolate mixture and whisk until combined. whisk in sour cream until combined, then sift remaining flour mixture over and whisk until batter is homogeneous and thick.'),
('35766', '5', 'Fill cupcake line  full.'),
('35766', '6', 'Add a Reeses peanut butter cup to each well and finish pouring cupcake batter on top of it until the wells are two-thirds full.'),
('35766', '7', 'Bake until skewer inserted into center of cupcakes comes out clean, 18 to 20 minutes.'),
('35766', '8', 'Cool cupcakes to room temperature before icing, about 30 minutes.'),
('35774', '1', 'Preheat the oven to 35'),
('35774', '2', 'Generously oil a rimmed baking sheet. In a bowl, toss the crisped rice and peanuts with the corn syrup until evenly coated. add a pinch of salt.'),
('35774', '3', 'Spread the mixture as thinly as possible on the baking sheet and bake for 10 minutes, until crisp. While still warm, transfer the crunch to a plate. let cool. Break the crunch into large pieces.'),
('35774', '4', 'Scoop vanilla ice cream into sundae glasses and pour hot chocolate sauce on top. Top with the crunch and serve.'),
('35785', '1', 'Preheat oven to 35'),
('35785', '2', 'To prepare bread, combine first 5 ingredients in a large bowl. beat with a mixer at medium speed.'),
('35785', '3', 'Add granulated and brown sugars. beat until blended.'),
('35785', '4', 'Weigh or lightly spoon flour into dry measuring cups. level with a knife.'),
('35785', '5', 'Combine flour and next 5 ingredients (through allspice) in a small bowl.'),
('35785', '6', 'Add flour mixture to banana mixture. beat just until blended. Stir in nuts.'),
('35785', '7', 'Pour batter into a 9 x 5-inch loaf pan coated with cooking spray.'),
('35785', '8', 'Bake at 350 for 1 hour and 5 minutes or until a wooden pick inserted in center comes out clean.'),
('35785', '9', 'Remove from oven. cool 10 minutes in pan on a wire rack.'),
('35785', '10', 'Remove bread from pan. cool.'),
('35785', '11', 'To prepare glaze, combine powdered sugar, milk, and 1 tablespoon peanut butter in a small bowl, stirring with a whisk.'),
('35785', '12', 'Drizzle glaze over bread.'),
('35793', '1', 'Preheat the oven to 37'),
('35793', '2', 'In a medium glass bowl, combine the chocolate and butter and microwave at high power in 20-second intervals until the chocolate is melted. Stir well, then stir in the cookie crumbs. Press the cookie crumbs over the bottom of a 9-inch springform pan and 1 1/2 inches up the side.'),
('35793', '3', 'Bake the crust for 10 minutes, or until set. the crust will continue to firm up as it cools.'),
('35793', '4', 'In a large bowl, using a handheld electric mixer, beat the cream cheese with the peanut butter, sugar and vanilla extract until blended. In another large bowl, using the same beaters, whip the chilled cream until firm. Fold one-third of the whipped cream into the peanut butter mixture to loosen it, then fold in the remaining whipped cream and 1/2 cup of the chopped peanuts. Spoon the filling into the crust, smoothing the surface. Sprinkle lightly with salt and refrigerate until set, about 3 hours.'),
('35793', '5', 'In a medium glass bowl, combine the chocolate with the heavy cream and microwave at high power in 20-second intervals until the chocolate is melted and the cream is hot. Stir the chocolate topping until blended, then let cool to barely warm, stirring occasionally.'),
('35793', '6', 'Spread the chocolate topping over the peanut butter filling and refrigerate until just firm, about 15 minutes. Sprinkle the remaining 1/4 cup of chopped peanuts around the edge of the pie. Carefully run a thin knife around the pie crust to loosen it, then remove the springform ring. Using a sharp knife, cut the pie into wedges. Run the knife under hot water and dry it between each cut.'),
('35798', '1', 'Melt butter in a medium saucepan over medium heat.'),
('35798', '2', 'Remove pan from heat and stir in peanut butter, confectioners'' sugar, honey and vanilla. Stir in Rice Krispies and oats and allow mixture to cool.'),
('35798', '3', 'Stir in raisins and chocolate chips. Form mixture into 1-inch balls, then roll each ball in chopped peanuts, pressing to coat. Store in refrigerator.'),
('35800', '1', 'Heat oil in nonstick skillet over medium heat.'),
('35800', '2', 'Add shallot, ginger and garlic. saute until shallot is tender, about 3 minutes.'),
('35800', '3', 'Add curry powder and crushed red pepper. Stir until aromatic, about 15 seconds. Stir in 1 cup broth, peanut butter, lime juice, soy sauce, and brown sugar. whisk to blend. Simmer until mixture thickens, whisking constantly, about 3 minutes. Season with salt and pepper.'),
('35800', '4', 'Transfer to bowl and cool, whisking occasionally. Cover and refrigerate 2 hours. (Can be made 2 days ahead. Keep refrigerated.) Thin dip with more broth by tablespoonfuls if needed.'),
('35800', '5', 'Serve dip chilled or at room temperature.'),
('35805', '1', 'Preheat oven to 35'),
('35805', '2', 'Shape cookie dough into 24 (1-inch) balls, and place in cups of lightly greased miniature muffin pans.'),
('35805', '3', 'Bake 15 to 18 minutes or until edges are lightly browned.'),
('35805', '4', 'Remove from oven, and press 1 bite-size chocolate-covered caramel-peanut nougat bar into each cookie. Sprinkle cookies evenly with candy-coated chocolate pieces.'),
('35805', '5', 'Note: We tested with Snickers and M & M''s.'),
('35806', '1', 'In a large saucepan of boiling salted water, cook the rice noodles until they are al dente, 6 to 7 minutes.'),
('35806', '2', 'Drain and rinse them under running water until cold. Shake out the excess water and pat the noodles thoroughly dry with paper towels.'),
('35806', '3', 'In a blender or food processor, combine the coarsely chopped ginger with the Thai chiles, scallion pieces and smashed garlic and pulse until chopped.'),
('35806', '4', 'Add the fish sauce, lime juice and sugar and process until smooth.'),
('35806', '5', 'Transfer the rice noodles to a large serving bowl.'),
('35806', '6', 'Add the chicken, carrots, cucumber, radishes, cilantro and mint and toss.'),
('35806', '7', 'Add the dressing and toss until evenly coated. Sprinkle the rice noodles with peanuts and serve with lime wedges.'),
('35821', '1', 'To skin peanuts, blanch in a 3-quart saucepan of boiling salted water 1 minute, then drain well. Slip off and discard skins using your fingers and transfer peanuts to a bowl.'),
('35821', '2', 'Bring 5 cups water to a boil with bay leaf in same saucepan.'),
('35821', '3', 'Add peanuts and reduce heat to moderate, then simmer, covered, until peanuts are soft enough to crumble easily when pressed with tines of a fork, about 30 to 45 minutes. (Test 1 or 2 peanuts, leaving the rest intact.)'),
('35821', '4', 'Drain well.'),
('35821', '5', 'When peanuts are almost finished cooking, stir together tomatoes, cilantro, chiles, lemon juice, and sea salt in a bowl.'),
('35821', '6', 'Add drained peanuts and stir to combine.'),
('35826', '1', 'Drop dough by tablespoonfuls onto cookie sheets sprayed with cooking spray.'),
('35826', '2', 'Bake at 350 degrees for 10 to 12 minutes or until lightly browned. This recipe should yield 40 to 48 cookies.As for the results, the cookies turned out pretty well. Nothing spectacular or unique, but very good and very simple.cookies1 Comment'),
('35827', '1', 'Heat olive oil in an 8-inch stainless skillet over medium heat until shimmering.'),
('35827', '2', 'Add the annatto seeds. Stir occasionally until most of the seeds start to sizzle steadily. Immediately turn off the heat.'),
('35827', '3', 'Let skillet sit off heat until seeds stop sizzling. Strain seeds and pour infused oil into a large dutch oven.'),
