INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('3017', '4', 'Let the fish cook until about 3/4 the way done, then put a little butter on top of fish and add blackening seasoning. When fish is done, put on a plate and move to the side and keep it warm.Stir in lemon juice into pan drippings. If you need a little more butter and garlic, put some in pan. Then add green onions and mushrooms.'),
('3017', '5', 'Let cook until green onions and mushrooms soak up lemon juice or until done.Taste mushroom and if it makes you make a sour face, then you know it''s done. If not, add a little more lemon juice.Spoon over fish and enjoy.'),
('3018', '1', 'Combine sour cream and 2 tablespoons lime juice. Cover and chill.'),
('3018', '2', 'Place a large nonstick skillet over medium heat.'),
('3018', '3', 'Add corn. saut 3 to 4 minutes or until corn is lightly browned.'),
('3018', '4', 'Combine corn, tomato, green onions, 1 tablespoon lime juice, 1 tablespoon oil, cilantro, jalapeo pepper, 1/4 teaspoon salt, and 1/8 teaspoon black pepper in a bowl. Toss gently. Cover and chill.'),
('3018', '5', 'Add 1 tablespoon oil to pan.'),
('3018', '6', 'Place over medium heat.'),
('3018', '7', 'Add sliced onion. saut 3 to 4 minutes or until onion is crisp-tender.'),
('3018', '8', 'Add bell pepper. cook 2 to 3 minutes or until pepper softens. Stir in 1/4 teaspoon salt. transfer to a bowl.'),
('3018', '9', 'Heat tostada shells according to package directions. keep warm.'),
('3018', '10', 'Prepare grill.'),
('3018', '11', 'Combine fish, 1 1/2 teaspoons oil, 1 1/2 teaspoons lime juice, chili powder, cumin, 1/4 teaspoon salt, and 1/8 teaspoon black pepper in a large zip-top plastic bag. Toss gently.'),
('3018', '12', 'Place fish on grill rack coated with cooking spray. grill 6 to 7 minutes on each side or until fish flakes easily when tested with a fork. Flake fish.'),
('3018', '13', 'Top each tostado shell with 1/4 cup shredded lettuce. Spoon onion and bell pepper mixture evenly over lettuce. divide fish evenly over onion and bell pepper mixture. Top fish with corn salsa. drizzle with the sour cream mixture.'),
('3020', '1', 'Preheat greased grill to medium-high heat.'),
('3020', '2', 'Place cilantro, dressing, lime juice and mustard in blender container. cover.  Blend on medium speed until smooth.'),
('3020', '3', 'Cut one 12-inch square from each banana leaf.'),
('3020', '4', 'Cut reserved trimmings into thin strips. set aside for later use.'),
('3020', '5', 'Place one fillet in center of each banana leaf square.'),
('3020', '6', 'Spread 2 Tbsp. of the cilantro mixture over each fillet. top with one quarter each of the yuca and tomatoes.  Fold in sides of each banana leaf to form packet. tie with banana leaf strips to secure.'),
('3020', '7', 'Place packets on grate of grill. cover grill with lid.  Grill 15 to 20 min. or until fish flakes easily with fork.'),
('3020', '8', 'Place packets on individual serving plates to serve.'),
('3021', '1', 'In a large pot, heat the oil.'),
('3021', '2', 'Add the onion, celery and carrot and cook over moderately high heat until softened, 5 minutes.'),
('3021', '3', 'Add the garlic, orange zest, thyme sprigs, fennel and coriander seeds and saffron and cook over moderate heat, stirring, until fragrant, 5 minutes. Stir in the tomato paste and cook over high heat until glossy, 1 minute.'),
('3021', '4', 'Add the tomatoes, clam juice, wine and port and bring to a boil.'),
('3021', '5', 'Add the grouper and shrimp, cover partially and simmer for 45 minutes. Discard the zest and thyme sprigs.'),
('3021', '6', 'Working in batches, transfer the soup to a food processor and pulse until coarsely chopped. Rinse out the pot. Set a food mill fitted with a coarse blade over the pot and run the soup through the food mill. Bring the soup to a simmer. Stir in the Pernod and season with salt and pepper. Ladle the soup into bowls and serve.'),
('3022', '1', 'Blend steak sauce, oranges and peppers in blender until well blended.  Reserve 1/4 cup. pour remaining over fish in shallow glass dish.  Turn fish over to coat both sides.  Refrigerate 20 min. to marinate.'),
('3022', '2', 'Heat grill to medium-high heat.'),
('3022', '3', 'Remove fish from marinade. discard marinade.  Grill fish 6 min. or until fish flakes easily with fork, turning after 4 min.'),
('3022', '4', 'Remove fish from grill. let stand 5 min.'),
('3022', '5', 'Meanwhile, mix reserved steak sauce mixture, onions, orange juice and cilantro.  Spoon onto half of each tortilla. top with fish.  Fold in half.'),
('3023', '1', 'Mix dressing and crushed red pepper.'),
('3023', '2', 'Pour over fish and peppers in shallow glass dish. turn fish and peppers over to coat both sides of each with dressing mixture.  Refrigerate 15 min. to marinate.'),
('3023', '3', 'Heat grill to medium-high heat.'),
('3023', '4', 'Remove fish and peppers from marinade. discard marinade.'),
('3023', '5', 'Grill fish and peppers on covered grill 4 min.. turn fish over. Grill, covered, 2 min. or until fish flakes easily with fork.'),
('3023', '6', 'Place fish and peppers on serving plate. Sprinkle with cheese and cilantro. let stand 3 min.'),
('3024', '1', 'Preheat oven to 40'),
('3024', '2', 'Combine first 8 ingredients in an 11 x 7-inch baking dish.'),
('3024', '3', 'Bake at 400 for 20 minutes. Arrange fish on top of tomato mixture.'),
('3024', '4', 'Drizzle with oil. sprinkle with salt and pepper. Cover with foil. bake 20 minutes or until fish flakes easily when tested with a fork.'),
('3026', '1', 'Heat the oil in a medium enameled cast-iron casserole.'),
('3026', '2', 'Add the shallots, garlic, onion, bell pepper, ginger and lemongrass and cook over moderate heat until the vegetables are softened, about 7 minutes.'),
('3026', '3', 'Add the tomatoes, season with salt and pepper and cook for 3 minutes. Season the shrimp with salt and pepper and add them to the casserole along with the coconut milk and cilantro leaves. Cover and cook for 2 minutes. Season the grouper with salt and pepper. add to the casserole, cover and cook for 3 minutes. Discard the lemongrass.'),
('3026', '4', 'Add the lime juice and season the stew with salt and pepper.'),
('3026', '5', 'Garnish with the chopped cilantro and serve.'),
('3027', '1', 'Preheat oven to 45'),
('3027', '2', 'Combine first 6 ingredients and crushed red pepper, if desired. set aside.'),
('3027', '3', 'Place snapper on a broiler pan lined with aluminum foil. coat foil with cooking spray. Sprinkle snapper with paprika. coat with cooking spray.'),
('3027', '4', 'Bake at 450 for 10 minutes.'),
('3027', '5', 'Top snapper with tomato mixture. bake 5 minutes or until fish flakes easily when tested with a fork. Sprinkle with parsley, and serve with lemon wedges.'),
('3028', '1', 'In a large pot, heat the oil.'),
('3028', '2', 'Add the onion, celery and carrot and cook over moderately high heat until softened, 5 minutes.'),
('3028', '3', 'Add the garlic, orange zest, thyme sprigs, fennel and coriander seeds and saffron and cook over moderate heat, stirring, until fragrant, 5 minutes. Stir in the tomato paste and cook over high heat until glossy, 1 minute.'),
('3028', '4', 'Add the tomatoes, clam juice, wine and port and bring to a boil.'),
('3028', '5', 'Add the grouper and shrimp, cover partially and simmer for 45 minutes. Discard the zest and thyme sprigs.'),
('3028', '6', 'Working in batches, transfer the soup to a food processor and pulse until coarsely chopped. Rinse out the pot. Set a food mill fitted with a coarse blade over the pot and run the soup through the food mill. Bring the soup to a simmer. Stir in the Pernod and season with salt and pepper. Ladle the soup into bowls and serve.'),
('3029', '1', 'Heat oil in a large Dutch oven over medium-high heat.'),
('3029', '2', 'Add leek, fennel, and garlic to pan. saut 4 minutes or until tender. Stir in tomatoes, broth, wine, and 1 tablespoon parsley. bring to a boil.'),
('3029', '3', 'Add fish and shrimp. cook 3 minutes or until done. Sprinkle with remaining 2 tablespoons parsley, and garnish with parsley sprigs, if desired.'),
('3029', '4', 'Choice Ingredient'),
('3029', '5', 'Fennel, an aromatic plant native to the Mediterranean region, has licorice-like flavor and is delicious raw or cooked. Chopped and sauted, the fennel bulb adds body and rich flavor to soups. Look for small, heavy, white bulbs that are firm and free of cracks, browning, or moist areas. Store fennel bulbs in a perforated plastic bag in the refrigerator for up to 5 days.'),
('3030', '1', 'Preheat oven to 40'),
('3030', '2', 'Bring first 3 ingredients to a simmer in a small saucepan (do not boil). Keep warm over low heat.'),
('3030', '3', 'Peel the shrimp, leaving tails intact.'),
('3030', '4', 'Combine shrimp, grouper, and squid in a bowl. sprinkle with salt, let stand 5 minutes.'),
('3030', '5', 'Heat 1 tablespoon oil in a 13-inch paella pan or large skillet over medium-high heat.'),
('3030', '6', 'Add fish mixture, and saute for 1 minute (the mixture will not be completely done).'),
('3030', '7', 'Remove fish mixture and any liquid from pan, and place in a bowl.'),
('3030', '8', 'Heat 2 tablespoons oil in pan over medium-high heat.'),
('3030', '9', 'Add bell peppers, onion, garlic, and paprika. saut 3 minutes. Stir in tomato. cook 2 minutes. Stir in rice, and coat well.'),
('3030', '10', 'Add clam juice mixture. bring to a boil, and cook 3 minutes.'),
('3030', '11', 'Add reserved fish. cook 2 minutes.'),
('3030', '12', 'Add mussels to pan, nestling them into rice mixture.'),
('3030', '13', 'Bake at 400 for 15 minutes or until shells open. discard any unopened shells.'),
('3030', '14', 'Remove from oven. cover and let stand 10 minutes.'),
('3031', '1', 'Heat oil in a large Dutch oven over medium heat.'),
('3031', '2', 'Add onion and bell pepper. cook 5 minutes.'),
('3031', '3', 'Add wine and next 6 ingredients. bring to a boil. Reduce heat. simmer 5 minutes, stirring occasionally.'),
('3031', '4', 'Nestle fish into tomato mixture. top with mussels. Cover and cook 8 minutes. gently shake pan twice to stir mussels (do not lift lid). Discard bay leaf and any unopened shells. Sprinkle with parsley.'),
('3033', '1', 'Heat oil in a large Dutch oven over medium heat.'),
('3033', '2', 'Add onion and bell pepper. cook 5 minutes.'),
('3033', '3', 'Add wine and next 6 ingredients. bring to a boil. Reduce heat. simmer 5 minutes, stirring occasionally.'),
('3033', '4', 'Nestle fish into tomato mixture. top with mussels. Cover and cook 8 minutes. gently shake pan twice to stir mussels (do not lift lid). Discard bay leaf and any unopened shells. Sprinkle with parsley.'),
('3034', '1', 'Sprinkle the grouper steaks on both sides with 1/4 tsp of the salt and 1/8 tsp of the pepper. In a large, nonstick frying pan, heat 1 1/2 tsp of the olive oil over medium high heat.'),
('3034', '2', 'Add the fish to the pan and sear on both sides until lightly browned, about 2 minutes per side.'),
('3034', '3', 'Transfer to a plate and keep warm.Reduce the heat to medium and add the remaining 1 T. olive oil to the pan.'),
('3034', '4', 'Add the onion and saute until soft and lightly golden, about 6 minutes.'),
('3034', '5', 'Add garlic and saute 1 minute more.'),
('3034', '6', 'Add the tomatoes, olives, capers, and jalapeno and simmer for 10 minutes to allow the flavors to blend. Stir in the remaining 1/4 teaspoons salt and 1/8 teaspoons pepper.Return the fish to the pan, cover, and simmer until the fish is opaque throughout when tested with the tip of a knife, 6-8 minutes.'),
('3034', '7', 'Transfer the grouper steaks to warmed individual plates/ Stir the lime juice into the vegetables and pan juices and spoon some sauce over each steak.'),
('3034', '8', 'Serve immediately.'),
('3035', '1', 'In a large saucepan, combine the water and clam broth with the shrimp shells, smashed garlic, sherry, crushed red pepper, bay leaves and one third of the onion. Bring to a boil and simmer, covered, over low heat for 20 minutes. Strain the shrimp stock into a heatproof bowl and discard the solids.'),
('3035', '2', 'In a soup pot, heat the oil.'),
('3035', '3', 'Add the fennel, celery, bell pepper, minced garlic and the remaining onion. Cover and cook over moderate heat, stirring once or twice, until the vegetables are barely softened, 3 minutes. Uncover and cook until tender, 3 minutes longer.'),
('3035', '4', 'Add the tomatoes with their juices and the shrimp stock. bring to a simmer.'),
('3035', '5', 'Add the potato, season with salt and pepper and simmer until just tender, 15 minutes.'),
('3035', '6', 'Add the shrimp, grouper, oysters and Worcestershire sauce. simmer until cooked through, 3 minutes. Off the heat, stir in the buttermilk and parsley.'),
('3035', '7', 'Serve in deep bowls.'),
('3036', '1', 'In a medium saucepan, bring 5 cups of the water to a boil and add the clams and a pinch of salt. Reduce the heat and simmer, partly covered, for 30 minutes.'),
('3036', '2', 'Remove from the heat and set aside, covered, leaving the clams in the water. (Discard any that do not open.)'),
('3036', '3', 'Meanwhile, put the mussels in a small saut pan, add 1/3 cup of the water, and bring to a boil. Reduce the heat and simmer, uncovered, until all of the mussels have opened, 3 to 5 minutes.'),
('3036', '4', 'Remove from the heat and set aside, covered. Do not drain. (Discard any that do not open.)'),
('3036', '5', 'Season the fish generously with salt and pepper. In a 16- to 18-inch paella pan, heat the oil over medium heat. When the oil begins to shimmer, dredge the fish, piece by piece, in flour and then cook in batches, turning just once, until golden on the outside and just cooked through in the middle.'),
('3036', '6', 'Transfer to a platter.'),
('3036', '7', 'Remove any solids left in the oil with a skimmer or slotted spoon and then prepare the sofrito in the same pan.'),
('3036', '8', 'Add the bell pepper, and cook, over medium heat, stirring frequently, until it begins to brown and become fragrant, about 3 minutes.'),
('3036', '9', 'Add the cuttlefish and cook until its moisture has been expelled, about another 5 minutes, stirring constantly and scraping anything that sticks to the pan.'),
('3036', '10', 'Add the shrimp and cook until pink, about 2 minutes on each side. Lower the heat to medium-low, add the garlic, tomatoes, and 2 pinches of salt, and cook, stirring from time to time, until the tomato has darkened to a deeper shade of red and the sofrito is pasty, 10 to 15 minutes.'),
('3036', '11', 'Meanwhile, strain the broth from the clams and reserve it. Discard one shell (the empty one) from each clam, and set aside the rest.'),
('3036', '12', 'When the sofrito is ready, sprinkle in the pimentn and saffron, letting the flavors meld for a few seconds while stirring constantly.'),
('3036', '13', 'Add 4 cups of the reserved clam broth plus the remaining 3 cups of water, increase the heat to high, and bring to a boil. Taste for salt and adjust the seasoning as needed.'),
('3036', '14', 'Sprinkle in the rice. With a wooden spoon, probe the pan to make sure the rice is evenly distributed. Do not stir again. Lay the pieces of fish on top and then the shrimp. Cook, uncovered, for 10 minutes over high heat.'),
('3036', '15', 'Reduce the heat to low and cook for an additional 8 minutes, or until the liquid is absorbed and the rice is al punto, with just a bite to it.'),
('3036', '16', 'Remove the paella from the heat, cover with paper towels, and let rest for 5 minutes before serving.'),
('3036', '17', 'var article'),
('3036', '18', 'Type_27_data = {}.'),
('3036', '19', 'article'),
('3036', '20', 'Type_27_data.init_step_by_step_images = 0.'),
('3037', '1', 'In a heavy skillet, bring cream to a simmer. Stir cornstarch and wine together, then whisk into the cream. Stir in creole mustard and Gouda cheese, adding a little at a time to allow the cheese to melt. Continue stirring until smooth.In another skillet, saute okra, sausage, crawfish, and tomatoes. Then stir into the cream mixture.Coat fish filets with 1/4 cup blackening seasoning. Blacken the grouper filets in an iron skillet.Stir the additional 1 tbsp blackening seasoning into the cream sauce.Plate with cornbread, soak with cream sauce, then top with the grouper filet.'),
('3037', '2', 'Add more sauce over the fish.'),
('3038', '1', 'In a large, deep skillet, bring the water to a simmer with 1 tablespoon of salt.'),
('3038', '2', 'Add the grouper fillets and poach over low heat for 6 minutes, until partially cooked. Using a slotted spoon, transfer the fish to a plate.'),
('3038', '3', 'Pour 4 cups of the poaching liquid into a medium bowl. discard the rest.'),
('3038', '4', 'Pour 2 cups of the reserved poaching liquid into a bowl and add the tamarind. use a potato masher to break up the tamarind as much as you can. Strain the tamarind juice into a small bowl, pressing on the solids. discard the solids.'),
('3038', '5', 'In a small skillet, combine the soaked red chiles, garlic, curry powder, coriander seeds, cumin seeds and belacan and toast over moderate heat, stirring, until fragrant, 1 to 2 minutes.'),
('3038', '6', 'Transfer the seasonings to a spice grinder and let cool. Grind the seasonings to a dry paste.'),
('3038', '7', 'Wipe out the deep skillet and add the vegetable oil.'),
('3038', '8', 'Add the mustard seeds and cook over moderately low heat until they begin to pop, about 30 seconds.'),
('3038', '9', 'Add the spice paste and cook, stirring, until the color deepens slightly, about 3 minutes.'),
('3038', '10', 'Add the onion, curry leaves and lemongrass and cook, stirring occasionally, until the onion is softened, about 8 minutes.'),
('3038', '11', 'Add the tamarind juice to the skillet and bring to a boil.'),
('3038', '12', 'Add the coconut milk, okra, eggplant, tomatoes, Thai chiles, sugar and the remaining 2 cups of poaching liquid and bring to a simmer. Season with salt and cook the curry over low heat until the vegetables are tender and the liquid is thickened slightly, about 40 minutes.'),
('3038', '13', 'Cut the fish into 2-inch pieces and nestle them in the sauce. Simmer over moderately high heat until the fish is just cooked through, about 5 minutes longer.'),
('3039', '1', 'Stir together the mayonnaise, green onions, jalapenos, hot sauce, lemon juice, salt and red pepper in a medium bowl. Cover and chill until ready to serve.Stir together hushpuppy mix and milk in a medium bowl.'),
('3039', '2', 'Pour oil into a large deep skillet to a depth of 1/2".'),
('3039', '3', 'Heat oil to 350*F. Dredge fish in flour then in hushpuppy mix.'),
('3039', '4', 'Place fish in oil and fry in batches 3 to 4 minutes on each side or until golden.'),
('3039', '5', 'Serve with sauce. Enjoy!'),
('3040', '1', 'Clean the grouper and cubed.Peel the mangoes and cubed.Wrap each cube of grouper with a slice of ham and insert them in a skewer alternating them with the mango pieces.In a saucepan on low heat, melt the Camembert with the cream and mustard. Sprinkle the skewers with pepper and saut in olive oil until the grouper is cooked.'),
('3040', '2', 'Pour some Camembert and mustard sauce on each plate, set skewers on top and decorate with raisin.'),
('3041', '1', 'process garlic and onion to a smooth paste in a spice blender, adding a little oil if needed to keep the mixture turning,set aside.mix curry powder with 4 tbsp water to form a paste,set aside.soak tamarind pulp in 500ml (2 cups) of water for 5 minutes, then squeeze and strain to obtain juiceset aside.heat oil in a wide saucepan,add mustard seeds, fenugreek, cumin and curry leaves. fry until mustard seeds start to pop (around 30 seconds)add the garlic onion paste, stir fry over low heat until mixture smells fragrant and starts to brown (about 5 minutes).add curry paste and cook over low heat until dry and oil starts to separate (8 to 10 minutes).add tamarind juice and bring to a boil.add fish and okras, tomatoes, chillies, coconut milk, salt. simmer gently about 10 minutes (or until fish and okras are cooked through).'),
('3042', '1', 'In a pan, simmer sun-dried tomatoes in 1 1/2 cups water until very soft. discard water.'),
('3042', '2', 'In a large pot, saute onion and green pepper in oil until softened.'),
('3042', '3', 'In a food processor or blender, combine sun-dried tomatoes and 1 bottle clam juice until smooth. add to pot. Stir in remaining clam juice, diced tomatoes, wine, garlic, herbs, bay leaves and olives. Simmer 20 minutes.'),
('3042', '4', 'Add beans, fish, fennel seeds, salt and pepper. Simmer until fish is done, about 10 minutes.'),
('3042', '5', 'Remove bay leaves. Ladle into bowls. sprinkle with cheese.'),
('3043', '1', 'Rub both sides of fillets with garlic.Sprinkle with salt.Arrange fillets in a single layer in a large shallow dish.'),
('3043', '2', 'Add lime rind and juice, turning to coat.Cover and marinate in refrigerator 1 hour.'),
('3043', '3', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('3043', '4', 'Add onion and saute 5 minutes or until golden.Stir in olives and next 6 ingredients (olives through tomatoes).Reduce heat and simmer, uncovered, 10 minutes, stirring occasionally.Stir in capers.'),
('3043', '5', 'Remove from pan.Melt butter in pan over medium-high heat.'),
('3043', '6', 'Add fillets, cooking 3 minutes on each side or until fish flakes easily with fork.'),
('3043', '7', 'Pour tomato mixture over fillets and cook 5 minutes or until thoroughly heated.Sprinkle with cilantro.Serving size: 1 fillet and 1/2 cup tomato sauce.'),
('3044', '1', 'Preheat oven to 35'),
('3044', '2', 'Place the fish in an oiled casserole dish.Top the fillets with the onion rounds and sprinkle them with the dill, pepper, parsley, lemon juice, chopped tomato, and feta cheese.'),
('3044', '3', 'Bake for 20 minutes or until the fish flakes easily.Baking time will depend on the thickness of the fish fillets.'),
('3046', '1', 'Preheat oven to 42'),
('3046', '2', 'Place fish in an 11 x 7-inch baking dish coated with cooking spray.'),
('3046', '3', 'Combine lime juice, mayonnaise, onion powder, and pepper in a small bowl, and spread over fish. Sprinkle with breadcrumbs. drizzle with butter.'),
('3046', '4', 'Bake at 425 for 20 minutes or until fish flakes easily when tested with a fork. Sprinkle with parsley.'),
('3048', '1', 'Heat oil in a large saucepan over medium heat.'),
('3048', '2', 'Add onion and next 3 ingredients (through garlic). cook 5 minutes, stirring frequently.'),
('3048', '3', 'Add tomato, fennel seeds, thyme, tarragon, and saffron. cook 1 minute. Stir in wine and liqueur. bring to a boil. Reduce heat, and simmer 5 minutes.'),
('3048', '4', 'Add juices and pepper. bring to a simmer. Cook 10 minutes.'),
('3048', '5', 'Add clams and grouper. cook over medium heat 3 minutes or until clams begin to open.'),
('3048', '6', 'Add mussels, shrimp, and lobster. cook 4 minutes or until mussels open. Discard any unopened clams or mussels.'),
('3048', '7', 'Garnish with parsley.'),
('3048', '8', 'Wine note: In the south of France, where it originated, bouillabaisse is enjoyed with a wine that''s considered obligatory and the perfect match: ros. Ros will work throughout this entire menu, from the crab cocktail to the crepes. A still ros would be fine, but why not heighten the pleasure (and romance) and serve a California sparkling ros? Gloria Ferrer''s nonvintage Brut Ros is smashing at $ -Karen MacNeil'),
('3049', '1', 'Cut the fish into 1-inch wide strips and place in a 2-qt. microwave-safe dish. Scatter the sugar snap peas, mushrooms, ginger, carrots and scallions evenly over the fish. It''s going to look really pretty so take a moment to admire it.'),
('3049', '2', 'Combine the hoisin sauce, soy sauce and vinegar in a small bowl and then slowly drizzle over the fish and vegetables. Cover the dish with plastic wrap, folding back one corner to allow the steam to escape.'),
('3049', '3', 'Place the dish in the microwave and cook on high power until the fish is cooked through and the vegetables are crisp tender, 6 minutes. Stop every 2 minutes to gently stir and reposition the fish so that the outside pieces are moved to the inside. ***I didn''t really believe that the fish and veggies would be cooked in 6 minutes but they WERE and they were perfect. I set the MWave for 2 minutes and just gently rearranged the fish each time (3 times).'),
('3049', '4', 'Serve the fish and veggies with the cooked rice.'),
('3050', '1', 'Heat oven to 400F.'),
('3050', '2', 'Stir saffron into chicken stock. set aside.'),
('3050', '3', 'Heat oil in paella pan or very large ovenproof skillet on medium-high heat.'),
('3050', '4', 'Add chicken and pork. cook until chicken is lightly browned, turning meat occasionally.'),
('3050', '5', 'Add garlic, onion and sausage. cook and stir 5 min. or until onions are crisp-tender.'),
('3050', '6', 'Add rice. cook and stir 5 min. Carefully spoon off any excess oil.  Stir in bay leaves, wine, tomatoes, and pepper. Bring to boil.'),
('3050', '7', 'Add half of the chicken stock.  Bring to boil.'),
('3050', '8', 'Add shrimp, squid, monkfish, clams and mussels. mix well.'),
('3050', '9', 'Place paella carefully in oven.'),
('3050', '10', 'Add enough remaining chicken stock to cover ingredients in pan.  Top with the peas and bell peppers. cover.'),
('3050', '11', 'Bake 35 min. or until heated through and clams open.  Top with the lemon wedges.'),
('3052', '1', 'In a food processor or blender pure the coriander, the parsley, the garlic, the lemon juice, the paprika, the cumin, the cayenne, 3 tablespoons of the oil, and salt and pepper to taste.In a skillet heat 1 inch of the additional oil to 375F on a deep-fat thermometer, dredge the fish in the flour, shaking off the excess, and in the oil fry it, turning it once, for 1-1/2 to 2 minutes on each side, or until it is cooked through.'),
('3052', '2', 'Transfer the fish to paper towels to drain, divide it between 2 plates, and drizzle the sauce over it.'),
('3053', '1', 'Preheat oven to 375F.'),
('3053', '2', 'Place the fish pieces in a metal baking pan.Season lightly with salt.'),
('3053', '3', 'Combine all the remaining ingredients, except the wine and olive oil, season, and distribute on top of fish.'),
('3053', '4', 'Pour the wine and olive oil over and bake for about 35-40 minutes, or until the fish flakes.'),
('3055', '1', 'Heat oil in a large saucepan over medium heat.'),
('3055', '2', 'Add onion and next 3 ingredients (through garlic). cook 5 minutes, stirring frequently.'),
('3055', '3', 'Add tomato, fennel seeds, thyme, tarragon, and saffron. cook 1 minute. Stir in wine and liqueur. bring to a boil. Reduce heat, and simmer 5 minutes.'),
('3055', '4', 'Add juices and pepper. bring to a simmer. Cook 10 minutes.'),
('3055', '5', 'Add clams and grouper. cook over medium heat 3 minutes or until clams begin to open.'),
('3055', '6', 'Add mussels, shrimp, and lobster. cook 4 minutes or until mussels open. Discard any unopened clams or mussels.'),
('3055', '7', 'Garnish with parsley.'),
('3060', '1', 'Place fillets in a greased 15-in. x 10-in. x 1-in. baking pan. Sprinkle with dill. Arrange lemon slices over fillets. Cover and bake at 350 degrees F for 30 minutes or until fish flakes easily with a fork. In a small bowl, combine the tartar sauce ingredients.'),
('3060', '2', 'Serve with fish.'),
('3064', '1', 'Turn the grill on high heat.   Meanwhile, lay the fish on a large tray or cutting board, and coat both sides of the fish with oil. Sprinkle generous amounts of salt and pepper on both sides. Stuff the cavity of the fish with the lemon, herbs, and green onion.'),
('3064', '2', 'Take the fish off the tray and place directly on grill and cook (roughly 10 minutes per inch), making sure to flip half way through the process. When done, transfer to a clean tray or board and remove the head.  Move the body of the fish to serving platter.'),
('3064', '3', 'Remove the layer of skin on top. Using a serving spoon or metal spatula, find the top layer of bones, and serve the meat that lays above that. At this point, you should be able to remove the bones from the whole fish, leaving just the remaining meat on the platter.'),
('3068', '1', 'Peel and boil the potatoes.'),
('3068', '2', 'Remove the skin from the fish (if necessary) and cut into 3cm chunks. In a large saucepan, mix 350ml of the milk, the cream, wine, bay leaf and peppercorns and bring to the boil. Simmer gently for 8-10 minutes.'),
('3068', '3', 'Remove from heat and transfer the fish chunks onto a plate to drain. Strain and reserve the liquid, and scatter the cooked fish as well as the prawns over the base of a large, shallow oven-proof dish.In a clean saucepan, melt 50g of the butter, add the flour and mix well. Cook for 1 minute, then remove from the heat. Gradually add the cooking liquid from the fish, whisking it in a little at a time and then return to the heat. Bring gently to the boil and allow to simmer gently for 10 minutes.'),
('3068', '4', 'Remove from the heat, season with salt and pepper and stir in the chopped dill and chives.'),
('3068', '5', 'Pour over the fish in the shallow dish. Pre-heat the oven to 200C.Mash the potatoes together with the remaining butter and milk to form a smooth, creamy mash.'),
('3068', '6', 'Spread over the fish in the oven-proof dish so that it covers the fish completely  you can score patterns in the mash with a fork if you feel so inclined. Sprinkle the grated cheese over the mash.'),
('3068', '7', 'Bake uncovered at 200C for about 35 minutes until nicely browned and bubbling.'),
('3068', '8', 'Serve with steamed green beans or minted peas (or, in my case) lemon thyme peas and a full-bodied white wine.More deliciousness for you!Moiras New England clam chowder'),
('3068', '9', 'Pan-fried salmon on kale, sweet potato and pomegranate'),
('3068', '10', 'Wholly mackerel!Whole baked tilapia with flat-leaf parsley and garlic'),
('3078', '1', 'Peel and roughly chop the potatoes, put them into a pan of salted water and bring to the boil. Cook until tender and then mash into a bowl.'),
('3078', '2', 'Put the fish, with the smoked fish underneath, into a large skillet with the milk, parsley stalks and a good grinding of pepper. Bring the pan to a simmer and cook for about 58 minutes, turning if necessary.'),
('3078', '3', 'Take the cooked fish out of the pan, flake it into a bowl and add the chopped parsley. Finely chop the hard-boiled eggs and add them with the mustard, lemon zest and juice.'),
('3078', '4', 'Turn the flaked fish mixture into the mashed potato and mix very thoroughly. If youre making these ahead, wait till contents of both bowls are cold before combining. Check the seasoning, adding salt and pepper as needed.'),
('3078', '5', 'Crush the Ritz crackers which is very satisfying: put them in a freezer bag, bashing and rolling them with a rolling pin until they are crumbs. Line the bottom of a tray or shallow roasting pan with these crumbs.'),
('3078', '6', 'Shape the fish and potato mixture into 10 fishcakes, each weighing approximately 10oz (4 inches across by an inch thick). As you make each fat patty, press them into the Ritz cracker crumbs on both sides to get a good coating and leave them in the tray or pan. I think theyre better not refrigerated but if you are making them a lot in advance, it would, of course, be better to sit them in the fridge.'),
('3078', '7', 'When you are ready to cook them, preheat the oven to 400F.'),
('3078', '8', 'Put the fishcakes on to a baking sheet, shaking off the excess Ritz crumbs but leaving a visible coating around each fishcake. Cook them for about 20 minutes or until they are heated through. If they are in the oven for too much longer they will crack a little, but no other harm comes to them, so dont worry too much if people take a long time to make it to the table to eat.'),
('3078', '9', 'Makes 10 fishcakes: these are so large no one is likely to need seconds, but its good to know you can provide more if required.'),
('3078', '10', 'var article'),
('3078', '11', 'Type_27_data = {}.'),
('3078', '12', 'article'),
('3078', '13', 'Type_27_data.init_step_by_step_images = 0.'),
('3080', '1', 'Preheat oven to 350 degrees F (175 degrees C). Lightly butter a medium or large baking dish.'),
('3080', '2', 'Rinse and dry fillets. Season with 1 teaspoon salt and 1/8 teaspoon pepper.'),
('3080', '3', 'In a skillet or frying pan, melt butter over medium heat.'),
('3080', '4', 'Saute onion in butter until golden. Stir in flour until completely incorporated. Stir in mustard, 1/2 teaspoon salt, light and heavy creams. Cook until thickened, stirring constantly.'),
('3080', '5', 'Remove from heat and stir in cheeses.'),
('3080', '6', 'Pour sauce over fish and sprinkle with paprika.'),
('3080', '7', 'Bake in preheated oven for 30 minutes, until brown and bubbly.'),
('3081', '1', 'Preheat oven to 375F.'),
('3081', '2', 'Cook onions in butter in a 12-inch heavy skillet over moderate heat, stirring occasionally, until softened and just beginning to brown, 7 to 8 minutes.'),
('3081', '3', 'Remove skillet from heat and stir in haddock, 1 tablespoon parsley, and salt and pepper to taste.'),
('3081', '4', 'Halve or quarter celery root to fit slicer. Thinly slice potatoes and celery root (about 1/8-inch thick) with slicer. Layer one third of potatoes and celery root in buttered baking dish.'),
('3081', '5', 'Spread half of haddock mixture on top, then repeat layering with half of remaining vegetables, all of remaining haddock mixture, and then remaining vegetables. Stir together cream, milk, salt, and pepper and pour on top of gratin, then cover dish tightly with buttered foil.'),
('3081', '6', 'Bake gratin in middle of oven until vegetables are just tender, about 1 hour. Uncover and bake, basting 2 or 3 times with pan juices, until top is golden, about 30 minutes more.'),
('3081', '7', 'Let stand 10 minutes, then sprinkle with remaining tablespoon parsley.'),
('3081', '8', '* Available at Asian cookware shops.'),
('3083', '1', 'Place the haddock in a deep baking tray with the milk and bay leaves, then cover the tray with foil and cook for 15 minutes. Meanwhile, cook the potatoes in salted boiling water for about 15 minutes, until soft.'),
('3083', '2', 'Drain them in a colander to get rid of any excess water, then return to the pan on a low heat and mash.Flake the cooked fish into a large bowl, picking out any bones and removing the skin.'),
('3083', '3', 'Add the mashed potato, parsley, mint, lemon and lime zest, fennels seeds, eggs and chilli and season with salt and freshly ground black pepper.'),
('3083', '4', 'Mix well, taste and add more salt if necessary.Flour your work surface, then take 1 tablespoon of the mix in your hands with a little flour and pat it into a flattened circle, rolling it in the flour. Rough and ready is good, so dont worry about having them all exactly the same!'),
('3083', '5', 'Pour enough oil into a large heavy-bottomed saucepan to fill the pan about a third of the way up.'),
('3083', '6', 'Heat over a medium heat until a deep-frying thermometer inserted into the oil reaches 185C/360F. (If you dont have a thermometer, heat the oil until a cube of bread will brown in about 3 minutes.) Deep-fry the fishcakes for about 5 minutes until brown and crispy.'),
('3083', '7', 'Drain on kitchen paper, sprinkle with sea salt and serve on a large plate with lots of lemon halves.Tip'),
('3084', '1', 'Preheat oven to 375 degrees F (190 degrees C). Lightly butter a 2-quart casserole or baking dish large enough to hold haddock fillets in a single layer.'),
('3084', '2', 'Melt 1 tablespoon of the butter in a skillet over medium heat and cook the onion slices, stirring occasionally, until soft, about 5 minutes. Stir in spinach and nutmeg  and cook for about 3 minutes.'),
('3084', '3', 'Arrange haddock fillets in baking dish. Spoon equal portions of the spinach mixture between the fillets. Spoon drained tomatoes around fillets and sprinkle with the thyme, tarragon and salt.'),
('3084', '4', 'Bake, uncovered, for 20 to 25 minutes or until fish flakes easily with a fork.'),
('3084', '5', 'While fish is baking, make the sauce. If necessary add enough water to reserved tomato liquid to make 1 cup.  In the skillet, melt the remaining 1 tablespoon butter over medium heat. Stir in the minced onion and cook until soft, about 5 minutes.'),
('3084', '6', 'Add 3/4 cup of the tomato juice to the onions. Bring mixture to a boil.'),
('3084', '7', 'Whisk the cornstarch into the remaining 1/4 cup juice, then add to the skillet. Reduce heat and simmer, stirring, until sauce thickens slightly.'),
('3084', '8', 'Pour sauce over baked fillets and serve.'),
('3094', '1', 'Preheat oven to 350 degrees F (175 degrees C). Lightly butter a 2 quart casserole dish.'),
('3094', '2', 'Arrange fish fillets in the bottom of the prepared casserole dish, and sprinkle with salt and pepper to taste. Layer onion slices over fish.'),
('3094', '3', 'Spread cream of mushroom soup over all, and top with shredded cheese.'),
('3094', '4', 'Bake in preheated oven for about 40 minutes, or until bubbly and fish flakes easily with a fork.'),
('3096', '1', 'Make the batter by mixing all the ingredients except for the fish and the oil in a large mixing bowl.'),
('3096', '2', 'Remove the skin and any bones from the fish fillets.'),
('3096', '3', 'Pour the oil into a wide and deep pan (we used a wok), turn on the heat to medium and heat the oil to 140c (if you dont have a thermometer, drop a few drops of the batter into the oil when its hot, the batter should immediately start bubbling and rise to the surface).'),
('3096', '4', 'Put the fish fillets into the bowl of batter and mix them around so that they are all completely covered. Then, one at a time, pick them out and carefully put them into the oil, making sure you dont overcrowd the pan (there should be plenty of space around each one, so do it in batches if necessary).Cook the fish for about 8 minutes, until they are a medium golden brown. While they are cooking, turn them over regularly and drop some of the batter from the bowl onto each piece (this gives it an interesting texture).When the fish is cooked, carefully take it out of the oil and put it onto some kitchen paper to drain off the excess fat (if you are cooking the fish in batches, put the cooked fish into a 100c oven to keep warm).'),
('3096', '5', 'Serve. We served it with chips, tinned mushy peas and tartar sauce.'),
('3098', '1', 'Cook and stir bacon in large saucepan until crisp.  Use slotted spoon to remove bacon from pan. drain on paper towels.  Discard all but 1 Tbsp. drippings from pan.'),
('3098', '2', 'Add next 3 ingredients to reserved drippings in pan. cook on medium heat 12 to 14 min. or until vegetables are crisp-tender, stirring occasionally.'),
('3098', '3', 'Add broth and potatoes. stir.  Bring to boil. cover.  Simmer 10 to 12 min. or until potatoes are tender.'),
('3098', '4', 'Add cream cheese spread. cook, uncovered, 2 to 3 min. or until melted, stirring frequently.'),
('3098', '5', 'Add milk, fish and bacon. stir.  Bring to boil, stirring frequently.  Cook 3 to 4 min. or until fish flakes easily with fork.'),
('3099', '1', 'Whisk mayonnaise, yogurt, vinegar and crushed red pepper to taste in a medium bowl.'),
('3099', '2', 'Add pineapple and coleslaw mix and stir to combine.'),
('3099', '3', 'Place cornmeal in a shallow dish. Sprinkle both sides of fish with Cajun seasoning and salt. Dredge the fish in the cornmeal.'),
('3099', '4', 'Heat 2 teaspoons oil in a large nonstick skillet over medium-high heat.'),
('3099', '5', 'Add half the fish and cook until golden, about 2 minutes per side.'),
('3099', '6', 'Transfer to a plate and repeat with the remaining 2 teaspoons oil and fish, adjusting heat as needed to prevent burning.Top toasted bread with the fish and pineapple slaw to make sandwiches.'),
('3099', '7', 'Serve immediately.'),
('3103', '1', 'Melt 50g butter in a large saucepan (about 20cm across), add 1 finely chopped medium onion and cook gently over a medium heat for 5 minutes, until softened but not browned.'),
('3103', '2', 'Stir in 3 split cardamom pods,  tsp turmeric, 1 small cinnamon stick and 2 bay leaves, then cook for 1 minute.'),
('3103', '3', 'Tip in 450g basmati rice and stir until it is all well coated in the spicy butter.'),
('3103', '4', 'Pour in 1 litre chicken or fish stock, add  teaspoon salt and bring to the boil, stir once to release any rice from the bottom of the pan. Cover with a close-fitting lid, reduce the heat to low and leave to cook very gently for 12 minutes.'),
('3103', '5', 'Meanwhile, bring some water to the boil in a large shallow pan.'),
('3103', '6', 'Add 750g un-dyed smoked haddock fillet and simmer for 4 minutes, until the fish is just cooked. Lift it out onto a plate and leave until cool enough to handle.'),
('3103', '7', 'Hard-boil 3 eggs for 8 minutes.'),
('3103', '8', 'Flake the fish, discarding any skin and bones.'),
('3103', '9', 'Drain the eggs, cool slightly, then peel and chop.'),
('3103', '10', 'Uncover the rice and remove the bay leaves, cinnamon stick and cardamom pods if you wish to. Gently fork in the fish and the chopped eggs, cover again and return to the heat for 2-3 minutes, or until the fish has heated through.'),
('3103', '11', 'Gently stir in almost all the 3 tbsp chopped fresh parsley, and season with a little salt and black pepper to taste.'),
('3103', '12', 'Serve scattered with the remaining parsley and garnished with 1 lemon, cut into wedges.'),
('3104', '1', 'Preheat the oven to 375F (190C).'),
('3104', '2', 'Place the smoked haddock in a baking dish with 3 tbsp water. Cover with aluminum foil.'),
('3104', '3', 'Bake for 15 minutes, until heated through. Uncover and let cool, then flake into pieces.'),
('3104', '4', 'Mix the flaked haddock, mashed potato, scallions, parsley, lemon zest and juice, and mustard together in a bowl. Season with salt and pepper.'),
('3104', '5', 'Divide the mixture into 12 cakes.'),
('3104', '6', 'Place the flour in a small dish, the beaten egg in another, and the bread crumbs in a third dish.'),
('3104', '7', 'Roll each fishcake in the flour, then dip into the egg, and coat with the bread crumbs.'),
('3104', '8', 'Heat the oil in a large frying pan over medium heat. In batches, add the cakes and cook about 5 minutes, turning once, until golden brown.'),
('3104', '9', 'Transfer to paper towels to drain.'),
('3104', '10', 'Serve hot.'),
('3104', '11', 'var article'),
('3104', '12', 'Type_27_data = {}.'),
('3104', '13', 'article'),
('3104', '14', 'Type_27_data.init_step_by_step_images = 0.'),
('3105', '1', 'Fill a large bowl with ice water. In a medium bowl, whisk 2 cups of the flour with 1 teaspoon of salt.'),
('3105', '2', 'Whisk in the club soda until the batter is smooth. Set the bowl in the ice bath. let stand until chilled, 10 minutes.'),
('3105', '3', 'Meanwhile, in a small bowl, combine the cumin with the oregano and paprika. Season the fish with salt and pepper and sprinkle with the spice mixture. In a large bowl, gently toss the tomatoes with the onion, jalapeo and cilantro and season with salt.'),
('3105', '4', 'In a large, deep skillet, heat 2 inches of vegetable oil to 35'),
('3105', '5', 'Place a rack over a rimmed baking sheet. Working with two at a time, dredge the fish fillets in the flour, shaking off any excess. Dip the fillets in the batter and fry, turning once, until golden and cooked through, 4 minutes. transfer to the rack. Repeat with the remaining fish.'),
('3105', '6', 'Arrange the rolls on a work surface cut sides up. Top the bottom halves with the lettuce, fried fish and tomato mixture. Close the sandwiches and serve right away.'),
('3111', '1', 'Preheat the oven to 200C/400F/gas 6 and bring a large pan of salted water to the boil. Peel the potatoes and cut into 2cm chunks. Once the water is boiling, add your potatoes and cook for around 12 minutes, until soft (you can stick your knife into them to check). Meanwhile, get yourself a deep baking tray or earthenware dish and stand a box grater in it. Peel the carrot. Grate the celery, carrot and Cheddar on the coarse side of the grater. Use the fine side of the grater to grate the zest from the lemon. Finely grate or chop your chilli. Finely chop the parsley leaves and stalks and add these to the tray.'),
('3111', '2', 'Cut the salmon and smoked haddock into bite-size chunks and add to the tray with the prawns. Squeeze over the juice from the zested lemon (no pips please!), drizzle with olive oil and add a good pinch of salt and pepper. If you want to add any spinach or tomatoes, do it now.'),
('3111', '3', 'Mix everything together really well. By now your potatoes should be cooked, so drain them in a colander and return them to the pan.'),
('3111', '4', 'Drizzle with a couple of good lugs of olive oil and add a pinch of salt and pepper. Mash until nice and smooth, then spread evenly over the top of the fish and grated veg.'),
('3111', '5', 'Place in the preheated oven for around 40 minutes, or until cooked through, crispy and golden on top.'),
('3111', '6', 'Serve piping hot with tomato ketchup, baked beans, steamed veg or a lovely green salad'),
('3111', '7', 'Tip'),
('3113', '1', 'Preheat oven to 400F. line a baking sheet with a silpat liner or parchment paper and brush a light coating of olive oil on the silpat or parchment.In a small skillet, heat olive oil over low heat. add onion and garlic and saut until tender and just starting to brown (about 5-7 minutes), stirring occasionally.'),
('3113', '2', 'Add breadcrumbs and saut until light golden brown (about 1-2 minutes), stirring frequently. Turn off heat and stir in thyme, 2 tablespoons parsley, and a pinch of salt and pepper.Pat the fish dry and lay it (skin side down) on the prepared baking sheet. drizzle 1 teaspoon of lemon juice on each fillet. Top with the breadcrumb mixture and bake until the fish is fully cooked (it will become opaque and flake easily with a fork when its done), about 15-25 minutes.Sprinkle remaining 1 tablespoon parsley on top and serve with fresh lemon to squeeze on top.000356Share on Pinterest0Share with your friends'),
('3113', '3', 'Your Name'),
('3113', '4', 'Your Email'),
('3113', '5', 'Recipient Email'),
('3113', '6', 'Enter a MessageI read this article and found it very interesting, thought it might be something for you. The article is called'),
('3113', '7', 'Baked Fish with Crumb Topping and is located at http://www.anediblemosaic.com/baked-fish-with-crumb-topping/.Captcha'),
('3113', '8', 'Submit'),
('3122', '1', 'Combine the olive oil, half the parsley, and the garlic in a cazuela or saut pan large enough to hold the fish and clams in a single layer. Sprinkle the hake on both sides with salt and add to the cazuela, skin side down. Dust the fish with flour, then add the clams and  cup water and bring to a simmer. Cook for 2 minutes, then turn the fish, lower the heat, and simmer very gently until the clams open and the fish is cooked through, about 5 minutes. Divide the fish and clams among four plates, stir the pan juices, and spoon over the fish and into the clams. Sprinkle with the remaining parsley and serve.'),
('3122', '2', 'var article'),
('3122', '3', 'Type_27_data = {}.'),
('3122', '4', 'article'),
('3122', '5', 'Type_27_data.init_step_by_step_images = 0.'),
('3128', '1', 'In a medium pot of boiling salted water, cook the lobster until bright red all over, about 9 minutes.'),
('3128', '2', 'Transfer the lobster to a plate and let cool slightly. Twist the tail and claws from the body and crack the claws.'),
('3128', '3', 'Remove the meat from the tail in 1 piece. Make a slit down the center of the tail meat and remove the intestinal tract.'),
('3128', '4', 'Remove the meat from the claws.'),
('3128', '5', 'Cut the lobster meat into 1-inch pieces. Cover and refrigerate.'),
('3128', '6', 'Melt the butter in a large saucepan.'),
('3128', '7', 'Add the salt pork and cook over moderate heat, stirring, for 1 minute. Stir in the onions and cook until softened, about 7 minutes.'),
('3128', '8', 'Add the potatoes, clam juice, water and bay leaf and bring to a simmer. Cook over moderate heat until the potatoes are just tender, about 12 minutes.'),
('3128', '9', 'Add the cream and return to a simmer.'),
('3128', '10', 'Add the fish fillets and simmer gently until they break apart and are cooked through, about 10 minutes.'),
('3128', '11', 'Remove the soup from the heat and stir in the mussels, shrimp and lobster meat. Cook over low heat until the shellfish is just heated through.'),
('3128', '12', 'Add the paprika and season with salt and pepper. Ladle the chowder into mugs or bowls, garnish with the parsley and serve.'),
('3131', '1', 'Heat the oil in the pan.'),
('3131', '2', 'Add the onion and saute until tender, about 6-10 minutes.'),
('3131', '3', 'Add the garlic and chili pepper flakes and saute until fragrant, about a minute.'),
('3131', '4', 'Add the fennel and red peppers and saute for a few minutes.'),
('3131', '5', 'Add the white wine and simmer for a few minutes.'),
('3131', '6', 'Add the tomatoes, oregano, paprika, salt and pepper, cover and simmer for 20 minutes.'),
('3131', '7', 'Add the fish simmer until cooked, about 5 minutes.'),
('3131', '8', 'Remove and mix in the fresh herbs.'),
('3132', '1', 'To the milk add, salt, pepper, cumin and coriander, whisk to mix.'),
('3132', '2', 'Add milk mixture to a small frypan. bring to a low simmer, add fish and simmer about 3 minutes, carefully turn the fish and simmer another 2 minutes, Turn the heat off leaving the fish in the milk.Topping:.Take 4 or 5 tablespoons of the poaching milk and add to a small pot. add corn, tomato,red onion, cumin, coriander and cayenne pepper. stir to mix. bring to simmer, simmer for 2 minutes.'),
('3132', '3', 'Remove the fish from the milk to a serving plate. Spoon the relish over the fish in a neat line.'),
('3132', '4', 'Serve immediately.'),
('3133', '1', 'Preheat oven to 200C (390F). Lightly brush an oven-proof baking dish w/some of the oil & set aside.'),
('3133', '2', 'Cut haddock into pieces, season w/salt + pepper & set aside.'),
('3133', '3', 'Heat remaining oil in a non-stick frying pan.'),
('3133', '4', 'Saute leek & garlic over med-heat till softened.'),
('3133', '5', 'Add chopped bell peppers + mushrooms (if using) & saute for 2-3 minutes.'),
('3133', '6', 'Add shrimp, single cream, pineapple tidbits, & pineapple juice. Stir in Worcestershire sauce, curry powder & paprika. Taste & add salt & pepper as desired.Simmer for 2 minutes.'),
('3133', '7', 'Add fish pieces & simmer for 1 minute.'),
('3133', '8', 'Remove from heat & pour into the prepared baking dish. Cover loosely w/foil & bake for 15-20 minutes.'),
('3133', '9', 'Serve over rice.'),
('3134', '1', 'Pre-head oven to 350 degrees.In a bowl, combine the breadcrumbs, salt, pepper, garlic powder, onion powder, parsley and red pepper flakes.'),
('3134', '2', 'Mix.Spray a bake dish/pan with non-stick cooking spray.'),
('3134', '3', 'Place 4 pieces of fish on bake ware, skin side down.'),
('3134', '4', 'Add a 1/4 tablespoon of olive oil to each piece of fish. spread on fish.'),
('3134', '5', 'Add the breadcrumb mixture on top of each piece of haddock (about 1/4 cup to each piece of fish, more or less depending on the size of the fillet).Cook in the oven for 15 minutes.Meanwhile -- add the tomatoes, scallions, cilantro and lemon juice to bowl.'),
('3134', '6', 'Mix together with spoon or fingers.After the 15 minute cooking time period is up, add the tomato/cilantro mixture to top of each fish and cook for an additional 5 minutes.'),
('3134', '7', 'Serve immediately.'),
('3136', '1', 'Boil the eggs for 10 minutes, then hold under cold running water.'),
('3136', '2', 'Put the fish and bay leaves in a shallow pan with enough water to cover. Bring to the boil, cover and simmer for about 5 minutes, until cooked through.'),
('3136', '3', 'Remove from pan and leave to cool.'),
('3136', '4', 'Remove the skin from fish, flake into chunks and set aside.Cook the rice in salted water for about 10 minutes and drain. Refresh in cold water, drain again, and leave in the fridge until needed. Melt the butterghee in a pan over a low heat.'),
('3136', '5', 'Add the ginger, onion and garlic. Soften for about 5 minutes, then add the curry powder and mustard seeds. Cook for a further few minutes, then add the chopped tomatoes and lemon juice.Quarter the eggs.'),
('3136', '6', 'Add the fish and rice to a pan and gently heat through.'),
('3136', '7', 'Add the eggs, most of the coriander and the chilli and stir gently.'),
('3136', '8', 'Place in a warm serving dish.'),
('3136', '9', 'Mix the rest of the coriander into the yoghurt and serve with the kedgeree.Tip'),
('3139', '1', 'Preheat your oven to 220C/425F/Gas 7.Coat a baking tray with 1/2 tsp olive oil and place the fish on top.'),
('3139', '2', 'Mix the breadcrumbs, cheese and parsley, season to taste with salt and pepper and press, using the back of a spoon, onto the top of the fish fillets.'),
('3139', '3', 'Place the tomatoes around the fish on the baking tray and drizzle everything with the rest of the oil.Roast for approx 10 minutes until the crust becomes golden and the fish is cooked.Times may vary depending on the thickness of your fish, If it needs longer you may need to cover the top with tin foil to stop it from burning, after the first 10 minutes.'),
('3140', '1', 'Preheat oven to 425.Wash and dry fish fillets, then season with salt.Meanwhile, mix breadcrumbs, melted butter, juice of a lemon, salt, pepper, and garlic powder.You will need to spray some cooking spray on the breadcrumbs to make sure they are moist enough. The breadcrumbs should be forming into moist crumbs.'),
('3140', '2', 'Place fish in shallow baking pan.'),
('3140', '3', 'Pour the white wine around the fish, making sure it does not actually cover the fish.'),
('3140', '4', 'Place the breadcrumb mixture evenly over the fish.'),
('3140', '5', 'Put the fish(for haddock or cod) in the oven for about 10-12 minutes, until almost done.You then may want to broil the fish for a minute or two just to crisp up the topping.'),
('3141', '1', 'Cut the haddock into two or more pieces to fit into a frying pan (preferably one with a lid).'),
('3141', '2', 'Add some pepper, the bay leaf, blade of mace, if you have one, and sprig of parsley, and pour over the water. Cover the pan with a lid, or some tightly sealed foil, and bring to the boil. Turn down and simmer the haddock for 3-5 minutes so that the fish is cooked through but not falling apart.'),
('3141', '3', 'Remove with a slotted spatula and wrap the haddock in foil and reserve the liquid from the pan, straining it into a measuring jug. Make the liquid in the jug up to the 1 litre / 4 cup mark with boiling water and add the vegetable broth granules or cube or whatever you''re using.'),
('3141', '4', 'Pour this liquid into a saucepan and put over a low heat.On a nearby burner, in a fairly wide saucepan, heat 30g / 2 tablespoons of the butter and the oil. Trim the leek, and then finely slice it into circles, adding it to the oily pan. Cook gently for about 5 minutes until the leek softens.'),
('3141', '5', 'Add the rice to the pan and turn well in the buttery oil until slicked and glossy then stir in the spices and lemon zest. Turn up the heat and add the wine, stirring until it is bubblingly absorbed. Then add a ladleful of the reserved fish cooking liquid mixed with vegetable stock in its nearby saucepan, stirring until it too is absorbed then proceed ladleful by ladleful until the rice is cooked and sticky - about 20 minutes - and the liquid is used up or nearly all used up. You probably don''t need me to remind you, but let me anyway: it is important that each ladleful is absorbed before you add the next one.Meanwhile, put the quail''s eggs in a pan of cold water and bring to the boil. Once the water''s come to the boil, drain the eggs and put them in a bowl of cold water, running the tap for a while over them to make sure they stop cooking.Once you have reached the right point with the risotto, and the rice is done, add the fish, minimally flaked with a fork or your fingers, to the rice along with the remaining butter and the lemon juice, beating well, off the heat, with your wooden spoon to make sure everything is creamy and well amalgamated. Spoon the risotto on to a large plate so that it is fairly flat, add the peeled and halved quails eggs au choix and sprinkle with the parsley.'),
('3144', '1', 'Place butter in a 13-in. x 9-in. x 2-in. baking dish. place in a 400 degrees F oven until melted.'),
('3144', '2', 'Spread butter over bottom of dish. cover with onion. Arrange fish over onion. sprinkle with salt, dill and pepper.'),
('3144', '3', 'Combine the Parmesan cheese, mayonnaise, parsley and lemon juice. spread over fish.'),
('3144', '4', 'Bake, uncovered, at 400 degrees F for 18-20 minutes or until fish flakes easily with a fork. Sprinkle with almonds.'),
('3145', '1', 'Preheat the oven''s broiler and set the oven rack about 6 inches from the heat source.'),
('3145', '2', 'Place the orange roughy filets on the broiler pan and squeeze the lemon over the top of the fish.  Broil the filets in the preheated oven for about 6 to 8 minutes.'),
('3145', '3', 'Combine parmesan, butter, dijionnaise, garlic, and salt in a small bowl.'),
('3145', '4', 'Remove the fish from the oven and spread the cheese mixture on top of the filets.  Sprinkle with paprika.  Broil until the topping is lightly browned and the fish flakes easily with a fork, about 3 minutes.'),
('3146', '1', 'Place the haddock in a single layer in a large, deep frying pan.'),
('3146', '2', 'Add enough water to cover and heat over medium heat until just simmering. Reduce the heat to low, and simmer for 7 minutes. Using a slotted spoon, transfer the fish to a plate and cool.'),
('3146', '3', 'Meanwhile, bring the rice, 2 cups water, saffron, and  tsp salt to a boil in a medium saucepan. Reduce the heat to low and cover. Simmer about 15 minutes, until the rice is tender.'),
('3146', '4', 'Remove from heat and stir in the butter.'),
('3146', '5', 'Remove the yolks from the hard-boiled eggs. chop finely, and set aside. Chop the egg whites and stir into the rice with the flaked fish and 2 tbsp chopped parsley.'),
('3146', '6', 'Spoon onto heated plates, sprinkled with the chopped egg yolk and parsley, and serve with the lemon wedges.'),
('3146', '7', 'var article'),
('3146', '8', 'Type_27_data = {}.'),
('3146', '9', 'article'),
('3146', '10', 'Type_27_data.init_step_by_step_images = 0.'),
('3147', '1', 'Heat the water,2 tablespoonsbutter, carrots and pepper in a 3-quart saucepan over medium-high heatto a boil.'),
('3147', '2', 'Remove the saucepan from the heat.'),
('3147', '3', 'Add the stuffing and mix lightly.'),
('3147', '4', 'Spoon the stuffing across thecenter of a 3-quart shallow baking dish. Arrange the fish on each side of the stuffing.'),
('3147', '5', 'Heat the remaining butter in an 8-inch skillet over medium heat until it''s melted.Stir in thelemon juice and parsley. Spoonthe butter mixture over the fish.'),
('3147', '6', 'Bake at 400F. for 15 minutes or until the fish flakes easily when tested with a fork.'),
('3147', '7', '*For moister stuffing increase the water to 1 1/2 cups.'),
('3148', '1', 'Preheat oven to 400F.'),
('3148', '2', 'Spread rice in 8-inch square baking dish.'),
('3148', '3', 'Pour boiling water over rice.  Cover with plastic wrap.'),
('3148', '4', 'Let stand 5 min.  Uncover.'),
('3148', '5', 'Arrange broccoli over rice.'),
('3148', '6', 'Mix soup and water. pour over broccoli.  Sprinkle with half of the cheese.  Top with fish. sprinkle with remaining cheese.'),
('3148', '7', 'Bake 30 min. or until fish flakes easily with fork.'),
('3149', '1', 'Whisk together the salt, ancho and chili de arbol powders in a bowl. Set aside.'),
('3149', '2', 'Cut potatoes into 1/4-inch thick slices then cut each slice into 1/4-inch thick fries.'),
