INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('5902', '1', 'Add 1 lb fresh water prawn or shrimp, 1 shallot (finely chopped), 1 bunches of scallion, 1 tablespoon fish sauce and 1/2 teaspoon black pepper in a mixing bowl and allow to marinate.In a wok or small pan, add 2 soup spoons of cooking oil and allow the oil to get hot.'),
('5902', '2', 'Add the sugar and with a spatula stir the sugar in oil so that the caramel sauce is not congested into a clump. Once the sugar and oil take on a caramel color, set aside.In a wok or skillet, heat 2 tablespoons of cooking oil and add the prawn and saute them for 2 minutes.'),
('5902', '3', 'Add the caramel sauce and with your spatula saute everything together until the prawn turns pink all around and the juices have seem to have been sucked up by the shrimp.'),
('5902', '4', 'Serve immediately.Catherine Thai of Cat Restaurant in Little Saigon also provided me with her award-winning caramel shrimp recipe. Here you go.Caramelized Spotted Prawns in Clay Pot:To make the caramel sauce, put sugar in a small pan, spread to an even layer. Cook at medium heat (without stirring) until the sugar starts melting. Now, you can start stirring the sugar and keep cooking until this turns into a dark amber color. Turn off heat.Note that the sugar will continue to turn a darker color.Wait for about 30 seconds to one minute before adding the 2 tablespoons of water. Be careful as this will splatter. Turn the heat back on and cook at low heat until the caramel dissolves.'),
('5902', '5', 'Put the shells in a small pan and add a few tablespoons of water. Boil for a few minutes at high heat then discard the shells. Continue boiling to reduce the stock to about one tablespoon.'),
('5902', '6', 'Heat oil in a wok at high heat.'),
('5902', '7', 'Add shallot and garlic. saut until fragrant.'),
('5902', '8', 'Add the shrimp and brown quickly.'),
('5902', '9', 'Add the stock, fish sauce, caramel sauce, salt, and sugar. Cook until the shrimp is done and the sauce thickens, about 4 to 5 minutes.'),
('5902', '10', 'Add the scallions, stir, and turn off heat. Sprinkle on some black pepper and serve with steamed rice.'),
('5903', '1', 'In a small saucepan, combine the ginger with the vinegar, sugar and chiles. Bring to a boil, stirring to dissolve the sugar.'),
('5903', '2', 'Transfer to a large bowl. let cool.'),
('5903', '3', 'In a large pot of boiling salted water, simmer the shrimp until pink and cooked through, about 2 minutes.'),
('5903', '4', 'Drain the shrimp and add them to the ginger mixture. Stir in the ice cubes and refrigerate for at least 4 hours or overnight.'),
('5903', '5', 'Drain the shrimp and pat dry. Discard the ginger and chiles.'),
('5903', '6', 'In a small bowl, mix the Thai chili sauce with the lime juice, ketchup and fish sauce. Refrigerate until chilled. Arrange the shrimp on a platter with the celery sticks and cucumber spears and serve with the sauce.'),
('5906', '1', 'Rinse shrimp and pat dry with paper towels. Set aside. In a small saucepan over medium-high heat, bring soy sauce, honey, and lime zest and juice to a boil. Reduce heat to low and simmer until syrupy and reduced by half, 4 to 5 minutes. Set aside.'),
('5906', '2', 'Heat a large wok or nonstick skillet over high heat until hot, about 2 minutes.'),
('5906', '3', 'Add olive oil and heat for 30 seconds.'),
('5906', '4', 'Add shrimp and stir-fry until opaque, about 1 minute.'),
('5906', '5', 'Add soy-sauce mixture and stir-fry for 1 minute more.'),
('5906', '6', 'Add bok choy and stir-fry until leaves are just wilted, about 1 minute.'),
('5906', '7', 'Serve immediately.'),
('5907', '1', 'Bring the clam juice and orange juice to a boil over high heat in a 12-inch skillet until the mixture is reduced by half, about 5 min. Meanwhile, peel and devein the shrimp (to save time, look for "easy-peel" shrimp, which has already been deveined). With a spatula, scrape the reduced sauce into a small bowl and set aside.    Without rinsing the pan, return it to high heat and add the butter and garlic. cook until the garlic starts to sizzle, about 15 seconds.'),
('5907', '2', 'Add the shrimp and saut until it just starts to lose its raw color, 2 to 3 minutes, sprinkling lightly with salt and pepper to taste. The pan will start to darken as the sugar from the sauce cooks. don''t worry, this will just add more flavor to the finished sauce.'),
('5907', '3', 'Add the reduced sauce and bring to a simmer. Stir in the Pernod or vermouth and the basil.'),
('5907', '4', 'Remove and discard the garlic cloves, adjust the seasonings, and serve. Angel hair pasta or rice makes a nice accompaniment.'),
('5908', '1', 'In a small saucepan, over medium heat reduce Worcesteshire Sauce to 1/4 cup. Once reduced, remove from heat and let cool. Once cool, add Red Hot Sauce and stir to combine.In a large saucepan, over medium heat, bring chicken stock to a gentle boil. Stir in grits. Cook for 30 minutes, stirring occasionally. (The grits will stick to the bottom of the pan a bit, so dont panic.) Lower the heat to medium low and add whole milk and half & half to grit mixture and stir to combine. Cook for an additional 30 minutes, stirring occasionally.'),
('5908', '2', 'Remove the pan from heat and set aside.In a large skillet, add 2 tablespoons of canola oil until it shimmers.'),
('5908', '3', 'Add the sliced sausage and stir frequently to brown edges, then add sliced mushrooms. (The mushrooms will release a lot of their moisture.) Cook sausage and mushrooms until liquid is almost gone.'),
('5908', '4', 'Add chopped tomatoes and green onions. Sprinkle with a pinch of kosher salt to help remove liquid from tomatoes and green onions and stir to combine.'),
('5908', '5', 'Add shrimp and cook for 3-4 minutes and stir. Next pour in the Worcesteshire/Red Hot sauce. Stir to thoroughly incorporate sauce into the ingredients and cook for another 3-4 minutes.'),
('5908', '6', 'Remove skillet from heat and stir in chopped parsley.'),
('5908', '7', 'Serve shrimp and sausage mixture over grits. Top grits with shredded monterey jack cheese if desired.**The grits, by themselves, make for a warm and filling breakfast (which is how they are traditionally served). But never ever put sugar or pour syrup on them. The great spirits of the South will find you and torment you for desecrating the sanctity of the grits. My husband (Craig) is still trying to live that one down.Welcome to My Man''s Belly! Leave me a comment and let me know what you think about the site or if there''s a recipe you''d like to see here. Have a great day.Like this? You''ll love these:Chicken Cauliflower Fried Rice'),
('5908', '8', 'Traditional Italian Pasta Sauce Dinner in a Pumpkin'),
('5908', '9', 'Easy Chicken Recipes  Chicken Arrabiata'),
('5908', '10', 'Chilaquiles For Breakfast, Lunch or Dinner'),
('5908', '11', 'Spicy Sausage Lentil Soup'),
('5908', '12', 'Tweet'),
('5908', '13', 'Pin It'),
('5910', '1', 'Dissolve the yeast in 1 glass warmluke water.'),
('5910', '2', 'Add to the flour, toghether with a small pinch of salt, and mix with a fork, adding some more water untill you get a medium liquid dough. Cover and let rest for one hour.'),
('5910', '3', 'Poor the soybeab sauce and the honey in a small saucepann and cook for 5 minutes over high heat till the mixture thikens in a littlee. Set aside.'),
('5910', '4', 'Heat the oil in a wok. Take back the risen dough, mix it quickly and dip one shrimp at a time in the batter. Sprinkle with some sesam seed and put it in the hot oil. Fry 4-5 shrimps at a time until golden, thes take then out with a clotted spoon and put them to drain on a few layers of paper. Sprinkle with a little salt.'),
('5910', '5', 'Serve the fried shrimps immediately with the soy reduction on the side, as a dip.'),
('5911', '1', 'Place chiles directly over the burners of a gas stove. Roast over medium-high heat, turning occasionally, until skin is charred and chiles soften, 10 to 15 minutes. (To roast in oven, cover a large cookie sheet with foil.'),
('5911', '2', 'Place chiles on sheet and broil, turning occasionally, until skin is charred and chiles soften, 12 to 17 minutes.)'),
('5911', '3', 'Remove from heat and cool.'),
('5911', '4', 'Remove peel and seeds. Slice thinly. set aside. Sprinkle shrimp with half the salt and pepper.'),
('5911', '5', 'Heat oil in a large pan over high heat. Cook shrimp, stirring occasionally, 2 to 3 minutes.'),
('5911', '6', 'Add garlic. cook until fragrant, about 1 minute. Stir in chiles, red peppers, tomatoes, zest and lime juice. Cook until liquid reduces by half and shrimp are no longer translucent, 1 to 2 minutes.'),
('5911', '7', 'Add wine and reduce until slightly syrupy. Stir in pasta. Reduce heat to low and cover 1 minute. Top with cilantro and serve.'),
('5911', '8', 'Place chiles directly over the burners of a gas stove. Roast over medium-high heat, turning occasionally, until skin is charred and chiles soften, 10 to 15 minutes. (To roast in oven, cover a large cookie sheet with foil.'),
('5911', '9', 'Place chiles on sheet and broil, turning occasionally, until skin is charred and chiles soften, 12 to 17 minutes.)'),
('5911', '10', 'Remove from heat and cool.'),
('5911', '11', 'Remove peel and seeds. Slice thinly. set aside. Sprinkle shrimp with half the salt and pepper.'),
('5911', '12', 'Heat oil in a large pan over high heat. Cook shrimp, stirring occasionally, 2 to 3 minutes.'),
('5911', '13', 'Add garlic. cook until fragrant, about 1 minute. Stir in chiles, red peppers, tomatoes, zest and lime juice. Cook until liquid reduces by half and shrimp are no longer translucent, 1 to 2 minutes.'),
('5911', '14', 'Add wine and reduce until slightly syrupy. Stir in pasta. Reduce heat to low and cover 1 minute. Top with cilantro and serve.'),
('5913', '1', 'Peel shrimp, and devein, if desired. set aside.'),
('5913', '2', 'Bring nectar to a boil in a medium saucepan. boil 45 minutes or until reduced to 1 cup. Stir in 2 tablespoons lime juice and next 3 ingredients.'),
('5913', '3', 'Remove from heat, and cool.'),
('5913', '4', 'Pour half of nectar mixture in a large shallow dish or heavy-duty zip-top plastic bag. add shrimp. Cover or seal, and chill 1 hour.'),
('5913', '5', 'Remove shrimp from marinade, discarding marinade.'),
('5913', '6', 'Grill, in 2 batches, in a grill basket over medium-high heat (350 to 40'),
('5913', '7', '3 to 4 minutes or until shrimp turn pink.'),
('5913', '8', 'Add remaining 2 tablespoons lime juice, tomato, and next 4 ingredients to remaining nectar mixture. Cook over medium heat until thoroughly heated. Stir in shrimp. serve over rice.'),
('5913', '9', 'Garnish, if desired.'),
('5913', '10', '*1 pineapple, chopped, may be substituted for papaya.'),
('5913', '11', 'NOTE: Select unblemished papayes or mangoes that yield slightly to pressure. If underripe, place in a paper bag at room temperature to speed up the process.'),
('5916', '1', 'Preheat oven to 400 degrees Farenheit.Peel and devein shrimp.'),
('5916', '2', 'Place shrimp on a baking sheet and drizzle them with 2 tablespoons of olive oil and season with salt and pepper. Stir the shrimp around to thoroughly coat them with the oil and seasonings. Make sure they are spread evenly, in a single layer, on the pan and roast in the oven for 6-10 minutes. Cook until shrimp are pink and firm.'),
('5916', '3', 'Pour 2 tablespoons of oil into a saucepan and add chopped garlic. Over medium high heat saute the garlic. Keep stirring the garlic so that it doesnt burn. Once you start to smell the garlic add the beans, tomatoes and sage. Stir to combine and keep over the heat until everything is heated through. Season with salt and pepper.Spoon the bean mixture onto the plate and top with shrimp and Parmesan cheese.Welcome to My Man''s Belly! Leave me a comment and let me know what you think about the site or if there''s a recipe you''d like to see here. Have a great day.Like this? You''ll love these:Easy Shrimp Tacos'),
('5916', '4', 'Cilantro Lime Shrimp'),
('5916', '5', 'Greek Orzo Pasta Salad'),
('5916', '6', 'Dinner in a Pumpkin'),
('5916', '7', 'Clean Eating Basic White Beans Recipe'),
('5916', '8', 'Rich and Delicious Vegetarian Chili'),
('5916', '9', 'Tweet'),
('5916', '10', 'Pin It'),
('5918', '1', 'Combine the ingredients and set aside in container. This step can be done the day before dinner.'),
('5918', '2', 'Peel and cut the citrus fruit into sections over a plate.'),
('5918', '3', 'Drain the juice from the plate into a bowl. Season liberally with gray salt and black pepper.'),
('5918', '4', 'Whisk in olive oil to form a vinaigrette (it should be in proportion, about 2 parts juice to 1 part olive oil).'),
('5918', '5', 'Season citrus sections with salt and pepper.'),
('5918', '6', 'Drizzle a little of the vinaigrette on them to marinate and put them on a platter.'),
('5918', '7', 'Have your fishmonger peel the prawns but leave the tails on for handles. Season liberally with salt and pepper. Preheat a saute pan on high. Dredge the shrimp in the flour mixture. This will give them a nice crust and allow them to stay crispy and fresh at room temperature.'),
('5918', '8', 'Add olive oil to the pan and put in 1 layer of shrimp. You want them to caramelize, so don''t toss or move them.'),
('5918', '9', 'Add a little more oil if the flour absorbs what''s in the pan. After about 3 minutes, turn over the prawns.'),
('5918', '10', 'Let it caramelize, toss and turn out onto a cookie sheet.'),
('5918', '11', 'Add about 1/4 cup more olive oil to the already hot saute pan.'),
('5918', '12', 'Drain pan juices from the cookie sheet into the saute pan.'),
('5918', '13', 'Add sliced garlic and let it get light brown.'),
('5918', '14', 'Add chiles and let them get soft.'),
('5918', '15', 'Add the basil and stand back - there''s a lot of water in basil and it will pop.'),
('5918', '16', 'Let it get crispy, less than a minute. While this is happening, arrange prawns over the citrus salad.'),
('5918', '17', 'Add the orange zest to the basil/garlic/chile mixture in the saute pan. Season with salt and pepper, then spoon basil/garlic/chile mixture over the prawns.'),
('5918', '18', 'Toss the spinach with the citrus vinaigrette and mound on top of the prawns.'),
('5918', '19', 'Serve.'),
('5922', '1', 'Preheat oil to 350F.'),
('5922', '2', 'Place shrimp, green onions and garlic into a large mixing bowl and toss together. Set Aside.'),
('5922', '3', 'Pour water into medium pot and add butter and salt and bring to a boil.'),
('5922', '4', 'Once mixture has come to a boil, add flour and quickly stir with a wooden spoon, until dough forms. Continue to stir over medium heat, for about 3 minutes.'),
('5922', '5', 'Place dough into a stand mixer fixed with a paddle attachment and run on medium speed, allowing steam to escape.'),
('5922', '6', 'Once most of the steam has disappeared add the egg, one at a time, scraping down the sides of the bowl after each addition.'),
('5922', '7', 'Fold pepper into the pate a choux (the doughy/battery mixture).'),
('5922', '8', 'Fold the shrimp mixture into the pate a choux until fully incorporated.'),
('5922', '9', 'Once oil is hot, add tablespoon sized balls of the shrimp mixture into the oil (youll have to do this in batches). make sure not to crowd the pan/fryer.1'),
('5922', '10', 'Fry each fritter for 4 to 6 minutes, flipping halfway if necessary.'),
('5922', '11', 'Drain on a paper towel and season lightly with salt.'),
('5922', '12', 'Serve immediately with spicy honey drizzle.'),
('5923', '1', 'Heat 2 tbsp. oil in a large wide pot over medium-low heat.'),
('5923', '2', 'Add onion and cook, covered, until starting to soften, 5 minutes.'),
('5923', '3', 'Add pasta and more oil if it looks dry, then toast over medium-high heat, turning constantly with tongs, until golden.'),
('5923', '4', 'Add garlic and saffron (if using), tomatoes and tomato paste, sausages, and broth.'),
('5923', '5', 'Boil pasta in soup, uncovered, until noodles are tender, about 5 minutes.'),
('5923', '6', 'Add shrimp and cook just until pink and curled, about 1 minute. Season with salt to taste and stir in parsley.'),
('5924', '1', 'Heat oil in a large saut pan over medium-high heat. Saut onion until golden brown, about 3 minutes. Grind ginger and garlic into a paste. add it and remaining spices and tomatoes to pan. simmer 5 minutes. In a separate pan, saut shrimp 30 seconds.'),
('5924', '2', 'Add sauce and stir continuously on high heat, 2 or 3 minutes, until most of the liquid evaporates.'),
('5924', '3', 'Serve over rice.'),
('5924', '4', 'Garnish with coriander.'),
('5924', '5', 'Heat oil in a large saut pan over medium-high heat. Saut onion until golden brown, about 3 minutes. Grind ginger and garlic into a paste. add it and remaining spices and tomatoes to pan. simmer 5 minutes. In a separate pan, saut shrimp 30 seconds.'),
('5924', '6', 'Add sauce and stir continuously on high heat, 2 or 3 minutes, until most of the liquid evaporates.'),
('5924', '7', 'Serve over rice.'),
('5924', '8', 'Garnish with coriander.'),
('5927', '1', 'In a medium bowl, toss the flour with the baking powder, sugar and salt. In a small bowl, whisk together the egg yolk, water, milk, yogurt and oil. Stir the liquid into the flour mixture with a wooden spoon.'),
('5927', '2', 'Transfer the dough to a lightly floured work surface and knead briefly until smooth. Divide the dough into 4 pieces and shape each piece into an oval disk. Wrap each dough disk in plastic wrap and refrigerate until chilled, about 4 hours or overnight.'),
('5927', '3', 'In a small bowl, stir together 1 tablespoon of the crme frache, 1 tablespoon of the lime juice, 1 tablespoon of the chopped dill and the horseradish and mayonnaise. Fold in the pineapple. Refrigerate until chilled, about 2 hours.'),
('5927', '4', 'Set a large pizza stone in the bottom third of the oven. Preheat the oven to 500 for at least 40 minutes. In a small bowl, combine the remaining 1/4 cup of crme frache with the remaining 1/2 tablespoon of chopped dill and 1/2 tablespoon of the lime juice.'),
('5927', '5', 'On a lightly floured work surface, roll out each piece of dough to a 9-by-7-inch oval. Set the ovals on the pizza stone and bake for about 3 1/2 minutes, or just until golden and puffed.'),
('5927', '6', 'Meanwhile, in a bowl, whisk the oil with the remaining 1 teaspoon of lime juice and season with salt and pepper.'),
('5927', '7', 'Add the greens and toss to coat.'),
('5927', '8', 'Set a hot naan on each of 4 plates and top with the greens. Cover the naans with the pineapple, half of the dill cream and the shrimp. Spoon the remaining dill cream on top and serve at once.'),
('5929', '1', 'Place the lemon grass, garlic, galangal, chili, cilantro, lime juice and zest, green onions, shrimp paste, fish sauce, oil and palm sugar in a foor processor and process.'),
('5929', '2', 'Marinate the shrimp in the paste for at least 10 minutes.'),
('5929', '3', 'Skewer the shrimp.'),
('5929', '4', 'Grill until cooked, about 2-3 minutes per side.'),
('5930', '1', 'Combine 1 cup of the flour with the cayenne, salt, sugar and baking powder in a medium bowl.'),
('5930', '2', 'Add beer all at once and whisk until smooth. Set aside at least 1/2 hour.'),
('5930', '3', 'Heat oil to deep-fry temperature (350/) in a large saucepan. Test oil by sprinkling a few drops of'),
('5930', '4', 'batter and if they rise to the surface, the oil is ready. Toss the shrimps in the flour for dusting and toss to coat evenly, then pat off excess. Drop a few at a time first in the batter then into the hot oil and fry until lightly golden and crispy-- about 2 minutes.'),
('5930', '5', 'Remove with a slotted spoon and drain on paper towels.'),
('5930', '6', 'Serve immediately with Chipotle Honey Dipping Sauce.'),
('5930', '7', 'In a small saucepan, bring chiles, tomato, water, onion, garlic and salt to a boil and reduce to a simmer. Cook, slowly, covered for 15 minutes, then puree in a blender until smooth transfer to a small bowl and add honey and vinegar.'),
('5930', '8', 'Serve at room temperature as a dipping sauce with shrimps.'),
('5933', '1', 'Combine 2 teaspoons sugar, chili powder, chile powders, and 1/4 teaspoon salt in a shallow dish.'),
('5933', '2', 'Add shrimp to spice mixture. toss well to coat.'),
('5933', '3', 'Heat 1 tablespoon oil in a large nonstick skillet over medium-high heat.'),
('5933', '4', 'Add 1/2 cup onion, bell pepper, garlic, and ginger to pan. saut 3 minutes.'),
('5933', '5', 'Add remaining 1 1/2 teaspoons sugar and corn to pan. cook 3 minutes, stirring occasionally. Stir in vinegar. cook 30 seconds.'),
('5933', '6', 'Transfer corn mixture to a bowl. stir in remaining 1/4 teaspoon salt and 1/2 cup green onions.'),
('5933', '7', 'Wipe pan with a paper towel.'),
('5933', '8', 'Heat remaining 2 teaspoons oil in pan over medium-high heat.'),
('5933', '9', 'Add shrimp to pan. saut 3 minutes or until done, turning once.'),
('5933', '10', 'Serve with corn mixture.'),
('5934', '1', 'Combine lemon halves, next 3 ingredients, and salted water to cover in a Dutch oven. Bring to a boil. add shrimp, and cook 2 to 3 minutes or just until shrimp turn pink. Plunge shrimp into ice water to stop the cooking process. drain.'),
('5934', '2', 'Peel shrimp, leaving tails on. Devein, if desired.'),
('5934', '3', 'Combine orange juice and next 9 ingredients in a large shallow dish or heavy-duty zip-top plastic bag.'),
('5934', '4', 'Add shrimp, cover or seal, and chill 25 minutes.'),
('5934', '5', 'Drain off liquid.'),
('5934', '6', 'Serve shrimp over lettuce leaves with Louis Sauce.'),
('5934', '7', 'Garnish, if desired.'),
('5936', '1', 'Place yogurt, sour cream, chives, tarragon, garlic, mustard, oil, sugar, salt and pepper in a bowl. Zest lemons over bowl. Juice 1 lemon into bowl.'),
('5936', '2', 'Whisk until smooth.'),
('5936', '3', 'Add shrimp, broccoli, arugula and noodles. Toss to coat and serve with remaining lemon, cut into wedges, if desired.'),
('5936', '4', 'Place yogurt, sour cream, chives, tarragon, garlic, mustard, oil, sugar, salt and pepper in a bowl. Zest lemons over bowl. Juice 1 lemon into bowl.'),
('5936', '5', 'Whisk until smooth.'),
('5936', '6', 'Add shrimp, broccoli, arugula and noodles. Toss to coat and serve with remaining lemon, cut into wedges, if desired.'),
('5937', '1', 'Preheat oven to 450 degrees Fahrenheit.Bring a large pot of salted water to a boil.'),
('5937', '2', 'Cut or break the tough bottoms of the asparagus spears.'),
('5937', '3', 'Spread out the asparagus in one layer on a cookie sheet lined with aluminum foil. Sprinkle olive oil, salt, and pepper evenly on top. Roast in oven for 15 minutes.Toss the cleaned and deveined shrimp in a bowl with salt, pepper, olive oil, and balsamic.'),
('5937', '4', 'Spread evenly in one layer on another cookie sheet lined with aluminum foil. Roast in oven for 8 minutes, until pink and cooked through.Cook the pasta until al dente. Reserve 1/2 cup of the cooking liquid before draining. Toss the pasta immediately with the butter, 1/4 cup of olive oil, lemon juice, and reserved pasta liquid.'),
('5937', '5', 'Add salt and pepper.As soon as the shrimp is cooked, fold into the pasta.'),
('5937', '6', 'Serve immediately alongside the asparagus.'),
('5939', '1', 'Heat the oil and butter in a shallow casserole.'),
('5939', '2', 'Add the shrimp and garlic and saut over high heat about 3 minutes.'),
('5939', '3', 'Add the lemon juice, sherry, paprika, chili pepper, salt, and pepper. Sprinkle with parsley and serve immediately, preferably in the cooking dish.'),
('5939', '4', 'var article'),
('5939', '5', 'Type_27_data = {}.'),
('5939', '6', 'article'),
('5939', '7', 'Type_27_data.init_step_by_step_images = 0.'),
('5940', '1', 'Heat the oil in a large skillet over medium-high heat. When it is very hot, add the curry powder. Cook, stirring, for 2 minutes.'),
('5940', '2', 'Add the onion, scallion, garlic, sweet pepper, Scotch bonnet pepper and black pepper. Cook, stirring constantly, for 3 minutes.'),
('5940', '3', 'Add the tomato sauce or paste and cook 3 minutes more.'),
('5940', '4', 'Add the water and blend well.'),
('5940', '5', 'Add the okra and shrimp. Reduce the heat to medium, cover and cook until the shrimp are just cooked through, about 5 minutes. It is best served hot, straight out of the pan.'),
('5940', '6', 'var article'),
('5940', '7', 'Type_27_data = {}.'),
('5940', '8', 'article'),
('5940', '9', 'Type_27_data.init_step_by_step_images = 0.'),
('5942', '1', 'Combine first 4 ingredients in a small bowl. set aside.'),
('5942', '2', 'Place a large nonstick skillet coated with cooking spray over medium heat until hot.'),
('5942', '3', 'Add shrimp and seasoning. saut 2 minutes.'),
('5942', '4', 'Add yogurt spread mixture, and cook 3 minutes or until shrimp are done. Spoon shrimp and liquid into individual serving bowls, and sprinkle with parsley.'),
('5944', '1', 'Prepare Gruy&egrave.re Grits. set aside, and keep warm.'),
('5944', '2', 'While grits are cooking, heat oil in a large skillet over medium heat. add bell pepper, onion, and garlic, and saut&eacute. 2 minutes to soften.'),
('5944', '3', 'Add sausage, and cook 6 to 7 minutes or until browned, stirring often.'),
('5944', '4', 'Add wine, and cook until almost all liquid has evaporated.'),
('5944', '5', 'Sprinkle flour over mixture in skillet, and cook 3 minutes, stirring constantly. (Flour will start to brown.) Gradually whisk in chicken broth and cream. add bay leaves and Creole seasoning.'),
('5944', '6', 'Bring mixture to a simmer, and cook, uncovered, 7 minutes or until thick, stirring often. ('),
('5944', '7', 'Mixture may be cooked to this point, and then covered and kept warm until serving time.)'),
('5944', '8', 'Just before serving, add shrimp to sauce, and cook 3 to 4 minutes or until shrimp turn pink, stirring often.'),
('5944', '9', 'Remove and discard bay leaves, and stir in parsley. Spoon shrimp and sauce over Gruy&egrave.re Grits, and serve immediately.'),
('5945', '1', 'Combine the first 3 ingredients in a shallow baking dish. toss to combine. Weigh or lightly spoon rice flour and all-purpose flour into dry measuring cups. level with a knife.'),
('5945', '2', 'Combine flours and baking soda in a large bowl, stirring with a whisk. Gradually add beer, stirring with a whisk until smooth.'),
('5945', '3', 'Heat a large skillet over medium-high heat.'),
('5945', '4', 'Add 3 tablespoons oil to pan. swirl to coat. Dip half of shrimp in batter. shake off excess. Dredge shrimp lightly in panko mixture.'),
('5945', '5', 'Place shrimp in a single layer in pan, and cook for 2 1/2 minutes on each side or until golden brown.'),
('5945', '6', 'Remove shrimp from pan. drain on paper towels. Repeat procedure with the remaining oil, shrimp, batter, and panko mixture.'),
('5946', '1', 'Combine first 7 ingredients in a large bowl. stir well with a whisk.'),
('5946', '2', 'Add shrimp. toss to coat.'),
('5946', '3', 'Place in an 8-inch square baking dish. Cover and marinate 4 hours.'),
('5946', '4', 'Microwave, uncovered, at HIGH 6 minutes or until shrimp are done, stirring after 3 minutes.'),
('5948', '1', 'Prepare Grits: Bring 7 cups water to a boil in a 4-qt. saucepan over medium-high heat. Slowly whisk in grits. reduce heat to medium, and cook, whisking constantly, 5 minutes. Cover, reduce heat to low, and cook, stirring occasionally, 1 hour or until tender. Fold in cheese and 1/4 cup butter.'),
('5948', '2', 'Prepare Shrimp Sauce: Peel shrimp. devein, if desired.'),
('5948', '3', 'Cook bacon in a large skillet over medium-high heat, stirring often, 4 to 5 minutes or until crisp. remove bacon, and drain on paper towels, reserving 2 Tbsp. drippings in skillet.'),
('5948', '4', 'Melt 6 Tbsp. butter in hot drippings in skillet. Reduce heat.'),
('5948', '5', 'Add onion, poblano pepper, and garlic. saut 2 minutes or until onion is translucent.'),
('5948', '6', 'Add shrimp. cook, stirring often, 1 to 2 minutes.'),
('5948', '7', 'Add salt and next 2 ingredients. toss to coat.'),
('5948', '8', 'Sprinkle flour over shrimp mixture. toss.'),
('5948', '9', 'Add broth and next 2 ingredients. Cook just until shrimp turn pink, stirring to loosen particles from skillet. Stir in bacon and parsley.'),
('5948', '10', 'Serve over grits with green onion.'),
('5949', '1', 'Stir bulgur, 1 1/2 cups water, 1/2 cup lemon juice, and 1/3 cup oil in large bowl.'),
('5949', '2', 'Let stand until bulgur is tender and most liquid is absorbed, about 2 hours.'),
('5949', '3', 'Meanwhile, whisk together remaining 2 tablespoons lemon juice, 2 tablespoons oil, 3 tablespoons mint, and 1/2 teaspoon salt in medium bowl.'),
('5949', '4', 'Mix in shrimp. Marinate 30 minutes, stirring occasionally.'),
('5949', '5', 'Drain off any excess liquid from bulgur.'),
('5949', '6', 'Mix in tomatoes, arugula, feta, green onions, garlic, remaining 3 tablespoons mint, and 1 1/2 teaspoons salt. Season salad to taste with pepper.'),
('5949', '7', 'Mound salad in large shallow bowl or on individual plates. Spoon shrimp and dressing over and serve.'),
('5949', '8', '*Also called cracked wheat. available at supermarkets, specialty foods stores, and natural foods stores.'),
('5950', '1', 'Soak wooden skewers in water 30 minutes.'),
('5950', '2', 'If frozen, thaw shrimp according to package directions. Peel shrimp, leaving tails on. devein, if desired.'),
('5950', '3', 'Place shrimp in a medium bowl.'),
('5950', '4', 'Stir together chili with lime seasoning, ground mustard, and garlic powder in a small bowl. Sprinkle mixture over shrimp, tossing to coat.'),
('5950', '5', 'Grate rind from 1 lime, and add to shrimp mixture in bowl.'),
('5950', '6', 'Cut lime in half, and squeeze juice into bowl. Stir in olive oil. Thread 4 to 5 shrimp onto each skewer, and place skewers on a plate. Cover and chill.'),
('5950', '7', 'Preheat grill to 300 to 350 (medium).'),
('5950', '8', 'Prepare Seasoned White Beans and Rice.'),
('5950', '9', 'Meanwhile, grill shrimp skewers, covered with grill lid, over 300 to 350 (medium) heat 3 to 4 minutes on each side or just until shrimp turn pink. Spoon Seasoned White Beans and Rice onto a serving platter, and top with shrimp skewers.'),
('5950', '10', 'Garnish, if desired.'),
('5950', '11', 'Note: For testing purposes only, we used McCormick Chili With Lime Seasoning.'),
('5951', '1', '1 In a blender, puree the first 8 ingredients until they form a paste.'),
('5951', '2', '2 In a large bowl, toss your protein with the marinade. Chill for at least 4 hours or overnight.'),
('5951', '3', '3 When ready to cook, heat the grill and shake any excess marinade from the protein. Grill 9 minutes for chops, 6 to 8 minutes a side on a covered grill for chicken, or 4 minutes a side for shrimp.'),
('5951', '4', 'Serve.'),
('5952', '1', 'Snip shells of shrimp with scissors down middle of back, leaving tail and first segment of shell intact. Make an incision along length of back where shells are cut and devein, leaving shells in place. (Shells will prevent shrimp from becoming tough on outside when grilled.) Toss shrimp with oil, garlic, and 1/2 teaspoon salt and marinate at cool room temperature 15 minutes.'),
('5952', '2', 'While shrimp marinate, prepare grill for cooking. If using a charcoal grill, open vents on bottom of grill, then light charcoal. Charcoal fire is medium-hot when you can hold your hand 5 inches above rack for 3 to 4 seconds. If using a gas grill, preheat burners on high, covered, 10 minutes, then reduce heat to moderately high.'),
('5952', '3', 'Heat butter, chili powder, pepper, Worcestershire sauce, and remaining 1/4 teaspoon salt in a small heavy saucepan over moderately low heat, stirring, until butter is melted, then remove from heat and stir in lemon juice.'),
('5952', '4', 'Thread 4 or 5 shrimp onto each skewer and grill, covered only if using a gas grill, turning over once, until just cooked through, 3 to 4 minutes total. Push shrimp off skewers into a bowl, then pour butter mixture over them and toss to combine well.'),
('5953', '1', 'Rinse the shrimp under cold running water, then blot them dry with paper  towels.'),
('5953', '2', 'Place the chile powder, garlic salt, coriander, oregano, cumin, and pepper in a mixing bowl and whisk to mix.'),
('5953', '3', 'Add the shrimp and toss to coat. Stir in the olive oil.'),
('5953', '4', 'Let the shrimp marinate in the refrigerator, covered, for 30 minutes to 1 hour.'),
('5953', '5', 'Cook the shrimp, following the instructions below for any of the grills, until just cooked through. When done the shrimp will turn pinkish white and will feel firm to the touch.'),
('5953', '6', 'Spoon the Avocado and Corn Salsa into 4 large martini glasses or serving bowls. Drape 4 of the hot shrimp over the edge of each glass or bowl and serve at once. Or for a cold shrimp cocktail, let the cooked shrimp cool to room temperature. Refrigerate the shrimp, covered, until they are chilled before serving them with the salsa. The cooked shrimp can be refrigerated for up to 2 days.'),
('5954', '1', 'To prepare shrimp, combine first 3 ingredients in a large zip-top plastic bag.'),
('5954', '2', 'Add shrimp to bag. seal. Marinate in refrigerator for 2 hours, turning bag occasionally.'),
('5954', '3', 'Prepare grill to medium-high heat.'),
('5954', '4', 'Remove shrimp from bag. Sprinkle shrimp with 1/4 teaspoon salt.'),
('5954', '5', 'Place shrimp on grill rack coated with cooking spray. grill 3 minutes on each side or until shrimp are done.'),
('5954', '6', 'Drizzle 2 tablespoons juice over shrimp. keep warm.'),
('5954', '7', 'To prepare chutney, combine onion and remaining ingredients except the cilantro sprigs in a food processor. process until smooth.'),
('5954', '8', 'Serve with shrimp.'),
('5954', '9', 'Garnish with cilantro sprigs, if desired.'),
('5955', '1', 'If using bamboo skewers, soak skewers in water at least 30 minutes. Prepare outdoor grill for direct grilling on medium-high.In blender, puree cilantro, sour cream, mayonnaise, 2 tablespoons lemon juice, vinegar, 1/4 teaspoon salt, and 1/2 teaspoon freshly ground black pepper. set dressing aside.In large bowl, combine shrimp, oil, coriander, remaining 2 tablespoons lemon juice, 1/8 teaspoon salt, and 1/4 teaspoon freshly ground black pepper, tossing until well coated.Thread shrimp, 1/2 inch apart, on skewers. Grill 3 to 4 minutes or until shrimp just turn opaque, turning over once.'),
('5955', '2', 'Transfer to plate.In another large bowl, toss lettuce with half of dressing until well coated. Divide among 4 serving plates. In same bowl, toss tomatoes and apple with half of remaining dressing until well coated. place on lettuce with shrimp.'),
('5955', '3', 'Drizzle with remaining dressing.'),
('5956', '1', 'Heat grill. Fold four 18-inch-long pieces of foil in half. unfold and coat inside with cooking spray.'),
('5956', '2', 'Place 2 cups spinach in center of 1 half of each piece of foil.'),
('5956', '3', 'Combine couscous with 1/4 cup water. divide evenly among packets, placing on top of spinach.'),
('5956', '4', 'Combine shrimp, 1/4 cup cilantro, oil and 1/2 tsp salt in a bowl. Divide shrimp evenly among packets, placing next to couscous. Fold foil to close and crimp edges to seal. place on grill. close lid. cook until packets are fully puffed, 10 minutes.'),
('5956', '5', 'Combine remaining 1/4 cup cilantro with remaining 1/4 tsp salt, mango, avocado, tomato, onion, jalapeo and lime juice in a bowl. Carefully cut foil to open. stir contents. garnish with salsa before serving.'),
('5956', '6', 'Heat grill. Fold four 18-inch-long pieces of foil in half. unfold and coat inside with cooking spray.'),
('5956', '7', 'Place 2 cups spinach in center of 1 half of each piece of foil.'),
('5956', '8', 'Combine couscous with 1/4 cup water. divide evenly among packets, placing on top of spinach.'),
('5956', '9', 'Combine shrimp, 1/4 cup cilantro, oil and 1/2 tsp salt in a bowl. Divide shrimp evenly among packets, placing next to couscous. Fold foil to close and crimp edges to seal. place on grill. close lid. cook until packets are fully puffed, 10 minutes.'),
('5956', '10', 'Combine remaining 1/4 cup cilantro with remaining 1/4 tsp salt, mango, avocado, tomato, onion, jalapeo and lime juice in a bowl. Carefully cut foil to open. stir contents. garnish with salsa before serving.'),
('5958', '1', 'Heat oil in a medium saute pan over high heat. Saute garlic until browned, about 2 minutes.'),
('5958', '2', 'Add shrimp and chiles. saute until shrimp are cooked through, about 4 minutes.'),
('5958', '3', 'Add brandy and cook 1 minute more.'),
('5958', '4', 'Remove from heat.'),
('5958', '5', 'Transfer to a platter or divide equally among 8 small plates. Sprinkle with parsley, add salt to taste and serve.'),
('5959', '1', 'In a medium bowl, stir together garlic and ginger.'),
('5959', '2', 'Transfer half of the mixture to a large bowl and stir in 2 tablespoons oil.'),
('5959', '3', 'Add the shrimp, toss until evenly coated, and then cover and refrigerate for 30 minutes. Cover remaining garlic-ginger mixture and refrigerate.'),
('5961', '1', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('5961', '2', 'Add 1/2 cup onions. coat onions with cooking spray. Cook 1 minute, stirring occasionally.'),
('5961', '3', 'Add shrimp and chili powder. cook 4 minutes or until desired degree of doneness, stirring occasionally.'),
('5961', '4', 'Remove from heat.'),
('5961', '5', 'Add lime juice, butter, and salt, and stir until butter melts. Sprinkle with 1/4 cup onions.'),
('5962', '1', 'Spread salt in 13x9x2-inch baking dish.Arrange shrimp in single layer atop salt.'),
('5962', '2', 'Preheat oven to 500F. Boil wine,lemon juice, and garlic in saucepan overmedium-high heat until liquid is reducedto 1 tablespoon, about 10 minutes.'),
('5962', '3', 'Removefrom heat.'),
('5962', '4', 'Add a few pieces of butter.whisk until creamy. Return pan to lowheat.'),
('5962', '5', 'Add a few more pieces of butter.whisk until smooth (do not let mixture boil).Continue whisking in butter, a few piecesat a time. Stir in parsley. season with saltand pepper.'),
('5962', '6', 'Let stand while shrimp cook.'),
('5962', '7', 'Roast shrimp on salt until just opaquein center and shells are pink, 6 to 7 minutes.'),
('5962', '8', 'Transfer sauce to bowl. nestle in salt.'),
('5963', '1', 'Blend cream cheese, grape leaves, and lemon juice in mini processor until grape leaves are minced and mixture is blended. Season spread to taste with salt and pepper. Can be made 1 day ahead.'),
('5963', '2', 'Transfer spread to small bowl. Cover and refrigerate. Bring spread to room temperature before using.'),
('5964', '1', 'Preheat oven to 400F. Line a baking sheet (with sides) with parchment paper. Finely grate the zest of 1 orange. set aside. Using a sharp knife, peel both oranges, removing all the bitter white pith. Thinly slice the oranges crosswise, then cut the slices into quarters.'),
('5964', '2', 'Spread the orange slices on the prepared baking sheet and sprinkle with 1/4 teaspoon salt. Roast until the oranges are slightly dry, about 12 minutes.Meanwhile, toss shrimp with oil, curry powder, pepper, the orange zest and the remaining 1/4 teaspoon salt in a large bowl.'),
('5964', '3', 'Transfer the shrimp to the baking sheet with the oranges and roast until pink and curled, about 6 minutes. Divide the oranges and the shrimp among 4 plates and serve.'),
('5965', '1', 'Mix remaining ingredients in a bowl. Grill shrimp until cooked through, about 3 minutes per side.'),
('5965', '2', 'Serve with dipping sauce on the side.'),
('5965', '3', 'Mix remaining ingredients in a bowl. Grill shrimp until cooked through, about 3 minutes per side.'),
('5965', '4', 'Serve with dipping sauce on the side.'),
('5966', '1', 'Peel shrimp, and devein, if desired. set aside.'),
('5966', '2', 'Combine cornstarch and salt in a large zip-top plastic bag.'),
('5966', '3', 'Whisk together egg whites and peppers in a shallow dish.'),
('5966', '4', 'Combine cornmeal and cumin in a shallow dish.'),
('5966', '5', 'Place shrimp in bag with cornstarch mixture. shake to coat well. Dip in egg white mixture, and roll in cornmeal mixture. Fry shrimp, in batches, in 2 inches hot oil (35'),
('5966', '6', 'until golden.'),
('5966', '7', 'Serve with Red Pepper-Chipotle Dipping Sauce, and garnish, if desired.'),
('5968', '1', 'Cook the noodles:    Bring a medium potful of water to a rolling boil.'),
('5968', '2', 'Add the rice vermicelli and, stirring often, cook them until the strands are soft and white, but still resilient, 3 to 5 minutes. Don''t be tempted to undercook them, as they must be fully cooked to absorb the flavors of the dish. Rinse them in a colander under cold water just until they''re cool and the water runs clear.'),
('5968', '3', 'Let the noodles drain in the colander for 30 minutes, and then set them aside for up to 2 hours, unrefrigerated.    Cook the shrimp:    In a large skillet, heat the oil over high heat.'),
('5968', '4', 'Add the shallots and garlic, quickly stirring until fragrant, about 30 seconds.'),
('5968', '5', 'Add the shrimp and lemongrass. stir-fry for about 2 minutes.'),
('5968', '6', 'Add the mushrooms and sprinkle with the fish sauce, sugar, and a little salt. Stir-fry until the shrimp is cooked and the mushrooms are wilted, another 2 to 3 minutes.'),
('5968', '7', 'Remove from the heat.    Assemble the salads:    Divide the lettuce, bean sprouts, cucumber, mint, and basil among four large soup or pasta bowls. Fluff the noodles with your fingers and divide them among the prepared salad bowls.'),
('5968', '8', 'Put the shrimp topping on the noodles and garnish each bowl with the peanuts and cilantro. Pass the nuoc cham at the table. each diner should drizzle about 3 Tbs. over the salad and then toss the salad in the bowl a few times with two forks or chopsticks before eating.'),
('5968', '9', 'Photo: Ben Fink'),
('5968', '10', 'Rate this Recipe and View Reviews'),
('5969', '1', 'Preheat oven to 375F with rack in middle.'),
('5969', '2', 'Cook onion and garlic in oil with 1/4 teaspoon salt in a 4-quart heavy saucepan over medium heat until softened, about 5 minutes. Stir in spices and cook, stirring, 30 seconds.'),
('5969', '3', 'Add chopped tomatoes with juice and sugar and simmer, uncovered, stirring occasionally, until slightly thickened, about 20 minutes.'),
('5969', '4', 'Remove from heat.'),
('5969', '5', 'Season shrimp with 1/8 teaspoon salt, then stir into tomato sauce.'),
('5969', '6', 'Transfer to a 2-quart shallow baking dish and top with feta.'),
('5969', '7', 'Bake until just cooked through, 18 to 20 minutes.'),
('5969', '8', 'Serve sprinkled with dill.'),
('5969', '9', 'Nutrition Data'),
('5969', '10', 'See Nutrition Data''s complete analysis of this recipe '),
('5972', '1', 'Watch how to make this recipe.'),
('5972', '2', 'Preheat the oven to 400 degrees.'),
('5972', '3', 'Heat 2 tablespoons of the olive oil in a 10-or 12-inch heavy ovenproof skillet over medium-low heat.'),
('5972', '4', 'Add the fennel and saute for 8 to 10 minutes, until the fennel is tender.'),
('5972', '5', 'Add the garlic and cook for 1 minute.'),
('5972', '6', 'Add the wine and bring to a boil, scraping up any browned bits. Cook for 2 to 3 minutes, until the liquid is reduced by half.'),
('5972', '7', 'Add the tomatoes with the liquid, tomato paste, oregano, Pernod, salt, and pepper to the skillet. Simmer over medium-low heat, stirring occasionally, for 10 to 15 minutes.'),
('5972', '8', 'Arrange the shrimp, tails up, in one layer over the tomato-mixture in the skillet. Scatter the feta evenly over the shrimp. In a small bowl, combine the bread crumbs, parsley, and lemon zest with the remaining 2 tablespoons of olive oil and sprinkle over the shrimp.'),
('5972', '9', 'Bake for 15 minutes, until the shrimp are cooked and the bread crumbs are golden brown. Squeeze the juice of 1 lemon over the shrimp.'),
('5972', '10', 'Serve hot with the remaining lemon cut into wedges.'),
('5973', '1', 'For raita'),
('5973', '2', 'In a bowl, combine all raita ingredients and set aside.For shrimp'),
('5973', '3', 'Heat olive and sesame oils in a medium saucepan over high heat.'),
('5973', '4', 'Saute ginger and garlic about 45 seconds.'),
('5973', '5', 'Add shrimp and chile paste, tossing to cook evenly, about 3 minutes.'),
('5973', '6', 'Add lemon juice and stir.'),
('5973', '7', 'Serve raita with shrimp. garnish with chives.Red Mountain Spa, St. George, UTIn a bowl, combine all raita ingredients and set aside.'),
('5973', '8', 'Heat olive and sesame oils in a medium saucepan over high heat.'),
('5973', '9', 'Saute ginger and garlic about 45 seconds.'),
('5973', '10', 'Add shrimp and chile paste, tossing to cook evenly, about 3 minutes.'),
('5973', '11', 'Add lemon juice and stir.'),
('5973', '12', 'Serve raita with shrimp. garnish with chives.Red Mountain Spa, St. George, UT'),
('5975', '1', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('5975', '2', 'Add thyme, capers, and garlic. saut 1 minute.'),
('5975', '3', 'Add shrimp and lemon juice. saut 4 minutes or until shrimp are done.'),
('5975', '4', 'Microwave rice according to package directions.'),
('5975', '5', 'Serve shrimp mixture over rice.'),
('5975', '6', 'Serve with: Greek-Style Green Beans'),
('5976', '1', 'Combine everything in a bowl and let marinate in the refrigerator for 20 minutes or up to 1 hour.'),
('5976', '2', 'Drain and blot shrimp dry before grilling over medium high heat just until barely cooked through, one to two minutes per side.'),
('5976', '3', 'Serve hot or refrigerate until ready to serve.'),
('5980', '1', 'Place first 3 ingredients in a blender. process until smooth.'),
('5980', '2', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray. add shrimp. Coat shrimp with cooking spray. sprinkle with cumin and salt. Saut 4 minutes or until shrimp are done, stirring frequently.'),
('5980', '3', 'Transfer shrimp to a serving platter. Reduce heat to medium, add half-and-half mixture to pan, and cook 1 minute, stirring constantly.'),
('5980', '4', 'Pour sauce over shrimp. sprinkle with cilantro.'),
('5980', '5', 'Serve over linguine, if desired.'),
('5981', '1', 'Using a sharp knife, peel the oranges, removing all of the bitter white pith. Working over a strainer set over a medium bowl, cut between the membranes to release the orange sections into the strainer. Squeeze the juice from the membranes into the bowl through the strainer.'),
('5981', '2', 'Whisk 1 teaspoon of the hot sauce into the strained juice with 1 tablespoon of the oil and the mint. Season with salt and pepper. add the shrimp and toss.'),
('5981', '3', 'In another bowl, combine the lime juice with the remaining 1/4 cup of oil and 1 teaspoon of hot sauce.'),
('5981', '4', 'Add the tomatoes, onion, cilantro and oregano and the orange sections. Season lightly with salt.'),
('5981', '5', 'Light a grill or heat a grill pan. Grill the shrimp over high heat for about 4 minutes, turning once or twice until lightly charred and cooked through.'),
('5981', '6', 'Transfer the shrimp to plates. Gently fold the avocados into the orange salad and serve alongside the shrimp.'),
('5982', '1', 'In a mini food processor, blend the egg white, salt, wine, and cornstarch until thick and smooth, about 2 minute. Or mix the ingredients by hand, smoothing lumps with your fingers and beating with a fork to thicken slightly.    With your hands, toss the chicken or fish with the marinade to evenly coat and separate the pieces. Cover with plastic and refrigerate for 30 minutes or overnight.    In a wok or stir-fry pan, bring the water to a steaming, near simmer, or bring the oil to the slow-fry stage, 275F on a deep-fry thermometer. Next to the stove, set a plate big enough to hold the fish or chicken in a single layer. Have a large Chinese mesh skimmer at hand.    Toss the chicken or fish once more and slide it into the hot water or oil, leaving any excess marinade behind. Stir gently with chopsticks to separate the pieces. Watch carefully to see when the outside turns 95% white, 5 to 10 seconds for shreds or tiny cubes, 30 to 45 seconds for larger nuggets. Scoop out the food promptly with the mesh spoon and quickly spread it on the plate.'),
('5982', '2', 'Rate this Recipe and View Reviews'),
('5984', '1', 'Bring the water to a boil and stir in the sugar.When the sugar water turns golden add the walnuts and boil for 2 minutes.Strain the walnuts and set them on parchment paper to cool.'),
('5984', '2', 'Heat the oil in a pan.Dip the shrimp into the egg and then into the corn starch.Fry the shrimp in the oil until golden brown'),
('5984', '3', 'Mix the mayonnaise, honey, sweetened condensed milk and lemon juice in a bowl.'),
('5984', '4', 'Add the shrimp and toss to coat.'),
('5984', '5', 'Serve the shrimp garnished with the walnuts.'),
('5985', '1', 'Heat the oil in a pan.'),
('5985', '2', 'Add the shallots and saute until tender, about 3-5 minutes.'),
('5985', '3', 'Add the garlic, jalapeo and cumin and saute until fragrant, about 1 minute.'),
('5985', '4', 'Add the shrimp, tequila and cook until the shrimp are pink, about 1-3 minutes per side.'),
('5985', '5', 'Remove the shrimp and set aside.Simmer the sauce to reduce to the desired amount.'),
('5985', '6', 'Remove from the heat and add the shrimp, lime juice, cilantro and salt and pepper.'),
('5986', '1', 'Heat the oil in a pan.'),
('5986', '2', 'Add the shrimp and saute until cooked, about 2-3 minutes per side and set aside.'),
('5986', '3', 'Add the garlic and ginger and saute until fragrant, about a minute.'),
('5986', '4', 'Add the orange juice, orange zest, soy sauce, rice wine, honey and chili sauce, deglaze the pan and simmer to reduce to a sauce like consistency.'),
('5986', '5', 'Remove from heat and mix in the shrimp and cilantro.'),
('5987', '1', 'Marinate the shrimp in the sweet chili sauce, lemon juice, lemon zest, kaffir lime leaves, chili sauce, fish sauce, garlic and sugar for 10 or more minutes.'),
('5987', '2', 'Heat a pan over medium heat.'),
('5987', '3', 'Add the shrimp along with the marinade and the coconut milk and simmer until the shrimp are cooked, about 2-3 minutes.'),
('5987', '4', 'Remove from heat and mix in the cilantro.'),
('5988', '1', 'Heat your gas grill at high heat.Skewer the shrimp on metal or wooden skewers (be sure to soak wooden skewers in water ahead of time).'),
('5988', '2', 'Drizzle olive oil on both sides of the shrimp. Salt and pepper generously.'),
('5988', '3', 'Place the shrimp on the grill for 1-2 minutes on each side.'),
('5988', '4', 'Add the lemon to the grill as well.Take the shrimp and lemon off the grill and squeeze the lemon over the shrimp before serving.'),
('5991', '1', 'Heat the broiler or prepare a grill fire. In a large bowl, combine the coriander, mint, curry powder, garlic, ginger, peppercorns, and salt. Toss the shrimp with the rub and then thread them onto skewers. Broil or grill until just opaque and cooked through, 5 to 6 minutes, turning once.'),
('5993', '1', 'Mix the Kung Pao sauce ingredients and set aside.'),
('5993', '2', 'Heat up a wok and add the cooking oil until the oil is very hot.'),
('5993', '3', 'Add the ginger and do a few quick stirs.'),
('5993', '4', 'Addthe onion,green pepper, and dried red chilies. Stir-fry until you smell the spicy aromas from the dried red chilies.'),
('5993', '5', 'Add in the shrimp and roasted peanuts and keep stirring.When the shrimp are almost cooked, add the Kung Pao sauce into the wok, keep stirring until the sauce thickens.'),
('5993', '6', 'Add the chopped scallions, do a few quick stirs, dish out and serve hot.'),
('5994', '1', 'Whisk together the vinegar, sugar, and salt.'),
('5994', '2', 'Place the cucumber, red pepper, and lemon zest in a medium mixing bowl.'),
('5994', '3', 'Pour the dressing over the vegetables. Toss gently to coat. Chill the vegetables and let stand for 1 hour before serving.'),
('5994', '4', 'For the puree: In a sauce pot, combine the vinegar, sugar, ginger, and lemon juice. Simmer the mixture over medium-low heat until big bubbles start to form and it becomes a light syrup. Reduce until thickened.'),
('5994', '5', 'Remove the pot from the heat.'),
('5994', '6', 'Meanwhile, in a large pot, combine the parsnips, potatoes, and chicken stock, and bring to a boil. Cook until both the parsnips and potatoes are fork tender.'),
('5994', '7', 'Drain the parsnips and potatoes, and mash with the heavy cream, butter, and ginger syrup until smooth. Season the parsnip-potato mash with salt, to taste.'),
('5994', '8', 'Heat a large saute pan over medium-high heat and add the olive oil, garlic, and shrimp. Cook the shrimp for about 3 minutes, or until cooked through. On a warmed serving platter, make a bed of parsnip puree, top with the shrimp, then top the shrimp with the pickled vegetables and some of the juice.'),
('5997', '1', 'If using regular yogurt, place it in a strainer lined with paper towel and set the strainer over a bowl.'),
('5997', '2', 'Let the yogurt drain and thicken for 20 minutes.In a bowl, stir together the thickened or Greek-style yogurt, mayonnaise, celery, scallion and lemon juice. Fold in the lobster meat and season, to taste, with salt and pepper. Chill until ready to use. Just before serving, open the hot dog buns and brush the inside with olive oil.'),
('5997', '3', 'Heat a grill pan over moderately high heat and grill the bread, cut side down, until toasted, about 3 minutes. Fill each with 3/4 cup of the lobster mixture and serve immediately.'),
('6000', '1', 'Whisk tamarind concentrate into lime juice in a small bowl until dissolved. Stir in remaining sauce ingredients and chill, covered.'),
('6001', '1', 'In a blender, puree the 1/3 cup of basil leaves with the olive oil until smooth. Season the oil with salt and black pepper.'),
('6001', '2', 'Light a grill or preheat a grill pan. In a small bowl, mix the sweet smoked paprika with the pure ancho chile powder, light brown sugar, cumin, coriander, cayenne pepper, 1/2 teaspoon of salt and 1/4 teaspoon of black pepper.'),
('6001', '3', 'Brush the shrimp with the canola oil and season all over with the spice mixture. Grill the shrimp over moderately high heat, turning once, until they are lightly charred and cooked through, about 4 minutes total.'),
('6001', '4', 'Arrange the tomato and onion slices on a platter and drizzle with the basil oil. Top with the shrimp, garnish with the remaining basil leaves and serve.'),
('6002', '1', 'In a medium bowl, combine the orange juice with the garlic, adobo sauce and 1 tablespoon of the lime juice.'),
('6002', '2', 'Add the shrimp, season with salt and pepper. let sit at room temperature for 10 minutes.'),
('6002', '3', 'Preheat a grill pan. Thread the onion slices on skewers to hold them together.'),
('6002', '4', 'Brush the onions with some of the olive oil and season with salt and pepper. Grill the slices over high heat, turning once, until softened and charred, about 3 minutes per side.'),
('6002', '5', 'Let cool slightly, then coarsely chop the onions and transfer them to a medium bowl.'),
('6002', '6', 'Add the sliced oranges, chipotles, cilantro and the remaining 1 tablespoon lime juice. Season with salt and pepper.'),
('6002', '7', 'Drain and thread the shrimp onto 6 metal skewers.'),
('6002', '8', 'Brush lightly with the remaining olive oil and grill over moderately high heat, turning occasionally, until charred in spots, about 5 minutes.'),
('6002', '9', 'Serve the shrimp with the onion and orange salad.'),
('6004', '1', 'Stir rice vinegar, olive oil, lemon juice, lemon slices, onion slices, garlic cloves, bay leaves, celery seeds, mustard seeds, coarse kosher salt, and black pepper in large bowl until salt dissolves. DO AHEAD: Can be made 1 day ahead. Cover and chill.'),
('6006', '1', 'Stir together ingredients, 1/8 teaspoon salt, and 1/4 teaspoon pepper.'),
('6007', '1', 'Bring first 4 ingredients to a boil in a medium saucepan. gradually whisk in grits. Reduce heat, and simmer, stirring occasionally, 10 minutes or until thickened.'),
('6007', '2', 'Add Cheddar cheese and next 4 ingredients. Keep warm.'),
('6007', '3', 'Cook bacon in a large skillet until crisp. remove bacon, and drain on paper towels, reserving 1 tablespoon drippings in skillet. Crumble bacon, and set aside.'),
('6007', '4', 'Sprinkle shrimp with pepper and salt. dredge in flour.'),
('6007', '5', 'Saut mushrooms in hot drippings in skillet 5 minutes or until tender.'),
('6007', '6', 'Add green onions, and saut 2 minutes.'),
('6007', '7', 'Add shrimp and garlic, and saut 2 minutes or until shrimp are lightly brown. Stir in chicken broth, lemon juice, and hot sauce, and cook 2 more minutes, stirring to loosen particles from bottom of skillet.'),
('6007', '8', 'Serve shrimp mixture over hot cheese grits. Top with crumbled bacon. serve with lemon wedges.'),
('6008', '1', 'Marinate the shrimp in the orange juice and zest, chipotles, oil and cilantro for 15+ minutes.'),
('6008', '2', 'Remove the shrimp from the marinade and season with salt and pepper.Skewer the shrimp and grill or fry in a pan for 1-3 minutes per side.'),
('6009', '1', 'Inspiration can come from a variety of sources. It can strike when I''m browsing the Farmers Market, or flipping through a cooking magazine, or falling asleep at night, dreaming of the things I want to eat the next day. It''s an elusive and wonderful thing, inspiration, and when it strikes, you have to seize on it.The September 2010 issue of "Food & Wine" magazine takes on Southern cooking in a modern and delightful way. I''ve been whipping up several recipes inspired by their articles, including this one for Smoky Shrimp with Grits.Last weekend, bored with the same old lunch, I made this shrimp dish, a warm hearty meal, perfect for the start of football season (Kuzak is a massive UMich fan). I always keep raw, frozen shrimp in my freezer. Lately, I''ve been enjoying pink Gulf Coast shrimp (while I can). The shrimp is sauteed with garlic and smoked paprika, which turns into a lovely red-tinged sauce when reduced with wine, and served over grits with roasted heirloom cherry tomatoes and goat cheese. I served it with a plate of lovely mixed greens.This dish would be great for lunch or dinner (it cooks up in a jiffy), and pairs best with a rich California Chardonnay. Enjoy!Smoky Shrimp and Grits with Roasted Cherry Tomatoes and Goat Cheese'),
('6009', '2', 'Adapted from "Food & Wine" Sept. 2010'),
('6009', '3', 'Serves 4 people'),
('6009', '4', 'Cooking time: 30 minutes'),
('6009', '5', 'Print Recipe Ingredients1 lb medium shrimp, shelled and deveined 1/2 teaspoon smoked paprika (pimenton)2 large garlic cloves, peeled and thinly sliced1/4 cup dry white wine2 tablespoons olive oilsalt & peppergrits:3/4 cup quick-cooking gritssalt & pepper2 cups cherry tomatoes, halved1 tablespoons olive oil1/4 cup fresh goat cheese (chevre)Directions'),
('6009', '6', 'Preheat oven to 425 degrees.'),
('6009', '7', 'Place the cherry tomatoes in a roasting pan.'),
('6009', '8', 'Drizzle with the olive oil and sprinkle with salt and pepper. Roast in the oven until soft and bubbling (about 20 minutes).'),
('6009', '9', 'Remove and set aside.Meanwhile, to make the grits, in a medium saucepan, bring 3 cups of water to a boil. Gradually add the grits and add a generous pinch of salt. Cover and cook over low heat, stirring occasionally, until the grits are thick and porridge-like (about 7 minutes). Stir in the roasted cherry tomatoes and goat cheese. Season to taste with salt and pepper. Cover the grits and keep them warm.In a large skillet, heat the olive oil with the garlic over high heat until fragrant (about 30 seconds).'),
('6009', '10', 'Add the shrimp and paprika, season with salt and pepper and cook until the shrimp are opaque (about 2 minutes).'),
('6009', '11', 'Add the white wine and cook until the shrimp are white throughout and the garlic-paprika sauce is slightly reduced.Spoon the grits into bowls and top with the shrimp and sauce. Enjoy!Source for Ingredientsfrozen wild caught Gulf shrimp, smoked paprika, and organic grits from Whole Foodsorganic garlic and Soledad Farms goat cheese from Hollywood Farmers Marketorganic heirloom cherry tomatoes from Trader Joe''s');