INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('14820', '6', 'Add a little more oil to the pan, then pour in leeks.'),
('14820', '7', 'Saute leeks 5 minutes, until soft and translucent.'),
('14820', '8', 'Add 1 cup wine to the pan and nestle chicken breasts down into leeks. Reduce heat to simmer and cook chicken 5 to 7 minutes longer.'),
('14820', '9', 'To serve, remove chicken from pan and slice on an angle. Fan and arrange sliced chicken breasts over a bed of'),
('14820', '10', 'Sauteed leeks on each dinner plate or a warm serving platter.'),
('14820', '11', 'Serve with rice and salad.'),
('14820', '12', 'Pilaf: heat a medium saucepan or pot over moderate heat.'),
('14820', '13', 'Add oil and butter and shallots to the pan.'),
('14820', '14', 'Saute shallots 2 minutes, then add 1 1/2 cups rice. Lightly brown rice 3 to 5 minutes.'),
('14820', '15', 'Add wine and allow it to evaporate entirely, 1 to 2 minutes.'),
('14820', '16', 'Add thyme and chicken broth to the rice. Fill broth can half-again with water or, measure 1 cup water and add to pot. Bring liquid to a boil. Cover rice and reduce heat. Cook rice 20 minutes, until tender.'),
('14820', '17', 'Stir the zest of 1 lemon and parsley into rice.'),
('14820', '18', 'Transfer lemon rice to dinner plates or warm serving dish and garnish with toasted slivered almonds.'),
('14820', '19', 'Heat 3-inches of water in a deep skillet and heat to a boil.'),
('14820', '20', 'Add trimmed wax and green beans and julienne sliced yellow squash to the pot. Simmering vegetables in water for 2 minutes, add red peppers and simmer 1 minute longer. You want the vegetables to remain full of color and bite.'),
('14820', '21', 'Drain vegetables and cold-shock under running water in your colander.'),
('14820', '22', 'Place drained vegetables in a serving dish and combine with sliced scallions and shredded dark garden greens, such as spinach or arugula.'),
('14820', '23', 'Whisk together mustard, vinegar, and lemon juice.'),
('14820', '24', 'Add olive oil in a slow stream while whisking to get a nice emulsion of your dressing.'),
('14820', '25', 'Add herbs and pour dressing over the salad. Toss salad to combine flavors and coat your vegetables evenly.'),
('14821', '1', 'Squeeze the lime juice (from the now cooled lime) through the feed opening of a running blender. With the blender still running, add the vinegar, corn syrup, shallot and rosemary, 1 at a time, and pour the oil in a slow steady stream into the vinegar mixture very slowly to emulsify.'),
('14821', '2', 'Remove to a container and season with salt and pepper, to taste.'),
('14825', '1', 'In a pot filled with 2 inches of water, steam the broccoli or Broccolini until the stems are just tender, 4 to 5 minutes.'),
('14825', '2', 'Transfer to a platter.'),
('14825', '3', 'Discard the water.'),
('14825', '4', 'Add the butter, soy sauce, five-spice powder, and 2 teaspoons water and place over medium-low heat.'),
('14825', '5', 'Stir until the butter has melted.'),
('14825', '6', 'Drizzle the mixture over the vegetables, top with the nuts, and serve.'),
('14826', '1', 'Heat oil in wok over high heat until hot but not smoking, then stir-fry garlic until pale golden, 10 to 15 seconds.'),
('14826', '2', 'Add broccoli and stock and stir-fry 2 minutes.'),
('14826', '3', 'Add bean sauce, oyster sauce, and sugar and stir-fry until broccoli is crisp-tender, 4 to 5 minutes.'),
('14827', '1', 'Cut broccoli stems diagonally into 1-inch pieces and coarsely chop leaves. Cook stems in a large pot of boiling salted water until just tender, about4 minutes. Stir in leaves and cook 1 minute.'),
('14827', '2', 'Drain in a colander, then rinse under cold water to stop cooking. Do not squeeze out excess water.'),
('14828', '1', 'Save Recipe'),
('14828', '2', 'Print Recipe'),
('14828', '3', 'Chinese Broccoli Beef'),
('14828', '4', 'Ingredients1 lb beef top sirloin steak, boneless ribeye steak, or minute steak (see kosher meat note below)1 lb broccoli florets (about 2 lbs whole head broccoli, cut from the stalks into medium sized florets)1/4 tsp baking soda1/4 cup low sodium soy sauce or tamari sauce, divided1 tbsp dry sherry (or substitute 1 tbsp orange juice)2 tbsp orange juice3 tbsp cornstarch, divided1/2 tsp garlic powder'),
('14828', '5', 'Pinch of cayenne1/4 cup grapeseed or peanut oil, divided2 tbsp brown sugar1 tsp fresh minced ginger (or 1/2 tsp dried ginger spice)2 cups steamed brown rice or quinoa (optional)'),
('14828', '6', 'Total Time: 40 Minutes'),
('14828', '7', 'Servings: 4'),
('14828', '8', 'Kosher Key: Meat'),
('14843', '1', 'To make the sauce, in a saucepan, combine the coconut milk, peanut butter, green onion, lemongrass, garlic, lime juice, soy sauce, curry powder, coriander and cumin.'),
('14843', '2', 'Place over medium heat and cook, stirring constantly, until well blended.'),
('14843', '3', 'Transfer to a blender or food processor and puree until smooth, thinning with water if necessary.'),
('14843', '4', 'Pour into a bowl and stir in the chili paste. Set aside.To make the rolls, in a bowl, soak the noodles in hot water to cover for 15 minutes.'),
('14843', '5', 'Drain the noodles and cut into 2-inch lengths. Set aside.In a wok or large fry pan over medium heat, warm the peanut oil.'),
('14843', '6', 'Add the garlic and cook, stirring, until lightly golden, about 2 minutes.'),
('14843', '7', 'Add the sesame oil, broccoli and carrot and toss and stir until softened, 4 to 5 minutes.'),
('14843', '8', 'Add the noodles and toss and stir until the noodles are hot, 2 to 3 minutes.'),
('14843', '9', 'Add the bean sprouts, toss to mix and soften, then set the filling aside to cool.Working with 1 rice paper round at a time, place the round on a work surface and brush liberally with water.'),
('14843', '10', 'Let stand for a minute or two until pliable.'),
('14843', '11', 'Transfer to a flat plate and place a heaping tablespoon of filling in the middle. Top with a few mint and cilantro leaves. Turn up two sides and roll into a cylinder. Repeat with the remaining rounds.Line a platter with lettuce leaves and arrange the rolls on top.'),
('14843', '12', 'Serve with the peanut sauce. Makes 24 rolls. serves 8.'),
('14844', '1', 'Bring a large pot of water to a boil.'),
('14844', '2', 'Add the noodles and cook for about 6 minutes.'),
('14844', '3', 'Drain and set aside.'),
('14844', '4', 'Meanwhile, whisk together the soy sauce, mushroom-flavored soy sauce, and brown sugar.  Set aside.'),
('14844', '5', 'Heat a wok or iron skillet over high heat.'),
('14844', '6', 'Add a tablespoon of the oil and toss in the Chinese broccoli.  Cook, stirring often, for a few minutes until the leaves are wilted and the stems are soft enough to eat.'),
('14844', '7', 'Transfer to a bowl.'),
('14844', '8', 'Pour in another tablespoon of oil and toss in the tofu.  Cook for two minutes, stirring constantly to keep the tofu from sticking.'),
('14844', '9', 'Transfer to the bowl with the broccoli.'),
('14851', '1', 'Stir together broth, rice wine, soy sauce, cornstarch, sugar, and salt in a small bowl until cornstarch is dissolved.'),
('14851', '2', 'Remove any bruised or withered outer leaves from gai lan, then trim and peel stalks, halving thick ones lengthwise.'),
('14851', '3', 'Cut crosswise into 2 1/2-inch pieces, separating leafy parts from thick stems.'),
('14851', '4', 'Cook stems in a 6- to 8-quart pot of boiling salted water, uncovered, until crisp-tender, about 3 minutes.'),
('14851', '5', 'Add leafy parts and cook until all of gai lan is just tender, 3 to 5 minutes.'),
('14851', '6', 'Drain well, then transfer to a clean kitchen towel and pat dry.'),
('14851', '7', 'Transfer to a large dish and keep warm, loosely covered with foil.'),
('14851', '8', 'Pat shrimp dry.'),
('14851', '9', 'Heat wok over high heat until a drop of water vaporizes instantly.'),
('14851', '10', 'Pour peanut oil around side of wok, then tilt wok to swirl oil, coating side. When oil just begins to smoke, add ginger and stir-fry 5 seconds.'),
('14851', '11', 'Add black beans, garlic, and jalapeo and stir-fry 1 minute. Working quickly, add shrimp, spreading in 1 layer on bottom and side of wok. Cook, undisturbed, 3 minutes, then stir-fry until shrimp are just pink on both sides, about 1 minute more. Stir broth mixture, then add to shrimp and bring to a boil. Boil, stirring, 2 minutes.'),
('14851', '12', 'Remove from heat and drizzle with sesame oil, then stir to combine.'),
('14851', '13', 'Pour shrimp and sauce over gai lan.'),
('14851', '14', 'Cooks'' note:Gai lan can be trimmed and cut 1 day ahead and chilled in sealed plastic bags lined with paper towels. Bring to room temperature before using.'),
('14853', '1', 'Combine the oyster sauce, cornstarch, chicken stock, rice wine, sugar, soy sauce, ginger, garlic and sesame oil in a small saucepan.Bring to a boil and cook until sauce thickens.Set aside.Wash the gai lan in cold water.Trim off and discard the tough bottoms.Peel stalks if they are thick and tough. leave gai lan whole or cut into thirds.Bring 1-3 quarts of water to a boil in a wok and add the soy and oil.'),
('14853', '2', 'Add the greens, bring back to a second boil with lid on.Turn off the heat and let greens steam for a minute or two.When the green stalks brighten, test one for doneness.It should be tender and crisp.'),
('14853', '3', 'Drain immediately and shake off excess water.'),
('14853', '4', 'Transfer to a platter, pour dressing over, and serve immediately.'),
('14854', '1', 'Combine sauces and oil and marinate beef in them for about 30 minutes.It should cover all of the beef.If not add more in even amounts.Meanwhile wash gai lan well and cut into three to four inch pieces.(Note: seems to taste better when leaves and stalks are attached) 5-A Boil a large pot of water 5-B When water boils drop pieces of gai lan into boiling water and remove when desired softness.(I like mine a little crispy)'),
('14854', '2', 'Heat a frying pan or wok over medium high heat.When pan is hot, saut garlic in about 1 tsp of oil until just lightly browned.Be careful-- this will sizzle a lot.When garlic is browned dump in the beef with marinade and saut until done.'),
('14854', '3', 'Serve over steamed rice, and Chinese broccoli.Use remaining sauce with rice and veggie.NOTE: This might be too salty for some. I suggest using a lite soy sauce instead of regular to reduce the salt content some.'),
('14856', '1', 'Heat the oil in a large wok or frying pan.Tip in the garlic and cook for a few seconds.Throw in the kale and toss around the pan to coat in the garlicky oil.'),
('14856', '2', 'Pour over boiling water and cook for 7 minutes more until the kale has wilted and is cooked through.Stir in the soy and oyster sauces and heat through to serve.'),
('14858', '1', 'Cut the broccoli stalks in half lengthwise if more than 1/2 inch in diameter.'),
('14858', '2', 'Cut the stalks and leaves into 2-inch-long pieces, keeping the stalk ends separate from the leaves. In a small bowl combine the broth, rice wine, ginger juice, cornstarch, salt, and sugar.'),
('14858', '3', 'Heat a 14-inch flat-bottomed wok over high heat until a bead of water vaporizes within 1 to 2 seconds of contact. Swirl in the oil, add the ginger, and stir-fry 10 seconds or until the ginger is fragrant.'),
('14858', '4', 'Add only the broccoli stalks and stir-fry 1 to 1-1/2 minutes until the stalks are bright green.'),
('14858', '5', 'Add the leaves and stir-fry 1 minute until the leaves are just limp. Stir the broth mixture and swirl it into the wok. Stir-fry 1 minute or until the sauce has thickened slightly and lightly coats the vegetables.Note: To make ginger juice, grate a small amount of ginger and then squeeze it with your fingers to extract the juice.'),
('14861', '1', 'Preheat oven to 400F. Wrap sweet potatoes individually in foil. Roast until tender, 1 to 1 1/2 hours. Cool and peel. Puree in processor until smooth. Measure 3 cups puree and transfer to microwave-safe bowl. Stir in mustard. Season with salt. DO AHEAD: Can be made 1 day ahead. Cover and chill. Boil vinegar in small saucepan until reduced to ` cup, about 8 minutes. Stir in soy sauce.'),
('14861', '2', 'Remove from heat.'),
('14861', '3', 'Cook broccoli in pot of boiling salted water until crisp-tender, about 1 minute.'),
('14861', '4', 'Drain. set aside. Cook bacon in medium skillet over medium heat until edges are crisp.'),
('14861', '5', 'Transfer to paper towels to drain. DO AHEAD: Reduction and broccoli can be made 2 hours ahead.'),
('14861', '6', 'Let stand at room temperature.'),
('14861', '7', 'Process mustard seeds in spice grinder until coarsely ground. Sprinkle fish with salt and pepper. Sprinkle ground seeds over top of fish.'),
('14861', '8', 'Heat 1 tablespoon oil in large skillet over medium-high heat.'),
('14861', '9', 'Add fish, mustard side down, and cook until brown and just opaque in center, about 3 minutes per side.'),
('14861', '10', 'Meanwhile, rewarm puree in microwave until heated through.'),
('14861', '11', 'Heat 1 tablespoon oil in another large skillet.'),
('14861', '12', 'Add broccoli and bacon. saute until heated through. Season with salt and pepper.'),
('14861', '13', 'Divide broccoli, fish, and puree among plates.'),
('14861', '14', 'Drizzle with balsamic reduction and serve.'),
('14861', '15', '*Chinese broccoli is also called gai lan or Chinese kale. it''s available at Asian markets. Broccoli rabe is an Italian leafy green vegetable with scattered clusters of broccoli-like florets. you''ll find it at some supermarkets and at specialty foods stores.'),
('14861', '16', 'Per serving: 517 calories, 21g fat (4g saturated) 42 mg cholesterol, 422 mg sodium, 35 mg carbohydrates, 6g fiber, 38g protein'),
('14861', '17', 'Nutrition Data'),
('14861', '18', 'See Nutrition Data''s complete analysis of this recipe '),
('14864', '1', 'Pound sliced meat strips with the back of the knife until tender. Set aside.'),
('14864', '2', 'Combine cornstarch and rice wine.'),
('14864', '3', 'Add meat to cornstarch and rice wine mixture and marinate for at least 30 minutes.'),
('14864', '4', 'Combine Kikkoman soy sauce and sugar. Set aside.In the meantime, cut the broccoli into small florets, cutting the small stems diagonally. discard the big stalk.'),
('14864', '5', 'Heat oil in a wok over medium flame.Stir fry marinated beef. keep stirring until it changes color, but only until it''s half done (half color).'),
('14864', '6', 'Add onions and the kikkoman with sugar mixture.'),
('14864', '7', 'Add the broccoli and oyster sauce. keep stirring for 5 minutes or until cooked. while adding also a pinch of baking soda to the broccoli.'),
('14864', '8', 'Add 1/4 cup water and stir fry for another minute.'),
('14864', '9', 'Serve warm.'),
('14877', '1', 'Heat grill to medium (350 to 450). In a large bowl, mix 1 tbsp. oil, the garlic, and 1/4 tsp. each salt and pepper.'),
('14877', '2', 'Add kale and toss to coat well. Dump onto grill, quickly arrange in a single layer, and grill, turning once, until streaked brown, 3 to 5 minutes. Set aside to crisp up, then slice into ribbons about 1/2 in. wide and 3 to 4 in. long.'),
('14877', '3', 'Brown pancetta in a medium saucepan over medium heat, about 4 minutes (if using speck, don''t cook). With a slotted spoon, transfer pancetta to paper towels.'),
('14877', '4', 'Add enough oil to fat in pan to make 2 tbsp.'),
('14877', '5', 'Add rice to pan, reduce heat to medium, and cook, stirring, until rice starts to toast slightly, 1 to 2 minutes.'),
('14877', '6', 'Add onion, 1/2 tsp. salt, and 1/4 tsp. pepper. cook until onion is softened, 2 to 3 minutes.'),
('14877', '7', 'Add enough broth to just cover rice. cook, stirring constantly, until liquid is absorbed. Continue adding broth to just cover rice and stirring until it''s barely tender, 15 to 18 minutes. If needed, add more broth so risotto is loose-textured. it will thicken a bit as it stands.'),
('14877', '8', 'Remove risotto from heat and loosely fold in pancetta, mascarpone, walnuts, butter, and tomatoes. Fold in most of kale and spoon into a serving dish. Top with remaining kale and serve immediately.'),
('14877', '9', '*You can buy speck on amazon.com'),
('14884', '1', 'In a very large soup pot, heat the olive oil.'),
('14884', '2', 'Add the garlic and cook over moderately high heat, stirring, just until fragrant, about 30 seconds.'),
('14884', '3', 'Add the chicken stock, then add the kale in large handfuls, letting it wilt slightly before adding more. Season with salt and pepper, cover and cook over moderate heat until the kale is tender, about 5 minutes.'),
('14884', '4', 'Remove the lid and cook until the liquid has evaporated, about 3 minutes longer.'),
('14884', '5', 'Transfer to a bowl and serve.'),
('14889', '1', 'Cut the kale into bite-size pieces, removing any tough stems. Rinse and shake dry.'),
('14889', '2', 'Warm the oil and garlic in a large stockpot over medium-high heat.'),
('14889', '3', 'Remove the garlic as soon as it browns (don''t let it burn).'),
('14889', '4', 'Add the kale and stir-fry 5 minutes.'),
('14889', '5', 'Add 1/4 cup water, cover, and cook 8 to 10 minutes or until tender. Uncover and add the sugar, salt, olives, and peppers. Cook over medium-high heat until the liquid has evaporated. Spoon into a serving dish. scatter the garlic over the top.'),
('14889', '6', 'Drizzle with the balsamic vinegar.'),
('14889', '7', 'Serve warm or at room temperature.'),
('14897', '1', 'Coat a large saute pan with olive oil and add the garlic cloves and crushed red pepper. Bring the pan to a medium heat and cook the garlic until it gets golden and very aromatic.'),
('14897', '2', 'Remove the garlic and discard.'),
('14897', '3', 'Add the 2 types of kale and stir to coat with the oil. Season with salt and add the chicken stock. Cover and cook for 2 to 3 minutes.'),
('14897', '4', 'Uncover and stir to be sure that the kale is cooked evenly.'),
('14897', '5', 'Let the liquid evaporate. Sprinkle with sherry vinegar. Taste to make sure that the kale is seasoned perfectly.'),
('14897', '6', 'Serve immediately.'),
('14899', '1', 'Heat oil in a Dutch oven over medium-high heat.'),
('14899', '2', 'Add onion to pan. saut 6 minutes or until onion is tender and begins to brown.'),
('14899', '3', 'Add 5 cups kale, 1/4 cup broth, salt, and peppers to pan. Cover, reduce heat, and cook 4 minutes.'),
('14899', '4', 'Add remaining 5 cups kale and remaining 1/4 cup broth to pan. Cover and cook 16 minutes or until tender, stirring occasionally. Sprinkle with bacon.'),
('14899', '5', 'Serve with lemon wedges.'),
('14910', '1', 'Remove the stems from the kale and chop the leaves coarsely. Wash and drain well, but do not dry.'),
('14910', '2', 'Heat a large saut pan, add  cup olive oil and enoungh kale to cover the bottom of the pan, and cook over high heat while stirring to rotate the leaves.'),
('14910', '3', 'Add more kale as the leaves wilt. When all of the kale has been added, season with salt, cover, and reduce the heat to medium. Cook, stirring occasionally. the cooking time will depend on the maturity of the kale. Young kale will be tender after 4 or 5 minutes. It may be necessary to add a splash of water if the leaves begin to scorch. When the leaves are tender, remove the lid and allow any excess water to cook away. Push the kale to one side of the pan and add an extra drizzle of olive oil, the garlic, and a pinch of red pepper flakes to the bare spot. Just as you smell the aroma of the garlic, stir to combine it with the kale. Turn off the heat, add a splash of vinegar, and correct the seasoning with salt and pepper as necessary.'),
('14910', '4', 'Serve warm or room temperature.'),
('14910', '5', 'var article'),
('14910', '6', 'Type_27_data = {}.'),
('14910', '7', 'article'),
('14910', '8', 'Type_27_data.init_step_by_step_images = 0.'),
('14912', '1', 'In a small bowl, cover the dried currants with hot water.'),
('14912', '2', 'Let stand until softened, about 5 minutes. drain.'),
('14912', '3', 'Meanwhile, in a large pot of boiling water, cook the kale until tender, about 5 minutes, then drain. When the kale is cool enough to handle, gently squeeze out any excess water. Coarsely chop the kale.'),
('14912', '4', 'In a large, deep skillet, melt the butter in the olive oil.'),
('14912', '5', 'Add the onion and cook over moderately low heat, stirring occasionally, until softened, about 7 minutes.'),
('14912', '6', 'Add the chicken broth and blanched kale and toss thoroughly. Cover and cook over moderate heat, stirring a few times, until the kale is hot and sizzling, about 3 minutes. Stir in the currants, olives, lemon zest and lemon juice and cook, stirring constantly, until heated through. Season with salt and pepper and serve.'),
('14914', '1', 'Blanch the kale: Bring a large pot (4 qts) of water to a boil.'),
('14914', '2', 'Add a Tablespoon of salt to the water.'),
('14914', '3', 'Add the chopped kale. Cook until wilted, about 5 minutes.'),
('14914', '4', 'Drain and set aside.'),
('14914', '5', 'Saute onions, add smoked paprika and crushed red pepper: '),
('14914', '6', 'Heat olive oil in a large saute pan on medium heat.'),
('14914', '7', 'Add the chopped onion and saute until translucent, about 5 minutes. Stir in the smoked paprika and crushed red pepper.'),
('14914', '8', 'Add the kale and saute for several more minutes. Sprinkle on more salt and smoked paprika to taste.'),
('14919', '1', 'Preheat the oven to 37'),
('14919', '2', 'In a bowl, toss the kale with all but 1 tablespoon of the olive oil and half of the garlic.'),
('14919', '3', 'Spread the kale on 2 baking sheets and roast in the upper and lower thirds of the oven for about 15 minutes, until crisp. shift the pans from top to bottom halfway through. Season the kale with salt and pepper and transfer to a large platter.'),
('14919', '4', 'In a small bowl, whisk the yogurt with the lemon zest and juice and the remaining garlic and 1 tablespoon of oil. Season with salt and pepper.'),
('14919', '5', 'Serve with the roasted kale.'),
('14925', '1', 'Remove stems and center ribs from kale. Wash and pat dry. Coarsely chop to measure 24 cups. Bring water to a boil in an 8-quart stockpot.'),
('14925', '2', 'Add kale. cover and cook 3 minutes.'),
('14925', '3', 'Drain well. place kale in a bowl.'),
('14925', '4', 'Melt butter in a small skillet over medium-high heat. cook 3 minutes or until lightly browned. Stir in raisins, juice, and vinegar. cook 30 seconds, stirring constantly with a whisk.'),
('14925', '5', 'Pour butter mixture over kale. Sprinkle with salt and pepper. toss well to coat.'),
('14927', '1', 'Bring extra-large pot of salted water toboil.'),
('14927', '2', 'Add kale and cook until almost tender,about 8 minutes.'),
('14927', '3', 'Drain. Rinse kale undercold running water.'),
('14927', '4', 'Drain again. Coarselychop kale. DO AHEAD: Can be made 6 hoursahead. Cover and chill.'),
('14927', '5', 'Heat oil in large pot (preferablynonstick) over medium heat.'),
('14927', '6', 'Add shallotsand saute until tender but not brown, about3 minutes.'),
('14927', '7', 'Add garlic and capers. stir 1minute. Stir in kale and saute until tenderand heated through, about 7 minutes.Season to taste with coarse salt and pepper.'),
('14927', '8', 'Transfer kale to large bowl and serve.'),
('14927', '9', 'Bon Appetit'),
('14934', '1', 'Strip the kale leaves from the tough stems. Discard the stems. coarsely chop the leaves. Rinse well in a colander, leaving the water on the leaves.'),
('14934', '2', 'Heat the oil in a large skillet over low heat.'),
('14934', '3', 'Add the garlic and cook, stirring, until it''s golden and aromatic (3-4 minutes).'),
('14934', '4', 'Transfer the garlic to a dish and reserve.'),
('14934', '5', 'Reheat the oil over medium heat, then add the kale and the broth. Cover and simmer until the kale is tender (3-4 minutes). Season with the salt and pepper.'),
('14934', '6', 'Transfer to a serving platter and top with the garlic and Parmesan, if desired.'),
('14939', '1', 'Cook kale in a 6-quart pot of boiling salted water (1 1/2 tablespoons salt for 4 quarts water), uncovered, until almost tender, 5 to 7 minutes.'),
('14939', '2', 'Drain in a colander, then immediately transfer kale to an ice bath to stop cooking. When kale is cool, drain but do not squeeze.'),
('14939', '3', 'Cook garlic in oil in same pot over medium heat, stirring, until fragrant, about 30 seconds.'),
('14939', '4', 'Add kale, dried cranberries, 3/4 teaspoon salt, and 1/8 teaspoon pepper and cook, tossing frequently with tongs, until kale is heated through and tender, 4 to 6 minutes.'),
('14941', '1', 'Arrange oven racks in center and lower third of oven. Preheat oven to 42'),
('14941', '2', 'Place a large jelly-roll pan in oven for 5 minutes.'),
('14941', '3', 'Combine first 4 ingredients in a large bowl. toss to coat.'),
('14941', '4', 'Place kale mixture on hot pan, spreading with a silicone spatula to separate leaves.'),
('14941', '5', 'Bake at 425 for 7 minutes. Stir kale.'),
('14941', '6', 'Bake an additional 5 minutes or until edges of leaves are crisp and kale is tender.'),
('14941', '7', 'Place kale in a large bowl.'),
('14941', '8', 'Drizzle with vinegar. toss to combine.'),
('14941', '9', 'Serve immediately.'),
('14947', '1', 'Place a Dutch oven over medium heat.'),
('14947', '2', 'Add bacon. cook 5 minutes or until crisp, stirring occasionally.'),
('14947', '3', 'Remove bacon from pan, reserving 1 teaspoon drippings in pan. Crumble bacon, and set aside.'),
('14947', '4', 'Increase heat to medium-high.'),
('14947', '5', 'Add onion to pan. cook 5 minutes or until tender, stirring occasionally.'),
('14947', '6', 'Add kale, and cook 5 minutes or until wilted, stirring frequently.'),
('14947', '7', 'Add cider and vinegar. cover and cook 10 minutes, stirring occasionally.'),
('14947', '8', 'Add apple, salt, and pepper. cook 5 minutes or until apple is tender, stirring occasionally. Sprinkle with bacon.'),
('14950', '1', 'Stack a few kale leaves and roll lengthwise into a cigar shape.'),
('14950', '2', 'Cut crosswise into 1/4-inch-wide strips with a sharp knife. Repeat with remaining leaves.'),
('14950', '3', 'Cook bacon in a wide 6- to 8-quart heavy pot over moderate heat, stirring occasionally, until crisp, then transfer with a slotted spoon to paper towels to drain.'),
('14950', '4', 'Pour off and discard all but 3 tablespoons fat from pot, then cook garlic in remaining fat over moderately low heat, stirring, until pale golden, about 30 seconds.'),
('14950', '5', 'Add kale (pot will be full) and cook, turning with tongs, until wilted and bright green, about 1 minute.'),
('14950', '6', 'Add water and simmer, partially covered, until just tender, 6 to 10 minutes. Toss with bacon and salt and pepper to taste.'),
('14960', '1', 'Heat the olive oil in a large soup pot.'),
('14960', '2', 'Add the garlic and onions and cook over moderate heat, stirring occasionally, until softened, about 12 minutes.'),
('14960', '3', 'Add the ginger and andouille and cook for 5 minutes, stirring occasionally.'),
('14960', '4', 'Add the tomatoes and their juices. bring to a boil.'),
('14960', '5', 'Add the stock and kale. return to a boil.'),
('14960', '6', 'Reduce the heat to moderate and simmer the soup until the kale is tender, about 10 minutes. Season the soup with salt and pepper and serve, or let cool and freeze.'),
('14979', '1', 'Preheat the oven to 35'),
('14979', '2', 'Spread the bread on a baking sheet and toss with 1 tablespoon of the olive oil.'),
('14979', '3', 'Bake for 8 minutes, or until lightly toasted.'),
('14979', '4', 'Let the croutons cool on the baking sheet.'),
('14979', '5', 'In a large, deep skillet, heat the remaining 1/4 cup of olive oil.'),
('14979', '6', 'Add the shallot, onion and garlic and cook over moderate heat, stirring occasionally, until softened, 7 minutes.'),
('14979', '7', 'Add the kale, cover and cook over moderately low heat, stirring occasionally, until tender, about 15 minutes. Stir in the thyme and season with salt and pepper.'),
('14979', '8', 'Transfer the kale to an 8-by-10-inch glass baking dish. Scatter the cheese over the kale and top with the croutons.'),
('14979', '9', 'Bake for about 20 minutes, or until the cheese is bubbling and the croutons are golden.'),
('14979', '10', 'Let stand for 5 minutes, then serve.'),
('14983', '1', 'Watch how to make this recipe.'),
('14983', '2', 'Heat a medium skillet with extra-virgin olive oil and butter over medium to medium-high heat. When fat is hot, add garlic and mushrooms and place a lid which is too small for the skillet down into the pan, pressing and smothering the mushrooms. Cook 7 to 8 minutes, stirring once, then wilt the kale into the pan, turning it with tongs to combine with mushrooms. Smother the greens for 1 to 2 minutes, then deglaze the pan with Marsala and season the mixture with salt and pepper, to taste.'),
('14987', '1', '*Note: Recipe can easily be halved.'),
('14987', '2', 'Mix together eggs, half-and-half, salt, pepper, and minced oregano. Set aside.'),
('14987', '3', 'Drizzle olive oil over mushrooms and sprinkle with salt and pepper, then roast in a 425 degree oven for 15 to 20 minutes, or until golden brown.'),
('14987', '4', 'Remove from oven and set aside.'),
('14987', '5', 'Heat olive oil over medium-high heat, then throw in kale. Cook for 2 minutes, or until slightly wilted.'),
('14987', '6', 'Remove from heat and set aside.Layer half the bread, half the kale, half the mushrooms, and half the cheese in a large, buttered lasagna pan. Repeat with the other half of all the ingredients, ending with the cheese. Slowly pour egg mixture all over the top.Cover with plastic wrap and refrigerate overnight if possible. To bake, remove from fridge 20-30 minutes before baking. Replace plastic wrap with foil and bake in a 350 degree oven for 30 to 40 minutes.'),
('14987', '7', 'Remove foil and continue baking until top is golden brown and slightly crisp.'),
('14992', '1', 'Prepare the kale and set it aside. In a medium pot. boil sliced potatoes until tender.'),
('14992', '2', 'Drain and set aside. In a large pot, crumble and brown the Italian sausage.'),
('14992', '3', 'Drain as much as the fat as you can. Stir in the red pepper flakes, oregano, chicken broth, milk, and half-and-half. Simmer for 30 minutes.Give it a taste and adjust seasonings as needed.'),
('14992', '4', 'Add the potatoes, a splash of heavy cream for richness, then stir in the kale. Simmer an additional 10-15 minutes, then serve.'),
('14998', '1', 'Rub cut side of garlic on toasts. Top withbean mixture and cheese shavings.'),
('14998', '2', 'Per serving: 76 calories, 2 g fat,  1 g  fiber'),
('14998', '3', 'Bon Appetit'),
('15002', '1', 'Cook kale in large pot of boiling salted water until wilted, about 5 minutes.'),
('15002', '2', 'Transfer to colander. drain.'),
('15002', '3', 'Heat 1 tablespoon oil in heavy large skillet over medium heat.'),
('15002', '4', 'Add onion and saute until soft, about 5 minutes. Stir in 1/4 teaspoon smoked paprika and crushed red pepper. sprinkle with salt.'),
('15002', '5', 'Add kale and saute until heated through, about 4 minutes. Season to taste with salt and pepper and more smoked paprika, if desired.'),
('15002', '6', 'Transfer to serving bowl. drizzle with remaining 1 tablespoon oil and serve.'),
('15002', '7', '*Sweet smoked paprika is sometimes labeled Pimenton Dulce or Pimenton de La Vera Dulce, and hot smoked paprika is sometimes labeled Pimenton Picante or Pimenton de La Vera Picante. available at some supermarkets, at specialty foods stores, an from tienda.com.'),
('15003', '1', 'Remove the tough stems from the kale leaves. Discard the stems, and coarsely chop the greens. Rinse the kale and drain. Bring a large pot of water to a boil, and season with a generous amount of salt.'),
('15003', '2', 'Add the spaghetti and cook until al dente, tender but still firm.'),
('15003', '3', 'While the pasta cooks, heat a large, heavy saute pan over medium-high heat.'),
('15003', '4', 'Add half of the oil, the onion, chile flakes, and a pinch of salt, and cook, stirring occasionally, until the onion is tender and lightly colored, about 5 to 7 minutes. (If the onion begins to scorch, reduce the heat to medium.)'),
('15003', '5', 'Add the kale and cook, stirring and tossing, until the kale is wilted and tender, about 3 minutes.'),
('15003', '6', 'Add water to the pan if the greens are dry, and if the greens are on the sturdy side, cover the pan briefly to steam them.'),
('15003', '7', 'Add the garlic, season with salt, and cook for 2 minutes more. Take care that the garlic doesn''t brown.'),
('15003', '8', 'Drain the pasta when cooked, reserving some of the pasta water.'),
('15003', '9', 'Add the pasta to the saute pan and toss to combine. Loosen with a splash of the cooking water as needed, and taste for salt.'),
('15003', '10', 'Transfer the pasta to a warm platter or serving bowls, and drizzle a thin stream of olive oil on top.'),
('15003', '11', 'Garnish with shavings of Parmesan or Romano cheese, and serve immediately.'),
('15004', '1', 'In a 4- to 5-qt. pan over medium heat, cook bacon, stirring, until crisp, 8 to 10 minutes.'),
('15004', '2', 'Pour bacon and fat through a fine strainer into a bowl. Return 5 tbsp. fat to pan. discard the rest.'),
('15004', '3', 'Add onion, garlic, and bay leaves and cook over medium-high heat, stirring often, until onion is pale golden, 5 minutes. Toss in kale. cook, stirring, until wilted.'),
('15004', '4', 'Add 1 cup water, half the bacon, 2 tbsp. each soy sauce and coconut vinegar, the pepper, and chile. Simmer, covered, adding water if pan gets dry, until kale is very tender, 60 minutes.'),
('15004', '5', 'Add soy and vinegar to taste.'),
('15004', '6', 'Serve sprinkled with remaining bacon.'),
('15008', '1', 'Heat bacon fat in large skillet on medium-high heat.'),
('15008', '2', 'Add onions and garlic. cook 3 min., stirring frequently.  Reduce heat to medium.'),
('15008', '3', 'Add kale, a handful at a time.  Cook and stir 5 min. or until leaves just begin to wilt.  (Kale will be just tender.)'),
('15021', '1', 'Whisk all ingredients in medium bowl. Season rouille to taste with salt and freshly ground black pepper. DO AHEAD:  Can be made 1 day ahead. Cover and chill.'),
('15026', '1', 'Watch how to make this recipe.'),
('15026', '2', 'Warm the olive oil in a large, heavy saute pan over medium-high heat.'),
('15026', '3', 'Add the onions and cook until translucent, about 4 minutes.'),
('15026', '4', 'Add the mushrooms, green beans, salt, and pepper and cook for 2 minutes.'),
('15026', '5', 'Add the wine and continue cooking until the green beans are almost tender, about 5 minutes.'),
('15026', '6', 'Add the red pepper flakes and the kale and continue cooking until the kale has wilted, about 4 to 5 minutes.'),
('15026', '7', 'Add the lemon juice and the Parmesan cheese. Toss to coat and serve immediately.'),
('15031', '1', 'Place the kale into a salad bowl. Toss with the carrot, orange juice, lemon juice ,and salt, and using your hands, rub the acid into the kale.'),
('15031', '2', 'Let the kale sit a few minutes while you shock the onion. Prepare a large bowl of ice water and a saucepan with boiling water.'),
('15031', '3', 'Place the thinly sliced onion into the boiling water for 15 to 30 seconds, and then shock them in the cold water, stopping the cooking immediately.'),
('15031', '4', 'Drain the water and blot the onions with a paper towel.'),
('15031', '5', 'Add the onion, bacon, olive oil, salt and pepper and toss well.'),
('15031', '6', 'Add the mayonnaise and mix the slaw well. Refrigerate until ready to serve. Can be made several hours in advance.'),
('15068', '1', 'Save Recipe'),
('15068', '2', 'Print Recipe'),
('15068', '3', 'Kale, Fig and Halloumi Salad'),
('15068', '4', 'Ingredients8 oz halloumi cheese1 bunch (about 10 oz) curly kale3 tbsp olive oil3 tbsp balsamic vinegar or lemon juice8 oz  fresh figs - about 10 medium figs1/3 cup roughly chopped walnuts1/4 tsp salt'),
('15068', '5', 'Total Time: 15 Minutes'),
('15068', '6', 'Servings: 8'),
('15068', '7', 'Kosher Key: Dairy'),
('15074', '1', 'Preheat the oven to 35'),
('15074', '2', 'In a medium bowl, toss the squash with 2 tablespoons of the olive oil and season with salt and pepper.'),
('15074', '3', 'Spread the squash on a baking sheet and roast for about 30 minutes, turning once, until tender and lightly browned.'),
('15074', '4', 'In a large skillet, heat the remaining 1/4 cup plus 2 tablespoons of olive oil.'),
('15074', '5', 'Add the kale and cook until it is wilted, about 8 minutes.'),
('15074', '6', 'Add the garlic slices and cook until the kale is tender, about 3 minutes longer. Season the kale with salt and pepper.'),
('15074', '7', 'Add the squash and toss gently to combine.'),
('15074', '8', 'Heat a cast-iron grill pan.'),
('15074', '9', 'Brush the bread with olive oil and grill over high heat, turning once, until toasted. Mound the squash and kale on the toasts, top with the shaved cheese and serve.'),
('15077', '1', 'Save Recipe'),
('15077', '2', 'Print Recipe'),
('15077', '3', 'Kale, Pear and Cranberry Salad'),
('15077', '4', 'Ingredients1/3 cup raw pine nuts or unsalted raw sunflower seeds1 bunch (about 10 oz.) kale3 tbsp olive oil3 tbsp fresh squeezed lemon juice1 red bartlett pear diced into 1/2 inch cubes1/3 cup dried sweetened cranberries1/4 tsp salt, or more to taste'),
('15077', '5', 'Total Time: 15 Minutes'),
('15077', '6', 'Servings: 8 servings'),
('15077', '7', 'Kosher Key: Pareve'),
('15080', '1', 'Preheat the oven to 45'),
('15080', '2', 'In a very large roasting pan, toss the kale, potatoes and onion with the olive oil. Season with salt and pepper and spread in an even layer.'),
('15080', '3', 'Set the chicken on a cutting board, skin side down. Slice halfway through the joint between the drumsticks and thighs. Season with salt and pepper, sprinkle with the paprika and set on top of the vegetables.'),
('15080', '4', 'Cover the pan with foil. Roast the chicken in the upper third of the oven for 20 minutes.'),
('15080', '5', 'Remove the foil and roast for 30 minutes longer, until the chicken is cooked through and the vegetables are tender.'),
('15080', '6', 'Transfer the chicken to plates and spoon the vegetables alongside.'),
('15080', '7', 'Serve with lemon wedges.'),
('15099', '1', 'In a large bowl, combine the spelt flour with the yeast, water, honey, 1 tablespoon of the olive oil and 3/4 teaspoon of kosher salt and stir until a dough forms. Turn the dough out onto a lightly floured surface and knead just until smooth, no more than 1 minute. Oil the bowl and return the dough to it.'),
('15099', '2', 'Let the dough rise, covered, in a warm, draft-free place until doubled in bulk, about 1 hour.'),
('15099', '3', 'Line a baking sheet with parchment paper. Punch down the dough, then transfer it to the baking sheet and press it into a 12-by-8-inch oval.'),
('15099', '4', 'Brush with 1 teaspoon of the olive oil. Press small indentations all over the dough and sprinkle with the rosemary and sea salt.'),
('15099', '5', 'Let the dough stand uncovered for 45 minutes, until slightly risen. Preheat the oven to 37'),
('15099', '6', 'Bake the focaccia for about 30 minutes, until lightly browned all over.'),
('15099', '7', 'Meanwhile, in a bowl, toss the kale with the lemon juice, crushed red pepper and 1 teaspoon of oil. Squeeze the kale gently to soften it, then let it stand for 20 minutes.'),
('15099', '8', 'In a large nonstick skillet, heat the remaining 1 teaspoon of oil.'),
('15099', '9', 'Add the squash, season with kosher salt and cook over moderately high heat until golden, 2 minutes. Turn the squash, add the garlic and cook over moderately low heat until the squash is tender, 5 minutes.'),
('15099', '10', 'Top the focaccia with the kale and squash and bake for 1 minute longer, to heat the vegetables. Scatter the pecorino on top, cut into wedges and serve.'),
('15100', '1', 'In a small saucepan, cover the rice with 1 1/2 cups of water and bring to a boil. Cover and cook over low heat until the water has been absorbed, about 35 minutes.'),
('15100', '2', 'Transfer to a large bowl and fluff with a fork.'),
('15100', '3', 'Meanwhile, in a small glass bowl, microwave the sugar and salt with 2 tablespoons of water at high power for 10 seconds, until the sugar is dissolved. Stir in 1 tablespoon of the rice vinegar. Sprinkle the vinegar mixture over the warm rice and stir well.'),
('15100', '4', 'Lay a nori sheet on a work surface.'),
('15100', '5', 'Spread 1/4 cup of the rice on the bottom half and spread 1/2 teaspoon of wasabi paste over the rice. Top with 2 green beans, 1 kale leaf and a halved scallion. Fold the nori over to form a cone or roll. set on a platter and repeat with the remaining nori and fillings.'),
('15100', '6', 'In a bowl, stir the soy sauce and sesame oil with the remaining vinegar.'),
('15100', '7', 'Serve the rolls with the dipping sauce.'),
('15101', '1', 'Preheat the oven to 350 and position racks in the lower and upper thirds of the oven. In a saucepan, combine the rice with 2 cups of water and a pinch of salt. bring to a boil. Cover and simmer over low heat for 35 minutes, until the rice is tender.'),
('15101', '2', 'In a small bowl, whisk the olive oil with the sesame oil and soy sauce.'),
('15101', '3', 'Transfer two-thirds of the dressing to a large bowl.'),
('15101', '4', 'Add the kale, coconut and tofu. toss to coat, then spread on 2 rimmed baking sheets.'),
('15101', '5', 'Bake for 25 minutes, until crispy. Stir once or twice and shift the pans halfway through baking. Return the mixture to the large bowl and toss with the remaining dressing and rice. Season with salt and serve right away.'),
('15111', '1', 'Arrange kale in a steamer basket over boiling water. cover and steam 2 minutes.'),
('15111', '2', 'Drain.'),
('15111', '3', 'Remove thick stems, and cut leaves into thin strips. set aside.'),
('15111', '4', 'Cook pasta according to package directions. drain and set aside.'),
('15111', '5', 'Remove and discard casings from sausage. Cook sausage in a Dutch oven over medium heat, stirring until it crumbles and is no longer pink. drain.'),
('15111', '6', 'Add onion to sausage in Dutch oven, and saut 5 minutes.'),
('15111', '7', 'Add garlic, and saut 1 minute.'),
('15111', '8', 'Add vinegar, and cook 3 minutes.'),
('15111', '9', 'Add chicken broth and kale. cook 5 minutes. Stir in basil and next 3 ingredients. cook 1 minute. Stir in pine nuts, pasta, and feta cheese. cook until thoroughly heated.'),
('15111', '10', 'Serve immediately.'),
('15111', '11', '*1 (6-ounce) package fresh baby spinach may be substituted for kale. Omit steaming procedure.'),
('15113', '1', 'Preheat oven to 400F.'),
('15113', '2', 'Place sweet potato on a baking sheet or sheet of aluminum foil and roast for 4060 minutes, or until tender and beginning to caramelize. Allow to cool slightly.'),
('15113', '3', 'Meanwhile, heat olive oil in a large skillet over low heat.'),
('15113', '4', 'Add onion and stir to coat. Allow onion to slowly caramelize, stirring occasionally. (On my stove, it takes about an hour to caramelize onions, although other people have told me it takes them 30 minutesuse your best judgment here!)'),
('15113', '5', 'When onion is almost caramelized, stir in crumbled chorizo. Continue to cook for 68 minutes, or until chorizo is beginning to brown.'),
('15113', '6', 'Add chopped kale and cover. Cook until kale is bright green and wilted, approximately 5 minutes more.'),
('15113', '7', 'Remove from heat.'),
('15113', '8', 'Remove sweet potato skin and mash insides in a small bowl. Season with salt and pepper.'),
('15113', '9', 'Combine rice, lime juice, cilantro, and salt in another bowl.'),
('15113', '10', 'In another bowl (last one, I promise!), stir together black beans and paprika until beans are coated.'),
('15113', '11', 'To assemble, divide vegetable and chorizo mixture, rice, sweet potatoes, beans, and salsa among 4 tortillas. If you don''t know how to wrap a burrito, follow these handy dandy instructions.'),
('15119', '1', 'Cook kale in a pot of boiling salted water (1 1/2 tablespoons salt for 4 quarts water), uncovered, until tender, about 7 minutes.'),
('15119', '2', 'Drain kale, then immediately transfer to an ice bath to stop cooking. When kale is cool, drain but do not squeeze.'),
('15119', '3', 'While kale cooks, peel potatoes and cut into 1/2-inch pieces. Simmer in cream with 1/2 teaspoon salt and 1/4 teaspoon pepper in a heavy medium saucepan, covered, stirring occasionally, until tender, 15 to 20 minutes.'),
('15119', '4', 'Puree potato mixture with kale in 2 batches in a food processor until just smooth (use caution when blending hot liquids).'),
('15119', '5', 'Transfer to a 4-to 5-quart heavy saucepan and cook over low heat, stirring frequently, until heated through. Season with salt and pepper.'),
('15124', '1', 'Preheat oven to 32'),
('15124', '2', 'Heat a Dutch oven over medium-high heat.'),
('15124', '3', 'Add 2 teaspoons canola oil. Sprinkle the chicken with black pepper and 1/4 teaspoon salt.'),
('15124', '4', 'Place flour in a dish, and dredge chicken.'),
('15124', '5', 'Place 2 leg quarters in pan, and cook for 1 1/2 minutes on each side.'),
('15124', '6', 'Remove from pan. Repeat procedure with 2 teaspoons oil and remaining 2 leg quarters.'),
('15124', '7', 'Remove from pan.'),
('15124', '8', 'Add remaining 2 teaspoons oil to pan.'),
('15124', '9', 'Add garlic. cook for 20 seconds.'),
('15124', '10', 'Add half of kale. cook for 2 minutes.'),
('15124', '11', 'Add remaining half of kale. cook 3 minutes. Stir in tomatoes and broth. bring to a boil. Return chicken to pan. Cover and bake at 325 for 1 hour and 15 minutes.'),
('15124', '12', 'Remove chicken from pan. stir in vinegar.'),
('15124', '13', 'Serve chicken over kale mixture.'),
('15127', '1', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('15127', '2', 'Add garlic. saut 1 minute.'),
('15127', '3', 'Add kale, broth, salt and pepper, stirring to comvine. Cover, reduce heat to medium, and simmer 5 minutes or until the kale wilts, stirring occasionally.'),
('15127', '4', 'Add pasta, juice, and beans to pan, stirring to combine. cook 1 minute or until mixture is thoroughly heated.'),
('15127', '5', 'Divide pasta mixture evenly among 4 plates. sprinkle each serving withi 1 tablespoon parsley and 1 tablespoon cheese.'),
('15128', '1', 'Slice each leek in half lengthwise, then slice each half into 1/4-inch-thick half-moons (about 2 cups).'),
('15128', '2', 'Place in a large bowl of cold water and swish to remove any grit.'),
('15128', '3', 'Drain and pat dry.'),
('15128', '4', 'Remove the stems from the kale. Stack the leaves on top of one another and slice them crosswise into 1/2-inch-wide strips. you''ll need 3 cups.'),
('15128', '5', 'Heat the oil in a saucepan over medium heat.'),
('15128', '6', 'Add the leeks and cook for 3 minutes.'),
('15128', '7', 'Add the tomatoes and cook, breaking them up with a spoon, for 5 minutes.'),
('15128', '8', 'Add the water and bring to a boil. Stir in the kale, sweet potatoes, lentils, thyme, salt, pepper, and basil (if using). Simmer until the lentils are tender, about 30 minutes. Spoon into individual bowls. Sprinkle with the Parmesan (if using). Tip: Basic brown lentils retain their shape better during cooking than pricier red and yellow lentils, so they''re terrific for soups. You can substitute green lentils, which taste slightly peppery. To Freeze: Omit the Parmesan.'),
('15128', '9', 'Let the soup cool, then ladle into large resealable bags, filling each one halfway. Store for up to 3 months. To Reheat: Thaw overnight in the refrigerator or thaw partially in the microwave. Warm in a covered saucepan over medium heat for 20 minutes. Ladle into individual bowls and sprinkle with the Parmesan (if using).'),
('15143', '1', 'Put the beans in a large soup pot.'),
('15143', '2', 'Add the ham hock, whole carrot, garlic, celery, whole onion, bouquet garni and water and bring to a boil. Cover partially and cook over moderate heat until the beans are just barely tender, about 1 1/2 hours.'),
('15143', '3', 'Using a slotted spoon, discard the carrot, celery and onion.'),
('15143', '4', 'Add the sliced carrots, chopped onion and stock. season with salt and pepper. Cover partially and simmer until the beans are tender, about 45 minutes.'),
('15143', '5', 'Remove the hock and let cool slightly, then shred the meat and return to the soup.'),
('15143', '6', 'Add the kale and cook until tender, 10 minutes. Discard the bouquet garni, season with salt and pepper. serve.'),
('15147', '1', 'Heat the oil in a Dutch oven over medium heat.'),
('15147', '2', 'Add the sausage and cook, without stirring, until browned, about 3 minutes. Turn, add the garlic, and cook for 2 minutes more.'),
('15147', '3', 'Add the beans, broth, and tomatoes and their juices. Increase heat to medium-high and bring to a simmer.Fold each kale leaf in half lengthwise and remove the stem by ripping or cutting it. Tear each leaf into large pieces.'),
('15147', '4', 'Add the kale to the pan and cook, stirring occasionally, until wilted, 2 to 3 minutes.'),
('15147', '5', 'Remove from heat. Season with the salt and pepper and spoon into individual bowls.'),
('15147', '6', 'Serve with the bread (if using).'),
('15148', '1', 'Cook the kale in a large, covered saucepan over medium-high heat until the leaves wilt. Once the volume of the kale is reduced by half, uncover and stir in the garlic, olive oil and vinegar. Cook while stirring for 2 more minutes.'),
('15148', '2', 'Add salt and pepper to taste.'),
('15149', '1', 'Cook pasta in boiling water 8 minutes or until almost tender.'),
('15149', '2', 'Add kale, and cook 2 minutes.'),
('15149', '3', 'Drain in a colander over a bowl, reserving 1/2 cup cooking liquid.'),
('15149', '4', 'While pasta cooks, cook bacon in a large skillet over medium-high heat 4 minutes or until crisp.'),
('15149', '5', 'Remove bacon from pan with a slotted spoon. crumble and set aside. Reduce heat to medium-low.'),
('15149', '6', 'Add sun-dried tomatoes, crushed red pepper, and garlic to drippings in pan. cook 1 minute, stirring frequently.'),
('15149', '7', 'Add pasta mixture, reserved 1/2 cup cooking liquid, black pepper, and salt to pan. toss to combine. Top pasta mixture evenly with bacon and cheese. drizzle evenly with lemon juice.'),
('15150', '1', 'If using fresh greens, discard any tough stems and chop the leaves. Rinse and shake gently to remove most but not all of the water.'),
('15150', '2', 'Place 2 tablespoons of the oil in a large stockpot with the garlic and cook over medium-high heat. As soon as the garlic begins to brown, add the greens and toss.'),
('15150', '3', 'Add 1/2 teaspoon of the salt. Cover immediately and cook over medium heat, stirring occasionally, for 10 minutes or until very tender. (If using frozen spinach, press out the liquid, then saute the spinach in 2 tablespoons of the oil and the garlic for about 5 minutes.)'),
('15150', '4', 'Remove from heat and set aside to cool. Meanwhile, in a medium saucepan over medium heat, combine the remaining olive oil, the flour, and the remaining salt. Cook, whisking constantly, for about 3 minutes.'),
('15150', '5', 'Add the milk and increase heat to medium-high. Cook, stirring constantly, until the sauce thickens and boils, about 10 minutes. Stir in all but 1/2 cup of the grated cheese.'),
('15150', '6', 'Heat oven to 350 F. Coat a 13-by-9-inch baking pan with cooking spray. Blend the ricotta, eggs, lemon zest, and nutmeg into the greens.'),
('15150', '7', 'Spread about 1/2 cup of the cheese sauce in the bottom of the baking pan.'),
('15150', '8', 'Place 3 sheets of pasta on top.'),
('15150', '9', 'Spread on 1/4 of the spinach filling and 1/2 cup sauce, then another 3 sheets of pasta. Make 3 more layers. End with the pasta and sauce, and sprinkle with the remaining cheese. Cover with foil and bake 45 minutes.'),
('15150', '10', 'Remove the foil and cook 15 minutes more or until golden.'),
('15150', '11', 'Let stand 10 minutes before serving. (Can be made up to 1 day ahead. Cover and refrigerate. Reheat in a 325 F oven for 20 minutes or until a knife inserted in the center comes out hot.)'),
('15151', '1', 'In a large saucepan or pot, bring the leeks, potatoes, fennel, thyme, broth, vinegar, salt, and pepper to a boil. Reduce heat to medium-low and simmer gently for 5 minutes.'),
('15151', '2', 'Add the chicken, return to a gentle simmer, and cook for 7 minutes.'),
('15151', '3', 'Add the Swiss chard or kale and cook until the greens are tender and the chicken is cooked through, about 3 minutes.'),
('15151', '4', 'Transfer the chicken to a cutting board and thickly slice it. Divide the chicken among individual bowls. Spoon the potato and fennel mixture over the chicken and drizzle with the oil.Tip: Poaching means simmering something gently, allowing only an occasional bubble to come to the surface. For this dish, the difference between poaching and boiling means supple rather than rubbery chicken and tender vegetables instead of mushy ones.'),
('15152', '1', 'Cook pasta according to package directions, omitting salt and fat.'),
('15152', '2', 'Drain, reserving 1 cup cooking liquid. keep warm.'),
('15152', '3', 'Drain tomatoes in a small sieve over a bowl, reserving 2 teaspoons oil. slice tomatoes.'),
('15152', '4', 'Heat a large Dutch oven over medium heat.'),
('15152', '5', 'Add sliced tomatoes, reserved 2 teaspoons tomato oil, onion, and sausage to pan. cook 10 minutes or until sausage is browned, stirring to crumble.'),
('15152', '6', 'Add garlic to pan. cook 1 minute.'),
('15152', '7', 'Add seasoning, pepper, and broth to pan. Stir in kale. cover and simmer 5 minutes or until kale is tender. Stir in pasta, reserved 1 cup cooking liquid, and beans.'),
('15153', '1', 'Melt butter in a large saucepan over medium heat.'),
('15153', '2', 'Add onion. cook 8 minutes or until tender, stirring frequently.'),
('15153', '3', 'Add garlic. cook 30 seconds, stirring constantly. Stir in broth, potato, salt, and bay leaf. bring to a boil. Cover, reduce heat, and simmer 15 minutes or until potato is tender.'),
('15153', '4', 'Stir in kale and basil. Cover and simmer 10 minutes or until kale is tender. Discard bay leaf. Partially mash potatoes with a potato masher until thick and chunky. Top with cheese.'),
('15156', '1', 'Preheat the broiler but place the oven rack on the second shelf down from the heat source.'),
('15156', '2', 'Bring a few inches of water to a boil in a deep skillet or pot, add the kale and salt and cook 5 to 6 minutes. drain and dry the greens.'),
('15156', '3', 'Return the skillet to the stove over medium-high heat and add 1 tablespoon of extra-virgin olive oil and pancetta. Crisp the pancetta and add the cream and garlic. Season with nutmeg, salt, and pepper then reduce 7 to 8 minutes to about 1/2 to 2/3 cup.'),
('15156', '4', 'Add cooked greens to cream and stir to coat evenly.'),
('15156', '5', 'Transfer to shallow casserole.'),
('15156', '6', 'Toss with breadcrumbs with the remaining 2 tablespoons of extra-virgin olive oil. Season the crumbs with salt and pepper and combine with cheese.'),
('15156', '7', 'Place the casserole on the second shelf under broiler and brown breadcrumbs and cheese for 5 minutes.'),
('15158', '1', 'Pour the whole bottle of wine into a pasta pot and add about the same amount of water. Salt the liquid and bring to a boil over medium heat.'),
('15169', '1', 'To prepare pork, trim fat from pork.'),
('15169', '2', 'Combine pork and next 3 ingredients (pork through vinegar) in a large zip-top plastic bag. Seal and marinate in refrigerator for 2 hours, turning occasionally.'),
('15169', '3', 'Remove pork from bag, reserving marinade.'),
('15169', '4', 'Preheat oven to 37'),
('15169', '5', 'Place pork on a broiler pan coated with cooking spray. Insert meat thermometer into thickest portion of pork.'),
('15169', '6', 'Bake at 375 for 40 minutes or until thermometer registers 160 (slightly pink).'),
('15169', '7', 'Let stand 10 minutes before slicing.'),
('15169', '8', 'To prepare sauce, combine reserved marinade, 2 tablespoons honey, and next 5 ingredients (honey through 1 tablespoon mustard) in a small saucepan. bring to a boil. Reduce heat to medium. cook 15 minutes. Set aside.'),
('15169', '9', 'To prepare kale, combine kale, 1/4 cup chicken broth, 1 tablespoon mustard, and 1 tablespoon shallot in a large skillet over medium heat. Cover and cook 8 minutes or until tender.'),
('15185', '1', 'Bring water to a boil in a Dutch oven. add kale. Cover and cook over medium heat 5 minutes or until tender.'),
('15185', '2', 'Remove kale with a slotted spoon, reserving cooking liquid. Chop kale and set aside.'),
('15185', '3', 'Add potato to reserved cooking liquid in pan. bring to a boil. Reduce heat, and simmer 10 minutes or until tender.'),
('15185', '4', 'Drain. partially mash potatoes. Stir in kale and 1/4 teaspoon salt.'),
('15185', '5', 'Preheat oven to 40'),
('15185', '6', 'Heat oil and butter in a large nonstick skillet over medium-high heat.'),
('15185', '7', 'Add 1/2 teaspoon salt, diced onion, and chopped sage. Cook 13 minutes or until browned.'),
('15185', '8', 'Combine potato mixture, onion mixture, green onions, and pepper.'),
('15185', '9', 'Remove from heat. cool slightly. Divide potato mixture into 8 equal portions, shaping each into a 1/2-inch-thick patty.'),
('15185', '10', 'Place patties on a baking sheet coated with cooking spray.'),
('15185', '11', 'Bake at 400 for 20 minutes.'),
('15185', '12', 'Preheat broiler.'),
('15185', '13', 'Broil patties for 5 minutes or until browned.'),
('15185', '14', 'Garnish with sage sprigs, if desired.'),
('15186', '1', 'Heat a large saucepan over medium-high heat.'),
('15186', '2', 'Add chorizo to pan. saut 1 minute.'),
('15186', '3', 'Add onion and garlic to pan. saut 5 minutes or until tender.'),
('15186', '4', 'While onions cook, pour broth into a microwave-safe bowl. microwave at HIGH for 3 minutes.'),
('15186', '5', 'Add hot broth and beans to pan. bring to a boil. Partially mash beans with potato masher. Stir in kale and 1/2 teaspoon pepper. cook over medium heat 6 minutes. Sprinkle with cracked pepper, if desired.'),
('15187', '1', 'Preheat oven to 50'),
('15187', '2', 'If using a pizza stone, place it on a rack in the oven.'),
('15187', '3', 'Bring 2 qts. very hot water to a boil in a covered pot.'),
('15187', '4', 'Add kale. cook until tender to the bite, about 3 minutes.'),
('15187', '5', 'Drain, rinse with cold water, and squeeze out excess water.'),
('15187', '6', 'Meanwhile, roll dough on a floured work surface into a 14-in. circle, letting it rest a few seconds between passes of the rolling pin so it will stretch. Lay dough on a floured baking sheet.'),
('15187', '7', 'Sprinkle dough with manchego, chorizo, kale, and pepper. Slide pizza onto hot stone, if using, or bake on the baking sheet until browned and puffed, 5 to 10 minutes.'),
('15187', '8', 'Drizzle with oil.'),
('15188', '1', 'Watch how to make this recipe.'),
('15188', '2', 'Heat oil in a deep pot over medium high heat.'),
('15188', '3', 'Add potatoes and onions, cover and cook 5 minutes, stirring occasionally.'),
('15188', '4', 'Add garlic, bay leaves, and kale to the pot. Cover pot and wilt greens 2 minutes. Season with salt and pepper.'),
('15188', '5', 'Add beans, tomatoes, chourico, and broth to the pot and bring soup to a full boil. Reduce heat back to medium and cook 5 to 10 minutes longer or until potatoes are tender.'),
('15188', '6', 'Serve soup with hunks of crusty bread and butter.'),
('15188', '7', 'Cook''s Note: If you are in Mystic, ask for cherise (phonetic pronunciation), if you want to sample the chourico.'),
('15195', '1', 'Heat a large saucepan over medium-high heat.'),
('15195', '2', 'Add smoked sausage to pan. cook 2 minutes, stirring occasionally.'),
