INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('20872', '4', 'Roast vegetables 30 minutes. Reverse baking sheets and continue to roast until all vegetables are tender, stirring occasionally, about 45 minutes longer. (Can be prepared 4 hours ahead.'),
('20872', '5', 'Let stand at room temperature. Rewarm in 350F oven about 20 minutes.)'),
('20872', '6', 'Transfer to platter and serve.'),
('20874', '1', 'Butter 4-quart oval baking dish.'),
('20874', '2', 'Place chicken breasts in heavy large pot.'),
('20874', '3', 'Add just enough broth to cover chicken. Bring broth to boil. reduce heat to low. Cover pot and simmer until chicken is just cooked through, skimming surface occasionally, about 20 minutes. Using tongs, transfer chicken to plate and cool.'),
('20874', '4', 'Add carrots and turnips to chicken broth in pot. Simmer uncovered until vegetables are just tender, about 10 minutes. Using slotted spoon, transfer vegetables to prepared baking dish.'),
('20874', '5', 'Add turnip greens to broth and cook just until wilted, about 1 minute. Using slotted spoon, transfer greens to colander. drain well.'),
('20874', '6', 'Add to vegetables in baking dish.'),
('20874', '7', 'Strain broth. reserve 4 cups.'),
('20874', '8', 'Remove skin and bones from chicken.'),
('20874', '9', 'Cut meat into 1/2- to 3/4-inch pieces.'),
('20874', '10', 'Add chicken to vegetables in baking dish.'),
('20874', '11', 'Melt butter in same pot over medium heat.'),
('20874', '12', 'Add leeks, shallots and thyme. Saute until tender, about 8 minutes.'),
('20874', '13', 'Add flour and stir 2 minutes. Stir in 4 cups broth and white wine. Increase heat to high and bring to boil, stirring constantly.'),
('20874', '14', 'Add cream and boil until sauce thickens enough to coat spoon, whisking frequently, about 6 minutes. Season with salt and pepper.'),
('20874', '15', 'Pour gravy over mixture in dish. Stir to blend. Cool 45 minutes. (Filling can be made 1 day ahead. Cover and refrigerate.)'),
('20874', '16', 'Position 1 rack in top third of oven and place baking sheet on bottom rack in oven. preheat to 400deg.F.'),
('20874', '17', 'Roll out crust dough on parchment paper to 15x10 1/2-inch rectangle. Using paper as aid, turn dough over onto filling. Trim dough overhang. tuck dough edge inside dish.'),
('20874', '18', 'Roll out dough scraps to 1/4-inch thickness.'),
('20874', '19', 'Cut out leaf shapes.'),
('20874', '20', 'Brush bottom of cutouts with water and place on crust. cut slits in crust to allow steam to escape.'),
('20874', '21', 'Place pot pie on top rack and bake until crust is golden and gravy is bubbling, about 50 minutes.'),
('20874', '22', 'Let stand 10 minutes before serving.'),
('20878', '1', 'Melt butter with olive oil in a skillet over medium heat.'),
('20878', '2', 'Add the onions, and cook until caramelized, 10 to 15 minutes.'),
('20878', '3', 'Transfer the onion to a bowl, and mix with the grated turnip. Season with salt and pepper. Refrigerate for 30 minutes to allow the flavors to mingle.'),
('20878', '4', 'Serve on small toast  or crackers.'),
('20882', '1', 'Take the shanks out of the braiseliquid. Discard the bones and fat, and reserve about 12 oz of the meat, keeping the rest for another recipe. Strain the braiseliquid and reserve.In a saucepan, saut the pancetta over high heat.'),
('20882', '2', 'Add the mushrooms, and cook until soft.'),
('20882', '3', 'Add the braise liquid, and reduce until it coats the back of a spoon. Stir in the heavy cream and green peas. Shred the meat between your fingers, add to the saucepan and reserve.'),
('20882', '4', 'Roll the puff pastry into a rectangle about 3 thick.'),
('20882', '5', 'Cut out 8 discs using a 3 1/2 cutter.'),
('20882', '6', 'Transfer to a baking sheet lined with parchment paper, and refrigerate for 30 minutes.'),
('20882', '7', 'Cut out the centers of 4 of the discs using a 2 3/4 cutter. You should now have 4 small discs, 4 large discs, and 4 rings.'),
('20882', '8', 'Mix the egg yolk and the milk, and brush the discs and rings with this eggwash.'),
('20882', '9', 'Place the rings on top of the large discs, pressing lightly to adhere. Prick the centers of these bouches and bake together with the small discs (the lids) in a 350 F oven for 20 minutes.'),
('20882', '10', 'Transfer to a cooling rack, and remove the excess dough inside the bouches.Reheat the meat mixture and stir in the butter. Fill the bouches and serve immediately.'),
('20883', '1', 'Preheat oven to 325F. If using peanuts, blend in a food processor until they form a butter, 2 to 3 minutes. Put fresh or jarred peanut butter in a bowl and gradually whisk in 1 1/2 cups water.'),
('20883', '2', 'Pat chicken dry and season with salt.'),
('20883', '3', 'Heat oil in an ovenproof 4- to 5-quart heavy pot (with a tight-fitting lid, for use later) over moderately high heat until hot but not smoking, then brown chicken, uncovered, in 3 or 4 batches, without crowding, about 6 minutes.'),
('20883', '4', 'Transfer chicken to a bowl as browned.'),
('20883', '5', 'Pour off all but about 2 tablespoons fat from pot, then add onion and bell pepper and saute, stirring occasionally, until onion begins to brown, about 4 minutes.'),
('20883', '6', 'Add garlic and saute, stirring, 1 minute.'),
('20883', '7', 'Stir in peanut butter mixture, remaining 1 1/2 cups water, tomatoes with juice, cayenne (to taste), salt, and chicken with any juices accumulated in bowl and bring to a simmer. Cover pot with lid, then braise chicken in middle of oven until tender, 45 minutes to 1 hour.'),
('20883', '8', 'Transfer chicken with tongs to a large (4-quart) serving dish and keep warm, covered.'),
('20883', '9', 'Stir potatoes and turnips into sauce and simmer on top of stove, uncovered, until vegetables are tender, 15 to 20 minutes.'),
('20883', '10', 'Transfer cooked vegetables with a slotted spoon to serving dish.'),
('20883', '11', 'Simmer sauce, uncovered, stirring, until reduced to about 4 cups, about 5 minutes.'),
('20883', '12', 'Remove from heat and stir in spinach, then let stand, partially covered, until spinach is wilted, 2 to 3 minutes. Season with salt if necessary, then spoon over chicken.'),
('20889', '1', 'Soak dried chickpeas in 3 cups water at least 8 hours and up to 2'),
('20889', '2', 'Drain soaked chickpeas and combine with 6 cups cold water in a 3- to 4-quart saucepan and simmer, uncovered, until tender, about 1 hour.'),
('20889', '3', 'Drain and set aside.'),
('20897', '1', 'Heat oil in a large heavy pot over medium heat.'),
('20897', '2', 'Add sausage, and cook about 5 minutes.'),
('20897', '3', 'Add onion and garlic. saut 5 minutes.'),
('20897', '4', 'Add 3/4 teaspoon salt and next 7 ingredients. stir well.'),
('20897', '5', 'Add stock, and bring to a boil. reduce heat, and simmer 20 minutes or until pumpkin is tender when pierced with a fork. Stir in zucchini and chickpeas. simmer about 10 minutes more or until zucchini is tender but not falling apart.'),
('20897', '6', 'Cook couscous according to package directions with remaining 3/4 teaspoon salt. Fluff with a fork. keep warm until ready to serve.'),
('20897', '7', 'Pile warm couscous on a large platter.'),
('20897', '8', 'Remove sausage and vegetables from pot with slotted spoon, and place around couscous.'),
('20897', '9', 'Garnish, if desired.'),
('20897', '10', 'Pour broth into a serving bowl. Invite guests to serve themselves individual portions of couscous, vegetables, and broth.'),
('20897', '11', '*Substitute 1 butternut squash or large sweet potato, if desired.'),
('20902', '1', 'Heat oil in a large skillet over medium heat.'),
('20902', '2', 'Add turmeric, cumin, and paprika. cook, stirring, until the spices begin to foam.'),
('20902', '3', 'Add cilantro, parsley, garlic, and tomatoes. cook, stirring until they''re well blended.'),
('20902', '4', 'Add fennel, potatoes, turnips, carrots, and broth. Then reduce heat to medium. Cover tightly and cook until the potatoes and carrots are tender (about 30 minutes).'),
('20902', '5', 'Add peas and cook until they are thoroughly heated. Season the mixture with salt, pepper, and lemon juice.'),
('20902', '6', 'Transfer the mixture to a tagine pot or platter.'),
('20902', '7', 'Garnish with cilantro sprigs.'),
('20903', '1', 'Saut ham in hot oil in a Dutch oven over medium-high heat 5 minutes or until lightly browned.'),
('20903', '2', 'Add broth and remaining ingredients. bring to a boil. Cover, reduce heat to low, and simmer, stirring occasionally, 25 minutes.'),
('20905', '1', 'Preheat oven to broil. Cook bacon in a Dutch oven over medium-high heat 5 to 6 minutes or until crisp. remove bacon, and drain on paper towels, reserving 1 Tbsp. drippings in Dutch oven.'),
('20905', '2', 'Saut onion and garlic in hot drippings 3 to 4 minutes.'),
('20905', '3', 'Add wine, and cook 1 to 2 minutes, stirring to loosen particles from bottom of Dutch oven. Stir in turnip greens, next 4 ingredients, and 1/2 cup Parmesan cheese. Cook, stirring often, 6 to 8 minutes or until cream cheese is melted and mixture is thoroughly heated.'),
('20905', '4', 'Transfer to a lightly greased 1 1/2-qt. baking dish. (Make certain that you use a broiler-safe baking dish.) Sprinkle with remaining 1/4 cup Parmesan cheese.'),
('20905', '5', 'Broil 6 inches from heat 4 to 5 minutes or until cheese is lightly browned. Sprinkle with bacon.'),
('20905', '6', 'Garnish, if desired.'),
('20905', '7', 'Serve with assorted crackers, flatbread, and wafers.'),
('20905', '8', 'Note: To make ahead, prepare recipe as directed through Step  Cover and chill 8 hours.'),
('20905', '9', 'Bake, covered with aluminum foil, at 350 for 30 minutes. Uncover and bake 30 minutes. Sprinkle with bacon.'),
('20905', '10', 'Serve with assorted crackers and chips.'),
('20905', '11', 'Warm Spinach-Artichoke Dip: Substitute 2 (10-oz.) packages frozen spinach, thawed and drained, and 1 (14-oz.) can quartered artichoke hearts, drained and coarsely chopped, for turnip greens. Proceed with recipe as directed.'),
('20907', '1', 'Melt butter with oil in a large Dutch oven over medium-high heat. add garlic, and cook, stirring often, 1 minute.'),
('20907', '2', 'Add chopped turnip greens and remaining ingredients. cook, stirring often, 10 to 14 minutes or until greens are tender.'),
('20907', '3', 'Serve immediately.'),
('20907', '4', 'Note: Any combination of winter greens may be used in this recipe.'),
('20912', '1', 'Pickling the red onion: Peel and thinly slice the red onion. mince finely.'),
('20912', '2', 'Place the sliced onion in a bowl, sprinkle with  brown sugar and drizzle with the juice of half of a lime. Toss well. Set aside.  Making ginger paste: Clean the ginger. Peel the ginger root with a paring knife and finely chop it.'),
('20912', '3', 'Place the chopped ginger in a mini-blender, adding about 2 tablespoons (or more) of water for a smooth flow. Gather about 2 teaspoons. Set aside.Prepping the chicken:Bring about 7 quarts of water to a boil.'),
('20912', '4', 'Add the fried onions. Boil for about 5 minutes. No sugar is necessary yet because of the natural sweetness of the onions. Do NOT salt.'),
('20912', '5', 'Add the whole chicken and chicken thighs and drumsticks to the onion broth. Cook for about 10-12 minutes.'),
('20912', '6', 'Remove the whole chickens from the pot.'),
('20912', '7', 'Let them cool a bit until you can handle them without discomfort. Make several deep diagonal incisions throughout the birds'' flesh.'),
('20912', '8', 'Place the chicken pieces back in the broth.'),
('20912', '9', 'Add half a daikon, whole onion, rock sugar and mushroom seasoning salt. Bring to one more boil and simmer for another 30 minutes until the whole onion and daikon are soft and tender.Season with salt. Bring back to a boil, then immediately lower the heat to a gentle boil. Cook for another 10-12 minutes.'),
('20912', '10', 'Remove the chicken pieces.'),
('20912', '11', 'Let them cool a bit until you can handle them without discomfort. Shred the meat. Sprinkle with 1/4 teaspoon of black pepper. Set the meat aside on a platter. Reserve the chicken broth for another recipe (see tips).Peanuts: In a mortar and pestle, slightly crush the peanuts. You still want to have visible pieces of peanuts for a crunchy texture.Gi sauce (salad dressing): In a bowl, combine the rest of the lime juice, sugar, salt, pickled garlic, ginger paste and soy sauce.'),
('20912', '12', 'Mix well.Assembly time: In a large bowl, combine the shredded chicken, red Thai chili, shredded daikon, dried fried shallot. shredded cabbage and pickled red onion with its macerating liquid. When you''re ready to serve, drizzle the gi sauce (salad dressing).'),
('20912', '13', 'Add all the chopped herbs. Toss well. Season with more salt (if needed) and the remaining black pepper. Sprinkle the peanuts (if you like).'),
('20912', '14', 'Serve with a little mui t (chili salt) and nc mm (if needed) on the side. Call your gang immediately.Eat with chopsticks and enjoy!'),
('20913', '1', 'Heat the olive oil in a large saucepan over medium heat. Stir in the onion, garlic, cumin, and curry powder. cook and stir until the onion has softened and turned translucent, about 5 minutes.'),
('20913', '2', 'Add the garbanzo beans, red bell pepper, turnip, corn, and tomato sauce. Season with red pepper flakes, salt, and black pepper. Bring to a simmer over medium-high heat, then reduce heat to medium-low, cover, and simmer until the vegetables are tender and the curry has thickened, 1 1/2 to 2 hours.'),
('20914', '1', 'Preheat the oven to 35'),
('20914', '2', 'In a small bowl, mash the garlic, cumin, 1 tablespoon of salt and 1 teaspoon of pepper with 2 tablespoons of the oil. rub all over the steak. Cover and let stand at room temperature for 1 hour.'),
('20914', '3', 'Meanwhile, in a medium baking dish, mix the bulgur and cinnamon. Stir in 2 tablespoons of the oil and the boiling water and season with salt and pepper. Cover tightly with foil and bake for 20 minutes, until the water is completely absorbed. Fluff the bulgur with a fork, then cover and keep warm.'),
('20914', '4', 'In a large saucepan, melt the butter in 1 tablespoon of the oil.'),
('20914', '5', 'Add the onion and cook over moderate heat until barely softened, about 2 minutes.'),
('20914', '6', 'Add the carrots and turnip, season with salt and pepper and cook for 2 minutes, until just softened.'),
('20914', '7', 'Add the stock and bring to a simmer. Cover and cook over low heat until the vegetables are tender, 10 minutes. Stir the vegetables and liquid into the bulgur with the lemon juice, parsley, mint and 2 tablespoons of the oil.'),
('20914', '8', 'In an ovenproof skillet, heat the remaining 1 tablespoon of oil and swirl to coat the pan.'),
('20914', '9', 'Add the steak and cook over high heat, turning once, until browned, 8 minutes.'),
('20914', '10', 'Transfer the skillet to the oven and roast for 25 minutes, turning once, until an instant-read thermometer inserted into the thickest part registers 13'),
('20914', '11', 'Transfer the steak to a cutting board and let rest for 10 minutes. Thinly slice the steak and serve with the bulgur.'),
('20916', '1', 'In a saucepan, cover the farro with water and bring to a boil. Cover and cook over moderate heat until just tender, 12 minutes.'),
('20916', '2', 'Drain and transfer to a medium bowl. Refrigerate for about 30 minutes, until chilled.'),
('20916', '3', 'In a small bowl, whisk 2 tablespoons of water with the tahini and olive oil.'),
('20916', '4', 'In a skillet, heat the vegetable oil.'),
('20916', '5', 'Add the farro in an even layer and cook over high heat, stirring once, until toasted, about 5 minutes.'),
('20916', '6', 'Add 1/4 cup of water and the greens and cook over moderate heat, stirring a few times, until the greens are just tender, about 2 minutes. Stir in the parsley and the tahini mixture and remove from the heat. Stir in the lemon juice and season with salt.'),
('20916', '7', 'Transfer the farro to a bowl, drizzle with pomegranate molasses and serve.'),
('20919', '1', 'Pre-heat the oven to 350 F.'),
('20919', '2', 'Cut the garlic head in half horizontally and wrap in aluminium foil.'),
('20919', '3', 'Bake for 45 minutes.When cool enough to handle, squeeze out the garlic and put it in a bowl and squash with a fork until you have a paste. Set aside.'),
('20919', '4', 'Lower the oven to 275 F. Salt and pepper the meat and set aside.'),
('20919', '5', 'Add 3 tablespoons of olive oil in a wide frying pan and allow to heat well.'),
('20919', '6', 'Add the bacon strips and brown evenly.'),
('20919', '7', 'Remove with a slotted spoon and set aside.'),
('20919', '8', 'In the same frying pan, without taking the olive oil and fat rendered by the bacon, saute the mushrooms, with thyme, salt and pepper. (If they dont fit all in the frying pan saute in 2 batches so as not to steam).'),
('20919', '9', 'Remove mushrooms with a slotted spoon and keep fat and juices in the frying pan.'),
('20919', '10', 'Deglaze the frying pan with half the wine and allow the alcohol to evaporate. Reserve.'),
('20919', '11', 'Lightly dust the meat with flour.'),
('20919', '12', 'In a dutch oven, heat 4 tablespoons of olive oil, add the meat and seal it on all sides  do this in 3 batches so the meat fries well. Keep removing the previous batch of meat and go ahead with the second, until you have browned all the meat pieces. Keep the meat in a bowl off to the side.'),
('20919', '13', 'Add the sage leaves and fry for 1 minute, then add the diced onion and garlic and allow to color until just very pale blond.'),
('20919', '14', 'Add the other half of the red wine and deglaze the dutch pan well.'),
('20919', '15', 'Add the reserved deglazing liquid and the 1 tablespoon of roasted garlic mash and stir to dissolve very well. Allow to come to a boil again.'),
('20919', '16', 'Add the meat, bacon, and mushrooms, stirring well to combine.'),
('20919', '17', 'Add the celery, carrots, and enough stock to come to 2/3 of the height of the meat.'),
('20919', '18', 'Cover and cook in the oven at 275 F for 2 to 3 hours, stirring from time to time and adding more hot vegetable stock when necessary. When cooked, the meat should almost fall apart.'),
('20919', '19', 'Return the dutch oven to the stove again over medium low heat and check the seasoning with salt and pepper. Discard the sage leaves.'),
('20919', '20', 'In a separate small pot, dissolve the flour in the cream and add 1/2 a ladle of the hot meat sauce to the cream and stir well.'),
('20919', '21', 'Pour the cream in the pot, reduce the heat, stir well until all the sauce is well mixed and the meat covered with it, and cook for 4 minutes or until the sauce thickens with the flour.'),
('20919', '22', 'Assembling the pie: Raise oven temperature back to 40'),
('20919', '23', 'Butter the bottom of an oven proof dish, add one good layer of potato mash (about 1/3 of the height of the dish).'),
('20919', '24', 'Add the meat and vegetable stew with enough sauce to come almost to the top.'),
('20919', '25', 'Clean the borders of the dish well and layer the puff pastry. Press lightly on the border to adhere it to the dish and with a very sharp knife cut around the dish. At this point you can freeze the dish if you desire. (You can also choose to make individual or 2 portion pies or even put the pastry directly on the Dutch oven -- whichever you like!)'),
('20919', '26', 'Lightly brush the pastry with egg yolk, make one whole in the middle for the steam to come out and bake in the oven until the puff pastry is golden brown. Enjoy!'),
('20919', '27', 'Here''s the recipe for the turnip mash: http://food52.com/recipes/2998_roasted_turnip_and_celery_with_garlic_and_rosemary_infused_potato_mash, or feel free to use your favorite one!'),
('20920', '1', 'Preheat the oven to 40'),
('20920', '2', 'Tightly wrap the beets in a double layer of aluminum foil and roast them on the bottom shelf of the oven for 1 1/2 hours, or until they are tender when pierced with the tip of a knife. When the beets are cool enough to handle, peel and cut them into 1-inch pieces.'),
('20920', '3', 'Meanwhile, divide the carrots, parsnips and turnips between 2 large rimmed baking sheets. Toss the vegetables in each pan with 1 tablespoon of the vegetable oil. Arrange the onion wedges on the baking sheets, keeping them intact.'),
('20920', '4', 'Brush the onion wedges all over with the remaining 1 tablespoon of vegetable oil. Generously season the vegetables with salt and pepper. Roast the vegetables for 40 minutes.'),
('20920', '5', 'Brush the vegetables with the warm honey and sprinkle with the sage. Continue to roast the vegetables for 25 minutes longer, or until they are tender and glazed. Loosen the vegetables with a spatula and let them cool to room temperature in the pans.'),
('20920', '6', 'In a small bowl, mix the goat cheese with the herbs and olive oil and season with salt and pepper.'),
('20920', '7', 'In a small bowl, combine the olive oil with the vinegar, garlic and herbs. season with salt and pepper. In a large bowl, toss the arugula with 1 tablespoon of the vinaigrette and arrange on plates.'),
('20920', '8', 'Add the roasted vegetables to the bowl and toss with the remaining vinaigrette. Top the arugula with the vegetables, dot each plate with small spoonfuls of the herbed goat cheese and serve.'),
('20921', '1', 'Preheat oven to 425 degrees F (220 degrees C). Line a baking sheet with a piece of aluminum foil and lightly grease.'),
('20921', '2', 'Peel the turnips, and cut into French fry-sized sticks, about 1/3 by 4 inches.'),
('20921', '3', 'Place into a large bowl, and toss with the vegetable oil to coat.'),
('20921', '4', 'Place the Parmesan cheese, garlic salt, paprika, onion powder in a resealable plastic bag, and shake to mix.'),
('20921', '5', 'Place the oiled turnips into the bag, and shake until evenly coated with the spices.'),
('20921', '6', 'Spread out onto the prepared baking sheet.'),
('20921', '7', 'Bake in preheated oven until the outside is crispy, and the inside is tender, about 20 minutes.'),
('20921', '8', 'Serve immediately.'),
('20924', '1', 'COMBINE the fennel, leek, carrot, turnip, mushrooms, and bouquet garni with the broth in a 4-quart pot. Simmer gently over medium heat until the vegetables barely begin to soften, after about 10 minutes.'),
('20924', '2', 'ADD the tomatoes and chicken to the simmering soup. Make sure the chicken is completely submerged and simmer for about 20 minutes more. Take the chicken out of the soup with a slotted spoon and let it cool. Peel off the skin. If youre serving this soup as a main course, you may want to leave the chicken pieces whole. otherwise, pull the chicken away from the bone and cut it into chunks.'),
('20924', '3', 'SPRINKLE the basil leaves with olive oil to keep them from turning dark and chop them finely with a chefs knife or in a blender. If you use a blender, you may have to add a little more olive oil to get the leaves moving.'),
('20924', '4', 'Combine the chopped basil with the heavy cream.'),
('20924', '5', 'PUT the chicken back in the soup along with the beans and spinach and simmer the soup for about 2 minutes. Season with salt and pepper.'),
('20924', '6', 'PUT half the garlic and saffron mayonnaise in a mixing bowl and whisk in the hot soup.'),
('20924', '7', 'Place a slice of French bread toast in the bottom of each wide soup bowl and ladle the soup over it. If youve left the chicken pieces whole, prop the chicken up on the toasts and ladle the soup over that.'),
('20924', '8', 'Drizzle the top of each bowl with a tablespoon of garlic mayonnaise and a tablespoon of the basil cream. Pass the remaining mayonnaise and basil cream at the table.SUGGESTIONS AND VARIATIONS Almost any vegetable soup can be turned into a chicken soup by poaching pieces of chicken in the simmering soup about 15 minutes before serving. If you dont want to deal with the last-minute skinning and boning of the chicken, bone the chicken in advanceif you have time, make the broth with the bonesand then just add the boneless chicken meat to the soup about 5 minutes before serving.'),
('20924', '9', 'var article'),
('20924', '10', 'Type_27_data = {}.'),
('20924', '11', 'article'),
('20924', '12', 'Type_27_data.init_step_by_step_images = 0.'),
('20925', '1', 'Blanch onions in a 2- to 3-quart pot of boiling salted water 1 minute, then transfer with a slotted spoon to a bowl of cold water to stop cooking.'),
('20925', '2', 'Drain onions and peel, trimming root ends with a paring knife. Wash leek slices in a bowl of water, agitating them, then lift out and drain in a medium-mesh sieve.'),
('20925', '3', 'Preheat oven to 350F.'),
('20925', '4', 'Pat lamb dry and sprinkle with 1 teaspoon salt and 1/4 teaspoon pepper. Put lamb and 3 tablespoons flour in a sealable plastic bag, then seal bag and shake to coat lamb.'),
('20925', '5', 'Melt 2 tablespoons butter in casserole dish over moderately high heat until foam subsides, then brown half of lamb, turning, about 6 minutes.'),
('20925', '6', 'Add 1 tablespoon garlic and cook, stirring, 2 minutes.'),
('20925', '7', 'Transfer browned lamb and garlic to a plate with a slotted spoon and repeat with remaining lamb and tablespoon garlic (do not add more butter).'),
('20925', '8', 'Add wine to casserole dish and deglaze by boiling over high heat, stirring and scraping up brown bits, 1 minute, then stir in tomato paste and boil, stirring, until liquid is reduced by half, about 5 minutes.'),
('20925', '9', 'Add broth, water, thyme, browned lamb with any juices that have accumulated on plate, onions, leeks, carrots, turnips, remaining teaspoon salt, and remaining 1/4 teaspoon pepper and stir to combine. Bring to a simmer over moderately high heat, then remove from heat.'),
('20925', '10', 'Cover dish with lid or foil and braise lamb and vegetables in middle of oven, stirring once or twice, until lamb is tender, 1 1/2 to 2 hours. Season with salt and pepper.'),
('20926', '1', 'Warm olive oil in large nonstick skillet over medium heat.'),
('20926', '2', 'Add chopped vegetables. saut for 8 minutes.'),
('20926', '3', 'Add garlic. saut 1 minute longer.'),
('20926', '4', 'Pour in vegetable broth. Cover, reduce heat to low and simmer until vegetables are tender.'),
('20926', '5', 'Transfer to a bowl. Boil pasta in a pot of salted water until al dente. Reserve 1 cup cooking liquid. drain pasta, then add to vegetables. Sprinkle with chopped parsley and lemon zest, and toss to coat (add cooking liquid 1 Tbsp. at a time if pasta is dry). Top with grated Parmesan.'),
('20927', '1', 'Cook bacon in a Dutch oven over medium heat until crisp.'),
('20927', '2', 'Remove bacon from pan using a slotted spoon, reserving drippings in pan. Crumble bacon.'),
('20927', '3', 'Add onion to drippings in pan. saut 4 minutes, stirring occasionally. Stir in broth and the next 5 ingredients (through greens). bring to a boil. Reduce heat, and simmer for 55 minutes or until peas are tender, stirring occasionally and skimming as necessary. Stir in vinegar. Ladle about 1 1/3 cups pea mixture into each of 4 bowls. top evenly with crumbled bacon.'),
('20928', '1', 'Combine first 5 ingredients in a large Dutch oven. bring to a boil. Stir in remaining ingredients. Reduce heat. cover and simmer 15 minutes or until vegetables are tender. Ladle into individual soup bowls. serve warm.'),
('20931', '1', 'Saut ham in hot oil in a Dutch oven over medium-high heat 5 minutes or until lightly browned.'),
('20931', '2', 'Add broth and remaining ingredients. bring to a boil. Cover, reduce heat to low, and simmer, stirring occasionally, 25 minutes.'),
('20933', '1', 'Place chicken, parsnip, turnip, carrots, celery, leek, onion, parsley and dill in an 8 quart stock pot. cover with water and bring to a boil.  Reduce heat. cover, and simmer for 2 hours.'),
('20933', '2', 'Remove whole chicken from soup, tear meat from bone, and set meat aside. Discard chicken bones, parsley and dill.'),
('20933', '3', 'Remove vegetables from stock pot. Using a food processor, puree vegetables and return to stock pot, along with chicken.  Salt and pepper to taste.'),
('20937', '1', 'Adjust rack to lower third of oven. Preheat to 300F. Simmer wine in large saucepan over medium heat until reduced to 1 cup, about 30 minutes.'),
('20937', '2', 'Meanwhile, heat oil in heavy large wide pot over medium heat. Sprinkle roasts with salt and pepper.'),
('20937', '3', 'Add 1 roast to pot and cook until brown on all sides, about 13 minutes.'),
('20937', '4', 'Transfer to large plate. repeat with remaining roast. Spoon fat from pot'),
('20937', '5', 'Add onion, carrot, celery, and garlic to pot. Sprinkle with salt and pepper. saute over medium-high heat until vegetables begin to brown, about 6 minutes.'),
('20937', '6', 'Add tomato paste. stir 1 minute.'),
('20937', '7', 'Add broth. bring to boil.'),
('20937', '8', 'Add sage, parsley, bay leaf, and peppercorns. Return roasts and any accumulated juices to pot, tucking roasts to fit in single layer.'),
('20937', '9', 'Pour reduced red wine over. cover.'),
('20937', '10', 'Transfer roasts to oven and braise 1 hour 15 minutes. Turn roasts over. Cover and braise until roasts are tender, about 1 hour 15 minutes longer. DO AHEAD Can be made 2 days ahead. Cool slightly. Chill uncovered until cool, then cover and keep chilled. Rewarm in 350F oven until heated through, about 30 minutes.'),
('20937', '11', 'Transfer roasts to cutting board. tent with foil. Strain braising liquid into medium saucepan, pressing on solids in strainer. Spoon fat from surface of braising liquid. keep liquid warm.'),
('20938', '1', 'Preheat oven to 45'),
('20938', '2', 'Combine first 7 ingredients in a shallow roasting pan.'),
('20938', '3', 'Bake at 450 for 30 minutes.'),
('20938', '4', 'Place vegetable mixture in a Dutch oven over medium heat.'),
('20938', '5', 'Add flour, ginger, and sage. cook 3 minutes.'),
('20938', '6', 'Add Vegetable Stock, and bring to a boil. Cover, reduce heat, and simmer 30 minutes. Stir in salt and pepper. Sprinkle each serving with 1 1/2 teaspoons parsley and top with 1 teaspoon crme frache.'),
('20939', '1', 'Place flour in a shallow dish. dredge chicken in flour.'),
('20939', '2', 'Heat 1 tablespoon oil in a large nonstick skillet over medium-high heat.'),
('20939', '3', 'Add chicken. saut 5 minutes, turning once.'),
('20939', '4', 'Remove chicken from pan, and keep warm.'),
('20939', '5', 'Heat 2 teaspoons oil in pan.'),
('20939', '6', 'Add onion. saut 3 minutes.'),
('20939', '7', 'Add rutabaga, turnip, squash, parsnip, and garlic. saut 3 minutes. Stir in broth and remaining ingredients. nestle chicken into vegetable mixture. Bring to a boil. cover, reduce heat, and simmer 20 minutes or until chicken is done. Uncover and simmer 3 minutes or until thick.'),
('20939', '8', 'Remove bay leaf.'),
('20941', '1', 'For chicken: Wash and prepare all vegetables, and set aside. Reserve 6 sprigs of dill and chop finely, and set aside. Reserve 4 sprigs of parsley and chop finely, and set aside. Tie together, the remainder of parsley and dill with butchers twine. Wash and pat chicken dry with paper towels.Sprinkle with 1/2 tsp of salt and the white pepper on both sides. In a Dutch oven or a heavy-bottomed soup pot, add 2 tbsp of butter.'),
('20941', '2', 'Heat on a high flame and place chicken skin side up and sear until brown. This should take about 2-3 minutes.Flip chicken pieces and do the same to brown.'),
('20941', '3', 'Add water and layer with bay leaves, peppercorns, onions, carrots, celery, turnips, parsnips and the remainder of salt. Bring this to a rapid boil, place the tied parsley and dill in the pot.'),
('20941', '4', 'Add the remainder of butter (1 tbsp) to soup if a white foam appears. This is a little trick to help it to dissipate, in order to achieve a clear broth.Reduce heat to a medium simmer and cook for 1 hour. Using a slotted spoon, remove dill and parsley bunch, and discard.'),
('20941', '5', 'Remove parsnips, turnips, bay leaves, peppercorns, onions and celery, and discard.'),
('20941', '6', 'Remove skin from chicken and discard.'),
('20941', '7', 'Transfer chicken pieces to a soup tureen, and then carrots.Finally, skim fat from broth and pour in the soup tureen. Top with fresh chopped dill and parsley. Cover to keep warm.In a mixing bowl, add matzo and baking powder, mix well, and set aside.'),
('20941', '8', 'Whisk eggs, salt, white pepper, dill, chicken stock and vegetable oil.'),
('20941', '9', 'Pour this into the matzo meal mixture and combine well. Do not be deterred by its soggy appearance. Cover and refrigerate for 30 minutes.Bring soup stock to a boil. Fill a small bowl with water for wetting hands.'),
('20941', '10', 'Remove mixture from refrigerator, wet hands and mold each matzo ball to tennis-ball size.'),
('20941', '11', 'Add to pot of water or stock, they will pop up to the top. Cover and simmer on low for 25 minutes, be sure to flip them in while cooking.'),
('20941', '12', 'Let them rest in soup stock to expand and absorb broth for 20 minutes before serving. Ladle in soup bowls and serve.For Matzo Balls: In a mixing bowl, add matzo and baking powder, mix well, and set aside.'),
('20941', '13', 'Whisk eggs, salt, white pepper, dill, chicken stock and vegetable oil.'),
('20941', '14', 'Pour this into the matzo meal mixture and combine well. Do not be deterred by its soggy appearance. Cover and refrigerate for 30 minutes.Bring soup stock to a boil. Fill a small bowl with water for wetting hands.'),
('20941', '15', 'Remove mixture from refrigerator, wet hands and mold each matzo ball to tennis-ball size.'),
('20941', '16', 'Add to pot of water or stock, they will pop up to the top. Cover and simmer on low for 25 minutes, be sure to flip them in while cooking.'),
('20941', '17', 'Let them rest in soup stock to expand and absorb broth for 20 minutes before serving. Ladle in soup bowls and serve.'),
('20947', '1', 'Preheat oven to 42'),
('20947', '2', 'Place 8 thyme sprigs, beets, carrots, and turnips in a large bowl.'),
('20947', '3', 'Drizzle with 1 tablespoon oil. sprinkle with 1/4 teaspoon salt and 1/4 teaspoon pepper. Toss to coat. Arrange vegetables in a jelly-roll pan.'),
('20947', '4', 'Bake at 425 for 45 minutes or until vegetables are tender and begin to brown, stirring occasionally.'),
('20947', '5', 'Place remaining 8 thyme sprigs, garlic, onions, and fennel in a bowl.'),
('20947', '6', 'Drizzle with remaining 1 tablespoon oil. sprinkle with remaining 1/4 teaspoon salt and 1/4 teaspoon pepper. Arrange vegetables in a single layer in a jelly-roll pan.'),
('20947', '7', 'Bake at 425 for 25 minutes or until vegetables are tender and begin to brown, stirring occasionally.'),
('20947', '8', 'Combine beet mixture and onion mixture. sprinkle with chopped thyme.'),
('20951', '1', 'In a large pot, blanch the marrow bone (if using) in boiling water for a few minutes. Throw out the water. Bring plenty of fresh water to the boil in the pot. Put in the bone and the meat, whole, on top. Bring to the boil again, remove the scum, and add the rest of the ingredients, also whole. Barely simmer for at least 3 hours, keeping the meat covered with water.'),
('20951', '2', 'Remove as much of the fat as possible from the surface with a spoon, and mop up what is left by trailing a rolled-up paper towel over the surface.'),
('20951', '3', 'var article'),
('20951', '4', 'Type_27_data = {}.'),
('20951', '5', 'article'),
('20951', '6', 'Type_27_data.init_step_by_step_images = 0.'),
('20952', '1', 'Pour 6 cups water and beer into large deep roasting pan.'),
('20952', '2', 'Add coarse salt. stir until dissolved.'),
('20952', '3', 'Add sugar. stir until dissolved. If desired, stir in Insta Cure No.'),
('20952', '4', 'Mix in pickling spices. Pierce brisket all over with tip of small sharp knife. Submerge brisket in liquid, then top with heavy platter to weigh down. Cover and refrigerate 4 days.'),
('20952', '5', 'Remove brisket from brine. Stir liquid to blend. Return brisket to brine. top with heavy platter. Cover. refrigerate 4 days.'),
('20952', '6', 'Remove brisket from brine. Rinse with cold running water.'),
('20953', '1', 'Heat 1 1/2 tablespoons oil in a Dutch oven over medium-high heat.'),
('20953', '2', 'Place flour in a shallow dish. Sprinkle beef with 1/2 teaspoon salt. dredge beef in flour.'),
('20953', '3', 'Add half of beef to pan. cook 5 minutes, turning to brown on all sides.'),
('20953', '4', 'Remove beef from pan with a slotted spoon. Repeat procedure with remaining 1 1/2 tablespoons oil and beef.'),
('20953', '5', 'Add onion to pan. cook 5 minutes or until tender, stirring occasionally. Stir in tomato paste. cook 1 minute, stirring frequently. Stir in broth and beer, scraping pan to loosen browned bits. Return meat to pan. Stir in remaining 1/2 teaspoon salt, raisins, caraway seeds, and pepper. bring to a boil. Cover, reduce heat, and simmer 1 hour, stirring occasionally. Uncover and bring to a boil. Cook 50 minutes, stirring occasionally.'),
('20953', '6', 'Add carrot, parsnip, and turnip. Cover, reduce heat to low, and simmer 30 minutes, stirring occasionally. Uncover and bring to a boil. cook 10 minutes or until vegetables are tender. Sprinkle with parsley.'),
('20955', '1', 'Watch how to make this recipe.'),
('20956', '1', 'Place meat in stockpot.'),
('20956', '2', 'Add broth. bring to boil on medium-high heat.  Cover. simmer on low heat 1 hour, skimming surface occasionally.'),
('20956', '3', 'Cook carrots, onions, jalapeo peppers and crushed red pepper in dressing in large skillet on medium heat 10 min., stirring occasionally.'),
('20956', '4', 'Add to ingredients in stockpot. stir.'),
('20956', '5', 'Add all remaining ingredients except mint. stir.  Simmer on medium-low heat 20 min. or just until potatoes are tender.  (Do not overcook.)'),
('20956', '6', 'Spoon 1 piece of meat in each of 8 bowls.  Ladle broth and vegetables over meat.  Sprinkle with mint.'),
('20958', '1', 'In a large shallow dish, mix together 1 tablespoon each of the basil and parsley, 1 teaspoon of the tarragon, 1 tablespoon of the olive oil and 1 minced garlic clove. Rub the herb mixture all over the lamb chops and season them generously with salt and pepper.'),
('20958', '2', 'Let the lamb chops stand at room temperature for at least 30 minutes and for up to 2 hours.'),
('20958', '3', 'Meanwhile, preheat the oven to 42'),
('20958', '4', 'In a large skillet, bring the water to a boil.'),
('20958', '5', 'Add the carrots and a pinch of salt and cover. Simmer the carrots over low heat for 4 minutes.'),
('20958', '6', 'Add the turnip, cover and cook until both vegetables are tender, about 8 minutes.'),
('20958', '7', 'Drain the vegetables and transfer them to a plate. Return the skillet to low heat. When hot, add 2 tablespoons of the olive oil and the shiitake and season generously with salt and pepper. Cover and cook the shiitake, stirring occasionally, until lightly browned, about 4 minutes.'),
('20958', '8', 'Add the chanterelles, cover and cook until tender, about 3 minutes.'),
('20958', '9', 'Add the shallots and the remaining 2 garlic cloves and cook, stirring, until fragrant, about 3 minutes.'),
('20958', '10', 'Add the carrots and turnip, cover and remove the vegetables from the heat.'),
('20958', '11', 'In a large ovenproof skillet, heat the remaining 2 tablespoons of olive oil until shimmering.'),
('20958', '12', 'Add the lamb chops and cook them over moderately high heat until browned on the bottom, about 3 minutes. Turn the lamb chops over and roast them in the oven for about 8 minutes for medium rare.'),
('20958', '13', 'Transfer the lamb chops to a plate, cover with foil and keep warm.'),
('20958', '14', 'Discard the fat from the skillet and set it over moderately high heat.'),
('20958', '15', 'Add the vermouth and cook until almost evaporated, about 3 minutes.'),
('20958', '16', 'Add the chicken stock and boil until reduced to 3/4 cup, about 3 minutes.'),
('20958', '17', 'Add any accumulated lamb juices and pour the liquid over the reserved vegetables. Stir in the cherry tomatoes and simmer until hot. Stir in the remaining 1 tablespoon each of chopped basil and parsley and 1 teaspoon of chopped tarragon. Season the ragout with salt and pepper.'),
('20958', '18', 'Spoon the vegetable ragout into shallow bowls and sprinkle with Parmesan cheese. Top each plate with a lamb chop and serve at once.'),
('20960', '1', 'Heat oil in a large saucepan over medium-high heat.'),
('20960', '2', 'Add onion and leek. saut 5 minutes.'),
('20960', '3', 'Add coriander and next 4 ingredients (through garlic). cook 1 minute, stirring constantly.'),
('20960', '4', 'Add 3 cups Simple Vegetable Stock and the next 8 ingredients (through chickpeas). bring to a boil. Cover, reduce heat, and simmer 30 minutes. Stir in parsley and honey.'),
('20960', '5', 'Remove 2/3 cup hot cooking liquid from squash mixture.'),
('20960', '6', 'Place cooking liquid and remaining 2/3 cup stock in a medium bowl. Stir in couscous. Cover and let stand 5 minutes. Fluff with a fork.'),
('20960', '7', 'Serve with lemon wedges.'),
('20961', '1', 'Pour enough water into large roasting pan to reach depth of  2 inches. set near stove.'),
('20961', '2', 'Pour enough water into large nonstick skillet to reach depth of 1 1/2 inches. add 1 teaspoon salt and bring to simmer. Crack each egg into separate custard cup. Working  with 4 eggs per batch, gently slide 1 egg at a time into simmering water in skillet. Cook just until egg whites are set, about 1 minute (yolks will be only partially cooked). Using slotted  spoon, carefully transfer eggs to prepared roasting pan with water. Reserve skillet with water. DO AHEAD: Poached eggs can be made 1 hour ahead.'),
('20961', '3', 'Let stand at room temperature.'),
('20965', '1', 'Preheat oven to 42'),
('20965', '2', 'To prepare vegetables, place first 6 ingredients in a single layer on a jelly-roll pan coated with cooking spray. Lightly coat vegetable mixture with cooking spray. Sprinkle evenly with 1/2 teaspoon salt and 1/4 teaspoon black pepper. toss.'),
('20965', '3', 'Bake at 425 for 1 hour or until browned.'),
('20965', '4', 'Transfer vegetable mixture to a large bowl.'),
('20965', '5', 'To prepare pesto, combine basil leaves and remaining ingredients in a food processor. process until smooth, scraping sides. Spoon basil mixture over vegetable mixture, and toss to coat.'),
('20967', '1', 'Preheat oven to 45'),
('20967', '2', 'Combine first 11 ingredients in a large bowl. toss well. Arrange vegetable mixture in a single layer on a jelly-roll pan coated with cooking spray.'),
('20967', '3', 'Bake at 450 for 25 minutes or until vegetables are browned and tender.'),
('20967', '4', 'Place vegetable mixture in a large bowl.'),
('20967', '5', 'Add honey and cider vinegar to vegetables, and toss well.'),
('20968', '1', 'Preheat oven to 45'),
('20968', '2', 'Combine first 6 ingredients in a 13 x 9inch baking dish coated with cooking spray, tossing well to coat.'),
('20968', '3', 'Bake at 450 for 10 minutes. Stir in syrup.'),
('20968', '4', 'Bake an additional 20 minutes or until tender and golden, stirring after 10 minutes.'),
('20970', '1', 'Heat oil in a Dutch oven over medium heat.'),
('20970', '2', 'Add onion to pan. cook 5 minutes or until tender, stirring occasionally.'),
('20970', '3', 'Add garlic and 2 teaspoons rosemary. cook 1 minute, stirring occasionally. Stir in potato and next 5 ingredients (through 2 cups water). Bring to a simmer. cook, covered, 20 minutes or until vegetables are tender.'),
('20970', '4', 'Place 3 cups vegetable mixture in a blender.'),
('20970', '5', 'Remove center piece of blender lid (to allow steam to escape). secure blender lid on blender.'),
('20970', '6', 'Place a clean towel over opening in blender lid (to avoid splatters). Blend until smooth. Return to pan. Stir in cream, pepper, and salt.'),
('20970', '7', 'Preheat broiler.'),
('20970', '8', 'Arrange bread slices on a baking sheet. Sprinkle each bread slice with 1 tablespoon cheese. top evenly with remaining 1 teaspoon rosemary. Broil 1 minute or until cheese melts.'),
('20971', '1', 'Fill a medium-sized pan with about 2 quarts of water. Bring to a boil.'),
('20971', '2', 'Add the rice vermicelli noodles. Wait for the water to come back to a boil (about 1-2 minutes) then lower the heat to medium-low for about 8 minutes.'),
('20971', '3', 'Drain the liquid. Rinse the noodles. Set the noodles aside.'),
('20971', '4', 'Heat about 1 inch of canola oil in a skillet. Fry 3 onions and shallots in the oil, stirring frequently to prevent the onions from burning until the color is evenly golden brown.'),
('20971', '5', 'Drain on paper towels. Set aside.Bring about 7 quarts of water to a boil.'),
('20971', '6', 'Add the sliced ginger, fried onions and shallots.'),
('20971', '7', 'Add the 2 whole chickens and chicken carcasses to the onion broth. Cook for about 10-12 minutes.'),
('20971', '8', 'Remove the whole chickens from the pot.'),
('20971', '9', 'Let them cool a bit until you can handle them without discomfort. Make several deep diagonal incisions throughout the birds'' flesh.'),
('20971', '10', 'Place the chickens back in the broth.'),
('20971', '11', 'Add the daikon, whole onion, rock sugar and mushroom seasoning salt. Bring to one more boil and simmer for another 30 minutes until the whole onion and daikon are soft and tender. Sprinkle freshly ground black pepper to taste.Season with salt. Bring back to a boil, then immediately lower the heat to a gentle boil. Cook for another 10-12 minutes.'),
('20971', '12', 'Remove the chickens and shred the meat. Set the meat aside on a platter.In a different deep saucepan, bring about 1 quart of the chicken broth to a boil.'),
('20971', '13', 'Add the sliced bamboo shoots and cook until tender (about 10-15 minutes).Be organized. Line up 8 large bowls.'),
('20971', '14', 'Place some vermicelli noodles, chopped white onion, shredded cabbage, green onions, bean sprouts, cilantro and the other Vietnamese herbs in each bowl.'),
('20971', '15', 'Add the boiled, drained rice noodles, following with the boiling broth with sliced bamboo shoots. Top with shredded chicken.'),
('20971', '16', 'Serve with chili garlic sauce, Thai basil, mint, jalapeno peppers and the bird chiles.'),
('20971', '17', 'Drizzle some nc mm to the broth to finish.Dig in!'),
('20972', '1', 'In a large pot, combine the onion and half each of the leeks, celery and carrots. Set the beef shanks and rump roast on top of the vegetables. Wrap the parsley, thyme and bay leaves in a piece of moistened cheesecloth and tie into a bundle.'),
('20972', '2', 'Add the bundle to the pot along with the peppercorns and 1 tablespoon of kosher salt.'),
('20972', '3', 'Add 2 of the marrow bones and the water. Bring to a boil over high heat, then reduce the heat to low, cover partially and simmer, skimming occasionally, until the rump roast is very tender, about 2 1/2 hours.'),
('20972', '4', 'Transfer the shanks and roast to a large bowl and cover. Strain the broth and return it to the pot. Boil over high heat until reduced to 10 cups, about 45 minutes. skim off the fat.'),
('20972', '5', 'Add the remaining leeks, celery and carrots to the broth along with the parsnips, turnips and rutabagas. Cover and simmer over low heat until the vegetables are just tender, 30 minutes.'),
('20972', '6', 'Add the remaining 6 to 8 marrow bones and the potatoes. Cover and simmer until the potatoes are tender, 40 minutes.'),
('20972', '7', 'Untie the rump roast and cut it across the grain into 6 to 8 slices.'),
('20972', '8', 'Cut the shank meat into 2-inch chunks. add the meats to the pot and simmer until heated through. Season with salt and pepper. Ladle the broth into shallow bowls.'),
('20972', '9', 'Add the meats, marrow bones and vegetables and serve, passing horseradish, mustard and sour cream at the table.'),
('20973', '1', 'Season turnips with salt and pepper. In a large ovenproof saute pan, heat butter until starting to brown.'),
('20973', '2', 'Add turnips and toss to coat well.'),
('20973', '3', 'Add poppy seeds and saute until light golden brown, about 8 to 9 minutes.'),
('20973', '4', 'Add paprika and toss to coat.'),
('20973', '5', 'Add vinegar and cook until evaporated, 4 to 5 minutes, remove from heat and serve.'),
('20976', '1', 'Cut fennel stalks flush with bulb, discarding them, and trim off any tough outer layers from bulb. Chop fennel into 1/2-inch pieces.'),
('20976', '2', 'Cook pancetta in oil in a 7- to 9-quart heavy pot over moderate heat, stirring occasionally, until just beginning to brown, 5 to 7 minutes. Stir in fennel, onion, turnip, carrots, and cabbage and cook, stirring occasionally, until cabbage is wilted, 5 to 7 minutes.'),
('20976', '3', 'Add cheese rind, squash, potato, thyme sprigs, bay leaf, salt, and water and bring to a boil.'),
('20976', '4', 'Reduce heat and simmer, uncovered, 10 minutes.'),
('20976', '5', 'Add lima beans, green beans, and cannellini and simmer until vegetables are tender, about 5 minutes. Discard cheese rind, thyme sprigs, and bay leaf. Stir in spinach and season with salt and pepper.'),
('20980', '1', 'Bring 6 cups water and bouillon base to boil in large pot over medium-high heat, stirring to dissolve bouillon.'),
('20980', '2', 'Add carrots and next 5 ingredients. Simmer until vegetables are tender, about 7 minutes.'),
('20980', '3', 'Drain. reserve vegetables and broth.'),
('20980', '4', 'Melt butter in same pot over medium heat.'),
('20980', '5', 'Add onions. saut until beginning to brown, about 10 minutes.'),
('20980', '6', 'Mix in garlic and rosemary. stir 2 minutes.'),
('20980', '7', 'Add flour. stir 1 minute. Gradually whisk in reserved broth, then cream and Sherry. Cook until sauce is thick and reduced to 4 cups, whisking often, about 8 minutes.'),
('20980', '8', 'Mix in reserved vegetables and parsley. Season with salt and pepper.'),
('20980', '9', 'Transfer filling to buttered 13x9x2-inch baking dish. DO AHEAD: Can be made 2 days ahead. Cover with foil. chill.'),
('20980', '10', 'Preheat oven to 400F.'),
('20980', '11', 'Bake filling, covered, until bubbling, about 50 minutes. Meanwhile, prepare biscuits.'),
('20986', '1', 'Preheat oven to 35'),
('20986', '2', 'Combine the first 6 ingredients in a shallow 2-quart baking dish coated with cooking spray. Top with butter.'),
('20986', '3', 'Bake at 350 for 1 1/2 hours or until tender, stirring after 45 minutes.'),
('20990', '1', 'Place flour in a shallow dish. Sprinkle beef evenly with salt and pepper. dredge in flour.'),
('20990', '2', 'Heat a large skillet over medium-high heat.'),
('20990', '3', 'Add oil to pan. swirl to coat.'),
('20990', '4', 'Add beef. saut 10 minutes, turning to brown on all sides.'),
('20990', '5', 'Place turnip greens in a 6-quart electric slow cooker. top with parsnips, potatoes, and onions.'),
('20990', '6', 'Transfer beef to slow cooker.'),
('20990', '7', 'Add tomato paste to skillet. cook 30 seconds, stirring constantly. Stir in wine and broth. bring to a boil, scraping pan to loosen browned bits. Cook 1 minute, stirring constantly.'),
('20990', '8', 'Pour broth mixture into slow cooker.'),
('20990', '9', 'Place peppercorns and next 4 ingredients (through parsley) on a double layer of cheesecloth. Gather edges of cheesecloth together. secure with twine.'),
('20990', '10', 'Add cheesecloth bundle to slow cooker. Cover and cook on LOW 8 hours or until beef and vegetables are tender. Discard cheesecloth bundle.'),
('20990', '11', 'Remove roast from slow cooker. slice.'),
('20990', '12', 'Serve with vegetable mixture and cooking liquid.'),
('20990', '13', 'Garnish with thyme sprigs, if desired.'),
('20991', '1', 'Melt 2 tablespoons butter in heavy large pot over medium-high heat.'),
('20991', '2', 'Add onion and saut until deep golden, about 7 minutes.'),
('20991', '3', 'Add next 7 in-gredients and stir 1 minute.'),
('20991', '4', 'Add broth and 1 cup water. bring to boil. Reduce heat, cover and simmer until vegetables are almost tender, about 10 minutes. Stir in cream, shiitake mushrooms, peas and chives. Season to taste with salt. Bring mixture to simmer.'),
('20991', '5', 'Mix remaining 1 tablespoon butter and flour in small bowl to blend. Stir into vegetable mixture. simmer until mixture thickens slightly, about 5 minutes. Divide vegetable mixture among six 2-cup souffl or baking dishes. set aside. (Can be prepared 1 1/2 hours ahead.'),
('20991', '6', 'Let stand at room temperature.)'),
('20993', '1', 'Wash all the chicken parts under cold water.'),
('20993', '2', 'Place in a 6- to 8-quart pressure cooker with 8 cups of water. Slowly bring to almost boiling, skimming off the scum as it rises to the surface. When water is clear and free of scum, add the remaining ingredients.'),
('20993', '3', 'Seal the cooker.'),
('20993', '4', 'Place the pressure regulator firmly on the vent pipe. When pressure regulator begins to gently rock, start timing. Cook for 30 minutes with pressure regulator, rocking- slowly and continuously, or follow the manufacturers directions for your cooker.'),
('20993', '5', 'Allow pressure to drop gradually with the lid in place until all the steam has left the cooker. Do not place the cooker under cold running water to reduce the pressure. Follow the manufacturers directions for, cooling. Cool the stock to room temperature, then strain through several layers of cheesecloth. Discard the vegetables, but reserve the chicken parts and gizzards for another use. Refrigerate the stock overnight for easy removal of excess fat.'),
('20993', '6', 'var article'),
('20993', '7', 'Type_27_data = {}.'),
('20993', '8', 'article'),
('20993', '9', 'Type_27_data.init_step_by_step_images = 0.'),
('20996', '1', 'Preheat oven to 450F. Toss fennel bulbs, carrots, turnips, potatoes, and 1/4 cup oil in large bowl. Sprinkle generously with salt and pepper.'),
('20996', '2', 'Transfer to large rimmed baking sheet. Roast until tender and brown around edges, about 1 hour.'),
('20996', '3', 'Finely mince 1/4 cup parsley and garlic together.'),
('20996', '4', 'Transfer to small bowl. Stir in paprika, saffron and 1 teaspoon salt.'),
('20996', '5', 'Heat 3 tablespoons oil in large skillet over medium-high heat.'),
('20996', '6', 'Add onion and saute until soft, about 8 minutes.'),
('20996', '7', 'Add tomatoes. saute 2 minutes.'),
('20996', '8', 'Add rice and parsley mixture. stir 2 minutes. Stir in broth, water, and wine. bring to boil. Reduce heat to low, cover and simmer 15 minutes. Stir in asparagus, garbanzo beans, and roasted vegetables. Increase heat to medium-low. cover and simmer until liquid is absorbed, stirring often, about 20 minutes. Season paella with salt and pepper.'),
('20996', '9', 'Transfer to large platter. Sprinkle with fennel fronds and remaining parsley.'),
('20997', '1', 'Cook the pancetta in a large heavy pot over medium heat until most of the fat is rendered, 8 to 10 minutes.'),
('20997', '2', 'Drain the beans, add them to the pot, along with enough water to cover them by 2 inches, and bring to a boil. Skim off the foam, then lower the heat and simmer gently, partially covered, for 45 minutes to 1 hour, or until the beans are beginning to soften.'),
('20997', '3', 'Add the onion, potatoes, and turnips and cook for 20 minutes, or until the vegetables are softened.'),
('20997', '4', 'Add the chorizo and greens and cook for 10 minutes, or until the greens are tender.'),
('20997', '5', 'var article'),
('20997', '6', 'Type_27_data = {}.'),
('20997', '7', 'article'),
('20997', '8', 'Type_27_data.init_step_by_step_images = 0.'),
('20998', '1', 'MELT the butter in a 4-quart pot over medium heat.'),
('20998', '2', 'Add the vegetables and cook for 15 to 20 minutes, until the vegetables soften. (If youre using canned beets, add them after the other vegetables have softened.)'),
('20998', '3', 'ADD the beef broth and bring the soup to a simmer. Simmer slowly for 10 minutes. Reach in with a spoon and sample a few of the vegetables to make sure they have softened thoroughly.'),
('20998', '4', 'SPRINKLE in the wine vinegar to taste. Season with salt and pepper.'),
('20998', '5', 'SERVE in hot bowls. Pass the sour cream, chopped dill, and sliced black bread at the table.SUGGESTIONS AND VARIATIONS You can turn this simple borscht into a puree or a simple cream soup by putting it in a blender and straining itand, if you like, finishing it with a cup of heavy cream. In the summer, cold pureed borscht makes a delightful cold soup. (See also the cream of beet soup .)'),
('20998', '6', 'var article'),
('20998', '7', 'Type_27_data = {}.'),
('20998', '8', 'article'),
('20998', '9', 'Type_27_data.init_step_by_step_images = 0.'),
('21001', '1', 'Put the ingredients in a blender. Blend until the consistency of a fine paste, scraping down the sides of the bowl as necessary.'),
('21001', '2', 'Rub all but  cup of the curry paste onto the lamb shanks. Cover both the lamb shanks and the curry paste and refrigerate overnight.'),
('21001', '3', 'Heat half the oil in a large skillet over high heat. Season the lamb with salt and pepper and add to the pan. Sear until nicely browned, then turn and sear the other side.'),
('21001', '4', 'Remove from the heat and set aside.'),
('21001', '5', 'Put the lemongrass, galangal, chiles, lime leaves, and  cup of the cilantro leaves in a piece of cheesecloth. Wrap and secure the sachet with kitchen string.'),
('21001', '6', 'Heat the remaining 1 tablespoons oil in a large deep pot or Dutch oven, which can later be covered, over medium heat.'),
('21001', '7', 'Add the onion and cook until softened, about 5 minutes.'),
('21001', '8', 'Add the reserved curry paste and cook, stirring occasionally, until fragrant, about 3 minutes.'),
('21001', '9', 'Add the lamb shanks, stock, 1 cup of the coconut milk, and the sachet. Bring to a boil and then lower the heat and simmer, partially covered, until the meat is falling off the bone, at least 1 hour and probably longer.'),
('21001', '10', 'Remove the meat to another platter, cover, and refrigerate until serving time.'),
('21001', '11', 'Remove the sachet and chill the sauce, covered, in the refrigerator. When it has chilled, remove the fat with a spoon.'),
('21001', '12', 'Meanwhile, fill a large bowl with water and ice and set aside. Bring a small pot of water to a boil and add the remaining cilantro leaves (reserving the sprigs for garnish). As soon as the water returns to a boil, drain the leaves and transfer to the ice water, reserving the cooking liquid. When cold, drain again, and put the leaves in a blender with 2 tablespoons of the reserved liquid. Pure until smooth and set aside.'),
('21001', '13', 'Fill a large bowl with water and ice and set aside. Bring a large pot of water to a boil.'),
('21001', '14', 'Add the carrots, turnips, scallions, peas, and beans and cook just until tender, about 3 minutes. Immediately transfer to the ice water, drain, and set aside.'),
('21001', '15', 'Bring the skimmed sauce back to a steady simmer in a large saucepan.'),
('21001', '16', 'Add the meat and eggplant and cook until the meat is reheated and the eggplant tender, about 15 minutes. Stir in the cilantro pure and remaining  cup coconut milk.'),
('21001', '17', '. Melt the butter in a skillet over medium heat.'),
('21001', '18', 'Add the carrots, turnips, scallions, peas, and beans, season to taste with salt, and saut to reheat.'),
('21001', '19', 'Put the lamb in the center of the serving plates. Spoon the eggplant and green curry sauce and the sauted vegetables around the lamb, garnish with cilantro sprigs, and serve.'),
('21001', '20', 'var article'),
('21001', '21', 'Type_27_data = {}.'),
('21001', '22', 'article'),
('21001', '23', 'Type_27_data.init_step_by_step_images = 0.'),
('21002', '1', 'Preheat the oven to 400F. Cook the honey in a large heavy skillet over medium heat until it is thick and dark with large bubbles, about 10 minutes. Stir in the carrots, parsnips, turnips, rutabagas, and onions and cook until the vegetables are deeply glazed, 8 to 10 minutes.');