INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('6103', '7', 'The event came to a close with us being given Chef Samuelsson''s new cookbook, New American Table, as a parting gift. The thick tomb is chocked full of exciting recipes that I can''t wait to try at home. I even hung around after the event to have my book signed by a very gracious and smiling Chef Samuelsson.Thank you to Buick, Food & Wine, Travel + Leisure and everybody who worked the event for making it such a fantastic foodie occasion.Chef Marcus Samuelsson''s Shrimp & Red Grits'),
('6103', '8', 'Serves 4 people'),
('6103', '9', 'Cooking time: about 30 minutes'),
('6103', '10', 'Print Recipe'),
('6103', '11', 'Ingredients1 red onion, finely chopped4 garlic cloves, minced1 teaspoon paprika powder1 teaspoon chili powder1/2 cup olive oil1 cup grits1 bay leaf1 cup canned crushed tomatoes1 cup corn1/2 cup white wine3 cups waterjuice from 2 lemons12 U-12 shrimp, peeled and de-veined1 tablespoon chopped parsley1 tabelspoon chopped cilantrosalt and pepper8 cherry tomatoes, halved'),
('6103', '12', 'Add the onion, garlic, half the dry spices and half the olive oil in a pan.'),
('6103', '13', 'Add the grits and bay leaf, saute for 30 seconds.'),
('6103', '14', 'Add the canned tomato.'),
('6103', '15', 'Add corn.'),
('6103', '16', 'Add half the white wine and water.'),
('6103', '17', 'Let simmer for 25 minutes. In a bowl, add half the lemon juice, a tablespoon of the olive oil, remaining spices and shrimp.'),
('6103', '18', 'Let sit for 15 minutes.In a pan, saute the shrimp and remaining garlic on high heat for 3 minutes. Toss in remaining lemon juice, remaining white wine, chopped parsley and chopped cilantro. Season with salt and pepper, to taste.'),
('6103', '19', 'Add cherry tomatoes and serve.To serve, place 2 tablespoons of grits in a bowl. Top with 3 shrimp per bowl.Photo Gallery:The Bazaar''s Executive Chef Jorge Chicas'),
('6103', '20', 'Chef Chicas Making Watermelon Skewers'),
('6103', '21', 'Liquid Olives in Olive Oil"Old Way" Olives'),
('6103', '22', 'Ingredients for Liquid Olives'),
('6103', '23', 'Ginger Gin Sour "Mocktail"'),
('6105', '1', 'PREP: Chop white and green parts of scallions. Finely chop garlic. Peel and devein shrimp.'),
('6105', '2', 'Preheat oven to 400F.'),
('6105', '3', 'Heat olive oil in a large ovenproof skillet over medium heat.'),
('6105', '4', 'Add scallions and garlic and cook, stirring often, until scallions wilt, about 2 minutes.'),
('6105', '5', 'Add tomatoes and their juice and bring to a boil. Cook until tomato juices thicken, about 5 minutes. Season with freshly ground pepper to taste.'),
('6105', '6', 'Remove from heat and stir in shrimp. Sprinkle with feta cheese.'),
('6105', '7', 'Bake until cheese melts and shrimp are firm and opaque, about 10 minutes. Sprinkle with dill and serve hot.'),
('6105', '8', 'var article'),
('6105', '9', 'Type_27_data = {}.'),
('6105', '10', 'article'),
('6105', '11', 'Type_27_data.init_step_by_step_images = 0.'),
('6106', '1', '1 In a medium bowl beat together the cream cheese and mayonnaise until smooth.'),
('6106', '2', 'Add the lemon juice and lemon zest. Beat until smooth (you may need to use a whisk.)2 If you have a food processor, pulse together the shrimp and the cream cheese mixture, three 1-second pulses. If not, or if you just don''t want to deal with the food processor, chop up the shrimpfine to medium chopand mix into the cream cheese.3 Return to the bowl and stir in the scallions and parsley.'),
('6106', '3', 'Add the hot sauce and black pepper to taste.'),
('6106', '4', 'Add more lemon juice to taste.Keep chilled.'),
('6106', '5', 'Serve with crackers or crudite.'),
('6108', '1', 'Add the clam juice to 4 cups of water in a pot, heat until steamy. Do not let it boil. 2 In separate pot (thick-bottomed), heat 2 tablespoons butter over medium heat, and saut the minced shallots for 2-3 minutes, until just translucent.3'),
('6108', '2', 'Add the rice to the pot. Stir-fry the rice for 2-3 minutes, until all the grains are well coated in butter and are beginning to toast. 4 Increase the heat to high and add the white wine. With a wooden spoon, stir the rice vigorously. Once the wine boils, turn the heat down until the wine is just simmering gently. Stir almost constantly. You are doing this to agitate the rice, which releases its starch and creates the creamy sauce you want in a risotto. 5 When the wine is almost cooked away  under no circumstances should you let the rice sizzle on the bottom of the pot  pour in two ladles of the hot clam broth-water mixture. Stir well to combine, and add a healthy pinch of salt. 6 Stirring almost constantly, let this liquid reduce until it is almost gone, then add another ladle of broth. Continue this until the sauce coats the back of a spoon. Taste the spoon and see if the risotto needs salt. If so, add a small pinch. This much risotto rice should need about 4-5 cups of liquid total (including the wine) to come together, so start tasting the rice at the 3rd cup. If it is almost there  firm in the center but translucent on the outside, and fully surrounded with a creamy sauce  add one more cup of broth, stir well, and taste one more time for salt. (If not, you have old rice and youll need to go one more cup and let it cook away.) 7 Now add in the shrimp, the parsley, and the remaining tablespoon of butter. Stir constantly until this last cup of broth is about half gone: Remember you want this risotto to be loose and creamy. Right before you serve, add in the lemon zest and serve at once. Best served with bowls and spoons rather than plates and forks.'),
('6109', '1', '1 In a large pot, bring to a boil 4 quarts of water, salted with 2 Tbsp salt.'),
('6109', '2', 'Add the shrimp and cook for 1 minute to 2 minutes max, depending on size of shrimp. (Over-cooking the shrimp will turn it rubbery.)'),
('6109', '3', 'Remove shrimp with a slotted spoon and place into a bowl of ice water to stop the cooking.2'),
('6109', '4', 'Drain the shrimp.'),
('6109', '5', 'Cut each piece of shrimp in half, or into inch-long pieces.'),
('6109', '6', 'Place shrimp in a glass or ceramic bowl.'),
('6109', '7', 'Mix in the lime and lemon juice. Cover and refrigerate for a half hour.3'),
('6109', '8', 'Mix in the chopped red onion and serrano chile. Refrigerate an additional half hour.4 Right before serving, add the cilantro, cucumber, and avocado.'),
('6111', '1', 'Coat hot pan with the 1 T grapeseed oil and 1 T butter and 2 cloves of crushed garlic. On medium-high heat, quickly cook shrimp till tender (about 30 seconds of each side).'),
('6111', '2', 'Remove from pan. Season with fresh cracked pepper and a dash of sea salt.Coat hot pan with 2 T sesame oil and add 2 cloves of crushed garlic. Cook stems on medium heat until tender (@ 30 sec  1 min.).'),
('6111', '3', 'Remove from heat, then add mustard leaves and stir until leaves are slightly wilted. For broader and tougher mustard leaves, cook with the heat on until leaves are tender to taste (approx. 1 min.)'),
('6111', '4', 'Serve shrimp on top of mustard greens, then dress with about 1 1/2 T of nuoc cham dressing.'),
('6112', '1', 'Cut all tomatoes into 1/3-inch cubes. place in large bowl.'),
('6112', '2', 'Add 1 teaspoon fleur de sel. toss.'),
('6112', '3', 'Let stand 15 minutes.'),
('6112', '4', 'Transfer tomatoes to strainer set over large bowl. let stand 45 minutes to drain well, tossing often.'),
('6112', '5', 'Transfer tomatoes to medium bowl. stir in chopped basil, 1 tablespoon olive oil, garlic, and shallot. Season with fleur de sel and ground black pepper.'),
('6112', '6', 'Line six 3/4-cup ramekins or custard cups with plastic wrap, leaving long overhang. Fill each ramekin with scant 1/2 cup tomato mixture. press to compact. Cover with plastic overhang, pressing firmly. DO AHEAD: Can be made 2 hours ahead.'),
('6112', '7', 'Let stand at room temperature.'),
('6112', '8', 'Prepare barbecue (medium-high heat). Open up plastic wrap on ramekins. Invert 1 ramekin onto each of 6 plates, releasing tomato mixture.'),
('6112', '9', 'Brush shrimp with olive oil. sprinkle with fleur de sel and pepper. Grill shrimp, shell side down, 1 1/2 minutes. Turn shrimp over and  grill just until opaque in center, about 1 1/2 minutes longer. Arrange 2 shrimp halves atop tomatoes on each plate.'),
('6112', '10', 'Drizzle remaining 1 tablespoon olive oil over tomatoes, garnish with whole basil leaves, and serve.'),
('6114', '1', 'Process or blend the shrimp with the garlic, scallions, salt, flour, sherry, and enough water to make a thick batter.'),
('6114', '2', 'Let stand, covered with plastic film, for 1 hour. Then fry, in drops of 1 heaping teaspoon, into the oil poured to a depth of 2 inches in a pan, for about 1 minute each side, or until golden brown.'),
('6114', '3', 'Drain on paper towels.'),
('6116', '1', 'Combine the olive oil and the lemon zest in a small bowl and reserve.For the pasta:Bring a large pot of salted water to a boil over high heat.'),
('6116', '2', 'Add the pasta and cook until tender but still firm to the bite, stirring occasionally, about 8 to 10 minutes.'),
('6116', '3', 'Drain pasta, reserving 1 cup of the cooking liquid. (I always forget to do this!!)Meanwhile, in a large, heavy skillet warm the olive oil over medium heat.'),
('6116', '4', 'Add the shallots and garlic and cook for 2 minutes.'),
('6116', '5', 'Add the shrimp and cook until pink, about 5 minutes.'),
('6116', '6', 'Add the cooked linguine, lemon juice, lemon zest, salt, and pepper. Toss to combine. Turn off the heat and add the arugula. Using a mesh sieve, strain the lemon zest out of the reserved lemon olive oil and add the oil to the pasta. The zest can be discarded.'),
('6116', '7', 'Add the chopped parsley to the pasta and toss to combine.'),
('6116', '8', 'Serve immediately.'),
('6117', '1', 'Watch how to make this recipe.'),
('6117', '2', 'In a large pot, bring the beer, water, shrimp boil seasoning, salt, peppercorns and the juiced lemon halves to a boil over medium heat. Allow mixture to boil covered for 10 minutes. In the meantime, melt butter in a small saucepan and add the lemon juice.'),
('6117', '3', 'Add the shrimp to the pot of boiling beer, cover, and turn off heat. Check shrimp after 3 minutes for a pink color throughout. Using a slotted spoon, remove the shrimp and transfer to serving bowls.'),
('6117', '4', 'Add 1/2 cup of the beer boiling liquid to the butter and simmer for 2 minutes, then transfer to small serving bowls.'),
('6117', '5', 'Serve the warm shrimp with the butter dipping sauce on the side, and don''t forget the empty bowls for the shrimp shells. Enjoy!'),
('6117', '6', 'Serving Suggestion: I love a great loaf of French bread with this to sop up the yummy sauce!'),
('6118', '1', 'In a large skillet, heat 4 teaspoons of olive oil over high heat.'),
('6118', '2', 'Add the shrimp and cook until opaque throughout, turning occasionally, about 3 minutes.'),
('6118', '3', 'Transfer to a bowl and set aside.To the same skillet, add:2 teaspoons olive oil2 cloves garlic, minced'),
('6118', '4', 'Cook over medium heat until fragrant, about 30 seconds.'),
('6118', '5', 'Add:A 14.5-oz. can diced tomatoes (plus juice)2 cups water'),
('6118', '6', 'Bring to a boil. Reduce the heat and simmer, stirring occasionally, until the tomatoes have softened and are saucy, about 15 minutes.'),
('6118', '7', 'Remove the sauce from the heat and stir in:1 pint cherry or grape tomatoes, halved'),
('6118', '8', 'Meanwhile, in a large pot of boiling salted water, cook the pasta until al dente according to package instructions.'),
('6118', '9', 'Drain and return the pasta to the pot.'),
('6118', '10', 'Add the tomato sauce, shrimp and basil and season with salt and pepper. Toss.'),
('6118', '11', 'Serve immediately, and garnish with fresh basil leaves.I brought this deliciousness with me to work for the following two days after making it and beginning at 9:30 each morning, I could not wait to eat lunch.Heart surgery, however, I can most definitely wait for.Click here for a printable recipe!'),
('6120', '1', 'Combine all ingredients, except the shrimp, in a microwave-safe bowl and stir until fully incorporated. Cover and heat for 40-60 seconds. Stir well, taste and adjust spiciness to taste. Divide the sauce into 2 small bowls--one for the grill, and one for dipping. Cover the second bowl and set aside. This sauce may need to be reheated before serving. Thread  shrimp onto skewers, brush with some sauce, then grill over medium-high heat. Keep basting the shrimp with sauce until cooked. Depending on the size of shrimp, cook 2-3 minutes per side. Watch for flare-ups from the honey and molasses on the grill.'),
('6120', '2', 'Serve as an appetizer with the second bowl of sauce for dipping. Or serve over white rice for an entree.'),
('6121', '1', '1 If you are starting with frozen raw shrimp, defrost them by placing them in a bowl of ice water until defrosted.  Then poach the raw shrimp for 1 to 2 minutes in boiling water, remove from pan with a slotted spoon, and rinse under cold water to stop the cooking.  If you are starting with frozen cooked shrimp, you can defrost them in a bowl of ice water or lemon juice with ice.2'),
('6121', '2', 'Place strained cooked shrimp in a bowl.'),
('6121', '3', 'Add lime or lemon juice, some chopped fresh jalapeno or serrano chile and/or a dash of chile powder (can also use chipotle chiles or chipotle chili powder) to desired level of heat, green onion, and cilantro.  Sprinkle with salt and pepper.'),
('6121', '4', 'Let marinate for 10 to 30 minutes.  Strain out the juice.3'),
('6121', '5', 'Heat a cast iron or stick-free skillet on medium high.'),
('6121', '6', 'Add a small amount of oil (about 1/2 teaspoon) and spread it around the bottom of the pan with a spatula (you could use butter as well).'),
('6121', '7', 'Place one flour tortilla on the skillet.  Flip the tortilla over a few times, 10 seconds between flips. Air pockets should begin to form within the tortilla.'),
('6121', '8', 'Remove the tortilla and repeat with the second tortilla.  Leave the second tortilla in the pan and reduce the heat to medium.4 Sprinkle the tortilla with the grated cheese.  Distribute the shrimp mixture on top of the cheese.'),
('6121', '9', 'Place the other tortilla on top. Using two spatulas (one to hold the top in place) flip the quesadilla over when the bottom tortilla is nicely toasted and the cheese has begun to melt.'),
('6121', '10', 'Remove the quesadilla from the pan when the now bottom tortilla has toasted sufficiently.You can also use just one tortilla instead of two, and fold the tortilla over itself like an omelette.5'),
('6121', '11', 'Cut like a pie into six pieces.  A pizza wheel works well for this.'),
('6121', '12', 'Place on a serving plate.'),
('6121', '13', 'Serve with avocado slices and sour cream.'),
('6121', '14', 'Garnish with chopped fresh cilantro.'),
('6123', '1', 'Finely chop garlic in food processor.'),
('6123', '2', 'Add all remaining ingredients. blend until smooth and pale green. Season sauce to taste with salt and pepper.'),
('6123', '3', 'Transfer sauce to serving bowl. Cover and refrigerate until cold. (Can be prepared 2 days ahead. Keep refrigerated.)'),
('6126', '1', 'Preheat oven to 400F. Pierce squash several times.'),
('6126', '2', 'Place on baking sheet. roast until tender, about 1 hour. Cool.'),
('6126', '3', 'Cut squash in half. discard seeds. Scoop flesh into processor. Puree until smooth. Measure 1 1/2 cups puree (reserve remaining puree for another use). DO AHEAD: Can be made 1 day ahead. Cover. chill.'),
('6126', '4', 'Place shrimp, 1 1/2 tablespoons olive oil, and 3 smashed garlic cloves in large resealable plastic bag. turn to coat. Chill 2 to 3 hours, turning bag occasionally.'),
('6126', '5', 'Stir cornmeal, 1/2 teaspoon salt, and 1/2 teaspoon pepper in medium bowl.'),
('6126', '6', 'Add shrimp. toss. Arrange in single layer on large plate.'),
('6126', '7', 'Preheat oven to 200F. Bring broth to simmer in heavy small saucepan. reduce heat to low and keep hot.'),
('6126', '8', 'Heat remaining 2 tablespoons olive oil in heavy large saucepan over medium-high heat.'),
('6126', '9', 'Add onion and cook until beginning to brown, stirring often, about 5 minutes.'),
('6126', '10', 'Add chopped garlic and 2 teaspoons thyme. stir 1 minute.'),
('6126', '11', 'Add rice and stir 1 minute.'),
('6126', '12', 'Add wine. stir until almost absorbed, about 2 minutes. Reduce heat to medium.'),
('6126', '13', 'Add 1 cup hot broth and cook until almost all liquid is absorbed, stirring often. Continue adding hot broth 1 cup at a time and stirring frequently until rice is almost tender, about 15 minutes.'),
('6126', '14', 'Meanwhile, add enough vegetable oil to heavy large skillet to reach depth of 1/4 inch.'),
('6126', '15', 'Heat oil over high heat. Working in 2 batches, fry shrimp until golden brown and cooked through, about 1 1/2 minutes per side.'),
('6126', '16', 'Transfer to paper-towel-lined baking sheet and place in oven to keep warm.'),
('6126', '17', 'Rewarm reserved 1 1/2 cups squash puree in microwave.'),
('6126', '18', 'Add warm puree to risotto and stir until rice is tender but still firm, about 2 minutes. Stir in Parmesan cheese and remaining 2 teaspoons thyme. Season with salt and pepper.'),
('6126', '19', 'Divide risotto among bowls. Top with shrimp and serve.'),
('6127', '1', 'Cook tomatillos in large pot of boiling salted water until olive-green color, about 5 minutes.'),
('6127', '2', 'Drain and transfer to blender.'),
('6127', '3', 'Add onion, jalapeno, and garlic and process tomatillo sauce until smooth.'),
('6127', '4', 'Heat 1 tablespoon oil in skillet over medium heat.'),
('6127', '5', 'Add sauce and bring to boil. Reduce heat and simmer until slightly thickened, stirring occasionally, about 5 minutes. Stir in cilantro. Season with salt and pepper. Cool to room temperature. (Can be made 1 day ahead. Chill. Bring to room temperature before using.)'),
('6127', '6', 'Prepare barbecue (medium-high heat). Toss shrimp with remaining 2 tablespoons oil in large bowl.'),
('6127', '7', 'Add ground chili, onion powder, and garlic powder. toss to combine. Sprinkle shrimp with salt and pepper. Grill shrimp until just cooked through, about 2 minutes per side.'),
('6127', '8', 'Spoon about 3 tablespoons tomatillo sauce into center of each of 6 plates. Arrange shrimp atop sauce. Sprinkle with queso fresco.'),
('6127', '9', '* Tomatillos (green tomato-like vegetables with paper-thin husks), ground New Mexican chilies, and queso fresco (also known as queso blanco) are available at Latin American markets and some supermarkets.'),
('6130', '1', 'In a medium bowl, whisk together lemon grass, garlic, chili sauce, fish sauce, sugar, olive oil, lime juice, pepper, and green onions.'),
('6130', '2', 'Add shrimp and toss to coat.'),
('6130', '3', 'Let marinate 15 minutes at room temperature or up to 1 hour in the refrigerator.'),
('6130', '4', 'Prepare a gas or charcoal grill for high heat (you can hold your hand 1 to 2 in. above grill level only 2 to 3 seconds).'),
('6130', '5', 'Brush grill with vegetable oil. Thread shrimp onto skewers and grill until curled, pink, and opaque, 2 to 3 minutes per side.'),
('6130', '6', 'Remove skewers and garnish with mint.'),
('6133', '1', 'Mix together pomegranate juice, clementine juice and pulp, garlic, ginger and sea salt in a saut pan over medium heat until it starts to bubble around the edges.  Lower heat slightly and cook until the sauce reduces to a thick syrup.  Reserve 2-3 tablespoons of glaze for dipping.On the Grill: String shrimp onto bamboo skewers (about 5 per skewer with 16/20 count shrimp).  Spray grill with nonstick cooking spray and heat to 400 F.'),
('6133', '2', 'Place skewers on the grill and brush with sauce.  Cook for about 2 minutes, basting once more at a minute in.  Flip shrimp, baste again and cook for another 2 minutes.  Shrimp should be a light pink color.'),
('6133', '3', 'Remove from grill.'),
('6133', '4', 'Garnish with scallions and serve with glaze.On the Range: Increase heat to medium.'),
('6133', '5', 'Add shrimp directly to saut pan.  Cook for 2 minutes.  Flip, cook an additional 2 minutes until shrimp have turned a light pink color.'),
('6133', '6', 'Remove from heat.  Sprinkle with scallions and serve.'),
('6137', '1', 'Heat the oil in a large, heavy stockpot over high heat and add the shrimp. Cook, stirring constantly, until the shrimp curl and just begin to brown, about 3 minutes.'),
('6137', '2', 'Remove the shrimp with a slotted spoon and set aside.'),
('6137', '3', 'Add the ham and sausage to the stockpot and cook, stirring frequently, until both are well browned, about 15'),
('6137', '4', 'minutes. Reduce heat to medium and add the garlic, celery, bell pepper, and onion. Cook, stirring frequently, until tender, about 10 minutes. Stir in the rice, tomatoes, broth, salt, cayenne pepper, and half the parsley. Cover, reduce heat to low, and simmer 20 minutes or until the liquid is almost absorbed. Stir in the shrimp and the remaining parsley. Cover and cook until all the liquid is absorbed, 3 to 5 minutes more. (Can be made up to 1 day ahead. Cover and refrigerate. Reheat, covered, in a 325 F oven for 20 minutes or until heated through, stirring once or twice.)'),
('6138', '1', 'Heat the oil in a large skillet over medium heat.'),
('6138', '2', 'Add the onion and carrots and cook, stirring occasionally, until soft, 6 to 8 minutes.'),
('6138', '3', 'Add the garlic and curry and cook, stirring, until fragrant, 2 minutes.'),
('6138', '4', 'Add the rice, 2 1/2 cups water, 1/2 teaspoon salt, and 1/2 teaspoon pepper and bring to a boil. Reduce heat to medium-low, cover, and simmer for 15 minutes. Season the shrimp with 1/2 teaspoon salt and 1/4 teaspoon pepper and nestle them in the partially cooked rice. Cover and cook until the shrimp are opaque throughout, 4 to 5 minutes. Fold in the basil and serve.'),
('6140', '1', 'Heat the oil in a large skillet over medium heat.'),
('6140', '2', 'Add the onion and cook, stirring occasionally, until golden brown, about 12 minutes. Stir in the garlic and ginger and cook 2 minutes.'),
('6140', '3', 'Add the wine and bring to a boil. Nestle the shrimp in the onions and simmer for 2 minutes.'),
('6140', '4', 'Add the snow peas and stir to combine. Continue cooking until the shrimp are bright pink and cooked through, about 2 minutes. Stir in the cilantro, salt, and pepper. Meanwhile, cook the couscous according to the package directions. Divide the couscous among individual bowls and spoon the shrimp and snow peas over the top.Upgrade: Replace the couscous with brown rice or barley for a healthy whole-grain lift.'),
('6141', '1', 'In a medium bowl, whisk the mayonnaise, lemon juice, 1/2 teaspoon salt, and 1/4 teaspoon pepper. Fold in the shrimp, celery, and chives, if desired. Line the buns with the lettuce and fill with the shrimp mixture.'),
('6141', '2', 'Serve with the potato chips.'),
('6142', '1', 'Cook the pasta according to the package directions.'),
('6142', '2', 'Drain the pasta and return it to the pot. Meanwhile, heat the oil in a large skillet over medium heat.'),
('6142', '3', 'Add the garlic and cook, stirring, for 1 minute (do not let it brown).'),
('6142', '4', 'Add the shrimp, wine, red pepper, and 1/2 teaspoon salt. Simmer until the shrimp are opaque, 2 to 3 minutes. Stir in the butter until melted. Toss the pasta with the shrimp mixture.'),
('6143', '1', 'Heat the oil in a wok or large saucepan over medium-high heat.'),
('6143', '2', 'Add the sausage and brown on both sides, about 5 minutes total. Reduce heat to medium and add the onion. Cook, stirring occasionally, for 5 minutes. Spoon off and discard all but 1 tablespoon of the fat.'),
('6143', '3', 'Add the wine and cook for 2 minutes.'),
('6143', '4', 'Add the broth, saffron, and rice and bring to a boil. Reduce heat, cover, and simmer for 15 minutes. Stir the shrimp and peas into the rice, cover, and cook for 5 minutes.'),
('6143', '5', 'Remove from heat. Season with the salt and pepper. Spoon onto plates and add the cilantro (if using).Tip: Saffron''s steep price tag makes sense when you realize that the vibrant red threads are hand harvested from crocus blossoms. You can find saffron in the spice aisle of most supermarkets.'),
('6146', '1', 'In a medium size heavy pan melt butter spread.'),
('6146', '2', 'Add rice and saute about a minute.'),
('6146', '3', 'Add chicken broth and peas and bring to a boil. When all liquid is absorbed reduce heat to low and cover. Cook on low for about 15 minutes, until rice is cooked through.In a large skillet, heat 2 tsp olive oil over medium heat. Season shrimp with salt and pepper and add to hot pan. Cook about 2-3 minutes, until shrimp is cooked through.'),
('6146', '4', 'Remove shrimp from pan and set aside.'),
('6146', '5', 'Add 1 tbsp olive oil to the skillet and add rice.'),
('6146', '6', 'Add grated cheese, shrimp, and parsley and saute another minute, mixing well.Print This8 PP 9 SP Lenten Friendly Recipes Main Dishes Recipes Seafood Recipes Springposted May 29, 2009 by Gina38 Comments'),
('6148', '1', 'Add tomato to the pan.'),
('6148', '2', 'Saute for 3 minutes, allowing tomato to release its juice and incorporate with the onion and celery.'),
('6148', '3', 'Add marsala and bring to a boil. Reduce heat to medium, cover and simmer for 5 minutes.'),
('6148', '4', 'Uncover and add mushrooms. Cook for 5 minutes before stirring in heavy cream. Return shrimp to pan. Cook until sauce thickens a bit, 10 minutes or so.*Note: Because shrimp is considered highly allergenic, some recommend waiting until 12 months to introduce it. Others suggest even longer (3+ years). That said, food introduction recommendations are changing, as mounting evidence suggests there is little benefit in delaying even allergenic foods for children with no personal or family history of food allergies. Read more about my age categories and speak to your pediatrician about whats right for your child.'),
('6150', '1', 'Heat the oven to 400F and arrange a rack in the middle. Line a baking sheet with foil. set aside.'),
('6150', '2', 'Place the sesame seeds on a plate. set aside.'),
('6150', '3', 'Combine the mayonnaise, cilantro, lime juice, soy sauce, sesame oil, cayenne pepper, and scallions in a medium bowl. set aside.2'),
('6150', '4', 'Place the shrimp in a large bowl, add the vegetable oil, salt, and pepper, and toss to coat. Dip one side of each shrimp in the toasted sesame seeds, skewer, and place on the prepared baking sheet, seeds-side up.'),
('6150', '5', 'Bake until the shrimp are firm to the touch, about 5 to 7 minutes.'),
('6150', '6', 'Serve immediately with the dipping sauce.'),
('6150', '7', 'Share This Recipe'),
('6150', '8', 'Print'),
('6150', '9', 'Email'),
('6150', '10', 'Save (402)'),
('6152', '1', 'Melt 2 tablespoons butter in a large saucepan.'),
('6152', '2', 'Add garlic and 1 tablespoon thyme. saut 1 minute.'),
('6152', '3', 'Add broth, whipping cream, and 1 cup water. Bring to a boil. whisk in grits. Reduce heat to low. cook 10 minutes or until done, stirring occasionally. Season with salt and pepper. Keep warm.'),
('6152', '4', 'Melt 2 tablespoons butter in a large skillet.'),
('6152', '5', 'Add celery and next 3 ingredients. saut 30 seconds.'),
('6152', '6', 'Add shrimp, and cook 7 minutes.'),
('6152', '7', 'Remove shrimp from skillet.'),
('6152', '8', 'Add verjuice, and cook 6 minutes over medium heat or until most liquid has evaporated, stirring to loosen browned bits.'),
('6152', '9', 'Reduce heat to low. whisk in remaining butter, 1 tablespoon at a time. Stir in lemon juice, tomato, and parsley.'),
('6152', '10', 'Serve over grits.'),
('6152', '11', 'Garnish, if desired.'),
('6152', '12', '*Verjuice is an acidic, sour liquid made from grapes. It''s used like lemon juice or wine to heighten flavor.'),
('6154', '1', 'Heat peanut oil in heavy large skillet over medium-high heat.'),
('6154', '2', 'Add sliced onion. stir-fry until soft and beginning to brown, about 4 minutes. Reduce heat to medium.'),
('6154', '3', 'Add green onions and curry paste. stir until fragrant, about 1 minute.'),
('6154', '4', 'Add coconut milk, chicken broth, fish sauce, and sugar. bring to boil.'),
('6154', '5', 'Add tomatoes and boil 2 minutes.'),
('6154', '6', 'Add shrimp and cook just until opaque in center, stirring often, about 3 minutes.'),
('6154', '7', 'Transfer curry to large shallow bowl.'),
('6154', '8', 'Garnish with cilantro.'),
('6154', '9', 'Serve, passing lime wedges separately.'),
('6154', '10', '*Available at Asian markets and in the Asian foods section of some supermarkets.'),
('6155', '1', 'Heat the oil in a large saut pan over medium heat.'),
('6155', '2', 'Add the shrimp, garlic, and salt and cook until the shrimp is pink and just cooked through, about 5 minutes.'),
('6155', '3', 'Remove the shrimp and set aside.'),
('6155', '4', 'Add the chili paste and coconut milk to the pan and bring to a boil. Reduce heat and simmer, stirring occasionally, until thickened and reduced by half, about 5 minutes.'),
('6155', '5', 'Add the rice, bean sprouts, scallion, lime juice, and shrimp and cook until heated through, 3 to 4 minutes.'),
('6155', '6', 'Serve garnished with basil leaves.'),
('6156', '1', 'Preheat oven to 450F.'),
('6156', '2', 'Place the tomatoes in a large baking dish. Spoon the olive oil and garlic over the tomatoes. Sprinkle with the salt and pepper and toss.'),
('6156', '3', 'Place on top rack of oven and roast for 20 minutes.'),
('6156', '4', 'Remove baking dish from oven and stir in the shrimp, parsley, and lemon juice. Sprinkle with the Feta.'),
('6156', '5', 'Place back in oven for another 10 to 15 minutes or until the shrimp are cooked.'),
('6156', '6', 'Serve warm with crusty bread.'),
('6157', '1', 'Heat 3 tablespoons of the oil in a large, nonstick skillet over medium heat.'),
('6157', '2', 'Add corn and cook, covered, 5 minutes, stirring occasionally.'),
('6157', '3', 'Add shrimp and cook just until shrimp turns pink, about 3 minutes.'),
('6157', '4', 'Remove from heat and transfer to a large bowl. Allow to cool slightly.'),
('6157', '5', 'Whisk together remaining tablespoon of oil with lemon juice and vinegar. and salt and freshly ground pepper to taste.'),
('6157', '6', 'Drizzle over corn and shrimp and toss with tomatoes, scallions, and cilantro leaves.'),
('6157', '7', 'Serve at room temperature or chilled.'),
('6158', '1', 'In a large pot, bring the broth, onion, ginger, carrot, celery, and soy sauce to a boil. Reduce heat, cover partially, and simmer for 20 minutes. Strain the broth. discard the solids. Return the broth to the pot and bring to a boil.'),
('6158', '2', 'Add a few of the dumplings, being careful not to crowd the pot. Simmer until the dumplings float on the surface and the shrimp inside turns pink (cut one in half to check), 3 to 4 minutes. Use a slotted spoon to transfer the dumplings to a plate. set aside. Repeat with the remaining dumplings.'),
('6158', '3', 'Add the peas and simmer until bright green, about 3 minutes. Return the cooked dumplings to the broth to warm. Ladle the soup into individual bowls.'),
('6161', '1', 'Saute bacon in heavy large skillet over medium heat until brown and crisp. Using slotted spoon, transfer bacon to paper towels to drain.'),
('6161', '2', 'Add cauliflower to drippings in skillet and saute until crisp-tender and beginning to brown, about 5 minutes.'),
('6161', '3', 'Add tomatoes, lemon juice, capers, and thyme. simmer 1 minute to blend flavors.'),
('6161', '4', 'Remove from heat.'),
('6162', '1', 'In a saute pan over medium high heat, melt about 3 T fat.  Pat the skate wings dry with a paper towel and sprinkle with S&P.'),
('6162', '2', 'Place the wing in the pan and saute for about 7 minutes, flip once you see a little bit of color and saute on the other side. You shouldnt see any pink or redness, if you do, cook it longer.'),
('6164', '1', 'PREP'),
('6164', '2', 'Put the flour in the shallow bowl and season it with salt and pepper. Dredge the fish in the flour and shake off the excess. Re-season the fish with salt and pepper.'),
('6164', '3', 'COOK'),
('6164', '4', 'In the saut pan, heat 1 tablespoon (14 g) of the butter over medium-high heat. When the butter has foamed and subsided, add the fish and cook over high heat for 2 minutes.'),
('6164', '5', 'Add 1 more tablespoon (14 g) of butter and turn the fish, cooking the other side for 2 minutes.'),
('6164', '6', 'Transfer the fish to the serving platter.'),
('6164', '7', 'FINISH'),
('6164', '8', 'Discard the butter from the pan and then add the remaining 2 tablespoons (28 g) of butter. Cook over high heat until it foams and subsides, then add the capers and croutons. Cook for 30 seconds, then add the lemon juice and parsley. (You can add the lemon segments at this point as well.)'),
('6164', '9', 'Remove from the heat and spoon the sauce over the fish.'),
('6164', '10', 'var article'),
('6164', '11', 'Type_27_data = {}.'),
('6164', '12', 'article'),
('6164', '13', 'Type_27_data.init_step_by_step_images = 0.'),
('6165', '1', 'Wash chopped leek well in a bowl of cold water, agitating it, then lift out and pat dry.'),
('6165', '2', 'Heat oil in a 3- to 4-quart heavy saucepan over moderately high heat until hot but not smoking, then saut leek, carrot, onion, and garlic clove, stirring frequently, until vegetables are soft and well browned, about 10 minutes. Stir in wine and deglaze saucepan by boiling, stirring and scraping up any brown bits, 1 minute.'),
('6165', '3', 'Add water, soy sauce, parsley, thyme, bay leaf, and porcini and simmer, uncovered, until liquid is reduced to 3/4 cup, about 25 minutes.'),
('6165', '4', 'Pour through a fine-mesh sieve into a glass measure, lightly pressing on and then discarding solids.'),
('6165', '5', 'Transfer to a small saucepan. If you have more than 3/4 cup, boil strained liquid a few minutes to reduce.'),
('6167', '1', 'Prepare cake batter and bake in 2 (9-inch) round pans as directed on package.  Cool cakes in pans 15 min.  (Do not remove cakes from pans.)'),
('6167', '2', 'Add boiling water to gelatin mixes. stir 2 min. until completely dissolved.  Pierce cakes with large fork or skewer at 1/2-inch intervals.'),
('6167', '3', 'Pour gelatin over cakes.  Refrigerate 4 hours.'),
('6167', '4', 'Unmold 1 cake layer onto serving plate. spread with 1/2 cup COOL WHIP.  Unmold second cake layer. carefully place on top of first layer.  Frost top and side of cake with 2 cups of the remaining COOL WHIP.  Tint remaining COOL WHIP with food coloring. spread on top of cake to resemble ice rink.  Outline outside edge of "ice rink" with decorating gel.  Refrigerate 1 hour.'),
('6167', '5', 'Decorate top of cake with candy-coated chocolate pieces.'),
('6167', '6', 'Add graham snacks for the "ice skaters."  Decorate ice cream cones with green decorating icing. place around ice rink.  Sprinkle cake with coconut then sugar.'),
('6168', '1', 'Cut the skate into four equal pieces and let them soak in the buttermilk for a few minutes. In a shallow bowl, combine the cornmeal, flour, salt, pepper, and chopped thyme. Dredge the skate pieces in the cornmeal mixture and shake off the excess'),
('6168', '2', 'Heat the oil in a heavy skillet or frying pan over medium heat until it barely begins to smoke. Carefully add the skate to the oil in a single layer. If they won''t fit in a single layer, fry them in batches. Cook for 3 to 4 min., until the crust is lightly browned. Turn and cook another 2 to 3 min.'),
('6168', '3', 'Remove the skate from the pan and drain on paper towels. Arrange the skate on plates with the lemon wedges, a few thyme sprigs, and a sprinkle of chopped parsley.'),
('6170', '1', 'Cut the fish into 5 or 6 pieces and set aside.'),
('6170', '2', 'In a 10-inch saute pan, heat the oil over medium heat and add the garlic, rosemary, skate and broccoli. Cook the fish and broccoli, turning the pieces to cook evenly, about 5 minutes total.'),
('6170', '3', 'Remove the rosemary and add half the parsley and the tomatoes. Bring to a boil over medium heat, then reduce to a simmer. Cook for 10 minutes, then keep warm.'),
('6170', '4', 'Remove the fish from the sauce and flake off the bones. Return it to the sauce.'),
('6170', '5', 'Bring 6 quarts of water to a boil and add 2 tablespoons salt. Cook the bucatini according to the package directions, until tender yet al dente.'),
('6170', '6', 'Drain the pasta and add it to the sauce along with the remaining parsley and salt and pepper to taste. Toss over high heat 1 minutes and divide evenly among warmed pasta bowls.'),
('6176', '1', 'Wash fish and pat dry with paper towels. For the whole fish, make 2-3 1/4" cuts diagonally across the fish body .Smash the stalks of the lemongrass. Reserve about a 1" stalk and chop finely or crush in mortar & pestle.In bowl, combine garlic, fish sauce, sugar, oil, chili''s, crushed lemongrass in both forms.'),
('6176', '2', 'Let diced chili infuse in marinade for about 5 minutes, then remove chilies and set aside for later use.'),
('6176', '3', 'Pour marinade over fish. For the whole fish, place the smashed lemongrass stalks in the body cavity of the fish. This will give extra lemongrass flavor.'),
('6176', '4', 'Let marinade for about 20 minutes.'),
('6176', '5', 'Place fish on hot grill. Cook for about 2 minutes on each side for fillets, 10 minutes on each side for the whole fish, or until cooked to your liking. Cook time for whole snapper will also depend on the size of your fish.'),
('6176', '6', 'Remove fish from grill and dress with the diced chili''s.'),
('6177', '1', 'Preheat oven to 250 degrees F.Make sure the fish is thoroughly cleaned and scaled. Rub with a tablespoon of oil and sprinkle some salt and pepper both inside and out. Stuff it with 1 sprig of rosemary.Toss the potatoes, olives, onions, bellpepper and other 2 sprigs of rosemary with the remaining olive oil then salt and pepper to taste.'),
('6177', '2', 'Put the fish in the middle of the roasting pan and surround with the veggies. Cover loosely with foil and put it in the oven.Depending on the size of the fish it will take anywhere from 1-2 hours, you can tell it''s done by inserting a fork into the thickest part of the fish and seeing if the meat flakes easily. When the fish is done, remove the foil and add the haricots verts. Toss the veggies with the olive oil that''s accumulated at the bottom of the pan. Spoon some oil over the fish and put it under a broiler for a few minutes to brown.Plate the veggies then use 2 forks to separate the meat from the bones running down the center of the fish. Spoon some sauce over the top and garnish with some fresh rosemary. If you went light on the salt, sprinkle some fleur de sel on top.'),
('6177', '3', 'Serve with lemon wedges for squeezing.'),
('6178', '1', 'Parboil the sunchokes in salted water until they are tender, but not mushy. Trim all the fins off the snapper and dry with a paper towel.'),
('6178', '2', 'Put the oven rack in the middle position and preheat to 450 degrees F.'),
('6178', '3', 'Add about 2 tablespoons of olive oil to a large chefs pan and heat over medium high heat.'),
('6178', '4', 'Add the garlic and saute until fragrant.'),
('6178', '5', 'Add the fennel, onion, and bay leaf and saute until the vegetables start turning brown at the edges (about 10 minutes).'),
('6178', '6', 'Add the tomatoes and salt and pepper to taste.'),
('6178', '7', 'Add the parboiled sunchokes, then make a little space in the middle of the pan for the fish.Generously salt and pepper both sides of the snapper as well as the inside, then spread the belly out a little so the fish can sit upright in the pan along with the sauteed vegetables.'),
('6178', '8', 'Drizzle with olive oil and put the pan in the oven.Toss the asparagus with olive oil and salt and pepper. After the fish has been in the oven for 15 minutes, sprinkle the asparagus around the fish and put it back in the oven and continue to cook for another 10-15 minutes, or until the fish is cooked all the way through. You can test it by sticking a fork or knife straight down into the meat around the spine and pulling away the meat. It should come away from the bone easily and be opaque. If it doesn''t or the meat looks translucent, cook it a little longer.Sprinkle with chopped mint and serve whole with the vegetables.'),
('6179', '1', 'Gut and clean the fish.  Or, buy one that is already cleaned and gutted...be sure that the eyes are clear and the fish is really really fresh...or forget it!'),
('6179', '2', 'Mix the olive oil and the minced garlic together.'),
('6179', '3', 'Slather this mixture over and in the cavity of the fish.'),
('6179', '4', 'Put the fish on a hot grill and cook until done. (usually 10 minutes per inch of fish)'),
('6179', '5', 'Remove from grill and carefully remove head, skin and debone the fish.'),
('6179', '6', 'Garnish with chopped parsley and Mac nuts sauteed in a little butter.'),
('6179', '7', 'Squeeze a little fresh lime juice over the filleted fish and serve.'),
('6182', '1', 'Preheat the oven at 400 F.In a bowl, combine the egg whites, thyme and salt.Take a baking dish and add a bed of this salt preparation at the bottom.'),
('6182', '2', 'Place the fish on top. Cover it completely with the rest of the salt.'),
('6182', '3', 'Bake for 30 minutes.'),
('6182', '4', 'Remove from the oven and let cool for 5 minutes before breaking the crust of salt. The flesh of the fish should be extremely tender. Eat as is, or with a dash of olive oil, and steamed potatoes.'),
('6183', '1', 'Combine first 3 ingredients in a large shallow bowl.'),
('6183', '2', 'Combine flour and cornstarch in a separate large shallow bowl.'),
('6183', '3', 'Pour oil to depth of 1 inch in a deep skillet or Dutch oven. heat to 350 to 36'),
('6183', '4', 'Place snapper in flour mixture, coating both sides and shaking off excess. Dip snapper into egg mixture and then back into flour mixture, shaking off excess.'),
('6183', '5', 'Place immediately into hot oil, and fry 3 minutes on each side or until golden brown and crispy.'),
('6183', '6', 'Serve immediately over hot cooked rice with Nuoc Nam, mango, and jalapeo.'),
('6185', '1', '*Momiji Oroshi is grated Daikon and whole dried Japanese chilies. To make 1/2 cup: grate 1 pound of daikon together with 16 dried chilies that have been soaked in hot water for 5 minutes.Lightly season the fish with salt all over, including the cavities.'),
('6185', '2', 'Let the fish rest for 30 minutes at room temperature.Wipe off moisture that accumulates on the surface of the fish with paper towels.'),
('6185', '3', 'Cut a 1/2-inch-deep slit lengthwise along the centerline of each fish, from head to tail. Do this on both sides. the cuts will help the fish cook faster and make it easier to flake off the grilled flesh.To make the dipping sauce, divide the momiji oroshi and scallions between the 4 bowls of ponzu. set aside.Preheat a grill to medium-hot.'),
('6185', '4', 'Brush the cooking grate clean and oil it well.Grill the fish about 5 minutes per side. Flip the snappers with caregently turn them with a fish spatula so they dont break apart. When the fish are ready, youll see juice bubbling from the back, and if you peek inside the cavity, youll see that the spine and flesh near it will have turned white.'),
('6185', '5', 'Serve the fish immediately, accompanied by the ponzu dipping sauce. Ponzu,Makes about 1 1/2 cups'),
('6185', '6', 'Add the sake and mirin to a small saucepan and bring to a boil over high heat. Boil for 1 minute, remove from heat, and let the liquid come to room temperature.In a bowl, stir together the soy sauce, citrus juice, vinegar, the 1/4 cup water, the sake mixture, kombu, and bonito flakes. Cover loosely with plastic wrap and let the mixture steep in the refrigerator for 12 hours, or overnight.Strain the ponzu through a cheesecloth or fine sieve. gently squeeze to press out the liquid. The ponzu will keep in the refrigerator for 2 weeks.'),
('6186', '1', 'In a small bowl, combine the paprika,oregano, thyme, cayenne, sugar, 1 teaspoonsalt, and black pepper. Set spicemixture aside.'),
('6186', '2', 'Place the fillets on a clean, dry work surface, skin side up, and cut 3 to 4 shallow slits across skin to keep it from curling up while cooking. Turn fillets over, and sprinkle the top of each fillet with a heaping teaspoon of the reserved spice mixture. pat gently with hands to make spice mixture stick. Cover, and place in the refrigerator for 1 hour.'),
('6186', '3', 'Heat 1 teaspoon oil in a heavy skillet.When hot, but not smoking, add half thefillets, seasoned side down. Cook untilwell browned, about 2 minutes. Flip. cookuntil fish is cooked through, 2 to 3 minutesmore. Carefully wipe skillet with apaper towel. Repeat with remaining oiland fillets. serve.'),
('6191', '1', 'Preheat the oven to 350 degrees F. Line a large baking sheet with foil and dot with 2 tablespoons butter.'),
('6191', '2', 'Butterfly the fish by cutting almost in half horizontally and opening like a book. Carefully cut and remove the spine.'),
('6191', '3', 'Place the fish, skin-side down, on the foil.'),
('6191', '4', 'Roll up the edges of the foil to come close to the edge of the fish to prevent the juices from spilling onto the baking sheet. Sprinkle the fish with salt and pepper. Sprinkle the fish with the garlic powder and then with the tomato bouillon.'),
('6191', '5', 'Drizzle the fish with the hot sauce and then squeeze the limes over.'),
('6191', '6', 'Cut and squeeze the orange juice all over the fish. Then, using the flesh side of the orange, brush the fish all over to form a wet paste on top of the fish. Dot the fish with the remaining butter.'),
('6191', '7', 'Bake the fish until just cooked through, about 15 minutes. Turn on the broiler and broil until browned, 8 to 10 minutes.'),
('6191', '8', 'Serve with warm tortillas to make tacos and lime wedges for squeezing over the fish.'),
('6193', '1', 'Light a grill or preheat the oven to 50'),
('6193', '2', 'Using a small, sharp knife, peel the lemon, removing all the bitter white pith.'),
('6193', '3', 'Cut the lemon into 1/4-inch dice, discarding the seeds.'),
('6193', '4', 'Transfer the diced lemon to a medium bowl and add the tomatoes, cucumber, shallot, thyme and chives. Stir in the 1/4 cup of olive oil and season with salt and pepper.'),
('6193', '5', 'Lay two 20-inch-square sheets of heavy-duty foil on top of each other, then fold them in half to form a rectangle. Fold up 2 inches on each side, neatly folding in the corners to form a low-sided box.'),
('6193', '6', 'Brush the foil with olive oil and set the fish on the foil. Season with salt and pepper and spoon 1/3 cup of the vinaigrette on each fillet. Using 2 long spatulas, set the foil package on a medium-hot grill and cook for about 15 minutes, or until the fish is just cooked through. Alternatively, roast the foil package on a cookie sheet in the oven for about 20 minutes.'),
('6193', '7', 'Transfer to a platter and serve with Braised Endives.'),
('6196', '1', 'Preheat oven to 40'),
('6196', '2', 'Stuff fish with sliced lemons and rosemary.'),
('6196', '3', 'Combine kosher salt, egg whites, and 1/2 cup water in a large bowl. Line a large, rimmed baking sheet with aluminum foil or parchment paper.'),
('6196', '4', 'Spread one-third of the salt mixture on the lined baking sheet. Top with fish. cover with remaining salt mixture.'),
('6196', '5', 'Bake fish 40 to 50 minutes. Crack salt layer with a hammer or meat mallet, and remove. Peel back fish skin. carefully remove meat, discarding skin and bones.'),
('6197', '1', 'Thai Steamed Snapper | Whole Foods Market'),
('6197', '2', 'Skip to main content'),
('6197', '3', 'Whole Foods Market'),
('6197', '4', 'Welcome(find a store)User menu'),
('6197', '5', 'Find a Store'),
('6197', '6', 'On Sale'),
('6197', '7', 'Recipes'),
('6197', '8', 'ShopContact UsSign In / Register'),
('6197', '9', 'Global Search'),
('6197', '10', 'Enter your keywords'),
('6197', '11', 'Whole Foods Market'),
('6197', '12', 'Healthy Eating'),
('6197', '13', 'Getting Started4 Ways to a Healthier YouHealth Starts Here'),
('6197', '14', 'Simple Changes for Lifelong Health'),
('6197', '15', 'Resources'),
('6197', '16', 'What to EatHealthy Recipes'),
('6197', '17', 'Weekly Meal Plans'),
('6197', '18', 'The Engine 2 Diet'),
('6197', '19', 'Healthy Cooking'),
('6197', '20', 'Healthy Pantry Makeover'),
('6197', '21', 'Healthy Cooking Videos'),
('6197', '22', 'Cooking with Whole Grains'),
('6197', '23', 'Add Flavor, NaturallyANDI Guide'),
('6197', '24', 'Family and Special Diets'),
('6197', '25', 'Parents & Kids'),
('6197', '26', 'Special Diets'),
('6197', '27', 'About Our Products'),
('6197', '28', 'Our Quality Standards'),
('6197', '29', 'Organic Food'),
('6197', '30', 'Food Ingredient Quality Standards'),
('6197', '31', 'Meat Animal Welfare Standards'),
('6197', '32', 'Premium Body Care Standards'),
('6197', '33', 'Responsibly Grown'),
('6197', '34', 'MoreProduct Ingredient FAQsProduct FAQs: GMOsFood Allergies'),
('6197', '35', 'Ingredients'),
('6197', '36', 'Milk and Eggs'),
('6197', '37', 'Olive OilMore'),
('6197', '38', 'Food Safety'),
('6197', '39', 'Bisphenol-ACold Storage Chart'),
('6197', '40', 'Handling Meat & Poultry Safely'),
('6197', '41', 'Handling Seafood Safely'),
('6197', '42', 'Irradiation (US and Canada)MoreGMOs: Your Right to KnowGMO Quick Facts: What, Why, Where'),
('6197', '43', 'How To Shop if Youre Avoiding GMOsOur Commitment to GMO LabelingFAQs on GMOsOur Product Lines365 Everyday Value'),
('6197', '44', 'Engine 2 Plant-Strong'),
('6197', '45', 'Whole Foods Market Brand'),
('6197', '46', 'Whole Trade'),
('6197', '47', 'Locally Grown'),
('6197', '48', 'Local Growers MapLocal Vendor Profiles'),
('6197', '49', 'Recipes'),
('6197', '50', 'Recipes'),
('6197', '51', 'Featured'),
('6197', '52', 'Newest'),
('6197', '53', 'Top Rated'),
('6197', '54', 'Cooking & Entertainment Guides'),
('6197', '55', 'Holiday Guide'),
('6197', '56', 'The Perfect Antipasto Plate'),
('6197', '57', 'Tapas: Tiny Treasures of Spain'),
('6197', '58', 'Cooking Tips'),
('6197', '59', 'Hosting Tips'),
('6197', '60', 'MoreFood Guides'),
('6197', '61', 'Beans'),
('6197', '62', 'Chocolate'),
('6197', '63', 'Cooking Oils'),
('6197', '64', 'Dairy Products'),
('6197', '65', 'EggsMore'),
('6197', '66', 'Seasonal Recipe Collections5-Ingredient Dessert Recipes5-Ingredient Summer Mains5-Ingredient Salad Recipes'),
('6197', '67', 'No-Cook Recipes for Summer'),
('6197', '68', 'Perfect Pesto Recipes'),
('6197', '69', 'MoreOnline Ordering'),
('6197', '70', 'Available At Your Store'),
('6197', '71', 'Catering & Holiday Ordering'),
('6197', '72', 'Nationwide'),
('6197', '73', 'Gift Cards'),
('6197', '74', 'Gift Card(s) Terms and Conditions'),
('6197', '75', 'Gift Cards FAQMission & Values'),
('6197', '76', 'Our Values'),
('6197', '77', 'Core Values'),
('6197', '78', 'Commitment to Society'),
('6197', '79', 'Community Giving'),
('6197', '80', 'Local Producer Loan Program'),
('6197', '81', 'Whole Kids Foundation'),
('6197', '82', 'Whole Planet Foundation'),
('6197', '83', 'Whole Cities Foundation'),
('6197', '84', 'Environmental StewardshipA Better BagCloned Meat Q&ADoing The Green Thing'),
('6197', '85', 'Eco Scale'),
('6197', '86', 'Green Mission'),
('6197', '87', 'Organic Farming'),
('6197', '88', 'Growth of the Organics Industry'),
('6197', '89', 'About Organic Farming'),
('6197', '90', 'Farming Organically'),
('6197', '91', 'How Does Biodynamic Farming Fit In?Organic Industry Timeline'),
('6197', '92', 'MoreSeafood Sustainability'),
('6197', '93', 'Seafood Sustainability Basics'),
('6197', '94', 'Our Collaboration with the Marine Stewardship Council'),
('6197', '95', 'Wild-Caught Seafood Sustainability Ratings'),
('6197', '96', 'Aquaculture'),
('6197', '97', 'Seafood Sustainability FAQMore'),
('6197', '98', 'Whole Trade'),
('6197', '99', 'Whole Trade Helps Real People'),
('6197', '100', 'Whole Trade Videos'),
('6197', '101', 'Whole Trade Products'),
('6197', '102', 'Our Certifier Partners'),
('6197', '103', 'Animal Welfare5-Step Animal Welfare Rating'),
('6197', '104', 'Animal Welfare Basics'),
('6197', '105', 'Collaboration with Global Animal Partnership'),
('6197', '106', 'Meet the Farmers & Ranchers'),
('6197', '107', 'Blogs'),
('6197', '108', 'Whole Story'),
('6197', '109', 'Whole Story BlogCEO Blogs'),
('6197', '110', 'John Mackey''s Blog'),
('6197', '111', 'Walter Robb''s Blog'),
('6197', '112', 'Store Departments'),
('6197', '113', 'Unique To Your Store'),
('6197', '114', 'Events Calendar'),
('6197', '115', 'Find Your Store'),
('6197', '116', 'Store Departments'),
('6197', '117', 'Bakery'),
('6197', '118', 'BeerBulk'),
('6197', '119', 'Cheese'),
('6197', '120', 'Coffee & TeaFlowers and Floral Arrangements'),
('6197', '121', 'Grocery'),
('6197', '122', 'Meat & Poultry'),
('6197', '123', 'Prepared Foods'),
('6197', '124', 'Produce'),
('6197', '125', 'Seafood'),
('6197', '126', 'WineWhole Body'),
('6197', '127', 'PetsHome  Recipes  Thai Steamed Snapper'),
('6197', '128', 'Thai Steamed Snapper'),
('6197', '129', 'Tweet'),
('6197', '130', 'Serves 2 to 4This light seafood recipe is perfect for the summer.'),
('6197', '131', 'Serve with cilantro-spiked steamed rice and veggies on the side, if you like.Log in or create an account to save favorite recipes to your Recipe Boxprintemail'),
('6197', '132', 'Check out our top pins!Home  Recipes  Thai Steamed Snapper'),
('6197', '133', 'Ingredients:1 (1-pound) skinless fillet of snapper or other white fish'),
('6197', '134', 'Salt1 tablespoon expeller-pressed canola oil1 tablespoon finely chopped ginger1 green onion, thinly sliced2 Thai or serrano chiles, seeded and cut into very thin strips1 lime, Grated zest of2 teaspoons fish sauce'),
('6197', '135', 'Cilantro leaves for garnish'),
('6197', '136', 'Lime wedges'),
('6197', '137', 'Add ingredients to shopping list'),
('6197', '138', 'Create a new list...You must be signed in to use shopping lists. Sign in or create account'),
('6197', '139', 'Create a new list:Cancel'),
('6197', '140', 'Place fish on a large piece of oiled parchment paper and season with salt.'),
('6197', '141', 'Heat oil in a small skillet over medium-high heat.'),
('6197', '142', 'Add ginger, green onions and chiles and cook, stirring frequently, until fragrant but not browned, about 1 minute. Stir in lime zest and fish sauce and cook for about 10 seconds more.'),
('6197', '143', 'Pour mixture over fish and wrap up parchment paper snugly to form a packet.Carefully transfer fish to rack in wok or skillet. Bring water to a simmer over medium heat, cover and steam until fish is just cooked through, 8 to 10 minutes. Carefully remove parchment packet from wok and transfer to a large plate.'),
('6197', '144', 'Garnish with cilantro and lime wedges.Nutritional Info:Per Serving: 200 calories (60 from fat), 7g total fat, 1.5g saturated fat, 55mg cholesterol, 500mg sodium, 1g carbohydrates, 31g protein.Special Diets:Dairy Free'),
('6197', '145', 'Gluten Free'),
('6197', '146', 'Sugar Conscious'),
('6197', '147', 'Wheat Free'),
('6197', '148', 'Note: We''ve provided special diet and nutritional information for educational purposes. But remember  we''re cooks, not doctors! You should follow the advice of your health-care provider. And since product formulations change, check product labels for the most recent ingredient information. See our Terms of Service.Advanced Search'),
('6197', '149', 'Filter Recipes By:Special Diet'),
('6197', '150', 'Dairy Free'),
('6197', '151', 'Fat Free'),
('6197', '152', 'Gluten Free'),
('6197', '153', 'High Fiber'),
('6197', '154', 'Low FatLow Sodium'),
('6197', '155', 'Sugar Conscious'),
('6197', '156', 'Vegan'),
('6197', '157', 'Vegetarian'),
('6197', '158', 'Wheat Free'),
('6197', '159', 'Occasion'),
('6197', '160', 'Grilling'),
('6197', '161', 'Summer'),
('6197', '162', 'Type of Dish'),
('6197', '163', 'Appetizers'),
('6197', '164', 'Breads and Muffins'),
('6197', '165', 'Breakfast and Brunch'),
('6197', '166', 'Desserts'),
('6197', '167', 'Dressings, Sauces and Condiments'),
('6197', '168', 'Drinks'),
('6197', '169', 'Main Dishes'),
('6197', '170', 'Salads'),
('6197', '171', 'Sandwiches'),
('6197', '172', 'Side Dishes'),
('6197', '173', 'Snacks'),
('6197', '174', 'Soups and Stews'),
('6197', '175', 'Main Ingredient'),
('6197', '176', 'Beans and Lentils'),
('6197', '177', 'BeefCheese'),
('6197', '178', 'Chocolate'),
('6197', '179', 'Dairy'),
('6197', '180', 'EggsFruit'),
('6197', '181', 'Grains'),
('6197', '182', 'LambNuts'),
('6197', '183', 'Pasta'),
('6197', '184', 'PorkPoultry'),
('6197', '185', 'RiceSeafood'),
('6197', '186', 'Tofu/SoyVegetables'),
('6197', '187', 'Cuisine'),
('6197', '188', 'African'),
('6197', '189', 'Asian'),
('6197', '190', 'Central/South American'),
('6197', '191', 'European'),
('6197', '192', 'Indian'),
('6197', '193', 'Jewish'),
('6197', '194', 'Mediterranean'),
('6197', '195', 'Mexican and Tex-MexMiddle Eastern'),
('6197', '196', 'Southern American'),
('6197', '197', 'Category'),
('6197', '198', 'Budget Friendly'),
('6197', '199', 'Cooking with Kids'),
('6197', '200', 'Entertaining'),
('6197', '201', 'Family Friendly'),
('6197', '202', 'Gifts'),
('6197', '203', 'Learn to Cook'),
('6197', '204', 'Make Ahead'),
('6197', '205', 'No Cook'),
('6197', '206', 'One Dish Meals'),
('6197', '207', 'Picnic and Potluck'),
('6197', '208', 'Quick and Easy'),
('6197', '209', 'Slow Cooker'),
('6197', '210', 'The Whole Deal'),
('6197', '211', 'Recipe Newsletter'),
('6197', '212', 'Get seasonal recipes and cooking tips delivered to your inbox!Email'),
('6197', '213', 'Address'),
('6197', '214', 'Featured Recipes'),
('6197', '215', 'Grilled Barbecue Pork and Plum Kabobs15-Minute Couscous Salad with Zucchini and Parsley'),
('6197', '216', 'Learn to Cook: Cold-Brewed Coffee'),
('6197', '217', 'Spring Chicken Salad'),
('6197', '218', 'Halibut Tacos with Creamy Corn and Cabbage Slaw'),
('6197', '219', 'Fresh Pineapple Salsa'),
('6197', '220', 'Whole Wheat Linguine with Green Pea Pesto'),
('6197', '221', 'Tex-Mex Noodles'),
('6197', '222', 'Gluten-Free Blackberry Upside-Down Cake'),
('6197', '223', 'Related Recipes'),
('6197', '224', 'Baked Basmati and Currant Stuffed Trout'),
('6197', '225', 'French Quarter Catfish Amandine'),
('6197', '226', 'Broiled Catfish with Thyme Breadcrumbs'),
('6197', '227', 'Southwestern Calamari Salad'),
('6197', '228', 'Blackened Catfish with Edamame Succotash'),
('6197', '229', 'Catfish Gumbo'),
('6197', '230', 'Catfish Escabeche with Peppers and Mushrooms'),
('6197', '231', 'Holiday Cioppino'),
('6197', '232', 'Cod Poached in Tomato-Tarragon Sauce'),
('6197', '233', 'Haddock Fillets with Roasted Garlic Potato Crust'),
('6197', '234', 'Recipe Discussion'),
('6197', '235', 'Shopping'),
('6197', '236', 'Find a Store'),
('6197', '237', 'Coupons'),
('6197', '238', 'Sales Flyers'),
('6197', '239', 'Catering & Online Ordering'),
('6197', '240', 'Gift Cards'),
('6197', '241', 'Store Departments'),
('6197', '242', 'Store Events'),
('6197', '243', 'Company'),
('6197', '244', 'About Whole Foods Market'),
('6197', '245', 'Careers'),
('6197', '246', 'Mission & Values'),
('6197', '247', 'Investor Relations'),
('6197', '248', 'Newsroom'),
('6197', '249', 'Customer Service'),
('6197', '250', 'Eating & Cooking'),
('6197', '251', 'Healthy Eating'),
('6197', '252', 'Recipe Collections'),
('6197', '253', 'Special Diets'),
('6197', '254', 'Parents & Kids'),
('6197', '255', 'About Our Products'),
('6197', '256', 'Quality Standards'),
('6197', '257', 'Food Safety'),
('6197', '258', 'Organic FarmingGMOs: Your Right to Know'),
('6197', '259', 'More from Whole Foods Market'),
('6197', '260', 'Whole Planet Foundation'),
('6197', '261', 'Whole Kids Foundation'),
('6197', '262', 'Whole Cities Foundation365 by Whole Foods Market'),
('6197', '263', 'User Login');