INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('6431', '5', 'Add the liquor, fish and pepper, and cook another few minutes, just until the fish is cooked through. Press on the cheesecloth to release as much liquid as you can before discarding. Adjust the texture and seasonings to taste.'),
('6431', '6', 'Add fresh fennel leaves to garnish, if desired. Makes a dozen ample servings.'),
('6432', '1', 'Heat the olive oil in a Dutch oven over medium-high heat.'),
('6432', '2', 'Add onion and garlic, and saut for 5 minutes or until lightly browned.'),
('6432', '3', 'Add tomatoes, 1/2 cup olives, water, 2 tablespoons capers, 2 tablespoons jalapeos, parsley, oregano, and bay leaves. Bring to a boil; reduce heat, and simmer 30 minutes or until reduced to 6 cups. Stir in 1/2 teaspoon salt. Discard bay leaves.'),
('6432', '4', 'Arrange fish in a single layer in a 13 x 9-inch baking dish; drizzle with lime juice, and sprinkle with 1/2 teaspoon salt. Cover and marinate in refrigerator 30 minutes; discard marinade.'),
('6432', '5', 'Preheat oven to 35'),
('6432', '6', 'Spoon sauce over fish.'),
('6432', '7', 'Bake at 350 for 15 minutes or until fish flakes easily when tested with a fork. Sprinkle with 1/2 cup olives, 2 tablespoons capers, and 2 tablespoons jalapeos.'),
('6432', '8', 'Garnish with parsley sprigs, if desired.'),
('6434', '1', 'Cook bacon in large skillet on medium heat until crisp.  Use slotted spoon to remove bacon from skillet; drain on paper towels.  Discard drippings from skillet.  Wipe out skillet with additional paper towels.'),
('6434', '2', 'Add peppers, onions and garlic to skillet; cook and stir 5 min. or until crisp-tender.'),
('6434', '3', 'Cut banana leaves into 6 (12-inch) squares.'),
('6434', '4', 'Cut trimmings into thin strips; set aside for later use.'),
('6434', '5', 'Place 1 fish fillet in center of each banana leaf; top with 1 epazote leaf, about 3/4 cup vegetable mixture, bacon and 1 tsp. dressing.  Fold in opposite sides of each banana leaf to form packet; tie closed with banana leaf strips.'),
('6434', '6', 'Place packets in steamer; cover.  Cook 25 min.'),
('6435', '1', 'Bring about 1 1/2 inches of water to boil in a steamer fitted with a basket large enough for the snapper to lie flat. Season snapper with salt and pepper, and place in the steamer basket. Top fish with ginger, and drizzle with soy sauce and sesame oil.'),
('6435', '2', 'Place shiitake mushrooms, tomato, and red chile pepper in the steamer basket.'),
('6435', '3', 'Steam fish 15 minutes, or until easily flaked with a fork. Sprinkle with cilantro.'),
('6436', '1', 'Cut eggs in half.'),
('6436', '2', 'Remove yolks; set aside. Coarsely chop whites; place in medium bowl.  Stir in tomatoes, peppers and ham.'),
('6436', '3', 'Blend mayo, water, bread and egg yolks in blender until smooth.'),
('6436', '4', 'Coat fish with flour; gently shake off excess.'),
('6436', '5', 'Heat dressing in large skillet on medium-high heat.'),
('6436', '6', 'Add fish; cook 4 min. on each side or until fish flakes easily with fork.'),
('6436', '7', 'Place fish on plate; top with tomato mixture and mayo mixture.'),
('6437', '1', 'Place fish and peppers in foil-lined 15x10x1-inch baking pan.'),
('6437', '2', 'Brush with half of the dressing.  Broil 10 min. or until fish flakes easily with fork and peppers are crisp-tender, turning over after 5 min. and brushing occasionally with the remaining dressing.  Cover fish to keep warm.'),
('6437', '3', 'Cut peppers into chunks; place in blender container.'),
('6437', '4', 'Add chicken broth and onions; cover.  Blend until pureed; pour into saucepan.  Bring to boil on medium-high heat.  Reduce heat to low; simmer 5 min., stirring occasionally.'),
('6437', '5', 'Remove from heat.'),
('6437', '6', 'Add cream cheese spread; stir until well blended.'),
('6437', '7', 'Serve fish topped with the red pepper sauce.'),
('6438', '1', 'Heat 3 tablespoons oil in heavy large pot over medium heat.'),
('6438', '2', 'Add onion; sauté 5 minutes.'),
('6438', '3', 'Add carrot, celery, and garlic; sauté 5 minutes.'),
('6438', '4', 'Add tomatoes with juices and 1 bottle clam juice and bring to boil. Reduce heat; simmer uncovered 10 minutes. Cover and simmer 10 minutes.'),
('6438', '5', 'Transfer mixture to processor. Blend to chunky puree; return to pot.'),
('6438', '6', 'Mix in 2 bottles clam juice to make tomato broth.'),
('6438', '7', 'Combine mussels, clams, and wine in another large pot. Cover and cook over high heat until mussels and clams open, about 8 minutes. Using tongs, transfer mussels and clams to bowl (discard any that do not open). Strain cooking liquid into tomato broth.'),
('6438', '8', 'Place couscous in large bowl. Bring 2 1/2 cups water, 3 cups tomato broth, and 1/4 cup oil to boil in medium saucepan.'),
('6438', '9', 'Mix into couscous. Cover; let stand until liquid is absorbed, about 10 minutes. Season with salt and pepper. Cover; let stand until ready to serve.'),
('6438', '10', 'Meanwhile, mix thyme and bay leaves into remaining tomato broth in pot and bring to boil over medium-high heat.'),
('6438', '11', 'Add fish. Cover and simmer 4 minutes.'),
('6438', '12', 'Add shrimp; cover and simmer until seafood is opaque in center, about 4 minutes. Turn off heat.'),
('6438', '13', 'Add reserved mussels and clams. Cover; let stand 2 minutes.'),
('6438', '14', 'Mound couscous on platter. Top with seafood. Spoon some tomato broth over to moisten. Sprinkle with parsley.'),
('6438', '15', 'Mix 3/4 cup tomato broth and hot chili paste in small dish.'),
('6438', '16', 'Serve couscous, passing chili mixture and remaining broth separately.'),
('6438', '17', '* Sambal oelek is available in Asian markets and some supermarkets.'),
('6440', '1', 'Preheat broiler.  Using a sharp paring knife, cut a 1/2-inch-thick slice off top and bottom ends of 2 of the oranges.'),
('6440', '2', 'Cut peel and white pith away from fruit, using downward cutting motion following shape of fruit.'),
('6440', '3', 'Place peeled fruit piece on its side, then cut down along membrane on both sides of each section to remove fruit.  Set orange sections aside.'),
('6440', '4', 'Cut remaining orange horizontally into 8 slices.'),
('6440', '5', 'Place on foil-covered baking sheet; top with fish.'),
('6440', '6', 'Mix mayo and half of the bacon; spread evenly over fish.  Top with orange sections and olives.'),
('6440', '7', 'Broil, 6 to 7 inches from heat, 15 min. or until fish flakes easily with fork and oranges are beginning to brown.  Sprinkle with remaining bacon.'),
('6442', '1', 'Pour dressing over fish in shallow dish; turn to evenly coat both sides of each fillet.  Refrigerate 20 min. to marinate.'),
('6442', '2', 'Meanwhile, blend next 4 ingredients in blender until smooth; pour into bowl.  Stir in parsley.  Refrigerate until ready to use.'),
('6442', '3', 'Heat large nonstick skillet on medium-high heat.'),
('6442', '4', 'Remove fish from marinade; discard marinade.'),
('6442', '5', 'Add fish to skillet; cook 6 min. on each side or until fish flakes easily with fork.'),
('6442', '6', 'Serve topped with sauce.'),
('6443', '1', 'Cook onion, fennel, and chiles in oil over medium heat in a Dutch oven until onion is tender.'),
('6443', '2', 'Add bell pepper and garlic; cook, stirring constantly, 3 minutes. Stir in tomatoes and next 5 ingredients. Bring to a boil; cover, reduce heat, and simmer 45 minutes.'),
('6443', '3', 'Stir in zucchini and rosemary; bring to a simmer, and simmer 10 minutes.'),
('6443', '4', 'Remove and discard bay leaf. Stir in salt and pepper.'),
('6443', '5', 'Add scallops and shrimp, and cook 3 minutes.'),
('6443', '6', 'Add mussels and fish; cook 4 more minutes or until mussels open and fish flakes easily when tested with a fork.'),
('6444', '1', 'Preheat oven to 40'),
('6444', '2', 'To prepare rouille, combine roasted red bell peppers and mayonnaise in a blender or food processor; process until smooth. Set aside.'),
('6444', '3', 'To prepare the croutons, arrange baguette slices in a single layer on a baking sheet; bake slices at 400 for 8 minutes or until toasted. Rub one side of each crouton with cut side of garlic clove halves; discard garlic clove halves. Set croutons aside.'),
('6444', '4', 'To prepare bouillabaisse, heat oil in a large Dutch oven over medium heat.'),
('6444', '5', 'Add onion and garlic to pan; cook 8 minutes or until tender.'),
('6444', '6', 'Add tomato; cook 3 minutes.'),
('6444', '7', 'Add saffron; cook 30 seconds.'),
('6444', '8', 'Add potato, fennel, clam juice, and broth; bring to a boil. Cover, reduce heat, and simmer 10 minutes or until potato is almost done. Increase heat to medium.'),
('6444', '9', 'Add clams; cover and simmer 5 minutes.'),
('6444', '10', 'Add mussels; cover and simmer 3 minutes.'),
('6444', '11', 'Add shrimp and fish; cover and simmer 5 minutes or until shells open, shrimp is done, and fish flakes easily with a fork or until desired degree of doneness. Discard any unopened shells.'),
('6444', '12', 'Ladle 2 cups seafood mixture into each of 6 shallow bowls.'),
('6444', '13', 'Spread each crouton with about 1 tablespoon rouille.'),
('6444', '14', 'Place 1 crouton on top of each bowl; sprinkle each serving with 1 tablespoon parsley.'),
('6445', '1', 'Lightly salt the shrimp and red snapper and arrange on a platter at the table with the mussels and lemon wedges. In a fondue pot, bring the water, wine, and cilantro to a boil, then reduce the heat to a gentle simmer. Season with salt to taste. Provide each diner with a soup bowl.'),
('6445', '2', 'Add the mussels, a few pieces at a time. Cook about 4 minutes.'),
('6445', '3', 'Add the shrimp and red snapper, a few pieces at a time, without crowding the broth, and cook until just opaque and the mussels open, about 2 minutes. Discard any mussels that dont open.'),
('6445', '4', 'Diners transfer portions to their individual bowls and add a spoonful of one of the sauces and a squeeze of lemon.'),
('6446', '1', 'Preheat oven to 475 with a rack set at the top level. Sprinkle both sides of fillets with 1/2 tsp. each salt and pepper, then set on a baking sheet lined with foil.'),
('6446', '2', 'Brush tops of fillets with 2 tsp. olive oil and squeeze a little lemon on top.'),
('6446', '3', 'Combine panko, parmesan, nuts, parsley, zest, remaining 1 tsp. olive oil, and a pinch of salt and pepper. Evenly cover fillets with almond mixture.'),
('6446', '4', 'Bake until fish is opaque in center, 6 to 8 minutes.'),
('6446', '5', 'Serve with more lemon.'),
('6447', '1', 'Start by peeling the ginger and julienne it. You should have about 2 Tbsp when shredded.'),
('6447', '2', 'Place 1 Tbsp in a small bowl on the side.With the other Tbsp, take a frying pan pour about a large Tbsp of safflower oil.'),
('6447', '3', 'Heat on high and when ready, fry for a few min. When done, put on a paper towel to absorb the excess of oil, and set aside (for decoration)Wash the scallions and slice them diagonally-wise. Take a small pot and heat some water in it. Blanch the scallions for a few min and set aside.Take a frying pan and dry roast the pine nuts. Then crush them coarsely.Chop the coriander thinly.'),
('6447', '4', 'Mix together the ginger placed in the bowl, the pine nuts, the scallions, the peanut oil, and the fish sauce; set aside.Take your sole fillets and brush them with peanut oil, with salt and pepper on both side.Take a steamer and steam the fish for a few min only.You can now assemble your dish'),
('6447', '5', 'Place the fish on a warm plate, and place the ginger/scallion pesto on top. Decorate with fried ginger.'),
('6447', '6', 'Serve immediately, with steamed jasmine rice and a few greens (I also served it with mashed squash and steamed fennel, and it was delicious! See below)'),
('6450', '1', 'Heat the wine in a large skillet over medium heat.'),
('6450', '2', 'Add the sole, drizzle with the oil, and season with 1/4 teaspoon salt and 1/8 teaspoon pepper. Sprinkle the capers over the top and cook, covered, until just cooked through, opaque, and beginning to flake, about 4 minutes. Sprinkle with the chives. Divide among individual plates, spooning the wine and caper sauce over the top.'),
('6451', '1', 'Measure juice from citrus salsa. If needed, add orange juice to make 1/3 cup.'),
('6451', '2', 'Place fillets of sole in a heavy zip-lock plastic bag and pour in juice. Seal bag and chill for 15 minutes.'),
('6451', '3', 'Meanwhile, in a blender or food processor, pulse cashews until finely ground. In a shallow bowl, mix nuts with panko, salt, and pepper.'),
('6451', '4', 'Pour 2 tablespoons oil into a 10- to 12-inch nonstick frying pan over medium-high heat; when hot, lift fillets from juice. Dip each in egg, then in cashew mixture to coat. Working in batches, place fillets in a single layer in pan (do not crowd). Cook until browned on the bottom, about 2 minutes; turn with a wide spatula and cook until other side is browned and fish is opaque but still moist-looking in center (cut to test), about 2 minutes longer.'),
('6451', '5', 'Drain briefly on paper towels; keep warm in a 200 oven. Repeat to fry remaining fish, wiping out pan with paper towels and adding 2 tablespoons oil between batches.'),
('6451', '6', 'Transfer fillets to plates and top with citrus salsa; serve at once with remaining salsa alongside.'),
('6456', '1', 'Dredge the filets in flour until well-coated.'),
('6456', '2', 'Heat 4 tablespoons butter or ghee in a cast iron skillet over a medium flame until the butter begins to foam and brown (this foaming process will not occur if youre using ghee or clarified butter).Reduce heat to medium-low, then place the floured filets of sole into the hot butter and fry on each side about two minutes.'),
('6456', '3', 'Remove the fish from the skillet and plate them.'),
('6456', '4', 'Heat additional two tablespoons butter in the skillet until melted, then add lemon zest, lemon juice and minced parsley to the skillet whisking together to combine for about one minute.'),
('6456', '5', 'Pour sauce over the fish, season with salt and pepper and garnish with lemon wedges.'),
('6459', '1', 'Preheat an oven to 375F. Lightly butter an 8-by-12-inch gratin dish.In a saucepan over medium-low heat, melt the butter. Stir in the flour to make a roux and cook, stirring constantly, for 2 to 3 minutes; do not let the mixture color. Gradually whisk in the milk. Increase the heat to medium and bring the mixture to a simmer, whisking frequently. Adjust the heat to maintain a low simmer and cook, whisking frequently, until thickened into a white sauce, about 10 minutes.'),
('6459', '2', 'Whisk in the 1 tsp. salt and white pepper to taste. Cover and set aside.'),
('6459', '3', 'Place the spinach in a small stockpot and set over medium heat. Cover and cook until wilted, about 3 minutes. Empty into a colander and run cold water over the spinach to cool. In small handfuls, squeeze as much water from the spinach as possible. Using a chefs knife, chop the spinach finely.'),
('6459', '4', 'Transfer to a bowl and stir in 1/2 cup of the white sauce. Season with salt and pepper.Lay the sole fillets, smooth skin side down, on a cutting board. Check the fish for bones, removing and discarding any you find. Spoon one-fourth of the spinach mixture onto the center of each fillet, and fold the 2 ends of the fillet over the top of the spinach. Using a metal spatula, transfer each fillet, seam side down, to the prepared dish.In a blender, combine all but 1/4 cup of the shrimp, the remaining white sauce, the stock and the tomato paste and puree until smooth.'),
('6459', '5', 'Transfer to a bowl and season with salt and cayenne.'),
('6459', '6', 'Pour the sauce over the sole and bake until the fish is opaque throughout, about 25 minutes. Sprinkle the remaining shrimp on top of the fish and bake for 5 minutes more. Sprinkle with chives and serve immediately.'),
('6459', '7', 'Serves 4.Adapted from Williams-Sonoma Collection Series, Seafood, by Carolyn Miller (Simon & Schuster, 2005).'),
('6465', '1', 'Trim and discard discolored stem ends from mushrooms; thinly slice mushrooms. In a 10- to 12-inch frying pan over high heat, stir mushrooms in 1 tablespoon butter often until lightly browned, 12 to 15 minutes. Spoon into a shallow 1 1/2-quart casserole or divide equally among 4 shallow ramekins (about 1 1/2 cups each).'),
('6465', '2', 'Add remaining butter and the onion and chilies to pan. Stir often until onion is limp, about 5 minutes.'),
('6465', '3', 'Add flour, mix well, and stir in broth. Pure mixture in a blender or food processor; return to pan.'),
('6465', '4', 'Add sour cream and stir over high heat until boiling.'),
('6465', '5', 'Remove from heat and add lime juice. Rinse fish, arrange in an even layer over mushrooms in casserole (or equally in ramekins), and cover with sauce.'),
('6465', '6', 'Bake in a 400 oven until fish flakes when prodded, 12 to 15 minutes. Season with salt.'),
('6466', '1', 'Combine first 8 ingredients in a bowl; stir in 1/2 teaspoon salt and 1/8 teaspoon black pepper.'),
('6466', '2', 'Heat oil in a large nonstick skillet over medium-high heat. Sprinkle fish with 1/2 teaspoon salt and 1/8 teaspoon black pepper.'),
('6466', '3', 'Add fish to pan; cook 1 1/2 minutes on each side or until fish flakes easily when tested with a fork.'),
('6466', '4', 'Serve with salsa.'),
('6468', '1', 'Drizzle each sole fillet with 1 tsp lemon juice, 1 tsp soy sauce,  tsp ginger, and a light, even drizzle of sesame oil. Gently roll the fillets lengthwise and arrange them on a heatproof plate.'),
('6468', '2', 'Fill a large saucepan fitted with a steamer with 1in (2.5cm) water; bring to the boil, then reduce the heat to a simmer.'),
('6468', '3', 'Blanch the bok choy leaves for several seconds in the water, or until soft, then place them briefly into a bowl of iced water.'),
('6468', '4', 'Wrap each fillet in 45 leaves, securing with cocktail sticks if necessary. Set the plate with the fish on the steamer rack, place the lid on the steamer, and steam for 810 minutes, or until the fish becomes opaque.'),
('6468', '5', 'Good with a mix of stir-fried vegetables, or with boiled white rice.'),
('6469', '1', 'Heat up a small pot of water and bring it to boil.'),
('6469', '2', 'Add a few drops of cooking oil into the water (to preserve the color of the Brussels sprouts) and boil the Brussels sprouts for two minutes.'),
('6469', '3', 'Drain and set aside.'),
('6469', '4', 'Heat up the wok and add the cooking oil.'),
('6469', '5', 'Add the sliced garlic and do a quick stir.'),
('6469', '6', 'Add in the dried sole fillet pieces and stir fry until they turn golden brown and crispy.'),
('6469', '7', 'Add in the Brussels sprouts, oyster sauce, water and stir fry for 1 minute.'),
('6469', '8', 'Add the sesame oil, a dash of white pepper powder and a pinch of sugar.'),
('6469', '9', 'Dish up and serve hot.'),
('6472', '1', 'Dip fillets in beaten egg, and then in bread crumbs.'),
('6472', '2', 'In an electric fryer, heat oil to 375 degrees F (190 degrees C).  Fry fish until golden brown.'),
('6472', '3', 'Transfer to a dish, and keep warm.'),
('6472', '4', 'In a small saucepan, melt butter over medium heat.'),
('6472', '5', 'Add garlic, and saute for 1 to 2 minutes. Stir in chicken broth, wine, and lemon juice; bring to a boil. Season with salt and pepper.'),
('6472', '6', 'Remove from heat, and stir in chopped parsley.'),
('6472', '7', 'Serve butter sauce over fish fillets.'),
('6473', '1', 'In a small bowl, combine lemon juice, green onion, garlic, and wine.  Set aside.'),
('6473', '2', 'Lay filets flat, and divide shrimp evenly among them in a band across one end of each fillet.'),
('6473', '3', 'Roll up around shrimp, and secure with toothpick.'),
('6473', '4', 'Place in a baking dish.  Season to taste with salt, pepper, and paprika.'),
('6473', '5', 'Pour lemon juice mixture over the fish.  Cover.'),
('6473', '6', 'Bake at 350 degrees F (175 degrees C) for 25 minutes.'),
('6473', '7', 'When fillets are nearly done, prepare sauce. In a small saucepan, melt butter over medium heat. Stir in flour.'),
('6473', '8', 'Transfer fish to serving platter ,and keep warm.'),
('6473', '9', 'Pour pan juices into butter/flour mixture; cook and stir until thickened.'),
('6473', '10', 'Pour over sole, and serve.'),
('6475', '1', 'Rinse lemon, and with a small, sharp knife, cut off and discard peel and white membrane. Thinly slice lemon crosswise, discarding seeds and ends.'),
('6475', '2', 'Rinse sole and pat dry. If fillets are longer than 6 or 7 inches, cut in half crosswise so they''ll be less likely to break when you turn them. Sprinkle each fillet lightly with salt. Coat on all sides with flour, shake off excess, and lay pieces side by side on a sheet of plastic wrap.'),
('6475', '3', 'In a 12- to 14-inch frying pan over high heat, melt 2 tablespoons butter; when hot, lay as many pieces as will fit side by side in pan without crowding and cook until browned on the bottom, 1 1/2 to 2 minutes. Turn with a wide, flexible metal spatula and brown remaining side, 1 to 2 minutes longer (if butter begins to scorch, reduce heat to medium-high). With spatula, transfer fillets to an ovenproof platter, laying pieces side by side, and keep warm in a 200 oven. Melt 1 more tablespoon butter in frying pan; repeat step to cook remaining sole fillets, transfer to platter, and keep warm in the oven.'),
('6475', '4', 'With a paper towel, wipe frying pan clean and return to high heat.'),
('6475', '5', 'Add 1 to 2 more tablespoons butter and the capers; stir until butter is melted.'),
('6475', '6', 'Add lemon juice, remove from heat, and stir in about 3 tablespoons of the parsley. At once, scrape butter mixture over hot fish fillets.'),
('6475', '7', 'Garnish with lemon slices and remaining parsley and sprinkle generously with pepper. With spatula, transfer fillets to plates. Season to taste with more salt.'),
('6476', '1', 'Preheat oven to 450F.'),
('6476', '2', 'Heat oil in a large saut pan and cook chard, carrots, celery and half of scallions until soft, about 8 minutes.'),
('6476', '3', 'Let cool slightly, then toss with orange juice and zest. Season to taste with salt and pepper and set aside.'),
('6476', '4', 'Cut a 2-foot length of parchment paper (or foil) and place on a sheet pan. Spoon about 2 tablespoons veggie mixture onto each fish fillet. Gently roll each fillet and secure with toothpicks. Arrange fillets on one half of the paper. Sprinkle with pepper, top with lemon slices and any remaining sauce. Fold paper in half and crimp edges until well sealed.'),
('6476', '5', 'Bake 12 to 18 minutes until fish is opaque.'),
('6476', '6', 'Remove rolls and sprinkle with remaining scallions.'),
('6476', '7', 'Remove toothpicks.'),
('6476', '8', 'Serve.'),
('6477', '1', 'In a small bowl, combine the butter, lemon juice, salt and pepper. In another bowl, combine the broccoli, rice, cheese and half of the butter mixture. Spoon 1/2 cup onto each fillet.'),
('6477', '2', 'Roll up and place seam side down in a baking dish coated with nonstick cooking spray.'),
('6477', '3', 'Pour remaining butter mixture over roll-ups.'),
('6477', '4', 'Bake, uncovered, at 350 degrees F for 25 minutes or until fish flakes easily with a fork. Baste with pan drippings; sprinkle with paprika.'),
('6478', '1', 'Stir together the quinoa, 1/2 cup water, parsley, basil, and lemon zest in a small saucepan over high heat. Bring to a boil, then reduce heat to medium-low, cover, and simmer until the quinoa is tender, about 20 minutes.'),
('6478', '2', 'Pour into a mixing bowl, fold in the Parmesan cheese, and allow the mixture to cool.'),
('6478', '3', 'Preheat the oven''s broiler and set the oven rack at about 6 inches from the heat source. Lightly grease a small baking dish.'),
('6478', '4', 'Spoon a quarter of the quinoa mixture onto one end of each sole fillet. Fold the other side of the sole overtop, sprinkle with black pepper, and place a lemon slice on top.'),
('6478', '5', 'Place the sole into the prepared baking dish, and add the vinegar and remaining water.'),
('6478', '6', 'Broil in the preheated oven until the sole flakes easily with a fork, and the flesh is opaque, 3 to 4 minutes.'),
('6479', '1', 'Preheat the oven to 200 degrees F. Have 2 heat-proof dinner plates ready'),
('6479', '2', 'Combine the flour, 2 teaspoons salt, and 1 teaspoon pepper in a large shallow plate. Pat the sole fillets dry with paper towels and sprinkle one side with salt.'),
('6479', '3', 'Heat 3 tablespoons of butter in a large (12-inch) saute pan over medium heat until it starts to brown. Dredge 2 sole fillets in the seasoned flour on both sides and place them in the hot butter. Lower the heat to medium-low and cook for 2 minutes. Turn carefully with a metal spatula and cook for 2 minutes on the other side. While the second side cooks, add 1/2 teaspoon of lemon zest and 3 tablespoons of lemon juice to the pan. Carefully put the fish filets on the ovenproof plates and pour the sauce over them. Keep the cooked fillets warm in the oven while you repeat the process with the remaining 2 fillets. When they''re done, add the cooked fillets to the plates in the oven. Sprinkle with the parsley, salt, and pepper and serve immediately.'),
('6480', '1', 'Preheat oven to 35'),
('6480', '2', 'Fold 4 pieces of parchment paper (12 by 14 in. each) in half to form 7- by 12-in. rectangles and cut them into half-heart shapes as large as the paper allows. Unfold into hearts.'),
('6480', '3', 'Place a fish fillet to one side of center of each heart and sprinkle with 1/4 of the salt.'),
('6480', '4', 'Spread each fillet with 1/4 of the ginger.'),
('6480', '5', 'Drizzle with 1/4 of the sesame oil and top with 1/4 of the green onions. Fold papers over fillets and crimp edges to close (see "How to Make a Parchment Packet," below).'),
('6480', '6', 'Put packets on a baking sheet and bake 15 minutes, or until the fish is opaque and flakes easily in the center; if necessary, cook 5 minutes more.'),
('6480', '7', 'Serve hot.'),
('6480', '8', 'How to Make a Parchment Packet: The key to cooking en papillote starts with the shape of the paper. Fold a piece of parchment paper, about 2 1/2 times the size of what you''ll be cooking, in half and cut it into a half-heart shape. Unfold, fill one half with the ingredients, and fold the other half over to enclose. Starting at the top of the heart in the center of the dip, fold about 1/4 in. of the edge toward the center and start rolling this "hem" around the edge, crimping the roll as you seal it. When the roll reaches the bottom tip of the heart, twist to seal. When using aluminum foil, simply fold foil over contents and crimp edges to seal.'),
('6481', '1', 'Tip:To make citrus segments, just slice the ends off the fruit with a small, sharp knife. Stand the fruit on one of its cut ends and slice off the skin in strips (try to get all the bitter white pith). Working over a bowl, cut the segments free from the membrane, letting each segment fall into the bowl as you go.'),
('6481', '2', 'Remove any seeds from the segments.'),
('6481', '3', 'Heat the oven to 200F. Melt 1-1/2 Tbs. of the butter in a 10- to 12-inch nonstick skillet over medium heat.'),
('6481', '4', 'Add the bread cubes to the pan, stirring and tossing almost constantly with a wooden spoon, until the cubes are golden brown and crisp, 3 to 5 minutes.'),
('6481', '5', 'Drain on paper towels and sprinkle with salt. Wipe out the skillet.    Segment the whole lemon.'),
('6481', '6', 'Cut each segment into four pieces.'),
('6481', '7', 'Transfer to a small bowl and add 1 Tbs. juice squeezed from the lemon half.    Season the sole fillets lightly on each side with salt and pepper and dredge the fillets in the flour, shaking off any excess.'),
('6481', '8', 'Heat the oil in the nonstick skillet over medium-high heat. Working in batches to avoid crowding the pan, cook the fillets until the first side is light golden, about 2 minutes. Using two spatulas to support the delicate fish, flip the fillets and cook until the second side is light golden and the fillets are opaque, another 2 minutes.'),
('6481', '9', 'Transfer to two dinner plates and keep warm in the oven.    Wipe out the skillet with a paper towel and add the remaining 3 Tbs. butter. Over medium-high heat, melt the butter and cook, swirling the pan until the butter turns a medium brown, about 2 minutes. Immediately remove the skillet from the heat and add the lemon segments and lemon juice, the capers, and the parsley; season to taste with salt and pepper.'),
('6481', '10', 'Drizzle the sauce over the fish and sprinkle on the croutons.    Serving Suggestions'),
('6481', '11', 'Serve with herbed rice pilaf.'),
('6483', '1', 'Using a long spatula, gently lift the braids onto a lightly oiled baking sheet. Give them a little of salt and a grind of pepper.'),
('6483', '2', 'Bake in a preheated 350 oven for 15 minutes, until just cooked through. Use the spatula to transfer toserving plates, remembering to remove the toothpicks first!Le Bec-Fin''s recipe included some complicated sauces  I find the beauty of the braid is lovely as is. If you do want to dress with sauce, do as the Le Bec Fin does: serve them in puddles on the sides, so the design of the braid is not obscured.'),
('6486', '1', 'Heat up the wok and add in some cooking oil.'),
('6486', '2', 'Add sliced ginger, onions, bell peppers, dried red chilies and stir fry them until aromatic.'),
('6486', '3', 'Add in the fish and do a quick stir.'),
('6486', '4', 'Add the black bean sauce, fish sauce, sugar, and sesame oil and stir fry until the fish is cooked.'),
('6486', '5', 'Add in the corn starch mix to thicken the sauce.6)Toss in the chopped scallion and do a quick stir, dish up and serve hot.'),
('6487', '1', 'In a microwave-safe bowl, combine the butter and almonds.'),
('6487', '2', 'Heat, uncovered, on high for 2 minutes or until almonds are golden brown.'),
('6487', '3', 'Place the fillets in a greased microwave-safe 11-in. x 7-in. x 2-in. dish. Top with almond mixture.'),
('6487', '4', 'Combine the lemon juice, dill, salt and pepper; drizzle over fish. Sprinkle with paprika. Cover and microwave on high for 4 minutes or until fish flakes easily with a fork.'),
('6488', '1', 'Rinse fish and pat dry. In a medium size, wide bowl mix breadcrumbs, Italian Seasoning, parsley, garlic salt, salt and pepper. Coat fish lightly with olive oil, then dip in breadcrumb mixture. Preheat oven to 350 degrees and place prepared fish on foil lined cookie sheet to minimize clean-up. Cook for 3  minutes and flip fish once. Cook for no more than 7 minutes total  this will depend on the type of fish. Mangia bene!'),
('6489', '1', 'Make sure the salmon and sole do not have any bones left in the flesh. If they do, pull them out with a pair of tweezers or electricians pliers (be sure to clean them first). Also, remove the skin from the fillets and remove the shells and "vein" from the prawns.Lay a large piece of cling-film/plastic-wrap on a work surface, put the salmon on top of this and then lay another large piece of cling-film/plastic-wrap on top of the salmon.Using a rolling pin or the flat side of a meat hammer, gently flatten the salmon until it is about 1cm thick (be careful not to hit the salmon too hard as it crushes very easily).'),
('6489', '2', 'Remove the top layer of cling-film/plastic-wrap, chop the dill finely and sprinkle this over the salmon, then season it with salt & pepper.Flatten the sole fillets in the same way as the salmon but make it cm thick, then lay these on top of the salmon leaving a 3cm - 5cm gap along on side of the salmon.Lay the shelled prawns in a straight line down the middle of the sole fillets, then season with salt & pepper again.Using the cling-film/plastic-wrap, roll up the salmon into a neat sausage, starting at the opposite edge to the gap left by the sole fillets, then wrap it in another piece of cling-film/plastic-wrap and put it in the fridge for 30 minutes to set the shape.Preheat the oven to 210c.After 30 minutes, roll out the pastry to a thickness of about 2mm, remove the cling-film/plastic-wrap from the rolled salmon and place it on the pastry, a third of the way in from an edge.Fold the pastry over the salmon and roll it up until the pastry overlaps itself by 1cm, then cut off any excess.Seal the long edge of the pastry with a little water, fold the two open ends upwards onto the seam, seal them down with a little water and then turn the whole thing over, so the seam is underneath.'),
('6489', '3', 'Put the puff-pastry parcel onto a baking tray lined with greaseproof paper, mix the egg yolk with 1 teaspoon of water to make an eggwash and brush this onto the surface of the pastry. Then put it in the oven for 25 minutes.'),
('6489', '4', 'Cut into portions and serve.'),
('6495', '1', 'Butter two 2-cup au gratin dishes.'),
('6495', '2', 'Place 1 fillet on bottom of each, then layer with scallops, crabmeat, shrimp, cheese and a second fillet; set aside.'),
('6495', '3', 'Preheat oven to 450 degrees F (230 degrees C).'),
('6495', '4', 'Melt butter. In a medium mixing bowl, combine yolks, lemon juice, mustard and salt; mix on high and slowly add butter in a steady stream until sauce is thick and creamy.'),
('6495', '5', 'Pour sauce over fillets.'),
('6495', '6', 'Bake in preheated oven for 10 to 15 minutes; sprinkle with parsley and paprika.'),
('6495', '7', 'Serve.'),
('6499', '1', 'preheat your oven to 350 degrees.spray a baking sheet with cooking spray.lay your fillets evenly spaced on the sheet.evenly & gently pour the lemon juice over each fillet- creating a moist side.sprinkle cajun seasoning over each fillet coating well - almost giving the image of blackened sole.bake for 30 minutes (max) -VEGETABLES -Microwave your cauliflour until cooked but still a little crunchy (approx. 8 - 10 mins).finely cut up your green onion and toss into the bean bowl.microwave your frozen french cut green beans & onion until done (approx 8 mins).'),
('6499', '2', 'Drain any liquid from the vegetables and toss together with the butter, salt and pepper totaste.'),
('6499', '3', 'Serve while still hot and fish is fresh from the oven. These two dishes take approximately the same time to cook / prepare and cook so there is no wait time between dishes.Enjoy Bon Appetite !'),
('6500', '1', 'Preheat oven (200C, 390F).Peel potatoes or just wash them thoroughly.'),
('6500', '2', 'Cut them into thick slices (about 1/4 inch or a little thicker).'),
('6500', '3', 'Mix them in a bowl with a little olive oil.'),
('6500', '4', 'Brush a little olive oil on a baking tray. Lay the potatoes in a single layer on the baking tray. The layer of potatoes should fit the size of the sole. Sprinkle with salt to taste.'),
('6500', '5', 'Remove the leaves of 3 sprigs rosemary and sprinkle them onto the potatoes. Half the olives and arrange on the potatoes. Cover potatoes with aluminium foil and bake for 20 minutes.'),
('6500', '6', 'Remove aluminium foil and let bake for another 10 minutes to brown the potatoes slightly.Meanwhile, cut the pancetta into pieces.'),
('6500', '7', 'Brush the sole lightly with olive oil and salt slightly to taste.'),
('6500', '8', 'Put the fish onto the layer of potatoes, arrange pancetta on the sole.'),
('6500', '9', 'Remove the leaves from one sprig of rosemary and sprinkle them above the sole. Put some olive oil onto the sole.'),
('6500', '10', 'Bake the sole for about 10 minutes in the middle of the oven. After 10 minutes the fish should almost be done. To brown it a little put tray in the upper part of the oven and broil for just a few minutes (2-5 minutes) longer.Meanwhile remove the lower and hard parts of the arugula leaves and put them into a bowl. Flavour 2 tablespoons of olive oil with 1 teaspoon of lemon juice.'),
('6500', '11', 'Mix flavoured oil with arugula prior to serving.'),
('6500', '12', 'Cut the rest of the lemon into slices.Take the fish out of the oven, sprinkle with some arugula leaves and decorate with some lemon slices.'),
('6500', '13', 'Serve fish on baking tray with the rest of the arugua as a salad and some white bread.NOTE: you can do this recipe also with other plaice, like flounder.'),
('6501', '1', 'In medium bowl, whisk together soy sauce, sugar, rice wine, and five-spice powder.'),
('6501', '2', 'Transfer fish to 2 rimmed plates.'),
('6501', '3', 'Drizzle each piece with 1 tablespoon soy sauce mixture and scatter with julienned ginger. (Set remaining sauce aside for finishing dish.) Cover and refrigerate 15 minutes.'),
('6501', '4', 'Fit large saucepan with flat steamer basket, fill with 1 inch water, and bring to boil over high heat. Reduce heat to low and transfer 1 plate to steamer basket. Cover and steam 4 minutes. Without lifting lid, turn off flame and allow residual heat to finish cooking until fish is just cooked through, about 1 minute more. Carefully remove plate (keep warm in oven). Return water in steamer to boil, transfer second plate to steamer, and steam remaining fish in same manner.'),
('6501', '5', 'While fish is steaming, in small saucepan over moderate heat, heat vegetable oil. Keep warm.'),
('6501', '6', 'Divide fish among 4 plates and top with julienned scallions.'),
('6501', '7', 'Pour splash of hot oil over each dish.'),
('6501', '8', 'Serve immediately with bok choy.'),
('6502', '1', 'Heat 1 tablespoon of the oil in a medium pot over medium-high heat.'),
('6502', '2', 'Add garlic, onions and mushrooms and cook, stirring frequently, until onions are translucent and mushrooms have wilted, about 5 minutes.'),
('6502', '3', 'Add rice and toast, stirring constantly, until fragrant, 3 to 4 minutes.'),
('6502', '4', 'Add broth and bay leaf, stir well, bring to a boil and then cover. Reduce heat to low and simmer until all of the moisture is absorbed, about 40 minutes. Set pot aside off of the heat, covered, for 15 minutes; remove and discard bay leaf and fluff rice with a fork. Set aside, uncovered.Arrange a rack about 8 inches from the heating element in your oven; preheat broiler. Arrange fish on an oiled foil-lined baking sheet in a single layer.'),
('6502', '5', 'Drizzle with remaining 1 tablespoon oil and season with salt and pepper. Broil until almost cooked through, 3 to 4 minutes. Divide orange slices among the fillets, arranging them over the top of each and return to the oven. Broil until fish is cooked through and oranges are deep golden brown around edges, 2 to 3 minutes more.Spoon pilaf onto plates and top with fillets.'),
('6502', '6', 'Serve immediately.'),
('6504', '1', 'Sprinkle each fillet with juice and pepper.  Arrange broccoli spears on narrow end of each fish fillet; roll up.  Secure with toothpicks.'),
('6504', '2', 'Place, seam side down, in 10x6-inch microwavable dish; cover.'),
('6504', '3', 'Microwave on HIGH 5 to 7 minutes or until fish flakes easily with fork.'),
('6504', '4', 'Mix all remaining ingredients in small microwavable bowl.  Microwave 2 to 3 minutes or until sauce is smooth, stirring after each minute.'),
('6504', '5', 'Remove toothpicks from fish roll-ups.'),
('6504', '6', 'Serve fish with sauce.'),
('6505', '1', 'Bring 1 inch of water to a boil in a large saucepan. Put asparagus in a steamer basket, place in the pan, cover and steam until tender-crisp, about 4 minutes.'),
('6505', '2', 'Transfer to a large plate, spreading out to cool.'),
('6505', '3', 'Combine chili powder, garlic powder and 1/4 teaspoon salt on a plate. Dredge fillets in the spice mixture to coat.'),
('6505', '4', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('6505', '5', 'Add the fish and cook until just opaque in the center, gently turning halfway, 5 to 7 minutes total. Divide among 4 plates. Immediately add lemon juice, the remaining 1/4 teaspoon salt and asparagus to the pan and cook, stirring constantly, until the asparagus is coated and heated through, about 2 minutes.'),
('6505', '6', 'Serve the asparagus with the fish.'),
('6507', '1', 'Heat grill to medium heat.'),
('6507', '2', 'Arrange 3 lemon slices, slightly overlapping, on half of each of 4 large sheets heavy-duty foil sprayed with cooking spray.'),
('6507', '3', 'Place fish, skinned-sides up, on work surface.'),
('6507', '4', 'Spread each with 1 Tbsp. cream cheese spread; top each with 2 tsp. onions.'),
('6507', '5', 'Roll up, starting at thin end of each fillet.'),
('6507', '6', 'Place 2 roll-ups, seam-sides down, on lemon slices on each foil sheet; top with asparagus and peppers. Fold each foil sheet to make packet.'),
('6507', '7', 'Grill 6 to 8 min. or until fish flakes easily with fork. Carefully open foil packets; top fish with remaining onions and lemon slices.'),
('6508', '1', 'In small bowl, mix flour, chili powder, 1 tablespoon salt and 1 teaspoon pepper. Line up 3 like-sized baking dishes or shallow bowls.'),
('6508', '2', 'Place flour mixture in first dish.'),
('6508', '3', 'Place beaten eggs in second dish. In third dish, place bread crumbs. To bread fish fillets, coat with flour mixture, dip into eggs, then coat with bread crumbs. Set aside on platter or baking tray.In 12-inch nonstick skillet, heat 1/3 cup oil over high heat.'),
('6508', '4', 'Add half of the fillets, cook about 2 minutes or until lightly browned and crisp. Turn fish; cook other side about 1 minute.'),
('6508', '5', 'Remove from skillet to warmed serving platter, cover to keep hot. Cook remaining fillets, adding more oil if neccesary. Move remaining cooked fillets to platter, cover to keep hot.'),
('6508', '6', 'Add garlic an chile to hot oil in skillet. Season with salt and pepper. Cook and stir 2 minutes.'),
('6508', '7', 'Add basil; cook and stir 2 minutes to crisp. Toss in orange peel.Arrange fillets on serving platter or individual plates, top with the basil, garlic and orange mixture.'),
('6509', '1', 'Make Hollandaise: In double boiler top with wire whisk, slightly beat egg yolks. Slowly beat in melted butter. Cook, stirring, over hot water (water in base should not touch upper pan) just until thick.'),
('6509', '2', 'Mixture will curdle if cooked too long.'),
('6509', '3', 'Whisk the heavy cream into sauce. Gradually beat in lemon juice and 1/4 teaspoon salt. Beat until as thick as mayonnaise. Set aside to cool.Preheat oven to 350F.Gently rinse fillets and pat dry with paper towels.'),
('6509', '4', 'Place dark side up on board. Sprinkle fillets with 3/4 teaspoon salt and dash of pepper. Dot with 2 tablespoons butter.Starting at narrow end, roll up fillets. Secure with toothpicks. In buttered shallow baking dish, stand fillets upright on even sides.'),
('6509', '5', 'Pour water and white wine over fish. Top with sliced onion and bay leaf.'),
('6509', '6', 'Bake, uncovered, 15 minutes or until fish flakes when tested with fork.'),
('6509', '7', 'Remove bay leaf and onion.'),
('6509', '8', 'Remove fillets to oven-proof platter and keep warm. (Leave the oven on; youll be broiling these soon.)'),
('6509', '9', 'Remove toothpicks gently; fish is fragile. Strain fish stock, reserving 1 1/4 cups liquid.Melt 3 tablespoons butter in saucepan.'),
('6509', '10', 'Remove from heat. Stir in flour and dash cayenne until smooth. Gradually stir in fish stock and bring to boil, stirring. Reduce heat and simmer 3 minutes. Stir in light cream and mix well.'),
('6509', '11', 'Pour over fish.Increase oven temperature to broil.Melt remaining 2 tablespoons butter and saut mushrooms.'),
('6509', '12', 'Add lemon juice and salt. Cook until tender. Spoon mushrooms around fish.'),
('6509', '13', 'Pour Hollandaise sauce over fillets. Broil 4 inches from heat source until golden brown.'),
('6509', '14', 'Garnish with parsley or watercress.'),
('6511', '1', 'In a large bowl, mix the paprika, 1 tablespoon of the oil and 1/4 teaspoon of salt.'),
('6511', '2', 'Add the chicken and toss. Cover and refrigerate for at least 3 hours or overnight.'),
('6511', '3', 'Arrange the sole in a single layer in a shallow baking dish. In a bowl, combine 1 tablespoon of the oil with 1 pinch of the saffron.'),
('6511', '4', 'Drizzle the oil over the fish and let stand at room temperature for 30 minutes.'),
('6511', '5', 'In a saucepan, combine the vegetable stock with the remaining pinch of saffron and season with salt and pepper. Bring to a simmer, cover and keep warm.'),
('6511', '6', 'In a 14-inch paella pan or cast-iron skillet, heat the remaining 2 tablespoons of oil.'),
('6511', '7', 'Add the chicken and cook over moderately high heat, turning, until browned all over, about 15 minutes; transfer to a platter.'),
('6511', '8', 'Add the chorizo to the pan and cook until lightly browned, about 3 minutes.'),
('6511', '9', 'Transfer the chorizo to the platter with the chicken.'),
('6511', '10', 'Pour off and reserve any excess fat in the pan; leave a thin layer of fat coating the bottom.'),
('6511', '11', 'Add the squid and cook until just white throughout, about 2 minutes.'),
('6511', '12', 'Transfer the squid to the platter with the chicken.'),
('6511', '13', 'Return 2 tablespoons of the reserved fat to the pan.'),
('6511', '14', 'Add the onion and garlic, season with salt and pepper and cook, stirring occasionally, until translucent, about 5 minutes.'),
('6511', '15', 'Transfer the onion mixture to the platter.'),
('6511', '16', 'Return 2 additional tablespoons of the reserved fat to the pan. Stir in the rice and cook over moderately high heat for 2 minutes.'),
('6511', '17', 'Add the chicken, chorizo, squid and onion mixture to the pan along with any accumulated juices. Stir in the peas. Gently pour the warmed stock into the pan. Cover and cook for 10 minutes.'),
('6511', '18', 'Using tongs, nestle the clams and mussels into the rice. Cover and cook for 10 minutes. Arrange the sole fillets and the crabmeat on the rice. Cover and cook for 5 minutes longer, until the sole is cooked through and the rice is tender.'),
('6511', '19', 'Remove the pan from the heat and let the paella stand for 5 minutes. Discard any mussels and clams that have not opened. Sprinkle the paella with the parsley and serve right away.'),
('6512', '1', 'Preheat oven to 375 degrees.Wash and dry fillets and season with salt and pepper.Arrange fillets in a buttered baking dish in a single layer and sprinkle with the green onions, melted butter, wine, parsely, thyme, and bay leaves.Cover with greased paper facing down, then cover dish and bake 20 minutes.Carefully remove fillets from baking dish.Strain pan juices into a small saucepan, add 1 tablespoon butter,and let melt.Blend in the flour, add the cream, and cook 4 minutes.'),
('6512', '2', 'Pour over fish and serve.'),
('6513', '1', 'Place the fish fillets in a casserole dish. Put some salt and lemon-pepper to taste.'),
('6513', '2', 'Add the garlic, the onion sliced, the peppers sliced and then put the lemon juice and the olive oil.'),
('6513', '3', 'Cut tomato to slices and place on top to cover the fish in order not to get burn and remain juicy!'),
('6513', '4', 'Bake at 350F for 30 minutes approx!'),
('6514', '1', 'Coat a baking sheet with nonstick cooking spray.Arrange fillets so they don''t overlap.In a small bowl, combine the mayonnaise, mustard, parsley, and pepper and mix thoroughly.'),
('6514', '2', 'Spread the mixture evenly over the fillets.Broil 3 to 4 inches from the heat for 4 minutes until fish flakes easily with a fork.Arrange fillets on a serving platter, garnish with lemon wedges, and serve.'),
('6515', '1', 'In a shallow dish, whisk together the egg, mustard, and salt; set aside.'),
('6515', '2', 'Place the potato flakes in another shallow dish.'),
('6515', '3', 'Heat oil in a large heavy skillet over medium-high heat.'),
('6515', '4', 'Dip fish fillets in the egg mixture. Dredge the fillets in the potato flakes, making sure to completely coat the fish. For extra crispy, dip into egg and potato flakes again.'),
('6515', '5', 'Fry fish fillets in oil for 3 to 4 minutes on each side, or until golden brown.'),
('6516', '1', 'Salt the fillets and place them in a greased ovenproof dish.'),
('6516', '2', 'Add the wine, 3 tbsp of butter and the chopped mushrooms.Cover and bake 20 minutes in a 350 oven.Make the sauce: melt the butter in a sauce pan, add the flour and stir.'),
('6516', '3', 'Pour the juices from the baked fish into the butter/flour mixture.Stir and simmer a couple of minutes.'),
('6516', '4', 'Pour the sauce over the fish and serve.'),
('6519', '1', 'Combine 3 tablespoons soy sauce, wine, onion powder, sugar and ginger in shallow pan; add fillets, turning to coat both sides well.'),
('6519', '2', 'Let stand 10 minutes; turn over once.Meanwhile, toss carrot and zucchini with remaining soy sauce; pour off excess sauce. Turn vegetables out onto 8-inch round heatproof plate.'),
('6519', '3', 'Remove fillets from marinade; spread out flat and sprinkle with 2 tablespoons green onions. Starting at thinner end, roll up fillet, jellyroll fashion; arrange, seam side down, on vegetables.'),
('6519', '4', 'Place plate on large steamer rack set in large pot or wok of boiling water. (Do not allow water level to reach plate.) Steam, covered, 12 minutes, or until fish flakes easily with fork.Sprinkle remaining 1 tablespoons green onions evenly over fish.'),
('6520', '1', 'Place the fresh washed spinach in a pot with a lid with the water still clinging to it (you do not need additional water).Steam until just wilted, approx 4 minutes,drain well, cool enough to handle.'),
('6520', '2', 'Heat oven to 400F degrees.Tear off 4 pieces of parchment paper or tin foil about 12"x 18".'),
('6520', '3', 'Place the paper on your counter and put 1/4 of the spinach on each, in the center. Cover with onion, jalapeno and the garlic.'),
('6520', '4', 'Place a filet on each and cover with a sliced tomatoe.Season with salt & pepper.Seal the packages and place on a baking sheet or a baking stone.'),
('6520', '5', 'Bake for apprx 12- 15 minutes.Test one pkg to see that the fish is done. The package will be puffed out a bit when done.'),
('6520', '6', 'Transfer to individual plates and let each person open their own surprise package.'),
('6521', '1', 'Arrange fish on foil lined greased rimmed baking sheet.Stir together coriander black bean and garlic sauce and garlic.Spoon over fish.Roast in 450f degree oven until fish flakes easily when tested, 12 to 15 minutes.'),
('6521', '2', 'Serve sprinkled with green onions.'),
('6522', '1', 'Combine the scallops and the egg in a food processor; sprinkle the salt and white pepper over them. Turn on the processor and add the cream through the feed tube. Process until the mixture is smooth; about 10 seconds total. Dont overprocess or the mousse will turn out rubbery. With a stiff rubber spatula or scraper, force the mixture through a medium-fine mesh sieve into a bowl. Check the seasoning by steaming a dab of mousseline for 1 to 2 minutes or until cooked through. Taste and adjust seasonings if needed. Cover and chill the mousse until its time to assemble the timbales.'),
('6522', '2', 'Assemble the timbales:    Butter the bottom and sides of eight 4-oz. molds. If the sole fillets are more than 1/2 inch thick, split each one lengthwise to make 1/4-inch-thick fillets.'),
('6522', '3', 'Wrap a ramekin tightly in plastic. Using the bottom, gently press each fillet to a uniform thickness of 1/8 inch. Start near the center and gently push outward toward the edges, taking care not to tear the fish. Using a sharp 2-inch cookie cutter (or one thats equal in diameter to the inside of the mold youre using), mark circles in the fish.'),
('6522', '4', 'With kitchen shears, cut out the circles. Make as many circles as you can and save all the scraps.'),
('6522', '5', 'Take the eight neatest circles and place one in each buttered timbale mold, with the side the skin was on facing up (the bottom of the ramekin becomes the top of the finished, unmolded timbale). Lightly season each with salt and pepper. Using a pastry bag with a plain tip (or no tip), pipe or spoon a 3/8-inch-thick layer of scallop mousseline into each mold.'),
('6523', '1', 'Set oven to 375 degrees.Butter (do not use cooking spray) a 13 x 9-inch baking dish.Rinse fish fillets with cold water and pat dry with a paper towel.Arrange fillets in a single layer in dish.Sprinkle with shredded mozza cheese.Top with tomato slices.Sprinkle seasonings over top.'),
('6523', '2', 'Bake for 15 minutes, or until fish is "flakey" and cooked (do not over bake fis).'),
('6523', '3', 'Serve immediately.'),
('6524', '1', 'Grease baking dish.Dust fillets with flour.Arrange fillets and sprinkle with lemon juice, sherry, onion, mushrooms and salt'),
('6524', '2', 'Add cream.Cover and bake at 350 degrees for 20 minutes.'),
('6525', '1', 'Heat broiler.In medium bowl, stir together all ingredients except fish and lemon juice.'),
('6525', '2', 'Place sole fillets on broiler pan; sprinkle with lemon juice.Broil 3-4 inches from heat until fish flakes with a fork (about 3-5 minutes).'),
('6525', '3', 'Spread Parmesan mixture over fillets and broil until bubbly and golden brown (3-5 minutes).'),
('6526', '1', 'Preheat oven to 375F degrees.Butter a shallow baking dish and arrange fish pieces in it; cover fish with onion slices.In a small bowl, whisk together sour cream, wine, flour, lemon juice and the seasonings; pour over the fish and onions.'),
('6526', '2', 'Bake, uncovered, for 25 minutes or until fish is tender; do not overcook or fish will dry out.'),
('6527', '1', 'Put oven rack in middle position and preheat oven to 325°F. Oil terrine mold and line bottom with a sheet of wax paper (cut to fit), then oil paper.'),
('6527', '2', 'Remove any visible silver skin or sinew from fish and cut on either side of pin bones until all pin bones have been removed, then cut fish into 1-inch pieces. Purée fish with salt, white pepper, and nutmeg in a food processor until very smooth.'),
('6527', '3', 'Add egg white and purée until incorporated, then transfer mixture to a bowl set in a larger bowl of ice.'),
('6527', '4', 'Set tamis, screen side up, over a plate and work fish mixture through sieve about 2 tablespoons at a time with scraper until all that remains is sinews. Continue to work fish through sieve, scraping strained fish from underside of tamis from time to time and transferring to a large bowl set in another bowl of ice.'),
('6527', '5', 'Weigh strained fish to determine equal amount of cream (1 cup cream weighs 8 ounces). Then, keeping fish mixture over ice, stir cream into fish mixture, about 1/4 cup at a time, with a large rubber spatula until all cream is incorporated.'),
('6527', '6', 'Transfer one fourth of mixture to a small bowl and stir in dill. Gently fold salmon roe into remaining fish mixture.'),
('6527', '7', 'Spread about two thirds of roe mixture in terrine and create a wide trough lengthwise along the middle with back of a spoon. Fill trough with dill mixture, mounding it slightly and smoothing surface. Cover with remaining roe mixture and rap mold firmly on counter to compact terrine. Smooth top with offset spatula and cover surface with an oiled sheet of wax paper (oiled side down).'),
('6527', '8', 'Bake in awater bathuntil terrine is firm to the touch and separates easily from sides of mold and thermometer inserted diagonally through paper into center of terrine registers 110 to 120°F (a metal skewer or thin knife plunged to bottom of terrine for 5 seconds and removed will feel hot), 40 to 45 minutes.'),
('6527', '9', 'Transfer terrine in mold to a rack and let cool 10 to 15 minutes before unmolding.'),
('6527', '10', 'To unmold, remove wax paper and run a thin knife around inside edge of mold. Invert a cutting board or serving dish over terrine, then reinvert and remove mold and wax paper, blotting any excess liquid.'),
('6527', '11', 'Cut terrine into slices with a sharp knife, supporting each slice as cut with a flat metal spatula and transferring as cut to small plates.'),
('6527', '12', '*Available at bridgekitchenware.com.'),
('6528', '1', 'oven preheated 350F degrees.combine honey, mustard, curry,& butter in small bowl; mix well.lightly butter shallow baker; add sole fillets, slightly overlapping is good.Top side up.pour curry sauce on top; bake (uncovered) for 15-20 minutes.serve warm, with cilantro and roasted almond pieces on top.MM!'),
('6529', '1', 'Melt butter in skillet over low heat.'),
('6529', '2', 'Add mushrooms and saute over medium heat until tender.Rub oil over shallow 4 quart baking dish and sprinkle with grated cheese.'),
('6529', '3', 'Place fish on cheese.Sprinkle fish with salt and pepper.'),
('6529', '4', 'Add green pepper and top with mushrooms.'),
('6529', '5', 'Pour wine over fillets.'),
('6529', '6', 'Bake at 450F for 20 minutes or until fish flakes.Sprinkle with lemon juice and parsley.'),
('6530', '1', 'Mix the flour with seasoned salt and pepper in a shallow dish.Dredge the fish fillets in the flour mixture.'),
('6530', '2', 'Heat a large skillet over high heat.'),
('6530', '3', 'Add in about 3 tablespoons butter to the hot skillet.'),
('6530', '4', 'Saute the fillets in 2 batches, cooking on each side (on high heat about 2 minutes per side) or until just cooked through; transfer the fish to a plate to keep warm.'),
('6530', '5', 'Add in the remaining 4 tablespoons butter and cook until golden in colour; add in lemon juice, bring to a boil and add in the parsley.Season the sauce with salt and pepper.'),
('6530', '6', 'Pour the warm sauce over the fish.'),
('6530', '7', 'Serve immediately.'),
('6531', '1', 'Mix seasoning with the minced fish and the flour.Beat the mixture very well and integrate the butter.'),
('6531', '2', 'Add eggs one at a time.Gradually add the liquid.If the mixture curdles stand the bowl in hot water and whisk until it is smooth again.Check your seasoning.Shape the farce into round balls using 2 spoons dipped in hot water.Bring about 2 pints of salted water to a boil.Cook one ball to check the consistency.'),
('6531', '3', 'Add more egg if the ball is too soft, or cream if it is too stiff.If the ball is right cook all the balls, they only take a minute to cook and float when done.'),
('6531', '4', 'Serve as an appetizer, use in the Danish mock turtle soup or make it in a ring shaped mold and serve it with a sauce as your main course.'),
('6532', '1', 'Preheat the oven to 450F Grease a large baking dish.Arrange the fish in the baking dish in a single layer.Stir together the shallot, parsley, lemon juice, sugar and salt in a small bowl.'),
('6532', '2', 'Whisk in the oil until well blended.'),
('6532', '3', 'Pour over the fish. Top with lemon slices.'),
('6532', '4', 'Bake until the fish is just cooked through, 5 to 8 minutes, allowing about 10 minutes per inch of thickness.'),
('6532', '5', 'Serve hot.'),
('6533', '1', 'For the chutney (prep time includes marinating chutney, you can make the night before), mix all ingredients and allow flavors to mingle for about 3 hours- if you are in a pinch, it''s fine to marinate it for less time.Rinse fillets and pat dry-- make sure they are not slippery at all.Preheat oven to 375F.Put olive oil in the bottom of a baking dish, tilt to coat bottom.'),
('6533', '2', 'Combine ginger garlic paste with tumeric, chili powder, cumin and salt and rub this all over the fillets on both sides.Take each fillet and place about 3 tablespoons of chutney near the wide end and roll it up.'),
('6533', '3', 'Place fillet rolls seam side down in the oiled dish.'),
('6533', '4', 'Bake in preheated oven.Fish are done when they flake with a fork, about 30 minutes (watch closely; if your fillets are a little smaller or they are rolled a little bigger, the cooking time will vary).'),
('6533', '5', 'Serves 4- 8, depending on the size of your fillets- we serve 2 per person.'),
('6534', '1', 'Rinse the rice in a fine strainer.'),
('6534', '2', 'Combine rice and cooking liquid in a large pan, bring to a boil, reduce heat and simmer for about 30-45 minutes. Be careful not to overcook the rice, you want it to be a little chewy because it will soak up the dressing later. After rice is done cooking, use a fine strainer to rinse rice under cold water.'),
