INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('19329', '3', 'Remove from pan, and keep warm.'),
('19329', '4', 'Heat 2 teaspoons oil in pan over medium-high heat.'),
('19329', '5', 'Add shrimp and bell pepper. stir-fry 2 minutes.'),
('19329', '6', 'Combine sake and the remaining ingredients.'),
('19329', '7', 'Add sake mixture to shrimp. Bring to a boil. cook 1 minute.'),
('19329', '8', 'Serve shrimp over spinach.'),
('19334', '1', 'Peel shrimp. devein, if desired.'),
('19334', '2', 'Saut shrimp and garlic in hot oil in a large skillet over medium-high heat 3 to 4 minutes or just until shrimp turn pink.'),
('19334', '3', 'Remove shrimp from skillet. keep warm.'),
('19334', '4', 'Add chicken broth and next 3 ingredients to skillet, stirring to loosen particles from bottom of skillet. Cook 4 to 5 minutes or until liquid is reduced by half.'),
('19334', '5', 'Add spinach, and cook 2 minutes or just until spinach is wilted. Stir in shrimp. Season with salt and pepper to taste.'),
('19334', '6', 'Serve immediately.'),
('19338', '1', 'In a small saucepan, bring 1 quart of water to a boil.'),
('19338', '2', 'Add 1 teaspoon of salt and the eggs and simmer over moderately high heat for 5 minutes. Using a slotted spoon, transfer the eggs to a bowl of cold water and let stand for 3 to 4 minutes. Keep the pan of hot water on the stove over low heat.'),
('19338', '3', 'Meanwhile, put the spinach in a large bowl. In a medium skillet, combine the olive oil, sherry and balsamic vinegars, shallots and thyme, and boil for 1 minute.'),
('19338', '4', 'Crack the eggs all over and gently peel them under warm running water, keeping them whole. Using a slotted spoon, slip the eggs in the hot water for 30 seconds.'),
('19338', '5', 'Pour the warm dressing over the spinach, season with salt and pepper and toss. Mound the salad on plates, top each with an egg and serve.'),
('19340', '1', 'Combine first 6 ingredients, stirring well with a whisk.'),
('19340', '2', 'Combine onion, spinach, and apple in a large bowl.'),
('19340', '3', 'Drizzle with dressing. toss gently to coat. Sprinkle with cheese.'),
('19341', '1', 'Sprinkle salmon with salt and pepper. Melt 1 tablespoon butter in medium skillet over medium-high heat.'),
('19341', '2', 'Add salmon. saute until just opaque in center, about 4 minutes per side.'),
('19341', '3', 'Transfer to plate.'),
('19341', '4', 'Melt 1/2 tablespoon butter in same skillet.'),
('19341', '5', 'Add half of shallots and half of tarragon. saute 30 seconds. Increase heat to high. add half of spinach and toss 30 seconds.'),
('19341', '6', 'Add remaining spinach. toss until wilted. Divide between plates.'),
('19341', '7', 'Melt remaining 1/2 tablespoon butter in same skillet over medium-high heat.'),
('19341', '8', 'Add remaining shallots and tarragon. saute 30 seconds.'),
('19341', '9', 'Add wine and cream and boil until sauce is thick enough to coat spoon, about 3 minutes. Season with salt and pepper. Return salmon to skillet. simmer 1 minute. Arrange salmon with sauce atop spinach.'),
('19348', '1', 'In a medium bowl, whisk the buttermilk with the sour cream, shallot and cider vinegar. Stir in the blue cheese. Season the dressing with salt and pepper.'),
('19348', '2', 'In a large nonstick skillet, cook the bacon over moderate heat until crisp, about 6 minutes. Using a slotted spoon, transfer the bacon to paper towels to drain.'),
('19348', '3', 'In a very large bowl, toss the spinach with the red onion and bacon, then toss with the dressing. Mound the salad on plates, top with the eggs and serve.'),
('19351', '1', 'Cook bacon in a skillet over medium-high heat 6 to 8 minutes or until crisp. remove bacon, and drain on paper towels, reserving 1 Tbsp. drippings in skillet.'),
('19351', '2', 'Saut onion in hot drippings 2 to 3 minutes or until soft.'),
('19351', '3', 'Add vinegar, lime juice, and honey. cook 2 minutes, stirring to loosen particles from bottom of skillet.'),
('19351', '4', 'Place spinach in a serving bowl.'),
('19351', '5', 'Add warm vinaigrette, and toss to coat. Top with mango, queso fresco, and bacon. season with salt and pepper to taste.'),
('19351', '6', 'Serve immediately.'),
('19356', '1', 'Cook bacon in a Dutch oven over medium heat until crisp.'),
('19356', '2', 'Remove bacon from pan, reserving 1 tablespoon drippings in pan. Crumble bacon. set aside.'),
('19356', '3', 'Add garlic to drippings in pan. cook over medium heat 1 minute.'),
('19356', '4', 'Add wine and crushed red pepper.'),
('19356', '5', 'Add mussels to pan. cover and cook 6 minutes or until shells open.'),
('19356', '6', 'Remove from heat. discard any unopened shells.'),
('19356', '7', 'Place mussels in a bowl.'),
('19356', '8', 'Add sliced red onion and spinach to wine mixture in pan. cook 1 minute or until spinach wilts. Divide spinach mixture among 4 plates. sprinkle evenly with bacon. Arrange mussels over the spinach mixture. drizzle evenly with any remaining wine mixture.'),
('19360', '1', 'Combine the water, red lentils, and 1/4 teaspoon salt in a medium saucepan. Bring to a boil. cover, reduce heat to medium-low, and simmer for 20 minutes.'),
('19360', '2', 'Drain and set aside.'),
('19360', '3', 'Combine 1/4 teaspoon salt, mint, and the next 5 ingredients (mint through curry powder).'),
('19360', '4', 'Combine 1/4 cup mint dressing, torn spinach, mushrooms, and bell pepper. toss well to coat.'),
('19360', '5', 'Combine lentils and 1/4 cup mint dressing, and toss well to combine.'),
('19360', '6', 'Arrange 2 cups spinach mixture on each of 4 plates. top each serving with 1/2 cup lentil mixture. Divide shrimp evenly among salads. drizzle with remaining dressing.'),
('19364', '1', 'Whisk together vinegar, a rounded 1/4 teaspoon salt, and 1/8 teaspoon pepper in a small bowl, then add oil in a slow stream, whisking well. Put spinach, strawberries, and pecans in a large bowl and toss with just enough vinaigrette to lightly coat.'),
('19367', '1', 'Combine first 8 ingredients in a large bowl, stirring with a whisk.'),
('19367', '2', 'Add mushrooms and remaining ingredients. toss well to coat.'),
('19373', '1', 'Remove large stems from spinach, and rinse with cold water. drain.'),
('19373', '2', 'Place a large Dutch oven over medium heat, and add spinach. (Spinach will need to be tightly packed into the pan to cook all of it in one batch). Cover and cook 5 minutes or until spinach wilts. stir spinach well after 2 minutes.'),
('19373', '3', 'Place spinach in a colander, and drain well, pressing spinach with the back of a spoon to remove as much moisture as possible.'),
('19373', '4', 'Place pan coated with cooking spray over medium heat until hot.'),
('19373', '5', 'Add shallots. saut 2 minutes.'),
('19373', '6', 'Combine flour, salt, and nutmeg. add to pan, stirring well. Cook 30 seconds.'),
('19373', '7', 'Add milk and cheese, stirring with a whisk. cook 1 minute or until thick.'),
('19373', '8', 'Add spinach. cook 30 seconds or until thoroughly heated.'),
('19374', '1', 'Melt 1 stick of butter in a pot. Sprinkle in flour and whisk together. Cook over medium heat for five minutes or until light golden brown. Throw in onion and garlic and stir together, cooking for another minute.'),
('19374', '2', 'Pour in milk, whisking constantly, and cook for another five minutes while you cook the spinach.To cook spinach, melt 3 tablespoons butter in a separate pot.'),
('19374', '3', 'Add spinach in increments until all incorporated, and cook until wilted but not soggy, about 4 to 5 minutes.Season the cream sauce with salt, pepper, and nutmeg.'),
('19374', '4', 'Add spinach to the cream sauce, stirring gently to combine.'),
('19374', '5', 'Serve immediately.'),
('19377', '1', 'Heat the oil in a large skillet over medium-low heat.'),
('19377', '2', 'Add the garlic and cook for 2 minutes.'),
('19377', '3', 'Add the pine nuts and cook until lightly golden, about 3 minutes. Increase heat to medium and add the spinach, salt, pepper, and 2 tablespoons of water. Cover and cook, tossing occasionally with tongs, until the spinach wilts, about 4 minutes.'),
('19377', '4', 'Remove from heat.'),
('19377', '5', 'Add the basil and toss until it wilts, about 1 minute.'),
('19377', '6', 'Serve immediately.Tips: -'),
('19377', '7', 'Serve this quick side dish with grilled chicken, fish, lamb, pork, or steak. Or toss it with pasta for a last-minute main dish. - If you cant find basil, just omit from the recipe.'),
('19404', '1', 'Watch how to make this recipe.'),
('19404', '2', 'Preheat the oven to 375 degrees F. Butter an 8 by 8-inch baking dish. Melt the butter in a large skillet over medium-high heat.'),
('19404', '3', 'Add the onion and a pinch of salt.'),
('19404', '4', 'Saute for 3 minutes, then add the garlic and red chili flakes and saute for 2 more minutes.'),
('19404', '5', 'Add the heavy cream, Parmesan, and nutmeg.'),
('19404', '6', 'Heat until the cream is just beginning to bubble, stirring often. Turn the burner off and stir in sour cream and spinach. Adjust the seasoning with salt and pepper, to taste.'),
('19404', '7', 'Pour into the prepared baking dish and sprinkle the top evenly with fried onions.'),
('19404', '8', 'Bake until golden and bubbly, 15 to 20 minutes.'),
('19407', '1', 'In a bowl, toss the spinach, onion and Peppered Corn Bread Croutons. In a blender, puree the vinegar, shallot, mustard, lemon zest and juice, honey and cloves. With the machine on, slowly blend in the canola and olive oils.'),
('19407', '2', 'Add the parsley and thyme. pulse until chopped. Season the dressing with salt and pepper and toss with the salad. Season with salt and pepper and serve.'),
('19410', '1', 'Cook spinach in 2 batches in 1 inch of boiling salted water in an 8-quart pot, stirring constantly, until wilted, 1 to 2 minutes.'),
('19410', '2', 'Drain in a colander and rinse under cold running water until cool. Squeeze small handfuls of spinach to remove as much moisture as possible, then coarsely chop.'),
('19410', '3', 'Heat milk and cream in a small saucepan over moderate heat, stirring, until warm. Meanwhile, cook onion in butter in a 3-quart heavy saucepan over moderately low heat, stirring occasionally, until softened, about 4 minutes.'),
('19410', '4', 'Whisk in flour and cook roux, whisking, 3 minutes.'),
('19410', '5', 'Add warm milk mixture in a fast stream, whisking constantly to prevent lumps, and simmer, whisking, until thickened, 3 to 4 minutes. Stir in nutmeg, spinach, and salt and pepper to taste and cook, stirring, until heated through.'),
('19417', '1', 'In a small saucepan over medium heat, warm the milk. In a medium saucepan over medium heat, melt the butter.'),
('19417', '2', 'Whisk the flour into the butter and cook for 2 minutes to make a roux.'),
('19417', '3', 'Whisk in the warm milk a bit at a time to avoid lumps. Cook until the sauce begins to thicken, 2 to 3 minutes.'),
('19417', '4', 'Add the pumpkin pie spice and a pinch of salt and pepper. Turn the heat to low, stir in the cheese, and let melt. Stir in the spinach and cook for another 2 to 3 minutes to heat it through. (Save 1 cup for Round 2 Recipe Spinach and Cheese Souffle).'),
('19418', '1', 'Watch how to make this recipe.'),
('19418', '2', 'Rinse the spinach well in cold water to make sure it''s very clean. Spin it dry in a salad spinner, leaving just a little water clinging to the leaves.'),
('19418', '3', 'In a very large pot or Dutch oven, heat the olive oil and saute the garlic over medium heat for about 1 minute, but not until it''s browned.'),
('19418', '4', 'Add all the spinach, the salt, and pepper to the pot, toss it with the garlic and oil, cover the pot, and cook it for 2 minutes. Uncover the pot, turn the heat on high, and cook the spinach for another minute, stirring with a wooden spoon, until all the spinach is wilted. Using a slotted spoon, lift the spinach to a serving bowl and top with the butter, a squeeze of lemon, and a sprinkling of sea or kosher salt.'),
('19418', '5', 'Serve hot.'),
('19419', '1', 'Place eggs in a large saucepan. Cover with water to 1 inch above eggs, and bring just to a boil.'),
('19419', '2', 'Remove from heat. Cover and let stand 15 minutes.'),
('19419', '3', 'Drain and rinse with cold running water until cool.'),
('19419', '4', 'Remove shells.'),
('19419', '5', 'Cut 2 eggs in half lengthwise, and remove and discard the yolks. Coarsely chop egg whites and remaining egg.'),
('19419', '6', 'Heat 1/2 teaspoon oil in a large Dutch oven over medium-high heat.'),
('19419', '7', 'Add 1/2 cup onion, and saut 5 minutes or until browned.'),
('19419', '8', 'Add 1/2 teaspoon red pepper. saut 30 seconds.'),
('19419', '9', 'Add half of spinach. saut 3 minutes or until wilted.'),
('19419', '10', 'Remove from pan. Repeat procedure with the remaining oil, onion, red pepper, and spinach.'),
('19419', '11', 'Place the spinach mixture in a colander, and drain well. Return spinach mixture to pan. stir in salt and black pepper. Cook over medium-high heat 2 minutes or until thoroughly heated, stirring constantly. Sprinkle with the chopped egg.'),
('19421', '1', 'In a large bowl, combine 3 tablespoons of oil, lemon juice, herbs, salt, pepper, and shrimp. Cover and refrigerate for 20 to 30 minutes.'),
('19421', '2', 'Soak skewers in warm water at least 20 minutes while shrimp is marinating.'),
('19421', '3', 'Heat remaining oil in a large skillet over low heat and wilt spinach with fennel seeds, about 3 to 4 minutes (do in two batches if necessary).'),
('19421', '4', 'Remove skillet from heat and cover to keep warm.'),
('19421', '5', 'Heat broiler or grill.'),
('19421', '6', 'Remove shrimp from marinade and thread onto skewers. Broil or grill the shrimp until just done, about 5 to 6 minutes.'),
('19421', '7', 'Serve shrimp and spinach with the beans.'),
('19425', '1', 'Discard seasoning packet in package of noodles. Crumble noodles.'),
('19425', '2', 'Place 2 cups spinach on each of 4 plates. Top evenly with of noodles, chicken, and next 3 ingredients.'),
('19425', '3', 'Combine honey and remaining 3 ingredients, stirring with a whisk. Spoon about 2 1/2 tablespoons honey mixture over each salad.'),
('19426', '1', 'Cut bacon into 3/4-inch-thick matchsticks and cook in a heavy skillet over moderately low heat, stirring, until crisp but still chewy, 6 to 8 minutes.'),
('19426', '2', 'Transfer with a slotted spoon to paper towels to  drain.'),
('19426', '3', 'Pour off fat from skillet and add 1 1/2 tablespoons oil, mushrooms, and 1/2 teaspoon salt. Cook over moderate heat, stirring occasionally, until mushrooms are golden, about 8 minutes, then cool.'),
('19426', '4', 'Whisk together lemon juice, vinegar, mustard, remaining 1/2 teaspoon salt, pepper, and remaining 2 tablespoons oil in a large salad bowl until blended.'),
('19426', '5', 'Add pea shoots and spinach to dressing and toss to coat.'),
('19426', '6', 'Add bacon, mushrooms, chives, and radishes and toss again.'),
('19428', '1', 'Heat olive oil in a large Dutch oven over medium heat.'),
('19428', '2', 'Add onion and garlic to pan. cover and cook for 8 minutes or until tender, stirring occasionally. Stir in smoked paprika, and cook for 1 minute.'),
('19428', '3', 'Add white wine, vegetable broth, and tomatoes. bring to a boil.'),
('19428', '4', 'Add chickpeas. reduce heat, and simmer until sauce thickens slightly (about 15 minutes), stirring occasionally.'),
('19428', '5', 'Add spinach. cover and cook for 2 minutes or until spinach wilts. Stir in parsley and vinegar.'),
('19431', '1', 'Heat 3 tablespoons oil in heavy large skillet over medium heat.'),
('19431', '2', 'Add onion and saute until translucent, about 5 minutes.'),
('19431', '3', 'Add tomato paste. stir 1 minute.'),
('19431', '4', 'Add chiles and 1/3 of spinach. Cook until spinach wilts, adding remaining spinach in 2 additions and tossing often, about 4 minutes.'),
('19431', '5', 'Mix in rice. Cover and simmer until rice is tender and moisture from spinach is absorbed, adding water by tablespoonfuls if needed for rice, about 10 minutes. Uncover and continue to cook until mixture is dry, about 2 minutes. discard chiles.'),
('19431', '6', 'Meanwhile, press garlic cloves into small bowl, stir in yogurt, and season with salt and pepper. Melt butter with 1 tablespoon oil in small skillet.'),
('19431', '7', 'Mix in cayenne and remove from heat.'),
('19431', '8', 'Spread spinach mixture on platter. make indentations with back of spoon. Spoon yogurt into indentations and drizzle with cayenne butter.'),
('19432', '1', 'In a medium saucepan, combine the barley, stock, thyme and half of the garlic.'),
('19432', '2', 'Add a generous pinch of salt and bring to a boil. Cover and cook over moderately low heat until the barley is tender, 25 minutes. Discard the thyme.'),
('19432', '3', 'Drain the barley and transfer to a large bowl. cover and keep warm.'),
('19432', '4', 'Meanwhile, in a large skillet, heat 1 tablespoon of the oil.'),
('19432', '5', 'Add the mushrooms, season with salt and pepper and cook over high heat, stirring, until lightly browned, 5 minutes.'),
('19432', '6', 'Add the shallots and cook, stirring, until softened, 3 minutes longer. Scrape the mushrooms into the barley and toss.'),
('19432', '7', 'Add the spinach, basil and mint, but do not stir.'),
('19432', '8', 'Heat the remaining 1 tablespoon of oil in the skillet.'),
('19432', '9', 'Add the remaining garlic and cook over moderate heat until softened.'),
('19432', '10', 'Add the vinegar, lemon juice and brown sugar and bring to a boil. Cook until slightly thickened, 1 minute.'),
('19432', '11', 'Add the tomatoes and cook until heated through. Stir in the tofu and season with salt and pepper. Scrape the dressing over the salad and toss.'),
('19432', '12', 'Serve warm.'),
('19436', '1', 'In a bowl, whisk the lemon juice, soy sauce, mustard and sesame oil. Slowly whisk in 1/2 cup of the vegetable oil and season with salt and pepper.'),
('19436', '2', 'In a skillet, toast the sesame seeds over high heat, shaking the pan until the seeds are fragrant, 2 minutes.'),
('19436', '3', 'Transfer to a plate.'),
('19436', '4', 'Heat the remaining vegetable oil in the skillet until shimmering.'),
('19436', '5', 'Add the sausages and cook over high heat until lightly browned, 5 minutes.'),
('19436', '6', 'Transfer to a plate to cool.'),
('19436', '7', 'In a large bowl, toss the spinach, pears and sesame seeds with half of the dressing. season with salt and pepper.'),
('19436', '8', 'Transfer to plates.'),
('19436', '9', 'Add the sausages to the bowl and toss with the remaining dressing. Using a slotted spoon, transfer the sausages to the plates and serve.'),
('19437', '1', 'Heat 1/2 tablespoon olive oil in large nonstick skillet over medium-high heat.'),
('19437', '2', 'Add shallot. stir 30 seconds.'),
('19437', '3', 'Add Calvados (brandy may ignite). boil 30 seconds.'),
('19437', '4', 'Add cream. boil 2 minutes.'),
('19437', '5', 'Transfer sauce base to bowl. (Sauce base can be made 2 hours ahead.'),
('19437', '6', 'Let stand at room temperature.)'),
('19437', '7', 'Preheat oven to 300F. Sprinkle scallops with salt and pepper.'),
('19437', '8', 'Heat vegetable oil in another large nonstick skillet over high heat.'),
('19437', '9', 'Add 8 scallops.'),
('19437', '10', 'Cook until brown, about 2 minutes per side.'),
('19437', '11', 'Transfer to rimmed baking sheet. place in oven to keep warm. Repeat with remaining scallops.'),
('19437', '12', 'Add apple juice and thyme to hot skillet. Boil 1 minute, scraping up brown bits.'),
('19437', '13', 'Add sauce base. bring to boil.'),
('19437', '14', 'Remove from heat.'),
('19437', '15', 'Heat remaining 1 tablespoon olive oil in large saucepan over medium-high heat.'),
('19437', '16', 'Add garlic and stir 30 seconds.'),
('19437', '17', 'Add spinach. toss until barely wilted and still bright green, about 2 minutes. Sprinkle with salt and pepper. Using tongs, mound spinach in center of 8 plates, dividing equally.'),
('19437', '18', 'Arrange 2 scallops on spinach on each plate.'),
('19437', '19', 'Pour any collected juices from baking sheet into sauce in skillet. Boil until thickened, about 2 minutes. Season with salt and pepper. spoon over scallops.'),
('19445', '1', 'Whisk first 5 ingredients in large bowl. Season to taste with salt and pepper. Set dressing aside.'),
('19445', '2', 'Cut off peel and white pith from orange.'),
('19445', '3', 'Cut orange into 1/3-inch rounds. cut rounds crosswise in half.'),
('19445', '4', 'Add spinach to dressing. toss to coat.'),
('19445', '5', 'Add avocado and orange. toss gently.'),
('19445', '6', 'One serving contains the following: Calories (kcal) 152.90. % Calories from Fat 65.6. Fat (g) 11.22. Saturated Fat (g) 1.37. Cholesterol (mg) 0. Carbohydrates (g) 14.20. Dietary Fiber (g) 6.19. Total Sugars (g) 3.48. Net Carbs (g) 8.00. Protein (g) 2.47'),
('19445', '7', 'Bon Appetit'),
('19447', '1', 'Preheat oven to 450F.'),
('19447', '2', 'Toss squash with 1 1/2 tablespoons oil in a shallow baking pan and spread cubes in 1 layer. Season with salt and pepper and roast in middle of oven, stirring once halfway through roasting, until squash is just tender and pale golden, about 30 minutes total. Cool in pan on a rack until warm, about 15 minutes.'),
('19447', '3', 'While squash is roasting, cook almonds in remaining 4 tablespoons oil in a 10-inch skillet over moderately low heat, stirring constantly, until golden, about 3 minutes, then season with salt and pepper.'),
('19447', '4', 'Pour almonds and oil into a fine-mesh sieve set over a large bowl and cool until warm, about 10 minutes.'),
('19447', '5', 'When almonds and oil have cooled, whisk lemon juice into oil in bowl until combined well, then season with salt and pepper.'),
('19447', '6', 'Add squash, spinach, and half of almonds to dressing and toss gently to coat.'),
('19447', '7', 'Divide salad among 6 salad plates and sprinkle with remaining almonds.'),
('19448', '1', 'Assemble salad, toss in dressing and enjoy!'),
('19465', '1', 'Spread the spinach on a large platter. In a large skillet, cook the bacon over moderate heat until crisp, about 4 minutes.'),
('19465', '2', 'Drain off all but 2 tablespoons of the bacon fat. Season the shrimp with salt and pepper and cook it with the bacon over moderately high heat until just white throughout, about 4 minutes.'),
('19465', '3', 'Add the beans, season with salt and pepper and toss until heated through, about 1 minute. Scrape the shrimp and beans onto the bed of spinach.'),
('19465', '4', 'In the same skillet, heat 1 tablespoon of the olive oil.'),
('19465', '5', 'Add the shallot and cook over moderately low heat until softened, about 1 minute.'),
('19465', '6', 'Add the mustard to the skillet and whisk in the red wine vinegar, then whisk in the remaining 1/4 cup of olive oil. Season the dressing with salt and pepper, pour it over the salad and serve.'),
('19476', '1', 'In a large bowl, toss together the spinach, nectarines, and strawberries.'),
('19476', '2', 'In a small bowl, stir together the oil, lemon juice, vinegar, sugar, and dry mustard.'),
('19476', '3', 'Pour the dressing over the salad and toss to combine.  Sprinkle with sunflower seeds and serve.'),
('19476', '4', 'Variation: Substitute peaches for the nectarines and raspberries for the strawberries.'),
('19479', '1', 'Cook bacon in a large skillet until crisp. remove and drain on paper towels, reserving drippings in skillet. Saut shallot and garlic in hot drippings until tender.'),
('19479', '2', 'Remove shallot and garlic.'),
('19479', '3', 'Drain oil from skillet, reserving 1 teaspoon.'),
('19479', '4', 'Heat 1 teaspoon reserved oil over medium-high heat. Cook scallops in batches 3 to 4 minutes.'),
('19479', '5', 'Remove scallops from skillet. set aside.'),
('19479', '6', 'Add red bell pepper and next 7 ingredients. Stir, loosening brown bits from bottom of skillet. Cook about 5 minutes or until vegetables are tender.'),
('19479', '7', 'Add bacon and scallops. cook until heated through.'),
('19479', '8', 'Place spinach in a large salad bowl, and toss with scallops and warm dressing.'),
('19479', '9', 'Serve immediately.'),
('19479', '10', 'Wine note: "Domdechant Werner Riesling ($2'),
('19479', '11', 'from Germany or Chateau d''Orschwihr Riesling Rangen ($3'),
('19479', '12', 'from (Alsace) France are picks. These wines do wonderfully with bacon and seafood--more often prepared together than one might think. The wine will bring a balance of body to the dish."--Franklin Ferguson, wine director and bar manager, Citrine restaurant, Los Angeles, CA.'),
('19481', '1', 'In a medium saucepan, combine the barley, stock, thyme and half of the garlic.'),
('19481', '2', 'Add a generous pinch of salt and bring to a boil. Cover and cook over moderately low heat until the barley is tender, 25 minutes. Discard the thyme.'),
('19481', '3', 'Drain the barley and transfer to a large bowl. cover and keep warm.'),
('19481', '4', 'Meanwhile, in a large skillet, heat 1 tablespoon of the oil.'),
('19481', '5', 'Add the mushrooms, season with salt and pepper and cook over high heat, stirring, until lightly browned, 5 minutes.'),
('19481', '6', 'Add the shallots and cook, stirring, until softened, 3 minutes longer. Scrape the mushrooms into the barley and toss.'),
('19481', '7', 'Add the spinach, basil and mint, but do not stir.'),
('19481', '8', 'Heat the remaining 1 tablespoon of oil in the skillet.'),
('19481', '9', 'Add the remaining garlic and cook over moderate heat until softened.'),
('19481', '10', 'Add the vinegar, lemon juice and brown sugar and bring to a boil. Cook until slightly thickened, 1 minute.'),
('19481', '11', 'Add the tomatoes and cook until heated through. Stir in the tofu and season with salt and pepper. Scrape the dressing over the salad and toss.'),
('19481', '12', 'Serve warm.'),
('19485', '1', 'Heat the oil in a heavy pot over medium heat and add the mustard seeds.  Fry until they begin to pop, then add the onion and ginger and fresh chili, if using.'),
('19485', '2', 'Saute, stirring occasionally,  until beginning to brown.'),
('19485', '3', 'In the meantime, bring a pot of water to boil for the spinach.  Peel the potatoes if desired and chop into chunks.'),
('19485', '4', 'Add the potatoes, chili powder (if using), salt, and water to the pot.  Bring the heat to low and cover, cooking until the potatoes are close to soft.  Stir occassionally.'),
('19485', '5', 'In the meantime, blanch the spinach for 3-4 minutes, then drain and press out as much water as possible.'),
('19485', '6', 'When the potatoes are close to soft, uncover and add the spinach.'),
('19485', '7', 'Add more water if necessary to avoid burning.  Continue cooking until the potatoes are tender, increasing the heat if desired to brown the potatoes. Season to taste with salt and serve.'),
('19488', '1', 'In a medium skillet, heat 1 tablespoon of the olive oil.'),
('19488', '2', 'Add 1 cup of the onions and cook over moderately high heat, stirring frequently, until golden.'),
('19488', '3', 'Add the oregano and sugar and season with salt and black pepper. Cook, stirring, for 1 minute.'),
('19488', '4', 'Add the wine and simmer, stirring, for 1 minute.'),
('19488', '5', 'Add the tomato sauce and water and simmer over moderate heat until slightly thickened, 10 minutes.'),
('19488', '6', 'Remove from the heat.'),
('19488', '7', 'Melt the butter in a medium sauce-pan.'),
('19488', '8', 'Add 1/4 cup of the onions and cook over moderate heat, stirring, until softened, about 4 minutes.'),
('19488', '9', 'Whisk in the flour until combined.'),
('19488', '10', 'Add the milk in 2 batches, whisking constantly until smooth before adding more. Bring to a boil over moderately high heat, then simmer over moderate heat until thickened, about 2 minutes.'),
('19488', '11', 'Whisk in 1/4 cup of the Parmesan cheese, the nutmeg, white pepper and 3/4 teaspoon of salt.'),
('19488', '12', 'Remove from the heat and press a piece of plastic wrap directly on the surface of the white sauce.'),
('19488', '13', 'In a large skillet over high heat, add the spinach by handfuls and toss until wilted. Wipe out the skillet. Squeeze the spinach dry, then finely chop.'),
('19488', '14', 'In the same skillet, heat the remaining 1 tablespoon of olive oil.'),
('19488', '15', 'Add the bacon and cook over moderately high heat until golden, about 3 minutes.'),
('19488', '16', 'Add the garlic and cook, stirring, until fragrant, about 30 seconds.'),
('19488', '17', 'Add the remaining 1/4 cup of chopped onion and cook until translucent, about 3 minutes.'),
('19488', '18', 'Add the spinach and cook, stirring, for 2 minutes.'),
('19488', '19', 'Add 1 cup of the white sauce and 1 teaspoon each of salt and black pepper.'),
('19488', '20', 'Remove from the heat and stir in 1/2 cup of the remaining Parmesan cheese and the chopped walnuts.'),
('19488', '21', 'Preheat the oven to 40'),
('19488', '22', 'Lay 16 crpes on a work surface and spread 3 tablespoons of the spinach filling in a strip down the center of each one. Tightly roll the crpe around the filling, tucking in the edges as you roll to form a neat cylinder. Repeat with the remaining filling and crpes.'),
('19488', '23', 'Spread 1/4 cup of tomato sauce on the bottom of a 9-by-13-inch glass or ceramic baking dish. Arrange the cannelloni over the tomato sauce.'),
('19488', '24', 'Spread the remaining white sauce over the cannelloni.'),
('19488', '25', 'Drizzle the remaining tomato sauce on top and sprinkle with the remaining 1/4 cup of Parmesan.'),
('19488', '26', 'Bake for 25 minutes, or until the cheese is golden and the cannelloni are heated through.'),
('19488', '27', 'Let stand for 10 minutes before serving.'),
('19494', '1', 'Whisk first 5 ingredients in small bowl.'),
('19494', '2', 'Whisk in oil. Season with salt and pepper.'),
('19494', '3', 'Toss spinach with vinaigrette in large bowl. And cheese and toss.'),
('19496', '1', 'Melt butter in a large nonstick skillet with sloped sides over medium-high heat.'),
('19496', '2', 'Add onion and garlic, and saut until tender.'),
('19496', '3', 'Combine egg substitute and next 4 ingredients. add onion mixture, stirring well.'),
('19496', '4', 'Pour egg mixture into pan. Cover. cook over medium-low heat 10 minutes or until mixture is set.'),
('19496', '5', 'Remove from heat. sprinkle with cheese. Cover. let stand 5 minutes or until cheese melts.'),
('19496', '6', 'Cut into 8 wedges, and serve with warm marinara sauce.'),
('19496', '7', 'carbo rating: 3'),
('19507', '1', 'Line a colander with 2 layers of cheesecloth and set in the sink. Bring milk to boil in a large pot over medium-high heat, stirring occasionally to prevent scorching.'),
('19507', '2', 'Let it boil 30 seconds (remove from heat if it starts to boil over) and stir in 1/4 cup lemon juice. Milk will curdle, separating into cheese curds and a clear yellow whey.'),
('19507', '3', 'Pour into cheesecloth-lined colander.'),
('19507', '4', 'Rinse curds with cold water. Pull up edges of the cheesecloth, gently squeeze out as much water as possible, and form curds into a 6-in. disk. Put cheesecloth-wrapped disk on a large plate, top with a large cutting board, and weigh down with a heavy pot. Put in the refrigerator and let press at least 3 hours and up to overnight.'),
('19507', '5', 'Meanwhile, bring a large pot of water to boil. Fill a large bowl with ice water and set aside. To boiling water, add 3 tsp. salt and the spinach. Cook 1 minute, then drain and transfer spinach to ice water. Swirl around to cool spinach and drain again. Use your hands to squeeze water from spinach. Set aside.'),
('19507', '6', 'In a blender, whirl garlic, onions, chiles, ginger, and 1/4 cup of water to make a paste. Set aside.'),
('19507', '7', 'In a medium pot over medium-high heat, add oil, cardamom, cloves, bay leaves, and cinnamon. Cook until spices darken, about 2 minutes.'),
('19507', '8', 'Add reserved onion paste. Cook, stirring occasionally, until mixture thickens and darkens, about 15 minutes. If the mixture starts to stick, add 1 tbsp. of water at a time, stirring, to help loosen it.'),
('19507', '9', 'Stir in coriander, cumin, and turmeric. Cook until fragrant, about 2 minutes.'),
('19507', '10', 'Add tomato and yogurt. Cook until thickened slightly, about 3 minutes. Stir in spinach and remaining salt. Turn heat to low and cover. Cook, stirring occasionally, until flavors are blended, about 30 minutes.'),
('19507', '11', 'Cut paneer into 1/2-in. cubes and gently stir into spinach mixture. Cook until paneer is heated through, about 2 minutes.'),
('19507', '12', 'Add garam masala and remaining lemon juice. Adjust salt and lemon juice to taste.'),
('19507', '13', 'Serve hot, with flatbread or rice.'),
('19509', '1', 'Watch how to make this recipe.'),
('19509', '2', 'Heat a large pot over medium heat.'),
('19509', '3', 'Drizzle with a 2-count of oil, add the butter, and stir it around so it melts.'),
('19509', '4', 'Saute the onion and garlic until soft, about 5 minutes.'),
('19509', '5', 'Add the spinach in batches, pushing it down with a wooden spoon to help it wilt. Keep adding more spinach when there is room in the pot. Cook the spinach until it is dry, then lower the heat and add the cream and nutmeg. Stir and cook for 10 minutes. Season with salt and pepper and serve hot.'),
('19510', '1', 'Watch how to make this recipe.'),
('19510', '2', 'Squeeze all of the water from the spinach. In a large pan, heat the oil over a medium heat.'),
('19510', '3', 'Add the shallots and cook, stirring, until softened, about 2 minutes.'),
('19510', '4', 'Add the flour and cook, stirring, for 30 seconds.'),
('19510', '5', 'Add the milk and broth and cook, scraping up any bits from the bottom of the pan. Bring to a simmer and cook for 2 minutes.'),
('19510', '6', 'Add the spinach and simmer until tender, about 5 minutes. Stir in the evaporated milk and nutmeg and season to taste with salt and pepper.'),
('19510', '7', 'Excellent source of: Protein, Vitamin A, Riboflavin, Folate, Calcium, Magnesium, Manganese, Potassium'),
('19510', '8', 'Good source of: Fiber, Thiamin, Vitamin B6, Vitamin C, Vitamin D, Copper, Iodine, Iron, Phosphorus, Selenium'),
('19522', '1', 'Prepare grill.'),
('19522', '2', 'Prepare Sherry Vinaigrette. set aside 1/4 cup vinaigrette.'),
('19522', '3', 'Coat peach halves and chicken with cooking spray. brush chicken with remaining 1 1/2 tablespoons vinaigrette.'),
('19522', '4', 'Place peach halves and chicken on a grill rack coated with cooking spray. Grill chicken 3 to 4 minutes on each side. Grill peach halves 1 to 2 minutes on each side. cut each half into 4 wedges.'),
('19522', '5', 'Cut chicken crosswise into thin strips.'),
('19522', '6', 'Place peach wedges, chicken strips, spinach, and pine nuts in a large bowl. drizzle with reserved 1/4 cup vinaigrette, and toss well.'),
('19522', '7', 'Place 2 cups salad mixture on each of 4 plates. sprinkle evenly with cheese.'),
('19524', '1', 'To make the dressing, in a small jar with a tight-fitting lid, combine the olive oil, vinegar, mustard, sugar, salt, and pepper to taste. Cover tightly and shake vigorously to blend. Taste and adjust the seasoning. Set aside.'),
('19524', '2', 'Place the onions in a medium bowl and cover with cold water.'),
('19524', '3', 'Let stand for 30 minutes. This crisps the onion and takes away the raw onion taste.'),
('19524', '4', 'Drain well and pat dry on paper towels.'),
('19524', '5', 'In a small bowl, toss the cranberries with 2 tablespoons of the dressing to soften them. Set aside for at least 20 minutes or until ready to serve the salad.'),
('19524', '6', 'To assemble the salad, place the spinach, onions, and pears in a large bowl. Give the remaining dressing a last-minute shake and pour over the salad. Toss to coat evenly. Arrange the salad in a large serving bowl or divide it evenly among 8 salad plates. Scatter the cranberries and hazelnuts over the top(s).'),
('19524', '7', 'Serve immediately.'),
('19524', '8', 'Cook''s Notes'),
('19524', '9', 'Try to buy shelled hazelnuts (also called filberts) with the brown, papery skins removed as well. To toast, spread the hazelnuts in a single layer on a rimmed baking sheet and place in a preheated 375F oven. Toast for about 12 minutes until lightly browned. If the nuts still have the skins on, transfer them while theyre hot to a clean kitchen towel. (Use a clean towel that is old or you dont mind washing with bleach, because the skins tend to discolor the fabric.) Rub the nuts to remove most of the skins (they never come completely off).'),
('19524', '10', 'You can substitute unsalted cashews for the hazelnuts. Toast cashews, as directed above for hazelnuts, for 8 to 10 minutes until lightly browned.'),
('19524', '11', 'Do Ahead'),
('19524', '12', 'The dressing can be made up to 1 day in advance, covered tightly, and refrigerated.'),
('19524', '13', 'Remove from the refrigerator 2 hours before serving. The nuts can be toasted up to 1 day in advance. store at room temperature in an airtight container. The onions and cranberries can be prepared up to up to 4 hours in advance. Set aside at room temperature.'),
('19524', '14', 'Reprinted with permission from The New Thanksgiving Table by Diane Morgan, (C) October 2009, Chronicle Books'),
('19525', '1', 'Steam spinach until tender and set aside to cool in a colander placed over a bowl to catch any excess moisture. (Steaming preserves vitamins, so since it cooks quickly, be careful to avoid overcooking the spinach, which will negate that advantage.)'),
('19525', '2', 'Cook bacon until crispy in a saute pan and remove to paper toweling to drain and cool.'),
('19525', '3', 'Pour most of the fat out of the pan and add the cream to the same pan over low heat, allowing to reduce by about one-third.'),
('19525', '4', 'While the cream is reducing, finely chop the now cooled spinach, and return it briefly to the colander placed over a bowl.'),
('19525', '5', 'Cut the bacon strips into 1/4-inch pieces.'),
('19525', '6', 'Whisk the Parmesan into the reduced cream, and season with pepper. Since the cheese will add saltiness, add salt only if needed. Fold the well-drained spinach and bacon into the sauce.'),
('19525', '7', 'Transfer to a serving dish.'),
('19529', '1', 'Rinse chicken and pat dry. Slice crosswise into 1/4-inch-thick strips.'),
('19529', '2', 'Put spinach in a large, shallow serving or mixing bowl. In a small bowl, mix vinegar, 3 tablespoons olive oil, capers, and mustard.'),
('19529', '3', 'Set a 10- to 12-inch frying pan over high heat. When pan is hot, add remaining tablespoon olive oil and the chicken. Stir often until chicken is no longer pink in center of thickest part (cut to test), about 4 minutes.'),
('19529', '4', 'Add onion and garlic and stir until onion begins to soften slightly, about 1 minute.'),
('19529', '5', 'Add vinaigrette and stir until hot, about 30 seconds.'),
('19529', '6', 'Pour over spinach.'),
('19529', '7', 'Sprinkle tomatoes on top and mix. add salt and pepper to taste.'),
('19539', '1', 'Cook bacon in a skillet over medium heat until crisp.'),
('19539', '2', 'Remove bacon from pan, reserving drippings, and crumble.'),
('19539', '3', 'Add the shrimp to pan, and cook 2 minutes, turning once.'),
('19539', '4', 'Combine bacon, 2 cups fennel, grape tomatoes, red onion, and baby spinach in a bowl.'),
('19539', '5', 'Combine the remaining ingredients in a small bowl, stirring with a whisk.'),
('19539', '6', 'Add the shrimp and balsamic mixture to spinach mixture. toss well.'),
('19556', '1', 'In a large bowl, whisk together the milk and eggs. Stir in the sour cream, spinach, asparagus, Parmesan, and salt.'),
('19556', '2', 'Add the flour and mix until well combined.'),
('19556', '3', 'In a large skillet, over medium heat, heat 1/3 of the oil. Make 4 pancakes (about 1/4 cup of batter per pancake) and cook until golden brown and slightly puffed, 2 to 3 minutes per side. Working in batches, make a total of 12 pancakes, adding oil as necessary.'),
('19557', '1', 'Cook the gnocchi according to the package directions, reserving 1/4 cup of the cooking liquid. Meanwhile, heat the oil in a large skillet over medium heat.'),
('19557', '2', 'Add the onion and cook until softened, about 5 minutes.'),
('19557', '3', 'Add the sausage and cook, crumbling it with a spoon, until browned, 5 to 7 minutes.'),
('19557', '4', 'Add the garlic, spinach, salt, and pepper and cook, tossing frequently, until the spinach wilts, about 3 minutes.'),
('19557', '5', 'Add the drained gnocchi, the reserved cooking liquid, and the Parmesan and toss. Divide among individual bowls and sprinkle with additional Parmesan.Tip: Gnocchi are small, quick-cooking dumplings, usually made from potatoes. You''ll find them with the fresh or dried pasta in supermarkets, or you can substitute a short pasta, such as rigatoni, penne, or farfalle.'),
('19559', '1', 'Heat oven to 400 F. Coat a shallow 2 1/2- to 3-quart baking dish with oil. set aside.'),
('19559', '2', 'Heat the oil in a large skillet over medium-high heat.'),
('19559', '3', 'Add the shallots, 1/2 teaspoon salt, and 1/4 teaspoon pepper. Cook, stirring occasionally, until soft, 6 to 8 minutes.'),
('19559', '4', 'Add the wine and simmer until evaporated, 4 to 6 minutes. Meanwhile, in a large bowl, whisk together the eggs, cream, milk, nutmeg, 1/2 teaspoon salt, and 14 teaspoon pepper. Squeeze the spinach to remove excess liquid. Stir the spinach, shallots, Gruyre, and Parmesan into the egg mixture.'),
('19559', '5', 'Transfer to the prepared baking dish.'),
('19559', '6', 'Bake until bubbling and the top is golden brown, 45 to 55 minutes. To Bring It: If the casserole is warm, transport it in an insulated bag or a cardboard box lined with towels. Or you can make it a day in advance and, upon arrival, reheat it, covered, at 350 to 400 F for 45 to 50 minutes.'),
('19564', '1', 'Preheat broiler.'),
('19564', '2', 'To prepare dressing, combine first 8 ingredients in a small bowl, and stir well with a whisk.'),
('19564', '3', 'To prepare salad, heat 1 teaspoon oil in a large nonstick skillet over medium-high heat.'),
('19564', '4', 'Add mushrooms and 1 cup onions. saut 8 minutes. Stir in corn. remove from heat.'),
('19564', '5', 'Place the fish on a foil-lined baking sheet. brush evenly with 1 teaspoon oil. Broil 8 minutes or until fish flakes easily when tested with a fork.'),
('19564', '6', 'Place 2 cups spinach on each of 4 plates. top each serving with 1/4 cup bean sprouts, 1/4 cup red bell pepper, 1/2 cup mushroom mixture, and 1 fillet.'),
('19564', '7', 'Drizzle about 2 tablespoons dressing over each salad.'),
('19565', '1', 'Whisk vinegar, mustard, salt, pepper, and 2 tsp. harissa in a bowl. Gradually whisk in olive oil. Taste. add more harissa if you''d like a hotter dressing. Set aside.'),
('19565', '2', 'Make salad: Put peppers on a baking sheet and broil, turning periodically, until charred on all sides, about 20 minutes.'),
('19565', '3', 'Place peppers in a paper bag about 15 minutes to allow trapped steam to loosen their skins.'),
('19565', '4', 'Remove charred skins, stems, and seeds. cut peppers into 1/2-in. pieces.'),
('19565', '5', 'Meanwhile, heat olive oil in a large nonstick frying pan over medium heat.'),
('19565', '6', 'Add eggplant and cook, stirring often, until softened and beginning to color, about 12 minutes.'),
('19565', '7', 'Add chickpeas, 2 tbsp. water, and 3/4 tsp. each salt and pepper. cook, stirring, to blend flavors, about 3 minutes. Stir in chopped peppers.'),
('19565', '8', 'Remove from heat and let stand until vegetables are warm but not hot.'),
('19565', '9', 'In a large bowl, toss spinach, mint, and red onion with half the vinaigrette.'),
('19565', '10', 'Add chickpea mixture, drizzle with additional dressing, and toss again to coat. Season to taste with more salt and pepper.'),
('19565', '11', '*Buy harissa, a north African chile-and-spice paste, in the international section of many supermarkets.'),
('19565', '12', 'Heat level varies greatly from brand to brand, so try a little before using.'),
('19568', '1', 'Heat oven to 400 F.'),
('19568', '2', 'Heat the oil in a medium skillet over medium-high heat.'),
('19568', '3', 'Add the garlic and cook for 1 minute.'),
('19568', '4', 'Add the tomatoes, 1/2 teaspoon salt, and 1/4 teaspoon pepper and simmer for 3 minutes.'),
('19568', '5', 'Add the spinach and cook until it begins to wilt, 1 minute.'),
('19568', '6', 'Transfer to a 2-quart baking dish.Beat the egg whites until foamy, about 30 seconds, then pour them over the spinach mixture. Carefully place the whole yolks over the top.'),
('19568', '7', 'Bake until the whites are set, 20 to 22 minutes.Divide among individual plates.'),
('19568', '8', 'Add dollops of the cream cheese, if desired.Tip: To separate an egg, crack the shell on a counter. Working over a bowl, hold the egg upright and separate the shell into halves. Carefully transfer the yolk back and forth from one eggshell half to the other, letting all the white slip out into the bowl.'),
('19569', '1', 'In a large nonstick skillet, over medium heat, melt the butter.'),
('19569', '2', 'Saute the onion until softened. Meanwhile, in a large bowl, whisk together the eggs, the milk or water, the salt, and the pepper.'),
('19569', '3', 'Pour the mixture into the pan and cook, stirring occasionally, to desired doneness, 4 to 5 minutes. Just before the eggs are set, stir in the spinach.'),
('19570', '1', 'Heat the oil in a large skillet over medium heat.'),
('19570', '2', 'Add the chickpeas and cook about 2 minutes.'),
('19570', '3', 'Add the spinach in batches, stirring until just wilted. Sprinkle the salt and lemon juice over the spinach mixture and stir once more.'),
('19570', '4', 'Serve warm with toasted pita.'),
('19573', '1', 'Cook the pasta according to the package directions.'),
('19573', '2', 'Drain and return to the pot.'),
('19573', '3', 'Add the olive oil, vinegar, and spinach and toss to wilt. Stir in the scallions, raisins, ricotta, 1/2 teaspoon salt, 1/2 teaspoon pepper, and the basil. Divide among individual bowls and top with the Parmesan and pine nuts, if using.'),
('19574', '1', 'Wrap tortillas in aluminum foil and heat in a 350 F oven for 15 minutes. Meanwhile, saute 1 onion in olive oil over medium heat until softened, about 3'),
('19574', '2', 'minutes.'),
('19574', '3', 'Add rice, pinto beans, and 1 salt and cook for 2 minutes. Stir in'),
('19574', '4', 'cilantro. Divide the rice-and-bean mixture among the 8 warm tortillas. Top each with some cheese and spinach and roll.'),
('19574', '5', 'Serve with salsa or sour cream, if desired.'),
('19581', '1', 'Preheat oven to 400F.'),
('19581', '2', 'Place the olive oil in a medium skillet and place'),
('19581', '3', 'over medium heat.'),
('19581', '4', 'Add the garlic. Cook and stir 1 minute, until'),
('19581', '5', 'fragrant.'),
('19581', '6', 'Add the spinach and saut gently for 2 minutes.'),
('19581', '7', 'Remove from'),
('19581', '8', 'heat and season with the salt and pepper. set aside.'),
('19581', '9', 'Coat a large baking sheet with cooking spray. Unfold 1 piecrust onto the'),
('19581', '10', 'baking sheet. Spoon the spinach mixture evenly over the crust, leaving a'),
('19581', '11', '1-inch border around the edge. Layer the cottage cheese, mushrooms, and'),
('19581', '12', 'peppers over the spinach. Sprinkle with the thyme and Parmesan.'),
('19581', '13', 'Brush half the egg around the crust''s 1-inch border.'),
('19581', '14', 'Place the second'),
('19581', '15', 'crust on top and crimp the edges to seal.'),
('19581', '16', 'Brush evenly with the'),
('19581', '17', 'remaining egg.'),
('19581', '18', 'Cut slits in the top crust to allow steam to escape.'),
('19581', '19', 'Bake'),
('19581', '20', '35 minutes or until golden. Cool on a rack for 5 minutes before serving.'),
('19581', '21', 'Serve warm or at room temperature.'),
('19582', '1', 'Heat the oil in a large skillet over medium-high heat. Season the chicken with 1/2 teaspoon salt and 1/4 teaspoon pepper and cook until browned and cooked through, 8 to 10 minutes per side.'),
('19582', '2', 'Transfer to plates. Spoon off and discard all but 1 tablespoon of the fat and return the skillet to medium heat.'),
('19582', '3', 'Add the shallots and cook, stirring, until they begin to soften, 2 to 3 minutes. Stir in the wine and sour cream.'),
('19582', '4', 'Add the spinach, 1/4 teaspoon salt, and 1/4 teaspoon pepper. Cook, tossing gently, until the spinach begins to wilt, 1 to 2 minutes.'),
('19582', '5', 'Serve with the chicken.'),
('19584', '1', 'Heat broiler.'),
('19584', '2', 'Heat the oil in a large skillet over medium heat.'),
('19584', '3', 'Add the onion, 1/2 teaspoon salt, and 1/4 teaspoon pepper and cook, stirring occasionally, until the onion begins to soften, 5 to 6 minutes.'),
('19584', '4', 'Add the bell pepper and cook, stirring occasionally, until softened, 5 to 6 minutes.'),
('19584', '5', 'Add the spinach and cook, tossing, until the spinach is just wilted, 1 to 2 minutes.Meanwhile, remove the sausages from their casings and form into twelve 1/2-inch-thick patties.'),
('19584', '6', 'Place them on a broilerproof rimmed baking sheet and broil until cooked through, 4 to 5 minutes per side.Form sandwiches with the rolls, sausage patties, and vegetable mixture. great for guests'),
('19584', '7', 'These bite-size sandwiches make easy hors d''oeuvres. Cook the vegetables and form the patties up to a day in advance. broil the patties, reheat the vegetables, and assemble the sliders just before guests arrive.'),
('19589', '1', 'Cook the rice according to the package directions. Pat the chicken dry with paper towels. Carefully stuff the ginger under the skin. Season the chicken with 1 teaspoon salt and 1/4 teaspoon pepper.'),
('19589', '2', 'Heat the olive oil in a large skillet over medium heat.'),
('19589', '3', 'Add the chicken, skin-side down, and cook until the skin is crisp, 7 minutes. Turn and cook, covered, until cooked through, about 6 minutes.'),
('19589', '4', 'Heat the sesame oil and seeds in another large skillet over medium heat until the seeds are light gold, about 2 minutes.'),
('19589', '5', 'Add the spinach, 1/2 teaspoon salt, and 1/8 teaspoon pepper and cook until wilted. Divide the spinach among individual plates and serve with the chicken and rice. Shortcut: Instead of making the white rice that accompanies this dish, you can pick up a pint from a local Chinese or Thai restaurant. Or try using frozen cooked rice from the supermarket. Choose the brown variety for a healthy boost of whole grains.'),
('19591', '1', 'Preheat the oven to 350 degrees.'),
('19591', '2', 'Place the pecans on a baking sheet and toast in the oven until golden and fragrant, 6 minutes. roughly chop.'),
('19591', '3', 'Preheat a grill to medium-high heat on one side and medium heat on the other. Lightly brush the peaches with oil and grill over medium until nicely marked, about 4 minutes per side. Meanwhile, place a flat cast-iron skillet on the grill over medium-high heat.'),
('19591', '4', 'Add the bacon and cook until crisp. transfer to a paper-towel-lined plate.'),
('19591', '5', 'Combine the spinach, red onion, grilled peaches, pecans and bacon in a large bowl.'),
('19591', '6', 'Make the dressing: Mash the blue cheese with a fork in a bowl.'),
('19591', '7', 'Mix in the buttermilk, sour cream, sugar, and salt and pepper to taste. Toss with the salad just before serving.'),
('19591', '8', 'Photography by Miki Duisterhof'),
('19596', '1', 'Bring 1 cup water to a boil in a wide large pot over high heat, then cook spinach, tossing with tongs, until completely wilted, about 5 minutes.'),
('19596', '2', 'Drain in a colander, pressing with back of a spoon to extract as much liquid as possible.'),
('19596', '3', 'Heat butter in same pot over medium heat until foam subsides, then stir in nutmeg, 1/2 teaspoon salt, 1/4 teaspoon pepper, and spinach. Cook, tossing with tongs, until just heated through.'),
('19597', '1', 'In a large bowl, combine the lemon juice, olive oil, and cumin.'),
('19597', '2', 'Whisk together to combine well.'),
('19597', '3', 'Add the spinach, cucumber, and cheese. Toss to mix well and season to taste with salt and freshly ground pepper.'),
('19597', '4', 'Serve immediately.'),
('19599', '1', 'Butter a shallow 1 1/2- to 2-quart baking dish. Squeeze out as much water as possible from the spinach (use your hands or a clean kitchen towel). Set aside.'),
('19599', '2', 'Heat spinach and cream in a large saucepan over medium-high heat. Reduce heat to low and stir in cheese to melt. Stir in salt, pepper, and nutmeg. Adjust seasoning to taste.'),
('19599', '3', 'Transfer spinach mixture to buttered baking dish and sprinkle with bread crumbs. Just before serving, place dish in the oven 5 to 6 in. below a broiler set to high. broil until top is golden and crunchy, about 3 minutes.'),
('19600', '1', 'Watch how to make this recipe.'),
('19600', '2', 'Heat the olive oil in large skillet over medium-high heat. Once hot, add bacon to skillet and brown, reserve the crispy bacon bits and add the shallots and garlic to the pan. Cook 3 to 4 minutes then deglaze the pan with vinegar, turn spinach into pan and wilt down a bit but do not fully cook the spinach, just give it a few turns with tongs. Season the greens with salt, pepper and nutmeg.'),
('19600', '3', 'Place spinach on a serving dish and top with quartered eggs, shavings of cheese and reserved bacon bits.'),
('19601', '1', 'Preheat oven to 400F. Toss spinach in a very large bowl or pot with 3 tablespoons olive oil until leaves are lightly coated. Toss again with 1/8 teaspoon salt, pinch of black pepper, and red pepper flakes.'),
('19601', '2', 'Mix bread crumbs with garlic and remaining 1 tablespoon olive oil in a small bowl. Season with salt and pepper to taste.'),
('19601', '3', 'Pack spinach into a 2-quart baking dish as best as possible. it will mound. Sprinkle prepared bread crumbs over top.'),
('19601', '4', 'Bake until spinach fills casserole by about half, is very tender, and crumbs are golden brown, about 30 minutes.'),
('19601', '5', 'Serve hot.'),
('19601', '6', 'var article'),
('19601', '7', 'Type_27_data = {}.'),
('19601', '8', 'article'),
('19601', '9', 'Type_27_data.init_step_by_step_images = 0.'),
('19602', '1', 'In a large pot, cover the potatoes with cold water, add some salt then bring to a simmer. Cook, uncovered, until tender when pierced with a knife, about 20 minutes.'),
('19602', '2', 'Drain the potatoes.'),
('19602', '3', 'Melt the butter in a large skillet over medium heat.'),
('19602', '4', 'Add the garlic and the onion and cook until the onion has softened, about 2 minutes.'),
('19602', '5', 'Add the potatoes. Stir in the curry powder, then add the spinach and tomato. Cook and stir until the spinach has wilted and all the flavors have merged together, about 2 more minutes.'),
('19602', '6', 'Serve warm.'),
('19605', '1', 'Watch how to make this recipe.'),
('19605', '2', 'Preheat the oven to 350 degrees F.'),
('19605', '3', 'Place the prosciutto slices on a baking sheet and bake until just crisp, about 10 minutes.'),
('19605', '4', 'Let cool. Crumble the prosciutto slices into a container and store in the refrigerator.'),
('19605', '5', 'In a blender, combine the orange zest, orange juice, balsamic vinegar, honey, garlic, salt, and pepper. Blend until smooth. With the blender running, add the olive oil in a steady stream until combined.'),
('19605', '6', 'Transfer to a container and store in the refrigerator.'),
('19605', '7', 'To serve, put the spinach in a large bowl. Toss with enough of the vinaigrette to coat the spinach. Sprinkle with the crisp prosciutto crumbles, toss again, and serve.'),
('19606', '1', 'Preheat oven to 375 degrees.Wash and dry mushrooms. Pull the stems off the mushrooms, then chop the stems finely.'),
('19606', '2', 'Heat olive oil and butter in a skillet over medium-high heat.'),
('19606', '3', 'Add onion and chopped mushrooms stems and saute for several minutes, or until soft and starting to turn golden.'),
('19606', '4', 'Add panko crumbs, salt, and pepper. Stir and continue cooking for 2 minutes.'),
('19606', '5', 'Remove from heat and set aside to cool.Squeeze excess liquid out of thawed spinach. Set aside. In a large bowl, add softened cream cheese, sour cream, grated cheeses, and the cooled mushroom/onion/panko mixture. Fold together to combine.'),
('19606', '6', 'Add spinach, a dash of salt, a little pepper, and hot sauce to taste. Fold together until combined. Using a spoon, mound the mixture into the stemmed mushroom caps. Use the spoon to round the mixture on top.'),
('19606', '7', 'Place on a baking sheet or in a baking dish and bake for 20 to 25 minutes, or until the mushrooms are cooked and the filling is hot.'),
('19606', '8', 'Serve immediately or at room temperature. Yummy!'),
('19610', '1', 'Combine cider and sugar in a small saucepan over medium-high heat. Bring to a boil. cook until reduced to 1/4 cup (about 9 minutes).'),
('19610', '2', 'Remove from heat.'),
('19610', '3', 'Cook bacon in a small nonstick skillet over medium-high heat until crisp.'),
('19610', '4', 'Remove bacon from pan, reserving 1 teaspoon drippings in pan. set bacon aside.'),
('19610', '5', 'Add chopped shallots to drippings in pan. saut 1 minute.'),
('19610', '6', 'Remove pan from heat. stir in cider mixture, cider vinegar, 1/4 teaspoon salt, and black pepper.'),
('19610', '7', 'Crumble reserved bacon.'),
('19610', '8', 'Combine bacon, Granny Smith apple, onion, and spinach in a large bowl.'),
('19610', '9', 'Combine remaining 1/2 teaspoon salt, curry powder, and red pepper in a small bowl. Sprinkle salt mixture evenly over both sides of scallops.'),
('19610', '10', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('19610', '11', 'Add scallops to pan. cook 3 minutes on each side or until done.'),
('19610', '12', 'Drizzle cider mixture over spinach mixture. toss gently to coat.'),
('19610', '13', 'Place about 2 1/2 cups salad mixture on each of 4 plates. top each serving with 5 scallops.'),
('19614', '1', 'Heat a grill pan over medium-high heat.'),
('19614', '2', 'Place chicken between 2 sheets of plastic wrap, and pound to an even thickness using a meat mallet or small heavy skillet. Sprinkle both sides of chicken evenly with chili powder and salt. Lightly coat chicken with cooking spray.'),
('19614', '3', 'Add chicken to pan. cook for 3 minutes on each side or until done.'),
('19614', '4', 'Remove from pan. set aside.'),
('19614', '5', 'Combine half of pineapple, cilantro, orange juice, vinegar, habanero, and garlic in a blender. process until smooth. With blender on, gradually add olive oil until blended.'),
('19614', '6', 'Combine remaining pineapple, jicama, and the remaining ingredients in a large bowl.'),
('19614', '7', 'Drizzle with 3/4 cup dressing, and toss gently to coat. Divide salad evenly among 4 plates.'),
('19614', '8', 'Cut chicken across the grain into thin slices. divide chicken evenly over salads.'),
('19614', '9', 'Drizzle salads evenly with remaining 1/4 cup dressing.'),
('19616', '1', 'Heat oil in medium saucepan on medium-high heat.'),
('19616', '2', 'Add onions. cook and stir 3 to 4 min. or until crisp-tender.'),
('19616', '3', 'Stir in Neufchatel, milk and seasonings. cook on low heat 1 to 2 min. or until Neufchatel is melted and sauce is well blended.'),
('19616', '4', 'Add 1/3  of the spinach. cook 2 min. or just until wilted, stirring frequently.'),
('19616', '5', 'Add remaining spinach in batches, cooking and stirriing 1 to 2 min. after each addition.'),
('19617', '1', 'Special equipment: a silpat mat, a muffin tin, and a small drinking glass'),
('19617', '2', 'Preheat the oven to 375 degrees F.'),
('19635', '1', 'Combine first 8 ingredients in a large Dutch oven over medium-high heat. bring to a boil.'),
('19635', '2', 'Add chicken. return to a boil. Cover, reduce heat, and simmer 10 minutes, stirring occasionally.');