INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('34275', '9', 'Add the cream. When it begins to steam, add the corn and its pulp and cook for 10 minutes, stirring often until the liquid thickens slightly.'),
('34275', '10', 'Add the lima beans and cook another 2 minutes until the beans are just tender.'),
('34275', '11', 'Add the lobster meat and cook an additional 3 minutes until the meat is warmed through. Season with the cloves, cayenne, salt, and pepper. Fold in the chives.'),
('34275', '12', 'Spoon the succotash and lobster in equal proportions into 4 warm soup plates and serve.'),
('34275', '13', 'var article'),
('34275', '14', 'Type_27_data = {};'),
('34275', '15', 'article'),
('34275', '16', 'Type_27_data.init_step_by_step_images = 0;'),
('34276', '1', 'Combine first 7 ingredients and hot sauce, if desired, in a large Dutch oven. Cover and bring to a boil; reduce heat, and simmer 6 minutes.'),
('34276', '2', 'While soup simmers, skin and bone chicken. Shred chicken to measure 3 1/2 cups; add chicken to soup. Cook 3 minutes.'),
('34279', '1', 'Trim roast and cut into 2-inch pieces. Stir together all ingredients in a 6-quart slow cooker.'),
('34279', '2', 'Cover and cook on LOW 10 to 12 hours or until potatoes are fork-tender.'),
('34279', '3', 'Remove pork with a slotted spoon, and shred. Return shredded pork to slow cooker, and stir well. Ladle stew into bowls.'),
('34280', '1', 'Pour 1 can vegetable broth and water into a large pot.'),
('34280', '2', 'Place potatoes and cabbage into pot, and bring to a boil. Cook 10 minutes, or until potatoes are tender but firm.'),
('34280', '3', 'Place the beef in a skillet over medium heat, and cook until evenly brown.'),
('34280', '4', 'Drain grease and mix beef into the pot. Stir the onion, celery, green bell pepper, and garlic into the skillet. Cook until tender, then mix into the pot.'),
('34280', '5', 'Pour remaining broth and tomato-vegetable juice cocktail into the pot.'),
('34280', '6', 'Mix in tomatoes, frozen mixed vegetables, okra, lima beans, beef bouillon, Worcestershire sauce, celery seed, and bacon grease. Season with salt and pepper. Bring to a boil. Reduce heat to low, and simmer 2 hours.'),
('34281', '1', 'Preheat oven to 400°F.'),
('34281', '2', 'Toss shallots and tomatoes with 3 tablespoons oil in a large roasting pan and season with salt. Roast until tomatoes are tender but not falling apart, about 25 minutes.'),
('34281', '3', 'Transfer tomatoes only to a large bowl.'),
('34281', '4', 'Add pumpkins with salt to taste to shallots, tossing to coat with oil in pan. Roast until pumpkins are just tender, about 30 minutes, then add vegetables to tomatoes.'),
('34281', '5', 'Reduce oven temperature to 200°F.'),
('34281', '6', 'Straddle roasting pan across 2 burners.'),
('34281', '7', 'Add water and 1/2 cup wine and deglaze by boiling over moderately high heat, stirring and scraping up any brown bits. Reserve liquid.'),
('34282', '1', 'Soak the dried gigantes beans in water with the bay leaves over night.'),
('34282', '2', 'Bring the water to a boil and simmer until the beans are tender, about 30-40 minutes.'),
('34282', '3', 'Heat the oil in a pan.'),
('34282', '4', 'Add the onions, carrot and celery and cook until tender, about 10-15 minutes.'),
('34282', '5', 'Add the garlic and chili pepper flakes and cook until fragrant, about a minute.'),
('34282', '6', 'Add the tomatoes, paprika and oregano and simmer until the sauce thickens, about 20 minutes.'),
('34282', '7', 'Season the tomato sauce with salt and pepper to taste.'),
('34282', '8', 'Mix the parsley, dill, beans and 1/2 cup of the liquid that the beans were cooked in into the tomato sauce.'),
('34282', '9', 'Pour the mixture into a casserole dish.1'),
('34282', '10', 'Bake in a preheated 350F oven until the top is browned and most of the liquid has evaporated, about 50-60 minutes.'),
('34284', '1', 'Save Recipe'),
('34284', '2', 'Print Recipe'),
('34284', '3', 'Butter Bean Soup'),
('34284', '4', 'Ingredients1 lb. dry butter beans (aka lima beans - you can sub cannellini or navy beans)1/4 cup extra virgin olive oil1  large sweet onion, peeled and chopped2 cloves garlic, minced2  large carrots, peeled and sliced into rounds2 celery ribs, sliced1 can (14 oz) crushed tomatoes (fire roasted ok)6 tbsp fresh chopped dill, divided1 bay leaf'),
('34284', '5', 'Salt and black pepper'),
('34284', '6', 'Servings: 8 servings'),
('34284', '7', 'Kosher Key: Pareve'),
('34287', '1', 'To make bean mix: Measure pinto, navy, kidney, lima, and garbanzo beans, and combine in a large airtight container or bag.'),
('34290', '1', 'Add clams and mussels.'),
('34290', '2', 'Let cook for 2 minutes.'),
('34290', '3', 'Add squid and shrimp; cook until shrimp turns pink and squid turns opaque. With a mortar and pestle or spice grinder, combine saffron with salt to create a powder.'),
('34290', '4', 'Transfer to a small bowl, and combine with 2 cups stock and 1 cup brandy.'),
('34291', '1', 'In a large skillet fry bacon until crispy and remove to a paper towel-lined plate, reserving fat in pan. To the skillet add the bell pepper and garlic and cook until softened slightly, about 5 minutes.'),
('34291', '2', 'Add corn, lima beans, pearl onions, hot sauce and cream. Bring to a simmer and cook until vegetables are thawed and tender. Stir in reserved bacon and season with salt and pepper.'),
('34294', '1', 'Place bacon in a large, deep skillet. Cook over medium high heat until evenly brown.'),
('34294', '2', 'Drain, crumble and set aside. Reserve 2 tablespoons bacon fat.'),
('34294', '3', 'Add onions to fat in pan, and saute until soft. Stir in garlic powder, dry mustard, wine vinegar, and brown sugar. Simmer for 20 minutes.'),
('34294', '4', 'In a large pot or slow cooker combine bacon and onion mixture with the  kidney beans, lima beans, butter beans, and baked beans.'),
('34294', '5', 'Mix together, and simmer for 70 minutes.'),
('34295', '1', 'Pat rabbit dry and sprinkle evenly with 1 teaspoon salt and 1/2 teaspoon black pepper.'),
('34295', '2', 'Whisk together flour and cayenne in a shallow bowl, then dredge rabbit in flour, shaking off excess.'),
('34295', '3', 'Heat 2 tablespoons oil in a wide 6- to 7-quart heavy pot over medium heat until it shimmers. Brown half of rabbit, turning once, about 10 minutes total.'),
('34295', '4', 'Transfer to a plate.'),
('34295', '5', 'Add 1 tablespoon oil to pot and brown remaining rabbit; transfer to plate.'),
('34295', '6', 'Add remaining tablespoon oil to pot along with onion, bell pepper, garlic, 3/4 teaspoon salt, and 1/2 teaspoon pepper and cook, stirring and scraping up brown bits, until vegetables are softened, about 8 minutes.'),
('34295', '7', 'Add bay leaf, broth, tomatoes with juice, and rabbit with any meat juices from plate and bring to a simmer. Simmer, covered, 50 minutes.'),
('34295', '8', 'Stir in corn and lima beans, then simmer, uncovered, until stew is slightly thickened and vegetables are tender, 15 to 20 minutes. Season with salt and pepper. Discard bay leaf.'),
('34295', '9', 'Per serving, assuming eight servings: 445 calories, 25g fat (6g saturated), 86mg cholesterol, 523mg sodium, 29g carbohydrate, 5g fiber, 28g protein'),
('34295', '10', 'Gourmet'),
('34295', '11', 'See Nutrition Data''s analysis of this recipe ›'),
('34296', '1', 'Cook bacon in a Dutch oven over medium heat 3 minutes, stirring frequently.'),
('34296', '2', 'Add sausage; cook 4 minutes or until browned, stirring to crumble.'),
('34296', '3', 'Add beef; cook 3 minutes or until browned, stirring occasionally.'),
('34296', '4', 'Add onion, carrot, and celery to pan; cook 5 minutes, stirring occasionally.'),
('34296', '5', 'Add chicken, salt, and pepper to pan; cook 4 minutes, stirring occasionally.'),
('34296', '6', 'Add garlic; cook 1 minute, stirring constantly. Stir in wine; bring to a boil. Cook until liquid almost evaporates (about 3 minutes). Stir in stock, 3 cups water, and rice; bring to a boil. Reduce heat to medium-low, cover, and simmer gently about 30 minutes. Stir in potatoes; cover and simmer gently about 20 minutes, stirring occasionally. Stir in green beans and corn; simmer gently for 8 minutes or until done, skimming as necessary. Sprinkle with hot sauce, if desired.'),
('34297', '1', 'Soak beans overnight in enough water to cover by 2 inches; drain.'),
('34297', '2', 'Cook bacon in large stockpot on medium-high heat 4 min., stirring occasionally.'),
('34297', '3', 'Add onions, leeks, carrots and garlic; stir.  Reduce heat to low; cook 15 min., stirring occasionally.'),
('34297', '4', 'Add beans, ham hocks, sausages, bay leaves and paprika.'),
('34297', '5', 'Add enough water to just cover ingredients in stockpot.  Bring to boil over medium heat, stirring occasionally.  Skim off foam and fat from top of stew.  Reduce heat to low.'),
('34297', '6', 'Simmer, partially covered, 2-1/2 hours or until beans are tender.  Skim fat from top of stew.'),
('34297', '7', 'Remove ham hocks.'),
('34297', '8', 'Remove meat from the bones.  Return meat to pot; discard bones.'),
('34297', '9', 'Remove bay leaves; discard.  Season with salt and pepper.'),
('34300', '1', 'In a large Dutch oven, brown the beef and chopped onion over medium heat.'),
('34300', '2', 'Drain off any fat.'),
('34300', '3', 'Add chilies, salt and pepper, beans, water, seasoning mixes, hominy, and stewed tomatoes to the beef and onion. Bring to a boil. Reduce heat, and simmer for 30 minutes.'),
('34300', '4', 'Top with shredded cheese, and serve with chips.'),
('34302', '1', 'Heat oven to 400F.'),
('34302', '2', 'Mix milk, dressing and flour in large microwaveable bowl.  Microwave on HIGH 2 to 3 min. or until sauce is thickened, stirring after each min. Stir in cheese; microwave 1 min.'),
('34302', '3', 'Mix until well blended.'),
('34302', '4', 'Add turkey, mixed vegetables and onions; toss to coat.  Spoon into 9-inch pie plate; smooth surface.'),
('34302', '5', 'Place crust over filling; flute edge and seal to rim of pie plate.'),
('34302', '6', 'Cut several slits in crust to permit steam to escape.'),
('34302', '7', 'Place on baking sheet.'),
('34302', '8', 'Bake 30 to 35 min. or until crust is golden brown.'),
('34302', '9', 'Let stand 10 min. before serving.'),
('34303', '1', 'Cook bacon in large skillet on medium-high heat until crisp.'),
('34303', '2', 'Remove bacon with slotted spoon; drain on paper towel.  Cook and stir onions in reserved bacon drippings until tender.'),
('34303', '3', 'Add lima beans and water; stir.  Cook 5 min. or until beans are just tender, stirring occasionally.'),
('34303', '4', 'Stir in corn, milk, butter and vinegar.  Bring to boil.  Reduce heat to medium; simmer 10 min.  Stir in bacon.  Season with the salt and pepper.'),
('34306', '1', 'In a large salad bowl, whisk together the sugar, vinegar and oil.'),
('34306', '2', 'Add the onion, bell pepper, celery, green beans, lima beans, kidney beans, pinto beans and pimentos.'),
('34306', '3', 'Toss to evenly coat and place in large sealed container.'),
('34306', '4', 'Place in refrigerator and turn periodically to mix.'),
('34308', '1', 'In a blender, blend the lemon juice, water, strawberries with juice, sugar, and ice cubes until slushy.'),
('34308', '2', 'Serve in a tall glass with a straw.'),
('34309', '1', 'Heat the oil in a large saucepan over medium heat, and stir in the onion. Cook and stir until the onion is soft and beginning to brown, about 8 minutes. Stir in the curry paste, cook for 2 minutes longer, then add the coconut milk water, and pumpkin. Bring to a boil over high heat, then reduce heat to medium-low, cover, and simmer until the pumpkin is nearly tender, about 10 minutes.'),
('34309', '2', 'Stir in the butter beans, and continue simmering until the pumpkin is tender, about 5 minutes. Season to taste with salt and pepper, then stir in the spinach and cilantro. Simmer a few more minutes to reheat, and serve.'),
('34312', '1', 'Bring a large pot of water to a boil; meanwhile, prepare an ice-water bath. With a paring knife, core tomatoes, and score an X on the bottoms. Working in batches, carefully lower tomatoes into boiling water; when skins begin to split, after 30 to 60 seconds, use a slotted spoon to transfer tomatoes to water bath.'),
('34318', '1', 'In slow cooker stoneware, combine beans, tomatoes,  cup (125 ml) tomato juice, green onions, salt and black pepper to taste.'),
('34318', '2', 'Cover and cook on Low for 6 hours or on High for 3 hours, until hot and bubbly. Stir in green pepper and cheese. Cover and cook on High for 20 minutes, until pepper is tender and cheese is melted.'),
('34318', '3', 'Make Ahead'),
('34318', '4', 'This dish can be partially prepared before it is cooked. Complete Step'),
('34318', '5', 'Cover and refrigerate overnight. The next morning, continue with the recipe.'),
('34318', '6', 'var article'),
('34318', '7', 'Type_27_data = {};'),
('34318', '8', 'article'),
('34318', '9', 'Type_27_data.init_step_by_step_images = 0;'),
('34319', '1', 'Saute the onions in oil until lightly browned. Rinse the split peas and barley in water and place in a large pot.'),
('34319', '2', 'Add the chicken stock and water and cook over medium-high heat. until almost tender, about 1 hour.'),
('34319', '3', 'Add the pasta and cook 10 minutes longer. Then add the lima beans and vegetables, cook until the vegetables are tender. Season with dill, salt and pepper.'),
('34321', '1', 'Season the chicken and rabbit generously with salt.'),
('34321', '2', 'In a 16-to 18-inch paella pan, heat the oil over medium heat.'),
('34321', '3', 'Add the chicken and rabbit and cook, stirring frequently, until browned, about 5 minutes.'),
('34321', '4', 'Add all the beans and cook until they begin to soften, about 5 minutes. Reduce the heat to medium-low, add the garlic, tomatoes, and 2 pinches of salt and cook, stirring from time to time, until the tomato has darkened to a deeper shade of red, 10 to 15 minutes.'),
('34321', '5', 'Stir in the snails (if using), sprinkle in the pimentn, and add the water. Bring to a simmer, and continue simmering for 10 minutes, or until the meat and beans are tender.'),
('34321', '6', 'Add the saffron and (if you are not using snails) the rosemary. Taste for salt and adjust the seasoning as needed. Increase the heat to high and bring to a boil. Sprinkle in the rice. With a wooden spoon, probe the pan to make sure the rice is evenly distributed. Do not stir again.'),
('34321', '7', 'Cook, uncovered, for 10 minutes over high heat, then reduce it to low and cook for an additional 8 minutes, or until the liquid is absorbed and the rice is al punto, with just a bite to it.'),
('34321', '8', 'Remove the paella from the heat, cover with paper towels, and let rest for 5 minutes before serving.'),
('34321', '9', 'var article'),
('34321', '10', 'Type_27_data = {};'),
('34321', '11', 'article'),
('34321', '12', 'Type_27_data.init_step_by_step_images = 0;'),
('34325', '1', 'Bring a large pot of lightly salted water to a boil.'),
('34325', '2', 'Add pasta and cook for 8 to 10 minutes or until al dente; drain and cool.'),
('34325', '3', 'In a large bowl, combine pasta, eggs, tuna Cheddar cheese, celery, onion, roasted red pepper, and lima beans.'),
('34325', '4', 'Whisk together mayonnaise, lemon juice, and paprika. Season with salt.'),
('34325', '5', 'Pour dressing over pasta mixture, and mix together.'),
('34326', '1', 'In a large bowl, whisk together the white sugar, vinegar, and vegetable oil. Stir in the celery, green pepper, red onion and pimentos.'),
('34326', '2', 'Pour the green beans, wax beans, lima beans and kidney beans into a colander, and rinse under cold water.'),
('34326', '3', 'Let drain for a few minutes, then stir into the bowl with the rest of the salad. Store in a large jar in the refrigerator, and shake or turn occasionally for 1 day to marinate. If you do not have a sealed container, simply stir the salad every few hours. This keeps for about a week, but will be gone sooner.'),
('34327', '1', 'In a large pot, bring the water to a boil.'),
('34327', '2', 'Add lima beans, salt and sugar. Cook over medium-low heat for 15 minutes.'),
('34327', '3', 'Add the corn and green chilies, cover, and continue cooking until the beans are tender, about 5 more minutes.'),
('34327', '4', 'Drain and serve immediately. Top with butter if desired.'),
('34328', '1', 'Watch how to make this recipe.'),
('34328', '2', 'In a slow cooker, combine all ingredients but the couscous, shredded cheese, cilantro and salt and pepper. Cover and cook on LOW for 6 to 8 hours or on HIGH for 3 to 4 hours.'),
('34328', '3', 'Five to 10 minutes before serving (depending on temperature of slow cooker) add couscous, cover and cook, until couscous is tender. Season, to taste, with salt and black pepper.'),
('34328', '4', 'Just before serving, top each serving with shredded cheese and cilantro.'),
('34334', '1', 'Put everything into crock pot & stir.Cook on low 4-6 hours.At serving time you can use a potato masher, slotted spoon or a fork (if you want to do it right in the serving bowl) to mash up some of the potatoes and thicken the soup a bit.'),
('34360', '1', 'Bring the water to a boil in a stockpot, then add the chicken and beef bouillon granules, seafood seasoning, worcestershire sauce, bay leaves and sugar; stir until bouillon is dissolved. Season with salt and pepper.'),
('34360', '2', 'Cut the whole crabs in half, add them to the pot, and bring to a second boil.'),
('34360', '3', 'Remove whole crabs after 5 to 10 minutes. Skim any excess froth created by the crab parts.'),
('34360', '4', 'Add the tomatoes and hot sauce; stir to combine.'),
('34360', '5', 'Add the carrots, celery, corn, green beans, lima beans, cabbage, and onion, bring to a low boil, and cook for 10 minutes.'),
('34360', '6', 'Add the potatoes and cook until tender.'),
('34360', '7', 'Add the crabmeat and cook for 10 minutes. Season with salt and pepper.'),
('34360', '8', 'Serve garnished with chopped parsley.'),
('34361', '1', 'If using ears of corn, cut the kernels off and set aside. Discard the cobs.'),
('34361', '2', 'Heat the oil in a large skillet over medium heat.'),
('34361', '3', 'Add the onions and cook, stirring occasionally, until softened, about 2 minutes.'),
('34361', '4', 'Add the garlic and cook for 1 minute more. Stir in the corn, lima beans, zucchini, and tomatoes and cook, stirring occasionally, until the vegetables are tender, about 7 minutes.'),
('34361', '5', 'Spray a large nonstick skillet or grill pan with cooking spray, and preheat it over medium-high heat.'),
('34361', '6', 'In the meantime, prepare the scallops. Pat them dry and season them with 1/4 teaspoon of salt and 1/4 teaspoon of pepper.'),
('34361', '7', 'Add the scallops and cook until the inside is opaque, 5 to 6 minutes, turning once.'),
('34361', '8', 'Stir the vinegar and basil into the succotash, season with additional salt and pepper, to taste, and serve topped with grilled scallops.'),
('34361', '9', 'Garnish with Parsley'),
('34361', '10', 'Drizzle.'),
('34361', '11', 'Combine all ingredients in a blender and puree.'),
('34369', '1', 'In an oiled large, heavy frying pan, bake sausages in a 350F oven, turning once, until lightly browned, 20 to 30 minutes.'),
('34369', '2', 'Remove and cut into 2-inch diagonal slices.'),
('34369', '3', 'Add enough oil to frying pan to make 3 tablespoons.'),
('34369', '4', 'Add onions and saut until limp. Stir in remaining ingredients except  cup of the parsley. Cover and simmer for about 45 minutes, stirring occasionally. Sprinkle with remaining parsley. Makes 4 to 5 servings.COOKED LIMAS. Put 1  cups large dry lima beans, rinsed, into a large kettle.'),
('34369', '5', 'Add enough cold water to cover deeply.'),
('34369', '6', 'Heat to boiling; boil for 2 minutes; remove from heat, cover, and let stand for 1 hour.'),
('34369', '7', 'Drain, rinse, and cover with fresh salted water.'),
('34369', '8', 'Heat to boiling, then gently boil, uncovered, until beans are tender, about 45 minutes; drain.SUGGESTED ACCOMPANIMENTS: Cooked chard dressed with oil, vinegar, salt, and pepper served at room temperature. Large bread sticks or crusty bread. Full fruity red table wine, as a hearty California Zinfandel. Chilled fresh orange segments.Womans Day.'),
('34380', '1', 'Mix the meat with paprika, garlic, Worcestershire, parsley, salt and pepper.'),
('34380', '2', 'Heat a large skillet over medium high heat with a tablespoon extra-virgin olive oil, a turn of the pan. Form 4 large patties and make a indentation in the center of each burger to counteract the burger bulge that happens as the meat cooks. Cook burgers 6 minutes on each side, turning once.'),
('34380', '3', 'Heat a small pot over medium heat with 2 tablespoons extra-virgin olive oil, eyeball it.'),
('34380', '4', 'Add onions and peppers, cook 8 to 10 minutes then add salt, pepper, vinegar and brown sugar. Stir 1 minute, add tomato sauce and reduce heat to low. Simmer 5 minutes.'),
('34380', '5', 'Heat a medium skillet over medium high heat.'),
('34380', '6', 'Add 1 tablespoon extra-virgin olive oil, a turn of the pan.'),
('34380', '7', 'Add limas, corn, okra, pickled beans, hot sauce, thyme, salt and pepper and cook to heat through 5 to 6 minutes. Toss in scallions and turn off heat.'),
('34380', '8', 'Serve burgers on buttered toasted muffins with pepper and onion topping.'),
('34380', '9', 'Serve succotash alongside.'),
('34394', '1', 'Remove limas from package and let defrost a little and separate them with your fingers.'),
('34394', '2', 'Heat a skillet over high heat until hot; add the peanut oil, swirl, heat for 30 seconds.Scatter in the beans; stir-fry briskly for 30 seconds until the color turns icy green.Sprinkle in the salt and sugar and stir rapidly for another 30 seconds to season them evenly.'),
('34394', '3', 'Add the stock or water, even out the beans, turn heat to medium-low to maintain a strong simmer.Cover (but leave the cover ajar so the liquid will concentrate) and simmer for about 5 minutes.Uncover, turn heat high and stir rapidly until the remaining liquid has evaporated.'),
('34394', '4', 'Add the sesame oil, stir to distribute evenly and pour into serving dish.'),
('34401', '1', 'Cook pasta according to directions.Meanwhile, in a saucepan, combine vegetable broth, veggies, juice, tomato paste, thyme, oregano, basil and pepper.Bring to a boil; cover and simmer for 5 minutes.'),
('34401', '2', 'Drain pasta; add cooked pasta to soup and simmer for an additional 15 minutes.'),
('34406', '1', 'Cook the pre-soaked beans in a pressure cooker, with enough water to cover by one inch, for 20 minutes and allow to sit, undisturbed, for 2-3 hours before proceeding with recipe.Tip the beans into a large baking pan.'),
('34406', '2', 'Add all of the remaining ingredients, except the dill, and stir well to distribute.'),
('34406', '3', 'Pour over enough hot water to cover beans by 1".'),
('34406', '4', 'Place pan in oven and set oven to 400F.'),
('34406', '5', 'Bake for 2 hours. Check, if you like your beans more tender, cook them a half hour longer.Stir dill in for last 15 minutes of baking.There will still be plenty of juices in the pan, but these will be absorbed by the beans and thicken as the beans cool.Like nearly all bean recipes, these only improve the next day, and the day after next.In Greece, these beans would constitute the main, ''vegetarian'' meal and would not include the bacon, which is my own addition. We often eat meatless, especially when we''re fasting. With or without the bacon or sausage, this is good eating, especially with a big chunk of sharp feta cheese on the side to nibble on between bites of beans and slurps of sauce and some good, honest, crusty bread to clean your plate up with. :-).'),
('34410', '1', 'In a 5- to 6-quart pan over high heat, bring 2 quarts water to a boil.'),
('34410', '2', 'Add 1 pound rinsed mung bean sprouts and 1/2 teaspoon salt. Cook until sprouts begin to wilt but still retain a slight crunch, 4 to 5 minutes.'),
('34410', '3', 'Drain well and pour into a bowl.'),
('34410', '4', 'Add 2 tablespoons white distilled vinegar, 2 tablespoons Asian sesame oil, 1 tablespoon sugar, and salt and pepper to taste.'),
('34410', '5', 'Serve at room temperature or cold.'),
('34410', '6', 'Shortly before serving, sprinkle mung bean sprout salad with about 1 tablespoon toasted sesame seeds.'),
('34419', '1', 'Rinse the mung beans in a few changes of cold water, picking through them to remove any stones or grit.'),
('34419', '2', 'Place the beans in a saucepan along with the water, cinnamon stick, and ginger. Bring to a boil, then reduce to a simmer and cook for 40 minutes, until the beans have cracked open a bit but are not mushy.'),
('34419', '3', 'Add the sugar, salt, and vanilla extract. Continue to simmer until the sugar is dissolved, about three minutes.'),
('34419', '4', 'Stir in the coconut milk. Cook until the coconut milk is just heated through, about 2 minutes. Take care not to simmer for too long, or else the milk will thicken too much.'),
('34419', '5', 'Remove the ginger and cinnamon stick from the pot. Ladle the porridge into bowls and serve warm.'),
('34424', '1', 'Boil noodles in salted water for 3 minutes; drain; set aside.'),
('34424', '2', 'Combine turkey, egg whites, scallions, mushrooms, fish sauce, oyster sauce, sugar and black pepper in a bowl.'),
('34424', '3', 'Heat oil in a large skillet over medium-high heat; cook turkey mixture, stirring, until dry and crumbly, about 7 minutes.'),
('34424', '4', 'Remove from heat. Push meat to one side; place pepper strips in pan. Fill a bowl with warm water. Soak 1 piece rice paper until pliable, but not entirely soft, 10 to 15 seconds. Lay flat on a cutting board.'),
('34424', '5', 'Place 2 bell pepper strips across wrapper 2 inches from bottom. On top of strips, layer 1/2 cup turkey mixture, 1/8 of mung beans, 1/8 of noodles and 1/8 of pepper strips to form a log-shaped pile. Fold bottom edge of wrapper up and sides in against filling.'),
('34424', '6', 'Roll up to top edge. Repeat with remaining ingredients.'),
('34424', '7', 'Cut in half on bias.'),
('34429', '1', 'Preheat the oven to 35'),
('34429', '2', 'In a baking dish, mix the mirin, vinegar and soy sauce.'),
('34429', '3', 'Add the tofu; let stand for 15 minutes, turning halfway through.'),
('34429', '4', 'Pour the marinade into a bowl.'),
('34429', '5', 'Bake the tofu for 10 minutes.'),
('34429', '6', 'Cut into 1/2-inch pieces.'),
('34429', '7', 'Meanwhile, bring a large pot of salted water to a boil and fill a large bowl with ice water.'),
('34429', '8', 'Add the noodles to the pot and cook until al dente, 6 minutes.'),
('34429', '9', 'Drain the noodles, reserving 1/3 cup of cooking water. Immediately plunge the noodles into the ice water to cool; drain well.'),
('34429', '10', 'Transfer the noodles to a large bowl and add the bean sprouts and cilantro.'),
('34429', '11', 'In a food processor, combine the peanut butter with 1 teaspoon of chili-garlic sauce. With the machine on, slowly add the 1/3 cup of reserved noodle cooking water.'),
('34429', '12', 'Pour in the reserved marinade, season with salt and process until combined.'),
('34429', '13', 'Pour the peanut sauce over the noodles and toss well.'),
('34429', '14', 'Transfer the noodles to bowls, top with the tofu and serve with lime wedges, peanuts and chili-garlic sauce.'),
('34431', '1', 'Put the ingredients except for the boiling water into a bowl.It will be super thick and very delicious.'),
('34431', '2', 'Put the sauce into a saucepan and let it cook through until it is hot.  It is going to be really thick and this is where the boiling water comes in.  I add enough hot water to get it the consistency that I want it to be.Slice the vegetables and grate the carrots.  Slice the limes to squeeze over the pizza when it is finished cooking.'),
('34431', '3', 'Roll out the pizza dough.'),
('34431', '4', 'Spread some of the sauce over the pizza crust.'),
('34431', '5', 'Add the vegetables and cheese.  Leave the cilantro and limes off until the pizza is cooked.'),
('34431', '6', 'Bake in a 500 degree oven that has been preheated for at least 30 minutes.  This is the secret for a crispy crust.'),
('34431', '7', 'Garnish the pizza with minced cilantro and a squeeze of lime.'),
('34433', '1', 'In a small bowl, soak the dried mung beans in warm water until they are softened, about 30 minutes.'),
('34433', '2', 'Drain the beans and transfer them to a blender.'),
('34433', '3', 'Add the coconut milk and puree until very smooth.'),
('34433', '4', 'Transfer the mung-bean puree to a large bowl and whisk in the white rice flour, cornstarch, water, scallions and turmeric, and season lightly with salt.'),
('34433', '5', 'Let the crpe batter rest for at least 20 minutes or refrigerate overnight.'),
('34433', '6', 'Heat 1 teaspoon of vegetable oil in a 10-inch nonstick skillet.'),
('34433', '7', 'Add a few slices of pork, a couple of shrimp and a few slivers of white onion and cook for 30 seconds. Stir the crpe batter and pour 2/3 cup of it into the pan; tilt and swirl the pan to coat the bottom with a very thin layer of batter, letting it come up the side of the pan. Scatter 1/4 cup of the bean sprouts over the crpe and drizzle 2 teaspoons of vegetable oil around the edges. Cover the skillet and cook over moderately high heat until the bottom of the crpe is golden and crisp, about 2 minutes. Slide the crpe onto a plate and serve with lettuce leaves, mint and the Sweet and Spicy Vietnamese Dipping Sauce. Repeat with the remaining ingredients, serving the crpes as soon as they are cooked.'),
('34434', '1', 'In a large pot of boiling salted water, cook the spaghetti until it is al dente.'),
('34434', '2', 'Drain the spaghetti and rinse under cold water until cool.'),
('34434', '3', 'Drain very well.'),
('34434', '4', 'Meanwhile, in a food processor, combine the peanut butter with the lime juice, red curry paste, stock and 1/4 cup of the cilantro leaves and puree. Season the sauce with salt.'),
('34434', '5', 'In a large bowl, toss the spaghetti with the peanut sauce, bean sprouts, scallions and carrot until well coated. Season with salt.'),
('34434', '6', 'Transfer to bowls and sprinkle with the remaining cilantro leaves and the peanuts.'),
('34434', '7', 'Serve with lime wedges.'),
('34436', '1', 'Heat peanut oil in a wok or 12-inch heavy skillet over moderately high heat until smoking.'),
('34436', '2', 'Add ginger, 1/4 cup scallions, and salt and stir-fry 1 minute.'),
('34436', '3', 'Add rice and stir-fry until beginning to brown, 7 to 10 minutes.'),
('34436', '4', 'Add remaining ingredients (including scallions) and stir-fry until liquid is absorbed, about 2 minutes. Season with pepper.'),
('34437', '1', 'In a large bowl, whisk the rice flour with the cornstarch, tapioca flour and salt.'),
('34437', '2', 'Whisk in the water and 2 teaspoons of the oil until blended.'),
('34437', '3', 'In a small bowl, cover the tree ear mushrooms with warm water and let stand until softened, about 5 minutes.'),
('34437', '4', 'Drain and chop the mushrooms.'),
('34437', '5', 'In a small skillet, heat the remaining 2 tablespoons of oil.'),
('34437', '6', 'Add the ground pork and the onion and cook over moderate heat, breaking up the meat with a spatula, until no pink remains, about 4 minutes. Stir in the chopped mushrooms and the fish sauce and season with salt and pepper.'),
('34437', '7', 'Preheat the oven to 42'),
('34437', '8', 'Oil 3 large baking sheets.'),
('34437', '9', 'Heat an 8-inch nonstick skillet and brush with oil.'),
('34437', '10', 'Whisk the rice-flour batter well. When the oil is hot, pour 2 tablespoons of the batter into the skillet, tilting and shaking the pan to evenly coat the bottom with batter. Cover and cook over moderate heat until the crpe is firm, about 2 minutes. With a spatula, flip the crpe and cook for 30 seconds longer. Flip the crpe out flat onto a prepared baking sheet. Repeat with the remaining batter to make a total of 18 crpes; don''t let the crpes overlap on the baking sheets or they will stick together.'),
('34437', '11', 'Spoon about 2 tablespoons of the mushroom filling into the center of each crpe and fold in the sides to cover the filling and form a neat square. Cover the crpes with foil and bake until heated through, about 5 minutes.'),
('34437', '12', 'Arrange the rice crpe packets on a platter and spoon the Nuoc Cham Sauce over them. Scatter the cucumber slices, fried shallots and bean sprouts all over the crpes and serve.'),
('34440', '1', 'Put noodles in a large bowl and cover with boiling water.'),
('34440', '2', 'Let sit 5 to 8 minutes, or until tender.'),
('34440', '3', 'Drain; rinse with cold water.'),
('34440', '4', 'Heat a large wok over medium heat.'),
('34440', '5', 'Add oil and swirl to coat.'),
('34440', '6', 'Add garlic and cook until fragrant, 30 seconds. Stir in sambal (start with 1 tbsp.); mixture will spatter, so stand back after adding.'),
('34440', '7', 'Increase heat to medium-high and add sausages. Cook, stirring occasionally, until sausages are light golden, 1 to 2 minutes.'),
('34440', '8', 'Add onions and cook, stirring, until beginning to soften but still quite crisp, 1 to 2 minutes.'),
('34440', '9', 'Add noodles and soy sauce, stirring to coat.'),
('34440', '10', 'Make a well in pan. Crack in eggs (push noodles aside if they fall into the center) and cook until whites begin to set, 3 minutes. Break yolks with a spoon; scramble eggs and toss with noodles.'),
('34440', '11', 'Add white pepper, 1 tbsp. water, the bean sprouts, and crab; cook, stirring, until bean sprouts are tender-crisp, 2 minutes.'),
('34440', '12', '*We love the complex flavor of Glory brand''s Nonya Sambal Chilli, available at Asian grocery stores. Grind white pepper in a clean coffee grinder; its fresh taste is worth the effort.'),
('34445', '1', 'In a large saucepan, cover the chicken breasts with water and bring to a gentle simmer. Cook over moderately low heat until the chicken is white throughout, about 12 minutes.'),
('34445', '2', 'Transfer the poached chicken breasts to a plate and let stand until cooled slightly, about 10 minutes.'),
('34445', '3', 'Meanwhile, in a small bowl, whisk the mayonnaise with the rice vinegar, wasabi powder, Asian sesame oil and 1 1/2 tablespoons of water and season with salt and pepper.'),
('34445', '4', 'In a large serving bowl, toss the lettuce with the Asian pear slices, cucumber, scallions, bean sprouts and 2/3 cup of the wasabi dressing. Slice the chicken breasts crosswise 1/4 inch thick and lay the slices on top of the salad. Spoon the remaining wasabi dressing over the chicken breasts, sprinkle with the chopped wasabi peas and serve at once.'),
('34447', '1', 'Cook rice according to directions.'),
('34447', '2', 'While rice cooks, combine 1 tablespoon sherry, 1 tablespoon soy sauce, sugar, and beef. Stir together 1 tablespoon sherry, 1 tablespoon soy sauce, broth, cornstarch, hoisin, and Sriracha.'),
('34447', '3', 'Heat 1 tablespoon oil in a large skillet over medium-high heat.'),
('34447', '4', 'Add beef mixture; saut 3 minutes or until browned.'),
('34447', '5', 'Remove beef from pan.'),
('34447', '6', 'Add remaining 1 tablespoon oil to pan.'),
('34447', '7', 'Add ginger and garlic; cook 30 seconds, stirring constantly.'),
('34447', '8', 'Add broccoli and 1/4 cup water; cook 1 minute.'),
('34447', '9', 'Add onions; cook 1 minute, stirring constantly.'),
('34447', '10', 'Add broth mixture and beef mixture; cook 2 minutes or until beef is thoroughly heated and sauce is slightly thick.'),
('34447', '11', 'Serve beef mixture over rice.'),
('34448', '1', 'Stir together chicken broth, soy sauce, oyster sauce and cornstarch in a large cup. Set mixture aside.'),
('34448', '2', 'Heat 1 Tbsp. oil in a 12-inch nonstick skillet over medium-high heat.'),
('34448', '3', 'Add onion, zucchini, bell pepper and bean sprouts. Cook, stirring constantly, until vegetables are crisp-tender, for about 3 minutes.'),
('34448', '4', 'Add chicken and cook for 1 minute more. Then transfer to a plate and keep warm.'),
('34448', '5', 'Add remaining tablespoon vegetable oil and eggs to pan.'),
('34448', '6', 'Let eggs set for about 30 seconds, then scramble until they''re firm, for 1 to 2 minutes. Stir reserved chicken broth mixture and pour it into pan with eggs. Stir until sauce thickens, for about 5 minutes.'),
('34448', '7', 'Add rice, chicken and vegetables to pan. Stir until blended thoroughly and heated through.'),
('34450', '1', 'Preheat the oven to 42'),
('34450', '2', 'In a medium bowl, lightly beat the eggs with the scallions. Season with salt and pepper.'),
('34450', '3', 'Heat the oil in a 9-inch nonstick ovenproof skillet.'),
('34450', '4', 'Add the ham and cook over moderately high heat until lightly browned, about 1 minute.'),
('34450', '5', 'Add the mushrooms and cook until softened, about 2 minutes.'),
('34450', '6', 'Add 1 tablespoon of the soy sauce and simmer for 30 seconds.'),
('34450', '7', 'Add the snow peas and cook, stirring, for 30 seconds, then add the bean sprouts and cook, stirring, for 30 seconds. Season with salt and pepper. Push the shrimp into the vegetables and add the eggs, spreading them evenly.'),
('34450', '8', 'Bake the omelet in the oven for about 12 minutes, or until set in the center.'),
('34450', '9', 'Meanwhile, in a small bowl, combine the remaining 2 tablespoons of soy sauce with the rice vinegar, sesame oil and chili oil.'),
('34450', '10', 'Remove the skillet from the oven, slide the omelet onto a serving plate and sprinkle with the cilantro.'),
('34450', '11', 'Cut the omelet into wedges and serve warm or at room temperature with the soy dipping sauce.'),
('34454', '1', 'Heat a wok until very hot.'),
('34454', '2', 'Add 2 tablespoons of the canola oil and when it is nearly smoking, add the sliced onion and chicken strips. Stir-fry over high heat until the chicken is lightly browned in spots but not cooked through, about 3 minutes.'),
('34454', '3', 'Add the fish sauce and stir-fry for 10 seconds. Scrape the chicken onto a medium plate and wipe out the wok.'),
('34454', '4', 'Heat the remaining 2 tablespoons of oil in the wok.'),
('34454', '5', 'Add the broccoli, celery, snow peas, garlic and ginger and stir-fry over high heat until crisp-tender, 3 to 4 minutes. Return the chicken to the wok along with any accumulated juices.'),
('34454', '6', 'Add the sambal and hoisin and oyster sauces and stir-fry just until the chicken is cooked through, 3 to 4 minutes longer.'),
('34454', '7', 'Add the bean sprouts, basil and lime juice and toss well.'),
('34454', '8', 'Transfer to a bowl and serve right away, with steamed jasmine rice.'),
('34455', '1', 'Preheat the broiler. In a small bowl, combine the ketchup, soy sauce, sherry and sesame oil. In another small bowl, blend 1 tablespoon of the ketchup sauce with the lemon juice and reserve.'),
('34455', '2', 'Arrange the mushroom caps on a cookie sheet, stemmed side down; brush with the vegetable oil and season with salt and pepper. Broil 6 inches from the heat for 4 minutes, rotating the pan if necessary, until browned. Turn the caps and broil for 3 minutes, or until lightly browned.'),
('34455', '3', 'Brush the caps with some ketchup sauce and broil for 30 seconds, or until crisp and deeply browned. Turn, brush again with sauce and broil for 30 seconds longer. Stack the caps and slice into 1/4-inch strips.'),
('34455', '4', 'On the cookie sheet, brush the tofu on both sides with some of the ketchup sauce. Broil for 1 minute, or until deeply browned and crisp. While still on the sheet, gently cut into 1-inch cubes.'),
('34455', '5', 'In a bowl, toss the mushrooms, scallion, tomato and sprouts with the lemon dressing; season with salt and pepper. Using a spatula, transfer the tofu to the salad, toss lightly and serve.'),
('34457', '1', 'Bring a pressure cooker full of water to a rolling boil.'),
('34457', '2', 'Add the oxtail and brisket to the boiling water and return to a boil. Set the timer for 12 minutes, after the water returns to a boil. Prepare a bowl of cold water.While the bones are boiling, put the onion and ginger on a sheet pan and place directly under the heating element of your broiler, cut side up. Broil until the onion and ginger is nicely charred.When the timer goes off, remove the oxtail and brisket and transfer them to the water to chill. Wash the bones thoroughly to remove any congealed blood, or other contaminants that can cloud your soup. Wash the pot out well, and then add the bones and meat back in.'),
('34457', '3', 'Put the cinnamon, star anise, fennel seeds and cloves into a pan and roast on the stove, tossing frequently to prevent burning, until the spices are fragrant.'),
('34457', '4', 'Add the roasted spices to the pot with the brisket and bones and then add the cilantro roots and 8 cups of water. Seal the lid and bring the cooker up to high pressure. When its at pressure, set the timer for 30 minutes.When the timer goes off, use the quick release method to release the pressure from your cooker and when the pressure has gone down, open the lid.'),
('34457', '5', 'Remove the brisket, and quickly wrap it in plastic wrap, to prevent the meat from drying out.'),
('34457', '6', 'Let this come down to room temperature and store it in the refrigerator until you''re ready to use it.Seal the lid to the pressure cooker again and bring the pot back up to high pressure. Continue cooking the broth for another 45 minutes and then let the pressure drop naturally.When the pressure has dropped, open the lid and use tongs to remove the oxtail and set aside(you can pick the meat and connective tissue off the oxtails to serve on top of your Pho, or season it and press it into a terrine). Pass the stock through a fine mesh sieve to remove the aromatics and then skim off most, but not all, of the fat.You should now have 5 cups of stock. If you have less, add some water to make 5 cups. If you have more, you will need to boil your stock down a little more to concentrate it.To prepare the Pho, soak the banh pho in warm water for an hour to rehydrate. When the noodles no longer have a tough core, drain them. You can store them in a sealable plastic bag in the refrigerator for up to a day.'),
('34457', '7', 'Put the prepared stock in a pot and add the fish sauce and evaporated cane juice, adjusting both to taste. Keep the Pho broth warm over low heat.Because the noodles will get soggy quickly be sure to have your table prepped with condiments and have all your toppings prepared so you can assemble all the bowls and get them to the table as quickly as possible.Slice the onion as thinly as possible and then soak them in water. Slice the cooked brisket. Slice the tenderloin as thinly as possible.Bring a large pot of water to a boil. The rehydrated noodles should cook in about 1 minute, so have a strainer ready and add the noodles to the boiling water.'),
('34457', '8', 'Drain as soon as they''re cooked (you''ll want them to still be a little chewy as they will continue to cook in the bowls with the broth).Divide the noodles between your bowls and top with the sliced onions, cilantro, brisket and raw tenderloin. Bring the Pho broth to a boil and divide it between the bowls and serve with the rest of the condiments and toppings.'),
('34459', '1', 'In a medium saucepan, bring the water to a boil with the ginger.'),
('34459', '2', 'Add the bean sprouts and cook for 5 seconds; drain and discard the ginger. Rinse the bean sprouts and drain again.'),
('34459', '3', 'Warm a wok over high heat for 45 seconds.'),
('34459', '4', 'Add the peanut oil and swirl to coat the wok. Stir in the salt and garlic and cook for 10 seconds.'),
('34459', '5', 'Add the carrots and stir-fry for 2 1/2 minutes.'),
('34459', '6', 'Add the cucumber, and stir-fry for 1 minute.'),
('34459', '7', 'Add the bean sprouts and stir-fry for 10 seconds. Turn off the heat and stir in the sesame oil.'),
('34459', '8', 'Serve at once.'),
('34460', '1', 'In a large saucepan, cover the chicken breasts with water and bring to a gentle simmer. Cook over moderately low heat until the chicken is white throughout, about 12 minutes.'),
('34460', '2', 'Transfer the poached chicken breasts to a plate and let stand until cooled slightly, about 10 minutes.'),
('34460', '3', 'Meanwhile, in a small bowl, whisk the mayonnaise with the rice vinegar, wasabi powder, Asian sesame oil and 1 1/2 tablespoons of water and season with salt and pepper.'),
('34460', '4', 'In a large serving bowl, toss the lettuce with the Asian pear slices, cucumber, scallions, bean sprouts and 2/3 cup of the wasabi dressing. Slice the chicken breasts crosswise  1/4 inch thick and lay the slices on top of the salad. Spoon the remaining wasabi dressing over the chicken breasts, sprinkle with the chopped wasabi peas and serve at once.'),
('34463', '1', 'Preheat a grill pan. Rub the steaks with the oil and season with salt and pepper. Grill over high heat, turning once, until an instant-read thermometer inserted in the thickest part registers 125, about 12 minutes.'),
('34463', '2', 'Let rest for 10 minutes before slicing thinly.'),
('34463', '3', 'Meanwhile, in a small skillet, heat the water with the sugar, stirring until dissolved.'),
('34463', '4', 'Transfer to a large bowl.'),
('34463', '5', 'Add the garlic, fish sauce, lime juice and sambal and let cool.'),
('34463', '6', 'Add the cucumber, onion, bean sprouts, mint and sliced steak and toss well. Sprinkle with the peanuts and serve right away, with lime wedges.'),
('34465', '1', 'Whisk together fish sauce, sugar, lime juice, garlic, red pepper flakes and, last, water. Set aside.'),
('34465', '2', 'Place noodles in a large bowl in sink; cover them with hot water and let stand for 10 minutes. Meanwhile, bring a large pot of water to a boil.'),
('34465', '3', 'Drain noodles and add to pot; cook, stirring, until tender, 3 to 4 minutes.'),
('34465', '4', 'Drain and rinse with cold water until cool.'),
('34465', '5', 'Transfer noodles to a large salad bowl.'),
('34465', '6', 'Add chicken and remaining ingredients; toss well.'),
('34465', '7', 'Pour half of dressing on salad and toss again.'),
('34465', '8', 'Add more dressing as desired.'),
('34467', '1', 'To prepare peanut sauce, combine 1/4 cup water, 1 tablespoon brown sugar, 3 tablespoons peanut butter, 1 teaspoon Sriracha, and 1 teaspoon soy sauce in a medium bowl, stirring well with a whisk. Set aside.'),
('34467', '2', 'To prepare stir-fry, combine 2 teaspoons sugar, 5 teaspoons soy sauce, 1 teaspoon Sriracha, and garlic in a small bowl, stirring with a whisk.'),
('34467', '3', 'Heat a large heavy skillet over medium-high heat.'),
('34467', '4', 'Add 1 tablespoon sesame oil to pan, swirling to coat.'),
('34467', '5', 'Add tempeh and half of soy sauce mixture; stir-fry for 5 minutes or until tempeh is golden brown.'),
('34467', '6', 'Remove tempeh mixture from pan, and keep warm.'),
('34467', '7', 'Add remaining 2 teaspoons oil to pan, swirling to coat.'),
('34467', '8', 'Add carrot, bell pepper, and green beans to pan; stir-fry 3 minutes.'),
('34467', '9', 'Add 1/2 cup water; reduce heat to medium. Cover and simmer for 5 minutes or until beans are crisp-tender. Stir in remaining half of soy sauce mixture, tempeh mixture, half of onions, and bean sprouts; cook for 2 minutes or until sprouts are tender.'),
('34467', '10', 'Serve with peanut sauce and remaining half of onions.'),
('34467', '11', 'Wine Match: Hogue Late Harvest Riesling ($1'),
('34467', '12', 'has a seductive touch of sweetness from dense peach and apricot notes to balance the spicy Sriracha. At the same time, its tangy acidity cuts through the rich flavors of peanut butter and sesame oil. --Jeffery Lindenmuth'),
('34472', '1', 'Heat oil or lard in a wok over medium heat until shimmering.'),
('34472', '2', 'Add the crushed chilies and Sichuan pepper and stirfry until oil is spicy and fragrant, about 10 seconds, taking care not to burn the spices.'),
('34472', '3', 'Add pickled vegetables and stir-fry 20 to 30 seconds longer.'),
('34472', '4', 'Add minced meat and soy sauce and cook meat until it''s lightly browned and crisp, about 1 minute.'),
('34472', '5', 'Transfer mixture to small bowl and set aside.'),
('34472', '6', 'Bring large pot of water to boil. Blanch bean sprouts for 30 seconds, remove from pot with slotted spoon, and rinse briefly under cold running water. Set aside. Cook noodles according to package directions in same pot.'),
('34472', '7', 'While noodles are cooking, combine sichuan peppercorns, sesame paste, soy sauce, and chili oil. Set aside.'),
('34472', '8', 'Drain noodles and toss with meat topping. You may add spoonfuls of the sauce to individual serving bowls, or keep on the table for your diners to add at their own discretion.'),
('34474', '1', 'In a heatproof bowl, cover the wakame with the boiling water and let stand until softened, about 15 minutes.'),
('34474', '2', 'Drain the wakame and press to remove any excess water.'),
('34474', '3', 'Toast the sesame seeds in a small skillet over moderate heat, stirring, for 3 minutes. In a medium bowl, whisk the rice vinegar with the soy sauce and ginger.'),
('34474', '4', 'Whisk in the peanut and sesame oils. Season with salt and cayenne.'),
('34474', '5', 'Add the tofu to the dressing and let stand for 5 minutes.'),
('34474', '6', 'Transfer the tofu to a small plate.'),
('34474', '7', 'Add the edamame, bean sprouts and wakame to the dressing and toss to coat. Fold in the tofu.'),
('34474', '8', 'Transfer to a serving bowl, sprinkle with the sesame seeds and serve.'),
('34476', '1', 'Prepare grill to medium-high heat.'),
('34476', '2', 'To prepare pork, combine first 6 ingredients in a large zip-top plastic bag; seal. Marinate in refrigerator 1 hour, turning occasionally.'),
('34476', '3', 'Remove pork from bag; discard marinade. Sprinkle pork evenly with salt and black pepper.'),
('34476', '4', 'Place pork on grill rack coated with cooking spray. Grill 22 minutes or until a thermometer registers 155, turning occasionally.'),
('34476', '5', 'Remove from heat; let stand 10 minutes.'),
('34476', '6', 'Cut into 1/2-inch-thick slices; cut each slice into thin strips, and keep warm.'),
('34476', '7', 'To prepare salad, combine carrot and next 7 ingredients (through jalapeo) in a medium bowl; toss well.'),
('34476', '8', 'Place about 1 1/2 ounces pork on each of 8 lettuce leaves; top each serving evenly with 1/4 cup mango mixture and 2 tablespoon bean sprouts.'),
('34478', '1', 'Bring a large pot of water to a boil. Meanwhile, put the cellophane noodles in a large bowl and cover with warm water.'),
('34478', '2', 'Let the noodles stand until pliable, about 20 minutes; drain. Using scissors, cut the noodles into 6-inch lengths.'),
('34478', '3', 'In a small skillet, toast the sesame seeds over moderately high heat, stirring, until golden, about 1 minute.'),
('34478', '4', 'Transfer to a plate. In a small bowl, whisk the soy sauce with the honey and sesame oil.'),
('34478', '5', 'Add the cellophane noodles to the boiling water and cook until al dente, about 3 minutes; drain. Return the noodles to the pot, fill it with cold water, then drain again.'),
('34478', '6', 'Transfer the noodles to a large bowl.'),
('34478', '7', 'Add the jicama, carrots, scallions, cucumber, jalapeo and bean sprouts and toss again.'),
('34478', '8', 'Add the soy sauce dressing and toss to coat. Season with salt and pepper and transfer to a platter. Sprinkle the salad with the peanuts and toasted sesame seeds and serve.'),
('34480', '1', 'Cook the noodles according to the directions on the package.'),
('34480', '2', 'Drain and rinse the noodles and place in a bowl.'),
('34480', '3', 'Add the sesame oil and toss to coat.'),
('34480', '4', 'Combine all the sauce ingredients in a bowl and stir to mix.'),
('34480', '5', 'Heat a heavy skillet or wok over medium-high heat, add the vegetable oil, and when hot, add the ginger, garlic, and chile and stir-fry for a couple of minutes.'),
('34480', '6', 'Add the broth, and when simmering, add the greens and cook until done.'),
('34480', '7', 'Add the mushrooms and mung beans and cook for a couple of minutes.'),
('34480', '8', 'Stir the sauce into the vegetable mixture, add the noodles, and toss to coat and reheat.'),
('34480', '9', 'Put the noodles into a bowl, garnish with toasted sesame seeds, and serve.'),
('34480', '10', 'var article'),
('34480', '11', 'Type_27_data = {};'),
('34480', '12', 'article'),
('34480', '13', 'Type_27_data.init_step_by_step_images = 0;'),
('34483', '1', 'Bring the water to a boil in a large saucepan.'),
('34483', '2', 'Put the bean sprouts in a strainer, lower it into the boiling water and blanch the bean sprouts for 10 seconds.'),
('34483', '3', 'Remove the strainer and rinse the sprouts in cold water; drain well.'),
('34483', '4', 'Add the salt to the water in the saucepan and bring it back to a boil.'),
('34483', '5', 'Add the noodles and cook, stirring, for 1 minute.'),
('34483', '6', 'Drain the noodles thoroughly in a colander and rinse them in cold water; drain. Rinse again then drain, lifting them to separate and dry the strands.'),
('34483', '7', 'In a small bowl, combine the chicken stock with the soy sauce and sesame oil to make the sauce.'),
('34483', '8', 'Warm a wok over high heat for 45 seconds.'),
('34483', '9', 'Add the peanut oil and swirl to coat the wok. Stir in the ginger and cook for 10 seconds.'),
('34483', '10', 'Add the snow peas and stir-fry until bright green, about 1 minute.'),
('34483', '11', 'Add the water chestnuts and stir-fry for 30 seconds.'),
('34483', '12', 'Add the bean sprouts and stir-fry for 1 minute.'),
('34483', '13', 'Stir the sauce, add it to the wok and bring to a boil.'),
('34483', '14', 'Add the noodles and stir-fry until they absorb the sauce, about 1 1/2 minutes.'),
('34483', '15', 'Transfer the noodles to a platter and serve at once.'),
('34486', '1', 'In a small bowl, combine the stock, soy sauce, mustard, vinegar, sesame oil and chili oil.'),
('34486', '2', 'In a large pot of boiling water, blanch the carrot for 1 minute. Using a slotted spoon, transfer the carrot to a plate.'),
('34486', '3', 'Add the noodles to the pot and cook, stirring, until they are al dente, about 5 minutes.'),
('34486', '4', 'Drain the noodles and return them to the pot. Fill the pot with cold water and swish the noodles to cool them.'),
('34486', '5', 'Drain and repeat.'),
('34486', '6', 'Transfer the cooled noodles to a colander and lift them occasionally with your fingers to help dry them out.'),
('34486', '7', 'Meanwhile, in a large, deep skillet, heat the vegetable oil until shimmering.'),
('34486', '8', 'Add the pork slices in a single layer, season with salt and pepper and cook over high heat, without stirring, until browned on the bottom, about 2 minutes. Stir a few times, then add the ginger and stir-fry over moderately high heat until fragrant, about 2 minutes.'),
('34486', '9', 'Add the bell pepper and carrot and stir-fry for 1 minute.'),
('34486', '10', 'Add the noodles to the skillet and toss until well combined.'),
('34486', '11', 'Add the soy sauce mixture, shiso, scallions and bean sprouts and toss until heated through.'),
('34486', '12', 'Transfer to a large, shallow bowl and serve.'),
('34488', '1', 'Stir cornstarch and 1 tablespoon cold water in small bowl to blend.'),
('34488', '2', 'Mix in soy sauce, sugar, and sesame oil.'),
('34488', '3', 'Blanch bean sprouts in large pot of boiling salted water 10 seconds. Using large slotted skimmer or sieve, transfer sprouts to colander. Rinse under cold water to cool quickly.'),
('34488', '4', 'Add noodles to same pot of boiling water and cook until just tender but still firm to bite, about 5 minutes.'),
('34488', '5', 'Drain well; rinse with cold water and drain again, tossing to release as much water as possible.'),
('34488', '6', 'Heat 1 tablespoon peanut oil in heavy large wok or skillet over medium-high heat.'),
('34488', '7', 'Add ginger, garlic, and minced green onions. Sauté 1 minute.'),
('34488', '8', 'Add carrots, snow peas, and pork. Stir-fry until carrots are just crisp-tender, about 2 minutes.'),
('34488', '9', 'Mix in bean sprouts, noodles, and green onion tops. Stir-fry 1 minute. Stir cornstarch mixture to reblend and add to wok. Cook until sauce thickens, stirring often, about 2 minutes. Season with salt and pepper.'),
('34488', '10', 'Transfer noodle mixture to large bowl and cool. (Can be made 2 hours ahead.'),
('34488', '11', 'Let stand at room temperature.)'),
('34488', '12', 'Heat 2 tablespoons peanut oil in heavy large nonstick skillet over medium heat.'),
('34488', '13', 'Add noodle mixture. Cook until bottom of noodle cake is brown and crusty, occasionally pressing to compact and shaking pan to prevent sticking, about 5 minutes. Turn cake out onto rimless baking sheet, browned side up.'),
('34488', '14', 'Add remaining 1 tablespoon oil to skillet and heat. Slide noodle cake back into skillet, browned side up. Cook until bottom is brown and crusty, about 6 minutes. Slide noodle cake out onto platter.'),
('34488', '15', 'Cut into wedges and serve.'),
('34488', '16', '*Thin, spaghetti-like noodles, available at Asian markets and in the Asian foods section of many supermarkets.'),
('34489', '1', 'Preparing Bibimbap Ingredients: Start by making the marinated tofu, the quick-pickled cucumber and then cook the rice.'),
('34489', '2', 'Cut the carrots and daikon into very thin sticks, then slice the mango and cut the nori into thin strips. Set aside in separate bowls.'),
('34489', '3', 'Add olive oil to a large frying pan on medium heat, add the spinach and let cook for a few minutes, stirring occasionally. When done, transfer to a bowland set aside. Wipe the frying pan clean, add a dash of olive oil then fry the mushrooms on medium heat for 7-8 minutes, stirring occasionally. When done, transfer to a bowland set aside. Wipe the pan clean again,then fry the eggs on one side on low heat, you want to keep the yolk loose.Assembling Bibimbap: You can either make 1 very large bowl or 4 smaller bowls.'),
('34489', '4', 'Place the rice in a bowl, then place tofu, carrots, daikon, mango, nori, cucumber, mushroom, kimchi, spinach, sprouts in small portions around the rice, sprinkle with sesame seeds and top with an egg and a dollop of Gochujang sauce. Stir around, using your chopsticks, before eating.Enjoy!Share'),
('34489', '5', 'Email'),
('34489', '6', 'Pinterest'),
('34489', '7', 'Facebook'),
('34489', '8', 'Twitter'),
('34489', '9', 'Google'),
('34489', '10', 'Print'),
('34489', '11', 'Related'),
('34490', '1', 'Bring the water to a boil.'),
('34490', '2', 'Remove from the heat, add the rice noodles and let soak until the noodles are tender, about 7 minutes.'),
('34490', '3', 'Drain well.'),
('34490', '4', 'In a small bowl, stir together the soy sauce, white wine, sugar and chili oil.'),
('34490', '5', 'In a large skillet or a wok with a handle, heat the oil.'),
('34490', '6', 'Add the kohlrabi and cook over moderately high heat until browned, about 3 minutes. Stir and cook for 1 minute.'),
('34490', '7', 'Add the red pepper and garlic and stir-fry until the garlic is fragrant, about 2 minutes.'),
('34490', '8', 'Add the eggs; stir-fry until just set, about 30 seconds.'),
('34490', '9', 'Add the rice noodles, bean sprouts, scallions, basil and the soy sauce mixture. Cook over moderately low heat, tossing gently, until the noodles are heated through and coated with sauce, about 1 minute.'),
('34490', '10', 'Transfer the noodles to plates or bowls and serve at once.'),
('34491', '1', 'Simmer peppercorns, vinegar, and sugar in a small saucepan over low heat until reduced by half, about 18 minutes. Stir in ketchup, then strain. Chill until ready to use.'),
('34491', '2', 'Drop noodles into a bowl of very hot water.'),
('34491', '3', 'Let sit, stirring occasionally, until soft and clear, about 4 minutes.'),
