INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('29045', '2', 'Cut each artichoke in half from the bottom to the top, then use a spoon to scrape out the hairy choke. Rinse again to remove any residual hairs.'),
('29045', '3', 'Melt the butter in a large skillet over medium heat.'),
('29045', '4', 'Add the garlic, and saute for about 1 minute to flavor the butter. Arrange artichoke halves cut-side down in the skillet.'),
('29045', '5', 'Saute for about 5 or 10 minutes, or until lightly browned. Reduce heat to low, and pour in about 1/4 cup of water, cover, and let steam for 15 to 20 minutes, or until the artichokes are tender. A fork should easily pierce the stem.'),
('29049', '1', 'In a large bowl, combine lemon juice and 2 quarts cold water. Slice off top halves of artichokes and discard. break off and discard outer leaves down to tender, pale green inner ones. Trim off and discard stem ends. With a small, sharp knife, pare off dark green fibrous skin from artichoke bottoms and remaining stems.'),
('29049', '2', 'Cut artichokes in half lengthwise. scoop out and discard fuzzy centers and any thorny petals.'),
('29049', '3', 'Cut each artichoke half in half again lengthwise and drop into lemon water.'),
('29049', '4', 'Peel onions. cut in half lengthwise, then slice lengthwise into 1/4-inch-thick slivers. Rinse fennel. trim off and discard stalks and root ends. Reserve a few leafy sprigs for garnish if desired.'),
('29049', '5', 'Cut heads lengthwise into about 1/4-inch-thick matchsticks. Shell peas. Rinse lettuce well and trim off and discard core. cut leaves into 3-inch lengths.'),
('29049', '6', 'Drain artichokes. In a 5- to 6-quart pan over medium-high heat, frequently stir artichokes, onions, and fennel in olive oil until onions are limp, 7 to 8 minutes.'),
('29049', '7', 'Add 5 cups water and bring to a boil over high heat. cover, reduce heat, and simmer, stirring occasionally, until artichokes are tender when pierced, 12 to 18 minutes.'),
('29049', '8', 'Add peas. bring mixture to a boil over high heat and cook until peas are tender when pierced, 2 to 3 minutes. Stir in lettuce and cook until barely wilted, about 30 seconds.'),
('29049', '9', 'Add salt and pepper to taste. Ladle stew into bowls and garnish with reserved fennel sprigs. Sprinkle with cheese to taste.'),
('29050', '1', 'Put broth, 2 cups water, 2 tsp. salt, bay leaves, half of the thyme sprigs, the garlic, and peppercorns in a large pot. Halve 1 of the lemons, squeeze juice from both halves into pot, and drop in juiced rinds.'),
('29050', '2', 'Working with 1 artichoke at a time, snap off outer leaves (about half of it. be ruthless) down to the yellowish core. Trim 1/2 in. from leaf points and trim stem to about 1/2 in. Drop into broth mixture.'),
('29050', '3', 'Bring artichokes in broth mixture almost to a boil. Reduce heat and simmer, covered, until leaves are tender when pierced with a sharp knife, 20 to 30 minutes.'),
('29050', '4', 'Let cool to room temperature, covered. then chill overnight and up to 3 days.'),
('29050', '5', 'Let artichokes come to room temperature (about 1 hour).'),
('29050', '6', 'Drain artichokes, cut them in half lengthwise, and remove cooked thyme sprigs. Divide artichokes and mozzarella balls among serving plates, drizzle with olive oil, and sprinkle with salt and pepper. With a zester or a Microplane, shred about 1 tsp. zest from remaining lemon and scatter over plates along with remaining thyme sprigs.'),
('29050', '7', 'Serve with red-pepper pine nut aioli and crusty bread.'),
('29054', '1', 'Cut artichoke bottoms crosswise into 3/8-inch-thick slices, then cut stems diagonally into 3/8-inch-thick slices.'),
('29054', '2', 'Transfer slices to a 1 1/2- to 2-quart baking dish and set aside.'),
('29054', '3', 'Cook haricots verts in a 3- to 4-quart pot of boiling salted water, uncovered, until crisp-tender, about 4 minutes.'),
('29054', '4', 'Drain in a sieve and transfer to a bowl of ice and cold water to stop cooking.'),
('29054', '5', 'Drain and pat dry, then toss with artichokes in baking dish.'),
('29054', '6', 'Cut a 1-inch chunk from spiced butter log, then cut chunk into bits. Dot vegetables with butter, then cover with plastic wrap and set aside until ready to bake.'),
('29055', '1', 'Squeeze the lemon juice into a medium bowl of water. add the lemon. Working with 1 artichoke at a time, snap off the tough outer leaves. Using a sharp knife, cut off the yellow leaves at the top of the heart and all but 1 inch of the stem. trim the dark green stubs and fibers from the artichoke bottom and stem. Using a melon baller or spoon, scoop out the furry choke. Thinly slice the artichoke heart and put it in the acidulated water.'),
('29055', '2', 'Drain the artichokes and put them in a saucepan.'),
('29055', '3', 'Add the heavy cream and garlic and cook over moderately low heat until the artichokes are tender and the cream thickens, about 15 minutes. add a few tablespoons of water if the cream gets too thick. Using a slotted spoon, transfer the artichokes to a food processor and puree until smooth.'),
('29055', '4', 'Transfer to a bowl and stir in the mascarpone, goat cheese and a generous pinch each of salt and pepper. Refrigerate until chilled.'),
('29055', '5', 'In a food processor, pulse the flour, semolina, oil and salt to combine.'),
('29055', '6', 'Add the eggs and process just until the mixture resembles wet crumbs.'),
('29055', '7', 'Transfer the dough to a board and knead until silky, about 1 minute. Wrap the dough in plastic and let rest at room temperature for 30 minutes.'),
('29055', '8', 'Cut the dough into 4 pieces. Using a hand-cranked pasta machine, roll 1 piece of the dough through successively narrower settings until you reach the thinnest setting. Lay the pasta sheet on a work surface and cover with a kitchen towel. Repeat with the remaining dough, layering it between towels. Using a 2 1/4-inch round biscuit cutter, cut out rounds from the dough sheets and arrange them without touching between layers of plastic wrap.'),
('29055', '9', 'Working with 6 rounds at a time, brush each one lightly with water. Set a heaping 1/4 teaspoon of the filling in the center of each round and fold the dough over to form half-moons. Crimp and seal the edges, pressing out the air. Arrange the agnolotti in a single layer, without touching, on a baking sheet dusted with semolina. Continue making agnolotti with the remaining dough and filling.'),
('29055', '10', 'In a medium nonstick saucepan, boil the Chicken Stock and thyme sprigs until reduced to 1/4 cup. discard the thyme. Reduce the heat to low and whisk in the butter. Season with salt and white pepper and remove from the heat.'),
('29055', '11', 'In a large pot of boiling salted water, cook the agnolotti, stirring gently, until just al dente, about 2 minutes.'),
('29055', '12', 'Drain the agnolotti and add them to the saucepan, turning to coat with the sauce. Sprinkle with the Parmesan. Using a slotted spoon, transfer the agnolotti to 4 shallow soup plates and spoon any sauce on top.'),
('29055', '13', 'Garnish with the truffle shavings and serve.'),
('29061', '1', 'Heat olive oil and butter in a large pan over medium heat until butter melts.'),
('29061', '2', 'Add carrots and turnips, and saut, stirring occasionally, about 8 minutes or until golden brown.'),
('29061', '3', 'Add radishes, asparagus, and tarragon, and saut 1 to 2 minutes, stirring occasionally. Stir in remaining ingredients. Cover, reduce heat to low, and simmer 2 to 3 minutes or until liquid is thickened slightly and vegetables are tender.'),
('29061', '4', 'Serve immediately.'),
('29063', '1', 'Preheat oven to 35'),
('29063', '2', 'Combine all ingredients except 1/2 cup of cheddar cheese. Spoon into a 2-quart casserole, then top with remaining 1/2 cup of cheese.'),
('29063', '3', 'Bake for 35 minutes or until dip is hot. Dip, dip hooray!'),
('29063', '4', 'Spanakopita Dip: Substitute feta cheese for the cheddar and omit artichoke hearts. Spoon into mini phyllo cups and bake 8 minutes or until filling puffs.'),
('29065', '1', 'Adjust oven rack to middle position and preheat oven to 350 F.'),
('29065', '2', 'Combine artichokes, mayonnaise, Parmesan cheese, garlic, Worcestershire sauce and salt in medium bowl.  Spoon into 1-quart casserole dish.'),
('29065', '3', 'Bake 30 minutes until hot a bubbly. Sprinkle with parsley and chopped tomatoes.'),
('29065', '4', 'Serve with crackers or toasted bread slices.'),
('29069', '1', 'Place lettuce in a serving bowl. Top with chickpeas, artichoke hearts, roasted red peppers, tomato, olives, provolone, mozzarella and pepperoni.'),
('29069', '2', 'Drizzle with oil and vinegar and serve.'),
('29073', '1', 'Process the onion, Garlic-Ginger Paste, and tomatoes in a food processor or blender until smooth.'),
('29073', '2', 'Meanwhile, warm the oil in a large skillet over medium-high heat. Once the oil is shimmering, add the cumin seeds. Once they''re done popping, add the onion-tomato paste you just made, and saute until it thickens and deepens in color, about 10 minutes.'),
('29073', '3', 'Add the ground coriander, garam masala, paprika, and turmeric and saute about 30 seconds. Then add the yogurt, a little at a time so it doesn''t curdle. Stir in the lime juice, chickpeas, artichokes, salt, to taste, and water. Cover and simmer 10 minutes. Taste for seasonings and serve garnished with cilantro.'),
('29073', '4', 'Throw the garlic, ginger, and canola oil in a mini-food processor and let it go until it forms a semi-smooth paste. There will still be tiny little pieces in there, but overall, it should resemble a paste.'),
('29073', '5', 'Save what you don''t use in a small glass jar. It should last in the fridge for 2 to 3 weeks. It''s a delicious addition to marinades, pasta sauces, stir fry sauces, slow-cooker recipes, gravy etc. We always had a jar of this stuff in our fridge growing up.'),
('29074', '1', 'In a medium saucepan, heat the 1 tablespoon of olive oil.'),
('29074', '2', 'Add the bacon and cook over moderate heat until the fat is rendered, about 3 minutes.'),
('29074', '3', 'Add the onion, carrot and garlic and cook, stirring occasionally, until the vegetables are slightly softened, about 4 minutes.'),
('29074', '4', 'Add the water, wine, lemon juice, thyme leaves and bay leaf, cover and simmer until the onion and carrot are tender, about 10 minutes.'),
('29074', '5', 'Add the green beans and artichokes, cover and cook until tender, about 3 minutes. Season with salt and pepper. Discard the bay leaf.'),
('29074', '6', 'Add the parsley and transfer to bowls.'),
('29074', '7', 'Serve with a drizzle of olive oil.'),
('29078', '1', 'In a large, heavy skillet, heat the oil over medium heat.'),
('29078', '2', 'Add the orange zest and red pepper and let the mixture sizzle for 30 seconds.'),
('29078', '3', 'Add the broccoli and cook, stirring occasionally, for 5 minutes or until tender. Sprinkle with the salt.'),
('29086', '1', 'Heat broiler. Cook the pasta according to the package directions. Meanwhile, heat the butter in a large pot over medium heat.'),
('29086', '2', 'Add the flour and cook, stirring, for 2 minutes.'),
('29086', '3', 'Whisk in the milk and cook, stirring occasionally, until slightly thickened, 4 to 5 minutes.'),
('29086', '4', 'Add 1 1/2 cups of the cheese and stir until melted. Stir in the nutmeg, 3/4 teaspoon salt, and 14 teaspoon pepper.'),
('29086', '5', 'Add the pasta and broccoli and toss to combine.'),
('29086', '6', 'Transfer to a broilerproof 8-inch square or another 1 1/2-quart baking dish. Sprinkle with the remaining 12 cup of cheese. Broil until golden, 3 to 4 minutes.'),
('29092', '1', 'Whirl the bread in a food processor or blender to make bread crumbs. Melt the butter in a small skillet.'),
('29092', '2', 'Add the bread crumbs and saut over medium heat until toasted. Grate the zest from the lemon.'),
('29092', '3', 'Cut the lemon in half and squeeze the juice from one half into the pan.'),
('29092', '4', 'Add the salt and several grinds of black pepper and cook, stirring constantly, until dry. (The Lemon Crumbs can be made to this point up to 2 days ahead. Spoon into a plastic bag and set aside at room temperature.)'),
('29092', '5', 'Microwave the broccoli according to the package directions. (If using fresh broccoli, pile the florets on a microwave-safe plate and sprinkle with a few tablespoons of water. Cover with plastic wrap and microwave 3 to 5 minutes or until crisp-tender.)'),
('29092', '6', 'Remove and sprinkle with the Lemon Crumbs.'),
('29092', '7', 'Time-saver: Cook the broccoli florets right in their microwavable bag. No waiting for water to boil. And, again, no extra pot to clean.'),
('29094', '1', 'Arrange broccoli in a steamer basket over boiling water. Cover and steam 4 minutes or until crisp-tender. Plunge broccoli into ice water to stop the cooking process. drain.'),
('29094', '2', 'Heat butter in a large nonstick skillet over medium heat 2 to 3 minutes or until melted.'),
('29094', '3', 'Add broccoli, pecans, salt, and pepper. Cook, stirring gently, 2 to 3 minutes or until thoroughly heated.'),
('29103', '1', 'Arrange broccoli in a steamer basket over boiling water. Cover, and steam 5 minutes or until crisp-tender.'),
('29103', '2', 'Arrange broccoli in a lightly greased 11- x 7-inch baking dish.'),
('29103', '3', 'Pour Pimiento Cheese Sauce evenly over broccoli.'),
('29103', '4', 'Combine breadcrumbs, melted butter, and Parmesan cheese. sprinkle evenly over cheese sauce.'),
('29103', '5', 'Bake at 375 for 20 minutes or until thoroughly heated.'),
('29107', '1', 'In a small skillet, melt 1/2 tablespoon of the butter over low heat.'),
('29107', '2', 'Add the pecans and saut until lightly browned, 2 to 3 minutes.'),
('29107', '3', 'Transfer to a plate to cool.'),
('29107', '4', 'Steam the broccoli until just tender, about 3 minutes.'),
('29107', '5', 'Drain well and toss with the remaining 3 tablespoons of butter and the salt. Mound the broccoli on plates or in bowls and sprinkle the pecans on top. Arrange a slice of prosciutto alongside and serve.'),
('29110', '1', 'In a 10- to 12-inch nonstick frying pan over medium-high heat, cook sausage patties in a single layer, turning once, until well browned on both sides and no longer pink in the center, about 8 minutes total.'),
('29110', '2', 'Transfer to paper towels to drain.'),
('29110', '3', 'Return pan to medium heat.'),
('29110', '4', 'Add oil, onion, and garlic and cook until onion is limp and starting to brown, 5 to 8 minutes.'),
('29110', '5', 'Add broccoli. cook 2 to 3 minutes.'),
('29110', '6', 'Add wine and sprinkle with salt and pepper. Cover and simmer, stirring occasionally, until broccoli is tender when pierced, 4 to 6 minutes.'),
('29110', '7', 'Gently stir in sausage and tomatoes and cook just until hot, about 1 minute. Sprinkle with parmesan cheese.'),
('29111', '1', 'Cook the broccoli in lightly salted boiling water until crisp-tender, 2 to 4 minutes.'),
('29111', '2', 'Drain. Melt the butter in a skillet over medium heat.'),
('29111', '3', 'Add the bread crumbs and thyme. Toast until golden, then remove from heat.'),
('29111', '4', 'Add the Parmesan, broccoli, and a few grinds of pepper. Toss.'),
('29116', '1', 'Place chicken breasts between 2 sheets of plastic wrap, and flatten to 1/4-inch thickness, using a rolling pin or flat side of a meat mallet. Thinly slice chicken.'),
('29116', '2', 'Whisk together broth, 2 tablespoons cornstarch, hot chili sauce, sugar, and vinegar.'),
('29116', '3', 'Place broccoli and 2 tablespoons water in a microwave-safe bowl. Cover with plastic wrap. fold back a small edge to allow steam to escape. Microwave at HIGH 1 minute.'),
('29116', '4', 'Combine chicken and soy sauce in a medium bowl. toss with remaining 2 tablespoons cornstarch to coat.'),
('29116', '5', 'Melt buttery spread in a 12-inch nonstick skillet over medium-high heat. add chicken, and cook, stirring occasionally, 3 minutes or until done.'),
('29116', '6', 'Transfer chicken to a serving platter. keep warm.'),
('29116', '7', 'Bring broth mixture to a boil in skillet over high heat, stirring frequently. Reduce heat to low, and simmer, stirring occasionally, 1 minute or until thickened.'),
('29116', '8', 'Add broccoli, and toss to coat. Cook 1 minute or until thoroughly heated.'),
('29116', '9', 'Pour sauce over chicken.'),
('29116', '10', 'Serve immediately.'),
('29118', '1', 'Bring a large pot of salted water to a boil.'),
('29118', '2', 'Add the broccoli and cook for 2 minutes.'),
('29118', '3', 'Drain well.'),
('29118', '4', 'In a large skillet, heat the olive oil.'),
('29118', '5', 'Add the garlic and cook over moderately high heat, stirring, until lightly golden, about 2 minutes.'),
('29118', '6', 'Add the broccoli florets and cook, stirring frequently, until just starting to brown, about 5 minutes.  Sprinkle the hot sauce over the broccoli and season with salt and pepper. Toss well to coat, then serve.'),
('29120', '1', 'Arrange broccoli in a steamer. Steam, covered, 4 minutes or until crisp-tender.'),
('29120', '2', 'Place broccoli in a large bowl.'),
('29120', '3', 'Whisk 1/4 cup beer and flour in a bowl.'),
('29120', '4', 'Combine milk and 1/4 cup beer in a pan. bring to a simmer. Stir in flour mixture. bring to a boil. Reduce heat. simmer 2 minutes.'),
('29120', '5', 'Add cheddar, chives, lemon rind, and kosher salt.'),
('29120', '6', 'Pour over broccoli.'),
('29121', '1', 'Grate 1 orange to equal 1 teaspoon grated rind. set aside. Peel and section oranges, removing seeds. set aside.'),
('29121', '2', 'Place broccoli florets in a steamer basket over boiling water, and cook 3 to 4 minutes or until crisp-tender.'),
('29121', '3', 'Melt butter in a nonstick skillet over medium-high heat. add onion and ginger, and saut until tender.'),
('29121', '4', 'Remove from heat.'),
('29121', '5', 'Toss together broccoli florets, onion mixture, 1 teaspoon orange rind, and orange sections in a large bowl. Stir in yogurt.'),
('29121', '6', 'Serve immediately.'),
('29122', '1', 'Arrange broccoli in a steamer. Steam, covered, 4 minutes or until crisp-tender.'),
('29122', '2', 'Place broccoli in a large bowl.'),
('29122', '3', 'Combine minced shallots, olive oil, lemon juice, Dijon mustard, and chopped fresh thyme in a bowl. stir with a whisk.'),
('29122', '4', 'Add broccoli and pine nuts to oil mixture. toss.'),
('29125', '1', 'Cut broccoli into 1 1/2-inch florets. Peel stems, cut in half lengthwise, and cut into 1/2-inch-thick slices on the diagonal.'),
('29125', '2', 'Combine balsamic vinegar, garlic, olive oil, 1/2 teaspoon salt, and 1/4 teaspoon pepper in a bowl, whisking well.'),
('29125', '3', 'Add 1/2 teaspoon salt to a pot of boiling water.'),
('29125', '4', 'Add broccoli stems to pot and cook for 2 minutes.'),
('29125', '5', 'Add broccoli florets to pot and cook for another minute, or until bright green. Rinse and drain.'),
('29125', '6', 'Combine the broccoli, sun-dried tomatoes, pine nuts, and balsamic mixture. toss well. Sprinkle 1/4 teaspoon each of salt and pepper on salad. drizzle with Champagne vinegar.'),
('29129', '1', 'Heat oil in a large nonstick skillet coated with cooking spray.'),
('29129', '2', 'Add broccoli and garlic. Saut 6 to 8 minutes or until crisp-tender.'),
('29129', '3', 'Remove broccoli mixture. keep warm.'),
('29129', '4', 'Add broth and next 4 ingredients to pan. Bring to a boil. Cook 3 minutes or until liquid is reduced to 1/4 cup.'),
('29129', '5', 'Add broccoli mixture, and cook 1 minute or until thoroughly heated.'),
('29134', '1', 'Combine the first 6 ingredients in a medium bowl. cover and chill for 1 hour.'),
('29134', '2', 'Combine water and next 4 ingredients (water through salt) in a small bowl. set aside.'),
('29134', '3', 'Heat oil in a stir-fry pan or wok over medium-high heat.'),
('29134', '4', 'Add broccoli. stir-fry 2 minutes.'),
('29134', '5', 'Add shrimp mixture. stir-fry 5 minutes or until shrimp are done.'),
('29134', '6', 'Add cornstarch mixture, and bring to a boil. Cook 1 minute or until sauce thickens.'),
('29134', '7', 'Serve over soba noodles.'),
('29137', '1', 'Cook the broccoli in lightly salted boiling water until crisp-tender, 2 to 4 minutes.'),
('29137', '2', 'Drain.'),
('29137', '3', 'Add the butter and garlic to the saucepan and cook until the garlic is softened, 1 to 2 minutes. Toss with the salt and a few grinds of pepper.'),
('29142', '1', 'In a large, deep saucepan, bring 1 inch of water to a boil. Fill a steamer basket with the broccoli, add it to the saucepan, cover and steam over high heat until the broccoli is crisp-tender, about 5 minutes.'),
('29142', '2', 'Transfer the broccoli to a platter.'),
('29142', '3', 'Meanwhile, in a saucepan, melt the butter.'),
('29142', '4', 'Add the flour and whisk over moderately high heat for 2 minutes.'),
('29142', '5', 'Add the milk and cream and cook, whisking, until thickened, about 2 minutes.'),
('29142', '6', 'Add the mustard and cheese and cook over moderately low heat until the cheese is melted. Season the sauce with salt, transfer to a bowl and serve with the broccoli.'),
('29149', '1', 'Watch how to make this recipe.'),
('29149', '2', 'Trim the woody skin off the broccoli stem and slice the broccoli into nice long "trees". In a large saucepan, mix the water, olive oil, garlic, red pepper flakes, salt, and pepper. Bring to a boil over high heat.'),
('29149', '3', 'Add the broccoli and cover to steam. After 3 minutes, turn off the heat, and allow the broccoli to sit for another couple of minutes. Toss to coat and serve.'),
('29151', '1', 'Trim and discard the thick stems from the broccoli.'),
('29151', '2', 'Cut the florets from the remaining stems, then peel the stems and cut into thin slices.'),
('29151', '3', 'Bring a large saucepan of salted water to a boil over high heat.'),
('29151', '4', 'Add the broccoli and blanch for 1 minute, then rinse under cold running water to stop the cooking and drain thoroughly.'),
('29151', '5', 'Heat the oil in a wok or large skillet over high heat.'),
('29151', '6', 'Add the garlic and stirfry quickly until fragrant and very lightly browned, about 15 seconds.'),
('29151', '7', 'Add the broccoli, oyster sauce, fish sauce, and vinegar and stir-fry until heated through and a light sauce has formed, about 45 seconds.'),
('29151', '8', 'Serve immediately.'),
('29151', '9', 'var article'),
('29151', '10', 'Type_27_data = {}.'),
('29151', '11', 'article'),
('29151', '12', 'Type_27_data.init_step_by_step_images = 0.'),
('29155', '1', 'Arrange broccoli in a steamer. Steam, covered, 4 minutes or until crisp-tender.'),
('29155', '2', 'Place broccoli in a large bowl.'),
('29155', '3', 'Heat a small skillet over medium-high heat.'),
('29155', '4', 'Add oil and garlic. cook 2 minutes or until garlic is fragrant.'),
('29155', '5', 'Add oil mixture, rind, juice, and salt to broccoli. toss to coat. Sprinkle broccoli mixture with cheese.'),
('29155', '6', 'Spicy Chile and Garlic variation: Prepare base recipe through step'),
('29155', '7', 'Heat a skillet over medium-high.'),
('29155', '8', 'Add 2 tablespoons olive oil, 1 1/2 teaspoons crushed red pepper, and 4 sliced garlic cloves. cook 2 minutes.'),
('29155', '9', 'Add 1 tablespoon lemon juice.'),
('29155', '10', 'Pour over broccoli. Sprinkle with 1 teaspoon grated lemon rind and 1/4 teaspoon kosher salt.'),
('29155', '11', 'Serves 6 Calories 61. Fat 8g (sat 7g). Sodium 96mg'),
('29155', '12', 'Dijon, Thyme, and Pine Nut variation: Prepare base recipe through step'),
('29155', '13', 'Combine 1 tablespoon minced shallots, 2 tablespoons olive oil, 1 tablespoon fresh lemon juice, 1 tablespoon Dijon mustard, and 2 teaspoons chopped fresh thyme in a bowl. stir with a whisk.'),
('29155', '14', 'Add broccoli and 2 tablespoons toasted pine nuts to oil mixture. toss.'),
('29155', '15', 'Serves 6 Calories 79. Fat 6g (sat 8g). Sodium 76mg'),
('29157', '1', 'Place noodles in a bowl of very hot water and let stand.'),
('29157', '2', 'Place 1/2 cup milk in a bowl, whisk in cornstarch and set aside. Microwave remaining milk at full power for 2 minutes.'),
('29157', '3', 'Melt butter in a heavy saucepan over medium heat.'),
('29157', '4', 'Add onion and cook for 5 minutes.'),
('29157', '5', 'Add flour and whisk to make a paste. Gradually whisk in hot milk.'),
('29157', '6', 'Whisk cornstarch and milk into hot sauce. Bring to a boil, whisking. continue to whisk for 2 minutes.'),
('29157', '7', 'Remove from heat. stir in Cheddar, salt and pepper.'),
('29157', '8', 'Remove 1 cup cheese sauce and set aside.'),
('29157', '9', 'Let remaining sauce cool in pot.'),
('29157', '10', 'Cook ground round over medium heat until browned.'),
('29157', '11', 'Transfer beef with a slotted spoon to cheese sauce in pot. stir in broccoli.'),
('29157', '12', 'In a small bowl, mix bread crumbs, olive oil and parsley. Preheat oven to 400F.'),
('29157', '13', 'Butter a 9-inch square baking dish. Lay 1 noodle on a work surface. top with 1/2 cup beef mixture and roll up. transfer to dish. Repeat with remaining noodles. Spoon Cheddar sauce on rolls and sprinkle breadcrumb mixture on top.'),
('29157', '14', 'Bake until bubbly, 15 to 20 minutes.'),
('29159', '1', 'Preheat the oven to 45'),
('29159', '2', 'In a small saucepan, melt the butter over low heat. Skim off the foam from the surface of the butter.'),
('29159', '3', 'Remove from the heat.'),
('29159', '4', 'In a food processor, pulse the bread to coarse crumbs.'),
('29159', '5', 'Transfer the crumbs to a small cookie sheet, toss with 1 teaspoon of the olive oil and season lightly with salt and pepper.'),
('29159', '6', 'Bake for about 2 minutes, until golden brown.'),
('29159', '7', 'On a large rimmed baking sheet, toss the broccoli with the remaining 2 tablespoons of olive oil. season with salt and pepper. Arrange the broccoli in an even layer and roast for about 15 minutes, until just tender and starting to brown.'),
('29159', '8', 'Meanwhile, in a medium saucepan, bring 1 inch of water to a simmer. In a stainless steel bowl, mix the egg yolks with the tablespoon of boiling water. Set the bowl over the saucepan and whisk the yolks constantly until thickened slightly and bright yellow, about 1 minute.'),
('29159', '9', 'Remove from the heat.'),
('29159', '10', 'Gently reheat the butter. very gradually, whisk it into the yolks until a slightly thick sauce forms.'),
('29159', '11', 'Whisk in the lemon juice and a dash of Tabasco and season the hollandaise sauce lightly with salt and pepper.'),
('29159', '12', 'Whisk in the mint and thyme.'),
('29159', '13', 'Transfer the broccoli to a platter. pour the hollandaise sauce on top. Sprinkle with the bread crumbs and serve.'),
('29170', '1', 'Place flour in a medium saucepan. Gradually add milk, stirring constantly with a whisk until smooth. Cook over medium-high heat 2 minutes or until mixture is bubbly and thickened, stirring constantly. Cook 1 additional minute, stirring constantly.'),
('29170', '2', 'Remove from heat.'),
('29170', '3', 'Add cheeses, mustard, salt, pepper, and thyme, stirring with a whisk until smooth. Keep warm.'),
('29170', '4', 'Add water to a large saucepan to a depth of 1 inch. set a large vegetable steamer in pan. Bring water to a boil over medium-high heat.'),
('29170', '5', 'Add broccoli to steamer. Steam broccoli, covered, 4 minutes or until crisp-tender.'),
('29170', '6', 'Serve broccoli immediately with sauce.'),
('29172', '1', 'Watch how to make this recipe.'),
('29172', '2', 'Cook the broccoli for 3 minutes in a large pot of boiling salted water.'),
('29172', '3', 'Remove the broccoli from the water with a slotted spoon or sieve.'),
('29172', '4', 'Place in a large bowl and set aside.'),
('29172', '5', 'In the same water, cook the bow-tie pasta according to the package directions, about 12 minutes.'),
('29172', '6', 'Drain well and add to the broccoli.'),
('29172', '7', 'Meanwhile, in a small saute pan, heat the butter and oil and cook the garlic and lemon zest over medium-low heat for 1 minute. Off the heat, add 2 teaspoons salt, the pepper, and lemon juice and pour this over the broccoli and pasta. Toss well. Season to taste, sprinkle with the pignolis and cheese, if using, and serve.'),
('29172', '8', 'To toast pignolis, place them in a dry saute pan over medium-low heat and cook, tossing often, for about 5 minutes, until light brown.'),
('29174', '1', 'Peel broccoli stems, then coarsely chop stems and florets. Cook broccoli in boiling salted water (1 1/2 teaspoons salt for 4 quarts water) until just tender, 4 to 6 minutes.'),
('29174', '2', 'Drain in a colander and run under cold water to stop cooking.'),
('29174', '3', 'Simmer cream, garlic, nutmeg, 1/4 teaspoon salt, and 1/8 teaspoon pepper in a medium saucepan, uncovered, until slightly thickened and reduced to about 2/3 cup, about 5 minutes.'),
('29174', '4', 'Add broccoli and simmer, mashing with a potato masher, until coarsely mashed and heated through, about 2 minutes.'),
('29174', '5', 'Remove from heat and stir in parmesan and lemon juice.'),
('29175', '1', 'Steam the broccoli or simply boil it for 3 mins. Make a rough paste by pounding or blending the garlic, ginger and coriander stems together.'),
('29175', '2', 'Pour the oil into a hot wok or frying pan.'),
('29175', '3', 'Add the paste, then turn up the heat to full and sizzle for 1 min. Tip in the cooked broccoli, toss well and sprinkle over the sesame seeds. Turn off the heat, throw in the coriander and basil leaves, give it a stir and serve.'),
('29176', '1', 'Place the salt in a large pot of water and bring to a boil.'),
('29176', '2', 'Add the fettuccine and cook according to the package directions for al dente. During the last 3 minutes of cooking, add the broccoli.'),
('29176', '3', 'Drain in a colander, reserving 1 cup of the water. set aside.'),
('29176', '4', 'Place the butter in the pot, reduce heat to medium-low, and stir until melted.'),
('29176', '5', 'Add  cup of the reserved pasta water, then stir in 1/3 cup of the Parmesan.'),
('29176', '6', 'Add the fettuccine and broccoli and the cayenne and nutmeg, if desired. toss.'),
('29176', '7', 'Remove from heat and sprinkle with another 1/3 cup of the Parmesan and the pepper. Toss again, adding more pasta water if the fettuccine is too sticky.'),
('29176', '8', 'Serve in bowls and sprinkle with the remaining Parmesan.'),
('29177', '1', 'In a medium saucepan, heat 1 tablespoon of the oil.'),
('29177', '2', 'Add the walnuts and cook over moderate heat, stirring frequently, until browned, about 4 minutes.'),
('29177', '3', 'Transfer the walnuts to a plate with a slotted spoon.'),
('29177', '4', 'Add another tablespoon of the oil to the saucepan.'),
('29177', '5', 'Add the garlic, season with pepper and cook over low heat, stirring occasionally, until golden, about 4 minutes.'),
('29177', '6', 'Add the 1 tablespoon of the reserved honey. cook over moderate heat, stirring, until deeply browned, 1 minute.'),
('29177', '7', 'Add the soy sauce and simmer until slightly reduced, about 4 minutes. Stir in the lemon juice and remove the garlic-caramel sauce from the heat.'),
('29177', '8', 'In a large skillet, heat the remaining 1 tablespoon of oil.'),
('29177', '9', 'Add the broccoli, cover and cook over moderate heat for 3 minutes. Uncover, add the shrimp and chiles and cook, stirring a few times, just until the shrimp are pink and curled. Stir in the garlic-caramel sauce, sprinkle the walnuts on top and serve.'),
('29181', '1', 'Melt butter in a Dutch oven over medium-high heat. add bell pepper and next 3 ingredients, and saut 4 to 5 minutes or until tender.'),
('29181', '2', 'Add potatoes and cumin, and saut 5 minutes or until browned and tender. Gradually stir in broth, stirring to loosen particles from bottom of Dutch oven. Bring to a boil. cover, reduce heat to low, and simmer 25 minutes.'),
('29181', '3', 'Whisk together flour and next 2 ingredients. Stir into potato mixture, and cook over medium heat, stirring constantly, 5 minutes or until thickened. Reduce heat to low.'),
('29181', '4', 'Add cheeses, and cook, stirring constantly, until cheeses melt and mixture is thoroughly heated.'),
('29181', '5', 'Place broccoli in a 1-qt. microwave-safe glass bowl. Cover tightly with plastic wrap. fold back a small edge to allow steam to escape. Microwave at HIGH 3 to 4 1/2 minutes or until broccoli is crisp-tender, stirring after 2 minutes.'),
('29181', '6', 'Drain and pat dry. Stir hot broccoli into chowder. Top each serving with sauteed chopped ham.'),
('29181', '7', '*Monterey Jack cheese may be substituted.'),
('29181', '8', 'Note: We tested with Simply Potatoes Southwest Style Hash Browns.'),
('29183', '1', 'Toast sesame seeds in heavy small skillet over medium heat until golden, about 5 minutes. Set aside 1 tablespoon toasted sesame seeds.'),
('29183', '2', 'Place remaining sesame seeds in spice grinder.'),
('29183', '3', 'Add salt and 1/2 teaspoon crushed red pepper. grind coarsely. Set sesame-red pepper mixture aside.'),
('29183', '4', 'Steam broccoli until crisp-tender, about 7 minutes.'),
('29183', '5', 'Transfer to large bowl.'),
('29183', '6', 'Add oil, 1 tablespoon reserved sesame seeds, remaining 1/4 teaspoon crushed red pepper, and 2 teaspoons sesame-red pepper mixture. toss to combine.'),
('29183', '7', 'Serve, passing remaining sesame-red pepper mixture separately.'),
('29187', '1', 'Place broccoli florets in a steamer basket over boiling water, and cook 7 minutes or until crisp-tender.'),
('29187', '2', 'Meanwhile, in a medium skillet, bring vinegar and shallots to a boil. reduce heat, simmer 7 minutes or until vinegar is almost absorbed.'),
('29187', '3', 'Remove from heat. add butter, a few pieces at a time, stirring constantly with a wire whisk until butter melts and sauce thickens. Stir in parsley, salt, and pepper. Toss with steamed broccoli.'),
('29187', '4', 'Fix it Faster: Buy broccoli crowns to save a step in the kitchen.'),
('29198', '1', 'In a large, deep skillet, heat 2 tablespoons of the olive oil.'),
('29198', '2', 'Add the broccoli, cut side down, cover and cook over moderate heat until richly browned on the bottom, about 8 minutes.'),
('29198', '3', 'Add the water, cover and cook until the broccoli is just tender and the water has evaporated, about 7 minutes.'),
('29198', '4', 'Add the remaining 1 tablespoon of olive oil along with the garlic and the crushed red pepper and cook uncovered until the garlic is golden brown, about 3 minutes. Season the broccoli with salt and black pepper, drizzle with the lemon juice and serve.'),
('29203', '1', 'Heat oven to 500 F. Toss the broccoli and sweet potato with the oil and water in a shallow roasting pan.'),
('29203', '2', 'Place in the oven and roast 20 minutes, turning occasionally, until browned.'),
('29203', '3', 'Add the pear and roast until the vegetables are tender, about 10 minutes more.'),
('29203', '4', 'Remove from oven and toss with the salt and pepper.'),
('29208', '1', 'Preheat oven to 42'),
('29208', '2', 'Cook broccoli in boiling water 1 minute.'),
('29208', '3', 'Drain and plunge into ice water. drain.'),
('29208', '4', 'Combine 1 1/2 teaspoons rind, juice, 1/4 teaspoon salt, and 1/4 teaspoon black pepper in a medium bowl.'),
('29208', '5', 'Add shrimp. toss to combine. Arrange broccoli and shrimp in a single layer on a jelly-roll pan coated with cooking spray.'),
('29208', '6', 'Bake at 425 for 8 minutes or until shrimp are done.'),
('29208', '7', 'Combine oil, remaining 1 1/2 teaspoons rind, remaining 1/4 teaspoon salt, remaining 1/4 teaspoon black pepper, and crushed red pepper in a large bowl.'),
('29208', '8', 'Add broccoli. toss to combine.'),
('29211', '1', 'Toast pine nuts in a large skillet over medium heat 6 minutes or until lightly browned.'),
('29211', '2', 'Remove from skillet, and set aside.'),
('29211', '3', 'Heat butter and oil in same skillet over medium heat until butter melts.'),
('29211', '4', 'Add garlic, and saut 1 to 2 minutes or until lightly browned.'),
('29211', '5', 'Add broccoli, salt, and crushed red pepper. Saut 8 minutes or until broccoli is tender. Stir in pine nuts before serving.'),
('29214', '1', 'Preheat oven to 350 degrees. Spray 5 quart glass baking dish with vegetable spray.'),
('29214', '2', 'Combine cooked pasta, margarine, and 1 cup shredded cheddar in baking dish. In another bowl combine eggs, soup and broth.'),
('29214', '3', 'Pour 1/2 of the soup mixture over pasta and cheese. Top with broccoli.'),
('29214', '4', 'Combine mozzarella and remaining cheddar cheese and sprinkle over broccoli.'),
('29214', '5', 'Pour rest of soup mixture over cheese.'),
('29214', '6', 'Bake for 30 minutes until hot and bubbly. Top with red pepper flakes, if desired. Ready in 45 minutes, recipe by Eggland''s Best Nutritional Information'),
('29214', '7', 'Per Serving: Calories 371. Fat 14g (8% calories from fat). Protein 19g. Carbohydrates 45g. Dietary Fiber 2g. Cholesterol 57mg. Sodium 563 mg.'),
('29216', '1', 'Prick the potatoes several times with a fork. Microwave on high until tender and a fork easily slides into the center, 12 to 15 minutes.'),
('29216', '2', 'Transfer the potatoes to a bowl and cover with a plate or foil to keep warm. In a medium microwave-proof bowl, combine the broccoli, butter, 1/2 teaspoon salt, and 1/4 teaspoon pepper. Microwave on high for 3 minutes, stir once, then microwave until hot, 3 to 4 minutes more. Split the potatoes (be careful of the steam). Top with the broccoli mixture and sour cream and sprinkle with 1/4 teaspoon pepper.'),
('29220', '1', 'Watch how to make this recipe.'),
('29220', '2', 'Put a pot of water on to boil. Prepare a large bowl of ice water.'),
('29220', '3', 'Cut the broccoli into florets. When the water is boiling, add the broccoli. Cook for 30 seconds. Immediately drain and add them to the bowl of ice water. When cool, drain well.'),
('29220', '4', 'In a large skillet over medium heat, add the olive oil. When it is warm, add the garlic and cook for 1 minute until toasted, do not let it burn.'),
('29220', '5', 'Add the broccoli, toss to coat with the oil and garlic, and season with salt and pepper, to taste.'),
('29220', '6', 'Add the chicken stock and hot chili sauce, raise the heat to high, and cook until the broccoli is just tender, about 2 minutes.'),
('29220', '7', 'Serve immediately with grilled shrimp, if using.'),
('29221', '1', 'Grate 1 orange to equal 1 teaspoon grated rind. set aside. Peel and section oranges, removing seeds. set aside.'),
('29221', '2', 'Place broccoli florets in a steamer basket over boiling water, and cook 3 to 4 minutes or until crisp-tender.'),
('29221', '3', 'Melt butter in a nonstick skillet over medium-high heat. add onion and ginger, and saut until tender.'),
('29221', '4', 'Remove from heat.'),
('29221', '5', 'Toss together broccoli florets, onion mixture, 1 teaspoon orange rind, and orange sections in a large bowl. Stir in yogurt.'),
('29221', '6', 'Serve immediately.'),
('29222', '1', 'Cook the pasta according to the package directions.'),
('29222', '2', 'Drain and return the pasta to the pot.'),
('29222', '3', 'Add the steamed broccoli, pine nuts, Brie, 3/4 teaspoon salt, and 1/2 teaspoon pepper. Stir until the cheese melts. Divide among individual bowls.Tip: The Brie''s rind adds a rich, earthy flavor to the pasta, but you can omit it if you prefer. You can also try fontina or Taleggio instead of Brie.'),
('29223', '1', 'Preheat oven to 350 degrees.'),
('29223', '2', 'Place crackers into a large ziploc bag and crush slightly, leaving some large chunks. Set aside.Plunge broccoli into boiling water and allow to boil for 1 minute. Strain and set aside.'),
('29223', '3', 'Cut Velveeta into chunks. Throw into a large pot with milk, cream, salt, pepper, and cayenne. Melt, stirring occasionally, until totally smooth. Stir in Dijon if using.'),
('29223', '4', 'Add broccoli to cheese sauce, then add half the cracker crumbs. Stir to combine, then pour mixture into a buttered 9 x 13 inch baking dish. Top with remaining cracker crumbs, then sprinkle the top generously with black pepper.'),
('29223', '5', 'Bake for 15 to 20 minutes, or until top is golden brown and casserole is bubbly.'),
('29224', '1', 'Melt butter in a pot over medium heat, then add the onions. Cook the onions for 3 to 4 minutes, then sprinkle the flour over the top. Stir to combine and cook for 1 minute or so, then pour in milk and half-and-half.'),
('29224', '2', 'Add nutmeg, then add broccoli, a small dash of salt, and plenty of black pepper. Cover and reduce heat to low. Simmer for 20 to 30 minutes, or until the broccoli is tender. Stir in cheese and allow to melt. Taste seasonings and adjust if needed. Then either serve as is, or mash it with a potato masher to break up the broccoli a bit, or transfer to a blender in two batches and puree completely. (If you puree it in a blender, return it to the heat and allow to heat up. Splash in chicken broth if needed for thinning.)Enjoy!'),
('29229', '1', 'Cook broccoli in boiling water 1 min.  Rinse with cold water. drain well.'),
('29229', '2', 'Toss broccoli with dressing, raisins, onions and lemon peel in large bowl. cover.'),
('29229', '3', 'Refrigerate at least 30 min.  Sprinkle with pecans just before serving.'),
('29230', '1', 'Marinate the beef: Stir together the beef marinade ingredients (1 teaspoon soy sauce, 1 teaspoon Chinese rice wine, 1/2 teaspoon cornstarch, 1/8 teaspoon black pepper) in a medium bowl.'),
('29230', '2', 'Add the beef slices and stir until coated.'),
('29230', '3', 'Let stand for 10 minutes.'),
('29230', '4', 'Prepare the sauce: Stir together the sauce ingredients (2 Tbsp oyster sauce, 1 teaspoon Chinese rice wine, 1 teaspoon soy sauce, 1/4 cup chicken broth) in a small bowl.'),
('29230', '5', 'Blanch or steam the broccoli: Bring a pot of water to a boil.'),
('29230', '6', 'Add the broccoli and cook until tender-crisp, about 2 minutes.'),
('29230', '7', 'Drain thoroughly.'),
('29230', '8', 'Stir-fry the beef: '),
('29230', '9', 'Heat a large frying pan or wok over high heat until a bead of water sizzles and instantly evaporates upon contact.'),
('29230', '10', 'Add the cooking oil and swirl to coat.'),
('29230', '11', 'Add the beef and immediately spread the beef out all over the surface of the wok or pan in a single layer (preferably not touching).'),
('29230', '12', 'Let the beef fry undisturbed for 1 minute. Flip the beef slices over, add the garlic to the pan and fry for an additional 30 seconds to 1 minute until no longer pink.'),
('29235', '1', 'Heat oil in large nonstick skillet on medium-high heat.'),
('29235', '2', 'Add garlic. cook and stir 30 sec. or until tender.'),
('29235', '3', 'Add broccoli and olives. cook and stir 4 min. or until heated through.'),
('29235', '4', 'Remove from heat.'),
('29235', '5', 'Stir in grated topping.'),
('29237', '1', 'Heat oil in large skillet on medium-high heat.'),
('29237', '2', 'Add chicken. cook 5 min. on each side or until lightly browned on both sides.'),
('29237', '3', 'Add water and the Pasta.  Bring to boil. cover.  Simmer on medium-low heat 4 min.'),
('29237', '4', 'Add broccoli. cover.  Cook 6 min. or until pasta and broccoli are tender and most of  liquid is absorbed.'),
('29237', '5', 'Stir in contents of pouch and Cheese Sauce until blended.'),
('29243', '1', 'Separate broccoli into 6 portions. set aside.  Stack 5 of the turkey slices, with slices slightly overlapping.  Repeat with remaining turkey slices to make a total of 6 turkey stacks.  Top each with a portion of broccoli. roll up.'),
('29243', '2', 'Place, seam sides down, in 12x8-inch microwavable dish.  Spoon CHEEZ WHIZ evenly over roll-ups. cover with  microwavable plastic wrap.'),
('29243', '3', 'Microwave on HIGH 8 minutes or until broccoli is crisp-tender and roll-ups are heated through.'),
('29243', '4', 'Let stand, covered, 5 minutes.'),
('29248', '1', 'Heat 2 tablespoons oil in heavy large skillet over medium heat.'),
('29248', '2', 'Add fennel seeds and stir until toasted, about 3 minutes.'),
('29248', '3', 'Add shallots and saute until golden, about 3 minutes.'),
('29248', '4', 'Add sliced fennel bulb and red bell pepper and saute until just tender, about 3 minutes.'),
('29248', '5', 'Add broccoli.'),
('29248', '6', 'Drizzle remaining 2 tablespoons oil over vegetables. Stir in herbes de Provence.'),
('29248', '7', 'Pour broth over. Simmer until broccoli is crisp-tender and liquid evaporates, about 6 minutes. Season with salt and pepper.'),
('29248', '8', '*A dried herb mixture available at specialty foods stores and in the spice section of some supermarkets. A combination of dried thyme, basil, savory, and fennel seeds can be substituted.'),
('29271', '1', 'Preheat oven to 35'),
('29271', '2', 'In a 5- to 6-quart pan over high heat, bring about 3 quarts water to a boil. Rinse broccoli and trim off and discard tough stem ends. if skin on stalks is tough, peel stalks.'),
('29271', '3', 'Cut broccoli into 1-inch pieces.'),
('29271', '4', 'Add to boiling water and cook just until barely tender when pierced, 3 to 5 minutes.'),
('29271', '5', 'Drain.'),
('29271', '6', 'Rinse and dry pan.'),
('29271', '7', 'Add 1/4 cup butter to pan and melt over medium heat. Stir in flour and salt until smoothly blended. cook until bubbly, about 1 minute.'),
('29271', '8', 'Add milk and stir over medium-high heat until mixture is boiling and thickened, about 3 minutes.'),
('29271', '9', 'Add cream cheese and gorgonzola. whisk until smoothly blended. Stir in broccoli.'),
('29271', '10', 'Pour into a shallow 2 1/2- to 3-quart casserole.'),
('29271', '11', 'In a blender or food processor, whirl bread cubes into coarse crumbs. you should have about 1 1/3 cups. In a small bowl, mix crumbs with 1 tablespoon melted butter. Sprinkle evenly over broccoli mixture.'),
('29271', '12', 'Bake until casserole is hot in the center and crumbs are golden, 20 to 30 minutes.'),
('29276', '1', 'Melt butter in a saucepan over medium-high heat. Stir in onion, and cook until the onion has begun to turn golden brown, about 5 minutes. Meanwhile, place broccoli in a steamer over 1 inch of boiling water, and cover. Cook until tender but still firm, about  6 minutes.'),
('29276', '2', 'Drain.'),
('29276', '3', 'When the onions have turned golden brown, remove the saucepan from the heat, and whisk in the sour cream, vinegar, sugar, poppy seeds, paprika, salt, and cayenne pepper.'),
('29276', '4', 'Place the cooked broccoli into a serving dish, and pour the sauce overtop. Sprinkle with chopped pecans to serve.'),
('29282', '1', 'Place the broccoli into a large pot with about 1 inch of water in the bottom. Bring to a boil, and cook for 7 minutes, or until tender but still crisp.'),
('29282', '2', 'Drain, and arrange broccoli on a serving platter.'),
('29282', '3', 'While the broccoli is cooking, melt the butter in a small skillet over medium heat.'),
('29282', '4', 'Mix in the brown sugar, soy sauce, vinegar, pepper and garlic. Bring to a boil, then remove from the heat.'),
('29282', '5', 'Mix in the cashews, and pour the sauce over the broccoli.'),
('29282', '6', 'Serve immediately.'),
('29284', '1', 'Cook the pasta according to the package directions. Reserve 1 cup of the cooking water, drain the pasta, and return it to the pot. Meanwhile, heat the oil in a skillet over medium-high heat.'),
('29284', '2', 'Add the garlic and cook, stirring, until golden, 1 to 2 minutes.'),
('29284', '3', 'Add the broccoli, red pepper, and 1 teaspoon salt. Cook until heated through, 1 to 2 minutes.'),
('29284', '4', 'Add the broccoli mixture, lemon juice, Parmesan, and the reserved pasta water to the pasta. Cook over medium heat, stirring, until combined and heated through, 2 to 3 minutes. Sprinkle with the lemon zest and serve.'),
('29285', '1', 'Combine steak sauce, soy sauce and garlic in shallow nonmetal dish.'),
('29285', '2', 'Add steak. toss to coat.  Cover. refrigerate 30 min. to marinate, stirring occasionally.'),
('29285', '3', 'Remove steak from marinade. reserve marinade.'),
('29285', '4', 'Heat oil in large skillet on medium-high heat.'),
('29285', '5', 'Add steak. cook and stir 3 to 4 min. or until no longer pink.'),
('29285', '6', 'Remove steak from skillet with slotted spoon. cover to keep warm.'),
('29285', '7', 'Mix vegetables and reserved marinade in same skillet.  Bring to boil.  Reduce heat to medium-low. cover.  Simmer 2 to 3 min. or until heated through.'),
('29285', '8', 'Add steak. mix lightly.'),
('29285', '9', 'Serve over rice.'),
('29286', '1', 'Preheat oven to 350F.'),
('29286', '2', 'Place 6 of the crackers on bottom of 1-1/2-quart casserole dish. set aside.'),
('29286', '3', 'Mix broccoli, mayo, cheese, almonds, pimientos and mustard.  Spoon into casserole dish. stand remaining 10 crackers around outside edge of dish.'),
('29286', '4', 'Bake 30 minutes or until heated through.'),
('29289', '1', 'Preheat oven to 400 degrees F (200 degrees C). Line a baking sheet with aluminum foil.'),
('29289', '2', 'Spread broccoli in a single layer on the prepared baking sheet. Sprinkle onion and sage leaves over broccoli. drizzle with olive oil. Sprinkle salt, garlic salt, and black pepper over broccoli mixture. toss to coat.'),
('29289', '3', 'Roast in the preheated oven until broccoli is browned and crisp, 20 to 30 minutes.'),
('29293', '1', 'Cook and stir chicken in large skillet sprayed with cooking spray on medium-high heat 2 to 3 min. or until evenly browned.'),
('29293', '2', 'Add broccoli, soup and water. stir.  Bring to boil.'),
('29293', '3', 'Stir in rice. sprinkle with cheese.  Cover. simmer on low heat 5 min.'),
('29294', '1', 'This Sweet ''n Smoky Tofu Cashew Broccoli Bowl is one of my favorite one-bowl wonder sort of meals. It is really very simple. A grain, veggie, nut, tofu and lively citrus accent. But it plates up quite stunningly with the thick triangle tofu and pops of color.Flavors. Sticky sweet blackened tofu is flavored with citrus, tamari, pepper, maple and liquid smoke. Crunchy pan-toasted cashews are also wrapped in sticky sweet flavors. A savory bed of golden couscous studded with sweet golden raisins blankets your bowl - or substitute with quinoa or rice if you''d prefer. And that cheezy broccoli adds the perfect green accent to this healthy feast. Citrus notes throughout. Rich in protein, fiber and complex carbohydrates - this colorful vegan bowl is one to cuddle up to...Couscous Quinoa or Rice will work .. but some nights I just love whole wheat couscous because it cooks up so quickly, yet has a fine, rice-like texture that pairs well with hearty ingredients like broccoli, nuts and tofu steaks.On the Side. This bowl is happy to welcome a dollop of garlic hummus, chili hummus or a drizzle of your favorite hot sauce. Protein. And yes, you could sub in a different protein too - tempeh or even some beans would be lovely!Sweet and Smoky Tofu Cashew Broccoli Bowlserves about 4, vegan'),
('29294', '2', 'Tofu:1 lb firm or silken tofu, sliced into thick triangles1 1/2 Tbsp safflower oil1 Tbsp tamari1 Tbsp maple syrup (or agave)2 Tbsp orange juice + pinch of zest (I used mandarins)1 tsp liquid smokefine black pepper to taste1/2 tsp garlic powder'),
('29294', '3', 'Broccoli:2 cups broccoli florets1 tsp safflower oil1/4 cup veggie broth2 Tbsp nutritional yeast (optional for cheezy flavor)Golden Couscous (you may have leftovers!):2 cups dried whole wheat couscous1/2 cup sweet onion, chopped1 cup water1 cup veggie broth2 Tbsp extra virgin olive oil1/4 tsp salt1/3 cup golden raisins (optional)1-3 Tbsp nutritional yeast (optional)3/4 cup raw cashewsgarnish: orange slices'),
('29297', '1', 'Arrange broccoli in a serving dish. Season with salt and pepper.'),
('29297', '2', 'Pour melted butter over broccoli, and sprinkle with Parmesan cheese.'),
('29297', '3', 'Place under broiler for 2 minutes or until cheese is golden brown.'),
('29298', '1', 'Cut a 1-inch-wide strip from the top of each baked potato. Carefully scoop out pulp, leaving shells intact.'),
('29298', '2', 'Mash pulp. Stir in broccoli and next 6 ingredients. Spoon into shells, and place on a baking sheet.'),
('29298', '3', 'Bake, covered, at 400 for 30 minutes.'),
('29304', '1', 'Wash and peel the potato and cut it into very thin shavings using a speed peeler.'),
('29304', '2', 'Cut little broccoli florets off the head and put them to one side.  Halve the thin stalk lengthwise, then slice thinly.  Pick the basil leaves and discard the stalks.'),
('29304', '3', 'Bring a large pan of salted water to a boil.'),
('29304', '4', 'Add the tagliatelle and broccoli stalks and cook according to the tagliatelle package instructions.  Two minutes before the the tagliatelle is cooked, add the broccoli and potato slices.'),
('29304', '5', 'Drain everything in a colander over a large bowl, reserving some of the  cooking water, and return to the pan.  Roughly chop half of your basil leaves and add to the pan with the pesto and half of the Parmesan.  Give it all a good stir and if the sauce is too thick for you, add a splash of the cooking water to thin it out a bit.'),
('29304', '6', 'Divide the pasta between your serving bowls.  Sprinkle over the rest of the Parmesan and the remaining basil leaves.'),
('29304', '7', 'Serve it a lovely big bowl of salad.'),
('29306', '1', 'Whisk together first 3 ingredients in a large bowl. gradually whisk in oil.'),
('29306', '2', 'Add broccoli slaw, apple, and raisins. toss well to coat. Cover and chill 3 hours.'),
('29307', '1', 'Rinse broccoli. Trim off leaves and stem ends.'),
('29307', '2', 'Cut crowns into 1- to 1 1/2-inch florets, and thinly slice stalks crosswise.'),
('29307', '3', 'In a 5- to 6-quart pan over high heat, bring about 3 quarts water to a boil.'),
('29307', '4', 'Add pasta and cook, uncovered, stirring occasionally, until barely tender to bite, 7 to 10 minutes.'),
('29307', '5', 'Meanwhile, in an 11- to 12-inch frying pan over medium-low heat, stir garlic, ginger, and cumin in peanut oil until garlic is soft, 3 to 5 minutes. Increase heat to medium.'),
('29307', '6', 'Add broccoli and 1/4 cup water. Cover and cook just until broccoli is tender-crisp to bite, about 2 minutes.'),
('29307', '7', 'In a small bowl, mix coconut milk, tahini, soy sauce, and sesame oil.'),
('29307', '8', 'Add to broccoli mixture. stir often just until simmering.'),
('29307', '9', 'Drain pasta and return to pan. Gently stir in broccoli mixture. Spoon into a serving bowl.'),
('29307', '10', 'Serve with hot sauce, lime wedges, and salt to add to taste.'),
('29309', '1', 'Bring broccoli and broth to boil in medium saucepan on medium-high heat.'),
('29309', '2', 'Add rice. stir.  Cover.'),
('29309', '3', 'Remove from heat. let stand 5 min.'),
('29309', '4', 'Stir in VELVEETA. let stand, covered, 5 min.   Stir until VELVEETA is melted.'),
('29310', '1', 'Microwave broccoli and water in microwaveable bowl on HIGH 5 min. or until broccoli is crisp-tender. drain.'),
('29310', '2', 'Toss broccoli with dressing and cheese.'),
('29311', '1', 'Mix cream cheese and dressing until well blended.  Spoon evenly over pepper slices.'),
('29311', '2', 'Top evenly with broccoli.'),
('29312', '1', 'After roasting a chicken, remove it from the roasting pan and place on a serving tray to rest. Leave the oven on.'),
('29312', '2', 'Pour off excess drippings from the roasting pan, leaving just enough to coat the broccoli. Toss broccoli and garlic in the drippings until coated and place in the still hot oven. Roast for 5 to 8 minutes, until tender.'),
('29316', '1', 'Combine all ingredients except broccoli in microwaveable bowl.'),
('29316', '2', 'Microwave on HIGH 3 min. or until VELVEETA is completely melted, stirring after each minute.'),
('29316', '3', 'Pour over broccoli.'),
('29316', '4', 'Serve immediately.'),
('29317', '1', 'Place broccoli in 10x6-inch baking dish. drizzle with dressing.  Sprinkle with cracker pieces.'),
('29317', '2', 'Bake at 375F for 15 minutes or until heated through.'),
('29318', '1', 'Cook spaghetti as directed on package, adding broccoli to the cooking water for the last 6 minutes of the spaghetti cooking time.'),
('29318', '2', 'Meanwhile, microwave CHEEZ WHIZ as directed on label.'),
('29318', '3', 'Drain spaghetti. place in large bowl.'),
('29318', '4', 'Add CHEEZ WHIZ. toss until spaghetti is evenly coated.'),
('29327', '1', 'Microwave vegetables in microwaveable bowl covered with waxed paper on HIGH 3 min.'),
('29327', '2', 'Add dressing. mix lightly.  Microwave, covered, 1 to 2 min. or until vegetables are crisp-tender.'),
('29327', '3', 'Stir in nuts.'),
('29329', '1', 'Heat salted water for pasta: Fill a large 8-quart stock pot at least half full with water and with 2 Tbsp of salt. bring to a boil.'),
('29329', '2', 'Blanch broccoli: While the water is the large stockpot is heating, bring a smaller saucepan (2-3 quarts) half filled with water to a boil. Blanch the broccoli in the boiling water for 1 minute.'),
('29329', '3', 'Remove from heat.'),
('29329', '4', 'Drain and run the broccoli under cold water to stop the cooking. Set aside.'),
('29329', '5', 'Cook and drain pasta: Cook the pasta in the large pot of boiling water according to the directions on the package (anywhere from 3 to 12 minutes, depending on the type of pasta you have) until al dente, or still slightly firm.'),
('29329', '6', 'Drain and toss with a little olive oil to keep from sticking.'),
('29329', '7', 'Make the sauce: While the pasta is cooking, combine the cream, wine, garlic, and black pepper in a large skillet and bring to a simmer over high heat. Reduce the heat to medium and simmer for 7 to 10 minutes until the mixture thickens.'),
('29340', '1', 'Preheat the oven to 45'),
('29340', '2', 'In a heatproof medium bowl, cover the anchos with boiling water and let stand until softened, about 20 minutes.'),
('29340', '3', 'Drain the chiles and pat dry. Discard the stems and seeds, then coarsely chop.'),
('29340', '4', 'Meanwhile, in a small skillet, heat 2 tablespoons of the olive oil until shimmering.'),
('29340', '5', 'Add the pine nuts and cook over moderately high heat, stirring constantly, until lightly browned, about 3 minutes.'),
('29340', '6', 'Add the garlic, cumin and coriander and cook, stirring, until the garlic is softened and the pine nuts are deep golden, about 1 minute longer.'),
('29340', '7', 'Let cool.'),
('29340', '8', 'In a food processor, puree the pine nut mixture with the anchos and butter. Season the ancho butter with salt and scrape into a bowl.'),
('29340', '9', 'In a large bowl, toss the broccoli with the remaining 2 tablespoons of olive oil, then spread on 2 large rimmed baking sheets. Roast the broccoli in the upper and lower thirds of the oven for 15 minutes, or until crisp-tender, shifting the pans from top to bottom and back to front halfway through.'),
('29340', '10', 'Add the ancho butter to the broccoli and toss to coat. Season with salt and roast for 10 minutes longer, or until the broccoli is tender.'),
('29340', '11', 'Transfer to a platter and serve warm or at room temperature.'),
('29341', '1', 'Preheat the oven to 50'),
('29341', '2', 'In a mini food processor, combine the parsley with the Brazil nuts, water, tarragon, garlic and lemon zest and pulse to a coarse paste.'),
('29341', '3', 'Add 3 tablespoons of the olive oil and the Parmesan and process to a slightly smooth paste. Season with salt and pepper.'),
('29341', '4', 'On 2 large, rimmed baking sheets, toss the broccoli florets with the remaining 2 tablespoons of olive oil and spread in an even layer. Season with salt and pepper. Roast the broccoli in the center of the oven for 8 minutes. Switch the baking sheets and continue to roast for about 8 minutes longer, or until the broccoli is browned and crisp-tender.'),
('29341', '5', 'Transfer the broccoli to a platter, drizzle the pesto on top and serve.'),
('29348', '1', 'Watch how to make this recipe.'),
('29348', '2', 'Preheat the oven to 425 degrees F.');