INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('5647', '6', 'Coat 4 individual gratin dishes with remaining 2 teaspoons oil. Arrange shrimp in a single layer in dishes. sprinkle with dash of salt and dash of pepper. Sprinkle with 1/2 cup breadcrumb mixture. top with tomato slices. Sprinkle with remaining dash of salt and dash of pepper. Top with remaining 1/2 cup breadcrumb mixture. dot with remaining 2 teaspoons butter.'),
('5647', '7', 'Bake at 450 for 12 minutes or until the shrimp are done.'),
('5647', '8', 'Drizzle with vinegar.'),
('5648', '1', 'In a medium saucepan with a lid, heat 1/2 tablespoon oil over medium.'),
('5648', '2', 'Add onion. cook until softened, 3 to 5 minutes.'),
('5648', '3', 'Add broth, and bring to a boil.'),
('5648', '4', 'Add rice. season with salt and pepper. Cover, reduce heat to low, and simmer until rice is tender, about 20 minutes.'),
('5649', '1', 'A friend who is a good cook complains, "I''m too busy to cook. I get home from work and tell my family let''s go out or order in."Personally I feel the same way. I''m very happy when I open the refrigerator and see take out containers filled with Vietnamese lemon grass chicken, broken rice and bbq pork chops with pickled cabbage.But sooner or later I hunger for a home cooked meal. I crave freshly prepared comfort food. Most of the time I don''t want to spend a lot of time in the kitchen, so I want an easy to make meal. Salads are easy to make, but so are pastas.At our farmers market, one of the vendors has a good supply of fish. Just recently he started carrying shelled, deveined shrimp, big fat ones. I bought a couple of pounds for an easy to make Sunday dinner.'),
('5649', '2', 'Sauteed and tossed with pasta, they are delicious.Spaghetti and Shrimp'),
('5649', '3', 'To build out the flavors, other ingredients can be added to this easy to make dish. Check out the variations below.'),
('5650', '1', 'Cook bacon in a large skillet over medium high heat until crispy and browned.'),
('5650', '2', 'Remove bacon from pan to a paper towel, reserving 2 tablespoons bacon fat in the pan to cook the shrimp.'),
('5650', '3', 'Combine shrimp with basil, oregano, paprika, salt and pepper and toss together. Bring chicken stock to a boil, then whisk in polenta, stirring over medium heat until polenta thickens, about 5 minutes.'),
('5650', '4', 'Whisk in cheese and heavy cream and set aside. Reheat skillet, then add shrimp, garlic, and half of the green onions. Cook about 2-3 minutes, turning shrimp, until shrimp is cooked. To serve, spoon polenta into a bowl and top with shrimp mixture. Sprinkle remaining green onions and crisp bacon on top and serve immediately.'),
('5651', '1', 'In a 450 oven, roast the tomatoes, garlic, bread, and nuts on a baking sheet for 15 minutes.'),
('5651', '2', 'Transfer to a food processor pulse to roughly chop.'),
('5651', '3', 'Add the pimentos, vinegar, oil, paprika, and salt and pulse until well combined. Toss the prawns in half the Romesco sauce to coat, and spread in a single layer on a baking sheet. Roast for 15 minutes, or until shrimp are just barely cooked through.'),
('5651', '4', 'Serve with remaining sauce for dipping.'),
('5655', '1', 'Preheat oven to 400F.'),
('5655', '2', 'Place Blue Bonnet in small (1-quart) baking dish and melt in oven.'),
('5655', '3', 'Add onion, pimientos, garlic, lemon juice and dill weed. stir together.'),
('5655', '4', 'Add shrimp. toss to coat.'),
('5655', '5', 'Bake uncovered 15 minutes or just until shrimp turn pink.'),
('5657', '1', 'Heat oil in a pan on medium-high.'),
('5657', '2', 'Combine the spices and toss with the shrimp.'),
('5657', '3', 'Add shrimp to the hot pan and cook about 45 seconds per side, or until opaque.'),
('5657', '4', 'Remove the shrimp.'),
('5657', '5', 'Add the scallions, garlic and ginger to the pan and cook for 2-3 minutes.  Return the shrimp to the pan and toss to mix with the vegetables.'),
('5657', '6', 'Saute until cooked through, firm to the touch and pink.'),
('5657', '7', 'Serve immediately over rice or orzo.'),
('5660', '1', 'Preheat oven to 40'),
('5660', '2', 'To prepare shrimp, peel and devein shrimp, leaving tails intact. Rinse shrimp in cold water. drain on paper towels until dry.'),
('5660', '3', 'Combine cornstarch, salt, and red pepper in a shallow dish. stir with a whisk.'),
('5660', '4', 'Place the egg whites in a medium bowl, and beat with a mixer at medium-high speed until frothy (about 2 minutes).'),
('5660', '5', 'Place coconut in a shallow dish.'),
('5660', '6', 'Working with one shrimp at a time, dredge in cornstarch mixture. Dip in egg white. dredge in coconut, pressing gently with fingers.'),
('5660', '7', 'Place shrimp on a baking sheet coated with cooking spray. Repeat the procedure with remaining shrimp, cornstarch mixture, egg white, and coconut. Lightly coat shrimp with cooking spray.'),
('5660', '8', 'Bake at 400 for 20 minutes or until shrimp are done, turning after 10 minutes.'),
('5660', '9', 'To prepare salsa, combine pineapple and remaining ingredients in a medium bowl. stir to combine.'),
('5661', '1', 'Bring 3 cups of water to a boil in a medium saucepan over high heat, covered. Uncover and slowly whisk in the grits, 1 teaspoon salt and 1/2 teaspoon pepper. Reduce the heat to medium low and cook, stirring occasionally, until thickened, about 5 minutes. Stir in the parmesan and 1 tablespoon butter.'),
('5661', '2', 'Remove from the heat and season with salt and pepper. Cover to keep warm.'),
('5661', '3', 'Meanwhile, season the shrimp with salt and pepper. Melt the remaining 2 tablespoons butter in a large skillet over medium-high heat.'),
('5661', '4', 'Add the shrimp, garlic and cayenne, if using, and cook, tossing, until the shrimp are pink, 3 to 4 minutes.'),
('5661', '5', 'Remove from the heat and add 2 tablespoons water, the lemon juice and parsley. stir to coat the shrimp with the sauce and season with salt and pepper.'),
('5661', '6', 'Divide the grits among shallow bowls and top with the shrimp and sauce.'),
('5661', '7', 'Serve with lemon wedges.'),
('5663', '1', 'Combine 1/4 cup olive oil and next 7 ingredients in a large bowl, and toss well. Cover with plastic wrap, and chill at least 2 hours or up to 6 hours.'),
('5663', '2', 'Preheat oven to 45'),
('5663', '3', 'Place a 15- x 10-inch jellyroll pan in oven 10 minutes or until extremely hot. Carefully spread shrimp in a single layer across pan.'),
('5663', '4', 'Bake 8 minutes, stirring once halfway through cooking.'),
('5663', '5', 'Remove from oven, and immediately add stock or water, butter, and remaining 2 tablespoons olive oil to pan. Stir well.'),
('5663', '6', 'Serve in shallow bowls with good bread and cold beer or dry German Riesling.'),
('5664', '1', 'Fill a large bowl halfway with ice and water.'),
('5664', '2', 'Pour 4 qt. water into a Dutch oven. squeeze juice from lemon into Dutch oven. Stir in lemon halves, black peppercorns, bay leaves, and salt. bring to a boil over medium-high heat.'),
('5664', '3', 'Remove from heat. add shrimp. Cover and let stand 5 minutes or just until shrimp turn pink. Stir shrimp into ice water. let stand 10 minutes. Peel and devein shrimp.'),
('5665', '1', 'Heat a large Dutch oven over medium-high heat.'),
('5665', '2', 'Add oil to pan. swirl to coat.'),
('5665', '3', 'Add onion and bell pepper. saut 3 minutes or until vegetables are tender, stirring frequently.'),
('5665', '4', 'Add garlic. cook 30 seconds, stirring constantly.'),
('5665', '5', 'Add shrimp to pan. cook 30 seconds, stirring frequently.'),
('5665', '6', 'Add rice and next 7 ingredients (through broth). Bring rice mixture to a boil. cover pan. Reduce heat, and simmer 5 minutes or until rice is done.'),
('5665', '7', 'Remove from heat. stir in peas and lemon juice.'),
('5666', '1', 'Drain sun-dried tomatoes in a sieve over a bowl, reserving oil.'),
('5666', '2', 'Place 1 tablespoon reserved oil in a food processor. Coarsely chop 1 cup tomatoes. add to food processor.'),
('5666', '3', 'Place remaining oil and sun-dried tomatoes in sun-dried tomato jar. reserve for another use.'),
('5666', '4', 'Add cilantro, rind, juice, and curry to food processor. process until smooth.'),
('5666', '5', 'Combine tomato mixture and shrimp in a large zip-top plastic bag. Seal and marinate in refrigerator 2 hours, turning bag occasionally.'),
('5666', '6', 'Remove shrimp from bag. discard marinade.'),
('5666', '7', 'Prepare grill to medium-high heat.'),
('5666', '8', 'Place shrimp on grill rack coated with cooking spray. grill 3 minutes on each side or until done.'),
('5667', '1', 'Preheat oven to 35'),
('5667', '2', 'Fit 1 wonton wrapper into each of 36 mini muffin cups coated with cooking spray, pressing the wrappers into sides of cups.'),
('5667', '3', 'Bake at 350 for 7 minutes or until lightly browned. Keep wontons in muffin cups.'),
('5667', '4', 'Combine cheese and remaining ingredients, and spoon about 1 tablespoon cheese mixture into each wonton cup.'),
('5667', '5', 'Bake at 350 for 6 minutes or until cheese melts.'),
('5667', '6', 'Remove from muffin cups.'),
('5667', '7', 'Serve immediately.'),
('5668', '1', 'Preheat the oven to 20'),
('5668', '2', 'Stack and wrap the tortillas in foil and heat until warmed through.'),
('5668', '3', 'Heat a large wok or skillet until very hot to the touch.'),
('5668', '4', 'Add 1 tablespoon of the oil and heat until smoking.'),
('5668', '5', 'Add the shrimp and stir-fry over high heat until lightly browned and cooked through, about 2 minutes. Scrape the shrimp onto a large platter.'),
('5668', '6', 'Add 2 tablespoons of the oil to the wok. Stir the eggs, season them with salt and pepper and add to the wok. Cook, stirring, until large soft curds form, about 2 minutes. Scrape the eggs onto the platter with the shrimp.'),
('5668', '7', 'Add 2 tablespoons of the vegetable oil to the wok.'),
('5668', '8', 'Add the ginger, garlic and mushrooms and stir-fry over high heat until lightly browned, about 4 minutes.'),
('5668', '9', 'Add the remaining 1 tablespoon of oil.'),
('5668', '10', 'Add the coleslaw mix and scallions, season with salt and pepper and stir-fry until the cabbage is just wilted but still crunchy, about 4 minutes. Return the shrimp and egg to the wok, add the 1 tablespoon of hoisin sauce and stir-fry just until combined.'),
('5668', '11', 'Transfer the moo shu shrimp to a large bowl and serve with the warmed tortillas, cilantro leaves and hoisin sauce.'),
('5669', '1', 'Combine first 5 ingredients in a large nonstick skillet. bring to a boil. Cook 5 minutes. add shrimp. Cover and cook 2 minutes or until shrimp are done, stirring occasionally. Spoon mixture into a bowl, and chill. Stir in parsley before serving.'),
('5670', '1', 'Heat a large nonstick skillet over medium-high heat.'),
('5670', '2', 'Add oil to pan.'),
('5670', '3', 'Add garlic and shrimp, and stir-fry 2 minutes.'),
('5670', '4', 'Add the onions, soy sauce, honey, and sambal oelek. stir-fry 3 minutes or until shrimp are done.'),
('5671', '1', 'Im back from Mexico where I had a wonderful time relaxing in the sun for a week with my family. And as the saying goes, from the frying pan to the fire, I immediately jumped into a bunch of family obligations back in Colorado. Fortunately, I cooked and photographed some recipes prior to the trip so Ill share them now until I can get back into the kitchen. First up is this simple oven baked shrimp scampi. Start by laying shrimp in a single layer of a baking dish and covering with minced garlic and parsley.Next cover with breadcrumbs and Parmigiano cheese, then drizzle with melted butter.'),
('5671', '2', 'Bake until the shrimp are just cooked through, about 10 minutes.Youll know they are done because the shrimp will have turned white and the cheese will be melted  not to mention the garlic aroma wafting through your kitchen!You can eat the scampi plain, or serve them over pasta with a simple sauce of lightly heated fresh tomatoes like I did. Either way, simple and delicious!Shrimp Scampi'),
('5671', '3', 'Serves 424 large shrimp, peeled and deveined8 cloves garlic, minced2 tablespoons chopped fresh parsley1/4 cup grated Parmigiano Reggiano cheese1/4 cup bread crumbs4 tablespoons melted butter'),
('5671', '4', 'Spread shrimp in a single layer in a back dish and sprinkle with garlic and parsley, then cover with cheese and breadcrumbs.'),
('5671', '5', 'Drizzle melted butter over the top and bake at 375 degrees until shrimp are cooked through, about 10 minutes.'),
('5671', '6', 'Serve alone or over pasta.Facebook'),
('5671', '7', 'Twitter'),
('5671', '8', 'Google'),
('5671', '9', 'Pinterest'),
('5671', '10', 'Pocket'),
('5671', '11', 'Email'),
('5671', '12', 'One Comment  Comments Feed'),
('5671', '13', 'Name (required)Mail (will not be published) (required)Website Previous'),
('5671', '14', 'Next'),
('5672', '1', '1 Start cooking rice, following package instructions.2 Pulse garlic, water and 1/2 teaspoon salt in a blender, just a few pulses, so you can still see chunks of garlic.'),
('5672', '2', 'Pour over shrimp to marinate. Marinate for 10 minutes. 3 Strain the water from the shrimp and garlic mixture.'),
('5672', '3', 'Add the lime juice (or finely sliced lemongrass), jalapeo, and 1/2 teaspoon of salt to the shrimp mixture. 4'),
('5672', '4', 'Heat 1 Tbsp olive oil in high heat in large saut pan.'),
('5672', '5', 'Add shrimp. Cook one minute.'),
('5672', '6', 'Add 1 small can of coconut milk. Cook 30 seconds more.'),
('5672', '7', 'Mix in a teaspoon red chili powder or sauce.5 Put rice into a large bowl.'),
('5672', '8', 'Mix in the second 5.6 ounce can of coconut milk to the cooked rice.'),
('5672', '9', 'Serve shrimp on rice.'),
('5672', '10', 'Garnish with chopped fresh cilantro (optional).'),
('5673', '1', 'Preheat oven to 450 degrees F.Rinse and drain your chickpeas and toss with one tablespoon of olive oil and a  teaspoon of salt. Arrange chickpeas in a layer on the bottom of your baking dish and bake for about 20 minutes, until golden.Meanwhile, toss your shrimp, one tablespoon of olive oil, juice of one lemon, garlic, lemon zest, red pepper flakes and one teaspoon of salt in a large bowl. Allow shrimp mixture to marinate for 10 to 15 minutes.Once your chickpeas have finished baking, spread your shrimp mixture over the roasted chickpeas and place a few lemon slices over top. Return your dish to the oven and bake for 5 to 8 minutes longer. Shrimp should be pink in color. Once done cooking, squeeze additional lemon juice over top and garnish with chopped parsley. Enjoy!'),
('5674', '1', 'To make the seasoning, mix together the salt, paprika, cumin, curry powder, cayenne and cinnamon. Sprinkle over shrimp and toss to combine.For grilling: Preheat your grill on medium heat and spray with cooking spray to prevent shrimp from sticking. Thread shrimp on skewers and place on grill for 1 to 2 minutes (until pink) then turn over and cook an additional 30 seconds to 1 minute, depending on how you like them. Squeeze lime juice over top and garnish with chopped cilantro, if desired.For pan frying: In a large skillet, melt about a tablespoon of light butter over medium-high heat.'),
('5674', '2', 'Add shrimp and cook, stirring occasionally for about 3 to 5 minutes. Shrimp should be opaque throughout. Squeeze lime juice over top and garnish with chopped cilantro, if desired. Enjoy!'),
('5678', '1', 'Heat covered 6-quart pot of water to boiling on high.'),
('5678', '2', 'Add 2 teaspoons salt.In 12-inch skillet, melt 1/2 tablespoon margarine on medium-high.'),
('5678', '3', 'Add bread crumbs and cook 2 to 3 minutes or until golden brown, stirring frequently. Stir in pinch salt and freshly ground black pepper.'),
('5678', '4', 'Transfer to plate.In same skillet, melt 2 tablespoons margarine on medium. Stir in onions and 1/4 teaspoon salt. Cover and cook 20 minutes or until golden and very tender, stirring occasionally.Meanwhile, add pasta to boiling water in pot. Cook 4 minutes less than minimum time that label directs, stirring occasionally.'),
('5678', '5', 'Add shrimp and broccoli and cook 3 minutes. Reserve 1 cup pasta cooking water.'),
('5678', '6', 'Drain pasta mixture and return to pot.'),
('5678', '7', 'Add onion mixture, reserved cooking water, 1/2 teaspoon salt, 1/2 teaspoon freshly ground black pepper, and remaining 1/2 tablespoon margarine. Cook on medium 2 minutes, tossing to coat. To serve, top with reserved toasted bread crumbs.'),
('5679', '1', 'Peel shrimp, leaving tails on. devein, if desired. Thread 4 shrimp onto each skewer. Set aside.'),
('5679', '2', 'Cook brown sugar in a small heavy saucepan over low heat until melted.'),
('5679', '3', 'Add garlic and next 6 ingredients. Cook 5 minutes or until tamarind paste melts.'),
('5679', '4', 'Remove from heat.'),
('5679', '5', 'Brush shrimp with olive oil. Grill, without grill lid, over medium-high heat (350 to 40'),
('5679', '6', 'for 4 to 6 minutes or until shrimp turn pink, turning once, and basting with tamarind glaze.'),
('5679', '7', 'Serve with Smoky Sweet Sauce.'),
('5679', '8', 'Note: Tamarind is a tree-growing fruit. Its long pods contain a sweet-and-sour pulp from which a paste is made. Look for tamarind paste in the Mexican or Asian section of your grocery store.'),
('5680', '1', 'Toss shrimp with lime juice.'),
('5680', '2', 'Combine 1/2 cup onion, 1/2 cup bell pepper, and garlic in the bowl of a food processor. pulse until finely chopped.'),
('5680', '3', 'Combine shrimp with onion mixture, remaining onion and bell pepper, and next 3 ingredients. Season with salt and pepper.'),
('5680', '4', 'Place one banana leaf on a 12- x 16-inch piece of aluminum foil.'),
('5680', '5', 'Spread half of the shrimp mixture in center of leaf. Cover it with second banana leaf and another 12- x 16-inch piece of foil.'),
('5680', '6', 'Roll 4 edges of foil over tightly to form a pouch. Repeat with remaining banana leaves, foil, and shrimp.'),
('5680', '7', 'Grill pouches, covered with grill lid, over medium heat 8 to 10 minutes.'),
('5680', '8', 'Remove pouches from grill.'),
('5680', '9', 'Remove foil. place pouches onto serving plates.'),
('5680', '10', 'Cut a slit in center of leaves, and peel back. Sprinkle with cilantro.'),
('5681', '1', 'In a large saucepan, combine the water, vinegar, sugar, garlic, jalapeos, bay leaves, crushed red pepper, salt, peppercorns and allspice berries and bring to a boil to dissolve the sugar.'),
('5681', '2', 'Add the shrimp and cook, stirring, for 1 minute.'),
('5681', '3', 'Transfer the shrimp and liquid to a large bowl and let cool to room temperature. Cover and refrigerate for 8 to 10 hours.'),
('5681', '4', 'In a large saucepan, boil the cream over high heat until reduced by half, about 3 minutes.'),
('5681', '5', 'Add the spinach and cook, stirring, until wilted, about 1 minute.'),
('5681', '6', 'Transfer the spinach mixture to a bowl and let cool. Stir in the crme frache and lemon juice and season with salt.'),
('5681', '7', 'Using a slotted spoon, lift the shrimp and jalapeos from the marinade and arrange on a platter.'),
('5681', '8', 'Garnish with cilantro leaves and serve the spinach dip in a bowl alongside.'),
('5683', '1', 'Watch how to make this recipe.'),
('5683', '2', 'For the pasta, put a large pot of water on the stove to boil. When it has come to the boil, add a couple of tablespoons of salt and the linguini. Stir to make sure the pasta separates. cover. When the water returns to a boil, cook for about 6 to 8 minutes or until the pasta is not quite done.'),
('5683', '3', 'Drain the pasta reserving 1 cup of water.'),
('5683', '4', 'Meanwhile, in a large skillet, melt 2 tablespoons butter in 2 tablespoons olive oil over medium-high heat.'),
('5683', '5', 'Saute the shallots, garlic, and red pepper flakes (if using) until the shallots are translucent, about 3 to 4 minutes. Season the shrimp with salt and pepper. add them to the pan and cook until they have turned pink, about 2 to 3 minutes.'),
('5683', '6', 'Remove the shrimp from the pan. set aside and keep warm.'),
('5683', '7', 'Add wine and lemon juice and bring to a boil.'),
('5683', '8', 'Add 2 tablespoons butter and 2 tablespoons oil. When the butter has melted, return the shrimp to the pan along with the parsley and cooked pasta and reserved pasta water. Stir well and season with salt and pepper.'),
('5683', '9', 'Drizzle over a bit more olive oil and serve immediately.'),
('5684', '1', 'After grits have cooked for 15 minutes, cook bacon in a large skillet over medium until browned, 4 to 6 minutes. Using a slotted spoon, transfer to a paper-towel-lined plate.'),
('5684', '2', 'Add onion and garlic to fat in skillet. season with salt and pepper. Cook, stirring occasionally, until onion is tender and browned, 8 to 10 minutes.'),
('5685', '1', 'Preheat oven to 42'),
('5685', '2', 'Arrange shrimp in a single layer in a 13 x 9-inch baking dish coated with cooking spray.'),
('5685', '3', 'Combine lemon juice and next 5 ingredients. pour over shrimp.'),
('5685', '4', 'Bake at 425 for 8 to 10 minutes or until shrimp are done. Sprinkle the parsley sover shrimp, and serve immediately.'),
('5685', '5', 'carbo rating: 7'),
('5687', '1', 'In a large pot, heat 2 tablespoons of the oil.'),
('5687', '2', 'Add the shrimp shells and cook over moderate heat until they turn pink, 3 minutes.'),
('5687', '3', 'Add the onion, fennel, celery, smashed garlic and saffron and cook until softened, 5 minutes.'),
('5687', '4', 'Add the Pernod and brandy and cook until evaporated. Stir in the tomato paste, add 6 cups of water and bring to a boil. Simmer until the broth is reduced to 4 cups, 45 minutes.'),
('5687', '5', 'Add the tarragon and parsley sprigs and let stand off the heat for 15 minutes.'),
('5687', '6', 'Strain the liquid, pressing the vegetables to mash them through the sieve. Alternatively, pass the mixture through a food mill. Discard the shrimp shells.'),
('5687', '7', 'Transfer the liquid to a saucepan and simmer until reduced to 2 cups, 30 minutes. Swirl in the butter and season with salt and pepper.'),
('5687', '8', 'In a large skillet, heat 1 tablespoon of the oil until shimmering. Season the shrimp with salt and pepper, then saut over high heat, turning once, until nearly cooked, 2 minutes.'),
('5687', '9', 'Transfer the shrimp to a plate.'),
('5687', '10', 'Add the remaining 3 tablespoons of oil to the skillet.'),
('5687', '11', 'Add the minced garlic and cook over low heat until softened and golden, 1 minute. Stir in the paprika. Return the shrimp to the skillet and add the chopped herbs and the lemon juice. Cook for 1 minute longer, until the shrimp are white throughout.'),
('5687', '12', 'Ladle the sauce into bowls and top with the shrimp.'),
('5687', '13', 'Drizzle any garlic oil over the shrimp and serve right away.'),
('5688', '1', 'Heat oil in a large nonstick skillet over medium heat.'),
('5688', '2', 'Add pepper, garlic, and bay leaf. cook 2 minutes, stirring constantly. Increase heat to medium-high.'),
('5688', '3', 'Add shrimp. saut until shrimp have pink or orange markings and white, opaque flesh (about 4 minutes).'),
('5688', '4', 'Remove from heat. Sprinkle with salt. Discard bay leaf. Sprinkle with parsley, and serve with lemon wedges.'),
('5689', '1', 'Preheat oven to 40'),
('5689', '2', 'To prepare shrimp, coat a baking sheet with cooking spray.'),
('5689', '3', 'Place prepared pan in 400 oven for 10 minutes.'),
('5689', '4', 'Combine panko, 1/4 teaspoon garlic powder, onion powder, and salt in a shallow dish, stirring with a whisk.'),
('5689', '5', 'Place egg white in another shallow dish. Dip shrimp in egg white, and dredge in panko mixture.'),
('5689', '6', 'Place on preheated baking sheet.'),
('5689', '7', 'Bake at 400 for 10 minutes or until done.'),
('5689', '8', 'To prepare sauce, combine mustard and the remaining ingredients.'),
('5689', '9', 'Serve sauce with shrimp.'),
('5691', '1', 'Cook the pasta according to package directions, omitting salt and fat.'),
('5691', '2', 'While pasta cooks, heat 1 tablespoon oil in a large skillet over medium-high heat. Sprinkle 1/2 teaspoon of salt and 1/8 teaspoon of black pepper evenly over shrimp.'),
('5691', '3', 'Add shrimp to pan. cook 1 1/2 minutes on each side or until done.'),
('5691', '4', 'Remove from pan.'),
('5691', '5', 'Add remaining 1 tablespoon olive oil to pan.'),
('5691', '6', 'Add onion, garlic, and red pepper. cook 2 minutes, stirring frequently.'),
('5691', '7', 'Add tomatoes, and cook 3 minutes or until tomatoes begin to soften, stirring occasionally. Stir in pasta and shrimp. cook 1 minute or until thoroughly heated.'),
('5691', '8', 'Remove from heat, and stir in 1/4 teaspoon salt, 1/8 teaspoon black pepper, cheese, and basil.'),
('5692', '1', 'To prepare gremolata, combine first 5 ingredients. set aside.'),
('5692', '2', 'To prepare shrimp, heat a large nonstick skillet over medium-high heat.'),
('5692', '3', 'Add 2 teaspoons oil to pan, swirling to coat. heat 20 seconds.'),
('5692', '4', 'Add asparagus to pan. saut 3 minutes, stirring frequently.'),
('5692', '5', 'Remove asparagus from pan. keep warm.'),
('5692', '6', 'Add remaining 2 teaspoons oil to pan, swirling to coat. heat 20 seconds.'),
('5692', '7', 'Add shrimp to pan. saut 3 minutes or until done, stirring occasionally.'),
('5692', '8', 'Add asparagus, 1/8 teaspoon salt, and 1/8 teaspoon pepper to pan. saut 1 minute or until thoroughly heated. Sprinkle evenly with gremolata.'),
('5693', '1', 'Melt butter in a large nonstick skillet over medium-high heat.'),
('5693', '2', 'Add garlic, and cook 1 to 2 minutes or until tender.'),
('5693', '3', 'Add pepper and next 5 ingredients. bring to a boil.'),
('5693', '4', 'Add shrimp, and cook 4 minutes.'),
('5693', '5', 'Add beer. cook 1 minute or until shrimp are done.'),
('5693', '6', 'Divide shrimp and sauce evenly among 4 shallow bowls.'),
('5693', '7', 'Serve with French bread and lemon wedges.'),
('5694', '1', 'Preheat broiler.'),
('5694', '2', 'Combine first 7 ingredients in a large bowl.'),
('5694', '3', 'Add shrimp to bowl. toss to coat. Thread 5 shrimp onto each of 20 (12-inch) wooden skewers. Arrange 10 skewers on a large baking sheet. Broil 3 minutes on one side. carefully turn and broil 2 minutes or until shrimp are done.'),
('5694', '4', 'Place skewers on a serving platter. Repeat procedure with remaining 10 skewers.'),
('5694', '5', 'Serve with lemon halves, if desired.'),
('5697', '1', 'Combine first 3 ingredients. set aside.'),
('5697', '2', 'Heat a 14-inch wok over high heat.'),
('5697', '3', 'Add oil to wok, swirling to coat.'),
('5697', '4', 'Add shallots, garlic, and jalapeo to wok. stir-fry 30 seconds or just until shallots begin to brown.'),
('5697', '5', 'Add shrimp to wok. stir-fry 3 minutes or until shrimp are done.'),
('5697', '6', 'Add corn. stir-fry 1 minute or just until corn is heated. Stir in juice mixture. sprinkle with cilantro.'),
('5698', '1', 'Preheat oven to 50'),
('5698', '2', 'Place olive oil and garlic in a food processor. process until garlic is finely chopped, scraping sides of bowl occasionally.'),
('5698', '3', 'Add green onions and parsley in food processor. pulse until minced. Spoon garlic mixture into a large bowl.'),
('5698', '4', 'Add 1/2 teaspoon salt, black pepper, red pepper, and shrimp to garlic mixture, and toss well to coat.'),
('5698', '5', 'Spoon the shrimp mixture into a shallow roasting pan, and add the wine.'),
('5698', '6', 'Bake at 500 for 7 minutes or until the shrimp are done, stirring once.'),
('5698', '7', 'Serve with bread.'),
('5699', '1', 'Prepare grill.'),
('5699', '2', 'To prepare salsa, combine first 6 ingredients in a medium bowl.'),
('5699', '3', 'To prepare sat, combine mint, juice, salt, and chili powder in a large bowl. add shrimp, tossing gently to coat. Thread 3 shrimp onto each of 8 (6-inch) skewers.'),
('5699', '4', 'Place shrimp on grill rack coated with cooking spray. grill 1 1/2 minutes on each side or until shrimp turn pink.'),
('5699', '5', 'Serve with salsa.'),
('5699', '6', 'Garnish with cilantro sprigs, if desired.'),
('5700', '1', 'Heat a large nonstick skillet over medium-high heat.'),
('5700', '2', 'Add oil to pan. swirl to coat.'),
('5700', '3', 'Add poblano chile and next 3 ingredients (through shallot). saut for 30 seconds, stirring frequently.'),
('5700', '4', 'Add shrimp and paprika. saut for 4 minutes or until shrimp are done, stirring frequently.'),
('5700', '5', 'Remove shrimp mixture from pan.'),
('5700', '6', 'Add sherry and orange juice to pan. Boil, and simmer 3 minutes or until slightly thick. Stir in butter, oregano, and red pepper. Return shrimp to pan. cook 2 minutes or until thoroughly heated.'),
('5701', '1', 'Combine 1 teaspoon oil and 1 cup carrot juice in a medium saucepan. bring to a boil. Gradually stir in couscous.'),
('5701', '2', 'Remove from heat. Cover and let stand 5 minutes.'),
('5701', '3', 'While couscous stands, bring remaining carrot juice to a boil in a small saucepan. cook until reduced to 1/4 cup (about 2 1/2 minutes).'),
('5701', '4', 'Remove from heat. stir in 2 teaspoons oil, lime juice, jalapeo, ginger, and salt.'),
('5701', '5', 'Fluff couscous with a fork. stir in 1/4 cup reduced carrot juice mixture and onions.'),
('5701', '6', 'Combine remaining carrot juice mixture, greens, and shrimp in a bowl, tossing gently to coat.'),
('5702', '1', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('5702', '2', 'Add garlic. cook until golden (about 30 seconds), stirring constantly. Stir in water, cumin, coriander, and turmeric. Cover, reduce heat, and simmer 7 minutes.'),
('5702', '3', 'Add shrimp. cook 3 minutes.'),
('5702', '4', 'Combine flour, sugar, salt, and yogurt. stir with a whisk. Stir yogurt mixture into shrimp mixture. Cover and cook 4 minutes or until shrimp are done. Stir in onions.'),
('5703', '1', 'Preheat oven to 45'),
('5703', '2', 'Coat inside of oven bag with cooking spray.'),
('5703', '3', 'Place the bag on a large shallow baking pan.'),
('5703', '4', 'Cook the pasta in boiling water 5 minutes, omitting salt and fat. drain.'),
('5703', '5', 'Place the pasta in a large bowl. Stir in 1 teaspoon oil and next 7 ingredients (1 teaspoon oil through pepper).'),
('5703', '6', 'Place the orzo mixture in prepared oven bag.'),
('5703', '7', 'Combine shrimp and basil. Arrange shrimp mixture on orzo mixture. Fold edge of bag over to seal.'),
('5703', '8', 'Bake at 450 for 25 minutes or until the shrimp are done.'),
('5703', '9', 'Cut open bag with a sharp knife, and peel back the foil.'),
('5703', '10', 'Drizzle with 1 teaspoon oil.'),
('5704', '1', 'Combine first 7 ingredients in a Dutch oven. bring to a boil. Reduce heat. simmer 15 minutes.'),
('5704', '2', 'Add shrimp. cook 3 minutes.'),
('5704', '3', 'Drain shrimp and place in a shallow dish.'),
('5704', '4', 'Combine lemon rind and remaining ingredients.'),
('5704', '5', 'Add to warm shrimp mixture. toss well. Cover and chill until ready to serve.'),
('5705', '1', 'Rinse shrimp in cold water and place in a large Ziploc bag.'),
('5705', '2', 'Combine garlic, ginger, both chili pastes, honey, lime juice, salt, pepper, and oil in a large bowl.'),
('5705', '3', 'Whisk thoroughly. Set aside 1 c. of the marinade.'),
('5705', '4', 'Pour remaining mixture over shrimp and refrigerate for at least 24 hours and up to 48 hours.When ready to cook, thread shrimp onto skewers.If using bamboo skewers, soak in water for at least 1/2 hour before skewering anything. Preheat outdoor grill. This really should be done outside because they get VERY smokey! When grill is hot, reduce heat to low and quickly place all skewers over the heat.'),
('5705', '5', 'Brush with reserved marinade. When theyve cooked for 1 1/2-2 minutes,quickly flip them over and brush or drizzle with remaining marinade. Cook for another 1 1/2-2 minutes, or until opaque and pink.Shrimp cook extremely quickly and you dont want to overcook them, but these are pretty forgiving if you do.'),
('5705', '6', 'Remove skewers from grill and remove shrimp from skewers. Pile them on a big ol platter, drizzle with any remaining reserved marinade, and squeeze the juice from a lime all over them.Toss to distribute the deliciousness. You could serve this with:Lime Cilantro Rice with Pineapple'),
('5705', '7', 'Sweet and Savory Coconut Rice'),
('5705', '8', 'Caramelized Green Beans'),
('5705', '9', 'Mango-Steak Salad(minus the steakor with the steak! Surf and turf, baby!)'),
('5709', '1', 'In a large bowl, toss the shrimp with the garlic, lime juice and 1 teaspoon of salt.'),
('5709', '2', 'Let marinate at room temperature for 30 minutes.'),
('5709', '3', 'In a large skillet, heat the Annatto Oil until shimmering.'),
('5709', '4', 'Add the onion, scallions and red and green bell peppers and cook over moderately high heat, stirring, until softened, about 4 minutes.'),
('5709', '5', 'Add the minced tomatoes and cook until softened, about 5 minutes. Reduce the heat to moderately low and add the tomato sauce, coconut milk, chile and 1 teaspoon of salt. Simmer until the sauce is reduced by one-fourth, about 10 minutes. Increase the heat to moderately high.'),
('5709', '6', 'Add the shrimp and cook, stirring, until they''re pink and opaque, about 5 minutes.'),
('5709', '7', 'Transfer to a serving dish and discard the chile. Sprinkle with the cilantro and serve with lime wedges.'),
('5711', '1', 'Combine 1/4 cup sugar, canola oil, fish sauce, chopped lemongrass, and grated garlic in a food processor or mini chopper. process until the lemongrass is finely chopped.'),
('5711', '2', 'Transfer sugar mixture to a large zip-top plastic bag.'),
('5711', '3', 'Add shrimp. seal and marinate in refrigerator 45 minutes.'),
('5711', '4', 'Prepare grill to high heat.'),
('5711', '5', 'Remove shrimp from bag. discard marinade. Thread 6 shrimp onto each of 6 (12-inch) skewers.'),
('5711', '6', 'Place skewers on grill rack. grill 2 minutes on each side or until done.'),
('5712', '1', 'Place shrimp in food processor, pulse until finely chopped'),
('5712', '2', 'In a large bowl, combine chopped shrimp, bell pepper, garlic, scallions, lime juice, agave, salt, chipotle, egg and cilantro'),
('5712', '3', 'Form mixture into 12 () inch thick patties, dip each in almond flour, coating thoroughly'),
('5712', '4', 'In a large skillet, over medium heat, warm 1 tablespoon oil'),
('5712', '5', 'Add 4 patties to the skillet and cook about 5 minutes per side, until browned. remove and place on paper towel lined plate'),
('5712', '6', 'Repeat with remaining cakes'),
('5713', '1', 'Preheat oven to 45'),
('5713', '2', 'Lightly crumple some aluminum foil and place it on a large baking sheet. Set aside.In a shallow bowl or on a plate, combine the chopped macadamia nuts and the coconut. Set aside.Rinse the shrimp. In a large Ziploc bag, combine the flour, lime zest, kosher salt, cayenne, garlic powder, and onion powder.'),
('5713', '3', 'Add the shrimp and toss to coat.Shake the excess flour from the shrimp. If your shrimp are smaller, dip a few shrimp at a time in the egg mixture, shake off the excess, and then roll them in the coconut/macadamia mixture.'),
('5713', '4', 'Place on the prepared baking sheet. If your shrimp are large, work with one at a time. Repeat with remaining shrimp.'),
('5713', '5', 'Place the baking sheet in the pre-heated oven.'),
('5713', '6', 'Bake for 10 minutes (slightly longer if your shrimp are very large).While the shrimp are cooking, combine the mango, pineapple, salt, and cayenne in a blender. Blend until smooth.'),
('5713', '7', 'Serve the hot shrimp immediately with the dipping sauce. Makes 4 servings.'),
('5715', '1', 'Rinse and devein the shrimp and pat dry the shrimp thoroughly with paper towels.'),
('5715', '2', 'Put the shrimp, garlic, white pepper, lard/cooking oil into a food processor and blend well to form a smooth paste.'),
('5715', '3', 'Transfer the shrimp paste into a bowl.Beat the egg white with an electronic hand beater until frothy.'),
('5715', '4', 'Combine the shrimp paste with beaten egg white and blend well. Chill in the refrigerator for 30 minutes and then divide the shrimp paste into four ('),
('5715', '5', 'equal portions.Oil both hands and wrap the shrimp paste around the sugar cane. Shape them nicely and leave 1.5 inch of the sugar cane exposed.'),
('5715', '6', 'Heat up a wok of oil and deep fry the chao tom until golden brown.'),
('5715', '7', 'Serve immediately.'),
('5717', '1', 'Sprinkle potato pieces with 1 tbsp water. microwave, covered, until fork-tender, 3 minutes.'),
('5717', '2', 'Heat oil and curry powder in a large skillet over medium heat.'),
('5717', '3', 'Add onion. cook until soft, 3 to 4 minutes. Push onion to side of skillet.'),
('5717', '4', 'Add shrimp. cook 2 minutes per side. Stir in potatoes and bell pepper. cook until pepper softens, 1 to 2 minutes.'),
('5717', '5', 'Add mango, coconut milk, fish sauce, sriracha and sugar. Simmer 2 minutes.'),
('5717', '6', 'Remove from heat. add basil.Sprinkle potato pieces with 1 tbsp water. microwave, covered, until fork-tender, 3 minutes.'),
('5717', '7', 'Heat oil and curry powder in a large skillet over medium heat.'),
('5717', '8', 'Add onion. cook until soft, 3 to 4 minutes. Push onion to side of skillet.'),
('5717', '9', 'Add shrimp. cook 2 minutes per side. Stir in potatoes and bell pepper. cook until pepper softens, 1 to 2 minutes.'),
('5717', '10', 'Add mango, coconut milk, fish sauce, sriracha and sugar. Simmer 2 minutes.'),
('5717', '11', 'Remove from heat. add basil.'),
('5718', '1', 'If using shrimp in the shell, peel and devein them. If using cleaned, thawed shrimp, skip this step. Either way, dry the shrimp well with paper towels and set aside.    Measure a generous 1/2 cup of mint leaves, somewhat loosely packed, and put them in a blender (or a mini food processor). Reserve the remaining mint leaves for garnish. To the blender, add the jalapeos, garlic, ginger, sugar, vinegar, and fish sauce (if using). Pure the ingredients until the mixture is smooth, scraping down the sides once or twice, about 3 minutes. Set the dressing aside (or refrigerate it overnight. bring it to room temperature before using).    Arrange the lettuce leaves, sprouts, cilantro, mango, and reserved mint leaves on a platter. set aside.    Set a wok or large skillet over high heat and add the oil. When hot, add the shrimp, season with salt and pepper, and stir-fry until theyre browned outside and opaque white inside, 3 to 5 minutes. cut one in half to check.'),
('5718', '2', 'Transfer to a warm platter.    To serve, bring the platters of shrimp and of lettuce and garnishes to the table. Fill a lettuce leaf with some shrimp and spoon on about 1 tsp. dressing.'),
('5718', '3', 'Add the garnishes, roll up the leaf, and eat.'),
('5719', '1', 'Melt Parkay in large skillet over medium heat 3 to 5 minutes or until Parkay just starts to turn golden brown, stirring occasionally.'),
('5719', '2', 'Remove from heat.'),
('5719', '3', 'Add honey, vinegar, mustard and pepper flakes. stir with wire whisk until well blended.'),
('5719', '4', 'Return skillet to heat.'),
('5719', '5', 'Add shrimp. stir to coat evenly. Cook 4 minutes or just until shrimp turn pink, stirring occasionally.'),
('5719', '6', 'Spoon shrimp onto serving plate. top with mustard sauce.'),
('5720', '1', 'Prepare grill.'),
('5720', '2', 'Combine first 6 ingredients in a large bowl.'),
('5720', '3', 'Add shrimp. toss to coat. Cover and marinate in refrigerator 10 minutes.'),
('5720', '4', 'Place bay leaves and lemon wedges in a large bowl. Coat with cooking spray. toss to coat.'),
('5720', '5', 'Thread 4 lemon wedges, 4 shrimp, and 4 bay leaves alternately onto each of 8 (10-inch) skewers.'),
('5720', '6', 'Place skewers on grill rack coated with cooking spray. grill 2 minutes on each side or until shrimp are done.'),
('5721', '1', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('5721', '2', 'Add garlic. saut 1 minute or until browned.'),
('5721', '3', 'Add shrimp. cook 1 to 2 minutes, stirring constantly.'),
('5721', '4', 'Add peas and next 6 ingredients (through tomatoes). cook 8 minutes or until shrimp are done. Top each serving with 4 teaspoons mint and 4 teaspoons goat cheese.'),
('5723', '1', 'Bring a 6-quart pot of highly salted water to boil over high heat.'),
('5723', '2', 'Add the shrimp to the boiling water and simmer until they are cooked through, 3 to 4 minutes. With a slotted spoon or strainer, transfer the shrimp to a bowl of ice water to stop the cooking. Once cooled, drain, pat dry and reserve.'),
('5723', '3', 'Puree the creme fraiche, tarragon, scallions, zest and lemon juice in food processor until smooth. Season with salt and pepper.'),
('5723', '4', 'Transfer to a bowl and serve with the reserved shrimp.'),
('5723', '5', 'BYOC: For a little extra depth of flavor, try adding an anchovy fillet to the puree... trust me, it''s great!'),
('5726', '1', 'Combine 3 cups cooked brown rice with 2 tablespoons lemon juice. Cook 1 pound peeled, deveined shrimp in 2 batches in a nonstick skillet over medium heat using 1/2 tablespoon oil for each batch, until shrimp are pink, 3-4 minutes.'),
('5726', '2', 'Transfer to a plate.'),
('5726', '3', 'Add 1 seeded, sliced Thai red chile pepper, 1/4 cup chopped lemongrass, 1 tablespoon chopped ginger, 1/2 cup sliced red onion, and 3 tablespoons sugar to pan and cook, 1 minute.'),
('5726', '4', 'Add 1 1/2 tablespoons fish sauce and 1 cup coconut water. cook 2 minutes.'),
('5726', '5', 'Add shrimp to pan. cook 2 minutes. Divide rice and shrimp among 4 bowls. garnish with cilantro and mung bean sprouts.'),
('5727', '1', 'Heat 1 tablespoon olive oil in a large skillet over medium heat.'),
('5727', '2', 'Add garlic, and cook 1 minute or just until lightly toasted.'),
('5727', '3', 'Add wine slowly, and cook 1 minute. Stir in paprika and next 3 ingredients, and add shrimp. reduce heat, and cook 2 minutes or just until shrimp turn pink. Sprinkle with fresh parsley, and drizzle with remaining 3 tablespoons olive oil.'),
('5727', '4', 'Serve immediately.'),
('5729', '1', 'Combine 1 1/2 gallons water and first 7 ingredients in a large Dutch oven, stirring well. Bring to a boil.'),
('5729', '2', 'Add shrimp, and cook over high heat 3 minutes or just until shrimp turn pink. drain.'),
('5729', '3', 'Place shrimp immediately in a single layer over ice on a rimmed baking sheet.'),
('5729', '4', 'Let cool 5 minutes.'),
('5729', '5', 'Remove shrimp with tongs to a bowl. cover and chill.'),
('5731', '1', 'In a bowl, whisk the sambal oelek with the lemon juice, lime juice, orange juice and oregano.'),
('5731', '2', 'Whisk in the 1/2 cup of olive oil and season with salt and pepper.'),
('5731', '3', 'Light a grill or preheat a grill pan.'),
('5731', '4', 'Brush the shrimp with oil and season with salt and pepper. Grill the shrimp over moderate heat, turning once, until cooked through, about 8 minutes.'),
('5731', '5', 'Transfer the shrimp to plates and spoon the dressing on top.'),
('5731', '6', 'Serve.'),
('5735', '1', 'Watch how to make this recipe.'),
('5735', '2', 'Preheat the oven to 350 degrees F.'),
('5735', '3', 'Using a 1 1/2-inch round cutter, cut 4 rounds from each slice of bread.'),
('5735', '4', 'Place the rounds on a sheet pan and toast in the oven until golden brown, 12 to 14 minutes.'),
('5735', '5', 'Bring a 5-quart pot of highly salted water to a boil. Prepare a medium bowl with ice and water.'),
('5735', '6', 'Add the shrimp to the boiling water and simmer until cooked through, 3 to 4 minutes. With a slotted spoon or strainer, transfer the shrimp to the ice water to stop the cooking.'),
('5735', '7', 'Drain, pat dry, cut lengthwise and keep cool.'),
('5735', '8', 'Pulse the creme fraiche with the horseradish in a food processor until smooth. Season with salt.'),
('5735', '9', 'Place 1 teaspoon of the creme fraiche mixture on 1 toasted round. Top with 1 shrimp and garnish with chopped chives.'),
('5735', '10', 'BYOC: Need a little extra spice in your life? Try adding your favorite hot sauce to the horseradish mixture. This is a great cocktail party item. You can make all the parts ahead of time and put together right before your guests arrive.'),
('5737', '1', 'Pour the olive oil into a wide, heavy-bottomed frying pan. Then add the chile and garlic and, over moderate to low heat, to infuse rather than to color, fry for 2 minutes, stirring all the time. Then turn the heat to high, add the shrimp, and stir-fry them for another 2 minutes or until they turn pink and are just, delicately, cooked. you want the flesh to stay tender.'),
('5737', '2', 'Pour in the white wine and let it bubble up. You don''t want a liquid puddle around the shrimp, just enough wine to let the juices ooze into a winy sauce. Another minute or so should do it. Season with the salt, if necessary, and then turn into your bowl and sprinkle with parsley. Eat with some good hunks of baguette. I eat these carapace, head, and all: one of the reasons I designate them for solitary dinner.'),
('5737', '3', 'If you want, you can add a tablespoonful or so of brandy before throwing in the wine.'),
('5738', '1', 'In a large saucepan, heat oil'),
('5738', '2', 'Saut garlic and onion over low heat until tender, about 10-15 minutes'),
('5738', '3', 'Add tomatoes, ginger, cumin, coriander and turmeric. simmer for 5 minutes'),
('5738', '4', 'Place shrimp in simmering sauce and cook for 10 minutes until cooked through'),
('5738', '5', 'Stir in cilantro'),
('5738', '6', 'Remove from heat, add lime juice'),
('5738', '7', 'Serve'),
('5739', '1', 'In a bowl, whisk together the egg yolks and sugar. Dissolve the tea in a little bit of water or cream to get rid of any lumps. whisk the cream, tea and vanilla into the egg yolks and sugar.Divide among 6 small ramekins, and put them into a roasting pan or 9?x13? pan. pour water in so that the water comes about halfway up the sides of the ramekins. This will sort of insulate them so that they cook gently and evenly.'),
('5739', '2', 'Bake for about 40 minutes, until the custards are set but still just slightly jiggly in the middle (youll get a feel for this!). Take them out, let them cool and then refrigerate for a few hours or overnight, until nice and cold.Sprinkle an even layer of sugar over each dish and caramelize with a torch or transfer to a cookie sheet and place under the broiler in the oven for about 2 minutes, just until the sugar is caramelized and golden. Turn the sheet around if you need to to help them caremelize evenly. Refrigerate again, or just let them sit on the countertop while you eat dinner, just until the sugar is set like glass.'),
('5739', '3', 'Serves 6.[print_link]'),
('5740', '1', 'Preheat oven to 500 degrees F.'),
('5742', '1', 'Heat 2 tsp oil in a 3-quart saucepan over medium-high heat. Cook onion, garlic, ginger, 1/4 tsp salt, allspice, cumin and cinnamon about 3 minutes.'),
('5742', '2', 'Add mango, vinegar, lime juice and sugar and gently boil, stirring occasionally, until sauce is thick. refrigerate in a bowl. Toss shrimp with red pepper, garlic powder and remaining 1/2 tsp salt.'),
('5742', '3', 'Heat remaining 2 tsp oil in a large nonstick skillet over medium-high heat. Cook shrimp until no longer translucent, about 2 minutes on each side.'),
('5742', '4', 'Let cool. serve with sauce.'),
('5742', '5', 'Heat 2 tsp oil in a 3-quart saucepan over medium-high heat. Cook onion, garlic, ginger, 1/4 tsp salt, allspice, cumin and cinnamon about 3 minutes.'),
('5742', '6', 'Add mango, vinegar, lime juice and sugar and gently boil, stirring occasionally, until sauce is thick. refrigerate in a bowl. Toss shrimp with red pepper, garlic powder and remaining 1/2 tsp salt.'),
('5742', '7', 'Heat remaining 2 tsp oil in a large nonstick skillet over medium-high heat. Cook shrimp until no longer translucent, about 2 minutes on each side.'),
('5742', '8', 'Let cool. serve with sauce.'),
('5743', '1', 'Peel shrimp, leaving the tails intact. Starting at tail end, butterfly each shrimp, cutting to, but not through, underside of shrimp.'),
('5743', '2', 'Combine shrimp, 6 tablespoons of Honeyed Lemon-Dijon Vinaigrette, and red pepper in a large zip-top plastic bag. Seal and marinate in refrigerator 15 minutes, turning bag occasionally.'),
('5743', '3', 'Prepare grill to medium-high heat.'),
('5743', '4', 'Remove shrimp from marinade. discard marinade. Sprinkle shrimp evenly with salt and black pepper.'),
('5743', '5', 'Place the shrimp, cut sides down, on grill rack coated with cooking spray. grill 2 minutes on each side or until done, basting frequently with the remaining 6 tablespoons of Honeyed Lemon-Dijon Vinaigrette.'),
('5743', '6', 'Serve shrimp with lemon wedges.'),
('5744', '1', 'In a large pot whisk together the coconut milk, lime juice, curry powder and ginger. Slowly bring to a low boil over low heat. Simmer for until slightly reduced and thickened, about 7 to 10 minutes. Taste for seasoning and add salt and or pepper, if needed.'),
('5744', '2', 'Add the shrimp and simmer, covered, until the shrimp are fully cooked, about 12 to 15 minutes.'),
('5744', '3', 'Transfer the curry to a serving bowl and serve with lime wedges.'),
('5745', '1', 'Combine garlic, 1 tablespoon olive oil, paprika, and 1/4 teaspoon salt in a large bowl. stir with a whisk.'),
('5745', '2', 'Add shrimp, and toss to coat. Set aside.'),
('5745', '3', 'Heat remaining 1 tablespoon oil in a 3-quart saucepan over medium-high heat.'),
('5745', '4', 'Add onion, and cook 2 to 3 minutes until soft.'),
('5745', '5', 'Add rice, remaining 1/4 teaspoon salt, and turmeric.'),
('5745', '6', 'Add 21/2 cups cold water. cover and reduce heat to low. Cook 4 minutes and remove from heat. Stir in peas and let stand, covered, until ready to serve.'),
('5745', '7', 'Warm a large nonstick skillet over medium-high heat.'),
('5745', '8', 'Place 1 shrimp in center of pan. When the shrimp begins to sizzle, add remaining shrimp and cook 2 to 3 minutes on each side until opaque.'),
('5745', '9', 'Add sherry, if desired, during the last minute of cooking, and toss to coat.'),
('5745', '10', 'Remove from heat, and sprinkle with parsley. Fluff rice and serve immediately.'),
('5747', '1', 'Mix sauce. Toss with shrimp'),
('5747', '2', 'Bake at 350 for 15 min in roasting pan.'),
('5747', '3', 'Serve Hot & Sauce'),
('5753', '1', 'Preheat broiler.'),
('5753', '2', 'Cut bell peppers in half lengthwise. discard seeds and membranes.'),
('5753', '3', 'Place pepper halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 15 minutes or until blackened.'),
('5753', '4', 'Place in a zip-top plastic bag. seal.'),
('5753', '5', 'Let stand 15 minutes. Peel peppers.'),
('5753', '6', 'Place bell peppers, sour cream, and next 6 ingredients (sour cream through garlic) in a food processor. process until smooth, scraping sides of bowl occasionally.'),
('5753', '7', 'Place bell pepper mixture in a small bowl. Cover and chill.'),
('5753', '8', 'Bring 6 cups of water to a boil in a Dutch oven.'),
('5753', '9', 'Add shrimp. cook 3 minutes or until done.'),
('5753', '10', 'Drain and rinse with cold water. peel. Cover and chill shrimp.'),
('5753', '11', 'Serve shrimp with sauce.'),
('5754', '1', 'Preheat oven to 40'),
('5754', '2', 'Combine the first 7 ingredients in a bowl. stir well with a whisk.'),
('5754', '3', 'Place a 1-inch-thick layer of rock salt (about 3 pounds) in the bottom of a Dutch oven.'),
('5754', '4', 'Place the pan in oven at 400 for 30 minutes or until rock salt is very hot. Arrange shrimp in a single layer over rock salt. Cover and bake at 400 for 2 minutes. Turn shrimp over, and bake for an additional 2 minutes or until done.'),
('5754', '5', 'Serve the shrimp with vinaigrette.'),
('5755', '1', 'Combine first 3 ingredients. set aside.'),
('5755', '2', 'Cook bacon in a large nonstick skillet over medium heat until crisp.'),
('5755', '3', 'Add onion, bell pepper, and garlic to drippings in pan. cook 5 minutes or until tender, stirring occasionally. Stir in shrimp mixture, broth, and 1/4 cup green onions. cook 5 minutes or until shrimp are done, stirring frequently.'),
('5755', '4', 'Bring water to a boil in a medium saucepan. gradually add grits, stirring constantly. Reduce heat to low. simmer, covered, for 5 minutes or until thick, stirring occasionally. Stir in butter and salt.'),
('5755', '5', 'Serve shrimp mixture over grits. sprinkle with cheese and remaining green onions.'),
('5759', '1', 'Bring a large saucepan of water to a boil. In a large bowl, cover the mung bean noodles with warm water and let stand until pliable, about 5 minutes.'),
('5759', '2', 'Drain the noodles and cut them into 4-inch lengths. Boil the noodles until tender but still chewy, about 25 seconds.'),
('5759', '3', 'Drain and return the noodles to the pot. Rinse twice under cold water and drain. let stand in the colander.'),
('5759', '4', 'Season the shrimp with salt, white pepper and 1/2 teaspoon of the Sichuan peppercorns. In a large, deep skillet, heat 1 tablespoon of the vegetable oil until shimmering.'),
('5759', '5', 'Add the shrimp and cook over moderately high heat, turning once, until pink on the outside and white within, about 2 minutes.'),
('5759', '6', 'Transfer the shrimp to a plate.'),
('5759', '7', 'Add the remaining 2 tablespoons of vegetable oil to the skillet and heat until shimmering. Stir in the scallions and ginger and cook until fragrant, about 1 minute. Stir in the mung bean noodles, soy sauce, vinegar, chile oil and the remaining 1/2 teaspoon of Sichuan peppercorns and cook until heated through, about 1 minute.'),
('5759', '8', 'Add the shrimp and season with salt and white pepper.'),
('5759', '9', 'Transfer to shallow bowls and serve right away.'),
('5760', '1', 'In a large skillet, heat the vegetable oil.'),
('5760', '2', 'Add the bacon and cook over moderate heat, stirring occasionally, until most of the fat has been rendered. Spoon off all but 1 tablespoon of the fat from the skillet. Stir in the garlic and whole chiles and cook until fragrant, about 1 minute.'),
('5760', '3', 'Add the shrimp, season with salt and pepper and cook over moderately high heat, stirring occasionally, until they are pink and curled, about 3 minutes.'),
('5760', '4', 'Add the vermouth and cook until nearly evaporated, about 1 minute. Stir in the mint, transfer to plates and serve.'),
('5761', '1', 'In a small saucepan, cover the chorizo with water and bring to a boil. Simmer over moderate heat for 5 minutes, then drain. Thinly slice 1 of the sausages and finely chop the other.'),
('5761', '2', 'In a medium bowl, blend the butter with the scallions, pimentn and chopped chorizo and season with salt.'),
('5761', '3', 'In a large skillet, cook the sliced chorizo over very low heat until the fat is rendered, about 4 minutes.'),
('5761', '4', 'Add the shrimp and cook over moderate heat until barely pink, about 2 minutes per side.'),
('5761', '5', 'Add the brandy, tip the skillet and, using a long match, carefully ignite the brandy. When the flames die down, add the chorizo butter and cook, stirring, until just melted, about 2 minutes.'),
('5761', '6', 'Remove the skillet from the heat and stir in the water to make a creamy sauce.'),
('5761', '7', 'Transfer the shrimp and sauce to a shallow serving dish and garnish with the lemon wedges.'),
('5761', '8', 'Serve at once with crusty bread.'),
('5762', '1', 'Preheat the oven to 42'),
('5762', '2', 'Finely grate the zest of 1 orange. Using a sharp knife, peel both oranges, removing all of the bitter white pith. Thinly slice the oranges crosswise. set aside. In a large bowl, toss the shrimp with 2 tablespoons of the olive oil, 1 tablespoon of the tarragon and the salt, pepper and garlic.'),
('5762', '3', 'Heat a large ovenproof skillet.'),
('5762', '4', 'Add the shrimp in a single layer and cook over moderately high heat, stirring, for 1 minute.'),
('5762', '5', 'Remove the skillet from the heat.'),
('5762', '6', 'Roast the shrimp in the oven for 2 minutes. Using tongs, turn the shrimp and add the orange juice and zest. Roast for another 1 to 2 minutes, or until the shrimp are opaque throughout.'),
('5762', '7', 'Meanwhile, in a large bowl, whisk the vinegar into the remaining 2 tablespoons of oil.'),
('5762', '8', 'Whisk in the juices from the shrimp.'),
('5762', '9', 'Add the arugula and toss. transfer the salad to plates. Arrange the shrimp, oranges and onion on the salads, garnish with the remaining tarragon and serve.'),
('5763', '1', 'Preheat the oven to 40'),
('5763', '2', 'On a sheet of foil, drizzle the olive oil on the unpeeled garlic, wrap up and bake for 40 minutes.'),
('5763', '3', 'In a medium saucepan, bring the water to a boil, add the wax beans and cook them until just tender, about 4 minutes. Using a slotted spoon, transfer them to a large bowl.'),
('5763', '4', 'Add the sliced garlic, bay leaves, thyme, lemon zest and juice, cayenne and 1 1/2 teaspoons each of salt and pepper to the saucepan. Bring to a boil and cook for 5 minutes.'),
('5763', '5', 'Add the shrimp and simmer for 3 minutes.'),
('5763', '6', 'Transfer the shrimp to a baking sheet.'),
('5763', '7', 'Let the shrimp boil cool to room temperature, then return the shrimp to it.'),
('5763', '8', 'Peel the roasted garlic. In a mini food processor, puree the roasted garlic with the mustard, rice vinegar and honey. Slowly blend in the 1/4 cup of olive oil. Season with salt and pepper.'),
('5763', '9', 'Toss the wax beans with the edamame, chickpeas and dressing. Mound the salad on plates, top with the shrimp and serve.'),
('5764', '1', 'In a medium bowl, mix the flour with the sugar and 1 teaspoon of salt. Make a well in the center of the dry ingredients. stir in the ale, egg yolk, ginger and the 1 tablespoon of oil. Gradually stir the dry ingredients into the wet ingredients.'),
('5764', '2', 'Let the batter stand at room temperature for 20 minutes.'),
('5764', '3', 'Meanwhile, in a large, heavy saucepan, heat the 1 quart of oil to 36'),
('5764', '4', 'In a small bowl, whisk the egg white with a pinch of salt until stiff peaks form. Gently fold the egg white into the batter. Dip the shrimp into the batter, one at a time, letting any excess batter drip back into the bowl. Fry the shrimp in batches over moderate heat until golden and crisp, 2 to 3 minutes.'),
('5764', '5', 'Transfer the shrimp to paper towels to drain.'),
('5764', '6', 'Serve hot with the Green Herb Sauce.'),
('5770', '1', 'Melt Parkay in medium skillet over medium heat 3 minutes or until Parkay just starts to turn golden brown, stirring occasionally.'),
('5770', '2', 'Remove from heat.'),
('5770', '3', 'Add honey, vinegar, mustard and pepper flakes. stir with wire whisk until well blended.'),
('5770', '4', 'Return skillet to heat.'),
('5770', '5', 'Add shrimp. stir to coat evenly. Cook 4 minutes or just until shrimp turn pink, stirring occasionally.'),
('5770', '6', 'Spoon shrimp onto serving plate. top with mustard sauce.'),
('5771', '1', 'Peel, devein and remove tails from shrimp. Toss with arrowroot to combine and set aside. Use back of knife to smash garlic and proceed to mince. [img src=" http://www.everydaymaven.com/wp-content/uploads/2012/02/IMG_6174.jpg" width="550"]Peel ginger and grate with a microplane or fine grater.Thinly slice scallions and separate lights from dark greens.'),
('5771', '2', 'Combine light with garlic. Set aside dark green for garnish.'),
('5771', '3', 'Cut mango flesh into a small dice. Measure coconut milk, tomatoes and cut lime in half.'),
('5771', '4', 'Heat a large frying pan over medium high heat.'),
('5771', '5', 'Add oil. Once hot, toss in shrimp.Cook 4 to 5 minutes until pink, turning once or twice.'),
('5771', '6', 'Remove from pan and set aside.'),
('5771', '7', 'Add 1 teaspoon of chili oil and garlic, ginger and scallion whites. Cook, stirring constantly, for 20 seconds. Toss in mango, tomato, coconut milk and salt. Squeeze lime juice in and stir. Cook, stirring occasionally and scrapping bottom of frying pan for 5 to 7 minutes.'),
