INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('22228', '3', 'Remove from heat.'),
('22228', '4', 'Add the pine nuts and the remaining ingredients, and stir well.'),
('22228', '5', 'Serve at room temperature.'),
('22229', '1', 'Place first 5 ingredients in a food processor. process until smooth. With processor on, slowly add oil through food chute. Stir in salt and black pepper.'),
('22230', '1', 'Preheat broiler.'),
('22230', '2', 'Place bell pepper half, skin side up, on a foil-lined baking sheet. flatten with hand. Broil 15 minutes or until blackened.'),
('22230', '3', 'Place in a zip-top plastic bag. seal.'),
('22230', '4', 'Let stand 10 minutes. Peel and finely chop.'),
('22230', '5', 'Combine bell pepper, juice, and garlic, stirring well.'),
('22230', '6', 'Preheat oven to 45'),
('22230', '7', 'Heat a small nonstick skillet coated with cooking spray over medium-high heat.'),
('22230', '8', 'Add mushrooms and shallots. saut 2 minutes or until tender.'),
('22230', '9', 'Remove from heat. stir in vinegar.'),
('22230', '10', 'Place crust on a baking sheet coated with cooking spray.'),
('22230', '11', 'Spread bell pepper mixture evenly over crust, leaving a 1/2-inch border. Sprinkle basil evenly over bell pepper mixture. top with spinach. Spoon mushroom mixture evenly over spinach. sprinkle with cheese.'),
('22230', '12', 'Bake at 450 for 4 minutes or until cheese melts. Sprinkle with black pepper and salt.'),
('22231', '1', 'Dissolve yeast in water in a large bowl. let stand 5 minutes.'),
('22231', '2', 'Lightly spoon flour into dry measuring cups. level with a knife.'),
('22231', '3', 'Add 1 cup flour to yeast mixture, stirring well to combine. Cover and let stand at room temperature 8 hours or overnight to create a sponge (mixture will become very bubbly).'),
('22231', '4', 'Preheat oven to 35'),
('22231', '5', 'Remove papery skin from garlic head (do not peel or separate cloves). Wrap in foil.'),
('22231', '6', 'Bake at 350 for 1 hour. cool 10 minutes.'),
('22231', '7', 'Separate cloves. squeeze to extract garlic pulp. Discard skins.'),
('22231', '8', 'Place garlic pulp, 1 tablespoon oil, and 1 teaspoon salt in a small bowl, and mash with a fork until smooth. Stir into sponge.'),
('22231', '9', 'Add 2 cups flour to the sponge. stir until a soft dough forms. Turn dough out onto a floured surface. Knead until smooth and elastic (about 8 minutes). add enough of remaining flour, 1 tablespoon at a time, to prevent dough from sticking to hands (dough will feel tacky).'),
('22231', '10', 'Place dough in a large bowl coated with cooking spray, turning to coat top. Cover and let rise in a warm place (85), free from drafts, 45 minutes or until doubled in size. (Gently press 2 fingers into dough. If indentation remains, dough has risen enough.)'),
('22231', '11', 'Punch dough down. Cover and let rest 5 minutes. Divide dough in half. roll each half into a 10-inch round.'),
('22231', '12', 'Place 1 dough round on a baking sheet sprinkled with cornmeal. Arrange basil over dough, leaving a 1/4-inch border. top with bell peppers. Sprinkle evenly with cheese. Top with other dough round. pinch edges to seal. Lightly coat with cooking spray. Cover and let rise 45 minutes or until dough is doubled in size.'),
('22231', '13', 'Preheat oven to 40'),
('22231', '14', 'Uncover dough. Make indentations in top of dough with a knife. Gently brush dough with 1 1/2 teaspoons oil, and sprinkle with 1/4 teaspoon salt.'),
('22231', '15', 'Bake at 400 for 30 minutes or until the focaccia is browned on bottom and sounds hollow when tapped.'),
('22231', '16', 'Remove from pan. cool on a wire rack.'),
('22232', '1', 'Heat oil in a large nonstick skillet over medium-high heat.'),
('22232', '2', 'Add fennel, onion, and bell pepper. saute 6 minutes.'),
('22232', '3', 'Add broth and next 4 ingredients (broth through garlic). Cover, reduce heat, and simmer 20 minutes or until vegetables are tender. Stir in basil and fennel fronds.'),
('22233', '1', 'Cook the pasta according to package directions, omitting salt and fat.'),
('22233', '2', 'Heat oil in a large skillet over medium heat.'),
('22233', '3', 'Add onion, and cook 8 minutes or until tender, stirring frequently.'),
('22233', '4', 'Add bell peppers. cook 2 minutes or until heated through. Increase heat to medium-high. Stir in vinegar. cook 1 minute or until liquid evaporates.'),
('22233', '5', 'Remove from heat. cool 5 minutes.'),
('22233', '6', 'Place bell pepper mixture in a blender. process until smooth. Return bell pepper mixture to pan. cook over low heat until warm.'),
('22233', '7', 'Combine half-and-half and tomato paste in a small bowl, stirring with a whisk. Stir tomato mixture into bell pepper mixture, stirring with a whisk until well combined. Stir in ground red pepper.'),
('22233', '8', 'Combine pasta and bell pepper mixture in a large bowl.'),
('22233', '9', 'Add 1/2 cup cheese, tossing to coat. Spoon 1 1/3 cups pasta into each of 6 bowls. top each with about 1 1/2 tablespoons cheese.'),
('22233', '10', 'Garnish with basil, if desired.'),
('22234', '1', 'Bring water and 1/2 teaspoon salt to a boil.'),
('22234', '2', 'Add grits, butter, and garlic, stirring with a whisk. Reduce heat and simmer, uncovered, for 5 minutes.'),
('22234', '3', 'Remove from heat. stir in red pepper.'),
('22234', '4', 'While grits cook, heat a large nonstick skillet coated with cooking spray over medium-high heat. Sprinkle pork with 1/4 teaspoon salt and black pepper.'),
('22234', '5', 'Add pork to pan. cook 4 minutes on each side or until done.'),
('22234', '6', 'Remove from pan. Stir in vinegar and honey, scraping pan to loosen browned bits. Bring to a boil. cook 1 minute or until thick, stirring constantly with a whisk. Return pork to pan. turn to coat.'),
('22234', '7', 'Serve pork and sauce over grits.'),
('22235', '1', 'Heat oil in a Dutch oven over medium-high heat.'),
('22235', '2', 'Add bell pepper, carrot, and onion. cook 10 minutes or until tender, stirring occasionally.'),
('22235', '3', 'Add paprika and garlic. saut 1 minute.'),
('22235', '4', 'Add 3 cups broth and black pepper. bring to a boil. Cover, reduce heat, and simmer 20 minutes or until the vegetables are tender.'),
('22235', '5', 'Place one-third of vegetable mixture in a blender.'),
('22235', '6', 'Remove center piece of blender lid (to allow steam to escape). secure blender lid on blender.'),
('22235', '7', 'Place a clean towel over opening in blender lid (to avoid spills). Blend until smooth.'),
('22235', '8', 'Pour into a large bowl. Repeat procedure with remaining vegetable mixture.'),
('22235', '9', 'Return pureed vegetable mixture to Dutch oven. stir in remaining 2 cups broth and pumpkin. Cook over low heat for 10 minutes or until thoroughly heated, stirring frequently.'),
('22235', '10', 'Remove from heat. stir in juice. Ladle 1 cup soup into each of 7 bowls. top each serving with about 1 teaspoon pumpkinseeds and about 1/2 teaspoon parsley.'),
('22235', '11', 'Serve immediately.'),
('22237', '1', 'Combine the first 4 ingredients in a medium bowl.'),
('22237', '2', 'Heat 2 teaspoons oil in a large nonstick skillet coated with cooking spray over medium-high heat.'),
('22237', '3', 'Add pork, and cook for 8 minutes or until the pork loses its pink color.'),
('22237', '4', 'Remove from pan. keep warm.'),
('22237', '5', 'Heat 2 teaspoons oil in pan coated with cooking spray over medium-high heat.'),
('22237', '6', 'Add bell peppers, garlic, and 1/4 teaspoon salt, and saut 5 minutes or until tender. Divide pork evenly among tortillas. top each serving with 1/2 cup pepper mixture, 2 tablespoons cheese, and 2 tablespoons salsa, and fold.'),
('22237', '7', 'Serve with lime wedges, if desired.'),
('22238', '1', 'Cook pasta according to package directions, omitting salt and fat.'),
('22238', '2', 'Place bell pepper in a colander. drain pasta over bell pepper.'),
('22238', '3', 'Combine pasta, bell pepper, tomatoes, and remaining ingredients in a large bowl. toss gently.'),
('22238', '4', 'Serve immediately.'),
('22240', '1', 'In a large saucepan, cover the beans generously with water.'),
('22240', '2', 'Add 1 garlic clove and bring to a boil. Cover partially and simmer over low heat until the beans are almost tender, about 1 hour and 45 minutes.'),
('22240', '3', 'Add 1 1/2 teaspoons of salt and simmer until the beans are tender, about 20 minutes longer. Measure out and reserve 1/4 cup of the bean cooking liquid.'),
('22240', '4', 'Meanwhile, preheat the broiler. Flatten the red peppers with your hands and brush the skins with oil. arrange skin side up on a baking sheet. Broil 5 inches from the heat for about 8 minutes, or until the skins are blistered and charred in places.'),
('22240', '5', 'Transfer the peppers to a plate and stack them to steam and cool.'),
('22240', '6', 'Remove the skins and slice the peppers lengthwise into 1-inch strips.'),
('22240', '7', 'In a shallow bowl, pour the water over the bread and set aside for 5 minutes. Coarsely chop the 1 remaining garlic clove. In a food processor, combine the bread with the garlic, pine nuts, lemon juice, olive oil and 1/4 teaspoon salt.'),
('22240', '8', 'Add the reserved 1/4 cup of warm bean cooking liquid and puree until the sauce is smooth.'),
('22240', '9', 'Transfer to a serving bowl.'),
('22240', '10', 'Drain the beans thoroughly.'),
('22240', '11', 'Add them to the sauce along with 2 tablespoons of the parsley. fold them into the sauce. Season with salt and pepper.'),
('22240', '12', 'Garnish with the red peppers, olives and the remaining 1 tablespoon of parsley and serve.'),
('22245', '1', 'Preheat oven to 425F. Finely chop garlic cloves with cayenne pepper and saffron in mini processor.'),
('22245', '2', 'Add roasted red pepper and vinegar to processor. blend until almost smooth. Blend in mayonnaise. Season rouille to taste with salt and pepper.'),
('22245', '3', 'Transfer 1/3 cup rouille to medium bowl.'),
('22245', '4', 'Add shrimp and toss to coat. Arrange sourdough baguette slices on baking sheet.'),
('22245', '5', 'Spread each slice with rouille.'),
('22245', '6', 'Bake until bottoms of toasts are crisp and rouille is darker in color, about 10 minutes.'),
('22245', '7', 'Heat large nonstick skillet over medium-high heat.'),
('22245', '8', 'Add shrimp, spreading in single layer. Cook until just browned and opaque in center, about 2 minutes per side. Arrange toasts on plate.'),
('22245', '9', 'Place 2 shrimp on each toast. sprinkle toasts with capers.'),
('22248', '1', 'Preheat oven to 450F.'),
('22248', '2', 'Toss vegetables with oil, salt, and pepper in a bowl, then spread in an oiled large shallow (1-inch-deep) baking pan. Roast vegetables in middle of oven, stirring occasionally, until tender, 25 to 30 minutes. Cool in pan on a rack, then coarsely mash with a potato masher and stir in basil.'),
('22249', '1', 'Preheat oven to 350F. and butter a 13 x 9 x 2-inch glass baking dish (3-quart).'),
('22249', '2', 'Trim asparagus and diagonally cut into 1/4-inch-wide slices.'),
('22249', '3', 'Cut bell peppers into 1/4-inch-wide strips and mince shallots. Halve zucchini lengthwise and diagonally cut both zucchini and scallions into thin slices.'),
('22249', '4', 'Have ready a bowl of ice and cold water. In a large saucepan of boiling salted water blanch asparagus 1 minute and drain in a colander. Immediately transfer asparagus to ice water to stop cooking.'),
('22249', '5', 'Drain asparagus well in colander and pat dry.'),
('22249', '6', 'In a large skillet cook bell peppers and shallots in butter over moderately low heat, stirring occasionally, until peppers are softened, about 10 minutes. In a large bowl whisk together eggs, cream, parsley, salt, and pepper. Stir in asparagus, bell pepper mixture, zucchini, and scallions.'),
('22249', '7', 'Pour custard into baking dish and bake in middle of oven until golden and set, about 35 minutes. Cool frittata on a rack. Frittata may be made 1 day ahead and chilled, covered. Bring frittata to room temperature before serving. If desired, loosen frittata from edges of pan and slide onto a platter.'),
('22253', '1', 'Preheat oven to 450F.'),
('22253', '2', 'Cook bell peppers in oil in a large nonstick skillet over moderate heat, stirring, until softened, about 8 minutes, then cool.'),
('22253', '3', 'Unfold pastry sheets on a lightly floured surface and cut out an 8-inch round from each.'),
('22253', '4', 'Transfer rounds to a buttered large baking sheet and prick all over with a fork, leaving a 1/2-inch border around edges.'),
('22253', '5', 'Spread 2 tablespoons cheese evenly over each round, then scatter with peppers and sprinkle with thyme, kosher salt, and pepper to taste.'),
('22253', '6', 'Bake tarts in middle of oven until puffed and golden brown, about 15 minutes, then transfer to a rack to cool slightly.'),
('22253', '7', 'Cut each tart into 8 wedges and serve warm.'),
('22254', '1', 'To prepare dressing, combine first 9 ingredients in a bowl. stir with a whisk.'),
('22254', '2', 'Preheat broiler.'),
('22254', '3', 'To prepare salad, combine 3 tablespoons dressing and eggplant, tossing to coat. Arrange eggplant slices in a single layer on a baking sheet coated with cooking spray. Broil 4 minutes on each side.'),
('22254', '4', 'Combine remaining dressing, eggplant, jicama, and bell peppers, tossing to coat.'),
('22257', '1', 'Combine first 3 ingredients and 1/4 teaspoon crushed red pepper in a bowl. Set aside.'),
('22257', '2', 'Drain pineapple, reserving 1/4 cup juice.'),
('22257', '3', 'Combine reserved juice, 6 tablespoons stock, ketchup, next 3 ingredients, and remaining 1/4 teaspoon crushed red pepper in a small bowl, stirring until sugar dissolves.'),
('22257', '4', 'Combine cornstarch and remaining stock in another small bowl.'),
('22257', '5', 'Heat oil in a large nonstick skillet over medium-high heat. Stir-fry pork mixture in hot oil 5 minutes or until pork is done.'),
('22257', '6', 'Remove pork from pan. keep warm.'),
('22257', '7', 'Add onion, bell peppers, and water chestnuts to pan. stir-fry 3 minutes or until crisp-tender.'),
('22257', '8', 'Add ketchup mixture. Bring to a boil. stir in cornstarch mixture, pineapple chunks, and pork mixture with any accumulated juices. Cook 2 minutes or until sauce thickens.'),
('22257', '9', 'Serve immediately over rice.'),
('22257', '10', 'Garnish with green onion slices, if desired.'),
('22261', '1', 'To prepare dressing, combine first 4 ingredients in a small bowl. stir with a whisk. Set aside.'),
('22261', '2', 'To prepare stir-fry, bring water to a boil in a small saucepan. Stir in the quinoa. cover, reduce heat, and simmer 10 minutes.'),
('22261', '3', 'Remove from heat.'),
('22261', '4', 'Let stand, covered, 10 minutes. fluff with a fork.'),
('22261', '5', 'Heat 1 tablespoon oil in a large nonstick skillet over medium-high heat.'),
('22261', '6', 'Add onion and garlic, and stir-fry 5 minutes.'),
('22261', '7', 'Add the bell pepper, mushrooms, asparagus, salt, and tofu. stir-fry 3 minutes. Stir in dressing.'),
('22261', '8', 'Serve over quinoa, and sprinkle with sesame seeds.'),
('22262', '1', 'Prepare grill to medium-high heat.'),
('22262', '2', 'Combine balsamic vinegar, olive oil, and garlic in a large bowl.'),
('22262', '3', 'Add bell peppers and portobello mushrooms. toss gently to coat.'),
('22262', '4', 'Remove vegetables from vinegar mixture, and discard vinegar mixture.'),
('22262', '5', 'Place bell peppers and mushrooms on a grill rack coated with cooking spray. grill 4 minutes on each side.'),
('22262', '6', 'Remove vegetables from grill. cool slightly.'),
('22262', '7', 'Cut bell peppers into thin strips.'),
('22262', '8', 'Combine bell peppers, basil, salt, and black pepper in a small bowl.'),
('22262', '9', 'Cut rolls in half horizontally. spread cheese evenly over cut sides of rolls. Arrange 1 mushroom cap on bottom half of each roll. top each serving with about 1/3 cup bell pepper mixture and top half of roll.'),
('22262', '10', 'Place sandwiches on grill rack coated with cooking spray.'),
('22262', '11', 'Place a cast-iron or other heavy skillet on top of sandwiches. press gently to flatten. Grill 3 minutes on each side or until bread is toasted (leave cast-iron skillet on sandwiches while they cook).'),
('22263', '1', 'Heat 2 teaspoons oil in a large nonstick skillet over medium-high heat. Sprinkle 1/4 teaspoon salt over chicken.'),
('22263', '2', 'Add chicken to pan. cook 1 minute on each side or until lightly browned.'),
('22263', '3', 'Add 1/4 cup vinegar. cook 2 minutes or until chicken is done and vinegar is syrupy.'),
('22263', '4', 'Remove chicken mixture from the pan. cover and keep warm. Wipe pan clean with a paper towel.'),
('22263', '5', 'Return pan to medium-high heat. add remaining 2 teaspoons oil.'),
('22263', '6', 'Add bell pepper and onion. saut 7 minutes or until tender. Stir in remaining 1/4 teaspoon salt and remaining 1/4 cup vinegar. cook 1 minute or until vinegar is syrupy.'),
('22263', '7', 'Arrange chicken mixture evenly over bottom halves of bread. top with bell pepper mixture. Arrange cheese over pepper mixture, and sprinkle with black pepper. Top with top halves of bread.'),
('22263', '8', 'Place a cast-iron or heavy skillet on top of sandwiches. let stand 5 minutes.'),
('22263', '9', 'Cut each sandwich into 6 wedges.'),
('22264', '1', 'Heat oven to 400 F.'),
('22264', '2', 'Heat 1 tablespoon of the oil in a large ovenproof skillet over medium heat.'),
('22264', '3', 'Add the sausage and cook, turning once, until it starts to brown, 5 minutes.'),
('22264', '4', 'Add the onions, 1/2 teaspoon salt, and 1/2 teaspoon pepper and cook, stirring, for 4 minutes.'),
('22264', '5', 'Add the bell peppers and garlic and cook until they are just soft, about 4 minutes. Stir in the wine and thyme.'),
('22264', '6', 'Transfer the skillet to oven. Roast until the sausage is cooked through, about 15 minutes.'),
('22264', '7', 'Heat the remaining oil in a large nonstick skillet over medium-high heat. Cook the polenta in batches, turning once, until golden brown.'),
('22264', '8', 'Place the polenta on a platter. Spoon the sausage, vegetables, and pan juices over the top.'),
('22264', '9', 'Serve with the crusty bread, if desired.Tip: Logs of ready-to-eat polenta are a cook''s secret weapon. Sold in the international section of the supermarket, the corn-meal mixture can be sliced into rounds to bake, broil, or sear. Use polenta as a base for fish, chicken, or hors d''oeuvres.'),
('22266', '1', 'Cut orange in half crosswise. slice about 1/4 inch from bottom of each half so they will sit flat.'),
('22266', '2', 'Cut bell pepper in half lengthwise. discard seeds and membranes.'),
('22266', '3', 'Place orange halves, cut side up, and pepper halves, skin side up, on a foil-lined baking sheet. flatten peppers with hand. Broil 15 minutes or until blackened.'),
('22266', '4', 'Place pepper halves in zip-top plastic bag. seal.'),
('22266', '5', 'Let stand 20 minutes. peel. Squeeze juice from orange over a bowl to equal 1/4 cup. discard oranges.'),
('22266', '6', 'Place peppers and orange juice in a food processor or blender. set aside.'),
('22266', '7', 'Heat margarine in a small saucepan over medium heat.'),
('22266', '8', 'Add onion and carrot. saut 12 minutes or until carrot is tender.'),
('22266', '9', 'Add onion mixture to food processor. process until smooth.'),
('22266', '10', 'Combine flour, broth, and milk in saucepan. stir with a whisk until blended.'),
('22266', '11', 'Place over medium heat. bring to a boil. Reduce heat. add pepper mixture, salt, pepper, and paprika. simmer 10 minutes, stirring occasionally.'),
('22266', '12', 'Garnish with oranges, if desired.'),
('22267', '1', 'Heat olive oil in a large nonstick skillet coated with cooking spray over medium-high heat.'),
('22267', '2', 'Add sliced mushrooms and bell pepper. saut 4 minutes.'),
('22267', '3', 'Add minced garlic, and saut 30 seconds.'),
('22267', '4', 'Add Caramelized Onions, chicken broth, salt, black pepper, and red pepper. bring to a simmer.'),
('22267', '5', 'Remove from heat. stir in sour cream and oregano.'),
('22267', '6', 'Serve over pasta, and garnish with oregano sprigs, if desired.'),
('22268', '1', 'Preheat the oven to 350 degrees Fahrenheit and oil a 13x7 or 13x9-inch baking pan. In a food processor or high-powered blender, combine all of the sauce ingredients. Blend until smooth. If you taste the sauce now, you may find by the raw onion flavor overpowering. Dont worry, it will mellow out thanks to the lime and after spending time in the oven.In a medium skillet over medium heat, add the olive oil and chopped onion. Saut for a few minutes, until the onion starts to turn translucent and starts lightly browning around the edges.'),
('22268', '2', 'Add the frozen spinach and corn and cook until warmed through and the juices have mostly evaporated.'),
('22268', '3', 'Add the black beans and green chiles and cook until warmed through.'),
('22268', '4', 'Remove from heat and pour in  cup enchilada sauce and feta cheese.'),
('22268', '5', 'Mix and add salt and pepper to taste.Gently warm the tortillas so they dont break when you roll them. The easiest way to do this is to place them in a stack in the microwave under a damp paper towel and microwave for about 60 seconds. Leave the paper towel on top to keep them warm as you roll. Working one at a time, lump a scant  cup filling down the middle of each tortilla and roll snugly.'),
('22268', '6', 'Place it with the seam side down in your baking dish. Repeat with the remaining tortillas, placing each rolled enchilada snugly next to the other until you have used up all your tortillas.'),
('22268', '7', 'Pour the enchilada sauce down the middle of your row of enchiladas and give the pan some little shakes to help distribute it. Sprinkle the Jack cheese down the middle.'),
('22268', '8', 'Bake the enchiladas for 20 to 25 minutes, until the cheese is melted, the enchiladas are warmed through and the top of the tortillas are just crisp.'),
('22268', '9', 'Let the enchiladas cool for five minutes, during which you can pit, peel and dice the avocados.'),
('22268', '10', 'Combine them in a bowl with chopped cilantro and toss with a big squeeze of lime juice. Divide the enchiladas onto plates, top with a healthy amount of the avocado mix and serve.'),
('22269', '1', 'Cook orzo according to package directions, omitting salt and fat.'),
('22269', '2', 'While orzo cooks, heat 2 teaspoons olive oil in a large nonstick skillet over medium-high heat. Sprinkle chicken with salt, black pepper, and red pepper.'),
('22269', '3', 'Add chicken to pan, and cook 4 minutes on each side or until done.'),
('22269', '4', 'Remove chicken from pan, and keep warm.'),
('22269', '5', 'Add the remaining 2 teaspoons olive oil and bell peppers to pan. saut 2 minutes.'),
('22269', '6', 'Add oregano and garlic. saut 1 minute.'),
('22269', '7', 'Remove from heat, and stir in lemon juice.'),
('22269', '8', 'Combine orzo and feta, and serve with chicken and bell pepper mixture.'),
('22276', '1', 'Place all ingredients in a food processor, and process until smooth.'),
('22282', '1', 'Heat olive oil in a large nonstick skillet over medium-high heat.'),
('22282', '2', 'Add broccoli, kosher salt, crushed red pepper, and sliced garlic. Saut 2 minutes.'),
('22282', '3', 'Add 1/4 cup water. Cover, reduce heat to low, and cook for 2 minutes or until broccoli is crisp-tender.'),
('22284', '1', 'Arrange the tomatoes, skin side down, on a baking sheet. Coat the bell pepper and onions with olive oil and put them on the other baking sheet along with the garlic, place the pepper skin side down as well. Give both sheets a light showering of salt, then bake until the tomatoes start to collapse and the onions start to brown and caramelize, about 45 minutes. Turn the onions if they start getting overly dark on the bottom .Check on the garlic as well, once the cloves are golden and oozy inside, pull them from the oven.'),
('22284', '2', 'Peel the garlic, dump all of the roasted vegetables into a big, high-sided bowl, and puree with a hand blender. Alternately, use a conventional blender or food processor and work in batches. Blend in a cup of the stock, and keep adding the rest 1/2 cup at a time until the soup is the desired consistency. I like a little chunk and texture to this soup particularly if the weather has a bit of a chill, but smooth or chunky is your call.'),
('22284', '3', 'Add the paprika and a bit more salt if needed - adjusting to your taste.'),
('22284', '4', 'Serves'),
('22284', '5', 'Print Recipe'),
('22284', '6', 'September 25, 2008'),
('22284', '7', 'If you make this recipe, I''d love to see it - tag it #101cookbooks on Instagram!'),
('22296', '1', 'Preheat oven to 35'),
('22296', '2', 'Spread pesto on 1 side of each bread slice.'),
('22296', '3', 'Cut each bread slice into 1/2- to 1-inch cubes.'),
('22296', '4', 'Place bread cubes in a single layer on a lightly greased aluminum foil-lined jelly-roll pan.'),
('22296', '5', 'Bake at 350 for 16 to 20 minutes or until golden, turning once after 10 minutes.'),
('22296', '6', 'Remove from oven, and let cool.'),
('22296', '7', 'Melt butter with oil in a large Dutch oven over medium-high heat.'),
('22296', '8', 'Add garlic and shallot, and cook, stirring constantly, 2 minutes or until vegetables are tender.'),
('22296', '9', 'Add tomato paste, and cook, stirring constantly, 1 minute. Stir in bell peppers and chicken broth. bring to a boil. Reduce heat to medium, and simmer, stirring occasionally, 5 minutes.'),
('22296', '10', 'Remove from heat. let cool 10 minutes.'),
('22296', '11', 'Process red pepper mixture, in batches, in a blender or food processor 8 to 10 seconds until smooth, stopping to scrape down sides. Return red pepper mixture to Dutch oven. stir in half-and-half and parsley, and cook over medium heat 5 minutes or until thoroughly heated. Season with salt and pepper to taste.'),
('22296', '12', 'Ladle soup into 6 bowls. top with croutons.'),
('22296', '13', 'Garnish, if desired.'),
('22298', '1', 'Heat unsalted butter and olive oil in a medium skillet over medium heat.'),
('22298', '2', 'Add bell pepper, onion, and kosher salt. Cook until soft and golden, 7 to 8 minutes.'),
('22299', '1', 'Mix together soy sauce, sherry, brown sugar, cornstarch, ginger, garlic, and chili paste (or chili oil.)'),
('22299', '2', 'Place sliced beef in the mixture and toss to coat. Set aside.'),
('22299', '3', 'Heat 1 tablespoon oil in a large skillet over medium-high to high heat. When it is very hot, throw in the onions and cook for less than a minute.'),
('22299', '4', 'Remove to a separate plate. Return skillet to flame, allow to reheat, and add bell peppers (and hot pepper/jalapeno if using.) Cook for a minute, tossing, until peppers have brown/black bits but are still firm.'),
('22299', '5', 'Remove to a plate. Return skillet to heat and allow to get hot.'),
('22299', '6', 'Add the remaining tablespoon of oil to the skillet.'),
('22299', '7', 'Add 1/3 of the meat mixture, evenly distributing over the surface of the skillet. Allow to sit for 20 to 30 seconds, then turn with tongs. Cook for another 30 seconds, then remove to a separate plate. Repeat with remaining meat until all brown.Reduce heat to low.'),
('22299', '8', 'Add all meat, onions, and peppers to the skillet and toss to combine.'),
('22299', '9', 'Pour in remaining sauce (the sauce the meat marinated in*) and stir. Allow to simmer on low for a few minutes. Sauce will slowly thicken. Turn off heat. *Update/Note: you can also whip up an extra batch of liquid if you do not want to use the same liquid you use for the meat. Turn off boiling water, then throw in noodles. Stir, then allow noodles to sit in hot water for 8 minutes or so (check package directions to be sure.)'),
('22299', '10', 'Drain, then add 1/2 the noodles to stir fry. Toss together, then add more noodles to taste.'),
('22299', '11', 'Add very hot water if needed to thin. Top with cilantro leaves.'),
('22299', '12', 'Serve immediately.'),
('22300', '1', 'Preheat the oven to 40'),
('22300', '2', 'Lightly oil two 6-by-3 1/2-inch metal loaf pans. In a skillet, heat 2 tablespoons of the oil.'),
('22300', '3', 'Add the carrot, celery, garlic and two-thirds of the onion. season with salt and white pepper and cook over moderate heat, stirring, until softened, about 10 minutes.'),
('22300', '4', 'Let cool.'),
('22300', '5', 'Add the turkey and cooked vegetables to a large bowl.'),
('22300', '6', 'Add the egg whites, panko, cottage cheese, 2 teaspoons of salt and  1/2 teaspoon of white pepper. Knead until blended and divide between the pans.'),
('22300', '7', 'Place the pans on a baking sheet and bake in the upper third of the oven for 35 minutes or until an instant-read thermometer registers 16'),
('22300', '8', 'Remove from the oven and preheat the broiler.'),
('22300', '9', 'Meanwhile, in a skillet, heat 2 tablespoons of the oil.'),
('22300', '10', 'Add two-thirds of the red peppers, the remaining onion and the thyme. Cover and cook over moderate heat until softened, 10 minutes.'),
('22300', '11', 'Add the water, cover and simmer until the peppers are very tender, 7 minutes. Discard the thyme.'),
('22300', '12', 'Transfer the contents of the skillet to a blender, add the half-and-half and puree. Season with salt and pepper.'),
('22300', '13', 'In a skillet, heat the remaining 1 tablespoon of oil.'),
('22300', '14', 'Add the remaining peppers and cook over moderate heat until softened, 10 minutes. Season with salt and pepper.'),
('22300', '15', 'Broil the meat loaves 4 inches from the heat until browned, 2 minutes. Turn the loaves out onto a plate and cut into  1/2-inch slices. Spoon the pepper sauce onto plates. Top with the meat loaf and peppers.'),
('22300', '16', 'Serve with wild rice and the remaining sauce.'),
('22302', '1', 'Cut tofu crosswise into 4 slices.'),
('22302', '2', 'Place tofu slices on several layers of heavy-duty paper towels. cover with additional paper towels.'),
('22302', '3', 'Let stand 30 minutes, pressing down occasionally.'),
('22302', '4', 'Combine basil and next 8 ingredients (through garlic) in a large zip-top plastic bag.'),
('22302', '5', 'Add tofu to bag. seal. Marinate in refrigerator 1 hour, turning bag occasionally.'),
('22302', '6', 'Place flour in a shallow dish.'),
('22302', '7', 'Place egg substitute in another shallow dish.'),
('22302', '8', 'Place panko in another shallow dish.'),
('22302', '9', 'Remove tofu from marinade, reserving remaining marinade. Working with one tofu piece at a time, dredge tofu in flour, shaking off excess. Dip tofu in egg substitute, allowing excess to drip off. Coat tofu completely with panko, pressing lightly to adhere. Set aside. Repeat procedure with remaining tofu, flour, egg substitute, and panko.'),
('22302', '10', 'Heat a large nonstick skillet over medium-high heat.'),
('22302', '11', 'Add olive oil to pan, swirling to coat.'),
('22302', '12', 'Add tofu to pan. reduce heat to medium, and cook for 4 minutes on each side or until browned.'),
('22302', '13', 'Remove tofu from pan, and keep warm.'),
('22302', '14', 'Combine reserved marinade, walnuts, and bell peppers in a blender. process until smooth (about 2 minutes).'),
('22302', '15', 'Pour bell pepper mixture into pan. cook over medium-high heat 2 minutes or until thoroughly heated.'),
('22302', '16', 'Serve with tofu.'),
('22303', '1', 'Preheat broiler.'),
('22303', '2', 'Cut bell peppers in half lengthwise. discard seeds and membranes.'),
('22303', '3', 'Place pepper halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 15 minutes or until blackened.'),
('22303', '4', 'Place in a paper bag. fold to close tightly.'),
('22303', '5', 'Let stand 20 minutes. Peel and chop. set aside.'),
('22303', '6', 'Cook fettuccine according to the package directions, omitting salt and fat. drain well. Set aside. keep warm.'),
('22303', '7', 'Heat 2 tablespoons olive oil and butter in a large skillet over medium-high heat.'),
('22303', '8', 'Add chopped onion and garlic to pan, and cook for 4 minutes or until the onion is tender, stirring frequently.'),
('22303', '9', 'Add shrimp to the pan, and cook for 2 minutes.'),
('22303', '10', 'Add bell peppers and 1/4 cup lemon juice to the pan, and cook for 4 minutes or until the shrimp are done and half of the liquid has evaporated.'),
('22303', '11', 'Add chopped parsley and the next 5 ingredients (through 1/2 teaspoon crushed red pepper) to the shrimp mixture.'),
('22303', '12', 'Remove pan from heat.'),
('22303', '13', 'Combine cooked fettuccine and 1 teaspoon olive oil in a large bowl. toss well.'),
('22303', '14', 'Add shrimp mixture, tossing gently to coat. Top each serving with cheese.'),
('22304', '1', 'Rinse beans under cold water, sorting out any rocks/particles.'),
('22304', '2', 'Place beans in a stock pot with the ham hock and cover with water by 2 inches. Bring to a boil, then reduce to a simmer. Cover the pot and simmer for 2 hours, checking occasionally to make sure the water level is fine.'),
('22304', '3', 'Add more water as needed.Then throw in diced onion, red bell pepper, garlic and jalapeno. Cover and continue cooking for another hour or two, remembering to check the water level.'),
('22304', '4', 'Add salt, chili powder (if desired) and pepper, then cover and cook for another 20 to 30 minutes, or until beans are lovely and tender.'),
('22304', '5', 'Serve with cornbread as a meal, or spoon on top of nachos, tacos, etc.'),
('22309', '1', 'Preheat oven to 375 degrees.In a large ovenproof skillet, melt butter and olive oil over medium-high heat.'),
('22309', '2', 'Add chicken and brown on both sides.'),
('22309', '3', 'Remove chicken to a clean plate.Reduce heat to medium.'),
('22309', '4', 'Add onions, garlic, and green bell pepper to the pan. Stir and cook for a couple of minutes.'),
('22309', '5', 'Add tomatoes and cook for a minute or two. Season with salt and pepper.'),
('22309', '6', 'Pour in wine and stir.'),
('22309', '7', 'Add chicken pieces back to pan, cover with lid, and place into the oven for 45 minutes.'),
('22309', '8', 'Remove pan from oven and remove lid.'),
('22309', '9', 'Add whole green olives and heavy cream (drizzle evenly over the top.) Put on lid and shake the pan to "stir" in the cream. Return to the oven for 15 to 20 minutes to thicken the sauce.'),
('22309', '10', 'Remove from oven and keep lid on until ready to serve.'),
('22309', '11', 'Place pasta into a large serving bowl or onto a large serving platter. Arrange chicken pieces on top of the pasta, then pour all of the sauce over the top. Can sprinkle with minced fresh parsley and Parmesan, if desired.You''ll love this!'),
('22310', '1', 'Combine the salsa, pepper, and onion.'),
('22310', '2', 'Serve with tortilla chips.'),
('22312', '1', 'Combine all ingredients in a small, heavy saucepan over medium-low heat. Cook 10 minutes, stirring occasionally.'),
('22312', '2', 'Remove from heat. cool 10 minutes. Store in an airtight container in refrigerator up to 1 month.'),
('22314', '1', 'Preheat oven to 350F. Mist a 9-inch square ovenproof glass baking dish with cooking spray.'),
('22314', '2', 'In a blender, combine eggs, cream, sugar, butter, flour, baking powder and salt. blend.'),
('22314', '3', 'Add corn and blend until mixture is nearly smooth. Stir in scallions and bell pepper.'),
('22314', '4', 'Pour into dish and bake until set, with golden brown top, 45 to 50 minutes.'),
('22314', '5', 'Remove from oven and let pudding rest for 5 to 10 minutes before serving.'),
('22322', '1', 'Combine olive oil, lime juice, garlic, chipotle peppers, and cilantro in the bowl of a food processor or a blender. Blend until totally combined.'),
('22322', '2', 'Place flank steak into a large plastic bag or baking dish.'),
('22322', '3', 'Pour in marinade and make sure it adequately coats the meat. Seal bag or cover tightly and refrigerate for 24 hours at least. When ready to make the nachos, preheat oven to 350 degrees.'),
('22322', '4', 'Heat an outdoor grill or an indoor grill pan (or you can use a skillet).'),
('22322', '5', 'Drizzle a little olive oil on the grill and grill the meat over very high heat, about 4 minutes per side. (Turn 45 degrees halfway through on both sides to get nifty grill marks.)'),
('22322', '6', 'Remove steak from grill and set aside to rest.In a large skillet, heat a couple of tablespoons of olive oil over medium-high heat.'),
('22322', '7', 'Add onions and peppers and cook for 3 to 5 minutes, or until vegetables are somewhat soft and starting to get black bits.'),
('22322', '8', 'Remove from heat and set aside. Slice half of the flank steak into strips against the grain, then chop slices into smaller bites.'),
('22322', '9', 'Place sauteed veggies on a cutting board and roughly chop to get them into smaller pieces. Arrange tortilla chips on a large ovenproof platter (or cookie sheet.) Sprinkle plenty of cheese all over the top.'),
('22322', '10', 'Place platter in oven for 3 minutes or so, just long enough to melt the cheese (but not burn the chips.)'),
('22322', '11', 'Remove from oven, then generously sprinkle peppers, onions, and chopped steak all over the top. Return to oven for no more than another minute---just long enough to heat up the meat and peppers (but not cook the meat all the way through.)'),
('22322', '12', 'Remove from oven and plop guacamole all over the top.'),
('22322', '13', 'Serve immediately with salsa and sour cream. Use the rest of the meat for more nachos...or make real fajitas!'),
('22324', '1', 'Blacken and peel the red peppers: Arrange the red peppers on a broiling pan and place them under a hot broiler so that their upper surfaces are about 1/2 inch from the heat.'),
('22324', '2', 'Broil for 15 minutes, turning occasionally, until the peppers are blistered and black on all sides. (You can alternatively blacken the peppers directly over the open flame of a gas cook-top, holding them and turning them with tongs.)'),
('22324', '3', 'Place them in a bowl and cover the bowl with a plate.'),
('22324', '4', 'Let the peppers steam in their own residual heat inside the bowl for 10 minutes. Then peel them (the skin will slide off) and remove the seeds.'),
('22324', '5', 'Note that Trader Joe''s makes an excellent bottled cooked red pepper that can be used as a shortcut to the above step.'),
('22340', '1', 'Cook pasta according to package directions, omitting salt and fat.'),
('22340', '2', 'Drain. keep warm.'),
('22340', '3', 'Heat oil in a large saucepan over medium-high heat.'),
('22340', '4', 'Add the onion and garlic. saut 5 minutes or until tender.'),
('22340', '5', 'Add bell pepper, salt, and ground red pepper. saut 2 minutes.'),
('22340', '6', 'Add tomatoes and wine. bring to a boil. Reduce heat to low, and simmer 10 minutes.'),
('22340', '7', 'Add mussels, and increase heat to medium. Cover and simmer for 7 minutes or until shells open. Discard any unopened shells.'),
('22340', '8', 'Serve mussel mixture over pasta. sprinkle with parsley.'),
('22342', '1', 'Cook bacon in a large nonstick skillet over medium-high heat until crisp.'),
('22342', '2', 'Remove bacon from skillet. crumble and set aside. Sprinkle chicken with salt and black pepper.'),
('22342', '3', 'Add chicken to bacon drippings in pan. saut 2 minutes on each side.'),
('22342', '4', 'Remove chicken from pan.'),
('22342', '5', 'Add onion, coriander, garlic, and chile to pan. saut 3 minutes. Stir in salsa and bell peppers. Return chicken to pan. Cover and cook over medium heat 12 minutes or until chicken is done. Sprinkle with crumbled bacon. garnish with cilantro, if desired.'),
('22344', '1', 'Preheat broiler.'),
('22344', '2', 'Cut bell peppers in half lengthwise. discard seeds and membranes.'),
('22344', '3', 'Place pepper halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 20 minutes or until blackened.'),
('22344', '4', 'Place in a zip-top plastic bag. seal.'),
('22344', '5', 'Let stand 20 minutes. Peel and cut into strips.'),
('22344', '6', 'Place peppers in beaker of an immersion blender. add oil. Puree until smooth.'),
('22344', '7', 'Transfer puree to a bowl. Stir in 1/8 teaspoon salt and 1/8 teaspoon black pepper.'),
('22344', '8', 'Heat a large, heavy saucepan over medium-low heat. Coat pan with cooking spray.'),
('22344', '9', 'Add onion to pan. cover and cook 5 minutes or until tender, stirring occasionally.'),
('22344', '10', 'Add sliced fennel and fennel seeds to pan. cover and cook over medium-low heat 8 minutes or until sliced fennel is tender. Increase heat to medium-high.'),
('22344', '11', 'Add zucchini and garlic to pan, and cook 3 minutes, stirring constantly.'),
('22344', '12', 'Add broth. bring to a boil. Cover, reduce heat, and simmer 20 minutes or until vegetables are tender.'),
('22344', '13', 'Place vegetable mixture, 1/4 teaspoon salt, and 1/4 teaspoon black pepper in beaker of an immersion blender. puree until smooth.'),
('22344', '14', 'Pour 1 cup soup into each of 6 bowls. top each serving with 1/3 cup pepper puree.'),
('22347', '1', 'Preheat a gas grill to medium. Oil grates. grill peppers, turning once or twice, until charred, 10 to 15 minutes.'),
('22347', '2', 'Transfer to a bowl. cover tightly.'),
('22347', '3', 'Let stand 10 minutes.'),
('22347', '4', 'Remove from bowl. scrape away skin.'),
('22347', '5', 'Brush corn with 1 Tbsp. olive oil. season with salt and pepper. Grill corn, turning, until lightly charred, 7 to 10 minutes.'),
('22347', '6', 'Remove from heat and cool.'),
('22347', '7', 'In a large bowl, whisk vinegar and mustard. Season with salt and pepper and whisk in remaining olive oil. Dice peppers. cut corn kernels from cobs.'),
('22347', '8', 'Mix peppers, corn, scallions and cilantro in bowl with dressing and toss. Season with salt and pepper.'),
('22347', '9', 'Serve at room temperature.'),
('22348', '1', 'Preheat oven to 400F.'),
('22348', '2', 'Cut off top of garlic head, place on a piece of foil, drizzle with oil and sprinkle with salt and pepper. Wrap tightly and roast until tender, 30 to 40 minutes.'),
('22348', '3', 'Let cool.'),
('22348', '4', 'Over an open flame or under a preheated broiler, cook bell pepper, turning frequently with tongs, until blackened all over.'),
('22348', '5', 'Place in a paper bag, close tightly and allow pepper to sweat for 10 minutes. Slip off pepper skin with your fingers.'),
('22348', '6', 'Roughly chop pepper, discarding seeds and membranes. Squeeze garlic cloves out of skins.'),
('22348', '7', 'Place pepper and garlic in food processor. add cumin, coriander and sour cream. puree until smooth. Season with salt and cayenne pepper. Cover and chill.'),
('22348', '8', 'Serve with assorted crudits and crackers.'),
('22349', '1', 'Stir together first 4 ingredients in a medium-size microwave-safe bowl. Microwave at HIGH 3 minutes. Stir in rice, and microwave at HIGH 2 minutes.'),
('22349', '2', 'Stir in 2 3/4 cups broth and 1/4 cup wine. Cover tightly with plastic wrap. (Do not vent.) Microwave at HIGH 9 minutes. Carefully swirl bowl without uncovering (to incorporate the mixture), and microwave at HIGH 8 minutes. Carefully remove and discard plastic wrap. Stir in cheese and 1/4 cup chicken broth, stirring 30 seconds to 1 minute or until creamy.'),
('22349', '3', 'Add up to 1/4 cup additional broth, 1 Tbsp. at a time, for desired consistency. Season with salt and pepper to taste.'),
('22349', '4', 'Stir in red peppers and spinach, and microwave at HIGH 1 minute or until spinach is wilted.'),
('22349', '5', 'Note: We tested with a 1,100-watt microwave oven and a 1 1/2-liter glass bowl. We found that press-and-seal plastic wrap will not work in this application.'),
('22350', '1', 'Combine first 8 ingredients in large bowl. whisk to blend. Season soup to taste with sea salt and freshly ground black pepper. Cover and refrigerate until well chilled and flavors blend, at least 2 hours. DO AHEAD: Can be made 6 hours ahead. Keep chilled.'),
('22350', '2', 'Ladle soup into 4 bowls. Top each with 1 goat cheese round and 3 grape tomato halves. Sprinkle with freshly ground black pepper and basil.'),
('22350', '3', 'Drizzle with oil and serve.'),
('22351', '1', 'Preheat oven to 350F. Butter 13x9x2-inch ceramic or glass baking dish.'),
('22351', '2', 'Whiskfirst 7 ingredients in large bowl. sprinklegenerously with pepper. Set aside.'),
('22351', '3', 'Place sausage in large nonstick skillet.push to 1 side.'),
('22351', '4', 'Add bell pepper to other sideof skillet.'),
('22351', '5', 'Sauteacute. over high heat, breaking upsausage with fork, until sausage is cookedthrough and bell peppers are brown in spots,about 7 minutes.'),
('22351', '6', 'Arrange half of bread slices in prepareddish.'),
('22351', '7', 'Pour half of egg mixture over. Sprinklewith half of cheese, then half of sausagepeppermixture. Repeat layering.'),
('22351', '8', 'Let stand20 minutes, occasionally pressing on breadto submerge.'),
('22351', '9', 'Bake strata until puffed andbrown, about 1 hour. Cool slightly.'),
('22351', '10', 'Per serving: 549.86 (kcal) calories,   51.7 % calories from fat,'),
('22351', '11', 'Bon Appetit'),
('22352', '1', 'Heat oil in heavy wide pot over medium-high heat. Sprinkle chicken with salt and pepper. add to pot. Cook until browned, about 6 minutes per side.'),
('22352', '2', 'Transfer chicken to bowl. Increase heat to high.'),
('22352', '3', 'Add next 3 ingredients and 1/2 teaspoon paprika to drippings in pot. saute until vegetables are soft and light brown, about 8 minutes. Return chicken to pot. add broth. Sprinkle chicken with remaining 1/2 teaspoon paprika. Bring to boil. Reduce heat, cover, and simmer 10 minutes. Uncover. simmer until chicken is tender, about 10 minutes longer. Season with salt and pepper. Sprinkle parsley over. serve.'),
('22352', '4', 'Self'),
('22353', '1', 'Melt butter in heavy medium skillet over low heat.'),
('22353', '2', 'Add ham and bell pepper and saute until light brown, about 10 minutes.'),
('22353', '3', 'Add garlic and dried red pepper. stir 1 minute.'),
('22353', '4', 'Remove from heat.'),
('22353', '5', 'Prepare barbecue (medium-high heat). Lightly brush baguette slices on both sides with oil. Grill bread until light brown on outside but soft on inside, about 2 minutes per side.'),
('22353', '6', 'Combine clams and wine in large pot. Cover and boil over high heat until clams begin to open, about 8 minutes. Using slotted spoon, transfer clams to 6 bowls, discarding any clams that do not open.'),
('22353', '7', 'Add liquid in pot to skillet with ham-bell pepper mixture. Bring to boil over medium-high heat. Reduce heat to medium and simmer until liquid is slightly reduced, about 3 minutes.'),
('22353', '8', 'Remove from heat. Stir in basil.'),
('22353', '9', 'Pour mixture over clams, dividing equally.'),
('22353', '10', 'Serve clams, passing grilled bread separately.'),
('22354', '1', 'Prepare barbecue (medium-high heat).'),
('22354', '2', 'Whisk first 4 ingredients in small bowl, then whisk in oil. Season dressing with salt and pepper. set aside. On each of 8 metal skewers, alternately thread 3 bell pepper pieces, 2 sausage pieces, 4 onion pieces, and 2 bread cubes.'),
('22354', '3', 'Brush skewers all over with 1 tablespoon dressing each. Grill until lightly charred, turning often, about 12 minutes. Toss greens in large bowl with enough remaining dressing to coat. divide among 4 plates. Top with skewers.'),
('22354', '4', 'Brush skewers with more dressing.'),
('22354', '5', 'Self'),
('22358', '1', 'In a large pot, melt butter over medium-high heat. Cook onions for a couple of minutes.'),
('22358', '2', 'Add bacon and cook for another minute or so, then add diced bell peppers and cook for a couple of minutes. Finally, add corn and cook for a minute. Sprinkle flour evenly over the top and stir to combine.'),
('22358', '3', 'Pour in broth and stir well. Allow this to thicken for 3 or 4 minutes, then reduce heat to low. Stir in half-and-half, then cover and allow to simmer/thicken for 15 minutes or so. Stir in cheeses and green onions. When cheese is melted and the soup is hot, check seasonings.'),
('22358', '4', 'Add salt and pepper as needed. Ladle into hollowed out boules and serve immediately.'),
('22363', '1', 'Watch how to make this recipe.'),
('22363', '2', 'Preheat the grill to high.'),
('22363', '3', 'In a bowl add the mayonnaise, lemon juice, red pepper flakes, and roasted peppers. Season with salt and pepper, to taste, and set aside.'),
('22363', '4', 'In a large bowl, mix the ground turkey with ranch dressing mix, and salt and pepper, to taste. Form the meat into 4 patties and put on a platter lined with parchment paper. Season the burgers with salt and pepper, to taste, and drizzle both sides with olive oil .Grill the burgers for 4 to 5 minutes on each side. Top each burger with 2 slices of Cheddar and 1 slice of bacon. Grill for an additional minute or until the cheese melts.'),
('22363', '5', 'Remove from grill.'),
('22363', '6', 'Spread the sweet pepper mayonnaise on each side of rolls and add the burgers.'),
('22363', '7', 'Serve with pickled jalapenos and enjoy.'),
('22368', '1', 'Cook corn in pot of boiling salted water 3 minutes.'),
('22368', '2', 'Drain. cool.'),
('22368', '3', 'Cut kernels off cob.'),
('22368', '4', 'Place corn kernels in medium bowl.'),
('22368', '5', 'Add shrimp, bell pepper, cilantro, green onion, lime juice, lime peel, and hot pepper sauce. toss to blend.'),
('22368', '6', 'Mix in mayonnaise. Season salad with salt and pepper. (Can be made 1 day ahead. Chill.)'),
('22368', '7', 'Pull some bread out of each roll half, hollowing out slightly. Divide salad among rolls and serve.'),
('22369', '1', 'Brush panini press, panini pan, or grill rack with oil. heat press, pan, or barbecue (medium-high heat).'),
('22369', '2', 'Brush eggplant rounds and pepper strips with oil. sprinkle with salt and pepper. Working in batches, grill eggplant until tender, turning occasionally, about 6 minutes. Working in batches, grill bell peppers until tender, turning occasionally and flattening with back of spatula for even cooking, about 6 minutes.'),
('22369', '3', 'Place 8 eggplant rounds and 8 bell pepperstrips on rimmed baking sheet.'),
('22369', '4', 'Place remaining eggplant and peppers on work surface and slice thinly. reserve for salad.'),
('22369', '5', 'Place 4 bread slices on work surface. Divide half of Fontina cheese among bread slices. top each with 2 eggplant rounds, 2 tablespoons Parmesan cheese, 1 tablespoon basil, and 1 teaspoon oregano. Top each with 2 bell pepper strips. Arrange remaining Fontina cheese atop peppers, then top with remaining bread slices, pressing to compact. DO AHEAD: Can be made 2 hours ahead. Cover with plastic and let stand at room temperature.'),
('22369', '6', 'Heat panini press, panini pan, or barbecue (medium-high heat).'),
('22369', '7', 'Brushpress or pan with oil (if using barbecue, lightly brush bread slices with oil).'),
('22369', '8', 'Place sandwiches in press or pan or on grill. cover and cook until bread is golden and cheese is melted, about 5 minutes per side.'),
('22369', '9', 'Meanwhile, whisk 2 tablespoons extra-virgin olive oil and vinegar in large bowl. season to taste with salt and pepper.'),
('22369', '10', 'Add spinach, thinly sliced eggplant, and thinly sliced peppers. toss to coat. Season salad to taste with salt and pepper.'),
('22369', '11', 'Cut sandwiches in half.'),
('22369', '12', 'Serve with spinach salad.'),
('22370', '1', 'Position rack in center of oven and preheatto 425F. Line baking sheet with parchmentpaper.'),
('22370', '2', 'Combine buttermilk and green onionsin medium bowl.'),
('22370', '3', 'Whisk flour, cornmeal, sugar, and 1/2 teaspoon ground black pepper in large bowl to blend.'),
('22370', '4', 'Add 1/2 cup chilledbutter and rub in with fingertips until mixtureresembles coarse meal.'),
('22370', '5', 'Add buttermilkmixture and stir until moist clumps form.'),
('22370', '6', 'Gather dough together. Turn dough outonto floured surface and knead gently justto combine, about 3 to 4 turns.'),
('22370', '7', 'Roll out to3/4-inch thickness. Using floured 2-inch cookieor biscuit cutter, cut out rounds. Rerollscraps and cut out additional rounds.'),
('22370', '8', 'Place2 inches apart on prepared baking sheet.'),
('22370', '9', 'Brush tops of biscuits with melted butter.Sprinkle each lightly with coarse sea salt andground black pepper.'),
('22370', '10', 'Bake biscuits until golden and testerinserted into center comes out clean, about20 minutes. Cool slightly.'),
('22370', '11', 'Serve warm or atroom temperature.'),
('22370', '12', 'Per serving: 154.52 calories (kcal),42.7 % calories from Fat,'),
('22370', '13', 'Bon Appetit'),
('22371', '1', 'Char bell peppers over open flame or in broiler until blackened on all sides. Enclose peppers in paper bag 10 minutes. Peel and seed peppers, then cut into 3/4-inch-wide strips.'),
('22371', '2', 'Whisk lemon juice, oil, garlic, and dried crushed pepper in small bowl to blend. Season to taste with salt and pepper. (Peppers and dressing can be made 1 day ahead. Cover separately and chill. Bring dressing to room temperature and rewhisk before using.)'),
('22371', '3', 'Toss sliced fennel bulb with half of dressing in medium bowl. Toss red peppers with remaining dressing in another medium bowl.'),
('22371', '4', 'Divide greens among 4 plates. Arrange fennel and red peppers over. Sprinkle reserved fennel fronds, olives, and Parmesan shavings over. Sprinkle with salt and pepper and serve.'),
('22371', '5', 'Per serving: calories, 140. total fat, 9 g. saturated fat, 1 g. cholesterol, 1 mg. fiber, 5 g'),
('22371', '6', 'Bon Appetit'),
('22372', '1', 'Char peppers over gas flame or in broiler until blackened on all sides. Enclose in paper bag and let stand 10 minutes. Peel, seed and slice peppers.'),
('22372', '2', 'Heat oil in heavy large saucepan over medium heat.'),
('22372', '3', 'Add shallots, garlic and thyme and saute 3 minutes.'),
('22372', '4', 'Add 3 cups broth and all but 4 slices of roasted pepper. Simmer uncovered until peppers are very soft, about 20 minutes.'),
('22372', '5', 'Working in batches, puree soup in blender until smooth. Return to same pot.'),
('22372', '6', 'Add half and half, vinegar and cayenne pepper. Rewarm soup, thinning with additional broth, if desired. Season to taste with salt and pepper. Ladle soup into bowls.'),
('22372', '7', 'Garnish with reserved pepper strips and basil.'),
('22376', '1', 'To prepare crust, remove dough and let sit for 30 minutes at room temperature before rolling on a light floured surface into a 1/8 inch thick crust.'),
('22376', '2', 'Transfer to the tart pan and gently press the crust into the edges of the pan, trimming away any excess crust. Wrap crust (in tart pan) in plastic wrap and refrigerate for 1 hour or up to 24 hours.Roasted Red Pepper and Feta Tart'),
('22376', '3', 'Serves 6-82 red peppers, cleaned and halved1 frozen spinach, 10 ounce box4 ounces crumbled feta cheese8 whole eggs2 cups half and half1/2 teaspoon dried oregano1/2 teaspoon salt1/2 teaspoon cracked black pepper'),
('22376', '4', 'Roast red peppers, skin side up, under the broiler and until the skin is fully blackened (10-15 minutes).'),
('22376', '5', 'Remove from oven and place peppers in a sealed plastic bag to cool. Meanwhile, line tart crust with foil and add pie weights.'),
('22376', '6', 'Bake at 350 for 15 minutes.'),
('22376', '7', 'Remove pie weights, discard foil and set crust aside.'),
('22376', '8', 'Remove the charred skin from the peppers and discard. Chop peppers. In a large bowl, beat eggs together lightly, then add half and half, oregano, salt and pepper.'),
('22376', '9', 'Mix well with a whisk.'),
('22376', '10', 'Place tart pan on a baking sheet.'),
('22376', '11', 'Spread peppers, spinach and feta cheese evenly over the bottom of the tart crust. Gently pour egg mixture on top, being careful not to overfill. Return tart to oven and bake until lightly golden on top and a toothpick comes out clean, about an hour.'),
('22376', '12', 'Let cool slightly before removing outer rim from tart pan and serving.Facebook'),
('22376', '13', 'Twitter'),
('22376', '14', 'Google'),
('22376', '15', 'Pinterest'),
('22376', '16', 'Pocket'),
('22376', '17', 'Email'),
('22376', '18', 'One Comment  Comments Feed'),
('22376', '19', 'Name (required)Mail (will not be published) (required)Website Previous'),
('22376', '20', 'Next'),
('22385', '1', 'Prepare barbecue (medium-high heat).'),
('22385', '2', 'Combine first 6 ingredients in processor. add 2/3 cup oil and puree until almost smooth. Season chimichurri with salt and pepper.'),
('22385', '3', 'Brush pepper strips, steaks, and cut side of bread with remaining 1/4 cup oil. Sprinkle peppers and steaks with salt and pepper. Grill peppers until tender, about 5 minutes per side. Grill steaks to desired doneness, about 4 minutes per side for medium-rare. Grill bread, cut side down, until beginning to brown lightly, about 2 minutes. Thinly slice steaks crosswise. divide among bread bottoms. Spoon chimichurri over steak (about 1/4 cup per sandwich), then top with pepper strips. Cover with bread tops and serve.'),
('22386', '1', 'Heat grill to medium-high heat. Season the steak with 1/2 teaspoon salt and 1/2 teaspoon pepper. Grill to the desired doneness, 4 to 5 minutes per side for medium-rare.'),
('22386', '2', 'Transfer to a cutting board and let rest 5 minutes before slicing. Meanwhile, brush both sides of the eggplant and peppers with 3 tablespoons of the oil. Season with 1/2 teaspoon salt and 1/4 teaspoon pepper. Grill until tender, 4 to 5 minutes per side. In a small bowl, combine the remaining oil, vinegar, garlic, and parsley. Divide the steak and vegetables among individual plates. Spoon the sauce over the vegetables or serve on the side.Tip: To serve this meal to a crowd, double the recipe and make it several hours in advance. Refrigerate, then serve at room temperature. You can use leftovers in sandwiches.'),
('22387', '1', 'Prepare grill to medium-high heat.'),
('22387', '2', 'Place bread slices on grill rack. grill 1 minute on each side or until golden brown with grill marks.'),
('22387', '3', 'Remove from grill. tear bread into 1-inch pieces.'),
('22387', '4', 'Combine tomatoes, onion, bell peppers, basil, and cucumber in a large bowl.'),
('22387', '5', 'Add bread. toss gently.'),
('22387', '6', 'Combine vinegar, black pepper, salt, and garlic in a small bowl, stirring with a whisk. Gradually add oil, stirring constantly with a whisk.'),
('22387', '7', 'Drizzle dressing over salad. toss gently to coat. Cover and chill 20 minutes before serving.'),
('22400', '1', 'Preheat oven to 425F.'),
('22400', '2', 'Place pizza crust on large baking sheet.'),
('22400', '3', 'Mix olive oil and minced garlic in small bowl. Using pastry brush, brush 2 tablespoons garlic oil evenly over crust. Top with spinach leaves, then sprinkle with sliced mushrooms, roasted red peppers, red onion slices, fresh basil, and crumbled goat cheese.'),
('22400', '4', 'Drizzle pizza evenly with remaining garlic oil.'),
('22400', '5', 'Bake pizza until crust is crisp and cheese begins to brown, about 18 minutes.'),
('22400', '6', 'Transfer pizza to board.'),
('22400', '7', 'Cut into wedges and serve warm.'),
('22401', '1', 'Heat oil in large pot over medium-high heat.'),
('22401', '2', 'Add mushrooms and saute until tender, about 10 minutes.'),
('22401', '3', 'Add canned tomatoes with juices. Cook until liquid thickens slightly, about 15 minutes. Season mushroom mixture with salt and pepper.'),
('22401', '4', 'Heat large skillet over high heat.'),
('22401', '5', 'Add 1 tortilla to skillet and cook until pliable, about 15 seconds per side.'),
('22401', '6', 'Place on work surface. Spoon 1/6 of mushroom mixture in strip on lower half, leaving 2-inch border at sides. Top with 1/4 cup cheese, 2 tablespoons onions, 2 tablespoons cilantro, 1/6 of peppers and tomatoes, then 1/2 cup spinach leaves. Fold in sides of tortilla over filling. fold up bottom and continue to roll up, enclosing filling. Repeat with remaining tortillas and filling.');