INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('3146', '1', 'Place the haddock in a single layer in a large, deep frying pan.'),
('3146', '2', 'Add enough water to cover and heat over medium heat until just simmering. Reduce the heat to low, and simmer for 7 minutes. Using a slotted spoon, transfer the fish to a plate and cool.'),
('3146', '3', 'Meanwhile, bring the rice, 2 cups water, saffron, and  tsp salt to a boil in a medium saucepan. Reduce the heat to low and cover. Simmer about 15 minutes, until the rice is tender.'),
('3146', '4', 'Remove from heat and stir in the butter.'),
('3146', '5', 'Remove the yolks from the hard-boiled eggs. chop finely, and set aside. Chop the egg whites and stir into the rice with the flaked fish and 2 tbsp chopped parsley.'),
('3146', '6', 'Spoon onto heated plates, sprinkled with the chopped egg yolk and parsley, and serve with the lemon wedges.'),
('3146', '7', 'var article'),
('3146', '8', 'Type_27_data = {}.'),
('3146', '9', 'article'),
('3146', '10', 'Type_27_data.init_step_by_step_images = 0.'),
('3147', '1', 'Heat the water,2 tablespoonsbutter, carrots and pepper in a 3-quart saucepan over medium-high heatto a boil.'),
('3147', '2', 'Remove the saucepan from the heat.'),
('3147', '3', 'Add the stuffing and mix lightly.'),
('3147', '4', 'Spoon the stuffing across thecenter of a 3-quart shallow baking dish. Arrange the fish on each side of the stuffing.'),
('3147', '5', 'Heat the remaining butter in an 8-inch skillet over medium heat until it''s melted.Stir in thelemon juice and parsley. Spoonthe butter mixture over the fish.'),
('3147', '6', 'Bake at 400F. for 15 minutes or until the fish flakes easily when tested with a fork.'),
('3147', '7', '*For moister stuffing increase the water to 1 1/2 cups.'),
('3148', '1', 'Preheat oven to 400F.'),
('3148', '2', 'Spread rice in 8-inch square baking dish.'),
('3148', '3', 'Pour boiling water over rice.  Cover with plastic wrap.'),
('3148', '4', 'Let stand 5 min.  Uncover.'),
('3148', '5', 'Arrange broccoli over rice.'),
('3148', '6', 'Mix soup and water. pour over broccoli.  Sprinkle with half of the cheese.  Top with fish. sprinkle with remaining cheese.'),
('3148', '7', 'Bake 30 min. or until fish flakes easily with fork.'),
('3149', '1', 'Whisk together the salt, ancho and chili de arbol powders in a bowl. Set aside.'),
('3149', '2', 'Cut potatoes into 1/4-inch thick slices then cut each slice into 1/4-inch thick fries.'),
('3149', '3', 'Place fries in a large bowl of cold water.'),
('3149', '4', 'Heat oil in a large, straight sided skillet to 325 degrees F.'),
('3149', '5', 'Drain fries in batches on paper towels. Fry each batch for 3 to 4 minutes until a pale blonde color forms and remove to a sheet pan lined with paper towels.'),
('3149', '6', 'Just before serving, increase the heat of the oil to 375 degrees F and fry the potatoes again, in batches, until golden brown.'),
('3149', '7', 'Remove to a sheet pan lined with paper towels and season with the spices and chopped cilantro.'),
('3151', '1', 'Heat oven to 450F.'),
('3151', '2', 'Cut fish into 3x1-inch strips.'),
('3151', '3', 'Mix egg and water in shallow dish.  Dip fish into egg mixture.'),
('3151', '4', 'Combine coating mix and cheese in shaker bag.  Shake fish in coating mix. place on baking sheet.'),
('3151', '5', 'Bake 15 min. or until fish flakes easily with fork.'),
('3152', '1', 'Cook onions in dressing in large skillet on medium heat 5 min. or until crisp-tender, stirring occasionally.'),
('3152', '2', 'Add tomatoes, peppers and olives. mix lightly.'),
('3152', '3', 'Top with fish. cover.  Simmer on medium heat 8 to 10 min. or until fish flakes easily with fork.'),
('3152', '4', 'Serve fish topped with sauce.'),
('3154', '1', 'Heat oven to 400F.'),
('3154', '2', 'Toss potatoes with Italian dressing, then 1/4 cup coating mix.'),
('3154', '3', 'Spread onto large baking sheet sprayed with cooking spray.'),
('3154', '4', 'Bake 20 min.'),
('3154', '5', 'Meanwhile, spread remaining coating mix onto large plate.'),
('3154', '6', 'Spread fish with 2 Tbsp. MIRACLE WHIP. press, dressing sides down, in coating mix.  Repeat to coat remaining sides of fillets.'),
('3154', '7', 'Place on rack of broiler pan.'),
('3154', '8', 'Add fish to oven with potatoes.'),
('3154', '9', 'Bake 15 min. or until fish flakes easily with fork and potatoes are tender.'),
('3155', '1', 'Heat oven to 450F.'),
('3155', '2', 'Place fish in 13x9-inch baking dish.'),
('3155', '3', 'Mix dressing and pesto. spread onto fish. Top with tomatoes.'),
('3155', '4', 'Bake 15 min. or until fish flakes easily with fork.'),
('3156', '1', 'Heat oven to 450F.'),
('3156', '2', 'Place fish in 13x9-inch baking dish. drizzle with dressing.'),
('3156', '3', 'Bake 25 min.. top with tomatoes and cheese.'),
('3156', '4', 'Bake 5 min. or until cheese is melted and fish flakes easily with fork.'),
('3156', '5', 'Sprinkle with parsley.'),
('3157', '1', 'Heat oven to 450F.'),
('3157', '2', 'Place frozen fish in 13x9-inch baking dish. drizzle with dressing.'),
('3157', '3', 'Bake 25 min. Top with mushrooms and cheese. bake 5 min. or until cheese is melted and fish flakes easily with fork.'),
('3157', '4', 'Sprinkle with parsley.'),
('3419', '1', 'Saute garlic in a small amount of olive oil for two minutes.'),
('3419', '2', 'Add chicken stock and lime zest and simmer about ten minutes, until stock is slightly reduced. Stir in lime juice and olive oil and heat for 2-3 minutes. Stir in cilantro and cook 1 minute more.'),
('3419', '3', 'Brush fish on both sides with sauce and let marinate 15 minutes while you pre-heat gas or charcoal grill to high heat. (For fish, I spray my grill with nonstick spray before I start heating it.) Grill fish until firm, but not hard, to the touch, about 5 minutes per side.To get nice grill marks, lay fish on a diagonal to grill slats, then rotate after about 3 minutes cooking time on the first side.'),
('3419', '4', 'Serve fish hot with additional sauce spooned over each piece of fish.'),
('3420', '1', 'Place onion, parsley, cilantro, lemon zest, lemon juice, olives, capers, garlic and pepper in a food processor. pulse several times to chop.'),
('3420', '2', 'Add oil and process, scraping down the sides several times, until a pesto-like paste forms. Pat halibut with the herb paste. Cover and refrigerate for 30 minutes.Preheat oven to 450F. Coat a 7-by-11-inch baking dish with cooking spray. Arrange the halibut in the dish and spoon any extra herb mixture on top.'),
('3420', '3', 'Bake, uncovered, until the fish is opaque in the center, 15 to 20 minutes.'),
('3420', '4', 'Serve immediately.'),
('3422', '1', 'Heat a grill pan or outdoor grill over high heat.'),
('3422', '2', 'Drizzle extra-virgin olive oil over the fish and season with salt and pepper. Grill 4 minutes on each side until fish is firm but not tough and cooked through. Grill bread alongside or char under broiler then dress with extra-virgin olive oil, salt and pepper as well.'),
('3422', '3', 'Preheat a skillet over medium-high heat.'),
('3422', '4', 'While fish cooks, peel the orange as you would a melon: cut off ends, stand it upright and cut off skin and pith in thin strips from top to bottom.'),
('3422', '5', 'Cut orange across into thin slices.'),
('3422', '6', 'To preheated skillet add extra-virgin olive oil, 2 turns of the pan, the fennel and onions, season with salt and pepper and cook 3 to 5 minutes until seared and beginning to soften.'),
('3422', '7', 'Add vinegar to the pan and give it a shake.'),
('3422', '8', 'Remove from heat and toss in the oranges, the parsley and oregano. Adjust seasoning and serve salad on dinner plates topped with fish, and seasoned bread alongside.'),
('3423', '1', 'To prepare fish: Preheat oven to 450F. Lightly coat a baking sheet with cooking spray.'),
('3423', '2', 'Cut fish into 4 portions.'),
('3423', '3', 'Mix coriander and salt in a small bowl and sprinkle evenly on both sides of the fish.'),
('3423', '4', 'Place on the prepared baking sheet.'),
('3423', '5', 'Bake the fish until it is juicy and almost flakes when pressed with a knife, 8 to 12 minutes, depending on thickness.To prepare relish: Meanwhile, stir together bananas, orange zest, chopped oranges, cilantro, lime juice, coriander and salt in a medium bowl. To serve, spoon the relish over the roasted fish.'),
('3425', '1', 'Bring 2 medium saucepans of water to a boil and prepare a large bowl of ice water.'),
('3425', '2', 'Add the cranberry beans, whole garlic cloves and thyme sprigs to one saucepan and simmer over moderate heat until the beans are tender, about 30 minutes.'),
('3425', '3', 'Drain the beans and discard the garlic and thyme. Wipe out the saucepan and return the beans to it.'),
('3425', '4', 'Meanwhile, preheat the oven to 42'),
('3425', '5', 'Add the fava beans to the second saucepan of boiling water and cook for 5 minutes. Using a slotted spoon, transfer the favas to the ice water to cool.'),
('3425', '6', 'Add the haricots verts to the boiling water and cook until crisp-tender, about 4 minutes. Using a slotted spoon, transfer the haricots verts to the ice water to cool.'),
('3425', '7', 'Add the sugar snaps to the boiling water and cook for 2 minutes.'),
('3425', '8', 'Drain and add them to the ice water.'),
('3425', '9', 'Drain all the beans and peas and pat dry. pop the favas out of their outer skins.'),
('3425', '10', 'Add the beans, sugar snaps and baby peas to the cranberry beans.'),
('3425', '11', 'Wipe out the medium saucepan and melt the 2 tablespoons of butter.'),
('3425', '12', 'Add the shallots and minced garlic and cook over moderate heat, stirring occasionally, until softened.'),
('3425', '13', 'Add the wine and cook until nearly evaporated, about 10 minutes.'),
('3425', '14', 'Add the chicken stock and cook until reduced to 1/4 cup, about 6 minutes. Reduce the heat to moderately low and whisk in the cubes of cold butter, a few at a time, until a creamy sauce forms.'),
('3425', '15', 'Add 1 tablespoon of the lemon juice and season the sauce lightly with salt and pepper.'),
('3425', '16', 'Pour all but 1/4 cup of the butter sauce over the vegetables and keep warm.'),
('3425', '17', 'Heat the oil in a very large ovenproof skillet. Pat the halibut dry and season with salt and pepper.'),
('3425', '18', 'Add the fillets to the skillet and cook over high heat until lightly browned, about 3 minutes.'),
('3425', '19', 'Transfer the skillet to the oven and cook until the halibut is almost opaque throughout, about 5 minutes. Carefully turn the fillets.'),
('3425', '20', 'Add the remaining butter sauce to the skillet with the remaining 2 tablespoons of lemon juice and the chopped thyme. Cook over moderate heat just until the sauce is bubbling and the fish is just cooked through.'),
('3425', '21', 'Transfer the halibut fillets to plates and spoon the lemon-butter sauce on top.'),
('3425', '22', 'Garnish with the microgreens and serve with the beans.'),
('3426', '1', 'Mix first 5 ingredients in bowl. Season with pepper. Cover and chill tartar sauce.'),
('3426', '2', 'Spread panko on plate.'),
('3426', '3', 'Whisk egg in small bowl. Sprinkle fish with salt and pepper. Working in batches, coat fish in egg. Coat in panko. shake off excess.'),
('3426', '4', 'Heat 1 1/2 tablespoons oil in large nonstick skillet over medium heat.'),
('3426', '5', 'Add half of fish and cook, turning often, until fish is opaque in center and golden on all sides, about 4 minutes total.'),
('3426', '6', 'Transfer to 2 plates. cover to keep warm. Repeat with remaining oil and fish. Spoon tartar sauce alongside.'),
('3427', '1', 'Put oil and mustard seeds in a skillet, cover, and heat over medium-high heat. They''ll start popping wildly. When the popping sounds die down, remove from heat.'),
('3427', '2', 'Let cool slightly, uncovered.'),
('3427', '3', 'Halve and pit apricots. cut into 1/2-in. dice. Put diced apricots in a large bowl and toss gently with lemon juice, onion, cilantro, chile, and mustard seeds with oil. Stir in 2 tsp. salt and chill for at least 30 minutes and up to 2 hours.'),
('3427', '4', 'Wipe skillet clean with paper towels and fill half-full with water.'),
('3427', '5', 'Add 1 tsp. salt and lemon slices.'),
('3427', '6', 'Heat water over medium heat until gently simmering.'),
('3427', '7', 'Add fish and cook, covered, until just opaque in center (cut to check), 5 to 8 minutes.'),
('3427', '8', 'Transfer fish with a spatula to a platter and chill at least 20 minutes. Season with salt to taste and serve cold, with salsa.'),
('3428', '1', 'Cut off peel and white pith from oranges.'),
('3428', '2', 'Cut oranges between membranes to release segments.'),
('3428', '3', 'Heat oil in heavy very large skillet over medium-high heat.'),
('3428', '4', 'Add onions and garlic. saut until tender and just beginning to brown, about 8 minutes.'),
('3428', '5', 'Add tomatoes and wine. Bring to boil. Reduce heat to medium-low and simmer 3 minutes. Gently stir in orange segments and olives. Season mixture to taste with salt and pepper. Sprinkle halibut fillets with salt and pepper. Arrange halibut in single layer atop vegetable mixture in skillet. Cover and simmer gently until halibut is just opaque in center, about 12 minutes.  Spoon vegetable mixture onto plates. Top with halibut.'),
('3428', '6', 'Place feta cheese atop vegetable mixture and alongside halibut. Sprinkle with chives and serve.'),
('3429', '1', 'Season fish with salt and pepper. In a large skillet add the oil. Arrange fish in the pan and turn to coat in oil, then add garlic, shallots and wine. Top each fillet of fish with 1/4 of the tomatoes.'),
('3429', '2', 'Place the pan on the stove top and bring the liquid to a boil over medium high heat. Top the pan with a tight fitting lid and reduce heat to moderate. Cook fish 8 to 10 minutes until opaque and flaky, but not dry. Carefully transfer fish topped with tomatoes to dinner plates or serving plate with a thin spatula. Spoon pan juices over the fish. Squeeze the wedge of lemon over the cooked fish and top each fillet with lots of torn or shredded basil.'),
('3429', '3', 'Serve immediately.'),
('3431', '1', 'Preheat oven to 450 degrees F (230 degrees C). Lightly grease a shallow baking dish.'),
('3431', '2', 'Heat olive oil in a medium saucepan over medium heat and stir in zucchini, onion, and garlic. Cook and stir 5 minutes or until tender.'),
('3431', '3', 'Remove saucepan from heat and mix in tomatoes, basil, salt, and pepper.'),
('3431', '4', 'Arrange halibut steaks in a single layer in the prepared baking dish. Spoon equal amounts of the zucchini mixture over each steak. Top with feta cheese.'),
('3431', '5', 'Bake 15 minutes in the preheated oven, or until fish is easily flaked with a fork.'),
('3432', '1', 'Heat grill to medium (about 375). Cook lettuce leaves 2 or 3 at a time in a pot of boiling water until ribs are flexible, 1 1/2 to 3 minutes. as done, transfer to a bowl of ice water. Lay leaves flat with smooth sides up on kitchen towels and pat dry.'),
('3432', '2', 'Spread the 8 largest leaves with tapenade.'),
('3432', '3', 'Cut fish into 8 pieces, each about 2 1/2 in. wide. set 1 at base of each leaf. If leaf isn''t big enough to enclose fish, overlap leaf with another.'),
('3432', '4', 'Roll up each bundle from base, folding in sides (gently crack lettuce ribs if needed).'),
('3432', '5', 'Brush bundles with oil. Discard any extra leaves.'),
('3432', '6', 'Grill, turning once, until fish is just opaque, 8 minutes.'),
('3432', '7', 'Serve with lemon.'),
('3433', '1', 'Preheat oven to 450F.'),
('3433', '2', 'Place all tomatoes in 13x9x2-inch glass baking dish. Sprinkle with salt and pepper. toss to combine. Sprinkle fish with salt and pepper. place atop tomatoes.'),
('3433', '3', 'Whisk oil, vinegar, green onions, chopped cilantro, basil, and saffron in small bowl to blend. Season dressing to taste with salt and pepper.'),
('3433', '4', 'Pour dressing evenly over fish.'),
('3433', '5', 'Let stand 10 minutes.'),
('3433', '6', 'Bake until fish is opaque in center, about 10 minutes. Cool slightly.'),
('3433', '7', 'Place 1 fillet on each of 8 plates. Season tomato mixture to taste with salt and pepper. Top fish with tomato mixture, dividing equally.'),
('3433', '8', 'Garnish with cilantro sprigs.'),
('3433', '9', 'Serve warm.'),
('3434', '1', 'Combine first 7 ingredients in a small bowl.'),
('3434', '2', 'Add 1/4 teaspoon of black pepper, stirring until well blended.'),
('3434', '3', 'Heat oil in a large nonstick skillet over medium heat.'),
('3434', '4', 'Add onion. cook 3 minutes, stirring occasionally.'),
('3434', '5', 'Add ginger mixture. cook 1 minute, stirring frequently.'),
('3434', '6', 'Add broth. bring to a boil. Reduce heat, and simmer 5 minutes.'),
('3434', '7', 'Add coconut milk and juice. simmer 2 minutes.'),
('3434', '8', 'Sprinkle fish with remaining 1/4 teaspoon black pepper and salt.'),
('3434', '9', 'Add fish to pan. cook 8 minutes or until fish flakes easily when tested with a fork or until the desired degree of doneness.'),
('3434', '10', 'Garnish with the chopped fresh parsley, if desired.'),
('3436', '1', 'Saute the peppers, celery, onion, and garlic in oil until tender.'),
('3436', '2', 'Add the tomato juice or water, apple juice, mashed tomatoes, and herbs.  Simmer for 30 minutes.'),
('3436', '3', 'Add halibut pieces to the soup.  Cook until halibut is done, about 30 minutes.  Salt and pepper to taste.'),
('3437', '1', 'Heat oil in non-stick saucepan over medium heat. Cook shallots and garlic gently until fragrant, but not brown. Stir in black bean sauce, rice wine, and soy sauce.  Bring to boil and cook until reduced by half.'),
('3437', '2', 'Remove from heat, and stir in vinegar. set aside.'),
('3437', '3', 'Pat fish dry. Rub with sesame oil and sprinkle with pepper. Preheat an outdoor grill for high heat, and lightly oil grate.'),
('3437', '4', 'Grill fish for about 5 minutes per side, or just until cooked through. Sprinkle with cilantro.'),
('3437', '5', 'Serve with sauce poured over top.'),
('3439', '1', 'Pour olive oil into a 4- to 6-quart pan over medium-high heat. add andouille sausages, sliced 1/4 inch thick, and stir often until beginning to brown.'),
('3439', '2', 'Add onion, peeled and chopped, and stir often until limp.'),
('3439', '3', 'Add saffron threads, chicken broth, and sweet potato, peeled and cut into 1/2-inch chunks. Bring to a boil, then reduce heat and simmer until sweet potato is barely tender when pierced, about 5 minutes. Stir in whipping cream and salt and pepper to taste.'),
('3439', '4', 'Meanwhile, rinse halibut and pat dry. cut into 1-inch chunks. Lay chunks on top of soup, cover, and cook until halibut is opaque but still moist-looking in the center (cut a piece to check), about 10 minutes. Gently stir soup. Ladle into bowls and garnish with thinly sliced green onion.'),
('3439', '5', 'Wine pairing: Arneis, a lively Italian white (the name means "little rascal"), is an almost perfect match for the halibut chowder, although a mineral-rich, aromatic dry Riesling works well too.'),
('3440', '1', 'To prepare salsa, combine first 9 ingredients. toss gently.'),
('3440', '2', 'Let stand 30 minutes before serving.'),
('3440', '3', 'Prepare grill to medium-high heat.'),
('3440', '4', 'To prepare fish, combine 4 teaspoons juice, oil, paprika, and 1 garlic clove in a large, shallow glass baking dish, stirring with a whisk.'),
('3440', '5', 'Add fish to juice mixture. turn to coat. Cover and let stand 15 minutes.'),
('3440', '6', 'Remove fish from marinade. discard marinade. Sprinkle fish evenly with 3/8 teaspoon salt and black pepper.'),
('3440', '7', 'Place fish on a grill rack coated with cooking spray. grill 3 minutes on each side or until desired degree of doneness.'),
('3440', '8', 'Serve fish with salsa.'),
('3441', '1', 'Tip:If raw eggs are an issue you can make the sauce with a pasteurized egg or with store-bought mayonnaise (use about 1 heaping cup in place of the egg and oils).'),
('3441', '2', 'Whisk the egg, lemon juice, salt, and a few grinds of black pepper in a bowl until well combined.'),
('3442', '1', 'Pour 3 tablespoons olive oil into a 10- to 12-inch frying pan over medium heat.'),
('3442', '2', 'Add onion and stir often until soft, 6 to 8 minutes.'),
('3442', '3', 'Add zucchini and 1 teaspoon salt. cook, stirring occasionally, until zucchini is soft and most of the liquid has evaporated, about 10 minutes longer.'),
('3442', '4', 'Meanwhile, in a 5- to 6-quart pan, bring 4 quarts water to a boil.'),
('3442', '5', 'Add penne and cook until tender to bite, 10 to 12 minutes.'),
('3442', '6', 'Drain.'),
('3442', '7', 'Coat halibut with remaining 2 tablespoons olive oil and sprinkle all over with salt and pepper.'),
('3442', '8', 'Place in a 10- to 12-inch nonstick frying pan over high heat and cook, turning once, until browned on both sides, about 4 minutes total.'),
('3442', '9', 'Pour in wine, reduce heat to maintain a simmer, and cook until fish flakes easily with a fork, about 5 minutes longer. Break halibut into flakes.'),
('3442', '10', 'Stir lemon peel into zucchini mixture. In a large bowl, combine pasta and zucchini mixture.'),
('3442', '11', 'Add flaked halibut and liquid in pan and sprinkle with all but 2 tablespoons mint. mix to coat pasta. Sprinkle with remaining mint.'),
('3443', '1', 'Combine tomatoes, onions, cilantro and pepper. set aside.'),
('3443', '2', 'Heat oil in large skillet on medium-high heat.'),
('3443', '3', 'Add fish. cook 3 to 5 min. until browned on bottom.  Carefully turn over. top with tomato mixture.  Cook 2 to 3 min. or until fish flakes easily with fork.'),
('3443', '4', 'Sprinkle with cheese. cover.'),
('3443', '5', 'Let stand 2 min. or until cheese is melted.'),
('3445', '1', 'In the bottom of an 11- to 12-inch-wide steamer or in a deep 5- to 6-quart pan, combine orange juice, lime juice, and ground ginger. Set a nonstick or oiled rack at least 1 inch above surface of juice (elevate, if necessary, on the rim of a cheesecake pan or three clean, empty 2- to 3-in.-tall cans with both ends removed). Cover pan and bring juice to a boil over high heat.'),
('3445', '2', 'Rinse fish. Set pieces slightly apart on rack over boiling juice. cover pan and reduce heat to medium. Steam until fish is barely opaque but still moist-looking in center of thickest part (cut to test), 8 to 10 minutes. Lift out rack. With a wide spatula, lift fish from rack and set on a warm plate. cover to keep warm. Increase heat to high and boil pan juices, uncovered, until reduced to about 1 1/2 cups, 10 to 12 minutes.'),
('3445', '3', 'In a small bowl, mix cornstarch with 3 tablespoons water.'),
('3445', '4', 'Add mixture, along with fresh ginger, to reduced pan juices. stir until boiling.'),
('3445', '5', 'Add salt and cayenne to taste.'),
('3445', '6', 'Divide sauce evenly among four dinner plates. Lay a piece of fish in sauce on each plate.'),
('3445', '7', 'Garnish each portion with a few drops of chili oil and shreds of lime peel.'),
('3446', '1', 'Rinse halibut and place on a plate.'),
('3446', '2', 'Pour 4 tablespoons lime juice over fish. sprinkle with 1 teaspoon salt and the pepper. Cover and chill for 20 minutes.'),
('3446', '3', 'Meanwhile, pour 1/2 inch oil into a 10- to 12-inch nonstick frying pan with sides at least 2 inches tall over medium-high heat. When surface looks rippled, gently lower a tortilla into oil and cook, turning once, until crisp, 1 to 2 minutes total.'),
('3446', '4', 'Transfer to paper towels to drain briefly. Repeat to fry remaining tortillas. Discard oil and wipe pan clean.'),
('3446', '5', 'In a small bowl, stir together yogurt, sugar, chili powder, and the remaining 1 tablespoon lime juice and 1/2 teaspoon salt.'),
('3446', '6', 'Set pan over medium-high heat. When hot, add fish to pan along with lime juice, cover, and cook until opaque in the center (cut to test), 10 to 12 minutes. Break fish into flakes with a fork.'),
('3446', '7', 'Pit, peel, and slice avocado.'),
('3446', '8', 'Place a fried tortilla on each plate and layer equally with shredded cabbage, flaked halibut with its juices, yogurt sauce, avocado slices, cilantro leaves, and fresh salsa.'),
('3447', '1', 'Combine first 4 ingredients in a small bowl.'),
('3447', '2', 'Combine 1 1/2 teaspoons spice mixture, 2 teaspoons oil, and garlic in a small bowl. rub garlic mixture evenly over fish.'),
('3447', '3', 'Heat 1 teaspoon oil in a large nonstick skillet over medium-high heat.'),
('3447', '4', 'Add fish to pan. cook 5 minutes on each side or until desired degree of doneness.'),
('3447', '5', 'Combine remaining 3/4 teaspoon spice mixture, remaining 2 teaspoons oil, fennel bulb, and remaining ingredients in a medium bowl, tossing well to coat.'),
('3447', '6', 'Serve salad with fish.'),
('3448', '1', 'Preheat oven to 350F.  Arrange half of the tomato slices on bottom of 9-inch square baking dish. top with fish, onions and remaining tomatoes.'),
('3448', '2', 'Drizzle with dressing. sprinkle with capers.'),
('3448', '3', 'Bake 20 to 25 min. or until fish flakes easily with fork.'),
('3448', '4', 'Spoon rice onto serving platter.  Top with the fish, vegetables and cooking juices.'),
('3449', '1', 'In a large bowl, stir together the bulgur and 1 teaspoon salt, then pour 1 1/2 cups boiling water over the mix. Cover and let sit until water is absorbed, 20 to 30 minutes. Fluff with a fork.'),
('3449', '2', 'In a bowl, combine olive oil, lemon peel, lemon juice, 1/2 teaspoon pepper, mint, and parsley.'),
('3449', '3', 'Pour dressing over cooked bulgur and stir to coat. Stir in green onions and pine nuts.'),
('3449', '4', 'Sprinkle both sides of halibut with 1/4 teaspoon salt and 1/8 teaspoon pepper.'),
('3449', '5', 'Heat a large frying pan over medium-high heat.'),
('3449', '6', 'Add oil, then halibut. Cook, turning once, until fish is opaque in the center, about 10 minutes total per inch of thickness.'),
('3449', '7', 'Mound tabbouleh on plates and top with halibut.'),
('3449', '8', 'Serve warm.'),
('3450', '1', 'Heat a grill to medium (350 to 450).'),
('3450', '2', 'Meanwhile, in a large bowl, combine olive oil, rosemary, salt, and pepper.'),
('3450', '3', 'Add halibut and bread. Toss to coat, then set aside 5 minutes.'),
('3450', '4', 'Skewer an end of 1 strip pancetta, then alternate fish and bread cubes on a 10-in. metal skewer*, weaving pancetta between them. Repeat 3 times.'),
('3450', '5', 'Grill kebabs, turning frequently, until fish is cooked through and bread is charred in places, about 6 minutes.'),
('3450', '6', '*You will need 4 metal skewers for the kebabs.'),
('3451', '1', 'Preheat the oven''s broiler and coat a baking sheet or broiling pan with olive oil.'),
('3451', '2', 'Rinse the fish and pat dry.'),
('3451', '3', 'Place on the greased pan, and brush with olive oil or coat with olive oil cooking spray. Squeeze the juice from the lemon wedges over the entire fillet, and season generously with salt first, then garlic and finally dill.'),
('3451', '4', 'Broil for 15 to 20 minutes in the preheated oven, until the fillet is opaque and can be flaked with a fork. Broiling time may depend on the thickness of your fillet.'),
('3452', '1', 'Heat olive oil in a 6-quart pot over medium-high heat.'),
('3452', '2', 'Add onion, garlic, and celery. saut 3 minutes.'),
('3452', '3', 'Stir in tomato paste and seasoning. Stir in tomatoes and broth. Bring to a boil, reduce heat, and simmer 10 minutes, stirring occasionally.'),
('3452', '4', 'Stir in fish and green beans. cook 5 to 7 minutes or until fish is cooked through. Stir in pasta. Cook 5 minutes or until pasta is heated through.'),
('3452', '5', 'WINES: This light minestrone will pair with a variety of wines. Continue the Italian theme with a Chianti, or go for a light French wine like Beaujolais. Prefer a white? Jim Coley, sommelier at Starker''s Restaurant in Kansas City, suggests the Dorigo Pinot Grigio. "The crisp acidity matches well with the broth and vegetables," he says.'),
('3453', '1', 'Preheat oven to 200 degrees F.'),
('3453', '2', 'Cut halibut in 4 equal pieces. In a mixing bowl, combine ginger, light soy sauce, white wine, and pepper in mixing bowl.'),
('3453', '3', 'Add fish to bowl and let marinate for about 20 to 30 minutes.'),
('3453', '4', 'Defrost potato nuggets. add panko, hoisin, oyster sauce, soy sauce, rice wine vinegar, and sesame oil.'),
('3453', '5', 'Mix together thoroughly and divide into 4 equal amounts.'),
('3453', '6', 'Heat a medium nonstick saute pan to low and add 2 tablespoons of oil.'),
('3453', '7', 'Remove fish from marinade, shake off excess marinade, and dredge in flour on both sides.'),
('3453', '8', 'Apply 1/4 of potato mixture to fish. press the mixture onto the top of the fish.'),
('3453', '9', 'Add fish potato-side-down to saute pan. cook 2 portions at a time. Cook until potato mixture is lightly browned and crispy. Gently turn the fish over. cook the other side for 2 minutes. When finished, remove, place on a baking sheet and hold in the oven until the next two fillets are cooked. Repeat the process for the next two fillets.'),
('3453', '10', 'Garnish with sesame seeds and green onions.'),
('3454', '1', 'Heat oven to 450F.'),
('3454', '2', 'Drizzle 2 Tbsp. dressing over fish in shallow baking dish.'),
('3454', '3', 'Bake 15 min. or until fish flakes easily with fork.  Meanwhile, cook mushrooms in remaining dressing in medium skillet 3 to 4 min. or until mushrooms are tender, stirring occasionally.'),
('3454', '4', 'Add water. bring to boil.  Stir in rice and peas. cover.  Simmer 5 min.'),
('3454', '5', 'Remove from heat. let stand 5 min.'),
('3454', '6', 'Spoon rice mixture onto serving plates. top with fish.'),
('3455', '1', 'Rinse fish and pat dry. Sprinkle lightly all over with salt and pepper and place on a 12- by 15-inch baking sheet.'),
('3455', '2', 'Bake in a 350 regular or convection oven until opaque but still moist-looking in center of thickest part (cut to test), about 10 minutes. With a wide spatula, transfer fish to a bowl. Chill until cold, at least 1 hour. if desired, cover when cold and chill up to 1 day.'),
('3455', '3', 'Shred fish with fork.'),
('3455', '4', 'Add pineapple and 2 tablespoons juice, cashews, coconut, green onions, and mayonnaise. mix well.'),
('3455', '5', 'Mound halibut salad equally on bottoms of 4 sandwich rolls. Top with salad mix and roll tops.'),
('3456', '1', 'Season both sides of halibut with salt and black pepper.'),
('3456', '2', 'Heat oil in a large skillet over medium-high heat.'),
('3456', '3', 'Add halibut and cook 2 minutes per side, until golden brown.'),
('3456', '4', 'Remove fish from pan and set aside.'),
('3456', '5', 'To the same pan, add artichoke hearts, broth and saffron. Bring to a simmer. Return fish to pan and simmer 2 minutes, until fish is fork-tender.'),
('3456', '6', 'Transfer to a serving platter and is usually served with couscous.'),
('3458', '1', 'Prepare the artichoke hearts: Working with 1 artichoke at a time, snap off tough outer leaves until half-green-half-yellow leaves are exposed. Using a chef''s knife, cut off dark-green top until just pale part remains. Using a paring knife, peel dark-green layer from base and stem. trim stem. Scrape out purple leaves and fuzzy choke using a spoon, and discard. Halve artichoke lengthwise. Rub artichoke with reserved lemon rinds as you work.'),
('3458', '2', 'Cut artichoke heart into 1/4-inch-thick slices, and transfer to lemon water.'),
('3460', '1', 'Mix first 7 ingredients in medium glass bowl. Season sauce to taste with salt and pepper. (Sauce can be prepared 2 days ahead. Cover and refrigerate.)'),
('3460', '2', 'Prepare barbecue (medium-high heat).'),
('3460', '3', 'Place carrot in medium bowl. Cover with ice water.'),
('3460', '4', 'Let stand 15 minutes, then drain well.'),
('3460', '5', 'Brush fish on all sides with 2 tablespoons oil. Sprinkle with salt and pepper. Grill until just opaque in center, about 4 minutes per side.'),
('3460', '6', 'Meanwhile, heat 1 tablespoon oil in large nonstick skillet over medium heat.'),
('3460', '7', 'Add shallot. stir 1 minute.'),
('3460', '8', 'Add tatsoi. sprinkle with salt. Toss until tatsoi is wilted but still bright green, about 2 minutes. divide among 4 plates.'),
('3460', '9', 'Place fish atop tatsoi. Sprinkle each fillet with carrot. drizzle each with 2 tablespoons sauce.'),
('3460', '10', 'Serve, passing remaining sauce separately.'),
('3461', '1', 'In a small bowl, whisk together the juice of 1 lemon, the olive oil and saffron. Season the fish fillets with coarse salt and pepper.'),
('3461', '2', 'Place in a nonreactive dish in a single layer.'),
('3461', '3', 'Pour the oil mixture over the fish and turn to coat. Cover and refrigerate for 1 to 2 hours.Preheat an oven to 450F.Spray a roasting pan with nonstick cooking spray and place in the oven until it is hot, about 5 minutes. Sprinkle a little coarse salt on the bottom of the hot pan. Lift the fish fillets from the marinade, reserving the marinade, and place them, skin sides down, on the hot pan. Roast until opaque throughout when pierced with a knife, 7 to 10 minutes.Meanwhile, prepare the vegetables: In a large nonreactive saut pan over medium-high heat, warm the olive oil.'),
('3461', '4', 'Add the shallots and saut until they begin to soften, 2 to 3 minutes.'),
('3461', '5', 'Add the saffron and continue to cook until the shallots are soft, about 4 minutes more.'),
('3461', '6', 'Transfer about 1 Tbs. of the shallots to a small dish and set aside.Increase the heat under the saut pan to high. Working in 3 batches, add the spinach leaves to the shallots remaining in the pan. Saut, tossing constantly, until the spinach is wilted but still bright green, 4 to 5 minutes.'),
('3461', '7', 'Transfer to a plate, season with coarse salt and pepper, and keep warm.'),
('3461', '8', 'Place the saut pan over medium heat and add the reserved shallots.'),
('3461', '9', 'Add the zucchini and cook, stirring occasionally, until it begins to soften, 2 to 3 minutes.'),
('3461', '10', 'Add the tomatoes and cook, stirring, until the tomatoes begin to soften, 3 to 4 minutes.'),
('3461', '11', 'Add the reserved marinade, increase the heat to high, and cook until the sauce is slightly thickened and the vegetables are just tender, 5 to 7 minutes more. Season with coarse salt, pepper and lemon juice.Mound a portion of the spinach in the center of each individual plate. Top each with a fish fillet and spoon the zucchini mixture over the fish. Dust the fish and the plate with the parsley.'),
('3461', '12', 'Cut the remaining lemon into wedges and divide among the plates.'),
('3462', '1', 'Finely grate enough peel from 2 limes to measure 11/2 teaspoons. Squeeze enough juice from 2 limes to measure 2 tablespoons.'),
('3462', '2', 'Cut third lime into wedges.'),
('3462', '3', 'Heat vegetable oil in large saucepan over medium-high heat.'),
('3462', '4', 'Add chopped shallots, diced red bell pepper, and minced ginger. saut until shallots are tender and peppers soften, about 5 minutes. Stir in curry paste, coconut milk, fish sauce, 11/2 teaspoons lime peel, and 2 tablespoons lime juice. Simmer gently, stirring often, about 5 minutes. Sprinkle fish and shrimp with salt and pepper.'),
('3462', '5', 'Add fish and shrimp to curry sauce. Return to very gentle simmer and cook just until fish and shrimp are opaque in center, 5 to 6 minutes. Season to taste with salt and pepper. Gently stir in cilantro and basil. serve with lime wedges.'),
('3463', '1', 'Combine first 8 ingredients in a large Dutch oven over medium-high heat. bring to a boil. Cover, reduce heat, and simmer 30 minutes. Strain mixture through a colander over a bowl, reserving broth and vegetable mixture. Return broth to pan. bring to a simmer.'),
('3463', '2', 'Add fish to pan. Cook 8 minutes or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('3463', '3', 'Remove fish from cooking liquid using a slotted spoon. reserve 1 cup plus 2 tablespoons cooking liquid. Discard remaining cooking liquid.'),
('3463', '4', 'Cook bacon in a large nonstick skillet over medium heat until crisp.'),
('3463', '5', 'Remove bacon from pan. crumble.'),
('3463', '6', 'Add shallots to drippings in pan. saut 1 minute or until tender, stirring constantly. Stir in 2 tablespoons vinegar and mustard. cook 1 minute, stirring occasionally. Stir in 2 tablespoons reserved cooking liquid, remaining 1 tablespoon vinegar, syrup, oil, salt, and pepper. cook 30 seconds, stirring occasionally. Stir in bacon.'),
('3463', '7', 'Place about 3/4 cup vegetable mixture in each of 4 shallow bowls. top each with 1/4 cup remaining cooking liquid.'),
('3463', '8', 'Place 1 bread slice and 1 fish fillet in each serving.'),
('3463', '9', 'Drizzle each serving with about 1 tablespoon bacon mixture.'),
('3463', '10', 'Garnish with parsley sprigs, if desired.'),
('3465', '1', 'Position a rack in the center of the oven and heat the oven to 425F.    Make the salsa'),
('3465', '2', 'In a small saucepan, boil the orange juice over medium heat until reduced to 1/4 cup, 8 to 10 minutes.'),
('3465', '3', 'Let cool.'),
('3465', '4', 'In a medium bowl, combine the reduced orange juice, blood orange segments, onion, cilantro, olive oil, and orange zest. Season to taste with salt and pepper.'),
('3465', '5', 'Cook the halibut'),
('3465', '6', 'In a small bowl, mix the orange zest, thyme, 1-1/2 tsp. salt, and 1/2 tsp. pepper. Rub the mixture all over the halibut fillets.'),
('3465', '7', 'Heat the oil in a 12-inch ovenproof skillet over medium-high heat. When the oil is shimmering hot, arrange the fillets in the pan. Sear for about 2 minutes without moving. then use a thin slotted metal spatula to lifta piece of fish and check the color. When the fillets are nicely browned, flip them and put the pan in the oven.'),
('3465', '8', 'Roast until the halibut is just cooked through, 3 to 5 minutes.'),
('3465', '9', 'Remove the pan from the oven and transfer the halibut to serving plates. Spoon some of the salsa over each fillet.'),
('3465', '10', 'Serving Suggestions'),
('3465', '11', 'Serve with a side salad ofButter'),
('3465', '12', 'Lettuce with Poppy Seed & Tarragon Crme Frache Dressing.'),
('3466', '1', 'Preheat oven to 40'),
('3466', '2', 'In a small bowl, whisk curry paste, gradually adding coconut milk.'),
('3466', '3', 'Transfer 1/2 cup sauce to another bowl. set bowls aside.'),
('3466', '4', 'Toast almonds in a small saucepan over medium heat until golden, 3 minutes. Stir in rice, reserved 1/2 cup sauce, 1/2 cup water, the coconut, and 1/2 tsp. salt. Bring to a boil, then reduce heat and simmer, covered, until rice is tender, 16 to 18 minutes.'),
('3466', '5', 'Season halibut with remaining 1/4 tsp. salt and the pepper while rice cooks.'),
('3466', '6', 'Cut 4 pieces of parchment, each 12 by 14 in. Set a fillet in center of each, then mound asparagus and peas on top (some may roll off). For each packet, bring 2 opposite sides of parchment up over ingredients and fold several times to seal. Bring other sides up and fold to seal.'),
('3466', '7', 'Place packets, folded sides up, on a rimmed baking sheet.'),
('3466', '8', 'Bake until fish is just opaque (poke with a sharp knife to check), 10 to 15 minutes.'),
('3466', '9', 'Microwave remaining 1/4 cup sauce to warm. Divide rice among 4 plates and top each with fish and vegetables from a packet, discarding extra liquid.'),
('3466', '10', 'Drizzle sauce over dishes and sprinkle with cilantro.'),
('3466', '11', 'Serve with lime wedges.'),
('3466', '12', '*Find in grocery stores'' Asian-foods aisle.'),
('3467', '1', 'Spread salt level (about 1 in. deep) in a 5- to 6-quart oval or 9- by 13-inch rectangular baking dish.'),
('3467', '2', 'Heat in a 450 regular or convection oven until very hot, about 20 minutes.'),
('3467', '3', 'Meanwhile, sprinkle one side of halibut lightly with salt and pepper.'),
('3467', '4', 'Pour olive oil into a 10- to 12-inch nonstick frying pan over high heat. When hot, place fish pieces in pan, seasoned side down, without crowding. work in batches if necessary. Cook until lightly browned on the bottom, about 2 minutes.'),
('3467', '5', 'Remove baking dish from oven and distribute thyme and oregano sprigs, bay leaves, and all but three of the lemon slices evenly over hot salt (some salt will still be visible). Set halibut pieces browned side up over herbs and salt, spacing evenly.'),
('3467', '6', 'Cut reserved lemon slices in half and place half a slice on each piece of fish.'),
('3467', '7', 'Bake until fish is opaque but still moist- looking in center of thickest part (cut to test), 15 to 20 minutes.'),
('3467', '8', 'Serve with herb oil to drizzle over fish to taste.'),
('3470', '1', 'In a non reactive bowl, stir halibut with onion, lime juice and vinegar to coat. Cover and refrigerate for 4 to 6 hours.'),
('3470', '2', 'Discard halibut marinade and in a clean bowl combine halibut and bell pepper.'),
('3470', '3', 'For dressing combine lime juice and rice vinegar and while whisking, add olive oil in a slow stream.'),
('3470', '4', 'Add lime zest, chives, cilantro, mint and chili flakes. Fold in halibut and bell pepper mixture and season, to taste, with salt and pepper. Spoon into martini glasses and top with radish sprouts.'),
('3471', '1', 'Pour 3 tbsp. oil into a large frying pan over medium heat. When hot, add onions, fennel, and garlic and cook, stirring occasionally, until very soft, about 15 minutes.'),
('3471', '2', 'Add wine, orange peel, thyme, and saffron. boil over medium-high heat, stirring often, until liquid has evaporated, about 3 minutes.'),
('3471', '3', 'Add tomatoes and salt and pepper to taste. reduce heat to low and cook, occasionally stirring gently, just until heated through, about 2 minutes.'),
('3471', '4', 'Meanwhile, prepare a grill for direct medium-high heat (about 450. you can hold your hand 5 in. above cooking grate only 4 to 6 seconds). oil grill well. Rub halibut all over with oil and sprinkle with salt and pepper.'),
('3471', '5', 'Lay halibut on cooking grate. close lid if using a gas grill. Cook, gently turning once, just until fish is opaque but still moist-looking in center of thickest part (cut to test), 6 to 10 minutes total.'),
('3471', '6', 'Spoon vegetables onto plates and top with halibut. garnish with fennel greens if you like.'),
('3471', '7', 'Serve rouille alongside.'),
('3473', '1', 'Preheat grill to medium-high heat.'),
('3473', '2', 'Brush 1 1/2 teaspoons oil over cut sides of tomato. sprinkle evenly with 1/8 teaspoon salt and 1/8 teaspoon pepper.'),
('3473', '3', 'Place tomato, cut sides down, on grill rack coated with cooking spray. Cover and grill 8 minutes. Cool slightly. peel and chop tomato.'),
('3473', '4', 'Combine tomato, 1/8 teaspoon salt, 1/8 teaspoon pepper, 1 tablespoon oil, basil, and next 6 ingredients (through garlic). toss gently.'),
('3473', '5', 'Brush fillets evenly with 1 tablespoon oil. sprinkle evenly with remaining 1/4 teaspoon salt and remaining 1/4 teaspoon pepper.'),
('3473', '6', 'Place fillets, flesh side down, on grill rack coated with cooking spray. Grill 5 minutes. turn and grill 3 minutes or until fish flakes when tested with a fork or until desired degree of doneness.'),
('3473', '7', 'Serve with tomato mixture.'),
('3475', '1', 'Watch how to make this recipe.'),
('3475', '2', 'Combine tomatoes, olives, onion, parsley, tarragon and extra-virgin olive oil in a small bowl and season with salt and pepper, to taste.'),
('3475', '3', 'Let sit at room temperature for 30 minutes before serving.'),
('3475', '4', 'Combine the garlic and the olive oil in a small bowl.'),
('3475', '5', 'Brush both sides of the halibut with the oil and let marinate for 15 minutes.'),
('3475', '6', 'Heat the grill to high.'),
('3475', '7', 'Season the halibut with salt and pepper, to taste, on both sides and grill until slightly charred and just cooked through, about 5 minutes per side.'),
('3475', '8', 'Remove from the grill to a platter.'),
('3475', '9', 'Garnish with tarragon and serve immediately with the tomato relish on the side.'),
('3476', '1', 'Preheat the oven to 450F (230C).'),
('3476', '2', 'Brush the bottom of a 13  9in (33  23cm) baking dish with 1 tbsp of the oil.'),
('3476', '3', 'Add the fish, skinned side down. Season with salt and pepper.'),
('3476', '4', 'Heat 2 tbsp of the oil in a large, heavy frying pan over medium heat.'),
('3476', '5', 'Add the bread crumbs, almonds, and garlic and cook, stirring often, until golden. Stir in the parsley. Spoon the mixture over the fish. Cover with aluminum foil and bake for 15 minutes. Uncover and bake 5 minutes more, until the fish is opaque when pierced with a knife.'),
('3476', '6', 'Meanwhile, to make the romesco sauce, pulse the red peppers, oil, vinegar, cayenne, and paprika in a food processor.'),
('3476', '7', 'Transfer the sauce to a serving bowl.'),
('3476', '8', 'Remove the fish from the oven and drizzle with the remaining 1 tbsp olive oil.'),
('3476', '9', 'Serve hot, topped with the romesco sauce.'),
('3476', '10', 'var article'),
('3476', '11', 'Type_27_data = {}.'),
('3476', '12', 'article'),
('3476', '13', 'Type_27_data.init_step_by_step_images = 0.'),
('3478', '1', 'Position a rack in the center of the oven and heat the oven to 450F.'),
('3478', '2', 'In a medium bowl, mix the tomatoes, capers, oregano, vinegar, 1/2 tsp. salt, and 1/4 tsp. pepper.'),
('3478', '3', 'Season the fish with 3/4 tsp. salt and 1/4 tsp. pepper and dredge it in the flour, shaking off the excess.'),
('3478', '4', 'Heat the oil in a 12-inch (preferably nonstick) ovenproof skillet over medium-high heat until shimmering hot.'),
('3478', '5', 'Add the fish, evenly spaced, and cook without touching until it browns and releases easily from the pan (check by gently lifting one of the corners), about 3 minutes. Flip the fish, sprinkle the garlic around it, and cook until the garlic just starts to brown on some edges, about 30 seconds.'),
('3478', '6', 'Pour the tomato mixture around the fish and transfer the skillet to the oven. Roast until the fish is just firm to the touch and opaque when you pry open a thicker piece with a paring knife, 3 to 6 minutes.'),
('3478', '7', 'Let the fish rest for a couple of minutes and then serve with the tomato mixture spooned over it.'),
('3479', '1', 'Process the herbs, oil, tarragon vinegar, and garlic in a blender until smooth. Season with salt and pepper. If it tastes slightly bitter, add sugar to taste.'),
('3479', '2', 'Transfer the sauce to a bowl, cover, and refrigerate until serving.'),
('3479', '3', 'Preheat the broiler or build a fire in an outdoor grill. Lightly brush each fillet with oil and season with salt and pepper. Broil or grill, turning once, about 4 minutes, until the fish is barely opaque when pierced with the tip of a sharp knife.'),
('3479', '4', 'Transfer to plates and serve, with the green sauce and the lemon wedges.'),
('3479', '5', 'Variation'),
('3479', '6', 'Seared Salmon with Green Sauce'),
('3479', '7', 'Substitute six salmon fillets for the halibut.'),
('3479', '8', 'var article'),
('3479', '9', 'Type_27_data = {}.'),
('3479', '10', 'article'),
('3479', '11', 'Type_27_data.init_step_by_step_images = 0.'),
('3482', '1', 'Preheat the oven to 400F. Rinse the fish and pat dry, then place on an aluminum foil-covered baking sheet. Top each fillet with a squeeze of lemon juice from half the lemon.'),
('3482', '2', 'Mix the bread crumbs and chile together, then sprinkle on the top, bottom, and sides of each.'),
('3482', '3', 'Place in the oven and bake until the fish flakes easily (approximately 8 to 10 minutes) when pierced with a fork.'),
('3482', '4', 'Cut the remaining half lemon lengthwise into quarters.'),
('3482', '5', 'Serve the fish napped with the salsa and a lemon wedge.'),
('3482', '6', 'Mix the bread crumbs and chile together, then sprinkle on the top, bottom, and sides of each.'),
('3482', '7', 'Place in the oven and bake until the fish flakes easily (approximately 8 to 10 minutes) when pierced with a fork.'),
('3482', '8', 'Cut the remaining half lemon lengthwise into quarters.'),
('3482', '9', 'Serve the fish napped with the salsa and a lemon wedge.'),
('3482', '10', 'var article'),
('3482', '11', 'Type_27_data = {}.'),
('3482', '12', 'article'),
('3482', '13', 'Type_27_data.init_step_by_step_images = 0.'),
('3483', '1', 'Preheat oven to 375 degrees. Lightly season the halibut fillets on both sides with salt and pepper.'),
('3483', '2', 'Cut 4 pieces of parchment paper (12 by 16 inches each) and lay them on a clean work surface. Fold each in half crosswise, making a crease in the middle, then open and lay flat.'),
('3485', '1', 'Season the fish with  teaspoon salt and  teaspoon pepper.'),
('3485', '2', 'Place in a large skillet with enough water to reach halfway up the sides of the fish.Bring to a simmer over medium heat. Cook the fish, covered, until opaque throughout, 6 to 8 minutes.'),
('3485', '3', 'Transfer the fish to a plate and refrigerate until cool, about 15 minutes. Using a fork, flake the fish into large pieces.Meanwhile, in a large bowl, whisk together the oil, lemon juice, mustard, cilantro,  teaspoon salt, and  teaspoon pepper.Toss the dressing with the mixed greens, chickpeas, avocado, and onion. Divide among plates and top with the fish.'),
('3486', '1', 'Pat halibut dry and season with salt and pepper.'),
('3486', '2', 'Heat 2 tablespoons oil in a 12-inch heavy skillet over moderately high heat until hot but not smoking, then saut fish, turning once, until golden and just cooked through, 4 to 6 minutes total.'),
('3486', '3', 'Transfer to plates and keep warm, loosely covered with foil.'),
('3486', '4', 'Add remaining tablespoon oil to skillet and cook shallot over moderate heat, stirring occasionally, until pale golden, 3 to 4 minutes.'),
('3486', '5', 'Add pecans and saut over moderately high heat, stirring, until fragrant and a shade darker, about 3 minutes.'),
('3486', '6', 'Add butter and stir until melted.'),
('3486', '7', 'Remove skillet from heat and stir in zest, parsley, and salt and pepper to taste. Sprinkle pecan shallot topping over fish.'),
('3486', '8', 'var article'),
('3486', '9', 'Type_27_data = {}.'),
('3486', '10', 'article'),
('3486', '11', 'Type_27_data.init_step_by_step_images = 0.'),
('3487', '1', 'Drizzle 1 tablespoon of olive oil over the halibut and season with salt and pepper.'),
('3487', '2', 'Heat a grill pan over high heat. Cook the fish on the grill pan until just cooked through, about 4 minutes per side, depending on thickness.'),
('3487', '3', 'In a medium saucepan, heat the 3 tablespoons of olive oil over medium-high heat.'),
('3487', '4', 'Add the shallots and cook for 1 minute.'),
('3487', '5', 'Add the garlic and artichokes and cook until golden brown, about 5 minutes.'),
('3487', '6', 'Add the white wine and stir, scraping the brown bits off the bottom of the pan with a wooden spoon.'),
('3487', '7', 'Add the chicken broth, tomatoes and juice, thyme, and 1/4 teaspoon each salt and pepper. Bring to a simmer.'),
('3487', '8', 'Ladle the artichoke and tomato broth into shallow bowls. Top with the grilled halibut.'),
('3487', '9', 'Serve immediately.'),
('3490', '1', 'Preheat the oven to 42'),
('3490', '2', 'Heat the olive oil in a large enameled cast-iron casserole.'),
('3490', '3', 'Add the onion, leek and garlic, cover and cook over low heat, stirring occasionally, until softened, about 10 minutes.'),
('3490', '4', 'Add the wine and cook until almost evaporated, about 3 minutes.'),
('3490', '5', 'Add the squash, Swiss chard, red and yellow bell peppers, fennel seeds, thyme and crushed red pepper. Season the vegetables generously with salt and pepper, cover and cook over low heat, stirring occasionally, until the squash is tender, about 15 minutes.'),
('3490', '6', 'Spread half of the vegetable stew in an 8-by-11-inch glass or ceramic baking dish. Season the halibut with salt and pepper and nestle the fillets in the stew. cover with the remaining vegetables.'),
('3490', '7', 'Bake for about 15 minutes, or until the halibut is just cooked through. Sprinkle with the basil and serve.'),
('3491', '1', 'Heat grill to medium-high. Lightly brush fish with olive oil, and season to taste with kosher salt and black pepper. Grill fish over direct heat until firm and opaque throughout, about 4 to 6 minutes per side. Fish should flake easily but remain moist.'),
('3491', '2', 'Brush bread lightly with olive oil, and grill until slightly toasted. Rub the cut side of garlic cloves over the bread.'),
('3491', '3', 'Combine mayonnaise and mustard.'),
('3491', '4', 'Spread mayonnaise mixture on 4 slices of bread. Top with arugula, fish fillets, Grilled Puttanesca Salsa, and remaining bread slices.'),
('3491', '5', 'Serve immediately.'),
('3493', '1', 'Preheat the oven to 400 degrees F (200 degrees C).'),
('3493', '2', 'Line a baking sheet with foil.'),
('3493', '3', 'Combine panko bread crumbs, parsley, dill, chives, extra-virgin olive oil, lemon zest, sea salt, and black pepper in a bowl. Taste and adjust with more salt if desired.'),
('3493', '4', 'Rinse halibut fillets and pat dry with a paper towel.'),
('3493', '5', 'Place halibut fillets onto the prepared baking sheet.'),
('3493', '6', 'Generously spoon the herbed crumbs over the fish, and lightly press crumb mixture onto each fillet.'),
('3493', '7', 'Bake in the preheated oven until crumb topping is lightly browned and fish flakes easily with a fork, 10 to 15 minutes.'),
('3494', '1', 'In large, deep skillet, heat the oil.'),
('3494', '2', 'Add the onion, ginger and garlic and cook over moderate heat, stirring frequently, until lightly browned, about 6 minutes.'),
('3494', '3', 'Add the cayenne, turmeric and coriander and cook for 1 minute, stirring.'),
('3494', '4', 'Whisk in the yogurt, then add the cream, garam masala and saffron and bring to a boil. Reduce the heat and simmer the sauce until slightly thickened, about 10 minutes. Season with salt.'),
('3494', '5', 'Add the halibut to the sauce and turn to coat. Cook over moderate heat, turning once, until the fish is cooked through, about 10 minutes.'),
('3494', '6', 'Serve with basmati rice and warm naan.'),
('3496', '1', 'Cut halibut filet into 30 (1-inch) pieces. Slice lemons crosswise into 30 thin slices. Soak bamboo skewers and bay leaves in water for 1/2 hour. Thread each skewer with 1 bay leaf, 1 piece of halibut, and 1 lemon slice.'),
('3496', '2', 'Brush skewers evenly with olive oil, and sprinkle with salt and black pepper. Grill kebabs over medium heat for about 2-3 minutes per side.'),
('3497', '1', 'Preheat the oven to 40'),
('3497', '2', 'Lightly oil a baking dish. On a work surface, overlap 3 of the grape leaves, vein side up, to create a 7- to 8-inch round. Repeat with the remaining grape leaves for a total of 4 rounds.'),
('3497', '3', 'Drizzle 1 teaspoon of the olive oil into the center of each round. sprinkle 1 teaspoon of the thyme over all of the rounds. Season with salt and white pepper. Set the halibut on the seasoned oil and fold the grape leaves around the fish. Arrange the fish packets, seam side down, in the baking dish. Roast for about 20 minutes, or until the grape leaves are crisp and the fish is just cooked through.'),
('3497', '4', 'Meanwhile, in a small bowl, whisk the lemon juice with the mustard and the remaining 1/4 cup of olive oil and 1 teaspoon of thyme. Season the vinaigrette with salt and white pepper.'),
('3497', '5', 'Transfer the fish packets to a platter. Carefully peel back the grape leaves. Spoon the vinaigrette over the fish and serve hot or at room temperature.'),
('3498', '1', 'Preheat oven to 375 degrees.  Or get your grill fired up to a medium heat.'),
('3498', '2', 'Combine all vegetables and olives in a bowl with a couple tablespoons of olive oil.  Season with salt and pepper.   Also, season fish with little salt and pepper here.'),
('3498', '3', 'Tear off 2 sheets of parchment paper about 24" long each.  (use foil if cooking on a grill.)  Some people will cut the paper into a heart shape (keep it folded in half and cut the shape of one-half a heart, Elementary school Valentines anyone!)  I just use the square shape as is.'),
('3498', '4', 'Using the bottom half of each parchment packet (keep the other half to fold over and make the packet), divide the veggies between the two papers, being sure to place in the center of the square, leaving at least an inch of space around the edge.'),
('3498', '5', 'Place fish on top of this and thyme sprig on top of fish.  Give everything a good squeeze of lemon juice.  And now you''re ready to crimp it shut!'),
('3498', '6', 'Bring the other half of the paper to cover the fish and vegetables.  Starting at one corner, fold the paper onto itself.  Moving around the edge of the paper, you''ll come to the other corner which you can tuck under.  You want to create a good seal, because basically, the fish and vegetables are going to steam inside the packet.'),
('3498', '7', 'Place on a baking sheet and bake 15-20 mins, depending on thickness of fish.  If using a grill, just place your foil pack right on the rack.'),
('3498', '8', 'When the fish is cooked, remove from oven and let sit for a minute, to let the steam dissipate a bit.  Depending on the setting, I place the packet on plate and just cut an X in the top of the packet and peel back the paper or foil a bit to expose the goodies inside.  Or you can slice open the packet on the side and slide the contents and all the juices onto a plate or shallow dinner bowl.  Finish with another hit of lemon juice if you want and enjoy.'),
('3499', '1', 'In a large saucepan, melt 2 tablespoons of the butter.'),
('3499', '2', 'Add the chopped shallot and garlic and cook over moderate heat until softened, about 3 minutes.'),
('3499', '3', 'Add the squash, parsnip and turnip and cook over moderately high heat until they begin to soften, about 5 minutes. Season with salt and pepper.'),
('3499', '4', 'Add the wine, thyme sprigs and bay leaf and cook until the wine reduces by half, about 2 minutes.'),
('3499', '5', 'Add the stock, cover and simmer until the vegetables are tender, about 10 minutes.'),
('3499', '6', 'Meanwhile, in a large nonstick skillet, heat the olive oil. Season the halibut pieces with salt and pepper and dust them lightly with the flour.'),
('3499', '7', 'Add the halibut to the hot skillet and cook over moderately high heat until light golden, about 2 minutes per side.'),
('3499', '8', 'Add the fish to the vegetables and simmer for 2 minutes. Using a slotted spoon, transfer the fish and vegetables to shallow bowls. Discard the thyme sprigs and bay leaf. Swirl the remaining 1 tablespoon of butter into the broth. Season with salt and pepper and spoon over the stew.'),
('3499', '9', 'Garnish with the thyme leaves and serve.'),
('3501', '1', 'Preheat the oven to 400F.'),
('3501', '2', 'Spread the onions and orange zest in a large (13  9-inch) roasting pan. drizzle with the olive oil. season with salt and a grinding of black pepper. Roast for 15 minutes, stirring once.'),
('3501', '3', 'Add the figs (if using dried, see the Variation below) and half of the oregano. Roast until the onions begin to brown at the edges, about 10 minutes.'),
('3501', '4', 'Remove the pan from the oven. Increase the oven temperature to 450F.'),
('3501', '5', 'Push the onions and figs to the side in the pan and add the halibut.'),
('3501', '6', 'Drizzle the orange juice over the fish. Sprinkle with the remaining oregano and salt and pepper to taste. Spoon some of the onions on top of the halibut. Return the pan to the oven and roast until the fish is cooked through, 10 to 12 minutes.'),
('3501', '7', 'Serve at once, with the roasted onions and figs spooned over the fish.Variation with dried figs: Trim off the stems of 8 dried Calimyrna or Black Mission figs.'),
('3501', '8', 'Combine the figs and 1 cup water in a small saucepan and heat to a boil. Cook, covered, over low heat until the figs are plumped and tender and most of the water has been absorbed, 20 to 25 minutes. Cool. then drain and cut the figs in half The figs can be prepared 2 or 3 days ahead and refrigerated, tightly covered, until ready to use.'),
