INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('2058', '4', 'Let fish stand at room temperature 10 minutes.'),
('2058', '5', 'Remove from buttermilk mixture, allowing excess to drip off. Dredge fish in cornmeal mixture, shaking off excess.'),
('2058', '6', 'Pour oil to depth of 2 inches into a large, deep cast-iron or heavy-duty skillet. heat to 36'),
('2058', '7', 'Fry fish, in batches, 2 minutes on each side or until golden brown.'),
('2058', '8', 'Transfer to a wire rack on a paper towel-lined jelly-roll pan. Keep warm in a 225 oven until ready to serve.'),
('2058', '9', '*All-purpose flour or plain yellow cornmeal may be substituted.'),
('2059', '1', 'Preheat grill for medium heat and lightly oil the grate.'),
('2059', '2', 'Season both sides of each catfish fillet with Greek seasoning. Sprinkle feta cheese and mint over one side of each fillet. drizzle olive oil over the cheese and mint. Beginning with narrower end, roll fish tightly around the filling and secure with a toothpick.'),
('2059', '3', 'Cook on preheated grill until the fish flakes easily with a fork, 20 to 25 minutes.'),
('2061', '1', 'Heat a fryer or a deep pot halfway filled with oil to 350 degrees F. Sprinkle both sides of each catfish with salt and crab boil seasoning. In a separate bowl, combine the flour and the cornmeal. Dredge the catfish in the flour mixture and place in fryer. Deep fry for approximately 7 to 8 minutes until done.'),
('2061', '2', 'Drain on paper towels.'),
('2062', '1', 'Heat a large nonstick skillet over medium-high heat. Coat pan and fillets with cooking spray. Sprinkle fillets evenly with salt and pepper.'),
('2062', '2', 'Add 2 fillets to pan, flat sides up. cook 4 minutes on 1 side or until browned. Turn fillets over. spoon 1 tablespoon salsa over each fillet. Cook 3 minutes or until fish flakes easily when tested with a fork or until desired degree of doneness. Repeat procedure with remaining 2 fillets.'),
('2062', '3', 'Serve with lime wedges and Cilantro-Chipotle Rice.'),
('2065', '1', 'Combine first 7 ingredients in a food processor. add 1/2 teaspoon salt. Process until pureed.'),
('2065', '2', 'Heat 1 1/2 teaspoons oil in a large nonstick skillet over medium-high heat. Sprinkle fish with 1/4 teaspoon salt and pepper.'),
('2065', '3', 'Add 3 fillets to pan. cook 3 minutes per side or until fish flakes easily when tested with a fork.'),
('2065', '4', 'Remove from pan, and keep warm. Repeat procedure with remaining oil and fillets. serve with sauce.'),
('2066', '1', 'Working with 1 piece of fish at a time, remove from buttermilk mixture, shaking off any excess, and dredge in flour mixture to coat.'),
('2066', '2', 'Transfer to a plate and repeat process with remaining fillets.'),
('2067', '1', 'Marinate the Fish -'),
('2067', '2', 'Put the fish in a ziplock bag.'),
('2067', '3', 'Mix all of the remaining ingredients under Fish Ingredients together and pour in the ziplock bag.  Put in the fridge while you prepare the remaining components or up to 2 hours.'),
('2067', '4', 'Pickle the Vegetables -'),
('2067', '5', 'Mix together the two vinegars, the 1/4 cup honey, 1/2 teaspoon Sriracha, 1 teaspoon salt.'),
('2067', '6', 'Add the carrots, onions, radishes, and cucumber and mix together.  Set aside for at least 30 minutes and up to 2 hours.  Note - you can really use any combo of these veggies you wish.'),
('2067', '7', 'Make the yogurt sauce -'),
('2067', '8', 'Mix together the yogurt, 1 tablespoon Sriracha, 1/4 teaspoon honey, and 1/4 teaspoon salt.  Set aside.'),
('2067', '9', 'Make the noodles and edamame - Boil water and add the rice noodles.  About 2 minutes before the noodles are done, add the edamame. Cook until al dente.'),
('2067', '10', 'Drain and Rinse with cold water.  Return to the pot and just before serving, add the sesame seeds, 4-6 TB (to taste) of the vegetable pickling liquid, and salt to taste.'),
('2067', '11', 'Cook the fish: Broil for about 6-10 minutes until browned and cooked through.  The cooking time really depends on the thickness of your fish.'),
('2067', '12', 'Assemble the Dish: In a shallow bowl or plate, place a mound of noodles and edamame, top with a piece of fish, drizzle the yogurt sauce over the fish, top with a scoop of the picked vegetables (drained of the pickling juice), and sprinkle with cilantro.'),
('2067', '13', 'Enjoy!'),
('2068', '1', 'Combine first 3 ingredients in a shallow dish. Dip fillets in buttermilk, allowing excess to drip off. sprinkle with salt and peppers, and dredge in cornbread mixture.'),
('2068', '2', 'Pour oil to depth of 4 inches into an electric fryer or Dutch oven. heat to 40'),
('2068', '3', 'Fry fillets, 2 at a time, 2 to 3 minutes or until they float. drain on paper towels.'),
('1580', '1', 'In a medium bowl, stir the butter with the Corn Pops, bread crumbs, curry powder, salt and cayenne.'),
('1580', '2', 'Transfer the butter to a piece of plastic wrap and form it into a 3-inch-long cylinder. Refrigerate the Corn Pops butter until firm.'),
('1580', '3', 'Meanwhile, in a medium saucepan, combine the milk with the bay leaf and star anise. Break each ear of corn in half and add them to the saucepan. Simmer over moderately low heat until the corn is very tender, about 40 minutes.'),
('1580', '4', 'Let cool slightly, then cut the kernels from the cobs and transfer them to a blender. Discard the bay leaf and star anise and add 1/2 cup of the milk to the blender. Blend at low speed until pureed. Increase the speed to high and gradually add the remaining milk. puree until very smooth.'),
('1580', '5', 'Add the crme frache and puree until blended.'),
('1580', '6', 'Preheat the oven to 25'),
('1580', '7', 'Cut the Corn Pops butter into 4 pieces. In a large nonstick skillet, heat the grapeseed oil until shimmering. Season the halibut with salt and pepper and cook over high heat, turning once, until golden, about 6 minutes.'),
('1580', '8', 'Transfer the halibut to a baking dish and top each fillet with a slice of the Corn Pops butter.'),
('1580', '9', 'Bake in the oven for about 2 minutes, or just until the butter begins to melt.'),
('1580', '10', 'Add the basil to the blender and puree with the corn soup. season with salt.'),
('1580', '11', 'Transfer the halibut fillets to shallow bowls.'),
('1580', '12', 'Pour the soup all around, garnish with basil sprigs and serve.'),
('1581', '1', 'Saut shallot in butter in a large Dutch oven over medium heat, stirring constantly, 2 minutes or until tender.'),
('1581', '2', 'Whisk in flour and salt until smooth. Cook 1 minute, whisking constantly. Gradually whisk in chicken broth.'),
('1581', '3', 'Add potatoes and bay leaf. Cover and bring to a boil. reduce heat, and simmer, uncovered, 15 minutes or until potatoes are almost tender.'),
('1581', '4', 'Add salmon. simmer 5 minutes or until fish flakes with a fork and potatoes are tender.'),
('1581', '5', 'Discard bay leaf. Stir in cream, 2 tablespoons chives, vinegar, and next 3 ingredients. Cook over medium heat, stirring often, 2 minutes or until thoroughly heated. (Do not boil.) Ladle into bowls. sprinkle with remaining 2 tablespoons chives.'),
('1582', '1', 'In a medium bowl, combine the tomatoes and their juices with the shallots, garlic, vinegar, chives, parsley, 2 tablespoons of the olive oil and 1/4 teaspoon of the ground fennel. Season with salt and pepper.'),
('1582', '2', 'In a small bowl, mix the remaining 3/4 teaspoon of ground fennel with 1/2 teaspoon each of salt and pepper. Sprinkle the mixture all over the fish. In a medium nonstick skillet, heat the remaining 1 tablespoon of olive oil until shimmering.'),
('1582', '3', 'Add the halibut and cook over moderately high heat until browned on the bottom, about 5 minutes. Flip the fillets and add the butter to the skillet. spoon the butter over the fillets as they cook, about 2 minutes longer.'),
('1582', '4', 'Transfer the halibut to plates, spoon the tomato vinaigrette on top and serve.'),
('1583', '1', 'In a saucepan, melt 3 tablespoons of the butter.'),
('1583', '2', 'Add the onion and cook over moderate heat until softened, 7 minutes.'),
('1583', '3', 'Add the red wine, beef stock and thyme and bring to a boil. Simmer until the liquid has reduced to 3/4 cup, 1 hour and 15 minutes. strain into a clean saucepan. Season with salt and pepper, cover and keep hot.'),
('1583', '4', 'Meanwhile, bring a medium saucepan of water to a boil.'),
('1583', '5', 'Add the wild rice and a pinch of salt, cover and simmer over low heat until tender, about 25 minutes.'),
('1583', '6', 'Drain the rice and return it to the saucepan. Season with salt, cover and keep warm.'),
('1583', '7', 'Preheat the oven to 32'),
('1583', '8', 'In a medium skillet, melt the remaining 2 tablespoons of butter.'),
('1583', '9', 'Add the shiitake and season with salt and pepper. Cover and cook, stirring occasionally, until tender and browned, about 5 minutes.'),
('1583', '10', 'Arrange the salmon fillets on a rimmed baking sheet, skinned side down, and season with salt and pepper.'),
('1583', '11', 'Bake for about 15 minutes, until just cooked in the center.'),
('1583', '12', 'Spoon the wild rice onto plates and set the salmon fillets on top. Spoon the shiitake mushrooms and red wine sauce over the fish and serve.'),
('1585', '1', 'Cook''s Note: The halibut can be substituted with 24 ounces of sole fillets. Reduce the cooking time in the wine mixture to 3 to 4 minutes.'),
('1585', '2', 'Spray a 7 by 11-inch glass baking dish with cooking spray. Set aside.'),
('1585', '3', 'For the bechamel sauce: In a 2-quart saucepan, melt the butter over medium heat.'),
('1585', '4', 'Add the flour and whisk until smooth, about 2 minutes. Gradually add the warm milk, whisking constantly to prevent lumps. Simmer over medium heat, whisking constantly, until the sauce is thick and smooth, about 10 minutes.'),
('1585', '5', 'Remove the pan from the heat and stir in the cheese, salt, pepper, and nutmeg.'),
('1585', '6', 'For the halibut: In a large saucepan, bring the wine and water to a boil over medium-high heat. Reduce the heat to a simmer and add the halibut. Cover the pan and cook until the flesh is opaque, 8 to 10 minutes. Using a fish spatula, carefully remove the fish and arrange in a single layer in the prepared baking dish. Season with salt and pepper.'),
('1585', '7', 'Preheat a broiler. Spoon the bechamel sauce over the fish and top with the Parmesan. Dot with butter and broil until golden, 2 to 4 minutes.'),
('1587', '1', 'Preheat oven to 350 degrees.'),
('1587', '2', 'Heat a large skillet to medium high heat.'),
('1587', '3', 'Add 1 tablespoon of butter and then add two fillets to pan. Cook for 3 to 5 minutes, until golden brown on bottom. Turn over and cook for another 2 to 3 minutes.'),
('1587', '4', 'Place fillets on a baking sheet.'),
('1587', '5', 'Saute the other two fillets in the same way and place them on the baking sheet.'),
('1587', '6', 'Place fillets in oven for 5 minutes while youre finishing the sauce.Cook shallots until translucent, about 3 minutes, stirring constantly.'),
('1587', '7', 'Add corn and cook another 3 to 5 minutes, until corn is lightly browned.'),
('1587', '8', 'Add half and half to pan and stir, scraping up bits from bottom of pan. Simmer over medium heat until sauce is reduced slightly.'),
('1587', '9', 'Add in minced tarragon, Tabasco and salt and pepper to taste.'),
('1587', '10', 'Remove from heat.Plate immediately, spooning sauce on to plate and then add fillets.'),
('1587', '11', 'Add tarragon leaves and come of corn as a garnish.'),
('1588', '1', 'Preheat oven 42'),
('1588', '2', 'Grate zest from lemons to equal 4 tsp.'),
('1588', '3', 'Cut lemons in half. squeeze juice from lemons into a measuring cup to equal 2 Tbsp.'),
('1588', '4', 'Combine panko, paprika, and 2 tsp. lemon zest in a shallow dish. Sprinkle fish with 1 tsp. salt. Dip fish in 1/4 cup melted butter. dredge in panko mixture, pressing panko to adhere.'),
('1588', '5', 'Place fish on a lightly greased rack in an aluminum foil-lined broiler pan.'),
('1588', '6', 'Drizzle remaining 2 Tbsp. melted butter over fish.'),
('1588', '7', 'Bake 20 to 25 minutes or until fish flakes with a fork.'),
('1588', '8', 'Meanwhile, prepare pasta according to package directions. Melt 2 Tbsp. butter in a large skillet over medium heat. add onion, and saut 5 to 6 minutes or until golden.'),
('1588', '9', 'Add garlic, and cook 1 minute.'),
('1588', '10', 'Add tomatoes, and cook 5 to 6 minutes or until tomato mixture begins to thicken. Stir in 2 Tbsp. lemon juice, 2 Tbsp. capers, and remaining 2 tsp. lemon zest and 1 tsp. salt. cook 2 to 3 minutes.'),
('1588', '11', 'Remove from heat, and toss with hot cooked pasta, feta cheese, and basil.'),
('1588', '12', 'Serve with fish.'),
('1589', '1', 'Combine first 3 ingredients in a large bowl, whisking well. Stir in edamame and next 4 ingredients. Set aside.'),
('1589', '2', 'Heat 2 tablespoons butter in a skillet over medium-high heat. Cook 2 trout fillets, skin side down, 5 minutes or until skin becomes crispy and lightly browned. Turn fish and cook an additional 5 minutes or until done. Repeat with remaining butter and trout.'),
('1589', '3', 'Spoon edamame salad on each of four plates. Top with trout and Crab-stuffed Piquillos.'),
('1589', '4', 'Garnish, if desired.'),
('1590', '1', 'Prepare Peach-Habanero Chile Sauce. keep warm.'),
('1590', '2', 'Process pecans in a food processor until finely ground.'),
('1590', '3', 'Combine pecans, 1/2 cup flour, baking powder, salt, and pepper in a shallow dish.'),
('1590', '4', 'Place eggs in another shallow dish.'),
('1590', '5', 'Coat fillets lightly in remaining 1/2 cup flour. Dip fillets into eggs, and dredge in pecan mixture.'),
('1590', '6', 'Melt 2 tablespoons butter with 2 tablespoons oil in a large skillet over medium-high heat. Cook 2 fillets 4 minutes on each side or until golden. Repeat with remaining butter, oil, and fillets.'),
('1590', '7', 'Serve immediately with Peach-Habanero Chile Sauce.'),
('1591', '1', 'Sprinkle fillets with 1 tsp. seasoning.'),
('1591', '2', 'Combine remaining seasoning, flour, and cornmeal. Dredge fillets in flour mixture, shaking off excess.'),
('1591', '3', 'Melt butter with oil in a large skillet over medium-high heat. add fillets, and cook 3 to 4 minutes on each side or until fish flakes with a fork. Squeeze juice from lemon over fillets, and garnish, if desired.'),
('1591', '4', 'Serve immediately.'),
('1591', '5', '*Creole seasoning may be substituted.'),
('1591', '6', 'Cajun-Seasoned Pan-Fried Chicken Breasts: Substitute 4 (8-oz.) skinned and boned chicken breasts for tilapia. Proceed with recipe as directed, cooking 8 to 10 minutes on each side or until done. Prep: 10 min., Cook: 16 min.'),
('1591', '7', 'Cajun-Seasoned Pan-Fried Pork Chops: Substitute 4 (8-oz.) bone-in center-cut pork chops for tilapia. Proceed with recipe as directed, cooking 8 to 10 minutes on each side or until done. Prep: 10 min., Cook: 16 min.'),
('1593', '1', 'Heat a small skillet over high heat.'),
('1593', '2', 'Add the andouille and cook, stirring, until sizzling, about 1 minute.'),
('1593', '3', 'Transfer to a medium bowl and let cool to room temperature.'),
('1593', '4', 'Mix the sausage with the sliced olives, softened butter and minced shallot.'),
('1593', '5', 'Light a grill. Rub the salmon fillets all over with olive oil and season lightly with salt and pepper. Grill the salmon over high heat, turning once, until nicely charred and just cooked through, about 3 minutes per side.'),
('1593', '6', 'Transfer the salmon to plates, top with the buttered andouille mixture and serve immediately.'),
('1594', '1', 'Preheat the oven to 45'),
('1594', '2', 'In a large, shallow dish, mix 2 tablespoons of the lime juice with the olive oil.'),
('1594', '3', 'Add the halibut fillets and turn to coat. Refrigerate for 15 minutes.'),
('1594', '4', 'In a medium skillet, combine the fish stock, wine, shallot, white peppercorns, bay leaf and the remaining 2 tablespoons of lime juice. Boil over high heat until reduced to 1/2 cup, about 6 minutes.'),
('1594', '5', 'Add the cream, bring to a boil and simmer over moderately low heat until reduced to 2/3 cup, about 10 minutes. Strain the sauce into a small saucepan.'),
('1594', '6', 'Season the halibut fillets with salt and white pepper and transfer them to a large rimmed baking sheet.'),
('1594', '7', 'Bake in the upper third of the oven until just cooked through, about 10 minutes.'),
('1594', '8', 'Add the olives to the cream sauce and bring to a boil.'),
('1594', '9', 'Pour in any accumulated fish juices.'),
('1594', '10', 'Remove the sauce from the heat and whisk in the butter until incorporated. Stir in the parsley and season with salt and white pepper. Set the halibut fillets on warmed plates, spoon the sauce on top and serve.'),
('1595', '1', 'In a medium saucepan of boiling salted water, cook the potatoes until just tender, about 15 minutes. Using a slotted spoon, transfer the potatoes to a plate and let cool slightly. Separate the brussels sprouts into leaves.'),
('1595', '2', 'Add the leaves to the boiling water and cook until they turn bright green, about 2 minutes. drain. Peel the potatoes and cut them into 1/2-inch dice.'),
('1595', '3', 'In a large skillet, cook the bacon over moderate heat, turning once, until crisp, about 5 minutes.'),
('1595', '4', 'Drain the bacon and coarsely chop it.'),
('1595', '5', 'Pour off all but 2 tablespoons of the bacon fat from the skillet.'),
('1595', '6', 'Add the potatoes and cook over moderate heat until browned on the bottom, about 4 minutes. Stir the potatoes and cook until browned all over, about 3 minutes.'),
('1595', '7', 'Add the onion to the skillet and cook over moderate heat, stirring, until softened and starting to brown, about 4 minutes.'),
('1595', '8', 'Add the brussels sprout leaves and the bacon and cook, stirring, until heated through, about 1 minute. Season with salt and pepper.'),
('1595', '9', 'Meanwhile, in a medium saucepan, boil the apple cider with the applejack and butter until the cider glaze is reduced to 2/3 cup, about 25 minutes.'),
('1595', '10', 'Preheat the broiler. Season the salmon steaks with salt and pepper and brush them on both sides with the cider glaze. Arrange the steaks in a broiler pan or on a rack set in a rimmed baking sheet. Broil the salmon for about 8 minutes, brushing occasionally with the glaze, or until crisp and just cooked through.'),
('1595', '11', 'Reheat the brussels sprout hash.'),
('1595', '12', 'Brush the salmon steaks with any remaining cider glaze, then transfer to plates and serve with the hash.'),
('1596', '1', 'Preheat oven to 425F.  Rinse and pat dry the salmon fillet.'),
('1596', '2', 'Place fillet, skin side down, in a lightly greased baking pan just large enough to hold it.'),
('1596', '3', 'Mix together lemon zest, ground pepper, and salt, and press onto salmon fillet.'),
('1596', '4', 'Pour the cream over the salmon.'),
('1596', '5', 'Roast in the oven until the salmon is just cooked, about 25 minutes (check for done-ness with a fork, the salmon should flake but not appear dry).'),
('1596', '6', 'Serve over the whipped parsnips with the cream sauce from the pan scraped/poured over each serving.  Season with extra salt, if desired.  Accompany with a cucumber salad or another green vegetable.'),
('1596', '7', 'Place parsnips in a pot, and fill with water just to cover.  Cover and bring to a boil, then turn down to a simmer and cook until the parsnip is quite tender, about 30 minutes.'),
('1596', '8', 'Drain, then return the parsnips to the pot, add the butter and the sour cream.  Use a handheld mixer to whip the parsnips, butter, and sour cream together, adding more butter or sour cream if they seem too dry.  Season to taste with salt and pepper.'),
('1596', '9', 'Serve with roast salmon.'),
('1598', '1', 'Preheat your oven to 400 (200C)'),
('1598', '2', 'Combine 1 tbsp breadcrumbs with 1 tbsp Parmesan. Used my food processor because I wanted to put some extra flavor in the topping, so I addeda littleleft-over chorizo.Its the perfect way to putflavor and structure in your topping. You dont need a lot of chorizo, just a few tiny pieces. Pulsate until it ends up pretty fine. You can do this with any kind of hard sausage or even crumbled up bacon, or just stick to breadcrumbs and Parmesan if you like it plain.Peel a medium carrot. Finely mince the carrot and onion. You can alsoadd grated garlic if you like, I didnt add it this time.Chop as much (or as little) dill as you like or simply use dried dill. Im not too crazy about dill, but do like how it combines with fish, so used a moderate amount.Action shot! I love how this one came out. If the light outside gets so bad (during autumn) Im forced to use a tripod, I might as well use it to my advantage.'),
('1598', '3', 'Heat two tbsp butter and sautee the onion and carrot over medium heat. Keep stirring every now and then, nothing should end up browned.Thawed 4 pieces of whitefish fillet. Always have them in my freezer, you can do lots of things with them. They make great fish cookies with a little leftover mashed potatoes, some vegetables and fresh herbs.When the onions are translucent, add the fish. Just get it all in there, lower the heat and let it cook until it starts to fall apart. Flip it over every now and then.Pretty soon the fish is going to fall apart and flake. Break up the coarse pieces.Top the fish with 1 heaping tbsp flour, stir a bit and cook for one minute. Slowly pour in the milk while carefully stirring until you have a sauce consistency you like. It shouldnt be too thin, though.'),
('1598', '4', 'Add a good pinch of salt and pepper. I used my fingers and kept checking the seasoning, so cant give you exact quantities. It just varies every time I make this dish.Ive added 1/2 tsp Dijon mustard, its pretty heavy in flavor but goes really well with the fish. Use less if you like. Also threw in a heaping tbsp sour cream, and for lack of fresh lemon juice, I committed sacrilege and used one of those plastic jars and just squeezed a little in. Dont tell anyone!In goes the dill. Now simmer the sauce over low heat for another minute or two.'),
('1598', '5', 'Transfer it all to a baking dish. When you see this creamy fish concoction, you just know its gonna taste fantastic with french fries, right?Sprinkle the bread/Parmesan mix on top.Until everything is royally covered. Pop in a preheated oven for 10 to 15 minutes, until the top is golden brown and crispy.'),
('1598', '6', 'Serve with french fries and a nice mixed vegetable salad on the side. My boy doesnt even need utensils with this, he simply uses the fish as a dip for his French fries. No, I didnt raise him like that, but what can you do? :)Printable'),
('1598', '7', 'Recipe kayotic.com'),
('1601', '1', 'Pre-heat the oven to 400Peel, then grate the potatoes and onions into a bowl'),
('1601', '2', 'Season generously with salt and pepper'),
('1601', '3', 'Tip into a tea towel and wring out until as dry as possible'),
('1601', '4', 'Wipe a thin layer of oil around the muffin tins to stop the rosti from sticking'),
('1601', '5', 'Press a tbsp of potato mixture firmly into the bottom of each hole (it should come about 1cm up the side of the tin)Put a tiny knob of butter on top (about  tsp)  (the butter helps the rosti brown, but add too much and theyll be greasy)'),
('1601', '6', 'Bake for about 35  45 minutes, depending on the thickness of the potato  you want the tops to be golden and crispy looking. They will get there. Be patient.Turn out so that the bottom is now the top'),
('1601', '7', 'Arrange on plates with a blob of dour cream, drape over the salmon and garnish with a few strands of dill.'),
('1601', '8', 'Serve a lemon quarter on the side for squeezing.'),
('1602', '1', 'In a shallow dish, combine the pistachios, salt, and pepper. Dredge the salmon in the pistachio mixture, pressing gently to coat.'),
('1602', '2', 'In a small skillet, heat the oil and garlic over medium heat.'),
('1602', '3', 'Add the salmon and cook until browned, about 2 to 3 minutes. Reduce the heat to medium. turn the salmon and cook until salmon flakes easily with fork, about 2 or 3 minutes more.'),
('1602', '4', 'Transfer the fillets to serving plates.'),
('1602', '5', 'Serve with Lemon Cream Sauce, and garnish with chopped pistachios, if desired.'),
('1602', '6', 'In a small saucepan, melt the butter over medium-high heat.'),
('1602', '7', 'Add the flour, whisking to combine and cook for 2 minutes. Reduce the heat to medium. stir in the broth and cream and simmer until thickened, whisking frequently, about 3 minutes.'),
('1602', '8', 'Add the lemon zest, lemon juice, salt, and pepper, whisking to combine. Cook for 2 minutes, whisking constantly.'),
('1602', '9', 'Pour into a serving dish and serve with the salmon.'),
('1605', '1', 'Preheat oven to 400F. Melt butter with 2tablespoons oil in large skillet over medium-highheat.'),
('1605', '2', 'Add mushrooms and saute untilbeginning to color. Stir in garlic and parsley.'),
('1605', '3', 'Add wine. simmer until almost evaporated,scraping up browned bits in skillet, about 1minute.'),
('1605', '4', 'Remove from heat. Stir in lemon peeland lemon juice. Season with salt and pepper.'),
('1605', '5', 'Brush 13x9x2-inch glass baking dish with1 tablespoon oil.'),
('1605', '6', 'Place cod, skin side down,in baking dish. Sprinkle with salt and pepper.Cover with mushroom mixture. Sprinklewith breadcrumbs and Parmesan. drizzle withremaining 1 tablespoon oil.'),
('1605', '7', 'Bake until fish isopaque in center, about 20 minutes.'),
('1608', '1', 'Preheat oven to 40'),
('1608', '2', 'Heat butter and 1 teaspoon oil in a large nonstick skillet over medium-high heat.'),
('1608', '3', 'Brush tops of fish fillets with egg white. sprinkle fish evenly with 1/4 teaspoon salt and 1/4 teaspoon pepper. Coat tops of fish with nuts, pressing gently to adhere.'),
('1608', '4', 'Place half of fish, nuts side down, in pan. cook 3 minutes or until browned. Turn fish over. cook 4 minutes or until desired degree of doneness.'),
('1608', '5', 'Combine remaining 1 teaspoon olive oil, garlic, and asparagus on a jelly-roll pan coated with cooking spray. toss to combine. Sprinkle with remaining 1/4 teaspoon salt, remaining 1/4 teaspoon pepper, and thyme.'),
('1608', '6', 'Bake at 400 for 8 minutes or until crisp-tender.'),
('1608', '7', 'Serve with fish and lemon wedges.'),
('1609', '1', 'Heat the chicken stock in a medium saucepan.'),
('1609', '2', 'Add the chanterelle trimmings, cover and simmer over low heat for 10 minutes. Strain the broth and discard the trimmings.'),
('1609', '3', 'In a large skillet, heat the extra-virgin olive oil until shimmering.'),
('1609', '4', 'Add the chanterelles, season lightly with salt and pepper and cook over moderately high heat, stirring, until dry and golden brown, about 8 minutes.'),
('1609', '5', 'Add the garlic and cook, stirring frequently, until fragrant, about 3 minutes.'),
('1609', '6', 'Transfer the chanterelles to a plate.'),
('1609', '7', 'Add the mushroom broth to the skillet and boil until reduced to 1 cup, about 10 minutes. Return the chanterelles to the skillet.'),
('1609', '8', 'In a large saucepan of boiling salted water, cook the asparagus until almost tender, about 2 minutes.'),
('1609', '9', 'Remove from the heat and cover.'),
('1609', '10', 'Season the salmon with salt and pepper. In a large, deep skillet, heat the pure olive oil until shimmering.'),
('1609', '11', 'Add the salmon and cook over moderate heat for 3 minutes. Using a spatula, carefully turn the fillets and simmer until just cooked through, about 3 minutes longer.'),
('1609', '12', 'Bring the chanterelles to a boil and remove from the heat.'),
('1609', '13', 'Add the thyme and whisk inthe butter, 1 tablespoon at a time. Season with salt and pepper. Spoon the sauce into warmed shallow bowls. Set a salmon fillet in each bowl, spoon the Three Onion Risotto beside it and garnish with the asparagus.'),
('1610', '1', 'Pulse nuts in a food processor until finely ground. Rinse trout and pat dry. Season with salt inside and out.'),
('1610', '2', 'Beat egg in a pie plate.'),
('1610', '3', 'Spread ground nuts on a dinner plate. Dip both sides of trout first in egg and then nuts.'),
('1610', '4', 'Heat oil in a 12-inch heavy skillet over moderate heat until hot but not smoking and cook trout, shaking skillet to prevent sticking and turning once with a metal spatula, until browned on both sides and just cooked through, about 12 minutes total.'),
('1610', '5', 'While trout is cooking, melt butter in a small saucepan and stir in lemon juice. Season with salt and pepper and keep warm.'),
('1610', '6', 'Pour over trout and sprinkle fish with parsley.'),
('1612', '1', 'Using a sharp knife, remove the peel and bitter white pith from the grapefruit. Working over a medium bowl, carefully cut in between the membranes to release the sections into the bowl. Squeeze the remaining grapefruit juice into a separate bowl.'),
('1612', '2', 'Put the flour, egg and cornmeal in 3 shallow bowls. Season the trout fillets with salt and pepper and lightly dust them with flour, tapping off the excess. Dip the fillets in the beaten egg, then dredge them in the cornmeal.'),
('1612', '3', 'In a large skillet, melt 1 tablespoon of the butter.'),
('1612', '4', 'Add the sage leaves and cook over moderate heat, turning once, until crisp, about 2 minutes per side.'),
('1612', '5', 'Transfer the sage leaves to a plate lined with paper towels to drain.'),
('1612', '6', 'Add 1/4 inch of the vegetable oil to the skillet and heat until shimmering. Carefully add the trout fillets and fry over moderately high heat until golden brown and just cooked through, about 3 minutes per side. Divide the fillets among 4 plates.'),
('1612', '7', 'Discard the oil and wipe out the skillet with paper towels.'),
('1612', '8', 'Add the fresh grapefruit juice and water to the skillet and bring to a boil. cook for 1 minute. Reduce the heat to moderate, add the grapefruit sections and simmer the sauce for 1 minute.'),
('1612', '9', 'Remove the skillet from the heat and swirl in the remaining 2 tablespoons of butter, 1 tablespoon at a time. Season with salt and pepper and spoon the sauce and grapefruit sections over the trout.'),
('1612', '10', 'Garnish each fillet with 2 sage leaves and serve immediately.'),
('1613', '1', 'Sprinkle fish with 1/4 teaspoon salt and pepper.'),
('1613', '2', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('1613', '3', 'Add 2 fish fillets to pan. cook 2 minutes on each side or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('1613', '4', 'Remove from pan. cover and keep warm. Repeat with remaining fish.'),
('1613', '5', 'Add wine, broth, shallots, and garlic to pan. bring to a boil. Reduce heat, and simmer until reduced to about 1/2 cup (about 10 minutes).'),
('1613', '6', 'Remove from heat. stir in butter, remaining 1/4 teaspoon salt, chives, and tarragon. Spoon sauce over fish. serve immediately.'),
('1613', '7', 'Wine note: The delicate, mild flavor of sole calls for a white wine that''s not overtly oaky. I find that one of the new, so-called unoaked chardonnays works beautifully, especially since chardonnay often has a touch of buttery flavor that picks up on the essence of this rich-tasting sauce. New Zealand makes many of the best unoaked chardonnays. One fantastic example is Kim Crawford Unoaked Chardonnay 2005 from Marlborough, New Zealand ($17). -Karen MacNeil'),
('1614', '1', 'In a mini food processor, combine the parsley with the olive oil, shallot and lemon juice and process to a coarse puree. Season with salt and pepper.'),
('1614', '2', 'In a shallow bowl, mix the flour with 1 teaspoon of salt and 1/2 teaspoon of pepper. Press 1 tablespoon of the thyme leaves onto the halibut and dredge in the flour, shaking off the excess.'),
('1614', '3', 'In a large nonstick skillet, melt the butter. When the foam subsides, add the halibut pieces and cook over moderately high heat, turning once, until golden brown and just cooked, about 3 minutes per side. Reduce the heat to moderate if the fish is getting too dark.'),
('1614', '4', 'Transfer the halibut to plates and sprinkle with the remaining 1 teaspoon of thyme leaves.'),
('1614', '5', 'Serve with the parsley sauce.'),
('1615', '1', 'Heat the oven to 350F.'),
('1615', '2', 'Cut a piece of parchment to fit inside a large ovenproof skillet, saut pan, or flameproof baking dish. Lightly butter one side of the parchment.'),
('1615', '3', 'Combine the lemon juice, tarragon, and crme frache in a small bowl and set aside. Melt 2 Tbs. of the butter in the pan or baking dish over medium-high heat.'),
('1615', '4', 'Add the shallot and vermouth and reduce to a glaze. remove from the heat. Season the fillets with salt and pepper and arrange in a single layer in the pan.'),
('1615', '5', 'Pour the crme frache mixture over the salmon, cover with the parchment, butter side down, and bake until the salmon is just opaque throughout, 18 to 20 minutes. dont overcook.'),
('1615', '6', 'Transfer the salmon to a plate and keep warm.'),
('1615', '7', 'Put the pan over medium heat and reduce the sauce until its thick enough to lightly coat a spoon.'),
('1615', '8', 'Remove from the heat, whisk in the remaining 2 Tbs. butter, and taste for salt and pepper. Put each salmon fillet on a warm dinner plate and spoon the sauce over each.'),
('1615', '9', 'Garnish with the dill or chives.    Serving Suggestions'),
('1615', '10', 'Serve the salmon with spring peas or asparagus.    Drink Suggestions    Try a crisp French Chardonnay or Sauvignon Blanc with little or no oak, such as the Chablis from'),
('1615', '11', 'Rolland Lavantureux or the Domaine Chavet Menetou-Salon, a little-known Loire Sauvignon Blanc.'),
('1618', '1', 'Heat a large nonstick skillet over medium-high heat. Sprinkle fish evenly with salt and pepper. Coat pan with cooking spray.'),
('1618', '2', 'Add fish to pan. cook 2 minutes on each side or until fish flakes easily when tested with a fork.'),
('1618', '3', 'Remove fish from pan. keep warm.'),
('1618', '4', 'Add wine, rind, juice, capers, and herbes de Provence to pan. cook 30 seconds, stirring constantly.'),
('1618', '5', 'Remove pan from heat.'),
('1618', '6', 'Add butter to pan, stirring constantly with a whisk until butter melts and sauce is smooth.'),
('1618', '7', 'Serve sauce over fish. sprinkle with parsley.'),
('1619', '1', 'Heat a large, heavy cast-iron skillet over medium-high heat.'),
('1619', '2', 'Open up the trout, pat dry, and season with salt and pepper.'),
('1619', '3', 'Mix together the cornmeal, flour, 1 teaspoon salt, 1/2 teaspoon pepper, and the parsley in a wide bowl.'),
('1619', '4', 'Dip the trout into the cornmeal mix on the cut side only.  Make sure it is thoroughly coated.  If not cooking right away, place the fish on a platter in one layer, uncovered, in the refrigerator.'),
('1619', '5', 'Add 2 tablespoons of canola oil to the hot pan and when it is just below smoking, carefully add 1 or 2 trout-however many will fit in your pan-skin side up.  After 1 minute, add 2 teaspoons of butter to the pan.  Watch the skin, and when you see it begin to dimple and curl (this will take about 2 minutes), turn the fish.  Cook on the skin side for 30 seconds to a minute, just until the fish begins to curl.'),
('1619', '6', 'Remove from the pan and keep warm in a low oven while you repeat with the remaining oil, butter, and fish.'),
('1619', '7', 'Serve hot, with lemon wedges.'),
('1620', '1', 'In a small, dry skillet over medium-low heat, toast the pepitas lightly. Don''t allow them to brown. As soon as you begin to smell them, remove the pan from the heat and transfer to a large plate. Set aside.'),
('1620', '2', 'Preheat the oven to 400 degrees F.'),
('1620', '3', 'Sprinkle the halibut on both sides with 1 teaspoon of the salt and the pepper.'),
('1620', '4', 'Heat the oil in a large skillet with an ovenproof handle over medium-high heat until it begins to shimmer but is not smoking.'),
('1620', '5', 'Place the fillets skin side up in the hot oil and sear until the fish begins to turn color, 2 to 3 minutes. Turn the fillets and add the lemon juice, wine, and butter to the pan. As soon as the butter melts and becomes foamy, add the capers and tomatoes and simmer until the tomatoes release some juices, about 1 minute.'),
('1620', '6', 'Place the pan in the oven until the fish is cooked through, 7 to 10 minutes. Baste the fish with some of the juices and transfer to serving plates.'),
('1620', '7', 'Add the cup torn basil, pepitas, and the remaining teaspoon of salt to the pan juices and stir until the basil is slightly wilted. Spoon the mixture over the fish, garnish with fresh basil leaves, and serve.'),
('1621', '1', 'To prepare jam, combine first 3 ingredients in a food processor. process until smooth.'),
('1621', '2', 'Combine water, sugar, red wine vinegar, and dash of salt in a small saucepan over medium-high heat. Cook until sugar dissolves, stirring frequently. Reduce heat to medium.'),
('1621', '3', 'Add pureed bell pepper mixture. cook 7 minutes or until thickened and reduced to 1/2 cup, stirring frequently.'),
('1621', '4', 'Remove from heat. stir in lime juice. Cool.'),
('1621', '5', 'Preheat oven to 35'),
('1621', '6', 'To prepare grouper, place the panko, coconut, and cashews in food processor. pulse 4 times or until cashews are finely chopped.'),
('1621', '7', 'Place panko mixture in a shallow dish.'),
('1621', '8', 'Place flour in another shallow dish. place egg whites in another shallow dish. Sprinkle fillets with 1/8 teaspoon salt and black pepper. Dredge 1 fillet in flour. Dip fillet into egg whites. dredge in panko mixture, gently pressing coating onto fillet to adhere. Repeat procedure with remaining fillet, flour, egg whites, and panko mixture.'),
('1621', '9', 'Melt butter in a large nonstick skillet over medium-high heat.'),
('1621', '10', 'Add fillets. cook 2 minutes or until lightly browned on bottom. Turn fillets over. wrap handle of pan with foil.'),
('1621', '11', 'Place pan in oven. bake at 350 for 8 minutes or until fish flakes easily when tested with a fork.'),
('1621', '12', 'Serve immediately with jam and lime wedges, if desired.'),
('1622', '1', 'Rinse and pat dry your halibut. For lucky people who have family members who actually eat seafood, this recipe has enough sauce for two servings.Dredge the fish through the flour.Melt the butter in a frying pan and start cooking the fish. You can sprinkle on some pepper at this point, some salt, season it up a bit. Cook on a medium heat so the butter doesnt burn.In another small pot, start the butter melting and add the minced garlic.The steaks should take about 6 minutes per side on a medium heat and when they are done, flake like this.So the sauce is made in a separate pot.'),
('1622', '2', 'Add in the lemon juice, parsley, capers,wine and zest.Simmer it a while until the liquid is reduced.'),
('1622', '3', 'Serve like this, place the fish steak on the plate and drizzle the sauce, heavy on the lovely tidbits that are in the sauce.'),
('1623', '1', 'Transfer to a platter and keep warm in the 225-degree oven.'),
('1623', '2', 'To the same skillet, add the butter and melt it over medium flame.'),
('1623', '3', 'Add the chopped pecans and coconut, tossing well to combine. Saut, stirring often, for about 3 or 4 minutes until the pecans are fragrant and the coconut is a pale gold.'),
('1623', '4', 'Transfer the fish to serving plates. Sprinkle with the chopped fresh herb of your choice and garnish with the pecan-coconut mixture.'),
('1625', '1', 'Melt the butter in a Dutch oven over medium-high heat.'),
('1625', '2', 'Add the leeks and cook for about 7 minutes, until they begin to soften.'),
('1625', '3', 'Add the celery and carrot and cook for 5 minutes more.'),
('1625', '4', 'Add the garlic and saute for about 30 seconds.'),
('1625', '5', 'Add the potatoes and water, bring the liquid to a simmer, and cook for 10 minutes.'),
('1625', '6', 'Add the trout to the pot along with the milk. Reduce the heat to medium and simmer for 30 minutes (do not boil).'),
('1625', '7', 'Season to taste with salt and pepper. Ladle in the bowls, sprinkle with chopped chives, and serve with chowder crackers.'),
('1626', '1', 'Preheat oven to 400F. Mash butter, parsley, garlic, 1/2 teaspoon ground mixed peppercorns, and lemon peel in small bowl. Season to taste with salt.'),
('1626', '2', 'Heat oil in heavy large ovenproof skillet over medium-high heat. Sprinkle swordfish with salt and ground mixed peppercorns.'),
('1626', '3', 'Add swordfish to skillet. Cook until browned, about 3 minutes. Turn swordfish over and transfer to oven. Roast until just cooked through, about 10 minutes longer.'),
('1626', '4', 'Transfer swordfish to plates.'),
('1626', '5', 'Add seasoned butter to same skillet. Cook over medium-high heat, scraping up browned bits, until melted and bubbling.'),
('1626', '6', 'Pour butter sauce over swordfish and serve.'),
('1627', '1', 'For the gefilte fish:  Pulse the snapper in the robot coupe/food processor until it still has some texture.'),
('1627', '2', 'Put the snapper in a bowl over ice.  Make a thick paste with the matzoh meal and water. Boil the water and add thematzoh meal.'),
('1627', '3', 'Mix thoroughly.'),
('1627', '4', 'Remove the paste from the heat and whisk in the whole eggs. Keep ice cold. Whip the butter in the robot coupe and remove.'),
('1627', '5', 'Add the paste, the egg yolk and the red snapper to the robot coupe. Pulsegently until it just comes together.'),
('1627', '6', 'Add the butter, chilies, lemon zest and salt. Pulse gently again until incorporated. Keep the mixture cold until you are ready to cook it. Bring the fish stock to a boil with some salt. It should be well seasoned and thenturn down to a simmer. Shape the gefilte fish into 2-ounce portions. About 2  inches long and 1 1/2 inches wide.'),
('1627', '7', 'Put the fish patties into the stock and cook for about25 minutes.'),
('1627', '8', 'Remove from the pot and cover with the stock.  For the tomato habanero sauce:  In a pan with very little oil, char the onion, garlic, tomato and habanero. Put into the blender with the lime juice, orange juice, oregano and season with salt.'),
('1630', '1', 'Melt butter in a Dutch oven over medium-high heat.'),
('1630', '2', 'Add onion, carrot, celery, and garlic to pan. saut 10 minutes or until lightly browned. Stir in tomato paste. cook 1 minute. Stir in wine. cook 1 minute.'),
('1630', '3', 'Add potato and next 7 ingredients (potato through bay leaf). bring to a boil. Reduce heat. simmer 30 minutes.'),
('1630', '4', 'Add fish. Cover and simmer 10 minutes or until fish flakes easily when tested with a fork. Discard bay leaf.'),
('1632', '1', 'Pour the water into a sauce pan, add the fish bouillon cube, sugar and juice of 1/2 or 1 lime. Trim the asparagus ends. I usually grab one stalk by both ends and bend it. Wherever it breaks is a pretty good sign of where you should cut all of them. Peel only the ends that seem thicker than the spears.Season the cod with salt, pepper and some dried parsley and wrap each piece in parma ham. Bring a large pot of lightly salted water to a boil for the asparagus.'),
('1632', '2', 'Place the lime infused fish bouillon on the stove and bring it to a boil.'),
('1632', '3', 'Add a tbsp water to the cornstarch and stir until its dissolved. Once the lime water cooks you stir in the cornstarch.'),
('1632', '4', 'Let the sauce simmer over low heat while you continue.'),
('1632', '5', 'Heat some butter or butter combined with olive oil and give the cod 3 to 4 minutes on each side until theyre fully cooked. This depends on the thickness of your fish. Carefully drop the asparagus into the boiling water, cook them for 5 to 7 minutes (without a lid!) depending on how tender or crunchy you like them, and drain them well.As soon as the cod is done you season the lime sauce with salt and pepper to taste and you finish it with a knob of butter and some finely minced dill. I serve this with boiled (Parisienne) potatoes that I tossed with some butter and finely minced dill and parsley.Now grab your plates and start with the asparagus.'),
('1632', '6', 'Place a piece of fish on top of the asparagus and place a small handful of herbed potatoes on the side of the plate.'),
('1632', '7', 'Serve the rest in a separate bowl.'),
('1632', '8', 'Pour a drop of lime sauce on top of the fish, a little over the potatoes and serve the rest on the side.'),
('1633', '1', 'In a medium saucepan, heat the olive oil until a piece of scallion sizzles in it. Season the tuna pieces with salt and pepper and carefully add them to the saucepan. they should be completely immersed. Cook over low heat at a bare simmer until the tuna is just cooked through and a fork inserted in the fish comes out easily, about 7 minutes.'),
('1633', '2', 'Transfer the tuna to a plate and cover with foil to keep warm.'),
('1633', '3', 'In a small saucepan, heat 3 tablespoons of the tuna cooking oil.'),
('1633', '4', 'Add the scallions and ginger and saut over low heat until the scallions are tender, about 10 minutes.'),
('1633', '5', 'Add the balsamic vinegar and simmer for 1 minute. Stir in the soy sauce and ketchup and simmer gently for 1 minute.'),
('1633', '6', 'Remove from the heat and stir in the butter until smooth. Season the sauce with salt and pepper.'),
('1633', '7', 'Set 2 pieces of tuna on each plate. Using a slotted spoon, spread a layer of the scallions on top of the tuna. Spoon the sauce on the fish and serve.'),
('1634', '1', 'Mix flour, salt and pepper in a shallow dish. Thoroughly dredge fish fillets in the mixture.'),
('1634', '2', 'Heat oil in a large nonstick skillet over medium-high heat until shimmering but not smoking (see Tip).'),
('1634', '3', 'Add the fish and cook until lightly browned and just opaque in the center, 3 to 4 minutes per side.'),
('1634', '4', 'Transfer to a plate and cover loosely with foil.'),
('1634', '5', 'Add shallot to the pan and cook over medium-high heat, stirring often, until softened and beginning to brown, about 3 minutes.'),
('1634', '6', 'Add wine and bring to a simmer, scraping up any browned bits. Cook until most of the liquid has evaporated, 1 to 2 minutes.'),
('1634', '7', 'Add orange juice and mustard. bring to a boil. Reduce heat to low and simmer until the sauce thickens a bit, about 5 minutes.'),
('1634', '8', 'Add butter and parsley. stir until the butter has melted.'),
('1634', '9', 'Transfer fish to individual plates, top with sauce and serve.'),
('1635', '1', 'In a medium saucepan, heat 1 tablespoon of the oil.'),
('1635', '2', 'Add the carrot, parsnip and onion and cook over moderate heat, stirring occasionally, until crisp-tender, about 3 minutes.'),
('1635', '3', 'Add the water and butter, season with salt and pepper and cook until the vegetables are tender and the liquid is nearly evaporated, about 5 minutes. Stir in the mirin, soy sauce and Szechuan peppercorns and keep warm.'),
('1635', '4', 'In a large nonstick skillet, heat the remaining 1 tablespoon of canola oil until nearly smoking. Season the tuna with salt and pepper and cook over high heat, turning once, until browned on the outside but still pink in the center, about 5 minutes.'),
('1635', '5', 'Transfer to a cutting board.'),
('1635', '6', 'Add the garlic and spinach to the skillet, season with salt and pepper and cook over high heat, stirring, just until wilted. Mound the spinach on plates. Thinly slice the tuna and arrange over the spinach. Spoon the root vegetables and any juices on top, sprinkle with the parsley and serve.'),
('1637', '1', 'Sprinkle the salmon with salt and pepper.'),
('1637', '2', 'Place skin side up and rub 1 1/2 tablespoons softened butter all over the skin of the salmon.'),
('1637', '3', 'Transfer the salmon, buttered side up, to a sheet pan. Chill in the fridge to firm the butter, about 20 minutes.'),
('1637', '4', 'Preheat the broiler to high.'),
('1637', '5', 'Place the salmon about 5 inches from the heat source and cook until the skin is crispy and the fish is cooked through, 7 to 8 minutes.'),
('1637', '6', 'In a small saucepan over moderate heat, whisk together the remaining 1 1/2 tablespoons butter, lemon zest, lemon juice, mustard and tarragon leaves. Divide the sauce between 2 plates and place 1 piece of salmon on top of each pool of sauce.'),
('1637', '7', 'What Makes This Recipe Really Sing: This is the coolest way to get crispy skin on fish ever and the crispy skin is like a naturally salted and big flavored chip, so it''s the best part!'),
('1638', '1', 'Combine first 3 ingredients.'),
('1638', '2', 'Melt 1 teaspoon of butter with oil in a large nonstick skillet over low heat.'),
('1638', '3', 'While butter melts, sprinkle fish fillets with salt and black pepper.'),
('1638', '4', 'Place the flour in a shallow dish. Dredge fillets in flour. shake off excess flour.'),
('1638', '5', 'Increase heat to medium-high. heat 2 minutes or until butter turns golden brown.'),
('1638', '6', 'Add fillets to pan. saut 3 minutes on each side or until fish flakes easily when tested with a fork.'),
('1638', '7', 'Remove fillets from pan.'),
('1638', '8', 'Add broth mixture to pan, scraping to loosen browned bits. Bring to a boil. cook until reduced to 1/2 cup (about 3 minutes).'),
('1638', '9', 'Remove from heat. Stir in two teaspoons of butter with a whisk.'),
('1638', '10', 'Serve sauce over fillets.'),
('1638', '11', 'Garnish with lemon wedges, if desired.'),
('1639', '1', 'Set broiler on high.'),
('1639', '2', 'Place the salmon on a foil-lined broiler pan, season with  teaspoon salt, and broil until it is the same color throughout and flakes easily, 7 to 10 minutes, depending on thickness.Meanwhile, in a saucepan, over medium-high heat, heat the oil and 1 tablespoon butter until it melts.'),
('1639', '3', 'Add the shallot and cook until soft, about 1 minute.'),
('1639', '4', 'Add the wine and cook until reduced by half, about 3 minutes.Reduce heat to low and whisk in the mustard, dill,  teaspoon salt, and  teaspoon pepper.'),
('1639', '5', 'Remove from heat.'),
('1639', '6', 'Cut the remaining 2 tablespoons butter into pieces, add to the sauce, and whisk until incorporated.'),
('1639', '7', 'Place the salmon on individual plates, spoon the sauce over top, and sprinkle with additional dill.'),
('1639', '8', 'Serve with the cucumber slices (if desired).'),
('1642', '1', 'In a medium saucepan, heat 1 tablespoon of the olive oil.'),
('1642', '2', 'Add the shallot and cook over moderate heat until softened, about 4 minutes.'),
('1642', '3', 'Add the thyme sprig, black pepper, red wine and balsamic vinegar and boil over high heat until reduced to 2 tablespoons, about 12 minutes.'),
('1642', '4', 'Remove the pan from the heat and whisk in the cream, then whisk in the butter, 1 tablespoon at a time. Season the sauce with salt and pepper. Strain into a bowl and keep warm.'),
('1642', '5', 'In a large nonstick skillet, heat the remaining 1 tablespoon of olive oil until shimmering. Season the salmon fillets with salt and pepper and add them to the skillet, skinned side up. Cook over moderately high heat until the fillets are browned, about 4 minutes. Turn the salmon and cook over moderate heat until the fish is just opaque throughout, about 3 minutes longer.'),
('1642', '6', 'Transfer the salmon to plates, spoon the sauce over the fish and garnish with ground black pepper.'),
('1642', '7', 'Serve immediately.'),
('1643', '1', 'In a saucepan, melt 3 tablespoons of the butter.'),
('1643', '2', 'Add the onion and cook over moderate heat until softened, 7 minutes.'),
('1643', '3', 'Add the red wine, beef stock and thyme and bring to a boil. Simmer until the liquid has reduced to 3/4 cup, 1 hour and 15 minutes. strain into a clean saucepan. Season with salt and pepper, cover and keep hot.'),
('1643', '4', 'Meanwhile, bring a medium saucepan of water to a boil.'),
('1643', '5', 'Add the wild rice and a pinch of salt, cover and simmer over low heat until tender, about 25 minutes.'),
('1643', '6', 'Drain the rice and return it to the saucepan. Season with salt, cover and keep warm.'),
('1643', '7', 'Preheat the oven to 32'),
('1643', '8', 'In a medium skillet, melt the remaining 2 tablespoons of butter.'),
('1643', '9', 'Add the shiitake and season with salt and pepper. Cover and cook, stirring occasionally, until tender and browned, about 5 minutes.'),
('1643', '10', 'Arrange the salmon fillets on a rimmed baking sheet, skinned side down, and season with salt and pepper.'),
('1643', '11', 'Bake for about 15 minutes, until just cooked in the center.'),
('1643', '12', 'Spoon the wild rice onto plates and set the salmon fillets on top. Spoon the shiitake mushrooms and red wine sauce over the fish and serve.'),
('1644', '1', 'In a medium saucepan, combine the sherry with the sugar and cook over high heat, stirring occasionally, until the sugar is dissolved.'),
('1644', '2', 'Add the rhubarb and cook until just tender, about 1 minute. Strain the rhubarb in a colander set over a bowl to catch the cooking liquid. Return the liquid to the saucepan and boil over high heat until reduced to 1/2 cup, about 8 minutes.'),
('1644', '3', 'Melt the butter in a medium saucepan.'),
('1644', '4', 'Add the onions and cook over low heat, stirring, until softened, about 1 minute.'),
('1644', '5', 'Add the chicken stock and thyme sprig and a pinch each of salt and pepper. Cover and simmer over low heat until the onions are tender, about 8 minutes.'),
('1644', '6', 'In a medium saucepan of boiling salted water, cook the fava beans for 2 minutes. Using a slotted spoon, transfer the beans to a bowl and refresh under cool running water. Peel off the tough bean skins and add the favas to the onions.'),
('1644', '7', 'Heat a cast-iron skillet. Lightly coat the salmon fillets with some vegetable oil and season with salt and pepper. Cook the salmon, skin side down, over moderately high heat until the skin is very crisp, about 4 minutes. Turn the salmon and cook over moderate heat until barely cooked through, about 4 minutes more, depending on the thickness of the fillets.'),
('1644', '8', 'To serve, discard the thyme sprig and rewarm the onions. add the lemon juice and season with salt and pepper. Bring the sherry-rhubarb liquid to a boil and add the cooked rhubarb. Spoon the rhubarb onto 4 large plates and set the onions alongside. Top with the salmon and serve at once.'),
('1646', '1', 'Place peppercorns, thyme, savory, and garlic in a piece of cheesecloth. tie with kitchen twine to enclose.'),
('1646', '2', 'Transfer to a medium saucepan, along with, Syrah, port, and shallots. Bring to a simmer over low heat and cook until liquid has reduced by three-quarters.'),
('1646', '3', 'Add beef stock and continue cooking until liquid has reduced by two-thirds and lightly coats the back of a spoon.'),
('1646', '4', 'Remove cheesecloth bundle from saucepan and discard. set sauce aside and keep warm.'),
('1648', '1', 'Preheat the oven to 230C/450F/gas 8.'),
('1648', '2', 'Half-fill a large saucepan with cold water and add a tiny pinch of salt.'),
('1648', '3', 'Place on a high heat and bring to the boil. Meanwhile4.Give the new potatoes a good scrub with a scrubber, then on a chopping board cut any bigger ones in half, leaving the smaller ones whole.'),
('1648', '4', 'Cut the tips from the runner beans until you cut into the stringy piece that runs the length of the bean.'),
('1648', '5', 'Pull the stringy bit and peel it down the length of the beans on both sides of each one, then slice at an angle into 5cm pieces.'),
('1648', '6', 'Trim the stalk-ends from the green and French beans, if using, but leave the wispy tips on, then slice the beans at an angle into 3cm pieces.'),
('1648', '7', 'Once boiling, carefully lower the potatoes into the water with a slotted spoon, bring back to the boil, then cook for around 10 to 12 minutes (depending on the size of your potatoes), or until theyre nearly done.Meanwhile'),
('1648', '8', 'If your peas are still in their pods, pod them now.1'),
('1648', '9', 'When the times up on the potatoes, carefully add all the beans to the pan and cook for a further 4 minutes.1'),
('1648', '10', 'Drain the potatoes and beans over the sink into a colander and steam dry for a couple of minutes, then tip into a 25cm x 35cm roasting tray.1'),
('1648', '11', 'Scatter over the peas, dot over the butter and drizzle with 1 tablespoon of olive oil.1'),
('1648', '12', 'Use a microplane to finely grate the zest of both lemons onto a chopping board, then scatter into the tray.1'),
('1648', '13', 'Cut the lemons in half.1'),
('1648', '14', 'Squeeze the juice over the salmon and vegetables, using your fingers to catch any pips.1'),
('1648', '15', 'Season lightly with salt and pepper then, toss together while still warm so that the flavours are absorbed.1'),
('1648', '16', 'Pick the basil leaves, discarding the stalks, then roughly chop them with the fennel tops or dill. 1'),
('1648', '17', 'Scatter half the herbs into the tray.1'),
('1648', '18', 'Carefully score the salmon fillets lightly on the skin side.2'),
('1648', '19', 'Rub each fillet with a little salt, pepper and olive oil, stuff the scores with the remaining herbs and place on top of the potatoes and beans, then wash your hands.2'),
('1648', '20', 'Bake in the hot oven for 10 to 15 minutes, depending on the exact size and thickness of your fillets, or until the salmon is cooked through and the vegetables are soft.2'),
('1648', '21', 'Divide between your plates using a fish slice, then drizzle with the cooking juices from the bottom of the tray and serve.Tip: This is one of those great dishes that you can really make your own by using whatever vegetables are in season  its particularly nice with broad beans, asparagus or little halved cherry tomatoes. Delicious served with a dollop of yoghurt or garlic mayonnaise.Tip'),
('1650', '1', 'Season each piece of salmon with salt and pepper and sprinkle with a little chopped parsley. If sauting, heat the olive oil in a wide skillet and cook the fish, about 3 minutes on the first side, then about 2 minutes on the second side to achieve a medium-rare temperature. (Increase the cooking time by about 90 seconds on each side if you want the salmon to be cooked through.) You may also grill or broil the salmon, as desired.'),
('1650', '2', 'Spoon the Martini Sauce over (or alongside) the cooked salmon and serve immediately. This salmon is delicious with boiled new potatoes or rice.'),
('1650', '3', 'Martini Sauce'),
('1650', '4', 'Place the shallots, gin, vermouth, juniper berries, and green peppercorns in a small saucepan and bring to a boil. Lower the heat and simmer until reduced to about 3 tablespoons liquid.'),
('1650', '5', 'Add the cream and reduce to 1/4 cup.'),
('1650', '6', 'Strain and return the liquid to the saucepan (discard the solids).'),
('1650', '7', 'Whisk in the butter.'),
('1650', '8', 'Add the olives and season to taste with lemon juice, salt, and a little pepper. Cover and keep warm while you prepare the salmon.'),
('1650', '9', 'Book, using the USDA Nutrition Database'),
('1650', '10', 'From Crescent City Cooking by Susan Spicer Copyright (c) 2007 by Susan Spicer Published by Knopf./n /nSusan Spicer was born in Key West, Florida, and lived in Holland until the age of seven, when her family moved to New Orleans. She has lived there ever since, and is the owner of two restaurants, Bayona and Herbsaint. This is her first cookbook./n /nPaula Disbrowe was the former Cowgirl Chef at Hart & Hind Fitness Ranch in Rio Frio, Texas. Prior to that, she spent ten years working as a food and travel writer. Her work has appeared in The New York Times, Food & Wine, and Saveur, among other major publications.'),
