INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('15726', '2', 'Cut lamb into 4 pieces, then brush 2 tbsp. of paste over each. Grill lamb, turning and brushing with a little more paste as you go, until done the way you like, about 10 minutes for medium-rare.'),
('15726', '3', 'Let rest 10 minutes, then slice.'),
('15726', '4', 'For salad, mix together chickpeas, mint, lemon peel, juice, salt, onion, and remaining 1/4 cup oil.'),
('15726', '5', 'Serve lamb slices over or mixed into bean salad, with reserved harissa sauce on the side.'),
('15726', '6', '*Buy harissa, a North African chile-and-spice paste, in the international section of many supermarkets.'),
('15743', '1', 'In a shallow bowl, mix vinegar, mustard, garlic, and pepper. In another shallow bowl, stir together panko, cheese, and mint.'),
('15743', '2', 'Trim excess fat from lamb and discard. Rinse chops and pat dry. One at a time, turn chops in vinegar mixture to coat well; lift out and press firmly in panko mixture, turning to coat all sides.'),
('15743', '3', 'Place chops slightly apart in a lightly oiled 10- by 15-inch pan; drizzle evenly with butter.'),
('15743', '4', 'Bake in a 500 regular or convection oven until coating is browned and meat is medium-rare (pink) in center of thickest part (cut to test), 10 to 14 minutes, turning once after 5 minutes.'),
('15743', '5', 'Serve with mint aioli and season to taste with salt.'),
('15746', '1', 'Heat oven to 450[degrees] F. Drop the garlic into a food processor with the motor running and the knife blade in place and process until finely chopped.'),
('15746', '2', 'Add the rosemary, fennel seeds, 1 teaspoon each of salt and pepper, and 3 tablespoons of the olive oil and pulse to make a paste.'),
('15746', '3', 'Cut 10 slits in the lamb, about 1/2 inch deep. Push some of the garlic paste into the slits and rub the remaining paste all over the lamb.'),
('15746', '4', 'Place the lamb in a small roasting pan and set aside.'),
('15746', '5', 'Remove the stalks and tough outer leaves from the fennel bulbs and cut each into eighths. In a shallow baking pan, combine the fennel and onions with the remaining salt, pepper, and oil, and toss to coat well.'),
('15746', '6', 'Place the lamb and vegetables in the oven, roast for 1 hour, then remove. Cover the vegetables with foil to keep warm.'),
('15746', '7', 'Check the internal temperature of the lamb with an instant-read thermometer. Continue roasting until it reaches 130[degrees] F for medium-rare, or 135[degrees] to 145[degrees] F for medium, checking every 10 minutes.'),
('15746', '8', 'Remove the lamb from oven, transfer to a cutting board, cover loosely with foil, and let rest for 15 to 20 minutes.'),
('15746', '9', 'Heat the roasting pan over medium-high heat.'),
('15746', '10', 'Add the wine and scrape up any browned bits on the bottom. Boil until reduced by half, about 2 minutes.'),
('15746', '11', 'Add the broth and juice and boil until reduced to about 1 cup, about 4 to 5 minutes more. Season to taste with salt and freshly ground pepper.'),
('15746', '12', 'Carve the lamb into thin slices and place on a platter with the vegetables.'),
('15746', '13', 'Serve with the sauce.'),
('15752', '1', 'Preheat oven to 375 degrees F.'),
('15752', '2', 'Place the lamb in a resealable plastic bag.'),
('15752', '3', 'Combine the marinade ingredients in a glass bowl or measuring cup.'),
('15752', '4', 'Pour the marinade over the lamb, seal the bag, and refrigerate for at least 1 hour or overnight.'),
('15752', '5', 'Once marinated, place the lamb in a cast iron pan with olive oil and sear the lamb on all sides. Cover pan with tinfoil and place in oven. Roast the lamb until done, for about 2 to 2 1/2 hours. The internal temperature should reach 180 degrees F on an instant-read thermometer.'),
('15762', '1', 'Save Recipe'),
('15762', '2', 'Print Recipe'),
('15762', '3', 'Persian Lamb Stew'),
('15762', '4', 'Ingredients1 tbsp turmeric2 tsp black pepper1 1/2 tsp salt1 tsp crushed red pepper flakes1/4 cup extra virgin olive oil2  medium onions, minced3 lbs lamb stew meat cut into chunks3 tbsp tomato paste1/4 cup fresh parsley or cilantro, chopped4 cups steamed basmati rice'),
('15762', '5', 'Servings: 8 servings'),
('15762', '6', 'Kosher Key: Meat'),
('15765', '1', 'Pour oil into a 12-inch nonstick frying pan over medium-high heat. When hot, add lamb chops and cook, turning once, until browned on both sides, about 4 minutes total.'),
('15765', '2', 'Transfer to a plate.'),
('15765', '3', 'Add onion and garlic to pan; stir often until limp, about 4 minutes.'),
('15765', '4', 'Add cinnamon and cumin; stir until fragrant, 1 minute longer. Stir in broth, tomato paste, apricots, and garbanzos; bring to a simmer. Return lamb chops to pan.'),
('15765', '5', 'Cover and simmer, turning chops once, until apricots are plump and chops are barely pink in the center (cut to test), 10 to 12 minutes.'),
('15765', '6', 'Set two lamb chops on each of four plates or in shallow bowls. Spoon garbanzo mixture around meat. Sprinkle with parsley.'),
('15773', '1', 'Rinse lamb stew meat, and pat dry. Sprinkle with salt and pepper; toss in flour, shaking off excess.'),
('15773', '2', 'Cook half of lamb in 2 Tbsp. hot oil in a Dutch oven over medium-high heat, stirring occasionally, 10 minutes or until browned. Repeat procedure with remaining lamb and oil. Stir in tomato paste; cook 1 minute.'),
('15773', '3', 'Add broth, and stir to loosen particles from bottom of Dutch oven.'),
('15773', '4', 'Transfer mixture to a 6-qt. slow cooker.'),
('15773', '5', 'Stir in celery, onion, and garlic. Top with butternut squash. (Do not stir to incorporate.) Cover and cook on LOW 4 1/2 hours or until meat is tender.'),
('15773', '6', 'Serve over hot cooked mashed potatoes, if desired.'),
('15773', '7', 'Garnish, if desired.'),
('15773', '8', 'Harvest Beef Stew: Substitute 2 1/2 lb. beef stew meat for lamb. Proceed with recipe as directed.'),
('15775', '1', 'Heat a medium skillet over moderately high heat.'),
('15775', '2', 'Add a large handful of spinach and cook, stirring, until the leaves are wilted.'),
('15775', '3', 'Transfer the wilted spinach to a colander and repeat with the remaining leaves. Gently squeeze the spinach dry, coarsely chop and reserve.'),
('15775', '4', 'In the same skillet, heat 1 tablespoon of olive oil.'),
('15775', '5', 'Add the red onion and cook over moderate heat until softened, about 7 minutes.'),
('15775', '6', 'Transfer the onion to a large bowl and let cool.'),
('15775', '7', 'Add the ground lamb to the bowl and break it up slightly.'),
('15775', '8', 'Add the red wine, cumin, cinnamon, 1/2 teaspoon of salt and 1/2 teaspoon of black pepper and blend well. Gently form the mixture into four 4-inch patties.'),
('15775', '9', 'In the same skillet, heat the remaining 2 tablespoons of olive oil.'),
('15775', '10', 'Add the minced garlic and cook over moderate heat until fragrant, about 40 seconds.'),
('15775', '11', 'Add the wilted spinach and cook, stirring, until hot. Season the spinach with salt and pepper, cover and keep warm.'),
('15775', '12', 'Light a grill. Lightly brush the bread with olive oil and grill, turning once, until lightly browned, about 1 minute per side.'),
('15775', '13', 'Spread the fresh goat cheese on the bread and top with the garlicky spinach.'),
('15775', '14', 'Brush the lamb patties with olive oil and season lightly with salt and pepper. Grill over moderately high heat, turning once, until the patties are nicely charred outside and medium-rare within, about 4 minutes per side.'),
('15775', '15', 'Transfer the chopped lamb steaks to the bread, garnish with marjoram leaves and serve with a fork and knife.'),
('15780', '1', 'Combine first 6 ingredients in a small bowl.'),
('15780', '2', 'Pat lamb dry, and place, fat side up, on a rack in a roasting pan. Make several 1-inch-deep slits in lamb with a paring knife; rub olive oil mixture over lamb, pressing mixture into slits. Cover loosely with foil, and let stand at room temperature 30 minutes.'),
('15780', '3', 'Meanwhile, preheat oven to 40'),
('15780', '4', 'Uncover lamb, and sprinkle with salt and pepper.'),
('15780', '5', 'Bake at 400 for 2 hours and 30 minutes or until a meat thermometer inserted into thickest portion registers 145 (medium rare).'),
('15780', '6', 'Let stand 30 minutes before slicing.'),
('15781', '1', 'Sprinkle lamb with salt and pepper. Cook lamb in a large nonstick skillet over medium-high heat 3 to 4 minutes on each side or until browned.'),
('15781', '2', 'Process bread and next 5 ingredients in a food processor until coarsely ground.'),
('15781', '3', 'Brush mustard over lamb; press breadcrumb mixture over mustard.'),
('15781', '4', 'Place lamb on a lightly greased rack in a broiler pan.'),
('15781', '5', 'Bake at 400 for 40 to 45 minutes or until a meat thermometer inserted into thickest portion registers 14'),
('15781', '6', 'Remove from oven, and let stand 5 minutes or until thermometer registers 150 (medium-rare).'),
('15782', '1', 'Bake pine nuts in a shallow pan at 350, stirring occasionally, 5 minutes or until toasted.'),
('15782', '2', 'Combine pine nuts and next 9 ingredients; press half of mixture into a lightly greased 9- x 5-inch loafpan. Sprinkle with cheese, and press remaining lamb mixture over cheese.'),
('15782', '3', 'Bake at 375 for 1 1/2 hours; remove from pan, and place on a rack in a broiler pan.'),
('15782', '4', 'Pour tomato sauce over top; bake 10 more minutes or until done.'),
('15782', '5', 'Garnish, if desired.'),
('15782', '6', 'Serve with toasted pita bread.'),
('15783', '1', 'In a medium saucepan, heat 3 tablespoons of the olive oil.'),
('15783', '2', 'Add the scallions and cook over moderate heat, stirring, until softened, about 4 minutes.'),
('15783', '3', 'Add the peas, lima beans, zucchini and crushed red pepper and season with salt and black pepper. Cover and cook over very low heat until barely softened, about 15 minutes.'),
('15783', '4', 'Add the lettuce and 2 tablespoons of the mint, cover and cook until the lettuce is very tender, about 10 minutes.'),
('15783', '5', 'Meanwhile, preheat a grill pan. Rub the chops with the remaining 1 tablespoon of oil and season with salt and black pepper. Rub the rosemary onto the chops. Grill the chops over high heat for 6 minutes, turning once or twice, for medium-rare meat.'),
('15783', '6', 'Spoon the vegetables onto plates and top with the lamb chops.'),
('15783', '7', 'Garnish with the remaining 2 tablespoons of mint and serve.'),
('15784', '1', 'In a small dry skillet, combine the coriander, cumin and caraway seeds and toast over moderate heat until fragrant, about 3 minutes.'),
('15784', '2', 'Transfer to a bowl and let cool. In a spice mill, grind the toasted spices to a fine powder with the crushed red pepper and salt.'),
('15784', '3', 'Transfer the spices to a bowl and blend in the oil.'),
('15784', '4', 'Light a grill or preheat a grill pan and oil it lightly. Rub the lamb with the spice paste and grill over a hot fire for 3 to 4 minutes per side for medium rare.'),
('15784', '5', 'Transfer to plates and serve with the Chickpea "Fries.".'),
('15785', '1', 'Soak the hickory chips in cold water for 1 hour. In a medium saucepan, combine the 3/4 cup of water, vinegar, Worcestershire sauce and lemon juice.'),
('15785', '2', 'Add 2 1/2 tablespoons of salt and 1/4 teaspoon of pepper and bring to a boil. Reduce the heat to moderate and stir just until the salt dissolves.'),
('15785', '3', 'Remove the sauce from the heat.'),
('15785', '4', 'Light a grill. Lightly brush the grate with oil.'),
('15785', '5', 'Drain the hickory chips and scatter them on the hot coals. If using a gas grill, place the chips in a 12-inch square of foil;fold the foil into a 6-inch square and poke 12 holes in the top.'),
('15785', '6', 'Place the package near the flames and let heat until smoking.'),
('15785', '7', 'Season the lamb with salt and pepper. Grill the lamb, boned side up, over moderate heat, covered, for 10 minutes. Generously brush the lamb with sauce and cook, covered, basting frequently, and turning the meat to avoid burning, for about 45 minutes, or until an instant-read thermometer inserted in the thickest part of the lamb registers 125 for medium rare or 140 for medium.'),
('15785', '8', 'Transfer the lamb to a cutting board, cover loosely with foil and let rest for 15 minutes. Thinly slice the lamb on the diagonal; transfer to a platter.'),
('15785', '9', 'Pour any accumulated juices on top and serve.'),
('15786', '1', 'In a medium skillet, combine the allspice, cinnamon, peppercorns and cloves and cook over moderate heat until lightly toasted, about 1 minute.'),
('15786', '2', 'Transfer the spices to a plate and let cool, then grind them to a powder in a spice grinder.'),
('15786', '3', 'In a food processor, combine the soy sauce, onion, garlic, scallions, oil, rum, thyme, salt, nutmeg and ground spices and process to a paste. In a large shallow dish, coat the lamb with the marinade. Cover and refrigerate overnight.'),
('15786', '4', 'Light a grill or preheat a broiler. Grill the lamb over a moderately high flame or broil for about 10 minutes per side for medium rare, rotating and turning the meat for even cooking.'),
('15786', '5', 'Transfer the lamb to a cutting board and let stand, loosely covered with foil, for 10 minutes. Carve the lamb across the grain and serve hot.'),
('15787', '1', 'Tie the parsley stems, thyme and bay leaf in a bundle. Stick the cloves in the onion halves. In a medium enameled cast-iron casserole, combine the lamb with the water, onion halves, carrot and herb bundle. Season lightly with salt. Cover and bring to a boil, then cook over low heat for 30 minutes, skimming occasionally.'),
('15787', '2', 'Using tongs, transfer the meat to a bowl.'),
('15787', '3', 'Remove and discard the herb bundle and the whole cloves, if you can find them.'),
('15787', '4', 'Pour the contents of the casserole through a fine strainer set over a bowl and press on the vegetables. Return the broth to the casserole; discard the vegetables. Return the lamb to the casserole and bring to a simmer over low heat.'),
('15787', '5', 'In a small bowl, cream the butter with the flour. Gradually whisk the butter paste into the simmering stew. Continue cooking until the lamb is very tender, about 30 minutes. Using tongs, transfer the lamb to a bowl. Simmer the sauce until reduced to 2 cups; return the lamb to the casserole.'),
('15787', '6', 'Whisk the cream into the stew and simmer for 10 minutes, skimming occasionally.'),
('15787', '7', 'Add the lemon juice, season with salt and white pepper and serve.'),
('15789', '1', 'Preheat grill to medium-high heat (350 to 400).'),
('15789', '2', 'Place lamb chops in a large bowl, and drizzle with olive oil. Sprinkle with rosemary and next 4 ingredients, and toss well to coat.'),
('15789', '3', 'Let stand 30 minutes. Meanwhile, prepare Mint Chimichurri.'),
('15789', '4', 'Place chops on greased grill rack. Cover and grill 3 to 4 minutes on each side for medium-rare (145), 8 minutes for medium (160), or 10 minutes for well-done (170).'),
('15789', '5', 'Remove from grill; let stand 5 minutes.'),
('15789', '6', 'Serve with Mint Chimichurri.'),
('15790', '1', 'Combine first 4 ingredients, and rub evenly into both sides of lamb chops.'),
('15790', '2', 'Brown chops in hot oil in a large nonstick skillet over medium-high heat 2 to 3 minutes on each side. Arrange chops on a lightly greased rack in a broiler pan.'),
('15790', '3', 'Bake chops at 350 for 35 to 40 minutes or until a meat thermometer inserted into thickest portion registers 145 (medium rare).'),
('15790', '4', 'Serve lamb with Mint Aioli.'),
('15790', '5', 'Garnish, if desired.'),
('15794', '1', 'In a strainer, toss the cucumber with 1/2 teaspoon of salt and let drain for 30 minutes; squeeze dry. In a bowl, mix the yogurt, cucumber, dill, zest and garlic; season with salt.'),
('15794', '2', 'Serve with the lamb.'),
('15795', '1', 'In a large skillet, heat 2 tablespoons of the olive oil until shimmering.'),
('15795', '2', 'Add the parsnips and cook over moderately high heat, turning once, until golden and tender, 6 to 7 minutes.'),
('15795', '3', 'Transfer the parsnips to a plate.'),
('15795', '4', 'Add the apple concentrate to the skillet and boil until syrupy and reduced to 1/4 cup, about 8 minutes.'),
('15795', '5', 'Add the lemon zest and juice, the parsnips and 1 tablespoon of the horseradish. Season with salt and pepper and keep warm.'),
('15795', '6', 'Meanwhile, in another large skillet, heat the remaining 1/2 tablespoon of olive oil until shimmering. Season the lamb chops with salt and pepper, add them to the pan and cook over high heat, turning once, until the meat is cooked but still pink throughout, about 7 minutes.'),
('15795', '7', 'Transfer the lamb and parsnips to plates. Spoon the sauce over the lamb, top the chops with the remaining 1 tablespoon of horseradish and serve.'),
('15796', '1', 'Preheat the oven to 35'),
('15796', '2', 'Put the flour in a large bowl and season generously with salt and pepper.'),
('15796', '3', 'Add the lamb cubes in 4 batches, tossing to coat thoroughly.'),
('15796', '4', 'In a large enameled cast-iron casserole, heat 2 tablespoons of the oil until shimmering.'),
('15796', '5', 'Add one-fourth of the lamb cubes and cook over moderately high heat until browned, about 6 minutes; transfer to a plate. Brown the remaining floured lamb in 3 batches, adding 2 tablespoons of oil to the pot per batch. Reduce the heat if the casserole bottom darkens too much.'),
('15796', '6', 'Return all of the lamb to the casserole.'),
('15796', '7', 'Add the wine and vinegar and bring to a boil.'),
('15796', '8', 'Add the stock and tarragon and return to a boil. Season with salt and pepper. Cover the casserole and braise the stew in the oven for about 1 hour, or until the meat is nearly tender.'),
('15796', '9', 'Add the carrots, parsnips, potatoes, turnips, fennel and shallot to the lamb stew. Season with salt and pepper and bring to a boil, stirring to distribute the vegetables. Cover the casserole, return it to the oven and cook until the meat and vegetables are tender, about 1 hour longer. Season with salt and pepper. Stir in the parsley and fennel fronds and serve the stew in deep bowls.'),
('15799', '1', 'Preheat the oven to 35'),
('15799', '2', 'In a skillet, melt the butter.'),
('15799', '3', 'Add the shallots and thyme and cook over moderate heat for 2 minutes.'),
('15799', '4', 'Add the vermouth and reduce by half.'),
('15799', '5', 'Transfer to a bowl; whisk in the mustard, egg, tarragon and a pinch of salt and pepper.'),
('15799', '6', 'Set the lamb fat side down and season with salt and pepper. Rub one-fourth of the mustard mixture on the meat.'),
('15799', '7', 'Roll up; tie at two-inch intervals with kitchen string.'),
('15799', '8', 'Heat the oil in a roasting pan.'),
('15799', '9', 'Add the lamb and sear over high heat until browned all over, 8 minutes.'),
('15799', '10', 'Transfer to a plate and remove the strings. Rub with the remaining mustard mixture and pat the bread crumb coating all over. Roast the lamb in the roasting pan for 50 minutes, until an instant-read thermometer inserted in the center registers 130 for medium-rare.'),
('15799', '11', 'Let rest for 15 minutes before carving.'),
('15802', '1', 'In a blender, whirl yellow onion, garlic, rosemary, lemon juice, and salt. With blender running, slowly pour in olive oil.'),
('15802', '2', 'Rinse lamb and pat dry. With a small knife, make small slashes (1 in. long, 1 in. deep) all over the lamb, and put it in a nonreactive dish. Coat lamb with onion marinade, making sure the mixture gets into the slits. Cover and chill 2 hours or up to overnight, turning occasionally.'),
('15802', '3', 'Remove lamb from refrigerator about 1 hour before you plan to cook it.'),
('15802', '4', 'Spread lamb flat on an oiled barbecue grill over a solid bed of medium-hot coals or medium heat on a gas grill (you can hold your hand 1 to 2 in. above grill level only 4 to 5 seconds). Close lid. Cook lamb, turning once and brushing with marinade, until a thermometer inserted in center of thickest part registers 140, about 40 minutes.'),
('15802', '5', 'Transfer meat to a platter and cover.'),
('15802', '6', 'Let rest 15 to 20 minutes. Thinly slice meat, garnish with sliced red onion and radishes, and serve with yogurt-mint sauce.'),
('15805', '1', 'In a blender, puree the oil, onion, garlic, dill, lemon juice, zest and oregano. In a baking dish, pour the marinade over the lamb and turn to coat. Refrigerate for at least 4 hours.'),
('15805', '2', 'Remove from the refrigerator 1 hour before cooking. Light a grill. Scrape off the marinade and season the lamb with salt and pepper. Grill over moderate heat for 28 minutes, turning once, until medium-rare.'),
('15805', '3', 'Transfer to a surface and let rest for 10 minutes. Slice the lamb against the grain and serve.'),
('15807', '1', 'In a large, shallow dish, combine the 1/4 cup of olive oil with the thyme, minced garlic, rosemary and cumin.'),
('15807', '2', 'Add the lamb chops and turn to coat with the marinade. Refrigerate overnight.'),
('15807', '3', 'Preheat the oven to 35'),
('15807', '4', 'Set the halved heads of garlic cut side up on a large sheet of foil and drizzle with oil. Wrap the garlic in the foil and roast for 1 hour, until tender.'),
('15807', '5', 'Light a grill.'),
('15807', '6', 'Remove the chops from the marinade; discard the thyme and scrape off the garlic. Season the chops with salt and pepper and grill over moderate heat until lightly charred and medium-rare, 5 minutes per side.'),
('15807', '7', 'Serve the chops with the roasted garlic and White Bean Puree.'),
('15808', '1', 'In a large, sturdy resealable plastic bag, combine the flour and chile powder with 1 tablespoon each of salt and pepper.'),
('15808', '2', 'Add the pork shanks, one at a time, and shake to coat thoroughly.'),
('15808', '3', 'In a large skillet, heat 2 tablespoons of the olive oil until shimmering.'),
('15808', '4', 'Add 3 of the pork shanks and cook over moderately high heat until browned all over, about 10 minutes.'),
('15808', '5', 'Transfer the browned shanks to a deep, heavy casserole. Wipe out the skillet and brown the remaining 3 pork shanks in the remaining 2 tablespoons of olive oil; lower the heat if necessary.'),
('15808', '6', 'Add the pork shanks to the casserole.'),
('15808', '7', 'Add the onion, carrots, celery and garlic to the skillet and cook over moderate heat until softened, about 5 minutes.'),
('15808', '8', 'Add the wine and bring to a boil. Simmer until slightly reduced, about 2 minutes.'),
('15808', '9', 'Pour the wine and vegetables over the pork.'),
('15808', '10', 'Add the stock, rosemary, bay leaves and thyme, season with salt and pepper and bring to a boil. Tuck the pork shanks into the liquid so that they''re mostly submerged. Cover and cook over moderately low heat for 2 1/2 hours, or until the meat is very tender. Turn the pork shanks every 30 minutes to keep them submerged in the liquid.'),
('15808', '11', 'Transfer the braised shanks to a large, deep platter, cover and keep warm.'),
('15808', '12', 'Strain the liquid, pressing hard on the solids; discard the solids. Return the liquid to the casserole and boil until reduced to 4 cups, about 20 minutes. Spoon off the fat, pour the pork gravy over the braised shanks and serve.'),
('15809', '1', 'Preheat the oven to 32'),
('15809', '2', 'In a large enameled cast-iron casserole, heat the olive oil. Season the lamb shanks with salt and pepper and brown them on 3 sides over moderately high heat, about 4 minutes per side.'),
('15809', '3', 'Add the garlic, carrots, celery and onion to the casserole.'),
('15809', '4', 'Add the red wine and boil for 3 minutes.'),
('15809', '5', 'Add the water and bring to a simmer.'),
('15809', '6', 'Add the bay leaves and peppercorns. Cover the casserole tightly and transfer to the oven. Braise the lamb shanks, turning once, for about 1 1/2 hours, or until very tender.'),
('15809', '7', 'Transfer the lamb shanks to an ovenproof serving dish. Using a fine sieve, strain the braising liquid into a medium saucepan, pressing on the solids. Boil the braising liquid over high heat until reduced  to 1 1/2 cups, about 20 minutes. Season  the sauce with salt and pepper and pour about  1/2 cup over the lamb shanks; keep the remaining sauce warm. Cover the lamb shanks with foil and reheat in the oven for about 10 minutes.'),
('15809', '8', 'Serve the lamb shanks with the remaining sauce, the Maple-Glazed Root Vegetables and the Braised Red Cabbage.'),
('15810', '1', 'Preheat the oven to 50'),
('15810', '2', 'In a small bowl, mix the paprika with the chile powder and cardamom. Rub the lamb with the olive oil and season with salt. Sprinkle the spices all over the lamb.'),
('15810', '3', 'Lay the lamb fat side down on a large rimmed baking sheet. Scatter the garlic cloves, rosemary and thyme sprigs and lemon slices around the lamb and roast on the top rack of the oven for about 25 minutes, or until nicely browned. Turn the lamb fat side up and roast for about 25 minutes longer, or until an instant-read thermometer inserted in the thickest part of the meat registers 130 for medium-rare.'),
('15810', '4', 'Transfer the lamb to a carving board and let rest for 10 minutes. Slice the lamb 1/4 inch thick and serve.'),
('15811', '1', 'In a small bowl, mix the spices with 1 1/2 teaspoons of kosher salt. Pat the garlic all over the lamb chops, then sprinkle them with the spice mixture.'),
('15811', '2', 'In a large skillet, heat the vegetable oil.'),
('15811', '3', 'Add the chops and cook over moderately high heat, turning once, for about 6 minutes for medium-rare.'),
('15811', '4', 'Transfer the chops to plates, garnish with the cilantro and serve.'),
('15812', '1', 'Preheat the oven to 32'),
('15812', '2', 'In a bowl, mix the bread crumbs with the butter, garlic, parsley, thyme, rosemary and lemon juice. Season the lamb all over with salt and pepper. Rub some of the herb mixture on the underside of the lamb and set in a roasting pan, fat side up.'),
('15812', '3', 'Spread the mustard over the top of the lamb, then pat the remaining herb mixture over the top of the lamb.'),
('15812', '4', 'Bake the lamb for about 2 hours, until browned on top and an instant-read thermometer inserted in the thickest part of the meat registers 150 for medium meat.'),
('15812', '5', 'Transfer the lamb to a carving board and let rest for 15 minutes. Carve into slices and serve.'),
('15813', '1', 'In a small bowl, combine the parsley, garlic, rosemary, thyme and lavender.'),
('15813', '2', 'Spread the lamb on a work surface, boned side up and season generously with salt and pepper.'),
('15813', '3', 'Spread half of the herb mixture over the lamb and roll it into a roast. Tie the lamb with kitchen string at 1-inch intervals.'),
('15813', '4', 'Spread the remaining herb mixture all over the outside of the roast and season with salt and pepper.'),
('15813', '5', 'Let the roast stand at room temperature for 1 hour.'),
('15813', '6', 'Meanwhile, in a large skillet, boil the stock over moderately high heat until reduced to 1 cup, about 30 minutes.'),
('15813', '7', 'Preheat the oven to 45'),
('15813', '8', 'Set the lamb in a roasting pan and roast in the oven for 10 minutes. Reduce the oven temperature to 35'),
('15813', '9', 'Cook the lamb for 45 minutes longer, or until an instant-read thermometer inserted in the thickest part registers 125 for medium-rare or 140 for medium.'),
('15813', '10', 'Transfer the lamb to a carving board, cover loosely with foil and let stand for 10 minutes.'),
('15813', '11', 'Add the fennel seeds to the roasting pan and cook over moderate heat until fragrant, about 1 minute. Increase the heat to high, add the reduced stock and cook, scraping up any browned bits on the bottom of the pan; season with salt and pepper.'),
('15813', '12', 'Discard the string. Carve the lamb into thick slices and arrange on a platter.'),
('15813', '13', 'Pour any carving juices into the sauce, spoon it over the lamb and serve.'),
('15815', '1', 'In a large glass baking dish, whisk the olive oil, vinegar, garlic and 2 tablespoons of the rosemary.'),
('15815', '2', 'Add the chops to the marinade and turn to coat.'),
('15815', '3', 'Let stand for 30 minutes.'),
('15815', '4', 'Meanwhile, in a small saucepan, heat 1/2 inch of vegetable oil until shimmering.'),
('15815', '5', 'Add the remaining 1/4 cup of rosemary leaves to the hot oil and fry for 15 seconds. Using a slotted spoon, transfer the rosemary to paper towels to drain. Fry the sage leaves until the bubbles in the oil subside, about 45 seconds; transfer to the paper towels.'),
('15815', '6', 'Add the parsley leaves to the hot oil and cover the pan immediately to avoid splattering; fry for 15 seconds, then add to the other herbs. Season the herbs with salt.'),
('15815', '7', 'Heat a grill pan. Scrape the marinade off the lamb chops and season the chops with salt and pepper. Working in batches, grill the chops over moderately high heat, turning once, just until pink in the center, about 6 minutes total.'),
('15815', '8', 'Transfer the lamb chops to plates, sprinkle with the frizzled herbs and serve.'),
('15817', '1', 'Light a grill. In a bowl, whisk the lemon juice with the mustard, oregano and the 2 tablespoons of olive oil. Season the ladolemono with salt and pepper.'),
('15817', '2', 'Drizzle the lamb chops with olive oil and season with salt and pepper. Grill over high heat until nicely charred outside and medium-rare within, 2 to 3 minutes per side.'),
('15817', '3', 'Transfer the chops to a platter and drizzle with the ladolemono. Sprinkle with the parsley and mint and serve with the stuffed tomatoes.'),
('15821', '1', 'Season the lamb with salt and pepper.'),
('15821', '2', 'Put the flour, eggs and panko in 3 shallow bowls; season each with salt and pepper. Dredge the lamb in the flour, then dip in the eggs and coat with panko.'),
('15821', '3', 'Transfer the lamb to a plate.'),
('15821', '4', 'In a blender, combine the tomato, roasted pepper, garlic, almonds, vinegar and sugar and process until smooth. With the machine on, add the 1/4 cup of olive oil in a thin stream and blend until creamy. Season the sauce with salt and pepper.'),
('15821', '5', 'In a large skillet, heat 1/4 inch of olive oil until shimmering.'),
('15821', '6', 'Add the breaded lamb cutlets and cook over moderately high heat, turning once, until golden and crisp, about 7 minutes.'),
('15821', '7', 'Drain on paper towels and transfer to plates. Spoon some of the romesco sauce over the lamb and garnish with the goat cheese, chives and parsley.'),
('15821', '8', 'Serve the remaining sauce on the side.'),
('15822', '1', 'In a roasting pan, toss the fennel, 2 tablespoons of the oil, 1/2 teaspoon of the salt, and 1/4 teaspoon of the pepper. Set aside.'),
('15822', '2', 'Dry the lamb shanks on paper towels and season with the remaining salt and pepper. In a Dutch oven, heat the remaining oil over medium-high heat. Brown the lamb until golden, 4 to 5 minutes per side. (Do in 2 batches if necessary.)'),
('15822', '3', 'Remove the lamb and set aside.'),
('15822', '4', 'Heat oven to 400 F.'),
('15822', '5', 'Pour off the excess oil from the Dutch oven. Stir in the onion, garlic, and rosemary. Cook 1 minute. Stir in the tomatoes, wine, broth, and lamb. Cover and bring to a boil.'),
('15822', '6', 'Place in oven.'),
('15822', '7', 'Cook the lamb until it is fork-tender, about 2 1/2 hours, occasionally basting with the cooking liquid. After 1 hour, place the pan of fennel in the oven and roast until tender.'),
('15822', '8', 'Serve with the pan juices.'),
('15822', '9', 'KEEP IT: The lamb and fennel can be stored separately in the refrigerator up to 3 days. To freeze (the lamb only; fennel turns mushy when thawed), divide into individual servings with the sauce. Warm in a 375 F oven for 35 to 40 minutes or until the sauce is bubbling. The lamb keeps in the freezer up to 3 months.'),
('15823', '1', 'Combine first 7 ingredients in a shallow dish or large heavy-duty zip-top plastic bag; add lamb chops. Cover or seal, and chill 8 hours or overnight, turning chops occasionally.'),
('15823', '2', 'Let stand at room temperature 30 minutes.'),
('15823', '3', 'Remove chops from marinade, discarding marinade. Grill, covered with grill lid, over medium-high heat (350 to 400), turning occasionally, 12 minutes or until a meat thermometer inserted into thickest portion registers 14'),
('15823', '4', 'Garnish, if desired.'),
('15831', '1', 'In a medium enameled cast-iron casserole, heat 1/4 cup of the olive oil until shimmering.'),
('15831', '2', 'Add the carrots, onion and red bell pepper and cook over moderate heat, stirring occasionally, until softened and just beginning to brown, about 12 minutes. Using a slotted spoon, transfer the vegetables to a plate.'),
('15831', '3', 'Heat the remaining 2 tablespoons of oil in the casserole.'),
('15831', '4', 'Add the pancetta and stir once or twice over moderately high heat until sizzling.'),
('15831', '5', 'Add the lamb and cook, stirring occasionally, until the liquid has evaporated and the meat is browned, 10 minutes. Return the vegetables to the casserole.'),
('15831', '6', 'Add the red wine and simmer until evaporated, scraping up any browned bits from the bottom of the casserole.'),
('15831', '7', 'Add the tomatoes and their juices, the chicken stock, bay leaf and crushed red pepper. Season with salt and black pepper and bring to a boil. Reduce the heat to moderately low, cover partially and simmer, stirring occasionally, until the lamb is very tender, 1 1/2 hours. Discard the bay leaf.'),
('15831', '8', 'In a large pot of boiling salted water, cook the rigatoni until al dente.'),
('15831', '9', 'Drain the rigatoni and toss with half of the lamb rag.'),
('15831', '10', 'Serve the pasta in large bowls, passing the remaining lamb rag and the Pecorino cheese at the table.'),
('15838', '1', 'In a bowl, mix the garlic, rosemary, thyme and oil. Season the lamb with salt and pepper and rub the herb oil all over the meat.'),
('15838', '2', 'Let stand at room temperature for 1 1/2 hours or refrigerate for at least 3 hours or overnight.'),
('15838', '3', 'Bring the lamb to room temperature if necessary. Light a grill. Grill the lamb over moderate heat, turning once, until browned outside and an instant-read thermometer inserted in the meat registers 125 for medium-rare, about 8 minutes per side.'),
('15838', '4', 'Transfer to a carving board and let rest for 10 minutes. Thinly slice the lamb across the grain and serve.'),
('15842', '1', 'In a large enameled cast-iron casserole, heat 1 tablespoon of the oil. Season the lamb with salt and pepper.'),
('15842', '2', 'Add one-third of the meat to the casserole and brown it over moderately high heat; transfer the lamb to a plate. Repeat with the remaining oil and meat in 2 batches.'),
('15842', '3', 'Discard the fat from the casserole.'),
('15842', '4', 'Add the wine and boil until reduced by half, about 5 minutes. Return all the meat to the casserole along with any accumulated juices.'),
('15842', '5', 'Add the scallions and butter and season with salt and pepper.'),
('15842', '6', 'Add the water and lettuce and bring to a boil. Simmer the stew over low heat until the lamb is tender, about 30 minutes, pressing down occasionally to submerge the greens.'),
('15842', '7', 'In a medium bowl, lightly beat the eggs. Beat in the lemon juice, cornmeal slurry and dill, then gradually beat in 1/4 cup of the hot liquid from the casserole.'),
('15842', '8', 'Add the egg mixture to the casserole and cook, stirring constantly, until the sauce thickens; do not boil or the eggs will curdle.'),
('15842', '9', 'Serve hot with feta cheese.'),
('15843', '1', 'In a medium saucepan, cook the blackberries with the sugar over moderately high heat until they are softened but still hold their shape, about 5 minutes.'),
('15843', '2', 'Transfer to a bowl and stir in the mint, horseradish, lime juice and the 1 tablespoon of olive oil. Season with salt and pepper and let cool.'),
('15843', '3', 'Light a grill or preheat a grill pan.'),
('15843', '4', 'Brush the lamb chops with olive oil and season with salt and pepper. Grill over a medium-hot fire until medium rare, about 2 minutes per side.'),
('15843', '5', 'Serve with the blackberry relish.'),
('15844', '1', 'Light a grill or preheat the oven to 37'),
('15844', '2', 'Season the lamb with salt and pepper.'),
('15844', '3', 'If grilling, melt the butter in the olive oil in a small saucepan. When the coals are covered in white ash, grill the lamb over low heat for about 40 minutes, turning every 2 to 3 minutes and brushing the racks with the rosemary sprigs dipped in the butter mixture. The lamb is done when an instant-read thermometer inserted in the thickest part of the meat registers 125 for rare.'),
('15844', '4', 'If pan-roasting the lamb, melt 1 tablespoon of the butter in 1 tablespoon of the oil in a large ovenproof skillet.'),
('15844', '5', 'Add the lamb racks, fat sides down, and cook over moderately high heat until the racks are browned all over, about 5 minutes.'),
('15844', '6', 'Add the rosemary sprigs and the remaining 1 tablespoon each of butter and oil to the skillet. Spoon some of the fat over the lamb. Roast for about 30 minutes, basting once or twice with the rosemary sprigs and fat and turning the racks halfway through. The lamb is done when an instant-read thermometer registers 125 for rare.'),
('15844', '7', 'Transfer the lamb to a cutting board and let rest for 10 minutes. Carve the racks into chops. Sprinkle with the chopped thyme, mint and parsley and serve.'),
('15845', '1', 'In a large saucepan, cover the beans and the bay leaf with 2 inches of water and bring to a boil. Simmer over low heat until the beans are tender, about 2 hours.'),
('15845', '2', 'Drain the beans and discard the bay leaf.'),
('15845', '3', 'Meanwhile, preheat the oven to 30'),
('15845', '4', 'Heat an enameled cast-iron casserole that''s large enough to hold the lamb shanks in a single layer. Season the shanks with salt and black pepper and cook over moderate heat, turning a few times, until lightly browned all over, about 15 minutes. Nestle the garlic cloves among the shanks. Cover and cook in the oven for about 1 hour and 45 minutes, turning 3 times, until the shanks are very tender.'),
('15845', '5', 'Reduce the oven temperature to 20'),
('15845', '6', 'Transfer the shanks to a small roasting pan, and the garlic cloves to a small bowl. Cover the shanks with foil and keep warm in the oven. Strain the juices from the casserole into a bowl and skim off the fat. Return the juices to the casserole, add the chicken stock and set the casserole over a burner. Boil over high heat until the juices have reduced to 2 cups, about 12 minutes.'),
('15845', '7', 'Peel the garlic cloves and add the sherry vinegar. With a fork, mash to a paste.'),
('15845', '8', 'Add the garlic paste to the juices in the casserole and stir in the beans and thyme. Simmer over low heat for 5 minutes. Season with salt and black pepper.'),
('15845', '9', 'Place the lamb shanks on plates and serve with the beans.'),
('15846', '1', 'In a food processor, pulse the basil leaves just until coarsely chopped.'),
('15846', '2', 'Add the olive oil and the coarsely ground black pepper and pulse just until a coarse paste forms. Rub the basil paste all over the lamb and set the roast on a rack set in a roasting pan.'),
('15846', '3', 'Let the roast stand at room temperature for 45 minutes to marinate. After 30 minutes, preheat the oven to 40'),
('15846', '4', 'Meanwhile, in a small heatproof bowl, cover the dried cherries with boiling water and let stand until plump, about 30 minutes.'),
('15846', '5', 'Drain.'),
('15846', '6', 'Season the lamb with salt and pepper. Roast it on the bottom shelf of the oven for 30 minutes. Reduce the oven temperature to 350 and roast the lamb for 1 1/2 hours longer, or until an instant-read thermometer inserted in the thickest part of the roast reads 12'),
('15846', '7', 'Transfer the roasted lamb to a carving board, cover the roast loosely with foil and let stand for 15 minutes.'),
('15846', '8', 'Meanwhile, spoon off the fat from the roasting pan and set the pan over 2 burners.'),
('15846', '9', 'Add the red wine and balsamic vinegar and bring to a boil over high heat, scraping up any browned bits from the bottom of the pan with a wooden spoon. Simmer until the liquid is reduced by half, about 5 minutes, then strain the liquid into a small saucepan.'),
('15846', '10', 'Add the beef stock and cook over moderately high heat until reduced to 3/4 cup, about 15 minutes.'),
('15846', '11', 'Add the reconstituted cherries and the butter, season the dried-cherry sauce with salt and pepper and keep warm.'),
('15846', '12', 'Remove the strings from the lamb roast and cut it into thin slices. Arrange the meat on a platter and surround it with the Caramelized Red Onions.'),
('15846', '13', 'Pour the dried-cherry sauce into a bowl and pass at the table.'),
('15847', '1', 'In a food processor, pulse the garlic and cilantro until finely chopped.'),
('15847', '2', 'Add all of the remaining ingredients except the lamb; pulse until a paste forms.'),
('15847', '3', 'Spread 1/4 cup of the paste over the lamb chops.'),
('15847', '4', 'In a saucepan, whisk remaining paste with 1/3 cup of water. Warm the sauce over low heat; it should be pourable.'),
('15847', '5', 'Light a grill or preheat a grill pan. Grill the chops over a medium-high fire for 4 minutes per side, or until an instant-read thermometer inserted in the thickest part of a chop registers 125 to 130 for medium rare.'),
('15847', '6', 'Transfer the chops to a platter. Spoon some warm peanut sauce over the lamb chops and serve, passing the extra sauce on the side.'),
('15848', '1', 'Rinse lamb and pat dry; trim off excess surface fat. With a small, sharp knife, cut slits about 1/2 inch wide and deep all over lamb and insert slivers of garlic.'),
('15848', '2', 'In a 9- by 13-inch noncorrosive baking dish or large bowl, mix wine, olive oil, lemon juice, sherry, thyme, rosemary sprigs, 1/2 teaspoon salt, and 1/4 teaspoon pepper.'),
('15848', '3', 'Add lamb and turn to completely coat with marinade. Cover the lamb and chill, turning occasionally, at least 2 hours or up to overnight.'),
('15848', '4', 'Lift lamb from marinade and spread out flat on an oiled barbecue grill over a solid bed of medium coals or medium heat on a gas grill (you can hold your hand just above grill level only 4 to 5 seconds). If cooking over charcoal, drop rosemary sprigs from marinade onto coals for aromatic smoke, if desired. Discard marinade. Close barbecue lid. Cook lamb, turning once, until a thermometer inserted in center of thickest part registers 135 for medium-rare (still slightly pink; cut to test), 20 to 35 minutes; thin parts will be well done.'),
('15848', '5', 'Transfer lamb to a rimmed cutting board or platter, cover lightly with foil to keep warm, and let stand 10 to 15 minutes. Slice meat thinly and sprinkle with salt and pepper to taste.'),
('15849', '1', 'Preheat the oven to 30'),
('15849', '2', 'Season the lamb shanks with 1 teaspoon of the salt and 1/2 teaspoon of the pepper.'),
('15849', '3', 'In an enameled cast-iron casserole just large enough to hold the lamb shanks, combine the shanks with the unpeeled garlic cloves, bay leaves and thyme sprigs. Cook the shanks over moderate heat until evenly browned, about 15 minutes. Cover the casserole and roast the shanks for 2 hours, or until very tender, turning every 20 minutes.'),
('15849', '4', 'Remove from the oven and let stand, covered, for 20 minutes.'),
('15849', '5', 'Remove the shanks and set them aside.'),
('15849', '6', 'Add the chicken stock to the casserole and bring to a boil over high heat, scraping up any browned bits from the bottom. Boil, skimming frequently, until reduced to 2 cups, about 10 minutes.'),
('15849', '7', 'Strain the stock and return it to the casserole.'),
('15849', '8', 'Add the peeled garlic cloves and simmer gently until tender, about 20 minutes. Return the lamb to the casserole and add the bell peppers and thyme leaves. Cover and cook until the peppers are tender, about 10 minutes.'),
('15849', '9', 'Using a slotted spoon, transfer the lamb shanks to warm serving plates. Stir the butter into the sauce and season with the remaining 1/4 teaspoon of salt and 1/2 teaspoon of pepper. Spoon the sauce around the shanks and serve.'),
('15853', '1', 'Preheat the oven to 40'),
('15853', '2', 'Season the lamb with salt and pepper and brush lightly with the egg white. On a dinner plate, toss the sunflower seeds with the flour.'),
('15853', '3', 'Roll the lamb loins in the seeds until evenly and thoroughly coated.'),
('15853', '4', 'Heat the oil in a large nonstick skillet.'),
('15853', '5', 'Add the lamb and cook over moderately high heat, turning with a spatula, until the sunflower seed crust is browned all over, about 2 minutes.'),
('15853', '6', 'Transfer the lamb to a baking sheet and roast for about 7 minutes for medium rare. Carve each loin into 12 slices.'),
('15853', '7', 'Arrange 3 lamb medallions on each of 8 warmed dinner plates.'),
('15853', '8', 'Drizzle some of the Lavender Balsamic Vinaigrette around the lamb and serve at once.'),
('15854', '1', 'Melt the butter in a medium enameled cast-iron casserole. Season the lamb with salt and pepper.'),
('15854', '2', 'Add the meat to the casserole and cook over moderately high heat until browned all over, about 10 minutes. Using a slotted spoon, transfer the meat to a large plate.'),
('15854', '3', 'Add the carrots and onion to the casserole and cook over moderate heat until just softened, about 10 minutes. Return the meat to the casserole.'),
('15854', '4', 'Add the cinnamon, allspice, lemon and orange zests and a generous pinch of pepper and cook, stirring, until fragrant.'),
('15854', '5', 'Add the tomatoes and stock and bring the stew to a boil.'),
('15854', '6', 'Partially cover the stew and cook over moderate heat until the meat is just tender, 40 minutes. Stir in the peas and cook uncovered until the meat is very tender and the sauce thickens slightly, about 10 minutes longer. Discard the lemon and orange zests and serve.'),
('15855', '1', 'Put oven rack in middle position and preheat oven to 400°F.'),
('15855', '2', 'Heat butter in a 10-inch heavy skillet over moderate heat until foam subsides, then cook flour, stirring, until golden brown, 3 to 4 minutes.'),
('15855', '3', 'Transfer to a small bowl.'),
('15855', '4', 'Purée onion, garlic, peppers, sugar, vinegar, and 1/2 teaspoon salt in a blender until smooth, adding 1 to 2 tablespoons water if needed to facilitate puréeing.'),
('15855', '5', 'Heat 2 tablespoons oil in a large nonstick skillet over moderate heat until hot but not smoking, then cook purée, stirring, until thickened, 3 to 4 minutes. (Don''t worry if mixture turns blue-green; this sometimes results from the interaction of vinegar and immature garlic.) Reserve 5 tablespoons purée in a small bowl (for coating lamb) and transfer remainder to another small bowl (to be served on the side with lamb).'),
('15855', '6', 'Sprinkle lamb with remaining tablespoon salt.'),
('15855', '7', 'Heat remaining tablespoon oil in cleaned 10-inch skillet over moderately high heat until hot but not smoking, then brown lamb 1 rack at a time, turning over once, about 4 minutes per rack.'),
('15855', '8', 'Transfer racks to a large roasting pan, arranging with bones curving downward.'),
('15855', '9', 'Spread 1 1/2 tablespoons malagueta purée over meaty part of each rack of lamb, excluding ends. Stir parsley into farofa mixture, then pat mixture onto lamb (over purée) to coat, pressing gently to adhere.'),
('15855', '10', 'Roast lamb until thermometer inserted diagonally 2 inches into center (do not touch bone) registers 125°F (for medium-rare), 20 to 25 minutes.'),
('15855', '11', 'Transfer to a cutting board and let racks stand 15 minutes (internal temperature will rise to about 130°F).'),
('15855', '12', 'Cut each rack into chops and serve remaining purée on the side.'),
('15857', '1', 'In a bowl, mix the sherry with 2 teaspoons of the soy sauce and the cornstarch.'),
('15857', '2', 'Add the lamb and stir to coat.'),
('15857', '3', 'In a bowl, combine the hoisin sauce, vinegar, chile-garlic paste, sugar and the remaining tablespoon of soy sauce.'),
('15857', '4', 'In a wok, heat 2 tablespoons of oil over high heat until smoking.'),
('15857', '5', 'Add the garlic; stir-fry until fragrant, 15 seconds.'),
('15857', '6', 'Add the lamb; cook, stirring, until lightly browned, 3 minutes; transfer to a plate.'),
('15857', '7', 'Add the remaining 1/2 tablespoon of oil to the wok.'),
('15857', '8', 'Add the beans and stir-fry until crisp-tender, about 4 minutes.'),
('15857', '9', 'Add the onion and cook until softened, 2 minutes.'),
('15857', '10', 'Add the pepper and leek and cook, stirring occasionally, until the leek is lightly browned, about 3 minutes.'),
('15857', '11', 'Add the hoisin-vinegar sauce to the wok and cook just until bubbling. Return the lamb to the wok and stir-fry until heated through.'),
('15857', '12', 'Transfer to a platter and serve.'),
('15859', '1', 'Preheat the oven to 35'),
('15859', '2', 'Season the lamb with salt and pepper.'),
('15859', '3', 'Heat the olive oil in a large skillet.'),
('15859', '4', 'Add 2 lamb loins and brown on all sides over high heat.'),
('15859', '5', 'Remove the loins to a platter and repeat with the remaining lamb.'),
('15859', '6', 'Let cool.'),
('15859', '7', 'Pour off the fat from the skillet.'),
('15859', '8', 'Add the wine and water and simmer over moderate heat for 5 minutes, scraping up the browned bits from the bottom of the pan. Strain this lamb jus into a small saucepan.'),
('15859', '9', 'Brush the lamb loins with the mustard and arrange on a baking sheet. Sprinkle with the chopped thyme leaves and roast in the oven for 15 to 20 minutes for medium rare.'),
('15859', '10', 'Transfer the lamb to a cutting board.'),
('15859', '11', 'Bring the reserved lamb jus to a simmer over moderate heat and cook until it has reduced by one-fourth, about 4 minutes.'),
('15859', '12', 'Whisk in the butter and season with salt and pepper.'),
('15859', '13', 'Slice the lamb crosswise into 1/2-inch medallions.'),
('15859', '14', 'Drizzle with the jus, garnish with the thyme sprigs and serve.'),
('15862', '1', 'Preheat oven to 40'),
('15862', '2', 'Mince 2 garlic cloves and rub onto lamb, spreading evenly. Generously sprinkle lamb with salt and pepper. Put lamb on a V-shaped rack in a large roasting pan. Surround rack with onion, carrots, shallots, tomato, and remaining 4 garlic cloves.'),
('15862', '3', 'Drizzle olive oil over vegetables and lamb.'),
('15862', '4', 'Roast 30 minutes. Reduce heat to 350 and cook another 30 minutes.'),
('15862', '5', 'Reduce heat to 25'),
('15862', '6', 'Transfer lamb to a plate and lift rack from pan. Set the roasting pan on a burner over high heat, add wine, and boil, using a wide metal spatula to stir and scrape caramelized vegetables from bottom of pan, until wine has reduced by half. Stir in 2 cups coffee.'),
('15862', '7', 'Remove from heat. Set lamb back in pan (without rack); spoon juices over it. Cover tightly with foil.'),
('15862', '8', 'Return to oven and cook until lamb is tender and pulling away from the bone, about 5 hours, turning lamb once halfway through cooking.'),
('15862', '9', 'Transfer lamb to a platter and cover with foil. Reheat remaining 1 cup coffee and pour with liquid and vegetables from pan into a blender, working in batches if needed. Pulse until smooth.'),
('15862', '10', 'Pour sauce through a strainer set over a bowl, using the back of a spoon or ladle to push it through if needed. Season sauce with salt and pepper.'),
('15862', '11', 'Pour half of sauce over lamb and serve the rest in a bowl. Sprinkle lamb with parsley.'),
('15863', '1', 'Using a paring knife, cut a few 1/4-inch-deep slashes in each lamb chop. In a large bowl, whisk the yogurt with the heavy cream, lemon juice, ginger, garlic, malt vinegar, garam masala, cumin, paprika, cayenne, mace, nutmeg and 1 teaspoon of salt.'),
('15863', '2', 'Transfer the lamb chops to the marinade and turn to coat, then cover and refrigerate overnight.'),
('15863', '3', 'Add the oil to the marinade and toss with the lamb chops.'),
('15863', '4', 'Remove the chops from the marinade and let stand at room temperature for 30 minutes.'),
('15863', '5', 'Light a grill. Season the chops with salt and grill over moderately high heat for 8 minutes, turning once, until well browned.'),
('15863', '6', 'Brush both sides of the chops with the melted butter and grill for another 2 minutes per side for medium-rare.'),
('15864', '1', 'Pour the ouzo into a shallow dish just large enough to hold the lamb chops in a single layer; add the olive oil, nutmeg, peppercorns and a big pinch of salt. Turn the chops in the marinade to coat.'),
('15864', '2', 'Let stand at cool room temperature for 3 hours, turning the chops every 30 minutes.'),
('15864', '3', 'Light a grill.'),
('15864', '4', 'Remove the chops from the marinade and season with salt and pepper; reserve the marinade. Grill the chops over a medium-hot fire, basting frequently with the marinade, until lightly charred outside and medium rare within, about 8 minutes per side.'),
('15865', '1', 'In a food processor, puree the lemons with the garlic, fennel, olive oil and the 1 tablespoon of pepper. Set the lamb in a glass baking dish and coat with the marinade. Cover with plastic wrap and refrigerate overnight.'),
('15865', '2', 'Preheat the oven to 35'),
('15865', '3', 'Scrape off some of the marinade and transfer the lamb into a roasting pan. Season with salt. Roast for about 45 minutes, until an instant-read thermometer inserted in the thickest part registers 12'),
('15865', '4', 'Transfer the lamb to a cutting board and let rest for 15 minutes.'),
('15865', '5', 'Meanwhile, in a large saucepan, combine the water with the polenta, whisking until smooth. Cook over moderate heat, stirring, until the polenta is slightly thickened, about 5 minutes.'),
('15865', '6', 'Whisk in the 1 cup of milk and cook over moderate heat, whisking constantly, until the polenta is almost tender, about 25 minutes.'),
('15865', '7', 'Whisk in the butter and mascarpone and cook for about 15 minutes longer, until the polenta is creamy and tender. Stir in the Pecorino Romano and season the polenta with salt and pepper.'),
('15865', '8', 'Spoon the polenta onto dinner plates. Thinly slice the roasted lamb and arrange the slices over the polenta. In a small bowl, combine the chopped parsley and prepared horseradish. Sprinkle the mixture over the lamb and serve.'),
('15867', '1', 'Season the lamb roasts generously with salt and pepper, wrap in plastic and refrigerate overnight. Bring the roasts to room temperature before cooking.'),
('15867', '2', 'Preheat the oven to 32'),
('15867', '3', 'In a food processor, pulse the almonds with the garlic until finely chopped.'),
('15867', '4', 'Add the mint leaves, cheese and 3/4 cup of the oil and process until smooth. Season the pesto with salt.'),
('15867', '5', 'In a large skillet, heat the remaining 2 tablespoons of olive oil until shimmering.'),
('15867', '6', 'Add the roasts and cook over high heat, turning, until browned all over, about 10 minutes.'),
('15867', '7', 'Transfer the roasts to a large roasting pan and spread half of the pesto over them. Cover tightly with foil and roast for about 2 hours, until an instant-read thermometer inserted in the center of each roast registers 17'),
('15867', '8', 'Remove the foil, increase the oven temperature to 425 and roast for 30 minutes longer, until browned on top.'),
('15867', '9', 'Transfer the lamb to a cutting board and let rest for 10 minutes.'),
('15867', '10', 'Remove the strings and carve each roast into 1/2-inch-thick slices.'),
('15867', '11', 'Serve with the remaining pesto and lemon wedges.'),
('15868', '1', 'Watch how to make this recipe.'),
('15868', '2', 'Place a grill pan over medium-high heat or preheat a gas or charcoal grill.'),
('15868', '3', 'In the bowl of a food processor, combine the balsamic vinegar, garlic, and honey. Pulse until blended. With the machine running, slowly pour in the vegetable oil until the mixture is smooth and forms a thick sauce. Season with salt and pepper, to taste.'),
('15868', '4', 'Season the lamb chops with salt and pepper.'),
('15868', '5', 'Drizzle with the olive oil and sprinkle with rosemary. Grill the lamb chops for 2 to 3 minutes each side until medium-rare.'),
('15868', '6', 'Arrange the lamb chops on a platter. Spoon the sauce over the top or serve the sauce on the side.'),
('15869', '1', 'Combine first 5 ingredients in a small bowl; set aside.'),
('15869', '2', 'Combine salt, cinnamon, and pepper, and sprinkle over both sides of lamb.'),
('15869', '3', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('15869', '4', 'Add lamb to pan; cook 5 minutes on each side or until desired degree of doneness.'),
('15869', '5', 'Remove skillet from heat; add apricot mixture, turning lamb to coat.'),
('15869', '6', 'Place 2 chops on each of 4 dinner plates; spoon remaining apricot mixture evenly over chops.'),
('15871', '1', 'Combine the first 3 ingredients; sprinkle evenly over lamb.'),
('15871', '2', 'Place lamb in a heavy-duty zip-top plastic bag.'),
('15871', '3', 'Add garlic and sherry; seal bag, turning to coat. Marinate in refrigerator 3 hours, turning occasionally.'),
('15871', '4', 'Prepare grill or broiler.'),
('15871', '5', 'Place lamb on grill rack or broiler pan coated with cooking spray; cook 5 minutes on each side or until desired degree of doneness.'),
('15871', '6', 'Serve with lime wedges, if desired.'),
('15872', '1', 'Combine first 8 ingredients in a large zip-top plastic bag.'),
('15872', '2', 'Add lamb; seal and marinate in refrigerator 8 hours or overnight.'),
('15872', '3', 'Preheat oven to 45'),
('15872', '4', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('15872', '5', 'Remove lamb from bag, and discard marinade. Sprinkle both sides of lamb evenly with salt and black pepper.'),
('15872', '6', 'Add half of lamb to skillet, and saut for 2 minutes or until browned.'),
('15872', '7', 'Transfer lamb, browned side up, to a broiler pan coated with cooking spray. Repeat procedure with remaining lamb.'),
('15872', '8', 'Bake lamb at 450 for 6 minutes or until desired degree of doneness.'),
('15873', '1', 'Combine first 5 ingredients in a small bowl; set aside.'),
('15873', '2', 'Combine salt, cinnamon, and pepper, and sprinkle over both sides of lamb.'),
('15873', '3', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('15873', '4', 'Add lamb to pan; cook 5 minutes on each side or until desired degree of doneness.'),
('15873', '5', 'Remove skillet from heat; add apricot mixture, turning lamb to coat.'),
('15873', '6', 'Place 2 chops on each of 4 dinner plates; spoon remaining apricot mixture evenly over chops.'),
('15875', '1', 'Cut off pointed ends of garlic bulbs.'),
('15875', '2', 'Place each bulb on a piece of aluminum foil; drizzle evenly with 2 tablespoons olive oil, and sprinkle evenly with 1/2 teaspoon salt and 1/2 teaspoon pepper. Fold foil to seal.'),
('15875', '3', 'Bake at 425 for 30 minutes; cool. Squeeze pulp from garlic cloves; mash and set aside.'),
('15875', '4', 'Whisk together 1/4 cup olive oil, lemon juice, and shallots; brush inside of lamb with half of oil mixture, and sprinkle with 1 teaspoon salt and 1 teaspoon pepper.'),
('15875', '5', 'Spread inside with mashed garlic, and sprinkle with rosemary, thyme, and lemon rind.'),
