INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('37418', '5', 'b'Add oil in a slow stream, whisking until combined.''),
('37418', '6', 'b'Toss together edamame, escarole, and mint in a large bowl.''),
('37418', '7', 'b'Add cheese and drizzle salad with dressing, then toss again.''),
('37418', '8', 'b'Serve immediately.''),
('37419', '1', 'b'Preheat oven to 400\xc2\xb0F. Arrangeprosciutto slices in single layer on rimmedbaking sheet.''),
('37419', '2', 'b'Bake until prosciutto is crisp,about 12 minutes.''),
('37419', '3', 'b'Remove prosciutto fromoven. let cool on sheet. Coarsely crumble.''),
('37419', '4', 'b'Whisk oil and vinegar in small bowl forvinaigrette. Season with salt and pepper.''),
('37419', '5', 'b'Combine next 4 ingredients in large bowl.''),
('37419', '6', 'b'Fill another large bowl with cold water.''),
('37419', '7', 'b'Pour enough water into large skillet toreach depth of 11/2 inches.''),
('37419', '8', 'b'Add 1 teaspooncoarse salt. bring to simmer. Crack 1 egginto each of 4 custard cups or small bowls,keeping yolks intact. Gently slide eggs intosimmering water. Cook just until whitesare set, about 2 minutes. Using slottedspoon, transfer 1 egg at a time to preparedbowl with cold water. Reserve skillet withwater. do ahead Prosciutto, vinaigrette,salad, and eggs can be made 4 hours ahead.Cover prosciutto, salad, and bowl with eggsseparately. chill.''),
('37419', '9', 'b'Let vinaigrette stand atroom temperature. rewhisk before using.''),
('37420', '1', 'b'Combine first 3 ingredients in a small bowl. Rub miso mixture over both sides of chicken breast halves. Wrap each breast half securely in plastic wrap. Arrange the packets in steamer rack. place rack in a Dutch oven. Steam packets, covered, 20 minutes or until done.''),
('37420', '2', 'b'Remove packets from steamer. let stand 5 minutes.''),
('37420', '3', 'b'Remove chicken from packets, reserving liquid from packets. Dice chicken. set aside. Discard water in pan. wipe pan dry with a paper towel.''),
('37420', '4', 'b'Place a large nonstick skillet coated with cooking spray over medium-high heat until hot.''),
('37420', '5', 'b'Add egg whites, and cook 2 minutes or until done.''),
('37420', '6', 'b'Remove egg whites from skillet. coarsely chop.''),
('37420', '7', 'b'Add reserved cooking liquid, chicken, onion, carrot, and fish sauce to Dutch oven, and bring to a boil. Reduce heat to medium. cook 5 minutes or until liquid almost evaporates.''),
('37420', '8', 'b'Add rice, mushrooms, parsley, green onions, and soy sauce. cook 3 minutes. Stir in egg whites and spinach.''),
('37421', '1', 'b'Preheat the broiler.''),
('37421', '2', 'b'Brush the bread with olive oil and transfer to a baking sheet. Broil the bread a few inches from the heat, turning once, for 2 minutes, until golden and toasted. Lightly rub the whole garlic clove over the toasts.''),
('37421', '3', 'b'In a large, deep pot, heat the 1/4 cup of olive oil.''),
('37421', '4', 'b'Add the shallot, sliced garlic and ginger, season lightly with salt and pepper and cook over high heat, stirring, until the garlic is softened and lightly browned, about 3 minutes.''),
('37421', '5', 'b'Add the mussels and cook, stirring, for 1 minute.''),
('37421', '6', 'b'Add the sake, cover and steam the mussels until they open, about 5 minutes.''),
('37421', '7', 'b'Remove from the heat. Using a slotted spoon, transfer the mussels to 4 deep bowls, discarding any mussels that do not open.''),
('37421', '8', 'b'Add the butter, miso and spinach to the broth, swirling and shaking the pot until the butter melts and the spinach wilts. Slowly pour the broth over the mussels, stopping before you reach the grit at the bottom of the pot.''),
('37421', '9', 'b'Serve the mussels with the garlic toasts.''),
('37422', '1', 'b'Bring a large pot of water to a boil and salt it.''),
('37422', '2', 'b'Add the noodles and cook, stirring occasionally, until tender but not mushy, 5 to 7 minutes.''),
('37422', '3', 'b'Drain and rinse them under cold water then put them in a bowl or pot of cold water.''),
('37422', '4', 'b'Put the beans, nuts, sesame seeds, soy sauce, and a few grinds of black pepper in a blender with 3 cups of ice water. Pure until smooth, thinning with a little more water if the broth looks to thick. Taste and adjust the seasoning. (You can make the broth up to a day ahead. cover tightly and refrigerate.)''),
('37422', '5', 'b'Drain the udon noodles well and pile them up in the center of bowls. Ladle the cool broth all around.''),
('37422', '6', 'b'Garnish with cucumber and a few sesame seeds, a drizzle of sesame oil, and if you like, some chile and scallion. serve.''),
('37422', '7', 'b'Put the beans, nuts, sesame seeds, soy sauce, and a few grinds of black pepper in a blender with 3 cups of ice water. Pure until smooth, thinning with a little more water if the broth looks to thick. Taste and adjust the seasoning. (You can make the broth up to a day ahead. cover tightly and refrigerate.)''),
('37422', '8', 'b'Drain the udon noodles well and pile them up in the center of bowls. Ladle the cool broth all around.''),
('37422', '9', 'b'Garnish with cucumber and a few sesame seeds, a drizzle of sesame oil, and if you like, some chile and scallion. serve.''),
('37423', '1', 'b'Heat a large nonstick skillet over medium heat.''),
('37423', '2', 'b'Add soy chorizo to pan, and cook for 12 minutes or until browned, crumbling and stirring occasionally.''),
('37423', '3', 'b'Place in a small bowl, and set aside.''),
('37423', '4', 'b'Return pan to medium heat.''),
('37423', '5', 'b'Add olive oil, swirling to coat.''),
('37423', '6', 'b'Add yellow onion. cover and cook for 10 minutes or until tender, stirring occasionally.''),
('37423', '7', 'b'Add saffron and garlic. cook for 1 minute, stirring constantly.''),
('37423', '8', 'b'Add 1 cup rice and bell pepper. cook for 2 minutes, stirring frequently. Stir in white wine, and cook for 2 minutes or until liquid is nearly absorbed, stirring frequently.''),
('37423', '9', 'b'Add vegetable broth and salt. bring to a simmer. Cover, reduce heat, and simmer for 20 minutes or until rice is tender and liquid is absorbed.''),
('37423', '10', 'b'Return soy chorizo to pan, and stir in edamame. Cook for 5 minutes or until edamame is thoroughly heated, stirring occasionally. Sprinkle with chopped parsley and 1/4 cup green onions.''),
('37425', '1', 'b'Steam haricots verts, wax beans, and edamame, covered, 6 minutes or until haricots verts and wax beans are crisp-tender.''),
('37425', '2', 'b'Drain and plunge beans into ice water. drain.''),
('37425', '3', 'b'Combine beans, tomatoes, bell pepper, and onion in a large bowl.''),
('37425', '4', 'b'Combine vinegar, sugar, and mustard, stirring with a whisk. Gradually add oil to vinegar mixture, stirring constantly with a whisk. Stir in parsley, salt, and black pepper.''),
('37425', '5', 'b'Drizzle vinaigrette over bean mixture. toss gently to coat.''),
('37426', '1', 'b'Heat oil in a large nonstick skillet over medium-high heat.''),
('37426', '2', 'b'Add mushrooms, ginger, garlic, and jalapeo. stir-fry 2 minutes.''),
('37426', '3', 'b'Add edamame. stir-fry 1 minute. Stir in the corn, soy milk, and vinegar. cook until liquid almost evaporates (about 3 minutes).''),
('37426', '4', 'b'Remove from heat, and stir in cherries, salt, and white pepper.''),
('37426', '5', 'b'Spoon the edamame mixture into the center of a large platter. arrange the cucumber and tomato slices alternately around mixture.''),
('37426', '6', 'b'Garnish with sesame seeds, if desired.''),
('37427', '1', 'b'Peel and chop 1 onion quarter, then pulse in a food processor until finely chopped.''),
('37427', '2', 'b'Add miso and pur\xc3\xa9e until smooth.''),
('37427', '3', 'b'Add 1/2 stick softened butter and 1/2 teaspoon pepper and pur\xc3\xa9e until combined (mixture will appear curdled).''),
('37427', '4', 'b'Put oven rack in lowest position and preheat oven to 350\xc2\xb0F.''),
('37427', '5', 'b'Rinse turkey inside and out, then pat dry. Working from large cavity end, gently run your fingers between skin and meat of breast to loosen skin, being careful not to tear skin. Push miso butter under skin, including thighs and drumsticks, and massage skin from outside to spread miso evenly (see Kitchen Notebook, page 230). Sprinkle large cavity with salt and remaining 1/2 teaspoon pepper. Fold neck skin under body and secure with metal picks or skewers, then stuff large cavity with remaining 3 onion quarters. Tie drumsticks together with string and tuck wings under body.''),
('37427', '6', 'b'Put turkey on rack in roasting pan and roast 30 minutes.''),
('37427', '7', 'b'Melt remaining 1/2 stick softened butter and brush over turkey, then add water (1 cup) to roasting pan. Tent turkey with foil and roast, basting every 30 minutes and adding more water to pan if necessary, until thermometer inserted into fleshy part of a thigh (do not touch bone) registers 170\xc2\xb0F, 2 to 2 1/2 hours more (total roasting time: 2 1/2 to 3 hours).''),
('37427', '8', 'b'Remove foil for last 30 minutes of roasting if turkey is pale.''),
('37427', '9', 'b'Transfer turkey to a platter (reserve roasting pan) and let stand, loosely covered, 25 minutes (temperature will rise to 180\xc2\xb0F while turkey stands).''),
('37427', '10', 'b'Remove picks from turkey.''),
('37427', '11', 'b'Pour pan juices through a fine-mesh sieve into a 2-quart glass measure, then skim off and reserve fat. (If there is less than 1/2 cup fat, add enough melted butter to total 1/2 cup.)''),
('37427', '12', 'b'Pour pan juices and 8 cups turkey stock into a 3-quart saucepan and bring to a simmer. Straddle roasting pan across 2 burners, then add remaining cup turkey stock and deglaze roasting pan by boiling over moderately high heat, stirring and scraping up brown bits, 1 minute.''),
('37427', '13', 'b'Pour through sieve into remaining stock and bring to a simmer.''),
('37427', '14', 'b'Cook flour and 1/2 cup reserved fat in a 4-quart heavy pot over moderately low heat, whisking, 5 minutes.''),
('37427', '15', 'b'Add hot stock mixture in a fast stream, whisking constantly to prevent lumps, then simmer, whisking occasionally, until gravy is thickened, about 10 minutes. Stir in any turkey juices accumulated on platter and season gravy with salt and pepper.''),
('37432', '1', 'b'Place beans into a large saucepan of boiling water. cook 5 minutes.''),
('37432', '2', 'b'Drain and plunge beans into ice water. drain.''),
('37432', '3', 'b'Place ginger on several layers of damp cheesecloth. Gather edges of cheesecloth. squeeze cheesecloth bag over a small bowl. Set 1/2 teaspoon ginger juice aside. reserve remaining juice for another use. Discard ginger.''),
('37432', '4', 'b'Combine 1/2 teaspoon ginger juice, walnuts, water, miso, and soy sauce in a food processor. process until nuts are minced.''),
('37432', '5', 'b'Combine walnut mixture and beans in a large bowl.''),
('37433', '1', 'b'In a medium-size saucepan, with a lid, combine the water, salt and soybean sprouts. Bring to a boil. Reduce to low heat, cover with a lid, and steam the sprouts for 5 minutes.''),
('37433', '2', 'b'Strain the sprouts and transfer to a mixing bowl.''),
('37434', '1', 'b'Heat a grill pan over medium-high heat. Rub steak with 2 teaspoons soy sauce. sprinkle with salt and pepper. Coat pan with cooking spray.''),
('37434', '2', 'b'Add steak to pan. Cook for 5 minutes on each side or until desired degree of doneness.''),
('37434', '3', 'b'Remove from pan. let stand 10 minutes.''),
('37434', '4', 'b'Cut steak diagonally across the grain into 1/2-inch-thick slices.''),
('37434', '5', 'b'Heat oil in a large nonstick skillet over medium heat.''),
('37434', '6', 'b'Add ginger and garlic. saut 1 minute, stirring occasionally.''),
('37434', '7', 'b'Add remaining 2 tablespoons soy sauce and edamame to pan. cook 2 minutes.''),
('37434', '8', 'b'Combine vinegar and wasabi paste in a bowl, stirring until smooth.''),
('37434', '9', 'b'Place 1/2 cup edamame mixture on each of 4 plates. Top each serving with 3 ounces steak. drizzle each with 1 tablespoon vinegar mixture.''),
('37435', '1', 'b'Combine first 4 ingredients, 1/4 cup peanuts, and 3 tablespoons oil in a small bowl. stir with a whisk.''),
('37435', '2', 'b'Cut each tofu block crosswise into 8 (1/2-inch-thick) slices. Arrange tofu on several layers of paper towels. Top with several more layers of paper towels. top with a cast-iron skillet or other heavy pan.''),
('37435', '3', 'b'Let stand 30 minutes.''),
('37435', '4', 'b'Remove tofu from paper towels.''),
('37435', '5', 'b'Heat 1 tablespoon oil in a large nonstick skillet over medium-high heat.''),
('37435', '6', 'b'Add 8 tofu slices to pan. saut 4 minutes on each side or until crisp and golden.''),
('37435', '7', 'b'Remove from pan, and drain tofu on paper towels. Repeat procedure with remaining 1 tablespoon oil and remaining 8 tofu slices.''),
('37435', '8', 'b'Place 1 cup greens on each of 8 plates. Top each serving with 2 tofu slices, 3 tablespoons miso mixture, and 1 1/2 teaspoons chopped peanuts.''),
('37435', '9', 'b'Garnish each serving with chives, if desired.''),
('37436', '1', 'b'Combine first 6 ingredients in a bowl. stir well with a whisk. Set aside.''),
('37436', '2', 'b'Heat a large nonstick skillet coated with cooking spray over medium-high heat.''),
('37436', '3', 'b'Add chicken. cook 4 minutes on each side or until done.''),
('37436', '4', 'b'Cut the chicken into 1/8-inch-thick slices.''),
('37436', '5', 'b'Cut off the raised portion of the main vein of each lettuce leaf. Divide chicken evenly among lettuce leaves. top with carrot, jicama, cucumber, bean sprouts, and cabbage, dividing evenly.''),
('37436', '6', 'b'Roll up, and secure with a pick.''),
('37436', '7', 'b'Serve with sauce.''),
('37442', '1', 'b'Prepare Creamy Grits. cover and keep warm.''),
('37442', '2', 'b'Cook bacon in a large skillet over medium-high heat 9 minutes or until crisp. remove bacon, and drain on paper towels, reserving drippings in skillet. Crumble bacon, and set aside.''),
('37442', '3', 'b'Sprinkle scallops with 1/2 teaspoon salt and 1/8 teaspoon pepper.''),
('37442', '4', 'b'Heat drippings over medium-high heat until hot.''),
('37442', '5', 'b'Add scallops, in 2 batches, and cook 3 minutes. Turn and cook 3 minutes.''),
('37442', '6', 'b'Remove scallops.''),
('37442', '7', 'b'Add butter to pan.''),
('37442', '8', 'b'Add onion and garlic. saut, stirring often, 2 minutes. Stir in bell pepper and edamame. cook 2 minutes or until crisp-tender.''),
('37442', '9', 'b'Add wine, and cook 30 seconds, stirring to loosen particles from bottom of skillet.''),
('37442', '10', 'b'Add bacon, remaining 1/4 teaspoon salt and 1/8 teaspoon pepper, and tomatoes. cook, stirring constantly, 5 minutes or until tomatoes soften. Return scallops to pan. cook 1 minute or just until thoroughly heated.''),
('37442', '11', 'b'Remove from heat, and stir in basil.''),
('37442', '12', 'b'Serve over Creamy Grits.''),
('37442', '13', 'b'Note: Stir the grits just before serving, adding a small amount of hot chicken broth or water if necessary to achieve desired consistency.''),
('37444', '1', 'b'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray. add steak strips. Stir-fry 5 minutes or until steak is done. transfer to a plate.''),
('37444', '2', 'b'Add edamame and water to pan. stir-fry 2 minutes or until thoroughly heated.''),
('37444', '3', 'b'Add bell pepper mix. stir-fry 2 to 3 minutes.''),
('37444', '4', 'b'Add garlic. stir-fry 1 minute. Stir in basting sauce. cook, stirring constantly, 1 minute or until thoroughly heated. Return beef to vegetable mixture. toss to coat.''),
('37444', '5', 'b'Serve with: Orange-Pineapple Spritzer''),
('37445', '1', 'b'Place steak in a 6" x 9" baking dish.''),
('37445', '2', 'b'Combine marinade ingredients. pour over meat. Cover with plastic. refrigerate 1/2 to 2 hours.''),
('37445', '3', 'b'Combine salad ingredients in a bowl. chill until ready to serve.''),
('37445', '4', 'b'Remove meat from marinade. pat dry. Coat grill or broiler pan with cooking spray.''),
('37445', '5', 'b'Heat grill on high. Grill or broil steak 3 minutes on each side for medium-rare.''),
('37445', '6', 'b'Transfer to a platter and let rest 10 minutes.''),
('37445', '7', 'b'Remove onion from marinade. Coat a nonstick skillet with cooking spray. Cook onion over medium-high heat until tender, 5 minutes. Move to a bowl.''),
('37445', '8', 'b'Cut meat thinly. For lettuce rolls: Layer rice, salad, soybean paste, onions and steak in the center of each lettuce leaf. roll up.''),
('37445', '9', 'b'Serve 4 rolls per person.''),
('37445', '10', 'b'Self''),
('37448', '1', 'b'Heat canola oil in a large nonstick skillet over medium-high heat.''),
('37448', '2', 'b'Add ginger, lemongrass, and garlic. saut 1 minute or just until mixture begins to brown.''),
('37448', '3', 'b'Add chicken. saut 2 minutes.''),
('37448', '4', 'b'Add edamame and stir-fry mix. saut 3 minutes.''),
('37448', '5', 'b'Combine soy sauce, mirin, sesame oil, and cornstarch, stirring with a whisk.''),
('37448', '6', 'b'Add to pan. cook 1 minute.''),
('37448', '7', 'b'Remove from heat. Stir in onions, sesame seeds, and salt.''),
('37448', '8', 'b'Serve over rice.''),
('37449', '1', 'b'Cook bacon in a large nonstick skillet over medium heat 7 minutes or until crisp.''),
('37449', '2', 'b'While bacon cooks, sprinkle fillets evenly with 1/4 teaspoon salt and black pepper. When bacon is done, transfer it to paper towels to drain. crumble bacon.''),
('37449', '3', 'b'Add fillets, skin sides up, to drippings in pan. Cook 4 minutes over medium-high heat or until browned. Turn fish over. add crumbled bacon, 1/4 cup water, and remaining ingredients to pan. Cover and steam 3 minutes or until fish flakes easily when tested with a fork or until desired degree of doneness.''),
('37449', '4', 'b'Serve fillets over succotash.''),
('37454', '1', 'b'Heat the oil in a 4-quart saucepan over medium heat.''),
('37454', '2', 'b'Add the onion and cook, stirring often, until softened but not browned, 4 to 5 minutes.''),
('37454', '3', 'b'Add the edamame and corn and cook, turning often, until heated through, about 7 minutes. Stir in the tomato, salt and pepper.''),
('37454', '4', 'b'Let cool and then chill if packing in a lunch box. When ready to serve, stir in the chives or basil.''),
('37454', '5', 'b'Real Food for Healthy Kids''),
('37454', '6', 'b"See Nutrition Data''s analysis of this recipe \xe2\x80\xba"'),
('37454', '7', 'b'Real Food For Healthy Kids reprinted with permission of William Morrow/An Imprint of Harper''),
('37454', '8', 'b'Collins Publishers.''),
('37456', '1', 'b'Prepare edamame according to package directions, omitting salt.''),
('37456', '2', 'b'Drain.''),
('37456', '3', 'b'Cook bacon in a large nonstick skillet over medium-high heat until crisp.''),
('37456', '4', 'b'Remove from pan, reserving 1 tablespoon drippings in pan. crumble bacon.''),
('37456', '5', 'b'Reduce heat to medium. add celery, onion, garlic, and jalapeo to pan. cook 2 minutes, stirring frequently. Stir in edamame, corn, and wine. cook 4 minutes, stirring frequently.''),
('37456', '6', 'b'Add shrimp. cook 5 minutes or until shrimp are done, stirring frequently.''),
('37456', '7', 'b'Remove from heat. Stir in salt and pepper. sprinkle with crumbled bacon and parsley.''),
('37456', '8', 'b'Serve immediately.''),
('37458', '1', 'b'To prepare dressing, combine first 6 ingredients in a bowl, stirring well with a whisk until smooth. Set aside.''),
('37458', '2', 'b'To prepare steak, combine onions, 2 tablespoons soy sauce, 2 teaspoons vinegar, sugar, and minced garlic in a large zip-top plastic bag.''),
('37458', '3', 'b'Add steak to bag. seal. Marinate in refrigerator 1 hour, turning occasionally.''),
('37458', '4', 'b'Prepare grill.''),
('37458', '5', 'b'Remove steak from bag.''),
('37458', '6', 'b'Place steak on grill rack coated with cooking spray. cook 5 minutes on each side or until desired degree of doneness.''),
('37458', '7', 'b'Let stand 5 minutes.''),
('37458', '8', 'b'Cut steak diagonally across grain into thin slices.''),
('37458', '9', 'b'Place steak in a medium bowl.''),
('37458', '10', 'b'Drizzle with half of dressing. toss well.''),
('37458', '11', 'b'Place salad greens in a large bowl.''),
('37458', '12', 'b'Drizzle with remaining dressing. toss well.''),
('37458', '13', 'b'Place about 1 cup salad mixture on each of 4 plates. Top each serving with 3 ounces steak, 4 tomato wedges, and one quarter of cucumber slices. Sprinkle each serving with 1/2 teaspoon sesame seeds.''),
('37458', '14', 'b'Wine note: When layering potent flavors like the savory soy and char-grilled smoke of Grilled Skirt Steak and Mesclun Salad with Miso Dressing, the wine should have similar complexity. A supple syrah, like Gloria Ferrer Syrah 2002 ($19), resonates with this dish: It has just enough tannin to stand up to the steak, and the ripe blackberry and smoky flavors are amplified by the savory elements. --Jeffery Lindenmuth''),
('37461', '1', 'b'Combine first 4 ingredients, 1/4 cup peanuts, and 3 tablespoons oil in a small bowl. stir with a whisk.''),
('37461', '2', 'b'Cut each tofu block crosswise into 8 (1/2-inch-thick) slices. Arrange tofu on several layers of paper towels. Top with several more layers of paper towels. top with a cast-iron skillet or other heavy pan.''),
('37461', '3', 'b'Let stand 30 minutes.''),
('37461', '4', 'b'Remove tofu from paper towels.''),
('37461', '5', 'b'Heat 1 tablespoon oil in a large nonstick skillet over medium-high heat.''),
('37461', '6', 'b'Add 8 tofu slices to pan. saut 4 minutes on each side or until crisp and golden.''),
('37461', '7', 'b'Remove from pan, and drain tofu on paper towels. Repeat procedure with remaining 1 tablespoon oil and remaining 8 tofu slices.''),
('37461', '8', 'b'Place 1 cup greens on each of 8 plates. Top each serving with 2 tofu slices, 3 tablespoons miso mixture, and 1 1/2 teaspoons chopped peanuts.''),
('37461', '9', 'b'Garnish each serving with chives, if desired.''),
('37464', '1', 'b'Cook noodles in boiling water 7 minutes or until almost al dente.''),
('37464', '2', 'b'Add soybeans to pan. cook 1 minute or until thoroughly heated.''),
('37464', '3', 'b'Drain.''),
('37464', '4', 'b'Place noodle mixture in a large bowl.''),
('37464', '5', 'b'Add carrots, onions, cilantro, and chile. toss.''),
('37464', '6', 'b'Heat a large skillet over medium-high heat. Sprinkle shrimp with salt and pepper. Coat pan with cooking spray.''),
('37464', '7', 'b'Add shrimp. cook 1 1/2 minutes on each side.''),
('37464', '8', 'b'Add shrimp to noodle mixture.''),
('37464', '9', 'b'Combine orange juice and remaining ingredients in a bowl, stirring well with a whisk.''),
('37464', '10', 'b'Drizzle juice mixture over noodle mixture. toss well.''),
('37465', '1', 'b'Preheat broiler.''),
('37465', '2', 'b'Sprinkle steak evenly with ginger, salt, and garlic.''),
('37465', '3', 'b'Place on a broiler pan coated with cooking spray. broil 6 minutes on each side or until desired degree of doneness.''),
('37465', '4', 'b'Let stand 5 minutes.''),
('37465', '5', 'b'Cut steak diagonally across grain into thin slices.''),
('37465', '6', 'b'Combine cilantro and next 6 ingredients (through chile paste) in a small bowl, stirring with a whisk.''),
('37465', '7', 'b'Combine lettuce and remaining ingredients in a large bowl.''),
('37465', '8', 'b'Drizzle half of miso mixture over lettuce mixture. toss to coat.''),
('37465', '9', 'b'Place 1 1/2 cups lettuce mixture on each of 4 plates. Top each with 3 ounces steak. top with miso mixture.''),
('37466', '1', 'b'Remove stems from mushrooms. Reserve stems. Slice mushroom caps into (1/4-inch) julienne strips. set aside.''),
('37466', '2', 'b'Combine stems, broth, ginger, and garlic in a large saucepan. bring to a boil. Reduce heat, and simmer 15 minutes. Strain broth through a sieve into a bowl. discard solids.''),
('37466', '3', 'b'Add miso to broth, stirring well with a whisk.''),
('37466', '4', 'b'Add tofu. Cover and keep warm.''),
('37466', '5', 'b'Heat oil in a large nonstick skillet over medium-high heat.''),
('37466', '6', 'b'Add sliced mushrooms caps and pepper to pan. saut 3 minutes or until browned.''),
('37466', '7', 'b'Add to broth mixture.''),
('37466', '8', 'b'Cook noodles according to package directions, omitting salt and fat.''),
('37466', '9', 'b'Drain and rinse with cold water. drain.''),
('37466', '10', 'b'Place 2/3 cup noodles into each of 6 shallow bowls. pour 1 1/2 cups hot broth mixture over each serving.''),
('37466', '11', 'b'Garnish each serving with 1/4 cup cabbage, about 1 1/2 tablespoons carrots, about 1 1/2 tablespoons onions, and 1 teaspoon sesame seeds.''),
('37468', '1', 'b'Watch how to make this recipe.''),
('37468', '2', 'b'For the edamame: Bring a medium pot of water to a boil over high heat. Carefully dump in the edamame, cover, and boil until the edamame are cooked through, about 5 minutes.''),
('37468', '3', 'b'Drain and put them into a serving bowl. Sprinkle over some sea salt and chili powder. serve immediately.''),
('37468', '4', 'b'For the jicama: Peel and cut the jicama into French fry size pieces.''),
('37468', '5', 'b'Put them into a bowl and sprinkle on some chili powder. Squeeze over some lime juice and mix well. serve immediately.''),
('37468', '6', 'b'For the mango: Peel and cut the mango into chunks.''),
('37468', '7', 'b'Put them into a bowl and sprinkle on some chili powder. Squeeze over some lime juice and mix well. serve immediately.''),
('37470', '1', 'b'In a large serving bowl, whisk together the red wine vinegar, grapeseed oil, cilantro, lime juice, sugar, salt and garlic. Set aside.''),
('37470', '2', 'b'Bring a large pot of lightly salted water to a boil.''),
('37470', '3', 'b'Add the soybeans and boil for 3 minutes.''),
('37470', '4', 'b'Add corn to the boiling water and continue cooking for 1 more minute.''),
('37470', '5', 'b'Drain very well, and pour into the bowl with the dressing. Gently mix in the cherry tomatoes, green onions and black beans. Cover and refrigerate for at least 2 hours before serving to chill and blend the flavors.''),
('37472', '1', 'b'Pur\xc3\xa9e bell pepper with vinegar and sugar in a blender until smooth.''),
('37472', '2', 'b'Transfer to a small heavy saucepan and stir in red pepper flakes. Simmer 5 minutes, then pour through a fine sieve into a bowl, pressing on solids.''),
('37477', '1', 'b'Place the peanuts in a food processor or large mortar and process or pound to a coarse powder. set aside. If using tamarind, press it through a sieve. reserve the liquid and discard the solids.''),
('37477', '2', 'b'Heat the oil in a wok or skillet over high heat.''),
('37477', '3', 'b'Add the garlic and stir-fry until it is starting to change color, about 15 seconds.''),
('37477', '4', 'b'Toss in the pork and use your spatula to break it up into small pieces.''),
('37477', '5', 'b'Once it all has changed color, add the soybean paste and the tamarind or tomato paste and stir to blend.''),
('37477', '6', 'b'Stir in  cup of the water, then stir in most of the ground peanuts, reserving about 1 tablespoon for garnish.''),
('37477', '7', 'b'Stir in the sugar and chiles.''),
('37477', '8', 'b'Add up to  cup more water, until you have the desired texture: a thick liquid, pourable but not watery.''),
('37477', '9', 'b'Serve in small individual condiment bowls or in one medium bowl with a spoon so guests can drizzle sauce onto their food or onto their plates.''),
('37477', '10', 'b'Serve warm or at room temperature, squeezing on the optional lime juice and sprinkling on the reserved ground peanuts just before serving.''),
('37477', '11', 'b'var article''),
('37477', '12', 'b'Type_27_data = {}.''),
('37477', '13', 'b'article''),
('37477', '14', 'b'Type_27_data.init_step_by_step_images = 0.''),
('37478', '1', 'b'To prepare dressing, combine the first 12 ingredients in a blender, and process until smooth.''),
('37478', '2', 'b'To prepare salad, combine lettuce and remaining ingredients in a medium bowl.''),
('37478', '3', 'b'Drizzle dressing over salad. toss gently to coat.''),
('37479', '1', 'b'Put the string beans and frozen edamame into a steamer basket and steam them for 4 minutes.''),
('37479', '2', 'b'Transfer the beans to a large bowl and put them into the refrigerator to cool for 15 minutes or longer.''),
('37479', '3', 'b'In a small bowl whisk together the oil, vinegar, apricot preserves, sugar and ginger.''),
('37479', '4', 'b'Add the black beans and scallions to the other beans, drizzle with dressing, and toss to coat. Season with salt, to taste.''),
('37480', '1', 'b'Preheat oven to 400 degrees F.''),
('37480', '2', 'b'Toss parsnip chunks with olive oil and salt and pepper and place on a baking sheet. Roast until nicely browned, turning as needed, about 20 minutes.''),
('37480', '3', 'b'Let cool. Then toss with watercress, apple and shallot.''),
('37480', '4', 'b'Whisk together dressing ingredients and season, to taste, with salt and pepper.''),
('37482', '1', 'b'Heat 1/2 cup oil to saute the spices till fragrant.''),
('37482', '2', 'b'Add in salt, rock sugar and 500ml general santan and bring to a low boil till sugar dissolves.''),
('37482', '3', 'b'Add in the rest of the coconut milk, tow pok, and pigs blood, if used. When soup comes to a boil, add prawn stock and seasoning, then bring to just boiling point.''),
('37485', '1', 'b'Cook rice according to package directions. set aside.''),
('37485', '2', 'b'Heat 1/2 teaspoon oil in a wok or large nonstick skillet over medium-high heat.''),
('37485', '3', 'b'Add ginger and garlic. saut 1 minute.''),
('37485', '4', 'b'Add pork. saut 3 minutes or until pork loses its pink color.''),
('37485', '5', 'b'Place pork mixture in a large bowl. cover and keep warm.''),
('37485', '6', 'b'Add 1 teaspoon oil to pan.''),
('37485', '7', 'b'Add edamame and carrot. saut 2 minutes.''),
('37485', '8', 'b'Add onions and bell pepper. saut 2 minutes.''),
('37485', '9', 'b'Add carrot mixture to pork mixture in bowl. keep warm.''),
('37485', '10', 'b'Heat remaining 2 1/2 tablespoons oil in pan.''),
('37485', '11', 'b'Add cooked rice and soy sauce to pan. saut 3 minutes. Return pork mixture to pan. Stir in broth and next 5 ingredients (through black pepper). cook 2 minutes or until thoroughly heated. Spoon 1 1/2 cups fried rice mixture onto each of 4 individual plates. top each serving with 1 1/2 teaspoons peanuts.''),
('37491', '1', 'b'Pulse about 1/4 of onion rings, plus rosemary and garlic in a food processor until finely chopped.''),
('37491', '2', 'b'Add black pepper, poultry seasoning, and miso paste and pur\xc3\xa9e until smooth.''),
('37491', '3', 'b'Add butter and pur\xc3\xa9e \xe2\x80\x94 mixture will appear curdled.''),
('37491', '4', 'b'Put oven rack in lowest position and preheat to 350\xc2\xb0F. Rinse turkey inside and out, then pat dry. Working from large cavity end, gently run fingers between skin and meat of breast to loosen skin, being careful not to tear skin. Push miso butter under skin, including thighs and drumsticks, and massage from outside to spread evenly.''),
('37491', '5', 'b'Place a lemon slice inside of a pepper ring and slide under skin, positioning evenly over breast and drumsticks. Repeat with remaining pepper and lemon slices until a pleasing pattern results. Sprinkle cavity with seasoned salt. Stuff cavity with lemon and orange quarters, squeezing juice into cavity as you go, and fold neck skin and flap into the cavity. Tie drumsticks together with kitchen string and tuck wings under body.''),
('37491', '6', 'b'Rub turkey with 2 tablespoons of oil. Shake 1 tablespoon flour in oven roasting bag, layer bottom of bag with onion and celery slices, and place bag into roasting pan.''),
('37491', '7', 'b'Place turkey on top of onions and celery in bag and close bag with tie included in the box.''),
('37491', '8', 'b'Cut six 1/2-inch slits in top of bag, as directed. Roast according to package directions, about 2 1/2 to 3 hours, or until timer pops out.''),
('37491', '9', 'b'Remove from oven and let sit in the bag for 30 minutes.''),
('37491', '10', 'b'Remove turkey from bag.''),
('37491', '11', 'b'Strain pan juices into a 3-quart saucepan and skim off excess fat, if desired.''),
('37491', '12', 'b'Add 4 cups turkey stock to pan juices and bring to a boil. While stock is reaching boil, whisk together water and cornstarch. Slowly pour cornstarch mixture into boiling stock, whisking continuously. Cook for 5 to 6 minutes or until gravy is thickened and clear. Stir in any turkey juices accumulated on platter and season gravy with salt and pepper.''),
('37492', '1', 'b'Preheat the oven to 400 degrees F (200 degrees C).''),
('37492', '2', 'b'Place the edamame into a colander and rinse under cold water to thaw.''),
('37492', '3', 'b'Drain.''),
('37492', '4', 'b'Spread the edamame beans into the bottom of a 9x13 inch baking dish.''),
('37492', '5', 'b'Drizzle with olive oil. Sprinkle cheese over the top and season with salt and pepper.''),
('37492', '6', 'b'Bake in the preheated oven until the cheese is crispy and golden, about 15 minutes.''),
('37493', '1', 'b'Preheat the oven to 350F (180C). Trim the crusts from the bread. Flatten the slices with a rolling pin, and brush with the melted butter.''),
('37493', '2', 'b'Using a 2in (5cm) round cookie cutter, stamp out 3 pieces from each slice of bread. Push the bread, butter-side down, firmly into a 12-cup mini-muffin pan.''),
('37493', '3', 'b'Bake for about 12 minutes, or until well crisped.''),
('37493', '4', 'b'Remove the croustades from the pan and let cool on a wire rack.''),
('37493', '5', 'b'Cook the frozen beans in a saucepan of lightly salted boiling water about 5 minutes, until tender.''),
('37493', '6', 'b'Drain, rinse in cold water, and drain again.''),
('37493', '7', 'b'Coarsely pure the beans, shallot, basil, oil, and garlic in a blender or food processor. Season with salt and pepper.''),
('37493', '8', 'b'Divide the bean pesto among the croustades and top each with a basil leaf.''),
('37493', '9', 'b'Serve immediately.''),
('37493', '10', 'b'var article''),
('37493', '11', 'b'Type_27_data = {}.''),
('37493', '12', 'b'article''),
('37493', '13', 'b'Type_27_data.init_step_by_step_images = 0.''),
('37506', '1', 'b'To prepare sauce, combine first 10 ingredients in a blender. process until well combined. Set aside.''),
('37506', '2', 'b'To prepare salsa, combine mango, red onion, mint, and jalapeo in a medium bowl, tossing to combine.''),
('37506', '3', 'b'To prepare coconut rice, combine rice, coconut, salt, and coconut milk in a medium saucepan. bring to a boil over medium-high heat, stirring once. Cover, reduce heat, and simmer 15 minutes or until liquid is absorbed.''),
('37506', '4', 'b'Remove from heat. cover and let stand 10 minutes. Fluff with a fork. keep warm.''),
('37506', '5', 'b'Cook edamame according to package directions, omitting salt and fat. Keep warm.''),
('37506', '6', 'b'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.''),
('37506', '7', 'b'Add chicken. cook 3 minutes on each side or until browned.''),
('37506', '8', 'b'Remove from heat, and cut chicken into 1/4-inch slices.''),
('37506', '9', 'b'Combine chicken and sauce in pan. cook 3 minutes or until done.''),
('37506', '10', 'b'Serve over rice. top with edamame and salsa.''),
('37509', '1', 'b'Preheat the oven to 350*F.''),
('37509', '2', 'b'Spread the almonds and walnuts on a baking sheet.''),
('37509', '3', 'b"Bake 6 minutes, stir, and bake 4 minutes longer.When it''s cool enough to handle, cut almonds in half crosswise.In a bowl, combine toasted nuts, soy nuts, blueberries and ginger. Enjoy!"'),
('37512', '1', 'b'Cook leek, celery, carrot, garlic, and thyme sprig in oil with 1/2 teaspoon salt and 1/4 teaspoon pepper in a 5-to 6-quart heavy pot over medium heat, stirring occasionally, until vegetables brown and stick to bottom of pot, 10 to 15 minutes.''),
('37512', '2', 'b'Add potatoes and chard stems with 1/2 teaspoon salt and cook, stirring occasionally, until beginning to soften, about 5 minutes.''),
('37512', '3', 'b'Add water and bring to a boil, stirring and scraping up brown bits.''),
('37512', '4', 'b'Stir in edamame, zucchini, green beans, pasta, chard leaves, and 1/4 tsp salt and simmer, uncovered, until pasta is al dente and vegetables are tender, about 10 minutes. Discard thyme sprig.''),
('37520', '1', 'b'Combine 2 tablespoons soy sauce, 2 tablespoons vinegar, sesame oil, and five-spice powder in a medium bowl, stirring with a whisk.''),
('37520', '2', 'b'Add beef. toss to coat.''),
('37520', '3', 'b'Let stand 10 minutes.''),
('37520', '4', 'b'Remove beef from bowl. discard marinade.''),
('37520', '5', 'b'Combine 2 tablespoons soy sauce, 2 tablespoons vinegar, water, and cornstarch, stirring with a whisk.''),
('37520', '6', 'b'Heat 1 teaspoon peanut oil in a large nonstick skillet over medium-high heat.''),
('37520', '7', 'b'Add beef. stir-fry 1 minute.''),
('37520', '8', 'b'Remove beef from pan.''),
('37520', '9', 'b'Add 1 teaspoon peanut oil, 2 tablespoons sesame seeds, ginger, and garlic to pan. stir-fry 30 seconds.''),
('37520', '10', 'b'Add bell pepper, edamame, mushrooms, and corn. stir-fry 2 minutes.''),
('37520', '11', 'b'Add beef and cornstarch mixture. stir-fry 3 minutes or until sauce thickens.''),
('37520', '12', 'b'Remove from heat. stir in 1 tablespoon sesame seeds and onions.''),
('37520', '13', 'b'Serve over rice.''),
('37521', '1', 'b'Finely grind coriander seeds in grinder. Stir together ground coriander and 2 tablespoons water in a small bowl.''),
('37521', '2', 'b'Coarsely pur\xc3\xa9e shallots and garlic in mini processor, scraping down side occasionally.''),
('37521', '3', 'b'Heat oil in a 6- to 7-quart wide heavy pot over moderately high heat until hot but not smoking, then cook shallot pur\xc3\xa9e with cinnamon stick, stirring occasionally and scraping up any brown bits, until pale golden, 4 to 5 minutes.''),
('37521', '4', 'b'Add coriander mixture, mashed soybean sauce, sugar, and cloves and cook, stirring, 2 minutes. Increase heat to high, then add pork and cook, stirring occasionally, until pork is no longer pink on the outside, 2 to 3 minutes.''),
('37521', '5', 'b'Add soy sauce and remaining 5 cups water and bring to a boil, stirring occasionally. Reduce heat and simmer, partially covered, until meat is tender, 1 1/2 to 1 3/4 hours.''),
('37521', '6', 'b'Meanwhile, blanch bamboo shoots in a large saucepan of boiling water 1 minute, then drain well in a colander. Stir bamboo shoots into braised pork and simmer, uncovered, until tender, about 15 minutes. (Liquid should be reduced to about 2 cups. If necessary, transfer pork and bamboo shoots with a slotted spoon to a bowl and boil liquid to reduce, then stir in pork and bamboo shoots.) Discard cinnamon stick and season with salt.''),
('37537', '1', 'b'Saut the chopped onion, garlic, and mushrooms (if using) in olive oil until onion is soft.''),
('37537', '2', 'b'Add the chopped chilies, flatten mixture in bottom of pan and saut, not stirring, until the onions begin to caramelize a little, then remove from heat.In a large bowl, mix remaining ingredients except tortillas.To put together the chimichangas, place about 3/4 to 1 cup of filling on a tortilla, fold the bottom over the filling, fold the sides in, then carefully fold/flip it over to close. repeat until you have as many chimichangas as you want to bake at one time.''),
('37537', '3', 'b"Place the chimichangas on a cookie sheet, brush each one with 1/2 teaspoon of olive oil, and bake at 400 degrees F for 15 minutes.Sprinkle each with grated cheddar, serve with extra sour cream, guacamole, and salsa, and enjoy!Makes 8 to 10 large chimichangas, depending on the amount of filling you put in each.(Black soybeans are good for those eating low carb because they are lower in carbohydrates and high in fiber. Information on black soybeans available at the Eden Foods website.).Note: To make these for a picnic or potluck, instead of baking them as I would at home, I make the filling and put it in a container, then bring tortillas and toppings and set them all out so folks can make their own sort of burritos. It''s very popular! :)."'),
('37539', '1', 'b'Place 2 pots of water on to boil: 1 pasta pot with a few inches of water in it, 1 medium sauce pan with 1 1/2 cups of water in it. Cover both pots and bring all the water to a boil.''),
('37539', '2', 'b'When the smaller pot of water comes to a boil, stir in rice and return water to a boil. Reduce heat to simmer.''),
('37539', '3', 'b'Place a colander over the pot and add the edamame to it.''),
('37539', '4', 'b'Place the pot cover over the edamame nesting it in the colander. Steam the edamame 5 minutes, then remove them to 2 small bowls, salt them and cover bowls with plastic or foil to keep warm. Set colander aside and return pot lid to rice, stirring rice before replacing the lid.''),
('37539', '5', 'b'While the edamame are steaming, before removing them to the bowls, you have a pocket of time to work with.''),
('37539', '6', 'b'Add 1/2 cup, a couple of handfuls of Napa cabbage to the second pot of water. Blanch the shredded cabbage 1 minute and remove with a spider or tongs to paper towels to drain and cool. Chop shredded blanched cabbage.''),
('37539', '7', 'b'Combine meat, chopped salad shrimp, sake, ginger, 1 scallion, 1 tablespoon tamari, sesame oil, black pepper and cooled, chopped cabbage in a bowl.''),
('37539', '8', 'b'Place 2 teaspoons of filling on each won ton wrapper. Wet your fingertips to help seal won ton wrappers. The gyoza should look like small half moons.''),
('37539', '9', 'b'Place 1 or 2 Napa cabbage leaves into the bottom of the colander. The leaves will prevent your dumplings from sticking to the surface of colander. Arrange dumplings on Napa leaf in colander and steam over second larger pot of simmering water.''),
('37539', '10', 'b'Place large pot lid over the colander to trap the steam. Dumplings need to steam 10 to 12 minutes. While you are working on this, go back and forth with the edamame as necessary per above directions.''),
('37539', '11', 'b'While dumplings work, slice the fillet steaks thinly across the grain. Toss with seasoning and teriyaki or tamari and sherry.''),
('37539', '12', 'b'Heat a nonstick skillet over high heat.''),
('37539', '13', 'b'Add oil and the meat and stir-fry. When meat browns at edges, add scallions and cook 2 minutes more, stirring frequently.''),
('37539', '14', 'b'Use remaining raw shredded Napa cabbage as a bed to serve your dumplings on. Plate all of your items on little dishes and in small bowls.''),
('37539', '15', 'b'Mix dipping sauce of tamari, mustard and vinegar for the gyoza and set out alongside dumplings.''),
('37539', '16', 'b'Warm or cold sake, leftover from cooking, is the perfect beverage and chilled navel oranges or tangerines make a refreshing end to this meal.''),
('37543', '1', 'b'If using desiccated coconut, soak in warm water to cover 1 hour and drain well in a sieve.''),
('37543', '2', 'b'Heat oil in a 3-quart heavy saucepan over moderate heat until hot but not smoking, then cook mustard seeds, cumin, dals, asafetida, chile, and curry leaves, stirring occasionally, until mustard seeds begin to pop. Stir in beans, water, and salt to taste and simmer, covered, until beans are just tender and most of water is evaporated, 6 to 8 minutes. Stir in coconut.''),
('37543', '3', 'b'* Dals are dried legumes.''),
('37549', '1', 'b'Combine the cabbage, carrot, and cauliflower in a medium-size saucepan.''),
('37549', '2', 'b'Add water to cover, and bring it to a boil over medium-high heat. Stir in the turmeric and curry leaves. Lower the heat to medium, cover the pan, and simmer, stirring occasionally, until the vegetables are fork-tender, 12 to 15 minutes.''),
('37549', '3', 'b'While the vegetables are cooking, heat the oil in a small skillet over medium-high heat. Sprinkle in the split peas, lentils, coriander seeds, and chiles. Roast until the legumes and seeds turn reddish brown and the chiles blacken, 2 to 3 minutes. Using a slotted spoon, transfer the legume-spice blend to a blender jar, leaving as much oil in the skillet as possible.''),
('37549', '4', 'b'Steal about 2 tablespoons of the cooking water from the simmering vegetables and pour it into a small bowl.''),
('37549', '5', 'b'Add the tamarind paste and stir to dissolve it.''),
('37549', '6', 'b'Pour this tart liquid over the spices in the blender jar, and add the tomato. Puree, scraping the inside of the jar as needed, to make a gritty, reddish-brown paste.''),
('37549', '7', 'b'Drain the vegetables in a colander, reserving 1 cups of the cooking water. Then return the vegetables to the saucepan.''),
('37549', '8', 'b'Add the lentil paste.''),
('37549', '9', 'b'Pour the reserved cooking water into the blender and give the blades a quick whir to wash out the jar.''),
('37549', '10', 'b'Add the washings to the pan, sprinkle in the salt, and stir once or twice.''),
('37549', '11', 'b'Reheat the oil remaining in the skillet over medium-high heat.''),
('37549', '12', 'b'Add the mustard seeds, cover the skillet, and cook until the seeds have stopped popping (not unlike popcorn), about 30 seconds. Stir this seedy oil into the vegetables.''),
('37549', '13', 'b'Heat the curry over medium heat, uncovered, stirring occasionally, to allow the flavors to marry, 3 to 5 minutes. Sprinkle the rice flour over the mixture and quickly stir it in. Cook until the curry has thickened, 1 to 2 minutes. Sprinkle with the cilantro, and serve.''),
('37549', '14', 'b'var article''),
('37549', '15', 'b'Type_27_data = {}.''),
('37549', '16', 'b'article''),
('37549', '17', 'b'Type_27_data.init_step_by_step_images = 0.''),
('37554', '1', 'b'In a medium saucepan, cover the cannellini beans with water and bring to a boil.''),
('37554', '2', 'b'Remove from the heat, cover and let stand for 1 hour.''),
('37554', '3', 'b'Drain the beans.''),
('37554', '4', 'b'In the same saucepan, heat 2 tablespoons of the oil.''),
('37554', '5', 'b'Add the onion, carrot, celery and garlic and cook over moderate heat, stirring, until softened, 5 minutes.''),
('37554', '6', 'b'Add the cannellini beans and chicken stock and bring to a boil. Cover and simmer over low heat, stirring occasionally, until the beans are tender, about 1 hour and 15 minutes.''),
('37554', '7', 'b'Meanwhile, roast the red pepper directly over a gas flame or under a preheated broiler until charred all over.''),
('37554', '8', 'b'Let cool slightly, then discard the charred skin, stem and seeds.''),
('37554', '9', 'b'Cut the pepper into 1/2-inch dice.''),
('37554', '10', 'b'Add the green beans to the cannellini beans and simmer over moderate heat until tender, about 5 minutes. Stir in the roasted red pepper and season with salt and pepper.''),
('37554', '11', 'b'Preheat the oven to 37''),
('37554', '12', 'b'On a rimmed baking sheet, toss the focaccia with 1 tablespoon of the oil.''),
('37554', '13', 'b'Bake for 7 minutes, or until crisp. let cool. Leave the oven on.''),
('37554', '14', 'b'In a small skillet, heat 1/2 tablespoon of the oil. Season the squab livers with salt and pepper and cook over moderately high heat until lightly browned, about 1 minute per side.''),
('37554', '15', 'b'Add the shallot and cook over low heat until softened, about 3 minutes. Finely dice the livers and add them to the focaccia along with the shallot. Stir in the thyme and season with salt and pepper.''),
('37554', '16', 'b'Stuff the squab with the focaccia. Rub the butter all over the squab and season with salt and pepper. In a large ovenproof skillet, heat the remaining 2 tablespoons of oil.''),
('37554', '17', 'b'Add the squab, breast side up. Roast the squab in the upper third of the oven for about 20 minutes, basting every 5 minutes, until an instant-read thermometer inserted in the breast registers 130 for medium-rare.''),
('37554', '18', 'b'Transfer the squab to a carving board and let rest for 5 minutes. Mound the stuffing from each bird onto each plate. Carve the breast halves and whole legs and transfer to the plates. Spoon the bean stew alongside and serve.''),
('37556', '1', 'b'In a Dutch oven, heat the pork fat and olive oil over high heat until it is almost smoking.''),
('37556', '2', 'b'Add the parsley and the onions and cook over high heat, until they are browned and soft, about 8 to10 minutes. Stir in the tomato paste and cook over medium heat 10 minutes.''),
('37556', '3', 'b'Add the chicken stock and the cooked beans and bring to a boil.''),
('37556', '4', 'b'Add the pasta pieces and cook 5 or 6 more minutes.''),
('37556', '5', 'b'Remove from heat and allow to rest 10 minutes. Divide among 6 serving bowls, drizzle with remaining oil and serve.''),
('37556', '6', 'b'In a large, heavy-bottomed saucepan, heat the oil over high heat until smoking.''),
('37556', '7', 'b'Add all the chicken parts and brown all over, stirring to avoid burning.''),
('37556', '8', 'b'Remove the chicken and reserve.''),
('37556', '9', 'b'Add the carrots, onions, and celery to the pot and cook until soft and browned. Return the chicken to the pot and add 6 quarts of water, the tomato paste, peppercorns, and parsley. Stir with a wooden spoon to dislodge the browned chicken and vegetables bits from the bottom of the pan. Bring almost to a boil, then reduce heat and cook at a low simmer until reduced by half, about 2 hours, occasionally skimming excess fat.''),
('37556', '10', 'b'Remove from heat, strain, and press on the solids with the bottom of a ladle to extract out all liquids. Stir the stock to facilitate cooling and set aside. Refrigerate stock in small containers for up to a week or freeze for up to a month.''),
('37557', '1', 'b'Remove the zampone from its bath and rinse in cold water. Pat dry.''),
('37557', '2', 'b'In a large bowl, thoroughly combine the pork meat, ham skin, the prosciutto, the Italian sausage and the spices. Season the inside of the zampone with salt and pepper and stuff with the pork mixture. Using a large needle and butcher?s twine, truss the leg. In a large pot, place the zampone with enough water to cover by several inches.''),
('37557', '3', 'b'Place over high heat and bring to a boil. Lower the heat and simmer covered for 2 hours.''),
('37557', '4', 'b'Meanwhile, boil the soaked beans in water 1 hour, until tender but still slightly firm.''),
('37557', '5', 'b'In a 12 to 14-inch saute pan, heat the lard over high heat.''),
('37557', '6', 'b'Add the onion and cook over high heat 5 minutes, until golden brown. Stir in the chicken stock and tomato paste and cook over medium heat 5 minutes.''),
('37557', '7', 'b'Add the drained beans and cook 10 minutes, stirring occasionally. Season with salt a pepper and place onto a serving platter.''),
('37557', '8', 'b'When the zampone is done, remove from the water, allow to rest 10 minutes, then slice into 1/2-inch rounds and place atop the beans.''),
('37557', '9', 'b'Drizzle with real balsamic vinegar, and serve.''),
('37557', '10', 'b'In a large, heavy-bottomed saucepan, heat the oil over high heat until smoking.''),
('37557', '11', 'b'Add all the chicken parts and brown all over, stirring to avoid burning.''),
('37557', '12', 'b'Remove the chicken and reserve.''),
('37557', '13', 'b'Add the carrots, onions, and celery to the pot and cook until soft and browned. Return the chicken to the pot and add 3 quarts of water, the tomato paste, peppercorns, and parsley. Stir with a wooden spoon to dislodge the browned chicken and vegetables bits from the bottom of the pan. Bring almost to a boil, then reduce heat and cook at a low simmer until reduced by half, about 2 hours, occasionally skimming excess fat.''),
('37557', '14', 'b'Remove from heat, strain, and press on the solids with the bottom of a ladle to extract out all liquids. Stir the stock to facilitate cooling and set aside. Refrigerate stock in small containers for up to a week or freeze for up to a month.''),
('37563', '1', 'b'Preheat the oven to 475 degrees F.''),
('37563', '2', 'b'Place the chicken wings in an oven proof baking dish.''),
('37563', '3', 'b'Add the barbecue sauce ingredients to a blender and mix for 5 seconds.''),
('37563', '4', 'b'Pour sauce over the chicken wings and toss to coat thoroughly.''),
('37563', '5', 'b'Bake in the oven for 15 minutes.Reduce oven temperature to 350 degrees F and bake for an additional 20 minutes.''),
('37563', '6', 'b'Serve hot or at room temperature.''),
('37564', '1', 'b'Heat olive oil and butter in a large pot over medium-high heat.''),
('37564', '2', 'b'Place chicken in the pot. Cook and stir 7 to 10 minutes, until chicken is no longer pink. Stir in the carrot, onion, celery, garlic, chili powder, cumin, paprika, and salt and pepper, and cook and stir until the onion is translucent and the vegetables are beginning to soften, 3 to 4 more minutes.''),
('37564', '3', 'b'Stir in the hot sauce, tomato sauce, crushed tomatoes, and white and red kidney beans. Bring to a boil, and simmer over medium-low heat about 1 hour, until the vegetables are tender and the flavors have blended.''),
('37570', '1', 'b'Heat the oil in a large skillet.''),
('37570', '2', 'b'Add the onion and cook over moderately high heat, until lightly browned.''),
('37570', '3', 'b'Add the long beans and red pepper and stir-fry until the beans are slightly softened and browned in spots, 5 minutes. Stir in the sugar.''),
('37570', '4', 'b'Add the water, cover and cook over moderately low heat until it has evaporated and the beans are tender, 5 minutes.''),
('37570', '5', 'b'Add the soy sauce and pepper and cook for 1 minute.''),
('37570', '6', 'b'Transfer to a platter and serve.''),
('37571', '1', 'b'Cook untrimmed beans in a 6- to 8-quart pot of boiling salted water, uncovered, stirring occasionally, until just tender, 3 to 5 minutes.''),
('37571', '2', 'b'Transfer with tongs to a large bowl of ice and cold water to stop cooking, then drain in a colander and pat dry with paper towels. Trim beans and cut crosswise into 3/4-inch pieces.''),
('37571', '3', 'b'Meanwhile, pulse peanuts in a food processor until about half of peanuts are finely ground and remainder are in very large pieces (do not grind to a paste).''),
('37571', '4', 'b'Stir together soy sauce, chiles, and salt in a small bowl.''),
('37571', '5', 'b'Heat wok over high heat until a bead of water dropped onto cooking surface evaporates immediately.''),
('37571', '6', 'b'Add oil, swirling to coat wok, then add garlic and stir-fry until garlic begins to turn pale golden, about 5 seconds.''),
('37571', '7', 'b'Add peanuts, and stir-fry until all of mixture is golden, about 30 seconds.''),
('37571', '8', 'b'Add beans, and stir-fry until hot and well coated, about 2 minutes.''),
('37571', '9', 'b'Remove wok from heat, then stir in soy sauce mixture and shallot, stirring until shallot has wilted.''),
('37571', '10', 'b'Drizzle in lime juice and season with salt, then transfer to a bowl.''),
('37571', '11', 'b'Serve warm or at room temperature.''),
('37571', '12', 'b'*Available at Asian markets.''),
('37571', '13', 'b'**Available at kalustyans.com.''),
('37572', '1', 'b'In a large pot of boiling water, blanch long beans for 2 minutes until slightly tender. Allow to cool.''),
('37572', '2', 'b'In a large skillet over medium-high heat, add butter.''),
('37572', '3', 'b'Add scallions, ginger and garlic.''),
('37572', '4', 'b'Mix together.''),
('37572', '5', 'b'Add red pepper flakes and long beans. Allow to cook for a few minutes. Stir in chicken stock, honey and sesame oil. Season with salt and pepper, to taste, and add sesame seeds, if desired.''),
('37572', '6', 'b'Mix together.''),
('37584', '1', 'b'Bring water to boil in medium saucepan.''),
('37584', '2', 'b'Add asparagus. cook 3 min. or until crisp-tender.''),
('37584', '3', 'b'Drain. immediately immerse asparagus in ice water.  Cool completely. drain.''),
('37584', '4', 'b'Place in large bowl.''),
('37584', '5', 'b'Add remaining ingredients. toss lightly.''),
('37584', '6', 'b'Serve immediately.  Or, cover and refrigerate until ready to serve.''),
('37591', '1', 'b'Bring 1-inch of water to a boil, add salt then green beans, cover and cook 2 minutes, then add asparagus and cook 3 minutes more. If using pencil asparagus, blanch for 1 to 2 minutes.''),
('37591', '2', 'b'Drain well and cold shock vegetables in ice water to stop cooking process.''),
('37591', '3', 'b'Drain the vegetables on clean kitchen towels to dry completely. Thinly slice the green beans lengthwise on an angle. pile them together and run your knife through them cutting them into 2-inch pieces. Halve the asparagus lengthwise if thicker, leave in spindles if thin, then cut the spears into 2-inch pieces on an angle.''),
('37591', '4', 'b'Combine the beans, asparagus, 1/2 cup of parsley and onion in a shallow bowl.''),
('37591', '5', 'b'Combine the lemon zest and juice, remaining 1/2 cup of parsley and herbs in a food processor with cheese. Turn processor on and stream in extra-virgin olive oil. Season the dressing with salt and pepper and pour over the salad. Season the sliced tomatoes with salt and garnish salad with them.''),
('37593', '1', 'b'In a food processor, whirl garlic to finely chop.''),
('37593', '2', 'b'Add butter, mustard, parsley, lemon juice, kosher salt, and pepper. whirl until well blended.''),
('37593', '3', 'b'Transfer to a bowl.''),
('37593', '4', 'b'Meanwhile, boil a quarter of beans at a time in a large pot of water until barely tender, about 3 minutes. Using tongs, immediately transfer beans to ice water and let cool, then transfer to a colander to drain.''),
('37593', '5', 'b'Preheat broiler with 1 rack 5 to 6 in. from heat and another rack below it. Blot beans dry, then arrange lengthwise in 2 rimmed baking pans. Dot beans in each pan with about a quarter of butter.''),
('37593', '6', 'b'Cook beans in oven 1 minute. Toss to coat with butter and switch positions of pans. Cook until top beans are blistered and speckled brown, 4 to 9 minutes.''),
('37593', '7', 'b'Remove top pan from oven, then broil second pan the same way.''),
('37593', '8', 'b'Transfer beans to a platter and sprinkle with coarse sea salt.''),
('37593', '9', 'b'Serve with remaining butter if you like.''),
('37593', '10', 'b'Make ahead: Prepare recipe through step 2. chill butter and beans airtight up to 1 day.''),
('37596', '1', 'b'Soak noodles in cold water to cover 30 minutes.''),
('37596', '2', 'b'While noodles soak, stir together all glaze ingredients in a small bowl. Stir together all sauce ingredients in another small bowl.''),
('37596', '3', 'b'Preheat oven to 450\xc2\xb0F with rack in middle.''),
('37596', '4', 'b'Blanch carrots in a small saucepan of boiling water 30 seconds, then transfer to a large bowl with a slotted spoon. Return water to a boil and cook beans until crisp-tender, about 2 minutes.''),
('37596', '5', 'b'Transfer to bowl with carrots.''),
('37596', '6', 'b'Bring a pasta pot of water to a boil.''),
('37596', '7', 'b'Meanwhile, put duck legs, skin sides up, on rack of a broiler pan, then pour 1 cup water into bottom of pan.''),
('37596', '8', 'b'Brush or spoon about half of glaze over skin side of duck. Roast duck until well browned, about 20 minutes.''),
('37596', '9', 'b'Turn on broiler.''),
('37596', '10', 'b'Brush duck with remaining glaze, then broil 3 to 4 inches from heat until skin is bubbling and lightly charred around edges, about 2 minutes more. Keep warm, covered.''),
('37596', '11', 'b'Drain noodles, then cook in boiling water 30 seconds. Reserve 1 cup cooking water and drain noodles again.''),
('37596', '12', 'b'Add hot noodles, sauce, and scallions to carrots and beans and toss with tongs until well coated with sauce, adding some of reserved cooking liquid to moisten if necessary''),
('37596', '13', 'b'Add hot noodles, sauce, and scallions to carrots and beans and toss with tongs until well coated with sauce, adding some of reserved cooking liquid to moisten if necessary'');