INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('8314', '407', 'Orland Park - 15260 S. LaGrange Road'),
('8314', '408', 'Park Ridge - 225 W. Touhy AveRiver Forest - 7245 Lake StSchaumburg - 750 N. Martingale Rd.Wheaton - 151 Rice Lake Square'),
('8314', '409', 'Willowbrook - 6300 S. Robert Kingery Highway'),
('8314', '410', 'Carmel - 14598 Clay Terrace Blvd.Eighty-Sixth St. - 1300 E. 86th St.Mishawaka - 4230 Grape Road'),
('8314', '411', 'Schererville - 199 US HWY 41Olathe - 14615 W. 119th Street119th St - 6621 West 119th Street91st and Metcalf - 7401 West 91st StWichita - 1423 N. Webb Rd. Suite 101Lexington - 161 Lexington Green Circle'),
('8314', '412', 'Louisville - 4944 Shelbyville Road'),
('8314', '413', 'Baton Rouge - 7529 Corporate Blvd'),
('8314', '414', 'Ambassador Caffery - 4247 Ambassador Caffery Parkway'),
('8314', '415', 'Mandeville - 3450 Highway 190Veterans - 3420 Veterans Memorial Blvd'),
('8314', '416', 'Arabella Station - 5600 Magazine Street'),
('8314', '417', 'Broad Street - 300 N Broad StAndover - 40 Railroad St.Arlington MA - 808 Massachusetts Avenue'),
('8314', '418', 'Bedford - 170 Great RdBellingham - 255 Hartford AveCharles River Plaza - 181 Cambridge StSouth End - 348 Harrison AveSymphony - 15 Westland AveBrighton - 15 Washington Street'),
('8314', '419', 'Brookline - 1028 Beacon Street'),
('8314', '420', 'Fresh Pond - 200 Alewife Brook Pkwy'),
('8314', '421', 'Prospect Street - 115 Prospect StRiver Street - 340 River StCharlestown - 51 Austin St.Dedham - 300 Legacy'),
('8314', '422', 'Place'),
('8314', '423', 'Framingham - 575 Worcester RdHadley - 327 Russell StHingham - 94 Derby Street'),
('8314', '424', 'Hyannis - 990 Iyannough Road'),
('8314', '425', 'Jamaica Plain - 413 Centre Street'),
('8314', '426', 'Lynnfield - 100 Market Street'),
('8314', '427', 'Medford - 2151 Mystic Valley Parkway'),
('8314', '428', 'Melrose - 880 Main Street'),
('8314', '429', 'Newton - 916 Walnut StNewtonville - 647 Washington Street'),
('8314', '430', 'Somerville - 45 Beacon Street'),
('8314', '431', 'South Weymouth - 35 Pleasant Street'),
('8314', '432', 'Swampscott - 331 Paradise RdWayland - 317 Boston Post RdWellesley - 442 Washington Street'),
('8314', '433', 'Westford - 160 Littleton Road'),
('8314', '434', 'Woburn - 400 Cambridge Rd.Annapolis - 200 Harker PIace'),
('8314', '435', 'Harbor East - 1001 Fleet Street'),
('8314', '436', 'Mt. Washington - 1330 Smith AveBethesda - 5269 River RdFriendship Heights - 4420 Willard Ave.Columbia - Maryland - 10275 Little Patuxent Pkwy'),
('8314', '437', 'Kentlands - 316 Kentlands Blvd'),
('8314', '438', 'Rockville - 11355 Woodglen Drive'),
('8314', '439', 'Silver Spring - 833 Wayne AvePortland - Maine - 2 Somerset StAnn Arbor - 3135 Washtenaw AveCranbrook - 990 W. Eisenhower Parkway'),
('8314', '440', 'Detroit - 115 Mack Ave.East Lansing - 2750 E. Grand River Ave.Rochester Hills - 2918 Walton Blvd'),
('8314', '441', 'Troy - 2880 West Maple RdWest Bloomfield - 7350 Orchard Lake Road'),
('8314', '442', 'Edina - 7401 France Ave SMaple Grove - 12201 Elm Creek Blvd NHennepin - 222 Hennepin Avenue'),
('8314', '443', 'Lake Calhoun - 3060 Excelsior Blvd'),
('8314', '444', 'Minnetonka - 1001 Plymouth Road'),
('8314', '445', 'St Paul - 1575 Selby Ave.Galleria - 1601 S. Brentwood Blvd'),
('8314', '446', 'Central West End - 4577 West Pine Blvd'),
('8314', '447', 'Town and Country - 1160 Town and Country Crossing'),
('8314', '448', 'Jackson - 4500 I-55 North Suite 99Asheville - 4 South Tunnel Rd.Greenlife Grocery Asheville - 70 Merrimon AveCary - 102B New Waverly'),
('8314', '449', 'Place'),
('8314', '450', 'Chapel Hill - 81 South Elliot Road'),
('8314', '451', 'Charlotte - 6610 Fairview Rd.Durham - 621 Broad Street'),
('8314', '452', 'Greensboro Friendly - 3202 West Friendly Avenue'),
('8314', '453', 'Lake Norman - 9129 Sam Furr Rd.North Raleigh - 8710 Six Forks RdRaleigh - 3540 Wade AveWilmington - 3804 Oleander Drive'),
('8314', '454', 'Winston-Salem - 41 Miller Street'),
('8314', '455', 'Lincoln - 6055 O Street'),
('8314', '456', 'Omaha - 10020 Regency Circle'),
('8314', '457', 'Bedford New Hampshire - 121 South River RdNashua - 255 Amherst Street'),
('8314', '458', 'Cherry Hill - 1558 North Kings Highway'),
('8314', '459', 'Clark - 1255 Raritan Road Unit 150Edgewater - 905 River Road'),
('8314', '460', 'Rose City - 222 Main StMarlboro - 113 Route 9 South'),
('8314', '461', 'Marlton - 940 Route 73 North'),
('8314', '462', 'Montclair - 701 Bloomfield AveMorristown - 110 Washington Street'),
('8314', '463', 'Paramus - 300 Bergen Town Center'),
('8314', '464', 'Princeton - 3495 US Route 1 South'),
('8314', '465', 'Middletown - 471 State Route 35 North'),
('8314', '466', 'Ridgewood - 44 Godwin AveMillburn - Union - 2245 Springfield Ave.Spring Lake Wall - 1933 State Road 35West Orange - 235 Prospect AveAcademy - 5815 Wyoming Blvd NEIndian School Plaza - 2103 Carlisle Boulevard NESanta Fe (Cerrillos) - 753 Cerrillos RdSanta Fe (St. Francis) - 1090 S. Saint Francis Drive'),
('8314', '467', 'Henderson - 100 S. Green Valley Pkwy'),
('8314', '468', 'Fort Apache - 8855 West Charleston Blvd.Las Vegas Blvd - 6689 Las Vegas Blvd.Tenaya - 7250 W. Lake Mead Blvd.Reno - 6139 S. Virginia Street'),
('8314', '469', 'Albany - 1425 Central AveThird and 3rd (Brooklyn) - 214 3rd Street'),
('8314', '470', 'Jericho - 429 North Broadway'),
('8314', '471', 'Lake Grove - Lake Grove Commons'),
('8314', '472', 'Manhasset - 2101 Northern Blvd'),
('8314', '473', 'Bowery - 95 East Houston StChelsea - 250 7th AveColumbus Circle - 10 Columbus Circle'),
('8314', '474', 'Midtown East (E 57th St) - 226 East 57th Street'),
('8314', '475', 'Tribeca - 270 Greenwich Street'),
('8314', '476', 'Union Square - 4 Union Square South'),
('8314', '477', 'Upper East Side - 1551 3rd AveUpper West Side - 808 Columbus Avenue'),
('8314', '478', 'Port Chester - 575 Boston Post Road'),
('8314', '479', 'White Plains - 110 Bloomingdale Road'),
('8314', '480', 'Yonkers - Westchester''s Ridge Hill'),
('8314', '481', 'Cincinnati - 2693 Edmondson Rd.Columbus - 3670 W. Dublin-Granville RdEaston - 4100 Easton Gateway Drive'),
('8314', '482', 'Dayton - 1050 Miamisburg Centerville Road'),
('8314', '483', 'Mason - 5805 Deerfield Boulevard'),
('8314', '484', 'Rocky River - 19607 Detroit Road'),
('8314', '485', 'Cedar Center - 13998 Cedar Rd.Upper Arlington - 1555 W. Lane AveChagrin - 27249 Chagrin Blvd'),
('8314', '486', 'Oklahoma City - 6001 N. Western Ave.Brookside - 1401 E. 41st St.Yale - 9136 South Yale Avenue'),
('8314', '487', 'Unionville - 3997 Highway 7Square One Mississauga - 155 Square One Drive'),
('8314', '488', 'Oakville - 301 Cornwall RdLansdowne Park - 951 Bank Street'),
('8314', '489', 'Yonge and Sheppard - 4771 Yonge Street'),
('8314', '490', 'Yorkville - 87 Avenue RdBend - 2610 Highway 20Tanasbourne - 19440 NW Cornell Rd.Fremont - Oregon - 3535 NE 15th Ave.Hollywood - 4301 NE Sandy Blvd.Laurelhurst - 2825 East Burnside St.Pearl District Portland - 1210 NW Couch StBridgeport - 7380 SW Bridgeport Rd.Greenway - 12220 SW Scholls Ferry Road'),
('8314', '491', 'Glen Mills - 475 Wilmington'),
('8314', '492', 'Jenkintown - 1575 The Fairway'),
('8314', '493', 'North Wales - 1210 Bethlehem Pike'),
('8314', '494', 'Callowhill - 2001 Pennsylvania Avenue'),
('8314', '495', 'South Street - 929 South Street'),
('8314', '496', 'Pittsburgh - 5880 Centre AvePlymouth Meeting - 500 W. Germantown Pike'),
('8314', '497', 'Devon - 821 W. Lancaster AveWexford - 10576 Perry Highway'),
('8314', '498', 'Wynnewood - 339 East Lancaster AveGarden City Center - 151 Sockanosset Cross Road'),
('8314', '499', 'Providence - 261 Waterman StUniversity - 601 N Main StColumbia - 702 Cross Hill Rd + Fort Jackson Blvd'),
('8314', '500', 'Greenville - 1140 Woodruff Road'),
('8314', '501', 'Hilton Head Island - 50 Shelter Cove Lane'),
('8314', '502', 'Charleston - 923 Houston Northcutt Blvd'),
('8314', '503', 'Chattanooga - 301 Manufacturers RdMcEwen - 1566 West McEwen Drive'),
('8314', '504', 'Germantown - 7825 U.S. Highway 72Knoxville - 6730 Papermill Drive'),
('8314', '505', 'Poplar Avenue - 5014 Poplar Avenue'),
('8314', '506', 'Green Hills - 4021 Hillsboro Pike'),
('8314', '507', 'Addison - 5100 Belt Line Road, Suite 1012Arlington TX - 801 East Lamar Blvd.Arbor Trails - 4301 W. William Cannon'),
('8314', '508', 'Domain - 11920 Domain Drive'),
('8314', '509', 'Gateway - 9607 Research Blvd.Lamar - 525 N Lamar Blvd.Bee Cave - 12601 Hill Country Blvd'),
('8314', '510', 'Colleyville - 4801 Colleyville Blvd'),
('8314', '511', 'Forest - 11700 Preston RdLakewood - 2118 Abrams Road'),
('8314', '512', 'Park Lane - 8190 Park Lane, Suite 351Uptown Dallas - 2510 McKinney AveFairview - The Village at Fairview'),
('8314', '513', 'Highland Park - 4100 Lomo Alto DrHighland Village - 4041 Waller Creek'),
('8314', '514', 'Bellaire - 4004 Bellaire Blvd'),
('8314', '515', 'Champions - 10133 Louetta Road'),
('8314', '516', 'Kirby - 2955 Kirby DrMontrose - 701 Waugh Drive'),
('8314', '517', 'Post Oak - 1700 Post Oak Blvd'),
('8314', '518', 'Voss - 1407 South Voss RdWestchase - 11041 Westheimer Rd.Wilcrest - 11145 Westheimer RdKaty - 6601 S. Fry Road'),
('8314', '519', 'Plano - 2201 Preston RdCityline - 1411 E. Renner Road'),
('8314', '520', 'Alamo Quarry - 255 E. Basse Rd, Ste. 130Vineyard - 18403 Blanco Road'),
('8314', '521', 'Sugar Land - 15900 Southwest Freeway'),
('8314', '522', 'The Woodlands - 1925 Hughes Landing Blvd.Giffnock - 124-134 Fenwick Road'),
('8314', '523', 'Cheltenham - Gallagher Retail Park'),
('8314', '524', 'Camden - 49 Parkway'),
('8314', '525', 'Clapham Junction - 305-311 Lavender Hill'),
('8314', '526', 'Fulham - 2-6 Fulham Broadway'),
('8314', '527', 'Kensington - 63-97 Kensington High Street'),
('8314', '528', 'Piccadilly Circus - 20 Glasshouse Street'),
('8314', '529', 'Richmond - 1-3 George Street'),
('8314', '530', 'Stoke Newington - 32-40 Stoke Newington Church StCottonwood Heights - 6930 S. Highland Drive'),
('8314', '531', 'South Valley - 11479 S. State Street, Unit BPark City - 1748 W Redstone Center Dr.Sugar House - 1131 E. Wilmington Ave.Trolley Square - 544 South 700 East'),
('8314', '532', 'Old Town - 1700 Duke StArlington VA - 2700 Wilson Blvd'),
('8314', '533', 'Ashburn - 19800 Belmont Chase Drive'),
('8314', '534', 'Charlottesville - 1797 Hydraulic Road'),
('8314', '535', 'Fair Lakes - 4501 Market Commons DrTysons - 7511 Leesburg Pike'),
('8314', '536', 'Short Pump - 11173 West Broad Street'),
('8314', '537', 'Newport News - 12080 Jefferson Ave.Reston - 11660 Plaza America DrSpringfield - 8402 Old Keene Mill RdVienna - 143 Maple Ave East'),
('8314', '538', 'Virginia Beach - 1800 Laskin Road'),
('8314', '539', 'Bellevue - 888 116th Ave NEBellingham Lakeway - 1030 Lakeway Drive'),
('8314', '540', 'Lynnwood - 2800 196th St. SWRedmond - 17991 NE Redmond WayInterbay - 2001 15th Avenue WRoosevelt Square - 1026 NE 64th Street'),
('8314', '541', 'South Lake Union - 2210 Westlake AveChambers Bay - 3515 Bridgeport Way West'),
('8314', '542', 'Mill Plain - 815 Southeast 160th Avenue'),
('8314', '543', 'Madison - 3313 University AveMilwaukee - 2305 N. Prospect AveWauwatosa - 11100 W. Burleigh Street'),
('8314', '544', 'Connect with UsNewsletter Subscription'),
('8314', '545', 'Enter your email address for recipes, news and tips.California Transparency in Supply Chains Act Disclosure (PDF)Copyright 2016 Whole Foods Market IP. L.P. | Terms of Use | Privacy Policy | Site Map | Site Information"Whole Foods Market" is a registered trademark of Whole Foods Market IP, L.P.Sign in with a social account{* login'),
('8314', '546', 'Widget *}Sign in with aWhole Foods Market account{* #user'),
('8314', '547', 'Information'),
('8314', '548', 'Form *}{* traditional'),
('8314', '549', 'SignIn_email'),
('8314', '550', 'Address *}{* traditional'),
('8314', '551', 'SignIn_password *}Forgot your password?{* traditional'),
('8314', '552', 'SignIn_sign'),
('8314', '553', 'InButton *}{* traditional'),
('8314', '554', 'SignIn_create'),
('8314', '555', 'Button *}{* /user'),
('8314', '556', 'Information'),
('8314', '557', 'Form *}Sign in with your social account'),
('8314', '558', 'Welcome back {* welcome'),
('8314', '559', 'Name *}!{* login'),
('8314', '560', 'Widget *}Use another account'),
('8314', '561', 'Sign in with your'),
('8314', '562', 'Whole Foods Market account'),
('8314', '563', 'Welcome back {* welcome'),
('8314', '564', 'Name *}!{* #user'),
('8314', '565', 'Information'),
('8314', '566', 'Form *}{* traditional'),
('8314', '567', 'SignIn_email'),
('8314', '568', 'Address *}{* traditional'),
('8314', '569', 'SignIn_password *}{* traditional'),
('8314', '570', 'SignIn_sign'),
('8314', '571', 'InButton *}{* /user'),
('8314', '572', 'Information'),
('8314', '573', 'Form *}Use another account'),
('8314', '574', 'Almost Done!Please confirm the information below before signing in.{* #social'),
('8314', '575', 'Registration'),
('8314', '576', 'Form *}{* social'),
('8314', '577', 'Registration_first'),
('8314', '578', 'Name *}{* social'),
('8314', '579', 'Registration_last'),
('8314', '580', 'Name *}{* social'),
('8314', '581', 'Registration_email'),
('8314', '582', 'Address *}{* social'),
('8314', '583', 'Registration_display'),
('8314', '584', 'Name *}{* social'),
('8314', '585', 'Registration_postal'),
('8314', '586', 'Code *}By clicking "Sign in", you confirm that you accept our terms of service and have read and understand privacy policy.{* back'),
('8314', '587', 'Button *}{* social'),
('8314', '588', 'Registration_sign'),
('8314', '589', 'InButton *}{* /social'),
('8314', '590', 'Registration'),
('8314', '591', 'Form *}Thank you for registering!We have sent a confirmation email to {* email'),
('8314', '592', 'Address'),
('8314', '593', 'Data *}. Please check your email and click on the link to activate your account.Close'),
('8314', '594', 'Almost Done!Please confirm the information below before signing in. Already have an account? Sign In.{* #registration'),
('8314', '595', 'Form *}{* traditional'),
('8314', '596', 'Registration_first'),
('8314', '597', 'Name *}{* traditional'),
('8314', '598', 'Registration_last'),
('8314', '599', 'Name *}{* traditional'),
('8314', '600', 'Registration_email'),
('8314', '601', 'Address *}{* traditional'),
('8314', '602', 'Registration_password *}{* traditional'),
('8314', '603', 'Registration_password'),
('8314', '604', 'Confirm *}{* traditional'),
('8314', '605', 'Registration_display'),
('8314', '606', 'Name *}{* traditional'),
('8314', '607', 'Registration_postal'),
('8314', '608', 'Code *}{* captcha *}By clicking "Create Account", you confirm that you accept our terms of service and have read and understand privacy policy.{* back'),
('8314', '609', 'Button *}{* create'),
('8314', '610', 'Account'),
('8314', '611', 'Button *}{* /registration'),
('8314', '612', 'Form *}Create a new password'),
('8314', '613', 'We''ll email you a link to create a new password.{* #forgot'),
('8314', '614', 'Password'),
('8314', '615', 'Form *}{* traditional'),
('8314', '616', 'SignIn_email'),
('8314', '617', 'Address *}{* back'),
('8314', '618', 'Button *}{* forgot'),
('8314', '619', 'Password_send'),
('8314', '620', 'Button *}{* /forgot'),
('8314', '621', 'Password'),
('8314', '622', 'Form *}Create a new password'),
('8314', '623', 'We''ve sent an email with instructions to create a new password. Your existing password has not been changed.Close{* merge'),
('8314', '624', 'Accounts *}Sign in to complete account merge{* #trad'),
('8314', '625', 'Authenticate'),
('8314', '626', 'Merge'),
('8314', '627', 'Form *}{* traditional'),
('8314', '628', 'SignIn_email'),
('8314', '629', 'Address *}{* merge'),
('8314', '630', 'Password *}{* back'),
('8314', '631', 'Button *}{* traditional'),
('8314', '632', 'SignIn_sign'),
('8314', '633', 'InButton *}{* /trad'),
('8314', '634', 'Authenticate'),
('8314', '635', 'Merge'),
('8314', '636', 'Form *}'),
('8315', '1', 'Peel the skin and white membrane off the grapefruit and separate the pieces. Reserve three grapefruit slices for the vinaigrette and squeeze the juice; set aside. Chop up remaining grapefruit for the salad.In a medium bowl whisk olive oil, squeezed grapefruit juice (from 3 slices of grapefruit), champagne vinegar, chopped shallots, salt and pepper.Season scallops with salt and pepper.'),
('8315', '2', 'Heat a large pan on a high heat. When the pan is hot, add oil and place scallops in the pan. Sear without touching them for a few minutes until the bottom forms a nice caramel colored crust. Turn and cook about another minute while their centers are still slightly translucent (you can check this by viewing them from the side). Be careful not to overcook.'),
('8315', '3', 'Remove from the pan. Divide the baby greens evenly between four plates. Arrange grapefruit on the plate and top with scallops; drizzle with vinaigrette.Print This3 SP 6 PP Lenten Friendly Recipes Lunch Main Dishes Recipes Salad Seafood Recipes Springposted March 15, 2011 by Gina28 Comments'),
('8316', '1', 'NOTE: PIZZA INGREDIENTS IN THIS RECIPE ARE FOR 1/3  OF THE PIZZA DOUGH RECIPE. USE LEFTOVER DOUGH TO MAKE OTHER KINDS OF PIZZA!Sprinkle yeast over 1 1/2 cups warm (not lukewarm) water.In a mixer, combine flour and salt. With the mixer running on low speed (with paddle attachment), drizzle in olive oil until combined with flour. Next, pour in yeast/water mixture and mix until just combined.Coat a separate mixing bowl with a light drizzle of olive oil, and form the dough into a ball. Toss to coat dough in olive oil, then cover the bowl tightly with plastic wrap and allow to rise for at least an hour. Use right away or store in the fridge until you need it. ***It’s best to make the dough at least 24 hours in advance, and 3 or 4 days is even better.Preheat oven to 500 degrees.'),
('8316', '2', 'Roll out 1/3 of the pizza dough as thinly as possible.'),
('8316', '3', 'Place on a large baking sheet.'),
('8316', '4', 'Drizzle lightly with olive oil and sprinkle lightly with kosher salt.'),
('8316', '5', 'Spread fig spread (or jam) all over the surface of the dough. Sprinkle lightly with salt. Lay sliced of mozzarella all over the surface. Sprinkle lightly with salt and freshly ground pepper.'),
('8316', '6', 'Bake for 12 to 15 minutes, or until crust is golden and cheese is bubbly.'),
('8316', '7', 'Remove from oven and immediately lay prosciutto over hot pizza. Just before serving, sprinkle on arugula and Parmesan shavings.'),
('8316', '8', 'Cut into wedges or squares and serve immediately!'),
('8318', '1', 'Sprinkle chicken with salt and pepper. Warm 1 Tbsp. olive oil and butter in a large skillet over medium-high heat until butter is foaming.'),
('8318', '2', 'Add chicken and cook, turning once, until golden on both sides, about 10 minutes total.'),
('8318', '3', 'Transfer to a plate.'),
('8318', '4', 'While chicken is cooking, whisk remaining 3 Tbsp. oil, vinegar, mustard, 1/2 tsp. salt and pepper in a small bowl.'),
('8318', '5', 'Slice chicken thinly across the grain.'),
('8318', '6', 'Place arugula, pears, chicken and any accumulated juices from plate in a mixing bowl. Top with dressing and toss gently with hands to coat. Divide among four dinner plates. Sprinkle each portion with walnuts and cranberries, and serve immediately.'),
('8319', '1', 'Whisk vinegar and shallot in medium bowl. Gradually whisk in oil. Season dressing to taste with salt and pepper.'),
('8319', '2', 'Place arugula, sliced fennel, and apricots in large bowl.'),
('8319', '3', 'Whisk chopped fennel fronds into dressing.'),
('8319', '4', 'Drizzle dressing over salad and toss to coat evenly. Season to taste with salt and pepper.'),
('8319', '5', 'Transfer salad to large serving bowl. Sprinkle pistachios over and serve.'),
('8325', '1', 'Preheat the oven to 450F and preheat a rimless baking sheet.'),
('8325', '2', 'Roll out the dough into a 12-inch circle and slide onto the baking sheet.'),
('8325', '3', 'Bake for 7-10 minutes.'),
('8325', '4', 'Remove crust from oven and flip over.'),
('8325', '5', 'Spread the tomato sauce evenly on top. Scatter chicken pieces over sauce and sprinkle with the mozzarella. Return to the oven to bake another 7-10 minutes until cheese is melted and pizza is crispy and brown.'),
('8325', '6', 'Remove pizza from the oven and top with the fresh arugula and a sprinkling of parmesan.Enjoy!'),
('8327', '1', 'In a medium bowl, whisk olive oil and balsamic.'),
('8327', '2', 'Add tomatoes, basil and onions; season with salt and pepper. and toss. Set aside at least 10 minutes so the juices combine.Preheat oven to 45'),
('8327', '3', 'Place a large baking pan in the oven to get hot.'),
('8327', '4', 'Combine breadcrumbs and grated cheese in one bowl. In another bowl combine olive oil, lemon juice, and pepper.Lightly pound chicken breasts into cutlets, you should have'),
('8327', '5', 'Wash and dry cutlets well with paper towels; season with salt and pepper.Dip cutlets into lemon/oil mixture, then into breadcrumbs, pressing firmly to adhere.'),
('8327', '6', 'Remove the baking pan from the oven and spray with cooking spray.'),
('8327', '7', 'Place the chicken on the baking sheets and spray with olive oil spray on top.'),
('8327', '8', 'Bake chicken, turning once halfway through for about 15 minutes total, or until chicken is golden.'),
('8327', '9', 'Remove from the oven and top with arugula and tomato salad on top.Print This6 PP 6 SP Chicken Recipes Main Dishes Recipes Under $10posted August 22, 2012 by Gina74 Comments'),
('8329', '1', 'Mix all ingredients in medium bowl. Season to taste with salt and pepper.'),
('8330', '1', 'Place arugula and raspberries in a large bowl'),
('8330', '2', 'To make vinaigrette, place vinegar in a vitamix'),
('8330', '3', 'Turn machine on to medium speed and drizzle in olive oil'),
('8330', '4', 'Blend in raspberry fruit spread'),
('8330', '5', 'Toss desired amount of dressing over arugula and raspberries'),
('8330', '6', 'Refrigerate remaining dressing in a mason jar'),
('8330', '7', 'Serve'),
('8335', '1', 'NOTE: PIZZA INGREDIENTS IN THIS RECIPE ARE FOR 1/3  OF THE PIZZA DOUGH RECIPE. USE LEFTOVER DOUGH TO MAKE OTHER KINDS OF PIZZA!Sprinkle yeast over 1 1/2 cups warm (not lukewarm) water.In a mixer, combine flour and salt. With the mixer running on low speed (with paddle attachment), drizzle in olive oil until combined with flour. Next, pour in yeast/water mixture and mix until just combined.Coat a separate mixing bowl with a light drizzle of olive oil, and form the dough into a ball. Toss to coat dough in olive oil, then cover the bowl tightly with plastic wrap and allow to rise for at least an hour. Use right away or store in the fridge until you need it. ***Its best to make the dough at least 24 hours in advance, and 3 or 4 days is even better.Preheat oven to 500 degrees.'),
('8335', '2', 'Roll out 1/3 of the pizza dough as thinly as possible.'),
('8335', '3', 'Place on a large baking sheet.'),
('8335', '4', 'Drizzle lightly with olive oil and sprinkle lightly with kosher salt.'),
('8335', '5', 'Spread fig spread (or jam) all over the surface of the dough. Sprinkle lightly with salt. Lay sliced of mozzarella all over the surface. Sprinkle lightly with salt and freshly ground pepper.'),
('8335', '6', 'Bake for 12 to 15 minutes, or until crust is golden and cheese is bubbly.'),
('8335', '7', 'Remove from oven and immediately lay prosciutto over hot pizza. Just before serving, sprinkle on arugula and Parmesan shavings.'),
('8335', '8', 'Cut into wedges or squares and serve immediately!'),
('8338', '1', 'In a salad bowl, whisk together olive oil, lemon juice, 1 tsp. thyme leaves, the mustard, 1/4 tsp. salt, and 1/4 tsp. pepper.'),
('8338', '2', 'Add arugula and gently toss until leaves are coated with dressing.'),
('8338', '3', 'Add berries and gently toss. Divide among 4 salad plates. Crumble 1/2 oz. cheese on each salad. Sprinkle with remaining thyme and salt and pepper to taste.'),
('8339', '1', 'Start by preparing your pasta dough ahead of time. If using a food processor, place the flour and salt in the bowl. Pulse and add the beaten eggs, then mix well.'),
('8339', '2', 'Add 1 Tbsp water at a time, until the dough forms a ball.'),
('8339', '3', 'Remove and work with the palm of your hand until it is elastic (a few mns). Wrap in plastic and let rest for 30 mns to 1 hour minimum.Blanch the spinach in salted boiling water for 3 mns. Rinse under cold water and squeeze out the excess water. Keep.'),
('8339', '4', 'Mix together the ricotta, sherry vinegar, 1 tsp pistachio oil, tarragon, shallots and season with salt and pepper. Keep.To prepare the lasagna, use a pasta machine if you have one to make thin lasagna sheets (or roll by hand). Make sure to cover the dough with a towel while working as it dries quickly. Cook the precut rectangular sheets of pasta in boiling salted water for 3 to 4 mns or so. Melt some butter with some water and once cooked, place the lasagna sheets in this sauce to wait, to prevent them from sticking.To assemble the lasagna, place individual pasta sheets in a dish and spread some ricotta.'),
('8339', '5', 'Add spinach. Repeat once and finish with a sheet of lasagna. Cook in a preheated oven at 400 F for about 10 mns.'),
('8339', '6', 'Serve with fresh arugula and roasted nuts and some nutty vinaigrette (made of 1 Tbsp sherry vinegar and 2 Tbsp of nutty oil).'),
('8340', '1', 'Over med-high heat, cook bacon until it just starts to crisp on the edges.'),
('8340', '2', 'Remove from pan & set aside.'),
('8340', '3', 'Pour off most of the bacon fat and reserve it for later. Leave a small skim of rendered fat at the bottom of the pan.'),
('8340', '4', 'Add sliced shallots to the saute pan over medium heat and quickly cook shallots until soft.'),
('8340', '5', 'Remove pan from heat and add the vinegar to shallot mixture.'),
('8340', '6', 'Whisk well. Then pour aside in a small bowl and add mustard, combine well.'),
('8340', '7', 'Pour about 3-4 tablespoons of the bacon fat back in to the saute pan and heat over medium heat. When fat is hot, carefully and vigorously whisk in the shallot mixture. Season with salt and pepper.Toss together arugula or frisee, strips of bacon, blue cheese and figs.'),
('8340', '8', 'Drizzle with bacon vinaigrette and toss into salad.'),
('8341', '1', 'Finely grated peel from 1 lemon'),
('8341', '2', 'Preheat oven to 400°F. Fill small bowlwith water.'),
('8341', '3', 'Place bread halves, cut sideup, on baking sheet; brush bread with 2tablespoons olive oil. Toast bread in ovenuntil crisp and light golden around edges,about 15 minutes.'),
('8341', '4', 'Remove from oven.Lightly brush each bread half with water(do not soak). Rub cut sides of bread halveswith cut sides of garlic halves.'),
('8341', '5', 'Place 2 bread halves, cut side up, oneach of 6 plates.'),
('8341', '6', 'Drizzle each bread halflightly with olive oil. Top each half with1 burrata wedge; sprinkle with salt andfreshly ground black pepper and drizzlelightly with olive oil. Toss arugula with 1tablespoon olive oil in small bowl; sprinklewith salt and freshly ground black pepper.Mound arugula salad atop burrata oneach bread half; sprinkle each with gratedlemon peel and serve.'),
('8341', '7', '* A soft, fresh Italian cheese made frommozzarella and cream; available at somesupermarkets and at specialty foodsstores and Italian markets.'),
('8341', '8', 'Bon Appétit'),
('8342', '1', 'Lay lahvosh on a work surface with longest sides parallel to surface edge and smooth, lighter sides up.'),
('8342', '2', 'Spread each with 1/2 cup pesto. On each sheet, place half of cheese slices on two-thirds of pesto, leaving 2 in. uncovered at top edge for sealing. Cover cheese with arugula. Starting with bottom edge, roll up each lahvosh and press to seal edge, securing with toothpicks if needed.'),
('8342', '3', 'Slice each roll into 1-in. pieces, remove toothpicks if used, and arrange on a platter. Makes about 32 pieces.'),
('8342', '4', '*Substitute 4 flour tortillas (10 in. wide).'),
('8343', '1', 'Fry the bacon in a large skillet over medium heat until crisp, about 8 minutes.Meanwhile, in a large bowl, combine the arugula, dates, almonds, and Parmesan; set aside.'),
('8343', '2', 'Transfer the bacon to a paper towel-lined plate. Carefully pour 2 tablespoons of the warm drippings into a small bowl.'),
('8343', '3', 'Add the vinegar, mustard, salt, pepper, and oil and whisk until combined.'),
('8343', '4', 'Drizzle the warm vinaigrette over the salad and toss. Divide among plates and top with the bacon, crumbling it if desired.'),
('8344', '1', 'Prepare the pizza dough 6 to 18 hours in advance and let it rest. Feel free to substitute white whole wheat flour or whole wheat pastry flour for the whole wheat flour and/or whole wheat pastry flour for the all-purpose flour.Preheat the oven to 500 degrees. Grease a 12-inch cast iron skillet with olive oil. Lightly dust your hands with flour and fold the dough over a few times, then divide the dough in half.'),
('8344', '2', 'Place one half of the dough in the skillet and gently spread it out over the surface of the pan and up the sides. Try not to break the dough, but spread it out as evenly and thinly as possible.'),
('8344', '3', 'Brush on some olive oil.Top the dough with half of your sauce, spread evenly. Sprinkle chopped preserved lemon or lemon salt around the edges, if using. Top with half of your grated mozzarella.'),
('8344', '4', 'Bake for 10 minutes or so, until the cheese is bubbling on top.'),
('8344', '5', 'Remove from the oven and transfer to a cutting board using a big spatula. Give it a few minutes to rest, then top with arugula, fresh parmesan shavings, and big sprinkle of lemon juice. Slice and serve with red pepper flakes and black pepper on the side.'),
('8345', '1', 'Toast 2 slices of bread.'),
('8345', '2', 'Spread mustard on one slice, mayo on the other.'),
('8345', '3', 'To the slice with mustard, add the turkey breast, then the cranberry sauce, then the arugula leaves.'),
('8345', '4', 'Top with the other slice of bread.'),
('8345', '5', 'Cut in half.'),
('8347', '1', 'In a small blender, combine basil, olive oil, balsamic, a pinch of salt and fresh cracked pepper. Blend until smooth.'),
('8349', '1', 'Preheat oven to 325 degrees.'),
('8349', '2', 'Prepare 13 inch x 9 inch casserole dish with butter.'),
('8349', '3', 'Mix together gorgonzola and 1/4 cup milk.'),
('8349', '4', 'Add ricotta, heavy cream, 1/2 cup Pecorino, salt, pepper and nutmeg.'),
('8349', '5', 'Chop the arugula thinly.  Reserve ~12 leaves for garnish.'),
('8349', '6', 'Saute arugula in 2 T butter just until wilted.'),
('8349', '7', 'Add minced garlic and saute for about one minute.'),
('8349', '8', 'Add arugula mixture to cheese mixture.'),
('8349', '9', 'Add 1/4 cups milk to buttered casserole dish.  Cover bottom of casserole with 3 homemade or prepared lasagna noodles.  Top with a quarter of the cheese and arugula mixture.'),
('8349', '10', 'Continue layering, ending with cheese and arugula mixture.'),
('8349', '11', 'Top with remaining 1 cup Pecorino, pine nuts, arugula leaved and sauteed shallots.'),
('8349', '12', 'Cover with foil and bake for 25 minutes.'),
('8349', '13', 'Remove foil and cook for an additional 15 minutes.  When you remove foil, if corners look dry, add a little milk to each corner.'),
('8349', '14', 'Let lasagna rest for about 10 minutes before slicing.'),
('8350', '1', 'Preheat the oven to 35'),
('8350', '2', 'Preheat a cast-iron skillet. In a bowl, mix the garlic, rosemary, sage, 1 1/2 teaspoons salt and 1/2 teaspoon of pepper. Rub the mixture all over the steak.'),
('8350', '3', 'Add 1 tablespoon of oil to the skillet.'),
('8350', '4', 'Add the steak and cook over moderate heat until browned all over. Stand the steak on its side and roast it in the oven for 20 minutes, or until an instant-read thermometer inserted in the center registers 13'),
('8350', '5', 'Transfer the steak to a cutting board and let rest for 10 minutes, then slice.'),
('8350', '6', 'Spread the arugula on a platter and top with the steak.'),
('8350', '7', 'Drizzle with oil and lemon juice and top with the cheese shavings.'),
('8355', '1', 'For the hash:Preheat oven to 400 degrees.'),
('8358', '1', 'Spread the honey mustard evenly over the bread. Top with the turkey, nectarine slices, and Brie. Season with 1/4 teaspoon salt and 1/4 teaspoon pepper. In a large bowl, toss the arugula, onion, oil, and 1/2 teaspoon salt.'),
('8359', '1', 'Preheat oven to 375F.Toss the pecans with a little canola oil and sea salt, and roast until fragrant, about 7 to 10 minutes.Meanwhile, peel and seed the squash and cut into 1/2-inch cubes. Toss with a little canola oil on two baking sheets (do not crowd) and sprinkle with more of the sea salt. When the pecans are done, remove from the oven, raise the temperature to 425F and roast the squash until it''s soft and the edges are deep brown.While the squash roasts, cut the bacon into 1-inch pieces and fry it up in a large skillet. You may need to do this in two batches, pouring off the fat (be sure to save it!) in-between.'),
('8359', '2', 'Drain the bacon on paper towels or on a brown paper bag.Keep the pan hot and make sure there are about 6 tablespoons of bacon fat in the pan.'),
('8359', '3', 'Add the shallots and saute over medium heat until they soften. Turn off the heat and add the vinegar. Swirl to combine.'),
('8359', '4', 'Add a few turns of the pepper mill''s worth of fresh black pepper.The salad can be served now, with the ingredients still warm, or at room temperature. To assemble: In a large bowl, toss the dressing with the squash and bacon.'),
('8359', '5', 'Add several large handfuls of the arugula. Strip about three or four sprigs of thyme leaves into the bowl and add the pecans (which should be broken into pieces if they''re not already.) Toss gently. Dot with the goat cheese (you may not need all of it) and serve.'),
('8360', '1', 'In a small bowl, whisk together oil and lemon juice to make dressing.'),
('8360', '2', 'Add salt and pepper to taste. Set aside.'),
('8360', '3', 'In a large salad bowl, combine arugula, avocado, tomato, and hearts of palm. Toss with dressing. Top with pine nuts and cheese.'),
('8363', '1', 'Heat 1 tbsp. oil in a large, wide pot over medium heat. Cook onion, stirring often, until translucent, about 7 minutes.'),
('8363', '2', 'Add broth and heat until simmering. Sprinkle in chickpea flour and yeast, whisking until smooth.'),
('8363', '3', 'Transfer mixture to a food processor. Pure until as smooth as baby food. Stir in thyme, fava leaves, and salt.'),
('8363', '4', 'Pour into a greased 9- by 13-in. baking dish. Lay a sheet of plastic wrap on top and use your hand to level mixture. Chill until cold, at least 1 1/2 hours and up to 2 days.'),
('8363', '5', 'Invert cake onto a cutting board.'),
('8363', '6', 'Cut into 12 squares, then cut each square again diagonally to make 24 triangles.'),
('8363', '7', 'Heat 1 tbsp. oil in a large nonstick frying pan over medium-high heat. Working in batches, brown triangles, turning once, 8 minutes total; add oil as needed. Set on 6 plates.'),
('8363', '8', 'Make salad: Toss arugula, fennel fronds, parsley, and half the vinaigrette in a bowl. Spoon salad over chickpea triangles and serve remaining dressing on the side.'),
('8363', '9', '*Find chickpea flour and nutritional yeast at natural-food stores or well-stocked grocery stores. Find fava leaves at farmers'' markets; if using spinach leaves instead, increase chickpea flour to 2 cups.'),
('8365', '1', 'Wash peaches, rubbing to remove fuzz.'),
('8365', '2', 'Cut in half; remove pits. Thinly slice peaches.'),
('8365', '3', 'Place peach slices in large bowl.'),
('8365', '4', 'Add 1/2 tablespoon lemon juice; toss.'),
('8365', '5', 'Whisk 1 1/2 tablespoons lemon juice and olive oil in small bowl.'),
('8365', '6', 'Whisk in cream, then chives. Season with salt and pepper.'),
('8365', '7', 'Add arugula to bowl with peaches.'),
('8365', '8', 'Add dressing and toss. Season with more salt and pepper, if desired, and serve.'),
('8368', '1', 'Two hours before grilling, remove the provolone cheese from the refrigerator and let sit at room temperature.'),
('8368', '2', 'Letting the cheese sit out in the air will allow the cheese to form a crust and make it easier to grill.'),
('8368', '3', 'Preheat the grill to medium-high direct heat, leaving some space for indirect cooking.'),
('8368', '4', 'Grill the chorizo, turning occasionally, until nicely charred and hot inside, about15 minutes. Chop roughly and set aside.'),
('8368', '5', 'Heat a griddle over the direct heat. Lightly brush the top of the cheese with canola oil and season with salt and pepper.'),
('8368', '6', 'Place on the griddle, seasoned-side down, and cook until the cheese is dark golden brown and crusty, about 5 minutes.'),
('8368', '7', 'Brush the top lightly with oil, season again, carefully flip over and move the griddle to the indirect heat. Continue cooking until the bottom begins to turn light brown and the cheese is melty, covering if need be.'),
('8368', '8', 'Remove to a plate and sprinkle with the oregano and red pepper flakes.'),
('8368', '9', 'Brush the bread on each side with some olive oil and sprinkle with salt and pepper. Grill over direct heat for about 1 minute per side-the bread should be crisp and a bit charred outside, but chewy inside.'),
('8368', '10', 'Heat a griddle or cast-iron skillet over medium-high heat.'),
('8368', '11', 'Add the butter and melt. Crack the eggs into the skillet, sprinkle with salt and pepper and cover with another pan. Cook until the whites are set and the yolks still runny, about 3 minutes.'),
('8368', '12', 'While the eggs cook, whisk together the vinegar and mustard in a large bowl and season with salt and pepper. Slowly whisk in 1/2 cup olive oil until emulsified. Taste and whisk in the honey if desired.'),
('8368', '13', 'Put the rocket, tomatoes and onions in a large bowl and season with salt and pepper.'),
('8368', '14', 'Drizzle some vinaigrette around the sides of the bowl and gently toss to coat.'),
('8368', '15', 'To serve: Smear some cheese on the toasted bread. Top with an egg, chopped chorizo, a drizzle of olive oil and parsley leaves.'),
('8368', '16', 'Serve each crostini with some rocket salad.'),
('8372', '1', 'Bake for 10 minutes.'),
('8372', '2', 'Remove from the oven and divide most of the broccoli and zucchini between the two pizzas. Sprinkle with most of the remaining Parm and return to the oven for 10 minutes.'),
('8372', '3', 'Remove once more, top each pizza with the arugula, sprinkle with salt, and return to the oven for 5 minutes, until the arugula has just wilted. Top with the remaining Parm and serve.'),
('8373', '1', 'Preheat oven to 42'),
('8373', '2', 'Lay out a sheet of parchment paper, unroll pie dough on top, and roll into a 13-in. round. Set on a rimless baking sheet.'),
('8373', '3', 'Leaving a 2-in. border, scatter cheese, chorizo, potatoes, and peppers over dough.'),
('8373', '4', 'Fold dough edges over filling, then bake until crust is golden and cheese is melted, 20 to 25 minutes.'),
('8373', '5', 'Toss arugula with vinegar and oil in a small bowl until coated. Scatter over galette.'),
('8373', '6', 'Cut into wedges and serve immediately.'),
('8373', '7', '*We especially like Pillsbury pie dough. Look for Barinaga Ranch Baserri, a California farmstead cheese sold at specialty shops, or use manchego.'),
('8374', '1', 'Heat a tablespoon of olive oil in a stick-free frying pan on medium heat. When the oil is hot, add the shallot slices and lightly sauté them until translucent. '),
('8374', '2', 'Remove shallots from pan and set aside.'),
('8374', '3', 'Sauté chicken pieces: '),
('8374', '4', 'Heat another tablespoon of olive oil in the pan and when the oil is hot, add the chicken breast pieces. Cook, stirring occasionally, until just cooked through, 5 to 10 minutes. Sprinkle some salt on the chicken while you are cooking it.'),
('8374', '5', 'Remove from pan and chill.'),
('8374', '6', 'Assemble salad: When chicken has cooled, toss together in a serving bowl the shallots, chicken, sliced green apple, arugula, toasted walnuts and goat cheese.'),
('8374', '7', 'Dress with olive oil, lemon juice, salt and pepper to taste.'),
('8375', '1', 'Whisk together tangerine juice, tangerine zest, sea salt, and olive oil.'),
('8375', '2', 'Rinse and dry arugula and red butterhead lettuce. Put in a serving bowl and toss gently but thoroughly with only enough dressing to coat.'),
('8375', '3', 'Add tangerines and croutons; toss just to mix. Divide salad among plates (or serve on a platter if you like).'),
('8375', '4', 'Add a quartered hard-cooked egg to each plate and drizzle eggs with a little more dressing.'),
('8382', '1', 'Using a mandoline or a knife, slice the zucchini lengthwise into 1/8-inch strips.'),
('8382', '2', 'Transfer to a large bowl.'),
('8382', '3', 'Drizzle with 2 Tbs. of the olive oil, season with salt and pepper and toss to coat evenly.Preheat a grill pan over medium-high heat. Working in batches, arrange the zucchini strips on the pan and cook for 1 to 2 minutes. Turn the zucchini over and cook until tender but not too soft, 1 to 2 minutes more.'),
('8382', '4', 'Transfer to a plate and cover loosely with aluminum foil.Bring a large saucepan three-fourths full of water to a boil over high heat. Break the lasagna noodles into large, uneven pieces.'),
('8382', '5', 'Add the 1 Tbs. salt and the noodles to the boiling water and cook according to the package instructions.Meanwhile, in a small saucepan over medium heat, warm the tomato pasta sauce.'),
('8382', '6', 'Drain the pasta and transfer to a large bowl.'),
('8382', '7', 'Drizzle with the remaining 2 Tbs. oil and toss to coat evenly.'),
('8382', '8', 'Add the zucchini, arugula and 1/4 cup of the cheese and gently toss together, being careful not to tear the zucchini strips.'),
('8382', '9', 'Transfer to individual pasta bowls, drizzle the tomato sauce over and around the pasta and sprinkle with the remaining 1/4 cup cheese.'),
('8382', '10', 'Serve immediately.'),
('8382', '11', 'Serves 4.'),
('8383', '1', 'Heat oil in heavylarge skillet over medium-high heat.'),
('8383', '2', 'Addonions. Sauté until golden, about 18 minutes.'),
('8383', '3', 'Remove from heat. Sprinkle with vinegar;stir to blend. Season with salt and pepper.'),
('8385', '1', 'Reduce heat to medium, and add remaining tablespoon oil to skillet.'),
('8385', '2', 'Add garlic, and cook for 15 seconds.'),
('8385', '3', 'Add spinach, arugula, red-pepper flakes, and remaining 1/2 teaspoon salt and 1/8 teaspoon pepper. Cook, tossing greens often, until just wilted, about 2 minutes.'),
('8385', '4', 'Transfer to a platter, top with scallops, and serve immediately.'),
('8388', '1', 'On a lightly floured work surface, roll out dough to 1/4 inch thick.'),
('8388', '2', 'Cut out a 12-inch circle. Fit circle into cake ring, pressing dough onto baking sheet and up sides of ring; trim dough flush with top edge of ring. Prick bottom all over with a fork. Freeze until firm, about 30 minutes. Preheat oven to 400 degrees.'),
('8390', '1', 'Preheat oven to 425 degrees. On a rimmed baking sheet, toss breadcrumbs and oil until well combined; spread on sheet. Cook, tossing once, until golden brown, 6 to 8 minutes.'),
('8390', '2', 'Transfer to a medium bowl.'),
('8390', '3', 'Place flour and eggs in separate bowls; season with salt and pepper.'),
('8390', '4', 'Place a rack on another rimmed baking sheet.'),
('8391', '1', 'In a 5- to 6-quart pan over high heat, bring 4 quarts water to a boil; add beans and cook just until barely tender to bite, about 1 minute. With a skimmer or slotted spoon, remove from water and transfer to a colander; rinse under cold running water until cool.'),
('8391', '2', 'Bring water back to a boil.'),
('8391', '3', 'Add farfalle and cook until tender to bite, 14 to 16 minutes.'),
('8391', '4', 'Drain.'),
('8391', '5', 'In a large bowl, mix pasta, beans, and 3/4 cup pesto. If more sauce is desired, add up to 1/4 cup more pesto. Top with cheese and halved cherry tomatoes.'),
('8393', '1', 'Preheat oven to 450 degrees. Wrap beet tightly in parchment paper-lined aluminum foil; place on a rimmed baking sheet. Cook until tender when pierced with the tip of a sharp knife, 45 to 50 minutes. When cool enough to handle, rub off skins, using paper towels to keep your hands from staining.'),
('8393', '2', 'Cut into wedges.'),
('8394', '1', 'Preheat oven to 400 degrees.'),
('8394', '2', 'Remove 1 garlic clove from 1 head, and very finely grate, setting aside 1/8 teaspoon. Wrap remaining heads of garlic in foil, and roast until very soft and golden inside, about 1 hour. Unwrap; let cool.'),
('8395', '1', 'Preheat oven to 450 degrees, with racks in upper and lower thirds. Divide dough into four equal pieces. Using your hands, stretch each piece into a 5-inch disk.'),
('8397', '1', 'Preheat the oven at 375 F.Grate the mozzarella.Take your pastry and top with the onions (0.5 away from the edge).Continue with the mozzarella and then place the tomatoes on top, face up.Cook in the oven for 30 to 35 mns, or until the dough is golden.'),
('8397', '2', 'Remove from the oven and let cool down.When ready to serve, top it with fresh washed arugula, shaved parmesan, pine nuts, salt and pepper, and a dash of olive oil. This tart is excellent lukewarm.'),
('8399', '1', 'Put the flour and salt in the bowl of an electric mixer and whisk together.'),
('8399', '2', 'Add the olive oil and eggs and mix together until it comes together into a ball. Attach the bowl to a mixer fitted with a dough hook and knead until the dough is smooth and satiny. Cover the dough with plastic wrap and let it rest while you make the filling.Blanch the arugula by putting it in a glass container, adding about a tablespoon of water, covering with another glass plate, and microwaving for 1 minute.'),
('8399', '3', 'Remove the lid, let it cool enough to handle, then squeeze as much moisture out of it as you can.'),
('8399', '4', 'Heat a small saute pan and add the olive oil.'),
('8399', '5', 'Saute the shallots, garlic and shiitake mushrooms until the mushrooms have given up most of their moisture (about 10-15 minutes).'),
('8399', '6', 'Let this mixture cool down to room temperature.'),
('8399', '7', 'Add the arugula, onion mixture, marscapone, ricotta, tahini, soy sauce and salt to a food processor and process until smooth.'),
('8399', '8', 'Add the water chestnuts and pulse a few times to roughly chop them up (there should still be chunks). Prepare an egg wash by whisking together an egg with 1 tablespoon of water.'),
('8399', '9', 'Heat the balsamic vinegar, honey and demi-glace in your smallest sauce pan. Once the demi-glace has disolved and the mixture is thick and bubbly, it''s ready (this shouldn''t take long). I poured the mixture into a mini squeeze bottle to make the dots, but you can also just pour a bit on the plate and smear it with a spoon, or just drizzle it on top of the raviolis.'),
('8399', '10', 'Cut off a quarter of the dough and flatten it out on a floured surface using your hands or a rolling pin, then pass it through the rollers of a pasta maker starting from the thickest setting and working your way down to a thinnest, passing the dough through at least 2 times per setting. If the dough starts to stick, just dust some flour on it. Lay the dough out on a long flat floured surface then repeat with another quarter of dough.When your second sheet is done, line the sheets up and trim off the ends so they are exactly the same length.'),
('8399', '11', 'Place 1 tablespoon of filling a few inches apart, leaving room around the edges of the dough so you can seal the raviolis. Be careful not to overcrowd the dough or you''ll have a hard time sealing the raviolis properly. Use a pastry brush to paint the egg wash all around the filling. Drape the other piece of dough over the first piece and use your fingers to start sealing each ravioli starting from one end. It''s crucial that there aren''t any air pockets with the filling as the air will expand while cooking and your ravioli will burst. The best way to do this is to seal one side, then use two fingers to trace the outline of the filling starting fromt he side that''s sealed, then seal off the other side, and you should be good.I used a round cookie cutter that''s 1/4" bigger than the filling mound on both sides, but you can also cut your ravioli with a knife. If you are freezing the ravioli, place them on a floured cookie sheet and freeze them. Once they are frozen you can put them in a ziplock bag, but they will stick together if you don''t freeze them separately first.To cook the ravioli, bring a large pot of water to a rolling boil, then turn down the heat to maintain a gentle boil. If you have a very large pot you can cook all 18 at the same time, but I just cooked them in two batches. Drop the raviolis in and then they float to the surface they are done (this won''t take very long).'),
('8399', '12', 'Drain the ravioli and transfer them to a bowl.'),
('8399', '13', 'Drizzle with sesame oil, add a handful of arugula, and sprinkle with salt and pepper and toss to coat.'),
('8399', '14', 'Serve the ravioli with the balsamic vinegar reduction. Sprinkle some toasted sesame seeds and chives on top to garnish.'),
('8400', '1', 'Preheat oven to 500 degrees.'),
('8400', '2', 'Place pizza stone in oven to preheat it as well. (You can use a cookie sheet if you dont have a pizza stone.)'),
('8400', '3', 'Roll dough on floured surface until nice and thin. Have all toppings prepared and at hand near oven.'),
('8400', '4', 'Remove hot pizza stone from oven. Sprinkle with cornmeal. Arrange dough on stone, brush olive oil over surface, and sprinkle with salt. Acting quickly, sprinkle first cheese, then bacon and finally asparagus over dough and place in the oven.At about 5 minutes, which will be your halfway point, remove pizza from oven. Crack three eggs over pizza. Return to oven and cook for another 5 minutes, until whites have set. You can cook it a little longer if youd like firmer yolks.'),
('8400', '5', 'Remove from oven and immediately spread arugula over pizza. Allow to cool for a few minutes, then serve.'),
('8401', '1', 'Preheat oven to 200 degrees.'),
('8401', '2', 'Cut the yellow and red tomatoes in half. Gently squeeze each tomato half to drain the juice and seeds. Lay tomatoes in a single layer on parchment lined baking sheets and allow to dry out in the oven for 2 hours. (You can skip the tomatoes for a quick weeknight meal or make them ahead. They will stay good covered in olive oil in an airtight container stored in the fridge for up to a month!)'),
('8401', '3', 'Cook pasta according to directions.'),
('8401', '4', 'Drain, saving some of the cooking water, but do not rinse the pasta.'),
('8401', '5', 'Add almonds and cheese to a food process or blender. Process at very slow speed until combined.'),
('8401', '6', 'Add arugula and garlic, then olive oil, salt and pepper. Process the mixture slowly the entire time to ensure that the blade doesnt heat up too much (which would cook the greens and cheese proteins, changing the flavor) and also that they mixture doesnt become overly smooth.'),
('8401', '7', 'Add pasta and pesto to a large bowl and toss to coat well. Dont be afraid to add a ladle or two of cooking water, if necessary to create a creamy texture. You can also add oil and cheese to taste. Toss in oven dried tomatoes, if using and toss one more time.'),
('8401', '8', 'Serve garnished with toasted sliced almonds.*Note: The most recent guidelines released by the American Academy of Pediatrics indicates no proven benefit in delaying solids, even high allergen foods including nuts, beyond 4- to 6-months. This doesnt mean that your child wont necessarily have an allergic reaction, but it does at means that it is safe and responsible to consider introducing high allergen foods as early as 6 months, especially if your child has no personal or family history of food allergies. Speak to your pediatrician about whats best for your family.**Im giving away vouchers that are good in exchange for free tickets to the concert and VIP section (where Barilla will be catering fresh food made on the premises for concert goers). Once you receive your vouchers, youll have to stop by Casa Barilla on Sept 13th or by noon on the 14th to make the switch. Ill provide full details directly to the winners. Good luck!This post has been sponsored by the good folks at Barilla, with whom I have entered a paid partnership. They have hired me to help raise awareness of the special events happening in NYC as part of their Summer of Italy. Im attending events personally so that I can share my experiences with you and all opinions are strictly my own. Read more about One Hungry Mama and sponsorships here.'),
('8402', '1', 'Preheat oven to 325 degrees. In a small bowl, toss bread pieces with 1 tablespoon oil; season with salt and pepper. Toss to coat; spread out in a single layer on a rimmed baking sheet.'),
('8402', '2', 'Bake, tossing once, until slightly crisp, about 7 minutes.'),
('8402', '3', 'Let cool.'),
('8407', '1', 'Preheat the oven to 42'),
('8407', '2', 'In a bowl, stir the mustard with the water, mirin, 1 teaspoon of the soy and 1/2 teaspoon of the sugar.'),
('8407', '3', 'In an ovenproof skillet, heat 1 tablespoon of the oil. Season the chicken with salt and pepper and cook over high heat until golden, 2 minutes. Flip the chicken and brush with the mustard; transfer to the oven and roast for 8 minutes, or until cooked through.'),
('8407', '4', 'Transfer the chicken to a cutting board and let rest for 5 minutes; slice. Wipe out the skillet.'),
('8407', '5', 'Meanwhile, steam the bok choy for 5 minutes.'),
('8407', '6', 'Drain; pat dry. In the same skillet, heat 1 tablespoon of the oil.'),
('8407', '7', 'Add the bok choy cut side down and cook over high heat, turning once, until browned, 3 minutes.'),
('8407', '8', 'Transfer to a platter; season with salt and pepper. Arrange the chicken over the bok choy.'),
('8407', '9', 'In a bowl, whisk the vinegar with the remaining oil, soy sauce and sugar; season with salt and pepper.'),
('8407', '10', 'Add the arugula and toss; arrange over the chicken and serve.'),
('8412', '1', 'Heat oil in heavy large skillet over medium-high heat.'),
('8412', '2', 'Add onions. Saut until golden, about 18 minutes.'),
('8412', '3', 'Remove from heat. Sprinkle with vinegar; stir to blend. Season with salt and pepper.'),
('8412', '4', 'Combine first 4 ingredients in another heavy large skillet. Bring to boil, whisking. Boil 1 minute.'),
('8412', '5', 'Add walnuts; stir. Toss until syrup forms glaze on nuts, about 3 minutes.'),
('8412', '6', 'Transfer nuts to sheet of foil and quickly separate nuts with forks. Cool. DO AHEAD Can be made 2 hours ahead.'),
('8412', '7', 'Let stand at room temperature. Preheat oven to 350F.'),
('8412', '8', 'Place bread cubes in large bowl.'),
('8412', '9', 'Drizzle with oil, tossing constantly to coat evenly. Scatter cubes in single layer on rimmed baking sheet. Sprinkle with salt and pepper.'),
('8412', '10', 'Bake croutons until crisp, stirring occasionally, about 15 minutes. DO AHEAD Can be made 2 hours ahead.'),
('8412', '11', 'Let stand on sheet at room temperature.'),
('8412', '12', 'Whisk oil and vinegar in small bowl. Season dressing with salt and pepper.'),
('8412', '13', 'Place arugula in very large bowl. Drop in onions, tossing to distribute evenly.'),
('8412', '14', 'Add nuts, croutons, and goat cheese. Toss with enough dressing to coat lightly.'),
('8413', '1', 'Set a grill over high heat, or place an iron skillet over high heat.'),
('8413', '2', 'When very hot, season the steak with lots of salt and pepper. If using an iron skillet, pour 1 teaspoon of canola oil in the skillet, if using the grill then place directly on the grates. Cook for 4 minutes a side. Set aside and let the meat rest for 5 minutes.'),
('8413', '3', 'Slice the steak against the grain.'),
('8413', '4', 'Place the meat on a platter with the arugula on side.'),
('8413', '5', 'Drizzle some olive oil over the meat and arugula, along with a sprinkling of rosemary. Squeeze some lemon juice over the arugula and serve.'),
('8416', '1', 'Preheat oven to 375 degrees.'),
('8416', '2', 'Spread pistachios on a rimmed baking sheet. Toast in oven until fragrant, about 8 minutes.'),
('8416', '3', 'Transfer to a plate; let cool completely.'),
('8417', '1', 'Preheat oven to 450 degrees. Turn a large baking sheet upside down; rub with oil. Using your hands, crush tomatoes into a pulp in a small bowl; season with salt and pepper.'),
('8418', '1', 'Meanwhile, grill onion until tender and charred, 4 to 5 minutes per side.'),
('8418', '2', 'Transfer to a plate; separate into rings. (To store, refrigerate steaks and onion, up to 1 day.)'),
('8421', '1', 'Transfer to a cutting board. Season with salt and pepper.Top with arugula, and drizzle with oil.'),
('8421', '2', 'Cut into squares.'),
('8423', '1', 'In a bowl, whisk together vinegars, garlic, and olive oil.'),
('8423', '2', 'Add salt and pepper to taste.'),
('8423', '3', 'Put arugula in a large bowl and toss with herbs and dressing.'),
('8423', '4', 'Add parmesan, then toss one more time.'),
('8427', '1', 'Combine first 5 ingredients in a large bowl; stir with a whisk.'),
('8427', '2', 'Add arugula and onion; toss well.'),
('8428', '1', 'Heat a gas grill to medium high or prepare a medium- hot charcoal fire. (Be sure the grate is hot, too.) Wipe the mushrooms clean and trim off the stems. If using portabellas, scrape out the black gills with the side of a spoon.'),
('8428', '2', 'Put the clean whole mushrooms in a large bowl, drizzle with 5 tablespoons of the oil, and gently toss. Sprinkle in a pinch of kosher salt and toss again. Grill the mushrooms directly over the heat until tender and well marked, 3 to 5 minutes on each side. If using portabellas, quickly cut the grilled mushrooms into 1-inch slices.'),
('8428', '3', 'Portion the arugula among four plates and top with the hot mushrooms.'),
('8428', '4', 'Garnish with the nuts and cheese and a generous drizzle of olive oil. Sprinkle lightly with fleur de sel or other sea salt and a grind of white or black pepper.'),
('8428', '5', 'Serve immediately.'),
('8429', '1', 'In a small bowl, whisk vinegar, shallots, mustard, and salt until thick and emulsified. Gradually whisk in olive oil.'),
('8429', '2', 'In a 3- to 4-quart pan over high heat, bring 2 quarts of water to a boil.'),
('8429', '3', 'Add corn kernels and cook for 1 minute; drain, rinse with cold water until cool, and drain again. In a large bowl, combine corn, radishes, and arugula.'),
('8429', '4', 'In a mortar, lightly crush coriander seeds (or place seeds in a zip-lock plastic bag and crush with a mallet or rolling pin).'),
('8429', '5', 'Pour dressing over the arugula mixture and gently mix to coat. Sprinkle salad with crushed coriander seeds.'),
('8435', '1', 'Preheat oven to 425 degrees. Season chicken with salt and pepper. On a clean work surface, lay cutlets flat (smooth sides down). Layer each cutlet with arugula; crumble goat cheese in the center. Starting with the narrow end, roll up chicken tightly; seal with a toothpick.'),
('8438', '1', 'Transfer to a bowl and taste test, adding salt and pepper to taste with the zest of about  the lemon, stir to combine. {This can be made ahead of time and refrigerated for a few hours until you are ready to serve.}Just before serving slice the ciabatta into 1.5cm ( inch) thick rounds and toast either in a sandwich press, under the grill or on a barbeque until golden and crispy.Rub each slice of crostini with the cut side of a clove of garlic and top with about 1 tablespoon of the pea & spinach mixture.'),
('8438', '2', 'Garnish with a little fresh mint or basil and drizzle over a splash of olive oil.The perfect quick vegetarian appetizer recipe for entertaining!'),
