INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('21984', '9', 'Eat the red pepper mousse with teaspoons, occasionally spreading some of it onto the garlic toasts.'),
('21993', '1', 'Heat the oil in small no-stick pan over medium heat.'),
('21993', '2', 'Add the onion and saute until tender, about 3-5 minutes.'),
('21993', '3', 'Add the garlic and sausage and cook until the sausage just starts to brown, breaking it up as it cooks and set aside.Turn the heat down one notch and pour in the eggs.When the eggs just starts to set, after about a minute, sprinkle the sausage over half of the eggs along with the roasted red pepper and the cheese on top.Cook until the eggs are just about set fold the side that is not covered over the other side and slide it onto a plate.'),
('21993', '4', 'Pour the marinara sauce over the omelette and garnish with parsley.'),
('21994', '1', 'Preheat the broiler.'),
('21994', '2', 'Place the red pepper halves, cut side down, in a baking pan and broil 4 to 5 inches from heat until the skins are black and blistered, about 8 minutes.'),
('21994', '3', 'Let cool, uncovered, 10 to 15 minutes. Peel the peppers and place in a bowl, reserving any juices.'),
('21994', '4', 'In a 3- to 4-quart pan over medium heat, add the olive oil and the onion. stir often until onion is soft, about 5 minutes.'),
('21994', '5', 'Add the garlic and stir until translucent, 1 to 2 minutes.'),
('21994', '6', 'Add the roasted peppers and tomatoes, along with their juices, and the paprika. Bring to a low simmer and cook, stirring occasionally, about 3 minutes.'),
('21994', '7', 'In a blender or food processor, pure the soup in small batches until smooth. Return pure to the pan and stir in broth and lemon juice. Stir over medium heat until hot. Season with salt and pepper to taste. Ladle into cups or bowls and garnish with a dollop of crme frache or plain yogurt and parsley.'),
('21994', '8', 'Do-ahead tips: Make soup up to 3 days ahead. Store airtight in the refrigerator. Reheat before serving.'),
('21994', '9', 'Party short-cut: If your guests tend to congregate in the kitchen, leave this roasted red pepper soup over a low flame on the stove and set cups, ladle, and toppings nearby (that''s one fewer dish to wash).'),
('21994', '10', 'Wine pairing: Classic Brut sparkling wine brings elegance to this dish. Alternatively, a dry, fruity ros is an unexpected match.'),
('21998', '1', 'Melt butter with oil in a Dutch oven over medium heat. add bell pepper and next 3 ingredients, and saut 8 to 10 minutes or until tender.'),
('21998', '2', 'Stir in chicken broth and next 4 ingredients. Bring to a boil. cover, reduce heat to low, and simmer 25 to 30 minutes.'),
('21998', '3', 'Let cool 20 minutes.'),
('21998', '4', 'Process soup, in batches, in a food processor until smooth, stopping to scrape down sides. Return to Dutch oven, and keep warm until ready to serve.'),
('21998', '5', 'Garnish, if desired.'),
('21998', '6', 'Note: To make ahead, let soup cool, and store in an airtight container in refrigerator up to 2 days. Reheat in a saucepan over medium-low heat, stirring often.'),
('21999', '1', 'Combine all ingredients, stirring well. Position knife blade in food processor bowl. add one-third of vegetable mixture. Process 30 seconds or until smooth.'),
('21999', '2', 'Transfer mixture to a bowl. Repeat procedure twice with remaining mixture. Cover and chill at least 3 hours.'),
('22007', '1', 'Cook green beans in boiling salted water to cover 3 to 4 minutes or until crisp-tender. drain well.'),
('22007', '2', 'Melt butter in a large skillet over medium-high heat. add sliced shallots and bell pepper, and saut 4 minutes or until tender.'),
('22007', '3', 'Add green beans, salt, pepper, and garlic powder, and toss to combine.'),
('22007', '4', '*1/2 small sweet onion, thinly sliced, may be substituted.'),
('22007', '5', '**1/2 tsp. regular salt may be substituted.'),
('22008', '1', 'Preheat the oven to 40'),
('22008', '2', 'On a baking sheet, brush the peppers with olive oil and roast for 20 minutes, turning once, until lightly browned and softened.'),
('22008', '3', 'Transfer the peppers to a bowl, cover with plastic wrap and let cool for 10 minutes.'),
('22008', '4', 'Meanwhile, in a medium skillet, heat 2 tablespoons of the olive oil.'),
('22008', '5', 'Add the mushrooms and cook over moderately high heat, stirring, until lightly browned, 4 minutes. Stir in the shallot, garlic and marjoram and cook until fragrant, 2 minutes. Season with salt and pepper and keep warm.'),
('22008', '6', 'Peel, core and seed the peppers.'),
('22008', '7', 'Transfer the peppers to a blender and puree. With the machine on, add the remaining 3 tablespoons of oil and the hot sauce and puree. Season with salt and pepper.'),
('22008', '8', 'Bring a large saucepan filled with 3 inches of water to a simmer. Crack each egg into a cup, then slide it into the water. Poach the eggs over low heat until the whites are set and the yolks are runny, 4 minutes. Using a slotted spoon, lift the eggs out of the water and blot them dry.'),
('22008', '9', 'Spoon the pepper puree onto plates and top with the mushrooms. Set the eggs on the mushrooms, season lightly with salt and pepper and serve.'),
('22012', '1', 'Preheat broiler.'),
('22012', '2', 'Cut bell pepper in half lengthwise. discard seeds and membranes.'),
('22012', '3', 'Place pepper halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 10 minutes or until blackened.'),
('22012', '4', 'Place in a zip-top plastic bag. seal.'),
('22012', '5', 'Let stand 10 minutes. Peel.'),
('22012', '6', 'Place bell pepper and remaining ingredients in a food processor. process until smooth.'),
('22014', '1', 'Cut a slit lengthwise in each chile and carefully scoop out the seeds and ribs. In a medium bowl, combine the beans, cheese, raisins, salsa, and chili powder. Stuff the peppers with the filling.'),
('22014', '2', 'Light a charcoal grill and allow the coals to burn until covered with gray ash or heat a gas grill to medium.'),
('22014', '3', 'Place peppers on grill and cook, turning frequently, until they are soft and the cheese has melted.'),
('22018', '1', 'Cook pasta according to package directions. drain and set aside.'),
('22018', '2', 'Stir together dressing and next 4 ingredients in a small microwave-safe bowl. Microwave at MEDIUM (50% power) 1 minute and 20 seconds to 1 minute and 30 seconds or until warm, stirring at 30-second intervals.'),
('22018', '3', 'Combine hot cooked pasta and red pepper strips in a serving bowl.'),
('22018', '4', 'Pour dressing mixture evenly over pasta mixture. Top with croutons, and serve immediately.'),
('22018', '5', '*Dried porcini mushroom tortelloni or refrigerated three-cheese tortellini may be substituted.'),
('22018', '6', 'Note: For testing purposes only, we used Barilla Ricotta and Asparagus Tortelloni, Wishbone Creamy Caesar Dressing, and Cardini''s Gourmet'),
('22018', '7', 'Cut Caesar Croutons.'),
('22019', '1', 'Toss together red peppers and garlic in a small bowl.'),
('22019', '2', 'Spread cut side of top half of bread evenly with tapenade and cut side of bottom half evenly with goat cheese. Layer red pepper mixture and arugula over goat cheese.'),
('22019', '3', 'Place top half of bread, tapenade side down, onto red pepper and arugula layers.'),
('22019', '4', 'Cut into 4 pieces.'),
('22020', '1', 'Drain roasted peppers, and pat dry with paper towels. coarsely chop.'),
('22020', '2', 'Spread tortillas evenly with goat cheese, and spread guacamole evenly over cheese.'),
('22020', '3', 'Sprinkle with chopped red pepper and ground pepper.'),
('22020', '4', 'Roll up, pressing edges to seal. cut each roll into 6 slices using a serrated knife. Secure slices with wooden picks.'),
('22020', '5', 'Garnish, if desired.'),
('22020', '6', 'Note: If time permits, wrap rolls in plastic wrap, and chill 1 hour before slicing.'),
('22021', '1', 'Heat olive oil in a large, deep skillet over medium heat.'),
('22021', '2', 'Add chorizo, and saut 3 minutes or until lightly browned.'),
('22021', '3', 'Add bell pepper, onion, and garlic, and saut 5 minutes.'),
('22021', '4', 'Add wine, paprika, and salt. bring to a boil. Cover, reduce heat to low, and simmer 5 minutes or until vegetables are tender.'),
('22021', '5', 'Increase heat to medium-high, and add mussels. Cover and cook 2 minutes or until mussels open. Discard any that do not open. Stir in cilantro. Spoon mussels, sauce, and vegetables into 4 shallow serving bowls.'),
('22021', '6', 'Serve immediately with lime wedges.'),
('22021', '7', 'Pour: Citrusy whites pair well with spicy foods. For this dish, Edward Peterman of Domaine Select Wine Estates suggests Villa Sparina Gavi di Gavio.'),
('22023', '1', 'Roast the peppers over a gas flame or under the broiler until charred all over.'),
('22023', '2', 'Transfer to a bowl, cover with plastic wrap and let steam for 20 minutes. Discard the skins, cores and seeds. Pat the peppers dry and finely chop them.'),
('22023', '3', 'In a skillet, cook the garlic in the oil over moderate heat until fragrant, about 30 seconds.'),
('22023', '4', 'Add the peppers and vinegar and cook over moderately low heat, stirring, until dry, about 12 minutes.'),
('22023', '5', 'Transfer to a bowl to cool. Stir in the sour cream and basil and season with salt and pepper. Refrigerate until chilled.'),
('22031', '1', 'Slice roasted peppers into 1-inch-thick strips.'),
('22031', '2', 'Place peppers and next 5 ingredients in a large bowl. stir gently to combine. Cover and chill at least 8 hours.'),
('22031', '3', 'Serve atop toasted baguette slices.'),
('22033', '1', 'In a large pot of boiling salted water, cook the penne until al dente.'),
('22033', '2', 'Drain, reserving 3/4 cup of the cooking water.'),
('22033', '3', 'Meanwhile, in a large, deep skillet, heat the olive oil until shimmering.'),
('22033', '4', 'Add the onion, season with salt and pepper and cook over moderately high heat until softened and just beginning to brown, about 5 minutes.'),
('22033', '5', 'Add the bell peppers, capers and crushed red pepper and cook, stirring occasionally, until the peppers are softened and lightly browned in spots, about 10 minutes. Stir in the vinegar and cook until nearly evaporated, about 2 minutes.'),
('22033', '6', 'Add the tomato sauce and cook for 5 minutes.'),
('22033', '7', 'Add the penne and the reserved cooking water to the sauce, season with salt and pepper and simmer, stirring, until thickened, about 2 minutes. Stir in the basil.'),
('22033', '8', 'Transfer the pasta to bowls, sprinkle with the Pecorino and serve.'),
('22034', '1', 'Preheat the oven to 42'),
('22034', '2', 'Butter 2 large baking sheets.'),
('22034', '3', 'In a food processor, puree the red bell pepper with the water and garlic until the mixture is as smooth as possible, about 2 minutes. Strain the pepper puree through a fine sieve set over a measuring cup, pressing hard on the solids with the back of a spoon to extract as much of the pepper juice as possible. you should have 1 cup. Stir in a little more water if necessary.'),
('22034', '4', 'Transfer the red pepper juice to a medium saucepan.'),
('22034', '5', 'Add the butter, salt and pepper and cook over moderately high heat until the butter melts.'),
('22034', '6', 'Add the flour all at once and beat with a wooden spoon until the dough pulls away from the side of the pan and forms a smooth, shiny ball on the spoon. Scrape the dough into a bowl. Using an electric mixer at medium speed, beat in the eggs, 1 at a time, beating well between additions. Beat in the Pecorino Romano and cayenne.'),
('22034', '7', 'Drop rounded teaspoons of the dough about 1 inch apart onto the prepared baking sheets.'),
('22034', '8', 'Bake the goures on the upper and middle racks of the oven for about 20 minutes, or until puffed and browned. shift the baking sheets from top to bottom and back to front halfway through baking.'),
('22034', '9', 'Serve the gougres hot, warm or at room temperature.'),
('22036', '1', 'In a saucepan, heat the olive oil.'),
('22036', '2', 'Add the peppers, garlic, onion and a pinch of salt. Cover and cook over moderately low heat until the peppers are softened, 8 minutes. Stir in the tomato paste, water and broth and bring to a boil. Cover and simmer over low heat until the peppers are very tender, about 10 minutes.'),
('22036', '3', 'Transfer the soup to a blender and puree. Season with salt and pepper and refrigerate for about 1 hour, until lightly chilled.'),
('22036', '4', 'Meanwhile, in a large skillet, heat inch of vegetable oil until shimmering.'),
('22036', '5', 'Add the tortilla strips and fry over moderately high heat until crisp.'),
('22036', '6', 'Drain and dust with the cheese.'),
('22036', '7', 'Serve with the chilled soup in shot glasses.'),
('22037', '1', 'Toss all of the ingredients in a large bowl and serve.'),
('22038', '1', 'In a 10- to 12-inch nonstick frying pan over medium-high heat, frequently stir bell pepper, onion, and garlic in oil until vegetables begin to brown, 8 to 10 minutes.'),
('22038', '2', 'Add artichokes, parsley, olives, and lemon juice, mixing well.'),
('22038', '3', 'Remove from heat. Season to taste with salt and pepper. If making up to 1 day ahead, cover and chill.'),
('22038', '4', 'Arrange baguette slices in a single layer on a 12- by 15-inch baking sheet. Broil 4 to 6 inches from heat until toasted on 1 side, about 1 minute.'),
('22038', '5', 'Remove from oven and turn slices over.'),
('22038', '6', 'Spoon artichoke mixture equally on untoasted side of baguette slices. spread level. Sprinkle with cheese.'),
('22038', '7', 'Broil 4 to 6 inches from heat until cheese begins to melt and topping is hot, about 1 minute.'),
('22043', '1', 'Soak 12 wooden skewers in cold water for 15 minutes. Thread the chicken, alternating with the bell peppers, onto the skewers.'),
('22043', '2', 'Transfer to a baking dish.'),
('22043', '3', 'In a small bowl, whisk the soy sauce with the olive oil and curry powder.'),
('22043', '4', 'Pour the marinade over the kebabs and let marinate for 10 minutes or for up to 1 hour, turning several times.'),
('22043', '5', 'Meanwhile, light a grill or preheat a grill pan. Grill the kebabs over moderately high heat until golden brown, about 6 minutes.'),
('22043', '6', 'Remove from the grill, brush with the melted butter and serve.'),
('22049', '1', 'Process mayonnaise, garlic, and roasted red bell pepper in a mini food processor until smooth.'),
('22052', '1', 'Preheat the oven to 45'),
('22052', '2', 'Arrange the peppers on a baking sheet and roast for 1 hour, turning occasionally, until tender and charred in spots.'),
('22052', '3', 'Transfer the peppers to a paper bag, close and let cool.'),
('22052', '4', 'Peel, core and seed the roasted bell peppers, keeping them intact.'),
('22052', '5', 'Cut each pepper in half lengthwise and pat dry with paper towels.'),
('22052', '6', 'Working over a bowl, press the ricotta through a sieve.'),
('22052', '7', 'Add the snipped chives, season with salt and pepper and stir the tomato into the filling.'),
('22052', '8', 'Arrange the roasted peppers on a work surface, skinned sides down. Divide the filling evenly between the halves and roll up into thick cylinders. Refrigerate for at least 15 minutes.'),
('22052', '9', 'Cut the cylinders into 3/4-inch-thick slices, transfer to a platter with the cut sides up and serve.'),
('22059', '1', 'In a large Dutch oven, saut red peppers, carrots, onions, celery and garlic in olive oil until tender. Stir in broth, rice, thyme, salt, pepper and cayenne pepper. bring to a boil. Reduce heat. cover and simmer for 20 to 25 minutes, or until vegetables and rice are tender. Cool for 30 minutes.'),
('22059', '2', 'Puree in small batches in a food processor or blender, return to pan and add red pepper flakes.'),
('22059', '3', 'Heat through.'),
('22059', '4', 'Garnish with croutons.'),
('22061', '1', 'Preheat broiler.'),
('22061', '2', 'Cut bell pepper in half lengthwise. discard seeds and membranes.'),
('22061', '3', 'Place pepper halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 10 minutes or until blackened.'),
('22061', '4', 'Place in a zip-top plastic bag. seal.'),
('22061', '5', 'Let stand 10 minutes. Peel.'),
('22061', '6', 'Place bell pepper and remaining ingredients in a food processor. process until smooth.'),
('22062', '1', 'Preheat broiler.'),
('22062', '2', 'Cut bell peppers in half lengthwise. discard seeds and membranes.'),
('22062', '3', 'Place pepper halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 15 minutes or until blackened.'),
('22062', '4', 'Place in a zip-top plastic bag. seal.'),
('22062', '5', 'Let stand 15 minutes. Peel and finely chop.'),
('22062', '6', 'Place coriander seeds in a small skillet. cook over medium heat 3 minutes or until seeds are lightly browned and fragrant, shaking pan frequently.'),
('22062', '7', 'Transfer seeds to a spice or coffee grinder, and process until finely ground.'),
('22062', '8', 'Heat oil in a medium nonstick skillet over medium heat.'),
('22062', '9', 'Add onion. saut 8 minutes or until translucent.'),
('22062', '10', 'Add coriander, crushed red pepper, and garlic. saut 3 minutes.'),
('22062', '11', 'Combine onion mixture and roasted bell pepper in a medium bowl. Stir in red wine vinegar and next 4 ingredients (red wine vinegar through black pepper). Cover and refrigerate 30 minutes. Stir in cilantro.'),
('22063', '1', 'Preheat oven to 32'),
('22063', '2', 'Stir together Cheddar cheese, pepper Jack cheese, cream cheese, roasted red bell peppers, mayonnaise, cilantro, green onions, jalapeo peppers, Worcestershire sauce, dried crushed red pepper, and salt and freshly ground black pepper to taste. Lightly grease a 2-qt. baking dish with cooking spray. spread cheese mixture in prepared dish.'),
('22063', '3', 'Bake 20 to 25 minutes or until thoroughly heated and bubbly.'),
('22064', '1', 'Dissolve yeast and sugar in warm water in a large bowl, and let stand 5 minutes.'),
('22064', '2', 'Add 1 cup flour, mustard, oil, salt, and pepper, and stir until smooth.'),
('22064', '3', 'Add 1 3/4 cups flour and cheese, and stir to form a soft dough. Turn dough out onto a lightly floured surface. Knead until smooth and elastic (about 10 minutes). add enough of remaining flour, 1 tablespoon at a time, to prevent dough from sticking to hands.'),
('22064', '4', 'Place dough in a large bowl coated with cooking spray, turning to coat top. Cover and let rise in a warm place (85), free from drafts, 1 hour or until doubled in bulk. Punch dough down. turn out onto a lightly floured surface.'),
('22064', '5', 'Roll dough into a 14 x 7-inch rectangle.'),
('22064', '6', 'Roll up rectangle tightly starting with a short edge, pressing firmly to eliminate air pockets. pinch seam and ends to seal.'),
('22064', '7', 'Place roll, seam side down, in a 9 x 5-inch loaf pan coated with cooking spray. Cover and let rise 1 hour or until doubled in bulk.'),
('22064', '8', 'Preheat oven to 37'),
('22064', '9', 'Uncover dough. bake at 375 for 35 minutes or until loaf sounds hollow when tapped.'),
('22064', '10', 'Remove from pan immediately. cool on a wire rack.'),
('22064', '11', 'Bread Machine Variaton: Follow manufacturer''s instructions for placing all dough ingredients in bread pan. Select cycle, and start bread machine.'),
('22076', '1', 'Melt butter in a large Dutch oven over medium-high heat. add bell peppers and next 2 ingredients.'),
('22076', '2', 'Saute 12 to 15 minutes or until onion is golden. Stir in garlic and next 4 ingredients. Cook, stirring constantly, 2 minutes.'),
('22076', '3', 'Add broth and bay leaves. bring to a boil. Reduce heat to medium-low, and simmer, stirring often, 25 minutes or until vegetables are tender. Discard bay leaves.'),
('22076', '4', 'Process soup with a handheld blender until smooth. Stir in cream, and season with salt and pepper to taste. Cook over medium heat 10 minutes or until thoroughly heated.'),
('22076', '5', 'Serve with Collard Green Pistou.'),
('22076', '6', 'Note: If you don''t have a handheld blender, let mixture cool slightly after Step 2. process mixture, in batches, in a regular blender until smooth. Return mixture to Dutch oven, and proceed with recipe as directed in Step'),
('22077', '1', 'Prepare broiler.'),
('22077', '2', 'Cut bell pepper in half lengthwise, discarding seeds and membranes.'),
('22077', '3', 'Place pepper halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 15 minutes or until blackened.'),
('22077', '4', 'Place in a paper bag. fold to close tightly.'),
('22077', '5', 'Let stand 10 minutes. Peel and coarsely chop.'),
('22077', '6', 'Place bell pepper and remaining ingredients in a blender, and process until smooth.'),
('22078', '1', 'Preheat oven to 35'),
('22078', '2', 'Bring 1/2 cup water to boil in a small saucepan. gradually stir in couscous.'),
('22078', '3', 'Remove from heat. cover and let stand 5 minutes. Fluff with a fork.'),
('22078', '4', 'Combine 1 tablespoon water, salt, black pepper, egg whites, and eggs in a medium bowl, stirring with a whisk.'),
('22078', '5', 'Heat a 10-inch ovenproof nonstick skillet coated with cooking spray over medium-high heat.'),
('22078', '6', 'Add bell pepper, onion, and garlic. saut 5 minutes. Stir in couscous and egg mixture. cook over medium heat 5 minutes or until almost set. Sprinkle with cheese.'),
('22078', '7', 'Bake at 350 for 10 minutes or until set.'),
('22078', '8', 'Let stand 5 minutes before serving.'),
('22079', '1', 'Preheat oven to 45'),
('22079', '2', 'Pierce eggplant several times with a fork. place on a foil-lined baking sheet.'),
('22079', '3', 'Bake at 450 for 20 minutes or until tender. Cool slightly. peel and chop.'),
('22079', '4', 'Place in a large bowl.'),
('22079', '5', 'Heat the oil in a large nonstick skillet over medium-high heat.'),
('22079', '6', 'Add onion, bell pepper, and nuts. Cook 6 minutes or until onion is tender.'),
('22079', '7', 'Add onion mixture, salt, black pepper, and eggs to eggplant. stir well to combine.'),
('22079', '8', 'Add matzo meal. toss gently to combine. Spoon mixture into an 11 x 7-inch baking dish coated with cooking spray. Sprinkle with paprika.'),
('22079', '9', 'Bake at 450 for 35 minutes or until pudding is thoroughly heated and golden brown.'),
('22080', '1', 'Combine bulgur and 1/2 cup boiling water in a large bowl. Cover and let stand 15 minutes or until the bulgur is tender.'),
('22080', '2', 'Drain well. return bulgur to bowl. Cool.'),
('22080', '3', 'Add tomato and remaining ingredients. toss well.'),
('22081', '1', 'Unroll pizza dough onto a baking sheet coated with cooking spray. pat dough into a 14 x 10-inch rectangle.'),
('22081', '2', 'Bake at 425 for 5 minutes. set aside.'),
('22081', '3', 'Heat oil in a nonstick skillet over medium-high heat.'),
('22081', '4', 'Add red bell pepper, basil, oregano, and garlic. saute 5 minutes.'),
('22081', '5', 'Remove from heat. stir in artichokes and mushrooms.'),
('22081', '6', 'Sprinkle half of cheese over prepared pizza crust, leaving a 1/2-inch border.'),
('22081', '7', 'Spread the vegetable mixture evenly over cheese, and top with remaining cheese. Sprinkle with cracked pepper, if desired.'),
('22081', '8', 'Bake at 425 for 10 minutes or until crust is lightly browned.'),
('22090', '1', 'Watch how to make this recipe.'),
('22090', '2', 'Preheat oven to 300 degrees F or preheat a grill over high heat. Rub the peppers with canola oil, put them on a baking sheet and roast them in the oven until golden brown, about 45 minutes to 1 hour. They can also be grilled until blackened all over.'),
('22090', '3', 'Remove the peppers to a bowl and cover the bowl.'),
('22090', '4', 'Let rest until cool enough to handle, then remove the skin and seeds and dice. Do not rinse.'),
('22090', '5', 'Put a Dutch oven on the stove top over high heat, coat with some canola oil and add the capicola.'),
('22090', '6', 'Saute for 3 to 5 minutes. Season the ribs with salt and pepper and add them to the pot with 3 tablespoons of oil. Brown well on all sides, then remove them to a plate.'),
('22090', '7', 'Add the onions and saute until they are starting to caramelize, then add the garlic and cook for 1 minute more. Stir in the capers and caper juice.'),
('22090', '8', 'Mix to combine and allow the mixture to caramelize a bit more. Deglaze with the white wine. Stir in the agave, chicken stock and red wine vinegar. Bring to a boil, then add the seared ribs along with the diced peppers.'),
('22090', '9', 'Cover and bake for 2 hours, stirring occasionally.'),
('22090', '10', 'Remove the pork from the oven to a serving platter and serve with the sauce.'),
('22090', '11', 'Guy''s tip: you can uncover 3/4 of the way through to allow the sauce to reduce for serving. Another alternative is to remove the Dutch oven from the oven, put the pork onto a serving platter and simmer the sauce over high heat to reduce for about 5 to 10 minutes before serving.'),
('22095', '1', 'Preheat broiler.'),
('22095', '2', 'To prepare pesto, cut bell peppers in half lengthwise. discard seeds and membranes.'),
('22095', '3', 'Place pepper halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 10 minutes or until blackened.'),
('22095', '4', 'Place in a zip-top plastic bag. seal.'),
('22095', '5', 'Let stand 15 minutes. Peel and discard skin.'),
('22095', '6', 'Combine peppers and next 7 ingredients (through garlic) in a blender or food processor. process until smooth.'),
('22095', '7', 'To prepare cheese filling, combine cheeses, 1/4 teaspoon salt, and red pepper in a medium bowl. stir well.'),
('22095', '8', 'Line an 8 x 4-inch loaf pan with plastic wrap, allowing plastic wrap to extend over edges of pan.'),
('22095', '9', 'Spread about 1 cup of cheese mixture in bottom of pan.'),
('22095', '10', 'Spread 1/2 cup pesto over cheese mixture. Repeat procedure with remaining cheese filling and pesto, ending with cheese filling. Cover and refrigerate 6 hours or overnight.'),
('22095', '11', 'To serve, invert terrine onto a platter. remove plastic wrap.'),
('22095', '12', 'Garnish with additional basil leaves, if desired.'),
('22095', '13', 'Serve with crackers.'),
('22099', '1', 'Save Recipe'),
('22099', '2', 'Print Recipe'),
('22099', '3', 'Green Bean Pepper Salad'),
('22099', '4', 'Ingredients1 lb. green beans, washed, trimmed, and cut into 2-inch pieces (if using young small beans, you can leave them whole after trimming)1 red bell pepper, roasted, peeled and seeded1/4 cup extra virgin olive oil1/4 cup white balsamic vinegar1 tbsp whole grain mustard1/2 tsp pepper (or more to taste)1/4 tsp salt (or more to taste)2 tbsp fresh minced parsley'),
('22099', '5', 'Total Time: 50 Minutes'),
('22099', '6', 'Servings: 8'),
('22099', '7', 'Kosher Key: Pareve, Kosher for Sephardic Passover'),
('22105', '1', 'Preheat broiler. Arrange zucchini slices in a single layer on a baking sheet and broil until tops are well charred and slices are slightly wilted, about 10 minutes.'),
('22105', '2', 'Remove from oven and cool for 10 minutes.'),
('22105', '3', 'Place cooled zucchini, peppers, oil, vinegar, parsley, garlic, feta, and black pepper in a food processor and pulse until incorporated but still chunky, 15-20 pulses.'),
('22105', '4', 'Serve spread on toasted baguette slices.'),
('22108', '1', 'Heat a large skillet over medium heat.'),
('22108', '2', 'Add 2 tablespoons oil. swirl to coat.'),
('22108', '3', 'Add garlic. cook 30 seconds, stirring constantly. Stir in pepper.'),
('22108', '4', 'Remove from heat.'),
('22108', '5', 'Bring 6 quarts water and 1 tablespoon salt to a boil in a large pot.'),
('22108', '6', 'Add pasta. cook 8 minutes or until almost al dente.'),
('22108', '7', 'Drain pasta in a colander over a bowl, reserving 1/2 cup cooking liquid.'),
('22108', '8', 'Add hot pasta, reserved cooking liquid, remaining 1/4 teaspoon salt, and cheese to garlic mixture. Increase heat to medium-high. cook 2 minutes or until pasta is al dente, tossing to combine.'),
('22108', '9', 'Remove from heat.'),
('22108', '10', 'Add parsley. toss.'),
('22108', '11', 'Place 1 1/2 cups pasta on each of 4 plates. drizzle each serving with 1 1/2 teaspoons olive oil.'),
('22109', '1', 'Heat the oil in a large nonstick skillet over medium-high heat.'),
('22109', '2', 'Add onion and cumin. saut 10 minutes or until onion is lightly browned.'),
('22109', '3', 'Add bell pepper and water. cover, reduce heat, and simmer 3 minutes.'),
('22109', '4', 'Add the green onions, salt, and beans. cover and cook for 2 minutes or until thoroughly heated, stirring occasionally.'),
('22109', '5', 'Remove from heat. stir in basil. Sprinkle with the breadcrumbs, and serve over rice.'),
('22110', '1', 'Gently stir together first 12 ingredients. cover and refrigerate at least 2 hours before serving.'),
('22110', '2', 'Serve with multicolored tortilla chips.'),
('22111', '1', 'Remove stems from mushrooms. reserve for another use.'),
('22111', '2', 'Grill mushrooms, bell peppers, and tomatoes, covered with grill lid, over medium-high heat (350 to 40'),
('22111', '3', '10 minutes or until peppers and tomatoes look blistered and mushrooms are blackened, turning occasionally.'),
('22111', '4', 'Place bell peppers in a heavy-duty zip-top plastic bag. seal and let stand 10 minutes to loosen skins. Peel peppers. remove and discard seeds. Peel tomatoes. Chop peppers, tomatoes, and mushrooms.'),
('22111', '5', 'Stir together grilled vegetables, green onions, and next 8 ingredients. Cover and chill 1 hour.'),
('22111', '6', 'Garnish, if desired.'),
('22112', '1', 'In a Dutch oven or other large, heavy pot, melt butter over medium heat.'),
('22112', '2', 'Add onions and cook, stirring, until softened, about 10 minutes.'),
('22112', '3', 'Add garlic and cook, stirring, for 2 minutes.'),
('22112', '4', 'Add plum tomatoes and their juice, chicken broth and crushed tomatoes. bring to a boil. then simmer for 5 minutes.'),
('22112', '5', 'Add red peppers, Pernod (if using), thyme, salt and pepper. bring to a boil. then simmer for 5 minutes longer.'),
('22112', '6', 'In a bowl, stir together sour cream and lemon peel. Cover and refrigerate.'),
('22112', '7', 'Strain soup into a large bowl. Puree strained solids in batches in a blender or food processor, adding soup liquid to blend. Strain again over same bowl and discard solids. Wipe out Dutch oven, add soup and bring to a simmer.'),
('22112', '8', 'Strain soup into a serving bowl, dollop sour cream on top and garnish with thyme.'),
('22113', '1', 'Melt butter in a large Dutch oven over medium-high heat.'),
('22113', '2', 'Add green beans, bell pepper strips, and remaining ingredients, tossing to coat.'),
('22113', '3', 'Add 1/4 cup water.'),
('22113', '4', 'Cook, covered, 4 to 6 minutes. uncover and cook, stirring often, 1 to 2 more minutes or until water is evaporated and beans are crisp-tender.'),
('22113', '5', 'Sugar Snap Peas-and-Red Bell Pepper Toss: Substitute 1 lb. trimmed sugar snap peas for green beans. Proceed as directed.'),
('22114', '1', 'Spread cucumber and bell peppers onto several layers of heavy-duty paper towels. let stand 5 minutes to drain excess moisture.'),
('22114', '2', 'Scrape into a medium bowl using a rubber spatula.'),
('22114', '3', 'Add the cheeses, onion, salt, and garlic. stir with a fork until well blended.'),
('22114', '4', 'Spread about 1/2 cup cheese mixture over 4 bread slices. top each serving with 2 lettuce leaves and 1 bread slice.'),
('22115', '1', 'Place all ingredients in a food processor, and process until smooth.'),
('22118', '1', 'Roast the red peppers over a gas flame or under the broiler, turning occasionally, until charred all over.'),
('22118', '2', 'Transfer the peppers to a bowl, cover with plastic wrap and let cool. Peel, core and chop the peppers.'),
('22118', '3', 'In a small skillet, toast the pine nuts over moderate heat until golden, about 4 minutes.'),
('22118', '4', 'Let cool.'),
('22118', '5', 'Transfer the peppers and pine nuts to a blender.'),
('22118', '6', 'Add the garlic and whole basil leaves and blend until coarsely chopped.'),
('22118', '7', 'Add the olive oil and puree to a chunky pesto. Season with salt and pepper.'),
('22118', '8', 'In a large saucepan of boiling salted water, add the pasta and cook until al dente.'),
('22118', '9', 'Drain and cool slightly under running water.'),
('22118', '10', 'Transfer the pasta to a bowl and toss with the pesto. Season the pasta with salt and pepper. Top with the chopped basil and pecorino and serve at room temperature.'),
('22122', '1', 'Light a grill. Grill the red bell peppers over moderately high heat, turning with tongs, until they''re blackened all over.'),
('22122', '2', 'Transfer the charred peppers to a bowl  and let them cool completely. Peel the  peppers and discard the skins, seeds and cores. Coarsely chop the peppers.'),
('22122', '3', 'In a food processor, combine the peppers, walnuts, crushed crackers, pomegranate molasses, lemon juice, cumin  and Aleppo pepper and process until  fairly smooth. With the machine on, add the 1 tablespoon of olive oil and process until creamy. Season with salt and pepper and transfer to a bowl.'),
('22122', '4', 'Drizzle with olive oil and garnish with the parsley.'),
('22122', '5', 'Serve the dip with the fennel wedges.'),
('22123', '1', 'Preheat the broiler. Roast the peppers under the broiler or over a gas flame, turning a few times, until charred all over. transfer to a work surface and let cool. Discard the skin, stems and seeds and cut the peppers into 2-by-1-inch strips.'),
('22123', '2', 'In a small bowl, combine the shallots with the garlic, red wine and sherry vinegars and a large pinch of salt.'),
('22123', '3', 'Let stand for 10 minutes. Stir in the olive oil and season with salt and pepper.'),
('22123', '4', 'Meanwhile, bring a large pot of salted water to a boil.'),
('22123', '5', 'Add the beans and cook until crisp-tender, about 4 minutes.'),
('22123', '6', 'Drain and spread out on a large baking sheet.'),
('22123', '7', 'Let cool to room temperature.'),
('22123', '8', 'In a large bowl, combine the peppers with the beans, tomatoes, mint and parsley.'),
('22123', '9', 'Add the shallot dressing and toss well. Sprinkle with the almonds and serve.'),
('22124', '1', 'Stir together all ingredients in a large bowl. Cover and chill until ready to serve.'),
('22127', '1', 'Heat olive oil in a saucepan over medium heat.'),
('22127', '2', 'Add couscous. saut 3 minutes.'),
('22127', '3', 'Add bell pepper and onion. saut 4 minutes.'),
('22127', '4', 'Add chicken stock and tomato paste. bring to a boil. Cover, reduce heat, and simmer 10 minutes.'),
('22130', '1', 'Combine peppers, onion, garlic, vinegar, honey, mustard, chipotle and salt and pepper in a blender and blend until smooth. With the motor running, slowly add the oil and blend until emulsified. Strain sauce into a bowl.'),
('22130', '2', 'Cook''s Note: This classic sauce is great on grilled veggies, chicken, fish and steak.'),
('22133', '1', 'In a medium skillet, heat the vegetable oil.'),
('22133', '2', 'Add the almonds and cook over moderate heat, stirring, until golden, about 5 minutes. transfer to paper towels and let cool, then coarsely chop.'),
('22133', '3', 'Arrange the peppers on plates. In a bowl, combine the olive oil, vinegar, garlic, capers, thyme and marjoram. season with salt and pepper and drizzle over the peppers. Top with the green olives, almonds and cheese. Sprinkle with the parsley and serve with crusty bread.'),
('22136', '1', 'Cut the ciabatta crosswise into 4 even pieces.'),
('22136', '2', 'Cut off a very thin layer from the top and bottom crusts. Halve each ciabatta horizontally. arrange 6 coppa slices on the bottom half of each sandwich, then top with 1 sliced cherry pepper and the arugula.'),
('22136', '3', 'Drizzle a little oil and vinegar over the arugula and season with salt and pepper. Close the sandwiches.'),
('22136', '4', 'Heat 4 teaspoons of olive oil in each of 2 large cast-iron skillets.'),
('22136', '5', 'Add 2 of the sandwiches to each skillet and weight them down with a smaller cast-iron skillet or other heavy pan. Cook over moderately high heat until browned and crisp, 2 minutes per side.'),
('22136', '6', 'Cut the panini in half and serve hot.'),
('22140', '1', 'Preheat broiler.'),
('22140', '2', 'Cut bell pepper in half lengthwise. discard seeds and membranes.'),
('22140', '3', 'Place pepper halves, skin sides up, on a foil-lined baking sheet. flatten with hand. Broil 10 minutes or until blackened.'),
('22140', '4', 'Place in a zip-top plastic bag. seal.'),
('22140', '5', 'Let stand 10 minutes. Peel.'),
('22140', '6', 'Place bell pepper and remaining ingredients in a food processor. process until smooth.'),
('22142', '1', 'Cover corn with water. let stand 30 minutes.'),
('22142', '2', 'Drain.'),
('22142', '3', 'Remove husks from corn. discard husks. Scrub silks from corn. set corn aside.'),
('22142', '4', 'Prepare grill.'),
('22142', '5', 'Place corn on grill rack. cook 25 minutes or until corn is lightly browned, turning every 5 minutes. Cool.'),
('22142', '6', 'Cut kernels from ears of corn to measure 2 cups. Set kernels aside. discard cobs.'),
('22142', '7', 'Cut bell peppers in half lengthwise. flatten with hand. Discard seeds and membranes.'),
('22142', '8', 'Place bell pepper halves, skin sides down, on grill rack. Cook 20 minutes or until blackened.'),
('22142', '9', 'Place in a zip-top plastic bag. seal.'),
('22142', '10', 'Let stand 15 minutes. Peel and finely chop to measure 3/4 cup.'),
('22142', '11', 'Combine corn, bell peppers, and remaining ingredients in a medium bowl. Cover and chill.'),
('22150', '1', 'Place all ingredients in container of a food processor, and pulse several times until well blended.'),
('22150', '2', 'Place mixture in a small saucepan. cook over medium heat 5 minutes or until thoroughly heated.'),
('22154', '1', 'In a large saucepan, cover the beans with 3 inches of cold water and bring to a boil. Cook over moderate heat until the beans are barely tender, about 30 minutes.'),
('22154', '2', 'Drain.'),
('22154', '3', 'Heat the olive oil in a large saucepan.'),
('22154', '4', 'Add the onion and bell pepper and cook over moderate heat until softened, about 7 minutes.'),
('22154', '5', 'Add the sausage and cook for 4 minutes, crumbling it with a spoon.'),
('22154', '6', 'Add the beans, tomatoes, stock, thyme and crushed red pepper and season with salt and pepper. Cover partially and simmer over moderate heat until the beans are tender, about 20 minutes.'),
('22154', '7', 'Add the potatoes, cover partially and cook until tender, about 15 minutes longer.'),
('22154', '8', 'Remove the thyme sprigs. Stir in the parsley and serve.'),
('22155', '1', 'Cut first 5 ingredients into 1-inch pieces.'),
('22155', '2', 'Saut onion and garlic in hot oil in a large skillet over medium heat 5 to 7 minutes or just until onion is tender. Stir in tomatoes and next 2 ingredients, and saut 8 to 10 minutes or just until eggplant begins to soften. Stir in bell peppers, zucchini, and squash. cover and cook, stirring occasionally, 8 to 10 minutes or until vegetables are tender and liquid is slightly reduced. Stir in basil.'),
('22155', '3', 'Add salt and freshly ground pepper to taste, and saut 3 minutes.'),
('22157', '1', 'Heat the oil in a large saucepan over medium heat.'),
('22157', '2', 'Add the onion, garlic, and red pepper. Saut until fragrant, about 3 minutes.'),
('22157', '3', 'Add the ground beef and brown, about 5 minutes. Stir in the tomato paste, chili powder, cumin, black pepper, cinnamon, and salt. Simmer, stirring occasionally, until the sauce has thickened slightly, about 12 minutes. Spoon onto the buns, sprinkle with the Cheddar, and top each sandwich with a dollop of the sour cream.Tip: If you have any leftover filling, use it for tacos the next day. Scoop the meat into a shell and add salsa.'),
('22165', '1', 'Heat a large nonstick skillet coated with cooking spray over medium-high heat.'),
('22165', '2', 'Add sausage to pan. cook 8 minutes or until lightly browned, turning occasionally.'),
('22165', '3', 'Remove from pan. cool slightly.'),
('22165', '4', 'Cut sausage into 1/2-inch-thick slices.'),
('22165', '5', 'Wipe pan with paper towels. recoat with cooking spray.'),
('22165', '6', 'Place pan over medium-high heat.'),
('22165', '7', 'Add peppers. saut 6 minutes.'),
('22165', '8', 'Add sausage. saut 2 minutes.'),
('22165', '9', 'Add garlic. saut 2 minutes.'),
('22165', '10', 'Add sauce. bring to a simmer. Reduce heat. cook 5 minutes, stirring occasionally.'),
('22165', '11', 'Remove from heat.'),
('22165', '12', 'Add mozzarella, stirring until melted.'),
('22165', '13', 'Place 1 cup pasta in each of 6 shallow bowls. spoon about 1 cup sausage mixture over each serving. Sprinkle each serving with 1 teaspoon Parmesan.'),
('22166', '1', 'Preheat oven to 45'),
('22166', '2', 'Heat a large skillet over medium-high heat.'),
('22166', '3', 'Combine 1/2 teaspoon salt, fennel seeds, 1/4 teaspoon black pepper, garlic powder, and oregano.'),
('22166', '4', 'Brush chicken with 1 1/2 teaspoons oil. sprinkle spice rub over chicken.'),
('22166', '5', 'Add 1 1/2 teaspoons oil to pan.'),
('22166', '6', 'Add chicken. cook 3 minutes or until browned. Turn chicken over. cook 1 minute. Arrange chicken in an 11 x 7inch baking dish coated with cooking spray.'),
('22166', '7', 'Bake at 450 for 10 minutes or until done.'),
('22166', '8', 'Heat remaining olive oil over medium-high heat.'),
('22166', '9', 'Add bell peppers, shallots, and rosemary. saut 3 minutes. Stir in broth, scraping pan to loosen browned bits. Reduce heat. simmer 5 minutes. Increase heat to medium-high. Stir in vinegar, 1/4 teaspoon salt, and 1/4 teaspoon pepper. cook 3 minutes, stirring frequently.'),
('22166', '10', 'Serve bell pepper mixture over chicken.'),
('22167', '1', 'Heat the oil in a large skillet over medium-high heat. Season the steak with 1/4 teaspoon of the salt and the pepper. Cook for 3 minutes. Turn and move to the sides of the skillet.'),
('22167', '2', 'Add the onion and cook, stirring occasionally, for 2 minutes.'),
('22167', '3', 'Add the bell pepper, season with the remaining salt, and cook until the vegetables are softened and the steak is medium-rare, 3 to 4 minutes more.'),
('22167', '4', 'Transfer the onion and bell pepper to a bowl.'),
('22167', '5', 'Transfer the steak to a cutting board.'),
('22167', '6', 'Place the tortillas in a microwave and warm on high for 1 1/2 minutes. Slice the steak and serve with the onion, bell pepper, tortillas, sour cream, salsa, and guacamole.'),
('22169', '1', 'Working in batches, place the tomatoes, garlic, onion, bell peppers, and cucumbers in the bowl of a food processor and pulse until almost pureed.'),
('22169', '2', 'Transfer to a large bowl and stir in the lemon juice, 1 1/2 teaspoons salt, and 1/2 teaspoon pepper. Ladle the soup into individual bowls and top with the goat cheese, corn, and cilantro.'),
('22169', '3', 'Drizzle with the olive oil and serve with the crusty bread (if using).Upgrade: Dress up this light dish by spooning crabmeat over each portion just before serving.'),
('22170', '1', 'For the frittata: Preheat the oven to 325 degrees F.'),
('22170', '2', 'In a large ovenproof saute pan over high heat, add the olive oil, onions, sausage, garlic and oregano, stirring frequently to break up the clumps.'),
('22170', '3', 'Add the roasted peppers and cook about 10 minutes.'),
('22170', '4', 'In a large bowl, whisk together the eggs, cream, feta cheese, smoked salt and pepper.'),
('22170', '5', 'Pour the mixture into the saute pan and bake until the eggs are set and golden brown and the frittata pulls away from the sides slightly, about 35 minutes.'),
('22170', '6', 'Remove the frittata from the oven and let cool about 10 minutes.'),
('22170', '7', 'For the sauce: In a small bowl, combine the chives, lemon zest and juice, sour cream and olive oil. Season with salt and pepper.'),
('22170', '8', 'Cut the frittata into pieces and serve with dollop of the sour cream sauce.'),
('22171', '1', 'Preheat oven to 35'),
('22171', '2', 'Place mini phyllo pastry shells, on a baking sheet.'),
('22171', '3', 'Cut Brie cheese, into 30 very small pieces. Spoon rounded 1/4 teaspoon red pepper jelly into each shell. top with cheese. Sprinkle with almonds.'),
('22171', '4', 'Bake tartlets 5 to 6 minutes or until cheese is melted.'),
('22172', '1', 'Cook the penne according to the package directions. Meanwhile, heat the oil in a large saucepan over medium heat.'),
('22172', '2', 'Add the bell peppers, salt, and 1/4 teaspoon of the black pepper. Cover and cook for 4 minutes. Stir in the garlic and red pepper flakes and cook for 1 to 2 minutes.'),
('22172', '3', 'Add the pasta sauce and cook until heated through, about 3 minutes.'),
('22172', '4', 'Drain the pasta and divide it among individual bowls. Top with the sauce, a dollop of the ricotta, and the remaining black pepper.'),
('22174', '1', 'Combine all ingredients into a small bowl.'),
('22174', '2', 'Serve with steak, carnitas, or carne asada.'),
('22178', '1', 'Combine 1 teaspoon cornstarch, 1 tablespoon soy sauce, and next 4 ingredients (through hot pepper sauce) in a small bowl. stir with a whisk.'),
('22178', '2', 'Combine remaining 2 3/4 teaspoons cornstarch, remaining 1 tablespoon soy sauce, and chicken in a medium bowl. toss well to coat.'),
('22178', '3', 'Heat a large nonstick skillet over medium-high heat.'),
('22178', '4', 'Add cashews to pan. cook 3 minutes or until lightly toasted, stirring frequently.'),
('22178', '5', 'Remove from pan.'),
('22178', '6', 'Add oil to pan, swirling to coat.'),
('22178', '7', 'Add chicken mixture to pan. saut 2 minutes or until lightly browned.'),
('22178', '8', 'Remove chicken from pan. place in a bowl.'),
('22178', '9', 'Add bell pepper to pan. saut 2 minutes, stirring occasionally.'),
('22178', '10', 'Add garlic and ginger. cook 30 seconds.'),
('22178', '11', 'Add chicken and cornstarch mixture to pan. cook 1 minute or until sauce is slightly thick. Sprinkle with cashews and green onions.'),
('22178', '12', 'Quick rice pilaf: Cook 1 (10-ounce) package frozen white rice (such as Birds Eye Steam'),
('22178', '13', 'Fresh) according to package directions.'),
('22178', '14', 'Combine cooked rice, 2 tablespoons drained chopped water chestnuts, 1/2 teaspoon crushed red pepper, 1/4 teaspoon salt, and 1/4 teaspoon freshly ground black pepper.'),
('22180', '1', 'To prepare dressing, combine first 6 ingredients, stirring with a whisk.'),
('22180', '2', 'To prepare salad, cook pasta in boiling water 6 minutes or until al dente.'),
('22180', '3', 'Add bell peppers to pasta in pan. cook 10 seconds.'),
('22180', '4', 'Drain.'),
('22180', '5', 'Combine pasta mixture and half of dressing in a large bowl. cool mixture to room temperature.'),
('22180', '6', 'Add remaining dressing, tomato, and remaining ingredients. toss gently to coat. Cover and chill at least 1 hour.'),
('22189', '1', 'Heat the oil in a large saucepan over medium-high heat.'),
('22189', '2', 'Add the carrots, onion, and poblano and cook, stirring, for 3 minutes.'),
('22189', '3', 'Add the beef and cook, breaking it up with a spoon, until it is no longer pink, 3 to 5 minutes.'),
('22189', '4', 'Add the tomato paste and cook, stirring, until it is slightly darkened, 1 minute.'),
('22189', '5', 'Add the beans, chili powder, 3 cups water, 1/2 teaspoon salt, and 1/4 teaspoon pepper. Simmer over medium heat until the vegetables are tender, about 10 minutes. Stir in the corn. Divide among bowls and top with the Cheddar and scallions. Make Ahead: You can cook the chili in advance and refrigerate it for up to 3 days or freeze it for up to 3 months.'),
('22192', '1', 'Bring a large pot of water to a boil.'),
('22192', '2', 'Heat a grill or grill pan to medium-high. In a large bowl, toss the onions, bell peppers, oil, 1/2 teaspoon salt, and 1/2 teaspoon pepper. Grill, turning occasionally, until tender, 8 to 10 minutes.'),
('22192', '3', 'Transfer to a cutting board and cut into bite-size pieces. Cook the pasta according to the package directions. Reserve 1 cup of the cooking water, drain the pasta, and return the pasta to the pot.'),
('22192', '4', 'Add the grilled vegetables, spinach, the reserved pasta water, and 3/4 cup of the Parmesan to the pasta and toss to combine. Top with the basil and the remaining Parmesan before serving.'),
('22195', '1', 'Cook the gnocchi according to package directions, omitting salt and fat.'),
('22195', '2', 'Drain the gnocchi in a colander over a bowl, reserving 1/4 cup cooking liquid. Keep gnocchi warm.'),
('22195', '3', 'Heat 1 teaspoon olive oil in large nonstick skillet over medium-high heat.'),
('22195', '4', 'Add sausage to pan. saut 3 minutes or until lightly browned, stirring frequently.'),
('22195', '5', 'Remove sausage from skillet using a slotted spoon.'),
('22195', '6', 'Heat remaining 1 teaspoon oil in pan.'),
('22195', '7', 'Add fennel, bell pepper, and onion to pan. cook 13 minutes or until tender, stirring occasionally.'),
('22195', '8', 'Add sausage, gnocchi, cheese, black pepper, and reserved cooking liquid to pan. cook 1 minute or until cheese melts, stirring constantly.'),
('22195', '9', 'Remove from heat. stir in parsley.'),
('22197', '1', 'Heat the oil in a large pot over medium-high heat.'),
('22197', '2', 'Add the onions, bell peppers, and garlic and cook, stirring occasionally, until soft, 6 to 8 minutes.'),
('22197', '3', 'Add the beef and cook, breaking it up with a spoon, until no longer pink, 5 to 7 minutes.'),
('22197', '4', 'Add the tomato paste, chili powder, and cumin and cook, stirring, for 2 minutes.'),
('22197', '5', 'Add the beer, beans, the tomatoes and their juices, 2 1/2 teaspoons salt, and 1/2 teaspoon pepper. Simmer over medium heat, stirring occasionally, until thickened, 20 to 25 minutes.'),
('22197', '6', 'Serve with the corn bread and toppings as desired.'),
('22198', '1', 'Heat 1/2 teaspoon oil in a large nonstick skillet coated with cooking spray over medium-high heat.'),
('22198', '2', 'Add green onions. saut 1 minute.'),
('22198', '3', 'Add bell pepper. saut 1 minute.'),
('22198', '4', 'Add mushrooms. cook 3 minutes, stirring frequently. Stir in tomato, 1/4 teaspoon salt, and black pepper. cook 30 seconds.'),
('22198', '5', 'Remove vegetable mixture from pan. cover and keep warm.'),
('22198', '6', 'Place 1/4 teaspoon salt, parsley, eggs, and egg whites in a bowl. stir well with a whisk to combine.'),
('22198', '7', 'Place 1/2 teaspoon oil and butter in skillet over medium-high heat until butter melts.'),
('22198', '8', 'Add egg mixture to pan. cook until edges begin to set (about 2 minutes). Slide front edge of a spatula between edge of omelet and pan. Gently lift edge of omelet, tilting pan to allow some uncooked egg mixture to come in contact with pan. Repeat procedure on opposite edge of omelet. Continue cooking until the center is just set (about 7 minutes).'),
('22198', '9', 'Spoon vegetable mixture evenly over 1/2 of omelet. top vegetable mixture with cheese. Loosen omelet with a spatula. fold in half. Carefully slide omelet onto a serving platter.'),
('22198', '10', 'Cut omelet into 4 wedges. top with sour cream.'),
('22198', '11', 'Serve immediately.'),
('22199', '1', 'Cut steak in half lengthwise.'),
('22199', '2', 'Cut each half across the grain into 1/8-inch-thick slices.'),
('22199', '3', 'Combine beef, soy sauce, garlic, and black pepper. toss well. Cover and refrigerate 30 minutes.'),
('22199', '4', 'Combine 1 1/2 tablespoons water, oyster sauce, and crushed red pepper in a small bowl. set aside.'),
('22199', '5', 'Cut broccoli into florets. Peel broccoli stems. cut stems diagonally into 1/4-inch-thick slices.'),
('22199', '6', 'Heat 1 tablespoon canola oil in a large nonstick skillet over medium-high heat.'),
('22199', '7', 'Add beef mixture to skillet. cook 3 minutes or until beef is browned, stirring constantly.'),
('22199', '8', 'Remove from heat.'),
('22199', '9', 'Transfer beef mixture to a bowl.'),
('22199', '10', 'Heat the remaining 1 tablespoon canola oil in pan over medium-high heat.'),
('22199', '11', 'Add broccoli. cook 2 minutes, stirring constantly.'),
('22199', '12', 'Add the remaining 2 tablespoons water. cook 1 minute, stirring constantly.'),
('22199', '13', 'Add bell pepper. cook 30 seconds, stirring constantly. Return beef mixture to pan. Stir in the oyster sauce mixture. cook until thoroughly heated.'),
('22199', '14', 'Serve over rice.'),
('22200', '1', 'Preheat broiler.'),
('22200', '2', 'Cut bell peppers in half lengthwise, and discard seeds and membranes.'),
('22200', '3', 'Place bell pepper halves, skin sides up, on a foil-lined baking sheet, and flatten with hand. Broil 15 for minutes or until blackened.'),
('22200', '4', 'Place in a zip-top plastic bag, and seal.'),
('22200', '5', 'Let stand 15 minutes. Peel and cut into strips.'),
('22200', '6', 'Combine bell peppers, green olives, and next 5 ingredients (olives through black pepper) in a bowl.'),
('22200', '7', 'Preheat oven to 35'),
('22200', '8', 'Divide the bell pepper mixture evenly among pizza crusts. sprinkle with cheese.'),
('22200', '9', 'Bake at 350 for 7 minutes or until cheese melts.'),
('22200', '10', 'Cut each into 12 wedges.'),
('22201', '1', 'Bring water to a boil in a small saucepan. gradually stir in couscous and salt.'),
('22201', '2', 'Remove from heat. cover and let stand 5 minutes. Fluff with a fork.'),
('22201', '3', 'Add bell peppers and remaining ingredients. toss gently to combine. Cover and chill.'),
('22203', '1', 'Working in batches, puree the tomatoes and bell pepper in a food processor and transfer to a large bowl. Stir in the vinegar and 1 1/2 teaspoons salt. Divide among serving bowls and top with the Feta, basil, pine nuts, oil, and 1/4 teaspoon pepper.'),
('22203', '2', 'Serve with the prosciutto, salami, and bread sticks, if desired.'),
('22205', '1', 'Peel sweet potatoes, and cut into 1/2-inch cubes.'),
('22205', '2', 'Cut yellow bell pepper into 1-inch pieces.'),
('22205', '3', 'Combine sweet potatoes, bell pepper, onions, and remaining ingredients in a large zip-top plastic bag. seal bag, and turn until vegetables are evenly coated.'),
('22205', '4', 'Remove vegetable mixture from bag, and place in a single layer in a lightly greased 11- x 15-inch jelly-roll pan.'),
('22205', '5', 'Bake at 450 for 30 to 35 minutes or until sweet potatoes are tender.'),
('22210', '1', 'Whirl garlic and almonds in a food processor until coarsely ground.'),
('22210', '2', 'Add peppers, oil, juice, and 1/4 cup water. whirl until the texture of salsa.'),
('22210', '3', 'Add cooked potato, salt, and pepper and pulse to blend, scraping bowl as needed.'),
('22210', '4', 'Serve with lettuce, jicama, and radishes.'),
('22214', '1', 'Heat oil in heavy large pot over medium-high heat.'),
('22214', '2', 'Add onions. saute until tender, about 12 minutes.'),
('22214', '3', 'Add garlic. stir 1 minute.'),
('22214', '4', 'Add squash and 5 1/2 cups broth. bring to boil. Reduce heat. cover and simmer until squash is soft, about 40 minutes. Cool slightly.'),
('22214', '5', 'Working in batches, puree soup in blender until smooth. Return puree to pot.'),
('22214', '6', 'Add 1 teaspoon thyme and orange peel. Thin soup with more broth if desired. Simmer 3 minutes. Season with salt and pepper. (Can be made 1 day ahead. Cool slightly. Cover and chill. Rewarm before serving, thinning with more broth if desired.)'),
('22214', '7', 'Ladle soup into bowls. Swirl 1 tablespoon Roasted Red Pepper Puree into soup in each bowl. Sprinkle with remaining 2 teaspoons thyme and serve.'),
('22214', '8', 'Per serving (including red pepper puree): calories, 200. total fat, 8 g. saturated fat, 1 g. cholesterol, 0. fiber, 8 g'),
('22214', '9', 'Gourmet'),
('22220', '1', 'Preheat the oven to 42'),
('22220', '2', 'Put the peppers on a cookie sheet, stemmed side down, and bake for 45 minutes, or until the skins are black. When they''re cool enough to handle, remove and discard the skins, cores and seeds. Finely dice 2 of the peppers.'),
('22220', '3', 'In a large saucepan, heat 2 tablespoons of the olive oil.'),
('22220', '4', 'Add the garlic, onion, cumin and crushed red pepper and cook over moderately low heat, stirring occasionally, until the onion is softened, about 10 minutes.'),
('22220', '5', 'Add the whole roasted peppers and the chicken broth and bring to a boil over high heat. Reduce the heat to low and simmer for 20 minutes.'),
('22220', '6', 'Add the orange juice, orange zest and cilantro.'),
('22220', '7', 'In a blender, puree the soup in batches. Return the soup to the saucepan and season with salt and pepper. keep hot.'),
('22220', '8', 'In a medium skillet, heat the remaining 1 tablespoon of olive oil until shimmering. Season the scallops with salt and pepper.'),
('22220', '9', 'Add the scallops to the skillet and cook over high heat until richly browned on the bottom, about 2 minutes. Turn the scallops and cook on the second side for 1 minute. Ladle the soup into bowls, garnish with the scallops and diced peppers and serve.'),
('22224', '1', 'Cook pasta according to package directions, omitting salt and fat.'),
('22224', '2', 'Drain and keep warm.'),
('22224', '3', 'Heat oil in a large skillet over medium heat.'),
('22224', '4', 'Add onion, and cook 8 minutes or until tender, stirring frequently.'),
('22224', '5', 'Add bell peppers. cook 2 minutes or until thoroughly heated. Increase heat to medium-high. Stir in vinegar. cook 1 minute or until liquid evaporates.'),
('22224', '6', 'Remove from heat. cool 5 minutes.'),
('22224', '7', 'Place bell pepper mixture in a blender. process until smooth. Return bell pepper mixture to pan. cook over low heat until warm.'),
('22224', '8', 'Combine half-and-half and tomato paste in a small bowl, stirring with a whisk. Stir tomato mixture into bell pepper mixture, stirring with a whisk until well combined. Stir in ground red pepper.'),
('22224', '9', 'Combine pasta and bell pepper mixture in a large bowl.'),
('22224', '10', 'Add 1/2 cup cheese, tossing to coat. Spoon 1 1/3 cups pasta into each of 6 bowls. top each serving with about 1 1/2 tablespoons cheese.'),
('22224', '11', 'Garnish with basil, if desired.'),
('22226', '1', 'Combine water and broth in a medium saucepan. bring to a simmer (do not boil). Keep broth mixture warm over low heat.'),
('22226', '2', 'Heat oil in a large saucepan over medium-high heat.'),
('22226', '3', 'Add rice, cumin, coriander (if desired), and garlic. saut 1 minute. Stir in 1/2 cup broth mixture. cook 2 minutes or until the liquid is nearly absorbed, stirring constantly.'),
('22226', '4', 'Add remaining broth mixture, 1/2 cup at a time, stirring constantly until each portion of liquid is absorbed before adding the next (about 20 minutes total). Stir in the onions, cheese, hot sauce, corn, and bell peppers. cook 3 minutes or until thoroughly heated.'),
('22227', '1', 'Process bell peppers, sugar, and 1 teaspoon salt in a blender, stopping once to scrape down sides.'),
('22227', '2', 'Pour into a small saucepan, and cook over medium heat 4 minutes or until thickened.'),
('22227', '3', 'Combine ground beef and remaining 1/4 teaspoon salt. shape into 8 thin patties.'),
('22227', '4', 'Combine cream cheese and jalapeo pepper. divide evenly in center of 4 patties. (Do not spread to edges.) Top with remaining patties. press edges to seal.'),
('22227', '5', 'Grill, covered with grill lid, over medium-high heat (350 to 40'),
('22227', '6', '4 to 5 minutes on each side or until done.'),
('22227', '7', 'Serve on buns with bell pepper ketchup and desired toppings.'),
('22228', '1', 'Heat the oil in a large nonstick skillet coated with cooking spray over medium heat.'),
('22228', '2', 'Add the onion, bell pepper, and thyme. cook for 25 minutes or until golden brown, stirring frequently.');