INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('19071', '5', 'Remove the skillet from the heat, and arrange the radicchio wedges in the baking dish in one layer. Spoon the onion all around, and pour the skillet liquid over.'),
('19071', '6', 'Drizzle on the remaining 2 tablespoons olive oil, season with freshly ground black pepper, and sprinkle the grated cheese in an even layer, covering the radicchio.'),
('19071', '7', 'Tent the dish with aluminum foil, pressing it against the sides.'),
('19071', '8', 'Bake covered for about 20 minutes, remove the foil, and bake another 5 minutes or more, until the radicchio wedges are tender and moist and glazed golden on top.'),
('19071', '9', 'var article'),
('19071', '10', 'Type_27_data = {};'),
('19071', '11', 'article'),
('19071', '12', 'Type_27_data.init_step_by_step_images = 0;'),
('19076', '1', 'Microwave rice according to package directions. Set aside; keep warm.'),
('19076', '2', 'Combine edamame and 3 tablespoons water in a small bowl. Cover with plastic wrap. Microwave at HIGH 3 minutes.'),
('19076', '3', 'Let stand 2 minutes; drain.'),
('19076', '4', 'Combine rice, edamame, chicken, and next 5 ingredients in a large bowl; toss to coat.'),
('19076', '5', 'Serve over radicchio.'),
('19083', '1', 'If you are planning to roast your red pepper, rather than use store bought, place your pepper under broiler to blacken. See red pepper method below.'),
('19083', '2', 'Preheat a large nonstick skillet over high heat. Pat tuna steaks dry and season with a little coarse salt.'),
('19083', '3', 'Drizzle extra virgin olive oil over tuna and lightly coat steaks on both sides. Coat 1 side of the steaks with a generous amount of coarse ground black pepper. When the pan is very hot, add steaks, peppered side down. Sear and brown steaks 2 minutes, then turn, and immediately reduce heat to medium. Loosely cover pan with aluminum foil tent and allow steaks to cook 5 minutes for rare, 7 minutes for medium. Steaks should be firm, but have a little give and some pink should remain at the center.'),
('19083', '4', 'In a second skillet over moderate heat, coat pan with olive oil, add garlic and onion, and saute 3 minutes to soften onion bits.'),
('19083', '5', 'Add beans and chopped roasted red pepper to the pan.'),
('19083', '6', 'Heat beans through, 2 to 3 minutes. Stir in rosemary and parsley and season beans with salt and pepper.'),
('19083', '7', 'Combine escarole and radicchio in shallow dish. Coat greens with lemon juice, then a drizzle of oil. Season salad with coarse salt and toss well.'),
('19083', '8', 'To serve, pile a serving of beans on a dinner plate and top with tuna steak.'),
('19083', '9', 'Serve salad greens along side beans and fish. You can also serve this with sliced bread that has been toasted and then rubbed with half a garlic clove.'),
('19083', '10', 'To roast red peppers: Preheat broiler to high. Split and seed pepper and place skin side up close to hot broiler. Blacken skins of pepper.'),
('19083', '11', 'Transfer pepper to brown paper bag and seal.'),
('19083', '12', 'Let pepper cool to handle. Peel charred skins away from pepper flesh.'),
('19084', '1', 'Watch how to make this recipe.'),
('19084', '2', 'Heat the oil in a heavy medium skillet over medium-low heat.'),
('19084', '3', 'Add the garlic, let it cook for 1 to 2 minutes and then add the herbs and saute until fragrant, about 30 seconds. Cool to room temperature.'),
('19084', '4', 'Whisk in the lemon juice. Season the dressing with salt and pepper, to taste.'),
('19084', '5', 'Prepare the barbecue (medium-high heat). Pat the scallops and squid dry with paper towels and thread them onto skewers.'),
('19084', '6', 'Brush them with 2 tablespoons of the dressing. Sprinkle with salt and pepper. Grill the scallops and squid until just cooked through, turning once, 2 to 3 minutes per side. Cool completely.'),
('19084', '7', 'Cut the squid crosswise into 1/4-inch-wide rings.'),
('19084', '8', 'Combine the arugula, carrots, bell peppers, and cannellini beans in a large bowl. Toss with 1/2 cup of the dressing to coat.'),
('19084', '9', 'Place 1 large or 2 medium radicchio leaves on each of 4 plates. Spoon the bean salad into the radicchio cups. Top with the scallops and squid.'),
('19084', '10', 'Drizzle the remaining dressing over the seafood and serve.'),
('19086', '1', 'Place the prosciutto on a large platter. Julienne all apples and place in a mixing bowl.'),
('19086', '2', 'Add the poppy seeds, olive oil, vinegar and radicchio and salt and pepper, to taste and toss to coat. Arrange the salad in the center of the plate and shave curls of Parmigiano-Reggiano over the salad and ham.'),
('19086', '3', 'Serve immediately.'),
('19087', '1', 'Watch how to make this recipe.'),
('19087', '2', 'To flaked salmon, add egg whites, parsley, the zest and juice of 1 lemon, 2/3 of the total amount of chopped garlic, the bread crumbs and lots of black pepper and a little salt.'),
('19087', '3', 'Mix together and form 4 large patties or 8 mini patties.'),
('19087', '4', 'To a salad bowl add the remaining zest and lemon juice, remaining garlic, chopped anchovies, Dijon mustard, and Worcestershire.'),
('19087', '5', 'Whisk in about 1/4 cup extra-virgin olive oil and cheese.'),
('19087', '6', 'Add lots of black pepper, no salt.'),
('19087', '7', 'Add shredded lettuces to the bowl and toss to coat evenly. Now, season the slaw with salt to taste, if necessary.'),
('19087', '8', 'Preheat 2 tablespoons, of extra-virgin olive oil, 2 turns of the pan, in a nonstick skillet over medium to medium high heat. Cook salmon patties 2 to 3 minutes on each side for mini patties, 4 minutes on each side for large patties.'),
('19087', '9', 'Serve salmon patties atop Caesar Slaw.'),
('19088', '1', 'Watch how to make this recipe.'),
('19088', '2', 'In a large bowl toss together the romaine, radicchio, and scallions. In a small bowl, whisk together the olive oil, lemon juice, dill, salt and pepper, to taste.'),
('19088', '3', 'Pour the dressing onto the salad and toss.'),
('19089', '1', 'Whisk the marmalade or jam together with vinegar and oil, streaming extra-virgin olive oil in.'),
('19089', '2', 'Add shredded radicchio to salad bowl along with peppers and onions. Toss to combine the salad and season the slaw with salt and pepper, to taste.'),
('19094', '1', 'Dressing: Simmer the port in a small saucepan until reduced to 2 tablespoons.'),
('19094', '2', 'Let cool, then whisk in the vinegar, shallot, and salt and pepper, to taste. Gradually whisk in the olive oil.'),
('19094', '3', 'Salad: In a large bowl, toss the frisee or mesclun, radicchio, and pear. Divide the salad among 4 plates.'),
('19094', '4', 'Drizzle with the dressing; you probably won''t use it all. With a vegetable peeler, shave the cheese over top. Scatter the walnuts on top and serve immediately.'),
('19094', '5', 'In a large, heavy-bottomed skillet, heat about 1-inch of oil to 350 degrees F.'),
('19094', '6', 'Bring a large pot of water to a boil.'),
('19094', '7', 'Add walnuts and blanch for 30 seconds.'),
('19094', '8', 'Drain and transfer nuts to a medium bowl. While nuts are still hot and slightly wet, add confectioners'' sugar and toss to coat nuts. Stir and toss until all the sugar has melted into the nuts; if bits of un-melted sugar remain on the nuts, they will not fry properly.'),
('19094', '9', 'Stir the nuts again before frying. Using a large slotted spoon, transfer a few nuts to the hot oil, allowing the foam to subside before adding another spoonful. (Otherwise, the oil could foam over and burn you.) Fry in small batches until the nuts are medium brown, about 45 seconds; be careful not to overcook. Scatter on an unlined baking sheet to cool slightly.'),
('19094', '10', 'In a small bowl, stir together cayenne, cinnamon, a pinch of salt, and pepper, to taste.'),
('19094', '11', 'While the nuts are still warm, transfer them to a bowl and sprinkle evenly with about half of the spice mix. Toss well to distribute the spices and then taste a nut.'),
('19094', '12', 'Add more spice mix, to taste, and toss well after each addition. When cool, pack in an airtight jar. They will keep at room temperature for at least 2 weeks.'),
('19095', '1', 'Preheat the oven to 350F.'),
('19095', '2', 'Place the bread slices in a bowl, sprinkle the olive oil over them, and toss.'),
('19095', '3', 'Spread the slices out in a single layer on a baking sheet, and bake until golden brown, about 20 minutes. Set them aside.'),
('19095', '4', 'Separate the romaine lettuce leaves, discarding any tough or bruised leaves. Rinse the leaves under cold running water, drain them well, and pat them dry. Tear the leaves into pieces.'),
('19095', '5', 'Place the romaine in a large salad bowl, and add the radicchio, cucumber, tomato, onion, feta, and parsley.'),
('19101', '1', 'Preheat the oven to 35'),
('19101', '2', 'In a small saucepan, cover the farro with the water and bring to a boil. Cover and cook over low heat until tender, 18 to 20 minutes.'),
('19101', '3', 'Drain the farro and transfer it to a large bowl to cool slightly.'),
('19101', '4', 'Meanwhile, spread the hazelnuts in a pie plate and toast in the oven for about 14 minutes, or until lightly browned and fragrant.'),
('19101', '5', 'Let cool, then transfer the nuts to a kitchen towel and rub off the skins. Coarsely chop the nuts.'),
('19101', '6', 'If using fresh peas, cook them in a medium saucepan of boiling water until tender, about 5 minutes; drain.'),
('19101', '7', 'In a small skillet, toast the coriander seeds over moderate heat until fragrant and lightly browned, about 3 minutes.'),
('19101', '8', 'Transfer to a mortar and coarsely grind.'),
('19101', '9', 'Add the garlic, lemon zest, sea salt and curry powder to the mortar and pound to a paste.'),
('19101', '10', 'Add the olive oil and lemon juice and stir until combined.'),
('19101', '11', 'Stir half of the dressing into the farro and let stand until cooled to room temperature.'),
('19101', '12', 'Add the chicken, peas, celery, radishes, parsley, chervil and the remaining dressing. Season the salad with pepper and toss to mix. Just before serving, add the olives and hazelnuts. Mound the chicken salad on the radicchio leaves and serve.'),
('19102', '1', 'Preheat oven to 400°F.'),
('19102', '2', 'Place head of garlic on sheet of foil.'),
('19102', '3', 'Drizzle with 2 tablespoons oil; wrap foil around garlic andcrimp to seal tightly.'),
('19102', '4', 'Place garlic and corn on rimmed baking sheet.'),
('19102', '5', 'Bake until corn is tender and garlic is soft, about 25 minutes for corn and 40 minutes for garlic. Cool slightly.'),
('19102', '6', 'Squeeze garlic out of skins into large bowl; add any oil from foil.'),
('19102', '7', 'Add lemon juice, lemon peel, and 3 tablespoons oil; mash garlic, then whisk mixture. Shuck corn; cut kernels from cob and transfer to same bowl.'),
('19102', '8', 'Meanwhile, cook pasta in pot of boiling salted water until tender but still firm to bite.'),
('19102', '9', 'Drain. Rinse with cold water; drain well.'),
('19102', '10', 'Place in medium bowl; toss with 1 tablespoon oil. Using kitchen shears, cut pasta crosswise several times.'),
('19102', '11', 'Add pasta, greens, radicchio, ricotta, grated Parmesan, and herbs to bowl with garlic mixture; toss to coat. Season with salt and pepper.'),
('19102', '12', 'Garnish with shaved Parmesan.'),
('19105', '1', 'In blender on high, blend tahini and garlic until smooth, about 30 seconds. With motor running, add 1/2 cup water, lemon juice, olive oil, salt, and pepper and blend until incorporated, about 30 seconds. (Tahini sauce can be prepared ahead and refrigerated, in airtight container, up to 2 days. If sauce is too thick after storage, whisk in several drops of water to thin.)'),
('19109', '1', 'Combine the anchovy paste, mustard, garlic, Worcestershire and lemon juice, stream in olive oil to form dressing then stir in cheese and lots of black pepper.'),
('19109', '2', 'Add lettuce and croutons or cubed toasted bread and toss to combine.'),
('19110', '1', 'Blend the chopped basil, oil, and vinegar in a food processor or blender until basil is mostly pureed. Season with salt and pepper.'),
('19110', '2', 'Overlap radicchio, mango, mozzarella, and basil leaves on plates.'),
('19110', '3', 'Drizzle with vinaigrette and serve, passing additional vinaigrette on the side.'),
('19123', '1', 'Trim, rinse, and dry radishes. Slice radishes thinly and put in a bowl.'),
('19123', '2', 'Add rice vinegar, ginger, and 1/4 tsp. salt. Toss to combine.'),
('19123', '3', 'Lay sorrel leaves in a stack and slice them crosswise into thin ribbons. Toss sorrel with radishes.'),
('19123', '4', 'Add additional salt to taste.'),
('19123', '5', 'Serve immediately.'),
('19124', '1', 'In a blender, puree the sorrel with 3/4 cup of the chicken stock until smooth. In a small bowl, sprinkle the gelatin over the remaining 1/4 cup of chicken stock and let stand until softened, about 2 minutes. Microwave the gelatin at medium power just until melted, 5 to 10 seconds.'),
('19124', '2', 'Add the gelatin mixture to the blender along with 2 tablespoons of the lemon juice and the red wine vinegar. Season with salt and white pepper and puree until very smooth.'),
('19124', '3', 'Add 1 cup of the heavy cream and pulse just until very lightly whipped, about 1 minute.'),
('19124', '4', 'Transfer the sorrel mousse to a measuring cup and pour into 6 small glasses. Refrigerate the mousse until set, about 4 hours.'),
('19124', '5', 'Meanwhile, in a bowl, whisk the remaining 1/4 cup of cream and 1 tablespoon of lemon juice with the crme frache to soft peaks. Season with salt and white pepper. Dollop the lemon cream on the mousse and top with the caviar.'),
('19124', '6', 'Serve chilled.'),
('19127', '1', 'Light a grill. In a small bowl, combine the 1/4 cup of extra-virgin olive oil with the lemon juice and season the dressing with salt and black pepper.'),
('19127', '2', 'Grill the torpedo onions or shallots over moderately high heat, turning a few times, until charred on the outside and just tender within, about 20 minutes.'),
('19127', '3', 'Transfer the onions to a bowl, cover with a damp cloth and let steam for 15 minutes. Peel the onions and trim the ends.'),
('19127', '4', 'Put the onions in a large bowl and keep warm.'),
('19127', '5', 'In a bowl, drizzle the squid bodies with olive oil and season liberally with salt and pepper. Grill the squid over high heat until it is lightly charred and tender, about 1 minute per side.'),
('19127', '6', 'Transfer the squid bodies to the bowl with the grilled onions. Repeat with the tentacles.'),
('19127', '7', 'Add the sorrel leaves and the dressing to the onions and squid and toss to combine. Season the salad with salt and pepper. Arrange the salad on 4 plates and serve right away.'),
('19130', '1', 'Roast bell pepper. Peel and chop pepper; purée with red wine vinegar, vanilla, and sugar in a blender until smooth.'),
('19130', '2', 'With machine running, gradually add olive oil. Season with salt and pepper.'),
('19130', '3', 'Halve and pit avocados and season with salt and pepper.'),
('19130', '4', 'Drizzle with olive oil and place cut side down on a medium-hot grill until nicely charred, about 5 minutes. Peel and thickly slice.'),
('19130', '5', 'Toss with arugula or sorrel and peaches.'),
('19130', '6', 'Drizzle dressing over.'),
('19130', '7', 'Bon Appétit'),
('19131', '1', 'In a large skillet, bring the vegetable stock and butter to a boil over moderate heat.'),
('19131', '2', 'Add the radishes and cook, stirring occasionally, until they are crisp-tender and the liquid has thickened slightly, about 15 minutes. Season with salt and pepper and transfer to a shallow bowl. Scatter the sorrel over the top and serve.'),
('19136', '1', 'Bring the water to a boil, remove from the heat, and add the sorrel and ginger.'),
('19136', '2', 'Let steep about 45 minutes, strain.'),
('19136', '3', 'Add ice cubes to a shaker. For 2 servings, add to the shaker about 2 or 3 ounces strained juice, 2 ounces simple syrup, a splash of lime juice, and a jigger of rum. Shake well and pour.'),
('19139', '1', 'Put the eggs, butter, and some salt and pepper in a saucepan or skillet with sloping sides. Turn the heat to medium high and begin to beat the mixture with a whisk, stirring almost constantly but not too fast; you do not want the mixture to become foamy. If you are using a nonstick pan or skillet, use a wooden spoon instead of a whisk.'),
('19139', '2', 'Once the butter has melted, the mixture will begin to thicken and develop small curds; this will take from 3 to 8 minutes, depending on your pan and cooktop. If the eggs begin to stick to the bottom of the pan, remove from the heat for a moment, continuing to whisk, and then return to the flame.'),
('19139', '3', 'When the eggs are very creamy, with small curds all over--not unlike very loose oatmeal--they are just about ready. Stir in the smoked salmon and cook for a minute, just to warm it.'),
('19139', '4', 'Remove from the heat, stir in the cream cheese and sorrel, and taste for salt and pepper.'),
('19139', '5', 'Garnish with chives and serve.'),
('19140', '1', 'In a large saucepan bring vegetable broth to a boil over medium heat.  Stir in rice and continue to boil for about 8 minutes.  Stir in sorrel and return to a boil.'),
('19140', '2', 'Remove from heat and puree in batches in a blender or food processor or using an immersion blender.'),
('19140', '3', 'Return to medium-low heat and stir in cream, salt and pepper.'),
('19140', '4', 'Heat through and serve.'),
('19142', '1', 'Preheat oven to 425°F.'),
('19142', '2', 'Wrap beets in foil in 2 packages (3 per package) and roast in middle of oven until tender, 1 1/4 to 1 1/2 hours. When cool enough to handle, peel beets and cut off stems and root ends. Halve beets crosswise and arrange, cut sides down, on a work surface.'),
('19142', '3', 'Cut out a cylinder from each half with cookie cutter. Halve each cylinder lengthwise, then cut crosswise into generous 1/4-inch-thick slices.'),
('19142', '4', 'Line a tray with plastic wrap and brush plastic wrap with some oil.'),
('19142', '5', 'Cut cheese logs crosswise into 1/4-inch-thick slices with an oiled knife, then halve slices. Arrange cheese slices in 1 layer on tray and brush with some oil, then top each with a slice of beet.'),
('19142', '6', 'Arrange sorrel leaf halves, veined sides up, on work surface. Put a cheese and beet stack in middle of each leaf half, then wrap sorrel over stack and secure with a pick.'),
('19145', '1', 'Bring a medium saucepan of water to a boil. Halve the chard leaves lengthwise and remove the thick ribs and stems.'),
('19145', '2', 'Cut the ribs and stems into 1/4-inch dice and transfer 3/4 cup to a large bowl; discard the rest. Blanch the chard leaves in the boiling water until just wilted, about 10 seconds.'),
('19145', '3', 'Transfer the chard leaves to a bowl of ice water to cool, then drain and pat dry.'),
('19145', '4', 'Bring the water in the saucepan back to a boil.'),
('19145', '5', 'Add the nettles and blanch for 1 minute (10 seconds if using spinach).'),
('19145', '6', 'Drain and refresh in ice water, then drain and squeeze dry. Coarsely chop the nettles and add to the chard stems, along with the parsley, sorrel, chives, zucchini, lovage, thyme, garlic, Pecorino, bread crumbs and 4 tablespoons of the olive oil. Season with salt and pepper and gently toss.'),
('19145', '7', 'Make a slit in the side of each zucchini blossom and snap off the pistils in the center.'),
('19145', '8', 'Spread the chard leaves on a work surface and pat completely dry. Spoon an equal amount of filling on each leaf. Press lightly and season with salt and pepper. Tightly roll up the chard leaves cigar-style. Stuff the chard rolls into 12 of the zucchini blossoms. Carefully fit these into the remaining 12 blossoms, overlapping the petals to seal.'),
('19145', '9', 'Arrange the blossoms, seam side down, in a large skillet in a single layer.'),
('19145', '10', 'Add 1/2 cup of water and the remaining 2 tablespoons of olive oil and bring to a simmer. Cover tightly and cook over moderately high heat until just tender when pierced with a knife, about 10 minutes. Uncover and cook until the liquid is reduced to 3 tablespoons, about 2 minutes longer.'),
('19145', '11', 'Transfer the zucchini blossoms to a platter and drizzle the pan juices on top.'),
('19146', '1', 'Place the quail’s eggs in a saucepan, cover with cold water and bring to the boil. Simmer for between 30 seconds (soft-boiled) and two minutes (hard-boiled), depending on how you like them cooked. Refresh in cold water, then peel.Blanch the peas (or fava beans) in boiling water for 30 seconds, then drain and refresh. Set Aside.In a separate pan of boiling water, cook the potatoes for 15 to 20 minutes, or until they are soft but not falling apart.While the potatoes are cooking, place the basil, parsley, pine nuts, parmesan and garlic in a food processor and blitz to a paste.'),
('19146', '2', 'Add the oil and pulse until you get a runny pesto.'),
('19146', '3', 'Pour into a large bowl.'),
('19146', '4', 'Drain the potatoes, then cut in two (or more pieces for larger potatoes) as soon as you can handle them (they will absorb more flavor when hot).'),
('19146', '5', 'Add to the bowl and toss with the pesto, vinegar, sorrel and peas.'),
('19146', '6', 'Mix well, even crushing the potatoes slightly, so all the flavors mix. Taste and adjust the seasoning; be generous with the pepper. (I ended up adding much more vinegar than prescribed).'),
('19146', '7', 'Cut the eggs in half and gently fold into the salad.'),
('19146', '8', 'Garnish with chopped parsley.'),
('19151', '1', 'Preheat the oven to 400°F.'),
('19151', '2', 'Fold a large piece of parchment in half, and cut around to create a pouch shape.'),
('19151', '3', 'Lay the asparagus on one side of the parchment.'),
('19151', '4', 'Place the salmon on top, season with salt and pepper, and then place the sorrel leaves on top.'),
('19151', '5', 'Top with crème fraîche, white wine, and lemon zest.'),
('19151', '6', 'Seal by folding the edge in pleats, one overlapping the last.  The trick is to fold it in any way that does not allow steam to escape, using a couple staples if necessary.'),
('19151', '7', 'Note: There are several ways to seal the parchment or foil when cooking en papillote.  The general rule of thumb is to do whatever you want just so long as the packet is very tightly sealed, allowing no steam to escape.  Foil, or foil lined with parchment, facilitates the process.  But if using just parchment, admittedly more aesthetically pleasing, work your way around, pleating the edges.  I have been known to staple the final pleat for security, both technical and emotional.  Here are the full Serious Eats instructions for traditional papillote cooking.'),
('19151', '8', 'Park the papillote packages on a baking sheet, and bake for 12 to 15 minutes.'),
('19154', '1', 'In a large shallow dish, combine 1/4 cup of the olive oil with the rosemary, lemon zest and two-thirds of the garlic. Stir in the shrimp and refrigerate for 2 to 4 hours.'),
('19154', '2', 'In a bowl, stir the mayonnaise with the scallions, cornichons, shallot, celery, tarragon, sherry vinegar, paprika, celery seeds and the remaining minced garlic. Season with salt and pepper.'),
('19154', '3', 'Light a grill. Toss the shrimp with the gin and sherry. Thread the shrimp onto 8 skewers; season with salt and pepper. Grill the shrimp over a hot fire until lightly charred and cooked through, 3 minutes per side; let cool slightly. Stir the grilled shrimp into the mayonnaise dressing.'),
('19154', '4', 'Brush the cut sides of the hot dog rolls with olive oil and grill until toasted.'),
('19154', '5', 'Place a sorrel leaf in each roll, spoon the shrimp salad into the rolls and serve.'),
('19158', '1', 'Fill a large pot to about 3/4-full with water; bring to a boil; add the potatoes and cook until fork tender, 8 to 10 minutes; add the green onions and cook another 1 to 2 minutes. Stir in the spinach and sorrel; cook another 2 to 3 minutes; remove from heat.'),
('19158', '2', 'Pour the beaten eggs into the mixture in a slow and steady stream while stirring until the soup thickens. Season with salt, sugar, and vinegar to get a slightly sweet and tangy taste. Allow soup to cool before moving to refrigerator to chill completely.'),
('19158', '3', 'Garnish with any combination of cucumber, egg, sour cream, and dill.'),
('19159', '1', 'In a small saucepan, boil 2 cups of the Pinot Noir over moderately high heat until reduced to 2 tablespoons, about 15 minutes. Scrape the syrup into a small bowl and reserve.'),
('19159', '2', 'Put the foie gras in a shallow bowl and pour the Cognac over it. Season with salt and pepper and refrigerate for at least 30 minutes or overnight.'),
('19159', '3', 'Melt the butter In a large skillet.'),
('19159', '4', 'Add the apple and cook over moderate heat, without stirring, until golden, about 4 minutes. Stir and cook for 1 minute longer.'),
('19159', '5', 'Add the tasso, garlic and shallot and cook, stirring, until the garlic starts to brown, about 3 minutes.'),
('19159', '6', 'Add the remaining 1/2 cup of Pinot Noir and boil until syrupy, about 3 minutes.'),
('19159', '7', 'Add the veal demiglace and simmer for 3 minutes longer.'),
('19159', '8', 'Remove from the heat.'),
('19159', '9', 'Light a grill or preheat a grill pan.'),
('19159', '10', 'Brush the veal chops on both sides with the oil and season with salt and pepper. Grill the chops over a moderately hot fire or over moderate heat in a grill pan until lightly charred on the outside and pink in the center, about 4 minutes per side. Sprinkle the chops with the parsley and thyme and transfer to a platter. Cover loosely and keep warm.'),
('19159', '11', 'Bring the sauce to a simmer over moderate heat.'),
('19159', '12', 'Add the foie gras and cook, stirring constantly, until some of it is melted but most of it retains its shape, about 3 minutes. Fold in the sorrel and cook until wilted, about 1 minute. Season the sauce with salt and pepper and remove from the heat.'),
('19159', '13', 'Put the veal chops on warmed plates and spoon the sauce on top. With a teaspoon, dot each chop with a few drops of the Pinot Noir syrup and serve.'),
('19164', '1', 'Set a pizza stone on the bottom or on the bottom shelf of the oven. Preheat the oven to 500, allowing at least 30 minutes for the stone to heat. On a lightly floured work surface, cut the dough into 4 pieces and roll each piece into a ball. Cover with plastic wrap and let rest for 10 minutes.'),
('19164', '2', 'In a saucepan of boiling salted water, cook the asparagus until tender, about 4 minutes.'),
('19164', '3', 'Drain and pat dry. Slice the asparagus 1/4 inch thick on the diagonal and transfer to a large bowl.'),
('19164', '4', 'Add the shallot and 2 tablespoons of the olive oil and season with salt and pepper.'),
('19164', '5', 'On a lightly floured surface, roll 1 ball of dough into an 8-inch round. Dust a pizza peel with semolina and set the dough round on it. Lightly brush the dough with olive oil. Scatter 1/2 cup of the Fontina cheese and 1/4 cup of the mozzarella on the dough, then top with one-fourth of the asparagus and 1/4 cup of the prosciutto. Slide the pizzetta onto the hot stone.'),
('19164', '6', 'Bake for about 6 minutes, or until it is crisp and browned on the bottom and bubbling on top. Using a large spatula, transfer the pizzetta to a work surface and cut it into quarters. Sprinkle the pizzetta with the sorrel and lemon juice and serve. As soon as 1 pizzetta is in the oven, prepare the next. Slide it into the oven when the first comes out.'),
('19166', '1', 'Blanch the shelled favas in boiling water for 1 minute.'),
('19166', '2', 'Drain, then rinse in cold water to stop the cooking; drain again. Pinch the favas out of their skins.'),
('19166', '3', 'Preheat the oven to 35'),
('19166', '4', 'In an ovenproof skillet, heat 2 tablespoons of the olive oil over moderate heat.'),
('19166', '5', 'Add the favas, garlic, squash and zucchini; season with salt and pepper. Cook until just softened, 3 minutes.'),
('19166', '6', 'Transfer to a plate.'),
('19166', '7', 'In a medium bowl, beat the eggs with the milk; season with salt and pepper. In the same skillet, heat the remaining 1 tablespoon of olive oil over moderately high heat.'),
('19166', '8', 'Pour in the eggs, then stir in the cooked vegetables, sorrel, peas, scallions and chives; season with salt and pepper. Cook the frittata over moderate heat until the edge is set, 2 minutes.'),
('19166', '9', 'Transfer the skillet to the oven and cook for 25 minutes, or until the frittata is set in the center and browned on top.'),
('19166', '10', 'Serve hot or at room temperature.'),
('19167', '1', 'Saute the onions, garlic, and spices in butter or margarine until the onions are soft.  Stir together with the pureed vegetables.'),
('19167', '2', 'Add cheese, maple syrup, egg, salt, and black pepper.  Adjust seasoning.  Set the filling aside.'),
('19167', '3', 'Preheat the oven to 400 degrees F (205 degrees C).  Toast the hazelnuts in a shallow pan on  the middle rack for 10 to 12 minutes, or until brown and fragrant.   When they are cool enough to handle, wrap the nuts tightly in a lint-free towel, and vigorously rub nuts against the towel.  Continue rubbing until the nuts are almost blond.'),
('19167', '4', 'Cook the cream, garlic, cayenne, and white pepper over high heat; stir often, and adjust heat to keep the cream from boiling over.  When the cream is thick enough to coat the back of a spoon, add a pinch salt.  Adjust seasoning.'),
('19167', '5', 'Remove sauce from heat until you''re ready to use it.'),
('19167', '6', 'Lay one sheet of Fresh Pasta out on a flat surface.  Spray with water to prevent drying, and to make it more flexible.'),
('19167', '7', 'Place half tablespoons of filling along the bottom edge of the pasta about 1/2 inch apart. For larger ravioli, use 1 tablespoon of filling, and leave 1 inch between dollops. Fold the pasta sheet over the filling, and cut apart with a ravioli cutter. Set the finished ravioli aside, and cover with a damp cloth.  Repeat until filling and/or pasta is completely used.'),
('19167', '8', 'Cook the ravioli in salted boiling water until al dente.'),
('19167', '9', 'Drain.'),
('19167', '10', 'Meanwhile, reheat the sauce.'),
('19167', '11', 'Add the shredded sorrel to the sauce; cook just until it wilts -- about 30 seconds.'),
('19167', '12', 'Add half the hazelnuts, turn the heat off, and add the cooked ravioli.  Stir gently, and serve immediately.'),
('19167', '13', 'Garnish with remaining hazelnuts.'),
('19169', '1', 'Combine the egg, yolks, vinegar, mustard, garlic, salt, and pepper in a food processor or blender. With the motor running, slowly pour in the oil until the sauce is thick and creamy.'),
('19169', '2', 'Add the chopped herbs and pulse until combined.'),
('19169', '3', 'Transfer to a covered container.'),
('19169', '4', 'var article'),
('19169', '5', 'Type_27_data = {};'),
('19169', '6', 'article'),
('19169', '7', 'Type_27_data.init_step_by_step_images = 0;'),
('19170', '1', 'In a small saucepan, cover the quinoa with the water and bring to a boil. Cover and cook over moderately low heat until the water has been absorbed and the quinoa is tender, about 15 minutes. Uncover, fluff the quinoa and transfer to a large bowl.'),
('19170', '2', 'Meanwhile, light a grill. Grill the dates over moderate heat until lightly charred and very soft, about 2 minutes.'),
('19170', '3', 'Transfer the dates to a shallow bowl and mash to a puree with a fork. Stir in the vinegar and season the puree with salt.'),
('19170', '4', 'Grill the fava bean pods over moderately high heat, turning, until the pods are softened and hot within, about 5 minutes.'),
('19170', '5', 'Transfer the pods to a bowl, cover with foil and let steam for 5 minutes.'),
('19170', '6', 'In a small bowl, stir the lemon zest, juice and olive oil and season with salt and pepper. Shell and peel the fava beans and toss them with 1 tablespoon of the dressing.'),
('19170', '7', 'Brush the scallions and green garlic with some of the dressing, season with salt and pepper and grill over moderately high heat, turning, until browned and tender, about 2 minutes.'),
('19170', '8', 'Transfer the scallions and green garlic to a work surface and cut them into 2-inch lengths.'),
('19170', '9', 'Mix the fava beans, scallions, green garlic and mint into the quinoa.'),
('19170', '10', 'Add the remaining dressing and toss well. Season with salt and pepper.'),
('19170', '11', 'Spread the date puree on the bottoms of 4 plates and spoon the quinoa salad on top.'),
('19170', '12', 'Garnish with the sorrel leaves and serve.'),
('19173', '1', 'Preheat oven to 350°F.'),
('19174', '1', 'Heat the oil and add the onion and potatoes, stirring all the time, cook them until they start to soften.'),
('19174', '2', 'Add the stock & milk, season well with salt and black pepper and bring to the boil.Simmer for 10-15 minutes until the potatoes are tender.2 minutes before the end of cooking, add the sorrel & the creme fraiche or cream.Liquidise the soup.'),
('19174', '3', 'Serve it chilled OR hot, with croutons and finely chopped sorrel leaves.To serve it chilled:.Allow it to cool and store in a cool place such as the fridge. Just before serving, add an ice cube to each bowl and pour the soup into the bowl.'),
('19174', '4', 'Garnish as before.'),
('19178', '1', 'Pull out any small bones that were left in the salmon and, if you wish, trim off the gray fat that was next to the skin. Holding your knife at a 30-degree angle to the cutting board, cut the salmon into 4-wide slices that are about -inch thick. Lay them in a shallow baking dish and pour in the olive oil, rubbing it around the fillets to coat all the sides.'),
('19178', '2', 'Let the fish sit in the oil as it comes to room temperature, 30 to 60 minutes.'),
('19178', '3', 'Preheat the oven to 225F, or 200F if you have the option of convection bake. Lift the fillets from the oil and evenly space them on a baking sheet lined with parchment paper. Sprinkle the fish lightly with salt.'),
('19178', '4', 'Bake for 15 to 20 minutes. When its done, the fat between the layers of fish will just begin to turn opaque, a small amount of liquid will collect under the fillets, and the fish will flake slightly when nudged with your finger. Pick up a piece and it should easily break apart between the layers rather than holding firmly together. It might appear to be underdone because the color will be vivid, but it will be fully cooked.'),
('19178', '5', 'While the fish is roasting, make the sauce. Boil the wine, shallots, lemon juice, and  teaspoon salt together in a small saucepan until you have half as much as you started with. Turn the heat to medium-low and whisk in the butter, one-third of it at a time, until it is all incorporated. If you have an immersion blender, use it to blend the sauce for about 10 seconds, which gives it a creamier consistency. If the fish is not quite ready, keep the sauce warm by putting the saucepan in a larger pan of hot water.'),
('19178', '6', 'When the salmon is done, transfer the fillets to individual warmed plates (since the sauce will run, choose plates with deep rims that will contain it, or use shallow bowls). Stir the coarsely chopped herbs into the sauce, taste it and add more salt if you think it needs it, then ladle it around the fish. Sprinkle each fillet with a pinch of coarse sea salt. Toss the reserved herb sprigs onto the plates in a casual way and serve.'),
('19178', '7', 'var article'),
('19178', '8', 'Type_27_data = {};'),
('19178', '9', 'article'),
('19178', '10', 'Type_27_data.init_step_by_step_images = 0;'),
('19180', '1', 'Bring 3 quarts water to a boil and add 1 tablespoon salt. One type at a time, blanch the vegetables until barely tender, then remove to a bowl of cold water to stop the cooking. When all are blanched, reserve 1 cup of the cooking water.'),
('19180', '2', 'Drain the vegetables. (This can be done ahead of time.)'),
('19180', '3', 'In a wide skillet, melt the butter with the thyme sprigs and reserved liquid.'),
('19180', '4', 'Add the vegetables and simmer until theyre warmed through.'),
('19180', '5', 'Add the lemon juice and season with salt and pepper.'),
('19180', '6', 'Add the sorrel and herbs and cook for 1 minute more.'),
('19180', '7', 'Serve at once.'),
('19180', '8', 'var article'),
('19180', '9', 'Type_27_data = {};'),
('19180', '10', 'article'),
('19180', '11', 'Type_27_data.init_step_by_step_images = 0;'),
('19183', '1', 'Melt 4 tablespoons of the butter in a large, heavy saucepan.'),
('19183', '2', 'Add the shallots, celery, leek and potatoes, cover and cook over moderately low heat, stirring occasionally, until softened, about 8 minutes.'),
('19183', '3', 'Add the wine and lemon juice and cook over high heat until evaporated.'),
('19183', '4', 'Add 4 cups of the water and the bouquet garni and bring to a simmer. Cover and cook over moderately low heat until the vegetables are tender, about 15 minutes. Discard the bouquet garni.'),
('19183', '5', 'Working in batches, puree the soup in a blender or food processor until smooth. Strain the soup into a clean saucepan through a fine sieve. Stir in the heavy cream.'),
('19183', '6', 'Bring a medium saucepan of salted water to a boil.'),
('19183', '7', 'Add the nettles and cook just until wilted.'),
('19183', '8', 'Drain the nettles and immediately plunge them into a medium bowl of ice water.'),
('19183', '9', 'Transfer the nettles to the blender or food processor and puree them with the remaining 1/4 cup of water. Strain the nettle puree into the soup and season with salt and white pepper. Bring the soup to a simmer over low heat, stir in the remaining 2 tablespoons of butter until melted and serve the soup right away.'),
('19184', '1', 'Whisk shallot, vinegar, 1/4 teaspoon sumac, and cumin in small bowl. Gradually whisk in 4 tablespoons oil. Season dressing with salt and pepper.'),
('19184', '2', 'Combine herbs and greens in large bowl. (Dressing and salad can be made 2 hours ahead. Cover separately and chill.)'),
('19184', '3', 'Using vegetable peeler, remove eggplant peel in vertical strips every 1 to 1 1/2 inches, making striped pattern.'),
('19184', '4', 'Cut eggplants crosswise into 1/3-inch-thick rounds.'),
('19184', '5', 'Place rounds in large colander. Sprinkle generously with kosher salt and toss to coat evenly.'),
('19184', '6', 'Let stand until rounds soften and release moisture, tossing occasionally, about 1 hour. Rinse rounds, 1 at a time, and press to release excess moisture. Arrange rounds in single layer on several thicknesses of paper towels. Pat dry with additional towels.'),
('19184', '7', 'Heat 3 tablespoons oil in large skillet over medium-high heat. Working in batches, fry eggplant until golden and soft, adding more oil by tablespoonfuls as needed, about 2 minutes per side.'),
('19184', '8', 'Transfer eggplant to paper towels to drain.'),
('19184', '9', 'Overlap eggplant rounds on platter. Sprinkle with pepper and more sumac, if desired. Toss herbs and greens with dressing; season to taste with salt and pepper. Mound salad atop eggplant.'),
('19184', '10', 'Garnish with nasturtium blossoms, if desired, and serve.'),
('19184', '11', '*A fruity and acidic seasoning powder made from ground dried sumac berries. It is available at Middle Eastern markets and by mail from Adriana''s Caravan (adrianascaravan.com).'),
('19204', '1', 'In a skillet, combine lemon juice, water, garlic cloves, and kosher salt. Bring to a simmer and cook spinach in batches until just wilted.'),
('19204', '2', 'Drain and reserve 1/2 for another use.'),
('19215', '1', 'In a 6- to 8-qt. pot, cook onion in oil over medium heat until softened, about 10 minutes.'),
('19215', '2', 'Add garlic and cook 2 minutes.'),
('19215', '3', 'Add ginger and spices and cook until fragrant, about 1 minute. Working in batches, stir in spinach and cook until wilted, about 5 minutes.'),
('19215', '4', 'Remove from heat and stir in yogurt and salt.'),
('19215', '5', 'Serve with steamed basmati rice and warm naan (Indian flatbread).'),
('19230', '1', 'On a 12- by 15-inch baking sheet, unroll pizza crust dough.'),
('19230', '2', 'Squeeze excess moisture from spinach.'),
('19230', '3', 'Mix spinach, ricotta cheese, parmesan cheese, nutmeg, and garlic.'),
('19230', '4', 'Spread mixture evenly over dough.'),
('19230', '5', 'Starting at a long edge of dough, roll to enclose filling. Set the loaf, seam down, on baking sheet.'),
('19230', '6', 'Brush loaf top with olive oil.'),
('19230', '7', 'Bake in a 425 oven until well browned, 12 to 15 minutes. Meanwhile, stir marinara sauce in a 1- to 1 1/2-quart pan over medium heat until hot; or heat in a microwave-safe bowl in a microwave oven at full power (100%) until hot.'),
('19230', '8', 'Slice loaf diagonally, making 10 equal portions. Offer 1 slice as an appetizer serving, or 2 slices as a main-dish sandwich. Spoon marinara sauce over slices to taste.'),
('19236', '1', 'In a 5- to 6-quart pan over high heat, bring about 3 quarts water to a boil.'),
('19236', '2', 'Add half the spinach and cook until wilted, 1 to 2 minutes.'),
('19236', '3', 'Remove spinach from water with a strainer and place in a large bowl of ice water until cool; lift out and drain. Repeat process to cook and cool remaining spinach.'),
('19236', '4', 'In a large bowl, mix sake, soy sauce, sugar, and sesame oil.'),
('19236', '5', 'Squeeze or roll spinach tightly in a kitchen towel to remove as much water as possible.'),
('19236', '6', 'Place in bowl and mix with dressing to coat. If making salad ahead, cover and chill up to 4 hours.'),
('19236', '7', 'Divide spinach into six cylindrical bundles and squeeze each tightly to compact the leaves. Arrange bundles on a serving plate or in individual small, shallow bowls. Spoon a little of the dressing left in the bowl over each bundle. Sprinkle each bundle with about 1 teaspoon sesame seeds.'),
('19251', '1', 'Combine first 4 ingredients in a large salad bowl.'),
('19251', '2', 'Whisk together sugar and next 4 ingredients until blended.'),
('19251', '3', 'Serve dressing with salad.'),
('19251', '4', 'Note: You can chill dressing up to 1 day; whisk well before serving.'),
('19252', '1', 'Toss together red onion and next 4 ingredients in a large bowl.'),
('19252', '2', 'Drizzle with red wine vinaigrette; sprinkle with salt and pepper to taste.'),
('19262', '1', 'Steam half of spinach, covered, for 5 minutes or until the spinach wilts; place steamed spinach in a colander. Repeat procedure with remaining spinach. Cool slightly, and squeeze dry.'),
('19262', '2', 'Place spinach in a bowl.'),
('19262', '3', 'Add onions and remaining ingredients; toss mixture well to combine.'),
('19262', '4', 'Serve chilled or at room temperature.'),
('19268', '1', 'In a shallow baking pan, bake pecans in a 350 oven until golden in the center (break one to check), 8 to 10 minutes.'),
('19268', '2', 'Let cool.'),
('19268', '3', 'In a large bowl, gently mix spinach, pecans, cranberries, crumbled gorgonzola, olive oil, and vinegar. Season salad to taste with salt and pepper.'),
('19269', '1', 'In a small saucepan, heat 2 teaspoons of the canola oil.'),
('19269', '2', 'Add the shallot and cook over low heat until softened, about 3 minutes.'),
('19269', '3', 'Add the vinegar and thyme sprig and bring to a boil. Simmer over low heat until the vinegar is reduced to 2 tablespoons, about 20 minutes. Discard the thyme sprig and stir the honey into the vinegar.'),
('19269', '4', 'In a small skillet, toast the pine nuts in the remaining 1 teaspoon of canola oil over moderate heat, stirring constantly, until golden, about 5 minutes.'),
('19269', '5', 'Transfer the pine nuts to a plate and let cool.'),
('19269', '6', 'Fill a soup pot with 1/2 inch of water and bring to a boil.'),
('19269', '7', 'Add the spinach in handfuls, stirring until wilted. When the spinach is wilted, transfer to a colander and squeeze out the excess water. Wipe out the pot.'),
('19269', '8', 'Heat the olive oil in the pot and add the spinach. Season with salt and pepper and cook, stirring, until heated through, about 5 minutes.'),
('19269', '9', 'Transfer the spinach to a platter and garnish with the currants and toasted pine nuts.'),
('19269', '10', 'Drizzle the sherry vinegar syrup on top and serve right away.'),
('19271', '1', 'Cook quinoa according to package directions. Meanwhile, whisk together zest, juice, oil, chile flakes, salt, and pepper in a large bowl.'),
('19271', '2', 'Add spinach and onions.'),
('19271', '3', 'Mix in warm quinoa and sprinkle top of salad with feta.'),
('19282', '1', 'Preheat the broiler and position a rack 10 inches from the heat. In a large soup pot, bring 1/4 inch of water to a boil.'),
('19282', '2', 'Add the spinach and cook over high heat, tossing with long tongs, until completely wilted, about 3 minutes.'),
('19282', '3', 'Transfer the spinach to a colander and drain, pressing out as much liquid as possible.'),
('19282', '4', 'In a medium, ovenproof skillet, heat the olive oil.'),
('19282', '5', 'Add the onion and cook over high heat, stirring, until softened, about 3 minutes.'),
('19282', '6', 'Add the wilted spinach and cook, stirring, for 1 minute.'),
('19282', '7', 'Add the Smoked Gouda Bchamel and cook over moderate heat, stirring, until bubbling, about 1 minute. Season with salt and pepper. Sprinkle the spinach with the bread crumbs and shredded Gouda and broil for 2 minutes, until golden and bubbling.'),
('19282', '8', 'Serve hot.'),
('19287', '1', 'Heat 1 tablespoon of the oil in a medium skillet over medium heat.'),
('19287', '2', 'Add the salami and cook until sizzling and browned, 2 to 3 minutes.'),
('19287', '3', 'Remove from heat. Using a slotted spoon, remove and set aside the salami, leaving the rendered fat.'),
('19287', '4', 'Add the mustard, honey, vinegar, salt, pepper, and the remaining 1 tablespoon of oil and whisk together to form a thin emulsion.'),
('19287', '5', 'Add the onion and salami and return to medium heat. Cook just until the onion wilts, about 1 minute. Divide the spinach among serving plates.'),
('19287', '6', 'Pour the hot salami dressing over the greens.'),
('19287', '7', 'Serve with the eggs, chopped, if desired.Tip: With its casing uncut, a whole salami can last for months if stored at a cool room temperature. Once cut, it can be refrigerated for up to 2 weeks if tightly wrapped.'),
('19298', '1', 'Preheat oven to 37'),
('19298', '2', 'Cook pumpkin in boiling water 8 minutes or until tender.'),
('19298', '3', 'Drain; set aside.'),
('19298', '4', 'Place a large nonstick skillet coated with cooking spray over medium heat; add onion, and saut 7 minutes or until golden brown.'),
('19298', '5', 'Remove onion from skillet, and set aside.'),
('19298', '6', 'Add flour to skillet. Gradually add broth, stirring with a whisk until blended. Cook over medium heat or until thick and bubbly (about 6 minutes), stirring constantly.'),
('19298', '7', 'Remove from heat; stir in salt, nutmeg, and pepper.'),
('19298', '8', 'Combine pumpkin, onion, 1/4 cup cheese, and spinach in a bowl. Spoon pumpkin mixture into a 6-cup gratin dish coated with cooking spray.'),
('19298', '9', 'Pour sauce over pumpkin mixture. Sprinkle 1/2 cup cheese over gratin.'),
('19298', '10', 'Bake at 375 for 30 minutes or until bubbly. Broil 3 minutes or until cheese is golden brown.'),
('19298', '11', 'Let stand 5 minutes before serving.'),
('19299', '1', 'Heat a large nonstick skillet over medium heat.'),
('19299', '2', 'Add the spinach in batches, turning frequently until wilted (about 7 minutes).'),
('19299', '3', 'Drain spinach (it should be neither wet nor dry, but moist).'),
('19299', '4', 'Combine spinach and garlic in a medium bowl.'),
('19299', '5', 'Combine water and lemon juice. Working with 1 artichoke at a time, cut off stem to within 1 inch of base; peel stem.'),
('19299', '6', 'Remove the bottom leaves and tough outer leaves, leaving the tender heart and bottom.'),
('19299', '7', 'Cut artichoke in half lengthwise.'),
('19299', '8', 'Remove fuzzy thistle from bottom with a spoon. Thinly slice artichoke heart; place in lemon water. Repeat procedure with remaining artichokes.'),
('19299', '9', 'Drain. (You should have about 4 cups sliced artichokes.) Sprinkle artichokes with salt and pepper.'),
('19299', '10', 'Preheat oven to 37'),
('19299', '11', 'Arrange 3 cups artichoke in an 11 x 7-inch baking dish coated with cooking spray. Sprinkle with 1/2 cup cheese. Repeat layers with artichoke and spinach.'),
('19299', '12', 'Cover and bake at 375 for 15 minutes. Uncover and bake 30 minutes. Sprinkle with 3/4 cup cheese.'),
('19299', '13', 'Bake an additional 10 minutes or until artichokes are tender.'),
('19300', '1', 'Cook spinach just until wilted, drain, squeeze dry and chop roughly.'),
('19300', '2', 'Heat butter in a large skiller over medium high heat, add mushrooms and onions and cook until softened and the mushrooms have released much of their water.'),
('19300', '3', 'Combine spinach, mushrooms and onions, mayonnaise, sour cream, 1/2 cup of the Parmigiano and stir together.'),
('19300', '4', 'Pour into a buttered casserole dish.'),
('19300', '5', 'Combine remaining Parmigiano with the bread crumbs and pour over the top.'),
('19300', '6', 'Drizzle with melted butter and bake at 350 degrees until bubbly and cooked through, about 45 minutes.Facebook'),
('19300', '7', 'Twitter'),
('19300', '8', 'Google'),
('19300', '9', 'Pinterest'),
('19300', '10', 'Pocket'),
('19300', '11', 'Email4 Comments  Comments Feed'),
('19300', '12', 'Name (required)Mail (will not be published) (required)Website Previous'),
('19300', '13', 'Next'),
('19303', '1', 'Soak wooden skewers in water to cover 30 minutes.'),
('19303', '2', 'Meanwhile, preheat grill to 350 to 400 (medium-high) heat. Devein shrimp, if desired.'),
('19303', '3', 'Combine shrimp and 3/4 cup Basil Vinaigrette in a large zip-top plastic freezer bag; seal and chill 15 minutes, turning occasionally.'),
('19303', '4', 'Remove shrimp from marinade, discarding marinade. Thread shrimp onto skewers.'),
('19303', '5', 'Grill shrimp, covered with grill lid, 2 minutes on each side or just until shrimp turn pink.'),
('19303', '6', 'Remove shrimp from skewers.'),
('19303', '7', 'Toss spinach, mangoes, and onion with 1/4 cup Basil Vinaigrette in a large bowl; arrange on a serving platter. Top with grilled shrimp. Sprinkle with crumbled goat cheese and raspberries.'),
('19303', '8', 'Serve with remaining Basil Vinaigrette.'),
('19305', '1', 'Preheat oven to 35'),
('19305', '2', 'In a bowl, combine sugar, corn syrup, 1/4 tsp. each salt and cardamom, the cayenne, and cloves. Stir in nuts.'),
('19305', '3', 'Spread onto a rimmed baking sheet lined with parchment paper.'),
('19305', '4', 'Bake, stirring once in a while with a fork, until syrup is deep golden, about 15 minutes. Stir again, then transfer nuts on paper to a work surface.'),
('19305', '5', 'Let nuts cool, breaking them up after 5 minutes.'),
('19305', '6', 'Whisk oil, vinegar, pepper, shallot, and remaining 1/4 tsp. each salt and cardamom in a large bowl. Gently toss with spinach, pears, and nuts.'),
('19305', '7', 'Serve immediately.'),
('19306', '1', 'Add the lentils to a pot and cover with a couple inches water and a good pinch or two of salt.  Bring to a boil and simmer until tender but not mushy, adding more water if necessary, about 30 minutes.  Season to taste as they cook.'),
('19306', '2', 'Drain, then add 1/2 the olive oil into the pot and cook the garlic until fragrant, about 2 minutes, then return the lentils to the pot and cook for an additional 5 minutes until warmed through. Stir in parsley and remaining oil.'),
('19306', '3', 'In the meantime, lightly pack the goat cheese into a 1/3 cup measure to divide the cheese into rounds, then press them gently flat into patties.'),
('19306', '4', 'Spread the flour on a small plate, the egg on another, and the panko or breadcrumbs on a third.  Dredge the goat cheese in flour, then egg, then breadcrumbs to coat on all sides, then set aside.'),
('19306', '5', 'While the lentils are warming with the garlic, heat the neutral oil in a large skillet until extremely hot, close to smoking.'),
('19306', '6', 'Add a goat cheese round; it should sizzle and turn golden within a couple minutes.  Repeat with remaining goat cheese rounds, cooking both sides until golden and crisp, removing to drain on paper towels after cooking.  Heap the lentils and spinach on plates, top with the goat cheese, and finish with drizzled olive oil and sprinkled sea salt.'),
('19307', '1', 'Combine first 5 ingredients in a shallow bowl.'),
('19307', '2', 'Rub salmon with brown sugar mixture.'),
('19307', '3', 'Place fillets, skin-side down, on grill rack coated with cooking spray. Grill over medium-high heat (350 to 40'),
('19307', '4', '12 minutes or until desired degree of doneness.'),
('19307', '5', 'Remove skin and discard.'),
('19307', '6', 'Toss spinach with 1/3 cup Peach Dressing. Arrange spinach on individual serving plates, top with salmon, and drizzle with remaining dressing.'),
('19312', '1', 'Cook pasta according to package directions, omitting salt and fat.'),
('19312', '2', 'While pasta cooks, melt butter in a medium saucepan over medium heat.'),
('19312', '3', 'Add flour; cook 1 minute, stirring constantly with a whisk. Gradually add the milk, stirring constantly with a whisk. Increase heat to medium-high; bring to a boil, stirring constantly. Reduce heat; simmer 3 minutes or until sauce thickens slightly, stirring frequently.'),
('19312', '4', 'Remove from heat, and stir in cheese, salt, and pepper.'),
('19312', '5', 'Combine the sauce, pasta, and spinach, tossing gently to coat.'),
('19313', '1', 'Preheat grill to 350 to 400 (medium-high) heat. Rub steak with 2 Tbsp. olive oil and next 3 ingredients.'),
('19313', '2', 'Brush corn with remaining 2 Tbsp. olive oil.'),
('19313', '3', 'Grill steaks and corn at the same time, covered with grill lid, 7 to 8 minutes, turning steak once and turning corn every 4 to 5 minutes.'),
('19313', '4', 'Let steak stand 10 minutes.'),
('19313', '5', 'Meanwhile, hold each grilled cob upright on a cutting board, and carefully cut downward, cutting kernels from cob. Discard cobs. Thinly slice steak.'),
('19313', '6', 'Layer spinach, grilled corn kernels, steak, avocados, and grapefruit on serving plates.'),
('19313', '7', 'Serve with bottled Ranch dressing.'),
('19319', '1', 'Preheat the grill to medium-high heat.'),
('19319', '2', 'To prepare vinaigrette, combine first 6 ingredients in a large bowl; stir well with a whisk.'),
('19319', '3', 'To prepare salad, drizzle lemon juice over fillets; sprinkle with 2 teaspoons pepper.'),
('19319', '4', 'Place fillets, skin sides up, on a grill rack coated with cooking spray; grill 5 minutes on each side or until fish flakes easily when tested with a fork or until desired degree of doneness.'),
('19319', '5', 'Remove skin from fillets; discard.'),
('19319', '6', 'Add spinach to vinaigrette in bowl; toss well.'),
('19319', '7', 'Place 2 cups spinach mixture on each of 4 serving plates; arrange 1 fillet and 6 orange slices on top of greens.'),
('19321', '1', 'Light a grill or heat a grill pan. Coat the mushroom caps with 3 tablespoons of the olive oil and season with salt and pepper. Grill the mushrooms, until deeply browned and crisp, about 5 minutes per side.'),
('19321', '2', 'Transfer to a large shallow dish to cool.'),
('19321', '3', 'Cut the caps in half, then thinly slice them crosswise; return to the dish.'),
('19321', '4', 'Grill the peppers until charred all over.'),
('19321', '5', 'Transfer to a bowl, cover with plastic wrap and let steam for 5 minutes.'),
('19321', '6', 'Remove the charred skins, seeds and stems.'),
('19321', '7', 'Cut the peppers into 1/2 -inch strips, removing the ribs, and add to the mushrooms.'),
('19321', '8', 'In a bowl, combine the remaining 3/4 cup of olive oil with the vinegar, 3 of the garlic cloves, the thyme, basil and 2 teaspoons of pepper.'),
('19321', '9', 'Pour all but 1/4 cup of the marinade over the mushrooms and peppers and season lightly with salt and pepper.'),
('19321', '10', 'Let marinate at room temperature for 1 to 3 hours.'),
('19321', '11', 'Drain before using.'),
('19321', '12', 'In a small saucepan, boil the wine with the remaining 1 garlic clove until reduced to 2 tablespoons, about 7 minutes.'),
('19321', '13', 'Add the cream and bring to a boil.'),
('19321', '14', 'Remove the pan from the heat and stir in the shredded cheese.'),
('19321', '15', 'Whisk over moderate heat until the fondue is smooth. Season with salt and pepper.'),
('19321', '16', 'In a large bowl, toss the spinach with the reserved 1/4 cup of marinade and mound on plates. Arrange the mushrooms, peppers and prosciutto alongside. Top with the sliced Fontina. Briefly reheat the fondue, whisking constantly until smooth.'),
('19321', '17', 'Drizzle the spinach with the fondue and serve the salad at once.'),
('19322', '1', 'Combine the first 6 ingredients in a large bowl, stirring well with a whisk.'),
('19322', '2', 'Add 6 cups spinach and red onion; toss to coat.'),
('19322', '3', 'Spinach-Pasta Salad Variation: Cook 1/2 cup mini farfalle according to package directions.'),
('19322', '4', 'Drain. Rinse with cold water; drain.'),
('19322', '5', 'Add garlic vinaigrette, 3 cups baby spinach, and 1/4 cup chopped red onion.'),
('19323', '1', 'In a small saucepan, cover the dried cranberries and blueberries with boiling water and let stand until softened, about 5 minutes.'),
('19323', '2', 'Drain well.'),
('19323', '3', 'Heat the oil in the same saucepan.'),
('19323', '4', 'Add the curry and garlic and cook over low heat for 1 minute; discard the garlic.'),
('19323', '5', 'Add the honey, salt and cayenne, then whisk in the orange juice. Stir in the dried fruits and bring to a simmer. In a large bowl, toss the spinach with the hot dressing and serve at once.'),
('19324', '1', 'Watch how to make this recipe.'),
('19324', '2', 'Heat the butter in a 12-inch saute pan over moderate heat.'),
('19324', '3', 'Add the onions and cook until soft, about 8 minutes.'),
('19324', '4', 'Whisk in the cream cheese and let melt. Fold in the spinach until evenly combined.'),
('19324', '5', 'Add up to 3 tablespoons water if the mixture seems too dry. Sprinkle the nutmeg on top and season with salt and pepper.'),
('19324', '6', 'BYOC: Lemon zest and juice would bring a little bit of sunshine to this dish. Just add with the salt and pepper.'),
('19325', '1', 'Heat oil in a wok or nonstick skillet over medium heat.'),
('19325', '2', 'Add garlic; cook 3 minutes, stirring constantly.'),
('19325', '3', 'Add half of spinach; stir-fry 1 minute.'),
('19325', '4', 'Add remaining spinach; stir-fry 1 minute.'),
('19325', '5', 'Add wine, sugar, and salt; stir-fry 1 minute.'),
('19326', '1', 'Add 3/4 cup strawberries, white wine vinegar, basil, olive oil, sugar, salt, and pepper to a food processor or blender and puree until smooth.'),
('19327', '1', 'Heat a large skillet over medium heat and add the butter. When the butter is hot, stir in the corn and the starchy liquid scraped from the cobs. Cook for 5 minutes, then stir in the garlic and season with salt and pepper, to taste. Cook for 2 to 3 minutes more, then add the cream and nutmeg, stirring occasionally, until very creamy, about 15 minutes.'),
('19327', '2', 'Add the spinach and stir until wilted. Season with salt and pepper, if needed.'),
('19327', '3', 'Transfer to a serving bowl and serve.'),
('19329', '1', 'Heat 1 teaspoon vegetable oil in a large nonstick skillet over medium heat.'),
('19329', '2', 'Add chopped spinach, and stir-fry for 1 minute or until wilted.'),
