INSERT INTO `Directions` (RecipeID, SortOrder, Direction) VALUES ('8796', '2', 'Coat both sides of bread with cooking spray. Broil 2 minutes on each side or until lightly toasted.'),
('8796', '3', 'Combine arugula, 2 teaspoons oil, juice, 1/8 teaspoon salt, and 1/4 teaspoon pepper. toss gently.'),
('8796', '4', 'Heat remaining 1 teaspoon oil in a large nonstick skillet over medium heat. Crack eggs into pan. cook 2 minutes. Cover and cook an additional 2 minutes or until whites are set.'),
('8796', '5', 'Remove from heat.'),
('8796', '6', 'Combine 1/4 teaspoon salt, ricotta, Parmigiano-Reggiano, and thyme. spread over bread slices. Divide salad and eggs evenly over bread. Sprinkle with remaining 1/8 teaspoon salt and remaining 1/4 teaspoon pepper.'),
('8797', '1', 'Preheat grill.'),
('8797', '2', 'Combine cheese and butter in a small bowl. stir until well blended.'),
('8797', '3', 'Grill bread 5 minutes on each side or until golden. cool.'),
('8797', '4', 'Spread 1 teaspoon cheese mixture on each slice. set aside.'),
('8797', '5', 'Thread 4 fig halves lengthwise onto each of 6 (8-inch) skewers. coat figs with cooking spray.'),
('8797', '6', 'Place fig kebabs on grill rack, and grill 4 minutes on each side. Cool slightly. remove figs from skewers.'),
('8797', '7', 'Combine vinegar, oil, salt, and pepper in a small bowl.'),
('8797', '8', 'Place spinach and arugula in a large bowl. add dressing, tossing gently to coat. Divide mixture evenly among 8 serving plates. Top with figs and lettuce leaves. sprinkle with onions.'),
('8797', '9', 'Serve with toasts.'),
('8798', '1', 'Cook bacon in a nonstick skillet over medium heat until crisp (about 8 minutes).'),
('8798', '2', 'Remove bacon from pan, reserving drippings. drain on paper towels.'),
('8798', '3', 'Add onion, water, and hot sauce to drippings in pan. cover and cook for 3 minutes. Stir in butter and sugar. cover and cook for 3 minutes. Uncover and cook for 5 minutes or until golden brown, stirring frequently. Set aside. keep warm.'),
('8798', '4', 'Heat a large nonstick skillet over medium-high heat. Coat pan with cooking spray.'),
('8798', '5', 'Place bread in pan, and cook for 3 minutes on each side or until lightly browned. Set aside, and keep warm.'),
('8798', '6', 'Recoat pan with cooking spray. Crack eggs into pan, and cook for 2 minutes. Gently turn eggs, one at a time. cook 1 minute or until desired degree of doneness. Sprinkle evenly with salt and black pepper.'),
('8798', '7', 'Place one bread slice on each of two plates. arrange onion mixture evenly over bread.'),
('8798', '8', 'Place 1 egg, 2 bacon slices, and 1/2 cup arugula over each serving. top with remaining bread slices.'),
('8798', '9', 'Serve immediately.'),
('8803', '1', 'Heat a couple teaspoons of cooking oil in a cast iron pan on high heat. Pat the steaks dry. Sprinkle the steaks on both sides with a little salt. Sear the steaks in the pan on both sides, just until nicely browned.'),
('8803', '2', 'Remove pan from heat and cover.'),
('8803', '3', 'Let cook for a few minutes more, until the steak is done to your liking. You can test with a meat thermometer.'),
('8803', '4', 'Remove steak from pan at 125 to 130F for rare, 140F for medium rare, 150 for medium. Or use your fingers to test the meat for doneness (see The Finger Test to Check the Doneness of Meat).'),
('8803', '5', 'Remove from pan to a cutting board.'),
('8803', '6', 'Let rest for a few minutes before cutting.'),
('8803', '7', 'Cutthin slices, on a diagonal so you slice wide pieces,acrossthe grain of the meat.2 Toss together the lettuce greens, arugula, bell pepper, goat cheese, and scallions. Arrange on individual plates. Sprinkle with avocado. Lay on top several slices of chilled sliced steak. Sprinkle with pomegranate seeds or sliced kumquats if using.3'),
('8803', '8', 'Mix together the lemon juice, olive oil, mustard, and salt and pepper to taste.'),
('8803', '9', 'Drizzle on salad.'),
('8804', '1', 'In a small bowl combine the shallot, pomegranate molasses, vinegar, salt and pepper and whisk until the salt is dissolved.'),
('8804', '2', 'Whisk in the olive oil and let vinaigrette stand at room temperature until salad is assembled.'),
('8804', '3', 'Combine the arugula, romaine, pears and half of the pomegranate seeds in a large bowl.'),
('8804', '4', 'Crumble half of the goat cheese over the ingredients in the bowl (this works best if the cheese is very cold).'),
('8804', '5', 'Whisk the vinaigrette until uniform and add all but 2 tablespoons of it to the bowl.'),
('8804', '6', 'Gently toss the salad with your hands or salad tongs, coating the ingredients well with the vinaigrette.  If the salad seems dry, add the vinaigrette in small increments until it is dressed to your liking.'),
('8804', '7', 'Crumble the remaining cheese over the salad and sprinkle the remaining pomegranate seeds and the pistachios over the top.'),
('8804', '8', 'Serve immediately.'),
('8805', '1', 'In a medium bowl, mix the shallot with the lemon juice and 1/2 teaspoon of salt. let stand for 5 minutes.'),
('8805', '2', 'Whisk in the pomegranate molasses and the olive oil. Stir in the pomegranate seeds and the parsley and season with salt and pepper.'),
('8805', '3', 'Arrange the arugula on a large platter and layer in the serrano ham and ricotta salata. Spoon the pomegranate salsa over the salad and serve.'),
('8806', '1', 'In a bowl, mix the pork and lamb with the onion, wine, parsley, zest, thyme, fennel, lavender and red pepper.'),
('8806', '2', 'Add one-third of the garlic, 2 teaspoons of salt and 1/2 teaspoon of pepper.'),
('8806', '3', 'Roll the mixture into 1-inch meatballs.'),
('8806', '4', 'In a very large skillet, heat 2 tablespoons of the oil.'),
('8806', '5', 'Add the meatballs and cook over moderately high heat, turning frequently, until browned, 5 minutes. Reduce the heat to moderate and cook for 5 minutes longer, or until no trace of pink remains.'),
('8806', '6', 'Transfer to a plate.'),
('8806', '7', 'In a food processor, puree the arugula with the almonds, 1/2 cup of Parmesan and the remaining 1/2 cup of olive oil and garlic. Scrape the pesto into a bowl. season with salt and pepper.'),
('8806', '8', 'In a pot of boiling salted water, cook the pasta until al dente. Reserve 1 cup of the cooking water.'),
('8806', '9', 'Drain the pasta. transfer it to bowl. Toss the pasta with the pesto and 1/2 cup of the cooking water. add more water if the sauce is dry.'),
('8806', '10', 'Serve with the meatballs and more Parmesan and olive oil.'),
('8807', '1', 'Preheat broiler.'),
('8807', '2', 'Whisk together vinegar, mustard, and salt and pepper to taste, then whisk in 2 tablespoons oil. Toss beets with vinaigrette.'),
('8807', '3', 'Arrange bread on a large baking sheet and brush tops with remaining tablespoon oil. Season with salt and pepper and broil 6 inches from heat 1 to 1 1/2 minutes, or until edges are golden.'),
('8807', '4', 'Remove 4 slices from oven. Turn remaining 4 slices over on baking sheet and spread thickly with goat cheese. Broil 1 minute more and transfer to plates. Top goat cheese with drained beets, onion, arugula, and remaining bread, toasted sides up.'),
('8808', '1', 'In a saucepan, heat 1 tablespoon of the oil.'),
('8808', '2', 'Add the apple, onion, curry and saffron and cook over moderate heat until the onion is softened, 5 minutes.'),
('8808', '3', 'Remove from the heat and stir in 1 teaspoon of water. let cool.'),
('8808', '4', 'Scrape the mixture into a mini food processor.'),
('8808', '5', 'Add the mayonnaise and process.'),
('8808', '6', 'Transfer the mayonnaise to a bowl and add the cilantro and mint. Season with salt and pepper, then fold in the crabmeat.'),
('8808', '7', 'Cut each slice of watermelon into 2 triangles and transfer to 4 plates. Season with salt and pepper and sprinkle each plate with 1 teaspoon of lime juice. Mound the crab salad on the watermelon. In another bowl, toss the arugula with the remaining 1 tablespoon of lime juice and the remaining 2 tablespoons of oil and season with salt and pepper. Arrange the arugula on the plates and serve.'),
('8809', '1', 'Preheat oven to 375F with rack in middle.'),
('8809', '2', 'Pat pork dry and sprinkle with 3/4 teaspoon salt and 1/2 teaspoon pepper.'),
('8809', '3', 'Heat vegetable oil in a 12-inch ovenproof heavy skillet over medium-high heat until it shimmers, then brown pork on all sides, about 6 minutes total.'),
('8809', '4', 'Transfer pork in skillet to oven and roast until an instant-read thermometer inserted into center registers 145 to 150F, 20 to 25 minutes.'),
('8809', '5', 'Transfer to a cutting board and let stand 10 minutes.'),
('8809', '6', 'While pork stands, add vinegar to skillet (be careful. handle will be very hot) and boil, scraping up any brown bits, until slightly reduced, about 30 seconds.'),
('8809', '7', 'Transfer to a heatproof measuring cup and add enough olive oil to bring total to 3/4 cup liquid.'),
('8809', '8', 'Pulse 3/4 cup walnuts with garlic, water, 1/2 teaspoon salt, and 1/4 teaspoon pepper to a coarse paste in a food processor. With motor running, slowly add oil mixture to make vinaigrette.'),
('8809', '9', 'Toss arugula and endive with just enough vinaigrette to coat, then divide among plates. Top with thin slices of pork and drizzle with remaining vinaigrette. Crumble remaining 1/4 cup walnuts over pork.'),
('8810', '1', 'Whisk first 4 ingredients in medium bowl to blend.'),
('8810', '2', 'Add walnut oil and extra-virgin olive oil. whisk until well blended. Season dressing to taste with salt and pepper. (Can be made 1 day ahead. Cover and chill.'),
('8810', '3', 'Let stand at room temperature 1 hour and rewhisk before continuing.)'),
('8810', '4', 'Toss arugula in large bowl with enough dressing to coat. Divide arugula among 10 plates. Arrange endive leaves and pear slices atop arugula on each.'),
('8810', '5', 'Drizzle with more dressing. Sprinkle with Candied Walnuts and serve.'),
('8811', '1', 'Preheat oven to 425F.'),
('8811', '2', 'Pat veal chops dry and season with salt and pepper.'),
('8811', '3', 'Heat 1/2 tablespoon butter and 1/2 tablespoon oil in a 12-inch heavy skillet (see cooks'' note, below) over moderately high heat until hot but not smoking, then sear chops until golden brown, about 3 minutes on each side.'),
('8811', '4', 'Transfer skillet to middle of oven and roast chops until an instant-read thermometer inserted horizontally into a chop registers 155F (do not touch bone), 10 to 15 minutes (depending on thickness).'),
('8811', '5', 'While chops are roasting, mash garlic to a paste with salt using a mortar and pestle (or mince and mash with a large heavy knife), then transfer half of paste to a bowl and whisk in 1/2 tablespoon vinegar, remaining tablespoon oil, and salt and pepper to taste.'),
('8811', '6', 'Transfer chops to a plate and keep warm.'),
('8811', '7', 'Add shallot and remaining garlic paste to skillet and cook over moderate heat, stirring, until softened, about 1 minute.'),
('8811', '8', 'Add wine and remaining tablespoon vinegar and boil, scraping up brown bits, until reduced to about 2 tablespoons, about 4 minutes.'),
('8811', '9', 'Add broth and rosemary and boil until reduced by half, about 4 minutes.'),
('8811', '10', 'Remove from heat and add remaining 2 tablespoons butter, swirling skillet to incorporate, then stir in any veal juices accumulated on plate. Season with salt and pepper.'),
('8811', '11', 'Add arugula to dressing and toss to coat.'),
('8811', '12', 'Serve chops with sauce and arugula.'),
('8813', '1', 'Whisk shallot and lemon juice in small bowl to blend. Gradually whisk in oil. Season to taste with salt and pepper.'),
('8813', '2', 'Let stand 15 minutes to blend flavors.'),
('8813', '3', 'Combine arugula and sliced fennel in large bowl. Toss with enough dressing to coat salad.'),
('8813', '4', 'Add shaved cheese. toss gently and serve.'),
('8814', '1', 'Whisk olive oil and lemon juice in small bowl to blend. set dressing aside.'),
('8814', '2', 'Place 1 bresaola slice on work surface with 1 long side parallel to edge.'),
('8814', '3', 'Place 3 arugula leaves at 1 short end so that leaves extend past 1 long side. Top with layer of sliced fennel, then 2 cheese strips. Sprinkle with pepper.'),
('8814', '4', 'Drizzle with 1/2 teaspoon dressing. Starting at filled end, roll up bresaola, enclosing filling. Arrange, seam side down, on platter. Repeat with remaining ingredients to form 18 rolls total. (Can be made 4 hours ahead. Cover with plastic wrap. chill. Before serving, let stand 30 minutes at room temperature.)'),
('8814', '5', '*Available at Italian markets and some specialty foods stores.'),
('8816', '1', 'Heat grill (or grill pan) to medium.'),
('8816', '2', 'Brush squash and bread with 1 tablespoon olive oil. season with half of the salt and pepper.'),
('8816', '3', 'Add squash and bread to grill. cook, turning occasionally, until squash is tender and bread is charred (4-6 minutes). Rub bread with cut side of garlic clove.'),
('8816', '4', 'In a large bowl, combine remaining 2 tablespoons olive oil, remaining salt and pepper, and vinegar. whisk well.'),
('8816', '5', 'Cut squash and tear bread into 1-inch pieces. toss in dressing with arugula and olives. Divide salad among 6 plates, and top each with 4 pieces of burrata.'),
('8816', '6', 'Drizzle with additional olive oil and sprinkle with sea salt, if desired.'),
('8816', '7', 'Note: The sum of constituent fats (saturated, monounsaturated, polyunsaturated) may not always equal the total-fat value.'),
('8817', '1', 'Combine first 3 ingredients in a small bowl, stirring with a whisk.'),
('8817', '2', 'Combine arugula, tomatoes, and beans in a large bowl.'),
('8817', '3', 'Add dressing. toss gently. Top with rye bread croutons and cheese.'),
('8818', '1', 'Heat oil in heavy large skillet over medium heat.'),
('8818', '2', 'Add shallots. saute 10 minutes.'),
('8818', '3', 'Add arugula. toss until wilted but still bright green, about 3 minutes.'),
('8818', '4', 'Transfer arugula mixture to large bowl and cool.'),
('8818', '5', 'Mix in goat cheese and Parmesan cheese. Season filling with salt and pepper.Line 2 baking sheets with heavy-duty foil. spray foil with nonstick spray.'),
('8818', '6', 'Place 4 wonton wrappers on work surface. cover remaining wrappers with plastic to prevent drying. Lightly brush entire surface of each wrapper with egg white. Spoon 1 generous teaspoon filling into center of each wrapper. Fold wrappers diagonally in half, forming triangles. Press edges firmly to seal. Arrange ravioli on prepared sheets. Repeat with remaining wrappers and filling. (Can be made ahead. Cover with plastic and chill up to 1 day. or cover with plastic, then heavy-duty foil, and freeze up to 1 week. If frozen, do not thaw before cooking.)Make tomato-pancetta butter:Cook chopped pancetta in large skillet over medium-high heat until crisp and brown. Using slotted spoon, transfer pancetta to paper towel. drain. Set aside.'),
('8818', '7', 'Pour off all but 1 tablespoon drippings from skillet.'),
('8818', '8', 'Add butter to drippings in skillet. melt over medium-high heat.'),
('8818', '9', 'Add tomatoes and thyme. saute until tomatoes are tender, about 5 minutes. Season with salt and pepper. (Can be made 2 hours ahead.'),
('8820', '1', 'In a large salad bowl, combine the lemon juice, extra virgin olive oil, salt and pepper.'),
('8820', '2', 'Place the arugula in the bowl and toss with the dressing. Using a vegetable peeler, shave sheets of Parmesan cheese onto salad (to taste).'),
('8820', '3', 'Serve immediately.'),
('8821', '1', 'Note: It is important to use jumbo shrimp in this recipe because smaller shrimp will overcook in the time it takes for the bacon wrapped around them to crisp. If jumbo shrimp are not available, precook the bacon slices until just golden but still pliable, and then wrap them around the nearly done shrimp and proceed with the recipe.To make dressing: Put 1 tablespoon honey in a medium bowl.'),
('8821', '2', 'Add lemon juice and mustard. whisk to combine. Slowly pour in olive oil, whisking constantly. Season to taste with salt and pepper. set aside.To make salad: Use 1/2 teaspoon pepper to season shrimp all over. Wrap 1 piece of bacon snugly around each shrimp and secure with a toothpick running lengthwise (so shrimp can lie flat).'),
('8821', '3', 'Heat a large skillet over medium heat. Arrange shrimp in a single layer and cook, flipping once, until bacon is just crisp, about 10 minutes.'),
('8821', '4', 'Drizzle honey over shrimp and continue to cook, basting often with pan juices, until bacon is caramelized and shrimp are cooked through, about 2 minutes more.'),
('8821', '5', 'Transfer to a large plate. When cool enough to handle, remove and discard toothpicks.Arrange arugula on plates. Top with warm shrimp, add dressing, and serve.Extra idea: This could also work just as well as a rice salad: Dice and saut the bacon, add the shrimp, then toss it all over warm rice, shredded greens, and honey-sweetened dressing.'),
('8829', '1', 'Bring a large pot of salted water to boil. Cook the pasta until al dente, then drain, reserving  cup of cooking water.Meanwhile, in a large nonstick skillet, heat the oil over a medium-high flame. Cook the garlic until beginning to brown, about 2 to 3 minutes.'),
('8829', '2', 'Add the shallot and the asparagus and lower the heat to medium.'),
('8829', '3', 'Saute the asparagus until it turns a vibrant green and is slightly tender, about 3 minutes. Season with  teaspoon salt and the red pepper flakes.'),
('8829', '4', 'Add the cream, lemon juice, and zest. Gently simmer until partially reduced, about 3 minutes.'),
('8829', '5', 'Remove the pan from the heat and add the peas, stirring to coat.'),
('8829', '6', 'Add the cooked pasta to the sauce, along with the arugula, and gently toss until everything is combined and the arugula is wilted.'),
('8829', '7', 'Serve immediately.'),
('8831', '1', 'Watch how to make this recipe.'),
('8831', '2', 'Preheat the oven to 400 degrees F.'),
('8831', '3', 'Put the oil and onions in a medium skillet and cook over very low heat, stirring occasionally, until onions are soft and caramelized, about 15 minutes. Turn the heat up to medium and add the arugula. Cook until the arugula is wilted, about 1 minute. Season with salt and pepper.'),
('8831', '4', 'Place the tortillas on a baking sheet and top each with some of the arugula/onion mixture. Crumble some goat cheese on top of each, and bake for 10 minutes. Allow to cool for a few minutes and cut each pizza into 4 triangles.'),
('8833', '1', 'Heat 1 tablespoon olive oil in a stick-free saut pan over medium-high heat until almost smoking, about 1-2 minutes.Sprinkle salt over the pounded chicken breasts and sear them for 2-3 minutes per side in the hot pan, working in batches so that you do not crowd the pan.'),
('8834', '1', 'Combine arugula and cheese in large bowl.'),
('8834', '2', 'Remove peel and white pith from oranges.'),
('8834', '3', 'Cut between orange membranes to release segments into bowl with arugula and cheese.'),
('8834', '4', 'Pour oil and lemon juice over. toss to blend. Season with salt and pepper.'),
('8836', '1', 'Whisk the dressing ingredients together.Lightly dress the salad greens, toss to coat then plate. Dress the peach batons separately, tossing to coat then scatter over the greens. Sprinkle some feta on top then grind some black pepper.'),
('8836', '2', 'Serve immediately.Great with an off-dry Riesling.'),
('8837', '1', 'The amount of ingredients depends on how many people you are serving and how much salad you intend to serve them.  The important thing is that this is a good blend of flavors.  I didn''t try tossing this salad. each plate was composed individually.The dressing for three individual salads was 1/4 cup of olive oil, 1/2 lemon, 1/4 teaspoon of powdered mustard, 3/4 teaspoon of sugar, salt and pepper to taste.  Actually, it is all to taste.  These are only approximate measurements.Assemble the salad according to how much you want.  A handful of arugula leaves, a few beet juliennes, some crumbled goat cheese, garnish with chopped walnuts.  Use a vinaigrette salad dressing or what I''ve described above.'),
('8838', '1', 'Prepare barbecue (medium-high heat). Rub steaks with oil and sprinkle lightly with salt and pepper. Grill until steaks are brown and crusty and thermometer inserted into thickest part registers 120F to 125F for medium-rare, turning every five minutes, about 25 minutes total. Using tongs, transfer steaks to cutting board. let steaks rest for 10 minutes.'),
('8838', '2', 'Coarsely chop enough arugula to measure 2 cups and set aside. Arrange remaining arugula on platter and sprinkle with oil, salt, and pepper.'),
('8838', '3', 'Cut meat away from bones. Slice meat thinly and arrange atop arugula. Sprinkle reserved chopped arugula and cheese shavings over steak.'),
('8839', '1', 'Preheat the oven to 325 degrees F.'),
('8839', '2', 'Cut the baguette lengthwise and drizzle all sides with olive oil. Then rub the baguette on all sides with garlic.'),
('8839', '3', 'Cut the baguette into cubes and place it into a baking dish.'),
('8839', '4', 'Add a sprinkle of salt and pepper and toss.'),
('8839', '5', 'Bake for 20 minutes then remove from the oven to let cool.Slice the heirloom and cherry tomatoes into bite sized pieces. In shallow bowls, combine  cup of tomato water with tomatoes, arugula and  cup small basil leaves.'),
('8839', '6', 'Drizzle with olive oil and add a few croutons just before serving. Enjoy!Georgia Pellegrini'),
('8839', '7', 'More Posts by Georgia Pellegrini (1)Follow Georgia Pellegrini:Georgia Pellegrini''s blog:http://georgiapellegrini.com'),
('8840', '1', 'With the heat on low, add the crab meat, lemon zest and juice and stir to combine. Tip in the cooked, drained pasta, turning so that the noodles are well-slicked with the buttery juices.'),
('8840', '2', 'Add the parsley and arugula, continuing to turn until the greens are slightly wilted. Check for seasoning, garnish with additional chili and fresh greens if desired, serve.'),
('8840', '3', 'Serves 4 as a main course, 6-8 as a light lunch or entre.'),
('8841', '1', 'Combine olives and oil, then spread on bottom halves of rolls.'),
('8841', '2', 'Heat a grill pan or large heavy skillet (not nonstick) over medium-high heat until hot, then heat sausages until hot, about 8 minutes.'),
('8841', '3', 'Make sandwiches on rolls with peppers, sausages, and arugula.'),
('8841', '4', 'Cut in half.'),
('8842', '1', 'Whisk first 3 ingredients in small bowl. Season dressing with salt and pepper.'),
('8842', '2', 'Cook green beans in large pot of boiling salted water until crisp-tender, about 6 minutes.'),
('8842', '3', 'Drain. Refresh under cold running water.'),
('8842', '4', 'Drain well.'),
('8842', '5', 'Transfer to large bowl.'),
('8842', '6', 'Add arugula and half of eggs.'),
('8842', '7', 'Drizzle with dressing. toss to coat. Top with remaining eggs.'),
('8843', '1', 'Preheat oven to 42'),
('8843', '2', 'Brush tops of mushrooms with 2 Tbsp. oil. Roast mushrooms, flipping once, until tender and browned, about 20 minutes.Meanwhile, heat remaining 1 Tbsp. oil in a saucepan over medium heat. Cook onion and celery until softened, about 5 minutes.'),
('8843', '3', 'Add garlic and cook, stirring, for 1 minute. Stir in lentils and broth and bring to a boil. Cover, reduce heat, and cook until lentils are just tender but not mushy, 67 minutes.'),
('8843', '4', 'Drain, then spread out on a baking sheet to cool slightly.'),
('8843', '5', 'Transfer lentil mixture to a medium bowl.'),
('8843', '6', 'Add brown rice and toss gently to combine well. Season to taste with salt, pepper, and lemon juice'),
('8843', '7', 'Place 4 mushrooms on plates. Spoon about 1 cup of lentil filling onto each. add toppings of choice.'),
('8843', '8', 'Place remaining 4 mushrooms on top of ''burgers.'''),
('8846', '1', '1 In a large bowl or baking dish combine tomatoes, onion, and vinegar and season with pepper and salt. Marinate 30 minutes.2 Layer mozzarella, tomatoes, onions and arugula on the focaccia half.'),
('8846', '2', 'Spread some mayonnaise on the top half of the focaccia if desired. Press top half over the bottom, hold together with a couple of tooth picks.'),
('8849', '1', 'Sprinkle chicken with salt.'),
('8849', '2', 'Place flour in a shallow bowl. Dredge each half chicken breast on both sides with flour, shaking off excess over bowl.'),
('8849', '3', 'Warm 2 Tbsp. oil in a large skillet over medium-high heat.'),
('8849', '4', 'Add chicken and cook until golden on both sides, about 10 minutes total.'),
('8849', '5', 'Transfer to a plate and cover loosely with foil to keep warm.'),
('8849', '6', 'Heat remaining 1 Tbsp. oil in skillet.'),
('8849', '7', 'Add onion and cook, stirring, until softened, about 5 minutes.'),
('8849', '8', 'Add broth and tomatoes and cook until sauce has thickened, about 3 minutes. Stir in olives and arugula and cook, stirring, until arugula has wilted, about 1 minute. Season with salt.'),
('8849', '9', 'Pour sauce over chicken and serve.'),
('8850', '1', 'Preheat oven to 475F. Warm 1 Tbsp. oil in a skillet over medium-high heat.'),
('8850', '2', 'Add mushrooms, sprinkle with salt and saut until mushrooms release their liquid and are lightly browned, 5 to 7 minutes.'),
('8850', '3', 'Transfer to a small bowl.'),
('8850', '4', 'Press and stretch dough evenly to cover a 15-inch round perforated pizza pan. Scatter mushrooms over dough. sprinkle cheese on top.'),
('8850', '5', 'Bake until underside is golden and cheese is bubbling, about 15 minutes.'),
('8850', '6', 'Toss arugula with remaining 1 Tbsp. olive oil, lemon juice and 1/2 tsp. salt. Arrange greens on top of pizza. Scatter tomatoes over greens. Return pizza to oven to wilt arugula, 2 to 3 minutes. Slice and serve.'),
('8851', '1', 'Preheat oven to 375F.'),
('8851', '2', 'Brush bread with olive oil (use only 2 Tbsp.). sprinkle with salt and 1/4 tsp. pepper.'),
('8851', '3', 'Bake until lightly browned, 12 minutes.'),
('8851', '4', 'Remove from oven and rub each crostini with cut side of garlic clove.'),
('8851', '5', 'Transfer to a platter. set aside.'),
('8851', '6', 'Heat 1 Tbsp. olive oil in a skillet over medium-high heat.'),
('8851', '7', 'Add artichokes and saut until golden, 5 minutes.'),
('8851', '8', 'Add roasted peppers and saut 1 minute more.'),
('8851', '9', 'Remove from heat. place mixture in a bowl.'),
('8851', '10', 'Add cheese and arugula. toss to combine. Season with pepper and spoon mixture onto crostini.'),
('8851', '11', 'Drizzle with remaining 1 Tbsp. oil and serve.'),
('8851', '12', 'Garnish with shaved Parmesan, if desired.'),
('8853', '1', 'Whisk marmalade, lemon juice and olive oil in a smaller bowl until well combined. Season with salt and pepper.In a big salad bowl mix the greens and onions with the oranges and the vinaigrette. Sprinkle with hazelnuts.'),
('8853', '2', 'Serve immediately.'),
('8854', '1', '1/3 cup (3 fl oz/80 ml) olive oil4 cups (4 oz/125 g) arugula1 cup (6 oz/185 g) Pickled Beets, slices halved1/4 lb (125 g) ricotta salata cheese'),
('8857', '1', 'Fill sink with ice water. In a stockpot, combine onion, carrot, bay leaves, garlic, ginger, zest, and peppercorns with 8 cups water. cover and bring to a boil.'),
('8857', '2', 'Add lobsters, cover, and cook 8 minutes once water has returned to a boil.'),
('8857', '3', 'Remove lobsters, reserving the liquid. transfer to the ice bath.'),
('8857', '4', 'When lobsters are cool enough to handle, break tails and claws from body. crack open to remove meat. Set meat aside.'),
('8857', '5', 'Add bodies and empty shells to reserved liquid. return to a boil. Reduce heat. simmer 30 minutes.'),
('8857', '6', 'Drain through a fine sieve. discard solids. Return liquid to pot. cook over medium-high heat until reduced to 1 cup, about 45 minutes.'),
('8857', '7', 'Cut meat from lobster-tail and claw into bite-size pieces. set aside.'),
('8857', '8', 'Bring a 5-quart saucepan of salted water to a boil, and cook pasta until al dente, about 7 minutes.'),
('8857', '9', 'Drain in a colander, and set aside.'),
('8857', '10', 'Cut onion into 1/8-inch wedges. remove the core.'),
('8857', '11', 'Cut zucchini lengthwise into quarters and crosswise into 1/2-inch pieces.'),
('8857', '12', 'Heat a low-sided 6-quart saucepan coated with olive-oil cooking spray over medium-high heat until very hot.'),
('8857', '13', 'Add onion and garlic. reduce heat to medium low. Cook until onions are translucent, about 3 minutes.'),
('8857', '14', 'Add zucchini. cook until tender, about 7 minutes.'),
('8857', '15', 'Add corn, reserved lobster meat, cooked pasta, reserved liquid, arugula, and marjoram. stir to combine. Stir in Parmesan, if desired. serve.'),
('8860', '1', 'Working with 1 slice of prosciutto at a time, cut prosciutto crosswise into 3 rectangles. Space prosciutto pieces 2 inches apart on work surface. Arrange 3 arugula leaves side by side atop each prosciutto piece, allowing tops to extend 1 inch over 1 long side of prosciutto. Top each with about 1 teaspoon cheese. Press generous 1/2 teaspoon currants into cheese atop each prosciutto piece. Starting at 1 short end of each prosciutto piece, roll up tightly, jelly-roll style.'),
('8860', '2', 'Transfer to platter. (Can be made 4 hours ahead. Cover rolls tightly and refrigerate.)'),
('8861', '1', 'In a large bowl, toss arugula, cherry tomatoes, and mint leaves with olive oil, salt, and pepper.'),
('8861', '2', 'Add lemon juice. toss to coat.Divide dough into 4 balls. cover loosely with plastic wrap.'),
('8861', '3', 'Remove one ball at a time from plastic wrap. transfer to large cookie sheet and gently pat and stretch dough to form 1/4-inch-thick free-form shape, as desired. Repeat.Carefully lift shaped dough and lay flat on grill. Cook 2 to 3 minutes or until puffed and dough releases easily from grill. Carefully turn crusts over, topping crusts with the thinly sliced 8-ounce ball fresh mozzarella cheese.'),
('8861', '4', 'Remove from grill. top with arugula salad, then prosciutto.'),
('8862', '1', 'To prepare dough, dissolve yeast and sugar in 1/2 cup warm water in a large bowl. let stand 5 minutes. Lightly spoon flour into dry measuring cups, and level with a knife. Stir 1 1/4 cups flour and 1/4 teaspoon salt into yeast mixture to form a soft dough. Turn dough out onto a lightly floured surface. Knead until smooth and elastic (about 5 minutes). add enough of remaining flour, 1 tablespoon at a time, to prevent dough from sticking to hands.'),
('8862', '2', 'Place dough in a large bowl coated with cooking spray, turning dough to coat. Cover. let rise in a warm place (85), free from drafts, 1 hour or until doubled in size. (Press two fingers into dough. If indentation remains, dough has risen enough.)'),
('8862', '3', 'Punch dough down. cover and let rest 5 minutes.'),
('8862', '4', 'Roll dough into a 14-inch circle on a lightly floured surface.'),
('8862', '5', 'Place dough on a pizza pan or baking sheet coated with cooking spray and sprinkled with cornmeal. Crimp edges of dough with fingers to form a rim.'),
('8862', '6', 'Preheat oven to 45'),
('8862', '7', 'To prepare topping, cook bacon in a large nonstick skillet over medium heat until crisp.'),
('8862', '8', 'Remove bacon from skillet, reserving 2 teaspoons of bacon drippings in pan. Crumble bacon. set aside.'),
('8862', '9', 'Add onion and mushrooms to pan. cook 10 minutes or until tender and moisture evaporates, stirring occasionally.'),
('8862', '10', 'Remove from heat. sprinkle with 1/4 teaspoon salt and 1/8 teaspoon pepper.'),
('8862', '11', 'Drizzle oil over dough. sprinkle with remaining 1/4 teaspoon salt and 1/8 teaspoon pepper.'),
('8862', '12', 'Place pan on lowest oven rack. bake at 450 for 10 minutes or until golden-brown.'),
('8862', '13', 'Remove from oven. spread ricotta evenly over crust, leaving a 1/2-inch rim. Arrange onion mixture and arugula evenly over ricotta. Sprinkle with bacon, mozzarella, and Parmesan.'),
('8862', '14', 'Bake an additional 10 minutes or until crust is lightly browned.'),
('8862', '15', 'Let stand 5 minutes before serving.'),
('8862', '16', 'Cut into wedges.'),
('8864', '1', 'Toss the bread cubes with a little olive oil, salt and pepper.'),
('8864', '2', 'Place on a baking sheet and bake until lightly browned and just crisp on the outside, about 10 minutes.'),
('8864', '3', 'Combine the vinegars, 1/4 tsp. salt, and a pinch of pepper in a large bowl and slowly whisk in the olive oil.'),
('8864', '4', 'Add the bread cubes, peppers, olives, and artichokes and toss to coat with the vinaigrette. Set aside to marinate for 10-15 minutes. Just before serving, toss in the arugula and cheese and adjust the seasoning with salt and pepper. (The salad, without the arugula and cheese, can be made up to 8 hours in advance. Store in the fridge but eat the salad at room temperature).Simple Artichoke Salad'),
('8864', '5', 'Makes about 3 cups'),
('8864', '6', 'If you are going to use frozen artichokes, I would add them, unthawed, to the poaching liquid as described below.2 pounds small artichokes, trimmed2 1/2 cups water1/4 cup olive oil1/4 cup white wine3 tbsp. lemon juice1 tbsp. Champagne vinegar2 garlic cloves, smashed with the flat side of a knife, skin left on3 fresh thyme sprigs1 bay leaf1 tsp. salt'),
('8864', '7', 'Pinch of pepper'),
('8864', '8', 'Combine everything except the artichokes in a wide non-reactive pan and bring to a boil. Drop in the artichokes and cover the surface with parchment paper or an heat-proof inverted plate to keep the artichokes submerged. Bring the liquid back to a boil, lower the heat and simmer until tender, 10-15 minutes depending on their size. To test whether they are done, stick the tip of a knife into the base and the leaves, make sure both are tender.Once done, drain the artichokes and toss them with:1/2 tbsp. olive oil1/2 tsp. minced garlic1/2 tsp. grated lemon zestsalt and pepper to taste'),
('8864', '9', 'One last note: To make sure the artichokes are done, I would taste one. You want to be able to easily bite through (and swallow the leaves). When I made this yesterday, the base was done but not the leaves so I ended up having to cut that part off and just use the base.'),
('8868', '1', 'Toast walnuts in a small dry skillet over medium-low heat, stirring frequently, until lightly browned and aromatic, 3 to 5 minutes.'),
('8868', '2', 'Transfer to a salad bowl. let cool for 5 minutes.'),
('8868', '3', 'Add arugula, strawberries, Parmesan, pepper and salt. Sprinkle vinegar and oil over the salad. toss gently and serve at once.'),
('8870', '1', 'Roast almonds and coarsely crush. Meanwhile, trim the ends off summer squash. Using a vegetable peeler, thinly slice the squash lengthwise into strips and transfer to a large bowl.In a small bowl, whisk together extra-virgin olive oil, fresh lemon juice, minced garlic clove, and kosher salt to taste.'),
('8870', '2', 'Pour dressing over squash.'),
('8870', '3', 'Let stand for a few minutes, then add a few handfuls of baby arugula. Shave a little Pecorino over the squash and toss. Season with kosher salt and freshly ground black pepper.'),
('8870', '4', 'Garnish with the crushed almonds.'),
('8871', '1', 'Prepare grill. Toss shrimp with 1 Tbsp. oil.'),
('8871', '2', 'Transfer to grill and cook, turning, until charred and firm, about 5 minutes.'),
('8871', '3', 'Transfer cooked shrimp to a large salad bowl.'),
('8871', '4', 'Brush bread with remaining oil and then grill, turning it occasionally, until toasted on both sides, about 5 minutes. Rub toast slices with garlic clove.'),
('8871', '5', 'Transfer toast to a board and cut into cubes. add cubes to bowl with shrimp, followed by vinegar, lemon peel and salt. Toss mixture well.'),
('8871', '6', 'Add arugula and tomato, season with pepper, and toss again.'),
('8873', '1', 'Weigh or lightly spoon flour into dry measuring cups and spoons. level with a knife.'),
('8873', '2', 'Combine flour, 3/4 cup warm water, thyme, oregano, and garlic in the bowl of a stand mixer with dough hook attached. mix until combined. Cover and let stand for 20 minutes.'),
('8873', '3', 'Dissolve yeast in the remaining 1/4 cup warm water in a small bowl. let stand 5 minutes or until bubbly.'),
('8873', '4', 'Add yeast mixture and salt to flour mixture. beat at low speed 5 minutes or until a soft dough forms.'),
('8873', '5', 'Place dough in a large bowl coated with cooking spray. cover dough with plastic wrap coated with cooking spray. Refrigerate 24 hours.'),
('8873', '6', 'Remove the dough from refrigerator.'),
('8873', '7', 'Let stand, covered, for 1 hour or until the dough comes to room temperature. Punch dough down. Divide dough into 4 equal portions. Press each portion into a 7-inch circle on a baking sheet sprinkled with cornmeal. Cover loosely with plastic wrap.'),
('8873', '8', 'Preheat grill to medium-high heat.'),
('8873', '9', 'Place pizza dough rounds, cornmeal side up, on grill rack coated with cooking spray, and grill for 3 minutes or until blistered. Turn dough over. grill for 3 minutes.'),
('8873', '10', 'Remove from grill.'),
('8873', '11', 'Sprinkle about 5 tablespoons fontina over each pizza. Top evenly with prosciutto and pepper.'),
('8873', '12', 'Combine oil and lemon juice in a bowl. add arugula, and toss gently. Divide arugula mixture evenly among pizzas.'),
('8873', '13', 'Serve immediately with lemon wedges.'),
('8874', '1', '- Preheat oven to 37'),
('8874', '2', 'Toss beets with oil in roasting pan. Sprinkle with salt. Cover pan with foil. Roast beets until tender, about 50 minutes.'),
('8874', '3', 'Let beets stand at room temperature still covered for 20 minutes. Peel beets.'),
('8874', '4', 'Place in bowl. Cover and chill for at least one hour.- Toss onion, oil, capers, and chives in small bowl. Season to taste with salt and pepper. Thinly slice beets. Arrange in concentric circles on each of 6 plates. Mound arugula atop the center of the beets. Spoon onion-caper mixture over. Season with additional salt and pepper.Comments'),
('8874', '5', 'Your name.Your email.Your URL.Your comment.Cancel.'),
('8876', '1', 'Heat oven to 375F. Wrap beets loosely in foil and roast until tender, 45 minutes to 1 hour.'),
('8876', '2', 'Let cool, then remove skins. (You can rub them off with a paper towel.) Slice beets into thin wedges. Make dressing: Blend grapeseed oil, vinegar, honey, mustard and sesame oil in a blender on high until frothy. season with salt and pepper.'),
('8876', '3', 'Combine beets, arugula, tomatoes and fennel in a bowl. add 2 tablespoon dressing (reserve the rest). toss. Top with goat cheese.'),
('8876', '4', 'Self'),
('8877', '1', 'Finely grate1/2 tsp. zest from the grapefruit. set aside. Slice just enough off the top and bottom of the grapefruit to expose the fruit. Stand the grapefruit on one cut end and slice away all of the peel and white pith. Working over a bowl, cut the segments away from the membranes, letting them fall into the bowl. Then, over another bowl, squeeze the membranes to get any remaining juice.'),
('8877', '2', 'Cut each segment into thirds.    In a small bowl, whisk 2 Tbs. of the reserved grapefruit juice and the zest with the oil, vinegar, rosemary, red pepper flakes,1/4 tsp. salt, and a pinch of pepper.    In a small bowl, mix the grapefruit segments, hearts of palm, and olives with 2 Tbs. of the dressing.    Toss the arugula and parsley in a large bowl with a generous pinch of salt and 3 Tbs. of the dressing. Divide the arugula among 4 plates, top with the hearts of palm mixture, and drizzle with the remaining dressing, if desired.'),
('8878', '1', 'For the blue cheese bchamel sauce:  In a saucepan, melt 8  tablespoons of  butter over medium-low. you don''t want the butter to  burn.'),
('8878', '2', 'Add the red chili flakes (if used). Bring the  heat back up to  medium-high (the butter should be hot and golden) and  add the flour.  Keep stirring manually with a whisk for approximately 3  minutes. The  flour should absorb the butter and form a paste. Stir well  until incorporated and add the milk in  3 stages. Increase the heat  while constantly stirring for about 5  minutes.'),
('8878', '3', 'Add 4 ounces of blue cheese and  reduce the heat to low. Once the cheese is melted and well incorporated, season with salt  and pepper.'),
('8878', '4', 'Let the sauce rest until it''s time to assemble the  dish.Prepping the pears: Peel, core and cut the pears in small wedges.'),
('8879', '1', 'In a large bowl toss tuna with capers, oil, vinegar, arugula, pasta and pepper. Divide on two plates and top with shaved parmesan.'),
('8880', '1', 'Remove your steak from the fridge and let it come to room temperature (about 30 minutes). Meanwhile, slice your red onion and let it soak in a bowl of very cold water. Now rub steak with a generous amount of sea salt.'),
('8880', '2', 'Add pepper if you like. (I prefer without.)'),
('8880', '3', 'Heat a cast-iron skillet over a high flame until the pan is very, very hot. Throw the steak on and cook for 4 minutes. flip and cook for another'),
('8880', '4', 'Remove to a plate and allow to rest for 10-12 minutes before slicing thinly.'),
('8880', '5', 'While your steak is cooking, make your salad dressing.'),
('8880', '6', 'Whisk honey, mustard and vinegar together. Then whisk in olive oil to emulsify. Taste and add salt and pepper as desired.'),
('8880', '7', 'When your steak is resting, drain the onion and pat dry with a paper towel.'),
('8880', '8', 'Combine in a bowl with the arugula, and toss well with the dressing.'),
('8880', '9', 'Serve your sliced steak with a pile of salad mounded on the side, or on top.'),
('8893', '1', 'Preheat oven to 40'),
('8893', '2', 'Heat 2 Tbsp. butter in a small saucepan over high heat. When butter begins to foam, add shallots and thyme. season with salt and pepper. Cook, stirring continuously with a wooden spoon or spatula, until shallots begin to soften and caramelize, 45 minutes. remove from heat and set aside.'),
('8893', '3', 'Heat a large heavy-bottomed skillet over medium heat. Working in 2 batches, add  1 Tbsp. butter and swirl in pan to melt butter and coat bottom of pan.'),
('8893', '4', 'Add 2 slices of bread to pan and cook until golden brown and crisp on the bottom, 23 minutes.'),
('8893', '5', 'Transfer bread, toasted side down,  to a rimmed baking sheet. Repeat with remaining butter and bread slices. Divide cheese evenly among bread slices. top cheese with reserved shallots.'),
('8893', '6', 'Place baking sheet in oven and bake  until cheese is melted, 78 minutes.'),
('8893', '7', 'Combine arugula, apple slices, lemon juice, and oil in a large bowl. toss to coat and evenly distribute. Season salad to  taste with salt and pepper.Press 2 pieces of bread together, melted cheese sides in. halve sandwich on a diagonal and place on a plate. Repeat with remaining bread slices. Divide salad between plates.'),
('8894', '1', 'Prepare grill for cooking. If using a charcoal grill, open vents on bottom of grill.'),
('8894', '2', 'Rinse squid under cold running water and pat dry with paper towels. If squid are large, halve tentacles lengthwise and cut longer ones, if attached, crosswise into 2-inch pieces. Pull off flaps from squid bodies, if attached, and reserve.'),
('8894', '3', 'Cut each squid body lengthwise along "seam" and open flat. Score large squid, including flaps, lengthwise with a sharp knife, making cuts close together (about 1/8 inch apart like ridges on rigatoni) and being careful not to cut through squid, then halve squid bodies crosswise.'),
('8894', '4', 'Squeeze enough juice from 2 lemons to measure 1/4 cup.'),
('8894', '5', 'Cut remaining whole lemon into wedges.'),
('8894', '6', 'Whisk together lemon juice, oil, garlic, 1/2 teaspoon salt, and 1/8 teaspoon pepper until combined well and transfer 1/4 cup dressing to a large shallow bowl, reserving remainder.'),
('8894', '7', 'Add squid to dressing in shallow bowl, tossing to coat, and marinate at room temperature, turning once, 10 minutes.'),
('8894', '8', 'Thread 2 skewers through each squid body, near opposite sides of body (to keep squid flat during grilling). Thread all the flaps onto 1 or 2 skewers. Thread all tentacles crosswise (through thickest part) onto skewers, without crowding, letting tentacles dangle. Discard marinade.'),
('8894', '9', 'When fire is hot (you can hold your hand 5 inches above rack for 1 to 2 seconds), grill squid on a lightly oiled grill rack, uncovered, turning once, until they just turn opaque, 1 to 1 1/2 minutes total.'),
('8894', '10', 'Transfer to a cutting board and remove skewers.'),
('8894', '11', 'Cut squid bodies lengthwise into 1 1/2-inch-thick strips. Halve strips crosswise if using larger squid.'),
('8894', '12', 'Toss squid with 3 tablespoons reserved dressing and salt and pepper to taste in a clean bowl. Toss arugula in another bowl with just enough of remaining dressing to coat, then season with salt and pepper. Divide arugula among 4 plates and top with squid.'),
('8894', '13', 'Serve with lemon wedges.'),
('8895', '1', 'Toss arugula and fennel in a salad bowl.'),
('8895', '2', 'Whisk oil, juice, vinegar, shallot, zest, salt and pepper in another bowl.'),
('8895', '3', 'Pour over fennel and arugula. toss to coat.'),
('8897', '1', 'Bring mushrooms and water to a boil in a small saucepan over high heat. Cover the pan and remove from the heat. let stand until the mushrooms are softened, about 10 minutes. Line a fine-mesh sieve with a wet paper towel and place over a large measuring cup or medium bowl.'),
('8897', '2', 'Pour the mushrooms and liquid into the sieve. Reserve the liquid.'),
('8897', '3', 'Transfer the mushrooms to a cutting board and let cool slightly, then coarsely chop.'),
('8897', '4', 'Add enough water to the strained liquid to equal 4 1/2 cups. set aside the mushrooms and liquid for Step 4.Cover edamame with water in a small saucepan and bring to a boil over high heat. Reduce heat to medium and simmer for 2 minutes. set aside in the cooking water.Meanwhile, place rice and shallot in a shallow 3-quart baking dish that will fit and rotate properly in your microwave. Stir in oil until the rice is evenly coated.'),
('8897', '5', 'Spread the rice evenly in the dish and microwave, uncovered, on High until it looks opaque and is just beginning to color in one or two spots, 3 minutes.'),
('8897', '6', 'Add lemon zest and juice, salt, pepper, the reserved chopped mushrooms and the mushroom water. stir together well. Microwave on High for 9 minutes. Stir well, then microwave until the rice is tender but still firm in the center and most of the liquid has been absorbed, 9 minutes more. Depending on the power of your microwave, this last cooking time will vary. After 9 minutes, cook in 3-minute intervals, stopping to stir and test rice for doneness.'),
('8897', '7', 'Drain the edamame and add to the risotto along with arugula and Parmesan. stir until the arugula is wilted.'),
('8897', '8', 'Serve immediately.'),
('8898', '1', 'Butter pan. Dust pan all over with 1/3 cup Parmesan. Melt 1/4 cup butter in a large saucepan over medium heat.'),
('8898', '2', 'Add flour. whisk for 2 minutes. Gradually whisk in milk. Bring to a simmer, whisking often. Reduce heat to medium. Cook, whisking frequently, until sauce is thickened, about 20 minutes.'),
('8898', '3', 'Remove from heat.'),
('8898', '4', 'Whisk in Fontina and 1 cup Parmesan.'),
('8898', '5', 'Add egg. whisk to blend. Season with salt and pepper. Cover sauce and keep warm.Arrange a rack in upper third of oven. preheat to 37'),
('8898', '6', 'Cook pasta in a large pot of boiling salted water, stirring occasionally, until almost al dente (pasta will continue to cook while baking). Using a large slotted spoon, transfer pasta to a large bowl.'),
('8898', '7', 'Add peas to pasta water. cook until just tender, about 1 minute.'),
('8898', '8', 'Drain peas. add to bowl with pasta. Stir in cheese sauce.'),
('8898', '9', 'Add arugula, 1 cup parsley, and 1/2 cup mint to pasta mixture. mix to evenly incorporate.'),
('8898', '10', 'Transfer half of pasta mixture to prepared pan.'),
('8898', '11', 'Mix ricotta and lemon zest in a small bowl. dot half of ricotta mixture over pasta. Spoon remaining pasta mixture into pan and dot with remaining ricotta mixture. Sprinkle with 1/4 cup Parmesan.'),
('8898', '12', 'Bake pasta for 30 minutes. Sprinkle with remaining 1/4 cup Parmesan.'),
('8898', '13', 'Bake pasta until top is golden brown, about 10 minutes longer.'),
('8898', '14', 'Let rest for 30 minutes. remove  pan sides. Sprinkle with 2 Tbsp. parsley and 2 Tbsp. mint and cut into wedges.'),
('8900', '1', 'Preheat oven to 450F. Toss squash, olive oil, and crushed red pepper on large rimmed baking sheet. Sprinkle with coarse salt. Roast 15 minutes. Using spatula, turn squash over. Roast until edges are browned and squash is tender, about 15 minutes longer. Sprinkle with coarse salt. DO AHEAD Can be made 2 hours ahead.'),
('8900', '2', 'Let stand at room temperature.'),
('8900', '3', 'Whisk orange juice, walnut oil, and lemon juice in large shallow bowl. Season to taste with salt and pepper.'),
('8900', '4', 'Add arugula, walnuts, and pomegranate seeds. toss to coat. Season to taste with coarse salt and pepper. Spoon warm or room-temperature squash over salad.'),
('8900', '5', 'Drizzle with pomegranate molasses and serve.'),
('8903', '1', 'Place potato pieces in a medium saucepan. cover with cold water to 2 inches above potatoes. Bring to a boil over medium-high heat. Reduce heat to medium, and gently simmer 10 minutes or until potatoes are tender.'),
('8903', '2', 'Drain potatoes.'),
('8903', '3', 'Heat a small skillet over medium-high heat.'),
('8903', '4', 'Add 1 teaspoon oil to pan. swirl to coat.'),
('8903', '5', 'Add shallots to pan. saut 3 minutes or until lightly browned, stirring occasionally.'),
('8903', '6', 'Remove from heat.'),
('8903', '7', 'Combine shallots, vinegar, mustard, lemon rind, lemon juice, salt, and black pepper in a small bowl, stirring well with a whisk. Gradually add remaining 2 tablespoons oil, stirring constantly with a whisk until combined.'),
('8903', '8', 'Drizzle dressing over warm potatoes. toss gently to coat. Cool completely.'),
('8903', '9', 'Add arugula to potato mixture. toss gently.'),
('8903', '10', 'Serve immediately.'),
('8906', '1', 'Preheat grill to medium-high.'),
('8906', '2', 'Whisk together 4 Tbsp. oil, vinegar, shallot, mustard and 1/2 tsp. salt.'),
('8906', '3', 'Brush peaches with 1 tsp. oil. Grill, flat side down, until warmed through, about 4 minutes.'),
('8906', '4', 'Remove from grill.'),
('8906', '5', 'Brush chicken on both sides with remaining 2 tsp. oil and sprinkle with salt. Grill until cooked through, turning once, about 8 minutes total.'),
('8906', '6', 'Cut chicken into thin diagonal slices.'),
('8906', '7', 'Cut peaches into 1/2-inch-thick slices.'),
('8906', '8', 'In a large bowl, toss greens with dressing. Divide greens among serving plates, top with peach halves and sliced chicken, and serve.'),
('8907', '1', 'Combine first 4 ingredients in a bowl, stirring well.'),
('8907', '2', 'Preheat oven to 40'),
('8907', '3', 'Arrange pancetta in a single layer on a baking sheet coated with cooking spray.'),
('8907', '4', 'Bake at 400 for 8 minutes or until crisp.'),
('8907', '5', 'Drain on paper towels.'),
('8907', '6', 'Spread mayonnaise mixture evenly over bread slices. Top each of 4 bread slices with 2 pancetta slices, 4 tomato slices, and 1/4 cup arugula. Top sandwiches with remaining 4 bread slices.'),
('8908', '1', 'Prepare grill to medium-high heat.'),
('8908', '2', 'Place asparagus on a jelly-roll pan. Coat asparagus with cooking spray, and sprinkle with salt. toss gently to coat.'),
('8908', '3', 'Place asparagus on grill rack. grill 3 minutes or until crisp-tender, turning occasionally.'),
('8908', '4', 'Remove asparagus from grill. cut into 2-inch pieces.'),
('8908', '5', 'Combine rind, juice, oil, and pepper in a large bowl, stirring with a whisk.'),
('8908', '6', 'Add asparagus and arugula. toss gently. Divide asparagus mixture evenly among 4 salad plates. Top each serving with 1 tablespoon cheese.'),
('8932', '1', 'Heat a large saut pan or cast iron pan on medium low heat. Lay the strips of bacon in a single layer on the pan. Slowly cook the bacon, rendering out the fat, until lightly browned on one side. Using a fork or tongs, turn the strips of bacon over to cook the other side.When the bacon strips are sufficiently cooked remove from pan and place on a plate lined with a paper towel to absorb the excess fat.'),
('8932', '2', 'Pour out excess fat from the pan (leaving about half a teaspoon in the pan) into a jar or a container to either dispose of or to store. (Never pour bacon grease down the sink, it will clog your pipes.)2 Wilt the arugula:In the same pan, add handfuls of fresh baby arugula or watercress. Toss in the remaining remaining fat. As soon as the greens start to wilt, remove from heat and remove from the pan to stop the cooking.3 Toast bread, build sandwich:Toast bread slices in a toaster.'),
('8932', '3', 'Spread mayonnaise (or your favorite spread, butter will do too) over the slices. Layer the sandwich with bacon, sliced tomato, and lightly wilted arugula.'),
('8932', '4', 'Cut on the diagonal.Eat immediately.'),
('8934', '1', 'Place first 4 ingredients in medium bowl. stir in mayonnaise to taste. Season with salt and pepper. Halve each bread square horizontally. Top 4 pieces with arugula, then salmon. cover with remaining bread.'),
('8939', '1', 'To poach chicken breast: Cover chicken breast in broth in a small pot, add water if it doesnt cover the chicken.'),
('8939', '2', 'Add salt and pepper, a piece of celery and its leaves (you could add herbs like parsley, garlic, onion, or whatever you want) and bring to a boil. Reduce to a simmer and cook 5 minutes.'),
('8939', '3', 'Remove from heat, cover tight and let it sit for 15-20 minutes or until thickest part of the breast registers 160 degrees. Chicken will be cooked through.'),
('8939', '4', 'Let it cool and cut into small cubes.'),
('8939', '5', 'Combine mayo, yogurt, salt, pepper and mix well.'),
('8939', '6', 'Add chicken, grapes, apples, celery, and let it chill in the refrigerator until you are ready to eat it.'),
('8939', '7', 'Mix in pecans right before serving.'),
('8939', '8', 'Serve over baby greens.'),
('8940', '1', 'Heat the tortillas on the griddle or in whatever way you like to heat tortillas.'),
('8940', '2', 'In a saute pan over medium heat, combine the rice,soup, tomatoes, and jalapeno peppers.'),
('8940', '3', 'Mush it all up together.'),
('8940', '4', 'Meanwhile, cook the eggs sunny-side up.'),
('8940', '5', 'To serve, put 1 handful of arugula in the bottom of two plates.'),
('8940', '6', 'Put the tortillas side by side on top of the arugula, and the rice-beans mixture on top of the tortillas, dividing it evenly.'),
('8940', '7', 'Carefully slide the sunnies on top of that, and serve.'),
('8940', '8', 'Taste'),
('8940', '9', 'Book, using the USDA Nutrition Database'),
('8940', '10', 'From Eat Me by Kenny Shopshin Copyright (c) 2008 by Kenny Shopshin Published by Knopf. Kenny Shopsin is a self-taught chef who has developed his own inimitable style: He colors outside of the lines and then uses the crayons in his pancakes. He lives in Greenwich Village.Carolynn Carreno is a James Beard Awardwinning journalist and the coauthor of 100 Ways to Be Pasta, Once Upon a Tart, and A Twist of the Wrist. She lives in Los Angeles and New York.'),
('8941', '1', 'Preheat oven to 350F.'),
('8941', '2', 'Roast nuts in a shallow baking pan in middle of oven until golden, 10 to 15 minutes. Rub warm nuts in a kitchen towel to remove skins (don''t worry if some skins don''t come off). Cool nuts, then coarsely chop.'),
('8941', '3', 'Whisk together vinegar, lemon juice, shallot, sugar, and salt and pepper to taste.'),
('8941', '4', 'Add oils in a slow stream, whisking until combined well.'),
('8941', '5', 'Toss together arugula, strawberries, hazelnuts, and dressing. Divide salad among plates and dot with goat cheese.'),
('8943', '1', 'Mix grated cheese and butter in small bowl.Season generously with salt and pepper.set aside. Sprinkle steak generously withsalt and pepper.'),
('8943', '2', 'Heat oil in medium skilletover medium-high heat.'),
('8943', '3', 'Add steak. cook todesired doneness, about 4 minutes per sidefor medium-rare.'),
('8943', '4', 'Transfer to plate.'),
('8943', '5', 'Addvinegar, shallots, and sugar to skillet. boil untilreduced to glaze, stirring constantly, about 1minute. Divide arugula and Parmesan shavingsbetween 2 plates. Squeeze lemon over. Slicesteak. place atop arugula. Top steak with'),
('8943', '6', 'Parmesan butter.'),
('8943', '7', 'Drizzle lightly with glaze.'),
('8943', '8', 'Per serving: 505.27 Calories (kcal),'),
('8943', '9', '1 % Calories from Fat,  33.74 Fat (g),14.77 Saturated Fat (g),    181.86 Cholesterol (mg),'),
('8943', '10', '27 Carbohydrates (g),'),
('8943', '11', '88 Dietary Fiber (g),'),
('8943', '12', '65 Total Sugars (g),'),
('8943', '13', '39 Net Carbs (g),37.62 Protein (g)'),
('8943', '14', 'Bon Appetit'),
('8944', '1', 'Heat oil in heavy large pot over medium heat.'),
('8944', '2', 'Add onion. saute until translucent, about 4 minutes.'),
('8944', '3', 'Add garlic. stir 1 minute.'),
('8944', '4', 'Add sausage. cook until browned, breaking up with back of spoon, about 5 minutes.'),
('8944', '5', 'Drain drippings from pot.'),
('8944', '6', 'Add wine, diced tomatoes with juice, and crushed tomatoes. increase heat and bring to boil. Reduce heat to low and simmer 30 minutes to blend flavors, stirring occasionally. DO AHEAD: Can be made 1 day ahead. Cool slightly. Refrigerate uncovered until cool, then cover and keep chilled. Rewarm over medium heat before continuing.'),
('8944', '7', 'Meanwhile, cook pasta in large pot of boiling salted water until tender but still firm to bite, stirring occasionally.'),
('8944', '8', 'Drain.'),
('8944', '9', 'Stir pasta, arugula, basil, and oregano into tomato sauce. Simmer until arugula wilts, stirring often, about 2 minutes. Season with salt and pepper.'),
('8944', '10', 'Transfer to large bowl. Sprinkle with Parmesan.'),
('8945', '1', 'Cook bacon in heavy large skillet over medium-high heat until brown and crisp. transfer to paper towels to drain.'),
('8945', '2', 'Wipe out skillet.'),
('8945', '3', 'Brush cut sides of bread with 1 tablespoon oil.'),
('8945', '4', 'Place bread, cut sides down, in skillet. Cook over medium heat until golden, about 3 minutes.'),
('8945', '5', 'Place 1 bread square, golden side up, on each of 2 plates. Top each with half of bacon, then 2 tomato slices.'),
('8945', '6', 'Whisk 1 tablespoon oil, shallot, and vinegar in medium bowl to blend. Season dressing with salt and pepper.'),
('8945', '7', 'Add arugula and toss to coat.'),
('8945', '8', 'Heat remaining 1 tablespoon oil in same skillet over medium heat. Crack eggs into skillet. Sprinkle with salt and pepper. Cook until whites are set and yolks are cooked as desired. Top each bread stack with egg, then arugula and cheese.'),
('8947', '1', 'Mix red peppers, olives, thyme, and vinegar in small bowl for relish. (Can be made 1 day ahead. Cover and refrigerate.) Reserve 2 tablespoons goat cheese for garnish.'),
('8947', '2', 'Spread remaining goat cheese on toasted baguette slices. Divide arugula among toasts. Fold roast beef slices to fit toasts. place atop arugula. Sprinkle beef slices lightly with salt and pepper. Top each with 1/3 teaspoon reserved goat cheese and small dollop of relish. Arrange crostini on platter and serve.'),
('8948', '1', 'Place onions in large resealable plastic bag.'),
('8948', '2', 'Add vinegar, 1 1/2 cups water, sugar and salt. Seal bag. shake until sugar dissolves. Chill onions in marinade at least 1 day and up to 3 days, turning often.'),
